update battle-stat,statLevelChangDescription for translate to edit
pagefaultgames/pokerogue pull request #1033
Opened 2024-05-17 14:57 UTC by Rei1mu

update battle-stat for zh-CN. en. 
battle-stat,and battleStatLevelChangeDescription can be edit for translate at 'src/locales/xx/battle-stat.ts'

2024-05-17 15:02 UTC, bennybroseph approved these changes

2024-05-17 15:02 UTC, bennybroseph commented on src/phases.ts
> +        messages.push(getPokemonMessage(this.getPokemon(), i18next.t('battleStat:levelChangeDescripion', { statsFragment: i18next.t(`battleStat:${statsFragment.replace(/\./g, '').replace(/[ ]/g, '_')
what do the `.replace()` calls do here?

2024-05-17 15:03 UTC, bennybroseph requested changes
what do the .replace() calls do here?

2024-05-17 15:06 UTC, bennybroseph requested changes

2024-05-17 15:06 UTC, bennybroseph commented on src/phases.ts
> +        messages.push(getPokemonMessage(this.getPokemon(), i18next.t('battleStat:levelChangeDescripion', { statsFragment: i18next.t(`battleStat:${statsFragment.replace(/\./g, '').replace(/[ ]/g, '_')
ones like this for reference

2024-05-17 15:51 UTC, Adri1 commented
Isn't the "!" fragment missing or I misslooked?

2024-05-17 17:07 UTC, Rei1mu commented
> Isn't the "!" fragment missing or I misslooked?
> 
> EDIT : It is possible to give to gendered languages the possibility to choose a determiner? Because in French for example before the stat name, you have to put a mandatory determiner like "the" but is either masculine/feminine/genderless Example :
> 
> * "[the (feminine)] Defense"
> * "[the (genderless, without any space between the derterminer and the word)] Attack"
> * "[the (masculine)] critical-hit ratio"

"!" maybe i  missed , but it can edit on 
 ```
"levelChangeDescripion": "'s {{statsFragment}} {{description}}", 
 "levelChangeDescripion": "'s {{statsFragment}} {{description}}!",
```
about [the] 's problem, this is just part of that . 
i think it means will change the 'the'  at getPokemonMessage() ?

```
export function getPokemonMessage(pokemon: Pokemon, content: string): string {
  return `${getPokemonPrefix(pokemon)}${pokemon.name}${content}`;
}
export function getPokemonMessage(pokemon: Pokemon, content: string): string {
  return `The ${getPokemonPrefix(pokemon)}${pokemon.name}${content}`;
}
```
like this ?  sorry i'm not good at languages

2024-05-18 03:15 UTC, Rei1mu commented
> what do the .replace() calls do here?

It's update. please check

2024-06-06 13:28 UTC, bennybroseph commented
Please address the above concerns

2024-06-23 22:16 UTC, Tempo-anon commented
Closing this PR as it's a bit out of date. If this is still required please submit a new PR

2024-06-23 22:16 UTC, closed without merging