[Implementation] (Speed | Power | Guard) Swap moves
pagefaultgames/pokerogue pull request #1035
Opened 2024-05-17 15:32 UTC by SoulsHawk

- Reworked the SwapStatsAttr used in the Heart Swap moves to implement Power and Guard Swap
- Added a SpeedSwapAttr for Speed Swap

2024-05-17 16:19 UTC, styrix560 requested changes
General logic looks good, only small things

2024-05-17 16:19 UTC, styrix560 commented on src/data/move.ts
> +      let userStat = userBattleStat[stat];
Is there a reason why this is not const?

2024-05-17 16:19 UTC, styrix560 commented on src/data/move.ts
> +      target.scene.queueMessage(getPokemonMessage(user, ' switched all changes to its ' + statsName.join(' and ')  + ' with its target!'));
Here, I would say 'switched its [stats which got changed here] with the target'. Also I would not join them by ' and ' but instead by ', ' and only the last one by ' and '.

So something like: 'switched its Attack, Defense and Speed with the target'

2024-05-17 16:19 UTC, styrix560 commented on src/data/move.ts
> +      const statsName = this.statsToSwap.map(stat => getBattleStatName(stat));
This variable should probably be in plural

2024-05-17 16:19 UTC, styrix560 commented on src/data/move.ts
> +export class SpeedSwapAttr extends MoveEffectAttr
Why is the swapping of Speed extra?

2024-05-17 16:19 UTC, styrix560 commented on src/data/move.ts
> +   * Swaps the user and the target's stat changes.
In this case the stat changes of only the speed

2024-05-17 16:23 UTC, SoulsHawk commented on src/data/move.ts
> +      let userStat = userBattleStat[stat];
Because my brain thought that the value will change so let but yeah, in a loop so doesn't matter

2024-05-17 16:24 UTC, SoulsHawk commented on src/data/move.ts
> +export class SpeedSwapAttr extends MoveEffectAttr
Other swap battle stats, here it changes the pokemon stat

2024-05-17 16:25 UTC, SoulsHawk commented on src/data/move.ts
> +      target.scene.queueMessage(getPokemonMessage(user, ' switched all changes to its ' + statsName.join(' and ')  + ' with its target!'));
There is no move that switch more than 2 battle stats but why not

2024-05-17 16:26 UTC, SoulsHawk commented on src/data/move.ts
> +export class SpeedSwapAttr extends MoveEffectAttr
I should remain the first one like "SwapBattleStatsAttr" but did not because it was "legacy"

2024-05-17 16:28 UTC, styrix560 commented on src/data/move.ts
> +export class SpeedSwapAttr extends MoveEffectAttr
What is the difference between battle stat and pokemon stat?

Either way if there is a good reason for it, it should probably be written in the docs comment.

2024-05-17 16:30 UTC, SoulsHawk commented on src/data/move.ts
> +      target.scene.queueMessage(getPokemonMessage(user, ' switched all changes to its ' + statsName.join(' and ')  + ' with its target!'));
And the "...all changes..." is something that I saw in an official game

2024-05-17 16:36 UTC, SoulsHawk commented on src/data/move.ts
> +export class SpeedSwapAttr extends MoveEffectAttr
Battle stats are your "boost" that you can see when pressing 'c'
Pokemon stats are in your pokemon summary
We talking about my attrs docs right ?

2024-05-17 18:13 UTC, XGSleepWalker commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any []): boolean
This implementation is going to cause some unforeseen problems that we currently don't have a nice way to tackle. 
For example, this would change Escape in an unintended way: https://bulbapedia.bulbagarden.net/wiki/Escape

My advice is to only include Power and Guard Swap on this PR and leave Speed Swap out for when there's a better plan on how to tackle this.

2024-05-18 14:04 UTC, styrix560 reviewed
code lgtm
I think the commit name should be more descriptive.

Also, I am not sure, whether the speed changes really cause undefined behaviour. However, if we are not sure we can just as well open another issue and leave this one as is.

2024-05-18 22:43 UTC, XGSleepWalker commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any []): boolean
There's three types of stats if you will. 

- Your raw base stats
- Your raw variable stats (affected by things like Speed Swap or Power Split)
- Your boosted stats (for things like Agility and Dragon Dance)

That code was changing the raw base stats, when it should be changing the raw variable stats (that should live under summonData). Unfortunately the implementation around summonData.stats isn't correct at the moment, so we'll have to work on that before working on this.

2024-07-29 17:57 UTC, flx-sta commented
No action within more than a month. 
Considered stale.

Feel free to re-open it when you are still working on it/want to work on it again

2024-07-29 17:57 UTC, closed without merging