Random Pokemon Starter Teams
pagefaultgames/pokerogue pull request #1036
Opened 2024-05-17 16:39 UTC by 121mwang

- Ability to generate random pokemon starter meeting point criteria
- Randomize button located in starter-select-ui bottom left hand side of screen

2024-05-17 16:42 UTC, bennybroseph commented
also, all translation additions need a matching key in all currently supported languages. can just be in English to start and someone else will translate it.

2024-05-17 16:51 UTC, 121mwang commented
Video file was too big to share on GitHub. I've attached a Youtube link that is still currently processing
[https://youtu.be/DFP3bIbqNxs](https://youtu.be/DFP3bIbqNxs)
Is there anywhere in overrides.ts or similar to unlock all Starter Pokemon?

2024-05-18 02:35 UTC, bennybroseph requested changes

2024-05-18 02:35 UTC, bennybroseph commented on src/ui/starter-select-ui-handler.ts
> +  }
using a while loop and checking for dupes is a little rough. An alternative is sometimes to fill an array with valid entries and remove entries each time you iterate over the list until there are no valid entries left. 

i.e. for classic:
- Randomly get Caterpie, remove it
  - Currently at 1 point, remove all 10 costs
- Randomly get Squirtle, remove it
  - Currently at 4 points, remove all 7 costs
- Randomly get  Dreepy, remove it
  - Currently at 8 points, remove all 3 costs
- Randomly get your reduced cost Bidoof, remove it
  - Currently at 9 points, remove all 2 costs
- Randomly get Hoothoot, done
  - Currently at 10 points 

Does this sound like something you'd be able to implement?

2024-05-18 02:49 UTC, 121mwang commented on src/ui/starter-select-ui-handler.ts
> +  }
Yes! Timeline will look like a couple days as I will not have time this weekend.
Is there a quick way to access an array of starter Pokemon that a user has access to rather than taking the global list and looking at the dex attributes?

2024-05-18 16:14 UTC, 121mwang commented
Just made an initial commit with the basic algorithm. I haven't fully tested it and the randomness is uniform by point value rather than every Pokemon having an equal chance.
Let me know if any changes need to be made with what is currently there! 
The rest will be implemented by Monday

2024-05-19 15:11 UTC, 121mwang commented
Bias for Pokemon has been added. 
We weren't sure what to do with the blue "selected" starter boxes that normally appear when manually selecting starters, so they were simply moved off-screen for the time being. There were issues when trying to simply overlay them over the starters as usual, probably from not fully understanding how the cursors are implemented. 
I gave it a quick run through and everything seems else to be in order.

2024-05-19 17:53 UTC, bennybroseph commented
Could we get an updated video of the behaviour for the sake of completeness?

2024-05-19 17:53 UTC, bennybroseph approved these changes

2024-05-19 18:04 UTC, 121mwang commented
[https://youtu.be/nR9Fn9H7bGM](https://youtu.be/nR9Fn9H7bGM)
I've attached a Youtube link again. The first section demonstrates it working with the Pokemon that the player currently can use as starters, and the second half of the video demonstrates it with all the starters effectively unlocked. 
I was not able to record sound but every time the Pokemon visible in the party changes is me pressing the button, just cycling it a few times to show the various combinations.

2024-05-22 20:07 UTC, 121mwang commented
Is there anything else that needs to be done on our end?

2024-05-25 12:35 UTC, bennybroseph commented
Needs to be checked again. This is what i get when I test with my account

https://github.com/pagefaultgames/pokerogue/assets/13838608/ca46cbfb-6fd1-45b8-9b0d-56e4a869f523

2024-05-25 18:19 UTC, 121mwang commented
If I understand correctly, the issues are the fact that the button overlaps with the cycle text and the top right sprite in the PC area is getting cycled?

2024-05-25 19:08 UTC, bennybroseph commented
> If I understand correctly, the issues are the fact that the button overlaps with the cycle text and the top right sprite in the PC area is getting cycled?

Correct

2024-05-25 19:20 UTC, hassanoza22 commented
This was already done in another PR if it helps with the movesets/natures/abililities randomization, also the code for randomization is a lot more efficient here:

https://github.com/pagefaultgames/pokerogue/pull/833

2024-06-03 16:54 UTC, bennybroseph commented
Is this still being worked on?

2024-07-11 17:55 UTC, Tempo-anon commented
Closing due to inactivity and merge conflicts. Quite a shame since random pokemon teams is a common user request. If anyone else is interested in mirroring this PR they can submit a new PR

2024-07-11 17:55 UTC, closed without merging