Implement Priority ignoring abilities, Quick feet, paralysis bug fix
pagefaultgames/pokerogue pull request #104
Opened 2024-04-12 20:02 UTC by LaukkaE

Implemented the three moves, that cause priority increased moves targeting the pokemon or ally to fail. (Queenly Majesty, Dazzling, Armor Tail). I left the trigger message out due to the ability flashing visibly.

Also implemented quick feet and fixed paralysis dropping speed to 1/4 when it should be 1/2.
Added attack boost to Thermal exchange.

Defendplayfield can be used in future to apply more abilities that affect both pokemon in defenders side.

2024-04-12 20:04 UTC, Flashfyre requested changes

2024-04-12 20:04 UTC, Flashfyre commented on src/data/ability.ts
> +    const pranksterStatus = attacker.getAbility().id === Abilities.PRANKSTER && move.getMove().category === MoveCategory.STATUS;
This will not support passive abilities. Direct ability checks are discouraged unless you also want to check it against the passive, which needs the canApplyPassive check

2024-04-12 20:13 UTC, LaukkaE commented on src/data/ability.ts
> +    const pranksterStatus = attacker.getAbility().id === Abilities.PRANKSTER && move.getMove().category === MoveCategory.STATUS;
You cannot get modified priority out of move i dont think, so you need the extra step. If you want to, that can be commented out for now and the ability does like 98% of what it should.

The passives are a brand new thing, i will look into including that.

2024-04-12 22:22 UTC, LaukkaE commented
Do not merge currently.

2024-04-14 15:53 UTC, Flashfyre requested changes

2024-04-14 15:53 UTC, Flashfyre commented on src/field/pokemon.ts
> +        if (this.status && this.status.effect === StatusEffect.PARALYSIS && this.getAbility().id !== Abilities.QUICK_FEET)
Please add support for passives

2024-04-14 15:53 UTC, Flashfyre commented on src/field/pokemon.ts
> +    const defendPlayField = this.isPlayer() ? this.scene.getPlayerField() : this.scene.getEnemyField() || [];
This needs a better name, I can't tell what this means

2024-04-14 15:55 UTC, LaukkaE commented on src/field/pokemon.ts
> +        if (this.status && this.status.effect === StatusEffect.PARALYSIS && this.getAbility().id !== Abilities.QUICK_FEET)
I think ill take the quick feet out of this pr, there are two other quick feet pr's open also

2024-04-15 11:18 UTC, closed without merging