So currently if you meet someone with a title it only shows there nam…
pagefaultgames/pokerogue pull request #1055
Opened 2024-05-17 20:20 UTC by CodeTappert

…e and only then the title (not like trainer classes). So i wanted to change that

Trainerclasses already do it this way. 

Currently (main):
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/88e85202-be1a-4ade-8ed3-9bac4c958085)

With this PR:
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/9f5a361c-bcbe-4c99-8532-89da7f729001)

2024-05-18 02:09 UTC, bennybroseph requested changes

2024-05-18 02:09 UTC, bennybroseph commented on src/data/trainer-config.ts
> +        this.title = "";
I'd also like it to display like this, but what does title do? I'm not sure that I like it being set to a blank string.

2024-05-18 07:44 UTC, CodeTappert commented on src/data/trainer-config.ts
> +        this.title = "";
As far as my IDE tells me. 

![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/48b30b43-025c-41e2-873f-c0def71ca50c)

![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/e2008cf4-c0ab-47b9-b910-e3a825f5deb7)


So it is really only used for this? 

Which doesnt make sense. It needs to be read somewhere

And this is basically done here:

```
getName(trainerSlot: TrainerSlot = TrainerSlot.NONE, includeTitle: boolean = false): string {
    let name = this.config.getTitle(trainerSlot, this.variant);
    let title = includeTitle && this.config.title ? this.config.title : null;


    if (this.name) {
      if (includeTitle)

      // Check if i18n is initialized
        if (!getIsInitialized()) {
          initI18n()
        }
        title = i18next.t(`trainerClasses:${name.toLowerCase().replace(/\s/g, '_')}`);
      if (!trainerSlot) {
        name = this.name;
        if (this.partnerName)
          name = `${name} & ${this.partnerName}`;
      } else
        name = trainerSlot === TrainerSlot.TRAINER ? this.name : this.partnerName || this.name;
    }

    return title ? `${title} ${name}` : name;
  }
```

At least this is what i traced back from the UI that implements the name tag. 

And it seems to be the only place. 

So in my understanding it is totaly fine to leave the title as an empty string. (if it would be set also it would show the title twice)

2024-05-18 09:49 UTC, bennybroseph commented on src/data/trainer-config.ts
> +        this.title = "";
shouldn't we populate it with the translation then?

2024-05-18 10:56 UTC, CodeTappert commented on src/data/trainer-config.ts
> +        this.title = "";
No. What you propose is how it currently works on main. It then does not show the title in the name tag (as you see in the pictures). 

Maybe we could change it so the name tag also shows the title value and not just the name value if that would be better for you

2024-05-18 16:13 UTC, bennybroseph commented on src/data/trainer-config.ts
> +        this.title = "";
I think that makes the most sense logically, rather than setting a value to nothing and then adding what it should do to another value

2024-05-18 16:16 UTC, CodeTappert commented on src/data/trainer-config.ts
> +        this.title = "";
Okay i will try to find a way

2024-05-18 16:29 UTC, CodeTappert commented
@bennybroseph The Solution was way easier then i thought tbh... The only reason why the title wasnt shown in the nametag is because only the default values were used in the getName function. By setting this to true it is shown. (and also does not break the normal trainers)

See:
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/118fa7df-57cf-404d-a3fe-cf49227050b4)


Well and the titles look like before (second image in first post)

2024-05-18 16:32 UTC, bennybroseph requested changes
Don't forget semi colons at the end of lines.

Also, now that you have a better understanding of these files, can you leave some comments for others?

2024-05-18 17:51 UTC, CodeTappert commented
> Don't forget semi colons at the end of lines.
> 
> Also, now that you have a better understanding of these files, can you leave some comments for others?

Added semicolons and comments (but i dont know how much sense they make to someone who already knows how to code tbh)

2024-05-19 11:23 UTC, bennybroseph approved these changes

2024-05-19 11:23 UTC, merged