Calculate recoil damage correctly
pagefaultgames/pokerogue pull request #1063
Opened 2024-05-17 23:37 UTC by rayanzmn

As #1048 highlighted recoil damage isn't calculated correctly. Currently the recoil damage is a certain % of the total damage the user has dealt during the entire battle, now it should only take into account the damage dealt during the turn in which recoil is activated.

2024-05-17 23:58 UTC, rayanzmn commented
*take into account the damage dealt by the recoil move.
So it works even when recoil is activated multiple times in a single turn. Should've worded it better.

2024-05-18 02:37 UTC, TempsRay approved these changes
Looks good to me for fixing the bug. Weird that `turnData` stores information for total damage dealt during the entire battle though, when it should only store damage dealt this turn.

2024-05-18 10:10 UTC, rayanzmn commented
That's true I also find it weird. I was thinking of changing the name of turnData.damageDealt into turnData.totalDamageDealt since I suppose it could still be useful but I would've broken pretty much everything that uses it.

2024-05-18 10:18 UTC, rayanzmn commented
Actually now that I think about it, it does actually store the damage dealt during the turn. The issue is that if damage is dealt twice in a single turn it doesn't differentiate between the damage dealt the first time and the second time, it simply adds them.

2024-05-18 10:26 UTC, rayanzmn commented
I have edited the PR description to better describe the bug.

2024-05-19 19:50 UTC, bennybroseph requested changes
Can we get a video of how this was tested?

2024-05-19 22:00 UTC, rayanzmn commented
This is the current behavior of recoil (bugged):

https://github.com/pagefaultgames/pokerogue/assets/129906641/c57e3b51-0ea2-4f10-a76a-f52a410a65dc

Whereas this is the behavior of recoil after having implemented the fix:

https://github.com/pagefaultgames/pokerogue/assets/129906641/dfb968ff-3a7f-4e39-b55c-3744187ceda5

In both videos I have the console opened because I used the `console.log()` method to show the contents of `user.turnData.damageDealt` and `user.turnData.currDamageDealt` just for the sake of these tests (they're not in the actual PR).

2024-05-19 22:54 UTC, bennybroseph approved these changes

2024-05-19 22:54 UTC, merged