Implemented the Imprison move
pagefaultgames/pokerogue pull request #1121
Opened 2024-05-19 05:22 UTC by audriddax

# Summary

I've been enjoying this game, and wanted to start helping out. The first non-implemented move I encountered after this was Imprison, so I took a stab at implementing it. I plan to keep making PR"s for other moves I encounter.

Full disclosure, I've never used Imprison in the actual games, so my implementation is based on my research, I think I covered all the nuances of it. I've included all my test scenarios in case there is behavior that isn't actually expected.

# Tests

## Test Scenario 1: Opponent has moves not imprisoned

### Overrides
 
```javascript
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.EMBER, Moves.ACID, Moves.RECOVER, Moves.IMPRISON];
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [Moves.EMBER, Moves.ACID, Moves.LEER];
```

### Party

1. Bulbasaur
2. Charmander

### Tests
* If the imprisoning pokemon moves first, the opposing pokemon cannot attack since the move it chose is imprisoned when it attacks.
* If the imprisoning pokemon wins the battle and the next battle is a wild encounter, imprison is still in effect.
* If the imprisoning pokemon is swapped out, imprison no longer has an effect, even if the imprisoning pokemon is brought back into battle.
* When a trainer battle started, imprisoned was reset, so the trainer could use any move until imprison was used again.
* After a boss battle, imprisoning is reset, so the player needs to use it again.

## Test Scenario 2: Opponent only has imprisoned moved

### Overrides
 
```javascript
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.EMBER, Moves.ACID, Moves.RECOVER, Moves.IMPRISON];
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [Moves.EMBER, Moves.ACID];
```

### Party

1. Bulbasaur
2. Charmander

### Tests
* Once imprisoned is used, the opponent can only use struggle.

## Test Scenario 3: Imprisoning Pokemon faints
 
```javascript
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.EMBER, Moves.IMPRISON, Moves.AGILITY, Moves.LEER];
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [Moves.EMBER, Moves.BUBBLE, Moves.AGILITY, Moves.LEER];
```

### Party

1. Bulbasaur
2. Charmander

### Tests
* Once imprisoned is used, I let Bulbasaur faint, won the battle with Charmander, revived Bulbasaur, then swapped to Bulbasaur for the next batter. Imprisoned was no longer active.

2024-05-19 05:30 UTC, JakubHanko commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
I suppose the hashtag is an oversight?

2024-05-19 05:39 UTC, audriddax commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
It's to make it a private function, so it's only callable from this class. I didn't want to bog down the isUsable function with a bunch of logic, so I abstracted it into a private function to make isUsable more readable.

I'm good moving this directly into the isUsable function if that's preferable, this is just my default habit to assist with my interpretation of self-documenting code.

2024-05-19 05:43 UTC, audriddax commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
For reference on the hashtag:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties#private_methods

Let me know if there's anything else I can help with!

2024-05-19 05:46 UTC, JakubHanko commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
So it's my lack of knowledge then. Thanks for the explanation!

2024-05-19 05:48 UTC, audriddax commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
no problem!

tbh...I don't often makes classes in JS, so I always need to lookup how to make private methods when I need it. It's not intuitive.

2024-05-19 05:49 UTC, audriddax commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
I kinda wish typescript implemented some "private" modifier for a function that would compile to the hashtag

2024-05-19 09:00 UTC, Xavion3 commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
Doesn't the standard private access modifier work on functions?

2024-05-19 09:07 UTC, audriddax commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
as far as I know, that's not a thing in javascript, but if I'm wrong, please correct me! I would love for that to be a thing, it's so much clearer than the hashtag!

2024-05-19 12:41 UTC, bennybroseph commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
this is written in typescript, and `private myFucntion()` is valid syntax.

2024-05-19 16:37 UTC, audriddax commented on src/field/pokemon.ts
> +  #isImprisoned(pokemon: Pokemon) {
omg...how have I not known about this?!?!

I updated the code to use the typescript private syntax.

2024-05-19 19:16 UTC, bennybroseph requested changes
Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

2024-05-19 19:16 UTC, bennybroseph commented on src/data/enums/battler-tag-type.ts
> +  IMPRISONING = "IMPRISONING",
Should this be IMPRISONED?

2024-05-19 19:35 UTC, audriddax commented on src/data/enums/battler-tag-type.ts
> +  IMPRISONING = "IMPRISONING",
I originally did that, but it seemed like the attacker isn't the one imprisoned, they are imprisoning the opposing pokemon.

Do you want me to change that?

2024-05-19 19:48 UTC, bennybroseph commented on src/data/enums/battler-tag-type.ts
> +  IMPRISONING = "IMPRISONING",
I'm not sure, this just feels off. Have you looked at other moves like this such as Safeguard/Light Screen/etc.? If we have those implemented, I would check and see what we did in those cases and report back. This seems similar as it interacts with the opponents moves but is on the user's side of the field.

2024-05-19 19:50 UTC, audriddax commented on src/data/enums/battler-tag-type.ts
> +  IMPRISONING = "IMPRISONING",
I'll be honest, I'm in the same boat, it does feel off. To me, it just felt more off to tag the pokemon using it as IMPRISONED since it's really the opponents that are IMPRISONED.

I'll take a look at those moves you listed, thanks for the references!

2024-05-19 19:51 UTC, audriddax commented
> Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

I have no idea why I didn't do that, I usually work in vanilla js at work and do that for intellisense. My best guess is I just got spoiled by the auto-intellisense of typescript with typing and forget.

I'll get this added!

2024-05-19 20:03 UTC, audriddax commented
> Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

@bennybroseph ok, I added jsdoc comments, thanks for the callout on that!

2024-05-19 20:12 UTC, audriddax commented on src/data/enums/battler-tag-type.ts
> +  IMPRISONING = "IMPRISONING",
So I looked at those, and it looks like they aren't quite the same since they apply to an entire side, whereas imprison applies to a specific pokemon. That being said, I think I'm even more confused now on the naming, I'm seeing two different approaches.

For example, safeguard just tags as SAFEGUARD, that's the verb/action being referenced. If you look at other tags just above the new one, you see MINIMIZED and GROUNDED. So it looks like some tags are phrased as "I will" (I will SAFE GUARD) and others are "I am" (I am MINIMIZED).

I can go either way on this, but where I'm at is it should be either IMPRISON or IMPRISONING, but not IMPRISONED.

2024-05-19 22:34 UTC, bennybroseph requested changes
Okay, final things. 
- Need a video showing this working. 
- What is your source for the messages used for this move?
- Let's just use IMPRISON

2024-05-19 22:52 UTC, audriddax commented
> Okay, final things.
> 
> * Need a video showing this working.
> * What is your source for the messages used for this move?
> * Let's just use IMPRISON

@bennybroseph:
* Ok, that'll take me a bit, I just rebuilt my PC and haven't installed recording software. Once I've got that, is a youtube video what you're looking for?
* I looked up videos of imprison in action, here's a link to one that shows the verbiage: https://youtu.be/Z2-a9YmRIjw?si=iEovHDv54g4ponyR&t=620
* Changed to IMPRISON, thanks!

2024-05-19 23:54 UTC, audriddax commented
> > Okay, final things.
> > 
> > * Need a video showing this working.
> > * What is your source for the messages used for this move?
> > * Let's just use IMPRISON
> 
> @bennybroseph:
> 
> * Ok, that'll take me a bit, I just rebuilt my PC and haven't installed recording software. Once I've got that, is a youtube video what you're looking for?
> * I looked up videos of imprison in action, here's a link to one that shows the verbiage: https://youtu.be/Z2-a9YmRIjw?si=iEovHDv54g4ponyR&t=620
> * Changed to IMPRISON, thanks!

@bennybroseph ok, got a video together where I show all my testing scenarios:
https://www.youtube.com/watch?v=cPqg0rt6k-Y

2024-05-21 08:32 UTC, bennybroseph requested changes

2024-05-21 08:32 UTC, bennybroseph commented on src/data/battler-tags.ts
> +    super(BattlerTagType.IMPRISON, BattlerTagLapseType.CUSTOM, Number.MAX_SAFE_INTEGER, sourceMove);
Last thing, I'm confident this works, but I just can't get over this line with `Number.MAX_SAFE_INTEGER`. Don't get me wrong, I know exactly why it's done, but I really don't like it. Can we add a property called `infiniteDuration` or `ignoreTurnCount` or something and ignore the decrementing turn count so that we don't have to use this workaround?

2024-05-21 22:00 UTC, audriddax commented on src/data/battler-tags.ts
> +    super(BattlerTagType.IMPRISON, BattlerTagLapseType.CUSTOM, Number.MAX_SAFE_INTEGER, sourceMove);
Yeah, I'll get that updated. I wasn't a big fan of it either. Since this was my first commit to the project, I didn't want to do _to_ much to rock the boat until I had a better handling of the general coding style here.

2024-05-21 22:31 UTC, audriddax commented on src/data/battler-tags.ts
> +    super(BattlerTagType.IMPRISON, BattlerTagLapseType.CUSTOM, Number.MAX_SAFE_INTEGER, sourceMove);
So, I noticed there is this check in the Pokmeon.lapseTags() function:
```javascript
tags.filter(t => lapseType === BattlerTagLapseType.FAINT || ((t.lapseType === lapseType) && !(t.lapse(this, lapseType))) || (lapseType === BattlerTagLapseType.TURN_END && t.turnCount < 1))
```

If I'm reading this correctly, either I need to:
1. Still set the `turnCount` to something positive, like 1
1. Add a check for the new property `ignoreTurnCount` here

I'm not a fan of option 1 because that is still deceptive, but I'm also hesitant to add to the line above because now my change has broader effects on other moves (though it _shouldn't_ make a difference).

I'm leaning towards option 2, adding the `ignoreTurnCount` check as I think that plus a `turnCount = 0` property is the most descriptive and accurate, and then I'll just have to do some spot checking of other moves, but I wanted your opinion on this.

Which approach are you more comfortable with me implementing?

2024-05-22 05:41 UTC, bennybroseph commented on src/data/battler-tags.ts
> +    super(BattlerTagType.IMPRISON, BattlerTagLapseType.CUSTOM, Number.MAX_SAFE_INTEGER, sourceMove);
It is more destructive, but I think option 2 is needed. I'll take a look after you make the changes to see how it looks. We may run into more problems than it seems, but I'd like to try anyway and can always go back to max int if we absolutely have to.

2024-05-22 23:21 UTC, audriddax commented on src/data/battler-tags.ts
> +    super(BattlerTagType.IMPRISON, BattlerTagLapseType.CUSTOM, Number.MAX_SAFE_INTEGER, sourceMove);
Sounds good!

I don't have time to do testing right now, but I pushed the changes so you can review them in case something sticks out when you see it.

I'll try to get testing done tomorrow!

2024-05-23 07:27 UTC, bennybroseph requested changes

2024-05-23 07:27 UTC, bennybroseph commented on src/overrides.ts
Make sure this is removed from commits

2024-05-24 17:23 UTC, audriddax commented on src/overrides.ts
Oh wow, can't believe I let that through. Thanks for catching it!

2024-06-03 16:55 UTC, bennybroseph commented
Is this still being worked on?

2024-06-08 21:39 UTC, audriddax commented
> Is this still being worked on?
sorry, was busy the last couple of weeks, gonna clean this up now!

2024-06-08 21:47 UTC, audriddax commented
@bennybroseph -
Any suggestions on what to test outside of Imprison with the new change? Any specific moves you think should be tested, or should I just play for a bit and see if anything weird happens?

2024-07-11 17:56 UTC, Tempo-anon commented
Closing due to inactivity and merge conflicts

2024-07-11 17:56 UTC, closed without merging