Changed How is local is checked and how serverURL is build to prevent…
pagefaultgames/pokerogue pull request #1122
Opened 2024-05-19 07:59 UTC by CodeTappert

… errros in offline mode

Fixes #1078

2024-05-19 09:21 UTC, Admiral-Billy requested changes
Not having the `window.location.hostname === ''` check breaks the offline detection for local files, such as from my app :(

2024-05-19 09:27 UTC, CodeTappert commented
> Not having the `window.location.hostname === ''` check breaks the offline detection for local files, such as from my app :(

You mean for compiled files? Because this change works fine when run via "npm start dev".

Even if you serve dist folder it should work without problems

2024-05-19 09:36 UTC, Admiral-Billy commented
This is indeed back to working. Also yeah, my app is serving compiled files and registers as an empty string for that check for whatever reason; I don't know the details behind it, but that is what happens for it. My Android apk registers normally as localhost though.

2024-05-19 09:37 UTC, CodeTappert commented
> This is indeed back to working. Also yeah, my app is serving compiled files and registers as an empty string for that check for whatever reason; I don't know the details behind it, but that is what happens for it. My Android apk registers normally as localhost though.

I readded the check for you

2024-05-19 09:38 UTC, Admiral-Billy commented
Yep, that's what I was talking about; it works fine for my app's particular offline now. Now it's just up to the actual devs to see what they think of this change for their purposes heh

2024-05-19 19:09 UTC, athias commented
As there were minor changes to the code, I tested this again and can confirm it fixes #1078

2024-05-20 01:15 UTC, Admiral-Billy approved these changes
As far as I can tell, this works perfectly fine for both the dev server and my app.

2024-05-23 22:13 UTC, CodeTappert commented
This PR is ready to be reviewed/merged by a dev.

2024-05-27 11:57 UTC, CodeTappert commented
> This PR is ready to be reviewed/merged by a dev.

Walker says this is fine. See https://discord.com/channels/1125469663833370665/1243948971110694982

2024-05-27 13:05 UTC, bennybroseph requested changes

2024-05-27 13:05 UTC, bennybroseph commented on src/utils.ts
> +) || window.location.hostname === "";
This needs some better formatting, it looks pretty bad. Please use any kind of consistency with where you're splitting up the line

2024-05-27 13:08 UTC, CodeTappert commented on src/utils.ts
> +) || window.location.hostname === "";
To be fair i wouldnt split the line at all....
But then it is pretty long.

2024-05-27 13:21 UTC, bennybroseph requested changes
This is just a different kind of bad

2024-05-27 13:24 UTC, CodeTappert commented
Now it is consistent and breaks after || or && if it would be to long without the break

2024-05-27 15:19 UTC, bennybroseph approved these changes

2024-05-27 15:20 UTC, merged