Removes EXP Balance
pagefaultgames/pokerogue pull request #1128
Opened 2024-05-19 14:59 UTC by bennybroseph

The EXP Balance item is not currently functioning as a useful item. This removes the item temporarily until a better solution can be found. Saves with this item will have them removed and shops will no longer carry them.

### With EXP Balance

https://github.com/pagefaultgames/pokerogue/assets/13838608/af4b8ffe-1477-432e-8087-71cfc423e18e

### Without EXP Balance

https://github.com/pagefaultgames/pokerogue/assets/13838608/116b0094-d7ee-43dd-b410-0cacd4df0ead

2024-05-19 15:09 UTC, Greenlamp2 approved these changes

2024-05-19 15:14 UTC, Greenlamp2 commented
i've created a save with 5 exp balance, than i've applied your changes, as soon as we load the save, we can already see that the exp balance is no longer there.


Fun fact, if you start a save with 5 exp balance, you got -145 exp on the first wave lmao
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/7982d879-90d3-4df1-9824-10753ea3cafd)

2024-05-19 15:18 UTC, Gammer0909 commented
W-Why?

2024-05-19 15:25 UTC, Gammer0909 requested changes
This is an unneeded PR, and the item is implemented correctly, therefore there is no need to remove it.

2024-05-19 16:08 UTC, TempsRay commented
Straight up just deleting the item? Not sure about that. Could set the weight to 0 for now just to stop it spawning, but ideally I would like to see this reworked completely to be just a positive like "your lowest leveled pokemon gains +10% (per stack) more exp"

2024-05-19 17:04 UTC, MooGoesCow21 commented
> This is an unneeded PR, and the item is implemented correctly, therefore there is no need to remove it.

Its implemented correctly but as it is atm its a Trap item that sabotages runs

2024-05-19 17:15 UTC, Gammer0909 commented
> > This is an unneeded PR, and the item is implemented correctly, therefore there is no need to remove it.
> 
> 
> 
> Its implemented correctly but as it is atm its a Trap item that sabotages runs

Then... dont grab the item and reroll? I'm not sure what the issue is here. If you don't need the item, *then don't take it*.

2024-05-19 19:20 UTC, bennybroseph commented
The item can't be ignored as it appears in the shop until you have the maximum amount of it. This items does not prevent this:
> 200, 176, 140, 109, 190, 107
That's what EXP Share is already for.

2024-05-20 01:04 UTC, Admiral-Billy commented
I think a better solution in the meantime would just be capping it to 4 max instead of 5, or changing it to no longer have a downside but make the upside smaller.

2024-05-20 09:06 UTC, Xavion3 approved these changes

2024-05-20 09:06 UTC, merged

2024-05-21 22:03 UTC, zizibaloob commented
This change was a significant reduction to the quality of life of my runs. All party members would be at the level cap, and then all party members would immediately grow to the level cap as soon as it was increased.

Now only my party member holding eggs hits the level cap, at which point it stops contributing to the total xp pool (thereby eliminating the benefit of all the eggs). It is now significantly more difficult to keep all party members at the level cap.

Please revert this change.