Add support for ability changing effects
pagefaultgames/pokerogue pull request #113
Opened 2024-04-13 14:33 UTC by Xavion3

Adds almost complete support for all ability changing moves and abilities. This covers Role Play, Entrainment, Doodle, Simple Beam, and Worry Seed for moves, and Trace, Wandering Spirit, Mummy, Receiver, Power of Alchemy, and Lingering Aroma for abilities.

Wandering Spirit is currently marked as (P) still because it interacts incorrectly with rock head. It's meant to switch abilities before recoil would apply so that a pokemon with rock head would lose rock head first and still take the recoil, but this is a niche interaction that seemed like it was poorly supported with the current ordering of move and ability attribute application so is not including in this pull request.

2024-04-13 17:55 UTC, Flashfyre requested changes

2024-04-13 17:55 UTC, Flashfyre commented on src/data/move.ts
> +    }
Does this work if there is only 1 pokemon left in a double battle?

2024-04-13 23:16 UTC, Xavion3 commented on src/data/move.ts
> +    }
It did not correctly, fixed in the next commit.

2024-04-14 03:21 UTC, Flashfyre approved these changes

2024-04-14 03:21 UTC, merged