Implement Zero to hero
pagefaultgames/pokerogue pull request #1131
Opened 2024-05-19 19:13 UTC by XGSleepWalker

2024-05-19 19:28 UTC, JakubHanko commented on src/overrides.ts
> +export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.PALAFIN;
The overrides shouldn't be changed IMHO

2024-05-19 19:57 UTC, bennybroseph requested changes
Can we get a video of how this was tested?

2024-05-19 19:57 UTC, bennybroseph commented on src/data/ability.ts
> +   *
either need doc here or a removal of this space

2024-05-19 19:57 UTC, bennybroseph commented on src/overrides.ts
need to remove this commit

2024-05-19 20:19 UTC, LaukkaE commented
- [ * ]  Palafin switches to the correct form, and also back correctly.

- [  * ] Works with Self switching moves, as well as opponents force switching moves.

- [  * ]  If form is fusioned with another pokemon, stays in the form indefinitely while fusioned.

- [  * ] No console Errors found while testing.

- [  * ] If another pokemon that has another form should somehow acquire Zero to Hero, the ability will announce itself, but not change the form. 

- [  * ] Not affected by Trace, Gastro Acid, etc.

- [  * ] Fainting will not cause the form to change back.

Feature wise, seems to work correctly.

2024-05-21 01:59 UTC, XGSleepWalker commented on src/overrides.ts
> +export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.PALAFIN;
Reverted overrides back, thanks for noticing.

2024-05-28 11:11 UTC, merged