Add support for a simple menu message
pagefaultgames/pokerogue pull request #1142
Opened 2024-05-19 23:25 UTC by Admiral-Billy

As the title implies, this adds support for a basic menu message that can be used to alert players of shiny events, special updates, giveaways, etc.

If the message is an empty string, it just won't show up at all. If the background color is blank, there will be no background color. if the text color is blank, it'll default to white.

For example this is the result of this code:

```typescript
export const MENU_MESSAGE: string = "Admiral Billy cool mode active!";
export const MENU_MESSAGE_TEXT_COLOR: string = "#FFD700";
export const MENU_MESSAGE_BACKGROUND_COLOR: string = "#FF69B4";
```

![image](https://github.com/pagefaultgames/pokerogue/assets/72857839/1466d2a1-a31e-4066-9a29-5134bfb1c2e9)

2024-05-19 23:58 UTC, molker requested changes
this is a great idea, very simple way to display events
one small suggestion

2024-05-19 23:58 UTC, molker commented on src/overrides.ts
> +export const MENU_MESSAGE_BACKGROUND_COLOR: string = "";
if these are always going to be used together can they be one object MENU_MESSAGE with keys for each of these consts?
and have an "active" key like in the pokeball override so we can use that as the conditional?

2024-05-20 00:46 UTC, Admiral-Billy commented on src/overrides.ts
> +export const MENU_MESSAGE_BACKGROUND_COLOR: string = "";
I pushed some changes; are you looking for something like that, or did I misunderstand? The settings currently pushed are for a shiny event, with gold text and a pale yellow background.

2024-05-20 01:30 UTC, danieland commented on src/overrides.ts
> +    text: "Shiny event active!",
Any thoughts on localization ?

2024-05-20 01:32 UTC, Admiral-Billy commented on src/overrides.ts
> +    text: "Shiny event active!",
I'm not sure how the localization is handled normally; presumably the text here can be handled the same way as other localization strings if needed?

2024-05-20 01:43 UTC, danieland commented on src/overrides.ts
> +    text: "Shiny event active!",
Code wise it's pretty straightforward, an example from the current code can be seen here:
https://github.com/pagefaultgames/pokerogue/blob/3671fe4c2f81b8efe097819079408fd4432d699c/src/data/pokeball.ts#L30

`import i18next from '../plugins/i18n';` gives access to the localization library
`i18next.t('pokeball:greatBall');` means get the translation with the name "greatBall" from the file "pokeball"

Personally I think all texts should be localizable, buuut maybe this one doesn't make sense to do since it's a sort of "admin" message that would require admins to be able to translate into 10+ languages ?

2024-05-20 01:51 UTC, molker commented on src/overrides.ts
> +    text: "Shiny event active!",
It would be nice to be able to translate it, we'd have to run it by a  native speaker or hope for the best with google translate or something
I think for an initial implementation english should be okay until we figure out a process for all translations

2024-05-20 01:52 UTC, molker commented on src/overrides.ts
> +export const MENU_MESSAGE_BACKGROUND_COLOR: string = "";
That's exactly what I meant, thank you

2024-05-20 02:38 UTC, Admiral-Billy commented
The PR still said the changes were needed so I went ahead and re-requested the review.

I can also change the current settings if needed, but they do at least accurately describe what's currently going on even if it isn't pretty.

2024-05-20 16:19 UTC, molker commented on src/ui/title-ui-handler.ts
> +        this.menuMessage = addTextObject(this.scene, (this.scene.game.canvas.width / 6) - 2, (this.scene.game.canvas.height / 6) - 100, Overrides.MENU_MESSAGE.text, TextStyle.MESSAGE, {
you  need to add menuMessage as a property of titleuihandler

2024-05-20 22:07 UTC, Admiral-Billy commented on src/ui/title-ui-handler.ts
> +        this.menuMessage = addTextObject(this.scene, (this.scene.game.canvas.width / 6) - 2, (this.scene.game.canvas.height / 6) - 100, Overrides.MENU_MESSAGE.text, TextStyle.MESSAGE, {
So you'd rather have it there instead of in the overrides? I can make that work.

2024-07-29 18:39 UTC, flx-sta commented
No action within more than a month. 
Considered stale.

Feel free to re-open it when you are still working on it/want to work on it again

2024-07-29 18:39 UTC, closed without merging