Achievements localization, organized some locales files and ptBR translations
pagefaultgames/pokerogue pull request #1150
Opened 2024-05-20 06:43 UTC by josericardo-fo

Localized whole achievements screen dded some ptBR translations and organized imports, classes and languages in alphabetical order.

2024-05-20 06:45 UTC, josericardo-fo commented
I'll be adding the achv.ts file for the other languages (english by default)

2024-05-20 17:14 UTC, josericardo-fo commented
Ready for review.

2024-05-20 18:29 UTC, josericardo-fo commented
Ready for review. Help wanted, explanation is in the description.

2024-05-20 21:29 UTC, josericardo-fo commented
Ready for commit.

2024-05-20 21:42 UTC, Adri1 approved these changes

2024-05-21 21:26 UTC, Adri1 commented
I subbitted a French translation to your branch

2024-05-21 23:59 UTC, Adri1 approved these changes

2024-05-22 18:41 UTC, Adri1 commented
Made a tiny typo correction to French achiv file

2024-05-23 15:48 UTC, josericardo-fo commented
@CodeTappert @Adri1 review this, just resolved some conflits

2024-05-26 15:39 UTC, Adri1 commented
@josericardo-fo I think you have some issues to address, as new checking procedures have been depoyed that currently prevent your PR to be successful

2024-05-26 17:57 UTC, josericardo-fo commented
@Adri1 I think everythings good here

2024-05-26 17:58 UTC, Adri1 approved these changes

2024-05-26 18:05 UTC, Adri1 approved these changes

2024-05-26 18:25 UTC, josericardo-fo commented
@Adri1 do you think theres a way to also localize the achievement pop-ups?

2024-05-26 18:34 UTC, Adri1 commented
> @Adri1 do you think theres a way to also localize the achievement pop-ups?

Don't your work also works for the pop-ups?
Because when I translated the Vouchers menu, it noticed that the it also automatically appeared translated in the pop-ups, including the unlocking condition and stuff

2024-05-26 18:48 UTC, josericardo-fo commented
Maybe DerTapp messed with that in his commit. Great, so this is ready for review

2024-05-26 18:53 UTC, CodeTappert commented
You should test it!

2024-05-26 20:04 UTC, josericardo-fo commented
When I get the shiny party achievement, it's printing SHINY_PARTY.description

2024-05-26 20:20 UTC, CodeTappert commented
> When I get the shiny party achievement, it's printing SHINY_PARTY.description

Well then it is not working correct

2024-05-27 23:26 UTC, josericardo-fo commented
@Adri1 @CodeTappert can you guys take a look here? Not finding what's wrong with the popup and recent commits changed the code and its failing checks.

2024-05-27 23:44 UTC, Adri1 commented
> @Adri1 @CodeTappert can you guys take a look here? Not finding what's wrong with the popup and recent commits changed the code and its failing checks.

I don't know if it's the only promen, but in src/plugins/i18n.ts , it seems you forgot a closing bracket on line 71 for this :

`export interface AchievementTranslationEntries {
  [key: string]: AchievementTranslationEntry`

2024-05-28 00:07 UTC, josericardo-fo commented
> > @Adri1 @CodeTappert can you guys take a look here? Not finding what's wrong with the popup and recent commits changed the code and its failing checks.
> 
> I don't know if it's the only problem, but in src/plugins/i18n.ts , it seems you forgot a closing bracket for this on lines 68/69 :

Should be fixed now. But the achievement popup is still not working

2024-05-28 01:28 UTC, josericardo-fo commented
@CodeTappert any ideas?

2024-05-28 14:52 UTC, CodeTappert commented
> > > @CodeTappert any ideas?
> > 
> > 
> > This PR fixes it: [josericardo-fo#5](https://github.com/josericardo-fo/pokerogue/pull/5)
> 
> 🙌

Ähm...You merged it into your main.

2024-05-28 14:57 UTC, josericardo-fo commented
lol sorry

2024-05-28 17:42 UTC, CodeTappert commented
I added a new PR to your project that now implements the size based on content. Here is a video showing it:


https://github.com/pagefaultgames/pokerogue/assets/38758606/00a10fdd-85f4-4001-a3a1-0ea07b425419

2024-05-28 17:47 UTC, CodeTappert commented
> I added a new PR to your project that now implements the size based on content. Here is a video showing it:
> 
>  Aufzeichnung.2024-05-28.193823.mp4

This one: https://github.com/josericardo-fo/pokerogue/pull/8

2024-05-28 19:09 UTC, Adri1 commented
While your PR is still waiting, I created a PR to your branch with some tiny edits on the French translation

2024-05-28 22:57 UTC, flx-sta commented on src/locales/de/pokemon-info.ts
> +    "HPshortened": "KP",
So KP includes the `Max` in it?
As far as I know `KP` stands for `Kraftpunkte` or so and that's not `maximal Kraftpunkte` isn't it?

2024-05-28 22:57 UTC, flx-sta commented on src/locales/en/config.ts
honestly the `enConfig` could be simplified to:
```js
export const enConfig = {
  ability,
  abilityTriggers,
  achv,
  battle,
  battleMessageUiHandler,
  berry,
  biome,
  commandUiHandler,
  egg,
  fightUiHandler,
  growth,
  menu,
  menuUiHandler,
  modifierType,
  move,
  nature,
  pokeball,
  pokemon,
  pokemonInfo,
  splashMessages,
  starterSelectUiHandler,
  titles,
  trainerClasses,
  trainerNames,
  tutorial,
  weather,
  battleMessageUiHandler,
  berry,
  gameStatsUiHandler,
  voucher,
  biome,
  pokemonInfoContainer,
  PGMdialogue,
  PGFdialogue,
  PGMbattleSpecDialogue,
  PGFbattleSpecDialogue,
  PGMmiscDialogue,
  PGFmiscDialogue,
  PGMdoubleBattleDialogue,
  PGFdoubleBattleDialogue,
};
```

but I think that's another PR/branch/committ

2024-05-28 22:57 UTC, flx-sta commented on src/locales/es/config.ts
same simplifications possible as in `enConfig`;

2024-05-28 22:57 UTC, flx-sta commented on src/locales/zh_CN/config.ts
same simplification possible as in `enConfig`

2024-05-28 22:57 UTC, flx-sta commented on src/plugins/i18n.ts
> +}
name & description are both optional?

2024-05-28 22:57 UTC, flx-sta commented on src/ui/achv-bar.ts
> +const FONT_SIZE = 72;
I feel like `FONT_SIZE` is too generic of a name (personalized opinion)

2024-05-28 22:57 UTC, flx-sta commented on src/ui/achv-bar.ts
> +const ACHEIVEMENT_BAR_MIN_HEIGHT = 40;
typo

2024-05-28 22:57 UTC, flx-sta commented on src/ui/achv-bar.ts
> +    this.descriptionText.setWordWrapWidth(680);
try to avoid "magic numbers".
Put it into a constant with a descriptive name

2024-05-28 22:57 UTC, flx-sta commented on src/ui/achv-bar.ts
> +    this.descriptionText.setText(getAchievementDescription((achv as Achv).localizationKey));
what the point of allowing `ache` being a `Voucher` type if you are going to force a type here anyway?

2024-05-28 22:57 UTC, flx-sta commented on src/ui/achvs-ui-handler.ts
> +    achv.name = i18next.t(`achv:${achv.localizationKey}.name`);
manipulating values of a method arg is not recommended practice for clean coding

2024-05-28 23:05 UTC, Adri1 commented on src/locales/de/pokemon-info.ts
> +    "HPshortened": "KP",
Whatever the language, I don't even knew where "Max" comes from in the first place, as even in English there no is such thing as "Max HP" in official games, no matter if we talk about shortened or not:
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/ea6ed966-bcf1-4c80-9a3c-7bb824ea1ef6)

As such, in the French translation of PokéRogue, we instantly got rid of it

2024-05-28 23:07 UTC, flx-sta commented on src/locales/de/pokemon-info.ts
> +    "HPshortened": "KP",
Oh I see what happened.
It was falsely added in the German version to begin with.
Thanks for clearing that up

2024-05-28 23:12 UTC, CodeTappert commented on src/locales/de/pokemon-info.ts
> +    "HPshortened": "KP",
> Oh I see what happened. It was falsely added in the German version to begin with. Thanks for clearing that up

Yes i removed it since it made no sense at all.

2024-05-28 23:12 UTC, CodeTappert commented on src/locales/en/config.ts
How?

2024-05-28 23:13 UTC, CodeTappert commented on src/ui/achv-bar.ts
> +const ACHEIVEMENT_BAR_MIN_HEIGHT = 40;
Is not relevant anymore. Since https://github.com/pagefaultgames/pokerogue/pull/1520 will override this anyways. @Dakurei fixed this way better then i ever could

2024-05-28 23:13 UTC, CodeTappert commented on src/plugins/i18n.ts
> +}
See https://github.com/pagefaultgames/pokerogue/pull/1150#discussion_r1617982920

2024-05-28 23:14 UTC, CodeTappert commented on src/ui/achv-bar.ts
> +const FONT_SIZE = 72;
See https://github.com/pagefaultgames/pokerogue/pull/1150#discussion_r1617982920

2024-05-28 23:14 UTC, CodeTappert commented on src/ui/achv-bar.ts
> +    this.descriptionText.setText(getAchievementDescription((achv as Achv).localizationKey));
I dont know. This was already there...

2024-05-28 23:15 UTC, CodeTappert commented on src/ui/achvs-ui-handler.ts
> +    achv.name = i18next.t(`achv:${achv.localizationKey}.name`);
How to do it better? i mean this is what is shown after all?

2024-05-28 23:19 UTC, CodeTappert commented on src/ui/achvs-ui-handler.ts
> +    achv.name = i18next.t(`achv:${achv.localizationKey}.name`);
Oh and achv.name always is empty (on purpose) so it can be localized

2024-05-28 23:19 UTC, CodeTappert commented on src/plugins/i18n.ts
> +}
Yes since they are empty and will be localized/filled during runtime

2024-05-28 23:21 UTC, flx-sta commented on src/ui/achvs-ui-handler.ts
> +    achv.name = i18next.t(`achv:${achv.localizationKey}.name`);
The reasons you want to avoid that is that you are passing an obj which is `by reference` thus it could cause unexpected side-effects that can be hard to back-track.

One way would be to save those values into their own variables and use these instead of `achv.name`

e.g.
`const localizedName = i18next.t(`achv:${achv.localizationKey}.name`);`

and then later

`this.titleText.setText(unlocked ? localizedText : "???");`

2024-05-28 23:23 UTC, CodeTappert commented on src/ui/achvs-ui-handler.ts
> +    achv.name = i18next.t(`achv:${achv.localizationKey}.name`);
Okay but achv.name is literally on purpose set empty.

2024-05-28 23:23 UTC, flx-sta commented on src/ui/achvs-ui-handler.ts
> +    achv.name = i18next.t(`achv:${achv.localizationKey}.name`);
> Oh and achv.name always is empty (on purpose) so it can be localized

I guess that how this project handles it then..
Not a fan personally.

2024-05-28 23:23 UTC, flx-sta commented on src/ui/achvs-ui-handler.ts
> +    achv.name = i18next.t(`achv:${achv.localizationKey}.name`);
Also. You could postpone loading the localized name ONLY if the achievement. is `unlocked`. Saves some processing time

2024-05-28 23:32 UTC, flx-sta commented on src/ui/achv-bar.ts
> +    this.descriptionText.setText(getAchievementDescription((achv as Achv).localizationKey));
@CodeTappert this is used [here](https://github.com/pagefaultgames/pokerogue/blob/47d39388ac181b3713ac42e03269dfb3ece5df0d/src/battle-scene.ts#L2141)
<img width="828" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/e223466b-10e4-4a5b-92bc-1e9ebe4ceb2d">

Can the Voucher interface also support the `localizationKey` prop? Otherwise this might cause side-effects

2024-05-29 06:52 UTC, CodeTappert commented on src/ui/achv-bar.ts
> +    this.descriptionText.setText(getAchievementDescription((achv as Achv).localizationKey));
> @CodeTappert this is used [here](https://github.com/pagefaultgames/pokerogue/blob/47d39388ac181b3713ac42e03269dfb3ece5df0d/src/battle-scene.ts#L2141) <img alt="image" width="828" src="https://private-user-images.githubusercontent.com/50131232/334600978-e223466b-10e4-4a5b-92bc-1e9ebe4ceb2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjU0OTEsIm5iZiI6MTcxNjk2NTE5MSwicGF0aCI6Ii81MDEzMTIzMi8zMzQ2MDA5NzgtZTIyMzQ2NmItMTBlNC00YTViLTkyYmMtMWU5ZWJlNGNlYjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA2NDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYmVlNDc0N2U0MjFlOWY2Y2QyM2MxM2I3ZGNmOWZkZWNjOTI0OTI3MDUyMWZiZTJlOTcyOTk3OWMyNmU5MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q1-dpA-1lt4qgYsXxDcPxArw3zoEVaAd23rUHoQRd-w">
> 
> Can the Voucher interface also support the `localizationKey` prop? Otherwise this might cause side-effects

You are correct. It breaks it. 
I will fix that.

2024-05-29 12:51 UTC, Dakurei requested changes
Only the 2 lines
```typescript
import {Achv, getAchievementDescription} from "../system/achv";
```
and 
```typescript
this.descriptionText.setText(getAchievementDescription((achv as Achv).localizationKey));
```
for the file `src/ui/achv-bar.ts` are necessary, the rest is a merge error, and produces some nasty interface errors

> With your erroneous changes
![Screenshot_20240529_144935_Firefox](https://github.com/pagefaultgames/pokerogue/assets/8146474/ada05f10-c414-4ee3-80b5-d39ce11d7828)

> Whithout your erroneous changes
![Screenshot_20240529_144547_Firefox](https://github.com/pagefaultgames/pokerogue/assets/8146474/b2f88aab-cf19-4c9c-abca-e7e314ae96a5)

2024-05-29 12:53 UTC, CodeTappert commented
> Only the 2 lines
> ```typescript
> import {Achv, getAchievementDescription} from "../system/achv";
> ```
> and 
> ```typescript
> this.descriptionText.setText(getAchievementDescription((achv as Achv).localizationKey));
> ```
> for the file `src/ui/achv-bar.ts` are necessary, the rest is a merge error, and produces some nasty interface errors
> 
> > With your erroneous changes
> ![Screenshot_20240529_144935_Firefox](https://github.com/pagefaultgames/pokerogue/assets/8146474/ada05f10-c414-4ee3-80b5-d39ce11d7828)
> 
> > Whithout your erroneous changes
> ![Screenshot_20240529_144547_Firefox](https://github.com/pagefaultgames/pokerogue/assets/8146474/b2f88aab-cf19-4c9c-abca-e7e314ae96a5)
> 

How? Like i did a merge request to his branch that did exactly what you said. (take main and only change the lines).

Didnt he merge my pr to his branch in (yet?)

2024-05-29 12:55 UTC, Dakurei commented
He didn't merge your PR

2024-05-29 12:57 UTC, CodeTappert commented
> He didn't merge your PR

https://github.com/josericardo-fo/pokerogue/pull/10


Did i do.it correctly? (And yes the Voucher Thing is necessary at the description)

2024-05-29 13:04 UTC, Dakurei commented
> > He didn't merge your PR
> 
> [josericardo-fo#10](https://github.com/josericardo-fo/pokerogue/pull/10)
> 
> Did i do.it correctly? (And yes the Voucher Thing is necessary at the description)

Yes indeed, there is also the condition for the voucher description, I skipped it without 😅

2024-05-29 13:13 UTC, Dakurei commented
Missings import at `src/ui/achv-bar.ts`

```typescript
import { Achv } from "../system/achv";
```

to

```typescript
import { Achv, getAchievementDescription } from "../system/achv";
```

2024-05-29 13:24 UTC, josericardo-fo commented
> Missings import at `src/ui/achv-bar.ts`
> 
> ```ts
> import { Achv } from "../system/achv";
> ```
> 
> to
> 
> ```ts
> import { Achv, getAchievementDescription } from "../system/achv";
> ```

fixed

2024-05-29 14:33 UTC, flx-sta commented on src/locales/en/config.ts
In js/ts in an an object if a key has the same name as the variable that is the value you can shorten it:
https://attacomsian.com/blog/javascript-object-property-shorthand

2024-05-30 00:23 UTC, XGSleepWalker submitted a review, later dismissed

2024-05-30 03:09 UTC, XGSleepWalker requested changes
Fix the build warnings, we'll merge it then.

2024-05-31 00:31 UTC, returntoice requested changes
korean localed suggested

2024-05-31 00:31 UTC, returntoice commented on src/locales/ko/achv.ts
> +    description: "Beat the game in classic mode",
```suggestion
    name: "업적",
  },
  "Locked": {
    name: "미완료",
  },

  "MoneyAchv": {
    description: "누적 소지금 ₽{{moneyAmount}} 달성",
  },
  "10K_MONEY": {
    name: "돈 좀 있나?",
  },
  "100K_MONEY": {
    name: "부자",
  },
  "1M_MONEY": {
    name: "백만장자",
  },
  "10M_MONEY": {
    name: "상위 1프로",
  },

  "DamageAchv": {
    description: "한 번의 공격만으로 {{damageAmount}} 대미지",
  },
  "250_DMG": {
    name: "강타자",
  },
  "1000_DMG": {
    name: "최강타자",
  },
  "2500_DMG": {
    name: "때릴 줄 아시는군요!",
  },
  "10000_DMG": {
    name: "원펀맨",
  },

  "HealAchv": {
    description: "기술이나 특성, 지닌 도구로 한 번에 {{healAmount}} {{HP}} 회복",
  },
  "250_HEAL": {
    name: "견습 힐러",
  },
  "1000_HEAL": {
    name: "상급 힐러",
  },
  "2500_HEAL": {
    name: "클레릭",
  },
  "10000_HEAL": {
    name: "회복 마스터",
  },

  "LevelAchv": {
    description: "포켓몬 Lv{{level}} 달성",
  },
  "LV_100": {
    name: "잠깐, 여기가 끝이 아니라구!",
  },
  "LV_250": {
    name: "엘리트",
  },
  "LV_1000": {
    name: "더 먼 곳을 향해",
  },

  "RibbonAchv": {
    description: "총 {{ribbonAmount}}개의 리본 획득",
  },
  "10_RIBBONS": {
    name: "포켓몬 리그 챔피언",
  },
  "25_RIBBONS": {
    name: "슈퍼 리그 챔피언",
  },
  "50_RIBBONS": {
    name: "하이퍼 리그 챔피언",
  },
  "75_RIBBONS": {
    name: "로그 리그 챔피언",
  },
  "100_RIBBONS": {
    name: "마스터 리그 챔피언",
  },

  "TRANSFER_MAX_BATTLE_STAT": {
    name: "팀워크",
    description: "한 개 이상의 능력치가 최대 랭크일 때 배턴터치 사용",
  },
  "MAX_FRIENDSHIP": {
    name: "친밀 맥스",
    description: "최대 친밀도 달성",
  },
  "MEGA_EVOLVE": {
    name: "메가변환",
    description: "포켓몬을 메가진화",
  },
  "GIGANTAMAX": {
    name: "엄청난 것",
    description: "포켓몬을 다이맥스",
  },
  "TERASTALLIZE": {
    name: "반짝반짝",
    description: "포켓몬을 테라스탈",
  },
  "STELLAR_TERASTALLIZE": {
    name: "숨겨진 타입",
    description: "포켓몬을 스텔라 테라스탈",
  },
  "SPLICE": {
    name: "끝없는 융합",
    description: "유전자쐐기로 두 포켓몬을 융합",
  },
  "MINI_BLACK_HOLE": {
    name: "도구가 가득한 구멍",
    description: "미니 블랙홀 획득",
  },
  "CATCH_MYTHICAL": {
    name: "환상",
    description: "환상의 포켓몬 포획",
  },
  "CATCH_SUB_LEGENDARY": {
    name: "(준)전설",
    description: "준전설 포켓몬 포획",
  },
  "CATCH_LEGENDARY": {
    name: "전설",
    description: "전설의 포켓몬 포획",
  },
  "SEE_SHINY": {
    name: "다른 색",
    description: "야생의 색이 다른 포켓몬 발견",
  },
  "SHINY_PARTY": {
    name: "찐사랑",
    description: "색이 다른 포켓몬만으로 파티 구성",
  },
  "HATCH_MYTHICAL": {
    name: "환상의 알",
    description: "알에서 환상의 포켓몬이 부화",
  },
  "HATCH_SUB_LEGENDARY": {
    name: "준전설 알",
    description: "알에서 준전설 포켓몬이 부화",
  },
  "HATCH_LEGENDARY": {
    name: "전설의 알",
    description: "알에서 전설의 포켓몬이 부화",
  },
  "HATCH_SHINY": {
    name: "빛나는 알",
    description: "알에서 색이 다른 포켓몬이 부화",
  },
  "HIDDEN_ABILITY": {
    name: "숨은 잠재력",
    description: "숨겨진 특성을 지닌 포켓몬을 포획",
  },
  "PERFECT_IVS": {
    name: "진짜배기 증명서",
    description: "최고의 개체값을 지닌 포켓몬 획득",
  },
  "CLASSIC_VICTORY": {
    name: "무패",
    description: "클래식 모드 클리어",
```

2024-05-31 13:50 UTC, josericardo-fo commented on src/locales/ko/achv.ts
> +    description: "Beat the game in classic mode",
added korean locales

2024-05-31 13:51 UTC, returntoice approved these changes

2024-06-01 23:52 UTC, XGSleepWalker approved these changes

2024-06-01 23:53 UTC, merged