Added support for Poison Heal (Ability)
pagefaultgames/pokerogue pull request #116
Opened 2024-04-13 17:50 UTC by EmoUsedHM01

Updated the Ability value, PostTurnStatusEffectPhase, and getStatusEffectActivationText (with placeholder if statement)
Functions as intended and heals the poke when poisoned, poison effects still deal damage as usual if you don't have the ability
Tested on local

2024-04-13 17:54 UTC, Flashfyre requested changes

2024-04-13 17:54 UTC, Flashfyre commented on src/data/status-effect.ts
> +      if (pokemon && pokemon.getAbility().id === Abilities.POISON_HEAL) {
This doesn't support passives. Please refer to how abilities are checked in existing code.

2024-04-13 17:54 UTC, Flashfyre commented on src/data/status-effect.ts
> +        console.log("Poison Heal ability detected");
Logs should be removed before pushing PR.

2024-04-13 17:54 UTC, Flashfyre commented on src/phases.ts
>          let damage: integer = 0;
Do we need 2 variables? It's always either one or the other, right?

2024-04-13 17:54 UTC, Flashfyre commented on src/phases.ts
>            pokemon.updateInfo();
These are almost the same, unify these

2024-04-13 18:11 UTC, EmoUsedHM01 commented
Should be cleaned up now, just double checked and tested again

2024-04-14 05:31 UTC, Flashfyre requested changes

2024-04-14 05:31 UTC, Flashfyre commented on src/phases.ts
> +        const isHealing = pokemon.getAbility().id === Abilities.POISON_HEAL;
This doesn't support passives. If you can't use apply then check pokemon.canApplyPassive and then check again pokemon.getPassive().id

2024-04-16 19:42 UTC, Flashfyre requested changes

2024-04-16 19:42 UTC, Flashfyre commented on src/phases.ts
> +        const isHealing = pokemon.getAbility().id === Abilities.POISON_HEAL || pokemon.getPassive().id === Abilities.POISON_HEAL; // Added check for both Ability and the new Passives
You need to check hasPassive or it'll count a disabled passive as active

2024-04-19 13:29 UTC, Flashfyre requested changes

2024-04-19 13:29 UTC, Flashfyre commented on src/phases.ts
> +        const isHealing = pokemon.getAbility().id === Abilities.POISON_HEAL || pokemon.hasPassive().id === Abilities.POISON_HEAL; // Added check for both Ability and the new Passives
hasPassive() is a boolean, it won't have id

2024-04-20 17:12 UTC, Xavion3 commented on src/phases.ts
> +        const isHealing = pokemon.getAbility().id === Abilities.POISON_HEAL || pokemon.hasPassive().id === Abilities.POISON_HEAL; // Added check for both Ability and the new Passives
Also you could just be using `pokemon.hasAbility(Abilities.POISON_HEAL)`.

2024-04-29 18:23 UTC, chacolah commented on src/phases.ts
> +        const isHealing = pokemon.getAbility().id === Abilities.POISON_HEAL || pokemon.hasPassive().id === Abilities.POISON_HEAL; // Added check for both Ability and the new Passives
Currently throwing an Abilities not defined error on line 2920 in Phases.ts

2024-05-08 04:13 UTC, bennybroseph commented
Not seeing the graphic for when an ability triggers. I'm getting healed from poison, but if I didn't know better I wouldn't understand why. The text also still says I'm hurt from poison.

2024-05-08 04:14 UTC, bennybroseph requested changes

2024-05-08 04:14 UTC, bennybroseph commented on src/phases.ts
> +          this.end();  // End the phase if no net effect to apply
I'm guessing it's because it's getting hardcoded here? I'm pretty sure we need an implementation where it triggers from an apply call on the Attribute itself

2024-05-13 08:56 UTC, bennybroseph commented
Closing based on Discord conversation

2024-05-13 08:56 UTC, closed without merging