No more end to Endless
pagefaultgames/pokerogue pull request #1229
Opened 2024-05-22 02:05 UTC by BatCrowP

Fixing the crash bug that occurs when Endless runs reach floor 5850

2024-05-22 02:13 UTC, MooGoesCow21 commented
Yeah this would be nice especially since there is a lot of people who have a big advantage with bugged runs that can do this already

2024-05-22 04:48 UTC, Reibd commented
This would be nice for people who want to continue their current run past 5850

2024-05-22 10:20 UTC, Greenlamp2 commented
Hello, could you explain why endless was crashing initially and what did you do to fix it please ?

2024-05-22 21:10 UTC, BatCrowP commented
Endless currently crashes upon reaching a full token count. It tries to find a new token to give to players and finds nothing so it returns null and proceeds to crash. 
The change I made was a tweak to getEnemyBuffModifierForWave that checks if the candidate token is a null and doesn't try to add the token if it is null. If the token isn't null it lets the function operate exactly as it currently does.

2024-05-23 05:27 UTC, BatCrowP reviewed
well this was an accident, meant to make a separate PR for the luck based encounters

2024-05-23 10:09 UTC, Greenlamp2 requested changes
In phases.ts, getEnemyBuffModifierForWave is called in this.scene.addEnemyModifier.
what happens there when it's null ?
(did you test your code on a real run ? if yes, could you provide an exported session ?)

2024-05-23 10:09 UTC, Greenlamp2 commented on src/modifier/modifier-type.ts
> +    } else {
alignment issue + unneeded ELSE since you got a return in the previous IF

2024-05-23 15:53 UTC, BatCrowP commented on src/modifier/modifier-type.ts
> +    } else {
[SessionData.zip](https://github.com/pagefaultgames/pokerogue/files/15418736/SessionData.zip)
Attached are two runs, one that I tested progressing normally and was still getting tokens, the 5852 is one that I tested a run that is currently frozen on 5850. When null is passed to addEnemyModifier then it will resolve after finding that the null is not a terrastilize or enemy modifier. No error messages when testing on either run

2024-05-24 18:08 UTC, Greenlamp2 approved these changes

2024-05-24 20:52 UTC, bennybroseph requested changes
needs conflicts resolved

2024-05-24 22:47 UTC, Greenlamp2 commented on src/modifier/modifier-type.ts
> +    } else {
are you sure these are the good save files ? None of these are stuck on 5850, and whatever i do, on the main branch, i can't make it crash.
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/33df9ee9-082e-4ae4-bb07-781b09bc1e86)

2024-05-24 23:11 UTC, BatCrowP commented on src/modifier/modifier-type.ts
> +    } else {
[sessionData_Krow.prsv.zip](https://github.com/pagefaultgames/pokerogue/files/15440737/sessionData_Krow.prsv.zip)
Attached is the 5850 file as it currently stands on the main branch.

2024-05-27 05:54 UTC, BatCrowP commented
Anything that I can do here or is this dead?

2024-05-28 05:15 UTC, Xavion3 commented
Yeah, an alternative solution was implemented in #1463

2024-05-28 05:15 UTC, closed without merging