Updated Hydro Steam to function correctly
pagefaultgames/pokerogue pull request #123
Opened 2024-04-14 10:17 UTC by EmoUsedHM01

the 3:1 multiplier stack with the 0.5 one from Sunlight gives an end result of 1.5, tested on local

2024-04-14 14:07 UTC, molker commented
does it need to be checking for SUNNY or HARSH_SUN

2024-04-14 14:29 UTC, EmoUsedHM01 commented
"Harsh Sun" should only come from Desolate Wasteland or w/e it's called, and that stops all water moves from working in general, including Hydro Steam

2024-04-14 16:05 UTC, molker commented
sounds good, wanted to double check 
the different terminology on bulbapedia was annoying me

2024-04-15 20:38 UTC, EmoUsedHM01 commented
> Anything that works in sunny should also work in harsh sun

https://www.serebii.net/games/weather.shtml

"Sunshine" is different from "Harsh Sun" which is a weather that stops all water moves from functioning at all

"Along with the usual effects of Sunshine, harsh sunlight causes damage-dealing Water-type moves to fail (unless a Pokémon on the field has the Air Lock or Cloud Nine Ability)."

2024-04-24 21:16 UTC, gooo12343 approved these changes

2024-04-26 08:24 UTC, Xavion3 requested changes

2024-04-26 08:24 UTC, Xavion3 commented on src/data/move.ts
> +      if (user.getAbility().id === Abilities.NORMALIZE)
This doesn't support other ways of changing a moves type, doesn't check if normalize is being applied, and doesn't even actually check if the pokemon has normalize. This might be best to wait until the move type refactor happens? But even before then there has to be a better way than this. hasAbility at least.

2024-04-27 09:45 UTC, closed without merging