Shinylock uncatchable Pokemon
pagefaultgames/pokerogue pull request #1252
Opened 2024-05-22 20:13 UTC by TempsRay

* #1248 
* Added more documentation
* Some refactoring

2024-05-23 00:21 UTC, Xavion3 requested changes

2024-05-23 00:21 UTC, Xavion3 commented on src/field/pokemon.ts
> +    } else if (rand > 1) {
Don't change variant chances.

2024-05-23 08:53 UTC, CodeTappert commented on src/field/pokemon.ts
> +    if (!this.isPlayer() && this.hasTrainer()) {
Doesnt this block the rival from having the Shiny Mega Rayquaza? Which is on purpose?

2024-05-23 13:22 UTC, TempsRay commented on src/field/pokemon.ts
> +    if (!this.isPlayer() && this.hasTrainer()) {
Nah, the rival's shiny is manually set without using the `trySetShiny` function. See [here](https://github.com/pagefaultgames/pokerogue/blob/main/src/data/trainer-config.ts#L1007)

2024-05-23 13:23 UTC, TempsRay commented on src/field/pokemon.ts
> +    }
Talked with Xavion offline and this is the one edge case that actually affects players. Currently, a player can find a shiny paradox in classic mode and then just put the save file on pause until they hatch the paradox Pokemon, at which point they will be allowed to catch it. This change makes it so that uncaught shiny paradoxes never even try to generate. Not sure if "put that save file on hold until you hatch it" is something that should be encouraged though

2024-05-23 18:18 UTC, Tsukistar1 commented
> Personally, I think just stop shinies spawning in the end in endless as a first step. I like seeing them occasionally from trainers, but also I feel like the complaints mostly just originate from endless where the shiny rate is so much higher.

Definitely a good first step, though I can confirm that there have been people who have been frustrated by random shiny trainer pokemon as well. It's just that - like you said - shiny rates in Endless are higher, and also people grind out Endless more I think.

2024-05-30 20:07 UTC, molker approved these changes

2024-05-30 20:20 UTC, merged