Luck based encounters
pagefaultgames/pokerogue pull request #1273
Opened 2024-05-23 06:14 UTC by BatCrowP

Increases chance to encounter rarer mons based on party luckValue

2024-05-23 06:22 UTC, BatCrowP commented
Numbers not super important on this, main points that I aimed for with the rough plan was 
1) Minimum encounter rate does not change
2) Max UR encounter rate stays close to 2.5x (arbitrary based on hearing that sam planned on that)
![image](https://github.com/pagefaultgames/pokerogue/assets/169752071/3774ab6c-f8e2-4d77-a632-c2c82e6201e5)
3) Keep Common as most frequently appearing

Below is a quick spreadsheet of the spawning rates with my proposed numbers at 14 and 10 luck as well as the relative increase from the original encounter chance
<img width="745" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/169752071/4ef5657b-08a0-4619-ae9f-07c6803d5da3">

2024-05-23 06:25 UTC, BatCrowP commented
Calculation is done by checking if luckValue is greater than 6, and if so multiplies the tier value by 5.5/luckValue.

2024-05-27 19:27 UTC, molker commented on src/field/arena.ts
> +        } else if (luckValue < 10) {
instead of an empty if result can you combine this with the first one?
`luckValue < 10 && luckValue >= 6` ?

2024-05-27 19:51 UTC, Xavion3 commented on src/modifier/modifier-type.ts
> +
What is actually being changed here?

2024-05-27 19:58 UTC, Xavion3 commented
While the idea of changing rarity is fine, I personally disagree with the scaling here. We generally have tried to have luck produce diminishing returns, this makes low luck irrelevant and makes luck have increasing returns so like 14 luck is significantly more than twice as strong as 7 luck. I feel like we could make this whole thing much cleaner overall.

2024-05-28 00:23 UTC, TempsRay commented on src/modifier/modifier-type.ts
> +
Looks like tabbing

2024-05-28 00:25 UTC, TempsRay commented on src/field/arena.ts
> +        if (luckValue < 6) {
Not sure how I feel about the balance of this. I think ideally either it should scale linearly or in such a way that there's diminishing returns for higher levels.

It also seems like it isn't too simple to explain, which I think should be an important factor. My initial thought of `generate the random number from 0 to (512 - luck * 2) for nonboss and 0 to (64 - luck/2) for bosses` for example is a lot simpler and understandable

2024-05-28 15:28 UTC, BatCrowP commented on src/field/arena.ts
> +        if (luckValue < 6) {
I definitely agree that it would be simpler to modify the ceiling but it doesn't give much incentive to actually have any luck at all. At max luck this only ends up increasing UR rarity from 1.56% to 1.75%, any increase is nice but it felt underwhelming looking at the numbers. Below is what the numbers would look like going from live branch to your suggestion. 

The simple equation would probably be for the best but it might be good to rethink the numbers. 
<img width="1109" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/169752071/cc9b1a79-a776-4dcc-8953-9df3234508e3">

2024-05-29 21:04 UTC, Xavion3 commented on src/modifier/modifier-type.ts
> +
Why though? I'm surprised this is even passing eslint since it's making the indentation inconsistent.

2024-06-03 17:27 UTC, brain-frog requested changes
Once comment is addressed and merge conflicts are solved this looks good to me

2024-06-03 17:27 UTC, brain-frog commented on src/field/arena.ts
> +          if (isBoss) {
since the parameter for randSeedInt is also based on `isBoss` can you please make the if statement structure be: 
```
if (isBoss) 
   have a constant for the parameter
   if (luckValue is defined) 
      have a constant for the multiplier to subtract from the parameter defined above

after all if statements 
const tierValue = Utils.randSeedInt(first const - second const)
```

2024-06-05 15:03 UTC, brain-frog commented
closing due to inactivity (but I did implement using your approach)

2024-06-05 15:03 UTC, closed without merging