useMove + pokemon affix localization
pagefaultgames/pokerogue pull request #1276
Opened 2024-05-23 08:08 UTC by laeticiapierre

Issue #1274

EDIT 05/27: 
ENG
<img width="500" alt="Capture d’écran 2024-05-27 à 17 13 48" src="https://github.com/pagefaultgames/pokerogue/assets/17924672/3c6e82f6-ab7b-4d55-97be-00a301567174">
<img width="500" alt="Capture d’écran 2024-05-27 à 17 13 54" src="https://github.com/pagefaultgames/pokerogue/assets/17924672/9c2fcc48-5154-44d1-914d-aa8a8dd9d45b">

FR
<img width="500" alt="Capture d’écran 2024-05-27 à 17 12 53" src="https://github.com/pagefaultgames/pokerogue/assets/17924672/5e9f2f2e-2335-4eda-b7ac-ec7df651c86a">
<img width="500" alt="Capture d’écran 2024-05-27 à 17 13 01" src="https://github.com/pagefaultgames/pokerogue/assets/17924672/8f905f83-0eee-4db3-861a-53440b51b6e4">

2024-05-23 08:13 UTC, Greenlamp2 approved these changes

2024-05-23 08:48 UTC, CodeTappert commented
Could you please make it so that both of them could be suffixes as well?

German for example uses: "Glumanda (Wild)" instead of "Wildes Glumanda" (Wild is the "prefix").

Same with the foe one

2024-05-23 09:04 UTC, laeticiapierre commented
> Could you please make it so that both of them could be suffixes as well?
> 
> German for example uses: "Glumanda (Wild)" instead of "Wildes Glumanda" (Wild is the "prefix").
> 
> Same with the foe one

I've put `pokemonPrefix` as a parameter name because it's the method name but you can place it wherever you like, feel free to check the french file, it's used that way

2024-05-23 09:05 UTC, Dakurei commented
As it's not at the beginning of a sentence in French, it's a suffix rather than a prefix, so there's no need to capitalize it.
Besides being ugly, it's incorrect 😅

2024-05-23 09:14 UTC, CodeTappert commented
> > Could you please make it so that both of them could be suffixes as well?
> > German for example uses: "Glumanda (Wild)" instead of "Wildes Glumanda" (Wild is the "prefix").
> > Same with the foe one
> 
> I've put `pokemonPrefix` as a parameter name because it's the method name but you can place it wherever you like, feel free to check the french file, it's used that way

Yeah i saw that. So pokemonPrefix is either wildPrefix or foePrefix? Am i understanding this correctly?

2024-05-23 09:15 UTC, laeticiapierre commented
> As it's not at the beginning of a sentence in French, it's a suffix rather than a prefix, so there's no need to capitalize it. Besides being ugly, it's incorrect 😅

We could easily fix this by updating the french file and replacing `Sauvage` with `sauvage`(same for `Ennemi`) but traduction is not done everywhere at the moment, there are some places left where we would have "sauvage Tortank [...]" as a sentence and I think it's better to have a capitalized letter at the start of it

2024-05-23 09:18 UTC, CodeTappert commented
German translation. Source (Pokemon Scarlet)
```
  "wildPokemonPrefix": "(wild)",
  "foePokemonPrefix": "(Gegner)",
  "useMove": "{{pokemonName}} {{pokemonPrefix}} setzt {{moveName}} ein!"
```

2024-05-23 09:22 UTC, CodeTappert commented
> German translation. Source (Pokemon Scarlet)
> 
> ```
>   "wildPokemonPrefix": " (wild)",
>   "foePokemonPrefix": " (Gegner)",
>   "useMove": "{{pokemonName}}{{pokemonPrefix}} setzt {{moveName}} ein!"
> ```

Just quick update. I updated this again just now so it works even when the prefix is set to an empty string (which i assume is done for our own Pokemon?). 

Just added a space in the prefix itself but removed the one in the useMove string

2024-05-27 05:27 UTC, wuzhaoqi1015 commented
Has this issue been merged?

2024-05-27 07:02 UTC, CodeTappert commented
> Has this issue been merged?

Not yet. The creator of the issue has not adressed the latest comments or made changes suggestet. It is a "Draft". So we wait

2024-05-28 09:17 UTC, CodeTappert commented
Could you please provide screenshots of the german version? Would love to see if it looks correct

2024-05-28 11:00 UTC, laeticiapierre commented
> Could you please provide screenshots of the german version? Would love to see if it looks correct

<img width="500" alt="Capture d’écran 2024-05-28 à 12 56 10" src="https://github.com/pagefaultgames/pokerogue/assets/17924672/c0034dfb-d350-4812-b628-01a29d11890f">
<img width="500" alt="Capture d’écran 2024-05-28 à 12 56 58" src="https://github.com/pagefaultgames/pokerogue/assets/17924672/1ce87899-2a66-4931-8fc9-54d1812e6ce8">

2024-05-28 11:09 UTC, CodeTappert commented
> > Could you please provide screenshots of the german version? Would love to see if it looks correct
> 
> <img width="500" alt="Capture d’écran 2024-05-28 à 12 56 10" src="https://github.com/pagefaultgames/pokerogue/assets/17924672/c0034dfb-d350-4812-b628-01a29d11890f">
> <img width="500" alt="Capture d’écran 2024-05-28 à 12 56 58" src="https://github.com/pagefaultgames/pokerogue/assets/17924672/1ce87899-2a66-4931-8fc9-54d1812e6ce8">
> 
> 

Thank. You. Looks very good!

2024-05-30 15:53 UTC, molker commented
Sorry this is a product of the delay in further review but since korean is now in locales can you please add that to this PR

2024-05-30 15:55 UTC, molker requested changes
Looks good, a few things to fix before we can approve

2024-05-30 15:55 UTC, molker commented on src/messages.ts
> +export function getPokemonNameWithAffix(pokemon: Pokemon): string {
please add documentation for this and the above method, reference `docs/comments.md` for a guide

2024-05-31 13:25 UTC, laeticiapierre commented on src/messages.ts
> +export function getPokemonNameWithAffix(pokemon: Pokemon): string {
Done 👍🏻 (and korean)

2024-05-31 13:38 UTC, returntoice requested changes

2024-05-31 13:38 UTC, returntoice commented on src/locales/ko/battle.ts
> +  "useMove": "{{pokemonNameWithAffix}} used {{moveName}}!"
```suggestion
  "wildPokemonWithAffix": "야생 {{pokemonName}}",
  "foePokemonWithAffix": "상대 {{pokemonName}}",
  "useMove": "{{pokemonNameWithAffix}}의 {{moveName}}!"
```
translated by the official translation(VIII, IX gen)

2024-05-31 14:00 UTC, returntoice approved these changes

2024-06-04 20:32 UTC, flx-sta commented
@laeticiapierre please resolve the merge conflicts

2024-06-06 13:35 UTC, bennybroseph approved these changes

2024-06-06 13:36 UTC, merged