WIP: Adding the option to have named trainers be able to have a double battle together
pagefaultgames/pokerogue pull request #1318
Opened 2024-05-24 13:17 UTC by CodeTappert

## What is the purpose of this?
- Honestly it started with the wish to have Tate and Liza to be able to fight together instead of Solo.
- Now every named trainer (gym leader, elite 4, champ) could partner up with any other
- For example red and blue
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/ee6f493b-0c9c-4d28-bf2f-ede465b2da4b)

## What is already done?
- Ability to pair up any two trainer types
- Ability to set a double title (see image above) (can be localized)
- Ability to set Double name (can be localized)
## What does still need to be added?
- Ability to mix their species togehter
- (Dont quite know how it works for normal doubles like a Ace-Duo? Do they have a split pokemon pool or do the trainers have their own?)

Help would be appriciated!

2024-05-24 15:54 UTC, CodeTappert commented
Added "Alder & Iris", "Blue & Red", "Steven & Wallice", "Tate & Liza" as teams for now.

Next step will be doing/adding dialogue

2024-05-24 20:33 UTC, CodeTappert commented
This is ready for review/merge by a dev!

2024-05-25 11:10 UTC, bennybroseph requested changes
This is very cool, but I have to ask for this change.

2024-05-25 11:10 UTC, bennybroseph commented on src/locales/en/trainers.ts
> +  "iris_alder_double": "Iris & Alder",
is there *any* way we can make these one entry per double battle? It seems very strange to need to provide the exact same translation twice but with reversed names.

2024-05-25 12:02 UTC, CodeTappert commented on src/locales/en/trainers.ts
> +  "iris_alder_double": "Iris & Alder",
> is there _any_ way we can make these one entry per double battle? It seems very strange to need to provide the exact same translation twice but with reversed names.

Sure. This is done ON purpose. 

If we just set the same name in the
`setHasDouble("tate_liza_double")` for both of them they would use the same locailzation string.

But i had done this with a reason. So first of all the Nametag is orderd like the charakter sprites.

And also that each unique parining (tate & liza vs liza & tate) could have their unique dialogue that starts with the person that is on the left (from player perspective)

I would really like to leave it that way since it is intentional

2024-05-25 12:47 UTC, bennybroseph approved these changes

2024-05-25 12:47 UTC, merged