Fix Illuminate
pagefaultgames/pokerogue pull request #1363
Opened 2024-05-25 10:49 UTC by JakubHanko

After SV, the Illuminate ability was changed to also prevent other Pokémon from lowering the accuracy stat stage of the Pokémon with this Ability, and also ignores the target's evasion stages. 

The change is just adding of IgnoreOpponentEvasionAbAttr attr and update of misleading docs.

2024-05-25 10:51 UTC, bennybroseph commented
I know this wasn't coded by you, but this attribute uses the exact same value. Can we test this to make sure it isn't resetting Evasion?

2024-05-25 13:39 UTC, JakubHanko commented
> I know this wasn't coded by you, but this attribute uses the exact same value. Can we test this to make sure it isn't resetting Evasion?

I am not sure I understand the question correctly. The newly added attribute is working with Utils.IntegerHolder and it is nowhere near any setting of battle stats so it shouldn't be able to do any permanent damage.

Or is your question alluding to a video demonstrating that the evasion is not reset?

2024-05-25 14:34 UTC, bennybroseph requested changes

2024-05-25 14:34 UTC, bennybroseph commented on src/data/ability.ts
>    apply(pokemon: Pokemon, passive: boolean, cancelled: Utils.BooleanHolder, args: any[]) {
It's right there

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/727111ba-ecdc-48df-b61e-f4d1ae3fa23c)

2024-05-25 14:49 UTC, JakubHanko commented on src/data/ability.ts
>    apply(pokemon: Pokemon, passive: boolean, cancelled: Utils.BooleanHolder, args: any[]) {
I can see that it's right there but I still don't understand what am I supposed to do.

The attribute is applied only in MoveEffect#hitCheck and yes, the evasion is "reset" but only in the scope of that function (since we are not working directly with the battle stat but only with the IntegerHolder).

2024-05-25 15:48 UTC, bennybroseph commented on src/data/ability.ts
>    apply(pokemon: Pokemon, passive: boolean, cancelled: Utils.BooleanHolder, args: any[]) {
We just had this conversation, what's the difference?

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/c8fbbe2f-cde7-4c9a-8d73-0b14d0da157c)

2024-05-25 16:07 UTC, JakubHanko commented on src/data/ability.ts
>    apply(pokemon: Pokemon, passive: boolean, cancelled: Utils.BooleanHolder, args: any[]) {
None, in the Unaware PR the code was working as well (same reasons as I keep reiterating here). When I closed the PR, I was AFK and I got convinced that I was wrong.

Moreover, I didn't reopen the Unaware PR because I found the code unnecessarily bloated. In the end, my changes added nothing relevant because the speed was already being ignored with how the code is structured.

2024-05-25 19:01 UTC, bennybroseph commented on src/data/ability.ts
>    apply(pokemon: Pokemon, passive: boolean, cancelled: Utils.BooleanHolder, args: any[]) {
Understood, closing this as well

2024-05-25 19:01 UTC, closed without merging

2024-05-26 07:42 UTC, JakubHanko commented on src/data/ability.ts
>    apply(pokemon: Pokemon, passive: boolean, cancelled: Utils.BooleanHolder, args: any[]) {
Not sure why. The "understood" is clearly misplaced.