Implement Spectral Thief
pagefaultgames/pokerogue pull request #1365
Opened 2024-05-25 11:38 UTC by jaimefd

Implemented the move Spectral Thief.

It steals positive stat boosts from the target before hitting them, as described [here](https://bulbapedia.bulbagarden.net/wiki/Spectral_Thief_(move)#Effect). Abilities that protect or alter stat changes only work on the attacker, not on the defender, even abilities that can't be ignored like Full Metal Body don't stop it, as described in its own [page](https://bulbapedia.bulbagarden.net/wiki/Full_Metal_Body_(Ability)#Effect)

Here's an example:
https://github.com/pagefaultgames/pokerogue/assets/22176793/4eeadf8d-b60d-4592-ae14-d718a4569da0

If the move fails, like the target being immune, stats are not stolen, as expected:
https://github.com/pagefaultgames/pokerogue/assets/22176793/8ae52492-b5a5-4706-ab75-b234d60a8b52

And as mentioned above, abilities are still applied for the attacker, in this case we have both Simple and Contrary:
https://github.com/pagefaultgames/pokerogue/assets/22176793/30a8b8c1-ac31-4dd1-8a6f-2e05c1fd2a7b

2024-05-25 13:38 UTC, jaimefd commented
Attack boosts were being applied after the move, when they should be applied before, the last commit fixed that:

https://github.com/pagefaultgames/pokerogue/assets/22176793/a996f89d-b5e2-4876-88bf-880facf7c945

2024-05-25 14:54 UTC, XGSleepWalker requested changes

2024-05-25 14:54 UTC, XGSleepWalker commented on src/data/move.ts
> +    if (target.summonData.battleStats.find((stat) => stat > 0)) {
Can you rework this logic to iterate only a single time for battleStats?

2024-05-25 16:50 UTC, jaimefd commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
Done

2024-05-25 17:07 UTC, jaimefd commented on src/data/move.ts
> +    if (target.summonData.battleStats.find((stat) => stat > 0)) {
Done, I reduced it from 4 iterations to just 2. I believe we should still iterate at least twice, once to take the stats from the target, and the second time to apply them to the user.

This is because StatChangePhase can only increase stats by the same amount, so if the target has different levels of boost for different stats, we need multiple phases. And I don't think it's a good idea to start any boost phase before removing all stats, in case we ever have abilities that react to enemy stat boosts.

2024-05-25 17:09 UTC, jaimefd commented
Tested it and everything still works fine after the changes

2024-08-07 19:30 UTC, flx-sta commented
ℹ️ PR considered stale. No actions in the last 30 days.

-----

❗ Feel free to ping me/comment if you want to re-open it

2024-08-07 19:30 UTC, closed without merging