Classic Turbo game mode
pagefaultgames/pokerogue pull request #1375
Opened 2024-05-25 17:03 UTC by arperry

This adds a shorter version of Classic that skips half of the levels but never any fixed fights or bosses.

While you now heal every five fights instead of ten, the game ends up more difficult, largely because you receive 44% of the usual number of shops (4 out of every 5 instead of 9 of 10). To counterbalance this, rerolls have been made much less expensive. You end up with much less money than usual, so that change isn't nearly enough to bring it to parity. Still, it's probably best that this game mode errs on the side of too difficult rather than too easy.

There is a single known issue with the game mode: trainers fought immediately after a biome change do not appear on screen. This is guaranteed to happen at wave 182. It is a cosmetic bug that has no gameplay effects.

This also fixes an issue with the animation for Psychic.

2024-05-25 19:53 UTC, bennybroseph requested changes

2024-05-25 19:53 UTC, bennybroseph commented on public/battle-anims/psychic.json
> +  "graphic": "PRAS- Psychic BG",
What's this for

2024-05-25 19:53 UTC, bennybroseph commented on src/phases.ts
> +    return cost;
Should we be making everything cheaper, not just rerolls?

2024-05-25 19:53 UTC, bennybroseph commented on src/game-mode.ts
> +      return waveIndex >= 200;
shouldn't this just fallthrough to match classic?

2024-05-25 19:53 UTC, bennybroseph commented on src/battle-scene.ts
> +    }
can we get some comments in here? Needing this many nested conditionals doesn't seem right

2024-05-25 19:54 UTC, bennybroseph commented
Could we get some screenshots or videos of what this looks like? Also, how was the reward system changed for this mode since it's way faster than Classic? Also, what are the unlock conditions for the mode?

2024-05-25 20:32 UTC, arperry commented on public/battle-anims/psychic.json
> +  "graphic": "PRAS- Psychic BG",
There is no "PsychicBG" file; this fixes a typo.

2024-05-25 20:33 UTC, arperry commented on src/game-mode.ts
> +      return waveIndex >= 200;
If Classic is fine with the >= logic, then that's OK. Otherwise, as Turbo skips 191, the logic to detect the final biome fails. I figured this was less intrusive.

2024-05-25 20:37 UTC, bennybroseph commented on public/battle-anims/psychic.json
> +  "graphic": "PRAS- Psychic BG",
let's make this a separate pull request

2024-05-25 20:38 UTC, arperry commented on src/battle-scene.ts
> +    }
Added.

2024-05-25 20:39 UTC, bennybroseph commented on src/game-mode.ts
> +      return waveIndex >= 200;
What floor does Turbo end on if not 200?

2024-05-25 20:47 UTC, arperry commented
> Could we get some screenshots or videos of what this looks like?

I'm afraid it's not visually much different from Classic mode. Here's the menu:
![image](https://github.com/pagefaultgames/pokerogue/assets/9615035/d9e07669-5844-458f-98b3-7bb6611c1d52)

Here's a GIF of the first few waves (1, 4, 5, 8 - the next would be 10).

![Recording 2024-05-25 at 15 44 03](https://github.com/pagefaultgames/pokerogue/assets/9615035/1b27dab6-29b7-456c-91b7-88a335cd5467)


> Also, how was the reward system changed for this mode since it's way faster than Classic?

Experience is increased by a factor of 1.5. Because this mode is trainer-heavy, it gives more experience overall, but some of that will usually be lost to fainted Pokémon (more than usual, I mean).

Rerolls cost 25% as much. Other item costs are unchanged. Because heals are more frequent, you don't need to purchase items much before the E4, but cash is noticeably tighter at that point. The aim is to roughly match Classic in difficulty, but it errs on the side of being a bit harder.

> Also, what are the unlock conditions for the mode?

Because you don't get a mode select until you unlock Endless, it currently shares the Endless unlock condition: clear Classic mode.

2024-05-25 20:50 UTC, arperry commented on src/phases.ts
> +    return cost;
Possibly, but as a starting point for this mode, I didn't want to overcorrect and make it easier than Classic. The reroll discount allows you to see more items, and you shouldn't need to heal quite as frequently as in Classic, so if the shop were discounted, it would probably make sense to discount it about 20% instead of the 75% that we apply here.

2024-05-25 20:51 UTC, bennybroseph commented
We'd probably want some alternate unlock condition for this. Also, I should have been more clear, I meant the reward system of gacha tickets that you get for E4, Champion, and Eternatus

2024-05-25 20:52 UTC, arperry commented on src/game-mode.ts
> +      return waveIndex >= 200;
It ends on 200, but the logic to detect end biome is waveIndex + 9, and we skip 191.

2024-05-25 20:54 UTC, arperry commented on public/battle-anims/psychic.json
> +  "graphic": "PRAS- Psychic BG",
Reverted.

2024-05-25 20:55 UTC, arperry commented
> We'd probably want some alternate unlock condition for this.

I'm indifferent to the unlock condition, and I don't have any good ideas for alternate conditions. Do you have any suggestions?

> Also, I should have been more clear, I meant the reward system of gacha tickets that you get for E4, Champion, and Eternatus

This is treated identically to Classic in that regard. If you've beaten a Gym Leader in Classic, you'll get the degraded reward in Turbo, and vice versa.

2024-05-27 21:42 UTC, TempsRay commented
I think I'm personally more in favor of a new game mode that's 100 floors long but have the trainer battles rebalanced for that mode, like gym leaders on X0 floors so there's exactly 8, then having the E4 and champ in floors 90-100

2024-05-28 16:32 UTC, Xavion3 commented
I feel like this could fall under my challenges PR, rather than being another game mode.

2024-06-04 02:18 UTC, Tempo-anon commented
We really appreciate the time and effort you've spent in making this new game mode but this is something that can be bundled in Xavion's challenges in the future. You're welcome to submit something as a shorter faster version of Classic mode using that framework then.

2024-06-04 02:18 UTC, closed without merging

2024-06-04 04:48 UTC, arperry commented
No worries. Thanks for following up.

On Mon, Jun 3, 2024, 9:18 PM Tempoanon ***@***.***> wrote:

> We really appreciate the time and effort you've spent in making this new
> game mode but this is something that can be bundled in Xavion's challenges
> in the future. You're welcome to submit something as a shorter faster
> version of Classic mode using that framework then.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pagefaultgames/pokerogue/pull/1375#issuecomment-2146442975>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJLNO76H4I6VLYEEZUFHF3ZFUPYRAVCNFSM6AAAAABIJBDF3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBWGQ2DEOJXGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>