Added Camper/Picknicker trainer class
pagefaultgames/pokerogue pull request #1406
Opened 2024-05-26 20:03 UTC by Alekemon

Added both in one PR since Camper is the male variant and Picknicker is the female variant, I'll upload the other trainer classes soon

2024-05-27 14:51 UTC, CodeTappert commented
German:

Camper: "Camper"
Picnicker: "Picknickerin"

2024-06-03 15:00 UTC, bennybroseph commented
Is this still being worked on?

2024-06-06 00:07 UTC, Alekemon commented
> Is this still being worked on?

It is, just that I didn't have enough time to do so, I'll continue starting from tomorrow

2024-06-08 19:02 UTC, Alekemon commented
@bennybroseph do you agree with the chosen dialogue or would you like to propose better lines like with the other 2 trainer class PRs?

2024-06-11 16:56 UTC, Alekemon commented
I removed Town from the possible biomes since it wouldn't be able to spawn

2024-06-13 22:40 UTC, bennybroseph requested changes

2024-06-13 22:40 UTC, bennybroseph commented on src/locales/de/dialogue.ts
> +      3: "No, wrong!"
I assume these are from official sources because I recognize most of them. They seem out of place here though so we should touch them up a bit or grab them from a different source. My suggestions:

"I saw your feet from the grass!" -> "Hey, watch it! You almost stepped on my sleeping bag!"
"I hid because the people on the bridge frightened me." -> "Oh come on! Our battle ruined my tent..."

"Aww, darn..." -> "Please don't tell my girlfriend..."

"I've been out at a Pokémon gym a few times. But I always lose." -> "Oh! Another trainer! You look gentle, so I think I can beat you."
"Ohh! After all my training!" -> "Darn, even stronger than the green-haired trainer from earlier..."

"You look gentle, so I think I can beat you." -> "I'm a cool girl. I've got a boyfriend!"
"No, wrong!" -> "Please don't tell my boyfriend..."

2024-06-14 23:39 UTC, Alekemon commented
Ok I'm done adding the requested dialogues, thanks!

2024-06-17 18:36 UTC, CodeTappert commented
Pleae resolve your conflicts

2024-06-17 18:52 UTC, Alekemon commented
> Pleae resolve your conflicts

Done

2024-06-17 19:01 UTC, CodeTappert approved these changes
Looks good to me

2024-07-10 18:08 UTC, CodeTappert commented
Please resolve conflicts

2024-07-30 03:22 UTC, Tempo-anon commented
Closing due to merge conflicts and age

2024-07-30 03:22 UTC, closed without merging