Added Firebreather trainer class
pagefaultgames/pokerogue pull request #1409
Opened 2024-05-26 20:19 UTC by Alekemon

2nd out of the 4 trainer class pull requests. This trainer class uses Pokémon who have Smog in their learnset

2024-05-27 08:35 UTC, bennybroseph commented
Can we get a screenshot or video showing this was tested?

2024-05-27 14:38 UTC, Alekemon commented
> Can we get a screenshot or video showing this was tested?

![image](https://github.com/pagefaultgames/pokerogue/assets/42167718/b380f45d-4dee-4e7d-83e4-50d556a4705c)

2024-05-27 14:45 UTC, CodeTappert commented
German: "Feuerspucker"

2024-05-29 23:47 UTC, bennybroseph commented
Does this have dialogue?

2024-05-31 00:45 UTC, Alekemon commented
> Does this have dialogue?

I forgot to re-add dialogue. I'll mark this as a draft and add it tomorrow

2024-05-31 09:58 UTC, Alekemon commented
Ok I re-added dialogue here, I'll do the same with the other PRs

2024-05-31 18:02 UTC, bennybroseph requested changes

2024-05-31 18:02 UTC, bennybroseph commented on src/locales/de/dialogue.ts
> +      2: "I flamed out.",
I couldn't find a source for this:

> If we only had it warmer.
> I flamed out.

Let's use this instead:

> I burned down to ashes...
> Yow! That's hot!

2024-05-31 18:30 UTC, Alekemon commented
Ok, I finished adding the requested dialogue lines. Thanks!

2024-05-31 18:33 UTC, bennybroseph approved these changes

2024-05-31 18:43 UTC, bennybroseph requested changes

2024-05-31 18:43 UTC, bennybroseph commented on src/data/trainer-config.ts
> +    .setSpeciesFilter(s => !!s.getLevelMoves().find(plm => plm[1] === Moves.SMOG)),
would like them to also pick some fire pokemon, not just smog pokemon

2024-05-31 19:04 UTC, bennybroseph approved these changes

2024-05-31 19:05 UTC, merged