Added Sailor trainer class
pagefaultgames/pokerogue pull request #1411
Opened 2024-05-26 20:27 UTC by Alekemon

3rd out of the 4 trainer class PRs, this trainer uses Water and Fighting type Pokemon

2024-05-27 14:46 UTC, CodeTappert commented
German: "Matrose"

2024-06-03 15:01 UTC, bennybroseph commented
Is dialogue being added for this as well?

2024-06-06 10:24 UTC, Alekemon commented
> Is dialogue being added for this as well?

I added some lines from the sailors in Kanto games

2024-06-06 12:17 UTC, Alekemon commented
![Captura de pantalla 2024-06-06 141530](https://github.com/pagefaultgames/pokerogue/assets/42167718/517572ec-0047-46a3-b540-df1043762636)

Screenshot

2024-06-06 15:33 UTC, Alekemon commented
![Captura de pantalla 2024-06-06 173055](https://github.com/pagefaultgames/pokerogue/assets/42167718/cff634dd-5f25-4c30-aa5b-e5bd0df52916)

Properly centered screenshot

2024-06-06 16:28 UTC, bennybroseph requested changes

2024-06-06 16:28 UTC, bennybroseph commented on public/images/sailor.png
why is there two

2024-06-06 16:30 UTC, Alekemon commented on public/images/sailor.png
First screenshot showed an earlier build of the PR which was readjusted in the second screenshot, I deleted the first screenshot and left the final one

2024-06-06 16:33 UTC, Alekemon commented on public/images/sailor.png
Oh you didn't mean the screenshot, let me take a look

2024-06-06 16:42 UTC, bennybroseph requested changes

2024-06-06 16:42 UTC, bennybroseph commented on src/locales/de/dialogue.ts
> +      3: "I was just careless!"
I think it's supposed to be "Come on then!" with no comma. Same with "Ahoy there!"

Would also like:
- "I was just careless!" changed to "I think it's me that's seasick..."

2024-06-06 16:48 UTC, Alekemon commented on src/locales/de/dialogue.ts
> +      3: "I was just careless!"
Ok, I applied these changes, thanks for clarifying!

2024-06-06 16:52 UTC, bennybroseph commented
what are you using to version these? This seems crazy 
![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/cb4762b9-47ab-469a-8ce2-0ad6e73e4e47)

2024-06-06 16:53 UTC, Alekemon commented
> what are you using to version these? This seems crazy ![image](https://private-user-images.githubusercontent.com/13838608/337360132-cb4762b9-47ab-469a-8ce2-0ad6e73e4e47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTMwNjQsIm5iZiI6MTcxNzY5Mjc2NCwicGF0aCI6Ii8xMzgzODYwOC8zMzczNjAxMzItY2I0NzYyYjktNDdhYi00NjlhLThjZTItMGFkNmU3M2U0ZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE2NTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYWM3MzViMTUxZWExYjJkYTdkNmY5NTZhYTFhMjU1ZTc2YTNmZDk3ZjgyNGMyMzhlZjZhZDBmZGNmNjRkOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5alaHiye6PmW4D6Sc6D2kJy_bSHWJCK-tDlvzBX73pA)

I just copy and paste the string over and over for each language available

2024-06-06 16:54 UTC, bennybroseph commented
you don't have to make a commit for each file brother

2024-06-06 16:55 UTC, bennybroseph commented
Same for these, idk how that happened
![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/7c8750f1-6235-4c2a-9c51-f033e5533794)

2024-06-06 16:55 UTC, bennybroseph approved these changes

2024-06-06 16:55 UTC, Alekemon commented
> you don't have to make a commit for each file brother

Ok, I'll note that. Should I revert those commits?

2024-06-06 16:55 UTC, merged