Implement Steely Spirit
pagefaultgames/pokerogue pull request #1439
Opened 2024-05-27 15:41 UTC by hayuna

Demo is in progress...

2024-05-27 16:03 UTC, hayuna commented
Implementation:

- [x]  Both pokemon have ability (attack should be multiply by 2.25
- [x]  Attacker has ability (attack should be multiply by 1.5)
- [ ]  Ally of attacker has ability (attack should be multiply by 1.5)

2024-05-30 04:50 UTC, td76099 requested changes
Got a couple more things to figure out - mainly just how to cleanly check an ally's abilities for a damage boost and simplifying the logic in the new attribute itself by adding a conditional where it gets registered and simplifying logic in the attribute.

2024-05-30 04:50 UTC, td76099 commented on src/data/ability.ts
> +    if (isSteelMove) {
You should look into using the .condition instead of placing it inside of `applyPreAttack`. You can see an example of how to implement it into your class [here](https://github.com/pagefaultgames/pokerogue/blob/795c50425fe8159a7cfa56ad898d883e3075184a/src/data/ability.ts#L1049) and an example of it being used [here](https://github.com/pagefaultgames/pokerogue/blob/795c50425fe8159a7cfa56ad898d883e3075184a/src/data/ability.ts#L3773). It's the standard most abilities use for conditions like this.

2024-05-30 04:50 UTC, td76099 commented on src/data/ability.ts
> +      if (twoPokemonWithAbility) {
Can't you just (roughly) do:
```
power.value *= 1.5 // You only got here because you have this attribute and the move is Steel, no need to check ability
if (pokemon.getAlly().hasAbility(Abilities.STEELY_SPIRIT) power.value *= 1.5 // Is important to check ally tho
return true;
```
If self has it, it's 1.5. If ally has it, it's 1.5. If both have it, it's 1.5*1.5.

2024-05-30 04:50 UTC, td76099 commented on src/field/pokemon.ts
> +        // If ally has ability with attribute SteelySpiritAbAttr, steel moves are boosted.
There are very little abilities implemented that affect just your ally, so there isn't much of a precedent set, but I can imagine that every single one can get its own clause like this. I would recommend looking at something like `Lightning Rod` or `Storm Drain` because they do something similar (check someone else's ability on their own turn) but not by individually checking each AbAttr.

2024-05-30 09:10 UTC, hayuna commented on src/field/pokemon.ts
> +        // If ally has ability with attribute SteelySpiritAbAttr, steel moves are boosted.
Thanks for the feedback ❤️ Will take a look and try to be better contributor 😊

2024-06-01 13:16 UTC, hayuna commented on src/field/pokemon.ts
> +        // If ally has ability with attribute SteelySpiritAbAttr, steel moves are boosted.
@td76099 Im afraid I cannot base on Lightning Rod or Storm Drain, this ability is raising move power based on ally ability, I tied to move it into phases file but its increasing power forever, then tried to use some Battletags, but seems like its overthinking.

2024-06-27 20:52 UTC, torranx commented
@hayuna , do you have plans to update this PR? if not, ill create a new one instead

2024-06-27 20:56 UTC, hayuna commented
@torranx go ahead. Lastly I have less time to contribute

2024-07-02 12:53 UTC, hayuna commented
New implementation here

https://github.com/pagefaultgames/pokerogue/pull/2749

2024-07-02 12:53 UTC, closed without merging