Bugfix: Abilities check final move type instead of default move type
pagefaultgames/pokerogue pull request #1440
Opened 2024-05-27 15:44 UTC by td76099

Updates abilities to no longer use `PokemonMove` but instead `Move` so that they can accurately track the type of a move in case it gets updated

That same `move` object is maintained through all of `MoveEffectPhase` in `phases.ts` and in all of `.apply()` to the `Pokemon` object in `pokemon.ts`

Has only been lightly tested to ensure it functions, but is this closer to what you were thinking? I could technically move
```   
    applyMoveAttrs(VariableMoveTypeAttr, source, this, move);
    applyPreAttackAbAttrs(MoveTypeChangeAttr, source, this, move, typeChangeMovePowerMultiplier);
```
outside of `pokemon.ts` before `hitResult`. @bennybroseph

2024-05-29 13:39 UTC, td76099 commented
@Madmadness65 @molker was hoping to get confirmation that a rework like this for passing the move around (instead of move id to look up the move every time) would be approved so I can start testing a bunch of stuff! Fixes a bug that happens more often than it should.

2024-06-01 17:20 UTC, td76099 commented
Testing complete! Ready for review.

2024-06-03 18:27 UTC, dirtydom236 commented
Hello, just did a bit of testing for this pr and I noticed that after using a refrigerated tackle once on the opponent, it straight up turns tackle into an ice move universally. I made sure to use Amaura so that there was no refrigerate override active, and I can confirm that this does not happen on main (third screenshot). 
![image](https://github.com/pagefaultgames/pokerogue/assets/130926160/852d6479-d418-45c1-8417-4efbdda18816)
![image](https://github.com/pagefaultgames/pokerogue/assets/130926160/576510af-0beb-4155-bb97-21da6af75996)
![image](https://github.com/pagefaultgames/pokerogue/assets/130926160/59729126-7426-413c-bd63-d28501feac0e)


https://github.com/pagefaultgames/pokerogue/assets/130926160/90b516e1-ba29-4316-89f2-d1e8bbbc3d16

2024-06-03 19:26 UTC, td76099 commented
Really good catch - I'll take a look at getting that fixed!

2024-06-04 19:04 UTC, td76099 commented
Alright I have pushed a fix for that issue - thanks for finding that issue! If you test some more and encounter anything else I'll take ASAP @dirtydom236 

https://github.com/pagefaultgames/pokerogue/assets/85713900/6a2d4e98-000c-43d8-9742-0854f100cbfb

2024-06-05 14:17 UTC, OrangeRed requested changes

2024-06-05 14:17 UTC, OrangeRed commented on src/field/pokemon.ts
> +        const typeBoost = source.findTag(t => t instanceof TypeBoostTag && (t as TypeBoostTag).boostedType === move.type) as TypeBoostTag;
Can you remove this type assertion here? `t instanceof TypeBoostTag && t.boostedType === move.type` 
Typescript is smart enough to know that t has type `TypeBoostTag` after you do instanceof

2024-06-05 14:17 UTC, OrangeRed commented on src/phases.ts
> +                      && !(attr as MoveEffectAttr).selfTarget && (!attr.firstHitOnly || firstHit), user, target, move).then(() => {
Can you remove the type assertions here as well?

2024-06-05 14:17 UTC, OrangeRed commented on src/phases.ts
> +          user, null, move);
Here too

2024-06-06 03:08 UTC, td76099 commented on src/field/pokemon.ts
> +        const typeBoost = source.findTag(t => t instanceof TypeBoostTag && (t as TypeBoostTag).boostedType === move.type) as TypeBoostTag;
Removed it

2024-06-06 03:09 UTC, td76099 commented on src/phases.ts
> +                      && !(attr as MoveEffectAttr).selfTarget && (!attr.firstHitOnly || firstHit), user, target, move).then(() => {
I am afraid to touch anything in `phases.ts`, especially that insane set of logic. Regardless, I have removed it.

2024-06-06 03:09 UTC, td76099 commented on src/phases.ts
> +          user, null, move);
same as others

2024-06-06 03:10 UTC, td76099 commented
@OrangeRed Update those things and added some docs for `PokemonMove` class as discussed in Discord

Obviously tested to make sure everything still worked afterwards lol

2024-06-06 03:23 UTC, OrangeRed approved these changes
I think it looks good. Get one more set of eyes on it though

2024-06-07 15:52 UTC, star-krieg commented
Tested this PR for a specific case that I read before in endless grinding chat on Discord.
Mentioning it here as well since it wasn't mentioned here.

Scrappy Slither Wing hits Wonder Guard Pokemon even if the Slither Wing had its ability overwritten with Entrainment - Normalize (Dark/Ghost and Normal/Ghost will usually die to Fighting moves enabled by Scrappy). Since Normalize would turn all of Slither Wing's moves to Normal, a Dark/Ghost Wonder Guard 'mon shouldn't be hit anymore. I overrode Slither Wing's moves to Close Combat/Focus Punch.

Here is a video of that interaction on the current version of the game:

https://github.com/pagefaultgames/pokerogue/assets/113486223/7f9fcb05-328c-4a62-9cce-d07978436c62

This is a video of the same interaction using this PR:

https://github.com/pagefaultgames/pokerogue/assets/113486223/d0ddb703-c2b5-4ef7-a4ab-1d866bc6c1b7

2024-06-07 20:57 UTC, brain-frog approved these changes
thanks for all the edits! great work

2024-06-07 20:57 UTC, merged