Voucher and Wide Lens item table Changes
pagefaultgames/pokerogue pull request #1472
Opened 2024-05-28 04:13 UTC by damocleas

- Wide Lens moved from Rogue -> Ultra Tier, same weight
- Voucher moved from Ultra -> Great Tier, same weight
- Voucher Plus moved from Master -> Rogue Tier, with weight starting at 9 -> 6 and decreasing with each reroll with 3 -> 2
- Voucher Premium added to Master (based on suggestion from Madmadness) with same weight as new Voucher Plus, and disabled in Endless / Endless Spliced

2024-05-28 04:14 UTC, Blitz425 commented
Wide Lens had NO business being in Rogue Tier.

2024-05-28 17:01 UTC, Xavion3 commented
There any explanation for some of these? Particularly making you get more than 10x as many vouchers from rewards, that seems like a pretty dramatic change to be just snuck in under an update which is otherwise focused on actual mechanical balance.

2024-05-28 18:35 UTC, ben-lear commented
These changes might have a (possibly unintended) significant impact on the functionality of Pickup mons, as you will no longer be able to go as many floors picking up berries before you are forced to re-distribute due to max stacks. It could get pretty annoying to micromanage berry stacks that small, especially with no ability to split stacks.

I really don't think the ability to stack berries to 10 is anywhere near game-breaking, especially with some of the other wacky tools at players' disposal.

2024-05-28 19:22 UTC, damocleas commented
> Is there any explanation for some of these? Particularly making you get more than 10x as many vouchers from rewards, that seems like a pretty dramatic change to be just snuck in under an update which is otherwise focused on actual mechanical balance.

Moving them to a different PR.

Also tested this, confirmed automatically reduces berry counts in current runs.

2024-05-30 20:43 UTC, Xavion3 requested changes

2024-05-30 20:43 UTC, Xavion3 commented on src/modifier/modifier.ts
> +    return 3;
Can we not use switch statements as a janky includes?

2024-06-02 01:41 UTC, XGSleepWalker requested changes
Waiting on Discord announcement

2024-06-02 01:42 UTC, Xavion3 approved these changes

2024-06-02 02:10 UTC, XGSleepWalker approved these changes

2024-06-02 02:10 UTC, merged