Fixed when roost removes flying type
pagefaultgames/pokerogue pull request #148
Opened 2024-04-15 20:31 UTC by IshanP02

Roost was removing flying type on the next turn instead of during the current turn. Just added a condition called GROUNDED that does the same thing as IGNORE_FLYING, but on the current turn instead of the next turn.

2024-04-15 20:33 UTC, Flashfyre requested changes
There are plenty of places already that use IGNORE_FLYING, and don't know about GROUNDED, can you ensure those still work properly?

2024-04-15 20:36 UTC, IshanP02 commented
I did not change anything that used IGNORE_FLYING or IGNORE_FLYING itself aside from roost, and I can confirm that roost works properly through local testing.

2024-04-15 20:40 UTC, IshanP02 commented
I might've misunderstood, are you asking if, for example, a Pokemon uses smack down, and then on the next turn, the pokemon hit uses roost, so both IGNORE_FLYING and GROUNDED are on the pokemon at the same time, does this cause issues. If so, looking at the code, all IGNORE_FLYING and GROUNDED do are remove the flying type of a Pokemon if it has it, so it shouldn't cause any issues, whichever is called first will just remove the flying type and the next will do nothing because there is no flying type to remove.

2024-04-15 21:46 UTC, Flashfyre commented
I was just asking you to look up every case of IGNORE_FLYING and check if it should also be applied to GROUNDED.

2024-04-15 22:45 UTC, IshanP02 commented
Understood, I just looked through and added a GROUNDED check to levitate. That should cover all instances of IGNORE_FLYING that need to be applied to GROUNDED.

2024-04-15 22:55 UTC, Flashfyre approved these changes

2024-04-15 22:58 UTC, Flashfyre requested changes

2024-04-15 22:58 UTC, Flashfyre commented on src/field/pokemon.ts
> +    if (forDefend && (this.getTag(BattlerTagType.GROUNDED) || this.scene.arena.getTag(ArenaTagType.GRAVITY))) {
One more thing, why are we duplicating the previous block here but with grounded? Is this necessary, can they not be combined?

2024-04-15 23:10 UTC, IshanP02 commented on src/field/pokemon.ts
> +    if (forDefend && (this.getTag(BattlerTagType.GROUNDED) || this.scene.arena.getTag(ArenaTagType.GRAVITY))) {
Yeah they could be combined, not sure why I duplicated it to be honest. Same result either way, but would be cleaner combined yes, I'll do that right now.

2024-04-15 23:11 UTC, IshanP02 commented on src/field/pokemon.ts
> +    if (forDefend && (this.getTag(BattlerTagType.GROUNDED) || this.scene.arena.getTag(ArenaTagType.GRAVITY))) {
Done

2024-04-16 17:40 UTC, IshanP02 commented
Just posting this comments because this pull request still says changes requested instead of review required and I think posting this comment will change that?

2024-04-16 18:31 UTC, merged