[Enhancement] Add Hidden Ability Gacha
pagefaultgames/pokerogue pull request #1518
Opened 2024-05-28 21:34 UTC by aeloan

## What are the changes?

Added a gacha with an x2 hidden ability chance up from the feature vote : https://trello.com/c/JBNmgfID/59-egg-gacha-for-higher-hidden-ability-chance
Can be seen at the right of the shiny gacha with an ability pill on top

## Why am I doing these changes?

These changes where asked on a feature vote, as a begginer on open-source project, I tried it

### Screenshots/Videos

![image](https://github.com/pagefaultgames/pokerogue/assets/99343744/844d5eb9-5640-4396-999b-3682909c725a)

## How to test the changes?

Change the UP_HIDDEN_ABILITY_CHANCE_OVERRIDE in the overrides.ts and test with multiple egg , you will know the presence of the hidden abilty during the hatch

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-05-28 22:43 UTC, Icehawk78 requested changes

2024-05-28 22:43 UTC, Icehawk78 commented on public/images/egg/gacha_underlay_hidden_ability.json
> +			"image": "gacha_underlay_shiny.png",
This looks like the wrong filename

2024-05-28 22:43 UTC, Icehawk78 commented on src/egg-hatch-phase.ts
> +        ret = this.scene.addPlayerPokemon(pokemonSpecies, 1, undefined, undefined, undefined, false, undefined, undefined, undefined, undefined, hiddenAbilityChance);
Could you create a new method similar to the `trySetShiny` for setting the hidden ability, to avoid having to modify the constructor signature?

2024-05-28 22:43 UTC, Icehawk78 commented on src/overrides.ts
> +export const UP_HIDDEN_ABILITY_CHANCE_OVERRIDE: integer = 128;
These seem more like global values than overrides. I don't hate the idea of extracting a bunch of these out into a more centralized location to make balancing changes easier, but this is definitely a different pattern than what the rest of the project uses. Probably worth bringing up in a larger discussion with the wider dev group on Discord?

2024-05-29 16:35 UTC, aeloan commented on src/egg-hatch-phase.ts
> +        ret = this.scene.addPlayerPokemon(pokemonSpecies, 1, undefined, undefined, undefined, false, undefined, undefined, undefined, undefined, hiddenAbilityChance);
I saw the method trySetShiny but I don't see the point of adding a method. Why would we change the presence of shiny on a pokemon after his initialization ? Where we use it for now is before the user knows it is shiny or not but unless we want to add an item that change the shinyness of a pokemon, it wouldn't happen on a real pokemon game

2024-05-30 00:12 UTC, bennybroseph commented
This is incredibly unprofessional for us and I really do apologize, but that Trello has been out of date for months. We use a different tool for this purpose now and it is not user-facing. We no longer want this feature implemented. I hope you do not see this as time wasted though, as everything is a learning experience. Everything done here just makes the next change easier.

2024-05-30 00:12 UTC, closed without merging