[enhancement] Added overrides for Post Battle rewards
pagefaultgames/pokerogue pull request #1526
Opened 2024-05-29 01:13 UTC by MPekelny

## What are the changes?
Added the ability to override how many and what items appear during the post battle reward screen.

## Why am I doing these changes?
There are a couple thing I want to do at some point where having the ability to specify rewards will be very helpful and I can also imagine others might find this functionality useful. So, I figure it is probably preferable to get this change reviewed/committed first separately from the other stuff I will be doing.

## What did change?
I added a REWARD_AMOUNT_OVERRIDE value that can be used to override the amount of rewards that appears in the selection, and REWARD_OVERRIDES that can override some or all of the rewards that appear.

I also, instead of having the override code in the place that uses it, put it in the override.ts file. I think once this is merged, something I will look to do is move any overriding code to overrides so that it can all be in one place rather than scattered throughout the codebase.

### Screenshots/Videos
Example shot showing it is the first wave, but I have overridden it to show 5 rewards and the first two rewards is the Acrobatics TM and Lum Berry.

## How to test the changes?
Go into overrides.ts and change the REWARD_AMOUNT_OVERRIDE and/or REWARD_OVERRIDES. Then win a battle and see the rewards use the values you specify.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-05-30 00:09 UTC, bennybroseph requested changes

2024-05-30 00:09 UTC, bennybroseph commented on src/overrides.ts
> +}
did you add functions to overrides.ts?

2024-05-30 02:03 UTC, MPekelny commented on src/overrides.ts
> +}
Are we not supposed to? It seems like it would be better if instead of the code that applies overrides be all over the place, all that code was contained in overrides.

2024-05-30 13:03 UTC, bennybroseph commented on src/overrides.ts
> +}
yeah, we edit overrides to debug. i don't wanna look at functions in that file.

2024-05-31 01:04 UTC, MPekelny commented on src/overrides.ts
> +}
That is very fair. I have moved those functions to a new overrides-functions.ts and added a comment to overrides to help make it clear for anyone else who might think to do the same.

I assume I am not supposed to resolve this conversation, you are if my change works for you, correct?

2024-08-07 19:31 UTC, flx-sta commented
ℹ️ PR considered stale. No actions in the last 30 days.

-----

❗ Feel free to ping me/comment if you want to re-open it

2024-08-07 19:31 UTC, closed without merging