Added Perish Body ability [Ability]
pagefaultgames/pokerogue pull request #1554
Opened 2024-05-29 07:33 UTC by newmattock

## What are the changes?
Added functionality for the Perish Body ability, applying the "Perish Song" effect to both Pokemon after the user is hit with a physical attacking move.

## Why am I doing these changes?
I introduced these changes because I thought Perish Body was a strategically interesting ability. My changes do not come from other PRs or previous issues, however, I believe it could improve the player experience by offering another ability that users could base their runs on, adding more variability.

## What did change?
I functionality for the Perish Body, which was unimplemented before I added these changes.

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/152253273/13979d87-63fd-4d9d-8e3b-982fbe31904b

## Checklist
- [ x] There is no overlap with another PR?
- [ x] The PR is self-contained and cannot be split into smaller PRs?
- [x ] Have I provided a clear explanation of the changes?
- [ x] Have I tested the changes (manually)?
    - [ x] Are all unit tests still passing? (`npm run test`)
- [ x] Are the changes visual?
  - [x ] Have I provided screenshots/videos of the changes?

2024-05-29 14:59 UTC, Tempo-anon commented on src/data/ability.ts
> +      pokemon.addTag(BattlerTagType.PERISH_SONG, this.turns);
Bulbapedia says
`When the Pokémon with Perish Body is hit with a [contact](https://bulbapedia.bulbagarden.net/wiki/Contact) move, both the attacker and the Pokémon with Perish Body will faint in three turns. If the attacker already has a perish count or is wearing [Protective Pads](https://bulbapedia.bulbagarden.net/wiki/Protective_Pads) or has [Long Reach](https://bulbapedia.bulbagarden.net/wiki/Long_Reach_(Ability)), the Ability does not affect anyone.`

2024-05-29 15:00 UTC, Tempo-anon requested changes
1. Needs documentation
2. Fix linting issues
3. Functionality needs to check if one of the pokemon is already being affected by perish song

2024-05-29 22:49 UTC, newmattock commented
Going to try to add the documentation and the functionality for if the attacker has perish song already by today. Let me know if there need to be any more changes afterward!

2024-05-29 22:52 UTC, Tempo-anon commented
The ability should do nothing if either the attacker OR defender are already under the effects of perish song. Otherwise seems fine to me

2024-05-30 04:51 UTC, Tempo-anon commented on src/data/ability.ts
> + * @description: This ability applies the Perish Song tag the attacking pokemon
nit: You're missing a word `to` here

2024-05-30 04:51 UTC, Tempo-anon commented on src/data/ability.ts
> +      // Applying the Perish Song tag to both pokemon
nit: I think the code here is clear enough that there's no need for comments

2024-05-30 04:52 UTC, Tempo-anon commented on src/data/ability.ts
> +    return getPokemonMessage(pokemon, `'s ${abilityName}\n will faint both pokemon in ${this.turns - 1} turns!`);
Prob best practice to localize this https://github.com/pagefaultgames/pokerogue/blob/main/src/locales/en/ability-trigger.ts

2024-05-30 04:53 UTC, Tempo-anon reviewed
Looks mostly good to me. Just some minor nitpicks

2024-05-30 05:05 UTC, newmattock commented on src/data/ability.ts
> +    return getPokemonMessage(pokemon, `'s ${abilityName}\n will faint both pokemon in ${this.turns - 1} turns!`);
working on it right now, thank you!

2024-05-30 15:36 UTC, merged