[Localization] modifier-select-ui-handler Locales
pagefaultgames/pokerogue pull request #1567
Opened 2024-05-29 16:52 UTC by Adri1

## What are the changes?
Locales for item selectionmenu (modifier-select-ui-handler) between battles

## Why am I doing these changes?
TO localize this menu and for accessibility

## What did change?
If translation is provided, this menu will be in the set language
Number forbat adapting to the language (ex : English "1,000" for a thousand and "1 000" in French for a thousand)

**Only one minor issue :**
As the cursor potion doesn't adjust according to text lengh, it desapear under the text, so if anybody has a solution provide...
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/3b54e05a-7dc8-4180-a44f-74ed0a1dc2ec)

### Screenshots/Videos
**Before** (French)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/d0af525d-1626-4b63-ab44-3e02d87319f0)

**After** (French)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/7d6a6194-f36d-40c8-ad47-ff86a015ac3f)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/617fb5d7-2af8-43ed-864d-18820f6bc71a)

## How to test the changes?
Being in Classic or Endless with a Lock Capsule and a least on item heal by any Pokémon of you team to unlock "Lock rarities" and "Transfer" options in the menu.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-05-29 23:10 UTC, Adri1 commented
Updated with Korean locales

2024-05-30 23:47 UTC, returntoice requested changes
ko/modifier-select-ui-handler.ts changes suggested

2024-05-30 23:47 UTC, returntoice commented on src/locales/ko/modifier-select-ui-handler.ts
> +  "transfer": "Transfer",
```suggestion
  "transfer": "도구 이동",
```

2024-05-30 23:47 UTC, returntoice commented on src/locales/ko/modifier-select-ui-handler.ts
> +  "reroll": "Reroll",
```suggestion
  "reroll": "새로고침",
```

2024-05-30 23:47 UTC, returntoice commented on src/locales/ko/modifier-select-ui-handler.ts
> +  "lockRarities": "Lock Rarities",
```suggestion
  "lockRarities": "레어도 고정",
```

2024-05-30 23:47 UTC, returntoice commented on src/locales/ko/modifier-select-ui-handler.ts
> +  "transferDesc": "Transfer a held item from one Pokémon to another.",
```suggestion
  "transferDesc": "포켓몬이 지닌 도구를 다른 포켓몬에게 옮깁니다.",
```

2024-05-30 23:47 UTC, returntoice commented on src/locales/ko/modifier-select-ui-handler.ts
> +  "lockRaritiesDesc": "Lock item rarities on reroll (affects reroll cost).",
```suggestion
  "rerollDesc": "소지금을 사용하여 선택 가능한 도구들을 새로고침합니다.",
  "lockRaritiesDesc": "새로고침할 때 도구 레어도를 고정합니다(새로고침 비용 상승함).",
```

2024-05-31 13:54 UTC, returntoice approved these changes

2024-05-31 14:37 UTC, Tempo-anon approved these changes

2024-05-31 14:39 UTC, merged

2024-05-31 14:54 UTC, Tempo-anon commented
@Adri1 Merged this in but it caused a game crash so I reverted it. It looks to be a git merge conflict where a variable was renamed
`    this.scene.updateAndShowLuckText(750);`

2024-05-31 15:04 UTC, Adri1 commented
... Oh great...

2024-05-31 15:27 UTC, Adri1 commented
@Tempo-anon Should be okay now, I just retested it and in doesn't crash anymore on the item selection screen