Move touch controls configuration
pagefaultgames/pokerogue pull request #1569
Opened 2024-05-29 18:36 UTC by TimPerdok

## What are the changes?

I've added a setting that opens a configuration panel to move the touch controls around the screen. This setting is only visible when the client has a touch screen. This setting does not use option values like the other settings, but instead opens the configuration panel using the action button. Both landscape mode and portrait mode have their own control positions saved separately.

## Why am I doing these changes?

I implemented these changes to improve the user experience by offering greater flexibility in the placement of the touch controls. This way the game is more accessible and comfortable to play on mobile devices. 

## What did change?

Most changes are inside a new singleton class (MoveTouchControlsHandler). This class is responsible for maintaining the configuration panel for the touch controls. Aside from this the CSS styling and HTML structure of the touch controls had to be changed to allow for these configuration options. Finally a new setting is added that can be activated using the action button that opens up the configuration panel.

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/43152351/9e4f2937-5c8a-45bd-a071-52a86272a10a

## How to test the changes?

Open the branch on a mobile device or a simulated mobile device using browser dev tools. Then navigate to the new setting on the bottom. This setting only appears when the client has a touch screen. By using the action button on the setting, a new panel opens up where you can drag the touch controls around the screen to reconfigure their position.

2024-05-31 18:50 UTC, joop339 commented
Thank you! Works like a charm!

2024-06-04 16:06 UTC, brain-frog commented
Settings got reworked so this will need to be updated to work with that, but I like this idea so please let me know when the merge conflicts are resolved and I'll review

2024-06-04 17:13 UTC, TimPerdok commented
@brain-frog I have fixed the merge conflicts. Let me hear if you find anything.

2024-06-05 18:45 UTC, brain-frog requested changes

2024-06-05 18:45 UTC, brain-frog commented on index.css
> +#touchControls:not([data-ui-mode='STARTER_SELECT']):not([data-ui-mode='SETTINGS']):not([data-ui-mode='SETTINGS_ACCESSIBILITY']):not([data-ui-mode='SETTINGS_GAMEPAD']):not([data-ui-mode='SETTINGS_KEYB
please update the second not to be
`:not([data-ui-mode^='SETTINGS'])` 
so it captures all current and future SETTINGS modes

2024-06-05 18:45 UTC, brain-frog commented on index.html
> +	<div id="touchControls" class="touchControls">
what is the reasoning behind it being both an id and a class

2024-06-05 18:45 UTC, brain-frog commented on src/ui/settings/settings-accessiblity-ui-handler.ts
> +    this.settings = Setting.filter(s => s.type === SettingType.ACCESSIBILITY && !s.hidden?.());
if it should be done every time it should probably be handled in the abstract class

2024-06-05 18:45 UTC, brain-frog commented on src/ui/settings/touch/move-touch-controls-handler.ts
> +  private setPosition(controlElement: HTMLElement, x: number, y: number) {
is there any check making sure users dont overlap buttons? I'd like to avoid buttons being pressed at the same time or lost under one another since this can lead to exploits easier

2024-06-05 21:05 UTC, TimPerdok commented on src/ui/settings/touch/move-touch-controls-handler.ts
> +  private setPosition(controlElement: HTMLElement, x: number, y: number) {
I don't think this would cause issues, as I expect that Phaser handles the inputs sequentially. This would be the same for users pressing keyboard keys simultaneously. Aside from this, the controls are all HTML, which means inputs can easily be modified by users. Obscuring that will have little advantage.

2024-06-05 21:10 UTC, TimPerdok commented on index.html
> +	<div id="touchControls" class="touchControls">
None, changed.

2024-06-05 21:10 UTC, TimPerdok commented on index.css
> +#touchControls:not([data-ui-mode='STARTER_SELECT']):not([data-ui-mode='SETTINGS']):not([data-ui-mode='SETTINGS_ACCESSIBILITY']):not([data-ui-mode='SETTINGS_GAMEPAD']):not([data-ui-mode='SETTINGS_KEYB
Good idea

2024-06-06 14:43 UTC, Greenlamp2 commented on src/system/settings/settings.ts
> +    key: SettingKeys.Language,
look like a bad copy/paste here

2024-06-06 14:47 UTC, Greenlamp2 commented on src/touch-controls.ts
> +  document.querySelectorAll(".apadBtn").forEach((element) => preventElementZoom(element as HTMLElement));
Did you test if this line of code crash when there is no Dom ? like in tests run for example

2024-06-06 18:16 UTC, TimPerdok commented on src/touch-controls.ts
> +  document.querySelectorAll(".apadBtn").forEach((element) => preventElementZoom(element as HTMLElement));
All the tests succeed. querySelectorAll always returns a NodeList. So if an element does not exist, it would just skip the line.

2024-07-30 03:08 UTC, Tempo-anon commented
Closing this because of merge conflicts and it's been a while. If this is still needed someone can open a PR for this feature

2024-07-30 03:08 UTC, closed without merging