[Feature] Add evil teams
pagefaultgames/pokerogue pull request #1577
Opened 2024-05-29 20:43 UTC by Tempo-anon

## What are the changes?
* Added evil teams to the game

## Why am I doing these changes?
* Evil teams are a commonly requested feature
* Classic mode is lacking content in the midgame apart from a few rival battles
* Players only need to prepare for the final boss and the rival as the main hurdles in a classic playthrough. This introduces some roguelike randomness where there is another major boss that players have to prepare for

## What did change?
* Added sprites and json's for new trainers
* Created an `evilTeam` that is randomly chosen when players begin a new game. This will then spawn grunts that will randomly replace normal trainers with increasing frequency until the evil team boss is defeated at floor 105
* Fixed evil team grunt spawns at floors 35, 111, and 113
* Evil team boss spawns on floor 115 and 165

### Screenshots/Videos
![](https://cdn.discordapp.com/attachments/1229525892624154684/1245473571875328001/image.png?ex=6658e127&is=66578fa7&hm=1fba43947a261e8efab43f00cf66977b1b305c3cbf2e70b7d06fb0846a71b449&)
![](https://cdn.discordapp.com/attachments/1229525892624154684/1245473902466039870/image.png?ex=6658e176&is=66578ff6&hm=01287c87fa9d9f043e501dfce1808b19412df7f9d9b6b8e84c6f891493ebfe6d&)

## How to test the changes?
Just pull the code and start a classic run. Overrides can be used to skip ahead to the relevant boss fights

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

## Todo
- [ ] Dialogue needs to be updated from memes and jokes
- [ ] How often grunts spawn probably need to be tweaked
- [ ] Evil Team Pokemon selection and balancing

## Goals
When making the teams of the grunts and bosses I tried to focus on a few principles
* The teams should all be distinct. Try not to reuse Pokemon species that other teams or notable trainers use
* The specific generation/region the team came from should be highlighted. This means team rocket should have an emphasis on gens 1-2 while magma/aqua have a focus on gen 3, etc
* Show off some underutilized features in classic mode such as more mega Pokemon
* Variety and variance among similar Pokemon in a team
* The first boss fight should reference the feel of fighting them in game. The second fight should highlight a legendary Pokemon as well as a more themed team. It _should_ be a challenge!

2024-05-29 20:54 UTC, flx-sta requested changes

2024-05-29 20:54 UTC, flx-sta commented on src/battle-scene.ts
> +        }
you should not first run `this.arena.randomTrainerType(newWaveIndex);` and then overwrite it after checking `this.evilTeamOverride(waveIndex)`. Instead initialize `trainerType` with the correct one immediately

2024-05-29 20:54 UTC, flx-sta commented on src/battle.ts
> +      return TrainerType.ROCKET_BOSS_GIOVANNI_1;
you can ditch this case (or make it fallthrough) as it returns the same as `default`

2024-05-29 20:54 UTC, flx-sta commented on src/battle.ts
> +      return TrainerType.ROCKET_BOSS_GIOVANNI_2;
you can ditch this case (or make it fallthrough) as it returns the same as `default`

2024-05-29 20:54 UTC, flx-sta commented on src/locales/de/trainers.ts
> +  "rocket_grunt": "Rüpel von Team Rocket",
I think it's actually `Team Rocket Rüpel` 
(same for the other following ones)

2024-05-29 20:54 UTC, flx-sta commented on src/battle-scene.ts
> +  }
Maybe these conditions should be wrapped into some kind of methods in a more "global" manner.
Otherwise eventual other changes in the future might not know that these waves are reserved for the evils

2024-05-29 21:11 UTC, CodeTappert commented on src/locales/de/trainers.ts
> +  "rocket_grunt": "Rüpel von Team Rocket",
See https://www.pokewiki.de/R%C3%BCpel_von_Team_Rocket

2024-05-29 21:11 UTC, CodeTappert commented on src/locales/de/trainers.ts
> +  "rocket_grunt": "Rüpel von Team Rocket",
Or here for the newest team (star): https://www.pokewiki.de/R%C3%BCpel_von_Team_Star

2024-05-29 21:58 UTC, flx-sta commented on src/locales/de/trainers.ts
> +  "rocket_grunt": "Rüpel von Team Rocket",
Even with sauce. Can't beat that

2024-05-29 22:15 UTC, SeafoamQueen commented
I was tester for this feature. I used a fire/water/grass team composed of pokemon available at the start of the game. I did use egg moves on them, but I don't feel like this substantially altered the viability of my team.

The new trainer battles felt fair in terms of both frequency and opposing team compositions.
This change does increase the difficulty of classic, but also increases the replayability.
It also increases mid-game engagement for players who are able to consistently complete classic in it's current state.

2024-05-30 13:09 UTC, Tempo-anon commented on src/battle-scene.ts
> +        }
I don't think it makes a functional difference besides neatness if I made it like this. Having it as separate lines in my mind makes it easier to remove/change since the final formula for overriding hasn't been determined yet
```
let trainerType = this.evilTeamOverride(waveIndex) ? this.getEvilTeamGrunt(this.evilTeamThisRun) : this.arena.randomTrainerType(newWaveIndex)
```

2024-05-30 13:10 UTC, Tempo-anon commented on src/battle.ts
> +      return TrainerType.ROCKET_BOSS_GIOVANNI_1;
I think this is just a styling preference since I like having explicit cases for each possibility as well as a default in case things go wrong, but you are right that I can skip the EvilTeam.TEAM_ROCKET case if they're also in the default

2024-05-30 13:11 UTC, Tempo-anon commented
> It seems like i told you the wrong sprite names yesterday...The game searches for magma_grunt_m and magma_grunt_f. (same for the other teams)
> 
> So maybe you can still revert that change. If not i will create a PR to this anyways since i want to swap the magma grunts to the M ones.
> 
> Here is the PR: [Tempo-anon#2](https://github.com/Tempo-anon/pokerogue/pull/2)

You tricked me 😭 it's fine, I'll fix it in a new commit soon

2024-05-30 13:15 UTC, Tempo-anon commented on src/battle-scene.ts
> +  }
The only reserved waves for evils right now are defined at the bottom of `battle.ts` which is 35, 111, and 113 right now. This is just a filler for now but I guess I can make it a bit more detailed

2024-05-30 16:16 UTC, flx-sta commented on src/battle.ts
> +      return TrainerType.ROCKET_BOSS_GIOVANNI_1;
Or use a fall through:
```ts
    switch (evilTeam) {
    case EvilTeam.TEAM_MAGMA:
      return TrainerType.MAGMA_GRUNT;
    case EvilTeam.TEAM_AQUA:
      return TrainerType.AQUA_GRUNT;
    case EvilTeam.TEAM_GALACTIC:
      return TrainerType.GALACTIC_GRUNT;
    case EvilTeam.TEAM_PLASMA:
      return TrainerType.PLASMA_GRUNT;
    case EvilTeam.TEAM_FLARE:
      return TrainerType.FLARE_GRUNT;
    case EvilTeam.TEAM_ROCKET:
    default:
      return TrainerType.ROCKET_GRUNT;
```

2024-05-30 16:19 UTC, flx-sta commented on src/battle-scene.ts
> +        }
You don't have to use short-if.

```ts
let trainerType: Trainer //idk the type tbh..

if (this.evilTeamOverride(waveIndex)) {
    trainerType = this.getEvilTeamGrunt(this.evilTeamThisRun) 
} else {
    trainerType = this.arena.randomTrainerType(newWaveIndex)
}
```

it saves processing time as the thread doesn't have to initialize two times

2024-05-30 18:21 UTC, star-krieg commented
I tested this feature on a fresh save (I used Fuecoco and 2 other starters for coverage - Mudkip and Turtwig). I failed a few runs because of bad RNG, but my best run so far was able to up to 195. The evil team bosses bring more challenge to classic  and reduces the monotony of having only the rival as trainers to actually prepare for during successive runs. 

I had to repeat a battle a few times to beat the 165 evil boss (I had Giovanni), and preparing a well-balanced team certainly helped. While this makes classic a bit more difficult, it provides another challenge to consider for the player.

2024-05-30 18:39 UTC, CodeTappert commented
German Dialogue: https://github.com/Tempo-anon/pokerogue/pull/4

2024-05-30 21:52 UTC, Xavion3 reviewed
I'm still unsure on a lot of these teams, plentiful boss pokemon, and megas and paradox mixed in make me cautious as these feel like they're trying to compete with the rival and have more stuff going for them than the e4/champ. I feel like these boss teams could be pretty much universally toned down, and save these stronger teams for a hypothetical hard mode.

2024-05-30 21:52 UTC, Xavion3 commented on src/battle-scene.ts
> +  public evilTeamThisRun: EvilTeam;
Why is this being stored instead of being dynamically generated?

2024-05-30 21:57 UTC, Tempo-anon commented on src/battle-scene.ts
> +  public evilTeamThisRun: EvilTeam;
Not sure what you mean by this. I dynamically generate it on line 828 `this.evilTeamThisRun = possibleEvilTeams[Utils.randInt(possibleEvilTeams.length)];` and then store it so the run generates grunts/bosses that match

2024-05-31 02:13 UTC, Tempo-anon commented on src/battle-scene.ts
> +  public evilTeamThisRun: EvilTeam;
I ended up just changing how they generated completely and basically copied how the E4 is generated

2024-05-31 02:22 UTC, flx-sta commented on src/battle.ts
> +  [125]: new FixedBattleConfig().setBattleType(BattleType.TRAINER).setSeedOffsetWave(35)
I’ve never seen this `  [125]: `.
Would you have a sauce/explanation for me ?

2024-05-31 02:30 UTC, Tempo-anon commented on src/battle.ts
> +  [125]: new FixedBattleConfig().setBattleType(BattleType.TRAINER).setSeedOffsetWave(35)
That means on wave 125 it will generate a battle based off the seed of wave 35 where each boss_2 lines up with the corresponding team grunt generated on wave 35

2024-05-31 02:52 UTC, flx-sta commented on src/battle.ts
> +  [125]: new FixedBattleConfig().setBattleType(BattleType.TRAINER).setSeedOffsetWave(35)
Okay. But how is that legit code. I’ve never seen that syntax before 👀 or is it basically like
```ts
[
 “Key”: “value”,
 [150]: “value”
]
```
?

2024-05-31 05:08 UTC, FogMP commented
I've been testing this feature recently, at different points of account progression(new account/only egg moves allowed/no restrictions) and it makes classic much more interesting to go through. These new trainers are added at points were not much really happen in classic, and they scale pretty well difficulty wise (The first evil team fight at 115 introduces boss in trainer battles, next rival fight has 2 bosses and finally the 165 evil team has 3), and this kind of difficulty was needed in my opinion.

It changes how you go through classic because now not only you have to consider which pokemon to bring just for the rival and the final boss, but also once you see which evil team you get at wave 35, you can start making a team that counters these fights.

Something that could be in consideration is that some of these evil teams use paradox pokemon, which are treated differently in pokerogue and you don't really meet at all until you are near to the end of a run, realistically this isn't that big of a deal, but to make classic more interesting the evil team fights could be added after you beat classic once, not only to make it more challenging but to give more variety to the gamemode  (which it really needs).

2024-05-31 05:11 UTC, Tempo-anon commented on src/battle.ts
> +  [125]: new FixedBattleConfig().setBattleType(BattleType.TRAINER).setSeedOffsetWave(35)
It uses this interface
```ts
interface FixedBattleConfigs {
    [key: integer]: FixedBattleConfig
}
```

2024-05-31 07:25 UTC, CodeTappert commented on src/locales/de/dialogue.ts
> +      1: "Du willst dich also mit Team Aqua anlegen? Du traust dich ja was…Dich werfe ich über Bord!",
Is missing a space before the "Dich werfe". 

Could you add that? Dont want to create a whole new PR for that

2024-06-03 11:25 UTC, FredeX commented on src/locales/de/dialogue.ts
> +      1: `Jetzt gibts Ärger!…
"gibt's" would be correct

2024-06-03 11:25 UTC, FredeX commented on src/locales/de/dialogue.ts
> +      1: `So sehen wir uns wieder. Es scheint, als wären unsere Schicksale miteinander verflochten
Missing a dot after "verflochten", right?

2024-06-03 11:34 UTC, CodeTappert commented on src/locales/de/dialogue.ts
> +      1: `Jetzt gibts Ärger!…
No. The pokewiki has it as "gibts" https://www.pokewiki.de/Team_Rocket_(Anime)#Mottos

2024-06-03 11:36 UTC, CodeTappert commented on src/locales/de/dialogue.ts
> +      1: `So sehen wir uns wieder. Es scheint, als wären unsere Schicksale miteinander verflochten
yes

2024-06-03 11:37 UTC, FredeX commented on src/locales/de/dialogue.ts
> +      1: `Jetzt gibts Ärger!…
either "gibt's" (season 9) or "gibt es" but "gibts" is just wrong.

2024-06-03 11:38 UTC, CodeTappert commented on src/locales/de/dialogue.ts
> +      1: `Jetzt gibts Ärger!…
```suggestion
      1: `Jetzt gibt es Ärger…
```

2024-06-03 11:38 UTC, FredeX commented on src/locales/de/dialogue.ts
> +      1: `Jetzt gibts Ärger!…
and if we follow the wiki there is no exclamation mark after Jessies first sentence

2024-06-03 11:40 UTC, FredeX approved these changes

2024-06-03 14:01 UTC, CodeTappert commented on src/locales/de/dialogue.ts
> +      1: `Jetzt gibts Ärger!…
See https://github.com/pagefaultgames/pokerogue/pull/1577#discussion_r1624271960 

I requested a change there.

Season 9 has a completly different Motto

2024-06-03 15:54 UTC, FredeX commented on src/locales/de/dialogue.ts
> +      1: `Jetzt gibts Ärger!…
alright whatever, good fix.

2024-06-05 20:34 UTC, CodeTappert commented
Hey i just found https://www.deviantart.com/akuma-tsubasa/art/Sprite-Commission-LightningKillua15-4-843105484 which are free to use (when credited) sprites of Cipher.

Could this be something we add in this pr? If not then i will just do a PR after yours is merged. 

If you want to add this to this one here then i will provide you the solo sprite images and json and all

2024-06-06 02:00 UTC, Tempo-anon commented
> Hey i just found https://www.deviantart.com/akuma-tsubasa/art/Sprite-Commission-LightningKillua15-4-843105484 which are free to use (when credited) sprites of Cipher.
> 
> Could this be something we add in this pr? If not then i will just do a PR after yours is merged.
> 
> If you want to add this to this one here then i will provide you the solo sprite images and json and all

I haven't really thought about Cipher since they're from a spin-off. You're more than welcome to make your own PR to add them once this is in though

2024-06-09 22:40 UTC, Tempo-anon commented
Added evil team assets (sprites, music, teams, dialogue). They do **NOT** spawn so there is no gameplay impact whatsoever.

2024-06-09 23:02 UTC, brain-frog approved these changes

2024-06-09 23:02 UTC, merged