Move DamagePhase to separated file
pagefaultgames/pokerogue pull request #1578
Opened 2024-05-29 21:06 UTC by hayuna

Refactor to reduce lines of code in phases.ts

## What are the changes?
Move phases to separated files

## Why am I doing these changes?
Reducing code in one huge file

## What did change?
Moving DamagePhase to separated file

### Screenshots/Videos

## How to test the changes?

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-05-29 21:09 UTC, hayuna commented
If this refactor will be acctepted and merged, I will move more files as well

2024-05-29 23:29 UTC, flx-sta commented
Since this is tech-debt fixes, would it make sense to add some test-coverage too?
_I don't have an idea how much test tooling is already there to get going. I do know there is some existing tests_

2024-05-30 09:30 UTC, hayuna commented
@flx-sta I dont know how to test this. If there would be at least example of testing that classes, would be easier to do this.

2024-05-30 15:23 UTC, Tempo-anon submitted a review, later dismissed
Looks good to me but I think this should get some opinions on the lead devs

2024-05-30 15:29 UTC, XGSleepWalker requested changes
I would like this to stay on hold until we have the testing framework done.

2024-05-30 16:20 UTC, flx-sta commented
> I would like this to stay on hold until we have the testing framework done.

Is there a PR/issue and/or ETA of the testing framework?
The one I see is vitest. Is it being ditched?

2024-05-30 19:43 UTC, hayuna commented
Ok, we will see the progress of vitest and testing framework. But in my opinion is better to keep files more simpler, it would be even easier to future testing

2024-05-30 20:05 UTC, flx-sta commented
@hayuna nobody is disagreeing with that.
the reasons it's postponed is that this is a big code-refactoring and you  never know which accidental bugs you introduce that way. Thus some test-coverage necessary

2024-06-04 04:24 UTC, ben-lear commented on src/phases/DamagePhase.ts
> +export class DamagePhase extends PokemonPhase {
Nit: Seeing as all other files in the project are in kebab case, can the file be renamed to “damage-phase.ts” instead of “DamagePhase.ts”

2024-06-04 04:45 UTC, flx-sta commented on src/phases/DamagePhase.ts
> +export class DamagePhase extends PokemonPhase {
I disagree. This is a class file and it’s also the beginning of a big refactoring.

2024-07-29 21:30 UTC, Tempo-anon commented
Closing for now since it seems like it might be a while until we break apart phases even though it's planned

2024-07-29 21:30 UTC, closed without merging