[QoL] Move Info Overlay
pagefaultgames/pokerogue pull request #1585
Opened 2024-05-30 00:35 UTC by prime-dialga

## What are the changes?
Overlays containing infos for currently selected moves have been added to various screens, which previous lacked move descriptions.

## What did change?
Those Overlays have been added to the following menus:
- when hovering over a TM on the item selection screen (only visible when pressing Shift or C)
- during the starter selection when selecting and replacing moves
- when using a memory mushroom

In addition, as the UI can get a bit cluttered in certain situations, this behavior can be disabled in the game settings through the "Move Info" option.

## Additional changes
To implement the above listed features some core components had to be modified:
- OptionSelectItem have now an optional "onHover" listener, triggered when the cursor is moved to a new element. (This feature needs to be enabled in the OptionSelectConfig with the "supportHover" setting)
- The scene can now register "InfoToggles", a new interface, with the "addInfoToggle" method. Allowing the use of the Button.STATS for other info-related tasks.

### Screenshots/Videos
The changes during starter selection...
![move-info-starter](https://github.com/pagefaultgames/pokerogue/assets/10091050/bcae49c3-5160-4688-aa1f-f63e649e242d)

... when chosing a TM...
![move-info-tm-1](https://github.com/pagefaultgames/pokerogue/assets/10091050/cdaf7877-b398-474b-80a3-403c55ec6e5f)
![move-info-tm-2](https://github.com/pagefaultgames/pokerogue/assets/10091050/289c9b67-3c1d-4b07-80fa-ad92cf0ccc89)

... and using a Memory Mushroom
![move-info-shroom](https://github.com/pagefaultgames/pokerogue/assets/10091050/da350ecc-82bd-48cf-b86f-88cc53a0fc43)

## Why am I doing these changes?
I personally thought it bothersome to look up moves.
In addition, Memory Mushrooms and TMs are considered "used" by the time the moves description is normally shown, which can be rather punishing for new and less experienced players.

## How to test the changes?
The starter changes can be tested easily, as movesets can always be adjusted and therefore the required menu is accessible.
As for Memory Mushrooms and TMs, as those require a specific item drop, i recommend resetting and exporting a safe file when such an item dropps as the first reward, that way it can be tested somewhat fast. Otherwise modifying the starter money value and rerolling for such an item can also work.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-05-30 03:17 UTC, star-krieg commented
This change will be much appreciated because there's multiple moves in the game, I don't expect everyone to just remember them on the fly.

Memory Mushrooms and TMs are used many times in the game and having the option to see the info in-game would a great change.

2024-05-30 03:18 UTC, Treeck7 commented
This is a great feature, information about the game should be reasonably accessible within the game. Pokemon has had such readily available information from the start so I see no reason to not attempt to do the same here. The ui could use some retouching, but that is something that can be perfected over time with user feedback rather than needing to be perfect from the start.

2024-05-30 03:18 UTC, DecaP0d commented
The game truly needs this! Adding functionality and improving through iteration should always take precedence over perfection! Many things in this game look broken and yet people love it because it is fun. Please let useful PRs that improve gameplay quality like this one through.

2024-05-30 04:05 UTC, flx-sta approved these changes
LGTM 🚀 

I just re-rolled till I got a TM as a reward.

edit:
 _I forgot to test for memory mushroom._


<img width="832" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/4be9bab6-a686-414e-96e4-5f2ba988dcf4">
<img width="842" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/c9970e10-ceec-4c37-8988-901c7218aaae">

--------

<details>
  <summary>Used overrides.ts</summary>
 
  ```ts
  import { Species } from "./data/enums/species";
import { Abilities } from "./data/enums/abilities";
import { Biome } from "./data/enums/biome";
import { Moves } from "./data/enums/moves";
import { WeatherType } from "./data/weather";
import { Variant } from "./data/variant";
import { BerryType } from "./data/berry";
import { TempBattleStat } from "./data/temp-battle-stat";
import { Nature } from "./data/nature";
import { Type } from "./data/type";
import { Stat } from "./data/pokemon-stat";
import { PokeballCounts } from "./battle-scene";
import { PokeballType } from "./data/pokeball";
import {TimeOfDay} from "#app/data/enums/time-of-day";
import { Gender } from "./data/gender";
import { TmModifier } from "./modifier/modifier";

/**
 * Overrides for testing different in game situations
 * if an override name starts with "STARTING", it will apply when a new run begins
 */

/**
 * OVERALL OVERRIDES
 */

// a specific seed (default: a random string of 24 characters)
export const SEED_OVERRIDE: string = "";
export const WEATHER_OVERRIDE: WeatherType = WeatherType.NONE;
export const DOUBLE_BATTLE_OVERRIDE: boolean = true;
export const STARTING_WAVE_OVERRIDE: integer = 10;
export const STARTING_BIOME_OVERRIDE: Biome = Biome.TOWN;
export const ARENA_TINT_OVERRIDE: TimeOfDay = null;
// Multiplies XP gained by this value including 0. Set to null to ignore the override
export const XP_MULTIPLIER_OVERRIDE: number = null;
export const IMMEDIATE_HATCH_EGGS_OVERRIDE: boolean = false;
// default 1000
export const STARTING_MONEY_OVERRIDE: integer = 500000;
export const POKEBALL_OVERRIDE: { active: boolean, pokeballs: PokeballCounts } = {
  active: false,
  pokeballs: {
    [PokeballType.POKEBALL]: 5,
    [PokeballType.GREAT_BALL]: 0,
    [PokeballType.ULTRA_BALL]: 0,
    [PokeballType.ROGUE_BALL]: 0,
    [PokeballType.MASTER_BALL]: 0,
  }
};

/**
 * PLAYER OVERRIDES
 */

// forms can be found in pokemon-species.ts
export const STARTER_FORM_OVERRIDE: integer = 0;
// default 5 or 20 for Daily
export const STARTING_LEVEL_OVERRIDE: integer = 50;
/**
 * SPECIES OVERRIDE
 * will only apply to the first starter in your party or each enemy pokemon
 * default is 0 to not override
 * @example SPECIES_OVERRIDE = Species.Bulbasaur;
 */
export const STARTER_SPECIES_OVERRIDE: Species | integer = 0;
export const ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const PASSIVE_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const GENDER_OVERRIDE: Gender = null;
export const MOVESET_OVERRIDE: Array<Moves> = [];
export const SHINY_OVERRIDE: boolean = false;
export const VARIANT_OVERRIDE: Variant = 0;

/**
 * OPPONENT / ENEMY OVERRIDES
 */

export const OPP_SPECIES_OVERRIDE: Species | integer = 0;
export const OPP_LEVEL_OVERRIDE: number = 0;
export const OPP_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const OPP_PASSIVE_ABILITY_OVERRIDE = Abilities.NONE;
export const OPP_GENDER_OVERRIDE: Gender = null;
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [];
export const OPP_SHINY_OVERRIDE: boolean = false;
export const OPP_VARIANT_OVERRIDE: Variant = 0;

/**
 * MODIFIER / ITEM OVERRIDES
 * if count is not provided, it will default to 1
 * @example Modifier Override [{name: "EXP_SHARE", count: 2}]
 * @example Held Item Override [{name: "LUCKY_EGG"}]
 *
 * Some items are generated based on a sub-type (i.e. berries), to override those:
 * @example [{name: "BERRY", count: 5, type: BerryType.SITRUS}]
 * types are listed in interface below
 * - TempBattleStat is for TEMP_STAT_BOOSTER / X Items (Dire hit is separate)
 * - Stat is for BASE_STAT_BOOSTER / Vitamin
 * - Nature is for MINT
 * - Type is for TERA_SHARD or ATTACK_TYPE_BOOSTER (type boosting items i.e Silk Scarf)
 * - BerryType is for BERRY
 */
interface ModifierOverride {
    name: string,
    count?: integer
    type?: TempBattleStat|Stat|Nature|Type|BerryType
}
export const STARTING_MODIFIER_OVERRIDE: Array<ModifierOverride> = [
  {name: "TM", count: 1, type: Type.FIGHTING}
];
export const OPP_MODIFIER_OVERRIDE: Array<ModifierOverride> = [];

export const STARTING_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [];
export const OPP_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [];

  ```
  
</details>

2024-05-30 14:03 UTC, molker commented
Has this been tested with other languages to make sure the text displays well

2024-05-30 15:45 UTC, Fasin78 commented
Tested with all other languages in order, also chose a move that has a long text description. They all displayed well. 

![Screenshot 2024-05-31 014054](https://github.com/pagefaultgames/pokerogue/assets/170799895/8d06d27b-9330-41b7-84de-ea3db3c44ce5)
![Screenshot 2024-05-31 013404](https://github.com/pagefaultgames/pokerogue/assets/170799895/a851625e-90e5-4afa-82ec-e50beeaa0f48)
![Screenshot 2024-05-31 013440](https://github.com/pagefaultgames/pokerogue/assets/170799895/2727ff50-3404-43cf-b224-08a49c1a8830)
![Screenshot 2024-05-31 013604](https://github.com/pagefaultgames/pokerogue/assets/170799895/e4efe79d-e8a7-4e80-be09-d14c9e4d9e91)
![Screenshot 2024-05-31 013628](https://github.com/pagefaultgames/pokerogue/assets/170799895/99b1770d-82b1-458c-84cb-b78be852186b)
![Screenshot 2024-05-31 013652](https://github.com/pagefaultgames/pokerogue/assets/170799895/c43a6fd6-07fe-4aea-b26b-b308ae17eba8)
![Screenshot 2024-05-31 013729](https://github.com/pagefaultgames/pokerogue/assets/170799895/0f0d890f-9032-4281-b7bc-d852400518e7)
![Screenshot 2024-05-31 013907](https://github.com/pagefaultgames/pokerogue/assets/170799895/47ef9911-a429-4ed2-8304-abe9b872622b)
![Screenshot 2024-05-31 013930](https://github.com/pagefaultgames/pokerogue/assets/170799895/1c4ce765-24ae-4202-af8a-c23ccf5561f2)

2024-05-30 16:38 UTC, Fasin78 commented
Tested with memory mushroom. Working.

![Screenshot 2024-05-31 023719](https://github.com/pagefaultgames/pokerogue/assets/170799895/03257672-5fc9-4e56-a4c2-d749acdb7cc1)

2024-05-30 16:54 UTC, prime-dialga commented
> Has this been tested with other languages to make sure the text displays well

It technically uses scrolling text in cases where the text requires more than 3 lines (like in the status-screen). Though i think that currently only happens in some cases for the memory mushroom.

2024-05-30 16:54 UTC, bennybroseph commented
We'll need some major changes to how this looks at the moment. It just looks like a page of the Move Summary screen got copy pasted in a little window. Not mention all of the bottom message UI is incorrectly shaped and sized. 

What's up with this overlap?

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/29a3587e-a93a-4bd8-9d04-9d75dbd560cb)

Something like this conveys the same info and matches the current UI, why not match this?

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/8cf1a465-f947-47e2-af04-239d359ebb98)

I'm not even sure this can be fixed, I'd rather this be in a separate PR because it looks so cluttered

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/86633d42-03af-4a7b-8a00-6f556d0dac4d)

More strange overlap

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/4db81bc2-9f53-46db-9ba9-0ccce5a19d5d)

2024-06-02 17:50 UTC, prime-dialga commented
Well, there is overlap, as it's its own UI element and an overlay.
Though i adjusted the noted points:

![move-info-v2-tm](https://github.com/pagefaultgames/pokerogue/assets/10091050/f63d806f-51d3-4726-bdfb-b5362c8c731c)
I kept the hard numbers on the left to closer mirror the move inspector on the status menu, though switching sides wouldn't be hard.

![move-info-v2-shroom](https://github.com/pagefaultgames/pokerogue/assets/10091050/7639353f-5411-429a-afb5-fdd4596be653)
Reduced the width to remove the overlap for the 6th pokemon in the party.

![move-info-v2-starter](https://github.com/pagefaultgames/pokerogue/assets/10091050/05b43d70-85de-4045-a4b2-3f37daa48abf)
Made some adjustments to the size and scale to closer resemble to other UI elements. Some other ideas which might look better than the current solution for the starter selection:
- Only appear when pressing C/Shift and overlay the menu / text in the bottom row (similar to the TM selection). Though it seems rather bothersome, since, if you want to check one move, you probably want to check all moves and it would cover the move list you are currently working with.
- Reduce the size a bit more to align with the right most border of the party list box. That might cause a few additional move infos to be cut of and scrolling.

----------

Also a new override for rewards has been added; simply replace the last line in overrides.ts ...
```typescript
export const ITEM_REWARD_OVERRIDE: Array<String> = [];
``` 

... with this:
```typescript
export const ITEM_REWARD_OVERRIDE: Array<String> = ["MEMORY_MUSHROOM", "TM_COMMON", "TM_ULTRA"];
``` 
(requires at least one pokemon in the party to be capable of remembering at least one move and learning one TM)

----------

I kept this as a draft until i got a bit more feedback regarding the design. That way we don't need to set is as draft again, in case further changes are needed.

2024-06-02 20:13 UTC, bennybroseph commented
This looks so much better now, I really like it.

For the first image, let's swap sides to match the Command UI layout since that is the element that we're mirroring.

> Well, there is overlap, as it's its own UI element and an overlay.

If it was as simple as that then these new screenshots wouldn't have adjusted the positions and alignment of the UI elements to no longer overlap. You've fixed the problem which is all that matters, but to say there was none is strange. Anyway, we should do the same for the second image now as well. It's currently covering up text behind it.

Lastly, I don't see a need for this to be an overlay accessible on a press and hold of a button. I think this should just be a setting enabled by default. Especially in the shop menu, this currently has no downside for simply being there by default. The others may be something people would like to turn off.

2024-06-02 20:39 UTC, prime-dialga commented
I didn't say there was no overlap, just that there *is* overlap (and implied that i personally didn't mind the overlap as overlay = covers what is behind it; well, different tastes and all that).

Anyway, settings option is present, TM overlay is swapped, rest as before:
- Starter: when the in game cursor is hovering over a move its description is displayed
- Memory Mushrooms: same as for Starters.
- TMs: hovering a TM *and* pressing C/Shift will show the description. (As it might not be perfectly clear to people without deeper knowledge of pokemon, what TMs are; so "teaches X to a pokemon" might still be a useful info.)

![move-info-v3-tm](https://github.com/pagefaultgames/pokerogue/assets/10091050/e0b484c1-5af9-46ba-a5b6-b4b800bb5078)

2024-06-02 22:42 UTC, bennybroseph commented
can we either update the original images or post images of how these changes look now in all situations?

2024-06-02 22:47 UTC, prime-dialga commented
Here a summery of the how it appears with the latest commit:

TM:
![move-info-tm-1](https://github.com/pagefaultgames/pokerogue/assets/10091050/cdaf7877-b398-474b-80a3-403c55ec6e5f)
![move-info-v3-tm](https://github.com/pagefaultgames/pokerogue/assets/10091050/e0b484c1-5af9-46ba-a5b6-b4b800bb5078)

Shroom:
![move-info-v2-shroom](https://github.com/pagefaultgames/pokerogue/assets/10091050/7639353f-5411-429a-afb5-fdd4596be653)

Starter:
![move-info-v2-starter](https://github.com/pagefaultgames/pokerogue/assets/10091050/05b43d70-85de-4045-a4b2-3f37daa48abf)

Settings:
![move-info-settings](https://github.com/pagefaultgames/pokerogue/assets/10091050/aeb36841-02b5-46f8-8f43-fb1c9f064553)

2024-06-04 03:15 UTC, bennybroseph commented
would like to get this working in the new settings menu and then we're good to go

2024-06-04 05:22 UTC, prime-dialga commented
Fixed, new settings menu though visually the same.

2024-06-04 18:27 UTC, bennybroseph requested changes

2024-06-04 18:27 UTC, bennybroseph commented on public/images/ui/summary_moves_effect_type.png
Need this removed since it isn't used anymore

2024-06-04 18:27 UTC, bennybroseph commented on src/system/settings/settings.ts
> +    type: SettingType.GENERAL
should put this in the new Accessibility settings instead of general

2024-06-04 18:27 UTC, bennybroseph commented on src/battle-scene.ts
there's a lot of formatting changes here. did something happen?

2024-06-04 18:33 UTC, flx-sta commented on src/battle-scene.ts
> +     */
why change indentation?

2024-06-04 18:33 UTC, flx-sta commented on src/battle-scene.ts
> +                }
why change indentation

2024-06-04 18:33 UTC, flx-sta commented on src/battle-scene.ts
> +                    const rgbaToHexFunc = (r, g, b) => [r, g, b].map(x => x.toString(16).padStart(2, '0')).join('');
why change indentation

2024-06-04 19:51 UTC, prime-dialga commented on public/images/ui/summary_moves_effect_type.png
it is now removed

2024-06-04 19:55 UTC, prime-dialga commented on src/battle-scene.ts
it seems like originally tabs ("\t") were used for those indention.
as i personally also use tabs and need to replace those with two blanks ("  ") before commiting (as eslint doesn't automatically replace tabs). eslint now found those unusual indentions and adjusted them to how they are expected to look like.
so i don't think it's an issue?

2024-06-06 01:25 UTC, bennybroseph approved these changes

2024-06-06 01:28 UTC, merged

2024-06-06 13:49 UTC, bennybroseph commented
@prime-dialga What is your name on Discord?