Implemented explosives, fixed immunity abilities
pagefaultgames/pokerogue pull request #159
Opened 2024-04-16 18:02 UTC by Fontbane

- Implemented Damp, and "explosive" move attribute
- Implemented Mind Blown and Steel Beam (recoil taken even if move doesn't hit) with HalfHpAttackAttr
- Implemented Hydro Steam, Misty Explosion and Spirit Shackle
- Status immunity abilities that cure the status when active now do so (for example, a paralyzed mon gaining Limber, or a mon with Mycelium Might using Spore on a mon with Insomnia) via ContinuousResetStatusAbAttr. Note that I've marked Pastel Veil as (P), because it's also supposed to apply to its allies. This can probably be implemented in conjunction with Healer.
- Fixed a console error due to lacking null check in Quick Feet condition

I have not yet tested this yet.

2024-04-16 18:30 UTC, Flashfyre requested changes

2024-04-16 18:30 UTC, Flashfyre commented on src/data/move.ts
> +export class Explosive extends MoveAttr {
Per convention, always end Attr classes with Attr

2024-04-16 19:51 UTC, Fontbane commented on src/data/move.ts
> +export class Explosive extends MoveAttr {
Fixed this and also cleaned up ContinuousResetStatusAbAttr a little

2024-04-17 00:33 UTC, Flashfyre requested changes

2024-04-17 00:33 UTC, Flashfyre commented on src/field/pokemon.ts
> +          const arenaAttackTypeMultiplier = (move.id == Moves.HYDRO_STEAM && this.scene.arena.weather.weatherType==WeatherType.SUNNY)?
Is there a better way to do this without hardcoding?

2024-04-17 01:43 UTC, Fontbane commented on src/field/pokemon.ts
> +          const arenaAttackTypeMultiplier = (move.id == Moves.HYDRO_STEAM && this.scene.arena.weather.weatherType==WeatherType.SUNNY)?
Added IgnoreWeatherDebuffsAttr

2024-04-19 01:03 UTC, Fontbane commented
The mid-turn status healing didn't work as expected, so for now I've implemented a temporary solution (heal on switch out or end of turn). It'll be easier to implement if we get some kind of "PostAbilityGainAbAttr"

2024-04-25 17:52 UTC, closed without merging