[Bug] Fix FutureSight
pagefaultgames/pokerogue pull request #1590
Opened 2024-05-30 01:56 UTC by geefuoco

## What are the changes?

Add in a check for future sight instead of ending turn when user switches out
## Why am I doing these changes?

Its a bug, Future sight should work if user is switched out. Addresses issue #1568 
## What did change?

Add a check for future sight move in MoveEffectPhase 
### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/87877876/c2fe7b2d-c04f-49b6-832e-4e983609a057
## How to test the changes?

Give futuresight to mon your mon in overrides and use it, then switch out.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-05-31 23:57 UTC, geefuoco commented
https://github.com/pagefaultgames/pokerogue/assets/87877876/df0314bb-e53d-429c-aaa0-9546c2c312ce

---

Focus band and Sturdy works, but endure does not. 
Changing endure functionality is out of scope

2024-06-02 18:11 UTC, geefuoco commented
@Tempo-anon can you review ?

2024-06-11 05:16 UTC, Tempo-anon commented on src/data/arena-tag.ts
> +export class DelayedAttackTag extends ArenaTag {
Can you add documentation to this class?

2024-06-11 05:16 UTC, Tempo-anon commented on src/data/move.ts
>    apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): Promise<boolean> {
Also documentation on the `DelayedAttackAttr` class and this `apply`

2024-06-11 05:17 UTC, Tempo-anon commented on src/data/move.ts
> +    const side = user.isPlayer() ? ArenaTagSide.ENEMY : ArenaTagSide.PLAYER;
shouldn't this be `const side = target.isPlayer() ? ArenaTagSide.PLAYER : ArenaTagSide.ENEMY` ? For the edge case for when you use a delayed attack move on your ally

2024-06-11 05:19 UTC, Tempo-anon commented on src/data/move.ts
> +      .ignoresProtect(),
Should this also be on doom desire too?

2024-06-11 05:21 UTC, Tempo-anon commented on src/phases.ts
> +        console.log("Doom Desire tag:", doomDesireTags);
nit: remove `console.log`s

2024-06-11 21:36 UTC, geefuoco commented on src/data/move.ts
> +    const side = user.isPlayer() ? ArenaTagSide.ENEMY : ArenaTagSide.PLAYER;
yes good catch

2024-06-11 21:37 UTC, geefuoco commented
I've updated the code, note that tests are not passing, but its coming from the main branch and not this one
![image](https://github.com/pagefaultgames/pokerogue/assets/87877876/e54289a4-de97-4833-9dfd-8a0fd2fa6cbb)

2024-06-12 01:42 UTC, Tempo-anon commented on src/data/move.ts
> +   * @param {any[]} args- Additional arguments to pass when applying a move
You should describe what args[0] and args[1] are since they are used in the code

2024-06-12 02:24 UTC, geefuoco commented on src/data/move.ts
> +   * @param {any[]} args- Additional arguments to pass when applying a move
I'm not entirely sure what they are tbh. I didn't create the class from scratch, I just updated an existing class.

2024-06-12 20:08 UTC, Tempo-anon commented on src/data/move.ts
> +   * @param {any[]} args- Additional arguments to pass when applying a move
Can you figure it out and document it? Also add documentation to `DelayedAttackTag`

2024-06-14 20:57 UTC, geefuoco commented on src/data/move.ts
> +   * @param {any[]} args- Additional arguments to pass when applying a move
Not really since its implementing an abstraction. The interface itself has this definition 
![image](https://github.com/pagefaultgames/pokerogue/assets/87877876/8a5acc96-4c52-4dbc-a8d3-6a555b3be342)

Or here from the base class
![image](https://github.com/pagefaultgames/pokerogue/assets/87877876/270d3c6d-73cc-4bc6-965c-3a063e61a45b)

so assuming its the same, I can just make note of that

2024-06-16 02:27 UTC, Tempo-anon submitted a review, later dismissed

2024-06-16 02:28 UTC, Tempo-anon commented
Merge conflicts?

2024-06-26 19:01 UTC, Tempo-anon requested changes

2024-06-26 19:01 UTC, Tempo-anon commented on src/data/move.ts
> +    const side = target.isPlayer() ? ArenaTagSide.PLAYER: ArenaTagSide.ENEMY;
This will cause a crash if future sight lands on the same turn you KO a trainer's last Pokemon
![](https://cdn.discordapp.com/attachments/1176874654015684739/1255597641836924928/image.png?ex=667db5ed&is=667c646d&hm=1aa4a4a85cbd6a58ca0980617bff9df96d05b1e5b641a408d9f9e6e6a88eeb27&)

2024-08-08 01:24 UTC, flx-sta commented
ℹ️ PR considered stale. No actions in the last 30 days.

-----

❗ Feel free to ping me/comment if you want to re-open it

2024-08-08 01:24 UTC, closed without merging