[Move] Implement Alluring Voice and Burning Jealousy
pagefaultgames/pokerogue pull request #1619
Opened 2024-05-30 22:45 UTC by ElliottSimmonds

## What are the changes?
Implementing the special functionality of Alluring Voice and Burning Jealousy, which will either confuse or burn target Pokemon if they have had their stats boosted previously on the same turn.

## Why am I doing these changes?
Both moves are partially implemented and I think they're cool.

## What did change?
* Added `statsBoosted` bool to `PokemonTurnData`. This is set to true in the `StatChangePhase` if the pokemon recieves a stat boost.
* Added `statsBoostedFirstTurn` bool to `PokemonBattleData`. It is only set to true after a stat boost on the first turn of a battle.
* Added `ConfuseIfBoostedAttr` class for Alluring Voice, which will confuse the target if their stats have been boosted this turn.
* Added `BurnIfBoostedAttr` class for Burning Jealousy, which will burn the target(s) if their stats have been boosted this turn.

To further explain `statsBoostedFirstTurn` -  On the first turn of the battle only (verified on showdown), boosts that occur before the turn selection phase (from on summon abilities such as download, or intimidate>defiant) will still trigger the move's effects.
This makes sense but is a little awkward to implement, because PokemonTurnData isn't defined until after the initial StatChangePhase. I added this to compensate and achieve the desired functionality. There may be better way to do it though, feels a bit hacky to me!

Another thing to note: Stat boost copying, such as by Ditto's transform or psych up, do not trigger the move effects (verified on showdown).

### Screenshots/Videos
Example of the move effects triggering on turn 1:

[2024-05-29 19-44-16.webm](https://github.com/pagefaultgames/pokerogue/assets/33560264/be8f076c-2f8d-41af-876a-b64b2db00b38)

[2024-05-29 19-45-01.webm](https://github.com/pagefaultgames/pokerogue/assets/33560264/07df7d27-6196-4ce1-be17-24b5f20afd5b)

Example of the move effects triggering after the target has boosted their stats:

[2024-05-29 19-51-21.webm](https://github.com/pagefaultgames/pokerogue/assets/33560264/7024fff4-6ece-4b37-871d-71c1f175f2ea)

Example of move effects not triggering, for good measure:

[2024-05-29 19-52-43.webm](https://github.com/pagefaultgames/pokerogue/assets/33560264/f81348e7-ec4a-409b-840d-5470d1a3f93b)

## How to test the changes?

I just made use of overrides, using abilities that boost stats on summon and stat boosting moves.
The effects trigger if the moves hit after stats have been boosted, so your starter will need to be slower than the opponent in most situations.
I skipped to the Eternatus battle to make sure it works against the boosts bosses recieve when one of their health bars is knocked out.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-03 16:40 UTC, OrangeRed requested changes

2024-06-03 16:40 UTC, OrangeRed commented on src/data/move.ts
> +  }
Can you make it so that this class takes a `BattlerTagType` as a constructor param instead of hard coding it to only use `BattlerTagType.CONFUSED`?

2024-06-03 16:40 UTC, OrangeRed commented on src/data/move.ts
> +
Can you make it so that this class takes a `StatusEffect` as a constructor param instead of hard coding it to only use `StatusEffect.BURN`?

2024-06-03 16:40 UTC, OrangeRed commented on src/phases.ts
> +          }
Do you need this if you're already checking in the Attrs whether the target has stat boosted this turn?
isn't `user.scene.currentBattle.turn === 1 && target.turnData.statBoosted` handle this variable and even still if you want to be super safe you can use `PokemonTurnData.acted` to check if the target acted in the turn prior to the move's user?

2024-06-03 16:40 UTC, OrangeRed commented on src/field/pokemon.ts
> +  public statsBoosted: boolean;
I would default these to false so it resets properly instead of resetting to undefined

2024-06-03 21:06 UTC, ElliottSimmonds commented on src/data/move.ts
> +  }
Thanks, I've made these changes :)

2024-06-03 21:30 UTC, OrangeRed commented on src/phases.ts
> +          }
> The problem is during the first turn of wild battles pokemon.turnData is undefined during the StatsChangePhase, so statBoosted can't be set to true.

If this is the case I would explore trying to add `pokemon.resetTurnData()` during the EncounterPhase or the TurnStartPhase. This will require some experimentation to figure out the optimal location, you should also consult with some the devs about this.

2024-06-03 21:54 UTC, ElliottSimmonds commented on src/phases.ts
> +          }
Looking into it further, turnData being undefined isn't the real issue, but rather the turnData being reset in the `resetTurnData()` call in the `TurnInitPhase`.  Since on summon effects happen before, any changes to `statsBoosted` triggered by abilities such as download will be reset back to false. I'll defo need to give the devs a shout from the look of it

2024-06-11 19:06 UTC, ElliottSimmonds commented on src/phases.ts
> +          }
I have found using a battler tag instead provides a cleaner solution

2024-06-11 19:35 UTC, OrangeRed requested changes
Can you some tests that verify this works correctly?

2024-08-19 18:47 UTC, frutescens commented
Work continued in #3508

2024-08-19 18:47 UTC, closed without merging