[Ability] Implement the secondary effect with Super Luck and Compound Eyes
pagefaultgames/pokerogue pull request #1624
Opened 2024-05-31 00:27 UTC by EvasiveAce

## What are the changes?

Added the Gen VIII out of battle effect for Super Luck, and Compound Eyes:
### If a Pokémon with this Ability leads the [party](https://bulbapedia.bulbagarden.net/wiki/Party) (even if [fainted](https://bulbapedia.bulbagarden.net/wiki/Fainting)), the chances of finding [a wild Pokémon holding an item](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_wild_held_item) increase from 50%/5% to 60%/20%. This effect is shared with [Compound Eyes](https://bulbapedia.bulbagarden.net/wiki/Compound_Eyes_(Ability)).

## Why am I doing these changes?

Both Super Luck and Compound Eyes are partially implemented, so I thought I would fix them.

## What did change?

I added the 20% extra enemy held item modifier, so if you give `BonusItemChance` to an ability, it should make enemies 20% more likely to have a held item.

### Screenshots/Videos

Video of the chances of an enemy holding an item with Super Luck/Compound Eyes.

[Video](https://github.com/pagefaultgames/pokerogue/assets/71776311/e7d75b24-b05b-4781-a597-60e86e594346)

Video of the chances of an enemy holding an item without Super Luck/Compound Eyes.

[Video](https://github.com/pagefaultgames/pokerogue/assets/71776311/eb291c48-26cd-4f2a-bf1c-c61de8cad41c)

## How to test the changes?

Give yourself the ability Super Luck/Compound Eyes, and set some console.logs before the chances are set/changed in battle-phase.ts, and after they are set/changed. Check `BonusItemChance` documentation for more information.

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-03 19:04 UTC, OrangeRed approved these changes
Logically this looks fine. What remains is the decision of whether this is behavior is desirable.

2024-08-19 18:30 UTC, flx-sta commented
### Are you still working on this PR?
-----
No change since June 3 and open conflicts

2024-08-19 19:29 UTC, EvasiveAce commented
I am not currently working on this or #1927. Feel free to fork and fix the conflicts.

2024-08-25 00:24 UTC, flx-sta commented
> for now just close it and dont give them an effect at all until a better effect is thought up of
> since giving enemies items is just hurting the player more often then not
- Balance Team

2024-09-05 07:50 UTC, DayKev commented
![image](https://github.com/user-attachments/assets/34852e83-3aa4-4385-a282-cbdee5054253)

2024-09-05 08:07 UTC, torranx commented on src/battle-scene.ts
> +      if (this.getPlayerPokemon()?.getAbility().hasAttr(BonusItemChanceAbAttr) || this.getPlayerPokemon()?.getPassiveAbility().hasAttr(BonusItemChanceAbAttr)) {
i think `hasAbility` should cover both active and passive abilities

2024-09-05 08:12 UTC, innerthunder commented on src/battle-scene.ts
> +      if (this.getPlayerPokemon()?.getAbility().hasAttr(BonusItemChanceAbAttr) || this.getPlayerPokemon()?.getPassiveAbility().hasAttr(BonusItemChanceAbAttr)) {
```suggestion
      if (this.getPlayerPokemon()?.hasAbilityWithAttr(BonusItemChanceAbAttr)) {
```
better to use `hasAbilityWithAttr` here

2024-09-09 20:34 UTC, flx-sta requested changes
Just 2 minor NIT

2024-09-09 20:34 UTC, flx-sta commented on src/battle-scene.ts
> +        chances += Math.floor(chances * 1.2);
@DayKev should this live in a constant in `src/constants.ts`?

maybe move this one too then:
```ts
      if (isFinalBoss) {
        chances = Math.ceil(chances * 2.5);
      }
```

2024-09-10 09:43 UTC, DayKev commented on src/battle-scene.ts
> +        chances += Math.floor(chances * 1.2);
Replaced the magic numbers.

2024-09-12 15:52 UTC, flx-sta approved these changes

2024-09-12 19:58 UTC, flx-sta commented
Closed due to rejection by @pagefaultgames/balance-team .
If needed again re-open

2024-09-12 19:58 UTC, closed without merging