add type inference to getAttrs methods and refactor accordingly
pagefaultgames/pokerogue pull request #1633
Opened 2024-05-31 03:40 UTC by OrangeRed

## What are the changes?
Add type inference to `getAttrs` methods in `move.ts` and `ability.ts`

## Why am I doing these changes?
`as Type` assertions are dangerous and we should rely more on the typescript compiler

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-05-31 16:22 UTC, flx-sta requested changes

2024-05-31 16:22 UTC, flx-sta commented on src/data/ability.ts
> +  getAttrs<T extends AbAttr>(attrType: new(...args: any[]) => T ): T[] {
I know you didn't name this method but it could be confused with a getter for `this.atts`.
Maybe it should be renamed to `getAttrsOfType()` or the parameter should be made optional to return the whole `this.attrs` field (idk if that is needed)

2024-05-31 16:22 UTC, flx-sta commented on src/data/move.ts
> +  getAttrs<T extends MoveAttr>(attrType: new(...args: any[]) => T): T[] {
I know you didn't name this method but it could be confused with a getter for `this.atts`.
Maybe it should be renamed to `getAttrsOfType()` or the parameter should be made optional to return the whole `this.attrs` field (idk if that is needed)

2024-05-31 16:31 UTC, flx-sta commented
@OrangeRed https://github.com/OrangeRed/pokerogue/pull/1

2024-05-31 19:20 UTC, hayuna commented
@flx-sta If this test is for specific ability / move, could we start creating deeper structure?

src/tests/ability/Magician.test.ts
src/tests/move/RainDance.test.ts

Would be easier to future development to not store every ability tests in single one file.

2024-05-31 19:43 UTC, flx-sta commented
> @flx-sta If this test is for specific ability / move, could we start creating deeper structure?
> 
> src/tests/ability/Magician.test.ts src/tests/move/RainDance.test.ts
> 
> Would be easier to future development to not store every ability tests in single one file.

The abilities were chosen randomly. It is generally about testing the methods inside ability & move

2024-05-31 20:12 UTC, OrangeRed commented
To clear up any confusion I changed the tests to use `Ability.None` and `Move.None`. The id of the move doesn't really effect anything when it comes to testing its internal functionality so that should be a safe change to make.

2024-05-31 20:15 UTC, flx-sta commented
> To clear up any confusion I changed the tests to use `Ability.None` and `Move.None`. The id of the move doesn't really effect anything when it comes to testing its internal functionality so that should be a safe change to make.

Funny enough initially I went with these too.
But they I thought I should use some cooler Abilities. 
well... here we are :d

2024-05-31 20:15 UTC, flx-sta approved these changes

2024-05-31 20:16 UTC, flx-sta commented
@hayuna an approval (if you tested) is always appreciated ❤️

2024-05-31 22:09 UTC, bennybroseph requested changes
I'm very glad we've included tests for this change, but please split those tests off into a different PR as we have critiques which will prevent us from merging the change itself.

2024-05-31 22:14 UTC, flx-sta commented
> I'm very glad we've included tests for this change, but please split those tests off into a different PR as we have critiques which will prevent us from merging the change itself.

Ruthless 🗡️ . 
They were meant to provide coverage/leverage :D

2024-05-31 22:20 UTC, XGSleepWalker requested changes

2024-05-31 22:20 UTC, XGSleepWalker commented on src/test/ability.test.ts
This file structure will scale very poorly, I would rather bring a baseline that everyone can follow later on than building on top of this right now. Please remove the tests and we'll add them at a later stage.

2024-06-01 00:50 UTC, bennybroseph approved these changes

2024-06-01 00:50 UTC, merged