Disables all double battles but tate and Liza. And those two will now…
pagefaultgames/pokerogue pull request #1654
Opened 2024-05-31 14:57 UTC by CodeTappert

… always have lunatone and the other one (solrock?) as their first pokemon

## What are the changes?

We discussed in contribuer chat about it. The double battles destroy the balance. We want to keep them for a possible future mode. 
Only tate&liza should have a chance to appear at a 1/3 chance. 

## Why am I doing these changes?

Because we came to a conclusion to do so. And i was the person who introduced the double battle thing in the first place

## What did change?

The champs and piers/marnie can not longer appear in the double battles. 
And Tate&Liza now always have a solrock and lunatone as their first pokemon.

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/38758606/c1bd6479-cc4f-4b54-848c-3adf28604771

(Not quite sure how i would show the removal of the other double battles)

## How to test the changes?

Made Blue spawn as the champion (forced) for wave 190 several times. He didnt appear as a double even once.
Made Tate&Liza forced spawn as a double at wave 5 to see if the their first pokemon are always the ones we want

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-05-31 18:00 UTC, flx-sta requested changes

2024-05-31 18:00 UTC, flx-sta commented on src/field/trainer.ts
instead of hard-coding the trainers in the if and their pokemon I think it would make sense to create a matcher for it.
something along this
```ts
const variable_name: Record<TrainerType, Species[]> = {
  TrainerType.TATE: [ Species.SOLROCK ],
  TrainerType.LIZA: [ Species.LUNATONE ],
}
```

2024-05-31 18:12 UTC, CodeTappert commented on src/field/trainer.ts
Why? This will never get extended. 

The feature will remain unchanged until we, maybe, at some point do a "double classic" mode or something. 

And then the logic for building the team gets reworked completly.

2024-05-31 21:13 UTC, CodeTappert commented
To test just set the wave to 5 and then this line:
https://github.com/pagefaultgames/pokerogue/blob/fe34051687dd6720167b2eca6feaf42baa7904dc/src/battle.ts#L331

to  

```
    .setGetTrainerFunc(scene => new Trainer(scene, TrainerType.TATE, Utils.randSeedInt(2) ? TrainerVariant.DOUBLE : TrainerVariant.DOUBLE)),

```

2024-05-31 22:01 UTC, flx-sta approved these changes
lgtm 🚀 

<img width="1011" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/0bbed620-307b-4f10-ad10-271366d6cb06">

2024-06-01 12:17 UTC, CodeTappert commented
Maybe @bennybroseph can take a Look. Since you apporved the other PRs about that

2024-06-01 23:09 UTC, XGSleepWalker approved these changes

2024-06-01 23:15 UTC, merged