[Localization] [Balance] Toxic and Flame Orb odds small tweak, Spanish Localisation and entry to other Localisation files
pagefaultgames/pokerogue pull request #1668
Opened 2024-05-31 23:21 UTC by InnocentGameDev

## What are the changes?
This changes follow this PR https://github.com/pagefaultgames/pokerogue/pull/1574 . The things that are different are:

- Guts and Marvel Scale have their odds of flame orb raised to maximum (4, increasing to 32 with waves), and their odds of Toxic Orb decreased to minimum (1, increasing to 8 with waves). This is due to how one item is just better than the other for this mons, so we reconsidered adjusting the odds a bit more.

- Flame Orb's and Toxic Orb's localisation in Spanish is done.

- Flame Orb's and Toxic Orb's localisation was missing from the other languages as well, so I added it (in English) to be translated later by future PRs.

## Why am I doing these changes?
- A bit more "feels good" and less "feels bad" when finding these items.
- Spanish experience QoL
- QoL for future translators

## What did change?
Flame Orb weight multiplier on Guts, Marvel Scale: 2 -> 4 (same as Flare boost now)
Toxic Orb weight multiplier on Guts, Marvel Scale: 2 -> 1  (same as the moves in the code)

## How to test the changes?
Open up the game and roll with infinite money override until you hit the items. Often times, you should see a Flame Orb much sooner than a Toxic Orb, if you are running a Guts or Marvel Scale Pokémon.

## Checklist
- [X] There is no overlap with another PR? No, I discussed changes with the author
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)? Not the localisations
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes? Haven't tested the localisations as I assume they're fine

2024-05-31 23:22 UTC, InnocentGameDev commented
Please do not approve yet, as I need to re-copy paste the English translation to the Bulbapedia's one.

2024-05-31 23:24 UTC, Dakurei requested changes
French translations from Pokémon Scarlet and Violet dumps

2024-05-31 23:24 UTC, Dakurei commented on src/locales/fr/modifier-type.ts
> +    "TOXIC_ORB": { name: "Toxic Orb", description: "Badly poisons its holder at the end of the turn if they do not have a status condition already" },
```suggestion
    "TOXIC_ORB": { name: "Orbe Toxique", description: "Un orbe bizarre qui empoisonne gravement son porteur durant le combat." },
```

2024-05-31 23:24 UTC, Dakurei commented on src/locales/fr/modifier-type.ts
> +    "FLAME_ORB": { name: "Flame Orb", description: "Burns its holder at the end of the turn if they do not have a status condition already" },
```suggestion
    "FLAME_ORB": { name: "Orbe Flamme", description: "Un orbe bizarre qui brûle son porteur durant le combat." },
```

2024-05-31 23:53 UTC, Dakurei requested changes
Italian translations from Pokémon Scarlet and Violet dumps

![image](https://github.com/pagefaultgames/pokerogue/assets/8146474/2080fd3c-195c-4bb4-b031-a23d72b70057)

2024-05-31 23:53 UTC, Dakurei commented on src/locales/it/modifier-type.ts
> +    "TOXIC_ORB": { name: "Toxic Orb", description: "It's a bizarre orb that exudes toxins when touched and will badly poison the holder during battle" },
```suggestion
    "TOXIC_ORB": { name: "Tossicsfera", description: "Sfera bizzarra che iperavvelena chi l’ha con sé in una lotta" },
```

2024-05-31 23:53 UTC, Dakurei commented on src/locales/it/modifier-type.ts
> +    "FLAME_ORB": { name: "Flame Orb", description: "It's a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle" },
```suggestion
    "FLAME_ORB": { name: "Fiammosfera", description: "Sfera bizzarra che procura una scottatura a chi l’ha con sé in una lotta" },
```

2024-06-01 00:12 UTC, Dakurei requested changes
Mixing error

2024-06-01 00:12 UTC, Dakurei commented on src/locales/pt_BR/modifier-type.ts
> +    "TOXIC_ORB": { name: "Heiß-Orb", description: "It's a bizarre orb that exudes toxins when touched and will badly poison the holder during battle" },
```suggestion
    "TOXIC_ORB": { name: "Toxic Orb", description: "It's a bizarre orb that exudes toxins when touched and will badly poison the holder during battle" },
```

2024-06-01 00:12 UTC, Dakurei commented on src/locales/pt_BR/modifier-type.ts
> +    "FLAME_ORB": { name: "Toxik-Orb", description: "It's a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle" },
```suggestion
    "FLAME_ORB": { name: "Flame Orb", description: "It's a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle" },
```

2024-06-01 00:22 UTC, InnocentGameDev commented
It's good to go, imo

2024-06-01 00:28 UTC, Dakurei commented
> It's good to go, imo

You're missing the 2 suggestions above
You made a little mix in a file 🤣

2024-06-01 00:53 UTC, Tempo-anon commented on src/locales/de/modifier-type.ts
> +    "FLAME_ORB": { name: "Toxik-Orb", description: "It's a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle" },
These are also swapped

2024-06-01 00:54 UTC, Tempo-anon requested changes
Fix typos, also change the PR title to reflect only localization changes

2024-06-01 06:25 UTC, CodeTappert commented on src/locales/de/modifier-type.ts
> +    "FLAME_ORB": { name: "Toxik-Orb", description: "It's a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle" },
It would need to be:
```suggestion
    "TOXIC_ORB": { name: "Heiß-Orb", description: "It's a bizarre orb that exudes toxins when touched and will badly poison the holder during battle" },
    "FLAME_ORB": { name: "Toxik-Orb", description: "It's a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle" },
```
    "TOXIC_ORB": { name: "Toxik-Orb", description: "Ein Item zum Tragen. Dieser bizarre Orb vergiftet seinen Träger im Kampf schwer." },
    "FLAME_ORB": { name: "Heiß-Orb", description: "Ein Item zum Tragen. Dieser bizarre Orb fügt seinem Träger im Kampf Verbrennungen zu." },

2024-06-01 06:29 UTC, CodeTappert commented on src/locales/de/modifier-type.ts
> +    "FLAME_ORB": { name: "Toxik-Orb", description: "It's a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle" },
Source https://www.pokewiki.de/Toxik-Orb and https://www.pokewiki.de/Hei%C3%9F-Orb

2024-06-01 11:01 UTC, InnocentGameDev commented
Sorry for the mistakes, was super tired last night. Everything should be now fine -- barring the missing translations. Let me know if there any mistakes or points of disagreement.

A note on the description/descriptions: Spanish file had no "." in the item descriptions whatsoever, and neither did English and French (off the top of my head). Italian was 50/50. Also in item's descriptions, most items that would contain "an item to be held by a Pokémon" (something that just seems obvious in this game) didn't have said part, so I also didn't implement it in Flame and Toxic Orb's. Otherwise it's exactly as in S/V.

All these translation choices were carried over to the other files if it made sense, to the best of my abilities -- ie, I checked that other German descriptions didn't have "." before I took out the ones @CodeTappert suggested and I also ctrl-f for the "to be held by a Pokémon" part, which I didn't find anywhere else.

2024-06-01 11:34 UTC, CodeTappert commented on src/locales/de/modifier-type.ts
> +    "FLAME_ORB": { name: "Toxik-Orb", description: "It's a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle" },
> It would need to be:
> ```suggestion
>     "TOXIC_ORB": { name: "Toxik-Orb", description: "Ein Item zum Tragen. Dieser bizarre Orb vergiftet seinen Träger im Kampf schwer." },
>     "FLAME_ORB": { name: "Heiß-Orb", description: "Ein Item zum Tragen. Dieser bizarre Orb fügt seinem Träger im Kampf Verbrennungen zu." },
> ```
> 

Please make it EXACTLY like i wrote it (unless it is to Long to fit). This is directly from the game

2024-06-01 11:42 UTC, InnocentGameDev commented
@Tempo-anon I have no idea how to revert this commit 6fc9a651d8f268ab1d98cfeca7a0963b4f8b8a47

It's proposing to delete the ko file, I just wanted to remove my changes since I saw a merge conflict with someone else that had already done the localisation

2024-06-01 15:16 UTC, Tempo-anon commented
> @Tempo-anon I have no idea how to revert this commit [6fc9a65](https://github.com/pagefaultgames/pokerogue/commit/6fc9a651d8f268ab1d98cfeca7a0963b4f8b8a47)
> 
> It's proposing to delete the ko file, I just wanted to remove my changes since I saw a merge conflict with someone else that had already done the localisation

I added it back, but in the future you should learn how to git revert

2024-06-01 15:23 UTC, Dakurei commented on src/locales/de/modifier-type.ts
> +    "FLAME_ORB": { name: "Toxik-Orb", description: "It's a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle" },
> > It would need to be:
> 
> Please make it EXACTLY like i wrote it (unless it is to Long to fit). This is directly from the game

It was decided to remove this part of the description because in this game an object can only be held, there is no concept of a bag.

2024-06-01 15:25 UTC, Tempo-anon approved these changes
Good enough for now. Adding periods to all the localization can be done in a later PR

2024-06-01 15:25 UTC, merged