[Move] Implemented Incinerate and Knock Off
pagefaultgames/pokerogue pull request #1671
Opened 2024-06-01 01:06 UTC by Arxalc

## What are the changes?

Incinerate incinerates berries. Knock off removes items and boosts power as expected.

## Why am I doing these changes?

This [PR](https://github.com/pagefaultgames/pokerogue/pull/1525) and [PR](https://github.com/pagefaultgames/pokerogue/pull/1253) cover the same thing, but I believe this implementation is more complete.

## What did change?

* Incinerate successfully burns up berries
* Knock off removes _removeable_ items 
* Knock off's power boost only applies when an item can be knocked off
* Items have an equal, random chance of being removed (unlike Thief and Covet which prioritize higher tier items - idk if that was intentional or not, but I'm not messing with that)

_Note: There are 2 unimplemented edge cases which apply to Thief as well. It's unlikely to occur, so I'm submitting this for now. These are commented in for the future.
"If the user faints due to the target's Ability (Rough Skin or Iron Barbs) or held Rocky Helmet, it cannot remove the target's held item."
"If Knock Off causes a Pokémon with the Sticky Hold Ability to faint, it can now remove that Pokémon's held item."_

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/63990624/a47cf2f5-0e20-4648-841c-2fb1a1b25ec8
_Incinerate only incinerates berries. Knock off power varies._
https://github.com/pagefaultgames/pokerogue/assets/63990624/a43266aa-d7d3-496a-8b98-ee45f021e463
_Yes, focus band can activate before being knocked off as intended._

## How to test the changes?

Override opponent held items to berries and other items. Override starter moves for Incinerate and Knock Off.

## Checklist
- [See Above] There is no overlap with another PR?
- [*] The PR is self-contained and cannot be split into smaller PRs?
- [*] Have I provided a clear explanation of the changes?
- [*] Have I tested the changes (manually)?
    - [*] Are all unit tests still passing? (`npm run test`)
- [*] Are the changes visual?
  - [*] Have I provided screenshots/videos of the changes?

2024-06-01 02:38 UTC, MPekelny commented
I agree, this is a more complete implementation than mine, so this is the PR that should get merged. I will close mine. 

The only thing is I believe because there are edge cases not handled, even though it is 99% implemented, it still needs to be marked as partial. A lead dev can confirm if this is the case.

2024-06-02 05:28 UTC, innerthunder commented on src/data/move.ts
> +      if (!this.berriesOnly && target.isPlayer()) { // Wild Pokemon cannot knock off Player Pokemon's held items.
Not sure if disabling this entirely against player Pokemon is the way to go. Limiting this effect to only remove berries on player Pokemon seems like a good middle ground; it would prevent the player from losing key/rare items while staying more faithful to the move's functionality.

2024-06-02 17:16 UTC, Arxalc commented on src/data/move.ts
> +      if (!this.berriesOnly && target.isPlayer()) { // Wild Pokemon cannot knock off Player Pokemon's held items.
I was following the wiki ["Wild Pokémon cannot remove held items of the player's Pokémon."](https://bulbapedia.bulbagarden.net/wiki/Knock_Off_(move)) but I can change it if desired for PokeRogue's balancing.

2024-06-02 18:25 UTC, Arxalc commented on src/data/move.ts
> +  constructor(berriesOnly: boolean) { // Optional restriction for item pool to berries only i.e. Differentiating Incinerate and Knock Off
Done. Should be ready to review again.
Kept opponents being unable to knock off player items as is. Unless specified by you.

2024-06-03 00:45 UTC, OrangeRed requested changes

2024-06-03 00:45 UTC, OrangeRed commented on src/data/move.ts
> +        heldItems = heldItems.filter(m => m instanceof BerryModifier && (m as BerryModifier).pokemonId === target.id, target.isPlayer());
You don't need this `m as BerryModifier`. Because you did `m instanceof BerryModifier` right before this typescript is smart enough to infer the type of `m` without you telling it using `as`

2024-06-05 17:42 UTC, Fractaos commented on src/data/move.ts
> +          target.scene.removeModifier(removedItem, !target.isPlayer());
I think it's "important" to check if the item has properly been removed (the return of the `removeModifier` method) to avoid displaying the message once the target pokemon is dead for instance.

I'm not 100% sure so it needs to be verified but if you don't do this check you might have the message that get displayed even if nothing got actually removed due to K.O before being applied.

2024-06-05 17:42 UTC, Fractaos commented
I also do agree that this is a more complete implemention of my own PR, which I'll close, thanks for the contribution 👍

2024-06-05 22:01 UTC, Arxalc commented on src/data/move.ts
> +          target.scene.removeModifier(removedItem, !target.isPlayer());
...After reviewing the removeModifier method, I realized it's seeing whether it's removing a form-changing/Tera Shard item. Because we've already filtered out those items, this check is actually useless so I'm removing it.

I have double checked that items will be still be removed if the target faints.

2024-06-08 19:46 UTC, Fractaos approved these changes
LGTM

2024-06-16 02:26 UTC, Tempo-anon approved these changes

2024-06-16 02:26 UTC, merged