Don't offer ball rewards past floor 189
pagefaultgames/pokerogue pull request #1677
Opened 2024-06-01 04:35 UTC by Fontbane

This PR removes balls from the reward pool from wave 189 onwards in classic, as they're no longer usable after that.

2024-06-01 04:50 UTC, Tempo-anon commented
Can you please fill out the PR description properly? And also include some screenshots/videos of testing where you override a bunch of money at floors 190+ and reroll a bunch of times?

2024-06-01 05:24 UTC, HighMans commented
> This PR removes balls from the reward pool from wave 189 onwards in classic, as they're no longer usable after that.

Is that true though? You can capture paradox-mon that you've got as starters.

2024-06-01 05:35 UTC, Fontbane commented
> > This PR removes balls from the reward pool from wave 189 onwards in classic, as they're no longer usable after that.
> 
> Is that true though? You can capture paradox-mon that you've got as starters, no?

Only if they're shiny

2024-06-01 05:37 UTC, HighMans commented
> > > This PR removes balls from the reward pool from wave 189 onwards in classic, as they're no longer usable after that.
> > 
> > 
> > Is that true though? You can capture paradox-mon that you've got as starters, no?
> 
> Only if they're shiny, but that rare edge case isn't worth the hindrance on most other runs.

That's not true, I'm 99% sure I've caught Iron Bundle with a master ball during a classic run that wasn't shiny.

2024-06-01 06:47 UTC, flx-sta requested changes
You should put the wave number into a descriptive variable.
Something like:
```ts
CLASSIC_POKEBALL_REWARD_MAX_WAVE=  184
```

maybe something shorter

2024-06-01 06:56 UTC, RNGezeus commented
> > > This PR removes balls from the reward pool from wave 189 onwards in classic, as they're no longer usable after that.
> > 
> > 
> > Is that true though? You can capture paradox-mon that you've got as starters, no?
> 
> Only if they're shiny, but that rare edge case isn't worth the hindrance on most other runs.

 Thats false, you can capture non-shiny paradoxes as well, provided  hatched them first.

Its one of the side reasons to run Classic very late in your collection, to scan paradoxes to improve their IVs

2024-06-01 20:25 UTC, Tempo-anon requested changes
This makes changes to classic _and_ endless which seems like it'd be larger than the initial scope especially since endless lets players farm items/balls pretty easily and this will change pool weights.

Also, you still haven't filled out the proper PR template along with proof of testing

2024-06-01 20:43 UTC, Fontbane commented
> This makes changes to classic _and_ endless which seems like it'd be larger than the initial scope especially since endless lets players farm items/balls pretty easily and this will change pool weights.
> 
> Also, you still haven't filled out the proper PR template along with proof of testing

Should I make it classic-only then? Or should it just be classic-only for the higher tiers, and the same changes would apply to only red balls in endless?

2024-06-04 17:57 UTC, brain-frog requested changes

2024-06-04 17:57 UTC, brain-frog commented on src/modifier/modifier-type.ts
If the same arrow function is being used every time can this just be converted into a reusable function above and used as a parameter
also please create a descriptive const for 99 since its being used every time
`MAX_BALL_COUNT` or something similar

2024-06-12 01:45 UTC, Tempo-anon commented on src/modifier/modifier-type.ts
> +function CheckForMaximumBalls(party: Pokemon[], ballType: PokeballType): boolean {
1. Should add documentation to new functions
2. Since this is a function the first letter should not be capitalized
3. A boolean function should make it clear it returns a boolean `hasMaximumBalls` for example

2024-06-24 23:37 UTC, brain-frog commented on src/modifier/modifier-type.ts
> + * Used to check if the player has max of a given ball type
specify this is for classic in comment please

2024-06-28 03:55 UTC, flx-sta commented
@Fontbane Marks as resolved when done 
<img width="197" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/3a45acaa-b66c-4b00-acd0-393181d75592">

2024-06-28 15:59 UTC, brain-frog approved these changes

2024-06-28 16:01 UTC, Tempo-anon approved these changes

2024-06-28 16:11 UTC, merged