[Localization] Implement pokemon forms localization
pagefaultgames/pokerogue pull request #1685
Opened 2024-06-01 11:24 UTC by Kiriox94

## What are the changes?
Localization of pokemon forms in the starter selection menu and in battles

## Why am I doing these changes?
So that the whole game can be localized in one day, and also because it was requested here #339

## What did change?
The strings for displaying forms are now retrieved from src/locales/{your language}/pokemon-form.ts and no longer raw in the code.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

2024-06-01 13:04 UTC, Adri1 commented
I created a PR to your branch with French traslations

2024-06-01 16:26 UTC, returntoice requested changes

2024-06-01 17:39 UTC, Kiriox94 commented
Thank you for your contribution @returntoice, next time if you could go through a pull request, it would be easier

2024-06-01 17:59 UTC, Kiriox94 commented
> Sorry I am not that familiar with the Github system. Is is right that I'd have been better off making a new PR and merging with this PR?

Oui en faisant une pull request sur ma branche ça aurait permis d'ajouter toutes les modifications d'un coup, mais le résultat est le même

2024-06-01 18:01 UTC, Adri1 commented
I juste pushed a new PR tout your branch to correct a typo

2024-06-02 07:29 UTC, CodeTappert commented
Could you please provide some screenshots about where they are used? I am about to provide a PR with the german localization but some form names depend on where they are shown.

2024-06-02 07:35 UTC, CodeTappert commented
> Could you please provide some screenshots about where they are used? I am about to provide a PR with the german localization but some form names depend on where they are shown.

For example
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/ec027fc5-43b8-44e5-b773-a0da9f28a654)

needs to be 
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/32fcbbcb-2e3f-4dc0-95e5-ab9bae3d7d9a)

in german. 

But could also be written as for example "Pikachu (Rocker)"

2024-06-02 07:44 UTC, CodeTappert commented
Maybe you could just include the "{{pokemonName}}" thing in all localization strings so every language can build the name like it has to. And it is more clear

2024-06-02 08:51 UTC, CodeTappert commented
You are missing some forms:
- Deoxys Forms
- Cherrim Forms
- Origin Forms for Palkia, Dialga, Girantina
- Shaymins alternative form
- (if needed the arceus forms)
- Darmanitan trance mode
- The animal spirt forms of Tornadus, Thundurus, Landorus and Enamorus
- Kyurem (White/Black)
- Keldeo Resolutform
- Meloetta Dancingform
- Genesect: Schock Drive, Burn Drive, ChillDrive, Douse Drive
- Furfrou (Natural Form)
- Aegislash (blade/shieldform)
- pumpkaboo (Medium)
- eiscue iceform
-  Sinistcha Unremarkable Form. Masterpiece Form
- No localizatiotion for the forms of Lycanroc
- Hoopa (Confined/Unbound)
- Mimikyu (Disguised/Busted)
- Wishiwashi: Schoolform/Soloform
- Silvally Forms
- Necrozma: Fusion with Solgaleo, Fusion with Lunala, Ultra Necrozma
- Cramorant: Gulping Form/Gorging Form
- Morpeko: Full-Belly Mode, Hangry Mode
- Zacian: Hero of Many Battles / Crowned Sword
- Zamazenta: Hero of Many Battles / Crowned Shield
- Calyrex: Ice Rider Calyrex / Shadow Rider Carylex
- Palafin: Heroform
- Ogerpon: Teal Mask/Wellspring Mask/Hearthflame Mask/Cornerstone Mask
- Terapagos: Terastal Form/Stellarform
- Partner Evee, Partner Pikachu
- Pikachu with the Caps
- Toxtricity: Highform/Lowform
- Urshifu: Rapid Style Strike, Single Style Strike
- Ursaluna: Bloodmoon form

2024-06-02 08:54 UTC, CodeTappert commented
German PR is here: https://github.com/Kiriox94/pokerogue/pull/4

2024-06-02 14:35 UTC, Kiriox94 commented
@Adri1 @CodeTappert @MrWaterT 
I forgot these 3 forms, for the others they either come from an evolution or the pokemon can transform into this form only in combat, so there is no interest in implementing them currently 

- Pikachu Partner line 20
- Eevee Partner line 21
- Mimikyu Disguised line 141
- Mimikyu Busted line 142

2024-06-02 15:22 UTC, CodeTappert commented
> @Adri1 @CodeTappert @MrWaterT I forgot these 3 forms, for the others they either come from an evolution or the pokemon can transform into this form only in combat, so there is no interest in implementing them currently
> 
> * Pikachu Partner line 20
> * Eevee Partner line 21
> * Mimikyu Disguised line 141
> * Mimikyu Busted line 142

https://github.com/Kiriox94/pokerogue/pull/5/files

2024-06-02 15:54 UTC, Adri1 commented
Update French PR submitted

2024-06-04 16:15 UTC, flx-sta requested changes

2024-06-04 16:15 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +          this.pokemonFormText.setText(formText?.join("") ? i18next.t(`pokemonForm:${speciesName.join("")}${formText?.join("")}`) : "");
```suggestion
          this.pokemonFormText.setText(formText?.join("") ? i18next.t(`pokemonForm:${speciesName.join("")}${formText.join("")}`) : "");
```
The second `?` shouldn't be necessary as you checked that in the condition alreadty

2024-06-04 16:17 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +        }
Using a `switch-case` seems a bit of an overload for me. 
maybe using an `if-case` might be the better choise as you have only 1 case + else

2024-06-06 15:22 UTC, bennybroseph approved these changes

2024-06-12 16:59 UTC, Kiriox94 commented
@bennybroseph Is it normal that the changes were not committed on the main branch?

2024-06-26 12:24 UTC, Adri1 reviewed
French tiny corrections

2024-06-26 12:24 UTC, Adri1 commented on src/locales/fr/pokemon-form.ts
> +  "castformRainy": "Pluie",
```suggestion
  "castformRainy": "Eau de Pluie",
```

2024-06-26 12:24 UTC, Adri1 commented on src/locales/fr/pokemon-form.ts
> +  "furfrouHeart": "Heart",
```suggestion
  "furfrouHeart": "Cœur",
```

2024-06-26 17:58 UTC, flx-sta commented
@Kiriox94 make sure to resolve those typedoc issues
https://github.com/pagefaultgames/pokerogue/actions/runs/9684296001/job/26721713817?pr=1685

2024-06-26 18:39 UTC, josericardo-fo commented on src/locales/pt_BR/pokemon-form.ts
> +  "primal": "Primal {{pokemonName}}",
```suggestion
  "primal": "{{pokemonName}} Primordial",
```

2024-06-26 18:44 UTC, josericardo-fo commented on src/locales/pt_BR/pokemon-form.ts
> +  "eeveePartner": "Partner",
```suggestion
  "pikachuCoolCosplay": "Cosplay Legal",
  "pikachuBeautyCosplay": "Cosplay Bonito",
  "pikachuCuteCosplay": "Cosplay Fofo",
  "pikachuSmartCosplay": "Cosplay Inteligente",
  "pikachuToughCosplay": "Cosplay Forte",
  "pikachuPartner": "Parceiro",
  "eeveePartner": "Parceiro",
```

2024-06-26 18:45 UTC, josericardo-fo commented on src/locales/pt_BR/pokemon-form.ts
> +  "castformSnowy": "Snowy",
```suggestion
  "castformSunny": "Ensolarado",
  "castformRainy": "Chuvoso",
  "castformSnowy": "Nevado",
```

2024-06-26 18:48 UTC, josericardo-fo commented on src/locales/pt_BR/pokemon-form.ts
> +  "rotomMow": "Mow",
```suggestion
  "burmyPlant": "Vegetal",
  "burmySandy": "Arenoso",
  "burmyTrash": "Lixo",
  "shellosEast": "Leste",
  "shellosWest": "Oeste",
  "rotomHeat": "Calor",
  "rotomWash": "Lavagem",
  "rotomFrost": "Congelante",
  "rotomFan": "Ventilador",
  "rotomMow": "Corte",
```

2024-06-26 19:05 UTC, 40chyan commented on src/locales/zh_CN/pokemon-form.ts
> +  "paldeaTaurosAqua": "Aqua",
```suggestion
  "pikachuCosplay": "服装",
  "pikachuCoolCosplay": "摇滚巨星",
  "pikachuBeautyCosplay": "贵妇",
  "pikachuCuteCosplay": "流行偶像",
  "pikachuSmartCosplay": "博士",
  "pikachuToughCosplay": "面罩摔跤手",
  "pikachuPartner": "搭档",
  "eeveePartner": "搭档",
  // 2G
  "pichuSpiky": "刺刺耳",
  "unownA": "A",
  "unownB": "B",
  "unownC": "C",
  "unownD": "D",
  "unownE": "E",
  "unownF": "F",
  "unownG": "G",
  "unownH": "H",
  "unownI": "I",
  "unownJ": "J",
  "unownK": "K",
  "unownL": "L",
  "unownM": "M",
  "unownN": "N",
  "unownO": "O",
  "unownP": "P",
  "unownQ": "Q",
  "unownR": "R",
  "unownS": "S",
  "unownT": "T",
  "unownU": "U",
  "unownV": "V",
  "unownW": "W",
  "unownX": "X",
  "unownY": "Y",
  "unownZ": "Z",
  "unownExclamation": "!",
  "unownQuestion": "?",
  // 3G
  "castformSunny": "晴天",
  "castformRainy": "雨天",
  "castformSnowy": "雪天",
  // 4G
  "burmyPlant": "草木蓑衣",
  "burmySandy": "砂土蓑衣",
  "burmyTrash": "垃圾蓑衣",
  "shellosEast": "东海",
  "shellosWest": "西海",
  "rotomHeat": "加热",
  "rotomWash": "清洗",
  "rotomFrost": "结冰",
  "rotomFan": "旋转",
  "rotomMow": "切割",
  // 5G
  "basculinRedStriped": "红条纹",
  "basculinBlueStriped": "蓝条纹",
  "basculinWhiteStriped": "白条纹",
  "deerlingSpring": "春天",
  "deerlingSummer": "夏天",
  "deerlingAutumn": "秋天",
  "deerlingWinter": "冬天",
  // 6G
  "froakieBattleBond": "牵绊变身",
  "scatterbugMeadow": "花园花纹",
  "scatterbugIcySnow": "冰雪花纹",
  "scatterbugPolar": "雪国花纹",
  "scatterbugTundra": "雪原花纹",
  "scatterbugContinental": "大陆花纹",
  "scatterbugGarden": "庭园花纹",
  "scatterbugElegant": "高雅花纹",
  "scatterbugModern": "摩登花纹",
  "scatterbugMarine": "大海花纹",
  "scatterbugArchipelago": "群岛花纹",
  "scatterbugHighPlains": "荒野花纹",
  "scatterbugSandstorm": "沙尘花纹",
  "scatterbugRiver": "大河花纹",
  "scatterbugMonsoon": "骤雨花纹",
  "scatterbugSavanna": "热带草原花纹",
  "scatterbugSun": "太阳花纹",
  "scatterbugOcean": "大洋花纹",
  "scatterbugJungle": "热带雨林花纹",
  "scatterbugFancy": "幻彩花纹",
  "scatterbugPokeBall": "球球花纹",
  "flabebeRed": "红花",
  "flabebeYellow": "黄花",
  "flabebeOrange": "橙花",
  "flabebeBlue": "蓝花",
  "flabebeWhite": "白花",
  "furfrouHeart": "心形造型",
  "furfrouStar": "星形造型",
  "furfrouDiamond": "菱形造型",
  "furfrouDebutante": "淑女造型",
  "furfrouMatron": "贵妇造型",
  "furfrouDandy": "绅士造型",
  "furfrouLaReine": "女王造型",
  "furfrouKabuki": "歌舞伎造型",
  "furfrouPharaoh": "国王造型",
  "pumpkabooSmall": "小尺寸",
  "pumpkabooLarge": "大尺寸",
  "pumpkabooSuper": "特大尺寸",
  "xerneasNeutral": "放松模式",
  "xerneasActive": "活跃模式",
  "zygarde50": "５０％形态",
  "zygarde10": "１０％形态",
  "zygarde50Pc": "５０％形态 群聚变形",
  "zygarde10Pc": "１０％形态 群聚变形",
  "zygardeComplete": "完全体形态",
  // 7G
  "oricorioBaile": "热辣热辣风格",
  "oricorioPompom": "啪滋啪滋风格",
  "oricorioPau": "呼拉呼拉风格",
  "oricorioSensu": "轻盈轻盈风格",
  "rockruffOwnTempo": "特殊岩狗狗",
  "miniorRedMeteor": "红色核心",
  "miniorOrangeMeteor": "橙色核心",
  "miniorYellowMeteor": "黄色核心",
  "miniorGreenMeteor": "绿色核心",
  "miniorBlueMeteor": "浅蓝色核心",
  "miniorIndigoMeteor": "蓝色核心",
  "miniorVioletMeteor": "紫色核心",
  "miniorRed": "红色",
  "miniorOrange": "橙色",
  "miniorYellow": "黄色",
  "miniorGreen": "绿色",
  "miniorBlue": "浅蓝色",
  "miniorIndigo": "蓝色",
  "miniorViolet": "紫色",
  "mimikyuDisguised": "化形",
  "mimikyuBusted": "现形",
  "magearnaOriginal": "500年前的颜色",
  "marshadowZenith": "全力",
  // 8G
  "sinisteaPhony": "赝品",
  "sinisteaAntique": "真品",
  "eiscueNoIce": "解冻头",
  "indeedeeMale": "雄性",
  "indeedeeFemale": "雌性",
  "zarudeDada": "老爹",
  // 9G
  "squawkabillyGreenPlumage": "绿羽毛",
  "squawkabillyBluePlumage": "蓝羽毛",
  "squawkabillyYellowPlumage": "黄羽毛",
  "squawkabillyWhitePlumage": "白羽毛",
  "tatsugiriCurly": "上弓姿势",
  "tatsugiriDroopy": "下垂姿势",
  "tatsugiriStretchy": "平挺姿势",
  "gimmighoulChest": "宝箱形态",
  "gimmighoulRoaming": "徒步形态",
  "poltchageistCounterfeit": "冒牌货",
  "poltchageistArtisan": "高档货",
  "paldeaTaurosCombat": "斗战种",
  "paldeaTaurosBlaze": "火炽种",
  "paldeaTaurosAqua": "水澜种",
```
cn translation

2024-06-26 21:13 UTC, josericardo-fo commented on src/locales/pt_BR/pokemon-form.ts
> +  "paldeaTaurosAqua": "Aqua",
```suggestion
  "basculinRedStriped": "Listras Vermelhas",
  "basculinBlueStriped": "Listras Azuis",
  "basculinWhiteStriped": "Listras Brancas",
  "deerlingSpring": "Primavera",
  "deerlingSummer": "Verão",
  "deerlingAutumn": "Outono",
  "deerlingWinter": "Inverno",
  // 6G
  "froakieBattleBond": "Vínculo de Batalha",
  "scatterbugMeadow": "Prado",
  "scatterbugIcySnow": "Neve Congelada",
  "scatterbugPolar": "Polar",
  "scatterbugTundra": "Tundra",
  "scatterbugContinental": "Continental",
  "scatterbugGarden": "Jardim",
  "scatterbugElegant": "Elegante",
  "scatterbugModern": "Moderno",
  "scatterbugMarine": "Marinho",
  "scatterbugArchipelago": "Arquipélago",
  "scatterbugHighPlains": "Planalto",
  "scatterbugSandstorm": "Deserto",
  "scatterbugRiver": "Rio",
  "scatterbugMonsoon": "Monção",
  "scatterbugSavanna": "Savana",
  "scatterbugSun": "Solar",
  "scatterbugOcean": "Oceano",
  "scatterbugJungle": "Selva",
  "scatterbugFancy": "Chique",
  "scatterbugPokeBall": "Poké Bola",
  "flabebeRed": "Vermelha",
  "flabebeYellow": "Amarela",
  "flabebeOrange": "Laranja",
  "flabebeBlue": "Azul",
  "flabebeWhite": "Branca",
  "furfrouHeart": "Coração",
  "furfrouStar": "Estrela",
  "furfrouDiamond": "Diamante",
  "furfrouDebutante": "Debutante",
  "furfrouMatron": "Madame",
  "furfrouDandy": "Cavalheiro",
  "furfrouLaReine": "Aristocrático",
  "furfrouKabuki": "Kabuki",
  "furfrouPharaoh": "Faraó",
  "pumpkabooSmall": "Pequeno",
  "pumpkabooLarge": "Grande",
  "pumpkabooSuper": "Extragrande",
  "xerneasNeutral": "Relaxado",
  "xerneasActive": "Ativo",
  "zygarde50": "Forma 50%",
  "zygarde10": "Forma 10%",
  "zygarde50Pc": "Forma 50% Agrupada",
  "zygarde10Pc": "Forma 10% Agrupada",
  "zygardeComplete": "Forma Completa",
  // 7G
  "oricorioBaile": "Flamenco",
  "oricorioPompom": "Pompom",
  "oricorioPau": "Hula",
  "oricorioSensu": "Leque",
  "rockruffOwnTempo": "Próprio Tempo",
  "miniorRedMeteor": "Meteoro Vermelho",
  "miniorOrangeMeteor": "Meteoro Laranja",
  "miniorYellowMeteor": "Meteoro Amarelo",
  "miniorGreenMeteor": "Meteoro Verde",
  "miniorBlueMeteor": "Meteoro Azul",
  "miniorIndigoMeteor": "Meteoro Anil",
  "miniorVioletMeteor": "Meteoro Violeta",
  "miniorRed": "Vermelho",
  "miniorOrange": "Laranja",
  "miniorYellow": "Amarelo",
  "miniorGreen": "Verde",
  "miniorBlue": "Azul",
  "miniorIndigo": "Anil",
  "miniorViolet": "Violeta",
  "mimikyuDisguised": "Disfarçado",
  "mimikyuBusted": "Descoberto",
  "magearnaOriginal": "Original",
  "marshadowZenith": "Zênite",
  // 8G
  "sinisteaPhony": "Falsificado",
  "sinisteaAntique": "Autêntico",
  "eiscueNoIce": "Descongelado",
  "indeedeeMale": "Macho",
  "indeedeeFemale": "Fêmea",
  "zarudeDada": "Papa",
  // 9G
  "squawkabillyGreenPlumage": "Plumas Verdes",
  "squawkabillyBluePlumage": "Plumas Azuis",
  "squawkabillyYellowPlumage": "Plumas Amarelas",
  "squawkabillyWhitePlumage": "Plumas Brancas",
  "tatsugiriCurly": "Curvado",
  "tatsugiriDroopy": "Caído",
  "tatsugiriStretchy": "Reto",
  "gimmighoulChest": "Baú",
  "gimmighoulRoaming": "Perambulante",
  "poltchageistCounterfeit": "Imitação",
  "poltchageistArtisan": "Artesão",
  "paldeaTaurosCombat": "Combate",
  "paldeaTaurosBlaze": "Chamas",
  "paldeaTaurosAqua": "Aquático",
```

2024-06-27 09:19 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "castformSnowy": "Snowy",
```suggestion
  "castformSunny": "Sol",
  "castformRainy": "Lluvia",
  "castformSnowy": "Nieve",
```

2024-06-27 09:19 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "burmyTrash": "Trash",
```suggestion
  "burmyPlant": "Planta",
  "burmySandy": "Arena",
  "burmyTrash": "Basura",
```

2024-06-27 09:22 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "rotomMow": "Mow",
```suggestion
  "rotomHeat": "Calor",
  "rotomWash": "Lavado",
  "rotomFrost": "Frío",
  "rotomFan": "Ventilador",
  "rotomMow": "Corte",
```

2024-06-27 09:22 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "basculinWhiteStriped": "White Striped",
```suggestion
  "basculinRedStriped": "Raya Roja",
  "basculinBlueStriped": "Raya Azul",
  "basculinWhiteStriped": "Raya Blanca",
```

2024-06-27 09:23 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "deerlingWinter": "Winter",
```suggestion
  "deerlingSpring": "Primavera",
  "deerlingSummer": "Verano",
  "deerlingAutumn": "Otoño",
  "deerlingWinter": "Invierno",
```

2024-06-27 09:24 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "froakieBattleBond": "Battle Bond",
```suggestion
  "froakieBattleBond": "Fuerte Afecto",
```

2024-06-27 09:25 UTC, Kiriox94 commented
Please, next time use the pr

2024-06-27 09:38 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "scatterbugPokeBall": "Poké Ball",
```suggestion
  "scatterbugMeadow": "Floral",
  "scatterbugIcySnow": "Nevado",
  "scatterbugPolar": "Polar",
  "scatterbugTundra": "Tundra",
  "scatterbugContinental": "Continental",
  "scatterbugGarden": "Vergel",
  "scatterbugElegant": "Elegante",
  "scatterbugModern": "Moderno",
  "scatterbugMarine": "Marino",
  "scatterbugArchipelago": "Isleño",
  "scatterbugHighPlains": "Estepa",
  "scatterbugSandstorm": "Desierto",
  "scatterbugRiver": "Río",
  "scatterbugMonsoon": "Borrasca",
  "scatterbugSavanna": "Sabana",
  "scatterbugSun": "Solar",
  "scatterbugOcean": "Océano",
  "scatterbugJungle": "Jungla",
  "scatterbugFancy": "Sofisticado",
  "scatterbugPokeBall": "PokéBall",
```

2024-06-27 09:39 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "flabebeWhite": "White",
```suggestion
  "flabebeRed": "Rojo",
  "flabebeYellow": "Amarillo",
  "flabebeOrange": "Naranja",
  "flabebeBlue": "Azul",
  "flabebeWhite": "Blanco",
```

2024-06-27 09:41 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "furfrouPharaoh": "Pharaoh",
```suggestion
  "furfrouHeart": "Corazón",
  "furfrouStar": "Estrella",
  "furfrouDiamond": "Diamante",
  "furfrouDebutante": "Debutante",
  "furfrouMatron": "Matrón",
  "furfrouDandy": "Dandi",
  "furfrouLaReine": "La Reine",
  "furfrouKabuki": "Kabuki",
  "furfrouPharaoh": "Faraón",
```

2024-06-27 09:42 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "pumpkabooSuper": "Super",
```suggestion
  "pumpkabooSmall": "Pequeño",
  "pumpkabooLarge": "Grande",
  "pumpkabooSuper": "Enorme",
```

2024-06-27 09:43 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "xerneasActive": "Active",
```suggestion
  "xerneasNeutral": "Relajado",
  "xerneasActive": "Activo",
```

2024-06-27 09:45 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "zygardeComplete": "Complete Forme",
```suggestion
  "zygarde50": "Al 50%",
  "zygarde10": "Al 10%",
  "zygarde50Pc": "Zygarde al 50%",
  "zygarde10Pc": "Zygarde al 10%",
  "zygardeComplete": "Zygarde Completo",
```

2024-06-27 09:57 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "oricorioSensu": "Sensu",
```suggestion
  "oricorioBaile": "Apasionado",
  "oricorioPompom": "Animado",
  "oricorioPau": "Plácido",
  "oricorioSensu": "Refinado",
```

2024-06-27 09:58 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "rockruffOwnTempo": "Own Tempo",
```suggestion
  "rockruffOwnTempo": "Ritmo Propio",
```

2024-06-27 10:00 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "miniorViolet": "Violet",
```suggestion
  "miniorRedMeteor": "Minior Núcleo Rojo",
  "miniorOrangeMeteor": "Minior Núcleo Naranja",
  "miniorYellowMeteor": "Minior Núcleo Amarillo",
  "miniorGreenMeteor": "Minior Núcleo Verde",
  "miniorBlueMeteor": "Minior Núcleo Azul",
  "miniorIndigoMeteor": "Minior Núcleo Añil",
  "miniorVioletMeteor": "Minior Núcleo Violeta",
  "miniorRed": "Rojo",
  "miniorOrange": "Naranja",
  "miniorYellow": "Amarillo",
  "miniorGreen": "Verde",
  "miniorBlue": "Azul",
  "miniorIndigo": "Añil",
  "miniorViolet": "Violeta",
```

2024-06-27 10:01 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "mimikyuBusted": "Busted",
```suggestion
  "mimikyuDisguised": "Encubierta",
  "mimikyuBusted": "Descubierta",
```

2024-06-27 10:02 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "magearnaOriginal": "Original",
```suggestion
  "magearnaOriginal": "Vetusto",
```

2024-06-27 10:03 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "marshadowZenith": "Zenith",
```suggestion
  "marshadowZenith": "Cénit",
```

2024-06-27 10:04 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "sinisteaAntique": "Antique",
```suggestion
  "sinisteaPhony": "Falsificada",
  "sinisteaAntique": "Auténtica",
```

2024-06-27 10:06 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "eiscueNoIce": "No Ice",
```suggestion
  "eiscueNoIce": "Cara Deshielo",
```

2024-06-27 10:06 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "indeedeeFemale": "Female",
```suggestion
  "indeedeeMale": "Macho",
  "indeedeeFemale": "Hembra",
```

2024-06-27 10:07 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "zarudeDada": "Dada",
```suggestion
  "zarudeDada": "Papá",
```

2024-06-27 10:08 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "squawkabillyWhitePlumage": "White Plumage",
```suggestion
  "squawkabillyGreenPlumage": "Plumaje Verde",
  "squawkabillyBluePlumage": "Plumaje Azul",
  "squawkabillyYellowPlumage": "Plumaje Amarillo",
  "squawkabillyWhitePlumage": "Plumaje Blanco",
```

2024-06-27 10:09 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "tatsugiriStretchy": "Stretchy",
```suggestion
  "tatsugiriCurly": "Curvada",
  "tatsugiriDroopy": "Lánguida",
  "tatsugiriStretchy": "Estirada",
```

2024-06-27 10:11 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "gimmighoulRoaming": "Roaming",
```suggestion
  "gimmighoulChest": "Cofre",
  "gimmighoulRoaming": "Andante",
```

2024-06-27 10:12 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "poltchageistArtisan": "Artisan",
```suggestion
  "poltchageistCounterfeit": "Imitación",
  "poltchageistArtisan": "Original",
```

2024-06-27 10:13 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "paldeaTaurosAqua": "Aqua",
```suggestion
  "paldeaTaurosCombat": "Combatiente",
  "paldeaTaurosBlaze": "Ardiente",
  "paldeaTaurosAqua": "Acuático",
```

2024-06-27 10:15 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "primal": "Primal {{pokemonName}}",
```suggestion
  "primal": "{{pokemonName}} Primigenio",
```

2024-06-27 10:18 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "pikachuToughCosplay": "Thoug Cosplay",
```suggestion
  "pikachuCosplay": "Coqueta",
  "pikachuCoolCosplay": "Roquera",
  "pikachuBeautyCosplay": "Aristócrata",
  "pikachuCuteCosplay": "Superstar",
  "pikachuSmartCosplay": "Erudita",
  "pikachuToughCosplay": "Enmascarada",
```

2024-06-27 10:20 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "eeveePartner": "Partner",
```suggestion
  "pikachuPartner": "Compañero",
  "eeveePartner": "Compañero",
```

2024-06-27 10:22 UTC, Adri1 commented
Yoo could you push all of the Spanish translation all a once?
My mailbox (and not only mine) is flooded of commit notifications..................

2024-06-27 10:29 UTC, Kiriox94 commented
> Yoo could you push all of the Spanish translation all at once? My mailbox (and not only mine) is flooded of commit notifications..................

I would have liked to, but I haven't been able to. My computer has been ringing every 2 minutes for the last hour because there's a new suggestion for a modification.

2024-06-27 10:29 UTC, InnocentGameDev reviewed
ES localization

2024-06-27 13:34 UTC, 40chyan commented on src/locales/zh_CN/pokemon-form.ts
> +  "eternamax": "E-Max {{pokemonName}}",
```suggestion
  "mega": "Mega {{pokemonName}}",
  "megaX": "Mega {{pokemonName}} X",
  "megaY": "Mega {{pokemonName}} Y",
  "primal": "原始回归{{pokemonName}}",
  "gigantamax": "超级巨{{pokemonName}}",
  "eternamax": "无极巨{{pokemonName}}",
```
cn form prefix added

2024-06-27 13:36 UTC, Adri1 approved these changes

2024-06-27 14:02 UTC, EnochG1 requested changes

2024-06-27 14:02 UTC, EnochG1 commented on src/plugins/i18n.ts
> -}
I'm sorry but it must not be erased.
It occurs error in localization files.
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/ee94cb9f-2e65-436e-8075-b8b28dcefd91)

2024-06-27 14:08 UTC, Kiriox94 commented on src/plugins/i18n.ts
> -}
I've just put back the last version of the file, my branch isn't up to date that's why it's giving you this error, but once merged with the main branch it'll be fine.

2024-06-27 14:22 UTC, Adri1 requested changes
-to cancel my review-

2024-06-27 17:33 UTC, returntoice requested changes
for canceling

2024-06-28 10:25 UTC, Kiriox94 commented
Why does everyone cancel their review?

2024-06-28 10:27 UTC, EnochG1 commented
Maybe they approve after you merge main branch.
You can do it if you approve and merge my PR.
https://github.com/Kiriox94/pokerogue/pull/8

2024-06-28 10:29 UTC, Kiriox94 commented
Yes, I'm just trying it out on my end to make sure everything works, then I'll merge your pr

2024-06-28 10:46 UTC, EnochG1 approved these changes

2024-06-28 10:47 UTC, Adri1 approved these changes

2024-06-28 13:36 UTC, josericardo-fo approved these changes

2024-06-28 16:49 UTC, mercurius-00 reviewed
fix typo

2024-06-28 16:49 UTC, mercurius-00 commented on src/locales/zh_CN/pokemon-form.ts
> +  "gigantamax": "超级巨{{pokemonName}}",
```suggestion
  "gigantamax": "超极巨{{pokemonName}}",
```

2024-06-28 16:57 UTC, flx-sta commented
I wasn't involved at all in this ticket, so I'll leave you guys at it

2024-06-30 13:34 UTC, InnocentGameDev commented on src/locales/es/pokemon-form.ts
> +  "scatterbugPokeBall": "PokéBall",
Taking back some of the translations where I did not follow mainline game translations exactly, in order to keep a more universal wording. Now they should be like they are in the mainline "ES" games, poor as I find those translations.

```suggestion
  "scatterbugMeadow": "Floral",
  "scatterbugIcySnow": "Polar",
  "scatterbugPolar": "Taiga",
  "scatterbugTundra": "Tundra",
  "scatterbugContinental": "Continental",
  "scatterbugGarden": "Vergel",
  "scatterbugElegant": "Oriental",
  "scatterbugModern": "Moderno",
  "scatterbugMarine": "Marino",
  "scatterbugArchipelago": "Isleño",
  "scatterbugHighPlains": "Estepa",
  "scatterbugSandstorm": "Desierto",
  "scatterbugRiver": "Oasis",
  "scatterbugMonsoon": "Monzón",
  "scatterbugSavanna": "Pantano",
  "scatterbugSun": "Solar",
  "scatterbugOcean": "Océano",
  "scatterbugJungle": "Jungla",
  "scatterbugFancy": "Fantasía",
  "scatterbugPokeBall": "Poké Ball",
```

2024-06-30 13:36 UTC, InnocentGameDev approved these changes
Reverted some changes I made to the Vivillion's forms. Otherwise "ES" looks good.

2024-07-05 16:25 UTC, returntoice approved these changes

2024-07-06 00:06 UTC, EnochG1 commented
@Kiriox94
Could you apply InnocentGameDev's suggestion?

2024-07-07 01:10 UTC, f-fsantos commented
@Kiriox94 can you confirm that both the UI and all the keys were tested?

2024-07-07 07:32 UTC, Kiriox94 commented
> @Kiriox94 can you confirm that both the UI and all the keys were tested? 

Yes

2024-07-07 13:37 UTC, EnochG1 commented
@f-fsantos
I checked code you said and there's no problem.
The reason for removing `form.formName` is that
it was separated by each form (for localization of form name also, including position of name.)


```Typescript
// As-is
      case SpeciesFormKey.MEGA:
      case SpeciesFormKey.PRIMAL:
      case SpeciesFormKey.ETERNAMAX:
        return `${form.formName} ${this.name}`; // this code covers 3 forms
      case SpeciesFormKey.MEGA_X:
        return `Mega ${this.name} X`;
      case SpeciesFormKey.MEGA_Y:
        return `Mega ${this.name} Y`;
      default:
        if (form.formKey.indexOf(SpeciesFormKey.GIGANTAMAX) > -1) {
          return `G-Max ${this.name}`;
        }
      }
```

```Typescript
// TO-BE
      case SpeciesFormKey.MEGA: // each form name separated
        return i18next.t("pokemonForm:mega", {pokemonName: this.name});
      case SpeciesFormKey.PRIMAL:
        return i18next.t("pokemonForm:primal", {pokemonName: this.name});
      case SpeciesFormKey.ETERNAMAX:
        return i18next.t("pokemonForm:eternamax", {pokemonName: this.name});
      case SpeciesFormKey.MEGA_X:
        return i18next.t("pokemonForm:megax", {pokemonName: this.name});
      case SpeciesFormKey.MEGA_Y:
        return i18next.t("pokemonForm:megay", {pokemonName: this.name});
      default:
        if (form.formKey.indexOf(SpeciesFormKey.GIGANTAMAX) > -1) {
          return i18next.t("pokemonForm:gigantamax", {pokemonName: this.name});
        }
      }
```

Here's my test screenshot in this branch. (English / Franch)

| En | Fr |
| --- | --- |
| ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/72b78066-c11d-42ee-9b61-ef28db0e1a51) | ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/e1fb36c4-94c5-4344-912b-344bf767dec0) |
| ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/0c80f5a9-ad45-41e1-a0a5-47033bc896d0) | ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/e220492e-8a47-448e-baec-396af2b25c89) |

2024-07-07 14:01 UTC, EnochG1 commented
@f-fsantos 
And I tested this part, too.
```Typescript
        const speciesName = Species[species.speciesId].toLowerCase().split("_");
        for (let i = 1; i < speciesName?.length; i++) {
          speciesName[i] = speciesName[i].charAt(0).toUpperCase() + speciesName[i].substring(1);
        }

        if (species.speciesId === Species.ARCEUS) {
          this.pokemonFormText.setText(i18next.t(`pokemonInfo:Type.${formText?.join("").toUpperCase()}`));
        } else {
          this.pokemonFormText.setText(formText?.join("") ? i18next.t(`pokemonForm:${speciesName.join("")}${formText.join("")}`) : "");
        }
```

| En | Fr |
| --- | --- |
| ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/b1414b04-768a-4e27-bdd7-5df2b4b44912) | ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/d4b65e90-ccf2-4950-a3d2-890dde1dc476) |

2024-07-07 14:59 UTC, f-fsantos approved these changes

2024-07-07 14:59 UTC, merged

2024-07-07 16:34 UTC, CodeTappert commented on src/data/pokemon-species.ts
> +        return i18next.t("pokemonForm:megay", {pokemonName: this.name});
change to megaY

2024-07-07 16:35 UTC, CodeTappert commented
Add Deoxys Normal Form

2024-07-07 16:36 UTC, CodeTappert commented
Add Shaymin Land form

2024-07-07 16:36 UTC, CodeTappert commented
Add giratinaAltered

2024-07-07 16:37 UTC, CodeTappert commented
add tornadusIncarnate

2024-07-07 16:37 UTC, CodeTappert commented
thundurusIncarnate

2024-07-07 16:37 UTC, CodeTappert commented
landorusIncarnate

2024-07-07 16:37 UTC, CodeTappert commented
keldeoOrdinary

2024-07-07 17:23 UTC, CodeTappert commented on src/locales/ko/config.ts
> +import { pokemonForm } from "../es/pokemon-form";
change to


```
import { pokemonForm } from "./pokemon-form";
```