Locales punctuation fix in descriptions in (en/es) modifier-type.ts (other languages WIP)
pagefaultgames/pokerogue pull request #1696
Opened 2024-06-01 17:48 UTC by InnocentGameDev

## Why am I doing these changes?
Ok, so I'll start with this considering the nature of the change. I made some other localization changes in another PR and was getting suggestions that included a "." at the end of the description of items. 95% of English item descriptions didn't end with punctuation and almost all of the Spanish, French and German item descriptions didn't have punctuation either. Italian is at 50/50 split.

So two goals are achieved here:
1- Consistency across the board.
2- Said consistency replicates the S/V item descriptions.

## What are the changes?
For now, not all modifier-type.ts are changed, but I wanted to make the PR already in case anyone is working on this as well.

- [X] English punctuation fix
- [X] Spanish punctuation fix
- [] German punctuation fix
- [] French punctuation fix
- [] Italian punctuation fix
- [] PT_BR punctuation fix
- [] Korean punctuation fix
- [] Chinese_CN punctuation fix
- [] Chinese_TW punctuation fix

## What did change?
Descriptions in locales/lang/modifier-type.ts got proper punctuation when applicable.

## How to test the changes?
Sentences should now show "." when showing an item's description.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-02 11:08 UTC, InnocentGameDev commented
The Berry Pouch numbers change made it to live before this so I had to re-add the "."s to resolve the conflict

2024-06-02 12:59 UTC, MrWaterT commented on src/locales/ko/modifier-type.ts
> +    "BERRY_POUCH": { name: "열매주머니", description: "사용한 나무열매가 소모되지 않을 확률이 33% 추가된다." },
```suggestion
    "BERRY_POUCH": { name: "열매주머니", description: "사용한 나무열매가 소모되지 않을 확률이 30% 추가된다." },
```

2024-06-02 13:59 UTC, InnocentGameDev commented on src/locales/ko/modifier-type.ts
> +    "BERRY_POUCH": { name: "열매주머니", description: "사용한 나무열매가 소모되지 않을 확률이 33% 추가된다." },
Didn't see korean didn't show up at all in the merge conflict. Other PR author must've not seen it. Added

2024-06-02 19:20 UTC, CodeTappert approved these changes

2024-06-04 19:04 UTC, brain-frog requested changes
small change to keep consistency

2024-06-04 19:04 UTC, brain-frog commented on src/locales/zh_CN/modifier-type.ts
> +    "TOXIC_ORB": { name: "Toxic Orb", description: "이 도구를 지닌 포켓몬은 턴이 끝나는 시점에 상태이상에 걸리지 않았다면 맹독 상태가 된다." },
these should use the same period symbol as the rest

2024-06-05 05:45 UTC, MrWaterT reviewed
Edit typo (maybe) resolve conflic.
Add punctuations to missing.

toxic orb, flame orb, berry pouch has no problem in ko.

2024-06-05 05:45 UTC, MrWaterT commented on src/locales/ko/modifier-type.ts
> +      description: "포켓몬에게 {{moveName}}[[를]] 가르침친다.",
```suggestion
      description: "포켓몬에게 {{moveName}}[[를]] 가르친다.",
```

2024-06-05 05:45 UTC, MrWaterT commented on src/locales/ko/modifier-type.ts
>      "ABILITY_CHARM": { name: "특성부적", description: "야생 포켓몬이 숨겨진 특성을 가지고 등장할 확률을 급격히 증가" },
```suggestion
    "SHINY_CHARM": { name: "빛나는부적", description: "야생 포켓몬이 색이 다른 포켓몬으로 등장할 확률을 급격히 높인다." },
    "ABILITY_CHARM": { name: "특성부적", description: "야생 포켓몬이 숨겨진 특성을 가지고 등장할 확률을 급격히 높인다." },
```

2024-06-09 15:57 UTC, brain-frog approved these changes

2024-06-09 15:57 UTC, merged