[Bug] Fix Berserk and Anger Shell from crashing the game when pokemon is forced to switch out
pagefaultgames/pokerogue pull request #1699
Opened 2024-06-01 19:52 UTC by torranx

## What are the changes?
- Fixed Berserk and Anger Shell abilities

## Why am I doing these changes?
- Game crashes/freezes when Berserk/Anger Shell is triggered with force switch move targeting the opposing side.

## What did change?
- added optional chain before checking `damage`

### Screenshots/Videos
- Game no longer crashes/freezes

https://github.com/pagefaultgames/pokerogue/assets/68144167/4a96d907-3df5-4119-963c-a62698bf73a5

## How to test the changes?
- Import the session data [here](https://discord.com/channels/1125469663833370665/1125662770629709935/1246535325967319040)
- Kill the first mon, opponent should use Circle Throw then

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
- [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
- [x] Have I provided screenshots/videos of the changes?

2024-06-01 20:19 UTC, Tempo-anon requested changes

2024-06-01 20:19 UTC, Tempo-anon commented on src/data/ability.ts
> +    if (this.condition(pokemon, attacker, move.getMove()) && (pokemon.hp <= hpGateFlat && (pokemon.hp + lastAttackReceived?.damage) > hpGateFlat)) {
Won't this be adding a number to undefined? I think it'd be better to do a check for lastAttackReceived and just make it not add or add 0 instead

2024-06-07 12:11 UTC, XGSleepWalker requested changes

2024-06-07 12:11 UTC, XGSleepWalker commented on src/data/ability.ts
> +    if (lastAttackReceived && this.condition(pokemon, attacker, move.getMove()) && (pokemon.hp <= hpGateFlat && (pokemon.hp + lastAttackReceived.damage) > hpGateFlat)) {
Please default lastAttackReceived to 0 instead of cancelling the whole condition.

2024-06-13 15:36 UTC, Tempo-anon approved these changes

2024-06-13 15:37 UTC, merged