Remove Poison Puppeteer's species lock
pagefaultgames/pokerogue pull request #1702
Opened 2024-06-01 21:54 UTC by innerthunder

## What are the changes?

This removes the condition that makes Poison Puppeteer exclusive to Pecharunt, as well as removing the reference to Pecharunt in the ability's English description.

## Why am I doing these changes?

Poison Puppeteer is currently exclusive to Pecharunt. This causes problems in this game for the following reasons:

- When another Pokemon fuses with Pecharunt, Poison Puppeteer is disabled.
- From a balance perspective, Poison Puppeteer cannot be used as a passive ability for other Pokemon even when it would be a major benefit to them.

Considering Poison Puppeteer doesn't introduce any mechanics that require its source to be Pecharunt, it doesn't make sense to keep it exclusive to the species.

## What did change?

- `data/ability`: Poison Puppeteer's `ConfusionOnStatusEffectAbAttr` is no longer conditional to the source's species.
- `locale/en/ability`: Poison Puppeteer's description no longer references Pecharunt, using "this Pokémon" in its place.

### Screenshots/Videos

Test Video:
- Bulbasaur was given Poison Puppeteer via `src/overrides.ts`.
- The video starts by showing Poison Puppeteer's new English description in Bulbasaur's summary.
- Bulbasaur uses Toxic to poison the opposing Caterpie. With Poison Puppeteer activating, this also confuses Caterpie.

https://github.com/pagefaultgames/pokerogue/assets/168692175/a4b86616-41f1-410c-8b68-fb288388fb0e

## How to test the changes?

See the description for the test video above.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-01 22:11 UTC, CodeTappert commented
``German: 

from
```
description: "Wenn Infamomo ein Ziel mit einer Attacke vergiftet, so wird dieses auch verwirrt.",
```
To
```
description: "Wenn der Anwender ein Ziel mit einer Attacke vergiftet, so wird dieses auch verwirrt.",
```

2024-06-02 05:07 UTC, innerthunder commented
Updated French locale:

from

```
description: "Lorsque Pêchaminus empoisonne un Pokémon grâce à l’une de ses capacités, ce dernier devient également confus.",
```

to

```
description: "Lorsque ce Pokémon empoisonne un Pokémon grâce à l’une de ses capacités, ce dernier devient également confus.",
```

2024-06-02 11:15 UTC, InnocentGameDev commented
Spanish locale:

from

    description: "Los rivales que Pecharunt envenene con sus movimientos también sufrirán confusión."

to

    description: "Los rivales que este Pokémon envenene con sus movimientos también sufrirán confusión."

2024-06-02 15:57 UTC, OrangeRed approved these changes
Logically everything looks good. The rest is whether the move should be balanced this way.

2024-06-04 21:54 UTC, Tempo-anon submitted a review, later dismissed
Code looks good to me. Will just leave it up to the lead devs for how we want to deal with species locking abilities in the future

2024-06-15 20:30 UTC, innerthunder commented
Just rebased this to fix merge conflicts.

For what it's worth, I had a conversation with @Madmadness65 about this a while ago:

![image](https://github.com/pagefaultgames/pokerogue/assets/168692175/b1175bb3-85ab-4685-a605-c0912fcb3176)

2024-07-13 16:54 UTC, OrangeRed commented
@innerthunder can you add localization for the other language or at minimum at the key to other locales.

2024-07-13 19:57 UTC, josericardo-fo commented on src/locales/pt_BR/ability.ts
> +    description: "Pokémon envenenados pelos movimentos de Pecharunt também ficarão confusos.", // TODO: Remove reference to Pecharunt
```suggestion
    description: "Pokémon envenenados pelos movimentos desse Pokémon também ficarão confusos.",
```

2024-07-13 22:06 UTC, sonnyding1 reviewed
Add zh-cn and zh-tw translations

2024-07-13 22:06 UTC, sonnyding1 commented on src/locales/zh_CN/ability.ts
> +    description: "因桃歹郎的招式而陷入中毒状态的\n对手同时也会陷入混乱状态。", // TODO: Remove reference to Pecharunt
```suggestion
    description: "因为此宝可梦的招式而陷入中毒状\n态的对手同时也会陷入混乱状态。",
```

2024-07-13 22:06 UTC, sonnyding1 commented on src/locales/zh_TW/ability.ts
> +            "因為桃歹郎的招式而陷入中\n毒狀態的對手同時也會陷入\n混亂狀態。", // TODO: Remove reference to Pecharunt
```suggestion
            "因為此寶可夢的招式而陷入中毒狀\n態的對手同時也會陷入混亂狀態。",
```

2024-07-13 22:54 UTC, returntoice requested changes

2024-07-13 22:54 UTC, returntoice commented on src/locales/ko/ability.ts
> +    description: "복숭악동의 기술에 의해 독 상태가 된 상대는 혼란 상태도 되어 버린다." // TODO: Remove reference to Pecharunt
```suggestion
    description: "이 포켓몬의 기술에 의해 독 상태가 된 상대는 혼란 상태도 되어 버린다."
```

2024-07-14 07:25 UTC, EnochG1 reviewed
@NicusPulcis requested to modify Italian via Discord.

2024-07-14 07:25 UTC, EnochG1 commented on src/locales/it/ability.ts
> +    description: "I Pokémon avvelenati dalle mosse di Pecharunt entreranno anche in stato di confusione.", // TODO: Remove reference to Pecharunt
```suggestion
    description: "I Pokémon avvelenati dalle mosse di questo Pokémon entreranno anche in stato di confusione.",
```

2024-07-14 07:37 UTC, innerthunder commented
All translations should be done now, thanks everyone!

2024-07-14 11:29 UTC, returntoice approved these changes

2024-07-14 11:49 UTC, EnochG1 approved these changes

2024-07-30 21:22 UTC, Tempo-anon commented
Closing this because of merge conflicts and we still never reached an actual consensus for what to do about species-locked abilities. Such an edge case though and I don't believe the passive team has assigned poison puppeteer anywhere

2024-07-30 21:22 UTC, closed without merging