Localized game-mode and save-slot-select-ui-handler
pagefaultgames/pokerogue pull request #1728
Opened 2024-06-02 14:08 UTC by josericardo-fo

## What are the changes?

Localized game-mode and save-slot-select-ui-handler
## Why am I doing these changes?

Those pages weren't localized yet
## What did change?

Translations and text in game-mode and save-slot-select-ui-handler files
### Screenshots/Videos (all screenshots are in ptBR)

## Game Modes
### Before
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/3d5c78a0-5fdb-4e0f-b978-7cb301e6989d)
### After
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/286611f9-9a0d-44f9-b9dc-0d355819a4d2)

## Save Slots
### Before
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/82fdc3a5-ba75-4d03-813a-4f63ae7ffeaa)
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/78e4163e-fb22-4ce9-96d3-d8a7727f6269)
### After
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/4cd5894b-4382-4e7a-9b6e-4dc22a65aee6)
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/d82a40ae-6d69-4d8a-8247-b7745bb08a14)

## Overwrite Data
### Before
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/dd2ee67c-64f2-4572-932d-cd0cbb738883)
### After
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/320af9ba-a5d4-4fee-bf3e-286c773438a9)

## How to test the changes?

Check the new game screen, load game screen and the text when overwriting a save slot.
## Checklist
- [ ] There is no overlap with another PR?
Overlap with #1674, but he just localized the overwriteData text
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-06-02 15:56 UTC, flx-sta commented
There is a lot of “noise” in the PR because you added the English translation for every locale.
Did you try if it will fall-back to English by default ? Because this makes reviewing more of a chore and it is Is intact not a translation. Just noise

2024-06-02 16:06 UTC, josericardo-fo commented
What do you mean? When I localize something, I don't translate the localized files beacuse I'm not qualified to do that. It's up to the other devs to add PRs to my PR to translate or wait for it to get merged than create their own PRs.

2024-06-02 16:08 UTC, flx-sta commented
I mean something like the `src/locales/de/game-mode.ts` file. It now contains the English translations. But if English is the fallback language anyways that shouldn’t be necessary and those are not “translations” anyway.

2024-06-02 16:11 UTC, josericardo-fo commented
I agree. But, as I said, I localized it and now other people can translate it if they want to. If it is working in every language, than its fine.

2024-06-02 16:54 UTC, flx-sta commented
That’s why I’m saying: see what is being printed if you remove a language that is not translated. Technically it should show the English translation. This you don’t have to provide those inside the locale file of a different language

2024-06-02 18:26 UTC, CodeTappert commented on src/locales/de/game-mode.ts
> +  "unknown": "Unknown",
```suggestion
  "classic": "Klassik",
  "endless": "Endlos",
  "endlessSpliced": "Endlos (Fusion)",
  "dailyRun": "Täglicher Run",
  "unknown": "Unbekannt",
```

2024-06-02 18:28 UTC, CodeTappert commented on src/locales/de/save-slot-select-ui-handler.ts
> +  "empty": "Leer",
```suggestion
  "overwriteData": "Den ausgewählten Speicherstand überschreiben?",
  "loading": "Läd...",
  "wave": "Welle",
  "lv": "Lvl",
  "empty": "Leer",
```

2024-06-02 20:55 UTC, GoldTra commented on src/locales/es/game-mode.ts
> +export const gameMode: SimpleTranslationEntries = {
```suggestion
export const gameMode: SimpleTranslationEntries = {
```

2024-06-03 07:00 UTC, GoldTra requested changes

2024-06-03 07:02 UTC, CodeTappert commented on src/locales/es/save-slot-select-ui-handler.ts
> +  "lv": "Lv",
The override thing may be too long. Could someone check that

2024-06-03 08:14 UTC, GoldTra commented on src/locales/es/save-slot-select-ui-handler.ts
> +  "lv": "Lv",
> The override thing may be too long. Could someone check that

![Captura1](https://github.com/pagefaultgames/pokerogue/assets/162721984/7aebc0f5-38d7-49e0-8b5c-de7b72a2e439)
![Captura3](https://github.com/pagefaultgames/pokerogue/assets/162721984/1175731d-4e84-4d1b-aca2-7f02c01b2280)

2024-06-03 08:22 UTC, CodeTappert commented on src/locales/es/save-slot-select-ui-handler.ts
> +  "lv": "Lv",
Okay then its all good. Just wanted to be sure since my german sentence was orignal to long

2024-06-03 11:36 UTC, Adri1 commented
PR opened on your branch with French translations

2024-06-03 11:41 UTC, Adri1 commented
Does this PR also convet numbers according to the language ?
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/17742f63-22b4-4425-9384-bb982f86755a)
Because I see this and for example in French, we use the comas before deciamals not dots.
It shoud be possible, as it is already the case for many numbers formatting when, for example money is displayed in some places.

2024-06-03 14:28 UTC, josericardo-fo commented
I will take a look on that

> Also, does this PR also converts dynamically numbers according to the set language, the navigator or system language? ![image](https://private-user-images.githubusercontent.com/2070109/336054807-17742f63-22b4-4425-9384-bb982f86755a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjUxMjIsIm5iZiI6MTcxNzQyNDgyMiwicGF0aCI6Ii8yMDcwMTA5LzMzNjA1NDgwNy0xNzc0MmY2My0yMmI0LTQ0MjUtOTM4NC1iYjk4MmY4Njc1NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMTQyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzcxNjM1ZGZjMDcxYzNlNzRhZTVkMmZkOWZhYzEzZGU4Y2U4ZWFiNjNjY2M1YjNiNDg0NTA0NWM2MzI4MWMzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DFju-aTxQ3ZBPtngZ3VD3xUE6pJzpH0DTUaHnvkSu-Y) Because I see this and for example in French, we use comas before deciamals not dots. (and just spaces where in English they use comas) It shoud be possible, as it is already the case for many number formatting when, for example, money is displayed in some places.

2024-06-03 15:53 UTC, josericardo-fo commented
@Adri1 
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/3df775bb-d9d6-4275-8d7b-f285cb004bdc)
At the end, they return a dot by default after decimals. It can be changed, but the comma is kinda strange:
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/4a23f008-7b64-4002-ad32-366bb47658be)
I didn't know that there was a way to localize that, looking for it becuse numbers here in Brazil are separated like this "$1.300,50" (one thousand, three hundred dollars and fifty cents) and I didn't insert that in, for example, the MoneyAchvs localization

2024-06-03 16:13 UTC, Adri1 commented
For example, here is what I did in PR #1656 :
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/00824516-28e1-41ff-bb05-463e5b4c3962)
I always only encountered `toLocaleString("en-US")` when I happened to come across numbers. So for what you have here, I admit I dont have any more ideas.
But if what I did can give you any ideas to adapt it to your case...

2024-06-03 16:55 UTC, josericardo-fo commented
Created a PR for that @Adri1 #1762

2024-06-03 17:10 UTC, GoldTra commented
@josericardo-fo PR opened on your branch with Spanish translations

2024-06-08 13:33 UTC, returntoice requested changes
Update for Korean locales

2024-06-08 13:33 UTC, returntoice commented on src/locales/ko/game-mode.ts
> +  "challenge": "Challenge",
```suggestion
  "classic": "클래식",
  "endless": "엔들리스",
  "endlessSpliced": "엔들리스(융합체)",
  "dailyRun": "데일리 런",
  "unknown": "언노운",
  "challenge": "챌린지",
```
Korean update

2024-06-08 13:33 UTC, returntoice commented on src/locales/ko/save-slot-select-ui-handler.ts
> +  "wave": "Wave",
```suggestion
  "overwriteData": "선택한 슬롯에 데이터를 덮어쓰시겠습니까?",
  "loading": "로딩 중...",
  "wave": "웨이브",
```

2024-06-08 15:02 UTC, Tempo-anon approved these changes
Going forward let's try having each separate localization go in their own PR since there indeed is a lot of noise to this one which makes it harder to read and review.

2024-06-08 15:03 UTC, merged