Balance endless tokens
pagefaultgames/pokerogue pull request #1733
Opened 2024-06-02 18:32 UTC by Fontbane

## What are the changes?

- Removed Sleep and Freeze tokens
- Rebalanced the others to be slightly less overbearing

## Why am I doing these changes?

Sleep and freeze tokens are widely agreed to make endless unfun. It’s honestly been a long time coming but the recent berry rebalancing made it much more urgent to finally rebalance these tokens.
These changes were made in accordance to discussions with the balance team and other devs.

## What did change?

- Reduced paralyze token proc chance from 10% to 5%
- For both burn and poison tokens, reduced proc chance from 10% to 5% and increased stack limit from 5 to 10
- Reduced endure token proc chance from 2.5% to 2%
- Reduced status heal token proc chance from 10% to 5%
- Total max amount of tokens remains the same

### Screenshots/Videos

TBA

## How to test the changes?

Import a current endless run and try to get another token. Try to set status on the opponent and take some hits to check the chances. You could override the opponent moves to Brutal Swing so there’s 3 proc chances in one move.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-02 20:19 UTC, bennybroseph commented
> These changes were made in accordance to discussions with the balance team and other devs.

Let's link the start of these discussions now and in future PRs so that others can catch themselves up in the event that they were offline at the time.

2024-06-02 21:56 UTC, bennybroseph requested changes

2024-06-02 21:56 UTC, bennybroseph commented on src/system/game-data.ts
>            }
This section can be removed now since most people should have already gotten the change saved

2024-06-02 21:56 UTC, bennybroseph commented on src/system/game-data.ts
> +            md.stackCount = Math.min(md.stackCount, 0);
Math.min here means it'll always be 0 or less than 0. Is that the intention? If so, we should just set it to 0 I think. We wouldn't want this to go negative if for some reason it is.

2024-06-02 22:02 UTC, Fontbane commented on src/system/game-data.ts
>            }
Most, but not all. Doesn’t hurt to account for older accounts.

2024-06-02 22:35 UTC, bennybroseph approved these changes

2024-06-04 04:10 UTC, Fontbane commented
The token code is so bad. It's unrecoverable. I'm refactoring this. It's so bad. It's so bad.

2024-06-04 18:33 UTC, Tempo-anon approved these changes
Gonna trust Damo and Fontbane that they have tested this

2024-06-04 20:56 UTC, Madmadness65 approved these changes
Changes look good to me. I will trust that these changes have been thoroughly tested and wont break existing saves in odd ways.

2024-06-04 21:39 UTC, merged