Fixed primal weather interaction.
pagefaultgames/pokerogue pull request #1744
Opened 2024-06-02 23:25 UTC by Arxalc

## What are the changes?

Closes #1715
* Primal weather can overwrite each other
* Primal weather ends upon switching out or fainting

## Why am I doing these changes?

Interactions weren't working before.

## What did change?

If a primal weather was already in effect, it could not be overriden by another -> now it can
Primal weather would not revert upon Pokemon switching out or fainting -> now it does

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/63990624/68eb7021-59a7-48ea-802a-5692f72bb95c

## How to test the changes?

Override ability to Desolate Land, Primordial Sea, or Delta Stream.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-03 00:17 UTC, Tempo-anon commented on src/data/ability.ts
> +      this.weatherType === WeatherType.STRONG_WINDS) || !pokemon.scene.arena.weather?.isImmutable()) {
Wonder if it would be worth having a util function in weather.ts `isPrimalWeather`

2024-06-03 00:18 UTC, Tempo-anon commented on src/data/ability.ts
> + * Clears weather upon Primal Groudon/Kyogre/Rayquaza switch out
nit: this ability attribute is not exclusive to those Pokemon, but rather on the abilites heavy rain, harsh sun, and strong winds

2024-06-03 00:18 UTC, Tempo-anon commented on src/data/ability.ts
> +export class PreSwitchOutClearWeatherAttr extends PreSwitchOutAbAttr {
nit: `PreSwitchOutClearWeatherAbAttr`

2024-06-03 00:19 UTC, Tempo-anon commented on src/data/ability.ts
> +    pokemon.scene.arena.trySetWeather(WeatherType.NONE, false);
Won't this cause a bug if there are two Primal Groudons out and one of them switches out? The harsh sun should still be in effect

2024-06-03 00:19 UTC, Tempo-anon commented on src/data/ability.ts
> +    pokemon.scene.arena.trySetWeather(WeatherType.NONE, false);
Same issue as above

2024-06-03 00:20 UTC, Tempo-anon requested changes
There's some edge cases to consider here

2024-06-04 06:01 UTC, Arxalc commented on src/data/ability.ts
> +    pokemon.scene.arena.trySetWeather(WeatherType.NONE, false);
You're right. Will try and fix.
Tested interactions on Showdown and found it works like this:
* Groudon vs. Kyogre. When Kyogre switches in, Desolate Land is overriden by Primordial Sea. If Kyogre dies, weather clears.
* Groudon 1 vs. Groudon 2. When Groudon 2 switches in, nothing special happens. If Groudon 1 dies, weather persists because Groudon 2 has the ability and is still on the field.

2024-06-04 13:30 UTC, Tempo-anon commented on src/data/ability.ts
> +    pokemon.scene.arena.trySetWeather(WeatherType.NONE, false);
What happens if Kyogre switches out after overwriting Desolate Land with Primordial Sea? If the weather still clears up it just means you need to add a check so on faint/switchout it checks the field to make sure no other Pokemon has that ability which means this ability attribute also needs to know what ability it's checking

2024-06-04 21:01 UTC, Arxalc commented
I added checking abilities for both switch out/faint so now all cases should be covered.

Fixed 1st comment case: Harsh sun persists after Desolate Land user faints and another Desolate Land ability remains
https://github.com/pagefaultgames/pokerogue/assets/63990624/277bb5d6-2ff2-4261-8f8c-dc666f80f546

2nd comment case: According to Showdown after overwriting a primal weather, weather should clear if Kyogre switches out/faints. This is intentional. 
https://github.com/pagefaultgames/pokerogue/assets/63990624/b6859ec9-34f5-46ea-bb22-415691a3468e

2024-06-04 21:47 UTC, Tempo-anon commented on src/data/ability.ts
> +      this.weatherType === WeatherType.STRONG_WINDS) || !pokemon.scene.arena.weather?.isImmutable()) {
nit: how come the strong winds check does not `as`?

2024-06-04 21:47 UTC, Tempo-anon commented on src/data/ability.ts
> +  applyPreSwitchOut(pokemon: Pokemon, passive: boolean, args: any[]): boolean | Promise<boolean> {
Please add tsdoc to the `applyPreSwitchOut` function, especially since you're using `pokemon` in it

2024-06-04 21:48 UTC, Tempo-anon commented on src/data/ability.ts
> +    const currentAbility = pokemon.getAbility().id;
I believe `getAbility` does not take into account passives which might be worth considering

2024-06-04 21:49 UTC, Tempo-anon commented on src/data/ability.ts
> +    (currentAbility === Abilities.DESOLATE_LAND && weatherType === WeatherType.HARSH_SUN)) {
There's two desolate land/harsh sun checks here but no strong winds check

2024-06-04 21:51 UTC, Tempo-anon commented on src/data/ability.ts
> +      if (pokemon.scene.getField(true).filter(p => p !== pokemon).filter(p => p.hasAbility(currentAbility)).length === 0) {
I wonder if there's a more elegant way of doing this

2024-06-04 21:51 UTC, Tempo-anon commented on src/data/ability.ts
> +    (currentAbility === Abilities.DESOLATE_LAND && weatherType === WeatherType.HARSH_SUN)) {
two desolate land checks here, which I guess makes sense since I assume this is copy/pasted. All my other comments about the other class also apply here

2024-06-04 21:52 UTC, Tempo-anon requested changes
See some errors but looking good!

2024-06-05 05:25 UTC, Arxalc commented
1. Removed the `as` part. (tldr: I only know Java. Tried `==`. Had errors. Read you needed `as`. Turns out I just needed to change to `===` instead.)
2. Added passive abilities into consideration. (Balance-wise, unlikely to ever happen
3. I completely missed strong winds 🤡
4. Lmk if there's a better way to do this. I don't think it's worth adding util functions for something that'll only happen twice ever.

2024-06-05 05:50 UTC, Tempo-anon commented on src/data/ability.ts
> +  applyPostFaint(pokemon: Pokemon, passive: boolean, attacker: Pokemon, move: PokemonMove, hitResult: HitResult, args: any[]): boolean {
Since we can make the assumption that there's only ever one weather at a time, would something like this make sense?
```ts
    let turnOffWeather = false;
    switch (weatherType) {
      case (WeatherType.HARSH_SUN):
        if (pokemon.hasAbility(Abilities.DESOLATE_LAND) 
          && pokemon.scene.getField(true).filter(p => p.hasAbility(Abilities.DESOLATE_LAND).length === 0)) {
            turnOffWeather = true;
        }
        break;
      case (WeatherType.HEAVY_RAIN):
        if (pokemon.hasAbility(Abilities.PRIMORDIAL_SEA) 
          && pokemon.scene.getField(true).filter(p => p.hasAbility(Abilities.PRIMORDIAL_SEA).length === 0)) {
            turnOffWeather = true;
        }
        break;
      case (WeatherType.STRONG_WINDS):
        if (pokemon.hasAbility(Abilities.DELTA_STREAM) 
          && pokemon.scene.getField(true).filter(p => p.hasAbility(Abilities.DELTA_STREAM).length === 0)) {
            turnOffWeather = true;
        }
        break;
      default:
    }
    if (turnOffWeather) {
      pokemon.scene.arena.trySetWeather(WeatherType.NONE, false);
      return true;
    }
    return false;
  ```

2024-06-05 17:37 UTC, Arxalc commented on src/data/ability.ts
> +  applyPostFaint(pokemon: Pokemon, passive: boolean, attacker: Pokemon, move: PokemonMove, hitResult: HitResult, args: any[]): boolean {
Is there a benefit of this code over mine? It seems to just be changing the order of checking conditions in more lines.

2024-06-05 20:50 UTC, Arxalc commented on src/data/ability.ts
> +  applyPostFaint(pokemon: Pokemon, passive: boolean, attacker: Pokemon, move: PokemonMove, hitResult: HitResult, args: any[]): boolean {
Replaced 👍

2024-06-06 01:39 UTC, Tempo-anon approved these changes

2024-06-07 19:22 UTC, merged