[QoL] Added an indicator when money changes.
pagefaultgames/pokerogue pull request #1772
Opened 2024-06-03 23:29 UTC by Mehauk

When the player uses money or gains money, an indicator to show that the money was changed would be nice. Mostly due to the golden punch not feeling like its doing anything unless you are looking at the top right corner of the screen.

There is now a short animation and color change occurs when money is added to or removed.

2024-06-03 23:34 UTC, Mehauk commented
I also created an issue on the issue board. I am not sure how to link the two. If this change is merged should I close the issue as well?

2024-06-04 01:34 UTC, Tempo-anon requested changes
Can you please fill out the PR template? And also provide a video of this in action?

2024-06-04 03:47 UTC, ben-lear commented
Can you add a video and screenshots of the change?

2024-06-04 03:49 UTC, ben-lear commented on src/phases.ts
> +            this.scene.animateMoneyChanged(false);
Why not put this inside the updateMoneyText() function so that the two are more tightly coupled? Having to keep track of calling both functions might become cumbersome.

2024-06-04 05:29 UTC, Mehauk commented on src/phases.ts
> +            this.scene.animateMoneyChanged(false);
That is what I did initially but the `updateMoneyText` was being called when starting/loading the game, as well as when the money was changed. Are we okay with showing the animation whenever someone starts playing? Another option was to add a couple of extra parameters, but whenever we would need to use it, we would have to provide the first optional parameter as well. Something like `updateMoneyText(true, true, false)`, which feels unreadable. Another option that comes to mind RN, is to use an object with the appropriate fields and only supply the fields that are required at the time;

```js
updateMoneyText({
    forceVisible: boolean,
    shouldAnimate: boolean,
    positiveChange: boolean,
}): void {}
```

2024-06-04 20:19 UTC, bennybroseph requested changes
I like the animation alright. I think it should be vertically centered, slightly faster, and slightly larger though. 

Can we upload another video with those changes to see how they would potentially look?

2024-06-06 14:28 UTC, bennybroseph commented
Got some conflicts. Also, the code looks correct to center the text scaling, but the video is definitely not centered. Is that an old video or is it actually not working?

2024-06-06 16:15 UTC, Mehauk commented
> Got some conflicts. Also, the code looks correct to center the text scaling, but the video is definitely not centered. Is that an old video or is it actually not working?

I have handled the merge conflict. I had dev tools open in the new video so I replaced it as well.

2024-06-06 16:47 UTC, bennybroseph approved these changes

2024-06-06 16:50 UTC, merged