[BUG] fix language auto detect
pagefaultgames/pokerogue pull request #1784
Opened 2024-06-04 08:27 UTC by BubbleBear

## What are the changes?
currently language auto detection is broken,
fixed according to [i18next documentation](https://www.i18next.com/how-to/faq#how-should-the-language-codes-be-formatted)

## Why am I doing these changes?
currently language auto detection is broken for **Simplified Chinese, Traditional Chinese, Portugese Brazilian**

## What did change?
i18next config resource key

### Screenshots/Videos
#### BEFORE FIX
<img width="1273" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/17879773/39236803-d8f6-4051-9506-e7c44be34cbd">

----

#### AFTER FIX
<img width="1318" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/17879773/ebeb6303-c087-4258-93bd-53731ca9da14">

## How to test the changes?

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-04 13:28 UTC, Tempo-anon commented
Can you show some proof that this works?

2024-06-04 20:24 UTC, bennybroseph requested changes

2024-06-04 20:24 UTC, bennybroseph commented on src/plugins/i18n.ts
> +      "zh-TW": {
assuming the rest is correct, this adds quotes here which cannot be correct

2024-06-06 03:31 UTC, BubbleBear commented on src/plugins/i18n.ts
> +      "zh-TW": {
this is the grammer, you cannot use `-` in object key unless wrap it in quotes

2024-06-06 03:31 UTC, BubbleBear commented
> Can you show some proof that this works?

sure thing sir

2024-06-06 03:39 UTC, BubbleBear commented
@Tempo-anon @bennybroseph 
Thanks for your review and patiences, I've added some screenshot proofs.

2024-06-07 10:40 UTC, davidyan-hub commented
I did not have envirement to do this...
Who can modify the text.ts to change the font-family and font-size for chinese.

Code as below:

fontFamily: localStorage.getItem('prLang')==="zh_CN"?'simhei':'emerald',

styleOptions.fontFamily = localStorage.getItem('prLang')==="zh_CN"?'MuZaiPixel':'pkmnems';

and same judgement logic for changing font-size, let the size is smaller.

2024-06-07 16:27 UTC, bennybroseph approved these changes

2024-06-07 16:27 UTC, merged

2024-06-08 13:54 UTC, BubbleBear commented
> I did not have envirement to do this... Who can modify the text.ts to change the font-family and font-size for chinese.
> 
> Code as below:
> 
> fontFamily: localStorage.getItem('prLang')==="zh_CN"?'simhei':'emerald',
> 
> styleOptions.fontFamily = localStorage.getItem('prLang')==="zh_CN"?'MuZaiPixel':'pkmnems';
> 
> and same judgement logic for changing font-size, let the size is smaller.

it's not like that easy, i've tried but the font size logic runs different from CSS