Complete after you implementation (no localization)
pagefaultgames/pokerogue pull request #1789
Opened 2024-06-04 11:11 UTC by Raidette

# After you implementation

Added the after you attack, that makes the target act right after the user, regardless of priority.
It currently only lacks localization for the displayed message.

Upon writing this request, i saw an older PR for the same move but it never got closed, so it might count as an overlap
(sorry, new to contributing, will be more careful next time)

## How to test the changes?
- Create a new team with Charmander and Bulbasaur (or any team with one faster and slower pokémon than Ivysaur)
- The overrides file will start a double battle against two same-level Ivysaurs with only splash
- Both your pokémon will have After You, Focus Punch, Headbutt and Accelerock

## Singles and doubles example
(slower then faster)
https://github.com/pagefaultgames/pokerogue/assets/73134872/a05fc079-f705-416a-a17c-b0829c36d87f

(lower priority, higher priority, faster target)
https://github.com/pagefaultgames/pokerogue/assets/73134872/b8096383-032e-430a-a157-8ba24919641a

## Checklist
- [ ] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
- [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
- [x] Have I provided screenshots/videos of the changes?

2024-06-04 15:43 UTC, Madmadness65 requested changes
You seem to have committed override changes to this PR. Please reset those first, before we can test this moves functionality.

2024-06-05 00:25 UTC, Raidette commented
Done !

2024-08-14 03:26 UTC, DayKev submitted a review, later dismissed

2024-08-14 03:26 UTC, DayKev commented on src/data/move.ts
> +    user.scene.queueMessage(getPokemonMessage(target," took the kind offer!"));
Please add placeholder messages in the various locale files (`src/locale/*/move-trigger.ts`), the localization team can then translate it. You can use other `Attr`s messages as an example.

2024-08-14 03:26 UTC, DayKev commented on src/data/move.ts
> +  private afterYouText:string;
```suggestion
  private afterYouText: string;
```
Small nit.

2024-08-24 07:06 UTC, flx-sta commented
@DayKev mind taking over this PR? It seems the original author just abandoned it. You have write access.

2024-08-24 08:40 UTC, DayKev commented
GitHub ran out of memory when running the test suite...

2024-08-24 14:51 UTC, flx-sta commented
If you want to debug it try using this
https://vitest.dev/config/#logheapusage

If you want a “quick” potential fix try using this:
https://vitest.dev/config/#pooloptions-vmthreads-memorylimit

2024-09-02 08:38 UTC, innerthunder requested changes

2024-09-02 08:38 UTC, innerthunder commented on src/data/move.ts
> +      target.scene.unshiftPhase(new MovePhase(target.scene, target, [...nextAttackPhase.targets], nextAttackPhase.move));
A bit of a sequencing error here. Say P0 goes first and uses After You on P1. Then the phase sequence would look like
```
P0 MovePhase, MoveEffectPhase --> P1 MovePhase, MoveEffectPhase, MoveEndPhase --> P0 MoveEndPhase
```
This would cause some awkwardly-timed post-move effects (e.g. Nightmare)

2024-09-06 21:54 UTC, flx-sta commented
Closing due to inactivity.
If you want to re-open it let us know

2024-09-07 07:53 UTC, DayKev commented on src/data/move.ts
> +      target.scene.unshiftPhase(new MovePhase(target.scene, target, [...nextAttackPhase.targets], nextAttackPhase.move));
Nice catch, fixed!

2024-09-09 21:04 UTC, flx-sta commented
https://github.com/user-attachments/assets/5e979251-f5cf-44d4-aa4f-e6a226875ba0

<sup>https://www.bisafans.de/attackendex/galanterie.php</sup>

2024-09-09 21:07 UTC, flx-sta approved these changes

2024-09-09 21:09 UTC, flx-sta approved these changes

2024-09-09 21:21 UTC, innerthunder approved these changes

2024-09-09 21:24 UTC, ben-lear approved these changes

2024-09-09 21:31 UTC, CodeTappert approved these changes

2024-09-09 21:32 UTC, SangaraSorama approved these changes

2024-09-09 21:35 UTC, merged