[Move] Implemented Court Change
pagefaultgames/pokerogue pull request #1799
Opened 2024-06-04 16:15 UTC by MutenYoshii

## What are the changes?

Added Court Change into the game. 
## Why am I doing these changes?

The move was unimplemented

## What did change?

 Added a swaptagsattr to move.ts. Also added a boolean value named quiet to ignore onAdd and onRemove tags when the move is used in arena-tag and arena.ts

### Screenshots/Videos

## How to test the changes?

I tested the move through override and the enemy would use on field effects, move works with spikes, toxic spikes, stealth rock,
sticky web, tailwind, light screen, reflect, and mist

I did.

No

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

Sticky Web:
https://github.com/pagefaultgames/pokerogue/assets/171395666/488d7831-cd10-4c2c-b327-8fab43232ebc
Mist: 
https://github.com/pagefaultgames/pokerogue/assets/171395666/b1a5fce9-d4e9-4156-b066-a026a4e4fd09
Light Screen:
https://github.com/pagefaultgames/pokerogue/assets/171395666/2d027324-7749-446f-9bff-0c898770c8bf
Toxic Spikes:
https://github.com/pagefaultgames/pokerogue/assets/171395666/0b9eb43e-012d-46a9-9e2a-d919ae2b3ced
Spikes:
https://github.com/pagefaultgames/pokerogue/assets/171395666/4081f822-707e-47a4-9c84-d453a2d0519a

2024-06-04 16:29 UTC, OrangeRed requested changes

2024-06-04 16:29 UTC, OrangeRed commented on src/data/arena-tag.ts
> +    super.onAdd(arena, quiet);
if you're going to explicitly check `quiet === false` you should default this variable to false everywhere.

2024-06-04 16:29 UTC, OrangeRed commented on src/data/move.ts
> +
Is getting arena tags one by one like this really the best option?
You can use `Arena.findTagsOnSide(matchFn)` to get all of the tags that pass the match function and then do enemy swapping / player swapping separately using a shared method.

2024-06-04 17:38 UTC, MutenYoshii commented on src/data/move.ts
> +
Sorry, I don't know how to do a Match Function, would it be something like a function with a switch statement that returns true if any of the valid tags are present? Would I put the shared method in arena or in move?

2024-06-04 18:45 UTC, OrangeRed commented on src/data/move.ts
> +
this is the type defintion of the match function `(t: ArenaTag) => boolean`
So `Arena.getTagsOInSide()` will return all tags that pass (return true) from any function that has the same signature 
For example `(tag) => !!swapTags.includes(tag)` <- will filter out all tags that are inside of swapTags

2024-06-04 18:58 UTC, MutenYoshii commented on src/data/move.ts
> +
So ```ts const tagPlayerTemp = user.scene.arena.findTagsOnSide((t => swapTags.includes(t.tagType)), ArenaTagSide.PLAYER);``` would work

2024-06-04 20:15 UTC, bennybroseph requested changes
I'm not sure that I like this implementation. Does this work with the new Arena Flyout?

2024-06-04 22:36 UTC, MutenYoshii commented
Didn't know I could just check the arena effects 

https://github.com/pagefaultgames/pokerogue/assets/171395666/819f9fb1-451e-4c4c-b11c-46017e9eabd4


https://github.com/pagefaultgames/pokerogue/assets/171395666/e1bdb0dd-d9c3-4802-b271-371d77ebf5a5


https://github.com/pagefaultgames/pokerogue/assets/171395666/fa7f48d3-10bc-4c30-882b-7a9a96b453d5


https://github.com/pagefaultgames/pokerogue/assets/171395666/0a12df36-a23e-4043-892d-17c184bdbe8a

2024-06-06 16:21 UTC, bennybroseph approved these changes

2024-06-06 16:26 UTC, bennybroseph requested changes

2024-06-06 16:26 UTC, bennybroseph commented on src/data/arena-tag.ts
> -  onAdd(arena: Arena, quiet: boolean): void {
I'd rather this than what you have now except `quiet` should be defaulted to false and only Court Change should remove/add it with `quiet` set to true. that way nothing changes for all other situations.

2024-06-06 16:54 UTC, MutenYoshii commented on src/field/arena.ts
> +  addTag(tagType: ArenaTagType, turnCount: integer, sourceMove: Moves, sourceId: integer, side: ArenaTagSide = ArenaTagSide.BOTH, quiet: boolean = false, targetIndex?: BattlerIndex): boolean {
I added the ```quiet``` boolean and initialized it to false. would that be good or would you want me to just make the change on move.ts

2024-06-06 16:58 UTC, bennybroseph commented on src/field/arena.ts
> +  addTag(tagType: ArenaTagType, turnCount: integer, sourceMove: Moves, sourceId: integer, side: ArenaTagSide = ArenaTagSide.BOTH, quiet: boolean = false, targetIndex?: BattlerIndex): boolean {
on arena-tag.ts where I commented

2024-06-06 17:02 UTC, bennybroseph requested changes

2024-06-06 17:02 UTC, bennybroseph commented on src/data/move.ts
> +    const swapTags = [ArenaTagType.AURORA_VEIL, ArenaTagType.LIGHT_SCREEN, ArenaTagType.MIST, ArenaTagType.REFLECT, ArenaTagType.SPIKES, ArenaTagType.STEALTH_ROCK, ArenaTagType.STICKY_WEB, ArenaTagTy
I feel like this should go somewhere outside of this function so that if people implement new swappable tags they can find this easier

2024-06-07 14:23 UTC, bennybroseph approved these changes

2024-06-07 14:27 UTC, merged