Create menu.ts
pagefaultgames/pokerogue pull request #181
Opened 2024-04-18 10:26 UTC by K4ution

Created a translated version of menu.ts
Directory named es_ES assuming there are going to be different versions for latam

2024-04-21 18:54 UTC, dpMelian requested changes
Great work! I have some recommendations if you could have a look at them. Thanks!

2024-04-21 18:54 UTC, dpMelian commented on src/locales/es_ES/menu.ts
> +    "selectGameMode": "Elegir modo de juego.",
## English
I think we should name this "Elige un modo de juego.". The prompt is asking you directly to choose a game mode so I would go with the text I mentioned. What do you think?

## Spanish
 Creo que sería mejor nombrar a esto «Elige un modo de juego.». El menú del juego te pide directamente que elijas un modo de juego entonces creo que es más apropiado la frase que he mencionado. ¿Cómo lo ves?

2024-04-21 18:54 UTC, dpMelian commented on src/locales/es_ES/menu.ts
> +    "trainerAppeared": "¡{{trainerName}} quiere luchar!",
## English
In the English version there is a `\n` character, maybe you want to consider adding this.

## Spanish
En la versión inglesa hay un carácter `\n`, quizá puedas revisar esto.

2024-04-21 18:54 UTC, dpMelian commented on src/locales/es_ES/menu.ts
> +    "multiWildAppeared": "¡Un {{pokemonName1}} y {{pokemonName2}} salvajes aparecieron!",
## English
Same here, I think you are missing a `\n` character.

## Spanish
Lo mismo aquí, creo que te dejaste un carácter `\n`.

2024-04-21 18:54 UTC, dpMelian commented on src/locales/es_ES/menu.ts
> +    "sendOutPokemon": "¡Vamos! ¡{{pokemonName}}!",
## English
Same as above

## Spanish
Aquí igual que arriba

2024-04-21 18:54 UTC, dpMelian commented on src/locales/es_ES/menu.ts
> +    "playerGo": "¡Vamos! {{pokemonName}}!",
## English
I think the text would look better like this: `¡Vamos, {{pokemonName}}!` Also because you are adding a `!` without a `¡` . By the way I just checked my Ruby version and it says `¡Adelante, {{pokemonName}}!` in case you want to use that one instead.

## Spanish
Creo que el texto luciría mejor así: `¡Vamos, {{pokemonName}}!` También por el hecho de que cierras admiración `!` pero no la abres `¡` . Por cierto, acabo de comprobar mi edición Rubí y dice `¡Adelante, {{pokemonName}}!` si prefieres esa versión.

2024-04-21 18:54 UTC, dpMelian commented on src/locales/es_ES/menu.ts
> +    "moveDisabled": "{{moveName}} está deshabilitado!",
## English
You are missing a `¡` here at the beginning

## Spanish
Te falta un `¡` al inicio

2024-04-21 18:54 UTC, dpMelian commented on src/locales/es_ES/menu.ts
> +    "noPokeballForce": "Una fuerza misteriosa\npreviene usar Poké Balls.",
## English
Here I would say `impide` instead of `previene` what do you think?

## Spanish
Aquí usaría `impide` en lugar de `previene`. ¿Qué opinas?

2024-04-21 18:54 UTC, dpMelian commented on src/locales/es_ES/menu.ts
> +    "noPokeballStrong": "¡El Pokémon objetivo es demasiado fuerte para ser capturado!\nNecesitas bajarle la vida primero!",
## English
You are missing a `¡` here at the beginning of the second phrase

## Spanish
Te falta un `¡` al inicio de la segunda frase

2024-04-21 18:55 UTC, dpMelian commented
For other reviewers, could you check if the position of `\n` characters in the strings are correct? I don't know the project well enough yet to test for myself

2024-04-21 21:48 UTC, K4ution commented
> Great work! I have some recommendations if you could have a look at them. Thanks!

Thanks for pointing those out! I have implemented your suggestions and fixes

2024-04-21 21:49 UTC, dpMelian approved these changes
As a native speaker I approve this PR! Nice job!

2024-05-14 20:04 UTC, TempsRay commented
es/Menu.ts has already been merged in so I will close out this PR.

2024-05-14 20:04 UTC, closed without merging