[Bug] Fix Toxic Chain applying for non-damaging moves
pagefaultgames/pokerogue pull request #1814
Opened 2024-06-05 04:40 UTC by drew9696

## What are the changes?
This changes the behavior of Toxic Chain to only activate on damaging moves

## Why am I doing these changes?
This [bug report](https://github.com/pagefaultgames/pokerogue/issues/1767) outlines the functional behavior of `Toxic Chain`, even if the description is not fully accurate to its effects

Previously, status moves could trigger Toxic Chain which is unacceptable.
Additionally, the default behavior of `PostAttackAbAttr` actually wasn't checking that we were using a damaging move, it triggered if any move was used.

## What did change?
This modifies the base behavior of `PostAttackAbAttr` to check that the move used is a damaging attack and not a `STATUS` move.
* This behavior is applied by default to all extensions of this class, but only needs to be "turned off" in the case of the ability `Poison Puppeteer` which is defined by `ConfusionOnStatusEffectAbAttr`
* All other `PostAttackAbAttr` abilities have been checking explicitly to enforce this condition already in slightly different ways, so this change gives a simpler/more generic way ensuring any future extensions can leverage the "damaging move required" functionality
  * Classes that will apply this behavior and can remove their special handling:
    * `PostAttackStealHeldItemAbAttr`
    * `PostAttackApplyStatusEffectAbAttr`
    * `PostAttackContactApplyStatusEffectAbAttr`
    * `PostAttackApplyBattlerTagAbAttr`

### Screenshots/Videos
*Before my fix:*
https://github.com/pagefaultgames/pokerogue/assets/25591514/d26db051-9612-418e-a6b8-9c1c8f668ba1

*After fix:*
Not really much to show except that toxic chain doesn't occur in this scenario anymore

## How to test the changes?
Can test the fix with the `src/overrides.ts` file
```
export const ABILITY_OVERRIDE: Abilities = Abilities.TOXIC_CHAIN;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.GROWL];
```

Can regression test by changing the ability to any of the following:
```
Abilities.MAGICIAN
Abilities.POISON_TOUCH
Abilities.STENCH
```

Can regression test poison puppeteer's confusion with the following:
```
export const STARTER_SPECIES_OVERRIDE: Species = Species.PECHARUNT;
export const ABILITY_OVERRIDE: Abilities = Abilities.POISON_PUPPETEER;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.TOXIC];
```

## Checklist
- [ ] There is no overlap with another PR?
   - #1440 changes the move type on `applyPostAttack` from `PokemonMove` to `Move`
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - N/A Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-06-05 13:54 UTC, OrangeRed requested changes

2024-06-05 13:54 UTC, OrangeRed commented on src/data/ability.ts
> +
I understand what you're doing here but I think passing in a `type PokemonAttackCondition = (user: Pokemon, target: Pokemon, move: Move) => boolean;` function would allow for more control / be more readable than a naked boolean like this.

2024-06-06 03:16 UTC, drew9696 commented on src/data/ability.ts
> +
Makes sense, but we do lose the `hitResult` check by doing this. I do think upon further investigation that we actually need to have hit before calling this function anyways so I think that was a frivolous check in the first place. I'll change it up, thanks!

2024-06-11 21:37 UTC, OrangeRed requested changes

2024-06-11 21:37 UTC, OrangeRed commented on src/data/ability.ts
> +  applyPostAttackAfterMoveTypeCheck(pokemon: Pokemon, passive: boolean, defender: Pokemon, move: PokemonMove, hitResult: HitResult, args: any[]): boolean | Promise<boolean> {
Instead of doing all of these renaming shenanigans can you instead invoke `super.applyPostAttack()` in all of children classes that potentially need to check the default move condition?

2024-06-11 21:59 UTC, drew9696 commented on src/data/ability.ts
> +  applyPostAttackAfterMoveTypeCheck(pokemon: Pokemon, passive: boolean, defender: Pokemon, move: PokemonMove, hitResult: HitResult, args: any[]): boolean | Promise<boolean> {
I actually prefer the renaming stuff because invoking `super.applyPostAttack()` requires that any future class that extends this also calls that method. By having a second method that is the default one to be overridden, it guarantees that each class will have this behavior applied for free without having to remember to call it, and calling it should happen in every invocation of this IMO. If you feel strongly against this and prefer the explicit calling of a super method I can change it but I honestly find this way to be better where we apply default behavior by default rather than by remembering.

2024-06-11 23:13 UTC, OrangeRed commented on src/data/ability.ts
> +  applyPostAttackAfterMoveTypeCheck(pokemon: Pokemon, passive: boolean, defender: Pokemon, move: PokemonMove, hitResult: HitResult, args: any[]): boolean | Promise<boolean> {
I agree that its nice to get the functionality 'for free' via inheritance but in the future when someone who has never touched this code before tries to make a new class or extend a `PostAttack` child they might have a hard time understanding what is happening when something not explicitly invoked is being executed.

If you want to continue with that route at the very least add some jsdoc comments to the parent `applyPostAttack` and `applyPostAttackAfterMoveTypeCheck` functions that explain the above. Make sure to add a `/** {@linkcode applyPostAttack} */` so someone unfamiliar can jump to parent's implementation when they need.

2024-06-15 03:36 UTC, drew9696 commented on src/data/ability.ts
> +  applyPostAttackAfterMoveTypeCheck(pokemon: Pokemon, passive: boolean, defender: Pokemon, move: PokemonMove, hitResult: HitResult, args: any[]): boolean | Promise<boolean> {
Thank you for your flexibility! Will do and I'll merge to resolve conflicts!

2024-07-11 20:15 UTC, OrangeRed commented
I think the changes here are good but its probably for the best that you try to create some tests that verify everything works.

2024-07-30 21:39 UTC, Tempo-anon commented on src/data/ability.ts
> +        const heldItems = this.getTargetHeldItems(defender).filter(i => i.getTransferrable(false));
```suggestion
        const heldItems = this.getTargetHeldItems(defender).filter(i => i.isTransferrable);
```

2024-07-30 21:44 UTC, merged