[QoL] Run History Function
pagefaultgames/pokerogue pull request #1815
Opened 2024-06-05 05:38 UTC by frutescens

## What are the changes?
This adds a new option on the menu for 'Run History'.
It allows users to store and look at a maximum of 25 past runs. This functionality automatically logs a run based on the current SessionSaveData and stores it in cache/the network database. At the moment, the function mirrors the 'Load Save' UI and only shows the team, whether they were victorious or not, the mode, wave, and the final timestamp of the run. 

The server-side code is here. 

## Why am I doing these changes?
This has been a feature requested by many users. In addition, this will allow the Balance and Development teams to do some analytics and have data on the gameplay experience. 

I also have a bad memory so I thought it would be helpful to be able to access past runs to see what I need to do better. 

## What did change?
There are many changes:
- New Menu Option
- New UI
- New 'RunHistoryData' item in cache
- Network communication with new endpoint / table in database
- New post-battle behavior

### Screenshots/Videos
Will attach videos soon. I messed up my Github settings foolishly. 

## How to test the changes?

Play normally and log runs - successful or losses. 

Yes - but just to kill my Pokemon faster so I could log defeats. 

No

Yes - need to run RogueServer for network/database functionality
If running this locally, you may need to change the parameters in phases.ts line 3954 to true. 

## Checklist
- [ x ] There is no overlap with another PR?
- [ x ] The PR is self-contained and cannot be split into smaller PRs?
- [ x ] Have I provided a clear explanation of the changes?
- [ x ] Have I tested the changes (manually)?
    - [ x ] Are all unit tests still passing? (`npm run test`)
    This still does not pass the Linter, but I plan on cleaning the PR up once all changes are made. My code is really messy, so I feel hesitant to remove all the imports.
- [ x ] Are the changes visual?
  - [ x ] Have I provided screenshots/videos of the changes?

2024-06-05 06:14 UTC, flx-sta reviewed
You seem to be using a lot of `.then()` etc. is there a specific reason not to use `async/await` instead?

2024-06-05 06:14 UTC, flx-sta commented on src/system/game-data.ts
> +export interface RunHistoryData {
Why not array ?

2024-06-05 06:14 UTC, flx-sta commented on src/system/game-data.ts
> +  public parseSessionData(dataStr: string): SessionSaveData {
Why add public ?

2024-06-05 06:14 UTC, flx-sta commented on src/system/game-data.ts
> +      return JSON.parse(decrypt(localStorage.getItem(`runHistoryData_${loggedInUser.username}`, true),true));
Doesn’t this crash if the local storage item is not defined ?

2024-06-05 06:14 UTC, flx-sta commented on src/system/game-data.ts
> +        var runHistoryData = response ? JSON.parse(response) : JSON.parse({});
```suggestion
        var runHistoryData = JSON.parse(response ?? {});
```

2024-06-05 06:14 UTC, flx-sta commented on src/system/game-data.ts
> +        console.log(Object.keys(runHistoryData));
You want to keep this console log ?

2024-06-05 06:42 UTC, frutescens commented on src/system/game-data.ts
> +  public parseSessionData(dataStr: string): SessionSaveData {
I think I started ignorant of everything and then learned some things during this. I'll fix it tomorrow. Thank you for all your suggestions!

2024-06-05 15:03 UTC, flx-sta commented on src/system/game-data.ts
> +export interface RunHistoryData {
but the key is just an integer. Which is basically what an array does too.
Or am I missing something?

2024-06-05 19:05 UTC, frutescens commented on src/system/game-data.ts
> +export interface RunHistoryData {
The key is a timestamp of when the run ended. Because for storage reasons, people are limited to only 25 runs, I use the timestamp to determine which one is the oldest run and remove that one.

2024-06-05 22:59 UTC, frutescens commented
![image](https://github.com/pagefaultgames/pokerogue/assets/171087428/d0f82120-05e1-4738-a08b-8ee971e04195)
Latest UI features

2024-06-17 14:52 UTC, brain-frog requested changes

2024-06-17 14:52 UTC, brain-frog commented on src/system/game-data.ts
> +  async public getRunHistoryData(scene: BattleScene): Promise<Object> {
'public' modifier must precede 'async' modifier.

2024-06-17 14:52 UTC, brain-frog commented on src/system/game-data.ts
> +        cachedResponse = JSON.parse(decrypt(cachedResponse, true));
if you want to reassign cachedResponse it needs to be a let not a const

2024-06-17 14:52 UTC, brain-frog commented on src/system/game-data.ts
> +      if (cachedResponse) {
do a localStorage.hasOwnProperty with the key first to determine if it exists before setting it

2024-06-17 14:52 UTC, brain-frog commented on src/system/game-data.ts
> +    if (!Utils.local) {
its Utils.isLocal

2024-06-17 14:52 UTC, brain-frog commented on src/system/game-data.ts
> +        const response = Utils.apiPost("savedata/runHistory", JSON.stringify(runHistoryData), undefined, true);
are you using this anywhere?

2024-06-17 16:40 UTC, frutescens commented on src/system/game-data.ts
> +        const response = Utils.apiPost("savedata/runHistory", JSON.stringify(runHistoryData), undefined, true);
Yes, in src/phases.ts in handleGameOver()

2024-06-19 14:40 UTC, brain-frog commented
also just so you know in your PR description
anything marked with `<!-- -->` in markdown means its a comment. if you respond to them it looks like you're saying "Yes" or "No" to nothing
if you want to respond to each of them, remove bookends that make it a comment

2024-06-20 22:57 UTC, frutescens commented
I'm still chipping away at some things but let me know if there's any changes I should make 
![image](https://github.com/pagefaultgames/pokerogue/assets/171087428/5b8765c6-13d1-4674-b4c0-a4ff27a71e0a)

2024-06-21 16:15 UTC, diazhi commented
I think the boxes indicating typing behind the icons are unnecessary and tacky.
There should be space to indicate whether or not the run was a Challenge.
The small text presents a readability issue.

2024-06-21 19:35 UTC, frutescens commented
Hi, I'll keep on consulting with others to find the best balance between simplicity/shareability and legibility. I personally disagree on the tackiness but I understand that aesthetics are a matter of personal opinion. Feel free to contribute in #dev-corner. 
I already implemented Challenges so people are able to see which rules they chose.

2024-06-28 20:58 UTC, frutescens reviewed
Addressed the issues + added the menu condition

2024-06-28 20:58 UTC, frutescens commented
Finalized Images
![image](https://github.com/pagefaultgames/pokerogue/assets/171087428/aa3abf02-6d96-4650-8e4a-9fd3929b9919)
![image](https://github.com/pagefaultgames/pokerogue/assets/171087428/e0ac31e8-a597-4ebc-b432-22900b6f78b7)

2024-06-28 21:09 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +      const spdef = addBBCodeTextObject(this.scene, 0, 0, i18next.t("pokemonInfo:Stat.SPDEFshortened")+": "+pStats[4], TextStyle.SUMMARY, { fontSize: "34px", align: "center" });
`34x` is considered a "Magic String" here. Please put it into a const and give it a descriptive name

2024-06-28 21:49 UTC, frutescens commented on src/ui/run-info-ui-handler.ts
> +      const spdef = addBBCodeTextObject(this.scene, 0, 0, i18next.t("pokemonInfo:Stat.SPDEFshortened")+": "+pStats[4], TextStyle.SUMMARY, { fontSize: "34px", align: "center" });
thank you! fixed!

2024-07-06 04:46 UTC, flx-sta commented on src/system/game-data.ts
> +      const data = await dataAPI.json();
```suggestion
      const response = await Utils.apiFetch("savedata/runHistory", true);
      const data = await response.json();
```

you are dealing with responses, not some API

2024-07-30 15:11 UTC, closed without merging