[Documentation] documentation of move.ts
pagefaultgames/pokerogue pull request #1828
Opened 2024-06-05 16:32 UTC by DustinLin

## What are the changes?

Documentation

## Why am I doing these changes?
Documentation is good

## What did change?
Nothing, just comments

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-05 18:08 UTC, EvasiveAce commented on src/data/move.ts
> +   * takes as input a boolean function and returns the first MoveAttr in attrs that matches true
nitpick: Starting the doc as capitalized since the rest seem to do as well

2024-06-06 14:57 UTC, bennybroseph requested changes

2024-06-06 14:57 UTC, bennybroseph commented on src/data/move.ts
> +   * @param target a {@linkcode Pokemon}
For all of these `@param` comments, please start your sentence off with the `{@linkcode <TYPE>}` portion instead of having it randomly within the sentence. i.e.
```ts
/**
...
* @param flag {@linkcode MoveFlags} to check against
* @param user {@linkcode Pokemon} with this flag
* @param target {@linkcode Pokemon} target of the move
...
*/
```

Would need this done for all comments, not just this function

2024-06-06 15:59 UTC, DustinLin commented on src/data/move.ts
> +   * @param target a {@linkcode Pokemon}
fixed!

2024-06-06 17:05 UTC, bennybroseph requested changes

2024-06-06 17:05 UTC, bennybroseph commented on src/data/move.ts
> +   * @param target {@linkcode Pokemon}
what's the point of these comments

2024-06-06 17:45 UTC, DustinLin commented on src/data/move.ts
> +   * @param target {@linkcode Pokemon}
Not sure if you mean the @param comments, or the whole:
- @param comments are for jsdocs? luckily the param names are pretty self explanatory given the description in the above comment (line 538). I can add a blurb about them, if you think they aren't needed I could remove them altogether.
- the whole comment block is for the function, figured `checkFlag` didn't have a jsdoc entry so wanted to add one for it

2024-06-07 01:10 UTC, bennybroseph commented on src/data/move.ts
> +   * @param target {@linkcode Pokemon}
there's no comments though

2024-06-07 01:11 UTC, bennybroseph approved these changes

2024-06-07 01:11 UTC, merged