[Localization] #1761 Korean trainer dialogue (Gym leader in Kanto region)
pagefaultgames/pokerogue pull request #1830
Opened 2024-06-05 16:36 UTC by sodaMelon

[Localization] #1761 Korean trainer dialogue (Gym leader in Kanto region)

## What are the changes?

Translating locales\ko\dialogue.ts into Korean.
This PR is added korean dialogue **for Gym leader in Kanto region**

@sodaMelon @Ohmry @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.

## Why am I doing these changes?

Few trainers's dialogue have been translated into Korean yet.

## What did change?

I've just translated Gym leader(in Kanto, 1st pokemon)battles' dialogues.
3세대 호연지방 **포켓몬 관장(7명+쌍둥이2명)** 다이얼로그를 번역했습니다.
말투 교정에는 정발판 ORAS, BW2(짐리더 토너먼트)을 참고했습니다.
(루네시티 짐 리더 아단(juan)이 RSE에만 등장하고, ORAS에는 등장을 안하는 걸 깜빡했어요)

그치만 이상한 점이 있으면 편하게 지적해주세요!
리뷰어 아니셔도 그냥 지나가다 이상하다?싶으시면 리뷰 주셔됩니다.

### Screenshots/Videos

( very hard to meet them.... and it's dosen't matter)

## How to test the changes?

It seems there won't be much to test since it's just a translation of an existing .ts file. You can check it when you meet the respective trainers.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~~[ ] Are the changes visual?~~
  - ~~[ ] Have I provided screenshots/videos of the changes?~~

2024-06-05 16:41 UTC, sodaMelon commented
thanks Tempo-anon👍✨( just made a mistake because I am sleepy now......)

2024-06-05 16:44 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      3: "바위 동굴에서 길을 잃은 기분이야!"
바위 동굴은 철구(brawly)가 사는 무로 마을의 "뒷산"인데요. 
뒷산에서 길잃는다고 놀리는 대사가 아마 있을겁니다 ㅋㅋㅋㅋ 일단은 뒷산대신 그래도 원작 내용대로 갔어요

2024-06-05 16:47 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      3: "할아버지에게 배운 기술을 한 수 보여줄게! 승부다!"
move를 뭐로 해석해야 자연스러울까 고민했는데,
체스나 바둑, 장기에서 한 수 주고 받는것도 move더라구요. 
그래서 "한 수"가 됐습니다. 
(578 라인에도 move가 있긴한데.. 🤔 불 타입 체육관의 뜨거움을 살리는게 중요해보였습니다.)

2024-06-05 16:50 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      3: "란이랑 함께였다면, 우리가 이겼어.\n둘이선 더 잘 할 수 있다구!"
쌍둥이라서 624번 629번 라인 대사가 같은데요.
finish one's thought = finish one's sentence가 (모든 수를 예측하고 대처해서) 잘 처리한다...라는? 의미의 숙어라고 합니다. 적당히 끼워맞췄습니다.

2024-06-05 18:20 UTC, returntoice requested changes

2024-06-05 18:20 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "찌릿찌릿해질때가 됐군!\n와하하하핫!",
```suggestion
      1: "찌릿찌릿해질 때가 됐군!\n와하하하핫!",
```
맞춤법 수정입니다.

2024-06-05 18:20 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      2: "내…내가 이기다니!\n내 방식대로 한게 통했어!",
```suggestion
      2: "내…내가 이기다니!\n내 방식대로 한 게 통했어!",
```

2024-06-05 18:20 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      2: "우리의 쇼가 즐거웠길 바래요.\우아한 춤은 끝났습니다.",
```suggestion
      2: "우리의 쇼가 즐거웠길 바라요.\우아한 춤은 끝났습니다.",
```

2024-06-06 00:50 UTC, sodaMelon commented
@returntoice 바래<->바라 용법은 항상 제가 적어두고도... 표준 국어를 생각하면 혼란스러운데요. 방향 잡아주셔서 감사합니다!
알려주신 내용은 다 반영했습니다.🤗👍

2024-06-06 01:19 UTC, returntoice approved these changes

2024-06-06 01:52 UTC, Tempo-anon approved these changes

2024-06-06 01:52 UTC, merged