[QoL] Show currently bound controls on starter menu for last active device
pagefaultgames/pokerogue pull request #1859
Opened 2024-06-06 06:16 UTC by SquillWall

## What are the changes?
The starter screen will now show the appropriate keybinds based on the input device you are using, rather than a static string

## Why am I doing these changes?
I play mostly on mobile with controller, but also on PC with controller on occasion. Prior to these changes, there was no immediate way to know (from a UX perspective) which buttons on the controller corresponded to which toggles in the starter screen. This PR aims to fix that by polling input from the last device and dynamically updating the control icons to reflect it.

## What did change?
There was a significant change to starter-select-ui-handler::updateInstructions() in order to accomodate the new UI changes

### Screenshots/Videos
Prior to my changes: ![image](https://github.com/pagefaultgames/pokerogue/assets/170910983/ff0a0a2a-3c0e-497e-83c0-60849feccaf9)

After my changes (keyboard example): 
![image](https://github.com/pagefaultgames/pokerogue/assets/170910983/f37e9759-70d4-466f-86a6-346c1d390a08)

After my changes (controller example):
![image](https://github.com/pagefaultgames/pokerogue/assets/170910983/4bd44973-c14a-474b-8dc9-7e80b77558cd)

## How to test the changes?
- Select new game
- ensure you have a starter with multiple genders/natures/abilities unlocked
- connect an external controller to your device OR simply use your keyboard
- navigate the menu with one or both options to see the icons dynamically update based on your preferred input
- rebinds are also supported and should update the icons

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

![image](https://github.com/pagefaultgames/pokerogue/assets/170910983/51c0405d-ca54-4981-a8f3-eed7d70014be)
All unit tests passed

2024-06-06 07:47 UTC, Greenlamp2 requested changes

2024-06-06 07:47 UTC, Greenlamp2 commented on src/ui-inputs.ts
> +  detectInputMethod(evt): void {
Not needed, you can already know which is the last inputMethod with the "lastSource" property in input-controller

2024-06-06 07:47 UTC, Greenlamp2 commented on src/battle-scene.ts
> +  public inputMethod: string;
not needed, same property as lastSource in input-controller

2024-06-06 07:47 UTC, Greenlamp2 commented on src/ui/starter-select-ui-handler.ts
> +    if (this.scene.inputMethod === "gamepad") {
not needed, you just need to update the texture (.setTexture) to the lastSource to update correctly the icons displayed

2024-06-06 14:50 UTC, SquillWall commented
@Greenlamp2 thanks for the feedback! I'll resolve those issues when i'm off work tonight

2024-06-06 22:02 UTC, SquillWall commented on src/battle-scene.ts
> +  public inputMethod: string;
Unfortunately as far as i can tell, both this and detectInputMethod are needed... lastSource only detects whether the last input was from a keyboard or a controller, and since there's no distinction between the touch controls and an actual keyboard, i had to make one myself. This becomes an issue when you rebind a key on the keyboard, as you would then have a discrepancy between the static touch controls and the new icon showing from the rebound key.

2024-06-06 22:06 UTC, SquillWall commented on src/ui/starter-select-ui-handler.ts
> +    if (this.scene.inputMethod === "gamepad") {
This is also a bit more difficult since the elements are being dynamically populated into the container based on the types caught in the dex entry... If it would be more performant i could iterate over the list of sprites and update their textures but it will definitely add a lot more edge cases to account for than simply clearing the container and repopulating it with the appropriate objects. Let me know what you think would be best i guess

2024-06-06 22:11 UTC, SquillWall commented on src/ui-inputs.ts
> +  detectInputMethod(evt): void {
Same as below

2024-06-06 23:11 UTC, Greenlamp2 commented on src/battle-scene.ts
> +  public inputMethod: string;
good point, but i was working on syncing keys displayed on touch with the keys bound on keyboard, (it's in one of my stash, but it has not been discussed with other dev yet if it's something we really want) until then, ok to leave it like that, but when/if synced keys are merged, i count on you to update your work

2024-06-06 23:17 UTC, Greenlamp2 commented on src/ui/starter-select-ui-handler.ts
> +    if (this.scene.inputMethod === "gamepad") {
Yeah, I understand. Indeed, the gain is minimal. If it can avoid adding unexpected issue, that's fine with me.

2024-06-06 23:42 UTC, SquillWall commented on src/battle-scene.ts
> +  public inputMethod: string;
Yeah definitely can do just give me a shout when/if those changes are merged in

2024-06-07 01:39 UTC, SquillWall commented
Merge conflicts are resolved so assuming this is ready for merge unless you had any other feedback for me to take care of greenlamp

2024-06-07 08:12 UTC, Greenlamp2 submitted a review, later dismissed

2024-06-07 20:08 UTC, SquillWall commented
NOTE BEFORE MERGE: i need to update locales other than english

2024-06-07 20:14 UTC, SquillWall commented
sorry to ping you again @Greenlamp2 nothing changed functionally here, was just updating the control strings for other locales as well

2024-06-08 21:21 UTC, Greenlamp2 approved these changes

2024-06-08 21:22 UTC, Greenlamp2 commented
It's good for me, i ask the input from the other dev, this is the final step, if they are all okay, i'll merge it, otherwise, i'll let you know what need to be changed.

2024-06-08 21:23 UTC, bennybroseph commented
Does this hide text when that cycle key isn't available? For example since Sentret doesn't have other forms, the form button should be hidden.

2024-06-08 22:36 UTC, SquillWall commented
@bennybroseph it does! The buttons will hide and show dynamically the same way that they did before (based on what you've caught/unlocked). Here's an example of my spearow for example from my local save that only has gender and nature to toggle
![image](https://github.com/pagefaultgames/pokerogue/assets/170910983/d4ab816a-e174-42a2-a838-1a5eb336bf04)

2024-06-09 01:35 UTC, merged

2024-06-09 01:38 UTC, Greenlamp2 commented
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/dabb3c40-0d9b-4b5a-90d9-61b1078c1414)

some elipsis might be needed there