[Localization] #1761 Korean trainer dialogue (Gym leader in Johto region with Elite-4)
pagefaultgames/pokerogue pull request #1878
Opened 2024-06-06 16:13 UTC by sodaMelon

[Localization] #1761 Korean trainer dialogue (Gym leader in Johto region with Elite-4)
## What are the changes?

Translating locales\ko\dialogue.ts into Korean.
This PR is added korean dialogue for **Gym leader in Johto region.** (2nd Pokemon Games)
I also translated **Elite-4's in 1st and 2nd's.**

@sodaMelon @Ohmry @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.

## Why am I doing these changes?

Few trainers's dialogue have been translated into Korean yet.

## What did change?

I translated **Gym leader(in Johto, 2nd pokemon)battles' dialogues.**
I also did **Elite-4's in 1st and 2nd game**

### Screenshots/Videos

( very hard to meet them.... and it's dosen't matter)

## How to test the changes?

It seems there won't be much to test since it's just a translation of an existing .ts file. You can check it when you meet the respective trainers.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~~[ ] Are the changes visual?~~
  - ~~[ ] Have I provided screenshots/videos of the changes?~~

2024-06-06 16:37 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "이걸로 끝!"
That's that 이라는 숙어가 있더라구요.
```
an expression that shows that something has ended:
I won't agree to it and that's that (= I won't discuss it any longer).
```
그래서 꼭두답게 깜찍하게 번역했습니다

2024-06-06 16:39 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "끝이다."
검은먹시티의 이향(드래곤)도 똑같이 That's that을 쓰는데
프라이드, 거만함을 싣어서 짧게 번역했습니다.

2024-06-06 18:33 UTC, returntoice requested changes
Great overall, but some suggestions

2024-06-06 18:33 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      5: "수련이 더 필요 하겠군.",
```suggestion
                $그치만 넌 그것과 다른 무언가를 많이 갖고 있는 것 같네… 흐음.`,
      5: "수련이 더 필요하겠군.",
```

2024-06-06 18:33 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "내가…다시 한 발짝 앞섰어.",
```suggestion
      1: "내가… 다시 한 발짝 앞섰어.",
```

2024-06-06 18:33 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: `얼음 포켓몬은 나를 대적할 사람이 없지! 빙결의 길은 강해!
```suggestion
      1: `얼음포켓몬을 내보내면 대적할 사람이 없지! 상대를 얼린다는 건 매우 강력한 공격이야.
```
"move"의 의미가 명확히 안 사는 것 같아서 [레츠고 대사 원문](https://youtu.be/Cy39z1HhLXo?si=rE9sudltMltrYclI&t=136)을 그대로 쓰는 걸 제안해 봅니다.

2024-06-06 18:33 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      3: "언제라도 다시 찾아와, 상대해줄게."
찾아보니 여섯 개 다 포켓몬 스타디움2의 대사던데, 그렇게 중요한 대사도 아니니 그래도 카렌인데 여섯 중 하나 대신 '그 유명한 대사' 하나 넣어보는 건 어떨까 제안해 봅니다 ㅋㅋㅋ

"강한 포켓몬, 약한 포켓몬, 그런 건 사람이 멋대로 정하는 것."
아니면
"강한 포켓몬, 약한 포켓몬, 그런 건 사람이 멋대로 정하는 것.\n정말 강한 트레이너라면 좋아하는 포켓몬으로 이길 수 있도록 열심히 해야 해."
하면 어떨까요?

2024-06-06 18:33 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "하! 나에게 도전하겠다고? 용감하거나, 혹은 무지막지한 녀석이군?"
```suggestion
      1: "하! 나에게 도전하겠다고? 용감한 거냐, 아니면 그냥 무모한 거냐?"
```
표현이 조금 어색한 듯하여 고쳐 보았습니다.

2024-06-07 00:13 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      3: "언제라도 다시 찾아와, 상대해줄게."
ㅋㅋㅋㅋ 저도 팬심으로 이거 넣고 싶었어요!! 근데 dialouge에는 비슷한 뉘앙스가 없어서~~  승리 다이얼로그를 사람들이 좀 더많이 보니까 거기 넣을까요? 
패배 다이얼로그는 거의 볼일이 없어서 ㄷㄷㄷ(물론 1xx스테이지 넘어가면 다르긴합니다)

2024-06-07 00:23 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: `얼음 포켓몬은 나를 대적할 사람이 없지! 빙결의 길은 강해!
이게 나은 것같아요 ㅋㅋ어제 렛츠고피카츄 칸나 대면 장면 고민하다가 그렇게 썼는데 확인감사합니다

2024-06-07 00:30 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "예상했던 대로네.",
```suggestion
      1: "정말 강한 트레이너라면 좋아하는 포켓몬으로 이길 수 있도록 열심히 해야 해.",
```
카렌의 생각이 드러날 수 있는 문장을 시그니쳐 대사로 고쳐 썼습니다.( That's about what I expected(

2024-06-07 00:32 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "예상했던 대로네.",
졌을 때 열심히 해! 라는 격려가 필요하다고 생각해서 이쪽에 넣었습니다

2024-06-07 01:23 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "안돼! 내가 지다니. 너 어떻게 그렇게 강해졌어?",
```suggestion
      1: "안돼! 내가 지다니. 너 어떻게 그렇게 강해졌어?(고민중)",
```
여기가 너무 좀... (저희가아는) 카렌스럽지 않은 말투라 생각좀해보겠습니다

2024-06-07 03:14 UTC, GINK-SS reviewed
정말 잘하셨네요! 성격도 반영해서 번역하는 게 너무 맘에 듭니다!!

2024-06-07 03:14 UTC, GINK-SS commented on src/locales/ko/dialogue.ts
> +      1: "얼마든지 내게 도전 할 수있 지만, 결과는 절대 바뀌지 않을 거다!"
띄어쓰기 관련 수정 : "얼마든지 내게 도전 할 수 있지만, 결과는 절대 바뀌지 않을 거다!"

2024-06-07 03:14 UTC, GINK-SS commented on src/locales/ko/dialogue.ts
> +      1: "있지! 포켓몬들말이야, 정말 너무 귀엽지?"
띄어쓰기 수정 : "있지! 포켓몬들 말이야, 정말 너무 귀엽지?"

2024-06-07 03:14 UTC, GINK-SS commented on src/locales/ko/dialogue.ts
> +      1: "젊음만으로는 승리를 보장할수 없다! 중요한 것은 경험이다."
띄어쓰기 수정 : "젊음만으로는 승리를 보장할 수 없다! 중요한 것은 경험이다."

2024-06-07 04:43 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "얼마든지 내게 도전 할 수있 지만, 결과는 절대 바뀌지 않을 거다!"
```suggestion
      1: "얼마든지 내게 도전 할 수 있지만, 결과는 절대 바뀌지 않을 거다!"
```

2024-06-07 04:43 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "있지! 포켓몬들말이야, 정말 너무 귀엽지?"
```suggestion
      1: "있지! 포켓몬들 말이야, 정말 너무 귀엽지?""
```

2024-06-07 04:44 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "젊음만으로는 승리를 보장할수 없다! 중요한 것은 경험이다."
```suggestion
      1: "젊음만으로는 승리를 보장할수 없다! 중요한 것은 경험이다."
```

2024-06-07 04:52 UTC, sodaMelon commented
@returntoice 카렌 dialouge 좀 더 캐릭터성이 잘 드러나게 고쳐썼어요.(Modified Karen's dialouge more characteristic)  기본적인의미는 영문 원본 대사에서 가져오고, 내용 자체는 본가 게임 스크립트에서 차용했습니다.
✔대사 길이가 길어져서 짤리지 않을까 조금 걱정되네요

@GINK-SS 띄어쓰기 적용했습니다🎶

검토 부탁드립니다~ ㅎ_ㅎ

2024-06-07 06:43 UTC, GINK-SS approved these changes

2024-06-07 09:30 UTC, returntoice approved these changes

2024-06-08 02:32 UTC, Tempo-anon approved these changes

2024-06-08 02:32 UTC, merged