[Bug] Show C-Button on Mobile during Modifier Selection
pagefaultgames/pokerogue pull request #1893
Opened 2024-06-06 21:07 UTC by prime-dialga

## What are the changes?
The C-Button is now shown on Mobule when selecting a modifier.

## Why am I doing these changes?
The C-Button is required to access additional information for the move a TM teaches.

## What did change?
Adjusted CSS Rule responsible for hiding the button during modifier selection to show the button.

### Screenshots/Videos
Before:
![IMG_0247](https://github.com/pagefaultgames/pokerogue/assets/10091050/2dc782ed-3055-49dc-bcf3-72fad5e14326)

Now a C Button appears in the bottom right corner, similar to the combat menu.

## How to test the changes?
Enter a fight, end the fight, the button should still be present.

Though, to be more specific:
Change the following override to get a TM as a reward.
`export const ITEM_REWARD_OVERRIDE: Array<String> = [];`
with
`export const ITEM_REWARD_OVERRIDE: Array<String> = ["TM_COMMON"];`
When hovering over the TM, before selecting it, you should be able to press C to view additional information.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)? Since i am not a mobile user, testing is unfortunately still required.
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-06 21:40 UTC, flx-sta commented
lgtm ✅ 
<img width="851" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/167e882a-2064-4701-b167-5fdb9dd74bdb">

2024-06-06 21:43 UTC, flx-sta requested changes

2024-06-06 21:43 UTC, flx-sta commented on index.css
> +#touchControls:not([data-ui-mode='COMMAND']):not([data-ui-mode='FIGHT']):not([data-ui-mode='BALL']):not([data-ui-mode='TARGET_SELECT']):not([data-ui-mode='MODIFIER_SELECT']) #apad .apadBattle {
since CSS4 not can be used with multiple params to chain them 

```suggestion
#touchControls:not([data-ui-mode='COMMAND'], [data-ui-mode='FIGHT'], [data-ui-mode='BALL'], [data-ui-mode='TARGET_SELECT'], data-ui-mode='MODIFIER_SELECT']) #apad .apadBattle {
```
**untested!**

source: https://developer.mozilla.org/en-US/docs/Web/CSS/:not?ref=serpapi

2024-06-06 21:49 UTC, prime-dialga commented on index.css
> +#touchControls:not([data-ui-mode='COMMAND']):not([data-ui-mode='FIGHT']):not([data-ui-mode='BALL']):not([data-ui-mode='TARGET_SELECT']):not([data-ui-mode='MODIFIER_SELECT']) #apad .apadBattle {
Tested on FF and it works; however: Opera (Android) doesn't seem to support that function, according to your reference link.
So it might not be worth it to improve the code style...

2024-06-06 21:53 UTC, flx-sta commented on index.css
> +#touchControls:not([data-ui-mode='COMMAND']):not([data-ui-mode='FIGHT']):not([data-ui-mode='BALL']):not([data-ui-mode='TARGET_SELECT']):not([data-ui-mode='MODIFIER_SELECT']) #apad .apadBattle {
that is true. Not worth it then. MB

2024-06-07 00:20 UTC, bennybroseph approved these changes

2024-06-07 00:20 UTC, merged