[Enhancement] Move event files to a central directory
pagefaultgames/pokerogue pull request #1918
Opened 2024-06-07 19:25 UTC by torranx

## What are the changes?
- Move event files to a single folder

## Why am I doing these changes?
- more organized file system

## What did change?
- file paths/directory

### Screenshots/Videos
- tests passed
<img width="367" alt="Screenshot 2024-06-08 at 3 12 21 AM" src="https://github.com/pagefaultgames/pokerogue/assets/68144167/961e0412-6522-4685-b19d-28ebd3d0cc7d">

## How to test the changes?
- this does not necessarily need testing because vscode autofills the file paths and no errors on my terminal

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
- [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
- [x] Have I provided screenshots/videos of the changes?

2024-06-07 19:37 UTC, flx-sta requested changes

2024-06-07 19:37 UTC, flx-sta commented on src/events/battle-scene.ts
> +import { BerryModifier } from "../modifier/modifier.js";
```suggestion
import { BerryModifier } from "../modifier/modifier";
```

2024-06-07 20:11 UTC, flx-sta commented
### lgtm 🚀

Build ✅ 
Tests ✅ 
Play (till wave 8, wasn't prepared for the rival..) ✅

2024-06-07 20:12 UTC, flx-sta approved these changes
### lgtm 🚀

Build ✅ 
Tests ✅ 
Play (till wave 8, wasn't prepared for the rival..) ✅

2024-06-11 01:04 UTC, bennybroseph approved these changes

2024-06-11 01:18 UTC, bennybroseph approved these changes

2024-06-11 01:19 UTC, merged