Ability Bar can now be localized. In a way that pokemonName abilityNa…
pagefaultgames/pokerogue pull request #1921
Opened 2024-06-07 20:30 UTC by CodeTappert

…me and passive string can be ordered freely

## What are the changes?

## Why am I doing these changes?

## What did change?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-07 20:30 UTC, CodeTappert commented
Currently filling the text at the top.

2024-06-07 20:39 UTC, torranx commented on src/ui/ability-bar.ts
> +    this.abilityBarText.setText(`${i18next.t("fightUiHandler:abilityFlyInText", { pokemonName: pokemon.name, passive: passive ? i18next.t("fightUiHandler:passive") : "", abilityName: !passive ?  poke
can't we just add the space here?

2024-06-08 09:37 UTC, CodeTappert commented on src/ui/ability-bar.ts
> +    this.abilityBarText.setText(`${i18next.t("fightUiHandler:abilityFlyInText", { pokemonName: pokemon.name, passive: passive ? i18next.t("fightUiHandler:passive") : "", abilityName: !passive ?  poke
We could. But i dont see the need todo so. There are plently of localization strings that start or end with a " "

2024-06-08 13:17 UTC, returntoice requested changes

2024-06-08 13:17 UTC, returntoice commented on src/locales/ko/fight-ui-handler.ts
> +  "passive": "Passive ", // The space at the end is important
```suggestion
  "abilityFlyInText": " {{pokemonName}}의 {{passive}}{{abilityName}}",
  "passive": "패시브 ", // The space at the end is important
```
Korean translation added

2024-06-09 20:12 UTC, CodeTappert commented on src/locales/de/fight-ui-handler.ts
> +  "abilityFlyInText": "{{passive}}{{abilityName}} von {{pokemonName}} wirkt",
```suggestion
  "abilityFlyInText": "{{passive}}{{abilityName}} von {{pokemonName}} wirkt.",
```

2024-06-09 20:13 UTC, CodeTappert commented on src/locales/de/fight-ui-handler.ts
> +  "abilityFlyInText": "{{passive}}{{abilityName}} von {{pokemonName}} wirkt.",
```suggestion
  "abilityFlyInText": "{{passive}}{{abilityName}} von {{pokemonName}} wirkt!",
```

2024-06-10 20:52 UTC, flx-sta commented
<img width="318" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/4b3b2c6e-1e1f-46f1-a4cb-6e1a53352437">
<img width="401" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/64891b33-351b-4edf-a1d2-a6405a32459f">

2024-06-10 20:52 UTC, flx-sta approved these changes
### lgtm 🚀 
<img width="318" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/4b3b2c6e-1e1f-46f1-a4cb-6e1a53352437">
<img width="401" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/64891b33-351b-4edf-a1d2-a6405a32459f">

If both have it:


https://github.com/pagefaultgames/pokerogue/assets/50131232/87cd384f-ba79-4c4f-a147-8c6cdef8b70d

2024-06-11 15:50 UTC, Tempo-anon approved these changes

2024-06-11 16:03 UTC, DustinLin commented
Just another sample of traditional chinese, seems to work as intended
https://github.com/pagefaultgames/pokerogue/assets/39450497/b94b0a04-abc4-49f2-b431-9b2a5ae082ad

2024-06-11 16:05 UTC, returntoice approved these changes

2024-06-12 13:45 UTC, merged

2024-06-13 22:31 UTC, CarsonVB commented
Due to the new handling of the ability bar text, the formatting is incorrect in the legacy UI
![image](https://github.com/pagefaultgames/pokerogue/assets/59876651/9224ffcc-ed46-4ea3-a441-f62b01a08050)
Previously the Pokemon's name appeared on the top of the box, where the text currently is, then the ability name would appear inside the box, like this
![image](https://github.com/pagefaultgames/pokerogue/assets/59876651/1466589d-4869-44d6-b66c-fdeabf08c0e2)