[Ability] Implement forecast
pagefaultgames/pokerogue pull request #1924
Opened 2024-06-07 21:40 UTC by Tempo-anon

## What are the changes?
Adding Forecast

## Why am I doing these changes?
Make Castform's ability work

## What did change?
* Added all 12 of Castform's form change transformations
* Added a new `SpeciesFormChangeWeatherTrigger` class for species form changes based on weather
* Modified Arena.trySetWeather so it checks all active Pokemon if any of them have any weather based form changes

### Screenshots/Videos
![](https://cdn.discordapp.com/attachments/1176874654015684739/1248743857827483679/image.png?ex=6664c6d8&is=66637558&hm=f55e2a4e0c9212c561bd691375b0ebcdedabc4d4a6f52012320497d62a799798&)
![](https://cdn.discordapp.com/attachments/1176874654015684739/1248744132122247189/image.png?ex=6664c719&is=66637599&hm=824e1db09992413463b0a7c4a1d28d11488a738e49e51555c157ed2284009599&)

## How to test the changes?
Override a Castform with weather moves
```ts
export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.CASTFORM;
export const ABILITY_OVERRIDE: Abilities = Abilities.FORECAST;
export const PASSIVE_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const STATUS_OVERRIDE: StatusEffect = StatusEffect.NONE;
export const GENDER_OVERRIDE: Gender = null;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.SANDSTORM, Moves.SUNNY_DAY, Moves.RAIN_DANCE, Moves.HAIL];
```

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-07 21:56 UTC, flx-sta requested changes

2024-06-07 21:56 UTC, flx-sta commented on src/data/pokemon-forms.ts
> +export class SpeciesFormChangeWeatherTrigger extends SpeciesFormChangeTrigger {
Wouldn't it be `SpeciesFormWeatherChangeTrigger` ?

2024-06-07 21:56 UTC, flx-sta commented on src/data/pokemon-forms.ts
> +    return weatherSuppressedFlag || (pokemon.hasAbility(this.ability)
when `weatherSuppresedFlag = true` it would return `true` thus saying `canChange => true`, right?

2024-06-07 21:56 UTC, flx-sta commented on src/field/arena.ts
> +      if ((p.hasAbility(Abilities.FORECAST) && p.species.speciesId === Species.CASTFORM)) {
```suggestion
      if (p.hasAbility(Abilities.FORECAST) && p.species.speciesId === Species.CASTFORM) {
```

2024-06-07 21:56 UTC, flx-sta commented on src/field/arena.ts
> +    );
```suggestion
    });
```

2024-06-08 01:47 UTC, Tempo-anon commented on src/data/pokemon-forms.ts
> +export class SpeciesFormChangeWeatherTrigger extends SpeciesFormChangeTrigger {
I modeled it after `SpeciesFormChangeTimeOfDayTrigger`

2024-06-08 01:49 UTC, Tempo-anon commented on src/field/arena.ts
> +      if ((p.hasAbility(Abilities.FORECAST) && p.species.speciesId === Species.CASTFORM)) {
Yeah I have a double pair of parantheses here because eventually Cherrim needs to be added here too

2024-06-08 02:26 UTC, Tempo-anon commented on src/data/pokemon-forms.ts
> +    return weatherSuppressedFlag || (pokemon.hasAbility(this.ability)
Yes. If the weather is suppressed then it's treated as no weather so the Pokemon should trigger a form change to go back to formIndex 0 if it is in a different state

2024-06-08 12:25 UTC, torranx commented
arent you missing some interactions? https://bulbapedia.bulbagarden.net/wiki/Forecast_(Ability)

<img width="972" alt="Screenshot 2024-06-08 at 8 25 25 PM" src="https://github.com/pagefaultgames/pokerogue/assets/68144167/6fe599f3-200e-40c2-b0ed-e7e001dbd845">

2024-06-08 14:28 UTC, Tempo-anon commented
> If a Pokémon [transforms](https://bulbapedia.bulbagarden.net/wiki/Transform_(move)) into Castform, the Pokémon will remain in the same form as the target Castform, regardless of the weather.

Proof Transform keeps you in the same form you transformed into. There's some undefined behavior if Castform transforms into another Castform but for now the Forecast check has a species lock on Castform.
![](https://cdn.discordapp.com/attachments/1176874654015684739/1249006532612456500/image.png?ex=6665bb7a&is=666469fa&hm=fc1a423fe0c9902248e7f95cbcbcc1fab22ba4319f75e2ade52e00991875335c&)
> If Castform loses Forecast or Forecast is suppressed with [Gastro Acid](https://bulbapedia.bulbagarden.net/wiki/Gastro_Acid_(move)), it will revert to its normal form and not be able to change form. If Castform regains Forecast, it will change form to match the current weather, unless it would be in its normal form in the current weather.

We currently don't have the framework of abilities triggering on gain/loss. Same issue with intimidate not activating when the ability is gained.

> [Role Play](https://bulbapedia.bulbagarden.net/wiki/Role_Play_(move)) fails if the target has the Ability Forecast. [Entrainment](https://bulbapedia.bulbagarden.net/wiki/Entrainment_(move)) fails if the user has the Ability Forecast. Forecast cannot be copied by [Power of Alchemy](https://bulbapedia.bulbagarden.net/wiki/Power_of_Alchemy_(Ability)) or [Receiver](https://bulbapedia.bulbagarden.net/wiki/Receiver_(Ability)), nor can it be traded by [Wandering Spirit](https://bulbapedia.bulbagarden.net/wiki/Wandering_Spirit_(Ability)).

Gave Forecast the `UnswappableAbilityAbAttr` (That name is.... ability ability?!?)

2024-06-09 04:34 UTC, Tempo-anon commented
Oh there's an edge case about weather suppressors coming in/out of combat, as well as the primal weathers... I think I should also refactor the check everyone for form changes based on weather into its own function I can call

2024-06-10 03:35 UTC, flx-sta commented
Figure I've tested as much as I could.Couldn't see anything odd except the already mentioned edge cases

2024-06-11 21:12 UTC, OrangeRed requested changes

2024-06-11 21:12 UTC, OrangeRed commented on src/data/ability.ts
> +}
I think this should do the same thing the other for change abilities do like schooling and zen mode in that they trigger on `PostBattleInitFormChangeAbAttr` instead of PostFaint. 
This will require you to change `PostBattleInitFormChangeAbAttr` to accept any trigger type instead of the current manual trigger

2024-06-11 21:12 UTC, OrangeRed commented on src/data/ability.ts
> +  }
Does this need to be its own class? Can't you do similar with the already existing `PostSummonFormChange` class?

2024-06-13 23:56 UTC, Tempo-anon commented on src/data/pokemon-forms.ts
> +  ],
I couldn't think of any hence this abomination. This is also seen in Ogerpon

2024-06-13 23:56 UTC, Tempo-anon commented on src/data/ability.ts
> +  }
Neat!

2024-06-14 00:05 UTC, Tempo-anon commented on src/data/pokemon-forms.ts
> +  public weathers: WeatherType[];
It's slightly different since weather suppressing abilities will always revert a Pokemon to their base form so the SpeciesFormChangeWeatherFormTrigger has different behavior when it comes to weather suppression. When a weather suppression ability is on the field SpeciesFormChangeWeatherFormTrigger will always return `false`. However, when a weather suppresor enters the field then it should always be `true` hence why I created two triggers

2024-06-14 00:06 UTC, Tempo-anon commented on src/data/ability.ts
> +}
Did you mean this on a different AbAttr? This is added onto weather suppression abilities to trigger all the weather form changers when they faint

2024-06-14 00:08 UTC, Tempo-anon commented on src/data/ability.ts
> +  }
I believe PostSummonFormChange only accounts for a single form and only works with `SpeciesFormChangeManualTrigger`s

2024-06-20 09:51 UTC, chaosgrimmon commented on src/data/pokemon-forms.ts
> +  ],
you'd have to introduce some kind of tag, basically a ANY_FORM_EXCEPT_EVO_FORM -> "evo_form_key", right? probably not worth the hassle provided the game only checks form change conditions provided a species with a form change has an existing Pokemon Object in play.

also, if you want these to not do the evolution-phase animation, you have to put a `true` at the end of them, to apply `quiet`.
```ts
 constructor(speciesId: Species, preFormKey: string, evoFormKey: string, trigger: SpeciesFormChangeTrigger, quiet: boolean = false, ...conditions: SpeciesFormChangeCondition[]) {
 ```
(see ogerpon for examples)

2024-08-08 21:01 UTC, Tempo-anon commented
Merge conflicts and edge cases... will leave this for swain who has a lot more experience with form changes like ice face and gulp missile

2024-08-08 21:01 UTC, closed without merging