[Localization] Partial Localization of Quick Claw Modifier
pagefaultgames/pokerogue pull request #1931
Opened 2024-06-08 00:28 UTC by kvngrnr

## What are the changes?
The message triggered by the Quick Claw modifier is hard coded right now. To address this, this PR starts by providing an english and german localization for the effect and uses the i18n plugin to show the correct translation to the user.
Additionally, the shop item for the quick claw got its correct german name (was just the english name before).

## Why am I doing these changes?
Having a hard coded english message might pose a problem to players with insufficient english skills as they might not understand the message. This could lead to frustration if, for example, the enemy pokemon uses their quick claw and the player does not understand why the were outsped.

## What did change?
The message text indicating that a pokemon just used its quick claw ("[PokemonName] used its Quick Claw to move faster!") was hard coded like this.
This PR starts by adding german and english localization for this text using the i18n plugin. Additionally, the german name for the quick claw item was added (was just the english name before).
**Unfortunately, I was not able to find any resources online on what this message is like in other languages in the main games, so I left out the localization for other languages for now.**

### Screenshots/Videos
Old version (german language but english message):
![image](https://github.com/pagefaultgames/pokerogue/assets/67913362/4eb76c12-54bf-413e-be86-73ee5feaf068)

New version in german:
![image](https://github.com/pagefaultgames/pokerogue/assets/67913362/6e187021-0c0e-469e-8d76-a3d99de06a3c)

New english version in english:
![image](https://github.com/pagefaultgames/pokerogue/assets/67913362/7abdda50-0859-4677-924f-95d13a7d709c)

New german name of item in shop:
![image](https://github.com/pagefaultgames/pokerogue/assets/67913362/ceee8ea1-f4c0-4d4e-8c22-3419be40f6d0)

**No I did not change the maximum held item count for the quick claw despite what the images suggest. That was just via the override file for simpler testing.**

## How to test the changes?
1. Add `{name: "QUICK_CLAW", count: 10}` to the `STARTING_HELD_ITEMS_OVERRIDE` and `"QUICK_CLAW"` to `ITEM_REWARD_OVERRIDE` in the `src/overrides.ts` file.
2. Start a new run.
3. Click an attack and check the displayed message.
4. Defeat a pokemon and check the first reward item's name.
5. Repeat in german and english.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-08 00:31 UTC, kvngrnr commented
As stated in the "what did change" section, I was not able to find any translations of the quick claw trigger message online, so I left out the localization for other languages out for now. If anyone can provide me with valid translations, I'll be happy to add them!

2024-06-08 08:34 UTC, CodeTappert commented on src/locales/de/modifier-type.ts
> +    "QUICK_CLAW": { name: "Flinkklaue", description: "Fügt eine 10% Change hinzu als erster anzugreifen. (Nach Prioritätsangriffen)" },
```suggestion
    "QUICK_CLAW": { name: "Flinkklaue", description: "Fügt eine 10% Change hinzu als Erster anzugreifen. (Nach Prioritätsangriffen)" },
```

2024-06-08 08:37 UTC, CodeTappert commented
Also you should add the english text to all langauges. So it can later be translated easily

2024-06-08 08:50 UTC, kvngrnr commented on src/locales/de/modifier-type.ts
> +    "QUICK_CLAW": { name: "Flinkklaue", description: "Fügt eine 10% Change hinzu als erster anzugreifen. (Nach Prioritätsangriffen)" },
Good find, done

2024-06-08 08:51 UTC, kvngrnr commented
@CodeTappert done, thanks for the input

2024-06-17 15:41 UTC, ddullgi requested changes

2024-06-17 15:41 UTC, ddullgi commented on src/locales/ko/battle.ts
> +  "useQuickClaw": "{{pokemonName}} used its Quick Claw to move faster!"
```suggestion
  "useQuickClaw": "{{pokemonName}}[[은]] 선제공격손톱으로\n행동이 빨라졌다!"
```

2024-07-05 01:33 UTC, EnochG1 commented
@kvngrnr 
Could you merge branch 'main' into your branch?
I want to continue this PR.
Or if it's difficult for you to continue this PR on your own, I would mirror yours and continue.

2024-07-05 07:16 UTC, kvngrnr commented
@ EnochG1
Done. I actually forgot this PR even existed ^^

2024-07-05 07:20 UTC, EnochG1 commented
@kvngrnr
Thanks a lot!
I would share this PR to Translation team.
Also, if other language's translation are suggested, you can apply it just clicking this button.
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/6728551f-6a18-483e-bb12-14594c076049)

2024-07-05 07:26 UTC, 40chyan reviewed
Yep we translation team will submit translated texts to you, you can also find them on
[ABCBOY pokemon corpus](https://abcboy101.github.io/poke-corpus)
![image](https://github.com/pagefaultgames/pokerogue/assets/47717431/4c3fea34-d96c-4f25-b305-02f3f997b215)

but in most cases we suggest you leave english for each language and ask us to submit. We have to check the grammar

2024-07-05 07:26 UTC, 40chyan commented on src/locales/zh_TW/battle.ts
> +  "useQuickClaw": "{{pokemonName}} used its Quick Claw to move faster!"
```suggestion
  "useQuickClaw": "{{pokemonName}}用了先製之爪後，\n行動變快了！"
```
zh_tw

2024-07-05 07:26 UTC, 40chyan commented on src/locales/zh_CN/battle.ts
> +  "useQuickClaw": "{{pokemonName}} used its Quick Claw to move faster!"
```suggestion
  "useQuickClaw": "{{pokemonName}}用了先制之爪后，行动变快了！"
```
zh_cn

2024-07-05 10:16 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "useQuickClaw": "{{pokemonName}} used its Quick Claw to move faster!"
```suggestion
  "useQuickClaw": "{{pokemonName}} usou sua Garra Rápida para atacar primeiro!"
```

2024-07-06 15:34 UTC, Arxxer reviewed
Hello! 

I'm suggesting a change for how the Quick Claw activation message is displayed to match how it actually is in all the original Pokemon games.

I did notice in Poke Corpus how in English it's displayed like [this ](https://abcboy101.github.io/poke-corpus/#query=can+act+faster+than+normal%2C+thanks+to&regex=false&caseInsensitive=true&common=true&script=true&collections=Emerald%2CDiamondPearl%2CPlatinum%2CHeartGoldSoulSilver%2CBlackWhite%2CBlack2White2%2CXY%2COmegaRubyAlphaSapphire%2CSunMoon%2CUltraSunUltraMoon%2CLetsGoPikachuLetsGoEevee%2CSwordShield%2CBrilliantDiamondShiningPearl%2CLegendsArceus%2CScarletViolet%2CColosseum%2CXD%2CBattleRevolution%2CBox%2CRanch%2CBank%2CHOME&languages=en-US%2Ces-ES%2Cen-GB) while trying to translate, and went ahead and also checked of others images in-game to check if it's actually accurate and it seems like so, so hopefully it isn't much trouble to do the change. 

Cheers!

2024-07-06 15:34 UTC, Arxxer commented on src/locales/en/battle.ts
> +  "useQuickClaw": "{{pokemonName}} used its Quick Claw to move faster!"
```suggestion
  "useQuickClaw": "{{pokemonName}} can act faster than normal, thanks to its Quick Claw!"
```

2024-07-06 15:52 UTC, kvngrnr commented on src/locales/en/battle.ts
> +  "useQuickClaw": "{{pokemonName}} used its Quick Claw to move faster!"
Looks good to me.
@EnochG1 what do you and the translation team say? I could apply these translations from [this](https://abcboy101.github.io/poke-corpus/#query=can+act+faster+than+normal%2C+thanks+to&regex=false&caseInsensitive=true&common=true&script=true&collections=Emerald%2CDiamondPearl%2CPlatinum%2CHeartGoldSoulSilver%2CBlackWhite%2CBlack2White2%2CXY%2COmegaRubyAlphaSapphire%2CSunMoon%2CUltraSunUltraMoon%2CLetsGoPikachuLetsGoEevee%2CSwordShield%2CBrilliantDiamondShiningPearl%2CLegendsArceus%2CScarletViolet%2CColosseum%2CXD%2CBattleRevolution%2CBox%2CRanch%2CBank%2CHOME&languages=en-US%2Ces-ES%2Cen-GB) link and you guys could check if its fine?

2024-07-06 16:36 UTC, EnochG1 commented on src/locales/en/battle.ts
> +  "useQuickClaw": "{{pokemonName}} used its Quick Claw to move faster!"
I agree with Arxxer's opinion. It's not MUST but if original game has messages, it's RECOMMENDED that you try to modify them as closely as possible.

2024-07-06 18:34 UTC, kvngrnr commented
Alright @EnochG1, I updated the translations again. Please have the translation team carefully check all texts, I really just copied all from poke corpus. I can only validate english and german myself.

And thanks @Arxxer for your recommendation!

2024-07-06 18:48 UTC, CodeTappert commented
German text is fine

2024-07-07 00:55 UTC, EnochG1 commented
@kvngrnr
Can you revert change of Korean?
Korean has special postposition logic(which is [[는]]) but you removed it and line break.
Before your modification(ddullgi) was right.

2024-07-07 07:32 UTC, EnochG1 approved these changes

2024-07-08 14:27 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "useQuickClaw": "{{pokemonName}} usou sua {{quickClaw}} para atacar primeiro!"
```suggestion
  "useQuickClaw": "{{pokemonName}} se move mais rápido que o normal graças a sua {{quickClaw}}!"
```

2024-07-08 17:14 UTC, kvngrnr commented
Pipeline failed for no reason. Is there a way to re-trigger the checks without a new commit?

2024-07-08 23:09 UTC, EnochG1 commented
@kvngrnr 
You should ask to dev admin if you want to do without a new commit.

2024-07-08 23:10 UTC, EnochG1 reviewed
But I think we can fix it with this commit. ('main' is changed so getPokemonMessage don't need anymore)

2024-07-08 23:10 UTC, EnochG1 commented on src/modifier/modifier.ts
> +import { getPokemonMessage, getPokemonNameWithAffix } from "../messages";
```suggestion
import { getPokemonNameWithAffix } from "../messages";
```

2024-07-09 14:02 UTC, NicusPulcis commented
@kvngrnr hey man i've fixed the italian translation in my recent PR on this project of yours (it was saying "quick claw moved faster thanks to pokemon name" lol)

2024-07-09 20:29 UTC, kvngrnr commented
@NicusPulcis fixed, thank you

2024-07-10 08:17 UTC, NicusPulcis commented
@kvngrnr aaalright

2024-07-28 13:15 UTC, EnochG1 commented
@kvngrnr
Could you merge branch 'beta' into your branch to resolve conflict?

2024-07-29 02:41 UTC, EnochG1 commented
@kvngrnr,
beta branch was reset after main release so old PRs needed to be reset.
Can you delete your local branch and get it from scratch?
If it's hard to do, I would mirror your task. Feel free and choose whichever you're more comfortable with.

2024-07-29 23:30 UTC, Tempo-anon commented
Closing this PR for now due to all the merge conflicts. Please either fix those or make a new PR with the changes.

2024-07-29 23:30 UTC, closed without merging