Added german localization for challenges
pagefaultgames/pokerogue pull request #1943
Opened 2024-06-08 08:05 UTC by CodeTappert

## What are the changes?

German Localization for the challenges

## Why am I doing these changes?

Because they werent localized

## What did change?

I translated all the keys into german

### Screenshots/Videos

![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/f38d0b2b-9569-4744-bd43-4705b26144b2)
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/a118b041-a3d4-45a9-9903-9629578f44f4)

## How to test the changes?

Set your game to german and startup a new challenge

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-08 15:01 UTC, flx-sta requested changes

2024-06-08 15:01 UTC, flx-sta commented on src/locales/de/challenges.ts
> +  "confirm_start": "Mit diesen Einschränkungen fortfahren?",
Wieso “Einschränkungen” und nicht “Modifikationen”? Steht ja auch so im Titel

2024-06-08 15:02 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +  "title": "Herausforderungsmodifikatoren",
Xavion said it was not needed

2024-06-08 15:03 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +  "confirm_start": "Mit diesen Einschränkungen fortfahren?",
Make a suggestion for that change please

2024-06-08 15:27 UTC, flx-sta commented on src/locales/de/challenges.ts
> +  "confirm_start": "Mit diesen Einschränkungen fortfahren?",
```suggestion
  "confirm_start": "Mit diesen Modifikatoren fortfahren?",
```

2024-06-08 15:29 UTC, flx-sta commented
So this is not part of THIS PR but I have a question to the person originally developing it:

why is there a translation for every single type necessary ? We could have just used a placeholder like:
```ts
You can only pick Pokemon of type {{type}}
```

a single translation would have covered them all then

2024-06-08 15:43 UTC, flx-sta commented on src/locales/de/challenges.ts
> +  "title": "Herausforderungsmodifikatoren",
Might wanna delete the English one too then ?

2024-06-09 04:22 UTC, FredeX approved these changes
Lgtm

2024-06-09 05:32 UTC, flx-sta approved these changes

2024-06-09 20:09 UTC, Tempo-anon approved these changes

2024-06-09 20:11 UTC, merged