[QoL] Starter UI selection update to allow removing specific pokemon from party
pagefaultgames/pokerogue pull request #1983
Opened 2024-06-09 04:13 UTC by Opaque02

## What are the changes?
Currently when you go to add a pokemon to your party, tapping the pokemon again gives you the option to "Add to party", even if it doesn't do anything. This PR changes that behaviour so if a pokemon is in your party, you now have the option to remove in instead of adding it. 

## Why am I doing these changes?
I got sick of going to start a run and choosing 5 pokemon only to decide my first pokemon is no good and having to remove all the pokemon until that point and then readd them all. This will fix that by letting you remove the pokemon you want no matter where they are. 

## What did change?
The starter selection ui now does a check when a pokemon is selected. If the pokemon is already in your party, the first option on the selection menu is changes the "Add to Party" text to "Remove from Party". If users choose that, it will remove the pokemon from the party at that slot and update all other arrays, including the starter icons and cursors. 

### Screenshots/Videos
This is a screenshot of the starter menu before the change, even if a pokemon was already in your party:

![Screenshot_20240609_123233_Gallery](https://github.com/pagefaultgames/pokerogue/assets/66582645/552c3215-f0a6-44b6-9f5b-d2fe691c6e32)

This is a screenshot of the menu option after the change for a pokemon that's already in your party - a pokemon not in your party still has the "Add to Party" option:

![Screenshot_20240609_123148_Gallery](https://github.com/pagefaultgames/pokerogue/assets/66582645/b29c676d-097c-48c4-ab49-3e37bb64925c)

Here is a video of the behaviour on the live version of the game:

https://github.com/pagefaultgames/pokerogue/assets/66582645/659ffb57-f49e-4a05-84f0-c7ef04dcdf3c

Here is a video of the behaviour after the change:

https://github.com/pagefaultgames/pokerogue/assets/66582645/3facd1fb-9c0b-4f2d-a8a2-7971da6934ec

As you can see, you can now remove pokemon from your party. I also realised I don't have a video of this working with different generations - I'll get a video later tonight and edit this to include it. 

## How to test the changes?
Download the branch and go to start a new game. Add pokemon to your party and then go to remove it using the action button (A/space etc) 

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-09 23:29 UTC, travbp commented
This would help a lot! A next evolution of this could be to make the Pokémon selectable from the party preview screen and have the pop up when they're selected there. Then, you wouldn't have to go hunt down the starter on its Gen page just to remove it or change around its moves.

2024-06-10 01:02 UTC, Opaque02 commented
@travbp - that's what someone in the discord mentioned as well! I've already been working on it and have got the code like 90% of the way. There's one small bug I need to fix with icons, and some logic I need to implement, and if all goes well with testing, that'll be done too :)!

2024-06-10 06:42 UTC, travbp commented
Sounds awesome!! Thanks for implementing it

2024-06-24 23:28 UTC, brain-frog requested changes
Love these changes, I think they'll be a really nice QoL addition to the starter select

A few comments: 
If there's code that's not necessary anymore after your changes, please do not leave it commented out in the code. 
Any functions you make a significant change to please add/update the function definition comments
and with the large chaining if statements please add more comments to help with readability

2024-06-24 23:28 UTC, brain-frog commented on src/ui/starter-select-ui-handler.ts
> +          let isDupe = false;
seeing how this is being used can this be renamed to something like `isInParty`

2024-06-24 23:28 UTC, brain-frog commented on src/ui/starter-select-ui-handler.ts
> +              }];
please extrapolate this as a function that can be passed to `handler:` for readability

2024-06-24 23:28 UTC, brain-frog commented on src/ui/starter-select-ui-handler.ts
> +    this.starterIconsCursorObj.setVisible(false);
```suggestion
    this.starterIconsCursorObj.setName("starter-icons-cursor");
    this.starterIconsCursorObj.setVisible(false);
```

2024-06-25 04:17 UTC, Opaque02 commented on src/ui/starter-select-ui-handler.ts
> +          let isDupe = false;
This is fixed - there's now a function for isInParty that returns a [boolean, number] for isDupe and removeIndex

2024-06-25 04:18 UTC, Opaque02 commented on src/ui/starter-select-ui-handler.ts
> +              }];
I've move a lot of this code out (and removed the old comments, sorry!)

There's still technically a few more things I could move out (like the if statement), but if it's not enough let me know and I can add more into the function

2024-06-25 04:19 UTC, Opaque02 commented on src/ui/starter-select-ui-handler.ts
> +    this.starterIconsCursorObj.setVisible(false);
This is fixed as per latest commit

2024-06-25 04:28 UTC, Opaque02 commented
@brain-frog - thanks for the code review and suggestions; I've gone through and removed all the old comments and added more in for nested if statements so hopefully it's easier to read, but I can add more in if not.

We've currently hit a bit of a block on this one - we were talking about it in discord not too long ago, but with monotype challenges, you can select pokemon that evolve into the type even if they aren't the type straight away. For example, if you're doing a flying monotype challenge, you can choose pidgey first which will then let you choose pokemon that evolve into a flying pokemon, like caterpie, however you can't choose caterpie until you choose pidgey. When you go to remove them, currently you remove from the back, meaning for our pidgey-caterpie starter party, we remove caterpie and are left with pidgey, which means we can add other pokemon that evolve into flying types

However with my changes, since we can now remove pokemon from any slot, there's a chance that for pidgey-caterpie, you could remove the pidgey first and then start the challenge with no current flying type pokemon. This makes the game crash since when you get to wave 1, you don't have any valid pokemon to send out. We were discussing on discord this morning ways around it and what we should do - whether we have some kind of message saying that the party is invalid, or have some other kind of thing going with it, and whether that'd be part of this PR or a new one. Until this is sorted though, I don't know if we can get this merged yet unfortunately

2024-06-27 16:40 UTC, Opaque02 commented
OK, that took way longer than I was expecting but all bugs are, I think, fixed now (as per my testing, hopefully). Had some weird edge cases, I think I got them all?

2024-07-18 14:09 UTC, brain-frog commented on src/ui/starter-select-ui-handler.ts
> +      //lastSpeciesIcon.setTexture(this.lastSpecies.getIconAtlasKey(props.formIndex, props.shiny, props.variant), this.lastSpecies.getIconId(props.female, props.formIndex, props.shiny, props.variant)
if this line is no longer needed please delete

2024-07-18 14:29 UTC, Opaque02 commented on src/ui/starter-select-ui-handler.ts
> +      //lastSpeciesIcon.setTexture(this.lastSpecies.getIconAtlasKey(props.formIndex, props.shiny, props.variant), this.lastSpecies.getIconId(props.female, props.formIndex, props.shiny, props.variant)
Done - thanks for the review :)

2024-07-18 14:30 UTC, brain-frog approved these changes

2024-07-22 22:32 UTC, merged