Implemented Toxic Debris
pagefaultgames/pokerogue pull request #199
Opened 2024-04-19 19:50 UTC by Procyonae

Checked it works when the defender faints and when the defender is hit by a multi hit move.
Checked it works for both player and opponent.
First PR and first time touching JS/TS so I may well have done something dumb.

2024-04-19 19:52 UTC, Flashfyre requested changes

2024-04-19 19:52 UTC, Flashfyre commented on src/data/ability.ts
> +export class PostDefendApplyArenaTragTagAbAttr extends PostDefendAbAttr {
```suggestion
export class PostDefendApplyArenaTrapTagAbAttr extends PostDefendAbAttr {
```

2024-04-19 19:58 UTC, Procyonae commented on src/data/ability.ts
> +export class PostDefendApplyArenaTragTagAbAttr extends PostDefendAbAttr {
Well that's embarrassing ;D

2024-04-22 02:58 UTC, Flashfyre approved these changes

2024-04-22 03:00 UTC, merged