[Localization] Add localization in battler-tags
pagefaultgames/pokerogue pull request #1990
Opened 2024-06-09 08:32 UTC by EnochG1

## What are the changes?
Add the option to localize message text in battler-tags.ts.

## Why am I doing these changes?
All text should be localizable and I thought battler-tags message need to translate.

## What did change?
- Change the code for localize >> messages of battler-tags.ts to add the option to localize.

```typescript
   // in battler-tags.ts
(-)    pokemon.scene.queueMessage(getPokemonMessage(pokemon, " must\nrecharge!"));
(+)    pokemon.scene.queueMessage(i18next.t("battle:battlerTagsRechargingLapse", { pokemonNameWithAffix: getPokemonNameWithAffix(pokemon) }));
```
- Added localization key in each language folders.
- Translated part of them to Korean.
- localized move.ts > Curse(ghost) apply message.

### Screenshots/Videos
English
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/c2c8a87c-0a47-4dac-a72d-e375d5c18bc3)

Korean
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/0f5c6563-95b3-4089-9d75-c96a45b333c4)

## How to test the changes?
1. Checkout this PR and change language (Korean <-> English)
2. You will show the message when pokemon faces specific tags in battle phase.
ref) https://docs.google.com/spreadsheets/d/1_nwKvSr89ONHp2VlTGXImJRiNPRTrRv86vhhgR53OXE/edit?usp=sharing

## Checklist
- [ ] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-10 18:01 UTC, returntoice approved these changes
Still some parts untranslated, but worth updating.

2024-06-11 01:35 UTC, sodaMelon approved these changes
hi. it's good to localize. 
I leave some coments about skill effect. 

~~From Line 109 to 112, I don't know them where to use....🤔🤔🤔🤔🤔~~
109 to 110 These Lines are for Regigigas.
But 111 to 112, I can't remember them

2024-06-11 01:35 UTC, sodaMelon commented on src/locales/ko/battle.ts
> +  "battlerTagsAquaRingLapse": "{{moveName}} restored\n{{pokemonName}}'s HP!",
```suggestion
  "battlerTagsAquaRingLapse": "{{moveName}} 효과로 \n{{pokemonName}}[[는]] HP를 회복했다!",
  ```

먹다남은 밥 효과 생각하시면 됩니다. 1/16일 회복해요

2024-06-11 02:40 UTC, sodaMelon requested changes

2024-06-11 02:40 UTC, sodaMelon commented on src/locales/ko/battle.ts
> +  "battlerTagsSlowStartOnAdd": "{{pokemonNameWithAffix}} can't\nget it going!",
```suggestion
  "battlerTagsSlowStartOnAdd": "{{pokemonNameWithAffix}}[[는]] 컨디션이\n좋아지지 않는다!",
```
기계 포켓몬으로 보이는 레지기가스(Regigigas)의 슬로스타트특성입니다. (효과:(배틀에 나간 5턴동안 공격과 스피드가 절반이 된다.)
9세대에 부르롱(Varoom)에게도  추가됐어요.

2024-06-11 02:40 UTC, sodaMelon commented on src/locales/ko/battle.ts
> +  "battlerTagsSlowStartOnRemove": "{{pokemonNameWithAffix}} finally\ngot its act together!",
```suggestion
  "battlerTagsSlowStartOnRemove": "{{pokemonNameWithAffix}} 는 마침내\n컨디션을 회복했다!",
```

2024-06-11 02:40 UTC, sodaMelon commented on src/locales/ko/battle.ts
> +  "battlerTagsCritBoostOnRemove": "{{pokemonNameWithAffix}} relaxed.",
```suggestion
  "battlerTagsCritBoostOnRemove": "{{pokemonNameWithAffix}}[[는]] 평소로 돌아왔다.",
```
의욕 넘침 기술의 효과가 끝났을때 나오는 말입니다

2024-06-11 02:45 UTC, sodaMelon commented on src/locales/ko/battle.ts
> +  "battlerTagsHighestStatBoostOnAdd": "{{pokemonNameWithAffix}}'s {{statName}}\nwas heightened!",
비스트 부스트 효과인데 한국어판 정발 스크립트를 좀 찾아볼게요

2024-06-11 02:50 UTC, sodaMelon requested changes
효과 스크립트, 나머지도 확인부탁드립니다.

2024-06-11 03:45 UTC, sodaMelon commented on src/locales/ko/battle.ts
> +  "battlerTagsHighestStatBoostOnAdd": "{{pokemonNameWithAffix}}'s {{statName}}\nwas heightened!",
```suggestion
  "battlerTagsHighestStatBoostOnAdd": "{{pokemonNameWithAffix}}의\n{{statName}}[[가]] 올라갔다!",
```

2024-06-11 03:48 UTC, sodaMelon commented on src/locales/ko/battle.ts
> +  "battlerTagsHighestStatBoostOnRemove": "The effects of {{pokemonNameWithAffix}}'s\n{{abilityName}} wore off!",
```suggestion
  "battlerTagsHighestStatBoostOnRemove": "{{pokemonNameWithAffix}}의\n{{abilityName}}[[가]] 원래대로 돌아왔다.",
```

2024-06-11 04:03 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsDestinyBondLapseIsBoss": "{{pokemonNameWithAffix}} is unaffected\nby the effects of Destiny Bond.",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:03 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsInfatuatedOnOverlap": "{{pokemonNameWithAffix}} is\nalready in love!",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:03 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsInfatuatedOnRemove": "{{pokemonNameWithAffix}} got over\nits infatuation.",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:03 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsNightmareOnOverlap": "{{pokemonNameWithAffix}} is\nalready locked in a Nightmare!",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:03 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsAquaRingOnAdd": "{{pokemonNameWithAffix}} surrounded\nitself with a veil of water!",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:03 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsAquaRingLapse": "{{moveName}} restored\n{{pokemonName}}'s HP!",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:03 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsSlowStartOnAdd": "{{pokemonNameWithAffix}} can't\nget it going!",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:03 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsSlowStartOnRemove": "{{pokemonNameWithAffix}} finally\ngot its act together!",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:03 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsCritBoostOnRemove": "{{pokemonNameWithAffix}} relaxed.",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:05 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsHighestStatBoostOnAdd": "{{pokemonNameWithAffix}}'s {{statName}}\nwas heightened!",
OnAdd는 코멘트 주신 내용 + 소드/실드에서 확인했는데요,
비스트부스트 스탯 증가가 일정 턴 한정 효과가 아닌 것으로 확인되어
OnRemove 이벤트 발동 여부 자체 확인이 필요해 보입니다.

2024-06-11 04:06 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsHighestStatBoostOnAdd": "{{pokemonNameWithAffix}}'s {{statName}}\nwas heightened!",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:06 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsHighestStatBoostOnRemove": "The effects of {{pokemonNameWithAffix}}'s\n{{abilityName}} wore off!",
applied in commit 8578de187bafae8b1b1edc2b126f548f7e1a8dea

2024-06-11 04:18 UTC, sodaMelon commented on src/locales/ko/battle.ts
> +  "battlerTagsHighestStatBoostOnAdd": "{{pokemonNameWithAffix}}'s {{statName}}\nwas heightened!",
한 턴이 아니고 이거 그 상대 상태 무효화하는 기술이 있었던거같은데......  잠깐 생각해볼게요

2024-06-11 04:59 UTC, EnochG1 commented
I skipped translation of **battlerTagsHighestStatBoostOnRemove** as discussed at Discord korean channel.
Since 'beastBoost' is not implemented so I couldn't check OnRemove is possible event.

비스트부스트가 아직 구현되지 않아
본가에서는 존재하지 않는 '비스트부스트' 효과 종료 이벤트 발생 여부가 불확실한 관계로
battlerTagsHighestStatBoostOnRemove 에 대한 번역은 스킵했습니다.

@sodaMelon 님, conflict는 해결해두었으니
수정 건 확인하시면 재 approve 부탁드립니다. 도움주셔서 감사합니다. :)

2024-06-11 05:06 UTC, sodaMelon approved these changes
LGTM! i cant grep Switch now. Thanks for check.
now it's time to merge! 

(and then.... I see. We will talk about Ultra Beast's Effect later on Disccord again. )

2024-06-12 05:09 UTC, returntoice approved these changes

2024-06-12 06:46 UTC, EnochG1 commented
@Tempo-anon
Hi, I have some questions about workflows. (It's my first PR and sorry to bother you.)
After I merge main branch to resolve conflict,
status of workflows are changed from passed to awaiting (and It seems new workflow added)
I requested reviewers to review code after merge and receive approval but 4 workflows still awaiting approval.
Is there anything else I have to do? Or do I have to wait for approval from other reviewers?

2024-06-12 13:54 UTC, sodaMelon commented on src/locales/ko/battle.ts
> +  "battlerTagsInfatuatedOnRemove": "{{pokemonNameWithAffix}}[[는]]\n헤롱헤롱한 상태에서 벗어났다.",
```suggestion
  "battlerTagsInfatuatedOnRemove": "{{pokemonNameWithAffix}}[[는]]\n헤롱헤롱 상태에서 벗어났다.",
```

의미상은 같으니까 제안 하나 드려봅니다.

2024-06-12 13:57 UTC, sodaMelon approved these changes
thanks. i think this PR has a problem

2024-06-12 14:20 UTC, Tempo-anon commented on src/locales/es/battle.ts
> -  "fainted": "¡El {{pokemonNameWithAffix}} se debilitó!"Name}}!",
Is the fainted supposed to be removed?

2024-06-12 14:27 UTC, EnochG1 commented on src/locales/es/battle.ts
> -  "fainted": "¡El {{pokemonNameWithAffix}} se debilitó!"Name}}!",
It was an merge error. "fainted" is at 64 line. My fault.

2024-06-12 14:44 UTC, sodaMelon commented on src/locales/es/battle.ts
> +  "fainted": "¡El {{pokemonNameWithAffix}} se debilitó!",
@EnochG1 it already exist here, right?

2024-06-12 14:48 UTC, EnochG1 commented on src/locales/es/battle.ts
> +  "fainted": "¡El {{pokemonNameWithAffix}} se debilitó!",
You're right. Thanks :)

2024-06-16 12:37 UTC, EnochG1 commented
@Tempo-anon
Hi, Can I get some help to run workflows again?
I head another conflicts with main branch so I resolved conflict again.

2024-06-16 13:06 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} is afflicted by the Curse!"
```suggestion
  "battlerTagsRechargingLapse": "{{pokemonNameWithAffix}} kann sich wegen des Rückstoßes durch den Angriff nicht bewegen!",
  "battlerTagsTrappedOnAdd": "{{pokemonNameWithAffix}} kann nicht mehr fliehen!",
  "battlerTagsTrappedOnRemove": "{{pokemonNameWithAffix}} wurde von {{moveName}} befreit.",
  "battlerTagsFlinchedLapse": "{{pokemonNameWithAffix}} ist zurückgeschreckt und kann nicht handeln!",
  "battlerTagsConfusedOnAdd": "{{pokemonNameWithAffix}} wurde verwirrt!",
  "battlerTagsConfusedOnRemove": "{{pokemonNameWithAffix}} ist nicht mehr verwirrt!",
  "battlerTagsConfusedOnOverlap": "{{pokemonNameWithAffix}} ist bereits verwirrt!",
  "battlerTagsConfusedLapse": "{{pokemonNameWithAffix}} ist verwirrt!",
  "battlerTagsConfusedLapseHurtItself": "Es hat sich vor Verwirrung selbst verletzt!",
  "battlerTagsDestinyBondLapseIsBoss": "{{pokemonNameWithAffix}} ist immun gegen den Effekt von Abgangsbund!",
  "battlerTagsDestinyBondLapse": "{{pokemonNameWithAffix}} nimmt {{pokemonNameWithAffix2}} mit sich!",
  "battlerTagsInfatuatedOnAdd": "{{pokemonNameWithAffix}} hat sich in {{sourcePokemonName}} verliebt!",
  "battlerTagsInfatuatedOnOverlap": "{{pokemonNameWithAffix}} ist bereits verliebt.",
  "battlerTagsInfatuatedLapse": "{{pokemonNameWithAffix}} ist in {{sourcePokemonName}} verliebt!",
  "battlerTagsInfatuatedLapseImmobilize": "{{pokemonNameWithAffix}} ist starr vor Liebe!",
  "battlerTagsInfatuatedOnRemove": "{{pokemonNameWithAffix}} ist nicht mehr verliebt!",
  "battlerTagsSeededOnAdd": "{{pokemonNameWithAffix}} wurde bepflanzt!",
  "battlerTagsSeededLapse": "{{pokemonNameWithAffix}} wurden durch Egelsamen KP geraubt!",
  "battlerTagsSeededLapseShed": "Egelsamen von {{pokemonNameWithAffix}} saugt Kloakensoße auf!",
  "battlerTagsNightmareOnAdd": "Nachtmahr sucht {{pokemonNameWithAffix}} heim!",
  "battlerTagsNightmareOnOverlap": "{{pokemonNameWithAffix}} wird bereits von Nachtmahr heimgesucht!",
  "battlerTagsNightmareLapse": "Nachtmahr schadet {{pokemonNameWithAffix}}!",
  "battlerTagsEncoreOnAdd": "({{pokemonNameWithAffix}} gibt eine Zugabe",
  "battlerTagsEncoreOnRemove": "Die Zugabe von {{pokemonNameWithAffix}} ist beendet!",
  "battlerTagsHelpingHandOnAdd": "{{pokemonNameWithAffix}} will {{pokemonName}} helfen!",
  "battlerTagsIngrainLapse": "{{pokemonNameWithAffix}} nimmt über seine Wurzeln Nährstoffe auf!",
  "battlerTagsIngrainOnTrap": "{{pokemonNameWithAffix}} pflanzt seine Wurzeln!",
  "battlerTagsAquaRingOnAdd": "{{pokemonNameWithAffix}} umgibt sich mit einem Wasserring!",
  "battlerTagsAquaRingLapse": "{{moveName}} füllt KP von {{pokemonName}} wieder auf!",
  "battlerTagsDrowsyOnAdd": "{{pokemonNameWithAffix}} wurde schläfrig gemacht!",
  "battlerTagsDamagingTrapLapse": "{{pokemonNameWithAffix}} wurde durch {{moveName}} verletzt!",
  "battlerTagsBindOnTrap": "{{pokemonNameWithAffix}} wurde durch {{moveName}} von {{sourcePokemonName}} gequetscht!",
  "battlerTagsWrapOnTrap": "{{pokemonNameWithAffix}} wurde von {{sourcePokemonName}} umwickelt!",
  "battlerTagsVortexOnTrap": "{{pokemonNameWithAffix}} wird in dem Strudel gefangen!",
  "battlerTagsClampOnTrap": "{{sourcePokemonNameWithAffix}} wurde von {{pokemonName}} geschnappt!",
  "battlerTagsSandTombOnTrap": "{{pokemonNameWithAffix}} wurde von {{moveName}} gefangen!",
  "battlerTagsMagmaStormOnTrap": "{{pokemonNameWithAffix}} wurde in wirbelndem Magma eingeschlossen!",
  "battlerTagsSnapTrapOnTrap": "{{pokemonNameWithAffix}} wurde durch Sandgrab gefangen!",
  "battlerTagsThunderCageOnTrap": "{{sourcePokemonNameWithAffix}} hat {{pokemonNameWithAffix}} gefangen!",
  "battlerTagsInfestationOnTrap": "{{sourcePokemonNameWithAffix}} plagt {{pokemonNameWithAffix}}!",
  "battlerTagsProtectedOnAdd": "{{pokemonNameWithAffix}} schützt sich selbst!",
  "battlerTagsProtectedLapse": "{{pokemonNameWithAffix}} schützt sich selbst!",
  "battlerTagsEnduringOnAdd": "{{pokemonNameWithAffix}} sammelt sich, um die nächste Attacke zu überstehen!",
  "battlerTagsEnduringLapse": "{{pokemonNameWithAffix}} übersteht die Attacke!",
  "battlerTagsSturdyLapse": "{{pokemonNameWithAffix}} übersteht die Attacke!",
  "battlerTagsPerishSongLapse": "Abgesang von {{pokemonNameWithAffix}} steht bei {{turnCount}}.",
  "battlerTagsTruantLapse": "{{pokemonNameWithAffix}} faulenzt!",
  "battlerTagsSlowStartOnAdd": "{{pokemonNameWithAffix}} kommt nicht in Fahrt!",
  "battlerTagsSlowStartOnRemove": "{{pokemonNameWithAffix}} kriegt schließlich doch noch die Kurve!",
  "battlerTagsHighestStatBoostOnAdd": "{{statName}} von {{pokemonNameWithAffix}} {{statName}} wird verstärkt!",
  "battlerTagsHighestStatBoostOnRemove": "Der Effekt von {{abilityName}} von {{pokemonNameWithAffix}} lässt nach!",
  "battlerTagsCritBoostOnAdd": "{{pokemonNameWithAffix}} läuft zu Hochtouren auf!",
  "battlerTagsCritBoostOnRemove": "{{pokemonNameWithAffix}} entspannt.",
  "battlerTagsSaltCuredOnAdd": "{{pokemonNameWithAffix}} wurde eingepökelt!",
  "battlerTagsSaltCuredLapse": "{{pokemonNameWithAffix}} wurde durch {{moveName}} verletzt!",
  "battlerTagsCursedOnAdd": "{{pokemonNameWithAffix}} nimmt einen Teil seiner KP und legt einen Fluch auf {{pokemonName}}!",
  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} wurde durch den Fluch verletzt!"
```

2024-06-16 13:07 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} is afflicted by the Curse!"
Source (where applicable) Pokemon Scarlet. The Rest is translated by myself. I removed the \n on purpose. So the text will break when needed

2024-06-16 13:09 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} is afflicted by the Curse!"
Also please test out hyper beam with this german. I fear the text might be to long (its from the original games)

2024-06-16 13:31 UTC, EnochG1 commented on src/locales/de/battle.ts
> +  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} is afflicted by the Curse!"
Could you make suggestion again?
Because it's outdated by https://github.com/pagefaultgames/pokerogue/pull/1990/commits/acd9aae7eddf13dda9b0ac5e10b55c45da441e7c

Also, I suggest you to add ```\n``` if there's break line in original game.
For example, if original game shows like below,
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/6b3ac77d-3626-47b9-9fbd-5d4d2e942340)
recommanded text is
```{{pokemonNameWithAffix}} setzt\n{{moveName}} ein!```

2024-06-16 13:33 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} is afflicted by the Curse!"
the amount of text that can fit on a line is different in pokerouge and in the orignal games. So i rather use the full width to not be in danger to having the second line be too long

2024-06-16 13:34 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} is afflicted by the Curse!"
```suggestion
  "battlerTagsRechargingLapse": "{{pokemonNameWithAffix}} kann sich wegen des Rückstoßes durch den Angriff nicht bewegen!",
  "battlerTagsTrappedOnAdd": "{{pokemonNameWithAffix}} kann nicht mehr fliehen!",
  "battlerTagsTrappedOnRemove": "{{pokemonNameWithAffix}} wurde von {{moveName}} befreit.",
  "battlerTagsFlinchedLapse": "{{pokemonNameWithAffix}} ist zurückgeschreckt und kann nicht handeln!",
  "battlerTagsConfusedOnAdd": "{{pokemonNameWithAffix}} wurde verwirrt!",
  "battlerTagsConfusedOnRemove": "{{pokemonNameWithAffix}} ist nicht mehr verwirrt!",
  "battlerTagsConfusedOnOverlap": "{{pokemonNameWithAffix}} ist bereits verwirrt!",
  "battlerTagsConfusedLapse": "{{pokemonNameWithAffix}} ist verwirrt!",
  "battlerTagsConfusedLapseHurtItself": "Es hat sich vor Verwirrung selbst verletzt!",
  "battlerTagsDestinyBondLapseIsBoss": "{{pokemonNameWithAffix}} ist immun gegen den Effekt von Abgangsbund!",
  "battlerTagsDestinyBondLapse": "{{pokemonNameWithAffix}} nimmt {{pokemonNameWithAffix2}} mit sich!",
  "battlerTagsInfatuatedOnAdd": "{{pokemonNameWithAffix}} hat sich in {{sourcePokemonName}} verliebt!",
  "battlerTagsInfatuatedOnOverlap": "{{pokemonNameWithAffix}} ist bereits verliebt.",
  "battlerTagsInfatuatedLapse": "{{pokemonNameWithAffix}} ist in {{sourcePokemonName}} verliebt!",
  "battlerTagsInfatuatedLapseImmobilize": "{{pokemonNameWithAffix}} ist starr vor Liebe!",
  "battlerTagsInfatuatedOnRemove": "{{pokemonNameWithAffix}} ist nicht mehr verliebt!",
  "battlerTagsSeededOnAdd": "{{pokemonNameWithAffix}} wurde bepflanzt!",
  "battlerTagsSeededLapse": "{{pokemonNameWithAffix}} wurden durch Egelsamen KP geraubt!",
  "battlerTagsSeededLapseShed": "Egelsamen von {{pokemonNameWithAffix}} saugt Kloakensoße auf!",
  "battlerTagsNightmareOnAdd": "Nachtmahr sucht {{pokemonNameWithAffix}} heim!",
  "battlerTagsNightmareOnOverlap": "{{pokemonNameWithAffix}} wird bereits von Nachtmahr heimgesucht!",
  "battlerTagsNightmareLapse": "Nachtmahr schadet {{pokemonNameWithAffix}}!",
  "battlerTagsEncoreOnAdd": "({{pokemonNameWithAffix}} gibt eine Zugabe",
  "battlerTagsEncoreOnRemove": "Die Zugabe von {{pokemonNameWithAffix}} ist beendet!",
  "battlerTagsHelpingHandOnAdd": "{{pokemonNameWithAffix}} will {{pokemonName}} helfen!",
  "battlerTagsIngrainLapse": "{{pokemonNameWithAffix}} nimmt über seine Wurzeln Nährstoffe auf!",
  "battlerTagsIngrainOnTrap": "{{pokemonNameWithAffix}} pflanzt seine Wurzeln!",
  "battlerTagsAquaRingOnAdd": "{{pokemonNameWithAffix}} umgibt sich mit einem Wasserring!",
  "battlerTagsAquaRingLapse": "{{moveName}} füllt KP von {{pokemonName}} wieder auf!",
  "battlerTagsDrowsyOnAdd": "{{pokemonNameWithAffix}} wurde schläfrig gemacht!",
  "battlerTagsDamagingTrapLapse": "{{pokemonNameWithAffix}} wurde durch {{moveName}} verletzt!",
  "battlerTagsBindOnTrap": "{{pokemonNameWithAffix}} wurde durch {{moveName}} von {{sourcePokemonName}} gequetscht!",
  "battlerTagsWrapOnTrap": "{{pokemonNameWithAffix}} wurde von {{sourcePokemonName}} umwickelt!",
  "battlerTagsVortexOnTrap": "{{pokemonNameWithAffix}} wird in dem Strudel gefangen!",
  "battlerTagsClampOnTrap": "{{sourcePokemonNameWithAffix}} wurde von {{pokemonName}} geschnappt!",
  "battlerTagsSandTombOnTrap": "{{pokemonNameWithAffix}} wurde von {{moveName}} gefangen!",
  "battlerTagsMagmaStormOnTrap": "{{pokemonNameWithAffix}} wurde in wirbelndem Magma eingeschlossen!",
  "battlerTagsSnapTrapOnTrap": "{{pokemonNameWithAffix}} wurde durch Sandgrab gefangen!",
  "battlerTagsThunderCageOnTrap": "{{sourcePokemonNameWithAffix}} hat {{pokemonNameWithAffix}} gefangen!",
  "battlerTagsInfestationOnTrap": "{{sourcePokemonNameWithAffix}} plagt {{pokemonNameWithAffix}}!",
  "battlerTagsProtectedOnAdd": "{{pokemonNameWithAffix}} schützt sich selbst!",
  "battlerTagsProtectedLapse": "{{pokemonNameWithAffix}} schützt sich selbst!",
  "battlerTagsEnduringOnAdd": "{{pokemonNameWithAffix}} sammelt sich, um die nächste Attacke zu überstehen!",
  "battlerTagsEnduringLapse": "{{pokemonNameWithAffix}} übersteht die Attacke!",
  "battlerTagsSturdyLapse": "{{pokemonNameWithAffix}} übersteht die Attacke!",
  "battlerTagsPerishSongLapse": "Abgesang von {{pokemonNameWithAffix}} steht bei {{turnCount}}.",
  "battlerTagsTruantLapse": "{{pokemonNameWithAffix}} faulenzt!",
  "battlerTagsSlowStartOnAdd": "{{pokemonNameWithAffix}} kommt nicht in Fahrt!",
  "battlerTagsSlowStartOnRemove": "{{pokemonNameWithAffix}} kriegt schließlich doch noch die Kurve!",
  "battlerTagsHighestStatBoostOnAdd": "{{statName}} von {{pokemonNameWithAffix}} wird verstärkt!",
  "battlerTagsHighestStatBoostOnRemove": "Der Effekt von {{abilityName}} von {{pokemonNameWithAffix}} lässt nach!",
  "battlerTagsCritBoostOnAdd": "{{pokemonNameWithAffix}} läuft zu Hochtouren auf!",
  "battlerTagsCritBoostOnRemove": "{{pokemonNameWithAffix}} entspannt.",
  "battlerTagsSaltCuredOnAdd": "{{pokemonNameWithAffix}} wurde eingepökelt!",
  "battlerTagsSaltCuredLapse": "{{pokemonNameWithAffix}} wurde durch {{moveName}} verletzt!",
  "battlerTagsCursedOnAdd": "{{pokemonNameWithAffix}} nimmt einen Teil seiner KP und legt einen Fluch auf {{pokemonName}}!",
  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} wurde durch den Fluch verletzt!"
```

2024-06-16 13:37 UTC, EnochG1 commented on src/locales/de/battle.ts
> +  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} is afflicted by the Curse!"
I understand.
I would approve your new suggestion if you can make.
(Cause I can't approve current suggestion)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/c0f4967e-a2a5-4de4-b3f2-279e02da0b8e)

2024-06-16 15:54 UTC, NicusPulcis commented
@EnochG1 i should've sent the PR for the italian translations

2024-06-17 22:44 UTC, EnochG1 commented on src/data/battler-tags.ts
> +import { getPokemonNameWithAffix } from "../messages";
```suggestion
import { getPokemonMessage, getPokemonNameWithAffix } from "../messages";
```
Someone add message which is not localized so it has to be leave. (getPokemonMessage)

2024-06-17 22:52 UTC, EnochG1 commented
@Tempo-anon 
Hi, could you review this request and check if it can be merged?
I'm resolving conflict of main several times because other reviews that came up later are merged first.
And I'm worried that I might make a mistake while merging to many times,
also I don't want to just close this request because lots of people participate for this translation 🙏 
Please let me know if there is anything I have to do that I missed.
I'm sorry to bother you when you're busy.

2024-06-18 11:36 UTC, CodeTappert approved these changes

2024-06-19 14:38 UTC, merged