Implements anticipation
pagefaultgames/pokerogue pull request #201
Opened 2024-04-19 23:30 UTC by shayebeadling

Functioning according to the explanation on showdown. The computation of hidden power type should probably live in a method somewhere but it idk how this app handles general purpose services like that, that could be used by both ability.ts and move.ts.

2024-04-20 03:43 UTC, Gammer0909 reviewed
LGTM 👍

2024-04-21 05:08 UTC, Flashfyre requested changes

2024-04-21 05:08 UTC, Flashfyre commented on src/data/ability.ts
> +          if ([Moves.FISSURE, Moves.SHEER_COLD, Moves.GUILLOTINE, Moves.HORN_DRILL].includes(move.getMove().id)) {
Get moves with OneHitKOAttr instead of hardcoding

2024-04-22 03:00 UTC, Flashfyre approved these changes

2024-04-22 03:01 UTC, merged