[Enhancement] Golden IVs Chart when all IVs are perfect
pagefaultgames/pokerogue pull request #2019
Opened 2024-06-09 20:49 UTC by prime-dialga

## What are the changes?
The IVs chart is now golden in case all IVs are perfect.

## Why am I doing these changes?
Dynamic colors for the IV chart was already part of a different mod so i thought i might as well as this effectively only requires one line of code to change.
Though the additional code for testing overrides added some more changes...

## What did change?
The IV chart shown for new captures and starters will now appear golden, in case all IVs are perfect (31).
This color change is also animated on the starter selection screen.

For testing purposes the following overrides have been introduced:
- `OPP_IVS_OVERRIDE : integer | integer[]`
    This may take an integer to replace all enemy IVs or an array with each element replacing the respective IV.
- `window.perfectIVsChartColor`
    This global variable can be set by the user and changes the default golden color for perfect IVs. This is intended temporarily to allow testers to modify the color and chose a better one than the current default setting. However, as it has no functional influence on the game itself, i'm inclined to leave this variable in the game.

### Screenshots/Videos
![golden-chart](https://github.com/pagefaultgames/pokerogue/assets/10091050/64ede9d5-f3e2-4023-8bbd-6bc6ec3c0d7e)

## How to test the changes?
During the starter selection, when toggling IVs, the altered color can appear, assuming all IVs are perfect.

Please use the following overrides for the `src/overrides.ts` file to generate any required IVs:
- replace `[PokeballType.MASTER_BALL]: 0,` with `[PokeballType.MASTER_BALL]: 1,` to get a masterball for a new run.
- replace `export const OPP_IVS_OVERRIDE: integer | integer[] = [];` with `export const OPP_IVS_OVERRIDE: integer | integer[] = 31;` to force any enemy pokemon to spawn with perfect IVs

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-10 01:40 UTC, brain-frog requested changes
I think this is a good idea but overthinking it
besides the overrides, this can be done simply by putting this at stats-container line 87:
```js
if (ivs.every((i) => i === 31)) {
  this.ivChart.fillColor = 0xe8e8a8;
} else {
  this.ivChart.fillColor = 0x98d8a0;
}
```

2024-06-10 01:40 UTC, brain-frog commented on src/ui/stats-container.ts
> +
this is unnecessary, it doesnt get set then gets null checked

2024-06-10 01:40 UTC, brain-frog commented on src/ui/stats-container.ts
> +    this.updateValues(ivs, 31, ivs.reduce((res, iv) => res && iv === 31, true) ? window.perfectIVsChartColor ?? 0xFFBE00 : 0x98d8a0, originalIvs);
no need to make this a 1 line function that only exists to call the function below it
also please use the existing color used for text of max IVs

2024-06-10 01:44 UTC, prime-dialga commented on src/ui/stats-container.ts
> +
This is unfortunately required to prevent typedocs from throwing errors when using the global variable.

2024-06-10 01:50 UTC, bennybroseph commented on src/ui/stats-container.ts
> +
a global variable just for a color?

2024-06-10 01:55 UTC, prime-dialga commented on src/ui/stats-container.ts
> +
It was mainly intended for testing purposes, but there were also a few people in the dev chat who suggested different colors and thought that the perfect IV yellow is a bit hard to notice.
So i added this to allow for an easy override while the game is running, so testers could offer suggestions for other colors.
I'm personally inclined to leave this variable as a way for moders to adjust the color of the chart and perfect IV text (keeping both linked as requested by brain-frog), though i can see arguments against this.

2024-06-10 02:06 UTC, bennybroseph commented on src/ui/stats-container.ts
> +
as someone coming from C++/C# the word global makes my skin crawl. It's probably not great here either, but I'm not positive

2024-06-10 02:11 UTC, brain-frog commented on src/ui/stats-container.ts
> +
its also not required at all 
if you see my overall comment on the PR

2024-06-10 02:12 UTC, prime-dialga commented on src/ui/stats-container.ts
> +
I also think it's rather weird and the code would run without this (as tested), but typedocs would throw errors if we try to access a variable it doesn't know for an object it was never declared.
And to declare a variable for `window` that seems to be the "correct" way, even if it's weird.

Anyway, I'll remove the variable for now.
While i think we should allow the user to adjust stuff like text color to improve accessability, adding this functionality randomly with this feature and only for this feature is rather weird.

2024-06-10 02:29 UTC, prime-dialga commented
Changes have been implemented as noted.
Though:
- The color change animation still remains (it looks better than simply setting the color to a new one)
- I'm parsing the color obtained from getTextColor so potential future changes to the color don't require additional changes to this code.

![golden-chart3](https://github.com/pagefaultgames/pokerogue/assets/10091050/0f05001f-8ca1-4d3e-abbf-abb7d6ce2034)

2024-06-10 23:55 UTC, EvasiveAce commented
> Changes have been implemented as noted. Though:
> 
>     * The color change animation still remains (it looks better than simply setting the color to a new one)
> 
>     * I'm parsing the color obtained from getTextColor so potential future changes to the color don't require additional changes to this code.
> 
> 
> ![golden-chart3](https://private-user-images.githubusercontent.com/10091050/338033224-0f05001f-8ca1-4d3e-abbf-abb7d6ce2034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjM5ODAsIm5iZiI6MTcxODA2MzY4MCwicGF0aCI6Ii8xMDA5MTA1MC8zMzgwMzMyMjQtMGYwNTAwMWYtOGNhMS00ZDNlLWFiYmYtYWJiN2Q2Y2UyMDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDIzNTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OTdkYTlhNDNjYzg0YTM1OTA1ZjYwZWM1NDEzYzA1OTk3ZWJiOTIyMTQ4YzY0NjUzNzRiNjgyYzE5ODM3N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yq_XJsHX5pSXU0Z_D5JnAfZIatyUUzkX51xt9EWyl7U)

I like the color better. Nice work.

2024-06-12 13:56 UTC, brain-frog approved these changes

2024-06-12 13:56 UTC, merged