[Bug] Adjusts bug bite/pluck to remove berry pouch preservation on opponent berries
pagefaultgames/pokerogue pull request #2047
Opened 2024-06-10 17:54 UTC by schmidtc1

## What are the changes?

Currently, bug bite/pluck has a chance to preserve the berry in an opponents inventory if the user has berry pouches, potentially creating a nearly endless supply. With these changes, bug bite/pluck will no longer coincide with berry pouch functionality.

## Why am I doing these changes?

Bug bite/pluck has a chance to preserve the berry in an opponents inventory if the user has berry pouches, potentially creating a nearly endless supply.

#1315

Balances bug bite/pluck with berry pouch better to avoid infinite supplies of berries.

## What did change?

Removes the StealEatBerryAttr class extension of EatBerryAttr and removes berry pouch preservation when stealing an opponents berry.

Before:
StealEatBerryAttr extended EatBerryAttr and the super class (EatBerryAttr) was called to eat the berry, gain its effects, and check for berry pouch preservation.
After:
StealEatBerryAttr extends only MoveEffectAttr and no longer calls the super class to eat the berry and no longer checks for berry pouch preservation.

### Screenshots/Videos

## How to test the changes?

Tested using the `src/overrides.ts` file. 
export const STARTING_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [{name: "BERRY", count: 3, type: BerryType.SITRUS}, {name: "BERRY_POUCH", count: 3}];
export const OPP_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [{name: "BERRY", count: 3, type: BerryType.SITRUS}];

Recommend testing with no berry pouches vs. three berry pouches to see the effect.

Yes.

No.

2024-06-10 18:30 UTC, flx-sta requested changes

2024-06-10 18:30 UTC, flx-sta commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean | Promise<boolean> {
Changing the return type to be a non-promise or a Promise seems absolutely confusing and inconsistent.
why is the Promise necessary now?

2024-06-10 18:30 UTC, flx-sta commented on src/data/move.ts
> +      if (this.chosenBerry === undefined) { // if no berry has been provided, pick a random berry from their inventory
```suggestion
      if (!this.chosenBerry) { // if no berry has been provided, pick a random berry from their inventory
```
don't check for `undefined` UNLESS you really want to exclude `null`

2024-06-10 18:30 UTC, flx-sta commented on src/data/move.ts
> +      if (!--this.chosenBerry.stackCount) {
don't do decrementing inside of an if-clause.
This is an abomination for readability

2024-06-10 18:30 UTC, flx-sta commented on src/data/move.ts
> +      user.scene.queueMessage(getPokemonMessage(user, ` stole and ate\n${target.name}'s ${this.chosenBerry.type.name}!`));
We should probably localize (i18n) this, not more hard-coded English texts please

2024-06-10 18:51 UTC, schmidtc1 commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean | Promise<boolean> {
Leftover code from previous testing on the EatBerryAttr class. Removed.

2024-06-10 19:28 UTC, schmidtc1 commented on src/data/move.ts
> +      if (!--this.chosenBerry.stackCount) {
Adjusted this code for readability.

2024-06-10 19:29 UTC, schmidtc1 commented on src/data/move.ts
> +      user.scene.queueMessage(getPokemonMessage(user, ` stole and ate\n${target.name}'s ${this.chosenBerry.type.name}!`));
Attempted localization steps. Created translation entries under "stealEatBerry" in the battle.ts file of each locale.

2024-06-10 20:34 UTC, flx-sta commented on src/data/move.ts
> +        this.chosenBerry = heldBerries[user.randSeedInt(heldBerries.length)];
wouldn't this possibly cause an `index out of bounds` error?
Because `heldBerries[heldBerries.length]` is 1 index too high (0 index starts)

2024-06-10 20:45 UTC, schmidtc1 commented on src/data/move.ts
> +        this.chosenBerry = heldBerries[user.randSeedInt(heldBerries.length)];
Correct me if I am wrong: I believe randSeedInt is non-inclusive on the range, meaning it is up to, not including heldBerries.length. 
I have not seen any index out of bounds errors when testing so far.

2024-06-12 01:24 UTC, schmidtc1 commented
Before:
https://github.com/pagefaultgames/pokerogue/assets/62030095/e4e7374e-38b5-49c6-83b8-3ddca29bf97a

After:
https://github.com/pagefaultgames/pokerogue/assets/62030095/a9c842d2-d124-4d71-8fa9-f20b9f5a5187

2024-06-12 15:35 UTC, schmidtc1 commented
Sticky hold example:

https://github.com/pagefaultgames/pokerogue/assets/62030095/d0de7482-1f5b-4be2-9a42-6619661f67c5

2024-06-20 18:06 UTC, schmidtc1 commented
Example with multi lens bug bite:

https://github.com/pagefaultgames/pokerogue/assets/62030095/3e19c7e7-8621-4437-bcc7-d2e5891d7fac

2024-06-20 23:08 UTC, Adri1 reviewed
French translation

2024-06-20 23:08 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "stealEatBerry": "{{pokemonName}} stole and ate\n{{targetName}}'s {{berryName}}!",
```suggestion
  "stealEatBerry": "{{pokemonName}} vole et mange\nla {{berryName}} de {{targetName}} !",
```

2024-06-20 23:21 UTC, InnocentGameDev commented on src/locales/es/battle.ts
> +  "stealEatBerry": "{{pokemonName}} stole and ate\n{{targetName}}'s {{berryName}}!",
"¡{{pokemonName}} robó la {{berryName}}\n de {{targetName}} y se la comió!"

2024-06-20 23:32 UTC, Adri1 reviewed
Missing "stealEatBerry" and coma here (and removed unnecessary space)

2024-06-20 23:32 UTC, Adri1 commented on src/locales/es/battle.ts
> +  "¡{{pokemonName}} robó la {{berryName}}\n de {{targetName}} y se la comió!"
```suggestion
  "¡{{pokemonName}} robó la {{berryName}}\nde {{targetName}} y se la comió!",
```

2024-06-20 23:38 UTC, schmidtc1 commented on src/locales/es/battle.ts
> +  "¡{{pokemonName}} robó la {{berryName}}\n de {{targetName}} y se la comió!"
Should be resolved in latest commits

2024-06-21 00:15 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "stealEatBerry": "{{pokemonName}} stole and ate\n{{targetName}}'s {{berryName}}!",
```suggestion
  "stealEatBerry": "{{pokemonName}}[[가]]\n{{targetName}}의 {{berryName}}[[를]] 빼앗아 먹었다!",
```

2024-06-21 14:38 UTC, Tempo-anon submitted a review, later dismissed

2024-06-21 14:58 UTC, Tempo-anon commented on src/data/move.ts
> +      if (!this.chosenBerry) { // if no berry has been provided, pick a random berry from their inventory
Will this ever be false?

2024-06-21 14:58 UTC, Tempo-anon commented on src/data/move.ts
> +
nit: excess lines

2024-06-21 14:58 UTC, Tempo-anon commented on src/data/move.ts
> +      this.chosenBerry = undefined;
Does this need to be set to undefined after?

2024-06-21 15:45 UTC, OrangeRed requested changes

2024-06-21 15:45 UTC, OrangeRed commented on src/data/move.ts
> +    this.chosenBerry = undefined;
Can you instead just add a method to EatBerryAttr that accepts a preserve boolean and handles the berry eating logic. I don't see a need to logically separate stealing a berry and eating berry (especially when some logic is reused) when instead you can make an inherited class method.

2024-06-21 15:50 UTC, OrangeRed commented on src/data/move.ts
> +      applyAbAttrs(HealFromBerryUseAbAttr, target, new Utils.BooleanHolder(false));
This logic could be moved into a shared class method and called on demand. There is no need to separate StealBerry and EatBerry if you do that.

2024-06-21 16:58 UTC, schmidtc1 commented on src/data/move.ts
> +    this.chosenBerry = undefined;
StealEatBerry and EatBerry were separated on the original bug bite implementation, I can work on merging the logic if that is preferred

2024-06-21 17:17 UTC, OrangeRed commented on src/data/move.ts
> +    this.chosenBerry = undefined;
> StealEatBerry and EatBerry were separated on the original bug bite implementation, I can work on merging the logic if that is preferred

They were not separated. The former inherits the latter and truly separating them like you do in this PR just increases how much identical code you have to write

2024-06-21 18:09 UTC, schmidtc1 commented on src/data/move.ts
> +    this.chosenBerry = undefined;
You're right I misremembered. I'll work on merging the logic.

2024-06-21 18:44 UTC, schmidtc1 commented on src/data/move.ts
> +      if (!this.chosenBerry) { // if no berry has been provided, pick a random berry from their inventory
Should be resolved in new commit that combines StealEatBerryAttr and EatBerryAttr

2024-06-21 18:45 UTC, schmidtc1 commented on src/data/move.ts
> +
Resolved in latest commit

2024-06-21 18:46 UTC, schmidtc1 commented on src/data/move.ts
> +      this.chosenBerry = undefined;
No, resolved.

2024-06-21 18:46 UTC, schmidtc1 commented on src/data/move.ts
> +      applyAbAttrs(HealFromBerryUseAbAttr, target, new Utils.BooleanHolder(false));
Combined StealBerry and EatBerry into EatBerryAttr. Should be resolved.

2024-06-27 00:52 UTC, OrangeRed requested changes
Overall this looks like what I was expecting. Can you just invert the conditional like I mentioned inside both EatBerryAbAttr and StealBerryAbAttr

2024-06-27 00:52 UTC, OrangeRed commented on src/data/move.ts
> +    return false;
I prefer early returns over nesting, so can you invert this to like it was before this change.
```ts
      if (heldBerries.length <= 0) {
        return false;
      }

     // ...

    return true;
```

2024-06-27 02:38 UTC, schmidtc1 commented on src/data/move.ts
> +    return false;
Should be resolved in latest commit

2024-06-27 02:40 UTC, OrangeRed approved these changes

2024-07-02 14:28 UTC, merged