[Feature] Add a BattlerTag for move-disabling effects
pagefaultgames/pokerogue pull request #2051
Opened 2024-06-10 18:43 UTC by zacharied

## What are the changes?
This PR implements a new `BattlerTag` for move-disabling effects such as those done by Disable, Taunt, Throat Chop, etc.. It also replaces the implementation of the move Disable and the ability Cursed Body with a new implementation using this tag.

## Why am I doing these changes?
The current implementation of disabling has a few issues:

* Only one move can be disabled per Pokemon at a time, and very few disable effects actually work this way in-game
* No way to introspect on source of the disable

#751 is an example of existing work to fix this, but it is susceptible to the same problems as the current approach, and there are many situations where that solution would not work -- for example, with #751 as a solution, a Pokemon that learned a sound-based move after getting hit by Throat Chop would be able to use it, which is incorrect behavior.

I see no reason for disabling to work this way when we already have the `BattlerTag` system specifically meant for temporary effects such as this. With these changes, implementing new disabling moves becomes trivial. I already have implementations of Taunt and Throat Chop ready to go if this is accepted, with more moves on the way.

## What did change?

Add abstract class `DisablingBattlerTag` that serves as the base for all tags that disable moves. Also add `DisabledTag` that represents Disabling as applied by the move Disable and ability Cursed Body.

Remove `DisableMoveAttr` and replace Disable's effect with adding a `DisabledTag`.

Add battler tag type `DISABLED` which maps to `DisabledTag`. This tag has been given the same `targetBenefit` as was previously bestowed by `DisableMoveAttr`.

`disabledMove` and `disabledTurns` fields removed from `PokemonSummonData`. Any time those fields would be set, instead an instance of tag `DisabledTag` is applied. Because this uses the tag system, all the code that had to manually manipulate/check `disabledTurns` has been removed as well.

Add new function `Pokemon.isMoveDisabled(Moves)` that checks whether the Pokemon has a tag that disables the given move.

### Screenshots/Videos

## How to test the changes?

I used the following overrides for testing:

```ts
**
 * OVERALL OVERRIDES
 */

// a specific seed (default: a random string of 24 characters)
export const SEED_OVERRIDE: string = "";
export const WEATHER_OVERRIDE: WeatherType = WeatherType.NONE;
export const DOUBLE_BATTLE_OVERRIDE: boolean = false;
export const SINGLE_BATTLE_OVERRIDE: boolean = false;
export const STARTING_WAVE_OVERRIDE: integer = 106;
export const STARTING_BIOME_OVERRIDE: Biome = Biome.TOWN;
export const ARENA_TINT_OVERRIDE: TimeOfDay = null;
// Multiplies XP gained by this value including 0. Set to null to ignore the override
export const XP_MULTIPLIER_OVERRIDE: number = null;
export const IMMEDIATE_HATCH_EGGS_OVERRIDE: boolean = false;
// default 1000
export const STARTING_MONEY_OVERRIDE: integer = 0;
export const POKEBALL_OVERRIDE: { active: boolean, pokeballs: PokeballCounts } = {
  active: false,
  pokeballs: {
    [PokeballType.POKEBALL]: 5,
    [PokeballType.GREAT_BALL]: 0,
    [PokeballType.ULTRA_BALL]: 0,
    [PokeballType.ROGUE_BALL]: 0,
    [PokeballType.MASTER_BALL]: 0,
  }
};

/**
 * PLAYER OVERRIDES
 */

// forms can be found in pokemon-species.ts
export const STARTER_FORM_OVERRIDE: integer = 0;
// default 5 or 20 for Daily
export const STARTING_LEVEL_OVERRIDE: integer = 100;
/**
 * SPECIES OVERRIDE
 * will only apply to the first starter in your party or each enemy pokemon
 * default is 0 to not override
 * @example SPECIES_OVERRIDE = Species.Bulbasaur;
 */
export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.PIKACHU;
export const ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const PASSIVE_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const STATUS_OVERRIDE: StatusEffect = StatusEffect.NONE;
export const GENDER_OVERRIDE: Gender = null;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.DISABLE, Moves.SPLASH, Moves.GROWL, Moves.TAIL_WHIP];
export const SHINY_OVERRIDE: boolean = false;
export const VARIANT_OVERRIDE: Variant = 0;

/**
 * OPPONENT / ENEMY OVERRIDES
 */

export const OPP_SPECIES_OVERRIDE: Species | integer = 0;
export const OPP_LEVEL_OVERRIDE: number = 1;
export const OPP_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const OPP_PASSIVE_ABILITY_OVERRIDE = Abilities.NONE;
export const OPP_STATUS_OVERRIDE: StatusEffect = StatusEffect.NONE;
export const OPP_GENDER_OVERRIDE: Gender = null;
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [Moves.DISABLE, Moves.SPLASH, Moves.NONE, Moves.NONE];
export const OPP_SHINY_OVERRIDE: boolean = false;
export const OPP_VARIANT_OVERRIDE: Variant = 0;
```

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-10 21:49 UTC, zacharied commented
I've added some moves as a proof of concept to another branch. For example, here's Throat Chop and Taunt: https://github.com/pagefaultgames/pokerogue/commit/94cfb53c243ecf37bf389a2dcd5ccde1f80bbd67

2024-06-11 07:59 UTC, zacharied commented
Rewrote OP to focus more on integrating the variety of disparate Disable effect commits.

2024-06-15 03:29 UTC, zacharied commented
Converted to draft due to significant overlap with other PRs.

2024-06-26 04:17 UTC, DayKev commented
Imo it'd be best if this PR was merged and then the other PRs were updated to use the new, non-spaghetti code.

2024-06-29 22:21 UTC, audriddax commented
I'm just going through this, but as the developer of #1121, I have no objection to cleaning this up. I kinda touched on it in some of my back and forth in that one, I wasn't thrilled with what it required to implement. Not only did I talk about how I was hesitant to update code on something that basically affected every move, but on my end I also was seeing exactly what you are trying to address based on your summary here.

I'm all for a change that creates a better framework for my code, I'll gladly update it rather than add extra code to an "unrelated" section just for my move. I'm actually glad I had to step away for a few weeks and haven't had my code committed if it means we're getting a better framework!

2024-06-29 22:23 UTC, audriddax commented
> Imo it'd be best if this PR was merged and then the other PRs were updated to use the new, non-spaghetti code.

I agree with this, don't try to update my move, I'll do that gladly!

2024-08-03 22:10 UTC, zacharied commented
WTF did i do to make those tests fail 😭

2024-08-04 00:47 UTC, DayKev commented
One of the overrides changed how it worked (instead of `SINGLE_BATTLE_OVERRIDE`/`DOUBLE_BATTLE_OVERRIDE` there's just `BATTLE_TYPE_OVERRIDE: "double" | "single" | null`).
Also there are helper functions to change overrides now (`game.override.x()`) that you can make use of.

2024-08-06 21:03 UTC, torranx commented
Are you still working on this @zacharied ?

2024-08-08 21:46 UTC, zacharied commented
> Hi, thank you for working on this. I was wondering if this was able to be extended to multiple categories / attrs of moves. I'm currently working on Heal Block right now and was hoping to try disabling moves based on attributes.

Yep, the Disable tag takes a filter function as argument, so you can disable based on any criteria you want.

2024-08-08 23:04 UTC, zacharied commented
Okay, just need to localize a couple strings and fix these test failures.

For the PURIFY failure, it seems like the mons are moving out of order. The Magikarp uses Splash when it's supposed to be the Pyukumuku using Purify. I can fix this by forcing Pyukumuku to be faster -- seems like an error with the test file?

Still investigating the HYPER BEAM failure, that's a weird one.

2024-08-08 23:58 UTC, DayKev commented
Fixed the test bugs in #3449

2024-08-09 16:39 UTC, zacharied commented
@DayKev looks like Hyper Beam is still RNG?

2024-08-09 19:33 UTC, DayKev commented
I wish Github would give the console log for the test... guess I'll just have to run the test a whole bunch.

2024-08-09 19:44 UTC, DayKev commented
Oh I guess you did break something..? Looking at the test in this branch after pulling in the latest beta changes, the Tackle never happens after the Hyper Beam. I guess it's something to do with the recharge part of hyper beam not being reset properly?
```
[ 'Magikarp used !' ]
[ '%cStart Phase MessagePhase', 'color:green;' ]
[ 'But it failed!' ]
```

2024-08-09 21:17 UTC, zacharied commented
> Oh I guess you did break something..? Looking at the test in this branch after pulling in the latest beta changes, the Tackle never happens after the Hyper Beam. I guess it's something to do with the recharge part of hyper beam not being reset properly?
> 
> ```
> [ 'Magikarp used !' ]
> [ '%cStart Phase MessagePhase', 'color:green;' ]
> [ 'But it failed!' ]
> ```

Oh, my bad then. Gonna dig into it.

2024-08-10 00:30 UTC, innerthunder requested changes
Will check out the test code later 🔍

2024-08-10 00:30 UTC, innerthunder commented on src/data/battler-tags.ts
> +  }
```suggestion
  lapse(pokemon: Pokemon, lapseType: BattlerTagLapseType): boolean {
    if (lapseType === BattlerTagLapseType.PRE_MOVE) {
      // Cancel the affected pokemon's selected move
      const phase = pokemon.scene.getCurrentPhase() as MovePhase;
      const move = phase.move;

      if (this.moveIsDisabled(move.moveId)) {
        pokemon.scene.queueMessage(this.interruptedText(pokemon, move.moveId));
        phase.fail();
      }
      return true;
    }
    // On turn end, subtract from lifetime and remove this tag if 0
    return super.lapse(pokemon, lapseType);
  }
```
Some style changes, should still function the same.

2024-08-10 00:30 UTC, innerthunder commented on src/data/battler-tags.ts
> +      phase.fail();
I think this should be `phase.cancel()` instead, so the move doesn't use PP when cancelled this way.

2024-08-10 00:30 UTC, innerthunder commented on src/data/battler-tags.ts
> +  public moveId: integer = 0;
```suggestion
  public moveId: Moves = Moves.NONE;
```

2024-08-10 00:30 UTC, innerthunder commented on src/data/battler-tags.ts
> +  }
Can be removed; we probably don't want to keep the `console.warn(...)`

2024-08-10 00:30 UTC, innerthunder commented on src/data/battler-tags.ts
> +    const history = pokemon.getLastXMoves();
Can you filter out `virtual` moves here (so moves generated from Metronome, etc. aren't considered)?

2024-08-10 00:47 UTC, DayKev commented on src/data/battler-tags.ts
> +    const history = pokemon.getLastXMoves();
That'll be removed when #3380 gets merged.

2024-08-10 01:24 UTC, innerthunder commented on src/data/battler-tags.ts
> +    const history = pokemon.getLastXMoves();
So `Move.virtual` is getting removed? I checked the PR and all I saw that was removed was the `IGNORE_VIRTUAL` flag

2024-08-10 01:59 UTC, innerthunder requested changes

2024-08-10 01:59 UTC, innerthunder commented on src/test/moves/disable.test.ts
> +    game.override.enemyMoveset([Moves.SPLASH,Moves.SPLASH,Moves.SPLASH,Moves.SPLASH]);
Use one of the test utils instead:
```suggestion
    game.override.enemyMoveset(ALL_SPLASH);
```

2024-08-10 01:59 UTC, innerthunder commented on src/test/moves/disable.test.ts
> +    expect(game.scene.getParty()[0].stats[Stat.SPD]).toBeGreaterThan(game.scene.getEnemyParty()[0].stats[Stat.SPD]);
Instead of using `game.scene.get<Enemy>Party()[0]` everywhere, get a reference to the Pokemon with `game.scene.getPlayerPokemon` or `game.scene.getEnemyPokemon`, e.g.
```ts
const pikachu = game.scene.getPlayerPokemon()!; // "!" to avoid strict-null issues
const shuckle = game.scene.getEnemyPokemon()!;

expect(pikachu.stats[Stat.SPD]).toBeGreaterThan(shuckle.stats[SPD])
/* ... */
```

2024-08-10 01:59 UTC, innerthunder commented on src/test/moves/disable.test.ts
> +    expect(game.scene.getParty()[0].getMoveHistory().at(0)!.result).toBe(MoveResult.FAIL);
Might want to add another `expect` to make sure `getMoveHistory` isn't empty

2024-08-10 01:59 UTC, innerthunder commented on src/test/moves/disable.test.ts
Some more tests I'd like to see:
- Disable fails if the target's last move was Struggle (you can use overrides to change the enemy's moveset to `Array(4).fill(Moves.STRUGGLE)` for this)
- Disable disables Nature Power, not the move invoked by Nature Power
- Disable forces the target to use Struggle if it doesn't have any other usable moves ([Metapod](https://bulbapedia.bulbagarden.net/wiki/Metapod_(Pok%C3%A9mon)) can only learn Harden, so it might be helpful if overrides don't work for this case)

2024-08-10 02:11 UTC, zacharied commented
Whoops, sorry for the extra review request.

2024-08-10 02:52 UTC, DayKev commented on src/test/moves/disable.test.ts
> +    game.override.enemyMoveset([Moves.SPLASH,Moves.SPLASH,Moves.SPLASH,Moves.SPLASH]);
It's `SPLASH_ONLY` btw.

2024-08-10 05:48 UTC, innerthunder approved these changes
lgtm (code-wise, haven't tested)

2024-08-10 14:09 UTC, torranx approved these changes
looks good to me

2024-08-15 19:27 UTC, snoozbuster commented on src/field/pokemon.ts
> +   * Gets whether a move is currently disabled for this Pokemon.
```suggestion
   * Gets whether the given move is currently disabled for this Pokemon.
```

2024-08-15 19:28 UTC, snoozbuster commented on src/field/pokemon.ts
> +    for (const tag of this.findTags(t => t instanceof DisablingBattlerTag)) {
Can't this be `return this.findTags(...).find(() =>...)`?

2024-08-15 19:30 UTC, snoozbuster commented on src/field/pokemon.ts
> +    if (this.getMove().name.endsWith(" (N)")) {
This check for the move name is insane lol surely this fails in non-english locales? There is no better way to do this? (I realize this was here before but it's still so insane)

2024-08-15 19:34 UTC, snoozbuster commented on src/data/battler-tags.ts
> +export abstract class DisablingBattlerTag extends BattlerTag {
This is maybe a weird ask but thoughts on calling this `MoveRestrictionBattlerTag` or something along those lines? I think given it's intended genericism that's something of a better name (for example, choice effects might also be implentable through this base class) but also the existing name kinda gives off "handicapped Pokémon" vibes to me 😅

2024-08-15 19:38 UTC, snoozbuster commented on src/data/battler-tags.ts
> +export abstract class DisablingBattlerTag extends BattlerTag {
Is this tag passed via baton pass? Is it supposed to be? (I didn't read the tests you added yet but since this tag is intended to be used across lots of moves it probably makes sense for it to be part of the baton pass test suite)

2024-08-15 20:25 UTC, innerthunder commented on src/data/battler-tags.ts
> +export abstract class DisablingBattlerTag extends BattlerTag {
Baton pass logic should be rewritten soon (#3472 is the first step), so I wouldn't worry about this too much

2024-08-15 20:29 UTC, innerthunder commented on src/field/pokemon.ts
> +    if (this.getMove().name.endsWith(" (N)")) {
I think " (N)" gets slapped onto the name of any move with `.unimplemented()`, regardless of language.

Obviously this check isn't ideal, but it shouldn't fail bc of localization issues.

2024-08-15 20:30 UTC, snoozbuster commented on src/field/pokemon.ts
> +    if (this.getMove().name.endsWith(" (N)")) {
wild. insane. bizarre

2024-08-15 20:59 UTC, DayKev commented on src/field/pokemon.ts
> +    if (this.getMove().name.endsWith(" (N)")) {
Unfortunately Sam decided the best way to check if a move is unimplemented is to slap " (N)" at the end and check for that, instead of properly adding some sort of `unimplemented` attribute. So we're stuck with it, and since 99% of moves are completed there's no real incentive to try and fix it.

2024-08-15 21:02 UTC, DayKev commented on src/data/battler-tags.ts
> +export abstract class DisablingBattlerTag extends BattlerTag {
The (new) default is for Baton Pass to not pass any `BattlerTag`s by default, requiring them to be specifically marked as transferrable. Since Baton Pass isn't supposed to pass Disable-type effects then it should automatically work properly.

2024-09-02 21:12 UTC, zacharied commented
Ah shit i forgor about this lmao

2024-09-05 00:05 UTC, innerthunder commented on src/test/moves/disable.test.ts
> +  };
Just use `game.move.select` instead of this; I think this is based on old test code

2024-09-05 02:28 UTC, flx-sta commented on src/data/ability.ts
> +    if (attacker.getTag(BattlerTagType.DISABLED) === null) {
Is it possible to be `undefined`?
E.g. due to `JSON.parse()` or something.

2024-09-05 02:28 UTC, flx-sta commented on src/data/battler-tags.ts
> +  public moveId: Moves = Moves.NONE;
NIT:
wouldn't `protected` be enough?

2024-09-05 02:36 UTC, torranx reviewed
couple nits, some docs are missing `@param` and `@returns` too, otherwise looks good to me

2024-09-05 02:36 UTC, torranx commented on src/field/pokemon.ts
> +   * Gets whether the given move move is currently disabled for this Pokemon.
nit:
```suggestion
   * Gets whether the given move is currently disabled for this Pokemon.
```

2024-09-05 02:36 UTC, torranx commented on src/test/moves/disable.test.ts
> +    enemyMon.stats[Stat.SPD] = 2;
nit: these should be mocked (same with other occurrences here)

2024-09-05 03:17 UTC, flx-sta commented on src/test/moves/disable.test.ts
> +    enemyMon.stats[Stat.SPD] = 2;
not a nit. We want to avoid spreading more of this `false` approach`

2024-09-05 03:19 UTC, flx-sta commented on src/test/moves/disable.test.ts
> +    enemyMon.stats[Stat.SPD] = 2;
@torranx Is this really the recommended way though?

```ts
vi.spyOn(playerPokemon[0], "stats", "get").mockReturnValue([20, 20, 20, 20, 20, 100]);
```

2024-09-05 04:07 UTC, torranx commented on src/test/moves/disable.test.ts
> +    enemyMon.stats[Stat.SPD] = 2;
aint pretty but it works. if you find better alternative, please inform us 👍

2024-09-05 07:36 UTC, torranx submitted a review, later dismissed
lgtm

2024-09-05 08:16 UTC, DayKev approved these changes

2024-09-05 08:28 UTC, torranx approved these changes

2024-09-05 08:33 UTC, innerthunder approved these changes

2024-09-05 08:44 UTC, f-fsantos approved these changes

2024-09-05 08:44 UTC, merged