[Localization] Localized Daily Run Scoreboard
pagefaultgames/pokerogue pull request #2053
Opened 2024-06-10 18:50 UTC by josericardo-fo

## What are the changes?

## Why am I doing these changes?

Localized the Daily Run Scoreboard

## What did change?

The labels of the columns in the scoreborad

### Screenshots/Videos

## Before (ptBR)
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/540123de-9d2d-4acb-992f-2bf026547bd1)

## After (ptBR)
(no assets yet)

## How to test the changes?

Run a server and check the scoreboards

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
    I got a bunch of errors that were not related to my changes
- [X] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-10 19:01 UTC, flx-sta commented on src/locales/de/menu.ts
> +  "wave": "Wave",
```suggestion
  "usernameScoreboard": "Benutzername",
  "score": "Punktzahl",
  "wave": "Welle",
```

2024-06-10 19:02 UTC, flx-sta commented on src/ui/daily-run-scoreboard.ts
> +    this.rankingsContainer.add(getEntry("#", i18next.t("menu:usernameScoreboard"), i18next.t("menu:score"), i18next.t("menu:wave")));
Idk if there is a language where they don't use `#` for the number abbrv. 
Should it be localized too?

2024-06-10 19:05 UTC, flx-sta commented
<img width="371" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/c8ef37c7-eedb-476e-b6a3-2c9921127525">

seems to work.
There is some comments open from me.
I see a problem with the `score` word in many languages as not every language has such a short word for it.

2024-06-10 19:41 UTC, josericardo-fo commented on src/ui/daily-run-scoreboard.ts
> +    this.rankingsContainer.add(getEntry("#", i18next.t("menu:usernameScoreboard"), i18next.t("menu:score"), i18next.t("menu:wave")));
localized

2024-06-10 19:43 UTC, josericardo-fo commented
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/50131232/338310921-c8ef37c7-eedb-476e-b6a3-2c9921127525.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDg2ODYsIm5iZiI6MTcxODA0ODM4NiwicGF0aCI6Ii81MDEzMTIzMi8zMzgzMTA5MjEtYzhlZjM3YzctZWVkYi00NzZlLWI2YTMtMmM5OTIxMTI3NTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE5Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkODhjZTc2NDFhNjBiMGQ4N2M1MTFmOTc5NGFmZWJhYjAxZWMzYTQzMzk5ZTZhODljMWJiNmJkZDYyYWEyY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FkTTCGg13363LHOXKOmCqnqAAKptT41OyZUaiHmT4s4">
> seems to work. There is some comments open from me. I see a problem with the `score` word in many languages as not every language has such a short word for it.

Do you think that this fix needs to be in this PR?

2024-06-10 20:35 UTC, flx-sta commented
I don't necessarily think so, but I also think this looks super ugly if not :D
I'd get some devs opinion on it

2024-06-14 13:32 UTC, EnochG1 requested changes
I suggest korean locales :)

2024-06-14 14:33 UTC, flx-sta commented on src/locales/de/menu.ts
> +  "score": "Punkte",
```suggestion
  "score": "Pkt.",
```

2024-06-16 06:58 UTC, EnochG1 approved these changes

2024-06-16 20:09 UTC, CodeTappert approved these changes
Looks good.

2024-06-16 20:15 UTC, CodeTappert approved these changes

2024-06-16 20:23 UTC, XGSleepWalker approved these changes

2024-06-16 20:23 UTC, merged