[Move] Implemented Magnet Rise
pagefaultgames/pokerogue pull request #2081
Opened 2024-06-11 07:55 UTC by Frisk17

## What are the changes?
Implemented the move [Magnet Rise](https://bulbapedia.bulbagarden.net/wiki/Magnet_Rise_(move))

## Why am I doing these changes?
The move was partially implemented with a `BattlerTag` but the effect of being immune from ground type moves wasn't.
[The issue for this move](https://github.com/pagefaultgames/pokerogue/issues/1505)

## What did change?
- Removed unimplemented from Magnet Rise in `move.ts`
- Implemented a message when the move is used in `battler-tag.ts`
- Implemented the immunity in `pokemon.ts`

### Screenshots/Videos
https://github.com/pagefaultgames/pokerogue/assets/38005728/4b9512df-914b-4d67-a195-0b311657ead9

## How to test the changes?
`overrides.ts`
```ts
import { Species } from "./data/enums/species";
import { Abilities } from "./data/enums/abilities";
import { Biome } from "./data/enums/biome";
import { Moves } from "./data/enums/moves";
import { WeatherType } from "./data/weather";
import { Variant } from "./data/variant";
import { BerryType } from "./data/enums/berry-type";
import { TempBattleStat } from "./data/temp-battle-stat";
import { Nature } from "./data/nature";
import { Type } from "./data/type";
import { Stat } from "./data/pokemon-stat";
import { PokeballCounts } from "./battle-scene";
import { PokeballType } from "./data/pokeball";
import {TimeOfDay} from "#app/data/enums/time-of-day";
import { Gender } from "./data/gender";
import { StatusEffect } from "./data/status-effect";
import { modifierTypes } from "./modifier/modifier-type";

/**
 * Overrides for testing different in game situations
 * if an override name starts with "STARTING", it will apply when a new run begins
 */

/**
 * OVERALL OVERRIDES
 */

// a specific seed (default: a random string of 24 characters)
export const SEED_OVERRIDE: string = "";
export const WEATHER_OVERRIDE: WeatherType = WeatherType.NONE;
export const DOUBLE_BATTLE_OVERRIDE: boolean = false;
export const SINGLE_BATTLE_OVERRIDE: boolean = false;
export const STARTING_WAVE_OVERRIDE: integer = 0;
export const STARTING_BIOME_OVERRIDE: Biome = Biome.TOWN;
export const ARENA_TINT_OVERRIDE: TimeOfDay = null;
// Multiplies XP gained by this value including 0. Set to null to ignore the override
export const XP_MULTIPLIER_OVERRIDE: number = null;
export const IMMEDIATE_HATCH_EGGS_OVERRIDE: boolean = false;
// default 1000
export const STARTING_MONEY_OVERRIDE: integer = 0;
export const POKEBALL_OVERRIDE: { active: boolean, pokeballs: PokeballCounts } = {
  active: false,
  pokeballs: {
    [PokeballType.POKEBALL]: 5,
    [PokeballType.GREAT_BALL]: 0,
    [PokeballType.ULTRA_BALL]: 0,
    [PokeballType.ROGUE_BALL]: 0,
    [PokeballType.MASTER_BALL]: 0,
  }
};

/**
 * PLAYER OVERRIDES
 */

// forms can be found in pokemon-species.ts
export const STARTER_FORM_OVERRIDE: integer = 0;
// default 5 or 20 for Daily
export const STARTING_LEVEL_OVERRIDE: integer = 0;
/**
 * SPECIES OVERRIDE
 * will only apply to the first starter in your party or each enemy pokemon
 * default is 0 to not override
 * @example SPECIES_OVERRIDE = Species.Bulbasaur;
 */
export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.MAGNEZONE;
export const ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const PASSIVE_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const STATUS_OVERRIDE: StatusEffect = StatusEffect.NONE;
export const GENDER_OVERRIDE: Gender = null;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.MAGNET_RISE, Moves.SPLASH];
export const SHINY_OVERRIDE: boolean = false;
export const VARIANT_OVERRIDE: Variant = 0;

/**
 * OPPONENT / ENEMY OVERRIDES
 */

export const OPP_SPECIES_OVERRIDE: Species | integer = Species.GOLEM;
export const OPP_LEVEL_OVERRIDE: number = 0;
export const OPP_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const OPP_PASSIVE_ABILITY_OVERRIDE = Abilities.NONE;
export const OPP_STATUS_OVERRIDE: StatusEffect = StatusEffect.NONE;
export const OPP_GENDER_OVERRIDE: Gender = null;
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [Moves.EARTHQUAKE, Moves.SPLASH, Moves.SPLASH, Moves.SPLASH];
export const OPP_SHINY_OVERRIDE: boolean = false;
export const OPP_VARIANT_OVERRIDE: Variant = 0;

/**
 * MODIFIER / ITEM OVERRIDES
 * if count is not provided, it will default to 1
 * @example Modifier Override [{name: "EXP_SHARE", count: 2}]
 * @example Held Item Override [{name: "LUCKY_EGG"}]
 *
 * Some items are generated based on a sub-type (i.e. berries), to override those:
 * @example [{name: "BERRY", count: 5, type: BerryType.SITRUS}]
 * types are listed in interface below
 * - TempBattleStat is for TEMP_STAT_BOOSTER / X Items (Dire hit is separate)
 * - Stat is for BASE_STAT_BOOSTER / Vitamin
 * - Nature is for MINT
 * - Type is for TERA_SHARD or ATTACK_TYPE_BOOSTER (type boosting items i.e Silk Scarf)
 * - BerryType is for BERRY
 */
interface ModifierOverride {
    name: keyof typeof modifierTypes & string,
    count?: integer
    type?: TempBattleStat|Stat|Nature|Type|BerryType
}
export const STARTING_MODIFIER_OVERRIDE: Array<ModifierOverride> = [];
export const OPP_MODIFIER_OVERRIDE: Array<ModifierOverride> = [];

export const STARTING_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [];
export const OPP_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [];
export const NEVER_CRIT_OVERRIDE: boolean = false;

/**
 * An array of items by keys as defined in the "modifierTypes" object in the "modifier/modifier-type.ts" file.
 * Items listed will replace the normal rolls.
 * If less items are listed than rolled, only some items will be replaced
 * If more items are listed than rolled, only the first X items will be shown, where X is the number of items rolled.
 */
export const ITEM_REWARD_OVERRIDE: Array<String> = [];
```

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-06-11 08:27 UTC, zacharied commented on src/field/pokemon.ts
> +    if (this.getTags(BattlerTagType.MAGNET_RISEN).filter((tag) => tag instanceof TypeImmuneTag && tag.immuneType === move.type).length !== 0) {
any special reason we specify MAGNET_RISEN here? I'd imagine all TypeImmuneTags are relevant here

2024-06-11 08:38 UTC, Frisk17 commented on src/field/pokemon.ts
> +    if (this.getTags(BattlerTagType.MAGNET_RISEN).filter((tag) => tag instanceof TypeImmuneTag && tag.immuneType === move.type).length !== 0) {
no, I think I did it because the only `TypeImmuneTag` was `MagnetRisen`
I've just changed it to handle every `TypeImmuneTag` now

2024-06-11 13:28 UTC, Tempo-anon commented
Does this account for all the edge cases and niche interactions? It's removed by smack down/thousand arrows and also fails if smacked down or thousand arrow'd. Gravity also disables magnet rise's effect during its duration. It's also transferable by baton pass.

2024-06-11 15:38 UTC, Frisk17 commented
> Does this account for all the edge cases and niche interactions? It's removed by smack down/thousand arrows and also fails if smacked down or thousand arrow'd. Gravity also disables magnet rise's effect during its duration. It's also transferable by baton pass.

It already works with baton pass and ignores spikes, stealth rock etc. as expected. I just made changes that makes gravity and Smack Down / Thousand Arrows also work as expected. Everything other than Snatch (which is still unimplemented) should work fine.

2024-06-11 17:15 UTC, Greenlamp2 commented
Would it be possible to write unit test to test these edge case ?

2024-06-11 20:20 UTC, OrangeRed requested changes
In general can you also write some tests to verify the move is working correctly.

2024-06-11 20:20 UTC, OrangeRed commented on src/data/move.ts
> +      !user.getTag(BattlerTagType.MAGNET_RISEN)),
Can you change this condition to use `[BattlerTagType].some(fn)` instead of three different conditional checks

2024-06-11 20:20 UTC, OrangeRed commented on src/field/pokemon.ts
> +      }
instead of `Array.filter()` can you use `Array.find()`

2024-06-11 20:20 UTC, OrangeRed commented on src/field/pokemon.ts
> +      }
This check should be moved into `Pokemon.getAttackTypeEffectiveness()` because that function is also used by a pokemon ai to determine what move to use

2024-06-11 20:20 UTC, OrangeRed commented on src/data/battler-tags.ts
> +    this.immuneType = immuneType;
Can you default the length to 1 so it retains the previous functionality

2024-06-11 20:20 UTC, OrangeRed commented on src/data/arena-tag.ts
> +    });
You might want to add a message to `onRemove()` to `MagnetRisenTag` to inform the player the effect has ended.

2024-06-12 04:41 UTC, Frisk17 commented on src/data/move.ts
> +      !user.getTag(BattlerTagType.MAGNET_RISEN)),
I created a `MoveConditionFunc` separately for magnet rise but I'm unsure what you mean by `[BattlerTagType].some(fn)` since BattlerTagType is an enum

2024-06-12 04:44 UTC, Frisk17 commented on src/field/pokemon.ts
> +      }
I added the check there too but I didn't remove this one since it doesn't look like that function is used for damage calculations (only the AI)

2024-06-12 04:45 UTC, Frisk17 commented on src/data/arena-tag.ts
> +    });
Yes, I've added a message in `onRemove`

2024-06-12 13:26 UTC, OrangeRed requested changes

2024-06-12 13:26 UTC, OrangeRed commented on src/test/moves/magnet_rise.test.ts
> +    const finalHp = game.scene.getParty()[0].hp;
Use the `game.doAttack()` utility instead of manually handling CommandPhase like this.

You also don't need to use `game.runFrom(Phase).to(Phase)` anymore, the `game.to(Phase)` should be sufficient in 90% of use cases

2024-06-12 13:26 UTC, OrangeRed commented on src/field/pokemon.ts
> +      }
after some closer inspection I think this type check shouldn't be here or inside of`Pokemon.getAttackMoveEffectiveness()` but instead should be moved into `Pokemon.getAttackTypeEffectiveness()` because that gets executed inside of both `Pokemon.getAttackMoveEffectiveness()` and `Pokemon.apply()`

2024-06-12 13:27 UTC, OrangeRed commented on src/field/pokemon.ts
> +      }
I added another comment explaining.

2024-06-12 13:29 UTC, OrangeRed commented on src/data/move.ts
> +      !user.getTag(BattlerTagType.MAGNET_RISEN)),
I meant to use `Array.some(fn)` where the array is an array of BattlerTagTypes. It would look something like `[BattlerTagType.MAGNET_RISEN, ...].some(tag => user.getTag(tag))` 
You would have to figure out the boolean logic however so it still works the same way

2024-06-13 04:35 UTC, Frisk17 commented on src/field/pokemon.ts
> +      }
I've made the changes

2024-06-13 14:07 UTC, OrangeRed commented on src/field/pokemon.ts
> +      }
> I've made the changes

Can you resolve conversations that you finish.

2024-06-17 03:12 UTC, OrangeRed requested changes

2024-06-17 03:12 UTC, OrangeRed commented on src/data/move.ts
> +
Can you instead do `[ BattlerTagType.INGRAIN, BattlerTagType.IGNORE_FLYING, BattlerTagType.MAGNET_RISE ].some((tag) => !user.getTag(tag))` instead of making a separate function.
Just double check that the logic is still the same.

2024-06-17 10:27 UTC, Frisk17 commented on src/data/move.ts
> +
I've made the requested changes

2024-06-17 11:51 UTC, OrangeRed approved these changes

2024-06-17 11:52 UTC, OrangeRed commented
Fix the conflicts and someone can merge thid

2024-06-17 14:31 UTC, OrangeRed commented on src/field/pokemon.ts
> +    if (!!this.summonData && !!this.summonData.tags.find((tag) => tag instanceof TypeImmuneTag && tag.immuneType === moveType)) {
Can you just null coalesce via `this.summonData?.tags.find...`

2024-06-17 15:35 UTC, Greenlamp2 approved these changes

2024-06-17 15:35 UTC, merged