[QoL Balance] Shiny Chance from 1/2048 -> 1/1024, shiny charm adjustment
pagefaultgames/pokerogue pull request #2170
Opened 2024-06-13 08:53 UTC by damocleas

## What are the changes?
Changes the base Shiny Chance after discussion from 1/2048 -> 1/1024

## Why am I doing these changes?
Shinies are a part of the overall progression of the game for most circumstances. 
This is marked as a draft to create discussion and/or actually make sure I'm doing the right coding for this.

## What did change?
Changed two 32's to a 64 for shiny chance, and a 2 to a 1 for shiny charms as of now.
Expecting to have to do more as no one has corrected me.

### Screenshots/Videos

## How to test the changes?
Merge the PR with an offline version, and/or double check the code to make sure the right lines are adjusted.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-13 13:41 UTC, Tempo-anon commented on src/field/pokemon.ts
> +    const rand2 = Utils.binToDec(Utils.decToBin(this.id).substring(16, 64));
what are you doing here? You're getting a 48 bit number for rand2

2024-06-13 13:44 UTC, Tempo-anon commented on src/modifier/modifier.ts
> +    (args[0] as Utils.IntegerHolder).value *= Math.pow(2, 1 + this.getStackCount());
The previous shiny charm boosts were 8x, 16x, 32x for 1/2/3. Now the charm boosts are 4x, 8x, 16x. Not sure if you still intend on the first one to be more impactful than the second and third.

2024-06-13 13:45 UTC, Tempo-anon requested changes
I literally wrote the documentation on how this code works 😭

2024-06-14 15:02 UTC, bennybroseph commented
Why aren't tests passing for this change?

2024-08-05 04:53 UTC, closed without merging