[Localization] #1761 Korean trainer dialogue (Gym leader in Galar region)
pagefaultgames/pokerogue pull request #2171
Opened 2024-06-13 09:21 UTC by sodaMelon

[Localization] #1761 Korean trainer dialogue (Gym leader in Galar region)
## What are the changes?

Translating locales\ko\dialogue.ts into Korean.
This PR is added korean dialogue for **Gym leader in Galar region.** (8th Pokemon Games)

@sodaMelon @Ohmry @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.

## Why am I doing these changes?

Few trainers's dialogue have been translated into Korean yet.

## What did change?

I translated **Gym leader(in Galar, 8th pokemon)battles' dialogues.**

8세대 체육관 관장 다이얼로그를 번역했습니다.(차기 관장인 비트, 마리 포함)

말투 교정에는 정발판 8세대 소드/실드 참고했습니다.

8세대 사천왕(역할을 해주는 관장들)+챔피온 단델은 다음PR에 올릴게요!

### Screenshots/Videos

( very hard to meet them.... and it's dosen't matter)

## How to test the changes?

It seems there won't be much to test since it's just a translation of an existing .ts file. You can check it when you meet the respective trainers.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~~[ ] Are the changes visual?~~
  - ~~[ ] Have I provided screenshots/videos of the changes?~~

2024-06-13 09:29 UTC, sodaMelon commented
Just a moment

2024-06-13 09:31 UTC, sodaMelon reviewed
Maybe It will be okay. Please check their dialouges when you have free time

2024-06-13 10:19 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      3: "에헤헤!"
야청 웃음소리 틀렸다면 지적 부탁드려요

2024-06-13 10:19 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      2: "아하하! 내가 또 이긴 것 같네!",
멜론 웃음소리 틀렸으면 알려주세요🫠

2024-06-13 10:30 UTC, sodaMelon reviewed
just test comment

2024-06-13 10:30 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "충격과 공포를 전해드리겠습니다."
![1178374334_origin_time2die](https://github.com/pagefaultgames/pokerogue/assets/66295123/16bb0523-2171-49c0-978c-69a3f3a7e5fe)
Shock and Awe, losers! Shock and Awe
From Simson meme ( very famous)

2024-06-13 10:30 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "뜨거운 현장을 즐길 준비는 됐겠지! 스파이크 마을, it's time to rock!"
```suggestion
      1: "뜨거운 현장을 즐길 준비는 됐겠지! 스파이크 마을이여, IT'S TIME TO ROCK!"
```
원본 mosh pit은 훌리건 or 오타게 같은건데 완역힜습니다

2024-06-13 10:30 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +                    $그러니까 너의 팀을 기분 좋게 잔들게 해주겠어!`,
```suggestion
                    $그러니까 너의 팀을 기분 좋게 잠들게 해주겠어!`,
```
오타 수정

2024-06-14 02:32 UTC, returntoice requested changes
일부 맞춤법 등 수정해 보았습니다.

2024-06-14 02:32 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "똑똑한 네가 어떤 계획을 세우고 있던지, 나와 내 파트너가 가라앉혀줄테니까 문제 없어.",
```suggestion
      1: "똑똑한 네가 어떤 계획을 세우고 있든지, 나와 내 파트너가 가라앉혀줄 테니까 문제 없어.",
```

2024-06-14 02:32 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      3: "이건 내 포켓몬이 주는 작은 선물이야… 네가 잘 받아줘야해!"
```suggestion
      3: "이건 내 포켓몬이 주는 작은 선물이야… 네가 잘 받아줘야 해!"
```

2024-06-14 02:32 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "봐주지는 않을거란다!",
```suggestion
      1: "봐주지는 않을 거란다!",
```

2024-06-14 02:32 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "너… 꽤하는 구나?",
```suggestion
      1: "너… 꽤 하는구나?",
```

2024-06-14 02:32 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "소리를 지르니라 목이 가버렸군… 그렇지만 박진감 넘치는 배틀이었다!"
```suggestion
      1: "소리를 지르느라 목이 가버렸군… 그렇지만 박진감 넘치는 배틀이었다!"
```

2024-06-14 02:32 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "네가 방금 승부 전략에서 즐거웠기를."
```suggestion
      1: "우리의 배틀 방식을 즐겼길 바라."
```
조금 어색한 듯하여 고쳐 보았습니다.

2024-06-14 02:46 UTC, sodaMelon reviewed
@returntoice  hi, i applied your suggestion. it looks more clear. thanks

2024-06-14 02:48 UTC, sodaMelon reviewed
maybe i think it's ok for merge

2024-06-14 02:48 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "네가 방금 승부 전략에서 즐거웠기를."
> 조금 어색한 듯하여 고쳐 보았습니다.

감사합니다ㅋㅋㅋ 뭔가 적당한 단어가 생각이 안나더라구요
제안해주신 문장이 더 자연스러운거같아요

2024-06-14 04:48 UTC, malloc3141 commented
It looks good to me 👍 

제가 8세대를 안해서 본가와 비교는 못하지만 전반적으로 자연스러운 것 같습니다!

2024-06-14 05:44 UTC, sodaMelon commented
> It looks good to me 👍
> 
> 제가 8세대를 안해서 본가와 비교는 못하지만 전반적으로 자연스러운 것 같습니다!

thanks. please give "approve", too...

2024-06-14 07:36 UTC, malloc3141 approved these changes
Looks good to me 👍

2024-06-14 09:12 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "뜨거운 현장을 즐길 준비는 됐겠지! 스파이크 마을, it's time to rock!"
네! 두송(Piers)는 락스타 캐릭터인데 저 말은 그대로 적고+대문자로 적어야 샤우팅하는 기분이 나서~~ 저렇게 뒀습니다!

2024-06-14 09:14 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      2: "트레이닝이 제값을 하는 것 같네. 승부에 응해줘서 고마워!"
훈련도 좋지만.. 마리(Marnie)는 위의 두송과 같은 락스타 컨셉 캐릭터예요! 일부러 영어단어는 몇몇개 살려도 문장 길이에 큰 문제가 없어 보여서 그렇게 뒀어요.🍀 소리 내서 읽어 봤을 땐 큰 문제 없는 거 같은데. 문장이 많이 어색한가요?

2024-06-14 09:39 UTC, malloc3141 commented on src/locales/ko/dialogue.ts
> +      1: "뜨거운 현장을 즐길 준비는 됐겠지! 스파이크 마을, it's time to rock!"
음 뭔가 IT'S TIME TO ROCK! 같이 확실하게 컨셉임을 표현해주는것도 괜찮을 것 같아요! 근데 이건 진짜 사소한거라 사실 반영 안하셔도 괜찮습니다 :)

2024-06-14 09:40 UTC, malloc3141 commented on src/locales/ko/dialogue.ts
> +      2: "트레이닝이 제값을 하는 것 같네. 승부에 응해줘서 고마워!"
음 다시 보니까 그냥 둬도 될 것 같아요!

2024-06-14 13:42 UTC, Tempo-anon approved these changes

2024-06-14 13:42 UTC, merged