[Localization] Fix bouncy bubble description for es fr it ko zh
pagefaultgames/pokerogue pull request #2175
Opened 2024-06-13 14:24 UTC by Tempo-anon

## What are the changes?
Updated bouncy bubble description

## Why am I doing these changes?
It should say 100% of damage dealt as healing instead of 50%

## What did change?
Changed es, fr, it, ko, and both zh localizations for bouncy bubble. Let me know if I've severely butchered anything

### Screenshots/Videos
n/a

## How to test the changes?
Pull

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-13 14:43 UTC, flx-sta approved these changes
Apart from that 1 tiny comment duck-duck-go translator says its good

2024-06-13 14:43 UTC, flx-sta commented on src/locales/fr/move.ts
> +    effect: "Évoli frappe l’adversaire avec des bulles d’eau qu’il absorbe ensuite pour récupérer un nombre de PV égal à la des dégâts infligés à l’ennemi."
this one still contains the `Evoli` instead of a more generic word

2024-06-13 14:59 UTC, flx-sta requested changes

2024-06-13 14:59 UTC, flx-sta commented on src/locales/fr/move.ts
> +    effect: "Évoli frappe l’adversaire avec des bulles d’eau qu’il absorbe ensuite pour récupérer un nombre de PV égal aux dégâts infligés à l’ennemi."
```suggestion
    effect: "L’adversaire est frappé par des bulles d’eau qui sont ensuite absorbées pour récupérer un nombre de PV égal aux dégâts infligés à l’ennemi."
```

Also from swain but without the Evoli part

2024-06-13 17:22 UTC, jts04 commented on src/locales/ko/move.ts
> +    effect: "물덩어리를 부딪쳐서 공격한다. 물을 흡수하여 데미지의 절만큼 HP를 회복한다."
wrong change here.
original text is right.

2024-06-13 18:18 UTC, Tempo-anon commented on src/locales/ko/move.ts
> +    effect: "물덩어리를 부딪쳐서 공격한다. 물을 흡수하여 데미지의 절만큼 HP를 회복한다."
Bouncy bubbles heals 100% of the damage dealt in Pokerogue and generations 8 and 9

2024-06-13 19:46 UTC, Greenlamp2 approved these changes

2024-06-13 20:24 UTC, merged

2024-06-14 13:30 UTC, EnochG1 commented on src/locales/ko/move.ts
> +    effect: "물덩어리를 부딪쳐서 공격한다. 물을 흡수하여 데미지의 절만큼 HP를 회복한다."
There is no word '절만큼' in korean.
If you want to explain 100% percent of damage, you can fix it like this

```suggestion
    effect: "물덩어리를 부딪쳐서 공격한다. 물을 흡수하여 데미지만큼 HP를 회복한다."
```