Working on the move fling. Currently a work in progress.
pagefaultgames/pokerogue pull request #2200
Opened 2024-06-14 11:13 UTC by AyushBarik

## What are the changes?

The user can now utilize the move fling. 

## Why am I doing these changes?

It is an important move in the game.

No.

Greater diversity of available moves, which enhances user experience.

## What did change?

The move fling is now fully functional

### Screenshots/Videos
--work in progress--

## How to test the changes?

--work in progress--

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-14 11:16 UTC, hayuna commented
Could you update title of this PR?

[Move] Implement Fling

2024-06-15 20:37 UTC, Arxalc commented
I see why you included all the item names, but since most of them aren't currently in PokeRogue, I'd just comment them out and let someone else add them in once the item is implemented in the future.

You can completely get rid of evolutionary stones. Pokemon don't hold those.

2024-06-15 20:43 UTC, Arxalc commented on src/data/move.ts
> +    }
You can put this as an else at the end of your else-if statements since it's already checking through all the arrays.

2024-06-15 20:43 UTC, Arxalc commented on src/data/move.ts
> +import { BerryType } from "#enums/berry-type";
Instead of importing BerryType, maybe you can check `if (this.randomItem instanceof BerryModifier || arr10.includes(this.randomItem)` ?

2024-06-15 20:43 UTC, Arxalc commented on src/data/move.ts
> +
```suggestion
  } else if (arr130.includes(this.randomItem)) {
          power.value = 130;
  } else {
        power.value = 0;
        user.scene.queueMessage("No valid item found!");
        return false;
  } // else-if
      user.scene.removeModifier(randomHeldItemModifier, !user.isPlayer());
      user.scene.updateModifiers(user.isPlayer());
      return true;
} // if
```

2024-06-16 11:47 UTC, AyushBarik commented on src/data/move.ts
> +import { BerryType } from "#enums/berry-type";
That code works when I tried it however,

In line 2675 **const validHeldItems = heldItems.filter(item => allItems.includes(item.type.name.toLowerCase().replace(/_/g, " ")));**

I filter out all the non-flingable items. By not importing berries and not adding them in my array, the berries would get filtered out as non-flingable items. How do I deal with this? 

I could manually type in the different berry types into the array and we can avoid having to import berry-type.ts. Is that something I should do?

2024-06-16 17:09 UTC, AyushBarik commented
Changes made as per the Suggestions:
- Got rid of evolutionary items as flingable items
- heldItems check moved to the beginning of the function
- Dealt with berries without importing berry-type.ts

Changes not made: 
- I was suggested to move the validHeldItems check at the end of the else-if statements but I felt that may cause bugs so I have not implemented it for now

Additionally, as for commenting out unimplemented items from the list of flingable items - I am not sure which items have or have not been implemented. Perhaps someone more familiar with the game can change the arrays accordingly.

2024-06-17 14:43 UTC, Tempo-anon commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
class and apply need tsdoc

2024-06-17 14:47 UTC, Tempo-anon commented on src/data/move.ts
> +  getMyHeldItems(user: Pokemon): PokemonHeldItemModifier[] {
nit: not sure if this needs to be its own function if it'll only be used for this. You can probably just inline this, though I'm surprised there isn't one already

2024-06-17 15:36 UTC, AyushBarik reviewed
Implemented all feedback from Tempo-anon:
- tsdoc created for class and apply
- unnecessary comments removed
- getMyHeldItems removed as a function and made inline instead.

2024-06-17 17:52 UTC, Arxalc commented on src/data/move.ts
> +    }
Oh I didn't think clearly on this. The way you have it is fine.

2024-06-21 18:06 UTC, OrangeRed requested changes

2024-06-21 18:06 UTC, OrangeRed commented on src/data/move.ts
> +    const arr130i = ["Iron Ball"];
Instead of making huge arrays of item names like this wouldn't it be better to just add the flingPower / weight of the item onto that item's class (ModifierType)?

2024-06-21 18:06 UTC, OrangeRed commented on src/data/move.ts
> +    ) as PokemonHeldItemModifier[];
`(m as PokemonHeldItemModifier)` isn't necessary because typescript infers the type from `m instanceof PokemonHeldItemModifier`

2024-06-27 08:23 UTC, AyushBarik commented
https://github.com/pagefaultgames/pokerogue/assets/128145955/b37ce86b-6420-460a-8fbc-d031567b7017

Test that displays the functionality of fling as well as the case if none of the held items possessed by the Pokemon are flingable. (For testing purposes flame orb was made unflingable temporarily).

2024-06-27 08:30 UTC, AyushBarik commented
https://github.com/pagefaultgames/pokerogue/assets/128145955/7467c694-9ad9-4eb9-a1b2-e37ab9f9e569

Displays what happens if the user has no held items

2024-06-27 17:37 UTC, OrangeRed reviewed
Since you're validating against the names of items does this work correctly in different locales?

2024-06-27 17:37 UTC, OrangeRed commented on src/data/move.ts
> +    }
Is this necessary? Doesn't the game just show "But it failed" if you don't have a valid item?

2024-06-28 06:00 UTC, AyushBarik commented on src/data/move.ts
> +    }
Not necessary, I just thought it would be useful. The user might have held items, but might be wondering why fling failed. this message tells them that their items are not flingable.

2024-06-28 06:37 UTC, AyushBarik commented on src/data/move.ts
> +    }
"Since you're validating against the names of items does this work correctly in different locales?"

I tried running the game in other languages and fling does not seem to work... How do i fix this issue?

2024-07-30 21:34 UTC, Tempo-anon requested changes
This does not work since it's checking for hardcoded english names. Could we not update `modifier-type.ts` to include the relevant type and damage info while just having the special effects in the FlingAttr?

2024-09-17 16:19 UTC, closed without merging