Implement ability illusion
pagefaultgames/pokerogue pull request #2217
Opened 2024-06-14 19:22 UTC by PyGaVS

## What are the changes?

Adding illusion

## Why am I doing these changes?

Make ability illusion works so we can play Zoroark with full potential and make fusion with illusion

## What did change?

Added PreSummonAbAttr class as ability attribute.
A pokemon with illusion create an illusion from the last pokemon of the trainer's party.
If we encounter a wild Zoroark he will use the illusion of Entei, Suicune or Raiku like in the original game. We can change that in the method generateIllusion() in src/field/pokemon.ts.
The class pokemon has a new attribute illusion. 
A shiny Zoroark will create a shiny illusion.
A non shiny Zoroark will create a non-shiny illusion.
This doesn't affect the luck of course, it's just visual.
A pokemon with illusion can use illusion one time per battle like in the original game.
After a battle, the pokemon can use illusion again.

### Screenshots/Videos

https://discord.com/channels/1125469663833370665/1176874654015684739/1251234015760089159
https://discord.com/channels/1125469663833370665/1176874654015684739/1251234045204103238
https://discord.com/channels/1125469663833370665/1176874654015684739/1251234047104127039

## How to test the changes?

I played Zoroark and override the enemy pokemon with Zoroark so we can see him using illusion of Raikou Suicune Entei
I used illusion on a fusion and with a fusion
I tried to switch with the illusion

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-14 21:30 UTC, Tempo-anon commented on src/data/ability.ts
> +   * @param {...any} args - Additional arguments.
If args is not used you can just write `n/a`

2024-06-14 21:30 UTC, Tempo-anon commented on src/data/ability.ts
> +   * Apply a new illusion after each turn if the illusion is available
I thought illusion only works when sent out

2024-06-14 21:30 UTC, Tempo-anon commented on src/data/ability.ts
> +    if (hitResult > 4) {
This isn't really easily understood. I'd prefer if you had a list of HitResult's so someone doesn't have to check HitResult. Just check if the hitResult is found in [HitResult.EFFECTIVE, HitResult.SUPER_EFFECTIVE, HitResult.NOT_VERY_EFFECTIVE, HitResult.ONE_HIT_KO]

2024-06-14 21:30 UTC, Tempo-anon commented on src/data/ability.ts
> +    pokemon.scene.queueMessage(getPokemonMessage(pokemon, "'s illusion wore off!"));
should probably be localized but localization should go in a seperate PR

2024-06-14 21:30 UTC, Tempo-anon commented on src/data/ability.ts
> +export class IllusionAfterBattle extends PostBattleAbAttr {
This is technically a buff to the ability right? Since most other on summon abilities do not reapply themselves after battle

2024-06-14 21:30 UTC, Tempo-anon commented on src/data/ability.ts
> +   * So the pokemon can use 1 illusion per battle.
Is Illusion once per battle? I thought it applied each time the Pokemon was sent out

2024-06-14 21:30 UTC, Tempo-anon commented on src/data/ability.ts
> +      //Illusion is available again after a battle again after a battle
nit: repeated `after a battle`

2024-06-14 21:30 UTC, Tempo-anon commented on src/enums/battler-tag-type.ts
> +  ICE_FACE = "ICE_FACE",
don't think the comma is needed on the last item

2024-06-14 21:30 UTC, Tempo-anon commented on src/field/pokemon.ts
> +  generateIllusion(pokemon: Pokemon, party: Pokemon[]): void {
should also add documentation to this function

2024-06-14 21:30 UTC, Tempo-anon commented on src/field/pokemon.ts
> +  public illusion: {active: boolean, available: boolean, species?: PokemonSpecies, name?: string, fusionSpecies?: PokemonSpecies};
Since this is basically a new struct I think it'd be good to document this as well

2024-06-14 21:30 UTC, Tempo-anon commented on src/field/pokemon.ts
> +        name: pokemon.name
is the name still `pokemon.name` instead of `lastPokemon.name`? Oh nvm I see you're using this to store the illusion pokemon's original name

2024-06-14 21:30 UTC, Tempo-anon commented on src/field/pokemon.ts
> +      const availables = [Species.ENTEI, Species.RAIKOU, Species.SUICUNE];
Bulbapedia says they disguise themselves as pokemon in the same area but that seems like it'd be more complicated to implement. I'm okay with this for now but Zoroarks don't appear in any of the same biomes as the legendary dogs so it'll be pretty obvious to the player

2024-06-14 21:30 UTC, Tempo-anon commented on src/field/pokemon.ts
> +      const randomIllusion: PokemonSpecies = getPokemonSpecies(availables[Math.floor(Math.random()*3)]);
we have randInt and randSeedInt functions for generating random numbers, probably shouldn't be using Math.random

2024-06-14 21:36 UTC, PyGaVS commented on src/data/ability.ts
> +   * Apply a new illusion after each turn if the illusion is available
The PostTurnAbAttr allow Zoroark to update his illusion when the last pokemon of the party is changed

2024-06-14 21:43 UTC, PyGaVS commented on src/data/ability.ts
> +export class IllusionAfterBattle extends PostBattleAbAttr {
It's more logical to recreate the illusion for me, but we can update that easily if needed

2024-06-14 21:43 UTC, PyGaVS commented on src/field/pokemon.ts
> +  generateIllusion(pokemon: Pokemon, party: Pokemon[]): void {
ok i'll add

2024-06-14 21:49 UTC, PyGaVS commented on src/field/pokemon.ts
> +      const availables = [Species.ENTEI, Species.RAIKOU, Species.SUICUNE];
Yes it's more complicated we can add this later, but in the original game Zoroark use the illusion of the legendary dogs even if we know it is not a legendary dog it's an easter egg. But we can add the feature for illusion as pokemon in the same area in the future and keeps the legendary dog illusion for the bosses. But this version is still better than unimplemented.

2024-06-15 12:57 UTC, DayKev commented
cf https://bulbapedia.bulbagarden.net/wiki/Illusion_(Ability)

A (mostly?) exhaustive list of things that could be tested, from the Bulbapedia page.

* [x] Illusion uses the appearance of the last conscious Pokémon in the party (ignoring itself), including:
  * [x] Species
  * [ ] Form
    - Zorua currently only uses the base form of the disguise target and not its actual form
  * [ ] Shininess
    - Zorua currently uses its own shininess to determine the disguise shininess when it should be looking at the disguise target's shininess
  * [x] Nickname (N/A)
  * [ ] Pokeball
    - Currently only a normal Pokeball is used
  * [ ] Gender
    - Currently Zorua's gender is used instead of the disguise target's
* [x] Attract will use the Pokémon's actual gender
  - Will probably require re-testing once the gender copying is fixed
* [ ] The type will always be displayed as the Pokémon it is disguised as, even when affected by Soak etc
  - Currently Soak (and probably other type changing moves) change the displayed Type
* [ ] The illusion will disappear if:
  * [ ] The Pokémon has its ability changed
    - Did not test
  * [ ] The Pokémon has its ability suppressed (ie: Neutralizing Gas)
    - Currently NG does not disable the disguise
  * [x] The Pokémon takes damage from a damaging move
* [x] Indirect damage will not break the illusion:
  * [ ] Life Orb (not yet implemented)
  * [x] Weather (such as Sandstorm)
  * [x] Status conditions
  * [x] Recoil
* [x] The illusion will break after the first hit of a multi-hit move
* [ ] Using a Z-Move will break the illusion before the move executes (Z-Moves not yet implemented)
* [x] Role Play will fail if the target is a Pokémon with Illusion
* [x] Skill Swap will fail if either Pokémon has Illusion
* [x] Illusion cannot be copied by:
  * [x] Trace
  * [x] Power of Alchemy
  * [x] Receiver
* [x] If copied via Imposter or Transform, it will not activate
  * However, the opponent's type will not be updated on the UI until the next turn (but that might be an unrelated bug in Transform/Imposter)
* [ ] Pokémon cannot transform into a Pokémon that is disguised by Illusion
  - Currently Pokémon can transform into a disguised Zorua
* [ ] Pokémon that are disguised by Illusion cannot Transform
  - Currently Pokémon disguised with Illusion can still Transform
* [ ] Wild Zoroark will be disguised as other wild Pokémon from the area
  - Already commented on in above PR comments
* [ ] If the disguised Pokémon is currently disguised as Ogerpon, terastallization will break the disguise
  - Did not test
* [ ] Illusion will not activate if the last conscious Pokémon is a Terastallized Ogerpon or Terapagos
  - Did not test

2024-07-03 01:20 UTC, PyGaVS commented
I've done a lot of updates for the illusion : 

-Illusion uses the appearance of the last conscious Pokémon in the party (ignoring itself), including : 
Species, Form, Shininess, Pokeball, Gender
-The type will always be displayed as the Pokémon it is disguised as, even when affected by Soak etc
-The illusion will disappear if the Pokemon has its ability changed
-Pokemon cannot transform into a Pokémon that is disguised by Illusion
-Pokémon that are disguised by Illusion cannot Transform
-Wild Zoroark will be disguised as other wild Pokémon from the area. Depending on Zorua or Zoroark level the illusion will be evolvedd or not.
-Illusion will not activate if the last conscious Pokémon is a Terastallized Ogerpon or Terapagos.

https://discord.com/channels/1125469663833370665/1176874654015684739/1257835032647831682
https://discord.com/channels/1125469663833370665/1176874654015684739/1257864381937619045
https://discord.com/channels/1125469663833370665/1176874654015684739/1257865512801538059

I've done a lot of test to see most of the possibility with illusion. And illusion is working well for me. If you find any bug, please tell me how we can create the bug so i can correct the bug for the futur merge.

2024-07-03 14:00 UTC, DayKev commented
Testing the stuff from my previous post that wasn't in at that time:

* [x] Illusion uses the appearance of the last conscious Pokémon in the party (ignoring itself), including:
  * [x] Form
  * [x] Shininess
  * [x] Pokeball
  * [x] Gender
* [x] Attract will use the Pokémon's actual gender
* [x] The type will always be displayed as the Pokémon it is disguised as, even when affected by Soak etc
* [x] The illusion will disappear if:
  * [x] The Pokémon has its ability changed
  * [ ] The Pokémon has its ability suppressed (ie: Neutralizing Gas)
    - NG still does not disable the disguise
* [x] Pokémon cannot transform into a Pokémon that is disguised by Illusion
* [x] Pokémon that are disguised by Illusion cannot Transform
* [x] Wild Zoroark will be disguised as other wild Pokémon from the area
  - Seems to be working, but one of the times it disguised as a Sableye on wave 1 in the Town biome and that Pokémon shouldn't normally spawn in that biome afaict

Seems like everything except ability suppression is working (excluding interactions with un-implemented stuff which I won't worry about now).

2024-07-04 13:53 UTC, PyGaVS commented
Now the pokemon can't do Illusion under neutralizing gas :
https://discord.com/channels/1125469663833370665/1176874654015684739/1258418548074745958

2024-07-05 19:57 UTC, OrangeRed requested changes

2024-07-05 19:57 UTC, OrangeRed commented on src/data/ability.ts
> +    for (pokemon of pokemon.scene.getField(true)) {
Remove these `console.log()` statements

2024-07-05 19:57 UTC, OrangeRed commented on src/data/ability.ts
> +}
if you're using `async / await` you can remove the Promise return statement, which then lets you remove the `Promise.then()` when you invoke these functions with `applyPreSummonAbAttr()`

2024-07-05 19:57 UTC, OrangeRed commented on src/phases.ts
> +            });
you don't need this `Promise.then()` because the underlying PreSummon isn't a promise

2024-07-05 19:57 UTC, OrangeRed commented on src/phases.ts
> +    applyPreSummonAbAttrs(PreSummonAbAttr, pokemon, party).then(() => this.preSummon());
Same here, don't treat the applyPreSummon like a Promise when it isn't.

2024-07-05 19:57 UTC, OrangeRed commented on src/phases.ts
> +    const party: Pokemon[] = pokemon.isPlayer() ? this.scene.getParty().filter(p => p.isAllowedInBattle()) : this.scene.getEnemyParty().filter(p => p.isAllowedInBattle());
Rather than having two filters inside the ternary instead apply the filter on the outside of the ternary
`(pokemon.isPLayer() ? getParty() : getEnemyParty()).filter(...)`

2024-07-05 19:57 UTC, OrangeRed commented on src/field/pokemon.ts
> +      }
Can you clean up this conditional by checking both Ogrepon and Terapagos at the same time so you're not repeating yourself twice?

2024-07-05 19:57 UTC, OrangeRed commented on src/field/pokemon.ts
> +
Why are you turning into these specific pokemon?

2024-07-05 19:57 UTC, OrangeRed commented on src/field/pokemon.ts
> +            }
Isn't this conditional backwards?

2024-07-05 19:57 UTC, OrangeRed commented on src/field/pokemon.ts
> +      }
Rather than making unnecessary copies of the overwriting availables with copies of arrays just mutate directly using `Array.push()`

2024-07-05 19:57 UTC, OrangeRed commented on src/field/pokemon.ts
> +  }
Can you invert this and the function before this so that you return false early rather than nesting

2024-07-05 19:59 UTC, OrangeRed commented on src/data/ability.ts
> +    for (pokemon of pokemon.scene.getField(true)) {
Also are you sure you want to be overwriting the `pokemon: Pokemon` param with this for loop?

2024-07-06 09:25 UTC, EnochG1 requested changes
Please do not hard-code messages, but localize.

2024-07-06 09:25 UTC, EnochG1 commented on src/data/ability.ts
> +        pokemon.scene.queueMessage(getPokemonMessage(pokemon, "'s illusion wore off!"));
Need to localize.

2024-07-06 09:25 UTC, EnochG1 commented on src/data/move.ts
> +      (this.selfTarget ? user : target).scene.queueMessage(getPokemonMessage((this.selfTarget ? user : target), "'s illusion wore off!"));
Need to localize.

2024-07-06 09:25 UTC, EnochG1 commented on src/data/move.ts
> +        user.scene.queueMessage("But it failed!");
```suggestion
        user.scene.queueMessage(i18next.t("battle:attackFailed"));
```
Need to localize and code already exists.

2024-07-06 09:25 UTC, EnochG1 commented on src/data/ability.ts
> +    pokemon.scene.queueMessage(getPokemonMessage(pokemon, "'s illusion wore off!"));
Need to localize.

2024-07-08 17:43 UTC, CodeTappert commented on src/locales/de/ability-trigger.ts
> +  "illusion": "{{pokemonName}}'s illusion wore off!",
```suggestion
  "illusion": "Das Trugbild von {{pokemonName}} verschwindet!",
```

2024-07-08 17:44 UTC, Adri1 requested changes
Corrected French

2024-07-08 17:44 UTC, Adri1 commented on src/locales/fr/ability-trigger.ts
> +  "illusion": "L'Illusion de {{pokemonName}} se brise !",
```suggestion
  "illusion": "L’illusion de {{pokemonName}} se brise !",
```

2024-07-08 17:44 UTC, josericardo-fo commented on src/locales/pt_BR/ability-trigger.ts
> +  "illusion": "{{pokemonName}}'s illusion wore off!",
```suggestion
  "illusion": "A ilusão de {{pokemonName}} acabou!",
```

2024-07-08 18:12 UTC, RimKnight commented on src/locales/zh_TW/ability-trigger.ts
> +  "illusion": "{{pokemonName}}'s illusion wore off!",
```suggestion
  "illusion": "{{pokemonName}}造成的\n幻覺解除了！",
```

2024-07-08 18:45 UTC, Adri1 approved these changes

2024-07-08 23:24 UTC, EnochG1 reviewed
Korean translation

+ minor issue.
IMO, "illusion" is ambiguous locale key because it is not seem to be 'apply' or 'on' event.
Why don't you make it more clear(by attaching a verb or something)

2024-07-08 23:24 UTC, EnochG1 commented on src/locales/ko/ability-trigger.ts
> +  "illusion": "{{pokemonName}}'s illusion wore off!",
```suggestion
  "illusion": "{{pokemonName}}의\n일루전이 풀렸다!",
```

2024-07-09 08:59 UTC, EnochG1 approved these changes
LGTM!

2024-07-09 14:26 UTC, NicusPulcis commented
@PyGaVS added the italian localization

2024-07-09 14:27 UTC, NicusPulcis commented
@PyGaVS added the italian localization

2024-07-09 19:36 UTC, Arxxer reviewed
es-es localization done

2024-07-09 19:36 UTC, Arxxer commented on src/locales/es/ability-trigger.ts
>  } as const;
```suggestion
  "trace": "{{pokemonName}} rastreó {{abilityName}}\nde {{targetName}}!",
  "windPowerCharged": "¡{{pokemonName}} se ha cargado de electricidad gracias a {{moveName}}!",
  "quickDraw": "¡Gracias a la Garra Rápida, {{pokemonName}} puede tener prioridad!",
  "illusionBreak": "¡La ilusión de {{pokemonName}} se ha desvanecido!",
} as const;
```

2024-07-10 16:44 UTC, PyGaVS commented
> es-es localization done

yes

2024-07-10 16:47 UTC, OrangeRed requested changes
1) Don't get the party data before passing it as a parameter into `applyAbAttrs()`. Instead get that data inside the specific ability that needs it.
2) You also didn't resolve / answer some of the other comments that I gave you earlier.

2024-07-10 16:47 UTC, OrangeRed commented on src/data/ability.ts
> +
Is there a reason to add `party` as a parameter here and in `applyPostBattleAbAttrs()` when you can easily get it from `pokemon.scene.getParty()` or `pokemon.scene.getEnemyParty()`?

2024-07-10 16:47 UTC, OrangeRed commented on src/data/ability.ts
> +      .bypassFaint(),
nitpick but put non-conditionals before conditionals

2024-07-10 16:47 UTC, OrangeRed commented on src/data/move.ts
>      user.scene.queueMessage("The " + getPokemonMessage((this.selfTarget ? user : target), ` acquired\n${allAbilities[this.ability].name}!`));
Instead of doing `this.selfTarget ? user : target` like four different times just make a variable that holds that value

2024-07-10 16:56 UTC, PyGaVS commented on src/field/pokemon.ts
> +
They are the pokemon of the abyss biome.

2024-07-10 16:56 UTC, PyGaVS commented on src/field/pokemon.ts
> +    } else if (!ignoreOverride && this.summonData?.gender !== undefined) {
Sometime we want the gender of the illusion (in battleInfo for example), and sometime we want the gender of Zoroark not the illusion (in summary for example), even if the illusion is active we still want to get the infos about Zoroark.

2024-07-10 17:00 UTC, PyGaVS commented on src/data/ability.ts
> +
Oh my bad

2024-07-10 17:00 UTC, PyGaVS commented on src/data/ability.ts
> +      .bypassFaint(),
ok

2024-07-10 17:01 UTC, PyGaVS commented on src/data/move.ts
>      user.scene.queueMessage("The " + getPokemonMessage((this.selfTarget ? user : target), ` acquired\n${allAbilities[this.ability].name}!`));
yes i hesitated

2024-07-11 17:16 UTC, OrangeRed commented on src/field/pokemon.ts
> +
> They are the pokemon of the abyss biome.

If that is the case why not just use the data inside of biomePokemonPools directly instead of hardcoding values?

2024-07-11 18:35 UTC, OrangeRed requested changes

2024-07-11 18:35 UTC, OrangeRed commented on src/field/pokemon.ts
> +    } else if (!ignoreOverride && this.summonData?.gender !== undefined) {
If that is the case can you change this variable to be something like `useIllusion` and add jsdoc everywhere you added this parameter

2024-07-11 18:35 UTC, OrangeRed commented on src/data/ability.ts
> +
Can you move this class closer to where it's being used? 
That is to say move it closer to where all the PreSummonAbAttrs are located

2024-07-11 18:35 UTC, OrangeRed commented on src/data/ability.ts
> +  }
Can you remove `Promise<boolean>` in all places that don't return a promise.

2024-07-11 18:35 UTC, OrangeRed commented on src/phases.ts
> +            });
`applyPreSummonAbAttrs` only returns a Promise when the underlying ability attributes return a Promise, and since none of the illusion attributes return a Promise `applyPreSummonAbAttrs` doesn't need to be treated as one.

2024-07-11 18:35 UTC, OrangeRed commented on src/data/ability.ts
> +
Did you implement this? I still see places where you're passing the party as a parameter.

2024-07-11 18:35 UTC, OrangeRed commented on src/data/move.ts
> +    user.scene.queueMessage("The " + getPokemonMessage(pokemon, ` acquired\n${allAbilities[this.ability].name}!`));
Do you need to access `allAbilities` when you can use the pokemon's ability that you just changed?

2024-07-11 19:01 UTC, PyGaVS commented on src/data/ability.ts
> +
Ok

2024-07-11 19:04 UTC, PyGaVS commented on src/data/ability.ts
> +  }
Yes, other method in these AbAttr classes also have it we might need to correct it in the future

2024-07-11 19:10 UTC, PyGaVS commented on src/phases.ts
> +            });
I already tested it if i don't put .then() this will not work because inside the function, the function `applyAbAttrsInternal` is a promise

2024-07-11 19:12 UTC, PyGaVS commented on src/field/pokemon.ts
> +    } else if (!ignoreOverride && this.summonData?.gender !== undefined) {
ok

2024-07-11 19:17 UTC, PyGaVS commented on src/data/move.ts
> +    user.scene.queueMessage("The " + getPokemonMessage(pokemon, ` acquired\n${allAbilities[this.ability].name}!`));
This is note my code, there is maybe a reason behind it, do i still need to change it ? This might create some bug

2024-07-11 19:34 UTC, PyGaVS commented on src/data/ability.ts
> +
i should have implemented this i will check where i missed the parameter

2024-07-31 17:55 UTC, flx-sta commented on package-lock.json
why did it touch the package-lock.json? this shouldn't happen

2024-07-31 17:55 UTC, flx-sta commented on public/images/items.json
How is this noise produced?

2024-07-31 17:55 UTC, flx-sta commented on src/data/ability.ts
> -
NIT: why remove this new line?

2024-07-31 17:55 UTC, flx-sta commented on src/data/ability.ts
> +    pokemon.scene.getField(true).filter(p => p !== pokemon).map(p => {
does `p => p !== pokemon` work in this case? I guess because they are references it does, right?

2024-07-31 17:55 UTC, flx-sta commented on src/data/ability.ts
> +    if (hitResult > 4) {
You ignored @Tempo-anon s improvement request here

2024-07-31 19:07 UTC, PyGaVS commented on src/data/ability.ts
> -
not intentional

2024-07-31 19:08 UTC, PyGaVS commented on package-lock.json
there is no changes inside

2024-07-31 19:09 UTC, closed without merging