[Bug]: fix dark aura and fairy aura not applying to moves
pagefaultgames/pokerogue pull request #2246
Opened 2024-06-15 05:11 UTC by OrangeRed

## What are the changes?
Fix Dark Aura and Fairy Aura not applying a damage bonus

## Why am I doing these changes?
Dark Aura and Fairy Aura don't apply a damage bonus when they should

## What did change?
Find a pokemon with an aura on the field and apply the ability to the move

## How to test the changes?
Add overrides for `Abilities.DARK_AURA` and without and see the damage difference
I can write e2e tests if necessary

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

2024-06-15 08:30 UTC, torranx commented on src/field/pokemon.ts
> +      }
wont this be enough? 

```suggestion
      this.scene.getField(true).map(p => applyPreAttackAbAttrs(FieldVariableMovePowerAbAttr, p, this, move, power));
```

2024-06-15 13:17 UTC, OrangeRed commented on src/field/pokemon.ts
> +      }
Doing this would make the damage bonus from the ability apply for every pokemon on the field that has the aura ability.
If two pokemon have dark_aura then the damage bonus would apply twice. I didn't think that was desirable behavior so I stop after the first is found.

2024-06-15 13:22 UTC, torranx commented on src/field/pokemon.ts
> +      }
> Doing this would make the damage bonus from the ability apply for every pokemon on the field that has the aura ability. If two pokemon on the field have dark_aura then the damage bonus would apply twice. I didn't think that was desirable behavior so I stop after the first is found.

i see, i did not think of that. nice catch! but why are you passing the same pokemon on the `applyPreAttackAbAttrs`?

2024-06-15 13:30 UTC, OrangeRed commented on src/field/pokemon.ts
> +      }
it doesn't matter which you pass in as the second 'defender' pokemon since `FieldVariableMovePowerAbAttr` doesn't use the defender at all. Ideally in the future we would get rid of this unnecessary variable passing but there is a PR blocking me from doing that

2024-06-15 13:51 UTC, torranx commented on src/field/pokemon.ts
> +      }
gotcha, consider this resolved, thanks!

2024-06-15 13:53 UTC, torranx approved these changes
lgtm

2024-06-15 15:43 UTC, XGSleepWalker requested changes

2024-06-15 15:43 UTC, XGSleepWalker commented on src/field/pokemon.ts
> +      if (fieldAuraPokemon) {
What happens if there's a Dark Aura and Fairy Aura in the field at the same time? Won't just one of them apply?

2024-06-15 15:49 UTC, OrangeRed commented on src/field/pokemon.ts
> +      if (fieldAuraPokemon) {
if there are two different auras there is no way for them to apply to the same move?
since they don't have overlapping conditions.
```ts
// boostedType is Type.DARK for dark_aura and is Type.FAIRY for fairy_aura
super((pokemon, defender, move) => move.type === boostedType, powerMultiplier || 1.5);
```

2024-06-17 16:50 UTC, OrangeRed commented
I was having issues where using the `applyPreAttackAbAttr()` method would activate both a dark aura and a fairy aura if a pokemon had both even if a different pokemon had already activated one of the auras.

Using `applyPreAttackAbAttr()` this would happen:
PokemonA: Dark Aura only
PokemonB: Dark Aura + Fairy Aura
Result -> the move's power would get boosted twice by Dark Aura

So I had to be more granular and use the AbAttr's `applyPreAttack()` directly

2024-06-17 16:58 UTC, torranx commented on src/field/pokemon.ts
> +          .map((p) => p.getAbilityAttrs(FieldVariableMovePowerAbAttr) as FieldVariableMovePowerAbAttr[])
can we change this to `FieldMoveTypePowerBoostAbAttr` instead? since only `FieldMoveTypePowerBoostAbAttr` extends `FieldVariableMovePowerAbAttr`. this would also "isolate" Dark/Fairy Aura

changed it on my PR https://github.com/pagefaultgames/pokerogue/pull/2268/files#diff-1867e67cee517f3348c17ed44e0f02a45a23e59575f38b6e15aacf194768d6dbR1755

2024-06-17 17:06 UTC, OrangeRed commented on src/field/pokemon.ts
> +          .map((p) => p.getAbilityAttrs(FieldVariableMovePowerAbAttr) as FieldVariableMovePowerAbAttr[])
done

2024-06-17 17:08 UTC, torranx approved these changes

2024-06-17 19:38 UTC, XGSleepWalker approved these changes

2024-06-17 19:52 UTC, merged