[Ability] implemented aura break + fairy aura and dark aura fix from OrangeRed
pagefaultgames/pokerogue pull request #2252
Opened 2024-06-15 09:20 UTC by newmattock

## What are the changes?

Added functionality to make the Aura Break ability work. I also added the changes from #2246 which are needed in order to make this ability work. Aura Break reverses the effect of the Fairy Aura and Dark Aura abilities, lowering the damage of either fairy or dark moves by 25% depending on which ability the opposing pokemon possesses.
## Why am I doing these changes?

The changes in #2246 are vital to the function of this PR and are the main inspiration behind this PR. The bug previously made implementing this ability difficult, as the effect of fairy aura and dark aura was not clear.

## What did change?

Before this PR, Aura Break, Fairy Aura, and Dark Aura were not functional. The lack of functionality in Fairy Aura and Dark Aura was due to a bug, and I added the functionality for Aura Break. 
### Screenshots/Videos

With Aura Break

https://github.com/pagefaultgames/pokerogue/assets/152253273/fcee427c-7753-4f0e-9e95-920175365152

Without Aura Break

https://github.com/pagefaultgames/pokerogue/assets/152253273/a955a4d2-f89e-4e1e-8f69-738a467d3957

With Aura Break

https://github.com/pagefaultgames/pokerogue/assets/152253273/324fc6e6-87f8-4fc7-a6ae-c34635cb90ac

Without Aura Break

https://github.com/pagefaultgames/pokerogue/assets/152253273/e2972e9c-f5f5-426c-bfac-0a29e86236fd

## How to test the changes?

I tested using Zygarde with Aura Break against a Xerneas with Fairy Aura or a Yveltal with Dark Aura.

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-15 10:16 UTC, Greenlamp2 commented
Could you write unit test please ? this would help a lot ! thanks

2024-06-15 10:32 UTC, newmattock commented
> Could you write unit test please ? this would help a lot ! thanks

i'll get on it!

2024-06-15 12:40 UTC, torranx commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 3/4),
why are you adding the `FieldMoveTypePowerBoostAbAttr`? doesnt this multiply the damage of the move?
also i believe the way you implemented it wont work on double battles

2024-06-15 13:13 UTC, newmattock commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 3/4),
It does multiply the damage of the move, but since I am multiplying the damage by a fraction it ends up lowering the damage. 

I'll test with double battles!

2024-06-15 13:25 UTC, torranx commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 3/4),
> It does multiply the damage of the move, but since I am multiplying the damage by a 3/4 or .75 it ends up lowering the damage.

But isnt it just offsetting the boost given by Dark/Fairy Aura instead of inverting the boost?

2024-06-15 13:33 UTC, OrangeRed commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 3/4),
> But isnt it just offsetting the boost given by Dark/Fairy Aura instead of inverting the boost?

This is exactly what this ability is doing. 
The conditions also only check for the main ability not if the pokemon has a passive.

I would recommend you use `FieldMovePowerBoostAbAttr` instead and pass in a more comprehensive condition rather than using the same class as fairy aura and dark aura

2024-06-16 04:40 UTC, newmattock commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 3/4),
I did a bit more testing, and it seems like passive detection is working. Here are a few more videos showing the results of the testing I did. However, the ability still only offsets the damage as you've mentioned, but im working on fixing this!

Without Aura Break
https://github.com/pagefaultgames/pokerogue/assets/152253273/3a11fd43-416c-4d98-95ac-152db4662ce2

With Aura Break
https://github.com/pagefaultgames/pokerogue/assets/152253273/a04a2532-0170-4ec0-ac73-3cd70e497f17

2024-06-16 04:45 UTC, newmattock commented
Without Aura Break
https://github.com/pagefaultgames/pokerogue/assets/152253273/095516a2-b4a0-4052-a83a-9cc85bee22a6

With Aura Break
https://github.com/pagefaultgames/pokerogue/assets/152253273/5cb81e02-3aed-4bb2-b7e5-56c1171fd81e

2024-06-16 12:30 UTC, torranx requested changes

2024-06-16 12:30 UTC, torranx commented on src/test/abilities/aura_break.test.ts
> +    expect(damage).not.toBe(undefined);
this does not actually test if it reverses the effect of fairy aura. you need to at least check the damage dealt and compare to the base power of the move, or something else that would show the actual reversal

2024-06-16 12:30 UTC, torranx commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMovePowerBoostAbAttr, (user: Pokemon, target: Pokemon, move: Move) => move.type === Type.FAIRY, 9/15),
why 9/15? i think the net decrease of power should be 25%

2024-06-16 12:37 UTC, newmattock commented on src/test/abilities/aura_break.test.ts
> +    expect(damage).not.toBe(undefined);
it's just a placeholder for the moment, if you have any suggestions for testing I'd appreciate it though!

2024-06-16 12:43 UTC, torranx commented on src/test/abilities/aura_break.test.ts
> +    expect(damage).not.toBe(undefined);
i mean Greenlamp specifically asked for unit tests so your PR should include it and not just a placeholder. I've only written a few tests so far, I used the existing tests as reference but your unit tests should actually test what you are describing

2024-06-16 12:44 UTC, newmattock commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMovePowerBoostAbAttr, (user: Pokemon, target: Pokemon, move: Move) => move.type === Type.FAIRY, 9/15),
since 3/4 or .75 was only offsetting the damage, I used 19/15 or .75 * .75, which should offset the power of the original ability and apply the 25% damage decrease as well. I'm not sure any of this is correct, so feel free to correct / help me!

2024-06-16 12:51 UTC, newmattock commented on src/test/abilities/aura_break.test.ts
> +    expect(damage).not.toBe(undefined);
i'll remove it for now!

2024-06-16 14:20 UTC, OrangeRed commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMovePowerBoostAbAttr, (user: Pokemon, target: Pokemon, move: Move) => move.type === Type.FAIRY, 9/15),
0.75 * 0.75 (3/4 * 3/4) = 9/16 is it not?

2024-06-16 23:42 UTC, newmattock commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMovePowerBoostAbAttr, (user: Pokemon, target: Pokemon, move: Move) => move.type === Type.FAIRY, 9/15),
thank you! i'll make a quick fix for this.

2024-06-17 20:13 UTC, OrangeRed commented
@newmattock #2246 was merged in, check if that implementation requires you to make changes somewhere.

2024-06-17 21:26 UTC, newmattock commented
working on this more today!

2024-06-18 00:17 UTC, OrangeRed requested changes

2024-06-18 00:17 UTC, OrangeRed commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 9 / 16),
What if the target has these abilities as a passive?

2024-06-19 09:34 UTC, newmattock commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 9 / 16),
I've done testing and it seems like it works with both the main ability and the passive.


https://github.com/pagefaultgames/pokerogue/assets/152253273/83beb0be-d5a3-4279-b645-b7306904861d



https://github.com/pagefaultgames/pokerogue/assets/152253273/99ec8483-0a5f-49ff-8858-8a6d35202582


https://github.com/pagefaultgames/pokerogue/assets/152253273/85d8e63c-3ba6-4ce6-9210-fca1f007d74d

Working on a unit test!

2024-06-19 14:18 UTC, OrangeRed commented on src/data/ability.ts
> +      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 9 / 16),
You're right I forgot that `Pokemon.hasAbility()` checks for both the ability and passive. `Pokemon.getAbility()` doesn't touch the passive so that was the source my confusion.

2024-06-21 17:51 UTC, OrangeRed approved these changes

2024-06-21 20:22 UTC, newmattock commented
> Could you write unit test please ? this would help a lot ! thanks

I finally added unit tests! sorry for the wait!

2024-06-21 21:14 UTC, torranx requested changes

2024-06-21 21:14 UTC, torranx commented on src/test/abilities/aura_break.test.ts
> +    expect(appliedPower).lessThan(basePower);
since youre mocking the power, can we use instead use `toBe` or `equal`, the amount would be the net basePower instead,

2024-06-21 21:14 UTC, torranx commented on src/test/abilities/aura_break.test.ts
> +
nit: remove extra new line

2024-06-21 21:14 UTC, torranx commented on src/test/abilities/aura_break.test.ts
> +    expect(appliedPower).lessThan(basePower);
same comment as above

2024-06-21 21:14 UTC, torranx commented on src/test/abilities/aura_break.test.ts
> +    await game.phaseInterceptor.to(TurnEndPhase);
can probably use MoveEffectPhase here for extra optimization, same with other tests

2024-06-21 21:14 UTC, torranx commented on src/test/abilities/aura_break.test.ts
> +const getAppliedMovePower = (defender: Pokemon, attacker: Pokemon, move: Move) => {
can we change this to getMockedMovePower() ? I've changed the other function names like so in another PR. also please add documentation

2024-06-21 22:57 UTC, newmattock commented on src/test/abilities/aura_break.test.ts
> +    expect(appliedPower).lessThan(basePower);
I'm confused about this part, can you explain what I should do a bit more? Thank you for all of your help!

2024-06-21 22:58 UTC, torranx commented on src/test/abilities/aura_break.test.ts
> +    expect(appliedPower).lessThan(basePower);
i meant what was did with power_spot test. it explicitly checked the net power of the move and not just "lessThan basePower"

2024-06-22 15:29 UTC, Tempo-anon approved these changes
Not a huge deal, but instead of 3/4 the games actually use 4096/5448 so this should be 16777216/29680704

2024-06-22 15:37 UTC, merged