[Localization] Translate forgotten phrases sentences
pagefaultgames/pokerogue pull request #2254
Opened 2024-06-15 10:43 UTC by Nolway

## What are the changes?
Translate forgotten sentences on the phases file.

## Why am I doing these changes?
Because I seen few sentences not translated.

## What did change?
Few sentences in the game are now translatable and available on english ans french.

### Screenshots/Videos
![image](https://github.com/pagefaultgames/pokerogue/assets/3711182/58866214-3096-4573-923e-af0037f2d9aa)

## How to test the changes?
Go in game, activate the retry setting and loose a battle.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-15 11:44 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "beatModeFirstTime": "{{speciesName}} beat {{gameMode}} Mode for the first time!\nYou received {{newModifier}}!",
```suggestion
  "fainted": "{{pokemonNameWithAffix}} wurde besiegt!",
  "retryBattle": "Möchtest du vom Beginn des Kampfes neustarten?", 
  "receivedNewModifier": "Du erhältst\n{{modifierName}}!",
  "unlockedSomething": "{{unlockedThing}}\nwurde freigeschaltet.",
  "congratulations": "Glückwunsch!",
  "beatModeFirstTime": "{{speciesName}} hat den {{gameMode}} Modus zum ersten Mal beendet!\nDu erhältst {{newModifier}}!",
```

2024-06-15 13:40 UTC, returntoice requested changes

2024-06-15 13:40 UTC, returntoice commented on src/locales/ko/battle.ts
> +  "beatModeFirstTime": "{{speciesName}} beat {{gameMode}} Mode for the first time!\nYou received {{newModifier}}!",
```suggestion
  "retryBattle": "이 배틀의 처음부터 재도전하시겠습니까?",
  "receivedNewModifier": "{{modifierName}}[[를]]\n손에 넣었다!",
  "unlockedSomething": "{{unlockedThing}}[[가]]\n해금되었다.",
  "congratulations": "축하합니다!",
  "beatModeFirstTime": "{{speciesName}}[[가]] {{gameMode}} 모드를 처음으로 클리어했다!\n{{newModifier}}[[를]] 손에 넣었다!",
```
Translations for Korean locales

2024-06-17 11:36 UTC, Nolway commented on src/locales/fr/battle.ts
The modifications is still present but I collapse many commits during a rebase ><

2024-06-17 11:36 UTC, Nolway commented on src/locales/fr/battle.ts
I fix that

2024-06-17 11:40 UTC, Nolway commented on src/locales/fr/battle.ts
fixed

2024-06-17 11:43 UTC, Dakurei commented on src/locales/fr/battle.ts
> fixed

Always in english after your force push
![image](https://github.com/pagefaultgames/pokerogue/assets/8146474/a0e6f3cc-2da3-4351-b994-ba219cb6a050)

2024-06-17 11:52 UTC, Dakurei commented on src/locales/fr/battle.ts
> +  "beatModeFirstTime": "{{speciesName}} beat {{gameMode}} Mode for the first time!\nYou received {{newModifier}}!",
Still in English

2024-06-17 12:17 UTC, Nolway commented on src/locales/fr/battle.ts
> +  "beatModeFirstTime": "{{speciesName}} beat {{gameMode}} Mode for the first time!\nYou received {{newModifier}}!",
Now it's ok, sorry about that

2024-06-17 12:19 UTC, Dakurei commented on src/locales/fr/battle.ts
> +  "beatModeFirstTime": "{{speciesName}} a battu le mode {{gameMode}} pour la première fois!\nVous avez reçu {{newModifier}}!",
```suggestion
  "retryBattle": "Voulez-vous réessayer depuis le début du combat ?",
  "receivedNewModifier": "Vous avez reçu\n{{modifierName}} !",
  "unlockedSomething": "{{unlockedThing}}\na été débloqué.",
  "congratulations": "Félicitations !",
  "beatModeFirstTime": "{{speciesName}} a battu le mode {{gameMode}} pour la première fois !\nVous avez reçu {{newModifier}} !",
```

2024-06-20 01:27 UTC, EnochG1 commented
LGTM!
I tested in Korean and it works well.
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/477b04b6-9050-44e6-b1a1-c762a8237c42)

2024-06-20 01:28 UTC, EnochG1 approved these changes

2024-06-20 12:32 UTC, Nolway commented
> LGTM! I tested in Korean and it works well. ![image](https://private-user-images.githubusercontent.com/19601207/341237325-477b04b6-9050-44e6-b1a1-c762a8237c42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODY5NzAsIm5iZiI6MTcxODg4NjY3MCwicGF0aCI6Ii8xOTYwMTIwNy8zNDEyMzczMjUtNDc3YjA0YjYtOTA1MC00NGU2LWIxYTEtYzc2MmE4MjM3YzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDEyMzExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOGY0ZTk5ODUxYjBkZWVmMjQwNWQyYjMxYmY2OWQ1NDViMjExM2M1MWZmYzNjOGUxY2IwMjFlZmQ2MjRlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bwXteiGSPY9Ittb7AZQ8rmmqacHchvqoa88K4dICSVs)

Nice =)

2024-07-05 01:34 UTC, EnochG1 commented
@Nolway 
Could you merge branch 'main' into your branch?
I want to continue this PR.
Or if it's difficult for you to continue this PR on your own, I would mirror yours and continue.

2024-07-06 18:12 UTC, CodeTappert commented
Please fix the conflicts here!

2024-07-08 05:20 UTC, EnochG1 commented
Mirror PR created at https://github.com/pagefaultgames/pokerogue/pull/2906

2024-07-08 06:57 UTC, Nolway commented
> Mirror PR created at #2906

You create a pr mirroire in 3 days without any answer while I've been waiting for 3 weeks ...

2024-07-08 06:58 UTC, closed without merging

2024-07-08 08:49 UTC, EnochG1 commented
@Nolway,
I apologize for being radical without thinking deeply.
I thought long and hard before commenting, and I didn't want to see your PR leave it because it was such good work. (I wasn't the only one who think it.)
I don't have any authority here, I'm just one person who wants people like me who are not comfortable with English to enjoy translated games.
My English may not be good enough, but I really hope these PR merged into the main.
And hope we can collaborate in the future if you are okay.