[QoL] Improve shop readibility
pagefaultgames/pokerogue pull request #2267
Opened 2024-06-15 20:27 UTC by CodeTappert

## What are the changes?

Added shader to text in the shop. Also changed rouge color from red to green for better readability

## Why am I doing these changes?

The Read is REALLY hard to read. See https://discord.com/channels/1125469663833370665/1251535006669733959

## What did change?

See screenshots or title

Yes i know this also impacts the LUCK Text. But i dont see it as any worse after this change

### Screenshots/Videos

Korean Main:
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/bf8b5f7c-a050-42e2-b1c0-f9869d32ea1d)
Korean with this PR:
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/372e7d3f-cb7f-441a-b23f-b82b60d4548b)

English main:
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/5822401d-10d6-4d8f-8c45-0882101bfa5f)
English with this PR:
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/5c0241a6-5d0c-44c9-85a5-1e6e7a266aea)

## How to test the changes?

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-15 20:28 UTC, CodeTappert commented on src/ui/modifier-select-ui-handler.ts
> +    this.itemText = addTextObject(this.scene, 0, 35, this.modifierTypeOption.type.name, TextStyle.PARTY, {    align: "center"   });
```suggestion
    this.itemText = addTextObject(this.scene, 0, 35, this.modifierTypeOption.type.name, TextStyle.PARTY, { align: "center" });
```

2024-06-15 21:03 UTC, CodeTappert commented
I am willing to not do the color changes. But the shadow imo is a MUST

2024-06-15 21:08 UTC, Dakurei requested changes
Just for consistency with the other constants

2024-06-15 21:08 UTC, Dakurei commented on src/ui/text.ts
> +    return 0xE38787;
```suggestion
    return 0xe38787;
```

2024-06-15 21:08 UTC, Dakurei commented on src/ui/text.ts
> +    return 0xEC74D8;
```suggestion
    return 0xec74d8;
```

2024-06-15 21:08 UTC, Dakurei commented on src/ui/text.ts
> +    return 0xEE825D;
```suggestion
    return 0xee825d;
```

2024-06-16 12:29 UTC, Dakurei approved these changes
This should greatly improve legibility for the majority of players

And as @CodeTappert hinted, designing an option for people with color difficulties ( i.e. protanopia, deuteranopia, tritanopia, ...) should be considered, but that's a whole other much bigger job that applies not just to the shop, but to the whole game 👍

2024-06-16 20:32 UTC, torranx approved these changes
approving this so it gets traction

2024-06-17 02:26 UTC, brain-frog commented
Would it be possible for you to look at putting the overlay above the modifier bars so the modifiers arent interfering with reading the top row of the shop? I know it becomes a lot during endless

2024-06-17 07:14 UTC, Dakurei commented
> Would it be possible for you to look at putting the overlay above the modifier bars so the modifiers arent interfering with reading the top row of the shop? I know it becomes a lot during endless

When I made the modifications for this new black overlay, I was made to understand that people might want to see what their Pokémon already has on the screen, so we'll have to choose whether we want to hide them or not

2024-06-18 13:02 UTC, CodeTappert commented
> > Would it be possible for you to look at putting the overlay above the modifier bars so the modifiers arent interfering with reading the top row of the shop? I know it becomes a lot during endless
> 
> When I made the modifications for this new black overlay, I was made to understand that people might want to see what their Pokémon already has on the screen, so we'll have to choose whether we want to hide them or not
> 
> _EDIT: Personally, I think it would be better to hide the modifiers during the shop stage. Furthermore, as the overlay is defined in the context of the `fieldUI`, it wouldn't be easy to ensure that the modifiers (which are part of the `uiContainer`) are displayed underneath it without reviewing the structure of these overlays in a little more depth._

I agree with the idea to hide the modifiers during shop

2024-06-21 23:03 UTC, XGSleepWalker approved these changes

2024-06-21 23:03 UTC, XGSleepWalker approved these changes

2024-06-21 23:04 UTC, merged