Implements cursed body
pagefaultgames/pokerogue pull request #227
Opened 2024-04-21 18:40 UTC by shayebeadling

couldn't figure out a more elegant way of getting the attacker and move data into the getTriggerMessage function, open to suggestions about improvement. I imagine the args[] array could be used but it's not obvious to me how.

2024-04-26 08:37 UTC, Xavion3 requested changes

2024-04-26 08:37 UTC, Xavion3 commented on src/data/ability.ts
> +    if (!attacker.summonData.disabledMove) {
Can this also check isMax? Per more recent changes max pokemon should be immune.

2024-05-01 19:15 UTC, TempsRay commented on src/data/ability.ts
>        .unimplemented(),
The .unimplemented() should be removed

2024-05-01 19:21 UTC, TempsRay commented on src/data/ability.ts
> +      if (move.getMove().checkFlag(MoveFlags.MAKES_CONTACT, attacker, pokemon) && (this.chance === -1 || pokemon.randSeedInt(100) < this.chance) && !attacker.isMax()) {
How does this interact with specific edge cases?
* Struggle cannot be disabled
* If a multi-hit moves becomes disabled mid-hit the rest of the hits still go through
* Does not proc if the cursed body user is behind a sub and only the sub gets hit
* If a move calls another move (like metronome or nature power) procs this, then the original move is still disabled

2024-05-01 21:53 UTC, shayebeadling commented on src/data/ability.ts
> +      if (move.getMove().checkFlag(MoveFlags.MAKES_CONTACT, attacker, pokemon) && (this.chance === -1 || pokemon.randSeedInt(100) < this.chance) && !attacker.isMax()) {
- Doesn't seem to disable struggle.
- Multi hit doesn't get disabled until it finishes, because of the nature of the postDefend hook. 
- Can't test cause we don't have sub yet right?
- Don't think any of our nature power moves make contact, and tested with metronome contact moves. It currently doesn't disable metronome. The way that we're handling these types of moves right now, they essentially are just queueing that move after metronome / nature power is used so we would have to have some flag or something. I'll see if I can cleanly get it working, but might just say f it.

2024-05-01 22:05 UTC, shayebeadling commented on src/data/ability.ts
> +      if (move.getMove().checkFlag(MoveFlags.MAKES_CONTACT, attacker, pokemon) && (this.chance === -1 || pokemon.randSeedInt(100) < this.chance) && !attacker.isMax()) {
Couldn't get it to disable metronome without some ugly stuff, oh well. It's quite the edge case

2024-05-06 17:18 UTC, TempsRay commented
Does it still disable struggle? That's the only concern I have since like you said, the other troublesome factors are either unimplemented or super edge cases

2024-05-06 17:35 UTC, bennybroseph commented
From my testing, never disabled struggle. However, it also never disables a move if the pokemon with Cursed Body fainted. Have you checked against that?

https://bulbapedia.bulbagarden.net/wiki/Cursed_Body_(Ability)

2024-05-06 23:20 UTC, shayebeadling commented
@bennybroseph good call, added the bypassFaint() tag that we use for similar abilities. Now working as intended. Tested by setting chance to 100%, and with these overrides.
![image](https://github.com/pagefaultgames/pokerogue/assets/16782886/656277b0-e75f-4da4-bd9f-93734f28702b)

2024-05-06 23:38 UTC, TempsRay approved these changes

2024-05-08 05:07 UTC, bennybroseph commented
Okay, looks to be working. Glad I checked again though. The message that plays when an enemy's move is no longer disabled doesn't specify who the message is for. Very confusing in this fight when we both had tackle. The one when someone is disabled plays properly

https://github.com/pagefaultgames/pokerogue/assets/13838608/d7ff9443-fad0-42d5-9d2b-10dd268af2a9

2024-05-08 09:51 UTC, Xavion3 approved these changes

2024-05-08 13:52 UTC, shayebeadling commented
It applies the same tag that disable does, so the messages are the same. But I just updated the messages to clarify which pokemon's move it is now.

2024-05-08 20:56 UTC, bennybroseph commented
Still getting a confusing message. I see the code as updated to include the Pokemon's name, but it's not clear if it was you or the opponent 

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/e00c1f15-8ef8-4f75-8da1-a0bf48ecce33)

For reference, the image is of the enemy Houndoom no longer being disabled.

2024-05-08 21:47 UTC, shayebeadling commented
Now sticking the prefix on the front, will be consistent with our other messages now

2024-05-08 22:49 UTC, bennybroseph commented
Looks like there's an extra space in the message here:

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/6d5835f7-6b17-4061-a7f8-17c4cb183e63)

Same here for trainer's pokemon:

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/1d5b3729-db62-4ab9-b2c7-e7ed59b7573b)

For comparison:

![image](https://github.com/pagefaultgames/pokerogue/assets/13838608/160f6dc3-9c97-4f49-81fc-3473c4fee7cf)

2024-05-08 23:19 UTC, bennybroseph commented
Looks good to me now

2024-05-09 00:25 UTC, Madmadness65 approved these changes

2024-05-09 00:25 UTC, merged