[Ability] Fix Damp implementation
pagefaultgames/pokerogue pull request #2288
Opened 2024-06-16 06:32 UTC by zacharied

Draft, still need to test and localize.

## What are the changes?
Re-implement the Damp ability to fix #1476 and other problems. 

## Why am I doing these changes?
The current implementation of Damp has a few problems, starting with #1476. This bug occurs because Damp prints its disable message from *inside* the `MoveConditionFunc` that is applied to the move. The problem is that MoveConditionFuncs get applied during AI calculation as well, meaning AI opponents will print the preventage message multiple times per `EnemyCommandPhase` as they calculate scores.

My goal is to transfer the responsibility of handling Damp's effect away from the moves that would be blocked by it. If we move all the processing over to the Damp ability, it solves #1476 for free.

## What did change?
* Introduce `FieldPreventMovesAbAttr`. This attr is applied during `MoveEffectPhase.start()` and will cancel any move that matches its criteria. This effectively replaces the existing `failIfDampCondition` that was applied to all Damp-suppressed moves.
* Introduce `PreventPostFaintContactAb+Attr`. This attr handles Damp's effect of suppressing Aftermath damage.
* Fix a [mistake(?)](https://github.com/pagefaultgames/pokerogue/compare/main...zacharied:fix/damp?expand=1#diff-4f07716a1d7f28eb4f6c3dde2af7fd57c03118e7b0c440b3b1d593c1ba5ef16bR3687) in `applyAbAttrsInternal` in which `getTriggerMessage` calls were not splatting their `args` field, causing `args` to be passed as an array inside an array.
* Add unit tests for Damp and Aftermath

### Screenshots/Videos

Using the overrides described below.

https://github.com/pagefaultgames/pokerogue/assets/6374275/b2095184-24bf-46d9-bae6-75a19166130d

## How to test the changes?

For testing fix of #1476 and explosion moves in general:
```ts
export const ABILITY_OVERRIDE: Abilities = Abilities.DAMP;
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [Moves.EXPLOSION, Moves.SELF_DESTRUCT, Moves.MISTY_EXPLOSION, Moves.MIND_BLOWN];
```

For testing Aftermath suppression:
```ts
export const ABILITY_OVERRIDE: Abilities = Abilities.DAMP;
export const OPP_ABILITY_OVERRIDE: Abilities = Abilities.AFTERMATH;
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [Moves.SPLASH,Moves.SPLASH,Moves.SPLASH,Moves.SPLASH];
```

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-16 22:02 UTC, zacharied commented
@Greenlamp2 Ready for review.

2024-06-19 14:27 UTC, OrangeRed commented on src/phases.ts
> +      }
Are you sure that a pokemon with Damp doesn't prevent its own explosion? The ability description on bulbapedia states "ALL pokemon" which to me sounds like it includes itself. This might be worth testing somehow on showdown.

2024-06-19 14:28 UTC, OrangeRed approved these changes
Other than the one question I asked this looks good to me

2024-06-20 21:03 UTC, OrangeRed approved these changes

2024-06-21 05:38 UTC, zacharied commented
Bad unit test, not related to this PR.

2024-06-24 13:18 UTC, OrangeRed requested changes

2024-06-24 13:18 UTC, OrangeRed commented on src/locales/en/ability-trigger.ts
> +  "movePrevented": "{{moveUser}} cannot use {{moveName}}!",
The reason your test is failing is because you have two identical keys on lines 7 and 10.

Also can you sort the locale keys by alphabetical order ('m' comes before 'p') and add this locale key to the other ability-trigger files with the English translation, this makes it easier for localizers to find and replace.

2024-06-24 13:18 UTC, OrangeRed commented on src/phases.ts
> +
I don't think these comments are necessary

2024-07-13 17:05 UTC, OrangeRed commented
@zacharied can you merge the most recent changes to beta verify that everything works correctly

2024-08-04 16:55 UTC, Snailman11 commented
Link to Discord's bug report (Damp triggers if the opponent HAS a self-destruct move even if it does not use it)
https://discord.com/channels/1125469663833370665/1242203040216514660

2024-08-13 02:11 UTC, zacharied commented
Uhhhhh i fucked up

2024-08-13 23:49 UTC, DayKev commented on src/test/abilities/damp.test.ts
> +    game.override.ability(Abilities.NONE);
Using `Abilities.NONE` as an ability override disables it (the check for whether to override the ability or not checks for `0`, which is equivalent to `Abilities.NONE`).

2024-08-13 23:49 UTC, DayKev commented on src/test/abilities/damp.test.ts
> +    game.override.enemyMoveset(SPLASH_ONLY);
If you're going to use the same overrides in every test, bring them out into the `beforeEach()` section.

2024-08-13 23:49 UTC, DayKev commented on src/test/abilities/damp.test.ts
> +    const enemyAbility = Abilities.DAMP;
There's no need to make single-use variables like this, the context makes it obvious what they are supposed to be.

2024-09-06 01:24 UTC, DayKev reviewed
We're not supposed to put placeholder i18n strings in non-English files anymore. I think.

2024-09-06 01:24 UTC, DayKev commented on src/locales/de/ability-trigger.json
> +  "movePrevented": "{{moveUser}} cannot use {{moveName}}!",
```suggestion
```

2024-09-06 01:24 UTC, DayKev commented on src/locales/fr/ability-trigger.json
> +  "movePrevented": "{{moveUser}} cannot use {{moveName}}!",
```suggestion
```

2024-09-06 01:24 UTC, DayKev commented on src/locales/ko/ability-trigger.json
> +  "movePrevented": "{{moveUser}} cannot use {{moveName}}!",
```suggestion
```

2024-09-06 01:24 UTC, DayKev commented on src/locales/pt_BR/ability-trigger.json
> +  "movePrevented": "{{moveUser}} cannot use {{moveName}}!",
```suggestion
```

2024-09-06 01:24 UTC, DayKev commented on src/locales/zh_CN/ability-trigger.json
> +  "movePrevented": "{{moveUser}} cannot use {{moveName}}!",
```suggestion
```

2024-09-13 23:04 UTC, flx-sta commented
@zacharied please address the merge-conflicts and failing actions

2024-09-17 16:20 UTC, flx-sta commented
@zacharied  closed for being stale (no updates for over a month)

----

Feel free to create a new PR or ask us to re-open this one.

2024-09-17 16:20 UTC, closed without merging