Hydro Steam, Spirit Shackle, U-turn fix
pagefaultgames/pokerogue pull request #231
Opened 2024-04-22 02:58 UTC by Fontbane

Split #159 for now. This part includes the Hydro Steam implementation, which is a little different since some things have changed. Also includes Spirit Shackle, and a fix for a bug(?) I noticed where a wild mon using U-turn would result in it fleeing.

2024-04-22 03:03 UTC, Flashfyre requested changes

2024-04-22 03:03 UTC, Flashfyre commented on src/data/move.ts
> +        if (!(user instanceof PlayerPokemon) && move.category!=MoveCategory.STATUS)
```suggestion
        if (!(user instanceof PlayerPokemon) && move.category !== MoveCategory.STATUS)
```
Minor formatting nitpick

2024-04-22 07:40 UTC, Xavion3 commented on src/data/move.ts
> +        if (!(user instanceof PlayerPokemon) && move.category!=MoveCategory.STATUS)
This should probably use hasTrainer too right?

2024-04-22 12:41 UTC, EmoUsedHM01 commented
The implementation of Hydro Steam is incorrect
Firstly the fix has already been PR'd (#123)
Secondly it should get a damage boost as if it was a fire type move under sun

2024-04-26 09:12 UTC, Xavion3 requested changes

2024-04-26 09:12 UTC, Xavion3 commented on src/data/move.ts
> +    this.weather=weather;
Should have spaces around the equals, just a small formatting thing.

2024-04-26 09:12 UTC, Xavion3 commented on src/data/move.ts
> +      return (user, target, move) => user.scene.arena.weather?.weatherType==this.weather;
Doesn't this cause the entire move to fail if there's no sun active?

2024-04-26 09:12 UTC, Xavion3 commented on src/data/move.ts
> +        if (!(user instanceof PlayerPokemon) && move.category !== MoveCategory.STATUS)
It should still work for enemy trainers, there should be a hasTrainer function.

2024-04-27 01:16 UTC, Fontbane commented
Should work properly now.

I also noticed there's more to forced switch out moves than we have implemented, including different interactions in double wild battles and taking levels into account. Might open an issue for that.

2024-05-06 19:30 UTC, Fontbane commented
Okay, Parting Shot is more involved than I thought. It only switches out if the target gets its stats lowered, or if the stat changes get bounced back via Mirror Armor. If used on a target with Magic Bounce, it lowers the user's stats and switches out the target. It also works even if it the user has nothing to switch to, in which case it just works as a regular stat lowering move.

Chilly Reception is similar, but different in that neither of the effects are dependent on each other, so it will still switch out even if snow can't be set up, and it will set up snow even if it can't switch out, but if it can't do either, the move fails... _but_ before it fails it will still display the message, "(user) is preparing to tell a chillingly bad joke!".

Teleport is the only self switch out move which allows the user to flee if it's a wild Mon.

2024-05-06 19:54 UTC, bennybroseph commented
Sorry, is that explanation for how it **does** work in the code you submitted or how it **should** work in the mainline series and more changes are still required?

2024-05-08 08:10 UTC, bennybroseph approved these changes

2024-05-09 19:18 UTC, bennybroseph approved these changes

2024-05-09 19:23 UTC, Madmadness65 approved these changes

2024-05-09 21:59 UTC, Xavion3 approved these changes

2024-05-10 01:21 UTC, Flashfyre approved these changes

2024-05-10 01:21 UTC, merged