[Refactor/Bug] Overhaul & Document Item/Modifier Overrides
pagefaultgames/pokerogue pull request #2320
Opened 2024-06-17 05:01 UTC by xsn34kzx

## What are the changes?

Refactors `overrideHeldItems`, `overrideModifiers`, and a portion of `getPlayerModifierTypeOptions` dealing with the `ITEM_REWARD_OVERRIDE` to fix an issue where overridden reward items would not persist on reload. Additionally, `ITEM_REWARD_OVERRIDE` had its type changed for more specificity with generators.

## Why am I doing these changes?

The primary goal was fixing the override portion of `getPlayerModifierTypeOptions` such that any reward items picked up during a run would continue to exist on reload. Likewise, `ITEM_REWARD_OVERRIDE` was limited in that it could not specify pre-generator arguments, meaning that generator items were subject to RNG or party weighting. While I was working on those two things, I noticed that this portion of code and the override functions dealing with items and modifiers behave very similarly if not exactly the same at some points, so I figured it would be best to have parity between all the functions. On top of this, because the documentation isn't too in-depth or JSDocs-friendly in `overrides.ts`, I decided to tackle that as well. 

## What did change?

`overrideHeldItems` and `overrideModifiers` are essentially rewritten to be a little easier to parse through, a tad more performant, and paralleling one another. A small addition is that there is now an option to forgo the use of `type` for generators that do not use `party` as an argument (like `TEMP_STAT_BOOSTER` or `BERRY`). 

For `ITEM_REWARD_OVERRIDE`, the array type was changed to `ModifierOverride`. Inconsequential changes at this stage included going from `Array<ModifierOverride>` to `ModifierOverride[]` and making `ModifierOverride` a type rather than an interface (this change was really only done because we have no intention to extend it, which is the only difference as stated [here](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces)). By using `ModifierOverride` instead of `string`, `type` can now be used to specify pre-generator arguments; likewise, `getPlayerModifierTypeOptions` was rewritten such that it matched the other override functions and called `withIdFromFunc` to set its `id` correctly, which was needed to save and reload any overridden item rewards.

Documentation for the override variables was written, and comments were adjusted to be more informative since the difference between the overrides isn't obvious at first glance for contributors, let alone testers. A lot of the work I've done with items has made more savvy to them, so I figure that it would be good to write the things I had to work through initially to save time and provide more accessibility for manual testers and people less familiar with the code base. JSDoc `linkcode` annotations were used in addition to some silent imports to allow people to quickly jump to those relevant classes.

### Screenshots/Videos

Note that most of the changes are effectively indistinguishable in-game; however, the bug related to saving `ITEM_REWARD_OVERRIDE` modifiers has a clear before and after.

#### `ITEM_REWARD_OVERRIDE` - Before, Generator-based Item

https://github.com/pagefaultgames/pokerogue/assets/109637146/a8eda429-55fe-49be-acf9-454620c698cd

#### `ITEM_REWARD_OVERRIDE` - After, Generator-based Item

https://github.com/pagefaultgames/pokerogue/assets/109637146/0e78ced9-e746-4a69-aa24-66e1b23b7092

#### `ITEM_REWARD_OVERRIDE` - Before, Held Item

https://github.com/pagefaultgames/pokerogue/assets/109637146/d9b4e1a9-29f5-434e-8daa-0c2de4fccb53

#### `ITEM_REWARD_OVERRIDE` - After, Held Item

https://github.com/pagefaultgames/pokerogue/assets/109637146/09a1c343-f437-4704-a927-434e5dfbfc07

## How to test the changes?

Testing can be done by just using any of the `MODIFIER_OVERRIDE`s, `HELD_ITEM_OVERRIDE`s, and/or `ITEM_REWARD_OVERRIDE` and making sure they apply correctly and persist on reload. It's worth mentioning that, because these are developer overrides, there is no strict checking beyond making sure the name of the entry exists in `modifierTypes`. This means that, if you provide the wrong `type` pre-generator argument, it'll crash, which matches the behavior from before this PR regardless.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-17 13:15 UTC, OrangeRed commented on src/overrides.ts
> +};
Can you use this piece of typescript instead to force the `ModifierOverride` Type to have a subtype when necessary. Also I would like for this typedef to be in `modifier-types.ts` since that feels like a more logical place to put it rather than in `overrides.ts`
```ts
type BaseModifierTypes = {
  name: Exclude<keyof typeof modifierTypes, GeneratorModifierTypes["name"]>;
  count: number;
};

type GeneratorModifierTypes = { count: number } & (
  | {
      name: "TEMP_STAT_BOOSTER";
      type: TempBattleStat;
    }
  | {
      name: "BASE_STAT_BOOSTER";
      type: Stat;
    }
  | {
      name: "MINT";
      type: Nature;
    }
  | {
      name: "TERA_SHARD" | "ATTACK_TYPE_BOOSTER";
      type: Type;
    }
  | {
      name: "BERRY";
      type: BerryType;
    }
);

type ModifierTypes = GeneratorModifierTypes | BaseModifierTypes;
```

2024-06-17 13:16 UTC, OrangeRed commented on src/overrides.ts
> + * @example {name: "BERRY", count: 5, type: BerryType.SITRUS} // type must be given to get a specific berry
I wrote the typescript for the first point in a later comment

2024-06-17 15:16 UTC, xsn34kzx commented on src/overrides.ts
> + * @example {name: "BERRY", count: 5, type: BerryType.SITRUS} // type must be given to get a specific berry
I gotchu, those single-line comments were largely legacy comments, so I didn't want to necessarily shelve them without second opinion.

2024-06-17 21:58 UTC, xsn34kzx commented
Type changes were introduced as suggested by @OrangeRed with some adjustment to allow for generator output to be random or specified.

### Example
With the following overrides:
- `STARTING_MODIFIER_OVERRIDE = [{ name: "EXP_SHARE", count: 3}, { name: "DYNAMAX_BAND" }];`
- `ITEM_REWARD_OVERRIDE = [{ name: "TEMP_STAT_BOOSTER" }, { name: "TEMP_STAT_BOOSTER", type: TempBattleStat.ATK }];`

<img width="670" alt="generatorRoll1" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/22c1d589-8d05-485b-8686-27e40755fbb2">

<img width="669" alt="generatorRoll2" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/4e613298-0006-44b5-b63a-1253c993d2d2">

As a result, the first `TEMP_STAT_BOOSTER` is random per roll while the second `TEMP_STAT_BOOSTER` is always X Attack.

Additionally, `EvolutionItem` and `FormChangeItem` were added to the types that can be used and specified.

### Example
With the following overrides:
- `STARTING_MODIFIER_OVERRIDE = [{ name: "MEGA_BRACELET" } ];`
- `ITEM_REWARD_OVERRIDE = [{ name: "EVOLUTION_ITEM", type: EvolutionItem.CRACKED_POT }, { name: "FORM_CHANGE_ITEM" }];`

<img width="681" alt="evolutionItem" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/e6c80068-aefa-4d55-9173-90cccaf0c136">

<img width="676" alt="evolutionFormItems" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/1e3b242f-af85-4253-b5e9-a2a99979eb18">

The first slot is always `CRACKED_POT`, but without Audino, no `FORM_CHANGE_ITEM` replaces the second roll slot. However, with an Audino and a Mega Bracelet, it appears.

2024-06-17 22:15 UTC, OrangeRed commented on src/overrides.ts
> +/* eslint-enable @typescript-eslint/no-unused-vars */
instead of disabling eslint why not remove the things that aren't being used anymore?

The only reason allSpecies has the eslint disable is because its being used in a comment but not in javascript.

2024-06-17 22:15 UTC, OrangeRed commented on src/modifier/modifier-type.ts
> + */
instead of 4 @example statements can you just make one @example that has all four examples inside back ticks.

2024-06-18 00:05 UTC, OrangeRed approved these changes

2024-06-21 17:49 UTC, OrangeRed commented on src/modifier/modifier-type.ts
> +    }
Does this need to be added here if you're not giving a type property?

2024-06-21 17:49 UTC, OrangeRed commented on src/modifier/modifier-type.ts
> +    /** Quantity of the held item or modifier desired */
This comment isn't needed. The combined type will inherit the jsdoc from the Base type

2024-06-21 20:15 UTC, xsn34kzx commented on src/modifier/modifier-type.ts
> +    }
Added them to group them together in the "item generated from a generator" category and because I'd also want to give a type to TMs to eventually specify them in an item roll. Wasn't sure if that was out of scope or not for this PR, but that was the main intention.

2024-06-21 20:53 UTC, OrangeRed commented on src/modifier/modifier-type.ts
> +    }
Just add them when it becomes relevant not now preemptively

2024-06-21 23:27 UTC, xsn34kzx commented on src/modifier/modifier-type.ts
> +    }
Gotcha, in that case I'll implement that too to round out the overhaul.

2024-06-22 00:15 UTC, xsn34kzx commented
In addition to form-changing items and evolution items, TMs can now be specified and/or randomly generated, which covers the last of the generator-based items (at least until #1899).

### Example
With the following override:
```ts
export const ITEM_REWARD_OVERRIDE: ModifierOverride[] = [ { name: "TM_ULTRA" }, { name: "TM_COMMON", type: Moves.FLAMETHROWER } ];
```

<img width="669" alt="generatorRoll3" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/cc36a262-2d50-4c03-b748-2369430b108f">

<img width="670" alt="generatorRoll4" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/b35b6213-db9c-4bca-8b62-6f517b46f6bf">

Similar to the previous items, not specifying the move of the TM leaves it up to the generator to decide the TM that is eventually rolled, which uses RNG and compatibility with the party (which, in these examples, give Flare Blitz and Fire Blast). If the move is specified, the desired TM will always roll. 

Also worth noting that any move can be used, even if it isn't an existing TM.

### Example

With the following override:
```ts
export const ITEM_REWARD_OVERRIDE: ModifierOverride[] = [ { name: "TM_ULTRA" }, { name: "TM_COMMON", type: Moves.GIGATON_HAMMER } ];
```

<img width="668" alt="customTm" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/1535697e-6f4d-408d-abd6-9f830a0f3c90">

2024-06-22 00:33 UTC, OrangeRed commented
What happens when you try to create a TM_ULTRA with a move that is normally TM_COMMON?

2024-06-22 01:02 UTC, xsn34kzx commented
> What happens when you try to create a TM_ULTRA with a move that is normally TM_COMMON?

@OrangeRed Because `TM_COMMON`, `TM_GREAT`, and `TM_ULTRA` use the same generator class, they should all get caught in the `pregenArgs` condition before tier matters, but I did a double check with a few differently tiered moves just to make sure.

Using Bulk Up (Common), Brine (Great), and Close Combat (Ultra) with `TM_ULTRA` name,
```ts
export const ITEM_REWARD_OVERRIDE: ModifierOverride[] = [ { name: "TM_ULTRA", type: Moves.BULK_UP }, { name: "TM_ULTRA", type: Moves.BRINE }, { name: "TM_ULTRA", type: Moves.CLOSE_COMBAT } ];
```
<img width="696" alt="rollTmUltra" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/f7f525b8-fd87-4118-bacb-49bc3571a4bb">

Using the same set of moves with `TM_GREAT` name,
<img width="699" alt="rollTmGreat" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/ea67f93f-7b6b-45c8-9077-661eff7656e0">

Using the same set of moves with `TM_COMMON` name,
<img width="717" alt="rollTmCommon" src="https://github.com/pagefaultgames/pokerogue/assets/109637146/6e966ec8-0f7a-411b-9f51-d871b457e4f2">

From these examples, I pretty much double checked that the following scenarios work and don't error on roll:
- A Common tier TM is used under Ultra/Great
- A Great tier TM is used under Common/Ultra
- An Ultra tier TM is used under Common/Great

2024-06-22 15:03 UTC, OrangeRed approved these changes

2024-06-25 19:45 UTC, OrangeRed approved these changes

2024-06-25 19:45 UTC, OrangeRed commented on src/overrides.ts
> +import { ModifierOverride } from "./modifier/modifier-type";
Can you add `type` here so its clear. `import { type ... } from "..."`

2024-06-27 19:40 UTC, xsn34kzx commented
> In addition to form-changing items and evolution items, TMs can now be specified and/or randomly generated, which covers the last of the generator-based items (at least until #1899).

Now that #1899 has been merged, `SPECIES_STAT_BOOSTER` is now included among the generator-based items and can also now be specified.

2024-07-12 15:10 UTC, flx-sta commented on src/modifier/modifier-type.ts
>    const modifierTier = luckValue ? luckValue > 2 ? luckValue > 5 ? luckValue > 9 ? luckValue > 11 ? ModifierTier.LUXURY : ModifierTier.MASTER : ModifierTier.ROGUE : ModifierTier.ULTRA : ModifierTier.
ik, ik. Not your PR but could you clean those up in your PR?

2024-07-12 15:18 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +export type ModifierOverride = GeneratorModifierOverride | BaseModifierOverride;
@OrangeRed what do you think?

2024-07-13 18:01 UTC, OrangeRed requested changes

2024-07-13 18:12 UTC, OrangeRed commented on src/modifier/modifier-type.ts
> +export type ModifierOverride = GeneratorModifierOverride | BaseModifierOverride;
@flx-sta I reviewed this again today and I think this needs to be separated somehow because as it is, its very possible to pass a held item as a party modifier and crash the game

2024-07-13 22:19 UTC, xsn34kzx commented on src/modifier/modifier-type.ts
> +    }
The only issue with how its done in that PR is that the game crashes when there's more entries in `ITEM_REWARD_OVERRIDE`, which I tested really quick before merging:

```ts
const overrides = {
  ITEM_REWARD_OVERRIDE: [ "AMULET_COIN", "AMULET_COIN", "AMULET_COIN", "AMULET_COIN", "AMULET_COIN", "AMULET_COIN"]
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

<img width="1052" alt="rewardError" src="https://github.com/user-attachments/assets/1ca47a79-778d-4e4e-8de7-e4d1e9fc83e7">

Sticking with this implementation since `minLength` covers this and the other scenario where there's less entries in `ITEM_REWARD_OVERRIDE`.

2024-07-13 22:21 UTC, xsn34kzx commented on src/modifier/modifier.ts
> +      let modifierType = modifierFunc();
`modifierFunc` is used again a little later in the function when calling `withIdFromFunc`.

2024-07-14 17:29 UTC, xsn34kzx commented on src/modifier/modifier-type.ts
> +      }
Ended up going one by one to every instance of this in the generator classes and incorporating type checking. The only caveat is that `instanceof` specifically can't be used for enums, where most if not all of the `pregenArgs` themselves are enums, so I did `pregenArgs[0] in ...` instead for the most part. Another random thing to note is that pretty much all of the `pregenArgs` should just have one element of that type, probably a refactor waiting to happen that may or may not be annoying/break how generator items are regenerated during save loading.

2024-07-29 05:19 UTC, xsn34kzx commented
Entries in `ITEM_REWARD_OVERRIDE` now correctly reflect their tier using a new function provided by @ben-lear 🎉 

### Example

With the following override:
```ts
ITEM_REWARD_OVERRIDE: [ { name: "FORM_CHANGE_ITEM", type: FormChangeItem.RED_ORB }, { name: "SCOPE_LENS" }, { name: "LEEK" } ]
```

<img width="373" alt="tieredRewards" src="https://github.com/user-attachments/assets/fea66870-e73d-443b-8223-717d60585f87">

2024-08-08 22:20 UTC, flx-sta approved these changes
lgtm 🚀 
and works like a charm (play-test)a

2024-08-12 04:53 UTC, DayKev approved these changes

2024-08-12 10:54 UTC, merged