[Move] Implement Natural Gift
pagefaultgames/pokerogue pull request #2333
Opened 2024-06-17 10:41 UTC by AyushBarik

## What are the changes?

User will be able to utilize the move Natural Gift.

## Why am I doing these changes?

Enhances User Experience.

## What did change?

Natural Gift is now a usable move.

### Screenshots/Videos

--work in progress--

## How to test the changes?

--work in progress--

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-17 14:48 UTC, Tempo-anon commented
Should be pretty similar to Fling implementation. I assume it will just choose a random berry if the user has more than 1 applicable berry.

2024-07-02 14:28 UTC, Tempo-anon requested changes

2024-07-02 14:28 UTC, Tempo-anon commented on src/data/move.ts
> +  getCondition(): MoveConditionFunc {
Doesn't this just return a boolean of whether or not the user has berries?

2024-07-02 14:28 UTC, Tempo-anon commented on src/data/move.ts
> +  getFailedText(user: Pokemon, target: Pokemon, move: Move, cancelled: Utils.BooleanHolder): string | null {
This is also checking for `cancelled` value too right? Is returning `null` the correct response for failure text when the user has berries?

2024-07-02 14:28 UTC, Tempo-anon commented on src/data/move.ts
> +export class NaturalGiftAttr extends VariablePowerAttr {
Shouldn't this also change the type of the attack based on the berry too?

2024-07-02 14:33 UTC, AyushBarik commented on src/data/move.ts
> +  getCondition(): MoveConditionFunc {
yes. there was an issue that "return false" wasn't working the way it was supposed to in fling so i was suggested to use this method by orangeRed

2024-07-02 14:34 UTC, AyushBarik commented on src/data/move.ts
> +  getFailedText(user: Pokemon, target: Pokemon, move: Move, cancelled: Utils.BooleanHolder): string | null {
what do you mean by cancelled value?

2024-07-02 14:35 UTC, AyushBarik commented on src/data/move.ts
> +export class NaturalGiftAttr extends VariablePowerAttr {
ah it does. let me fix that

2024-07-02 15:13 UTC, Tempo-anon commented on src/data/move.ts
> +  getFailedText(user: Pokemon, target: Pokemon, move: Move, cancelled: Utils.BooleanHolder): string | null {
Oh I see on 2768 and 2783 you're passing true in. Should update the function tsdoc to reflect all the variables

2024-07-04 19:15 UTC, AyushBarik commented on src/data/move.ts
> +export class NaturalGiftAttr extends VariablePowerAttr {
in order to pass information from one class to another i set up a global variable. is tht ok? maybe i can make setter and getter functions so its safer

2024-07-05 15:34 UTC, Tempo-anon requested changes

2024-07-05 15:34 UTC, Tempo-anon commented on src/modifier/modifier.ts
> +  [BerryType.LUM]: 1,     // Type.FLYING
Isn't Type.FLYING actually 2? https://github.com/pagefaultgames/pokerogue/blob/42304070a0e59193ebcc4b66c01b5e0e25d209c6/src/data/type.ts#L5

There's no need to use actual numbers here when the enums map to numbers. It'll also prevent errors like this where all your numbers seem to be off by 1

2024-07-05 16:11 UTC, AyushBarik commented on src/modifier/modifier.ts
> +  [BerryType.LUM]: 1,     // Type.FLYING
You are right. I removed the array and stopped passing in an index for the array and directly pass in the move type instead.

2024-07-27 10:20 UTC, innerthunder requested changes

2024-07-27 10:20 UTC, innerthunder commented on src/battle-scene.ts
> +  public naturalGiftBerryModifier: BerryModifier;
Can this be moved to a class closer in scope to Nature Power's attributes? `Pokemon` or even `TurnData` should be able to support this.

2024-07-28 13:19 UTC, AyushBarik commented on src/battle-scene.ts
> +  public naturalGiftBerryModifier: BerryModifier;
Both of those classes are in pokemon.ts which does not import BerryModifier. Should I import it in? Or stick with battle-scene.ts?

2024-07-29 19:16 UTC, AyushBarik commented on src/battle-scene.ts
> +  public naturalGiftBerryModifier: BerryModifier;
moved it to TurnData

2024-07-29 19:17 UTC, AyushBarik commented on src/data/move.ts
> +    const power = args[0] as Utils.NumberHolder;
ok

2024-07-29 19:17 UTC, AyushBarik commented on src/data/move.ts
> +   * @param args - Additional arguments for the move.
ok

2024-07-29 19:17 UTC, AyushBarik commented on src/data/move.ts
> +  getFailedText(user: Pokemon, target: Pokemon, move: Move, cancelled: Utils.BooleanHolder): string | null {
ok

2024-07-29 21:11 UTC, Tempo-anon commented on src/field/pokemon.ts
> +import { yyType } from "#enums/berry-type";
Is this a typo?

2024-07-30 14:14 UTC, AyushBarik commented on src/field/pokemon.ts
> +import { yyType } from "#enums/berry-type";
took care of that. made a new PR since this one got infiltrated with a bunch of commits from other people.

2024-07-30 14:59 UTC, flx-sta commented
closing in favor of #3247

2024-07-30 14:59 UTC, closed without merging