[Localization] Translate party UI
pagefaultgames/pokerogue pull request #2334
Opened 2024-06-17 10:53 UTC by Nolway

## What are the changes?
Translate missing sentences and words on the party UI.

## Why am I doing these changes?
Because few sentences and words aren't translated.

## What did change?
Theses sentences will be translatable.

### Screenshots/Videos
![image](https://github.com/pagefaultgames/pokerogue/assets/3711182/3971b46b-bf35-4671-a70e-635fdd9acac7)

The reason why I change the wording of "Cancel" on the french translation:
![image](https://github.com/pagefaultgames/pokerogue/assets/3711182/0df7a7f3-f738-4977-9a76-9102469d2a50)

## How to test the changes?
Go into the party UI with the french language.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-17 11:01 UTC, Dakurei requested changes
Some mistakes

2024-06-17 11:01 UTC, Dakurei commented on src/locales/fr/party-ui-handler.ts
> +  "selectPokemonSplice": "Sélectionner un autre Pokémon à séparer.",
```suggestion
  "selectPokemonSplice": "Sélectionnez un autre Pokémon à fusionner.",
```

2024-06-17 11:06 UTC, Dakurei commented on src/locales/fr/party-ui-handler.ts
> +  "selectItemTransfer": "Sélectionnez un objet tenu à transférer.\NUtilisez les touches < et > pour modifier la quantité.",
```suggestion
  "selectItemTransfer": "Sélectionnez un objet tenu à transférer.\nUtilisez les touches < et > pour modifier la quantité.",
```

2024-06-17 11:45 UTC, Dakurei requested changes
That remaining error

2024-06-17 11:45 UTC, Dakurei commented on src/locales/fr/party-ui-handler.ts
> +  "selectPokemonSplice": "Sélectionnez un autre Pokémon à séparer.",
```suggestion
  "selectPokemonSplice": "Sélectionnez un autre Pokémon à fusionner.",
```

2024-06-17 12:51 UTC, Dakurei commented on src/locales/fr/party-ui-handler.ts
> +  "CANCEL": "Sortir",
```suggestion
  "CANCEL": "Retour",
```

For the `cancelButton` I don't mind "Sortir" being used, but as far as this input is concerned, it's been "Retour" for several generations now.

Your change:
![Capture d’écran du 2024-06-17 14-04-41](https://github.com/pagefaultgames/pokerogue/assets/8146474/df0ddc82-eed8-4667-9058-165a4ecc8fa4)

In official French games:
![Screenshot_20240617_143137_SuperNDS](https://github.com/pagefaultgames/pokerogue/assets/8146474/aedd54e6-9980-450a-bc9f-8f7f765327e0)

2024-06-17 13:42 UTC, Dakurei requested changes
You've inverted what I told you

If you could apply the changes from Github rather than push force all your commits to each edits, it would also be simpler, and less illegible in the content of the PR

2024-06-17 13:42 UTC, Dakurei commented on src/locales/fr/party-ui-handler.ts
> +  "CANCEL": "Sortir",
```suggestion
  "CANCEL": "Retour",
```

2024-06-17 13:42 UTC, Dakurei commented on src/locales/fr/party-ui-handler.ts
> +  "cancelButton": "Retour",
```suggestion
  "cancelButton": "Sortir",
```

2024-06-17 15:03 UTC, returntoice requested changes
Korean translation

2024-06-17 15:03 UTC, returntoice commented on src/locales/ko/party-ui-handler.ts
> +  "cancelButton": "Cancel",
```suggestion
  "chooseAPokemon": "포켓몬을 선택하세요.",
  "doWhatWithPokemon": "무엇을 하겠습니까?",
  "selectMove": "기술을 선택하세요.",
  "selectItemTransfer": "옮기고자 하는 지닌 도구를 선택하세요.\n<와 > 키를 사용하여 수량을 변경할 수 있습니다.",
  "selectPokemonSplice": "융합할 다른 포켓몬을 선택하세요.",
  "cancelButton": "그만둔다",
```

2024-06-17 19:53 UTC, NicusPulcis commented
Italian PR has been sent

2024-06-20 23:01 UTC, GoldTra reviewed
Spanish translations

2024-06-20 23:01 UTC, GoldTra commented on src/locales/es/party-ui-handler.ts
> +  "cancelButton": "Cancel",
```suggestion
  "chooseAPokemon": "Elige un Pokémon.",
  "doWhatWithPokemon": "¿Que quieres hacer con el Pokémon?",
  "selectMove": "Selecciona un movimiento.",
  "selectItemTransfer": "Selecciona un objeto equipado para transferir.\nUsa < y > para cambiar la cantidad.",
  "selectPokemonSplice": "Selecciona otro Pokémon para fusionar.",
  "cancelButton": "Salir",
```

2024-06-21 09:03 UTC, GoldTra approved these changes

2024-06-22 17:12 UTC, returntoice approved these changes

2024-06-23 21:33 UTC, bennybroseph commented
Surely we already have some of these menu options translated. Why are we retranslating Cancel?

2024-07-05 02:37 UTC, EnochG1 commented
@Nolway 
Maybe this PR is duplicated with https://github.com/pagefaultgames/pokerogue/pull/2566

2024-07-08 06:58 UTC, closed without merging