[Localization] Translate summary
pagefaultgames/pokerogue pull request #2336
Opened 2024-06-17 13:07 UTC by Nolway

## What are the changes?
Translate missing sentences and words on the pokemon summary.

## Why am I doing these changes?
Because few sentences and words aren't translated.

## What did change?
Theses sentences will be translatable.

### Screenshots/Videos
![image](https://github.com/pagefaultgames/pokerogue/assets/3711182/86698a9b-1b1e-4edf-8409-fde992b0d87e)
![image](https://github.com/pagefaultgames/pokerogue/assets/3711182/8e7e8671-0552-47df-91ce-5f76ebd8b7f9)
![image](https://github.com/pagefaultgames/pokerogue/assets/3711182/3e94dbae-50a6-4590-bdda-d9c020c68855)

## How to test the changes?
Go into a Pokemon summary with the french language.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-17 14:00 UTC, Adri1 reviewed
Please change theses French entries

2024-06-17 14:00 UTC, Adri1 commented on src/locales/fr/pokemon-summary.ts
> +  "status": "Status",
```suggestion
  "status": "Statut",
```

2024-06-17 14:09 UTC, 40chyan commented on src/locales/zh_CN/pokemon-summary.ts
> +  "cancel": "Cancel",
```suggestion
"pokemonInfo": "宝可梦信息",
  "status": "状态",
  "powerAccuracyCategory": "威力\n命中率\n类别",
  "type": "属性",
  "unknownTrainer": "未知",
  "ot": "训练师",
  "luck": "幸运",
  "nature": "性格",
  "apparently": "命中注定般地",
  "metAtLv": "相遇于Lv.",
  "expPoints": "经验值",
  "nextLv": "下一级",
  "cancel": "取消",
```

2024-06-17 15:12 UTC, returntoice requested changes

2024-06-17 15:12 UTC, returntoice commented on src/locales/ko/pokemon-summary.ts
> +  "cancel": "Cancel",
```suggestion
  "pokemonInfo": "포켓몬 정보",
  "status": "스테이터스",
  "powerAccuracyCategory": "위력\n명중\n분류",
  "type": "타입",
  "unknownTrainer": "Unknown",
  "ot": "어버이",
  "luck": "럭",
  "nature": "성격",
  "apparently": "분명히",
  "metAtLv": "만난 레벨은 Lv.",
  "expPoints": "현재 경험치",
  "nextLv": "다음 레벨까지",
  "cancel": "돌아간다",
```

2024-06-17 15:40 UTC, ddullgi requested changes

2024-06-17 15:40 UTC, ddullgi commented on src/locales/ko/pokemon-summary.ts
> +  "cancel": "Cancel",
```suggestion
  "pokemonInfo": "포켓몬 정보",
  "status": "능력치",
  "powerAccuracyCategory": "위력\n명중\n분류",
  "type": "타입",
  "unknownTrainer": "알수없음",
  "ot": "어버이",
  "luck": "행운",
  "nature": "성격",
  "apparently": "apparently",
  "metAtLv": "met at Lv.",
  "expPoints": "현재 경험치",
  "nextLv": "다음 레벨까지",
  "cancel": "그만둔다",
```

Due to differences in word order between Korean and English, those parts have not been translated.

2024-06-17 15:43 UTC, returntoice commented on src/locales/ko/pokemon-summary.ts
> +  "cancel": "Cancel",
"status"는 9세대 스칼렛/바이올렛 기준으로 "스테이터스"라고 되어 있어 "능력치"보다는 "스테이터스"가 좋을 듯합니다. 마찬가지로 "cancel"도 "돌아간다"로 되어 있습니다.

2024-06-17 15:49 UTC, ddullgi commented on src/locales/ko/pokemon-summary.ts
> +  "cancel": "Cancel",
먼저 올리신 걸 나중에 봤네요.
의견주신 것들 고치면 거의 일치하니까 
제안은 취소할께요

2024-06-17 16:03 UTC, CodeTappert commented on src/locales/de/pokemon-summary.ts
> +} as const;
```suggestion
export const pokemonSummary: SimpleTranslationEntries = {
  "pokemonInfo": "Pokémon Info",
  "status": "Status",
  "powerAccuracyCategory": "Stärke\nGenauigkeit\nKategorie",
  "type": "Typ",
  "unknownTrainer": "Unbekannt",
  "ot": "OT",
  "luck": "Glück",
  "nature": "Wesen",
  "apparently": "Wahrscheinlich",
  "metAtLv": "getroffen auf Lvl. ",
  "expPoints": "Erf. Punkte",
  "nextLv": "Nächstes Lvl.",
  "cancel": "Abbrechen",
} as const;
```

2024-06-17 17:19 UTC, Dakurei commented on src/locales/fr/pokemon-summary.ts
> +  "ot": "DO",
```suggestion
  "ot": "D.O.",
```
![image](https://github.com/pagefaultgames/pokerogue/assets/8146474/7490c23d-faa6-4bbd-b4f1-6922ecad5c48)

2024-06-17 18:34 UTC, CodeTappert commented on src/locales/de/pokemon-summary.ts
> +} as const;
Please test if this actually fits

2024-06-17 19:58 UTC, NicusPulcis commented
Italian translations have been sent

2024-06-17 21:51 UTC, Dakurei commented on src/locales/fr/config.ts
> +>>>>>>> Translate pokemon summary to fr
You commit a merge conflict

2024-06-20 22:25 UTC, GoldTra commented on src/locales/es/pokemon-summary.ts
> +  "cancel": "Cancel",
```suggestion
  "pokemonInfo": "Info. Pokémon",
  "status": "Estado",
  "powerAccuracyCategory": "Potencia\nPrecisión\nCategoria",
  "type": "Tipo",
  "unknownTrainer": "Desconocido",
  "ot": "EO",
  "luck": "Suerte",
  "nature": "de naturaleza",
  "apparently": "aparentemente",
  "metAtLv": "encontrado al Nv.",
  "expPoints": "Puntos Exp.",
  "nextLv": "Nv. siguiente",
  "cancel": "Salir",
```

2024-06-20 22:26 UTC, GoldTra commented on src/locales/es/pokemon-summary.ts
> +  "cancel": "Cancel",
Spanish Translations

2024-06-20 22:53 UTC, GoldTra reviewed
Spanish translations

2024-06-20 22:53 UTC, GoldTra commented on src/locales/es/pokemon-summary.ts
> +  "cancel": "Cancel",
```suggestion
  "pokemonInfo": "Info. Pokémon",
  "status": "Estado",
  "powerAccuracyCategory": "Potencia\nPrecisión\nCategoria",
  "type": "Tipo",
  "unknownTrainer": "Desconocido",
  "ot": "EO",
  "luck": "Suerte",
  "nature": "de naturaleza",
  "apparently": "aparentemente",
  "metAtLv": "encontrado al Nv.",
  "expPoints": "Puntos Exp.",
  "nextLv": "Nv. siguiente",
  "cancel": "Salir",
```

2024-06-21 09:15 UTC, MrWaterT commented
Can you check PR[#5](https://github.com/Nolway/pokerogue/pull/5), [#6](https://github.com/Nolway/pokerogue/pull/6) for text modification in some language?

2024-06-21 18:45 UTC, Nolway commented
> Can you check PR[#5](https://github.com/Nolway/pokerogue/pull/5), [#6](https://github.com/Nolway/pokerogue/pull/6) for text modification in some language?

I merged the 6 and I'll wait for the 5 =)

2024-06-22 17:11 UTC, returntoice requested changes

2024-06-22 17:11 UTC, returntoice commented on src/locales/ko/pokemon-summary.ts
> +  "status": "능력치",
```suggestion
  "status": "스테이터스",
```
The current version(9th gen SV) officially translates "status" into "스테이터스"

2024-06-22 19:33 UTC, MrWaterT commented
I corrected both suggestion about "metAtLv" and "status" in [#5](https://github.com/Nolway/pokerogue/pull/5).
It is ready to be merged now.

2024-06-27 03:13 UTC, josericardo-fo commented on src/locales/pt_BR/pokemon-summary.ts
> +  "cancel": "Cancel",
```suggestion
  "pokemonInfo": "Informações do Pokémon",
  "status": "Status",
  "powerAccuracyCategory": "Poder\nPrecisão\nCategoria",
  "type": "Tipo",
  "unknownTrainer": "Desconhecido",
  "ot": "TO",
  "luck": "Sorte",
  "nature": "natureza",
  "apparently": "aparentemente",
  "metAtLv": "encontrado no Nv.",
  "expPoints": "Pontos EXP.",
  "nextLv": "Próx. Nv.",
  "cancel": "Cancelar",
```

2024-07-05 01:46 UTC, EnochG1 commented
@Nolway,
Could you merge branch 'main' into your branch?
I want to continue this PR.
Or if it's difficult for you to continue this PR on your own, I would mirror yours and continue.

2024-07-05 16:26 UTC, returntoice approved these changes
okay for Korean trans

2024-07-06 18:36 UTC, CodeTappert commented
Please fix your conflicts

2024-07-07 18:12 UTC, NicusPulcis commented
@CodeTappert sorry i can't find them, could you DM me on discord to help?

2024-07-08 05:17 UTC, EnochG1 commented
Mirror PR created at https://github.com/pagefaultgames/pokerogue/pull/2907

2024-07-08 06:58 UTC, closed without merging