ci: Bump actions version
pagefaultgames/pokerogue pull request #2341
Opened 2024-06-17 15:18 UTC by Yaminyam

## What are the changes?

## Why am I doing these changes?

## What did change?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-14 03:17 UTC, DayKev requested changes

2024-08-14 03:17 UTC, DayKev commented on .github/workflows/eslint.yml
> +        uses: actions/checkout@v4  # Use the checkout action version 2
```suggestion
        uses: actions/checkout@v4  # Use the checkout action version 4
```

2024-08-14 03:17 UTC, DayKev commented on .github/workflows/eslint.yml
> +        uses: actions/setup-node@v4  # Use the setup-node action version 1
```suggestion
        uses: actions/setup-node@v4  # Use the setup-node action version 4
```

2024-08-14 03:32 UTC, DayKev approved these changes

2024-09-13 16:49 UTC, Tempo-anon approved these changes

2024-09-13 16:49 UTC, flx-sta approved these changes
Checks seem to run just as fine as before.
lgtm

2024-09-13 16:52 UTC, merged