Implemented Terrain Pulse
pagefaultgames/pokerogue pull request #235
Opened 2024-04-22 06:44 UTC by lucfd

- [x] Type changes to match terrain if user is grounded

- [x] Power doubles while terrain is active

2024-04-26 09:12 UTC, Xavion3 requested changes

2024-04-26 17:21 UTC, lucfd commented on src/data/move.ts
> +      return false;
Amended, test condition is now ```!user.isGrounded```

2024-05-01 19:30 UTC, TempsRay commented
lgtm, but just wanted to double check that the move power doubling and terrain power boost stack. i.e. a non normal/electric Pokemon using terrain pulse in electric terrain should do 2.6x damage compared to no terrain

2024-05-02 15:10 UTC, lucfd commented
Yup, that's correct. From [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Terrain_Pulse_(move)):
> If the user is grounded under any type of terrain, Terrain Pulse's [power](https://bulbapedia.bulbagarden.net/wiki/Power) doubles to 100 (type power-ups from the terrain will be put into effect in addition to this boost).

2024-05-10 13:54 UTC, Xavion3 approved these changes

2024-05-19 13:31 UTC, merged