[Localization] include pokemon names, stats into battle:stat* keys
pagefaultgames/pokerogue pull request #2373
Opened 2024-06-18 10:21 UTC by hibiyasleep

## What are the changes?

There were untranslatable text template remain, "{Wild} {Pokemon}'s {Speed}{…localizable part}".
Make those transratable by moving template into`battle:stat…` strings.

## Why am I doing these changes?
not every language use "'s";
> (Name)'s (Stat)이 크게 올랐다!

and not every language write stats after name;
> L'(Stat) du (Name) ennemi augmente beaucoup!

## What did change?
`getBattleStatLevelChangeDescription` now accepts pokemon's name and changed stats

### Screenshots/Videos
before:
![image](https://github.com/pagefaultgames/pokerogue/assets/5380174/c7875c02-bd28-4df5-80d6-4c390fdd6c0f)

after: 
![image](https://github.com/pagefaultgames/pokerogue/assets/5380174/43c980db-b800-4520-8662-935a5014c9a7)

## How to test the changes?
Testcases working; while testing getBattleStatLevelChangeDescription, Pokemon name and status label is replaced with dummy.

## Checklist
- [v] There is no overlap with another PR?
- [v] The PR is self-contained and cannot be split into smaller PRs?
- [v] Have I provided a clear explanation of the changes?
- [v] Have I tested the changes (manually)?
    - [v] Are all unit tests still passing? (`npm run test`)
- [v] Are the changes visual?
  - [v] Have I provided screenshots/videos of the changes?

2024-06-19 14:59 UTC, sodaMelon commented
hi
There seems to be no problem with Korean grammar.
I will check others in the (Korean) morning

2024-06-19 15:34 UTC, EnochG1 approved these changes
일단은 조사와 부분 한글화를 수정하는 것이 시급해 보여 승인합니다.
I approved it cause seems to right in Korean.

2024-06-19 18:56 UTC, returntoice approved these changes

2024-06-19 23:44 UTC, Adri1 commented on src/locales/fr/battle.ts
>    "ppReduced": "It reduced the PP of {{targetName}}'s\n{{moveName}} by {{reduction}}!",
```suggestion
  "statRose": "{{stats}} de {{pokemonNameWithAffix}}\naugmente !",
  "statSharplyRose": "{{stats}} de {{pokemonNameWithAffix}}\naugmente beaucoup !",
  "statRoseDrastically": "{{stats}} de {{pokemonNameWithAffix}}\naugmente énormément !",
  "statWontGoAnyHigher": "{{stats}} de {{pokemonNameWithAffix}}\nne peut plus augmenter !",
  "statFell": "{{stats}} de {{pokemonNameWithAffix}}\nbaisse !",
  "statHarshlyFell": "{{stats}} de {{pokemonNameWithAffix}}\nbaisse beaucoup !",
  "statSeverelyFell": "{{stats}} de {{pokemonNameWithAffix}}\nbaisse énormément !",
  "statWontGoAnyLower": "{{stats}} de {{pokemonNameWithAffix}}\nne peut plus baisser !",
  "ppReduced": "Les PP de la capacité {{moveName}}\nde {{targetName}} baissent de {{reduction}} !",
```

2024-06-19 23:44 UTC, Adri1 commented on src/locales/fr/battle.ts
>    "ppReduced": "It reduced the PP of {{targetName}}'s\n{{moveName}} by {{reduction}}!",
Added French translations

2024-06-20 00:16 UTC, sodaMelon approved these changes
there's no problem. LGTM

@hibiyasleep You can choice when to merge. ( maybe you can wait that other foreign contributor do localize their language. if you want this, use pokerouge wiki discord)

if you have any opinion,  use comment.

2024-06-20 00:56 UTC, hibiyasleep commented
> 혹시 변경되는 스테이터스가 여러개일때에 대한 처리가 되었을까요?
> _Was it dealt with when there were multiple statuses that were changed?_

아직 없습니다. phrases.ts에서 구현된대로 “A, B, and C" 내지 ”stats"를 그대로 사용합니다. 이 부분은 별도 PR에서 개선해볼 생각입니다

Not yet, uses implementation of phrases.ts as "A, B and C" or "stats". Will try to improve on other PR.

2024-06-20 00:59 UTC, hibiyasleep commented
Will soon rebase and merge then! as it doesn't make things worse, additional i18n may go later.

2024-06-20 01:11 UTC, sodaMelon commented
> Will soon rebase and merge then! as it doesn't make things worse, additional i18n may go later.

OK. well done

2024-06-20 01:58 UTC, hibiyasleep commented
Ready to merge, awaiting review.

2024-06-20 03:59 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "statWontGoAnyLower": "{{pokemonNameWithAffix}}의 {{stats}}[[는]]\n더 떨어지지 않는다!",
```suggestion
  "statRose": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 올라갔다!",
  "statSharplyRose": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 올라갔다!",
  "statRoseDrastically": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 올라갔다!",
  "statWontGoAnyHigher": "{{pokemonNameWithAffix}}의\n{{stats}}[[는]] 더 올라가지 않는다!",
  "statFell": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 떨어졌다!",
  "statHarshlyFell": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 떨어졌다!",
  "statSeverelyFell": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 떨어졌다!",
  "statWontGoAnyLower": "{{pokemonNameWithAffix}}의\n{{stats}}[[는]] 더 떨어지지 않는다!",
```
```suggestion
  "statRose": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 올라갔다!",
  "statSharplyRose": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 올라갔다!",
  "statRoseDrastically": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 올라갔다!",
  "statWontGoAnyHigher": "{{pokemonNameWithAffix}}의 {{stats}}[[는]]\n더 올라가지 않는다!",
  "statFell": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 떨어졌다!",
  "statHarshlyFell": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 떨어졌다!",
  "statSeverelyFell": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 떨어졌다!",
  "statWontGoAnyLower": "{{pokemonNameWithAffix}}의 {{stats}}[[는]]\n더 떨어지지 않는다!",
```

Minor suggestion, but why don't you modify position of endline of WontGo (referred pokemon Scarlet/Violet)

줄바꿈을 본가 기준으로 맞췄습니다.
참고로, 현재 workflow가 돌지 않는 이유는
web github 혹은 github verified가 되지 않은 로컬에서
main 머지 작업을 하셔서 그런거 같습니다.

2024-06-20 04:36 UTC, hibiyasleep commented on src/locales/ko/battle.ts
> +  "statWontGoAnyLower": "{{pokemonNameWithAffix}}의 {{stats}}[[는]]\n더 떨어지지 않는다!",
gpg를 설정했습니다 :+1: 감사합니다!

변경 내용은 커밋에 합쳤습니다!

2024-06-20 22:46 UTC, GoldTra requested changes
Spanish Translations

2024-06-20 22:46 UTC, GoldTra commented on src/locales/es/battle.ts
> +  "statWontGoAnyLower": "¡{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRose": "¡El {{stats}} de {{pokemonNameWithAffix}} ha subido!",
  "statSharplyRose": "¡El {{stats}} de {{pokemonNameWithAffix}} ha subido mucho!",
  "statRoseDrastically": "¡El {{stats}} de {{pokemonNameWithAffix}} ha subido muchísimo!",
  "statWontGoAnyHigher": "¡El {{stats}} de {{pokemonNameWithAffix}} no puede subir más!",
  "statFell": "¡El {{stats}} de {{pokemonNameWithAffix}} ha bajado!",
  "statHarshlyFell": "¡El {{stats}} de {{pokemonNameWithAffix}}} ha bajado mucho!",
  "statSeverelyFell": "¡El {{stats}} de {{pokemonNameWithAffix}} ha bajado muchísimo!!",
  "statWontGoAnyLower": "¡El {{stats}} de {{pokemonNameWithAffix}} no puede bajar más!",
```

2024-06-21 05:52 UTC, hibiyasleep commented
How can I get this PR merged? I thought this PR has already reviewed…

2024-06-21 06:03 UTC, EnochG1 commented
You need to get review of reviewers who is maintainer.
개발 병합 권한이 있는 분의 머지를 기다려야 합니다.
approve 주신 분들은 대부분 junior dev 권한자들 혹은 번역을 도와주시는 분들이라서요..

특히 단순 번역은 승인이 빠른 반면 코드화는 시간이 좀 걸리고, 금일 점검도 있었어서 더욱 바쁘실거에요.

도움이 필요한 경우, discord에서 요청하시면 빠르게 승인해주실 수도 있습니다. (이 건은 테스트 코드도 이미 존재하니까요)

2024-06-21 07:37 UTC, sodaMelon commented
in this time, ask who added label. 
@Tempo-anon  hi. can you check this pull request? it's not not important but enought to merge.

and @hibiyasleep it's better using another way than "force push". (sometime workflow trigger can't read it)

2024-06-21 07:43 UTC, hibiyasleep commented
I made a force push is because this PR is rebased, then should I make merge commit instead? (I used to rebase & force push on this kind of job for clean linear history, and I think this is not wrong but different…….)

rebase 대신 merge commit 생성하는 쪽이 나을까요? (force push vs mergeback은 그냥 방식차이라고 생각합니다…….)

2024-06-21 07:44 UTC, hibiyasleep commented
> 특히 단순 번역은 승인이 빠른 반면 코드화는 시간이 좀 걸리고, 금일 점검도 있었어서 더욱 바쁘실거에요.

죄송합니다 다른 건 아니고 PR에 문제가 있어서 시간이 걸리는 줄 알았습니다. 확인해주셔서 감사합니다!

2024-06-21 07:49 UTC, sodaMelon commented
> I made a force push is because this PR is rebased, then should I make merge commit instead? (I used to rebase & force push on this kind of job for clean linear history, and I think this is not wrong but different…….)
> 
> rebase 대신 merge commit 생성하는 쪽이 나을까요? (force push vs mergeback은 그냥 방식차이라고 생각합니다…….)

저도 방식차이라고 생각했는데, EnochG1님 저번 PR 이나 다른 오픈소스 기여해보니깐,..........뭔가 있더라구요. 🫠 그래서 저도 그냥 제가 개인적으로 쓰는 repository 아니면 업무나 외부기여에는 사용안하고있습니다.
일단은 좀 더 기다려보시고, 한국어 번역 디스코드 놀러오세요... [포케로그 위키 채널 디스코드](https://discord.gg/xkrPZz2p)

2024-06-21 08:40 UTC, hibiyasleep commented
> 저도 방식차이라고 생각했는데, EnochG1님 저번 PR 이나 다른 오픈소스 기여해보니깐,..........뭔가 있더라구요. 🫠 그래서 저도 그냥 제가 개인적으로 쓰는 repository 아니면 업무나 외부기여에는 사용안하고있습니다.

조언 감사합니다 🫠 ㅠㅠ 초대장이 만료되었는데 재발급 부탁드릴게요…!

2024-06-21 08:44 UTC, sodaMelon commented
> > 저도 방식차이라고 생각했는데, EnochG1님 저번 PR 이나 다른 오픈소스 기여해보니깐,..........뭔가 있더라구요. 🫠 그래서 저도 그냥 제가 개인적으로 쓰는 repository 아니면 업무나 외부기여에는 사용안하고있습니다.
> 
> 조언 감사합니다 🫠 ㅠㅠ 초대장이 만료되었는데 재발급 부탁드릴게요…!

https://www.reddit.com/r/pokerogue/comments/1bvehw9/pokerogue_discord/
https://discord.com/invite/uWpTfdKG49
입니다

2024-06-21 10:01 UTC, Adri1 approved these changes

2024-06-23 01:52 UTC, Tempo-anon approved these changes

2024-06-23 01:55 UTC, merged