[Localization] localize hatch egg message (+ egg move unlock)
pagefaultgames/pokerogue pull request #2395
Opened 2024-06-19 04:04 UTC by EnochG1

## What are the changes?
Add the option to localize message text when egg is hatched.

## Why am I doing these changes?
All text should be localizable and I don't want to show message with mixed language.
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/fd02d562-7de4-4568-becb-4002919eb5c6)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/b1d87957-3878-40a5-bacd-1057948a3843)
As-is images in Korean.

## What did change?
 - Change the code for localize
 - Added localization key in each language folders.
 - Translated of them to Korean.

### Screenshots/Videos
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/aa313de9-5002-452a-a2c2-255d8f738c49)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/1167227d-f138-4b6b-9b4c-f8827ad70fc6)
English

![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/0b840897-15d0-4c6b-8e8a-978fb9df178a)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/c6e9cd70-08cb-4d7f-8c41-4c257e85f933)
Korean

## How to test the changes?
Manually.
1. Checkout this PR and change language
2. set overrides.ts ```IMMEDIATE_HATCH_EGGS_OVERRIDE = true;``` and try hatch the egg.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-06-19 05:49 UTC, CodeTappert commented on src/locales/de/egg.ts
> +  "rareEggMoveUnlock": "Rare Egg Move unlocked",
```suggestion
  "hatchFromTheEgg": "Ein {{pokemonName}} ist aus dem Ei geschlüpft!",
  "eggMoveUnlock": "Ei-Attacke freigeschaltet",
  "rareEggMoveUnlock": "Seltene Ei-Attacke freigeschaltet",
```

2024-06-19 06:12 UTC, 40chyan commented on src/locales/zh_CN/egg.ts
> +  "rareEggMoveUnlock": "Rare Egg Move unlocked",
```suggestion
  "hatchFromTheEgg": "{{pokemonName}} 从蛋中孵化了！",
  "eggMoveUnlock": "蛋招式已解锁",
  "rareEggMoveUnlock": "稀有蛋招式已解锁",
```

2024-06-19 13:09 UTC, EnochG1 commented
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/3db452fd-bceb-4cca-9c92-d9e586a0c98b)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/35091c87-70bd-4079-aed8-b5098eaa1901)
@CodeTappert Please approve if test results are right.

2024-06-19 13:11 UTC, EnochG1 commented
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/672a59d1-4aa3-4856-b6e4-30564a27fbea)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/21e23eb1-7b90-48a2-b819-8f27de159809)
@40chyan Please approve if test results are right.

2024-06-19 13:25 UTC, CodeTappert commented
> ![image](https://private-user-images.githubusercontent.com/19601207/341086834-672a59d1-4aa3-4856-b6e4-30564a27fbea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM3NzUsIm5iZiI6MTcxODgwMzQ3NSwicGF0aCI6Ii8xOTYwMTIwNy8zNDEwODY4MzQtNjcyYTU5ZDEtNGFhMy00ODU2LWI2ZTQtMzA1NjRhMjdmYmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzMjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NDRmYzliNTQ4ODkyNzJkODBlMjEwOGJiNDk0N2QzZjU3MDk0YTQyYmYzYmQ1NTAzN2ZmZWQ5MmVlMTNjODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTuqvA5vj-5yUU3TfdGTTlLtjHSswrzuIhvEeBxauCM) ![image](https://private-user-images.githubusercontent.com/19601207/341086848-21e23eb1-7b90-48a2-b819-8f27de159809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM3NzUsIm5iZiI6MTcxODgwMzQ3NSwicGF0aCI6Ii8xOTYwMTIwNy8zNDEwODY4NDgtMjFlMjNlYjEtN2I5MC00OGEyLWI4MTktOGYyN2RlMTU5ODA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzMjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYWU5MGQ3MmExYWQwMjNjODZiZmIwMjIyOTc4OWQ2YWU2ODEyMjJiODZhZjcwNzgxMGE3YjJlMGMwMjFmNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dfd6PyxZgXycK4eiHLIayVYq6sdZi1E5W7EyruIHCB0) @40chyan Please approve if test results are right.

The cursor position here looks pretty wrong

2024-06-19 14:28 UTC, EnochG1 commented
> The cursor position here looks pretty wrong

@CodeTappert 
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/aa8f0fc4-09b7-48e6-baa0-ebb16b8e686e)
I checked other case in game.
It might be not because of egg hatched message.

2024-06-20 01:45 UTC, 40chyan commented
> > The cursor position here looks pretty wrong
> 
> @CodeTappert ![image](https://private-user-images.githubusercontent.com/19601207/341112506-aa8f0fc4-09b7-48e6-baa0-ebb16b8e686e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NDc3ODYsIm5iZiI6MTcxODg0NzQ4NiwicGF0aCI6Ii8xOTYwMTIwNy8zNDExMTI1MDYtYWE4ZjBmYzQtMDliNy00OGU2LWJhYTAtZWJiMTZiOGU2ODZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAxMzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMjBjMTliYWVjZjQ0NGQ1OWY3MDlmZTcyYzQ4N2VkYWYzMzFhYjBmYmU3MWY0ODg2YjQ4NmUxODdhYjM5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G0saNumoF3hyu88A7KwNgAIOvfXnqruhYYRC5ryvgts) I checked other case in game. It might be not because of egg hatched message but chinese exclusive.

yes exactly what I want to say. a Chinese string problem maybe @EnochG1

2024-06-20 02:29 UTC, 40chyan approved these changes

2024-06-20 02:46 UTC, hibiyasleep commented on src/system/game-data.ts
> +      this.scene.ui.showText(`${eggMoveIndex === 3 ? i18next.t("egg:rareEggMoveUnlock") : i18next.t("egg:eggMoveUnlock")}: ${allMoves[speciesEggMoves[speciesId][eggMoveIndex]].name}`, null, () => res
I know this is a bit late, but can move name be included into translatable part?

> Egg Move unlocked: Harden
> 알 기술 해금: 단단해지기

would be better with

> Egg Move unlocked: _Harden_!
> 알 기술 _단단해지기_가 해금되었다! (…를 사용할 수 있게 되었다! maybe)

2024-06-20 03:27 UTC, EnochG1 commented on src/system/game-data.ts
> +      this.scene.ui.showText(`${eggMoveIndex === 3 ? i18next.t("egg:rareEggMoveUnlock") : i18next.t("egg:eggMoveUnlock")}: ${allMoves[speciesEggMoves[speciesId][eggMoveIndex]].name}`, null, () => res
Thanks for your advice! I think it's good idea.
좋은 생각인거 같아서 추가로 작업했습니다.
아래 코멘트에 테스트 스크린샷 첨부드릴테니 괜찮다 생각되면 approve 부탁드리겠습니다.

2024-06-20 03:29 UTC, EnochG1 commented
I approved @hibiyasleep's suggestion and make moveName to parameter in egg move unlock messages.
This is test screenshot of Korean and English(Not changed but for checking it works.)

![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/55be8a5d-2503-4add-ac6e-33fef177bedc)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/a97fe278-6ec6-4742-8791-2070d4bf833e)

2024-06-20 04:04 UTC, hibiyasleep commented on src/locales/ko/egg.ts
> +  "rareEggMoveUnlock": "레어 알 기술 {{moveName}}[[를]]\n사용할 수 있게 되었다.",
```suggestion
  "eggMoveUnlock": "알 기술 {{moveName}}[[를]]\n사용할 수 있게 되었다!",
  "rareEggMoveUnlock": "레어 알 기술 {{moveName}}[[를]]\n사용할 수 있게 되었다!",
```
to be consistent

2024-06-20 04:09 UTC, EnochG1 commented on src/locales/ko/egg.ts
> +  "rareEggMoveUnlock": "레어 알 기술 {{moveName}}[[를]]\n사용할 수 있게 되었다.",
Nice advice, thanks :)

2024-06-20 04:15 UTC, EnochG1 commented on src/locales/it/egg.ts
> +  "hatchFromTheEgg": "{{pokemonName}} hatched from the egg!",
```suggestion
  "hatchFromTheEgg": "Dall’Uovo è nato {{pokemonName}}!",
```

2024-06-20 04:22 UTC, hibiyasleep approved these changes

2024-06-20 10:14 UTC, Adri1 commented
@EnochG1 Do not forget the French translation too, submitted a bit earlier in this conversation 👌

2024-06-20 10:25 UTC, EnochG1 commented
@Adri1
I'm sorry but can you give me a link of your PR?
I can't find in my repo and I submitted your other PRs but that isn't this work.
https://github.com/EnochG1/pokerogue/pulls?q=is%3Aopen+is%3Apr

2024-06-20 10:28 UTC, Adri1 commented
@EnochG1 Not a PR, but a pending review in this very conversation 10+ hours ago

2024-06-20 10:32 UTC, EnochG1 commented
@Adri1 I can't find your review or suggestion.
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/62c8eb4e-2926-459c-8acf-773ef54ef208)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/33828246-9678-4722-a3df-4e52130ce3e6)

Maybe I'm missing something.
Or if your review or suggestion is 'Pending', you have to submit your review at here.
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/6a27b3aa-d084-4494-bc60-d59168fcec77)

2024-06-20 10:39 UTC, Adri1 commented
@EnochG1 What... Wierd because when I scroll up I still can see it.
Well I'm gonna make a new one

2024-06-20 10:41 UTC, Adri1 commented on src/locales/fr/egg.ts
> +  "rareEggMoveUnlock": "Rare Egg Move unlocked: {{moveName}}",
```suggestion
  "hatchFromTheEgg": "{{pokemonName}} sort de l’Œuf !",
  "eggMoveUnlock": "Capacité Œuf débloquée ",
  "rareEggMoveUnlock": "Capacité Œuf Rare débloquée ",
```

2024-06-20 10:41 UTC, Adri1 commented on src/locales/fr/egg.ts
> +  "rareEggMoveUnlock": "Rare Egg Move unlocked: {{moveName}}",
French Translation for these additions

Spaces added at the end of "eggMoveUnlock" and "rareEggMoveUnlock" sentences are completly normal.

2024-06-20 10:51 UTC, EnochG1 commented on src/locales/fr/egg.ts
> +  "rareEggMoveUnlock": "Capacité Œuf Rare débloquée ",
```suggestion
  "eggMoveUnlock": "Capacité Œuf débloquée {{moveName}}",
  "rareEggMoveUnlock": "Capacité Œuf Rare débloquée {{moveName}}",
```

2024-06-20 10:52 UTC, EnochG1 commented on src/locales/fr/egg.ts
> +  "rareEggMoveUnlock": "Capacité Œuf Rare débloquée ",
changed logic suggested by [hibiyasleep](https://github.com/hibiyasleep) must set moveName so I added it

2024-06-20 10:55 UTC, EnochG1 commented
@Adri1 I approved your suggestion and tested.
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/7ea7dde9-ce10-4edf-8a0b-7a118c7d7fe2)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/c483b783-b5f3-4e4f-aacd-0e9bf8d79924)
But second test result is not right.

After I fixed logic with Egg Move Unlocked, test result is below.
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/088142c5-0423-4297-a4ae-68f34d0587b7)

Please check test screenshot and approve when it is right!

2024-06-20 10:59 UTC, Adri1 reviewed
Oops I hav'nt noticed that ": {{moveName}}" has been added, sorry, I readapteded it
Except this tiny issue, everything is okay

2024-06-20 10:59 UTC, Adri1 commented on src/locales/fr/egg.ts
> +  "rareEggMoveUnlock": "Capacité Œuf Rare débloquée {{moveName}}",
```suggestion
  "eggMoveUnlock": "Capacité Œuf débloquée : {{moveName}}",
  "rareEggMoveUnlock": "Capacité Œuf Rare débloquée : {{moveName}}",
```

2024-06-20 11:06 UTC, Adri1 reviewed
A really tini tiny edit, just to be really sure

2024-06-20 11:06 UTC, Adri1 commented on src/locales/fr/egg.ts
> +  "rareEggMoveUnlock": "Capacité Œuf Rare débloquée : {{moveName}}",
```suggestion
  "eggMoveUnlock": "Capacité Œuf débloquée :\n{{moveName}}",
  "rareEggMoveUnlock": "Capacité Œuf Rare débloquée :\n{{moveName}}",
```

2024-06-20 11:12 UTC, Adri1 approved these changes

2024-06-20 11:13 UTC, EnochG1 commented
@Adri1 Don't mind. I committed your suggestion :)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/1d161075-1e16-4931-9aa4-d2d387b0721d)

2024-06-20 11:14 UTC, Adri1 commented
Perfection 👌

2024-06-20 22:31 UTC, GoldTra requested changes
Spanish Translations

2024-06-20 22:31 UTC, GoldTra commented on src/locales/es/egg.ts
> +  "rareEggMoveUnlock": "Rare Egg Move unlocked: {{moveName}}",
```suggestion
  "hatchFromTheEgg": "¡Ha salido un {{pokemonName}} del Huevo!",
  "eggMoveUnlock": "Mov. Huevo desbloqueado:\n{{moveName}}",
  "rareEggMoveUnlock": "Mov. Huevo Raro desbloqueado:\n{{moveName}}",
```

2024-06-20 23:03 UTC, GoldTra approved these changes

2024-06-21 05:45 UTC, EnochG1 commented
@GoldTra Thanks, I committed and added test screenshot at main article :)

2024-06-21 06:40 UTC, CodeTappert approved these changes

2024-06-22 17:17 UTC, returntoice approved these changes

2024-06-24 00:04 UTC, EnochG1 commented on src/locales/zh_TW/egg.ts
>    "sameSpeciesEgg": "{{species}} 會從這個蛋裡孵化！"
```suggestion
  "sameSpeciesEgg": "{{species}} 會從這個蛋裡孵化！",
```

2024-06-24 00:14 UTC, Tempo-anon approved these changes

2024-06-24 00:14 UTC, merged