Fixed type immunity abilities not working against status moves
pagefaultgames/pokerogue pull request #240
Opened 2024-04-22 19:34 UTC by lucfd

Currently type immunity abilities only work against instances of `AttackMove`, leading to unintentional behaviour such as moves like Leech Seed or Sleep Powder working against Pokemon with Sap Sipper.
- `TypeImmunityAbAttr` has been changed to work against all move categories (instances of `Move`)
- Added additional logic to prevent ability activation against moves that target the field (preventing Earth Eater from blocking spikes, Sap Sipper from blocking Grassy Terrain, etc)

2024-04-26 12:24 UTC, Xavion3 commented on src/data/ability.ts
> +    if (((move.getMove() instanceof Move && !targetsField) || move.getMove().getAttrs(StatusMoveTypeImmunityAttr).find(attr => (attr as StatusMoveTypeImmunityAttr).immuneType === this.immuneType)) &&
Why is this checking if a move is a move?

2024-05-06 16:57 UTC, lucfd commented on src/data/ability.ts
> +    if (((move.getMove() instanceof Move && !targetsField) || move.getMove().getAttrs(StatusMoveTypeImmunityAttr).find(attr => (attr as StatusMoveTypeImmunityAttr).immuneType === this.immuneType)) &&
Redundant logic from when this attribute checked for instanceof AttackMove. Removed in commit https://github.com/pagefaultgames/pokerogue/pull/240/commits/481d8e2796d7d8378dbf0add07b2d48defbf5a70

2024-05-14 03:43 UTC, bennybroseph requested changes

2024-05-19 13:35 UTC, bennybroseph commented
Closing this due to inactivity. Feel free to make a new request if interest is reignited

2024-05-19 13:35 UTC, closed without merging