Misc2
pagefaultgames/pokerogue pull request #241
Opened 2024-04-22 20:12 UTC by TempsRay

* Implemented Forewarn and created OHKO move flags
* Implemented Frisk to check the opponent's abilities rather than their items since all items are already visible
* Created BattlerTags for Magnet Rise implementation but have not implemented it yet since that would result in some changes to Smack Down and Thousand Arrows too

2024-04-22 20:28 UTC, Flashfyre submitted a review, later dismissed

2024-04-22 20:56 UTC, TempsRay commented on src/data/move.ts
> +  OHKO_Move = 65536
Is there a quick and easy way to check if a move is a OHKO move? Then again, I could just hardcode it in the forewarn method considering I already did so for counter/mirror coat/metal burst

2024-04-24 14:40 UTC, lucfd commented on src/data/move.ts
> +  OHKO_Move = 65536
You can use Move's findAttr() method and then check if `OneHitKOAttr` is present. Something like this: `move.getMove().findAttr(attr => attr instanceof OneHitKOAttr)`

2024-05-01 05:03 UTC, Xavion3 requested changes

2024-05-01 05:03 UTC, Xavion3 commented on src/data/ability.ts
> +        } else if (move.getMove().id === Moves.COUNTER || move.getMove().id === Moves.MIRROR_COAT || move.getMove().id === Moves.METAL_BURST) {
Why isn't this checking for every counter move? Is that actually how forewarn works to ignore one of them?

2024-05-01 06:06 UTC, TempsRay commented on src/data/ability.ts
> +        } else if (move.getMove().id === Moves.COUNTER || move.getMove().id === Moves.MIRROR_COAT || move.getMove().id === Moves.METAL_BURST) {
According to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Forewarn_(Ability)) and [Smogon](https://www.smogon.com/dex/sv/abilities/forewarn/) Comeuppence is not counted as a counter move for Forewarn. I don't have the cart to test but if anyone can confirm, I can add it in.

2024-05-04 01:43 UTC, Xavion3 commented on src/data/ability.ts
> +        } else if (move.getMove().id === Moves.COUNTER || move.getMove().id === Moves.MIRROR_COAT || move.getMove().id === Moves.METAL_BURST) {
Sure, weird but not the weirdest thing we've dealt with.

2024-05-04 02:07 UTC, Xavion3 approved these changes

2024-05-04 02:07 UTC, Xavion3 commented on src/data/move.ts
> +  OHKO_Move = 65536
This was changed to no longer use a flag

2024-05-04 02:10 UTC, merged