[Enhancement][Challenge] Nuzlocke challenge
pagefaultgames/pokerogue pull request #2421
Opened 2024-06-19 21:54 UTC by sirzento

## What are the changes?

Adding a Nuzlocke challenge to the game

## Why am I doing these changes?

Because more challenges = better, many people are asking for it and it was on the old roadmap.

## What did change?

This will be filled when I have developed more in this PR

### Screenshots/Videos

## How to test the changes?

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-29 07:50 UTC, hayuna commented
@sirzento What about this scenario?

Opponent has REVIVAL_SEED
Player is using thief move

Player will take REVIVAL_SEED from opponent. Should this be illegal in nuzlocke mode?

2024-06-29 09:14 UTC, sirzento commented
> @sirzento What about this scenario?
> 
> Opponent has REVIVER_SEED Player is using thief move
> 
> Player will take REVIVER_SEED from opponent. Should this be illegal in nuzlocke mode?

@hayuna Yeah I thought about it and just thought it will be alright because it's just so rare to get it like that. I could disable it somehow if that's wanted but I think it will be alright like that.

2024-07-12 10:38 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "desc": "Die Nuzlocke Challenge vordert verschiedene Einschränkungen um eine besondere Challenge zu gestallten.",
```suggestion
"desc": "Die Nuzlocke-Challenge beinhaltet verschiedene Einschränkungen, um eine besondere Herausforderung zu gestalten."
```

2024-07-12 10:40 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "desc.1": "Nuzlocke Regeln:\n- Keine Beleber.\n- Nur ein Pokémon pro 10 Wellen kann zum Team hinzugefügt werden.\n",
```suggestion
"desc.1": "Nuzlocke-Regeln:\n- Keine Beleber.\n- Pro 10 Wellen darf nur ein Pokémon zum Team hinzugefügt werden.\n"
```

2024-07-12 10:41 UTC, CodeTappert commented on src/locales/de/achv.ts
> +    description: "Complete the regular nuzlocke challenge.",
```suggestion
  "NUZLOCKE_REGULAR": {
    "name": "Unbezwingbar",
    "description": "Schließe die normale Nuzlocke-Herausforderung ab.",
```

2024-07-12 10:42 UTC, CodeTappert commented on src/locales/de/achv.ts
> +    description: "Complete the hardcore nuzlocke challenge.",
```suggestion
  "NUZLOCKE_HARDCORE": {
    "name": "Wie?",
    "description": "Schließe die Hardcore-Nuzlocke-Herausforderung ab.",
```

2024-07-12 10:44 UTC, sirzento commented on src/locales/de/challenges.ts
> +    "desc.1": "Nuzlocke Regeln:\n- Keine Beleber.\n- Nur ein Pokémon pro 10 Wellen kann zum Team hinzugefügt werden.\n",
Why did you remove the ","? This is needed ^^Is it possible to change this suggested code here?

2024-07-12 10:44 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +"desc": "Die Nuzlocke-Challenge beinhaltet verschiedene Einschränkungen, um eine besondere Herausforderung zu gestalten."
```suggestion
"desc": "Die Nuzlocke-Herausforderung beinhaltet verschiedene Einschränkungen, um eine besondere Herausforderung zu gestalten."
```

2024-07-12 10:49 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "desc.1": "Nuzlocke Regeln:\n- Keine Beleber.\n- Nur ein Pokémon pro 10 Wellen kann zum Team hinzugefügt werden.\n",
Okay sorry i didnt mean to remove the ,

2024-07-12 10:52 UTC, CodeTappert approved these changes

2024-07-12 21:44 UTC, Xavion3 requested changes
For the new signatures, can we be clearer whether the apply functions are expected to set it to true or false for each? It looks like they all assume true, and set to false if unexpected, but just having some kind of note in the function documentation about that would be good.

2024-07-12 21:44 UTC, Xavion3 commented on src/data/challenge.ts
> +      desc += i18next.t("challenges:nuzlocke.desc.2");
Can we just have two localisation entries for levels 1 and 2 instead of concatenating them? We try to avoid just concatenating multiple localisation when possible. You'd be able to remove this entire function override if you did that too.

2024-07-12 21:44 UTC, Xavion3 commented on src/data/challenge.ts
> +  public additionalData: {[x: string]: any};
Don't do this, you can include additional values in the specific challenge instances when necessary.

2024-07-12 21:44 UTC, Xavion3 commented on src/data/challenge.ts
> +    valid.value = !pokemon.legendary;
Why restrict only legends and not say, paradox, minor legends, mythicals, etc.? It seems very arbitrary.

2024-07-12 21:44 UTC, Xavion3 commented on src/system/challenge-data.ts
> +    this.additionalData = source.additionalData;
This will not work as is and will require server changes.

2024-07-12 21:44 UTC, Xavion3 commented on src/ui/challenges-select-ui-handler.ts
> +    const headerBg = addWindow(this.scene, 0, 0, (this.scene.game.canvas.width / 6) - 2, 24);
For this, and all the changes below, why are you changing the size of the UI elements? What will the challenge selection screen look like after you do so?

2024-07-12 21:44 UTC, Xavion3 commented on src/phases.ts
> +        }
What does this actually look like in game? It looks like it only allows you to add the first pokemon caught in each section to your party, instead of only allowing you to add one pokemon caught in each section to your party?

2024-07-12 21:44 UTC, Xavion3 commented on src/modifier/modifier-type.ts
> +export function getPlayerModifierTypeOptions(count: integer, party: PlayerPokemon[], gameMode: GameMode, modifierTiers?: ModifierTier[]): ModifierTypeOption[] {
You don't need to add an argument here since the scene object is already passed in.

2024-07-12 21:49 UTC, sirzento commented on src/data/challenge.ts
> +      desc += i18next.t("challenges:nuzlocke.desc.2");
I did that because the level 2 description is exactly as the first one but with additional text. But I can change that if you want.

2024-07-12 21:51 UTC, sirzento commented on src/data/challenge.ts
> +    valid.value = !pokemon.legendary;
Yeah that's something to discuss what should be used there for balancing. I can also restrict those if that would be a better overall challenge.

2024-07-12 21:53 UTC, sirzento commented on src/system/challenge-data.ts
> +    this.additionalData = source.additionalData;
Mhh are you 100% sure about that? I tested it with an running server and it did work fine since the challenges have no defined table schema inside the db. (Not 100% sure since I have just the knowledge from looking at the server code and nothing more)

2024-07-12 21:54 UTC, sirzento commented on src/data/challenge.ts
> +  public additionalData: {[x: string]: any};
Do those values persist after reloading etc? With the current setup I can save data in there that can be loaded back up again after reloading

2024-07-12 21:56 UTC, sirzento commented on src/ui/challenges-select-ui-handler.ts
> +    const headerBg = addWindow(this.scene, 0, 0, (this.scene.game.canvas.width / 6) - 2, 24);
It will look like the screenshots I posted. Without those changes the challenge text box was to small for displaying all the text of the challenge. Is it a proplem that I modified it?

2024-07-12 22:00 UTC, sirzento commented on src/phases.ts
> +        }
If you catch a pokemon and this challenge check returns false, it just wont get added to the party. So ingame it looks the same as every other catch with the exception that you wont have it in your team after that.

2024-07-12 22:05 UTC, sirzento commented on src/modifier/modifier-type.ts
> +export function getPlayerModifierTypeOptions(count: integer, party: PlayerPokemon[], gameMode: GameMode, modifierTiers?: ModifierTier[]): ModifierTypeOption[] {
Am I missing something or how can I access the gameMode object there via scene?

2024-07-12 22:12 UTC, Xavion3 commented on src/data/challenge.ts
> +      desc += i18next.t("challenges:nuzlocke.desc.2");
Similar text is fine, it's expected that some localization entries will be similar.

2024-07-12 22:14 UTC, Xavion3 commented on src/data/challenge.ts
> +    valid.value = !pokemon.legendary;
I'm just thinking, it feels weird to restrict say, Lugia but not Arceus is all. I think realistically this restriction could just not exist baked in, it has no bearing on the rules of a nuzlocke after all.

2024-07-12 22:15 UTC, Xavion3 commented on src/modifier/modifier-type.ts
> +export function getPlayerModifierTypeOptions(count: integer, party: PlayerPokemon[], gameMode: GameMode, modifierTiers?: ModifierTier[]): ModifierTypeOption[] {
Pokémon always have access to the scene.

2024-07-13 09:17 UTC, sirzento commented on src/phases.ts
> +        }
And yes, the first pokemon you catch each biome/10 waves will be added to the team and all others after that won't be added but you can still catch them if you want.

2024-07-13 10:52 UTC, sirzento commented on src/data/challenge.ts
> +    valid.value = !pokemon.legendary;
We could also restrict the other ones. That could actually be better than just legendaries. And yes, restricting legendaries is not part of the basic nuzlocke ruleset but it is listed as optional rule that people use to increase the difficulty. Same with the restriction of the healing phase. That would be the same as  a "no pokemon center" optional rule.

2024-07-13 19:33 UTC, sirzento commented on src/system/challenge-data.ts
> +    this.additionalData = source.additionalData;
After testing it again and looking more into the backend server code I have to say that you are right. I must have mixed up the ChallengeData field with another one and thought it should work like this. So the `ChallengeData` struct would only need this field to be added for it to work. Other challenges would not be affected by the change as they do not use this data.

But is it a problem that I have defined this field? I think it's not so bad to have a way to store challenge specific data like the information on which wave a Pokemon was last caught. Or what is your opinion on this?

2024-07-13 20:42 UTC, sirzento commented on src/system/challenge-data.ts
> +    this.additionalData = source.additionalData;
I think I'll change it so that only the FIRST Pokemon in each biome can be caught. Just like in a classic Nuzlocke Challenge. Then I would no longer need this field.

2024-07-13 23:20 UTC, sirzento commented
> For the new signatures, can we be clearer whether the apply functions are expected to set it to true or false for each? It looks like they all assume true, and set to false if unexpected, but just having some kind of note in the function documentation about that would be good.

I added some information to the comment above the apply functions that describes better what the boolean holder does. Thats what you meant right?

2024-08-14 02:22 UTC, DayKev commented
Can you fix the PR and then split this into multiple discrete challenges (ie: permadeath challenge, no auto-heal challenge, etc)?

2024-09-17 16:38 UTC, flx-sta commented
@sirzento I'm putting this into draft while you resolve those conflicts and work on the open comments.

---

Are you actually still actively working on this?

2024-09-18 07:23 UTC, DayKev commented
Ugh, trying to rebase this on current beta and it's just completely fucked. We really should have reverted the first beta merge and redid it correctly with rebasing... 
![](https://cdn.discordapp.com/emojis/1250574100384976997.webp?quality=lossless)

2024-09-18 09:21 UTC, DayKev commented
![image](https://github.com/user-attachments/assets/8f80d41f-200f-49d4-9f6e-01a2cc7c8611)

Now to check if I missed anything when manually copying the changes...

2024-09-18 10:43 UTC, DayKev commented
Draft update at #4311

2024-09-18 15:00 UTC, flx-sta commented
@DayKev so should this one be closed in favor of yours?

2024-09-18 15:05 UTC, DayKev commented
> @DayKev so should this one be closed in favor of yours?

Probably? I guess since the history is broken in this one it can't be used regardless.

2024-09-18 15:05 UTC, closed without merging