Make arena trap count as a lure ability
pagefaultgames/pokerogue pull request #245
Opened 2024-04-23 03:44 UTC by Akuma-Reiki

2024-04-23 03:45 UTC, Akuma-Reiki commented
Xavion told me to do it (kinda)

2024-04-23 06:33 UTC, amdevgwen commented
Hey can you add me as a contributor on this so I can push some updated code. Changed some templating and added user tags

2024-04-26 12:22 UTC, Xavion3 requested changes
Fix the merge conflicts and you're good to go

2024-04-26 17:49 UTC, Xavion3 approved these changes

2024-04-26 17:58 UTC, merged