[QoL] IV scanner update to hide the prompt and let you see the stats mid battle on the stats screen
pagefaultgames/pokerogue pull request #2451
Opened 2024-06-20 12:03 UTC by Opaque02

## What are the changes?
The IV scanner has been updated in two ways - the first is a setting that will allow you to disable the IV scanner prompt and all associated parts (animation, message etc), and the second is to change the stat container labels to show green/gold for the IV mid battle to show if the stats of the pokemon are better than what you've currently got.

## Why am I doing these changes?
A lot of people on discord have mentioned this is a feature they wanted, so I decided to make it

## What did change?
The first option is a setting that enables or disables the prompt about scanning a pokemon's IV. This is under the "general" tab of the settings.

The second option is to change the labels of the stat container to be green or gold depending on the stat. The stats container will show you the same amount of IV updates that you would from the IV scanner - so if you have no scanners you won't see any updates, all the way up to seeing all 6 stats for 3 scanners. If the stat is better than what you have, it'll show green, whereas if it's perfect IV it'll show gold; this is so if you do have the prompts being skipped, you can still see if the stat is perfect. Lastly, if the stat is unknown (not enough scanners) or equal/worse than what you have, the label is white as usual.

TO DO: Since the battle stats container doesn't show HP, I still need to have a place to put HP. Apart from that, everything else is shown.

### Screenshots/Videos
Here is a screenshot of the settings screen showing the new setting:

![image](https://github.com/pagefaultgames/pokerogue/assets/66582645/fd1a9d34-0b39-4c5b-8be3-129595bb1d51)

Here is a screenshot of the stats screen in battle showing some stats and the IV scanner on screen:

![image](https://github.com/pagefaultgames/pokerogue/assets/66582645/07a33f04-ef82-41e9-8887-54c7982fb37b)

As you can see, the only stats that are better than what we have are attack and Sp. Atk. Since Sp. Atk is "Best" (i.e. 31), it shows up gold on the stats container. However, Atk is not "Best", so it shows up green. The Def for this pokemon isn't better than what we have, so it's white like usual. This is with 2 IV scanners, so only 4 stats are shown.

Below is an example with 2 IV scanners in a run showing the difference with the IV scanner setting on (current behaviour) and the IV scanner setting off:

https://github.com/pagefaultgames/pokerogue/assets/66582645/78d13d6d-8887-495c-bb47-3cc50a421690

Here's an example of a run where there's no IV scanners:

https://github.com/pagefaultgames/pokerogue/assets/66582645/356de0a7-82fb-4e09-8bb0-059efa353e03

Here's an example with 3 IV scanners:

https://github.com/pagefaultgames/pokerogue/assets/66582645/cc7f444a-77ac-4d8b-a80c-d4d8b8d32bba

Here's a double battle with 1 IV scanner while also going through different waves:

https://github.com/pagefaultgames/pokerogue/assets/66582645/e437235d-9af2-4847-a3d9-6791110db928

## How to test the changes?
Download the branch to play with the changes. When you're at the battle screen, you can open the stats container (default C) to see the changes. Also in the settings, there should be an option to turn the setting on/off to hide the IV prompts

You can also use any of the following overrides:

Line 32 - this will force a double battle:

`export const DOUBLE_BATTLE_OVERRIDE: boolean = true;`

Line 90 - this will let you choose a specific pokemon to fight against. For example, this is set to spawn a charizard, but you can change that to anything else to fight other things:

`export const OPP_SPECIES_OVERRIDE: Species | integer = Species.CHARIZARD;`

Line 99 - this will let you set the IVs of the enemy pokemon. It takes an array of 6 numbers, which, in order, are HP, Atk, Def, Sp. Atk, Sp. Def, Spd:

`export const OPP_IVS_OVERRIDE: integer | integer[] = [31, 24, 5, 3, 19, 16];`

Line 121 - this will give you 3 IV scanners. To change it, change the "count: 3" to "count: 1" or "count: 2":

`export const STARTING_MODIFIER_OVERRIDE: Array<ModifierOverride> = [{name: "IV_SCANNER", count: 3}];`

**NOTE:** If you want to get rid of your IV scanners, you have to revert this; changing the count to 0 will NOT work, so to have 0 IV scanners, you need to use:

`export const STARTING_MODIFIER_OVERRIDE: Array<ModifierOverride> = [];`

Also note that for the IV scanners, you'll need to start a new game to see the effects. At first it'll look like it didn't work, but you'll be given the choice to see the pokemon's IVs before the fight as usual.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-21 00:18 UTC, Kelvez commented
Do you think it is possible to add the possibility to see if the pokemon has better stats without having to press a key.
Maybe an icon next to the pokeball icon or a different color on the pokemon name or something else.
Be sure to not miss pokemon with better stats because we forgot to press the button.
And a big big thanks for implementing this feature 🙏. You dropped this 👑

2024-06-21 10:32 UTC, Opaque02 commented
@Kelvez - yay, I'm glad you like it so far! So, ui stuff usually has to be approved by devs, so I'd have to see if they're happy with another icon near the pokeball, but based on the conversations we had around this, I can't promise that they'd go for it - I think they want to try and keep it pretty contained with the stat container for this feature

2024-07-10 23:55 UTC, f-fsantos requested changes

2024-07-10 23:55 UTC, f-fsantos commented on src/locales/en/settings.ts
> +  "hideIvs": "Hide IV scanner",
Please add the keys in all the languages. You can reuse the english version, but make sure all the keys are there.

2024-07-10 23:55 UTC, f-fsantos commented on src/phases.ts
> +        if (enemyIvs[ivStat] > currentIvs[ivStat] && ivsToShow.indexOf(Number(ivStat)) >= 0) {
This behavior is fundamentally different from what exists today, you shouldn't be using your currentIv as a comparison point to change the UI, it should only be around the scanned values themselves. Try to keep the same logic that exists today to determine the color of IV (1,10,20,30,31).

2024-07-11 00:31 UTC, Opaque02 commented on src/phases.ts
> +        if (enemyIvs[ivStat] > currentIvs[ivStat] && ivsToShow.indexOf(Number(ivStat)) >= 0) {
@f-fsantos This was actually discussed in the discord with Temp and other members of the community. Currently I think the numbers you've got there are related to the wording - things like Good, Best, Fantastic etc - but the colour is just that if it's better than what you've currently got, it's green. [Here's](https://github.com/pagefaultgames/pokerogue/blob/01f6ec2ef301dee9a6bfddd8f2cee4f91bd11864/src/phases.ts#L5470) a link for the ScanIvsPhase where we go to the promptIvs method, which is [here](https://github.com/pagefaultgames/pokerogue/blob/01f6ec2ef301dee9a6bfddd8f2cee4f91bd11864/src/ui/battle-message-ui-handler.ts#L192). Within that, for each shown stat, we call [getIvDescriptor](https://github.com/pagefaultgames/pokerogue/blob/01f6ec2ef301dee9a6bfddd8f2cee4f91bd11864/src/ui/battle-message-ui-handler.ts#L216C74-L216C89), which gets the text and the colour for the IV. Finally, that [getIvDescriptor](https://github.com/pagefaultgames/pokerogue/blob/01f6ec2ef301dee9a6bfddd8f2cee4f91bd11864/src/ui/battle-message-ui-handler.ts#L230) method checks to see if the [IV stat of the enemy is better than what your pokemon's IVs are](https://github.com/pagefaultgames/pokerogue/blob/01f6ec2ef301dee9a6bfddd8f2cee4f91bd11864/src/ui/battle-message-ui-handler.ts#L237), and if so, it shows as TextStyle.SUMMARY_GREEN, otherwise it shows as the default TextStyle.SUMMARY colour. The numbers [1, 10, 20, 30, 31] are only used [to get the actual wording](https://github.com/pagefaultgames/pokerogue/blob/01f6ec2ef301dee9a6bfddd8f2cee4f91bd11864/src/ui/battle-message-ui-handler.ts#L242) of the stat, not the colour.

For this PR, we decided to make it so that if an IV can be shown and is better than what you've got, it'll show up as green, which is the same as what we've got in live, but if it's Best (31), it shows in gold as the feedback people were having was that they'd like to know a way to tell if an IV was Best (31) for a stat that people didn't have so that people can choose to catch it if they choose. Again these only show if it's better than what you've got, so if you've already got a 31 IV stat, it won't show up on an enemy

2024-07-11 08:03 UTC, Opaque02 commented on src/locales/en/settings.ts
> +  "hideIvs": "Hide IV scanner",
This should be fixed in the latest commit

2024-07-11 17:43 UTC, CodeTappert commented
Honestly i find this very confusing. Why not just show the same dialogue as when the scanner is activated the first time?

The colors are hard to distinct for people with color problems

2024-07-12 01:47 UTC, Opaque02 commented
> Honestly i find this very confusing. Why not just show the same dialogue as when the scanner is activated the first time?
> 
> The colors are hard to distinct for people with color problems

@CodeTappert do you mean the "Use IV scanner on {pokemon name}" prompt? The idea was to not show it so that you didn't have to wait through the animations and wait for it to scan, yet to still be able to see if an enemy pokemon has a better IV in case you want to catch it. For example, you may not care about catching most pokemon so you can turn the prompt off, but there may be some you still care about, so you can see it when you open the stats container.

When we were thinking of the colour, we didn't think about people with difficulties with colours. Do you have suggestions on some good colours we could use instead? Temp originally said green for a stat that's better than what you've got and gold for something at 31 IV so you can still tell when an IV is at max (since lots of people still want that, and without the prompt, we need two colours), but we can change it if there's more suitable colour choices

2024-07-12 06:45 UTC, CodeTappert commented
> > Honestly i find this very confusing. Why not just show the same dialogue as when the scanner is activated the first time?
> > 
> > The colors are hard to distinct for people with color problems
> 
> @CodeTappert do you mean the "Use IV scanner on {pokemon name}" prompt? The idea was to not show it so that you didn't have to wait through the animations and wait for it to scan, yet to still be able to see if an enemy pokemon has a better IV in case you want to catch it. For example, you may not care about catching most pokemon so you can turn the prompt off, but there may be some you still care about, so you can see it when you open the stats container.
> 
> When we were thinking of the colour, we didn't think about people with difficulties with colours. Do you have suggestions on some good colours we could use instead? Temp originally said green for a stat that's better than what you've got and gold for something at 31 IV so you can still tell when an IV is at max (since lots of people still want that, and without the prompt, we need two colours), but we can change it if there's more suitable colour choices

No i mean the result screen that is shown after the animation. Which has actual text

2024-07-12 07:03 UTC, CodeTappert commented
![image](https://github.com/user-attachments/assets/651fc06f-5128-40ea-8c89-8daf28a25277)

2024-07-12 08:50 UTC, Opaque02 commented
> > > Honestly i find this very confusing. Why not just show the same dialogue as when the scanner is activated the first time?
> > > The colors are hard to distinct for people with color problems
> > 
> > 
> > @CodeTappert do you mean the "Use IV scanner on {pokemon name}" prompt? The idea was to not show it so that you didn't have to wait through the animations and wait for it to scan, yet to still be able to see if an enemy pokemon has a better IV in case you want to catch it. For example, you may not care about catching most pokemon so you can turn the prompt off, but there may be some you still care about, so you can see it when you open the stats container.
> > When we were thinking of the colour, we didn't think about people with difficulties with colours. Do you have suggestions on some good colours we could use instead? Temp originally said green for a stat that's better than what you've got and gold for something at 31 IV so you can still tell when an IV is at max (since lots of people still want that, and without the prompt, we need two colours), but we can change it if there's more suitable colour choices
> 
> No i mean the result screen that is shown after the animation. Which has actual text

The problem is showing that on double battles, there's no easy way to show which is which. Also people wanted something unrelated to the current IV prompt so we ended up with this design

2024-07-23 05:28 UTC, CodeTappert commented
The feature works fine...But as i said. I dont like that is only colours an no text. But since this is only a problem for people like me i will approve it.

2024-07-23 05:28 UTC, CodeTappert approved these changes

2024-08-07 20:48 UTC, closed without merging

2024-08-07 20:48 UTC, torranx commented
Closing because of the remade PR linked, if this is a mistake, please ping me.