[Enhancment] Added a bgmBar to show the name of the track once music is played
pagefaultgames/pokerogue pull request #2457
Opened 2024-06-20 14:54 UTC by CodeTappert

## What are the changes?

## Why am I doing these changes?

## What did change?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-20 16:32 UTC, CodeTappert commented
On the todo list for that is:
- Make it a setting
- Have well sounding (and maybe localized) names for all tracks.

2024-06-21 09:11 UTC, CodeTappert commented on src/ui/ability-bar.ts
> +    console.log("Ability Bar: Position and Size", this.x, this.y, this.width, this.height);
```suggestion
```

2024-06-21 10:45 UTC, Adri1 reviewed
Added French translation

2024-06-21 10:45 UTC, Adri1 commented on src/locales/fr/settings.ts
> +  "showBgmBar": "Show Music Names",
```suggestion
  "showBgmBar": "Montrer titre de la musique",
```

2024-06-21 10:45 UTC, Adri1 commented on src/locales/fr/bgm-name.ts
> +  "battle_plasma_grunt": "BW Team Plasma Battle",
```suggestion
  "battle_kanto_champion": "N2B2 - Vs. Maitre de Kanto",
  "battle_johto_champion": "N2B2 - Vs. Maitre de Johto",
  "battle_hoenn_champion": "N2B2 - Vs. Maitre de Hoenn",
  "battle_sinnoh_champion": "N2B2 - Vs. Maitresse de Sinnoh",
  "battle_champion_alder": "NB - Vs. Maitre d’Unys",
  "battle_champion_iris": "N2B2 - Vs. Maitresse d’Unys",
  "battle_kalos_champion": "XY - Maitresse de Kalos",
  "battle_alola_champion": "USUL - Maitre d’Alola",
  "battle_galar_champion": "ÉB - Maitre de Galar",
  "battle_champion_geeta": "ÉV - Vs. Alisma la Maitresse",
  "battle_champion_nemona": "ÉV - Vs. Menzi la Maitresse",
  "battle_champion_kieran": "ÉV - Vs. Kassis le Maitre",
  "battle_hoenn_elite": "ROSA - Vs. Conseil 4",
  "battle_unova_elite": "NB - Vs. Conseil 4",
  "battle_kalos_elite": "XY - Vs. Conseil 4",
  "battle_alola_elite": "SL  -Vs. Conseil 4",
  "battle_galar_elite": "ÉB - Vs. Tournoi des Champions",
  "battle_paldea_elite": "ÉV - Vs. Conseil 4",
  "battle_bb_elite": "ÉV - Vs. Conseil 4 de l’Institut Myrtille",
  "battle_final_encounter": "PMD ÉSDX - Vs. Rayquaza",
  "battle_final": "NB - Vs. Ghetis",
  "battle_kanto_gym": "N2B2 - Vs. Champion·ne d’Arène de Kanto",
  "battle_johto_gym": "N2B2 - Vs. Champion·ne d’Arène de Johto",
  "battle_hoenn_gym": "N2B2 - Vs. Champion·ne d’Arène de Hoenn",
  "battle_sinnoh_gym": "N2B2 - Vs. Champion·ne d’Arène de Sinnoh",
  "battle_unova_gym": "NB - Vs. Champion·ne d’Arène d’Unova",
  "battle_kalos_gym": "XY - Vs. Champion·ne d’Arène de Kalos",
  "battle_galar_gym": "ÉB - Vs. Champion·ne d’Arène de Galar",
  "battle_paldea_gym": "ÉV - Vs. Champion·ne d’Arène de Paldea",
  "battle_legendary_kanto": "XY - Vs. Légendaire de Kanto",
  "battle_legendary_raikou": "HGSS - Vs. Raikou",
  "battle_legendary_entei": "HGSS - Vs. Entei",
  "battle_legendary_suicune": "HGSS - Vs. Suicune",
  "battle_legendary_lugia": "HGSS - Vs. Lugia",
  "battle_legendary_ho_oh": "HGSS - Vs. Ho-oh",
  "battle_legendary_regis_g5": "N2B2 - Vs. Colosses Légendaires",
  "battle_legendary_regis_g6": "ROSA - Vs. Colosses Légendaires",
  "battle_legendary_gro_kyo": "ROSA - Vs. Groudon/Kyogre",
  "battle_legendary_rayquaza": "ROSA - Vs. Rayquaza",
  "battle_legendary_deoxys": "ROSA - Vs. Deoxys",
  "battle_legendary_lake_trio": "ROSA - Vs. Gardiens des Lacs",
  "battle_legendary_sinnoh": "ROSA - Vs. Légendaire de Sinnoh",
  "battle_legendary_dia_pal": "ROSA - Vs. Dialga/Palkia",
  "battle_legendary_giratina": "ROSA - Vs. Giratina",
  "battle_legendary_arceus": "HGSS - Vs. Arceus",
  "battle_legendary_unova": "NB - Vs. Légendaire d’Unys",
  "battle_legendary_kyurem": "NB - Vs. Kyurem",
  "battle_legendary_res_zek": "NB - Vs. Reshiram/Zekrom",
  "battle_legendary_xern_yvel": "XY - Vs. Xerneas/Yveltal",
  "battle_legendary_tapu": "SL - Vs. Divinités gardiennes d’Alola",
  "battle_legendary_sol_lun": "SL Vs. Solgaleo/Lunala",
  "battle_legendary_ub": "SL - Vs. Ultra-Chimère",
  "battle_legendary_dusk_dawn": "USUL - Vs. Necrozma Crinière du Couchant/Ailes de l’Aurore",
  "battle_legendary_ultra_nec": "USUL - Vs. Ultra-Necrozma",
  "battle_legendary_zac_zam": "ÉB - Vs. Zacian/ Zamazenta",
  "battle_legendary_glas_spec": "ÉB - Vs. Blizzeval/Spectreval",
  "battle_legendary_calyrex": "ÉB - Vs. Sylveroy",
  "battle_legendary_birds_galar": "ÉB - Vs. Oiseaux Légendaires de Galar",
  "battle_legendary_ruinous": "ÉV - Vs. Trésors du fléau",
  "battle_legendary_loyal_three": "ÉV - Vs. Adoramis",
  "battle_legendary_ogerpon": "ÉV - Vs. Ogerpon",
  "battle_legendary_terapagos": "ÉV - Vs. Terapagos",
  "battle_legendary_pecharunt": "ÉV - Vs. Pêchaminus",
  "battle_rival": "NB - Vs. Rival",
  "battle_rival_2": "NB - Vs. N",
  "battle_rival_3": "NB - Combat final Vs. N",
  "battle_trainer": "NB - Vs. Dresseur·euse",
  "battle_wild": "NB - Vs. Pokémon sauvage",
  "battle_wild_strong": "NB - Vs. Pokémon puissant sauvage",
  "end_summit": "PMD ÉSDX - Tour Céleste",
  "battle_plasma_grunt": "NB - Vs. Team Plasma",
```

2024-06-21 11:48 UTC, CodeTappert commented on src/locales/de/bgm-name.ts
> +  "battle_plasma_grunt": "BW Team Plasma Battle",
```suggestion
  "missing_entries" : "{{name}}",
  "battle_kanto_champion": "S2W2 Vs. Kanto Champion",
  "battle_johto_champion": "S2W2 Vs. Johto Champion",
  "battle_hoenn_champion": "S2W2 Vs. Hoenn Champion",
  "battle_sinnoh_champion": "S2W2 Vs. Champion Cynthia",
  "battle_champion_alder": "SW Vs. Champion Lauro",
  "battle_champion_iris": "S2W2 Vs. Champion Lilia",
  "battle_kalos_champion": "XY Vs. Champion Diantha",
  "battle_alola_champion": "USUM Vs. Alola Champion",
  "battle_galar_champion": "SWSH Vs. Champion Delion",
  "battle_champion_geeta": "KAPU Vs. Champion Sagaria",
  "battle_champion_nemona": "KAPU Vs. Champion Nemila",
  "battle_champion_kieran": "KAPU Vs. Jo",
  "battle_hoenn_elite": "ORAS Vs. Hoenn Top Vier",
  "battle_unova_elite": "SW Vs. Einall Top Vier",
  "battle_kalos_elite": "XY Vs. Kalos Top Vier",
  "battle_alola_elite": "SM Vs. Alola Top Vier",
  "battle_galar_elite": "SWSH Galar Champ-Cup",
  "battle_paldea_elite": "KAPU Vs. Paldea Top Vier",
  "battle_bb_elite": "KAPU Vs. Blaubeer-Top-Vier",
  "battle_final_encounter": "PMDDX Rayquazas Domäne",
  "battle_final": "SW Vs. G-Cis",
  "battle_kanto_gym": "S2W2 Vs. Kanto Arenaleiter",
  "battle_johto_gym": "S2W2 Vs. Johto Arenaleiter",
  "battle_hoenn_gym": "S2W2 Vs. Hoenn Arenaleiter",
  "battle_sinnoh_gym": "S2W2 Vs. Sinnoh Arenaleiter",
  "battle_unova_gym": "SW Vs. Einall Arenaleiter",
  "battle_kalos_gym": "XY Vs. Kalos Arenaleiter",
  "battle_galar_gym": "SWSH Vs. Galar Arenaleiter",
  "battle_paldea_gym": "KAPU Vs. Paldea Arenaleiter",
  "battle_legendary_kanto": "XY Vs. Legendäres Kanto Pokémon",
  "battle_legendary_raikou": "HGSS Vs. Raikou",
  "battle_legendary_entei": "HGSS Vs. Entei",
  "battle_legendary_suicune": "HGSS Vs. Suicune",
  "battle_legendary_lugia": "HGSS Vs. Lugia",
  "battle_legendary_ho_oh": "HGSS Vs. Ho-oh",
  "battle_legendary_regis_g5": "S2W2 Vs. Legendäre Giganten",
  "battle_legendary_regis_g6": "ORAS Vs. Legendäre Giganten",
  "battle_legendary_gro_kyo": "ORAS Vs. Groudon & Kyogre",
  "battle_legendary_rayquaza": "ORAS Vs. Rayquaza",
  "battle_legendary_deoxys": "ORAS Vs. Deoxys",
  "battle_legendary_lake_trio": "ORAS Vs. Seen-Trio",
  "battle_legendary_sinnoh": "ORAS Vs. Legendäres Sinnoh Pokémon",
  "battle_legendary_dia_pal": "ORAS Vs. Dialga & Palkia",
  "battle_legendary_giratina": "ORAS Vs. Giratina",
  "battle_legendary_arceus": "HGSS Vs. Arceus",
  "battle_legendary_unova": "SW Vs. Legendäres Einall Pokémon",
  "battle_legendary_kyurem": "SW Vs. Kyurem",
  "battle_legendary_res_zek": "SW Vs. Reshiram & Zekrom",
  "battle_legendary_xern_yvel": "XY Vs. Xerneas & Yveltal",
  "battle_legendary_tapu": "SM Vs. Kapu",
  "battle_legendary_sol_lun": "SM Vs. Solgaleo & Lunala",
  "battle_legendary_ub": "SM Vs. Ultrabestie",
  "battle_legendary_dusk_dawn": "USUM Vs. Abendmähne- & Morgenschwingen-Necrozma",
  "battle_legendary_ultra_nec": "USUM Vs. Ultra-Necrozma",
  "battle_legendary_zac_zam": "SWSH Vs. Zacian & Zamazenta",
  "battle_legendary_glas_spec": "SWSH Vs. Polaross & Phantoross",
  "battle_legendary_calyrex": "SWSH Vs. Coronospa",
  "battle_legendary_birds_galar": "SWSH Vs. Legendäre Galar-Vögel",
  "battle_legendary_ruinous": "KAPU Vs. Schätze des Unheils",
  "battle_legendary_loyal_three": "KAPU Drei Gefährten",
  "battle_legendary_ogerpon": "KAPU Vs. Ogerpon",
  "battle_legendary_terapagos": "KAPU Vs. Terapagos",
  "battle_legendary_pecharunt": "KAPU Vs. Infamomo",
  "battle_rival": "SW Vs. Rivale",
  "battle_rival_2": "SW Vs. N",
  "battle_rival_3": "SW Vs. N (Finale)",
  "battle_trainer": "SW Vs. Trainer",
  "battle_wild": "SW Vs. Wilde Pokémon",
  "battle_wild_strong": "SW Vs. Starke Wilde Pokémon",
  "end_summit": "PMDDX Gipfel des Himmelturms",
  "battle_plasma_grunt": "SW Vs. Team Plasma Rüpel",
```

2024-06-21 13:29 UTC, sodaMelon commented
I will add Korean translation. Wait a moment

2024-06-21 14:10 UTC, sodaMelon commented on src/locales/en/bgm-name.ts
> +  "battle_plasma_grunt": "BW Team Plasma Battle",
```suggestion
  "battle_kanto_champion": "BW2 관동 챔피언 배틀",
  "battle_johto_champion": "BW2 성도 챔피언 배틀",
  "battle_hoenn_champion": "BW2 호연 챔피언 배틀",
  "battle_sinnoh_champion": "BW2 신오 챔피언 배틀",
  "battle_champion_alder": "BW 하나 챔피언 배틀",
  "battle_champion_iris": "BW2 하나 챔피언 배틀",
  "battle_kalos_champion": "XY 칼로스 챔피언 배틀",
  "battle_alola_champion": "USUM 알로라 챔피언 배틀",
  "battle_galar_champion": "SWSH 가라르 챔피언 배틀",
  "battle_champion_geeta": "SV 챔피언 테사 배틀",
  "battle_champion_nemona": "SV 챔피언 네모 배틀",
  "battle_champion_kieran": "SV 챔피언 카지 배틀",
  "battle_hoenn_elite": "ORAS 사천왕 배틀",
  "battle_unova_elite": "BW 사천왕 배틀",
  "battle_kalos_elite": "XY 사천왕 배틀",
  "battle_alola_elite": "SM 사천왕 배틀",
  "battle_galar_elite": "SWSH 리그 토너먼트 배틀",
  "battle_paldea_elite": "SV 사천왕 배틀",
  "battle_bb_elite": "SV 블루베리 리그 사천왕 배틀",
  "battle_final_encounter": "불가사의 던전 구조대 DX 레쿠쟈의 영역",
  "battle_final": "BW 게치스 배틀",
  "battle_kanto_gym": "BW2 관동 체육관 배틀",
  "battle_johto_gym": "BW2 성도 체육관 배틀",
  "battle_hoenn_gym": "BW2 호연 체육관 배틀",
  "battle_sinnoh_gym": "BW2 신오 체육관 배틀",
  "battle_unova_gym": "BW 하나 체육관 배틀",
  "battle_kalos_gym": "XY 칼로스 체육관 배틀",
  "battle_galar_gym": "SWSH 가라르 체육관 배틀",
  "battle_paldea_gym": "SV 팔데아 체육관 배틀",
  "battle_legendary_kanto": "XY 관동 전설 조우 배틀",
  "battle_legendary_raikou": "HGSS 라이코 배틀",
  "battle_legendary_entei": "HGSS 엔테이 배틀",
  "battle_legendary_suicune": "HGSS 스이쿤 배틀",
  "battle_legendary_lugia": "HGSS 루기아 배틀",
  "battle_legendary_ho_oh": "HGSS 칠색조 배틀",
  "battle_legendary_regis_g5": "BW2 레지시리즈 배틀",
  "battle_legendary_regis_g6": "ORAS 레지시리즈 배틀",
  "battle_legendary_gro_kyo": "ORAS 그란돈 & 가이오가 배틀",
  "battle_legendary_rayquaza": "ORAS 레쿠쟈 배틀",
  "battle_legendary_deoxys": "ORAS 데오키시스 배틀",
  "battle_legendary_lake_trio": "ORAS 호수의 수호신 배틀",
  "battle_legendary_sinnoh": "ORAS 신오 전설 조우 배틀",
  "battle_legendary_dia_pal": "ORAS 디아루가 & 펄기아 배틀",
  "battle_legendary_giratina": "ORAS 기라티나 배틀",
  "battle_legendary_arceus": "HGSS 아르세우스 배틀",
  "battle_legendary_unova": "BW 하나 전설 조우 배틀",
  "battle_legendary_kyurem": "BW 큐레무 배틀",
  "battle_legendary_res_zek": "BW 레시라무 & 제크로무 배틀",
  "battle_legendary_xern_yvel": "XY 제르네아스 & 이벨타르 배틀",
  "battle_legendary_tapu": "SM 섬 수호신 배틀",
  "battle_legendary_sol_lun": "SM 솔가레오 & 루나아라 배틀",
  "battle_legendary_ub": "SM 울트라비스트 배틀",
  "battle_legendary_dusk_dawn": "USUM 황혼의 갈기 & 새벽의 날개 네크로즈마 배틀",
  "battle_legendary_ultra_nec": "USUM 울트라 네크로즈마 배틀",
  "battle_legendary_zac_zam": "SWSH 자시안 & 자마젠타 배틀",
  "battle_legendary_glas_spec": "SWSH 블리자포스 & 레이스포스 배틀",
  "battle_legendary_calyrex": "SWSH 버드렉스 배틀",
  "battle_legendary_birds_galar": "SWSH 가라르 전설의 새 배틀",
  "battle_legendary_ruinous": "SV 재앙의 보물 배틀",
  "battle_legendary_loyal_three": "SV 세벗들 배틀",
  "battle_legendary_ogerpon": "SV 오거폰 배틀",
  "battle_legendary_terapagos": "SV 테라파고스 배틀",
  "battle_legendary_pecharunt": "SV 복숭악동 배틀",
  "battle_rival": "BW 라이벌 배틀",
  "battle_rival_2": "BW N 배틀",
  "battle_rival_3": "BW 최종전 N 배틀",
  "battle_trainer": "BW 트레이너 배틀",
  "battle_wild": "BW 야생 포켓몬 배틀",
  "battle_wild_strong": "BW 강한 야생 포켓몬 조우 배틀",
  "end_summit": "불가사의 던전 구조대 DX 천공의 탑 꼭대기",
  "battle_plasma_grunt": "BW 플라스마단 배틀",
```

2024-06-21 14:11 UTC, sodaMelon commented on src/locales/ko/bgm-name.ts
> +  "battle_plasma_grunt": "BW Team Plasma Battle",
```suggestion
  "battle_kanto_champion": "BW2 관동 챔피언 배틀",
  "battle_johto_champion": "BW2 성도 챔피언 배틀",
  "battle_hoenn_champion": "BW2 호연 챔피언 배틀",
  "battle_sinnoh_champion": "BW2 신오 챔피언 배틀",
  "battle_champion_alder": "BW 하나 챔피언 배틀",
  "battle_champion_iris": "BW2 하나 챔피언 배틀",
  "battle_kalos_champion": "XY 칼로스 챔피언 배틀",
  "battle_alola_champion": "USUM 알로라 챔피언 배틀",
  "battle_galar_champion": "SWSH 가라르 챔피언 배틀",
  "battle_champion_geeta": "SV 챔피언 테사 배틀",
  "battle_champion_nemona": "SV 챔피언 네모 배틀",
  "battle_champion_kieran": "SV 챔피언 카지 배틀",
  "battle_hoenn_elite": "ORAS 사천왕 배틀",
  "battle_unova_elite": "BW 사천왕 배틀",
  "battle_kalos_elite": "XY 사천왕 배틀",
  "battle_alola_elite": "SM 사천왕 배틀",
  "battle_galar_elite": "SWSH 리그 토너먼트 배틀",
  "battle_paldea_elite": "SV 사천왕 배틀",
  "battle_bb_elite": "SV 블루베리 리그 사천왕 배틀",
  "battle_final_encounter": "불가사의 던전 구조대 DX 레쿠쟈의 영역",
  "battle_final": "BW 게치스 배틀",
  "battle_kanto_gym": "BW2 관동 체육관 배틀",
  "battle_johto_gym": "BW2 성도 체육관 배틀",
  "battle_hoenn_gym": "BW2 호연 체육관 배틀",
  "battle_sinnoh_gym": "BW2 신오 체육관 배틀",
  "battle_unova_gym": "BW 하나 체육관 배틀",
  "battle_kalos_gym": "XY 칼로스 체육관 배틀",
  "battle_galar_gym": "SWSH 가라르 체육관 배틀",
  "battle_paldea_gym": "SV 팔데아 체육관 배틀",
  "battle_legendary_kanto": "XY 관동 전설 조우 배틀",
  "battle_legendary_raikou": "HGSS 라이코 배틀",
  "battle_legendary_entei": "HGSS 엔테이 배틀",
  "battle_legendary_suicune": "HGSS 스이쿤 배틀",
  "battle_legendary_lugia": "HGSS 루기아 배틀",
  "battle_legendary_ho_oh": "HGSS 칠색조 배틀",
  "battle_legendary_regis_g5": "BW2 레지시리즈 배틀",
  "battle_legendary_regis_g6": "ORAS 레지시리즈 배틀",
  "battle_legendary_gro_kyo": "ORAS 그란돈 & 가이오가 배틀",
  "battle_legendary_rayquaza": "ORAS 레쿠쟈 배틀",
  "battle_legendary_deoxys": "ORAS 데오키시스 배틀",
  "battle_legendary_lake_trio": "ORAS 호수의 수호신 배틀",
  "battle_legendary_sinnoh": "ORAS 신오 전설 조우 배틀",
  "battle_legendary_dia_pal": "ORAS 디아루가 & 펄기아 배틀",
  "battle_legendary_giratina": "ORAS 기라티나 배틀",
  "battle_legendary_arceus": "HGSS 아르세우스 배틀",
  "battle_legendary_unova": "BW 하나 전설 조우 배틀",
  "battle_legendary_kyurem": "BW 큐레무 배틀",
  "battle_legendary_res_zek": "BW 레시라무 & 제크로무 배틀",
  "battle_legendary_xern_yvel": "XY 제르네아스 & 이벨타르 배틀",
  "battle_legendary_tapu": "SM 섬 수호신 배틀",
  "battle_legendary_sol_lun": "SM 솔가레오 & 루나아라 배틀",
  "battle_legendary_ub": "SM 울트라비스트 배틀",
  "battle_legendary_dusk_dawn": "USUM 황혼의 갈기 & 새벽의 날개 네크로즈마 배틀",
  "battle_legendary_ultra_nec": "USUM 울트라 네크로즈마 배틀",
  "battle_legendary_zac_zam": "SWSH 자시안 & 자마젠타 배틀",
  "battle_legendary_glas_spec": "SWSH 블리자포스 & 레이스포스 배틀",
  "battle_legendary_calyrex": "SWSH 버드렉스 배틀",
  "battle_legendary_birds_galar": "SWSH 가라르 전설의 새 배틀",
  "battle_legendary_ruinous": "SV 재앙의 보물 배틀",
  "battle_legendary_loyal_three": "SV 세벗들 배틀",
  "battle_legendary_ogerpon": "SV 오거폰 배틀",
  "battle_legendary_terapagos": "SV 테라파고스 배틀",
  "battle_legendary_pecharunt": "SV 복숭악동 배틀",
  "battle_rival": "BW 라이벌 배틀",
  "battle_rival_2": "BW N 배틀",
  "battle_rival_3": "BW 최종전 N 배틀",
  "battle_trainer": "BW 트레이너 배틀",
  "battle_wild": "BW 야생 포켓몬 배틀",
  "battle_wild_strong": "BW 강한 야생 포켓몬 조우 배틀",
  "end_summit": "불가사의 던전 구조대 DX 천공의 탑 꼭대기",
  "battle_plasma_grunt": "BW 플라스마단 배틀",
```

2024-06-21 14:13 UTC, sodaMelon reviewed
added Korean translation.
my suggestions exist in both top and bottom. ( maybe i did mistake when wrote review) 
when you merge them, check them too.

2024-06-21 14:13 UTC, sodaMelon commented on src/locales/ko/settings.ts
> +  "showBgmBar": "Show Music Names",
```suggestion
  "showBgmBar": "BGM 제목 보여주기",
```

2024-06-21 14:25 UTC, sodaMelon approved these changes

2024-06-21 14:56 UTC, Adri1 approved these changes

2024-06-22 15:00 UTC, Adri1 reviewed
French translations

2024-06-22 15:00 UTC, Adri1 commented on src/locales/fr/bgm-name.ts
> +  "title": "PMD EoS Top Menu Theme",
```suggestion
  "abyss": "PDM EdS - Cratère Obscur",
  "badlands": "PDM EdS - Vallée Stérile",
  "beach": "PDM EdS - Falaise Trempée",
  "cave": "PDM EdS - Pic Céleste (grotte)",
  "construction_site": "PDM EdS - Carrière Rocher",
  "desert": "PDM EdS - Désert du Nord",
  "dojo": "PDM EdS - Dojo Ossatueur",
  "end": "PDM EdS - Tour Céleste",
  "factory": "PDM EdS - Ruines Cachées",
  "fairy_cave": "PDM EdS - Caverne Étoile",
  "forest": "PDM EdS - Forêt Crépuscule",
  "grass": "PDM EdS - Bois aux Pommes",
  "graveyard": "PDM EdS - Forêt Trompeuse",
  "ice_cave": "PDM EdS - Montagne Glacier",
  "island": "PDM EdS - Côte Escarpée",
  //"jungle": "jungle", // The composer thinks about a more creative name
  //"labratory": "labratory", // The composer thinks about a more creative name
  "lake": "PDM EdS - Caverne Cristal",
  "meadow": "PDM EdS - Pic Céleste (forêt)",
  //"metropolis": "metropolis", // The composer thinks about a more creative name
  "mountain": "PDM EdS - Mt Corne",
  "plains": "PDM EdS - Pic Céleste (prairie)",
  "power_plant": "PDM EdS - Plaines Élek",
  "ruins": "PDM EdS - Ruine Scellée",
  "sea": "PDM EdS - Caverne Saline",
  "seabed": "PDM EdS - Caverne Saline profondeurs",
  "slum": "PDM EdS - Pic Céleste (côte)",
  "snowy_forest": "PDM EdS - Pic Céleste (plaine enneigée)",
  "space": "PDM EdS - Ravin Aubaine",
  "swamp": "PDM EdS - Mer Fermée",
  "tall_grass": "PDM EdS - Forêt Brumeuse",
  "temple": "PDM EdS - Grotte Égide",
  "town": "PDM EdS - Donjon aléatoire - Thème 3",
  "volcano": "PDM EdS - Grotte Étuve",
  "wasteland": "PDM EdS - Terres Illusoires",

  // Encounter
  "encounter_ace_trainer": "NB - Regards croisés (Topdresseur·euse)",
  "encounter_backpacker": "NB - Regards croisés (Randonneur·euse)",
  "encounter_clerk": "NB - Regards croisés (Employé·e)",
  "encounter_cyclist": "NB - Regards croisés (Cycliste)",
  "encounter_lass": "NB - Regards croisés (Fillette)",
  "encounter_parasol_lady": "NB - Regards croisés (Sœur Parasol)",
  "encounter_pokefan": "NB - Regards croisés (Pokéfan)",
  "encounter_psychic": "NB - Regards croisés (Kinésiste)",
  "encounter_rich": "NB - Regards croisés (Gentleman)",
  "encounter_rival": "NB - Tcheren",
  "encounter_roughneck": "NB - Regards croisés (Loubard)",
  "encounter_scientist": "NB - Regards croisés (Scientifique)",
  "encounter_twins": "NB - Regards croisés (Jumelles)",
  "encounter_youngster": "NB - Regards croisés (Gamin)",

  // Other
  "heal": "NB - Soin de Pokémon",
  "menu": "PDM EdS - Bienvenue dans le monde de Pokémon !",
  "title": "PDM EdS - Menu Principal",
```

2024-06-23 02:31 UTC, sodaMelon reviewed
added korean localization  about biome, encounter, and other.
### ref:  
- for unnamed trainer [korean wiki](https://pokemon.fandom.com/ko/wiki/%ED%8F%AC%EC%BC%93%EB%AA%AC_%ED%8A%B8%EB%A0%88%EC%9D%B4%EB%84%88/%EC%A2%85%EB%A5%98)
- for PMD series [korean-japanese](https://pokemon.fandom.com/ko/wiki/%ED%8F%AC%EC%BC%93%EB%AA%AC%EC%8A%A4%ED%84%B0_%EC%84%B8%EA%B3%84_(%EB%B6%88%EA%B0%80%EC%82%AC%EC%9D%98_%EB%8D%98%EC%A0%84)#%ED%83%90%ED%97%98%EB%8C%80), [japanese-english](https://bulbapedia.bulbagarden.net/wiki/Hidden_Land)

2024-06-23 02:31 UTC, sodaMelon commented on src/locales/ko/bgm-name.ts
> +  "title": "PMD EoS Top Menu Theme",
```suggestion
  "abyss": "불가사의 던전 하늘의 탐험대 어둠의 화구",
  "badlands": "불가사의 던전 하늘의 탐험대 불모의 계곡",
  "beach": "불가사의 던전 하늘의 탐험대 축축한 암반",
  "cave": "불가사의 던전 하늘의 탐험대 하늘 꼭대기 동굴",
  "construction_site": "불가사의 던전 하늘의 탐험대 바위 채석장",
  "desert": "불가사의 던전 하늘의 탐험대 북쪽 사막",
  "dojo": "불가사의 던전 하늘의 탐험대 텅구리 도장",
  "end": "불가사의 던전 구조대DX 천공의 탑",
  "factory": "불가사의 던전 하늘의 탐험대 숨겨진 유적",
  "fairy_cave": "불가사의 던전 하늘의 탐험대 별의 동굴",
  "forest": "불가사의 던전 하늘의 탐험대 검은 숲",
  "grass": "불가사의 던전 하늘의 탐험대 사과의 숲",
  "graveyard": "불가사의 던전 하늘의 탐험대 신비의 숲",
  "ice_cave": "불가사의 던전 하늘의 탐험대 광대한 얼음산",
  "island": "불가사의 던전 하늘의 탐험대 연안의 암반",
  //"jungle": "jungle", // The composer thinks about a more creative name
  //"labratory": "labratory", // The composer thinks about a more creative name
  "lake": "불가사의 던전 하늘의 탐험대 수정 동굴",
  "meadow": "불가사의 던전 하늘의 탐험대 하늘 꼭대기 숲",
  //"metropolis": "metropolis", // The composer thinks about a more creative name
  "mountain": "불가사의 던전 하늘의 탐험대 뿔산",
  "plains": "불가사의 던전 하늘의 탐험대 하늘 꼭대기 초원",
  "power_plant": "불가사의 던전 하늘의 탐험대 일렉트릭 평원",
  "ruins": "불가사의 던전 하늘의 탐험대 봉인의 암반",
  "sea": "불가사의 던전 하늘의 탐험대 바닷가 동굴",
  "seabed": "불가사의 던전 하늘의 탐험대 바닷가 동굴(저층)",
  "slum": "불가사의 던전 하늘의 탐험대 하늘 꼭대기 해변",
  "snowy_forest": "불가사의 던전 하늘의 탐험대 하늘 꼭대기 설원",
  "space": "불가사의 던전 하늘의 탐험대 행운 협곡",
  "swamp": "불가사의 던전 하늘의 탐험대 폐쇄되어진 바다",
  "tall_grass": "불가사의 던전 하늘의 탐험대 짙은 안개의 숲",
  "temple": "불가사의 던전 하늘의 탐험대 파수꾼의 동굴",
  "town": "불가사의 던전 하늘의 탐험대 랜덤 던전 테마 3",
  "volcano": "불가사의 던전 하늘의 탐험대 열수의 동굴",
  "wasteland": "불가사의 던전 하늘의 탐험대 환상의 대지",

  // Encounter
  "encounter_ace_trainer": "BW 눈이 마주치면 승부! (엘리트 트레이너)",
  "encounter_backpacker": "BW 눈이 마주치면 승부! (등산가)",
  "encounter_clerk": "BW 눈이 마주치면 승부! (회사원)",
  "encounter_cyclist": "BW 눈이 마주치면 승부! (사이클링)",
  "encounter_lass": "BW 눈이 마주치면 승부! (짧은 치마)",
  "encounter_parasol_lady": "BW 눈이 마주치면 승부! (파라솔 아가씨)",
  "encounter_pokefan": "BW 눈이 마주치면 승부! (애호가클럽)",
  "encounter_psychic": "BW 눈이 마주치면 승부! (초능력자)",
  "encounter_rich": "BW 눈이 마주치면 승부! (신사)",
  "encounter_rival": "BW 체렌",
  "encounter_roughneck": "BW 눈이 마주치면 승부! (빡빡이)",
  "encounter_scientist": "BW 눈이 마주치면 승부! (연구원)",
  "encounter_twins": "BW 눈이 마주치면 승부! (쌍둥이)",
  "encounter_youngster": "BW 눈이 마주치면 승부! (반바지 꼬마)",

  // Other
  "heal": "BW 포켓몬 센터",
  "menu": "불가사의 던전 하늘의 탐험대 포켓몬 세계에 온 것을 환영한다!",
  "title": "불가사의 던전 하늘의 탐험대 메뉴 테마",
```

2024-06-23 05:50 UTC, 40chyan commented on src/locales/zh_CN/settings.ts
> +  "showBgmBar": "Show Music Names",
```suggestion
  "showBgmBar": "显示音乐名称",
```

2024-06-23 08:02 UTC, 40chyan commented on src/locales/zh_CN/bgm-name.ts
> +  "title": "PMD EoS Top Menu Theme",
```suggestion
  "missing_entries" : "{{name}}",
  "battle_kanto_champion": "黑2白2「决战！关都冠军」",
  "battle_johto_champion": "黑2白2「决战！城都冠军」",
  "battle_hoenn_champion": "黑2白2「决战！丰缘冠军」",
  "battle_sinnoh_champion": "黑2白2「决战！神奥冠军」",
  "battle_champion_alder": "黑白「决战！合众冠军」",
  "battle_champion_iris": "黑2白2「决战！合众冠军」",
  "battle_kalos_champion": "XY「决战！卡洛斯冠军」",
  "battle_alola_champion": "究极日月「顶上决战！」",
  "battle_galar_champion": "剑盾「决战！伽勒尔冠军」",
  "battle_champion_geeta": "朱紫「决战！帕底亚冠军也慈」",
  "battle_champion_nemona": "朱紫「决战！帕底亚冠军尼莫」",
  "battle_champion_kieran": "朱紫「决战！蓝莓学园冠军乌栗」",
  "battle_hoenn_elite": "Ω红宝石α蓝宝石 「战斗！丰缘四天王」",
  "battle_unova_elite": "黑白 「战斗！合众四天王」",
  "battle_kalos_elite": "XY「战斗！卡洛斯四天王」",
  "battle_alola_elite": "日月「战斗！阿罗拉四天王」",
  "battle_galar_elite": "剑盾「联盟锦标赛」",
  "battle_paldea_elite": "朱紫「战斗！帕底亚四天王」",
  "battle_bb_elite": "朱紫「战斗！蓝之圆盘四天王」",
  "battle_final_encounter": "探险队DX 「裂空座的领域」",
  "battle_final": "黑白「战斗！魁奇思」",
  "battle_kanto_gym": "黑2白2「战斗！关都道馆主」",
  "battle_johto_gym": "黑2白2「战斗！城都道馆主」",
  "battle_hoenn_gym": "黑2白2「战斗！合众道馆主」",
  "battle_sinnoh_gym": "黑2白2「战斗！神奥道馆主」",
  "battle_unova_gym": "黑白「战斗！合众道馆主」",
  "battle_kalos_gym": "XY「战斗！卡洛斯道馆主」",
  "battle_galar_gym": "剑盾「战斗！伽勒尔道馆主」",
  "battle_paldea_gym": "朱紫「战斗！帕底亚道馆主」",
  "battle_legendary_kanto": "XY「战斗！传说宝可梦（关都）」",
  "battle_legendary_raikou": "心金魂银「战斗！雷公」",
  "battle_legendary_entei": "心金魂银「战斗！炎帝」",
  "battle_legendary_suicune": "心金魂银「战斗！水君」",
  "battle_legendary_lugia": "心金魂银「战斗！洛奇亚」",
  "battle_legendary_ho_oh": "心金魂银「战斗！凤王」",
  "battle_legendary_regis_g5": "黑2白2「战斗！传说中的巨人」",
  "battle_legendary_regis_g6": "Ω红宝石α蓝宝石「战斗！传说中的巨人」",
  "battle_legendary_gro_kyo": "Ω红宝石α蓝宝石「战斗！原始回归」",
  "battle_legendary_rayquaza": "Ω红宝石α蓝宝石「战斗！超古代宝可梦」",
  "battle_legendary_deoxys": "Ω红宝石α蓝宝石「战斗！代欧奇希斯」",
  "battle_legendary_lake_trio": "Ω红宝石α蓝宝石「战斗！由克希・艾姆利多・亚克诺姆」",
  "battle_legendary_sinnoh": "Ω红宝石α蓝宝石「战斗！传说的宝可梦」",
  "battle_legendary_dia_pal": "Ω红宝石α蓝宝石「战斗！帝牙卢卡・帕路奇亚」",
  "battle_legendary_giratina": "Ω红宝石α蓝宝石「战斗！骑拉帝纳」",
  "battle_legendary_arceus": "心金魂银「阿尔宙斯」",
  "battle_legendary_unova": "黑白「战斗！传说的宝可梦」",
  "battle_legendary_kyurem": "黑白「战斗！酋雷姆」",
  "battle_legendary_res_zek": "黑白「战斗！莱希拉姆・捷克罗姆」",
  "battle_legendary_xern_yvel": "XY「战斗！哲尔尼亚斯・伊裴尔塔尔」",
  "battle_legendary_tapu": "日月「战斗！卡璞」",
  "battle_legendary_sol_lun": "日月「战斗！露奈雅拉・索尔迦雷欧」",
  "battle_legendary_ub": "日月「战斗！究极异兽」",
  "battle_legendary_dusk_dawn": "究极日月「战斗！日食・月食 奈克洛兹玛」",
  "battle_legendary_ultra_nec": "究极日月「战斗！究极奈克洛兹玛」",
  "battle_legendary_zac_zam": "剑盾「战斗！苍响・藏玛然特」",
  "battle_legendary_glas_spec": "剑盾「战斗! 雪暴马・灵幽马」",
  "battle_legendary_calyrex": "剑盾「战斗！蕾冠王」",
  "battle_legendary_birds_galar": "剑盾「战斗！传说的鸟宝可梦」",
  "battle_legendary_ruinous": "朱紫「战斗！灾厄宝可梦」",
  "battle_legendary_loyal_three": "朱紫「战斗！宝伴」",
  "battle_legendary_ogerpon": "朱紫「战斗！厄鬼椪」",
  "battle_legendary_terapagos": "朱紫「战斗！太乐巴戈斯」",
  "battle_legendary_pecharunt": "朱紫「战斗！桃歹郎」",
  "battle_rival": "黑白「战斗！黑连・贝尔」",
  "battle_rival_2": "黑白「战斗！N」",
  "battle_rival_3": "黑白「决战！N」",
  "battle_trainer": "黑白「战斗！训练师」",
  "battle_wild": "黑白「战斗！野生宝可梦」",
  "battle_wild_strong": "黑白「战斗！强大野生宝可梦」",
  "end_summit": "探险队DX 「天空之柱 顶层」",
  "battle_plasma_grunt": "黑白「战斗！等离子团」",

  // Biome Music
  "abyss": "空之探险队「黑暗小丘」",
  "badlands": "空之探险队「枯竭之谷」",
  "beach": "空之探险队「潮湿岩地」",
  "cave": "空之探险队「天空顶端（洞窟）」",
  "construction_site": "空之探险队「幻影石室」",
  "desert": "空之探险队「北方沙漠」",
  "dojo": "空之探险队「嘎啦嘎啦道场」",
  "end": "探险队DX「天空之柱」",
  "factory": "空之探险队「隐藏遗迹」",
  "fairy_cave": "空之探险队「星之洞窟」",
  "forest": "空之探险队「黑暗森林」",
  "grass": "空之探险队「苹果森林」",
  "graveyard": "空之探险队「神秘森林」",
  "ice_cave": "空之探险队「大冰山」",
  "island": "空之探险队「沿岸岩地」",
  //"jungle": "jungle", // The composer thinks about a more creative name
  //"labratory": "labratory", // The composer thinks about a more creative name
  "lake": "空之探险队「水晶洞窟」",
  "meadow": "空之探险队「天空顶端（森林）」",
  //"metropolis": "metropolis", // The composer thinks about a more creative name
  "mountain": "空之探险队「角山」",
  "plains": "空之探险队「天空顶端（草原）」",
  "power_plant": "空之探险队「电气平原 深处」",
  "ruins": "空之探险队「封印岩地 深处」",
  "sea": "空之探险队「石滩洞窟」",
  "seabed": "空之探险队「石滩洞窟 下层」",
  "slum": "空之探险队「天空顶端（岩场）」",
  "snowy_forest": "空之探险队「天空顶端（雪山）」",
  "space": "空之探险队「财宝岩地」",
  "swamp": "空之探险队「封闭之海」",
  "tall_grass": "空之探险队「浓雾森林」",
  "temple": "空之探险队「守护洞穴」",
  "town": "空之探险队「随机迷宫3」",
  "volcano": "空之探险队「热水洞窟」",
  "wasteland": "空之探险队「梦幻高原」",

  // Encounter
  "encounter_ace_trainer": "黑白 「视线！精英训练师」",
  "encounter_backpacker": "黑白 「视线！背包客」",
  "encounter_clerk": "黑白 「视线！上班族」",
  "encounter_cyclist": "黑白 「视线！自行车手」",
  "encounter_lass": "黑白 「视线！迷你裙」",
  "encounter_parasol_lady": "黑白 「视线！阳伞姐姐」",
  "encounter_pokefan": "黑白 「视线！宝可梦爱好者」",
  "encounter_psychic": "黑白 「视线！超能力者」",
  "encounter_rich": "黑白 「视线！绅士」",
  "encounter_rival": "黑白「黑连」",
  "encounter_roughneck": "黑白 「视线！光头」",
  "encounter_scientist": "黑白 「视线！科学家」",
  "encounter_twins": "黑白 「视线！双胞胎」",
  "encounter_youngster": "黑白 「视线！短裤小子」",

  // Other
  "heal": "黑白「宝可梦回复」",
  "menu": "空之探险队「欢迎来到宝可梦的世界」",
  "title": "空之探险队「主题曲」",
```

2024-06-23 08:07 UTC, 40chyan commented on src/locales/zh_CN/bgm-name.ts
> +  "title": "PMD EoS Top Menu Theme",
refer [PMD EOS name references](https://baike.baidu.com/item/%E5%AE%9D%E5%8F%AF%E6%A2%A6%E4%B8%8D%E5%8F%AF%E6%80%9D%E8%AE%AE%E7%9A%84%E8%BF%B7%E5%AE%AB%EF%BC%9A%E7%A9%BA%E4%B9%8B%E6%8E%A2%E9%99%A9%E9%98%9F/24298227?fr=ge_ala#4)

other battle music names translated from Japanese OST

2024-06-23 17:24 UTC, Adri1 reviewed
Tiny French corrections

2024-06-23 17:24 UTC, Adri1 commented on src/locales/fr/bgm-name.ts
> +  "end_summit": "PMD ÉSDX - Tour Céleste",
```suggestion
  "battle_final_encounter": "PDM ÉSDX - Vs. Rayquaza",
  "battle_final": "NB - Vs. Ghetis",
  "battle_kanto_gym": "N2B2 - Vs. Champion·ne d’Arène de Kanto",
  "battle_johto_gym": "N2B2 - Vs. Champion·ne d’Arène de Johto",
  "battle_hoenn_gym": "N2B2 - Vs. Champion·ne d’Arène de Hoenn",
  "battle_sinnoh_gym": "N2B2 - Vs. Champion·ne d’Arène de Sinnoh",
  "battle_unova_gym": "NB - Vs. Champion·ne d’Arène d’Unys",
  "battle_kalos_gym": "XY - Vs. Champion·ne d’Arène de Kalos",
  "battle_galar_gym": "ÉB - Vs. Champion·ne d’Arène de Galar",
  "battle_paldea_gym": "ÉV - Vs. Champion·ne d’Arène de Paldea",
  "battle_legendary_kanto": "XY - Vs. Légendaire de Kanto",
  "battle_legendary_raikou": "HGSS - Vs. Raikou",
  "battle_legendary_entei": "HGSS - Vs. Entei",
  "battle_legendary_suicune": "HGSS - Vs. Suicune",
  "battle_legendary_lugia": "HGSS - Vs. Lugia",
  "battle_legendary_ho_oh": "HGSS - Vs. Ho-oh",
  "battle_legendary_regis_g5": "N2B2 - Vs. Colosses Légendaires",
  "battle_legendary_regis_g6": "ROSA - Vs. Colosses Légendaires",
  "battle_legendary_gro_kyo": "ROSA - Vs. Groudon/Kyogre",
  "battle_legendary_rayquaza": "ROSA - Vs. Rayquaza",
  "battle_legendary_deoxys": "ROSA - Vs. Deoxys",
  "battle_legendary_lake_trio": "ROSA - Vs. Gardiens des Lacs",
  "battle_legendary_sinnoh": "ROSA - Vs. Légendaire de Sinnoh",
  "battle_legendary_dia_pal": "ROSA - Vs. Dialga/Palkia",
  "battle_legendary_giratina": "ROSA - Vs. Giratina",
  "battle_legendary_arceus": "HGSS - Vs. Arceus",
  "battle_legendary_unova": "NB - Vs. Légendaire d’Unys",
  "battle_legendary_kyurem": "NB - Vs. Kyurem",
  "battle_legendary_res_zek": "NB - Vs. Reshiram/Zekrom",
  "battle_legendary_xern_yvel": "XY - Vs. Xerneas/Yveltal",
  "battle_legendary_tapu": "SL - Vs. Divinités gardiennes d’Alola",
  "battle_legendary_sol_lun": "SL - Vs. Solgaleo/Lunala",
  "battle_legendary_ub": "SL - Vs. Ultra-Chimère",
  "battle_legendary_dusk_dawn": "USUL - Vs. Necrozma Crinière du Couchant/Ailes de l’Aurore",
  "battle_legendary_ultra_nec": "USUL - Vs. Ultra-Necrozma",
  "battle_legendary_zac_zam": "ÉB - Vs. Zacian/ Zamazenta",
  "battle_legendary_glas_spec": "ÉB - Vs. Blizzeval/Spectreval",
  "battle_legendary_calyrex": "ÉB - Vs. Sylveroy",
  "battle_legendary_birds_galar": "ÉB - Vs. Oiseaux Légendaires de Galar",
  "battle_legendary_ruinous": "ÉV - Vs. Trésors du fléau",
  "battle_legendary_loyal_three": "ÉV - Vs. Adoramis",
  "battle_legendary_ogerpon": "ÉV - Vs. Ogerpon",
  "battle_legendary_terapagos": "ÉV - Vs. Terapagos",
  "battle_legendary_pecharunt": "ÉV - Vs. Pêchaminus",
  "battle_rival": "NB - Vs. Rival",
  "battle_rival_2": "NB - Vs. N",
  "battle_rival_3": "NB - Combat final Vs. N",
  "battle_trainer": "NB - Vs. Dresseur·euse",
  "battle_wild": "NB - Vs. Pokémon sauvage",
  "battle_wild_strong": "NB - Vs. Pokémon puissant sauvage",
  "end_summit": "PDM ÉSDX - Tour Céleste",
```

2024-06-23 17:30 UTC, Adri1 reviewed
French translation for "music" key

2024-06-23 17:30 UTC, Adri1 commented on src/locales/fr/bgm-name.ts
> +  "music": "Music",
```suggestion
  "music": "Musique ",
```

2024-06-23 17:35 UTC, Adri1 approved these changes

2024-06-24 04:35 UTC, 40chyan commented on src/locales/zh_CN/bgm-name.ts
> +  "music": "Music",
```suggestion
  "music": "BGM",
```
in zh_cn content we usally use BGM to indicate music here instead of directly translate into "音乐".
BGM has already been a widely used word in Chinese

2024-06-24 09:19 UTC, GoldTra requested changes
Spanish translations

2024-06-24 09:19 UTC, GoldTra commented on src/locales/es/bgm-name.ts
> +  "title": "PMD EoS Top Menu Theme",
```suggestion
  "music": "Música",
  "missing_entries" : "{{name}}",
  "battle_kanto_champion": "B2W2 - ¡Vs Campeón de Kanto!",
  "battle_johto_champion": "B2W2 - ¡Vs Campeón de Johto!",
  "battle_hoenn_champion": "B2W2 - ¡Vs Campeón de Hoenn!",
  "battle_sinnoh_champion": "B2W2 - ¡Vs Campeón de Sinnoh!",
  "battle_champion_alder": "BW - ¡Vs Campeón de Teselia!",
  "battle_champion_iris": "B2W2 - ¡Vs Campeón de Teselia!",
  "battle_kalos_champion": "XY - ¡Vs Campeón de Kalos!",
  "battle_alola_champion": "USUM - ¡Vs Campeón de Alola!",
  "battle_galar_champion": "SWSH - ¡Vs Campeón de Galar!",
  "battle_champion_geeta": "SV - ¡Vs Campeona Ságita!",
  "battle_champion_nemona": "SV - ¡Vs Campeona Mencía!",
  "battle_champion_kieran": "SV - ¡Vs Campeón Cass!",
  "battle_hoenn_elite": "ORAS - ¡Vs Alto Mando!",
  "battle_unova_elite": "BW - ¡Vs Alto Mando!",
  "battle_kalos_elite": "XY - ¡Vs Alto Mando!",
  "battle_alola_elite": "SM - ¡Vs Alto Mando!",
  "battle_galar_elite": "SWSH - Torneo de Finalistas",
  "battle_paldea_elite": "SV - ¡Vs Alto Mando!",
  "battle_bb_elite": "SV - ¡Vs Alto Mando de la Academia Arándano!",
  "battle_final_encounter": "PMD RTDX - Dominio de Rayquaza",
  "battle_final": "BW - ¡Vs Ghechis!",
  "battle_kanto_gym": "B2W2 - ¡Vs Líder de Kanto!",
  "battle_johto_gym": "B2W2 - ¡Vs Líder de Johto!",
  "battle_hoenn_gym": "B2W2 - ¡Vs Líder de Hoenn!",
  "battle_sinnoh_gym": "B2W2 - ¡Vs Líder de Sinnoh!",
  "battle_unova_gym": "BW - ¡Vs Líder de Teselia!",
  "battle_kalos_gym": "XY - ¡Vs Líder de Kalos!",
  "battle_galar_gym": "SWSH - ¡Vs Líder de Galar!",
  "battle_paldea_gym": "SV - ¡Vs Líder de Paldea!",
  "battle_legendary_kanto": "XY - ¡Vs Legendarios de Kanto!",
  "battle_legendary_raikou": "HGSS - ¡Vs Raikou!",
  "battle_legendary_entei": "HGSS - ¡Vs Entei!",
  "battle_legendary_suicune": "HGSS - ¡Vs Suicune!",
  "battle_legendary_lugia": "HGSS - ¡Vs Lugia!",
  "battle_legendary_ho_oh": "HGSS - ¡Vs Ho-oh!",
  "battle_legendary_regis_g5": "B2W2 - ¡Vs Regis!",
  "battle_legendary_regis_g6": "ORAS - ¡Vs Regis!",
  "battle_legendary_gro_kyo": "ORAS - ¡Vs Groudon/Kyogre!",
  "battle_legendary_rayquaza": "ORAS - ¡Vs Rayquaza!",
  "battle_legendary_deoxys": "ORAS - ¡Vs Deoxys!",
  "battle_legendary_lake_trio": "ORAS - ¡Vs Trío del Lago!",
  "battle_legendary_sinnoh": "ORAS - ¡Vs Legendarios de Sinnoh!",
  "battle_legendary_dia_pal": "ORAS - ¡Vs Dialga/Palkia!",
  "battle_legendary_giratina": "ORAS - ¡Vs Giratina!",
  "battle_legendary_arceus": "HGSS - ¡Vs Arceus!",
  "battle_legendary_unova": "BW - ¡Vs Legendarios de Teselia!",
  "battle_legendary_kyurem": "BW - ¡Vs Kyurem!",
  "battle_legendary_res_zek": "BW - ¡Vs Reshiram/Zekrom!",
  "battle_legendary_xern_yvel": "XY - ¡Vs Xerneas/Yveltal!",
  "battle_legendary_tapu": "SM - ¡Vs Tapus!",
  "battle_legendary_sol_lun": "SM - ¡Vs Solgaleo/Lunala!",
  "battle_legendary_ub": "SM - ¡Vs Ultraentes!",
  "battle_legendary_dusk_dawn": "USUM - ¡Vs Necrozma Melena Crepuscular/Alas del Alba!",
  "battle_legendary_ultra_nec": "USUM - ¡Vs Ultra-Necrozma!",
  "battle_legendary_zac_zam": "SWSH - ¡Vs Zacian/Zamazenta!",
  "battle_legendary_glas_spec": "SWSH - ¡Vs Glastrier/Spectrier!",
  "battle_legendary_calyrex": "SWSH - ¡Vs Calyrex!",
  "battle_legendary_birds_galar": "SWSH - ¡Vs Aves Legendarias de Galar!",
  "battle_legendary_ruinous": "SV - ¡Vs Tesoros Funestos!",
  "battle_legendary_loyal_three": "SV - ¡Vs Compatrones!",
  "battle_legendary_ogerpon": "SV - ¡Vs Ogerpon!",
  "battle_legendary_terapagos": "SV - ¡Vs Terapagos!",
  "battle_legendary_pecharunt": "SV - ¡Vs Pecharunt!",
  "battle_rival": "BW - ¡Vs Rival!",
  "battle_rival_2": "BW - ¡Vs N!",
  "battle_rival_3": "BW - ¡Vs N (Liga Pokémon)!",
  "battle_trainer": "BW - ¡Vs Entrenador!",
  "battle_wild": "BW - ¡Vs Pokémon Salvaje!",
  "battle_wild_strong": "BW - ¡Vs Pokémon Salvaje Raro!",
  "end_summit": "PMD RTDX - Techo del Cielo",
  "battle_plasma_grunt": "BW - ¡Vs Equipo Plasma!",

  // Biome Music
  "abyss": "PMD EoS - Cráter Oscuro",
  "badlands": "PMD EoS - Valle Desolado",
  "beach": "PMD EoS - Risco Calado",
  "cave": "PMD EoS - Cueva de la Cumbre del Cielo",
  "construction_site": "PMD EoS - Roquedal",
  "desert": "PMD EoS - Desierto Norte",
  "dojo": "PMD EoS - Dojo Marowak",
  "end": "PMD RTDX - Torre del Cielo",
  "factory": "PMD EoS - Ruinas Camufladas",
  "fairy_cave": "PMD EoS - Cueva Estrella",
  "forest": "PMD EoS - Bosque Sombrío",
  "grass": "PMD EoS - Manzanar",
  "graveyard": "PMD EoS - Bosque Misterio",
  "ice_cave": "PMD EoS - Gran Iceberg",
  "island": "PMD EoS - Costa Escarpada",
  //"jungle": "jungle", // The composer thinks about a more creative name
  //"labratory": "labratory", // The composer thinks about a more creative name
  "lake": "PMD EoS - Cueva Cristal",
  "meadow": "PMD EoS - Bosque de la Cumbre del Cielo",
  //"metropolis": "metropolis", // The composer thinks about a more creative name
  "mountain": "PMD EoS - Monte Cuerno",
  "plains": "PMD EoS - Pradera de la Cumbre del Cielo",
  "power_plant": "PMD EoS - Pradera Destello",
  "ruins": "PMD EoS - Sima Hermética",
  "sea": "PMD EoS - Cueva Aguamar",
  "seabed": "PMD EoS - Fosa Aguamar",
  "slum": "PMD EoS - Costa de la Cumbre del Cielo",
  "snowy_forest": "PMD EoS - Campo nevado de la Cumbre del Cielo",
  "space": "PMD EoS - Risco Fortuna",
  "swamp": "PMD EoS - Mar Circundante",
  "tall_grass": "PMD EoS - Bosque Niebla",
  "temple": "PMD EoS - Cueva Regia",
  "town": "PMD EoS - Tema del territorio aleatorio 3",
  "volcano": "PMD EoS - Cueva Vapor",
  "wasteland": "PMD EoS - Corazón Tierra Oculta",

  // Encounter
  "encounter_ace_trainer": "BW - Desafío Combate (Entrenador Guay)",
  "encounter_backpacker": "BW - Desafío Combate (Mochilero)",
  "encounter_clerk": "BW - Desafío Combate (Empresario)",
  "encounter_cyclist": "BW - Desafío Combate (Ciclista)",
  "encounter_lass": "BW - Desafío Combate (Chica)",
  "encounter_parasol_lady": "BW - Desafío Combate (Dama parasol)",
  "encounter_pokefan": "BW - Desafío Combate (Pokéfan)",
  "encounter_psychic": "BW - Desafío Combate (Médium)",
  "encounter_rich": "BW - Desafío Combate (Aristócrata)",
  "encounter_rival": "BW - Desafío Combate (Cheren)",
  "encounter_roughneck": "BW - Desafío Combate (Calvo)",
  "encounter_scientist": "BW - Desafío Combate (Científico)",
  "encounter_twins": "BW - Desafío Combate (Gemelas)",
  "encounter_youngster": "BW - Desafío Combate (Joven)",

  // Other
  "heal": "BW - Cura Pokémon",
  "menu": "PMD Eos - ¡Bienvenidos al mundo de los Pokémon!",
  "title": "PMD EoS - Tema del menú principal",
```

2024-06-24 15:24 UTC, CodeTappert commented on src/battle-scene.ts
> +  public showBgmBar: boolean = false;
```suggestion
  public showBgmBar: boolean = true;
```

2024-06-24 15:28 UTC, XGSleepWalker approved these changes

2024-06-24 15:31 UTC, merged