[Item] New Item: Assault Vest
pagefaultgames/pokerogue pull request #2463
Opened 2024-06-20 17:16 UTC by Greenlamp2

## What are the changes?
Implemented the item Assault Vest, which boosts the Special Defense by 50% but prevents the use of non-offensive moves.

## What did change?
- Added the item Assault Vest.
- The item boosts Special Defense by 50%.
- The item prevents the use of non-offensive moves.
- If the holder can only select non-offensive moves, it is forced to use Struggle.
- The Assault Vest allows non-offensive moves to be used via Dancer.
- The effect is triggered in the postSummonPhase, similar to the legacy game.
- The effect is cancelled when the item is transferred from the Pokémon.

### Screenshots/Videos

![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/fd734fb4-6d28-4229-996d-1cfabf480402)

## How to test the changes?
- Test the item Assault Vest in various battle scenarios.
- Ensure that Special Defense is boosted by 50% when the item is held.
- Verify that non-offensive moves cannot be selected when holding the item.
- Check that Struggle is used if only non-offensive moves are available.
- Confirm that non-offensive moves can still be used via Dancer.
- Validate that the effect is correctly triggered in the postSummonPhase.
- Test the effect cancellation when the item is transferred.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-20 17:17 UTC, Greenlamp2 commented
TODO:
- Localisations
- add the item sprite in the spritesheet

2024-06-20 20:38 UTC, Adri1 reviewed
Added French translations

2024-06-20 20:38 UTC, Adri1 commented on src/locales/fr/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "Raises the holder's Special Defense by 50%, but also prevents the holder from selecting any non-offensive moves except Me First." },
```suggestion
    "ASSAULT_VEST": { name: "Veste de Combat", description: "Augmente de 50% la Déf. Spé. de son porteur, mais l’empêche d’utiliser des capacités non-offensives sauf Moi d’Abord." },
```

2024-06-20 20:38 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "assaultVestRestriction": "The assault vest prevents the use of any non-offensive moves.",
```suggestion
  "assaultVestRestriction": "La Veste de Combat l’empêche d’utiliser une capacité non-offensive !",
```

2024-06-20 23:35 UTC, EnochG1 reviewed
I suggest translation of Korean.

2024-06-20 23:35 UTC, EnochG1 commented on src/locales/ko/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "Raises the holder's Special Defense by 50%, but also prevents the holder from selecting any non-offensive moves except Me First." },
```suggestion
    "ASSAULT_VEST": { name: "돌격조끼", description: "공격적으로 변하는 조끼. 지니게 하면 특수방어가 50% 올라가지만 변화 기술을 쓸 수 없게 된다." },
```

2024-06-20 23:35 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "assaultVestRestriction": "The assault vest prevents the use of any non-offensive moves.",
```suggestion
  "assaultVestRestriction": "돌격조끼 때문에 변화 기술을 쓸 수 없다!",
```

2024-06-21 02:07 UTC, 40chyan reviewed
zh_cn translation

2024-06-21 02:07 UTC, 40chyan commented on src/locales/zh_CN/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "Raises the holder's Special Defense by 50%, but also prevents the holder from selecting any non-offensive moves except Me First." },
```suggestion
    "ASSAULT_VEST": { name: "Assault Vest", description: "虽然携带后特防会提高50%，、\n但会无法使出变化招式。(除了抢先一步)" },
```

2024-06-21 02:07 UTC, 40chyan commented on src/locales/zh_CN/battle.ts
> +  "assaultVestRestriction": "The assault vest prevents the use of any non-offensive moves.",
```suggestion
  "assaultVestRestriction": "因为突击背心而无法使用变化招式！",
```

2024-06-21 09:57 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "assaultVestRestriction": "The assault vest prevents the use of any non-offensive moves.",
```suggestion
  "assaultVestRestriction": "Die Offensivweste verhindert den Einsatz von Status-Attacken.",
```

2024-06-21 09:58 UTC, CodeTappert commented on src/locales/de/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "Raises the holder's Special Defense by 50%, but also prevents the holder from selecting any non-offensive moves except Me First." },
```suggestion
    "ASSAULT_VEST": { name: "Offensivweste", description: "Erhöht die Spezial-Verteidigung des Trägers um 50%, aber der Träger kann keine Status-Attacken mehr einsetzen. Außer Egotrip." },
```

2024-06-21 12:18 UTC, Adri1 approved these changes

2024-06-21 12:22 UTC, Adri1 reviewed
Proper French translations. For some reason, others (and inomplete) have been implemeted?

2024-06-21 12:22 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "assaultVestRestriction": "La veste de combat empêche l'utilisation de toute capacités non offensives.",
```suggestion
  "assaultVestRestriction": "La Veste de Combat l’empêche d’utiliser\ndes capacités de statut !",
```

2024-06-21 12:22 UTC, Adri1 commented on src/locales/fr/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "Augmente de 50% la Défense Spéciale du porteur, mais le contraint à ne pas utiliser de capacités non offensives (à l’exception de Moi d’Abord
```suggestion
    "ASSAULT_VEST": { name: "Veste de Combat", description: "Augmente de 50% la Déf. Spé. de son porteur, mais l’empêche d’utiliser des capacités de statut à l’exception « Moi d’Abord »." },
```

2024-06-21 12:29 UTC, Greenlamp2 commented
> @Greenlamp2 Question. Why does the english say "non-offensive" moves instead of just status moves? Are there some non-status moves that are allowed?

I prefer saying non offensive than status because it's confusing player when they can not do stealth rock, sleep powder, taunt or whatever non offensive movse that does not sound like status move

2024-06-21 12:29 UTC, Greenlamp2 commented on src/locales/fr/battle.ts
> +  "assaultVestRestriction": "La veste de combat empêche l'utilisation de toute capacités non offensives.",
Because i did not like yours, especially the "l'empêche".
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/ecacab96-a844-4565-8475-b2135b4de9b8)

2024-06-21 12:30 UTC, Greenlamp2 commented on src/locales/fr/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "Augmente de 50% la Défense Spéciale du porteur, mais le contraint à ne pas utiliser de capacités non offensives (à l’exception de Moi d’Abord
I did not like the use of abreviation here

2024-06-21 12:33 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "assaultVestRestriction": "La veste de combat empêche l'utilisation de toute capacités non offensives.",
> Because i did not like yours, especially the "l'empêche".

Dang, I looked for this one and I haven't find it.

2024-06-21 12:33 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "assaultVestRestriction": "La veste de combat empêche l'utilisation de toute capacités non offensives.",
New version, because it had to be corrected anyway

2024-06-21 12:33 UTC, Greenlamp2 commented
> > > @Greenlamp2 Question. Why does the english say "non-offensive" moves instead of just status moves? Are there some non-status moves that are allowed?
> > 
> > 
> > I prefer saying non offensive than status because it's confusing player when they can not do stealth rock, sleep powder, taunt or whatever non offensive move that does not sound like status move
> 
> Ok. I just was confused because it says "status moves" in the offical text.
> 
> So i will keep it that way in german

yeah it really depends of the source
pokemon showdown for example:
![chrome_tg9OGHyLQk](https://github.com/pagefaultgames/pokerogue/assets/44787002/1a4a5672-fa19-41d6-ad6d-554a12d34cf9)

serebii:
![chrome_HNjaIt09Ii](https://github.com/pagefaultgames/pokerogue/assets/44787002/41a7a2e5-3508-4a22-b5db-870f8bf6295b)

when pokemonDb & bulbapedia says status move

2024-06-21 12:35 UTC, CodeTappert commented
I just went with the newest games on my switch.

2024-06-21 12:37 UTC, Greenlamp2 commented
> I just went with the newest games on my switch.

yep you are right ! I'm just thinking a bit ahead for future useless support ticket for people that does not understand how it works

2024-06-21 12:39 UTC, Greenlamp2 commented on src/locales/fr/battle.ts
> +  "assaultVestRestriction": "La veste de combat empêche l'utilisation de toute capacités non offensives.",
Like i said to CodeTappert:
I prefer saying non offensive than status because it's confusing player when they can not do stealth rock, sleep powder, taunt or whatever non offensive move that does not sound like status move.
I'm just thinking a bit ahead for future useless support ticket for people that does not understand how it works

2024-06-21 12:42 UTC, Adri1 commented
@Greenlamp2 About French localization, before marking things as "resolved" and unliatteraly decide, please lisen to what we suggest a leave a romm to compromise.
- About the ingame message, its had errors to adress, even if you managed to find the proper sentence? witch I don't
- About the item description, it may be too long. Furthermore, Déf. Spé. witten this way is already the consecrated form used all over the French transaltion, even withing sentences.

2024-06-21 12:55 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "assaultVestRestriction": "La veste de combat empêche l'utilisation de toute capacités non offensives.",
> Like i said to CodeTappert: I prefer saying non offensive than status because it's confusing player when they can not do stealth rock, sleep powder, taunt or whatever non offensive move that does not sound like status move. I'm just thinking a bit ahead for future useless support ticket for people that does not understand how it works

Whatever, in any case, there is still issues te resolve

2024-06-21 13:10 UTC, Adri1 commented on src/locales/fr/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "Augmente de 50% la Défense Spéciale du porteur, mais le contraint à ne pas utiliser de capacités non offensives (à l’exception de Moi d’Abord
It's not a question of liking it, but of consistency, as it its like this everywhere in the game.
+ It corrects the overall aesthetics of the sentence and prevent anything to go out of the text box or at lest to fell waaaay too loaded.

2024-06-21 20:05 UTC, bennybroseph commented
"This offensive vest boosts the holder's Sp. Def stat but prevents the use of status moves."

This is what Scarlet/Violet describes them as. In my opinion, we should never use 3rd Party sources for item descriptions unless 1st Party sources don't exist. Using the same text as the regular games makes it feel more official.

2024-06-22 15:24 UTC, Adri1 commented
> "This offensive vest boosts the holder's Sp. Def stat but prevents the use of status moves."
> 
> This is what Scarlet/Violet describes them as. In my opinion, we should never use 3rd Party sources for item descriptions unless 1st Party sources don't exist. Using the same text as the regular games makes it feel more official.
I already talked about it about before the introduction of the Orbs, but it I think it's a bit of a shame to to precisly not taking avantage of our position to not complete official description with more informations. I think we can provide good transations without betraying the spirit of the OG games. Because official ones tend to be -on purpose- very cryptic or incomplete in some cases

2024-06-23 00:52 UTC, bennybroseph commented
What's the guessing game? It prevents the use of Status Moves. That's all it needs to say.

2024-06-23 01:01 UTC, Adri1 commented
> What's the guessing game? It prevents the use of Status Moves. That's all it needs to say.

It does, however the initital description gives an extra information by mention an exception that is not too much to add. Exception that not everybody knows, here is the guessing game

2024-06-24 03:51 UTC, 40chyan commented on src/locales/zh_CN/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "虽然携带后特防会提高50%，、\n但会无法使出变化招式。(除了抢先一步)" },
```suggestion
    "ASSAULT_VEST": { name: "突击背心", description: "虽然携带后特防会提高50%，、\n但会无法使出变化招式。(除了抢先一步)" },
```

I forgot the item name sorry

2024-06-28 11:18 UTC, GoldTra requested changes
Spanish translations

2024-06-28 11:18 UTC, GoldTra commented on src/locales/es/battle.ts
> +  "assaultVestRestriction": "The assault vest prevents the use of any non-offensive moves.",
```suggestion
  "assaultVestRestriction": "El Chaleco Asalto impide que uses movimientos no ofensivos.",
```

2024-06-28 11:18 UTC, GoldTra commented on src/locales/es/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "Raises the holder's Special Defense by 50%, but also prevents the holder from selecting any non-offensive moves except Me First." },
```suggestion
    "ASSAULT_VEST": { name: "Chaleco Asalto", description: "Aumenta la Defensa Especial en un 50% del Pokémon
que lo lleva, pero le impide usar movimientos de estado excepto Yo Primero." },
```

2024-06-28 11:23 UTC, Adri1 commented on src/locales/es/modifier-type.ts
> +    "ASSAULT_VEST": { name: "Assault Vest", description: "Raises the holder's Special Defense by 50%, but also prevents the holder from selecting any non-offensive moves except Me First." },
Careful, a part of your sentence is on a second line

2024-06-29 21:32 UTC, Terrorforge commented
"Offensive" and "damaging" are not any more clear than "status move". Is Curse not an offensive, damaging move? What about Toxic? Or Confuse Ray?

I know that people will read "status move" as "move that inflicts a status condition". I know there's that one silly exception because it's a status move that turns into a non-status move. But at least "[status move](https://bulbapedia.bulbagarden.net/wiki/Status_move)" is a mechanically meaningful term. They're unambiguously identified in-game, and if you google "pokemon status move" you get relevant results.

If you want to make it clearer, may I suggest "but the holder may only select Physical and Special moves, as well as Me First"? Much less likely to be misunderstood, still refers to clearly defined labels the game actually uses.

2024-09-17 16:39 UTC, flx-sta commented
@Greenlamp2 Are you still working on this?

2024-09-17 20:40 UTC, Greenlamp2 commented
> @Greenlamp2 Are you still working on this?

It was done but i've passed the stick to the boss to decide everything about translations since we had a disagreement there. but as i can see, nothing has moved and i see there is a lot of conflict since i took my break of pokerogue. i draft back this PR for later then.

2024-09-17 22:00 UTC, flx-sta commented
> > @Greenlamp2 Are you still working on this?
> 
> It was done but i've passed the stick to the boss to decide everything about translations since we had a disagreement there. but as i can see, nothing has moved and i see there is a lot of conflict since i took my break of pokerogue.

Thanks for taking the time to respond.
<sub>Sorry about the inconvenience of no-responses...</sub>

---

How do you want to proceed? Give it up? Retry?  Resolve Conflicts and continue?

2024-09-18 00:57 UTC, Greenlamp2 commented
Unless players absolutely need assault vest, we can close this PR and i'll reopen it when i'm back, no worries

2024-09-18 00:57 UTC, closed without merging