Forecast and Flower Gift Partially Implemented
pagefaultgames/pokerogue pull request #249
Opened 2024-04-23 05:41 UTC by amdevgwen

Added SpeciesFormChangeWeatherTrigger to allow for forms to change when weather does.
Changed TrySetWeather and SummonPhases to trigger weather setting form Changes
Preliminary support for ability suppression form triggers in SpeciesFormChangeAbilitySuppressionTrigger

Implemented:
Forecast: Castform transforms with the weather.
Flower Gift: Cherrim Transforms in the weather.

Not yet implemented:

Both effects don't mirror the current generation exactly when it relates to ability suppression. Currently they mirror gen 4 in terms of behavior.
Forms would reach full intended behavior once ability suppression triggers have been finished.

2024-05-12 08:43 UTC, bennybroseph requested changes
Needs TSDoc documentation on all new classes and functions and code comments where applicable.

2024-05-12 08:43 UTC, bennybroseph commented on .gitignore
What are the changes in the .gitignore for?

2024-05-16 23:06 UTC, danieland commented on .gitignore
The .vs/ folder is created for anyone using the Visual Studio IDE, it's just state files and the like: https://developercommunity.visualstudio.com/t/vs-folder/82249#T-N83453

2024-05-19 13:37 UTC, closed without merging

2024-05-19 13:37 UTC, bennybroseph commented
Closing this due to inactivity from the original author. Feel free to make a new request if interest is reignited