[Enhancement] improve typing
pagefaultgames/pokerogue pull request #2501
Opened 2024-06-22 04:05 UTC by 2wheeh

## What are the changes?

It's minor type improvement.

## Why am I doing these changes?

It's better for type safety.

## What did change?

- makes some implicit any to have proper types 
- removes some unnecessary assertions.

### Screenshots/Videos

## How to test the changes?

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-25 20:33 UTC, OrangeRed requested changes

2024-06-25 20:33 UTC, OrangeRed commented on src/data/pokemon-species.ts
> +    const pixelColors: integer[] = [];
Typescript doesn't have an `integer` type can you use `number` instead?

2024-06-25 20:33 UTC, OrangeRed commented on src/field/pokemon.ts
>          levelMoves.push(...speciesLevelMoves.filter(lm => (includeEvolutionMoves && !lm[0]) || ((!e || lm[0] > 1) && (e === evolutionChain.length - 1 || lm[0] <= evolutionChain[e + 1][1]))));
Can you destructure here so these loops are easier to read.
1) `const [ species, level ] = evolutionChain[e]`
2) `speciesLevelMoves.filter(([ level, move ]) => { ... }`

2024-06-25 20:33 UTC, OrangeRed commented on src/data/pokemon-evolutions.ts
> +
Can you add jsdoc comments that explain what this type means. For example
```ts
/**
 * Pokemon evolution tuple type
 * @property 0 - Pokemon Species
 * @property 1 - The level at which it evolves
 */
```

2024-06-25 20:33 UTC, OrangeRed commented on src/field/pokemon.ts
>          levelMoves.push(...speciesLevelMoves.filter(lm => (includeEvolutionMoves && !lm[0]) || ((!e || lm[0] > 1) && (e === evolutionChain.length - 1 || lm[0] <= evolutionChain[e + 1][1]))));
This might be worth doing inside of a separate PR instead of this one.

2024-06-26 04:11 UTC, 2wheeh commented on src/data/pokemon-species.ts
> +    const pixelColors: integer[] = [];
I found there are many `integer` in the codebase:
https://github.com/pagefaultgames/pokerogue/blob/edb4c7e4a27679d0a9716546eadc5bdf59e8ced0/src/data/pokemon-species.ts#L533

which is type alias of `number` from `phaser` package.
```ts
// nodue_modules/phaser/types/phaser.d.ts
declare type integer = number;
```

So I thought it would be better for consistency if convention is to use `integer` over `number` when the value is integer case.

WDYT?

2024-06-26 04:12 UTC, 2wheeh commented on src/field/pokemon.ts
>          levelMoves.push(...speciesLevelMoves.filter(lm => (includeEvolutionMoves && !lm[0]) || ((!e || lm[0] > 1) && (e === evolutionChain.length - 1 || lm[0] <= evolutionChain[e + 1][1]))));
will do in next PR !

2024-06-26 04:12 UTC, 2wheeh commented on src/data/pokemon-evolutions.ts
> +
I added jsdoc in the way you suggest and changed it to a named tuple:

> <img width="468" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/40269597/8ff30190-f88d-46b3-a6c0-10810f723aac">

I wonder what is the best way to document tuple elements with jsdoc though. It doesn't seem well supported...

2024-06-26 17:50 UTC, OrangeRed commented on src/data/pokemon-evolutions.ts
> +
Yeah I tried looking it up but I couldn't find anything either. This is the best that I could come up with but if you find better by all means try it.

2024-06-26 17:53 UTC, OrangeRed commented on src/data/pokemon-species.ts
> +    const pixelColors: integer[] = [];
Sure for the phaser stuff we can keep it consistent and use integers

2024-07-13 16:52 UTC, OrangeRed commented
@2wheeh can you resolve the conflicts so this can be merged

2024-07-17 05:45 UTC, 2wheeh commented
@OrangeRed done ! sorry for the late iterate.

2024-08-07 20:46 UTC, torranx commented
@2wheeh please fix merge conflicts (again)

2024-08-11 08:43 UTC, 2wheeh commented
@torranx fixed.

2024-08-11 11:11 UTC, torranx approved these changes

2024-08-11 20:20 UTC, innerthunder approved these changes
🚀

2024-08-11 20:48 UTC, xsn34kzx approved these changes

2024-08-13 20:49 UTC, merged