[Localization] modifier-select-ui-handler Locales
pagefaultgames/pokerogue pull request #2527
Opened 2024-06-23 00:02 UTC by Adri1

Update of PR #1656  that as never be condisered

## What are the changes?
Locales for item selection menu (modifier-select-ui-handler) between battles

## Why am I doing these changes?
To localize this menu and for accessibility

## What did change?
If a translation is provided, this menu will be in the set language

**Only one minor visual issue :**
The cursor position doesn't adjusts according to text length, it disappears under the text if it is longer than the original text, so if anybody has a solution to provide...
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/3b54e05a-7dc8-4180-a44f-74ed0a1dc2ec)

### Screenshots/Videos
**Before** (French)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/d0af525d-1626-4b63-ab44-3e02d87319f0)

**After** (French)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/7d6a6194-f36d-40c8-ad47-ff86a015ac3f)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/617fb5d7-2af8-43ed-864d-18820f6bc71a)

## How to test the changes?
Being in Classic or Endless with a Lock Capsule and at least one item held by any Pokémon of you team to unlock "Lock rarities" and "Transfer" options in the menu.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-06-23 01:13 UTC, ddullgi requested changes

2024-06-23 01:13 UTC, ddullgi commented on src/locales/ko/modifier-select-ui-handler.ts
> +  "checkTeamDesc": "Check your team or use a form changing item.",
```suggestion
  "transfer": "건네주기",
  "reroll": "갱신",
  "lockRarities": "희귀도 고정",
  "checkTeam": "파티 확인",
  "transferDesc": "지닌 물건을 다른 포켓몬에게 건네줍니다.",
  "rerollDesc": "돈을 소모하여 아이템 목록을 새로 고칩니다.",
  "lockRaritiesDesc": "갱신되는 아이템의 희귀도가 고정됩니다(갱신 비용 증가).",
  "checkTeamDesc": "파티를 확인하거나 폼 변경 아이템을 사용합니다.",
```

2024-06-23 01:21 UTC, ddullgi commented on src/locales/ko/modifier-select-ui-handler.ts
> +  "checkTeamDesc": "Check your team or use a form changing item.",
It is based on the description of the existing items.

https://github.com/pagefaultgames/pokerogue/blob/db06c53693c655fae1612883cb81397ee00ce95d/src/locales/ko/modifier-type.ts#L195

Reroll -> 갱신 
Rarities -> 희귀도

https://github.com/pagefaultgames/pokerogue/blob/db06c53693c655fae1612883cb81397ee00ce95d/src/locales/ko/tutorial.ts#L15-L18

Team -> 파티

2024-06-23 05:46 UTC, 40chyan commented on src/locales/zh_CN/modifier-select-ui-handler.ts
> +  "checkTeamDesc": "Check your team or use a form changing item.",
```suggestion
  "transfer": "交换道具",
  "reroll": "刷新商店",
  "lockRarities": "锁定稀有度",
  "checkTeam": "查看队伍",
  "transferDesc": "将宝可梦携带的道具交换给其他宝可梦",
  "rerollDesc": "花钱刷新道具",
  "lockRaritiesDesc": "在刷新时锁定道具稀有度(影响刷新费用)",
  "checkTeamDesc": "检查队伍或使用形态改变道具",
```

2024-06-23 11:04 UTC, CodeTappert commented on src/locales/de/modifier-select-ui-handler.ts
> +  "itemCost": "₽{{formattedMoney}}"
```suggestion
export const modifierSelectUiHandler: SimpleTranslationEntries = {
  "transfer": "Übertragen",
  "reroll": "Neu rollen",
  "lockRarities": "Seltenheit festsetzen",
  "checkTeam": "Team überprüfen",
  "transferDesc": "Übertrage ein gehaltenes Item zu einem anderen Pokémon.",
  "rerollDesc": "Nutze Geld um die Items neu zu rollen.",
  "lockRaritiesDesc": "Setze die Seltenheit der Items fest. (Beeinflusst die Rollkosten).",
  "checkTeamDesc": "Überprüfe dein Team or nutze Formänderungsitems.",
  "rerollCost": "{{formattedMoney}}₽",
  "itemCost": "{{formattedMoney}}₽"

```

2024-06-24 17:46 UTC, josericardo-fo commented on src/locales/pt_BR/modifier-select-ui-handler.ts
> +  "itemCost": "₽{{formattedMoney}}"
```suggestion
  "transfer": "Alterar",
  "reroll": "Atualizar",
  "lockRarities": "Travar Raridades",
  "checkTeam": "Checar Time",
  "transferDesc": "Transfira um item segurado de um Pokémon para outro.",
  "rerollDesc": "Gaste dinheiro para atualizar as suas opções de itens.",
  "lockRaritiesDesc": "Trava a raridade dos itens na atualização (afeta o custo da atualização).",
  "checkTeamDesc": "Cheque seu time ou use um item de mudança de forma.",
  "rerollCost": "₽{{formattedMoney}}",
  "itemCost": "₽{{formattedMoney}}"
```

2024-06-28 12:18 UTC, GoldTra requested changes
Spanish translations

2024-06-28 12:18 UTC, GoldTra commented on src/locales/es/modifier-select-ui-handler.ts
> +  "itemCost": "₽{{formattedMoney}}"
```suggestion
  "transfer": "Transferir",
  "reroll": "Actualizar",
  "lockRarities": "Bloquear Rarezas",
  "checkTeam": "Ver Equipo",
  "transferDesc": "Transfiere un objeto que lleva un Pokémon a otro.",
  "rerollDesc": "Gasta dinero para actualizar las opciones de objetos.",
  "lockRaritiesDesc": "Bloquea las rarezas de los objetos al actualizar (afecta el costo de actualización).",
  "checkTeamDesc": "Revisa tu equipo o usa un objeto que cambia de forma.",
  "rerollCost": "{{formattedMoney}} ₽",
  "itemCost": "{{formattedMoney}} ₽"
```

2024-07-01 10:23 UTC, InnocentGameDev approved these changes
Changes seem perfect except for capitalized "Rarezas" which I don't agree with. Thank you @GoldTra

2024-07-01 10:23 UTC, InnocentGameDev commented on src/locales/es/modifier-select-ui-handler.ts
> +  "itemCost": "{{formattedMoney}} ₽"
Small capitalisation change for consistency with the other occurence of the same word. French did the same.

```suggestion
  "transfer": "Transferir",
  "reroll": "Actualizar",
  "lockRarities": "Bloquear rarezas",
  "checkTeam": "Ver Equipo",
  "transferDesc": "Transfiere un objeto que lleva un Pokémon a otro.",
  "rerollDesc": "Gasta dinero para actualizar las opciones de objetos.",
  "lockRaritiesDesc": "Bloquea las rarezas de los objetos al actualizar (afecta el costo de actualización).",
  "checkTeamDesc": "Revisa tu equipo o usa un objeto que cambia de forma.",
  "rerollCost": "{{formattedMoney}} ₽",
  "itemCost": "{{formattedMoney}} ₽"

```

2024-07-04 20:38 UTC, Tempo-anon approved these changes

2024-07-04 20:40 UTC, merged