[Qol/Balance] Dynamax cannon tweak
pagefaultgames/pokerogue pull request #2540
Opened 2024-06-23 14:39 UTC by InnocentGameDev

## What are the changes?

- Changed Dynamax Cannon damage to scale off of how overleveled the target is in comparison to the user. Adds an additive 10% damage to the move, and caps at 10 levels for the original 200% damage.
- Changed the move's description to match (English locale)
- Added comments on the other locales so that translators know to check the new English description.

## Why am I doing these changes?

I discussed with balance team how it felt highly counter-intuitive that a +1 level bump near the final fight that would take a mon, or maybe even your entire team with a rarer candy, from 200 to 201 would mean that you take x2 when Eternatus decides to Dynamax Cannon. With this newer implementation, you'd have to bring a 210 mon to take the same amount of damage, which is a situation a new player is less likely to encounter.

The arbitrary number of 200 also seemed very off with the rest of the design philosophy of this game.

Eternatus should still be hitting as hard when it comes to players going hard on candy jars in Endless. Eternatus as a starter (and whatever he would be fused with) takes a bit of a hit and he won't have access to a 200BP on mons above lvl 200. This seems to me in line with normal move balancing, a 200BP move with no downsides is rare.

It's mainly oriented to give clarity and transparency, especially thinking of newer players who might try to do a setup strategy on Eternatus and not know of the 201+ level breakpoint -- which was a mechanic not from mainline games either.

### Screenshots/Videos

The screenshots here provide examples of how the damage multiplier works now. Bonus example when Blissey copycated the move.

![1 level -110%](https://github.com/pagefaultgames/pokerogue/assets/170796740/511b3597-527b-42f4-aef0-cd9881e34800)
![10 levels - 200%](https://github.com/pagefaultgames/pokerogue/assets/170796740/2dab7c8b-01e7-4fed-afa0-7d72a5bda331)
![20 levels - capped 200%](https://github.com/pagefaultgames/pokerogue/assets/170796740/e4faaf0c-b23c-4b7d-8938-92c8970840bd)
![Underleveled - 100%](https://github.com/pagefaultgames/pokerogue/assets/170796740/a68510ad-eb53-4b0a-a77a-6810d08a08e6)

## How to test the changes?

Make an override, give your PKMN Dynamax Cannon and play around with level overrides. Make sure to use a SpDef Wall

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-23 14:56 UTC, Adri1 reviewed
French translation

2024-06-23 14:56 UTC, Adri1 commented on src/locales/fr/move.ts
> +    effect: "Le lanceur attaque en émettant un laser depuis son noyau. Cette capacité inflige deux fois plus de dégâts si l’adversaire est level 200." // Check new EN locale
```suggestion
    effect: "Le lanceur attaque en libérant l’énergie concentrée dans son noyau. Inflige deux fois plus de dégâts si l’adversaire a un niveau plus élevé que le lanceur."
```

2024-06-23 15:25 UTC, InnocentGameDev commented on src/locales/fr/move.ts
> +    effect: "Le lanceur attaque en émettant un laser depuis son noyau. Cette capacité inflige deux fois plus de dégâts si l’adversaire est level 200." // Check new EN locale
Thank you. I'll hold on committing this one until it's confirmed that the implementation will be done this way.

2024-06-23 15:28 UTC, Adri1 approved these changes

2024-06-23 15:41 UTC, Adri1 reviewed
Adding an important missing precision in French description

2024-06-23 15:41 UTC, Adri1 commented on src/locales/fr/move.ts
> +    effect: "Le lanceur attaque en libérant l’énergie concentrée dans son noyau. Inflige deux fois plus de dégâts si l’adversaire a un niveau plus élevé que le lanceur."
```suggestion
    effect: "Le lanceur attaque en libérant l’énergie concentrée dans son noyau. Inflige jusqu’à deux fois plus de dégâts si l’adversaire a un niveau plus élevé que le lanceur."
```

2024-06-23 15:54 UTC, Fontbane requested changes

2024-06-23 15:54 UTC, Fontbane commented on src/data/move.ts
> +        target.level > user.level ? 1 + Math.min(1, (target.level - user.level)/10) : 1)
Could this be adjusted to scale for endless? Something like
`target.level > user.level && user.level > 0 ? 1 + Math.min(1, target.level*20/user.level-20) : 1)`

This has the same result for the classic fight, but let's say level 8600 Eternatus vs level 8900 Eternatus would only have a 69% power increase since the levels are relatively closer. This way it would cap at the target being 5% higher level (200 vs 210) as opposed to pretty much instantly doubling in classic.

2024-06-23 16:06 UTC, Adri1 reviewed
Simple Chinese translation, made on behalf of a Chinese translataor (I missed, wait, ignore this message)

2024-06-23 16:06 UTC, Adri1 commented on src/locales/zh_TW/move.ts
> +    effect: "將凝縮在體內的能量從核心\n放出進行攻擊", // Check new EN locale
```suggestion
    effect: "将凝缩在体内的能量从核心放出进行攻击，\n对手的等级比你高的越多，造成的伤害越高，最多两倍。", 
```

2024-06-23 16:08 UTC, CodeTappert commented on src/locales/de/move.ts
> +    effect: "Der Anwender schießt einen Strahl aus seinem Kern ab. Dynamaximierte Ziele erleiden doppelten Schaden." // Check new EN locale
```suggestion
    effect: "Der Anwender greift an, indem er die in seinem Körper angesammelte Energie bündelt und aus seinem Kern abschießt. Verursacht bis zu doppelt so viel Schaden, wenn der Gegner ein höheres Level als der Anwender hat."
```

2024-06-23 16:09 UTC, Adri1 reviewed
Simple Chinese translation, made on behalf of a Chinese translataor (for real this time)

2024-06-23 16:09 UTC, Adri1 commented on src/locales/zh_CN/move.ts
> +    effect: "将凝缩在体内的能量从核心\n放出进行攻击", // Check new EN locale
```suggestion
    effect: "将凝缩在体内的能量从核心放出进行攻击，\n对手的等级比你高的越多，造成的伤害越高，最多两倍。", 
```

2024-06-23 16:12 UTC, 40chyan commented on src/locales/zh_CN/move.ts
> +    effect: "将凝缩在体内的能量从核心\n放出进行攻击", // Check new EN locale
```suggestion
    effect: "将凝缩在体内的能量从核心\n放出进行攻击，\n对手的等级比你高的越多，造成的伤害越高，最多两倍。", // Check new EN locale

```

2024-06-23 18:40 UTC, InnocentGameDev commented on src/locales/zh_CN/move.ts
> +    effect: "将凝缩在体内的能量从核心\n放出进行攻击", // Check new EN locale
I won't add this one since it's adding the same as the one Adri1 suggested and they same the same thing (I added the other commit since it didn't forget to remove the comment). Thanks though

2024-06-23 18:56 UTC, returntoice requested changes

2024-06-23 18:56 UTC, returntoice commented on src/locales/ko/move.ts
> +    effect: "코어에서 빔을 발사해서 공격한다. 상대의 레벨이 200보다 크면 데미지가 2배가 된다." // Check new EN locale
```suggestion
    effect: "코어에서 빔을 발사해서 공격한다. 상대의 레벨이 더 높다면 데미지가 2배가 된다."
```

Korean translation update

2024-06-23 19:06 UTC, InnocentGameDev commented on src/data/move.ts
> +        target.level > user.level ? 1 + Math.min(1, (target.level - user.level)/10) : 1)
I'm fairly new at TS but:

1) is user.level ever not greater than 0? why is "&& user.level > 0" necessary?
2) I discussed with lead balance and I wasn't told to make it a percentage, but a cap when target is 10 levels above, meaning 10% BP increase per level. Considering Dynamax Cannon atm hits for 200BP whenever above, I think it's already somewhat of a buff for Endless runs as well. If Balance team wants it differently I can change it, but it has to go through them.

2024-06-25 02:14 UTC, Fontbane commented on src/data/move.ts
> +        target.level > user.level ? 1 + Math.min(1, (target.level - user.level)/10) : 1)
> I'm fairly new at TS but:
> 
> 1. is user.level ever not greater than 0? why is "&& user.level > 0" necessary?
> 2. I discussed with lead balance and I wasn't told to make it a percentage, but a cap when target is 10 levels above, meaning 10% BP increase per level. Considering Dynamax Cannon atm hits for 200BP whenever above, I think it's already somewhat of a buff for Endless runs as well. If Balance team wants it differently I can change it, but it has to go through them.

1. Can never be too careful when dividing
2. Asked balance team, they approve
![image](https://github.com/pagefaultgames/pokerogue/assets/36677462/ce1cceb1-e89e-4359-8d94-873ae2b6e225)

2024-06-25 12:38 UTC, josericardo-fo commented on src/locales/pt_BR/move.ts
> +    effect: "O usuário libera um forte feixe de seu núcleo. Este movimento causa o dobro do dano se o alvo estiver acima do nível 200." // Check new EN locale
```suggestion
    effect: "O usuário libera um forte feixe de seu núcleo. Causa até o dobro do dano se o alvo tiver um nível maior que o usuário."
```

2024-06-30 23:10 UTC, Adri1 reviewed
French correction

2024-06-30 23:10 UTC, Adri1 commented on src/locales/fr/move.ts
> +    effect: "Le lanceur attaque en libérant l’énergie concentrée dans son noyau. Inflige jusqu’à deux fois plus de dégâts si l’adversaire a un niveau plus élevé que le lanceur." // Check new English
```suggestion
    effect: "Le lanceur attaque en libérant l’énergie concentrée dans son noyau. Inflige jusqu’à deux fois plus de dégâts si l’adversaire a un niveau très supérieur au lanceur."
```

2024-06-30 23:21 UTC, InnocentGameDev commented on src/locales/fr/move.ts
> +    effect: "Le lanceur attaque en libérant l’énergie concentrée dans son noyau. Inflige jusqu’à deux fois plus de dégâts si l’adversaire a un niveau plus élevé que le lanceur." // Check new English
Hello! I think that French is not properly translating the new way it works (perhaps you re-read the PR's description as I was editing it, sorry!). The new wording is this: "Deals up to twice the damage if the target is overly leveled."

"Overly leveled" is meaning "overly level in respect to the wave's level cap, so there's no longer any calculation involving the user ("lanceur", I presume). It's purely just the target, and how overleveled beyond the level cap the target is.

2024-06-30 23:48 UTC, InnocentGameDev commented on src/locales/pt_BR/move.ts
> +    effect: "O usuário libera um forte feixe de seu núcleo. Este movimento causa o dobro do dano se o alvo estiver acima do nível 200." // Check new EN locale
Check the new text when you get the time, please ^^

2024-07-01 01:43 UTC, josericardo-fo commented on src/locales/pt_BR/move.ts
> +    effect: "O usuário libera um forte feixe de seu núcleo. Este movimento causa o dobro do dano se o alvo estiver acima do nível 200." // Check new English description
```suggestion
    effect: "O usuário libera um forte feixe de seu núcleo. Este movimento causa até o dobro do dano se o alvo estiver com um nível maior que o seu."
```

2024-07-01 06:28 UTC, CodeTappert commented on src/locales/de/move.ts
> +    effect: "Der Anwender schießt einen Strahl aus seinem Kern ab. Verursacht bis zu doppelt so viel Schaden, wenn der Gegner ein höheres Level als der Anwender hat." // Check new English description
```suggestion
    effect: "Der Anwender schießt einen Strahl aus seinem Kern ab. Verursacht bis zu doppelt so viel Schaden, wenn das Level des Gegners höher als die Levelgrenze ist." 
```

2024-07-01 11:01 UTC, InnocentGameDev commented on src/locales/pt_BR/move.ts
> +    effect: "O usuário libera um forte feixe de seu núcleo. Este movimento causa o dobro do dano se o alvo estiver acima do nível 200." // Check new English description
Please follow the wording from the English or re-read the PR's description, because the functionality has changed.

Now user's level is not involved at all in the calculation. It only takes the target's level and compares it to the wave's level cap.

2024-07-01 13:00 UTC, josericardo-fo commented on src/locales/pt_BR/move.ts
> +    effect: "O usuário libera um forte feixe de seu núcleo. Este movimento causa o dobro do dano se o alvo estiver acima do nível 200." // Check new English description
fixed

2024-07-02 20:15 UTC, Fontbane approved these changes

2024-07-03 00:49 UTC, EnochG1 reviewed
eslint fix

2024-07-03 00:49 UTC, EnochG1 commented on src/locales/de/move.ts
> +    effect: "Der Anwender schießt einen Strahl aus seinem Kern ab. Verursacht bis zu doppelt so viel Schaden, wenn das Level des Gegners höher als die Levelgrenze ist."
```suggestion
    effect: "Der Anwender schießt einen Strahl aus seinem Kern ab. Verursacht bis zu doppelt so viel Schaden, wenn das Level des Gegners höher als die Levelgrenze ist."
```

2024-07-03 04:09 UTC, RimKnight reviewed
update zh-cn and zh-tw translation

2024-07-03 04:09 UTC, RimKnight commented on src/locales/zh_TW/move.ts
> +    effect: "將凝縮在體內的能量從核心\n放出進行攻擊", // Check new English description
```suggestion
    effect: "將凝縮在體內的能量從核心放出進行攻擊，\n對手等級比當前波次的最高等級越高，造成的傷害越高，最多兩倍。", 
```

2024-07-03 05:18 UTC, 40chyan commented on src/locales/zh_CN/move.ts
> +    effect: "将凝缩在体内的能量从核心放出进行攻击，\n对手的等级比你高的越多，造成的伤害越高，最多两倍。", // Check new English description
最高等级 → 等级上限

2024-07-03 12:35 UTC, sodaMelon reviewed
good evening, i added new localization into Korean.

When the target level is higher than the wave level, the damage is increased. 
(max 105% higher -> damage is  200%)
I thought about it, but the sentence becomes complicated because it accurately represents the formula.

한국어 설명 : PR 콘텐츠에 적힌 표 비례내용을 보시면 알겠지만
상대 레벨<->웨이브 단계와 비례해서, 상대레벨이 더 높을 때 데미지가 증가하는걸로 수식이 바뀌었습니다.  (댓글로 설명 달게요)

2024-07-03 12:35 UTC, sodaMelon commented on src/locales/ko/move.ts
> +    effect: "코어에서 빔을 발사해서 공격한다. 상대의 레벨이 더 높다면 데미지가 2배가 된다."
```suggestion
    effect: "코어에서 빔을 발사해서 공격한다. 상대의 레벨이 웨이브 단계보다 더 높다면, 최대 2배까지 데미지가 증가한다.  "
```

2024-07-03 14:58 UTC, InnocentGameDev commented on src/locales/ko/move.ts
> +    effect: "코어에서 빔을 발사해서 공격한다. 상대의 레벨이 더 높다면 데미지가 2배가 된다."
I don't understand this comment but the commit looks perfect when I pass it through ChadGPT so it's going in! ^^! Thanks!

2024-07-03 15:01 UTC, InnocentGameDev commented on src/locales/zh_CN/move.ts
> +    effect: "将凝缩在体内的能量从核心放出进行攻击，\n对手的等级比你高的越多，造成的伤害越高，最多两倍。", // Check new English description
Looks great, thank you!

2024-07-03 15:02 UTC, InnocentGameDev commented on src/locales/zh_TW/move.ts
> +    effect: "將凝縮在體內的能量從核心\n放出進行攻擊", // Check new English description
Looks good! Thank you!

2024-07-04 10:43 UTC, sodaMelon approved these changes

2024-07-04 23:39 UTC, EnochG1 approved these changes

2024-07-05 23:45 UTC, OrangeRed approved these changes
why is the variable name so long lol

2024-07-06 09:11 UTC, EnochG1 reviewed
Fixed korean translation for accuracy (Discussed with team)

2024-07-06 09:11 UTC, EnochG1 commented on src/locales/ko/move.ts
> +    effect: "코어에서 빔을 발사해서 공격한다. 상대의 레벨이 웨이브 단계보다 더 높다면, 데미지가 최대 2배가 된다."
```suggestion
    effect: "코어에서 빔을 발사해서 공격한다. 상대가 웨이브 레벨 최대치를 초과했다면, 초과한 정도에 비례하여 데미지가 최대 2배가 된다."
```

2024-07-10 18:51 UTC, returntoice approved these changes

2024-07-10 22:09 UTC, damocleas approved these changes

2024-07-11 10:53 UTC, AsdarDevelops commented
Added the test thanks to @xsn34kzx

2024-07-11 11:23 UTC, torranx commented on src/test/moves/dynamax_cannon.test.ts
> +    applyMoveAttrs(VariablePowerAttr, phase.getUserPokemon(), phase.getTarget(), move, power);
this is being repeated on all the tests, should probably create a small function for this similar to other existing tests

2024-07-11 11:25 UTC, torranx commented on src/test/moves/dynamax_cannon.test.ts
> +    expect(move.power).toBe(100);
I think this just overcomplicates things. The first assertion is unnecessary imo, while for second assertion, you could've just use the `moveToUse`

2024-07-11 22:10 UTC, xsn34kzx commented on src/test/moves/dynamax_cannon.test.ts
> +    expect(move.power).toBe(100);
I opted to keep the assertions since, even if they're relatively obvious as far as what they check, I'd rather double check for the future in case someone (i.e., changes the base power by accident). Definitely not likely but more assertions never hurt since we're not bottlenecked by having them.

2024-07-11 23:37 UTC, merged