[Localization] #1761 Korean trainer dialogue (Kalos region)
pagefaultgames/pokerogue pull request #2541
Opened 2024-06-23 14:49 UTC by sodaMelon

## What are the changes?

Translating locales\ko\dialogue.ts into Korean.
This PR is added korean dialogue for **named trainers in Kalos region.** (6th Pokemon Games)

@sodaMelon  @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.
@ Ohmry said he never played original Pokemon Game. so I decide to exclude this time.
(he only played Legend Arceus)

## Why am I doing these changes?

A few trainers's dialogue have been translated into Korean.
I did the others.
(Maybe this job will be ended next PR. There are only a few left.)

## What did change?

I translated **some Gym leader,Elite-4 and Champion(in Kalos, 6th pokemon)battles' dialogues.**
6세대 체육관 관장 2명+사천왕 + 카르네(챔피언) 다이얼로그를 번역했습니다.)

말투 교정에는 정발판 6세대 포켓몬스터 XY 참고했습니다.

(나머지 체육관 관장들은 다른 분이 해주셨습니다.)

### Screenshots/Videos

( very hard to meet them.... and it's dosen't matter)

## How to test the changes?

It seems there won't be much to test since it's just a translation of an existing .ts file. You can check it when you meet the respective trainers.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~~[ ] Are the changes visual?~~
  - ~~[ ] Have I provided screenshots/videos of the changes?~~

2024-06-23 18:44 UTC, returntoice requested changes

2024-06-23 18:44 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "기쁘네요! 그렇죠, 당신을 밑에서 짓밟을 수 있게 될 줄은 몰랐으니까."
표현이 좀 어색하게 느껴지는데 원문 혹시 찾으셨나요? 배틀샤토에서 플레이어가 패배했을 때 나오는 대사라는데 한국 정발판에선 뭐라고 하는지 인터넷에서 찾기가 힘드네요..

확실히 3DS까지는 캡처보드 없이는 스크린샷이나 영상 찍기가 힘들다 보니 잘 없는 듯합니다 ㅠ

2024-06-23 22:32 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "기쁘네요! 그렇죠, 당신을 밑에서 짓밟을 수 있게 될 줄은 몰랐으니까."
앗 전 사천왕전 대사만 봤는데(인게임에서 135층 이상은 무리입니다 llorz) 
이따 일본어쪽 원문 한번 찾아보겠습니다

2024-06-24 01:33 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "기쁘네요! 그렇죠, 당신을 밑에서 짓밟을 수 있게 될 줄은 몰랐으니까."
### English Original
"I am delighted! Yes, delighted that I could squash you beneath my heel."
기쁘네요. 내 구두굽 아래에서 당신을 밟아 으깰수 있어서 기뻐요.

### Japanese Original
うれしいわ あなたを プチっと つぶせて！
기쁘네요, 당신을 쁘띠하게 으깰 수 있어서요!

 つぶせて는 아래의 의미를 갖고 있습니다. 
1.찌부러뜨리다, 으깨다, 부수다.
卵を潰す 달걀을 깨다
2.못 쓰게 하다, 망치다.
声を潰す목청을 망치다; 목이 쉬다
3.탕진하다, 없애다, 파산시키다.
家を潰す 도산하다; 집안을 망하게 하다

2024-06-24 01:57 UTC, returntoice commented on src/locales/ko/dialogue.ts
> +      1: "기쁘네요! 그렇죠, 당신을 밑에서 짓밟을 수 있게 될 줄은 몰랐으니까."
"기쁘네요! 당신을 짓밟을 수 있어서 말이죠!" 정도는 어떨까요?

2024-06-24 01:58 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "기쁘네요! 그렇죠, 당신을 밑에서 짓밟을 수 있게 될 줄은 몰랐으니까."
プチっと 가 쁘띠하게라서 간단히or 말랑말랑한걸 으깨는 느낌이 있긴한데요 <->영문판은 콰직!하고 구두굽으로 세게  으깨는 느낌이라............................ 
느낌이 너무 다르니깐 그냥 부사 없이 가겠습니다

2024-06-24 01:58 UTC, sodaMelon commented on src/locales/ko/dialogue.ts
> +      1: "기쁘네요! 그렇죠, 당신을 밑에서 짓밟을 수 있게 될 줄은 몰랐으니까."
```suggestion
      1: "기쁘네요! 당신을 짓밟을 수 있어서 말이죠!"
```

2024-06-24 02:02 UTC, sodaMelon commented
@returntoice applied your suggestion. thanks!

2024-06-24 02:06 UTC, returntoice approved these changes

2024-06-24 03:51 UTC, EnochG1 approved these changes

2024-06-24 04:38 UTC, Tempo-anon approved these changes

2024-06-24 04:39 UTC, merged