[Feature] Fusion Names Overhaul
pagefaultgames/pokerogue pull request #2545
Opened 2024-06-23 15:57 UTC by amatsune

Following up this suggestion:
https://github.com/pagefaultgames/pokerogue/issues/2383
This is an early attempt to make it work

## What are the changes?
Fusion names should change a little.

## Why am I doing these changes?
Following up this suggestion I made.
https://github.com/pagefaultgames/pokerogue/issues/2383
 Now it will be possible to know the pokémon fused by the fusion name alone.

## What did change?

Created new localization files with affixes for each pokémon.
Edited the /src/interface/locales.ts to accomodate the new files
Edited the /src/data/pokemon-species.ts to make use of the new affixes replacing the original fusion name function

## How to test the changes?
Some tweaking of the pokemon-species.ts needs to happen before its functional. Was suggested to make a PR so it could be looked over.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-23 16:17 UTC, CodeTappert commented on src/locales/de/pokemon-fusion-affixes.ts
> +    fusionSuffix: "urtok",
```suggestion
    fusionSuffix: "tok",
```

2024-06-23 16:18 UTC, CodeTappert commented on src/locales/de/pokemon-fusion-affixes.ts
> +    fusionSuffix: "ettbo",
```suggestion
    fusionSuffix: "bo",
```

2024-06-23 18:29 UTC, Mewtwo2387 requested changes

2024-06-23 18:29 UTC, Mewtwo2387 commented on src/locales/zh_TW/pokemon-fusion-affixes.ts
Looks rather inconsistant and most of these doesn't really work, might be better to keep zh_CN and zh_TW as English for now and wait till our localization team discuss the correct prefix and suffix.

2024-06-23 20:32 UTC, amatsune commented on src/locales/zh_TW/pokemon-fusion-affixes.ts
What do you mean by inconsistent?

If it's about the code working: it doesn't…

If it's about the naming convention, can you point out what you mean by it?

2024-06-23 20:48 UTC, Mewtwo2387 commented on src/locales/zh_TW/pokemon-fusion-affixes.ts
Take some 3 word names for example - There are randomly some prefixes that uses the entire 3 words while some uses 1 like the rest, despite being the same evolution line with the same way of naming.

Also, this PR is supposed to make fusion names more clear, but this set of prefix/suffix names have a completely opposite effect as a lot of names only took 1 word out of 4.

2024-06-23 20:56 UTC, Mewtwo2387 commented on src/locales/zh_TW/pokemon-fusion-affixes.ts
Take the squirtle line for example:
```
  squirtle: {
    fusionPrefix: "傑尼龜",
    fusionSuffix: "龜",
  },
  wartortle: {
    fusionPrefix: "卡",
    fusionSuffix: "龜",
  },
  blastoise: {
    fusionPrefix: "水",
    fusionSuffix: "龜",
  },
  ```
  This is pretty much like
  ```
    squirtle: {
    fusionPrefix: "squirtle",
    fusionSuffix: "tle",
  },
  wartortle: {
    fusionPrefix: "wa",
    fusionSuffix: "tle",
  },
  blastoise: {
    fusionPrefix: "bla",
    fusionSuffix: "ise",
  },
```
Out of these 3, squirtle is the only one that uses the full name as the prefix, while the rest didn't even use the entire  name for prefix+suffix

Same problem with most of the other pokemon.

2024-06-23 21:00 UTC, amatsune commented on src/locales/zh_TW/pokemon-fusion-affixes.ts
Oh, yes for ideographic languages I honestly don't have a good rule for the division. I don't have the knowledge to make a rule that attends to the intricacies of a language I don't know the first thing about. I don't even know how it works currently with those languages, I assume it splits them in half?

In any case, if you have a proposed rule for tackling these localizations, I'm all ears. Otherwise, I'll take your suggestion and leave the English set for the time being.

> Take some 3 word names for example - There are randomly some prefixes that uses the entire 3 words while some uses 1 like the rest, despite being the same evolution line with the same way of naming.

This was something I tried to address, but my script kept coming up with blanks due to how the comparison worked. If the word shared characters with another word, then it would copy give the "prefix" and nothing else
If it didn't it would just leave it blank, for those I set it to output the full word instead.
I believe a solution that keeps to the principles I've set for Latin languages just isn't suited to non-syllabic structures.

Despite this, I think the possibility to manually tweak the Prefixes and Suffixes proposed by this PR should be a step forward in making sure we have the power to fix this manually on a case-by-case basis where necessary, and should there be a good proposed algorithm for a general rule, I'd love to use it.

2024-06-23 21:09 UTC, amatsune commented on src/locales/zh_TW/pokemon-fusion-affixes.ts
> Take the squirtle line for example:
> 
> ```
>   squirtle: {
>     fusionPrefix: "傑尼龜",
>     fusionSuffix: "龜",
>   },
>   wartortle: {
>     fusionPrefix: "卡",
>     fusionSuffix: "龜",
>   },
>   blastoise: {
>     fusionPrefix: "水",
>     fusionSuffix: "龜",
>   },
> ```
> 
> This is pretty much like
> 
> ```
>   squirtle: {
>   fusionPrefix: "squirtle",
>   fusionSuffix: "tle",
> },
> wartortle: {
>   fusionPrefix: "wa",
>   fusionSuffix: "tle",
> },
> blastoise: {
>   fusionPrefix: "bla",
>   fusionSuffix: "ise",
> },
> ```
> 
> Out of these 3, squirtle is the only one that uses the full name as the prefix, while the rest didn't even use the entire name for prefix+suffix
> 
> Same problem with most of the other pokemon.

As to using the entire name:


That's not the goal. Prefix and suffix are meant to include just the part of the name that isn't shared with any other 'mon (and in latin languages extend that to the next consonant/vowel, for phonetic reasons)
This way if you fuse bulbasaur with itself:

  bulbasaur: {
    fusionPrefix: "Bul",
    fusionSuffix: "asaur",
  },

you'll get Bulasaur.

That is on purpose. When playing with fusions, this indicates immediately that something isn't quite like it should, even though for all intents and purposes it will look like a normal bulbasaur.
By following these rules it should always be possible to tell the pokémon involved in the fusion.

2024-06-23 22:16 UTC, Mewtwo2387 commented on src/locales/zh_TW/pokemon-fusion-affixes.ts
All these 3 uses 龜 as the suffix. In chinese, the last word of a lot of evolution lines remains the same. So you'll never be able to figure out which pokemon is involved if you just use the last world - hence why I mentioned having to use more

2024-06-24 12:24 UTC, CodeTappert commented on src/field/pokemon.ts
> +    this.name = getFusedSpeciesName(this.species.getName(this.species), this.fusionSpecies.getName(Species));
```suggestion
    this.name = getFusedSpeciesName(this.species, this.fusionSpecies);
```

2024-06-24 12:26 UTC, CodeTappert commented on src/data/pokemon-species.ts
>  export function getFusedSpeciesName(speciesAName: string, speciesBName: string): string {
```suggestion
export function getFusedSpeciesName(speciesA: PokemonSpecies, speciesB: PokemonSpecies): string {
```

2024-06-24 12:27 UTC, CodeTappert commented on src/data/pokemon-species.ts
> +  return `${speciesAPrefix}${speciesBSuffix}`;
```suggestion
// Basically the only thing missing is now to get the non local species name in lowercase
return i18next.t(fusionAffixes:${speciesA}.fusionPrefix)+i18next.t(fusionAffixes:${speciesB}.fusionSuffix)

```

2024-06-24 14:33 UTC, CodeTappert commented on src/data/pokemon-species.ts
> +return i18next.t(fusionAffixes:${speciesA}.fusionPrefix)+i18next.t(fusionAffixes:${speciesB}.fusionSuffix)
```suggestion
  const prefix = i18next.t(`fusionAffixes:${Species[speciesA.speciesId].toLowerCase()}.fusionPrefix`);
  const suffix = i18next.t(`fusionAffixes:${Species[speciesB.speciesId].toLowerCase()}.fusionSuffix`);

  return `${prefix}${suffix}`;
}
```

2024-06-24 17:22 UTC, amatsune commented
![Screenshot 2024-06-24 185519](https://github.com/pagefaultgames/pokerogue/assets/48121978/456e6492-d22f-4adf-a116-37579aa568f2)
![Screenshot 2024-06-24 191024](https://github.com/pagefaultgames/pokerogue/assets/48121978/076c832b-be22-4ee8-8f6d-cedb435f087d)

2024-06-25 02:41 UTC, jaimefd commented
I know this is a lot of work and by no means I want to disrespect it but... is this really needed? Short names have their charm and I feel like this method creates very long and unnatural looking names. Also, we do not need to be able to tell the fusion immediately with the name, you can scroll over it.

I may sound immature here but the laughs and funny moments I got with all of these fusion names will really be missed, this new ones seem too serious. Maybe a toggle for players to choose which fusion naming method to use? I really love the current one

2024-06-25 06:13 UTC, amatsune commented
Besides the reasons stated in my initial suggestion, which goes over in length over many points, it turns out the current system doesn't handle other languages quite well, causing some names just appear broken.

Filipe Sant'Anna.
________________________________
From: Jaime ***@***.***>
Sent: Tuesday, June 25, 2024 4:41:23 AM
To: pagefaultgames/pokerogue ***@***.***>
Cc: Amatsune ***@***.***>; Author ***@***.***>
Subject: Re: [pagefaultgames/pokerogue] [Feature] Fusion Names Overhaul (PR #2545)


I know this is a lot of work and by no means I want to disrespect it but... is this really needed? Short names have their charm and I feel like this method creates very long and unnatural looking names. Also, we do not need to be able to tell the fusion immediately with the name, you can scroll over it.

I may sound immature here but the laughs and funny moments I got with all of these fusion names will really be missed, this new ones seem too serious. Maybe a toggle for players to choose which fusion naming method to use? I really love the current one

—
Reply to this email directly, view it on GitHub<https://github.com/pagefaultgames/pokerogue/pull/2545#issuecomment-2187844254>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALPEQ6TOHU7IBOIL4CUCCCLZJDKFHAVCNFSM6AAAAABJYPICAWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOBXHA2DIMRVGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-06-25 06:19 UTC, amatsune commented
![image](https://github.com/pagefaultgames/pokerogue/assets/48121978/4371a8fd-5f16-43a2-9320-8e5130b019e6)
Now handles CN names in a semantically correct order

2024-06-25 11:54 UTC, amatsune commented
> You seem to already solved it, but i was kinda curious.
> 
> I tryed some things in python and for symbolic languages found that `jieba` has a good solution.
> 
> Maybe you can analyze jiebe for that matter if some problems a rise down the line.

I included the python code I used in the pr, if you want to take a look. It's the long a commented out portion at the end that I used to deal with symbolic languages. It's not perfect by any means, so most of the CN affixes were adjusted manually to optimize meaning. That means I'm not sure if they are optimally following the original rule of keeping the species name always unique, but: the "double inversion" thing I mentioned makes sure that the suffixes (which is the part that tends to repeat more often through evolution lines) should at least be unique to evolution lines.

With that and the sprite it should be possible to know the fused species.

2024-06-28 02:04 UTC, 40chyan approved these changes

2024-06-28 11:38 UTC, CodeTappert commented on src/data/pokemon-species.ts
> +  console.log(`shouldReverse: ${shouldReverse}`); // logs the value of shouldReverse
Cant this be removed before merging to main?

2024-06-28 11:38 UTC, CodeTappert commented on src/data/pokemon-species.ts
> +  console.log(`prefix: ${prefix}, suffix: ${suffix}`); // logs the values of prefix and suffix
This also

2024-06-28 11:40 UTC, CodeTappert commented on src/locales/fusion-affixes-generator.py
> +#This script produces the list of affixes (prefix and suffix) used to create the fusion names.
I dont think this should be here. 
Maybe create a "tools" Folder in the locales folder or something

2024-06-28 11:52 UTC, CodeTappert commented on src/data/pokemon-species.ts
> -  const shouldReverse = i18next.t("fusionAffixes:shouldReverse");
Why did you also remove this line?

2024-06-28 11:53 UTC, CodeTappert approved these changes

2024-07-01 04:11 UTC, 40chyan commented
can you solve the conflicts so we can ask a dev to approve this?

2024-07-06 18:10 UTC, 40chyan approved these changes

2024-08-22 18:28 UTC, innerthunder commented
closing in favor of https://github.com/pagefaultgames/pokerogue/pull/3262

2024-08-22 18:28 UTC, closed without merging