localize reward message (You received ~)
pagefaultgames/pokerogue pull request #2556
Opened 2024-06-24 04:49 UTC by EnochG1

## What are the changes?
Add the option to localize message text when you receive modifier.

## Why am I doing these changes?
All text should be localizable.

## What did change?
 - Change the code for localize.
 - Added localization key in each language folders.
 - Translated it to Korean.

### Screenshots/Videos
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/0b428d42-bef0-4a8d-931f-94391442df72)
English

![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/b3f98d9d-8445-4177-bb42-92800da7c064)
Korean

## How to test the changes?
Manually.
Try wave clear with a fixed reward, like
classic 8 : rival (EXP. All)
classic 20 : Gym leader (Super EXP. Charm)
(find onReward of ModifierRewardPhase)

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-24 05:41 UTC, 40chyan commented on src/locales/zh_CN/battle.ts
> +  "rewardGain": "You received\n{{modifierName}}!",
```suggestion
  "rewardGain": "你获得了\n{{modifierName}}！",
```

2024-06-24 05:41 UTC, 40chyan commented on src/locales/zh_CN/battle.ts
> +  "rewardGain": "You received\n{{modifierName}}!",
cn translation

2024-06-24 07:13 UTC, GoldTra requested changes
Spanish translation

2024-06-24 07:13 UTC, GoldTra commented on src/locales/es/battle.ts
> +  "rewardGain": "You received\n{{modifierName}}!",
```suggestion
  "rewardGain": "¡Has obtenido\n{{modifierName}}!",
```

2024-06-24 09:19 UTC, GoldTra approved these changes

2024-06-24 09:41 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "rewardGain": "You received\n{{modifierName}}!",
```suggestion
  "rewardGain": "Du erhältst\n{{modifierName}}!",
```

2024-06-24 10:51 UTC, Adri1 reviewed
Added French

2024-06-24 10:51 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "rewardGain": "You received\n{{modifierName}}!",
```suggestion
  "rewardGain": "Vous recevez\n{{modifierName}} !",
```

2024-06-24 12:39 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "rewardGain": "You received\n{{modifierName}}!",
Suggested portuguese translation
```suggestion
  "rewardGain": "Você recebeu\n{{modifierName}}!",
```

2024-06-24 13:56 UTC, Adri1 approved these changes

2024-06-25 08:08 UTC, EnochG1 commented
@CodeTappert
@40chyan
@josericardo-fo

Could you approve this request if updated screenshot of your language at main article is correct?

2024-06-25 08:11 UTC, CodeTappert approved these changes

2024-06-26 02:00 UTC, josericardo-fo approved these changes

2024-06-26 02:03 UTC, 40chyan approved these changes
zh_cn approved

2024-06-26 02:13 UTC, Tempo-anon approved these changes

2024-06-26 02:13 UTC, merged