[Move] Implement Substitute (and Shed Tail?)
pagefaultgames/pokerogue pull request #2559
Opened 2024-06-24 07:44 UTC by innerthunder

## What are the changes?

This will implement the moves Substitute and Shed Tail

## Why am I doing these changes?

Substitute and Shed Tail are (N)

## What did change?

### Current Changes:
- `data/battler-tags`: Added new `SubstituteTag` which represents the [Substitute Doll effect](https://bulbapedia.bulbagarden.net/wiki/Substitute_(doll)#Effect) and stores the doll's HP. This tag uses the new type `SUBSTITUTE` and a new lapse type `HIT` to trigger on-hit dialogue
- `data/move`: Added a new attribute `AddSubstituteAttr` for Substitute's effect and another attribute `BypassSubstituteAttr` that enables some moves to ignore Substitute's effect.
- `field/pokemon`: `Pokemon.apply()` is updated so that if the `Pokemon` has a `SubstituteTag`:
    - Attack moves ([unless unaffected](https://bulbapedia.bulbagarden.net/wiki/Substitute_(move)#Unaffected_moves)) have their damage redirected to the `SubstituteTag`, removing the tag if it brings the tag's HP to 0 (or less)
    - Status moves (unless unaffected or self-targeting) will fail.

### TODO:
- Replace the user's sprite with a Substitute Doll while Substitute is in effect. This would also require adding animations to transition between the user's sprite and the doll (these could be triggered within the `SubstituteTag`).
- Unit tests for Substitute (and Shed Tail, if implemented)
- New move attribute for Shed Tail that forces a switch and gives the newly-summoned Pokemon a Substitute that scales its HP off of the user.

### Screenshots/Videos

Basic Implementation: Substitute vs. Earthquake (no changes to user's sprite)

https://github.com/pagefaultgames/pokerogue/assets/168692175/81849752-0fb2-49de-9d12-b537d4d29fd5

## How to test the changes?

Unit tests are WIP

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-24 14:36 UTC, Tempo-anon reviewed
Going to just assume that you got all the bypassSubstitute moves right based off the table on bulbapedia

2024-06-24 14:36 UTC, Tempo-anon commented on src/data/battler-tags.ts
> +  public substituteHp: integer;
nit: we should be moving away from `integer` and just use `number` since they're functionally identical

2024-06-24 14:36 UTC, Tempo-anon commented on src/data/battler-tags.ts
> +  HIT
Hmm, would this also work for something like disguise, ice face, or gulp missile?

2024-06-24 14:36 UTC, Tempo-anon commented on src/data/battler-tags.ts
> +    const ret = lapseType !== BattlerTagLapseType.CUSTOM || super.lapse(pokemon, lapseType);
nit: `const ret = (lapseType !== BattlerTagLapseType.CUSTOM || super.lapse(pokemon, lapseType));`

2024-06-24 14:36 UTC, Tempo-anon commented on src/data/move.ts
> +      user.damageAndUpdate(hpCost, HitResult.OTHER, false, true, true);
Just want to double check, does this `damageAndUpdate` work through things like magic guard?

2024-06-24 14:36 UTC, Tempo-anon commented on src/data/move.ts
> +    return Math.ceil((user.getHpRatio() - 0.25) * 4/3 * 10 - 5);
Did you get these numbers from somewhere or did you choose it arbitrarily? Some doc on this function to describe the calculation for now would be good

2024-06-24 14:36 UTC, Tempo-anon commented on src/field/pokemon.ts
> +            damage.value = 0;
Is there a message for when a substitute gets hit normally? Also, how does this work with this game's version of spaghetti multi-hit moves?

2024-06-24 18:05 UTC, innerthunder commented on src/data/battler-tags.ts
> +  HIT
I think it would! My only concern would be that the tags themselves can't interact with the `damage` values directly, which might make things a bit messy.

2024-06-24 18:32 UTC, innerthunder commented on src/field/pokemon.ts
> +            damage.value = 0;
It is meant to send a message when the substitute gets hit (and this is covered in the battler tag), but only for the first hit for multi-hit moves, as far as I know. I can easily check this with `hitCount` and `hitsLeft` from `source.turnData`, though.

2024-06-24 19:26 UTC, innerthunder commented on src/data/move.ts
> +    return Math.ceil((user.getHpRatio() - 0.25) * 4/3 * 10 - 5);
I simplified the calculation a bit. The idea is that the AI shouldn't use Substitute if they are a boss or don't have enough HP for it to succeed, and otherwise the score increases based on the user's HP ratio (so they're more inclined to use it at higher HP percentages)

2024-06-24 19:46 UTC, innerthunder commented on src/data/move.ts
> +      user.damageAndUpdate(hpCost, HitResult.OTHER, false, true, true);
It does now, just updated `AddSubstituteAttr` to account for magic guard in the `hpCost` calculation.

2024-07-06 05:50 UTC, innerthunder commented on src/data/battler-tags.ts
> +  HIT
The other issue would be determining the order in which these tags would lapse. If a Pokemon with Disguise used Substitute, it'd be expected to have the damage redirected to the Substitute doll first.

2024-07-06 06:21 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}'s substitute faded!"
```suggestion
  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} wurde durch den Fluch verletzt!",
  "battlerTagsSubstituteOnAdd": "Ein Delegator von {{pokemonNameWithAffix}} ist erschienen!",
  "battlerTagsSubstituteOnHit": "Der Delegator steckt den Schlag für {{pokemonName}} ein!",
  "battlerTagsSubstituteOnRemove": "Der Delegator von {{pokemonNameWithAffix}} hört auf zu wirken!"
```

2024-07-06 06:21 UTC, CodeTappert commented on src/data/battler-tags.ts
> +      pokemon.scene.queueMessage(i18next.t("battle:battlerTagsSubstituteOnHit", { pokemonName: pokemon.name }));
Why arent you using the pokemonNameWithAffix: getPokemonNameWithAffix(pokemon) here?

2024-07-06 06:52 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}'s substitute faded!"
```suggestion
  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} wurde durch den Fluch verletzt!",
  "battlerTagsSubstituteOnAdd": "Ein Delegator von {{pokemonNameWithAffix}} ist erschienen!",
  "battlerTagsSubstituteOnHit": "Der Delegator steckt den Schlag für {{pokemonNameWithAffix}} ein!",
  "battlerTagsSubstituteOnRemove": "Der Delegator von {{pokemonNameWithAffix}} hört auf zu wirken!"
```

2024-07-06 07:17 UTC, RimKnight reviewed
Add zh-cn and zh-tw translation.

2024-07-06 07:17 UTC, RimKnight commented on src/locales/zh_CN/battle.ts
> +  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}'s substitute faded!"
```suggestion
  "battlerTagsSubstituteOnAdd": "{{pokemonNameWithAffix}}的\n替身出现了！",
  "battlerTagsSubstituteOnHit": "替身代替{{pokemonNameWithAffix}}\n承受了攻击！",
  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}的\n替身消失了……"
```

2024-07-06 07:17 UTC, RimKnight commented on src/locales/zh_TW/battle.ts
> +  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}'s substitute faded!"
```suggestion
  "battlerTagsSubstituteOnAdd": "{{pokemonNameWithAffix}}的\n替身出現了！",
  "battlerTagsSubstituteOnHit": "替身代替{{pokemonNameWithAffix}}承受了攻擊！",
  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}的\n替身消失了……"
```

2024-07-06 08:06 UTC, EnochG1 reviewed
Korean translation

2024-07-06 08:06 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}'s substitute faded!"
```suggestion
  "battlerTagsSubstituteOnAdd": "{{pokemonNameWithAffix}}의\n대타가 나타났다!",
  "battlerTagsSubstituteOnHit": "{{pokemonNameWithAffix}}[[를]] 대신하여\n대타가 공격을 받았다!",
  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}의\n대타는 사라져 버렸다..."
```

2024-07-06 08:09 UTC, EnochG1 commented
@innerthunder 
Just out of curiosity, what happens if pokemon don't have enough HP?
(In the original game, it fails with the message "But it does not have enough HP left to make a substitute!")

2024-07-06 08:24 UTC, innerthunder commented
> @innerthunder Just out of curiosity, what happens if pokemon don't have enough HP? (In the original game, it fails with the message "But it does not have enough HP left to make a substitute!")

Right now it should just fail with the generic "But it failed!" message.

2024-07-06 11:27 UTC, Adri1 reviewed
Added French

2024-07-06 11:27 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}'s substitute faded!"
```suggestion
  "battlerTagsSubstituteOnAdd": "{{pokemonNameWithAffix}}\ncrée un clone !",
  "battlerTagsSubstituteOnHit": "Le clone subit les dégâts à la place\nde{{pokemonNameWithAffix}} !",
  "battlerTagsSubstituteOnRemove": "Le clone de {{pokemonNameWithAffix}}\ndisparait…"
```

2024-07-07 04:31 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}'s substitute faded!"
```suggestion
  "battlerTagsCursedLapse": "{{pokemonNameWithAffix}} foi ferido pelo Curse!",
  "battlerTagsSubstituteOnAdd": "{{pokemonNameWithAffix}} colocou um substituto!",
  "battlerTagsSubstituteOnHit": "O substituto tomou o dano pelo {{pokemonNameWithAffix}}!",
  "battlerTagsSubstituteOnRemove": "O substituto de {{pokemonNameWithAffix}} desbotou!"
```

2024-07-09 14:09 UTC, NicusPulcis commented
hey @innerthunder i've added the italian translation

2024-07-17 06:05 UTC, innerthunder commented
## Animations

With Substitute comes a new suite of in-battle animations (and a new phase to implement them)! The videos below show all of the new animations surrounding the Substitute doll in action during a double battle.

### Videos

**Adding Substitutes:**

https://github.com/user-attachments/assets/7394e1ad-e066-4a79-a215-00c04f30ec9d

When a Pokemon uses Substitute, a new sprite is generated (with its reference attached to the respective `SubstituteTag`), and the Pokemon is moved "out of focus," becoming semi-transparent.

**Switching Pokemon with Substitutes:**

https://github.com/user-attachments/assets/edd2be80-a024-44f4-8538-bd96a7c2c2d5

- When a Pokemon with an active Substitute switches normally, the Substitute's sprite despawns (after a short animation) before the switched-in Pokemon is summoned.
- When a Pokemon with an active Substitute uses Baton Pass, the Substitute's sprite remains on the field and becomes visible after the move resolves.

**Hitting and Removing Substitutes:**

https://github.com/user-attachments/assets/884f6d08-0172-4815-9ac8-c9fb520546be

- When a Pokemon with a Substitute uses a move, it moves into focus, uses the move, then moves back out of focus.
- When a Pokemon's Substitute takes more than its remaining HP in damage, a fading animation despawns the Substitute's sprite and brings the Pokemon back "into focus."

**KOing Pokemon with Substitutes:**

https://github.com/user-attachments/assets/602954cd-b456-43c0-8594-dd3fb51ea2af

When a Pokemon faints while it has a Substitute active, the Substitute's sprite is also removed from the field.

**Loading in Pokemon with Substitutes:**

https://github.com/user-attachments/assets/2ab94298-7ac5-47c8-86d5-180899268e3c

When the player loads into a wave where a Pokemon started with a Substitute, the on-add animation is replayed to regenerate the Substitute sprite.

2024-07-17 07:55 UTC, Xavion3 requested changes
Started reviewing this, but its a lot.

2024-07-17 07:55 UTC, Xavion3 commented on src/data/move.ts
> +   * example: @see {@linkcode Moves.WHIRLWIND}
Why is this being changed?

2024-07-17 07:55 UTC, Xavion3 commented on src/data/move.ts
> +    applyAbAttrs(BlockNonDirectDamageAbAttr, user, blockSelfDamage);
Magic guard doesn't prevent you damaging yourself with substitute.

2024-07-17 07:55 UTC, Xavion3 commented on src/data/move.ts
> +      .condition((user, target, move) => !user.getSubstitute() && user.getHpRatio() > 0.25 && !user.hasAbility(Abilities.WONDER_GUARD, false, true)),
Just check if max hp is > 1 probably, as that is what we're actually looking for.

2024-07-17 07:55 UTC, Xavion3 commented on src/field/pokemon.ts
> +  }
Why does this exist when its just a wrapper on the already existing getTag?

2024-07-17 08:34 UTC, innerthunder commented on src/field/pokemon.ts
> +  }
I made it because `getTag` would return the substitute tag as a `BattlerTag`. Since the code to manage the Substitute's sprite (outside of the tag itself) needs to access the tag's `sprite` field, it needs to be interpreted as a `SubstituteTag`.

I.e. instead of getting the tag's sprite like this:
```ts
const substitute = pokemon.getSubstitute();
if (!!substitute) {
  // do stuff with substitute.sprite
}
```
I'd either have to add a `instanceof` check wherever I need to access the Substitute's sprite
```ts
const substitute = pokemon.getTag(BattlerTagType.SUBSTITUTE);
if (!!substitute && substitute instanceof SubstituteTag) {
  // do stuff with substitute.sprite
}
```
or use `as` to change the type, which isn't as safe as using `instanceof`.
```ts
const substitute = pokemon.getTag(BattlerTagType.SUBSTITUTE) as SubstituteTag;
if (!!substitute) {
  // do stuff with substitute.sprite
}
```

2024-07-17 08:42 UTC, innerthunder commented on src/data/move.ts
> +   * example: @see {@linkcode Moves.WHIRLWIND}
It was a typo 😶, just fixed it

2024-07-17 09:23 UTC, AsdarDevelops requested changes
Spanish localization

2024-07-17 09:23 UTC, AsdarDevelops commented on src/locales/es/battle.ts
> +  "battlerTagsSubstituteOnRemove": "{{pokemonNameWithAffix}}'s substitute faded!"
```suggestion
  "battlerTagsSubstituteOnAdd": "¡{{pokemonNameWithAffix}} creó un sustituto!",
  "battlerTagsSubstituteOnHit": "¡El sustituto recibe daño en lugar del {{pokemonNameWithAffix}}!",
  "battlerTagsSubstituteOnRemove": "¡El sustituto del {{pokemonNameWithAffix}} se debilitó!"
```

2024-07-18 05:18 UTC, innerthunder commented
## Updates since opening this PR

- ES locale updated. All of Substitute's messages should be fully translated now!
- `data/battle-anims`: Added an option in `BattleAnim.play` to center target-based animations on the target Pokemon's Substitute instead of the target Pokemon itself. Calls to `play` in `phases.ts` and other files were also edited to account for the new option.
- `phases`: Target Pokemon no longer flash in the `DamagePhase` when the damage taken for that phase is 0. This means a Pokemon will not flash when it redirects damage with a Substitute.
- `BattleAnimPhase` and `BattleAnimType` have been renamed to `PokemonAnimPhase` and `PokemonAnimType` respectively to avoid confusion with the `BattleAnim` class in `data/battle-anims.ts`. The files containing these classes have also been renamed accordingly.

2024-07-18 06:19 UTC, Xavion3 commented on src/field/pokemon.ts
> +  }
`as` is implicitly safe here due to the structure of getTag as only being able to return the given tag or a falsy value. Like, we could teach typescript this if we really wanted, but we haven't bothered because it'd add dozens of lines of code just to make this slightly less aggressive about throwing warnings.

2024-07-18 20:23 UTC, innerthunder commented on src/field/pokemon.ts
> +  }
Just removed this function and added overloads to `getTag` from https://github.com/pagefaultgames/pokerogue/pull/2960 as discussed in the Discord:

```ts
/** @overload */
getTag(tagType: BattlerTagType): BattlerTag;

/** @overload */
getTag<T extends BattlerTag>(tagType: Constructor<T>): T;
```

2024-07-23 10:06 UTC, DayKev commented on src/test/moves/substitute.test.ts
> +    vi.spyOn(overrides, "SINGLE_BATTLE_OVERRIDE", "get").mockReturnValue(true);
There's [an overrides refactor](https://github.com/pagefaultgames/pokerogue/pull/3104) coming soon as requested by flx so you'll probably need to change this to `vi.spyOn(overrides, "BATTLE_TYPE_OVERRIDE", "get").mockReturnValue("single");`.

2024-07-23 10:08 UTC, DayKev commented
Oops I almost forgot to mention, you should probably add a test for Baton Pass.

>A substitute can be passed by [Baton Pass](https://bulbapedia.bulbagarden.net/wiki/Baton_Pass_(move)) with the HP it has remaining.

- https://bulbapedia.bulbagarden.net/wiki/Substitute_(doll)#Effect

2024-08-03 17:40 UTC, snoozbuster commented
Are we able to implement shed tail by combining AddSubstituteAttr and ForceSwitchOutAttr? I looked through move.ts in this PR and it didn't seem like it had been done

2024-08-04 13:15 UTC, torranx commented on src/data/ability.ts
> +        if (!!opponent.getTag(BattlerTagType.SUBSTITUTE)) {
I think placing the `opponent.getTag()` inside an if condition already converts it to bool?

2024-08-04 13:21 UTC, torranx commented on src/data/move.ts
> +export class RemoveAllSubstitutesAttr extends MoveEffectAttr {
add docs

2024-08-04 13:27 UTC, torranx commented on src/test/moves/substitute.test.ts
> +      .enemyMoveset(Array(4).fill(Moves.SPLASH))
```suggestion
      .enemyMoveset(SPLASH_ONLY)
```

2024-08-04 13:31 UTC, torranx commented on src/test/moves/substitute.test.ts
> +      expect(leadPokemon.hp).toBe(Math.ceil(leadPokemon.getMaxHp() * 3/4));
since the `enemyLevel` is high, there's a tendency that it will heal through item and this could fail

2024-08-04 13:49 UTC, DayKev commented on src/test/moves/substitute.test.ts
> +      expect(leadPokemon.hp).toBe(Math.ceil(leadPokemon.getMaxHp() * 3/4));
The player Pokémon shouldn't spawn with any held items, and the enemy Pokémon is already set to only have Splash. In this case I don't think any held items can interfere.

2024-08-04 13:53 UTC, torranx commented on src/test/moves/substitute.test.ts
> +      expect(leadPokemon.hp).toBe(Math.ceil(leadPokemon.getMaxHp() * 3/4));
oh right, I thought it was checking for enemy

2024-08-20 23:10 UTC, snoozbuster commented on src/battle-scene.ts
> +      p.destroySubstitute();
is there some reason why `p.destroy()` shouldn't call destroySubstitute? is there some weird edge case where we want to keep the sub even though the pkmn is destroyed?

2024-08-20 23:12 UTC, snoozbuster commented on src/data/ability.ts
> +    if (pokemon !== attacker && !!pokemon.getTag(BattlerTagType.SUBSTITUTE) && !move.canIgnoreSubstitute(attacker)) {
`!!` on `getTag` shouldn't be necessary, all types are coerced to boolean inside an if statement (as far as I'm aware, even TS shouldn't complain on strict settings). it's only necessary if you want to return the value or store it in a boolean variable

2024-08-20 23:16 UTC, snoozbuster commented on src/data/battle-anims.ts
> +      const targetSubstitute = (!!onSubstitute && user !== target) ? target!.getTag(SubstituteTag) : null;
this is another place where `!!` shouldn't be necessary

2024-08-20 23:19 UTC, snoozbuster commented on src/data/battler-tags.ts
> +    // TODO: load this tag's sprite (or generate a new one upon loading a game)
still relevant?

2024-08-20 23:20 UTC, snoozbuster commented on src/data/move.ts
> +  IGNORE_SUBSTITUTE = 1 << 18,
can you add a docstring? I understand that this particular flag is relatively obvious, but it's still a good pattern to have.

2024-08-20 23:22 UTC, snoozbuster commented on src/data/move.ts
> +        || user?.hasAbility(Abilities.INFILTRATOR)
pursuit needs to conditionally bypass substitute - it should only bypass it if the special effect triggers. instead of explicitly checking for an ability do you think that we could use a battler tag or something like that, which then infiltrator can apply? do you know if there's a better solution for this?

2024-08-20 23:27 UTC, snoozbuster commented on src/data/move.ts
> +          (target?.getTag(BattlerTagType.SUBSTITUTE) && !this.canIgnoreSubstitute(user))) {
I feel like I've seen the pattern of `pkmn.getTag(sub) && canIgnoreSub(user)` in a number of places already. do you think these could be combined somehow? for example, perhaps `pkmn.getTag(sub)?.canIgnoreSub(...)` would work well - it automatically evaluates to a falsy value if the sub tag is missing. I think there's also some value in putting the logic for what moves can ignore sub within the main part of the sub code (the tag) - keeps related code in more or less the same place. 

maybe there's a better place for this to live - perhaps the Pokemon class could have the `canIgnoreSubstitute` method which internally first looks for the tag and then does the rest of the logic (although in that case, based on the implementation and params it would need to be called something like `isBypassingSubstitute`). but it seems like it ought to be one fluid call somehow instead of two distinct checks that always need to happen together.

2024-08-20 23:27 UTC, snoozbuster commented on src/data/move.ts
> +          && this.checkFlag(MoveFlags.MAKES_CONTACT, user, null)) {
why the change to null?

2024-08-20 23:30 UTC, snoozbuster commented on src/data/move.ts
> +    if (!this.selfTarget && !!target.getTag(SubstituteTag) && !move.canIgnoreSubstitute(user)) {
another unnecessary `!!`, plus another instance of the `getTag() && canIgnoreSub()` pattern

2024-08-20 23:30 UTC, snoozbuster commented on src/data/move.ts
> +      if (!!target.getTag(SubstituteTag) && !move.canIgnoreSubstitute(user)) {
same pattern

2024-08-20 23:30 UTC, snoozbuster commented on src/data/move.ts
> +    if (!!target.getTag(SubstituteTag) && !move.canIgnoreSubstitute(user)) {
etc and so on (I'm not commenting on any more but I imagine you can find them all by searching for `canIgnoreSubstitute`

2024-08-20 23:34 UTC, snoozbuster commented on src/data/move.ts
> +      .condition((user, target, move) => !user.getTag(SubstituteTag) && user.getHpRatio() > 0.25 && user.getMaxHp() > 1),
I feel like you should encode this condition into `AddSubstituteAttr`'s `apply()` method instead. actually, is that how that works? I guess the move doesn't fail if that function returns false. isn't there another hook that attrs have to force-fail the move though?

given how heavily dependent the attr's `apply()` method is on this check being present and correct, it seems like the condition that guarantees it should be somewhere nearby.

2024-08-20 23:36 UTC, snoozbuster commented on src/data/move.ts
> +      .condition((user, target, move) => !target.getTag(BattlerTagType.SUBSTITUTE))
don't you need the canIgnoreSub check here? what if a sky drop user has infiltrator?

2024-08-20 23:52 UTC, snoozbuster commented on src/data/battler-tags.ts
> +    const hasSubstitute = pokemon.getTag(BattlerTagType.SUBSTITUTE);
I guess sub always blocks trapping moves even if the user has inflitrator?

2024-08-21 03:51 UTC, innerthunder commented on src/data/move.ts
> +      .condition((user, target, move) => !target.getTag(BattlerTagType.SUBSTITUTE))
From [Bulba](https://bulbapedia.bulbagarden.net/wiki/Substitute_(doll)#Unaffected_moves):

> Since [Generation VI](https://bulbapedia.bulbagarden.net/wiki/Generation_VI), a Pokémon with [Infiltrator](https://bulbapedia.bulbagarden.net/wiki/Infiltrator_(Ability)) can ignore a substitute with any move except [Transform](https://bulbapedia.bulbagarden.net/wiki/Transform_(move)) or [Sky Drop](https://bulbapedia.bulbagarden.net/wiki/Sky_Drop_(move)).

2024-08-21 03:54 UTC, innerthunder commented on src/data/move.ts
> +  IGNORE_SUBSTITUTE = 1 << 18,
Done

2024-08-21 04:15 UTC, innerthunder commented on src/data/move.ts
> +          && this.checkFlag(MoveFlags.MAKES_CONTACT, user, null)) {
Unseen Fist is meant to ignore Protect with every move that's allowed to make contact, even if the move would not make contact against a specific target.

Consider this scenario:
- Player is a Pokemon with Unseen Fist, Enemy is a Pokemon with Flame Body and a Substitute from a previous turn.
- Enemy uses Protect, then Player attacks into Enemy with Tackle (a move that makes contact in normal situations).

Because Player has Unseen Fist, it would ignore Enemy's Protect and deal damage to Enemy's Substitute. However, because the attack was deflected onto the Substitute, Player technically didn't make contact with Enemy, so Enemy's Flame Body will never activate.

Oh, and if you're wondering "Why not just use `hasTag`?", Unseen Fist still respects Long Reach if the user were to have both abilities (as far as I know, this is currently impossible with the passives available, but if a similar effect to Long Reach were implemented via something like Punching Gloves, then this would be relevant).

2024-08-21 04:19 UTC, innerthunder commented on src/data/move.ts
> +          (target?.getTag(BattlerTagType.SUBSTITUTE) && !this.canIgnoreSubstitute(user))) {
I ended up reducing this (and similar checks) to `move.hitsSubstitute(user, target)` (or the inverse). This cleaned things up pretty well, but I still feel like there are some redundant calls to it that I can reduce.

2024-08-21 04:28 UTC, innerthunder commented on src/data/battler-tags.ts
> +    // TODO: load this tag's sprite (or generate a new one upon loading a game)
nope 🍝

2024-08-21 04:29 UTC, innerthunder commented on src/data/move.ts
> +  IGNORE_SUBSTITUTE = 1 << 18,
Done

2024-08-21 04:32 UTC, innerthunder commented on src/data/move.ts
> +        || user?.hasAbility(Abilities.INFILTRATOR)
I figure the easiest way would be to add a field to `turnData` (say, `isPursuing`). Not really sure if there's an easy way to check if a specific move attribute has applied via the move itself atm.

2024-08-21 04:36 UTC, innerthunder commented on src/data/move.ts
> +      .condition((user, target, move) => !user.getTag(SubstituteTag) && user.getHpRatio() > 0.25 && user.getMaxHp() > 1),
It probably would be better off in a `getCondition()` method for the attribute (putting it in `apply()` wouldn't generate a fail message for that condition), but yeah.

2024-08-26 05:00 UTC, EnochG1 submitted a review, later dismissed

2024-08-26 07:22 UTC, innerthunder commented on src/data/battler-tags.ts
> +    const hasSubstitute = pokemon.getTag(BattlerTagType.SUBSTITUTE);
Not totally sure on this. Bulba says gaining a Substitute removes all binding effects from the user, but whether or not blocked effects are still applicable when the attacker has Infiltrator isn't made clear.

I ended up changing this condition to `!move.hitsSubstitute(attacker)`, so trap effects will go through if the attacker has Infiltrator for the time being.

2024-09-09 18:59 UTC, Chapybara-jp approved these changes

2024-09-10 07:40 UTC, DayKev commented on src/data/move.ts
> +  REDIRECT_COUNTER  = 1 << 19,
```suggestion
  REDIRECT_COUNTER = 1 << 19,
```

2024-09-10 07:40 UTC, DayKev commented on src/data/move.ts
> +    const hpCost = Math.floor(user.getMaxHp() / 4);
This should be a parameter for the move to set, because Shed Tail deals 50% damage to the user (though the sub still only has HP equal to 25% of the user's max HP).

2024-09-10 07:40 UTC, DayKev commented on src/field/pokemon.ts
> +    if (!!substitute && !!substitute.sprite) {
```suggestion
    if (substitute && substitute.sprite) {
```

2024-09-10 07:40 UTC, DayKev commented on src/field/pokemon.ts
> +    if (!!substitute) {
```suggestion
    if (substitute) {
```

2024-09-10 07:40 UTC, DayKev commented on src/field/pokemon.ts
> +      if (!!this.getTag(SubstituteTag)) {
```suggestion
      if (this.getTag(SubstituteTag)) {
```

2024-09-10 07:40 UTC, DayKev commented on src/phases/switch-summon-phase.ts
> +import { SubstituteTag } from "#app/data/battler-tags.js";
```suggestion
import { SubstituteTag } from "#app/data/battler-tags";
```

2024-09-10 07:40 UTC, DayKev commented on src/phases/switch-summon-phase.ts
> +      if (!!substitute) {
```suggestion
      if (substitute) {
```

2024-09-10 07:40 UTC, DayKev commented on src/phases/switch-summon-phase.ts
> +          if (!!substitute) {
```suggestion
          if (substitute) {
```

2024-09-10 07:40 UTC, DayKev commented on src/ui/target-select-ui-handler.ts
> +import { SubstituteTag } from "#app/data/battler-tags.js";
```suggestion
import { SubstituteTag } from "#app/data/battler-tags";
```

2024-09-10 08:17 UTC, innerthunder commented on src/data/move.ts
> +    const hpCost = Math.floor(user.getMaxHp() / 4);
I don't think Shed Tail will be able to make use of this attribute easily either way. The sequencing for adding the substitute doll fundamentally changes since Shed Tail has to generate the substitute onto the switched-in Pokemon (kinda like Baton Pass's implementation, I imagine).

2024-09-10 13:42 UTC, DayKev commented on src/data/move.ts
> +    const hpCost = Math.floor(user.getMaxHp() / 4);
Well the HP of the sub needs to be preserved when using Shed Tail or Baton Pass, are you saying they'd have to generate a new sub and manually set the HP value of it or something?

2024-09-11 05:46 UTC, innerthunder commented on src/data/move.ts
> +    const hpCost = Math.floor(user.getMaxHp() / 4);
Nvm, I just read Smogon's description of Shed Tail. I assumed the substitute was generated on the switched-in Pokemon after the switch resolved, but it's actually generated beforehand on the move user and then transferred over.

2024-09-11 05:55 UTC, innerthunder commented on src/data/move.ts
> +    const hpCost = Math.floor(user.getMaxHp() / 4);
Actually, I just noticed that the HP costs for Substitute and Shed Tail are rounded differently???

Substitute:
>The user takes 1/4 of its maximum HP, rounded down, and puts it into a substitute to take its place in battle.

Shed Tail:
>The user takes 1/2 of its maximum HP, rounded up, and creates a substitute that has 1/4 of the user's maximum HP, rounded down.

2024-09-11 05:58 UTC, innerthunder commented on src/data/move.ts
> +    const hpCost = Math.floor(user.getMaxHp() / 4);
Eh, I think Shed Tail needs a dedicated attribute anyway. The order of adding the substitute, then switching and transferring the substitute to the party Pokemon is something that should be enforced by a single attribute imo.

2024-09-11 12:38 UTC, SangaraSorama approved these changes

2024-09-11 12:55 UTC, DayKev commented on src/data/move.ts
> +    const hpCost = Math.floor(user.getMaxHp() / 4);
The sub itself has the same rounding, at least.

2024-09-12 03:33 UTC, DayKev commented
Other than sprite issues, it seems good.

Sub sprite offset from where it should be:
![image](https://github.com/user-attachments/assets/5da2559b-d726-46c9-8adc-c486fdff251a)
Gastly still offset after transitioning to a trainer battle:
![image](https://github.com/user-attachments/assets/12370e47-7e63-428d-bb15-ea5e7fff442a)

2024-09-13 04:55 UTC, DayKev approved these changes

2024-09-13 16:46 UTC, merged