Localization: Add new translations for party UI handler
pagefaultgames/pokerogue pull request #2566
Opened 2024-06-24 17:34 UTC by josericardo-fo

## What are the changes?

Localizations and translations

## Why am I doing these changes?

They weren't localized

## What did change?

Localized everything in party-ui-handler.ts

### Screenshots/Videos

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-24 19:41 UTC, Adri1 reviewed
Added French

2024-06-24 19:41 UTC, Adri1 commented on src/locales/fr/party-ui-handler.ts
> +  "smellYaLater": "Smell ya later, {{pokemonName}}!",
```suggestion
  "UNSPLICE": "Séparer",
  "ACTIVATE": "Activer",
  "DEACTIVATE": "Désactiver",

  "choosePokemon": "Sélectionnez un Pokémon.",
  "noEnergy": "{{pokemonName}} n’a plus l’énergie\nde se battre !",
  "hasEnergy": "{{pokemonName}} peut toujours\nse battre !",
  "cantBeUsed": "{{pokemonName}} ne peut pas\nse battre pour ce challenge !",
  "tooManyItems": "{{pokemonName}} porte trop\nd’exemplaires de cet objet !",
  "anyEffect": "Cela n’aura aucun effet.",
  "unpausedEvolutions": "{{pokemonName}} peut de nouveau évoluer.",
  "unspliceConfirmation": "Voulez-vous vraiment séparer {{fusionName}}\nde {{pokemonName}} ? {{fusionName}} sera perdu.",
  "wasReverted": "{{fusionName}} est redevenu {{pokemonName}}.",
  "releaseConfirmation": "Voulez-vous relâcher {{pokemonName}} ?",
  "releaseInBattle": "Vous ne pouvez pas relâcher Pokémon en combat !",
  "doWhat": "Que faire avec ce Pokémon ?",
  "selectAMove": "Sélectionnez une capacité.",
  "changeQuantity": "Sélect. un objet à transférer.\nChangez la quantité avec < et >.",
  "selectAnotherPokemonToSplice": "Sélectionnez un autre Pokémon à séparer.",
  "cancel": "Sortir",

  // Slot TM text
  "able": "Apte",
  "notAble": "Pas Apte",
  "learned": "Appris",

  // Releasing messages
  "goodbye": "Au revoir, {{pokemonName}} !",
  "byebye": "Bye-bye, {{pokemonName}} !",
  "farewell": "Adieu, {{pokemonName}} !",
  "soLong": "Salut, {{pokemonName}} !",
  "thisIsWhereWePart": "C’est là qu’on se sépare, {{pokemonName}}!",
  "illMissYou": "Tu vas me manquer, {{pokemonName}} !",
  "illNeverForgetYou": "Je ne t’oublierai pas, {{pokemonName}} !",
  "untilWeMeetAgain": "À la prochaine, {{pokemonName}} !",
  "sayonara": "Sayonara, {{pokemonName}} !",
  "smellYaLater": "À plus tard, {{pokemonName}}!",
```

2024-06-24 19:54 UTC, CodeTappert commented on src/locales/de/party-ui-handler.ts
> +  "UNSPLICE": "Unsplice",
```suggestion
  "UNSPLICE": "De-fusionieren",
```

2024-06-24 20:16 UTC, CodeTappert commented on src/locales/de/party-ui-handler.ts
> +  "smellYaLater": "Smell ya later, {{pokemonName}}!",
```suggestion
  "TEACH": "Erlernen",
  "UNSPLICE": "Defusionieren",
  "ACTIVATE": "Aktivieren",
  "DEACTIVATE": "Deaktivieren",

  "choosePokemon": "Wähle ein Poké,om.",
  "noEnergy": "{{pokemonName}} ist nicht fit genug, um zu kämpfen!",
  "hasEnergy": "{{pokemonName}} steckt noch voller Energie",
  "cantBeUsed": "{{pokemonName}} kann in dieser Herausforderung nicht verwendet werden!",
  "tooManyItems": "{{pokemonName}} trägt bereits zu viele dieser Items!",
  "anyEffect": "Das würde keine Wirkung zeigen.",
  "unpausedEvolutions": "Entwicklungen für {{pokemonName}} wurden wieder aktiviert.",
  "unspliceConfirmation": "Willst du wirklich {{fusionName}} von {{pokemonName}} defusionieren? {{fusionName}} wird freigelassen.",
  "wasReverted": "{{fusionName}} verwandelt sich in {{pokemonName}} zurück.",
  "releaseConfirmation": "Möchtest du {{pokemonName}} wirklich freilassen?",
  "releaseInBattle": "Pokémon, die aktuell im Kampf sind, können nicht freigelassen werden.",
  "doWhat": "Was soll mit diesem Pokémon geschehen?",
  "selectAMove": "Wähle eine Attacke.",
  "changeQuantity": "Wähle ein getragenes Item aus, das übertragen werden soll. Nutze < und > um die Anzahl zu ändern.",
  "selectAnotherPokemonToSplice": "Wähle ein anderes Pokémon mit dem fusioniert werden soll aus.",
  "cancel": "Abbrechen",

  // Slot TM text
  "able": "Erlernbar!",
  "notAble": "Nicht erlernbar",
  "learned": "Bereits erlernt!",

  // Releasing messages
  "goodbye": "Auf wiedersehen, {{pokemonName}}!",
  "byebye": "Byebye, {{pokemonName}}!",
  "farewell": "Mach’s gut, {{pokemonName}}!",
  "soLong": "Bis dann, {{pokemonName}}!",
  "thisIsWhereWePart": "Nun heißt es Abschied nehmen, {{pokemonName}}!",
  "illMissYou": "Ich werde dich vermissen, {{pokemonName}}!",
  "illNeverForgetYou": "Ich werde dich niemals vergessen, {{pokemonName}}!",
  "untilWeMeetAgain": "Bis wir uns wiedersehen, {{pokemonName}}!",
  "sayonara": "Sayonara, {{pokemonName}}!",
  "smellYaLater": "Also dann, man riecht sich! Ciao!, {{pokemonName}}!",
```

2024-06-24 21:11 UTC, Adri1 approved these changes

2024-06-24 21:44 UTC, Adri1 reviewed
Tiny french edit

2024-06-24 21:44 UTC, Adri1 commented on src/locales/fr/party-ui-handler.ts
> +  "smellYaLater": "À plus tard, {{pokemonName}}!",
```suggestion
  "smellYaLater": "À plus tard, {{pokemonName}} !",
```

2024-06-25 02:05 UTC, edaymall commented on src/locales/en/party-ui-handler.ts
> +  "learned": "Learned",
```suggestion
  "able": "배울 수 있다",
  "notAble": "배울 수 없다",
  "learned": "이미 알고 있다",
```

2024-06-25 02:07 UTC, sodaMelon commented on src/locales/ko/party-ui-handler.ts
> +  "learned": "Learned",
```suggestion
  "able": "배울 수 있다",
  "notAble": "배울 수 없다",
  "learned": "이미 알고 있다",
```

2024-06-25 02:26 UTC, InnocentGameDev commented on src/locales/es/party-ui-handler.ts
> +  "anyEffect": "It won't have any effect.",
```suggestion
  "TEACH": "Enseñar",
  "UNSPLICE": "Revertir Fusión",
  "ACTIVATE": "Activar",
  "DEACTIVATE": "Desactivar",

  "choosePokemon": "Elige a un Pokémon.",
  "noEnergy": "¡A {{pokemonName}} no le quedan\nfuerzas para combatir!",
  "hasEnergy": "¡A {{pokemonName}} aún le quedan\nfuerzas para combatir!",
  "cantBeUsed": "¡{{pokemonName}} no puede ser elegido\npara este reto!",
  "tooManyItems": "¡{{pokemonName}} tiene ya suficientes\n objetos de este tipo!",
  "anyEffect": "No tendrá ningún efecto.",
```

2024-06-25 02:40 UTC, josericardo-fo commented on src/locales/es/party-ui-handler.ts
> +  "anyEffect": "It won't have any effect.",
Outdated, suggest again
sorry

2024-06-25 02:51 UTC, 40chyan commented on src/locales/zh_CN/party-ui-handler.ts
> +  "smellYaLater": "Smell ya later, {{pokemonName}}!",
```suggestion
  "UNSPLICE": "分离",
  "ACTIVATE": "激活",
  "DEACTIVATE": "解除",

  "choosePokemon": "选择一只宝可梦。",
  "noEnergy": "{{pokemonName}}没有力气战斗了！",
  "hasEnergy": "{{pokemonName}}仍然精神十足！",
  "cantBeUsed": "{{pokemonName}}无法在此挑战中使用！",
  "tooManyItems": "{{pokemonName}}拥有\n太多这个道具了！",
  "anyEffect": "即便使用也无效果哦。",
  "unpausedEvolutions": "{{pokemonName}}的进化停止了。",
  "unspliceConfirmation": "真的要把{{fusionName}}\n从{{pokemonName}}身上分离吗? {{fusionName}}会就此消失。",
  "wasReverted": "{{fusionName}}恢复成了{{pokemonName}}。",
  "releaseConfirmation": "你真要放生{{pokemonName}}吗？",
  "releaseInBattle": "你无法放生正在战斗中的宝可梦！",
  "doWhat": "要对宝可梦做什么？",
  "selectAMove": "选择一个招式。",
  "changeQuantity": "选择一件道具来交换。\n使用 ← 和 → 来指定数量。",
  "selectAnotherPokemonToSplice": "选择另一只宝可梦来融合。",
  "cancel": "取消",

  // Slot TM text
  "able": "能学会！",
  "notAble": "无法学习",
  "learned": "已习得",

  // Releasing messages
  "goodbye": "再见，{{pokemonName}}！",
  "byebye": "拜拜，{{pokemonName}}！",
  "farewell": "再会了，{{pokemonName}}！",
  "soLong": "告辞了，{{pokemonName}}！",
  "thisIsWhereWePart": "就此分别吧，{{pokemonName}}！",
  "illMissYou": "我会想你的，{{pokemonName}}！",
  "illNeverForgetYou": "我不会忘记你的，{{pokemonName}}！",
  "untilWeMeetAgain": "下次再见了，{{pokemonName}}！",
  "sayonara": "撒由那拉，{{pokemonName}}！",
  "smellYaLater": "拜拜了您嘞，{{pokemonName}}！",
```
cn translation

2024-06-25 02:56 UTC, ddullgi commented
I think you might have missed 'SPLICE', 'PASS_BATON', and 'UNPAUSE_EVOLUTION'.

https://github.com/pagefaultgames/pokerogue/blob/dd7fc7268cf156641de532aea21ec64574723236/src/ui/party-ui-handler.ts#L41-L62

2024-06-25 03:48 UTC, ddullgi commented on src/locales/de/party-ui-handler.ts
> +  "UNSPLICE": "Defusionieren",
```suggestion
  "PASS_BATON": "Pass Baton",
  "REVIVE": "Revive",
  "UNPAUSE_EVOLUTION": "Unpause Evolution",
  "SPLICE": "Splice",
  "UNSPLICE": "Defusionieren",
```

2024-06-25 03:48 UTC, ddullgi commented on src/locales/en/party-ui-handler.ts
> +  "UNSPLICE": "Unsplice",
```suggestion
  "PASS_BATON": "Pass Baton",
  "REVIVE": "Revive",
  "UNPAUSE_EVOLUTION": "Unpause Evolution",
  "SPLICE": "Splice",
  "UNSPLICE": "Unsplice",
```

2024-06-25 03:48 UTC, ddullgi commented on src/locales/es/party-ui-handler.ts
> +  "UNSPLICE": "Unsplice",
```suggestion
  "PASS_BATON": "Pass Baton",
  "REVIVE": "Revive",
  "UNPAUSE_EVOLUTION": "Unpause Evolution",
  "SPLICE": "Splice",
  "UNSPLICE": "Unsplice",
```

2024-06-25 03:48 UTC, ddullgi commented on src/locales/fr/party-ui-handler.ts
> +  "UNSPLICE": "Séparer",
```suggestion
  "PASS_BATON": "Pass Baton",
  "REVIVE": "Revive",
  "UNPAUSE_EVOLUTION": "Unpause Evolution",
  "SPLICE": "Splice",
  "UNSPLICE": "Séparer",
```

2024-06-25 03:48 UTC, ddullgi commented on src/locales/it/party-ui-handler.ts
> +  "UNSPLICE": "Unsplice",
```suggestion
  "PASS_BATON": "Pass Baton",
  "REVIVE": "Revive",
  "UNPAUSE_EVOLUTION": "Unpause Evolution",
  "SPLICE": "Splice",
  "UNSPLICE": "Unsplice",
```

2024-06-25 03:48 UTC, ddullgi commented on src/locales/ko/party-ui-handler.ts
> +  "UNSPLICE": "Unsplice",
```suggestion
  "PASS_BATON": "Pass Baton",
  "REVIVE": "Revive",
  "UNPAUSE_EVOLUTION": "Unpause Evolution",
  "SPLICE": "Splice",
  "UNSPLICE": "Unsplice",
```

2024-06-25 03:48 UTC, ddullgi commented on src/locales/pt_BR/party-ui-handler.ts
> +  "UNSPLICE": "Separar",
```suggestion
  "PASS_BATON": "Pass Baton",
  "REVIVE": "Revive",
  "UNPAUSE_EVOLUTION": "Unpause Evolution",
  "SPLICE": "Splice",
  "UNSPLICE": "Separar",
```

2024-06-25 03:48 UTC, ddullgi commented on src/locales/zh_CN/party-ui-handler.ts
> +  "UNSPLICE": "Unsplice",
```suggestion
  "PASS_BATON": "Pass Baton",
  "REVIVE": "Revive",
  "UNPAUSE_EVOLUTION": "Unpause Evolution",
  "SPLICE": "Splice",
  "UNSPLICE": "Unsplice",
```

2024-06-25 03:48 UTC, ddullgi commented on src/locales/zh_TW/party-ui-handler.ts
> +  "UNSPLICE": "Unsplice",
```suggestion
  "PASS_BATON": "Pass Baton",
  "REVIVE": "Revive",
  "UNPAUSE_EVOLUTION": "Unpause Evolution",
  "SPLICE": "Splice",
  "UNSPLICE": "Unsplice",
```

2024-06-25 11:03 UTC, Adri1 reviewed
French Splice translation

2024-06-25 11:03 UTC, Adri1 commented on src/locales/fr/party-ui-handler.ts
> +  "SPLICE": "Splice",
```suggestion
  "SPLICE": "Fusionner",
```

2024-06-25 11:03 UTC, CodeTappert commented on src/locales/de/party-ui-handler.ts
> +  "REVIVE": "Revive",
```suggestion
  "TRANSFER": "Übertragen",
  "ALL": "Alle",
  "PASS_BATON": "Stafette nutzen",
  "UNPAUSE_EVOLUTION": "Entwicklung fortsetzen",
  "REVIVE": "Wiederbeleben",
```

2024-06-25 11:04 UTC, CodeTappert commented on src/locales/de/party-ui-handler.ts
> +  "SPLICE": "Splice",
```suggestion
  "SPLICE": "Fusionieren",
```

2024-06-25 11:07 UTC, Adri1 commented on src/locales/fr/party-ui-handler.ts
> +  "REVIVE": "Revive",
```suggestion
  "SPLICE": "Fusionner",
  "UNSPLICE": "Séparer",
  "ACTIVATE": "Activer",
  "DEACTIVATE": "Désactiver",
  "TRANSFER": "Transférer",
  "ALL": "Tout",
  "PASS_BATON": "Relais",
  "UNPAUSE_EVOLUTION": "Réactiver Évolution",
  "REVIVE": "Ranimer",
```

2024-06-25 13:57 UTC, 40chyan commented on src/locales/zh_CN/party-ui-handler.ts
> +  "smellYaLater": "Smell ya later, {{pokemonName}}!",
```suggestion
  "SPLICE": "融合",
  "UNSPLICE": "分离",
  "ACTIVATE": "激活",
  "DEACTIVATE": "解除",
  "TRANSFER": "交换",
  "ALL": "全部道具",
  "PASS_BATON": "接棒",
  "UNPAUSE_EVOLUTION": "接触进化暂停",
  "REVIVE": "复活",

  "choosePokemon": "选择一只宝可梦。",
  "doWhatWithThisPokemon": "要对宝可梦做什么？",
  "noEnergy": "{{pokemonName}}没有力气战斗了！",
  "hasEnergy": "{{pokemonName}}仍然精神十足！",
  "cantBeUsed": "{{pokemonName}}无法在此挑战中使用！",
  "tooManyItems": "{{pokemonName}}拥有\n太多这个道具了！",
  "anyEffect": "即便使用也无效果哦。",
  "unpausedEvolutions": "{{pokemonName}}的进化停止了。",
  "unspliceConfirmation": "真的要把{{fusionName}}\n从{{pokemonName}}身上分离吗? {{fusionName}}会就此消失。",
  "wasReverted": "{{fusionName}}恢复成了{{pokemonName}}。",
  "releaseConfirmation": "你真要放生{{pokemonName}}吗？",
  "releaseInBattle": "你无法放生正在战斗中的宝可梦！",
  "selectAMove": "选择一个招式。",
  "changeQuantity": "选择一件道具来交换。\n使用 ← 和 → 来指定数量。",
  "selectAnotherPokemonToSplice": "选择另一只宝可梦来融合。",
  "cancel": "取消",

  // Slot TM text
  "able": "能学会！",
  "notAble": "无法学习",
  "learned": "已习得",

  // Releasing messages
  "goodbye": "再见，{{pokemonName}}！",
  "byebye": "拜拜，{{pokemonName}}！",
  "farewell": "再会了，{{pokemonName}}！",
  "soLong": "告辞了，{{pokemonName}}！",
  "thisIsWhereWePart": "就此分别吧，{{pokemonName}}！",
  "illMissYou": "我会想你的，{{pokemonName}}！",
  "illNeverForgetYou": "我不会忘记你的，{{pokemonName}}！",
  "untilWeMeetAgain": "下次再见了，{{pokemonName}}！",
  "sayonara": "撒由那拉，{{pokemonName}}！",
  "smellYaLater": "拜拜了您嘞，{{pokemonName}}！",
```
new cn translation

2024-06-25 15:10 UTC, EnochG1 reviewed
Translated Korean (partial).

2024-06-25 15:10 UTC, EnochG1 commented on src/locales/ko/party-ui-handler.ts
> +  "smellYaLater": "Smell ya later, {{pokemonName}}!",
```suggestion
  "goodbye": "잘 가, {{pokemonName}}!",
  "byebye": "바이바이, {{pokemonName}}!",
  "farewell": "작별이야, {{pokemonName}}!",
  "soLong": "안녕, {{pokemonName}}!",
  "thisIsWhereWePart": "여기서 헤어지자, {{pokemonName}}!",
  "illMissYou": "보고 싶을거야, {{pokemonName}}!",
  "illNeverForgetYou": "잊지 못할거야, {{pokemonName}}!",
  "untilWeMeetAgain": "다시 만날 때까지, {{pokemonName}}!",
  "sayonara": "사요나라, {{pokemonName}}!",
  "smellYaLater": "또 보자, {{pokemonName}}!",
```

2024-06-26 07:44 UTC, EnochG1 reviewed
Can you commit suggestion then rerun workflow?

2024-06-26 07:44 UTC, EnochG1 commented on src/locales/zh_TW/party-ui-handler.ts
> +  "PASS_BATON": "Pass Baton",
```suggestion
  "ACTIVATE": "발동",
  "DEACTIVATE": "해제",
  "TRANSFER": "건네다",
  "ALL": "전부",
  "PASS_BATON": "배턴터치한다",
```

2024-06-26 08:02 UTC, EnochG1 commented on src/locales/ko/party-ui-handler.ts
> +  "PASS_BATON": "Pass Baton",
```suggestion
  "ACTIVATE": "발동",
  "DEACTIVATE": "해제",
  "TRANSFER": "건네다",
  "ALL": "전부",
  "PASS_BATON": "배턴터치한다",
```

2024-06-26 16:17 UTC, returntoice requested changes

2024-06-26 16:17 UTC, returntoice commented on src/locales/ko/party-ui-handler.ts
> +  "UNSPLICE": "Unsplice",
```suggestion
  "SPLICE": "융합",
  "UNSPLICE": "융합 해제",
```

2024-06-26 16:17 UTC, returntoice commented on src/locales/ko/party-ui-handler.ts
> +  "REVIVE": "Revive",
```suggestion
  "UNPAUSE_EVOLUTION": "진화 재개",
  "REVIVE": "되살린다",
```

2024-06-26 16:17 UTC, returntoice commented on src/locales/ko/party-ui-handler.ts
> +  "TRANSFER": "건네다",
```suggestion
  "TRANSFER": "건넨다",
```

2024-06-26 22:44 UTC, EnochG1 reviewed
Additional korean translation

2024-06-26 22:44 UTC, EnochG1 commented on src/locales/ko/party-ui-handler.ts
> +  "selectAnotherPokemonToSplice": "Select another Pokémon to splice.",
```suggestion
  "unpausedEvolutions": "{{pokemonName}}의 진화가 재개되었다.",
  "unspliceConfirmation": "{{pokemonName}}로부터 {{fusionName}}의 융합을 해제하시겠습니까?\n{{fusionName}}는 사라지게 됩니다.",
  "wasReverted": "{{fusionName}}은 {{pokemonName}}의 모습으로 돌아갔습니다!",
  "releaseConfirmation": "{{pokemonName}}[[를]]\n정말 놓아주겠습니까?",
  "releaseInBattle": "전투 중인 포켓몬은\n놓아줄 수 없습니다.",
  "selectAMove": "기술을 선택해 주십시오",
  "changeQuantity": "건네줄 지닌 도구를 선택해 주십시오.\n< 와 > 로 수량을 변경할 수 있습니다.",
  "selectAnotherPokemonToSplice": "융합할 포켓몬을 선택해 주십시오.",
```

2024-06-27 00:05 UTC, sodaMelon approved these changes

2024-06-27 00:13 UTC, torranx commented on src/locales/en/party-ui-handler.ts
> +  "noEnergy": "{{pokemonName}} has no energy\nleft to battle!",
why do we have 2 different naming conventions here and on the other locales files?

2024-06-27 01:27 UTC, josericardo-fo commented on src/locales/en/party-ui-handler.ts
> +  "noEnergy": "{{pokemonName}} has no energy\nleft to battle!",
wdym? are you talking about the top ones being in uppercase and the bottom ones in lower case?

2024-06-27 06:09 UTC, EnochG1 commented on src/locales/en/party-ui-handler.ts
> +  "noEnergy": "{{pokemonName}} has no energy\nleft to battle!",
@josericardo-fo 
I think you should make it all lower case(camel? case.), regardless of the purpose.

2024-06-27 07:47 UTC, torranx commented on src/locales/en/party-ui-handler.ts
> +  "noEnergy": "{{pokemonName}} has no energy\nleft to battle!",
> Wdym? Are you talking about the top ones being in uppercase and the bottom ones in lower case? If it is the case, the ones in capital letters are like that because they are parameters of a function in the party-ui-handler part that deals with options. The rest of the entries in lower case are simple texts.

yes im talking about the others being named like PASS_BATON while others are in camelCase, they are in the same object so i dont get why they are named in the same way.

2024-06-27 12:58 UTC, josericardo-fo commented on src/locales/en/party-ui-handler.ts
> +  "noEnergy": "{{pokemonName}} has no energy\nleft to battle!",
Like I said earlier, it messes up the text display because of the function they are using:

![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/83f76f2d-6bc2-49b8-b9ce-a48de7f97738)

```ts
  "sendOut": "Trocar", // changed to lower camel case and bugged
  "summary": "Sumário", // changed to lower camel case and bugged
  "CANCEL": "Cancelar",
  "release": "Soltar", // changed to lower camel case and bugged
  "APPLY": "Aplicar",
  "TEACH": "Ensinar",
  "SPLICE": "Fundir",
  "unsplice": "Separar", // changed to lower camel case and bugged
 ```

2024-06-27 13:22 UTC, torranx commented on src/locales/en/party-ui-handler.ts
> +  "noEnergy": "{{pokemonName}} has no energy\nleft to battle!",
> Like I said earlier, it messes up the text display because of the function they are using:

you did not say anything about it messing the display 😃, thats why i said :

> unless the function that deals with options only works if they are named like that, i dont see it needing to have 2 different naming conventions

anyways, with that, consider this resolved

2024-06-27 13:42 UTC, josericardo-fo commented on src/locales/en/party-ui-handler.ts
> +  "noEnergy": "{{pokemonName}} has no energy\nleft to battle!",
> > Like I said earlier, it messes up the text display because of the function they are using:
> 
> you did not say anything about it messing the display 😃, thats why i said :
> 
> > unless the function that deals with options only works if they are named like that, i dont see it needing to have 2 different naming conventions
> 
> anyways, with that, consider this resolved

Sorry if I was mean or something, I did not express myself clearly.
Okay, resolving this rn

2024-06-28 12:43 UTC, GoldTra requested changes
Spanish translations

2024-06-28 12:43 UTC, GoldTra commented on src/locales/es/party-ui-handler.ts
> +  "smellYaLater": "Smell ya later, {{pokemonName}}!",
```suggestion
  "TEACH": "Enseñar",
  "SPLICE": "Fusionar",
  "UNSPLICE": "Separar",
  "ACTIVATE": "Activar",
  "DEACTIVATE": "Desactivar",
  "TRANSFER": "Transferir",
  "ALL": "Todo",
  "PASS_BATON": "Relevo",
  "UNPAUSE_EVOLUTION": "Reanudar Evolución",
  "REVIVE": "Revivir",

  "choosePokemon": "Elige a un Pokémon.",
  "doWhatWithThisPokemon": "¿Que quieres hacer con este Pokémon?",
  "noEnergy": "¡A {{pokemonName}} no le quedan\nfuerzas para luchar!",
  "hasEnergy": "¡A {{pokemonName}} le quedan\nfuerzas para luchar!",
  "cantBeUsed": "¡{{pokemonName}} no puede usarse\nen este desafío!",
  "tooManyItems": "¡{{pokemonName}} tiene demasiados\nde este objeto!",
  "anyEffect": "No tendría ningún efecto.",
  "unpausedEvolutions": "Se reanudó las evoluciones de {{pokemonName}}.",
  "unspliceConfirmation": "¿Seguro que quiere separar a {{fusionName}}\nde {{pokemonName}}? {{fusionName}} se perderá.",
  "wasReverted": "{{fusionName}} se revirtió a {{pokemonName}}.",
  "releaseConfirmation": "¿Quieres liberar a {{pokemonName}}?",
  "releaseInBattle": "¡No puedes liberar un Pokémon que está en batalla!",
  "selectAMove": "Selecciona un movimiento.",
  "changeQuantity": "Selecciona un objeto equipado para transferir.\nUsa < y > para cambiar la cantidad.",
  "selectAnotherPokemonToSplice": "Selecciona otro Pokémon para fusionar.",
  "cancel": "Salir",

  // Slot TM text
  "able": "Apto",
  "notAble": "No apto",
  "learned": "Aprendido",

  // Releasing messages
  "goodbye": "¡Adiós, {{pokemonName}}!",
  "byebye": "¡Chao, {{pokemonName}}!",
  "farewell": "¡Hasta luego, {{pokemonName}}!",
  "soLong": "¡Nos vemos, {{pokemonName}}!",
  "thisIsWhereWePart": "¡Aquí es donde nos despedimos, {{pokemonName}}!",
  "illMissYou": "¡Te echaré de menos, {{pokemonName}}!",
  "illNeverForgetYou": "¡Nunca te olvidaré, {{pokemonName}}!",
  "untilWeMeetAgain": "¡Hasta que nos volvamos a encontrar, {{pokemonName}}!",
  "sayonara": "¡Sayonara, {{pokemonName}}!",
  "smellYaLater": "¡Nos vemos luego, {{pokemonName}}!",
```

2024-06-30 21:24 UTC, CodeTappert approved these changes

2024-07-01 08:23 UTC, 40chyan approved these changes

2024-07-05 01:28 UTC, Tempo-anon approved these changes

2024-07-05 01:40 UTC, merged