[Feature] Added pokemon renaming
pagefaultgames/pokerogue pull request #2570
Opened 2024-06-24 19:29 UTC by sirzento

## What are the changes?

You can now rename any pokemon in your party.

## Why am I doing these changes?

This feature exist in the offical pokemon games and it was also requested a bunch of times.

## What did change?

I added a new ui that opens if you choose the rename option in the party menu. This Ui will set the pokemon name.

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/16718523/ea6a9a20-7535-4f61-b79d-4d973e73960a

## How to test the changes?

Go the game and just rename a pokemon.

## TODOs
- User input error handling
- Better UI popup
- Persistant name change after reloading

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-25 08:21 UTC, CodeTappert commented
Not a fan on how the "OK" button looks. Otherwise super cool feature!

2024-06-25 08:53 UTC, sirzento commented
> Not a fan on how the "OK" button looks. Otherwise super cool feature!

@CodeTappert  Oh right. The first video uses an old version of the popup. The new version is shown in the second video. I will take a new one and replace it

2024-06-25 09:05 UTC, CodeTappert commented
Hmm the buttons still could use more padding i would say. So the border doesnt overlap with the text

2024-06-25 09:08 UTC, sirzento commented
I guess yes. The login screen could need the same change haha 

![grafik](https://github.com/pagefaultgames/pokerogue/assets/16718523/2c10b522-8c7a-4b3c-8df3-0b98045fac21)

2024-06-25 17:49 UTC, f-fsantos submitted a review, later dismissed

2024-06-25 17:49 UTC, XGSleepWalker commented on src/system/game-data.ts
> +
Delete these new lines

2024-06-25 17:49 UTC, XGSleepWalker commented on src/system/game-data.ts
> +
Delete these new lines

2024-06-26 18:34 UTC, Adri1 reviewed
French translation

2024-06-26 18:34 UTC, Adri1 commented on src/locales/fr/menu.ts
> +  "nickname": "Nickname",
```suggestion
  "renamePokemon": "Renommer Pokémon",
  "rename": "Renommer",
  "nickname": "Surnom",
```

2024-06-26 19:22 UTC, 40chyan commented on src/locales/zh_CN/menu.ts
> +  "nickname": "Nickname",
```suggestion
  "renamePokemon": "给宝可梦起名",
  "rename": "起名",
  "nickname": "昵称",
```

2024-06-26 19:22 UTC, 40chyan commented on src/locales/zh_CN/menu.ts
> +  "nickname": "Nickname",
very cool enhancement to the game

2024-06-26 20:27 UTC, josericardo-fo commented on src/locales/pt_BR/menu.ts
> +  "nickname": "Nickname",
```suggestion
  "renamePokemon": "Renomear Pokémon",
  "rename": "Renomear",
  "nickname": "Apelido",
```

2024-06-27 06:28 UTC, EnochG1 reviewed
IMO, we should localize messages also. like below
```
`It doesn\'t affect ${pokemon.getNameToRender()}!`;
getPokemonMessage(pokemon, ` stole\n${defender.getNameToRender()}'s ${stolenItem.type.name}!`)
getPokemonMessage(target, ` drank down all the\nmatcha that ${pokemon.getNameToRender()} made!`), true, !this.showAnim)
getPokemonMessage(pokemon, " frisked " + opponent.getNameToRender() + "'s " + opponent.getAbility().name + "!")
`Pointed stones dug into\n${pokemon.getNameToRender()}!`
`The opposing ${pokemon.getNameToRender()} was caught in a sticky web!`
```

It should be changed like 
```
i18next.t("abilityTriggers:windPowerCharged", { pokemonName: pokemon.getNameToRender(), moveName: this.getMoveName() })
```

2024-06-27 06:28 UTC, EnochG1 commented on src/locales/ko/menu.ts
> +  "nickname": "Nickname",
```suggestion
  "renamePokemon": "포켓몬의 닉네임은?",
  "rename": "닉네임 바꾸기",
  "nickname": "닉네임",
```

2024-06-27 07:18 UTC, sirzento commented
> IMO, we should localize messages also. like below
> 
> ```
> `It doesn\'t affect ${pokemon.getNameToRender()}!`;
> getPokemonMessage(pokemon, ` stole\n${defender.getNameToRender()}'s ${stolenItem.type.name}!`)
> getPokemonMessage(target, ` drank down all the\nmatcha that ${pokemon.getNameToRender()} made!`), true, !this.showAnim)
> getPokemonMessage(pokemon, " frisked " + opponent.getNameToRender() + "'s " + opponent.getAbility().name + "!")
> `Pointed stones dug into\n${pokemon.getNameToRender()}!`
> `The opposing ${pokemon.getNameToRender()} was caught in a sticky web!`
> ```
> 
> It should be changed like
> 
> ```
> i18next.t("abilityTriggers:windPowerCharged", { pokemonName: pokemon.getNameToRender(), moveName: this.getMoveName() })
> ```

I just changed it one to one. I thought that's something for a different PR to change all the hardcoded strings to localization.

2024-06-27 08:41 UTC, torranx commented
im curious, wont a getter function work instead of manually creating `getNameToRender()` and changing all instances of `.name`

2024-07-01 17:30 UTC, RedstonewolfX commented
I used this PR’s files in an offline/modded copy, and the game crashed when I hatched an egg because it had no nickname to copy (I may have copied it incorrectly though).

Also, there’s a generate name property of Pokemon.
When I tried to implement nicknames myself, I made it output the nickname if there was one, and set the name as normal if there wasn’t. You can make it call this function whenever the name is changed

2024-07-01 17:43 UTC, sirzento commented
> I used this PR’s files in an offline/modded copy, and the game crashed when I hatched an egg because it had no nickname to copy (I may have copied the files incorrectly though).

Hatching eggs does work for me. Might be that you did something wrong or you did something that I didn't test but since getting eggs from the gacha and hatching them works I don't know what else you might did^^


> Also, there’s a generate name property of Pokemon.

This is used to generate the name for fused pokemon and also changing this function would lead to the same problems as I have described on my last comment.


> When I tried to implement nicknames myself, I made it output the nickname if there was one, and set the name as normal if there wasn’t. You can make it call this function whenever the name is changed

We don't want to override the name property of `Pokemon` so I really don't think it would be much to use doing it in that function.

2024-07-01 17:49 UTC, RedstonewolfX commented
This is a very cool feature, though, and I hope it gets added

2024-07-11 18:14 UTC, sirzento commented
> so we want to replace "pokemon.name" everywhere with getPokemonWithAffix(pokemon).
> 
> This is not compatible with your change. Any ideas?

@CodeTappert  I think it is since I also changed the name inside the getPokemonWithAffix function. So it should work I guess.

2024-07-11 18:16 UTC, CodeTappert commented on src/data/ability.ts
> +    return `It doesn\'t affect ${pokemon.getNameToRender()}!`;
use getPokemonNameWithAffix everywhere

2024-07-11 18:17 UTC, CodeTappert commented
> > so we want to replace "pokemon.name" everywhere with getPokemonWithAffix(pokemon).
> > This is not compatible with your change. Any ideas?
> 
> @CodeTappert I think it is since I also changed the name inside the getPokemonWithAffix function. So it should work I guess.

THen use getPokemonWithAffix  everywhere

2024-07-12 09:08 UTC, sirzento commented
> > > so we want to replace "pokemon.name" everywhere with getPokemonWithAffix(pokemon).
> > > This is not compatible with your change. Any ideas?
> > 
> > 
> > @CodeTappert I think it is since I also changed the name inside the getPokemonWithAffix function. So it should work I guess.
> 
> THen use getPokemonWithAffix everywhere

Done. Some localizations needs do be changed now but I don't know if this all is still inside the scope of this PR. Like the battle.ts localization: `"singleWildAppeared": "A wild {{pokemonName}} appeared!",` will now print "A wild Mewtwo (wild) appeared!" cause of the affix. I can change it in the english localization but I have no clue about the other languages.

2024-07-12 09:09 UTC, CodeTappert commented
> > > > so we want to replace "pokemon.name" everywhere with getPokemonWithAffix(pokemon).
> > > > This is not compatible with your change. Any ideas?
> > > 
> > > 
> > > @CodeTappert I think it is since I also changed the name inside the getPokemonWithAffix function. So it should work I guess.
> > 
> > THen use getPokemonWithAffix everywhere
> 
> Done. Some localizations needs do be changed now but I don't know if this all is still inside the scope of this PR. Like the battle.ts localization: `"singleWildAppeared": "A wild {{pokemonName}} appeared!",` will now print "A wild Mewtwo (wild) appeared!" cause of the affix. I can change it in the english localization but I have no clue about the other languages.

Please list all localization keys that needs this Change

2024-07-12 09:20 UTC, sirzento commented
> > > > > so we want to replace "pokemon.name" everywhere with getPokemonWithAffix(pokemon).
> > > > > This is not compatible with your change. Any ideas?
> > > > 
> > > > 
> > > > @CodeTappert I think it is since I also changed the name inside the getPokemonWithAffix function. So it should work I guess.
> > > 
> > > 
> > > THen use getPokemonWithAffix everywhere
> > 
> > 
> > Done. Some localizations needs do be changed now but I don't know if this all is still inside the scope of this PR. Like the battle.ts localization: `"singleWildAppeared": "A wild {{pokemonName}} appeared!",` will now print "A wild Mewtwo (wild) appeared!" cause of the affix. I can change it in the english localization but I have no clue about the other languages.
> 
> Please list all localization keys that needs this Change

All localizations that have "wild" inside them. I currently only know about "singleWildAppeared" and "multiWildAppeared" and I don't think there are more like that.

2024-07-12 09:37 UTC, CodeTappert commented
Then dont do it for those two.

2024-07-12 10:31 UTC, sirzento commented
> Then dont do it for those two.

Alright. Chnaged those two back

2024-07-17 16:39 UTC, CodeTappert commented
![image](https://github.com/user-attachments/assets/a6793917-9e3b-4329-8044-85941c082bc3)

2024-07-17 16:42 UTC, CodeTappert commented
https://github.com/user-attachments/assets/5fc88e9a-7477-407c-b24a-96e8f2c88f4b

2024-07-17 16:47 UTC, CodeTappert commented
Setting name -> F5 -> Name gone

2024-07-17 16:49 UTC, CodeTappert commented
Setting a weird name like:
![image](https://github.com/user-attachments/assets/5eb70a27-0736-4b4d-bdef-b41b31686242)

Leads to 

![image](https://github.com/user-attachments/assets/679633e5-ec5c-4890-af9c-8862ee54b1ed)


So you need to disallow some characters or fix that bug

2024-07-17 16:58 UTC, sirzento commented
> ![image](https://private-user-images.githubusercontent.com/38758606/349587008-a6793917-9e3b-4329-8044-85941c082bc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzU0MDcsIm5iZiI6MTcyMTIzNTEwNywicGF0aCI6Ii8zODc1ODYwNi8zNDk1ODcwMDgtYTY3OTM5MTctOWUzYi00MzI5LTgwNDQtODU5NDFjMDgyYmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE2NTE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZWVlYmRkNjg3YWRmYWRjZDExYTNlZDdlNGY0ZTk5ZjU5YTMyMzljNmVmZjMwMjhjM2I2Y2Q5YTYxMjAyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xeyzdDLWw0KngkLP1dQUhmo9EZ9Kqy-p_A6K6HMwWWc)

Ok fixed. Yeah I didn't checked that one.

2024-07-17 16:59 UTC, sirzento commented
> Setting name -> F5 -> Name gone

Yes because the game doesn't get saved if you press F5. Should the game be saved after a rename?

2024-07-17 17:20 UTC, flx-sta commented
> Setting a weird name like: ![image](https://private-user-images.githubusercontent.com/38758606/349591321-5eb70a27-0736-4b4d-bdef-b41b31686242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzcwNjQsIm5iZiI6MTcyMTIzNjc2NCwicGF0aCI6Ii8zODc1ODYwNi8zNDk1OTEzMjEtNWViNzBhMjctMDczNi00YjRkLWJkZWYtYjQxYjMxNjg2MjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMjEyN2M5NzU3NGY3ZWE3ZmQxNzliODc3ZDYxNjU3YWQxOTY3NTNiZDY2ZTQ5MjIzOTVlYTY2MTA2NDc4MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Swmzu5LuwgOe3EaEkk-vnt-X5ipd4iMJNjMt3uFgIi4)
> 
> Leads to
> 
> ![image](https://private-user-images.githubusercontent.com/38758606/349590784-679633e5-ec5c-4890-af9c-8862ee54b1ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzcwNjQsIm5iZiI6MTcyMTIzNjc2NCwicGF0aCI6Ii8zODc1ODYwNi8zNDk1OTA3ODQtNjc5NjMzZTUtZWM1Yy00ODkwLWFmOWMtODg2MmVlNTRiMWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ODU3OGMyZTczZjE4ZGYwOGU4NDM0ZTI5YWQwZmRkNGU3MzQ1ZTljNDY4ZDFhZTllZjFlNmQyZDFmYmEwZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vo6IXPfJA-45ILEj7YjvXVsDSht--W1Re1-7-G8Amck)
> 
> So you need to disallow some characters or fix that bug

I think it would be cool to keep such weird names allowed
This shouldn't be an issue and we need to support non latin1 characters anyway for chinese/japanese and stuff

You just gotta [escape them](https://stackoverflow.com/a/56647993/4622620) before base64 encoding them

2024-07-17 17:27 UTC, sirzento commented
> > Setting a weird name like: [image](https://private-user-images.githubusercontent.com/38758606/349591321-5eb70a27-0736-4b4d-bdef-b41b31686242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzcwNjQsIm5iZiI6MTcyMTIzNjc2NCwicGF0aCI6Ii8zODc1ODYwNi8zNDk1OTEzMjEtNWViNzBhMjctMDczNi00YjRkLWJkZWYtYjQxYjMxNjg2MjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMjEyN2M5NzU3NGY3ZWE3ZmQxNzliODc3ZDYxNjU3YWQxOTY3NTNiZDY2ZTQ5MjIzOTVlYTY2MTA2NDc4MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Swmzu5LuwgOe3EaEkk-vnt-X5ipd4iMJNjMt3uFgIi4)
> > Leads to
> > [image](https://private-user-images.githubusercontent.com/38758606/349590784-679633e5-ec5c-4890-af9c-8862ee54b1ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzcwNjQsIm5iZiI6MTcyMTIzNjc2NCwicGF0aCI6Ii8zODc1ODYwNi8zNDk1OTA3ODQtNjc5NjMzZTUtZWM1Yy00ODkwLWFmOWMtODg2MmVlNTRiMWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ODU3OGMyZTczZjE4ZGYwOGU4NDM0ZTI5YWQwZmRkNGU3MzQ1ZTljNDY4ZDFhZTllZjFlNmQyZDFmYmEwZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vo6IXPfJA-45ILEj7YjvXVsDSht--W1Re1-7-G8Amck)
> > So you need to disallow some characters or fix that bug
> 
> I think it would be cool to keep such weird names allowed This shouldn't be an issue and we need to support non latin1 characters anyway for chinese/japanese and stuff
> 
> You just gotta [escape them](https://stackoverflow.com/a/56647993/4622620) before base64 encoding them

It's so cursed haha
![grafik](https://github.com/user-attachments/assets/9ee81645-9fa5-4720-a694-f2da6759756a)

2024-07-17 18:16 UTC, flx-sta requested changes

2024-07-17 18:16 UTC, flx-sta commented on src/field/pokemon.ts
> +      console.error(err);
Please add some context to the error
```suggestion
      console.error(`Failed to decode nickname for ${this.name}`, err);
```

2024-07-17 23:34 UTC, flx-sta approved these changes

2024-07-19 17:02 UTC, CodeTappert approved these changes

2024-07-19 20:26 UTC, CodeTappert commented
![image](https://github.com/user-attachments/assets/8731bce5-437a-43c0-91a4-f77cabd0b6c6)

I mean this time the game at least doesnt hang. But maybe have a look at it

2024-07-19 20:28 UTC, CodeTappert commented
Otherwise this fully works.

2024-07-19 21:34 UTC, flx-sta commented
Maybe we also wanna change this to be a `console.warn()` since it's not crucial, just nice to have

2024-07-19 22:12 UTC, sirzento commented
> ![image](https://private-user-images.githubusercontent.com/38758606/350544501-8731bce5-437a-43c0-91a4-f77cabd0b6c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjcyMTksIm5iZiI6MTcyMTQyNjkxOSwicGF0aCI6Ii8zODc1ODYwNi8zNTA1NDQ1MDEtODczMWJjZTUtNDM3YS00M2MwLTkxYTQtZjc3Y2FiZDBiNmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIyMDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNTE2NzQzMjIwNmE5ZDY0ZWJkZWJiM2U5YTg3YzdmNzkxZmU4OWMyM2RiYTljYTg0MTY1M2RlYzM0ZDc4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7Mgj3pNXD1ju1PF3bmEKIrDKwlhqPZCr7Ju06oGHNs)
> 
> I mean this time the game at least doesnt hang. But maybe have a look at it
> 
> (i named the pokemon '✌✌✌✌✌✌' )

Mh it does work on my end when I copy those emojis 
![grafik](https://github.com/user-attachments/assets/dc10f450-0fb1-42e1-9587-9079eb13f9ed)

2024-07-19 22:27 UTC, flx-sta commented
I can confirm that it works fine (english, legacy theme).
I even tried importing/exporting sessions =>. no problem

2024-07-19 22:34 UTC, CodeTappert commented
> > ![image](https://private-user-images.githubusercontent.com/38758606/350544501-8731bce5-437a-43c0-91a4-f77cabd0b6c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjcyMTksIm5iZiI6MTcyMTQyNjkxOSwicGF0aCI6Ii8zODc1ODYwNi8zNTA1NDQ1MDEtODczMWJjZTUtNDM3YS00M2MwLTkxYTQtZjc3Y2FiZDBiNmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIyMDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNTE2NzQzMjIwNmE5ZDY0ZWJkZWJiM2U5YTg3YzdmNzkxZmU4OWMyM2RiYTljYTg0MTY1M2RlYzM0ZDc4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7Mgj3pNXD1ju1PF3bmEKIrDKwlhqPZCr7Ju06oGHNs)
> > I mean this time the game at least doesnt hang. But maybe have a look at it
> > (i named the pokemon '✌✌✌✌✌✌' )
> 
> Mh it does work on my end when I copy those emojis. Do you have the latest version? ![grafik](https://private-user-images.githubusercontent.com/16718523/350590882-dc10f450-0fb1-42e1-9587-9079eb13f9ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0Mjg3MjAsIm5iZiI6MTcyMTQyODQyMCwicGF0aCI6Ii8xNjcxODUyMy8zNTA1OTA4ODItZGMxMGY0NTAtMGZiMS00MmUxLTk1ODctOTA3OWViMTNmOWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIyMzM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNzcyYzE5ODQ2NjNjZWM4M2VkYmZkNTg5NjAwOWQ1ZWZmMmM5NWNhYWFiZTM0NGJiNTBmYTk4YTE0Y2UzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tVcXJTcF40CrnSBxXF3xGh1H0HxKn6Y4fNM8otWKh-g)

As i said. it WORKS. But still produces those messages in the console on setting that name. I can play without problems

2024-07-19 22:50 UTC, flx-sta commented
@CodeTappert I don't see this console log issue

@sirzento But I found an issue: When writing the name it seems to notice some input still as ingame input. It might event get stuck in a `press-down` loop.
that is a big problem. (You can see that slightly in the video. When it constantly moves down in the shop. that wasn't me pressing any button doing that). YOu have to make sure to suppress that these inputs are propagated down

https://github.com/user-attachments/assets/45b1a1b4-759a-496d-b784-09eac0ab9975

2024-07-20 10:41 UTC, sirzento commented
@CodeTappert Yeah I actually ment that I also don't get those console outputs.

@flx-sta Oh okey. I have no clue on how to fix or prevent this. So this happens if you press buttons like left/down/right/up while in the text input field? I never got that behavior before.

2024-07-21 07:24 UTC, flx-sta commented
Yeah. It could be due to that specific Mac OS emoji menu thiough. So extremely specific

2024-07-22 16:46 UTC, merged

2024-07-30 04:51 UTC, flx-sta commented on src/phases.ts
> +      const pokemonName = getPokemonNameWithAffix(this.getPokemon());
This seems to cause wrong behavior @sirzento 
![image](https://github.com/user-attachments/assets/f1c144e9-666a-4240-a734-5def583c7208)