Localization: Localized game-data entries
pagefaultgames/pokerogue pull request #2589
Opened 2024-06-25 12:31 UTC by josericardo-fo

## What are the changes?

Localization and translations

## Overwrite Data (pt_BR)
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/cbc8957e-aa7d-4a95-8160-c82fd130f2f5)

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-25 13:20 UTC, Adri1 reviewed
Added French

2024-06-25 13:20 UTC, Adri1 commented on src/locales/fr/game-data.ts
> +  "errorUpdating": "An error occurred while updating {{dataName}} data. Please contact the administrator.",
```suggestion
  "systemData": "système",
  "sessionData": "de session",
  "settingsData": "des paramètres",
  "tutorialsData": "des tutoriels",
  "seenDialoguesData": "des dialogues connus",

  "dataCouldNotBeLoaded": "Impossible de charger les données {{dataName}}. Elles sont peut-être corrompues.",
  "dataWillBeOverridden": "Les données {{dataName}} seront effacées et la page rafraichie. Continuer ?",
  "errorContactServer": "Connexion au serveur impossible. Les données {{dataName}} n’ont pas eu être importées.",
  "errorUpdating": "Une erreur est survenue pendant le chargement des données {{dataName}}. Contactez un administrateur.",
```

2024-06-25 13:45 UTC, Adri1 reviewed
French corrections

2024-06-25 13:45 UTC, Adri1 commented on src/locales/fr/game-data.ts
> +  "errorUpdating": "Une erreur est survenue pendant le chargement des données {{dataName}}. Contactez un administrateur.",
```suggestion
  "dataCouldNotBeLoaded": "Impossible de charger les données {{dataName}}. Elles sont peut-être corrompues.",
  "dataWillBeOverridden": "Les données {{dataName}} seront effacées. Continuer ?",
  "errorContactServer": "Connexion au serveur impossible. Les données {{dataName}} n’ont pas eu être importées.",
  "errorUpdating": "Une erreur est survenue lors du chargement des données {{dataName}}. Contactez un administrateur.",
```

2024-06-25 15:15 UTC, CodeTappert commented on src/locales/de/game-data.ts
> +  "errorUpdating": "An error occurred while updating {{dataName}} data. Please contact the administrator.",
```suggestion
  "systemData": "System",
  "sessionData": "Session",
  "settingsData": "Einstellungen",
  "tutorialsData": "Tutorials",
  "seenDialoguesData": "Gesehener Dialog",

  "dataCouldNotBeLoaded": "Deine {{dataName}} Daten konnten nicht geladen werden. Möglicherweise sind sie beschädigt.",
  "dataWillBeOverridden": "Deine {{dataName}} Daten werden überschrieben und die Seite wird neugeladen. Fortfahren?",
  "errorContactServer": "Konnte den Server nicht kontaktieren. Deine {{dataName}} Daten konnten nicht importiert werden.",
  "errorUpdating": "Es ist ein Fehler aufgetreten während die {{dataName}} aktualisiert wurden. Kontaktiere bitte einen Administrator.",
```

2024-06-25 15:15 UTC, CodeTappert approved these changes

2024-06-25 15:35 UTC, Adri1 approved these changes

2024-06-26 07:58 UTC, EnochG1 reviewed
Korean Translation

2024-06-26 07:58 UTC, EnochG1 commented on src/locales/ko/game-data.ts
> +  "errorUpdating": "An error occurred while updating {{dataName}} data. Please contact the administrator.",
```suggestion
  "systemData": "시스템",
  "sessionData": "세션",
  "settingsData": "설정",
  "tutorialsData": "튜토리얼",
  "seenDialoguesData": "본 대화",

  "dataCouldNotBeLoaded": "{{dataName}}[[를]] 불러올 수 없었습니다. 파일이 손상되었을 수 있습니다.",
  "dataWillBeOverridden": "{{dataName}} 데이터를 덮어쓰고 페이지를 새로고침 합니다. 계속하시겠습니까?",
  "errorContactServer": "서버에 접근할 수 없습니다. {{dataName}} 데이터를 불러올 수 없습니다.",
  "errorUpdating": "{{dataName}} 데이터를 업데이트하는 도중 오류가 발생했습니다. 관리자에게 문의하십시오.",
```

2024-06-26 18:39 UTC, CodeTappert commented on src/locales/de/game-data.ts
> +  "dataWillBeOverridden": "Deine {{dataName}} Daten werden überschrieben und die Seite wird neugeladen. Fortfahren?",
```suggestion
  "dataWillBeOverridden": "Deine {{dataName}} Daten werden über-/nschrieben und es wird neugeladen. Fortfahren?",
```

2024-06-26 22:35 UTC, EnochG1 approved these changes

2024-07-01 10:31 UTC, InnocentGameDev requested changes
Added "es" localization

2024-07-01 10:31 UTC, InnocentGameDev commented on src/locales/es/game-data.ts
> +  "errorUpdating": "An error occurred while updating {{dataName}} data. Please contact the administrator.",
```suggestion
  "systemData": "sistema",
  "sessionData": "sesión",
  "settingsData": "ajustes",
  "tutorialsData": "tutoriales",
  "seenDialoguesData": "diálogos leídos",

  "dataCouldNotBeLoaded": "Tus datos "{{dataName}}" no se han podido cargar. Puede que estén corruptos.",
  "dataWillBeOverridden": "Tus datos "{{dataName}}" se sobreescribirán y la página recargará, ¿estás seguro?",
  "errorContactServer": "No se pudo contactar con el servidor. Tus datos "{{dataName}}" no han podido ser importados.",
  "errorUpdating": "Un error ha ocurrido mientras se subían los datos "{{dataName}}". Por favor, ponte en contacto con el administrador.",
```

2024-07-02 10:40 UTC, InnocentGameDev commented on src/locales/es/game-data.ts
> +  "errorUpdating": "Un error ha ocurrido mientras se subían los datos "{{dataName}}". Por favor, ponte en contacto con el administrador.",
```suggestion
  "dataCouldNotBeLoaded": "Tus datos {{dataName}} no se han podido cargar. Puede que estén corruptos.",
  "dataWillBeOverridden": "Tus datos {{dataName}} se sobreescribirán y la página recargará, ¿estás seguro?",
  "errorContactServer": "No se pudo contactar con el servidor. Tus datos {{dataName}} no han podido ser importados.",
  "errorUpdating": "Un error ha ocurrido mientras se subían los datos {{dataName}}. Por favor, ponte en contacto con el administrador.",
```

2024-08-01 02:22 UTC, josericardo-fo commented
Closed until future changes

2024-08-01 02:22 UTC, closed without merging