The stat messages can now be plural
pagefaultgames/pokerogue pull request #2600
Opened 2024-06-25 18:12 UTC by CodeTappert

## What are the changes?

There is new localization keys for when there is more then 1 stat changed. 

## Why am I doing these changes?

Because it probably was done by somebody who didnt understand that it may be different sentences needed when its one or multiple

## What did change?

See changes

### Screenshots/Videos

Before:
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/458b278f-d6b1-4293-b2fd-b19d3fc262ed)
https://github.com/pagefaultgames/pokerogue/assets/38758606/b3a263b7-dfaa-43e4-bb5f-23b9971569eb

After: 
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/711c90fd-5413-40c8-9a43-ff2cf8f9995c)
https://github.com/pagefaultgames/pokerogue/assets/38758606/35f0796e-224b-4074-aa26-47e1b9c0339c

## How to test the changes?

Use Ancient Power and check message

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-25 18:22 UTC, Adri1 reviewed
Added French

2024-06-25 18:22 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "statsAnd": "and",
```suggestion
  "statsAnd": "et",
```

2024-06-25 18:22 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "statWontGoAnyLowerMultiple": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRoseMultiple": "{{stats}} de {{pokemonNameWithAffix}}\naugmentent !",
  "statSharplyRoseMultiple": "{{stats}} de {{pokemonNameWithAffix}}\naugmentent beaucoup !",
  "statRoseDrasticallyMultiple": "{{stats}} de {{pokemonNameWithAffix}}\naugmentent énormément !",
  "statWontGoAnyHigherMultiple": "{{stats}} de {{pokemonNameWithAffix}}\nne peuvent plus augmenter !",
  "statFellMultiple": "{{stats}} de {{pokemonNameWithAffix}}\nbaissent !",
  "statHarshlyFellMultiple": "{{stats}} de {{pokemonNameWithAffix}}\nbaissent beaucoup !",
  "statSeverelyFellMultiple": "{{stats}} de {{pokemonNameWithAffix}}\nbaissent énormément !",
  "statWontGoAnyLowerMultiple": "{{stats}} de {{pokemonNameWithAffix}}\nne peuvent plus baisser !",
```

2024-06-25 19:43 UTC, Adri1 approved these changes

2024-06-25 19:46 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "stats": "Stats",
```suggestion
  "stats": "Les stats",
```

2024-06-26 01:56 UTC, EnochG1 reviewed
Korean Translation

2024-06-26 01:56 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "statWontGoAnyLowerMultiple": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRoseMultiple": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 올라갔다!",
  "statSharplyRoseMultiple": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 올라갔다!",
  "statRoseDrasticallyMultiple": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 올라갔다!",
  "statWontGoAnyHigherMultiple": "{{pokemonNameWithAffix}}의\n{{stats}}[[는]] 더 올라가지 않는다!",
  "statFellMultiple": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 떨어졌다!",
  "statHarshlyFellMultiple": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 떨어졌다!",
  "statSeverelyFellMultiple": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 떨어졌다!",
  "statWontGoAnyLowerMultiple": "{{pokemonNameWithAffix}}의\n{{stats}}[[는]] 더 떨어지지 않는다!",
```

2024-06-26 01:56 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "stats": "Stats",
```suggestion
  "statsAnd": "그리고",
  "stats": "스테이터스",
```

2024-06-26 06:45 UTC, 40chyan commented on src/locales/zh_CN/battle.ts
> +  "statWontGoAnyLowerMultiple": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRoseMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都提高了！",
  "statSharplyRoseMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都大幅提高了！",
  "statRoseDrasticallyMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都极大幅提高了！",
  "statWontGoAnyHigherMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都已经无法再提高了！",
  "statFellMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都降低了！",
  "statHarshlyFellMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都大幅降低了！",
  "statSeverelyFellMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都极大幅降低了！",
  "statWontGoAnyLowerMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都已经无法再提高了！",
```
cn translation, added a "都" to indicate plural

2024-06-26 06:54 UTC, 40chyan commented on src/locales/zh_CN/battle.ts
> +  "statWontGoAnyLowerMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都已经无法再提高了！",
```suggestion
  "statWontGoAnyLowerMultiple": "{{pokemonNameWithAffix}}的 {{stats}} 都已经无法再降低了！",
```
sorry my bad! wrong word here

2024-06-26 07:50 UTC, EnochG1 approved these changes

2024-06-26 09:58 UTC, GoldTra requested changes
Spanish translations

2024-06-26 09:58 UTC, GoldTra commented on src/locales/es/battle.ts
> +  "stats": "Stats",
```suggestion
  "statsAnd": "y",
  "stats": "Las estadísticas",
```

2024-06-26 09:58 UTC, GoldTra commented on src/locales/es/battle.ts
> +  "statWontGoAnyLowerMultiple": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRoseMultiple": "¡{{stats}} de\n{{pokemonNameWithAffix}} han subido!",
  "statSharplyRoseMultiple": "¡{{stats}} de\n{{pokemonNameWithAffix}} han subido mucho!",
  "statRoseDrasticallyMultiple": "¡{{stats}} de\n{{pokemonNameWithAffix}} han subido muchísimo!",
  "statWontGoAnyHigherMultiple": "¡{{stats}} de\n{{pokemonNameWithAffix}} no pueden subir más!",
  "statFellMultiple": "¡{{stats}} de\n{{pokemonNameWithAffix}} han bajado!",
  "statHarshlyFellMultiple": "¡{{stats}} de\n{{pokemonNameWithAffix}} han bajado mucho!",
  "statSeverelyFellMultiple": "¡{{stats}} de\n{{pokemonNameWithAffix}} han bajado muchísimo!",
  "statWontGoAnyLowerMultiple": "¡{{stats}} de\n{{pokemonNameWithAffix}} no pueden bajar más!",
```

2024-06-26 10:38 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "stats": "Stats",
```suggestion
  "statsAnd": "e",
  "stats": "Atributos",
```

2024-06-26 10:46 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "statWontGoAnyLowerMultiple": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRoseMultiple": "{{stats}} de {{pokemonNameWithAffix}} aumentaram!",
  "statSharplyRoseMultiple": "{{stats}} de {{pokemonNameWithAffix}} aumentaram bruscamente!",
  "statRoseDrasticallyMultiple": "{{stats}} de {{pokemonNameWithAffix}} aumentaram drasticamente!",
  "statWontGoAnyHigherMultiple": "{{stats}} de {{pokemonNameWithAffix}} não vão mais aumentar!",
  "statFellMultiple": "{{stats}} de {{pokemonNameWithAffix}} diminuíram!",
  "statHarshlyFellMultiple": "{{stats}} de {{pokemonNameWithAffix}} diminuíram duramente!",
  "statSeverelyFellMultiple": "{{stats}} de {{pokemonNameWithAffix}} diminuíram severamente!",
  "statWontGoAnyLowerMultiple": "{{stats}} de {{pokemonNameWithAffix}} não vão mais diminuir!",
```

2024-06-27 08:33 UTC, torranx commented on src/data/battle-stat.ts
> +export function getBattleStatLevelChangeDescription(pokemonNameWithAffix: string, stats: string, levels: integer, up: boolean,multiple: boolean = false) {
nit: space after `,`

2024-06-27 08:34 UTC, CodeTappert commented on src/data/battle-stat.ts
> +export function getBattleStatLevelChangeDescription(pokemonNameWithAffix: string, stats: string, levels: integer, up: boolean,multiple: boolean = false) {
```suggestion
export function getBattleStatLevelChangeDescription(pokemonNameWithAffix: string, stats: string, levels: integer, up: boolean, multiple: boolean = false) {
```

2024-06-28 14:26 UTC, CodeTappert commented
@XGSleepWalker

2024-06-28 21:31 UTC, flx-sta requested changes
Please use i18ns well integrated way to pluralize. Thus we don't need to integrate the logic:
https://www.i18next.com/translation-function/plurals

2024-06-28 21:40 UTC, CodeTappert commented
> Collaborator

@brain-frog Do we need this? Or is my solution good enough?

2024-07-10 18:30 UTC, CodeTappert commented on src/locales/zh_TW/battle.ts
> +  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRose_one": "{{pokemonNameWithAffix}} 的 {{stats}} 提高了！",
  "statRose_other": "{{pokemonNameWithAffix}}'s {{stats}} rose!",
  "statSharplyRose_one": "{{pokemonNameWithAffix}} 的 {{stats}} 大幅提高了！",
  "statSharplyRose_other": "{{pokemonNameWithAffix}}'s {{stats}} sharply rose!",
  "statRoseDrastically_one": "{{pokemonNameWithAffix}} 的 {{stats}} 極大幅提高了！",
  "statRoseDrastically_other": "{{pokemonNameWithAffix}}'s {{stats}} rose drastically!",
  "statWontGoAnyHigher_one": "{{pokemonNameWithAffix}} 的 {{stats}} 已經無法再提高了！",
  "statWontGoAnyHigher_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any higher!",
  "statFell_one": "{{pokemonNameWithAffix}} 的 {{stats}} 降低了！",
  "statFell_other": "{{pokemonNameWithAffix}}'s {{stats}} fell!",
  "statHarshlyFell_one": "{{pokemonNameWithAffix}} 的 {{stats}} 大幅降低了！",
  "statHarshlyFell_other": "{{pokemonNameWithAffix}}'s {{stats}} harshly fell!",
  "statSeverelyFell_one": "{{pokemonNameWithAffix}} 的 {{stats}} 極大幅降低了！",
  "statSeverelyFell_other": "{{pokemonNameWithAffix}}'s {{stats}} severely fell!",
  "statWontGoAnyLower_one": "{{pokemonNameWithAffix}} 的 {{stats}} 已經無法再降低了！",
  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",

```

2024-07-10 18:31 UTC, CodeTappert commented on src/locales/zh_CN/battle.ts
> +  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}的 {{stats}} 都已经无法再降低了！",
```suggestion
  "statRose_one": "{{pokemonNameWithAffix}}\n的{{stats}}提高了！",
  "statRose_other": "{{pokemonNameWithAffix}}的 {{stats}} 都提高了！",
  "statSharplyRose_one": "{{pokemonNameWithAffix}}\n的{{stats}}大幅提高了！",
  "statSharplyRose_other": "{{pokemonNameWithAffix}}的 {{stats}} 都大幅提高了！",
  "statRoseDrastically_one": "{{pokemonNameWithAffix}}\n的{{stats}}极大幅提高了！",
  "statRoseDrastically_other": "{{pokemonNameWithAffix}}的 {{stats}} 都极大幅提高了！",
  "statWontGoAnyHigher_one": "{{pokemonNameWithAffix}}\n的{{stats}}已经无法再提高了！",
  "statWontGoAnyHigher_other": "{{pokemonNameWithAffix}}的 {{stats}} 都已经无法再提高了！",
  "statFell_one": "{{pokemonNameWithAffix}}\n的{{stats}}降低了！",
  "statFell_other": "{{pokemonNameWithAffix}}的 {{stats}} 都降低了！",
  "statHarshlyFell_one": "{{pokemonNameWithAffix}}\n的{{stats}}大幅降低了！",
  "statHarshlyFell_other": "{{pokemonNameWithAffix}}的 {{stats}} 都大幅降低了！",
  "statSeverelyFell_one": "{{pokemonNameWithAffix}}\n的{{stats}}极大幅降低了！",
  "statSeverelyFell_other": "{{pokemonNameWithAffix}}的 {{stats}} 都极大幅降低了！",
  "statWontGoAnyLower_one": "{{pokemonNameWithAffix}}\n的{{stats}}已经无法再降低了！",
  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}的 {{stats}} 都已经无法再降低了！",
```

2024-07-10 18:31 UTC, CodeTappert commented on src/locales/pt_BR/battle.ts
> +  "statWontGoAnyLower_other": "{{stats}} de {{pokemonNameWithAffix}} não vão mais diminuir!",
```suggestion
  "statRose_one": "{{stats}} de {{pokemonNameWithAffix}} aumentou!",
  "statRose_other": "{{stats}} de {{pokemonNameWithAffix}} aumentaram!",
  "statSharplyRose_one": "{{stats}} de {{pokemonNameWithAffix}} aumentou bruscamente!",
  "statSharplyRose_other": "{{stats}} de {{pokemonNameWithAffix}} aumentaram bruscamente!",
  "statRoseDrastically_one": "{{stats}} de {{pokemonNameWithAffix}} aumentou drasticamente!",
  "statRoseDrastically_other": "{{stats}} de {{pokemonNameWithAffix}} aumentaram drasticamente!",
  "statWontGoAnyHigher_one": "{{stats}} de {{pokemonNameWithAffix}} não vai mais aumentar!",
  "statWontGoAnyHigher_other": "{{stats}} de {{pokemonNameWithAffix}} não vão mais aumentar!",
  "statFell_one": "{{stats}} de {{pokemonNameWithAffix}} diminuiu!",
  "statFell_other": "{{stats}} de {{pokemonNameWithAffix}} diminuíram!",
  "statHarshlyFell_one": "{{stats}} de {{pokemonNameWithAffix}} diminuiu duramente!",
  "statHarshlyFell_other": "{{stats}} de {{pokemonNameWithAffix}} diminuíram duramente!",
  "statSeverelyFell_one": "{{stats}} de {{pokemonNameWithAffix}} diminuiu severamente!",
  "statSeverelyFell_other": "{{stats}} de {{pokemonNameWithAffix}} diminuíram severamente!",
  "statWontGoAnyLower_one": "{{stats}} de {{pokemonNameWithAffix}} não vai mais diminuir!",
  "statWontGoAnyLower_other": "{{stats}} de {{pokemonNameWithAffix}} não vão mais diminuir!",
```

2024-07-10 18:32 UTC, CodeTappert commented on src/locales/ko/battle.ts
> +  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}의\n{{stats}}[[는]] 더 떨어지지 않는다!",
```suggestion
  "statRose_one": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 올라갔다!",
  "statRose_other": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 올라갔다!",
  "statSharplyRose_one": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 올라갔다!",
  "statSharplyRose_other": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 올라갔다!",
  "statRoseDrastically_one": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 올라갔다!",
  "statRoseDrastically_other": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 올라갔다!",
  "statWontGoAnyHigher_one": "{{pokemonNameWithAffix}}의\n{{stats}}[[는]] 더 올라가지 않는다!",
  "statWontGoAnyHigher_other": "{{pokemonNameWithAffix}}의\n{{stats}}[[는]] 더 올라가지 않는다!",
  "statFell_one": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 떨어졌다!",
  "statFell_other": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 떨어졌다!",
  "statHarshlyFell_one": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 떨어졌다!",
  "statHarshlyFell_other": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 크게 떨어졌다!",
  "statSeverelyFell_one": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 떨어졌다!",
  "statSeverelyFell_other": "{{pokemonNameWithAffix}}의\n{{stats}}[[가]] 매우 크게 떨어졌다!",
  "statWontGoAnyLower_one": "{{pokemonNameWithAffix}}의\n{{stats}}[[는]] 더 떨어지지 않는다!",
  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}의\n{{stats}}[[는]] 더 떨어지지 않는다!",
```

2024-07-10 18:33 UTC, CodeTappert commented on src/locales/it/battle.ts
> +  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRose_one": "{{pokemonNameWithAffix}}'s {{stats}} è aumentato/a!",
  "statRose_other": "{{pokemonNameWithAffix}}'s {{stats}} rose!",
  "statSharplyRose_one": "{{pokemonNameWithAffix}}'s {{stats}} è aumentato/a molto!",
  "statSharplyRose_other": "{{pokemonNameWithAffix}}'s {{stats}} sharply rose!",
  "statRoseDrastically_one": "{{pokemonNameWithAffix}}'s {{stats}} è aumentato/a drasticamente!",
  "statRoseDrastically_other": "{{pokemonNameWithAffix}}'s {{stats}} rose drastically!",
  "statWontGoAnyHigher_one": "{{pokemonNameWithAffix}}'s {{stats}} non può aumentare più di così!",
  "statWontGoAnyHigher_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any higher!",
  "statFell_one": "{{pokemonNameWithAffix}}'s {{stats}} è diminuito/a!",
  "statFell_other": "{{pokemonNameWithAffix}}'s {{stats}} fell!",
  "statHarshlyFell_one": "{{pokemonNameWithAffix}}'s {{stats}} è diminuito/a molto!",
  "statHarshlyFell_other": "{{pokemonNameWithAffix}}'s {{stats}} harshly fell!",
  "statSeverelyFell_one": "{{pokemonNameWithAffix}}'s {{stats}} è diminuito/a drasticamente!",
  "statSeverelyFell_other": "{{pokemonNameWithAffix}}'s {{stats}} severely fell!",
  "statWontGoAnyLower_one": "{{pokemonNameWithAffix}}'s {{stats}} non può diminuire più di così!",
  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```

2024-07-10 18:34 UTC, CodeTappert commented on src/locales/fr/battle.ts
> +  "statWontGoAnyLower_other": "{{stats}} de {{pokemonNameWithAffix}}\nne peuvent plus baisser !",
```suggestion
  "statRose_one": "{{stats}} de {{pokemonNameWithAffix}}\naugmente !",
  "statRose_other": "{{stats}} de {{pokemonNameWithAffix}}\naugmentent !",
  "statSharplyRose_one": "{{stats}} de {{pokemonNameWithAffix}}\naugmente beaucoup !",
  "statSharplyRose_other": "{{stats}} de {{pokemonNameWithAffix}}\naugmentent beaucoup !",
  "statRoseDrastically_one": "{{stats}} de {{pokemonNameWithAffix}}\naugmente énormément !",
  "statRoseDrastically_other": "{{stats}} de {{pokemonNameWithAffix}}\naugmentent énormément !",
  "statWontGoAnyHigher_one": "{{stats}} de {{pokemonNameWithAffix}}\nne peut plus augmenter !",
  "statWontGoAnyHigher_other": "{{stats}} de {{pokemonNameWithAffix}}\nne peuvent plus augmenter !",
  "statFell_one": "{{stats}} de {{pokemonNameWithAffix}}\nbaisse !",
  "statFell_other": "{{stats}} de {{pokemonNameWithAffix}}\nbaissent !",
  "statHarshlyFell_one": "{{stats}} de {{pokemonNameWithAffix}}\nbaisse beaucoup !",
  "statHarshlyFell_other": "{{stats}} de {{pokemonNameWithAffix}}\nbaissent beaucoup !",
  "statSeverelyFell_one": "{{stats}} de {{pokemonNameWithAffix}}\nbaisse énormément !",
  "statSeverelyFell_other": "{{stats}} de {{pokemonNameWithAffix}}\nbaissent énormément !",
  "statWontGoAnyLower_one": "{{stats}} de {{pokemonNameWithAffix}}\nne peut plus baisser !",
  "statWontGoAnyLower_other": "{{stats}} de {{pokemonNameWithAffix}}\nne peuvent plus baisser !",
```

2024-07-10 18:36 UTC, CodeTappert commented on src/locales/en/battle.ts
> +  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRose_one": "{{pokemonNameWithAffix}}'s {{stats}} rose!",
  "statRose_other": "{{pokemonNameWithAffix}}'s {{stats}} rose!",
  "statSharplyRose_one": "{{pokemonNameWithAffix}}'s {{stats}} sharply rose!",
  "statSharplyRose_other": "{{pokemonNameWithAffix}}'s {{stats}} sharply rose!",
  "statRoseDrastically_one": "{{pokemonNameWithAffix}}'s {{stats}} rose drastically!",
  "statRoseDrastically_other": "{{pokemonNameWithAffix}}'s {{stats}} rose drastically!",
  "statWontGoAnyHigher_one": "{{pokemonNameWithAffix}}'s {{stats}} won't go any higher!",
  "statWontGoAnyHigher_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any higher!",
  "statFell_one": "{{pokemonNameWithAffix}}'s {{stats}} fell!",
  "statFell_other": "{{pokemonNameWithAffix}}'s {{stats}} fell!",
  "statHarshlyFell_one": "{{pokemonNameWithAffix}}'s {{stats}} harshly fell!",
  "statHarshlyFell_other": "{{pokemonNameWithAffix}}'s {{stats}} harshly fell!",
  "statSeverelyFell_one": "{{pokemonNameWithAffix}}'s {{stats}} severely fell!",
  "statSeverelyFell_other": "{{pokemonNameWithAffix}}'s {{stats}} severely fell!",
  "statWontGoAnyLower_one": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```

2024-07-10 18:37 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "statWontGoAnyLower_other": "{{stats}} von {{pokemonNameWithAffix}} können nicht weiter sinken!",
```suggestion
  "statRose_one": "{{stats}} von {{pokemonNameWithAffix}} steigt!",
  "statRose_other": "{{stats}} von {{pokemonNameWithAffix}} steigen!",
  "statSharplyRose_one": "{{stats}} von {{pokemonNameWithAffix}} steigt stark!",
  "statSharplyRose_other": "{{stats}} von {{pokemonNameWithAffix}} steigen stark!",
  "statRoseDrastically_one": "{{stats}} von {{pokemonNameWithAffix}} steigt drastisch!",
  "statRoseDrastically_other": "{{stats}} von {{pokemonNameWithAffix}} steigen drastisch!",
  "statWontGoAnyHigher_one": "{{stats}} von {{pokemonNameWithAffix}} kann nicht weiter erhöht werden!",
  "statWontGoAnyHigher_other": "{{stats}} von {{pokemonNameWithAffix}} können nicht weiter erhöht werden!",
  "statFell_one": "{{stats}} von {{pokemonNameWithAffix}} sinkt!",
  "statFell_other": "{{stats}} von {{pokemonNameWithAffix}} sinken!",
  "statHarshlyFell_one": "{{stats}} von {{pokemonNameWithAffix}} sinkt stark!",
  "statHarshlyFell_other": "{{stats}} von {{pokemonNameWithAffix}} sinken stark!",
  "statSeverelyFell_one": "{{stats}} von {{pokemonNameWithAffix}} sinkt drastisch!",
  "statSeverelyFell_other": "{{stats}} von {{pokemonNameWithAffix}} sinken drastisch!",
  "statWontGoAnyLower_one": "{{stats}} von {{pokemonNameWithAffix}} kann nicht weiter sinken!",
  "statWontGoAnyLower_other": "{{stats}} von {{pokemonNameWithAffix}} können nicht weiter sinken!",
```

2024-07-10 18:40 UTC, flx-sta commented on src/locales/zh_TW/battle.ts
> +
NIT: accidental new-line

2024-07-10 18:40 UTC, flx-sta approved these changes
lgtm 🚀

2024-07-10 18:42 UTC, CodeTappert commented on src/locales/zh_TW/battle.ts
> +
```suggestion
```

2024-07-10 18:50 UTC, josericardo-fo approved these changes

2024-07-11 01:24 UTC, 40chyan reviewed
zh_cn fixed, based on the discussion in translation channel about i18n dose not differ plurals in chinese

2024-07-11 01:24 UTC, 40chyan commented on src/locales/zh_CN/battle.ts
> +  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}的 {{stats}} 都已经无法再降低了！",
```suggestion
  "statRose_one": "{{pokemonNameWithAffix}}\n的{{stats}}提高了！",
  "statRose_other": "{{pokemonNameWithAffix}}的 {{stats}}提高了！",
  "statSharplyRose_one": "{{pokemonNameWithAffix}}\n的{{stats}}大幅提高了！",
  "statSharplyRose_other": "{{pokemonNameWithAffix}}的 {{stats}}大幅提高了！",
  "statRoseDrastically_one": "{{pokemonNameWithAffix}}\n的{{stats}}极大幅提高了！",
  "statRoseDrastically_other": "{{pokemonNameWithAffix}}的 {{stats}}极大幅提高了！",
  "statWontGoAnyHigher_one": "{{pokemonNameWithAffix}}\n的{{stats}}已经无法再提高了！",
  "statWontGoAnyHigher_other": "{{pokemonNameWithAffix}}的 {{stats}}已经无法再提高了！",
  "statFell_one": "{{pokemonNameWithAffix}}\n的{{stats}}降低了！",
  "statFell_other": "{{pokemonNameWithAffix}}的 {{stats}}降低了！",
  "statHarshlyFell_one": "{{pokemonNameWithAffix}}\n的{{stats}}大幅降低了！",
  "statHarshlyFell_other": "{{pokemonNameWithAffix}}的 {{stats}}大幅降低了！",
  "statSeverelyFell_one": "{{pokemonNameWithAffix}}\n的{{stats}}极大幅降低了！",
  "statSeverelyFell_other": "{{pokemonNameWithAffix}}的 {{stats}}极大幅降低了！",
  "statWontGoAnyLower_one": "{{pokemonNameWithAffix}}\n的{{stats}}已经无法再降低了！",
  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}的 {{stats}}已经无法再降低了！",
```

2024-07-11 05:32 UTC, CodeTappert commented on src/locales/zh_TW/battle.ts
> +  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```suggestion
  "statRose_other": "{{pokemonNameWithAffix}}'s {{stats}} rose!",
  "statSharplyRose_other": "{{pokemonNameWithAffix}}'s {{stats}} sharply rose!",
  "statRoseDrastically_other": "{{pokemonNameWithAffix}}'s {{stats}} rose drastically!",
  "statWontGoAnyHigher_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any higher!",
  "statFell_other": "{{pokemonNameWithAffix}}'s {{stats}} fell!",
  "statHarshlyFell_other": "{{pokemonNameWithAffix}}'s {{stats}} harshly fell!",
  "statSeverelyFell_other": "{{pokemonNameWithAffix}}'s {{stats}} severely fell!",
  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}'s {{stats}} won't go any lower!",
```

2024-07-11 05:32 UTC, CodeTappert commented on src/locales/zh_CN/battle.ts
> +  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}的 {{stats}}已经无法再降低了！",
```suggestion
  "statRose_other": "{{pokemonNameWithAffix}}的 {{stats}}提高了！",
  "statSharplyRose_other": "{{pokemonNameWithAffix}}的 {{stats}}大幅提高了！",
  "statRoseDrastically_other": "{{pokemonNameWithAffix}}的 {{stats}}极大幅提高了！",
  "statWontGoAnyHigher_other": "{{pokemonNameWithAffix}}的 {{stats}}已经无法再提高了！",
  "statFell_other": "{{pokemonNameWithAffix}}的 {{stats}}降低了！",
  "statHarshlyFell_other": "{{pokemonNameWithAffix}}的 {{stats}}大幅降低了！",
  "statSeverelyFell_other": "{{pokemonNameWithAffix}}的 {{stats}}极大幅降低了！",
  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}的 {{stats}}已经无法再降低了！",
```

2024-07-11 06:07 UTC, 40chyan approved these changes

2024-07-11 06:07 UTC, 40chyan commented on src/locales/zh_CN/battle.ts
> +  "statWontGoAnyLower_other": "{{pokemonNameWithAffix}}的 {{stats}}已经无法再降低了！",
all good

2024-07-11 15:47 UTC, merged