[QoL] Added Able/Not Able for Evolution/Form Items
pagefaultgames/pokerogue pull request #2602
Opened 2024-06-25 21:01 UTC by Arxalc

**This is the same as #2104, but that branch got borked so I made a new one.**
## What are the changes?

Adds "Able/Not Able" text to party screen when applying a evolutionary/form change item similar to TMs.
## Why am I doing these changes?

Closes #1957 . Gives an indicator as to if a Pokemon can use the item.
## What did change?

Added generate compatible evolutionary/form change items functions and variable inside` PlayerPokemon` in `pokemon.ts`.
Like when generating compatible TM's, these will be called whenever a new Pokemon object is created.
### Screenshots/Videos

_Taking a Thunder Stone for example_
![Screenshot (5)](https://github.com/pagefaultgames/pokerogue/assets/63990624/a37873a0-f407-4f4e-b15d-b8a132e4bac3)

## How to test the changes?

Override to give a FORM_CHANGE_ITEM or EVOLUTION_ITEM as a shop reward with the appropriate pokemon. 
## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [Nothing that affects these changes] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-26 07:27 UTC, torranx commented on src/ui/party-ui-handler.ts
> +      }
please make able/not able localazible, also i think you can merge your conditions here

2024-06-26 18:56 UTC, Arxalc commented on src/ui/party-ui-handler.ts
> +      }
#2566 is localizing party-ui-handler things anyways, but I added the i18-thing for these. Also tidied the conditionals 👍

2024-06-26 19:00 UTC, torranx commented on src/locales/en/party-ui-handler.ts
> +  "learned": "Learned",
please follow existing naming convention

2024-06-27 00:09 UTC, josericardo-fo commented
Hm... what do you mean borked?

2024-06-27 00:10 UTC, josericardo-fo commented
#2566

2024-06-29 16:14 UTC, josericardo-fo commented
You should add placeholders for other languages

2024-06-29 19:29 UTC, Arxalc commented
> You should add placeholders for other languages

Do I just add the labels for the other locals but keep the text in english? I'm not familiar with how people localize things.

2024-07-02 18:21 UTC, OrangeRed requested changes
I can't comment on the UI changes so get a second opinion from someone else.

2024-07-02 18:21 UTC, OrangeRed commented on src/field/pokemon.ts
> +    if (this.isFusion() && pokemonEvolutions.hasOwnProperty(this.fusionSpecies.speciesId)) {
Instead of `Object.jasOwnProperty(property)` can you use `property in Object`?

2024-07-02 18:21 UTC, OrangeRed commented on src/field/pokemon.ts
> +      speciesFormEvolutions.concat(evolutions.filter(e => e.item !== EvolutionItem.NONE && (e.evoFormKey === null || (e.preFormKey || "") === this.getFusionFormKey()) && (!e.condition || e.condition.
Instead of doing this conditional filter twice and then the result concatenating can you instead move the evolutions array outside, concat it and then apply the filter only once.

2024-07-02 18:21 UTC, OrangeRed commented on src/field/pokemon.ts
> +    this.evolutionItems = possibleEvolutionItems;
I don't know if mutating class properties like this is desirable. Can you instead return the items and set `this.evolutionItems` using the return of this method.

2024-07-02 18:21 UTC, OrangeRed commented on src/field/pokemon.ts
> +  }
Can you do the same for this method as I mentioned in the previous comments

2024-09-17 16:39 UTC, flx-sta commented
@Arxalc   closed for being stale (no updates for over a month)

----

Feel free to create a new PR or ask us to re-open this one.

2024-09-17 16:39 UTC, closed without merging