[Feature] Stop trainer spawns on evil team and E4 floors
pagefaultgames/pokerogue pull request #2610
Opened 2024-06-26 02:33 UTC by Tempo-anon

## What are the changes?
Stop trainers from spawning on evil team and E4 floors

## Why am I doing these changes?
Players don't want trainers spawning on specific floors

## What did change?
Stop trainers from spawning on 63, 65, 67, 68, 69, 113, 116, 117, 118, 119, 183, 185, 187, 189

### Screenshots/Videos
n/a

## How to test the changes?
Pull and play

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-26 02:40 UTC, Xavion3 requested changes

2024-06-26 02:40 UTC, Xavion3 commented on src/game-mode.ts
> +      const forbiddenSpawnWaves = [63, 65, 67, 68, 69, 113, 116, 117, 118, 119, 183, 185, 187, 189];
Don't hardcode this. We already have a function for checking if a given wave is a fixed battle.

2024-06-26 02:48 UTC, Tempo-anon commented on src/game-mode.ts
> +      const forbiddenSpawnWaves = [63, 65, 67, 68, 69, 113, 116, 117, 118, 119, 183, 185, 187, 189];
This is only for generic trainer spawns. There really isn't a point for generic trainer spawns on the 6X and 11X or 18X floors since
1. The main point of trainers is to grant the player more money and more Pokemon than just the 1-2 per floor
2. Players will have already fought a bunch of trainers so more feels tedious and unnecessary
3. It doesn't fit thematically to have a random hiker pop up in between elite 4 members or right before/after evil team fights

2024-06-26 04:12 UTC, Tempo-anon commented
Xavion tells me I can refactor 
`          if ((w % 30) === (arena.scene.offsetGym ? 0 : 20) || this.isFixedBattle(waveIndex)) {`
and change waveIndex to w it would check for fixed battles within 3 waves and prevent random generic trainer spawns

2024-06-28 05:51 UTC, Xavion3 commented on src/game-mode.ts
> +        // Stop generic trainers from spawning in within 3 floors of a fixed battle
This comment is wrong, it tries to stop them spawning within 3 waves of any battle.

2024-06-28 05:51 UTC, Xavion3 requested changes
Looks functional to me.

2024-06-28 05:59 UTC, flx-sta requested changes
I've added some automated tests to cover this behavior
https://github.com/Tempo-anon/pokerogue/pull/7

2024-06-28 15:25 UTC, flx-sta commented on src/game-mode.ts
> +
Is there an issue number for that? If so we should mention it or even link the issue

2024-06-28 15:25 UTC, flx-sta commented on src/test/game-mode.test.ts
> +      expect(classicGameMode.isWaveTrainer(6, arena)).not.toBeTruthy();
This right now is the result of `isWaveTrainer()` returning `0` sometimes.
Technically it should do `toBeTruthy()`

2024-06-28 15:25 UTC, flx-sta commented on src/test/game-mode.test.ts
> +      expect(classicGameMode.isWaveTrainer(15, arena)).not.toBeTruthy(); // just to be sure...
This right now is the result of `isWaveTrainer()` returning `0` sometimes.
Technically it should do `toBeTruthy()`

2024-06-28 15:25 UTC, flx-sta commented on src/game-mode.ts
```ts
return allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance);
```


This doesn't always return a boolean (for some reasons). It should be either
```ts
return Boolean(allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance));
```
or
```ts
return !!(allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance));
```

**this will break the tests though!!** It's hard to control `Utils.randSeedInt()` the right way for this. But there is hope.

----

<img src="https://media.discordapp.net/attachments/1176874654015684739/1256259959155326986/image.png?ex=66801ec2&is=667ecd42&hm=d24b4568c93d632c1b310d1f0cd708dcfe8a3621372544ff64d22e59d5f47185&=&format=webp&quality=lossless&width=600&height=192"/>
<img src="https://media.discordapp.net/attachments/1176874654015684739/1256260170795847680/image.png?ex=66801ef4&is=667ecd74&hm=d5d60f83b3b5f92f4527592ec77a473c375712653c37a32718421db7ba583d2d&=&format=webp&quality=lossless&width=660&height=208"/>

2024-06-28 15:26 UTC, flx-sta commented on src/game-mode.ts
`waveTrainerChance` is the same as `trainerChance` if I'm not mistaken

2024-06-28 16:13 UTC, flx-sta requested changes
The test will fail unless you update `game-mode.ts#156` to be:
```ts
      return Boolean(allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance));
```

2024-06-28 16:13 UTC, flx-sta commented on src/test/game-mode.test.ts
> +});
```suggestion
import { GameMode, GameModes, getGameMode } from "#app/game-mode.js";
import {
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from "vitest";
import GameManager from "./utils/gameManager";
import * as Utils from "../utils";

describe("game-mode", () => {
  let phaserGame: Phaser.Game;
  let game: GameManager;

  beforeAll(() => {
    phaserGame = new Phaser.Game({
      type: Phaser.HEADLESS,
    });
  });

  afterEach(() => {
    game.phaseInterceptor.restoreOg();
    vi.resetAllMocks();
  });

  beforeEach(() => {
    game = new GameManager(phaserGame);
  });

  describe("classic", () => {
    let classicGameMode: GameMode;

    beforeEach(() => {
      classicGameMode = getGameMode(GameModes.CLASSIC);
    });

    it("does NOT spawn trainers within 3 waves of fixed battle", () => {
      const { arena } = game.scene;
      /** set wave 16 to be a fixed trainer fight meaning wave 13-19 don't allow trainer spawns */
      vi.spyOn(classicGameMode, "isFixedBattle").mockImplementation(
        (n: number) => (n === 16 ? true : false)
      );
      vi.spyOn(arena, "getTrainerChance").mockReturnValue(1);
      vi.spyOn(Utils, "randSeedInt").mockReturnValue(0);

      expect(classicGameMode.isWaveTrainer(12, arena)).toBeTruthy();
      expect(classicGameMode.isWaveTrainer(13, arena)).toBeFalsy();
      expect(classicGameMode.isWaveTrainer(14, arena)).toBeFalsy();
      expect(classicGameMode.isWaveTrainer(15, arena)).toBeFalsy();
      // Wave 16 is a fixed trainer battle
      expect(classicGameMode.isWaveTrainer(17, arena)).toBeFalsy();
      expect(classicGameMode.isWaveTrainer(18, arena)).toBeFalsy();
      expect(classicGameMode.isWaveTrainer(19, arena)).toBeFalsy();
    });
  });
});
```

2024-06-28 21:21 UTC, flx-sta commented on src/game-mode.ts
> +        // Stop generic trainers from spawning in within 3 waves of a trainer battle
```suggestion
        // Stop generic trainers from spawning in within 3 waves of a fixed trainer battle
```

2024-06-28 21:25 UTC, damocleas approved these changes

2024-06-29 07:09 UTC, torranx commented on src/game-mode.ts
> +      return Boolean(allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance));
im curious why do we need to wrap this with Boolean()?

2024-06-29 07:09 UTC, torranx commented on src/test/game-mode.test.ts
> +      /** set wave 16 to be a fixed trainer fight meaning wave 13-19 don't allow trainer spawns */
typo? 13-19 -> 17-19

2024-06-29 07:28 UTC, flx-sta commented on src/test/game-mode.test.ts
> +      /** set wave 16 to be a fixed trainer fight meaning wave 13-19 don't allow trainer spawns */
Checking below and above

2024-06-29 07:29 UTC, flx-sta commented on src/game-mode.ts
> +      return Boolean(allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance));
JS bs.
Try putting `0 && false` into your console.
It’s inconsistent with Boolean returns

2024-06-29 07:47 UTC, torranx commented on src/game-mode.ts
> +      return Boolean(allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance));
it is inconsistent if youre expecting a boolean value because `&&` immediately shortcircuits/returns the first falsy value it encounters. but i noticed on the tests youre using `.toBeFalsy()` and `.toBeTruthy` so there shouldnt be a need to wrap it in `Boolean()` . if im missing something, please do tell me, thanks!

2024-06-29 07:48 UTC, torranx commented on src/test/game-mode.test.ts
> +      /** set wave 16 to be a fixed trainer fight meaning wave 13-19 don't allow trainer spawns */
missed that, thanks

2024-06-29 15:53 UTC, flx-sta commented on src/game-mode.ts
> +      return Boolean(allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance));
Trust me. I’m as confused as you are. But as of now that is the solution to prevent the method from returning `0` instead of a Boolean.
You can juggle around with the test in your local ide to see for yourself.

2024-06-29 17:58 UTC, torranx commented on src/game-mode.ts
> +      return Boolean(allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance));
ran the tests multiple times and all passed without the `Boolean()` wrapper

<img width="739" alt="Screenshot 2024-06-30 at 1 58 10 AM" src="https://github.com/pagefaultgames/pokerogue/assets/68144167/2148c9d5-5168-4553-9d62-17e404e19836">

2024-06-30 00:59 UTC, flx-sta commented on src/game-mode.ts
> +      return Boolean(allowTrainerBattle && trainerChance && !Utils.randSeedInt(trainerChance));
Fair enough. Guess making a Boolean result defined method ensure to return a Boolean isn’t too bad though 😁

2024-07-08 02:55 UTC, Xavion3 approved these changes

2024-07-08 14:33 UTC, merged