[Feature][FUN] add spaceBreeder splash message
pagefaultgames/pokerogue pull request #2631
Opened 2024-06-26 22:45 UTC by flx-sta

## What are the changes?

added a `Space Breeders!` splash screen message

## Why am I doing these changes?

fun

## What did change?

see `what are the changes`

### Screenshots/Videos

<img width="518" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/6ce48e3e-e41a-45cd-b1d0-1a1351dbc897">

## How to test the changes?

replace `src/data/splash-messages.ts` with this:
```ts
import i18next from "i18next";

export function getBattleCountSplashMessage(): string {
  return `{COUNT} ${i18next.t("splashMessages:battlesWon")}`;
}

export function getSplashMessages(): string[] {
  const splashMessages = Array(10).fill(getBattleCountSplashMessage());
  splashMessages.push(...[
    // i18next.t("splashMessages:joinTheDiscord"),
    // i18next.t("splashMessages:infiniteLevels"),
    // i18next.t("splashMessages:everythingStacks"),
    // i18next.t("splashMessages:optionalSaveScumming"),
    // i18next.t("splashMessages:biomes"),
    // i18next.t("splashMessages:openSource"),
    // i18next.t("splashMessages:playWithSpeed"),
    // i18next.t("splashMessages:liveBugTesting"),
    // i18next.t("splashMessages:heavyInfluence"),
    // i18next.t("splashMessages:pokemonRiskAndPokemonRain"),
    // i18next.t("splashMessages:nowWithMoreSalt"),
    // i18next.t("splashMessages:infiniteFusionAtHome"),
    // i18next.t("splashMessages:brokenEggMoves"),
    // i18next.t("splashMessages:magnificent"),
    // i18next.t("splashMessages:mubstitute"),
    // i18next.t("splashMessages:thatsCrazy"),
    // i18next.t("splashMessages:oranceJuice"),
    // i18next.t("splashMessages:questionableBalancing"),
    // i18next.t("splashMessages:coolShaders"),
    // i18next.t("splashMessages:aiFree"),
    // i18next.t("splashMessages:suddenDifficultySpikes"),
    // i18next.t("splashMessages:basedOnAnUnfinishedFlashGame"),
    // i18next.t("splashMessages:moreAddictiveThanIntended"),
    // i18next.t("splashMessages:mostlyConsistentSeeds"),
    // i18next.t("splashMessages:achievementPointsDontDoAnything"),
    // i18next.t("splashMessages:youDoNotStartAtLevel"),
    // i18next.t("splashMessages:dontTalkAboutTheManaphyEggIncident"),
    // i18next.t("splashMessages:alsoTryPokengine"),
    // i18next.t("splashMessages:alsoTryEmeraldRogue"),
    // i18next.t("splashMessages:alsoTryRadicalRed"),
    // i18next.t("splashMessages:eeveeExpo"),
    // i18next.t("splashMessages:ynoproject"),
    i18next.t("splashMessages:spaceBreeders"),
  ]);

  return splashMessages;
}
```

reload a couple of times and it should show up eventually
## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-06-26 22:55 UTC, CodeTappert approved these changes

2024-06-27 01:36 UTC, josericardo-fo commented on src/locales/pt_BR/splash-messages.ts
> +  "spaceBreeders": "Space Breeders!",
Criadores Pokémon no Espaço!

2024-06-27 01:37 UTC, josericardo-fo commented on src/locales/pt_BR/splash-messages.ts
> +  "spaceBreeders": "Space Breeders!",
```suggestion
  "spaceBreeders": "Criadores Pokémon no Espaço!!",
```

2024-06-27 08:11 UTC, torranx commented
if this is in reference to breeders in space biome, isnt it more appropriate to word it like "Breeders In Space?!". The current text sounds like the person is breeding space to me.

2024-06-27 14:45 UTC, flx-sta commented
@torranx yeah.. I was a bit torn between those two wordings.. ironically the German translation is designed in that way of a sentence

2024-06-27 17:44 UTC, flx-sta commented
@josericardo-fo can you double check if the translation of pt_br is still accurate with the new wording?

2024-06-27 17:44 UTC, flx-sta commented
@Adri1 french?

2024-06-27 17:47 UTC, Adri1 reviewed
Added French

2024-06-27 17:47 UTC, Adri1 commented on src/locales/fr/splash-messages.ts
> +  "breedersInSpace": "Breeders in space!",
```suggestion
  "breedersInSpace": "Des Éleveurs dans l’espace !",
```

2024-06-27 17:49 UTC, Adri1 approved these changes

2024-07-10 17:58 UTC, flx-sta commented
@f-fsantos this would be ready to be merged

2024-07-10 18:00 UTC, flx-sta commented
Waiting for some more translations

2024-07-10 18:20 UTC, josericardo-fo commented on src/locales/pt_BR/splash-messages.ts
> +  "breedersInSpace": "Criadores Pokémon no Espaço!!",
```suggestion
  "breedersInSpace": "Criadores Pokémon no Espaço!",
```

2024-07-10 20:46 UTC, AsdarDevelops requested changes
Spanish localization

2024-07-10 20:46 UTC, AsdarDevelops commented on src/locales/es/splash-messages.ts
> +  "breedersInSpace": "Breeders in space!",
```suggestion
  "breedersInSpace": "Criadores... ¡EN EL ESPACIO!",
```

2024-07-10 22:16 UTC, NicusPulcis commented
@flx-sta added italian

2024-07-11 01:30 UTC, 40chyan reviewed
cn

2024-07-11 01:30 UTC, 40chyan commented on src/locales/zh_CN/splash-messages.ts
> +  "breedersInSpace": "Breeders in space!",
```suggestion
  "breedersInSpace": "饲养员也能上太空？",
```

2024-07-11 05:47 UTC, flx-sta commented
@Tempo-anon @f-fsantos reasy to merge. (Just 2 languages missing)

2024-07-11 22:02 UTC, NicusPulcis commented
@flx-sta i've sent a PR for the italian translation

2024-07-11 22:20 UTC, flx-sta commented
> @flx-sta i've sent a PR for the italian translation

thanks. A simple `suggestion` in the file works too next time. Takes less time to create
![Uploading image.png…]()

2024-07-12 14:11 UTC, NicusPulcis commented
aaaaaalright @flx-sta thanks for the tip! i'll try to remember how that works for the next time lol

2024-07-12 16:18 UTC, CodeTappert approved these changes

2024-07-12 21:12 UTC, Madmadness65 approved these changes

2024-07-12 21:13 UTC, merged