Added more dialogue options for evil team grunts [Enhancement]
pagefaultgames/pokerogue pull request #2640
Opened 2024-06-27 02:18 UTC by c0nsy

## What are the changes?
Adding more dialogue for grunts

## Why am I doing these changes?
closes : 2095](https://github.com/pagefaultgames/pokerogue/issues/2095)

## What did change?
More dialogue indialogue.ts

### Screenshots/Videos
![rocket1](https://github.com/pagefaultgames/pokerogue/assets/65863220/dc118305-e2b6-4d04-8f9e-e69d29028bdc)
![rocket2](https://github.com/pagefaultgames/pokerogue/assets/65863220/cc6efbdd-62c5-4bf7-ace2-aa74c7a1a26c)

## How to test the changes?
Set trainer battles to all be one of the following different types

  ROCKET_GRUNT,
  MAGMA_GRUNT,
  AQUA_GRUNT,
  GALACTIC_GRUNT,
  PLASMA_GRUNT,
  FLARE_GRUNT,

## Checklist
- [x ] There is no overlap with another PR?
- [x ] The PR is self-contained and cannot be split into smaller PRs?
- [ x] Have I provided a clear explanation of the changes?
- [x ] Have I tested the changes (manually)?
    - [ x] Are all unit tests still passing? (`npm run test`)
- [x ] Are the changes visual?
  - [x ] Have I provided screenshots/videos of the changes?

2024-06-27 02:33 UTC, josericardo-fo commented
Just a tip, to mark inside the [ ] checklist, just put the letter "x" inside of it without any spaces.
Like this: [x]
It will look like this:
- [x] example

2024-06-27 02:42 UTC, Tempo-anon requested changes
1. You'd need to edit `src/dialogue.ts` to actually add these into each of the grunt dialogues or they won't show up at all
2. You should add these keys into the other locales too so other languages can localize them at their own pace
3. I was expecting 3-4 funny lines per grunt so team flare is still lacking some
4. Some of the lines you put in encounter feel more like they should go in victory
5. There's a few really funny ones that I thought would be in here that are not

2024-06-27 10:50 UTC, CodeTappert commented
Please add the keys with english placeholders in for all languages

2024-06-27 21:21 UTC, c0nsy commented
> 1. You'd need to edit `src/dialogue.ts` to actually add these into each of the grunt dialogues or they won't show up at all [x]
> 2. You should add these keys into the other locales too so other languages can localize them at their own pace [x]
> 3. I was expecting 3-4 funny lines per grunt so team flare is still lacking some [x]
> 4. Some of the lines you put in encounter feel more like they should go in victory [x]
> 5. There's a few really funny ones that I thought would be in here that are not
Could you please suggest some?

2024-06-29 15:49 UTC, CodeTappert commented
They need to have the same amount of victory and encounter dialogue. Since they are basically linked as pairs

2024-07-01 16:55 UTC, c0nsy reviewed
Changes submitted

2024-07-01 20:53 UTC, Tempo-anon commented on src/locales/en/dialogue.ts
> +      11: "Resistance is futile! Give us your Pokémon or face the consequences!"
2 feels like it should be a victory quote rather than an encounter one. 4 feels weird by itself as an encounter quote.

I was hoping to find the "STEAL for team rocket EXPLOIT for team rocket" quote but I can't seem to find it. Maybe throw in the quote about dropping the lift key.

2024-07-01 20:53 UTC, Tempo-anon commented on src/locales/en/dialogue.ts
> +
2 feels really out of place. 4 doesn't fit as a standalone encounter quote. Do some of the longer lines like 6 and 7 actually fit without issue?

Also some formatting errors like a space before 14's line and extra lines at the bottom

2024-07-01 20:53 UTC, Tempo-anon commented on src/locales/en/dialogue.ts
> +      17: "I should have brought more potions... and a better strategy."
The steamed line feels like it got repeated from Rocket Grunt's victory dialogue

2024-07-01 20:53 UTC, Tempo-anon commented on src/locales/en/dialogue.ts
> +      8: "Hey! You there! Which do you think is cooler? Team Aqua's uniform or Team Magma's?",
Once again, 2 feels really out of place. 3 is also a bit weird since it's too specific. I'd change it to something like "I was going to ambush you, but you had to dawdle in the Plains forever, didn't you?" which makes more sense since every classic player will have to go through the plains. 8 is also another repeated line. Surely we can find enough lines so there's no need for exact repeats?

2024-07-01 20:53 UTC, Tempo-anon commented on src/locales/en/dialogue.ts
> +
Extra newline. No real complaints here but there's quite a lot of funny galactic grunt quotes that can be used.

Grunt: Cheerio, then! (to Crasher Wake) You daft codger, your mask's absurd!
Grunt: Because of you, they took my CLEFAIRY away...
Grunt: If you try to mess with me, I’ll shut you down with a Pokémon battle. So, what’s it going to be? Are you going to mess with me?

2024-07-01 20:53 UTC, Tempo-anon commented on src/locales/en/dialogue.ts
> +      9: "Team Plasma will liberate Pokémon from selfish humans like you!"
2 with the plasbad quote is definitely a victory quote rather than an encounter. You're also missing the beginning of that quote which is great "This is bad... Badbadbadbadbadbadbad! Bad for Team Plasma! Or Plasbad, for short!" There's a ton of very funny plasma quotes to use

 Extra spaces in 5 and 7

2024-07-01 20:53 UTC, Tempo-anon commented on src/locales/en/dialogue.ts
> +      9: "We came, we saw, we Plasma'd!"
The #2 daft codger line is from a galactic grunt. There's also a lot of good victory quotes you can find just by looking up "plasma" in the poke corpus

2024-07-01 20:53 UTC, Tempo-anon commented on src/locales/en/dialogue.ts
> +
Extra line after victory6 but I haven't personally played XY so I'll leave it to others if they have any must include flare quotes

2024-07-03 07:00 UTC, 40chyan reviewed
idk if the spaces can cause linting issues, but if so you may apply these changes to other files  too.

2024-07-15 03:27 UTC, 40chyan commented
1. since the english dialogue yet to be approved, I think you should make this PR a draft for now
2. @Tempo-anon can you please check the dialogue in this PR again so we translation team can start doing this.

2024-07-22 15:58 UTC, Blitz425 commented
I'd say since there is such a disparity between the amount of dialogue that each Grunt has, it would be better to limit the amount to around 5 options (also having up to 17 lines of dialogue is pretty overkill). In my opinion I think the best lines to keep per team would be something like

Rocket
1: "Prepare for trouble!",
2: "We're pulling a big job here! Get lost, kid!",
3: "Hand over your Pokémon, or face the wrath of Team Rocket!",
4: "You're about to experience the true terror of Team Rocket!",
5: "Resistance is futile! Give us your Pokémon or face the consequences!"

Magma
1: "If you get in the way of Team Magma, don't expect any mercy!",
2: "You'd better not interfere with our plans! We're making the world a better place!",
3: "You're in the way! Team Magma has no time for kids like you!",
4: "We're going to use the power of a volcano! It's gonna be... explosive! Get it? Heh heh!",
5: "I hope you brought marshmallows because things are about to heat up!"

Aqua
1: "No one who crosses Team Aqua gets any mercy, not even kids!",
2: "Grrr…You've got some nerve meddling with Team Aqua!",
3: "Hey, you there! Don't butt in!",
4: "We, Team Aqua, exist for the good of all!",
5: "Prepare to be washed away by the tides of my… uh, Pokémon! Yeah, my Pokémon!"

Galactic
1: "Don't mess with Team Galactic!",
2: "You dare to challenge Team Galactic?",
3: "Hope you're ready for a cosmic beatdown!",
4: "Witness the power of our technology and the future we envision!",
5: "In the name of Team Galactic, I'll eliminate anyone who stands in our way!"

Plasma
1: "We won't tolerate people who have different ideas!",
2: "If I win against you, release your Pokémon!",
3: "As a proud member of Team Plasma, I will gladly battle with you.",
4: "YOU! To please my Pokémon, lose!",
5: "Team Plasma will liberate Pokémon from selfish humans like you!"

Flarw
1: "Team Flare will cleanse the world of imperfection!",
2: "Prepare to face the brilliance of Team Flare!",
3: "Team Flare's style and grace will outshine any opponent!",
4: "Your Pokémon are no match for the elegance of Team Flare.",
5: "Hope you brought your sunglasses, because things are about to get bright!"

2024-08-08 13:15 UTC, Tempo-anon commented
Closing in favor of https://github.com/pagefaultgames/pokerogue/pull/3331

2024-08-08 13:15 UTC, closed without merging