[Enhancement] Pokemon generation number tooltip
pagefaultgames/pokerogue pull request #2642
Opened 2024-06-27 03:09 UTC by EmberCM

## What are the changes?
Adds a tooltip to show the generation of the Pokemon

## Why am I doing these changes?
I don't wanna have to check a pokedex for every Pokemon during a challenge run

## What did change?
Added a tooltip when you hover over the enemy Pokemon's name to show their generation number

### Screenshots/Videos
![tooltip](https://i.ember.zone/Y6ULxq2X5EYutDZr.png)
![mobile](https://i.ember.zone/QV02CyepzDSvMra1.png)
![setting](https://i.ember.zone/lkt3iQoE2ejzyM8H.png)

## How to test the changes?

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

![tests](https://i.ember.zone/0QH2PfBTI96hgNoS.png)

2024-06-27 03:11 UTC, OrangeRed commented
Instead of numbers can you use roman numerals like in the starter select menu

2024-06-27 06:10 UTC, EmberCM commented
> Instead of numbers can you use roman numerals like in the starter select menu

This will be aligned with `locales\starter-select-ui-handler.ts`
![rn](https://i.ember.zone/YyWtHDkc3aTRcl1i.png)

2024-06-27 08:05 UTC, torranx commented
If this is entirely a tooltip _on hover_, I dont see the need to create a dedicated option for this. The "option" is essentially when the user decides to hover the name.

2024-06-27 15:46 UTC, ReneGV commented
Given that the change is meant to help challenge runs I am not sure if there is overlap with
- https://github.com/pagefaultgames/pokerogue/pull/2628

2024-06-27 17:54 UTC, OrangeRed requested changes

2024-06-27 17:54 UTC, OrangeRed commented on src/battle-scene.ts
> +
you want to fixed values like this use the literal type `0 | 1 | 2` instead of number or just use the enum as the typedef

2024-06-28 19:47 UTC, EmberCM commented on src/battle-scene.ts
> +
Instance variable no longer exists

2024-06-28 19:48 UTC, EmberCM commented
> If this is entirely a tooltip _on hover_, I dont see the need to create a dedicated option for this. The "option" is essentially when the user decides to hover the name.

I added the option in case people only wanted to only have it show up during challenges, but you make a good point.

2024-06-29 04:00 UTC, torranx commented
> > If this is entirely a tooltip _on hover_, I dont see the need to create a dedicated option for this. The "option" is essentially when the user decides to hover the name.
> 
> 
> 
> I added the option in case people only wanted to only have it show up during challenges, but you make a good point.

My point stands that if the user doesnt want it to show up, then avoid hovering it, also its not as if the game is played using mouse so there is always the intention if the user decides to hover it. This is only my opinion tho. Its up for the devs to decide

2024-06-29 22:34 UTC, marcodola commented
I worked on [ [Feature]Highlight usable pokemon in green during a challenge #2628 ](https://github.com/pagefaultgames/pokerogue/pull/2628) but I didn't consider the option of the tooltip and it seems great. 
I was wondering if it's possible to merge the two ideas by showing a message like "This pokemon is suitable for the current challenge" or something similar

2024-07-08 17:41 UTC, CodeTappert commented on src/locales/de/battle-info.ts
> +  "generation": "Generation {{generation}}",
```suggestion
  "generation": "{{generation}}. Generation",
```

2024-07-08 17:41 UTC, Adri1 reviewed
Added French

2024-07-08 17:41 UTC, Adri1 commented on src/locales/fr/battle-info.ts
> +  "generation": "Generation {{generation}}",
```suggestion
  "generation": "Génération {{generation}}",
```

2024-07-08 17:42 UTC, josericardo-fo commented on src/locales/pt_BR/battle-info.ts
> +  "generation": "Generation {{generation}}",
```suggestion
  "generation": "Geração {{generation}}",
```

2024-07-08 17:45 UTC, RimKnight commented on src/locales/zh_TW/battle-info.ts
> +  "generation": "Generation {{generation}}",
```suggestion
  "generation": "第{{generation}}世代",
```

2024-07-08 17:45 UTC, RimKnight commented on src/locales/zh_CN/battle-info.ts
> +  "generation": "Generation {{generation}}",
```suggestion
  "generation": "第{{generation}}世代",
```

2024-07-08 23:27 UTC, EnochG1 reviewed
Korean translation

2024-07-08 23:27 UTC, EnochG1 commented on src/locales/ko/battle-info.ts
> +  "generation": "Generation {{generation}}",
```suggestion
  "generation": "{{generation}}세대",
```

2024-07-09 14:23 UTC, NicusPulcis commented
@EmberCM i've added the italian translation

2024-07-12 16:19 UTC, CodeTappert approved these changes

2024-07-12 21:23 UTC, merged