Localization: Localized Gacha Machine Names
pagefaultgames/pokerogue pull request #2645
Opened 2024-06-27 04:07 UTC by josericardo-fo

## What are the changes?

Localized the names of the gacha machines.
## Why am I doing these changes?

They weren't localized yet.
## What did change?

Localization and the names of the gachas.
### Screenshots/Videos

## Move UP!
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/e7a425a9-4a22-469b-8d62-afcf74760f31)

## Legendary UP! (just an example in pt_br)
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/46a80cb2-1cc0-4365-9d2c-1c017c316612)

## Shiny UP! (just an example in pt_br)
![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/8d891538-4910-4d7d-91c5-f19e13dd4a9a)

## How to test the changes?

See if the Gacha Machine name fits in the Gacha Menu.
## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-27 04:51 UTC, 40chyan commented on src/locales/zh_TW/egg.ts
> +  "legendaryUPGacha": "UP!",
```suggestion
  "moveUPGacha": "蛋招式UP!",
  "shinyUPGacha": "闪光概率UP!,
  "legendaryUPGacha": "UP!",
```
zh_cn

2024-06-27 05:59 UTC, flx-sta commented
Well that translation broke the build

2024-06-27 06:14 UTC, EnochG1 reviewed
Let's fix it at first.

2024-06-27 06:14 UTC, EnochG1 commented on src/locales/zh_TW/egg.ts
> +  "shinyUPGacha": "闪光概率UP!,
```suggestion
  "shinyUPGacha": "闪光概率UP!",
```

2024-06-27 06:36 UTC, CodeTappert commented on src/locales/de/egg.ts
> +  "legendaryUPGacha": "UP!",
```suggestion
  "moveUPGacha": "Attacken-UP!",
  "shinyUPGacha": "Schillernd-UP!",
  "legendaryUPGacha": "UP!",
```

2024-06-27 09:13 UTC, InnocentGameDev commented on src/locales/es/egg.ts
> +  "legendaryUPGacha": "UP!",
```suggestion
  "moveUPGacha": "¡Más Mov. Huevo Raro!",
  "shinyUPGacha": "¡Más Shiny!",
  "legendaryUPGacha": "más probable!",
```

2024-06-27 10:28 UTC, Adri1 reviewed
Added French

2024-06-27 10:28 UTC, Adri1 commented on src/locales/fr/egg.ts
> +  "legendaryUPGacha": "UP!",
```suggestion
  "moveUPGacha": "Capa + !",
  "shinyUPGacha": "Chroma + !",
  "legendaryUPGacha": "+ !",
```

2024-06-27 12:29 UTC, sodaMelon reviewed
here is the korean translation. ( it was decided in korean discord )

2024-06-27 12:29 UTC, sodaMelon commented on src/locales/ko/egg.ts
> +  "shinyUPGacha": "Shiny UP!",
```suggestion
  "moveUPGacha": "기술 UP!",
  "shinyUPGacha": "특별색 UP!",
```

2024-06-27 13:14 UTC, josericardo-fo commented on src/locales/es/egg.ts
> +  "legendaryUPGacha": "UP!",
The text needs to be smaller

2024-06-27 13:30 UTC, 40chyan commented on src/locales/zh_TW/egg.ts
> +  "shinyUPGacha": "闪光概率UP!",
```suggestion
  "shinyUPGacha": "概率UP!",
```
fixed

2024-06-27 13:30 UTC, 40chyan commented on src/locales/zh_TW/egg.ts
> +  "shinyUPGacha": "闪光概率UP!",
```suggestion
  "shinyUPGacha": "闪光UP!",
```

2024-06-27 13:36 UTC, 40chyan commented on src/locales/zh_CN/egg.ts
> +  "legendaryUPGacha": "UP!",
```suggestion
  "moveUPGacha": "蛋招式UP!",
  "shinyUPGacha": "闪光UP!",
  "legendaryUPGacha": "UP!",
```

2024-06-27 13:38 UTC, Adri1 approved these changes

2024-06-27 14:43 UTC, flx-sta commented on src/locales/es/egg.ts
> +  "legendaryUPGacha": "UP!",
Shorter*

2024-06-27 14:49 UTC, EnochG1 approved these changes

2024-06-27 15:05 UTC, InnocentGameDev commented on src/locales/es/egg.ts
> +  "legendaryUPGacha": "UP!",
How about?

```suggestion
  "moveUPGacha": "Mov. H. +!",
  "shinyUPGacha": "Shiny +!",
  "legendaryUPGacha": "+!",
```

2024-06-27 16:22 UTC, josericardo-fo commented on src/locales/es/egg.ts
> +  "legendaryUPGacha": "UP!",
Works just fine

2024-06-27 16:35 UTC, flx-sta commented on src/locales/es/egg.ts
> +  "legendaryUPGacha": "UP!",
what the heck? legendary is just `+!`?

2024-06-27 16:57 UTC, Adri1 commented on src/locales/es/egg.ts
> +  "legendaryUPGacha": "UP!",
> what the heck? legendary is just `+!`?

The legendary it the icon of the Pokémon and then the text, so what you see here is only the text part

2024-06-28 03:54 UTC, flx-sta requested changes

2024-06-28 03:54 UTC, flx-sta commented on src/ui/egg-gacha-ui-handler.ts
> +      if (currentLanguage === "de" || currentLanguage === "fr" || currentLanguage === "pt-BR") {
```suggestion
      if (["de", "fr", "pt-BR"].includes(currentLanguage)) {
```

2024-06-28 03:54 UTC, flx-sta commented on src/ui/egg-gacha-ui-handler.ts
> +        if (currentLanguage === "de" || currentLanguage === "fr") {
```suggestion
        if (["de", "fr"].includes(currentLanguage) {
```

2024-06-28 03:54 UTC, flx-sta commented on src/ui/egg-gacha-ui-handler.ts
> +        if (currentLanguage === "de" || currentLanguage === "fr") {
```suggestion
        if (["de", "fr"].includes(currentLanguage)) {
```

2024-06-28 04:06 UTC, edaymall approved these changes

2024-06-28 04:10 UTC, edaymall approved these changes

2024-06-28 04:11 UTC, sodaMelon approved these changes

2024-06-28 04:17 UTC, sodaMelon commented
edaymall is my friend's account. don't mind. (just click mistake)
there's no problem in Korean Localization

2024-06-28 13:59 UTC, josericardo-fo commented on src/ui/egg-gacha-ui-handler.ts
> +        if (currentLanguage === "de" || currentLanguage === "fr") {
fixed

2024-06-28 22:36 UTC, CodeTappert commented on src/locales/de/egg.ts
> +  "legendaryUPGacha": "UP!",
```suggestion
  "legendaryUPGacha": "erscheint\nöfter!",
```

2024-06-28 23:14 UTC, josericardo-fo commented on src/locales/de/egg.ts
> +  "legendaryUPGacha": "UP!",
committed

2024-06-29 01:05 UTC, InnocentGameDev approved these changes
The legendary one is the one that seems a bit off, otherwise it's great. Thanks for your work!.

2024-06-29 01:05 UTC, InnocentGameDev commented on src/locales/es/egg.ts
> +  "legendaryUPGacha": "+!",
```suggestion
  "legendaryUPGacha": ", ¡mayor prob.!",
```

2024-07-05 01:26 UTC, Tempo-anon approved these changes

2024-07-05 01:26 UTC, merged

2024-07-05 11:00 UTC, josericardo-fo commented
I didn't mean to revert it, just ignore this