[Fix] Refactor Disguise to work like Ice Face
pagefaultgames/pokerogue pull request #2684
Opened 2024-06-28 15:05 UTC by DayKev

## What are the changes?
Refactor disguise using the code of Ice Face as a base.

## Why am I doing these changes?
Disguise is buggy and spaghetti.

## What did change?
Most of the code for Disguise was removed, and replaced with a modified version of the Ice Face code. More tests were added using the Ice Face tests as a starting point.

## How to test the changes?
`npm run test disguise`

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-28 15:28 UTC, Adri1 commented on src/locales/en/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
Could you also add this line to all other locales, as it can be easily transaltaed by the translation teams?

2024-06-28 15:39 UTC, Adri1 reviewed
Added French (with some other corrections)

2024-06-28 15:39 UTC, Adri1 commented on src/locales/fr/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
```suggestion
  "windPowerCharged": "{{pokemonName}} a été touché par la capacité\n{{moveName}} et se charge en électricité !",
  "quickDraw": "Le talent Tir Vif de {{pokemonName}}\nlui permet d’agir plus vite que d’habitude !",
  "disguiseAvoidedDamage" : "Le déguisement de {{pokemonName}} tombe !",
```

2024-06-28 16:43 UTC, GoldTra requested changes
Spanish translations

2024-06-28 16:43 UTC, GoldTra commented on src/locales/es/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
```suggestion
  "disguiseAvoidedDamage" : "¡El disfraz de {{pokemonName}} se ha roto!",
```

2024-06-28 16:47 UTC, mercurius-00 commented on src/locales/zh_CN/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
```suggestion
  "disguiseAvoidedDamage" : "{{pokemonName}}的画皮脱落了！",
```

2024-06-28 16:47 UTC, mercurius-00 commented on src/locales/zh_TW/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
```suggestion
  "disguiseAvoidedDamage" : "{{pokemonName}}的畫皮脫落了！",
```

2024-06-28 17:15 UTC, josericardo-fo commented on src/locales/pt_BR/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
```suggestion
  "disguiseAvoidedDamage" : "O disfarce de {{pokemonName}} foi descoberto!",
```

2024-06-29 05:26 UTC, torranx requested changes

2024-06-29 05:26 UTC, torranx commented on src/data/ability.ts
> +      pokemon.damageAndUpdate(Math.floor(pokemon.getMaxHp() / 8), HitResult.OTHER);
do we need to manually call the damageAndUpdate() here? wont setting the multiplier enough?

2024-06-29 05:26 UTC, torranx commented on src/data/ability.ts
> -      .bypassFaint()
why was this removed?

2024-06-29 05:26 UTC, torranx commented on src/data/ability.ts
> +      .attr(DisguiseBlockDamageAbAttr, (target, user, move) => (move.category === MoveCategory.PHYSICAL || move.category === MoveCategory.SPECIAL) && !!target.getTag(BattlerTagType.DISGUISE) && targe
do we need explicit check for the move category and attack effectiveness?

2024-06-29 05:26 UTC, torranx commented on src/data/pokemon-forms.ts
> +    return "Its disguise served it as a decoy!";
I dont think this will be the appropriate message if it reverts on arena reset

2024-06-29 05:26 UTC, torranx commented on src/test/abilities/disguise.test.ts
can probably move disguiseDamage variable here

2024-06-29 12:15 UTC, Arxxer reviewed
es-es localization

2024-06-29 12:15 UTC, Arxxer commented on src/locales/es/ability-trigger.ts
>    "quickDraw": "{{pokemonName}} can act faster than normal, thanks to its Quick Draw!",
```suggestion
  "trace": "¡{{pokemonName}} ha copiado la habilidad {{abilityName}} \nde {{targetName}}!",
  "windPowerCharged": "¡{{pokemonName}} se ha cargado de electricidad gracias a {{moveName}}!",
  "quickDraw": "¡{{pokemonName}} ataca primero gracias a la habilidad Mano Rápida!",
```

2024-06-29 21:16 UTC, DayKev commented on src/data/ability.ts
> +      pokemon.damageAndUpdate(Math.floor(pokemon.getMaxHp() / 8), HitResult.OTHER);
Disguise damages the Pokémon that has it by 1/8 of its max HP when broken, but the damage comes from the Disguise ability and not the attacking Pokémon.

2024-06-29 21:28 UTC, DayKev commented on src/data/ability.ts
> +      .attr(DisguiseBlockDamageAbAttr, (target, user, move) => (move.category === MoveCategory.PHYSICAL || move.category === MoveCategory.SPECIAL) && !!target.getTag(BattlerTagType.DISGUISE) && targe
Ah true, the category check is probably not needed, I'll take it out. The type effectiveness check is though otherwise the disguise breaks even when a move doesn't do damage due to the user being immune (ie: Mimikyu is attacked with Tackle, without the check the disguise breaks even though Ghosts are immune to Normal attacks, but with the check the disguise doesn't break as intended).

2024-06-29 21:29 UTC, DayKev commented on src/data/ability.ts
> -      .bypassFaint()
I don't think there's a scenario where Disguise should trigger after the user faints.

2024-06-29 21:32 UTC, DayKev commented on src/data/pokemon-forms.ts
> +    return "Its disguise served it as a decoy!";
This doesn't trigger on reversion, only when the disguise breaks. When it's reset the `isRevert` check above applies as normal.

> [When this effect activates, the message, "Its disguise served it as a decoy!" is displayed](https://bulbapedia.bulbagarden.net/wiki/Disguise_(Ability))

2024-06-29 21:39 UTC, DayKev commented on src/test/abilities/disguise.test.ts
The problem is it needs to be calculated from the Mimikyu's current max HP, so we need it to exist when we define the `disguiseDamage` variable.

2024-06-30 06:44 UTC, torranx commented on src/test/abilities/disguise.test.ts
right, missed that

2024-06-30 06:50 UTC, torranx commented on src/data/ability.ts
> +      pokemon.damageAndUpdate(Math.floor(pokemon.getMaxHp() / 8), HitResult.OTHER);
i understand but wont setting `(args[0] as Utils.NumberHolder).value` to `pokemon.getMaxHp() / 8` not enough? pokemon variable here is mimikyu no?

2024-07-02 00:26 UTC, sodaMelon commented on src/locales/ko/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
```suggestion
  "disguiseAvoidedDamage" : "{{pokemonName}}의 정체가 드러났다!",
```

ref : 8th Pokemon SWSH Korean version script

2024-07-02 10:35 UTC, DayKev commented on src/data/ability.ts
> +      pokemon.damageAndUpdate(Math.floor(pokemon.getMaxHp() / 8), HitResult.OTHER);
This causes the opposing Pokémon to remain considered the source of the damage, which is not correct. For example, if a Disguise Pokémon was hit with a recoil move like Flare Blitz, the attacker would take recoil damage when they should not.

> If a recoil move (e.g. Flare Blitz) is used on Disguise, the Pokemon using Flare Blitz takes no recoil damage.

- https://www.smogon.com/forums/threads/pokemon-sun-moon-battle-mechanics-research.3586701/page-44

2024-07-07 17:53 UTC, NicusPulcis commented
Italy has been added @DayKev

2024-07-10 18:30 UTC, DayKev commented
> Italy has been added @DayKev

It doesn't seem to be showing up, possibly due to the branch change. Since this PR was effectively merged now via the beta version, I think you'll need to make a new standalone PR to add the Italian translation.

2024-07-10 21:14 UTC, DayKev commented
Apparently all the previous beta stuff was un-happened.

2024-07-10 22:17 UTC, NicusPulcis commented
@DayKev i'll make a separate PR dw : )

2024-07-18 06:33 UTC, flx-sta commented on src/locales/de/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
```suggestion
  "disguiseAvoidedDamage" : "Die Tarnung von {{pokemonName}} is aufgeflogen!",
```
[source 15:22](https://youtu.be/xlt7QtypSqI?si=ZVRASsn9sKuIVQLQ)

2024-07-18 06:41 UTC, CodeTappert commented on src/locales/de/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
```
Die Tarnung von {{pokemonName}} ist aufgeflogen!
```

2024-07-18 06:42 UTC, CodeTappert commented on src/locales/de/ability-trigger.ts
> +  "disguiseAvoidedDamage" : "{{pokemonName}}'s disguise was busted!",
(you are missing a t in ist)

2024-07-18 07:54 UTC, Adri1 reviewed
Added french

2024-07-21 22:27 UTC, NicusPulcis commented
@DayKev hey man i've sent a PR for the italian localization, i formatted the file so that the line would be in 13 as the other translators did, that way it should be as the english translation -> hopefully it works! :)

2024-07-27 12:04 UTC, DayKev commented
I'm hoping to reuse much of the Ice Face code rather than just duplicate it, lmk which you prefer @Tempo-anon (this PR version or the linked version below).
Relevant sections [here](https://github.com/DayKev/pokerogue/blob/f5d06e832ccb03f6be4c9570e49dcb30fccf63f0/src/data/ability.ts#L3810-L3860) + [here](https://github.com/DayKev/pokerogue/blob/f5d06e832ccb03f6be4c9570e49dcb30fccf63f0/src/data/ability.ts#L4779) for `src/data/ability.ts` and [here](https://github.com/DayKev/pokerogue/blob/f5d06e832ccb03f6be4c9570e49dcb30fccf63f0/src/data/battler-tags.ts#L1544-L1596) for `src/data/battler-tags.ts`.

2024-07-30 05:59 UTC, DayKev commented
I don't know why that random typo fix commit is here... but it shouldn't actually matter, since it was only editing comment text and the PR seems to show that it won't actually do anything anyway.

2024-07-30 06:31 UTC, torranx reviewed
I don't particularly like how we're using if conditions to separate the logic of Ice Face and Disguise abilities instead of using 2 separate classes. But I would leave it to the other devs to decide.

2024-07-30 06:31 UTC, torranx commented on src/data/ability.ts
> +   * @param {boolean} passive Whether the ability is passive.
apparently we need to use `n/a` for unused params

2024-07-30 06:31 UTC, torranx commented on src/data/ability.ts
> +    this.takesDamage = takesDamage;
I was thinking of a `damage: number` param so that it is will not be included in the class but I guess this could work

2024-07-30 08:57 UTC, DayKev commented on src/data/ability.ts
> +    this.takesDamage = takesDamage;
So have a `recoilDamage: (pokemon) => number` param and change `pokemon.damageAndUpdate(Math.floor(pokemon.getMaxHp() / 8), HitResult.OTHER);` to `pokemon.damageAndUpdate(recoilDamage(pokemon), HitResult.OTHER);` (and then put `(pokemon) => Math.floor(pokemon.getMaxHp() / 8)` in the move definition)?

2024-07-30 14:16 UTC, CodeTappert commented
> I don't particularly like how we're using if conditions to separate the logic of Ice Face and Disguise abilities instead of using 2 separate classes. But I would leave it to the other devs to decide.

agree

2024-07-30 14:35 UTC, ben-lear commented on src/battle-scene.ts
> +          // Only trigger form change when Eiscue is in Noice form (or Mimikyu is in Busted form)
Can we move the logic for these special form changes somewhere else, like to the pokemon object? Battle scene should not be responsible for managing form changes on Pokemon other than triggering the check itself.

2024-07-30 14:42 UTC, ben-lear commented on src/data/ability.ts
> +    this.tagType = tagType;
Can we be more descriptive with the var name for tagType? It is rather generic atm but I don’t think it broadly applies to all tag types atm, correct? Just a few special ones.

2024-07-31 03:36 UTC, DayKev commented
> > I don't particularly like how we're using if conditions to separate the logic of Ice Face and Disguise abilities instead of using 2 separate classes. But I would leave it to the other devs to decide.
> 
> agree

I'm not sure I see how hardcoding single-use abattrs is better than mostly reusing an abattr for 2 abilities that are nearly identical.

2024-08-01 06:53 UTC, DayKev commented on src/data/ability.ts
> +    this.tagType = tagType;
I guess I could change it to `battlerTagType`? Current convention everywhere else is to just use `tagType` and use the type hint and/or context to figure out what type of tag it's referring to though.

2024-08-04 03:33 UTC, Snailman11 commented
Link to the Discord bug report (Mimikyu Disguise Ability resets after switching out)
https://discord.com/channels/1125469663833370665/1267306283275386912

2024-08-04 13:13 UTC, torranx commented on src/battle-scene.ts
> -
I noticed this is updated to be an attr instead, but the hard check for the species is not there- this will break the game if Eiscue/Mimikyu is somehow fusioned

2024-08-04 13:38 UTC, DayKev commented on src/battle-scene.ts
> -
I checked with Mimikyu being both the primary and the secondary in a fusion and there was no crash. There also shouldn't be any way to give a Pokémon Disguise with Skill Swap etc, afaik.
```ts
      .attr(UncopiableAbilityAbAttr)
      .attr(UnswappableAbilityAbAttr)
      .attr(UnsuppressableAbilityAbAttr)
      .attr(NoTransformAbilityAbAttr)
      .attr(NoFusionAbilityAbAttr)
```

2024-08-04 13:51 UTC, torranx commented on src/battle-scene.ts
> -
I see, did you test for Eiscue too?

2024-08-04 14:22 UTC, DayKev commented on src/battle-scene.ts
> -
Not for this scenario, but it has the same 5 `AbAttr`s attached to it so it should work exactly the same.

2024-08-06 18:30 UTC, Adri1 commented on src/locales/fr/pokemon-form.ts
> +  "disguiseChange": "Its disguise served it as a decoy!",
```suggestion
  "disguiseChange": "Le déguisement absorbe l’attaque !",
```

2024-08-06 22:11 UTC, josericardo-fo commented on src/locales/pt_BR/pokemon-form.ts
> +  "disguiseChange": "Its disguise served it as a decoy!",
```suggestion
  "disguiseChange": "O seu disfarce serviu-lhe de isca!",
```

2024-08-06 23:27 UTC, sonnyding1 reviewed
Added zh_CN and zh_TW translations

2024-08-06 23:27 UTC, sonnyding1 commented on src/locales/zh_CN/pokemon-form.ts
> +  "disguiseChange": "Its disguise served it as a decoy!",
```suggestion
  "disguiseChange": "它的画皮被当作诱饵使用了！",
```

2024-08-06 23:27 UTC, sonnyding1 commented on src/locales/zh_TW/pokemon-form.ts
> +  "disguiseChange": "Its disguise served it as a decoy!",
```suggestion
  "disguiseChange": "它的畫皮被當作誘餌使用了！",
```

2024-08-07 02:36 UTC, returntoice commented on src/locales/ko/pokemon-form.ts
> +  "disguiseChange": "Its disguise served it as a decoy!",
```suggestion
  "disguiseChange": "탈이 대타가 되었다!",
```

2024-08-07 04:56 UTC, EnochG1 commented
@DayKev 
From now Japanese is added in beta.
Please merge latest beta and add Japanese locale files 🙏

2024-08-08 00:09 UTC, returntoice approved these changes

2024-08-11 06:56 UTC, innerthunder commented on src/data/ability.ts
> +      .attr(FormBlockDamageAbAttr, (target, user, move) => !!target.getTag(BattlerTagType.DISGUISE) && target.getAttackTypeEffectiveness(move.type, user) > 0, 0, BattlerTagType.DISGUISE,
Does this account for moves/abilities with variable type (Aerilate, Weather Ball, etc.)?

2024-08-11 06:56 UTC, innerthunder commented on src/data/battler-tags.ts
> +  constructor(tagType: BattlerTagType, sourceMove: Moves) {
Why is `sourceMove` a param here?

2024-08-11 08:11 UTC, DayKev commented on src/data/battler-tags.ts
> +  constructor(tagType: BattlerTagType, sourceMove: Moves) {
It doesn't seem to be used for anything, at least not at this point. Probably just due to copy/pasting when the Ice Face ability was made. Removed.

2024-08-11 08:32 UTC, DayKev commented on src/data/ability.ts
> +      .attr(FormBlockDamageAbAttr, (target, user, move) => !!target.getTag(BattlerTagType.DISGUISE) && target.getAttackTypeEffectiveness(move.type, user) > 0, 0, BattlerTagType.DISGUISE,
Just checked and it does, Aerialate Quick Attack was able to hit Mimikyu and break the Disguise.

2024-08-11 10:29 UTC, innerthunder commented on src/data/battler-tags.ts
> +export class FormBlockDamageTag extends BattlerTag {
I feel like in general this would be cleaner if there were two classes (say, `DisguiseBlockDamageTag` and `IceFaceBlockDamageTag`) that extended this and each had their own `canAdd` functions. It'd be consistent with how #2051 handles different disabling effects.

2024-08-11 15:05 UTC, NicusPulcis commented
@DayKev just checked to make sure italian localization was ok (it is)

2024-08-11 18:42 UTC, DayKev commented on src/data/battler-tags.ts
> +export class FormBlockDamageTag extends BattlerTag {
How about like this?

2024-08-11 18:59 UTC, innerthunder commented on src/data/battler-tags.ts
>      return false;
```suggestion
    return pokemon.formIndex === 0;
```

2024-08-11 19:00 UTC, innerthunder commented on src/data/battler-tags.ts
> +    return false;
```suggestion
    return super.canAdd(pokemon) || isWeatherSnowOrHail
```

2024-08-11 20:23 UTC, innerthunder approved these changes
lgtm 🚀

2024-08-11 20:34 UTC, torranx approved these changes
thanks for the update, lgtm

2024-08-12 10:52 UTC, merged