[Bug] Making FormChangeItems Untransferrable
pagefaultgames/pokerogue pull request #2695
Opened 2024-06-28 22:40 UTC by Arxalc

## What are the changes?

Makes form change items untransferrable.
## Why am I doing these changes?

closes #208 by preventing this scenario.
## What did change?

getTransferrable() really should have been an instance variable instead. The parameter was obselete and was used incorrectly.
### Screenshots/Videos

This G-Max Pikachu is holding a Max Mushroom, but it's no longer giving you the option to transfer it.
![Screenshot (7)](https://github.com/pagefaultgames/pokerogue/assets/63990624/e63bb2eb-bc30-49f5-8388-824c20ee4a44)

## How to test the changes?

Give yourself a form change item. Observe how you can no longer transfer it to other pokemon.
## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-07-02 18:45 UTC, OrangeRed requested changes

2024-07-02 18:45 UTC, OrangeRed commented on src/phases.ts
> +                    && (m as PokemonHeldItemModifier).isTransferrable && (m as PokemonHeldItemModifier).pokemonId === party[fromSlotIndex].id) as PokemonHeldItemModifier[];
Can you remove the inner `as PokemonHeldItemModifier` everwhere its not needed? 
typescript will infer the type from the `instanceof` that came right before so there is no reason to explicitly type cast with `as`

2024-07-02 18:45 UTC, OrangeRed commented on src/data/move.ts
> +    const heldBerries = this.getTargetHeldBerries(target);
Why did you remove this filter?

2024-07-02 18:45 UTC, OrangeRed commented on src/modifier/modifier.ts
> +  public isTransferrable: boolean = true;
Is being able to change this class property desirable? If not then change it to be readonly or the following if you want to make it readonly only outside the class
```ts
private _isTransferrable

get isTransferrable() { return this._isTransferrable }
```

2024-07-02 23:18 UTC, OrangeRed commented on src/phases.ts
> +                    && (m as PokemonHeldItemModifier).isTransferrable && (m as PokemonHeldItemModifier).pokemonId === party[fromSlotIndex].id) as PokemonHeldItemModifier[];
Can you do this everywhere not just in this one specific place

2024-07-02 23:19 UTC, OrangeRed commented
> Can you remove the inner `as PokemonHeldItemModifier` everwhere its not needed? typescript will infer the type from the `instanceof` that came right before so there is no reason to explicitly type cast with `as`

Can you do this everywhere you made changes not just in the one place that I mentioned.

2024-07-02 23:32 UTC, Arxalc commented
> > Can you remove the inner `as PokemonHeldItemModifier` everwhere its not needed? typescript will infer the type from the `instanceof` that came right before so there is no reason to explicitly type cast with `as`
> 
> Can you do this everywhere you made changes not just in the one place that I mentioned.

Would that not be better as a separate PR?

2024-07-02 23:37 UTC, OrangeRed commented
I would say a small typescript change like this, that simply removes unnecessary type casts in places that you've touched, doesn't necessarily need to be its own PR.

2024-07-03 01:58 UTC, OrangeRed approved these changes

2024-07-13 18:09 UTC, merged