[Enhancement] Add Move Header phase and attributes
pagefaultgames/pokerogue pull request #2716
Opened 2024-06-29 23:29 UTC by innerthunder

## What are the changes?

This adds a new phase, `MoveHeaderPhase`, which takes place before all moves in a turn and applies all the `MoveHeaderAttr` attributes of a move.

## Why am I doing these changes?

At the moment, this acts as a partial fix to [Focus Punch missing its on-cart messages](#898 ), but the overall intent is to create a framework so that Beak Blast and Shell Trap can be implemented (or reimplemented) in a more structured and intuitive way.

## What did change?

- `phases`: A new 'MoveHeaderPhase' is added and integrated into the game's turn sequence. With this new phase, the generic turn sequence (after all commands are selected) is as follows:
  1. If the player chooses to throw a ball, switch a Pokemon, or run away, those actions are resolved first.
  2. For each Pokemon that uses a move with a `MoveHeaderAttr`, a `MoveHeaderPhase` is added to the turn sequence. This phase applies all of the move's `MoveHeaderAttrs`, as long as the move itself can be used. If the user has a status that may block the use of the move, the status check is done here instead of in the `MovePhase`. `MoveHeaderPhases` are resolved in the same order as the turn's move order.
  3. `MovePhases` are added to the turn sequence for each move. If the user's status was previously checked in a `MoveHeaderPhase`, the status check here is ignored. Otherwise, this phase and all subsequent phases function in the same way as on upstream.
- `data/move`: `MoveHeaderAttr` is a new subclass of `MoveAttr` that encompasses all attributes that are applied in the `MoveHeaderPhase`. For now, the only `MoveHeaderAttr` implemented is `MessageHeaderAttr`, which queues a message, but more subclasses of `MoveHeaderAttr` can be created in the future to apply more effects, e.g. adding a battler tag to the user.
  - Focus Punch now uses a `MessageHeaderAttr` to show its initial message.
- `test/moves/focus_punch.test`: New unit test to ensure Focus Punch's effect timing is correct throughout the turn sequence

### Screenshots/Videos

Basic Example showing Focus Punch's new pre-move message:

https://github.com/pagefaultgames/pokerogue/assets/168692175/ca49eda0-341d-4269-9c5d-f7baf689fb26

## How to test the changes?

1. `npm run test focus_punch` (**Some turn sequence tests are WIP**)
2. Use `src/overrides` to give the player Pokemon Focus Punch, then use `npm run start:dev` and observe the turn sequence in battle when using the move:
  1. What happens when using Focus Punch compared to other moves?
  2. What happens when one player Pokemon switches, and the other uses Focus Punch?
  3. What happens when one player Pokemon throws a ball or runs, and the other uses Focus Punch?

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-06-30 04:41 UTC, innerthunder commented
### Update + Test Video

When a Pokemon's turn command is skipped (e.g. after the player chooses to run or throw a ball), and Focus Punch was selected for that Pokemon, that Pokemon's `MoveHeaderPhase` is now also removed from the turn sequence. This means that if a player Pokemon using Focus Punch is skipped, the player should not see any effects from the move throughout the turn.

**Test Video:** Shows two other possible move sequences:
- One player Pokemon tries to run (and fails), while the other uses Focus Punch. In this case, Focus Punch is skipped, and there's no visible indication that the move was used.
- One player Pokemon uses Focus Punch, then the other player Pokemon attacks its ally with Tackle. This is meant to show the sequence of Focus Punch's effects if the move fails.

https://github.com/pagefaultgames/pokerogue/assets/168692175/d7524fdf-c990-43fc-836e-372fc4bfc022

2024-07-18 22:13 UTC, mcmontag commented on src/phases.ts
> +          }
[Beak Blast](https://bulbapedia.bulbagarden.net/wiki/Beak_Blast_(move))
>The charging phase occurs whether or not the user's status would prevent it from executing Beak Blast. For example, if the user is confused, the confusion check is performed before the strike, not the initial charge.

I know this is for Focus Punch, but I'm not sure that resolving non-volatile statuses during the charging phase is correct in either case.

2024-07-18 22:20 UTC, innerthunder commented on src/phases.ts
> +          }
I wasn't sure how it worked in mainline; it just seemed weird for the added messages to pop up even when statuses prevent the move from being used.

If that's how it's meant to work, though, that definitely simplifies things.

2024-07-19 05:56 UTC, innerthunder commented on src/phases.ts
> +          }
Just tested on Showdown, and I can confirm that non-volatile statuses only resolve when Focus Punch is actually used, and the pre-move message is shown regardless of the user's status. No preemptive status check needed!

2024-07-19 12:16 UTC, mcmontag commented on src/phases.ts
> +          }
Solid!  I really wasn't sure, haven't played a mainline game since gen 4 haha.

I think your battler tag idea is a good one, and I definitely think charge moves need reworked.

My instinct is to have a `ChargedAttackMove` class subclassing `AttackMove`, with a `charge` method (delegating to a constructor param) and a `chargePriority`.  `charge` would add a volatile status and display a message, and `apply` would check for it before execution as a condition (or in Focus Punch's case, it could flinch the holder immediately if they're hit with an attack).

`TurnStartPhase` would treat `ChargedAttackMove` as a special case, and handle it as two separate actions to order.

Totally spitballing...thoughts?

2024-07-19 12:23 UTC, mcmontag commented on src/phases.ts
> +    this.queueMoveHeaders(moveOrder);
Why not filter `moveOrder` to exclude skipped commands first?  Would save you from having to remove any move headers this queues.

2024-07-19 18:45 UTC, innerthunder commented on src/phases.ts
> +    this.queueMoveHeaders(moveOrder);
Fixed with https://github.com/pagefaultgames/pokerogue/pull/2716/commits/c3dd186938ba245cdae8fb081282920316669afd

2024-07-23 11:58 UTC, EnochG1 requested changes

2024-07-23 11:58 UTC, EnochG1 commented on src/data/move.ts
> +      .attr(MessageHeaderAttr, (user, move) => getPokemonMessage(user, " is tightening its focus!"))
I think this message should be localize.

2024-07-24 00:39 UTC, innerthunder commented on src/data/move.ts
> +      .attr(MessageHeaderAttr, (user, move) => getPokemonMessage(user, " is tightening its focus!"))
There isn't a file for move trigger messages like this one in the locales atm. Should localization for this wait until those files are added?

2024-07-24 01:48 UTC, EnochG1 commented on src/data/move.ts
> +      .attr(MessageHeaderAttr, (user, move) => getPokemonMessage(user, " is tightening its focus!"))
IMO, if `getPokemonMessage(user, " is tightening its focus!")` can be displayed by queueMessage, it should be localized.
You can refer https://github.com/pagefaultgames/pokerogue/pull/3034/files#diff-62e9cf38a6ba2a2b69a102788cdfef2a33cdc173f79124df114636685a51e762R5808

2024-08-02 08:37 UTC, innerthunder commented on src/data/move.ts
> +      .attr(MessageHeaderAttr, (user, move) => getPokemonMessage(user, " is tightening its focus!"))
Just added a key for this message

2024-08-02 08:40 UTC, EnochG1 commented on src/data/move.ts
> +      .attr(MessageHeaderAttr, (user, move) => getPokemonMessage(user, " is tightening its focus!"))
Thanks!

2024-08-02 08:40 UTC, EnochG1 approved these changes

2024-08-03 19:19 UTC, snoozbuster commented
This is also useful for pursuit, I think - or at least, it's useful for the implementation of pursuit I have been working on. love this

2024-08-03 22:54 UTC, josericardo-fo commented on src/locales/pt_BR/move-trigger.ts
> +  "isTighteningFocus": "{{pokemonName}} is\ntightening its focus!",
```suggestion
  "isTighteningFocus": "{{pokemonName}} está\naumentando seu foco!",
```

2024-08-03 22:55 UTC, Adri1 reviewed
Added French

2024-08-03 22:55 UTC, Adri1 commented on src/locales/fr/move-trigger.ts
> +  "isTighteningFocus": "{{pokemonName}} is\ntightening its focus!",
```suggestion
  "isTighteningFocus": "{{pokemonName}} se concentre\nau maximum !",
```

2024-08-03 23:16 UTC, EnochG1 reviewed
Korean Translation

2024-08-03 23:16 UTC, EnochG1 commented on src/locales/ko/move-trigger.ts
> +  "isTighteningFocus": "{{pokemonName}} is\ntightening its focus!",
```suggestion
  "isTighteningFocus": "{{pokemonName}}[[는]]\n집중력을 높이고 있다!",
```

2024-08-04 03:50 UTC, sonnyding1 reviewed
Added zh_CN and zh_TW translations

2024-08-04 03:50 UTC, sonnyding1 commented on src/locales/zh_CN/move-trigger.ts
> +  "isTighteningFocus": "{{pokemonName}} is\ntightening its focus!",
```suggestion
  "isTighteningFocus": "{{pokemonName}}正在集中注意力！",
```

2024-08-04 03:50 UTC, sonnyding1 commented on src/locales/zh_TW/move-trigger.ts
> +  "isTighteningFocus": "{{pokemonName}} is\ntightening its focus!",
```suggestion
  "isTighteningFocus": "{{pokemonName}}正在集中注意力！",
```

2024-08-04 06:08 UTC, CodeTappert commented on src/locales/de/move-trigger.ts
> +  "isTighteningFocus": "{{pokemonName}} is\ntightening its focus!",
```suggestion
  "isTighteningFocus": "{{pokemonName}} konzentriert sich!",
```

2024-08-04 08:42 UTC, EnochG1 reviewed
Italian translation by @NicusPulcis

2024-08-04 08:42 UTC, EnochG1 commented on src/locales/it/move-trigger.ts
> +  "isTighteningFocus": "{{pokemonName}} is\ntightening its focus!",
```suggestion
  "isTighteningFocus": "{{pokemonName}} si concentra al massimo!",
```

2024-08-06 03:10 UTC, snoozbuster commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean | Promise<boolean> {
technically I don't think you really need to override this. the implementation is exactly the same as in the base class. could be some reason to that I'm not aware of though

2024-08-06 03:11 UTC, snoozbuster commented on src/data/move.ts
> +      ? this.message as string
does typescript get angry without the cast? I would have thought that the typeof would be enough to convince it that this branch is a string, without the need to cast.

2024-08-06 03:15 UTC, snoozbuster commented on src/phases.ts
> +    return this.pokemon.isActive(true) && this.move.isUsable(this.pokemon, true);
strictly speaking - is it correct to ignore PP here on `this.move.isUsable`? I don't know how exactly you would manage to reduce PP between the time that the move was queued and the time that the move header phase runs - but suppose that you were out of PP somehow when the MoveHeaderPhase ran, it would still show the "tightening focus" message even though the move itself will fail, right? is there any gotcha I'm not thinking of with setting this to `false`?

2024-08-06 03:18 UTC, snoozbuster commented on src/test/moves/focus_punch.test.ts
> +describe("Moves - Focus Punch", () => {
some other tests that might be worth adding, if you can figure out a good way to assert them:

- if the enemy queues a switch while you focus punch, the correct order for things to happen in is switch -> focus message -> focus punch
- maybe assert that if you use focus punch on both pokemon in doubles, the messages happen for each pokemon in speed order? (no idea if that's how it is on cart, but I assume so)
- is it possible to disable focus punch between tightening focus and the attack? is that special in some way that's worth testing?
- and if you want, a test for the weird PP edge case I mentioned above (especially if you can come up with a good way to have it actually happen in practice)

2024-08-06 03:20 UTC, snoozbuster approved these changes
minor cleanliness comments, nothing I would consider a blocker. I've been using this in a PR I've been working on and it seems to be working great for my use case there. tests are well-written (in my inexperienced-with-this-repo-opinion, anyway - they at least seem to succeed in accurately testing the behaviors they claim to test)

2024-08-06 03:32 UTC, innerthunder commented on src/phases.ts
> +    return this.pokemon.isActive(true) && this.move.isUsable(this.pokemon, true);
Good catch. I've been planning on adding an option to delay move headers (i.e. push them instead of unshift them in `TurnStartPhase`) for Chilly Reception's pre-move message. I don't think it matters atm, but having this check ignore PP in that case wouldn't be good.

2024-08-06 03:32 UTC, innerthunder commented on src/data/move.ts
> +      ? this.message as string
Yeah, the cast was redundant. Changing it with the next commit

2024-08-06 03:33 UTC, innerthunder commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean | Promise<boolean> {
Removed on next commit

2024-08-06 03:53 UTC, frutescens commented
lgtm! 

Do you think this can be applied in the case of the status move Quash and other priority breaking moves? (The affected Pokemon's move is moved to the end of the turn order)  https://archives.bulbagarden.net/media/upload/7/7a/Quash_V.png

2024-08-06 03:59 UTC, innerthunder commented
> lgtm!
> 
> Do you think this can be applied in the case of the status move Quash and other priority breaking moves? (The affected Pokemon's move is moved to the end of the turn order) https://archives.bulbagarden.net/media/upload/7/7a/Quash_V.png

You'd have to manipulate the phase queue some other way, I think. The main use case for these is for effects whose order in the turn sequence can be resolved at the start of the turn.

2024-08-06 04:02 UTC, frutescens commented
Video of Test: 
https://github.com/user-attachments/assets/3336f626-3de1-456b-93f7-67a5223d51c0

2024-08-06 04:45 UTC, innerthunder commented on src/test/moves/focus_punch.test.ts
> +describe("Moves - Focus Punch", () => {
- Added a test for the first case
- The second case was too difficult to implement under the current framework. I kept running into issues when trying to await the `MoveHeaderPhase` with the phase interceptor. I think since `MoveHeaderPhase` has such a short runtime, it completes before `game.phaseInterceptor` has a chance to catch it.
- The third case here is too similar to the "mid-turn sleep" test, imo.
- I also removed `ignorePP` from the call to `isUsable` in `MoveHeaderPhase`, so the last case no longer applies.

2024-08-06 17:52 UTC, snoozbuster commented on src/test/moves/focus_punch.test.ts
> +      expect(game.scene.getCurrentPhase() instanceof SwitchSummonPhase).toBeTruthy();
you might also want to assert that there are no instances of `"MoveHeaderPhase"` in `game.phaseInterceptor.log`, just to be double sure that the switch happened before the move header phase. as it stands, I don't think this test would have failed in my branch where I temporarily accidentally broke this behavior and swapped the header and switch phases.

2024-08-06 19:09 UTC, innerthunder commented on src/test/moves/focus_punch.test.ts
> +      expect(game.scene.getCurrentPhase() instanceof SwitchSummonPhase).toBeTruthy();
I made it check that a `MoveHeaderPhase` exists in `game.scene.phaseQueue` instead. `game.phaseInterceptor.log` is challenging to use since TS reads it as `any`.

2024-08-07 02:42 UTC, snoozbuster commented on src/test/moves/focus_punch.test.ts
> +      expect(game.scene.getCurrentPhase() instanceof SwitchSummonPhase).toBeTruthy();
I think I fixed the type in a different PR that hasn't merged yet, but the type of it is just `string[]` - just a list of phase names

2024-08-07 02:42 UTC, snoozbuster commented on src/test/moves/focus_punch.test.ts
> +      expect(game.scene.getCurrentPhase() instanceof SwitchSummonPhase).toBeTruthy();
but yeah - that assertion also works fine

2024-08-07 02:55 UTC, snoozbuster approved these changes

2024-08-07 18:27 UTC, snoozbuster approved these changes

2024-08-07 18:29 UTC, snoozbuster approved these changes

2024-08-07 18:32 UTC, merged