[Localization] Update French dialogues + typos
pagefaultgames/pokerogue pull request #2724
Opened 2024-06-30 12:28 UTC by Adri1

## What are the changes?
New batch of French translations + typos corrections

## Why am I doing these changes?
To expand French translations and correct typos

## What did change?
New texts in French and typos corrections

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?

2024-06-30 12:41 UTC, Dakurei requested changes
Fix typos

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      1: "J’ai tébuché !",
```suggestion
      1: "J’ai trébuché !",
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      1: "Les Pokémon ne tahissent jamais. Ils te rendront toujours l’amour que tu leur donne.",
```suggestion
      1: "Les Pokémon ne trahissent jamais. Ils te rendront toujours l’amour que tu leur donne.",
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      2: "Comment ça a pu arrver…\nAvec quoi nourris-tu tes Pokémon ?",
```suggestion
      2: "Comment ça a pu arriver…\nAvec quoi nourris-tu tes Pokémon ?",
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      4: "Hé ! Attends un seconde…\nTu saurais pas qui je suis ?"
```suggestion
      4: "Hé ! Attends une seconde…\nTu saurais pas qui je suis ?"
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      2: "Tes Pokémon… Monte-les-moi…",
```suggestion
      2: "Tes Pokémon… Montre-les-moi…",
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      3: "Et moi qui pensais qu’en grandissant, j’allais rester frêle et fragile, à me se briser à la moindre étreinte.",
```suggestion
      3: "Et moi qui pensais qu’en grandissant, j’allais rester frêle et fragile, à me briser à la moindre étreinte.",
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      1: "Les Pokémon ne tahissent jamais. Ils te rendront toujours l’amour que tu leur donne.",
```suggestion
      1: "Les Pokémon ne trahissent jamais. Ils te rendront toujours l’amour que tu leur donne.",
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      2: "Comment ça a pu arrver…\nAvec quoi nourris-tu tes Pokémon ?",
```suggestion
      2: "Comment ça a pu arriver…\nAvec quoi nourris-tu tes Pokémon ?",
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      1: "J’ai tébuché !",
```suggestion
      1: "J’ai trébuché !",
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      4: "Hé ! Attends un seconde…\nTu saurais pas qui je suis ?"
```suggestion
      4: "Hé ! Attends une seconde…\nTu saurais pas qui je suis ?"
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      2: "Tes Pokémon… Monte-les-moi…",
```suggestion
      2: "Tes Pokémon… Montre-les-moi…",
```

2024-06-30 12:41 UTC, Dakurei commented on src/locales/fr/dialogue.ts
> +      3: "Et moi qui pensais qu’en grandissant, j’allais rester frêle et fragile, à me se briser à la moindre étreinte.",
```suggestion
      3: "Et moi qui pensais qu’en grandissant, j’allais rester frêle et fragile, à me briser à la moindre étreinte.",
```

2024-06-30 13:54 UTC, Adri1 commented
> Did you make sure for all of them that they are displayed correctly? And not like cut off because they are too long

I have a scale for this, so unless it's broken it should be okay

2024-07-04 20:38 UTC, Tempo-anon approved these changes

2024-07-04 20:38 UTC, merged