[Qol] Add an option to import settings
pagefaultgames/pokerogue pull request #2729
Opened 2024-06-30 20:12 UTC by prateau

## What are the changes?
Added an option in the manage data menu to import and export settings

## Why am I doing these changes?
I oftenly clear the cookies of my browser and so I often have to re-enter all my settings manually. This is not fun.

Maybe this could be extended in the future to key mapping settings

## What did change?
I added two entries in the manage data menu to import and export the settings.

As I'm native in french but not in the other languages, I only added translation for english and french. Let me know if I need to translate the menu entries in the other language (with google translate)

### Screenshots/Videos
https://github.com/pagefaultgames/pokerogue/assets/56865723/9d36bc7f-d1f8-44d3-80ff-c3fd19c2e61b

## How to test the changes?
This can be tested by exporting and importing settings with the new option menu.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-07-01 13:49 UTC, Adri1 requested changes

2024-07-01 13:49 UTC, Adri1 commented on src/locales/fr/menu-ui-handler.ts
> +  "exportSettings": "Exporter paramètres",
Don't forget to also add these lines to all other languages local files
You can put them in English, tranalsation teams will do thier work once you added them

2024-07-01 21:03 UTC, prateau commented on src/locales/fr/menu-ui-handler.ts
> +  "exportSettings": "Exporter paramètres",
Ok I didn't knew this. It's done

2024-07-01 21:07 UTC, Adri1 submitted a review, later dismissed

2024-07-01 21:07 UTC, josericardo-fo commented on src/locales/pt_BR/menu-ui-handler.ts
> +  "exportSettings": "Export Settings",
```suggestion
  "importSettings": "Importar configurações",
  "exportSettings": "Exportar configurações",
```

2024-07-01 21:07 UTC, CodeTappert commented on src/locales/de/menu-ui-handler.ts
> +  "exportSettings": "Export Settings",
```suggestion
  "importSettings": "Einstellungen importieren",
  "exportSettings": "Einstellungen exportieren",
```

2024-07-01 21:15 UTC, Arxxer reviewed
ES localization done

2024-07-01 23:01 UTC, RimKnight commented on src/locales/zh_TW/menu-ui-handler.ts
> +  "exportSettings": "Export Settings",
```suggestion
  "importSettings": "導入設置",
  "exportSettings": "導出設置",
```

2024-07-02 00:16 UTC, sodaMelon reviewed
good morning
i added Korean localization!

2024-07-02 00:16 UTC, sodaMelon commented on src/locales/ko/menu-ui-handler.ts
> +  "exportSettings": "Export Settings",
```suggestion
  "importSettings": "설정 불러오기",
  "exportSettings": "설정 내보내기",
```

2024-07-02 10:04 UTC, sodaMelon submitted a review, later dismissed

2024-07-02 10:36 UTC, RimKnight approved these changes

2024-07-07 17:57 UTC, NicusPulcis commented
hey @prateau i've added italian

2024-07-07 21:37 UTC, prateau commented
Fixed conflicts

2024-07-07 21:39 UTC, prateau commented
> hey @prateau i've added italian

Hey I'm sorry but I don't see your change anywhere

2024-07-12 14:39 UTC, josericardo-fo submitted a review, later dismissed

2024-07-12 14:58 UTC, NicusPulcis commented
@prateau if you wanna add them yourself there they are:

"Import Settings" -> "Importa impostazioni"
"Export Settings" -> "Esporta impostazioni"

2024-07-23 20:45 UTC, prateau commented
Conflict resolved

2024-09-17 16:48 UTC, flx-sta commented
@prateau   closed for being stale (no updates for over a month)

----

Feel free to create a new PR or ask us to re-open this one.

2024-09-17 16:48 UTC, closed without merging