Add localization for able/not able/learned
pagefaultgames/pokerogue pull request #2730
Opened 2024-06-30 21:09 UTC by hayuna

## What are the changes?
Localization for TM learning

## Why am I doing these changes?
Hardcoded text -> localized text

## What did change?
Added localization (from Google Translate)

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-06-30 21:13 UTC, Dakurei requested changes
Translation mistakes

2024-06-30 21:13 UTC, Dakurei commented on src/locales/fr/party-ui-handler.ts
> +  "NOT_ABLE": "Pas capable",
```suggestion
  "ABLE": "Apte",
  "NOT_ABLE": "Non apte",
```

2024-06-30 21:14 UTC, Dakurei commented
Please never use online translators again in the future, but leave the default English text for native speakers to handle

2024-06-30 21:15 UTC, InnocentGameDev commented
Please do not add the Spanish yourself, always check with translators and we'll take care of it (from the English default).

2024-06-30 21:20 UTC, CodeTappert commented
Never add localized text to languages you dont speak. 
Use english text al placeholder instead

2024-06-30 21:22 UTC, CodeTappert commented
Also i will close this as this text is already in a PR. See https://github.com/pagefaultgames/pokerogue/pull/2566/files

So this is a duplicate

2024-06-30 21:22 UTC, closed without merging

2024-07-01 09:12 UTC, hayuna commented
got it