[Balance] Rework some evolutions
pagefaultgames/pokerogue pull request #2732
Opened 2024-06-30 23:38 UTC by Fontbane

## What are the changes?

- Many item+trade evos use their appropriate item instead of Linking Cord
- Bisharp requires Leader's Crest to evolve (item not fully implemented yet)
- Gligar, Sneasel require Razor Fang, Razor Claw
- Gimmighoul evolves when you have 15k money
- Biome specific evolutions changed to time-based or use an item
- Friendship evolution adjustments to come

## Why am I doing these changes?

- For balance
- Biome evos are restrictive and hard
- Gimmighoul is too easy to evolve
- Bisharp evolves too quickly

## What did change?

- Many evolution methods
- To do: Pause evolutions for any mon at any time. Paused evolutions won't put their evo item in reward pool.

### Screenshots/Videos

## How to test the changes?

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-01 06:47 UTC, CodeTappert commented
Doesnt the razor claw also have a seperate effect for boosting ciritcal hits?

My PR for this change was rejected because i only added it as a evoluton item. See https://github.com/pagefaultgames/pokerogue/pull/1449


So maybe you will have to add them as normal items with their intended effect

2024-07-01 18:43 UTC, Fontbane commented
> Doesnt the razor claw also have a seperate effect for boosting ciritcal hits?
> 
> My PR for this change was rejected because i only added it as a evoluton item. See #1449
> 
> So maybe you will have to add them as normal items with their intended effect

Sure, I could do that separately.

2024-07-01 19:39 UTC, CodeTappert commented on src/ui/party-ui-handler.ts
>            ui.playSelect();
I hate that this has hardcoded text...
Since you are changing this text anyways maybe localize it at this chance?

2024-07-01 19:39 UTC, CodeTappert commented on src/ui/party-ui-handler.ts
> +            optionName = `${pokemon.pauseEvolutions ? "Unpause" : "Pause"} Evolution`;
Definitly no NEW hardcoded text

2024-07-02 02:48 UTC, Fontbane commented on src/ui/party-ui-handler.ts
> +            optionName = `${pokemon.pauseEvolutions ? "Unpause" : "Pause"} Evolution`;
This isn't new, I put it there to make the text conditional

2024-07-03 17:08 UTC, Tempo-anon commented on src/data/pokemon-level-moves.ts
> +    [ 48, Moves.STEEL_WING ],
Custom moves should have a comment indicating it is such. Also was there a reason this was moved from 30 to 48?

2024-07-03 17:08 UTC, Tempo-anon commented on src/data/pokemon-level-moves.ts
> +    [ 30, Moves.IRON_DEFENSE ],
Custom moves should be commented as such

2024-07-03 17:08 UTC, Tempo-anon commented on src/ui/party-ui-handler.ts
>            ui.playSelect();
+1

Using a boolean check for adding a prefix sounds clever but will make it harder for localization.

2024-07-03 17:08 UTC, Tempo-anon commented on src/ui/party-ui-handler.ts
> +            optionName = `${pokemon.pauseEvolutions ? "Unpause" : "Pause"} Evolution`;
I'm fine with moving the localization into its own PR but at least set it up to be localized

2024-07-03 17:08 UTC, Tempo-anon commented on src/data/pokemon-evolutions.ts
> +    new SpeciesEvolution(Species.GHOLDENGO, 1, null, new SpeciesEvolutionCondition( p => p.evoCounter > 9 ), SpeciesWildEvolutionDelay.VERY_LONG)
I think I prefer the "have X money" (10-15k range) and it seems more elegant than remembering to take 9 money items while the Gimmighoul is in your party

2024-07-03 17:08 UTC, Tempo-anon commented on src/data/pokemon-evolutions.ts
> +    new SpeciesEvolution(Species.CRABOMINABLE, 1, EvolutionItem.ICE_STONE, null, SpeciesWildEvolutionDelay.VERY_LONG)
why this change

2024-07-03 17:08 UTC, Tempo-anon commented on src/system/pokemon-data.ts
> +  public evoCounter: integer;
Does adding information to pokemon-data require any server changes?

2024-07-03 17:08 UTC, Tempo-anon commented on src/field/pokemon.ts
> +              source.evoCounter++;
This might be accurate but this just sounds like a real pain in the butt though this doesn't have to all be in 1 battle

2024-07-03 18:24 UTC, Fontbane commented on src/system/pokemon-data.ts
> +  public evoCounter: integer;
Not as far as I'm aware. Think it just takes it all in as a blob.

2024-07-03 18:27 UTC, Fontbane commented on src/field/pokemon.ts
> +              source.evoCounter++;
Once the Leek gets added it basically gives him a 50% crit rate

2024-08-05 18:59 UTC, Fontbane commented on src/data/pokemon-evolutions.ts
> +    new SpeciesEvolution(Species.CRABOMINABLE, 1, EvolutionItem.ICE_STONE, null, SpeciesWildEvolutionDelay.VERY_LONG)
Wild evo delay is janky, reverted

2024-08-25 21:44 UTC, DayKev commented on src/field/pokemon.ts
> +      this.evoCounter = dataSource.evoCounter || 0;
```suggestion
      this.evoCounter = dataSource.evoCounter ?? 0;
```

2024-08-25 21:44 UTC, DayKev commented on src/field/pokemon.ts
> +            if (!this.isPlayer()) {
Why split the `if` like this?

2024-08-25 21:44 UTC, DayKev commented on src/system/pokemon-data.ts
> +    this.evoCounter = source.evoCounter || 0;
```suggestion
    this.evoCounter = source.evoCounter ?? 0;
```

2024-08-27 01:12 UTC, damocleas approved these changes

2024-08-27 01:35 UTC, damocleas approved these changes

2024-08-28 17:43 UTC, AsdarDevelops requested changes
Please review evolution delays because your PR description didn't mention these being changed at all. This is also setting different delays for similarly powered PKMN like Raichu or A.Raichu

2024-08-28 18:25 UTC, H-A-R-V commented on src/data/pokemon-evolutions.ts
>      new SpeciesFormEvolution(Species.RAICHU, "partner", "", 1, EvolutionItem.THUNDER_STONE, null, SpeciesWildEvolutionDelay.LONG)
idk, but regional forms have the precedent of being made rarer via egg weights. Maybe this is similar logic?
I also don't agree though.

2024-09-05 19:31 UTC, Blitz425 commented
You did end up doing the Charcadet evo item changes (Thank you) but they weren't listed on the PR or the spreadsheet.

2024-09-08 19:33 UTC, Blitz425 submitted a review, later dismissed

2024-09-14 23:45 UTC, Blitz425 approved these changes

2024-09-15 00:05 UTC, damocleas approved these changes

2024-09-15 01:11 UTC, DayKev commented on src/modifier/modifier.ts
> +  protected required: integer;
```suggestion
  protected required: number;
```

2024-09-15 01:12 UTC, DayKev commented on src/modifier/modifier-type.ts
> +        party.filter(p => p.isFusion() && p.fusionSpecies && pokemonEvolutions.hasOwnProperty(p.fusionSpecies.speciesId) && (!p.pauseEvolutions || p.fusionSpecies.speciesId === Species.SLOWPOKE || p.
Why can't pause evolutions be used on Slowpoke and Eevee?

2024-09-15 01:12 UTC, DayKev commented on src/ui/party-ui-handler.ts
> +          this.showText(i18next.t(pokemon.pauseEvolutions? "partyUiHandler:pausedEvolutions" : "partyUiHandler:unpausedEvolutions", { pokemonName: getPokemonNameWithAffix(pokemon) }), undefined, () =
```suggestion
          this.showText(i18next.t(pokemon.pauseEvolutions ? "partyUiHandler:pausedEvolutions" : "partyUiHandler:unpausedEvolutions", { pokemonName: getPokemonNameWithAffix(pokemon) }), undefined, () => this.showText("", 0), null, true);
```

2024-09-15 01:20 UTC, Fontbane commented on src/modifier/modifier-type.ts
> +        party.filter(p => p.isFusion() && p.fusionSpecies && pokemonEvolutions.hasOwnProperty(p.fusionSpecies.speciesId) && (!p.pauseEvolutions || p.fusionSpecies.speciesId === Species.SLOWPOKE || p.
Because they can evolve by level up as well as item. This way you don't lose the current functionality of pausing the level evolution until you get the item.

2024-09-15 01:23 UTC, DayKev commented
Should have mentioned, don't worry about the style changes, those can be fixed later; don't need to remove the approvals lol.

2024-09-15 01:23 UTC, DayKev approved these changes

2024-09-15 01:24 UTC, DayKev commented
Oh right
![image](https://github.com/user-attachments/assets/147d1ccc-aff6-431e-8c64-f00700f2cabe)

2024-09-15 01:26 UTC, Fontbane commented
Gee I hope I translated this text correctly from English to English

2024-09-15 01:32 UTC, f-fsantos approved these changes

2024-09-15 01:32 UTC, merged