implemented pollen puff
pagefaultgames/pokerogue pull request #274
Opened 2024-04-24 20:08 UTC by lucfd

Made new attr `ConditionalHealAttr` that gives a move the following properties when targeting an ally:
- power is set to zero
- target heals for 50% of their health

2024-05-01 19:45 UTC, TempsRay commented on src/data/move.ts
> +      Math.max(Math.floor(target.getMaxHp() * this.healRatio), 1), getPokemonMessage(target, ' regained\nhealth!'), true));
nit: tab line 1965 so it's clear it's still part of the previous line

2024-05-01 19:47 UTC, TempsRay commented on src/data/move.ts
> +      .attr(ConditionalHealAttr, (user, target, move) => (!user.isPlayer() && !target.isPlayer()) || (user.isPlayer() && target.isPlayer()) ? true : false, 0.5)
nit: wrapping the whole right side of the => in parentheses to make it clearer
`.attr(ConditionalHealAttr, (user, target, move) => ((!user.isPlayer() && !target.isPlayer()) || (user.isPlayer() && target.isPlayer())) ? true : false, 0.5)`

2024-05-01 19:47 UTC, TempsRay reviewed
LGTM

2024-05-13 10:07 UTC, bennybroseph requested changes
How does this interact with Telepathy and Heal Block?

2024-05-19 13:43 UTC, bennybroseph commented
Closing this due to inactivity. Feel free to make a new request if interest is reignited

2024-05-19 13:43 UTC, closed without merging