[Ability] Fully Implement Steely Spirit
pagefaultgames/pokerogue pull request #2749
Opened 2024-07-02 01:39 UTC by torranx

## What are the changes?
- implements steely spirit

## Why am I doing these changes?
- fully implement steely spirit

## What did change?
- changed `FieldMoveTypePowerBoostAbAttr` as base class `PreAttackFieldMoveTypePowerBoostAbAttr`

### Screenshots/Videos

## How to test the changes?
`$npm run test steely_spirit`

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-02 14:17 UTC, Tempo-anon reviewed
Can also get a unit test for if one or both of the steely spirit users have their abilities suppressed?

2024-07-02 17:50 UTC, OrangeRed requested changes

2024-07-02 17:50 UTC, OrangeRed commented on src/data/ability.ts
> +  }
Is this constructor necessary? Doesn't a class inherit it's parent constructor if none is specified?
So calling `constructor(...) {  super(...) }` is redundant if the parameters are the same

2024-07-02 17:50 UTC, OrangeRed commented on src/data/ability.ts
> +  }
Same as the previous comment, isn't this constructor redundant if nothing changed from its parent?

2024-07-02 17:50 UTC, OrangeRed commented on src/test/abilities/steely_spirit.test.ts
> +    game.scene.getPlayerField()[1].abilityIndex = 2;
Can you instead use `vi.spyOn(game.scene.getPlayerField()[1], "getAbility").mockReturnValue(allAbilities[Abilities.STEELY_SPIRIT]);`
Imo this is an unreadable way to set a pokemon's ability.

2024-07-02 17:50 UTC, OrangeRed commented on src/test/abilities/steely_spirit.test.ts
> +    expect(mockedMovePower).toBe(allMoves[moveToCheck].power * steelySpiritMultiplier * steelySpiritMultiplier);
Can you use `x**2` or `Math.pow(x, 2)` instead

2024-07-02 18:41 UTC, DustinLin commented on src/test/abilities/steely_spirit.test.ts
> +  alliedField.forEach(p => applyPreAttackAbAttrs(UserFieldMoveTypePowerBoostAbAttr, p, this, move, powerHolder));
I may be dumb but this already takes into account STAB correct?

2024-07-03 02:02 UTC, torranx commented on src/data/ability.ts
> +  }
> Is this constructor necessary? Doesn't a class inherit it's parent constructor if none is specified? So calling `constructor(...) { super(...) }` is redundant if the parameters are the same

its not necessary, i just find it more readable when its included. but since documentation includes `@extends PreAttackFieldMoveTypePowerBoostAbAttr` as well, ill remove it

2024-07-03 02:02 UTC, torranx commented on src/test/abilities/steely_spirit.test.ts
> +  alliedField.forEach(p => applyPreAttackAbAttrs(UserFieldMoveTypePowerBoostAbAttr, p, this, move, powerHolder));
no, as per documentation added here:
```Calculates the mocked power of a move.
Note this does not consider other damage calculations
except the power multiplier from Steely Spirit.```

2024-07-03 02:29 UTC, OrangeRed approved these changes

2024-07-03 02:35 UTC, torranx commented
> Can also get a unit test for if one or both of the steely spirit users have their abilities suppressed?

done

2024-07-03 16:55 UTC, merged