[Challenge] Eevee only challenge
pagefaultgames/pokerogue pull request #2753
Opened 2024-07-02 08:49 UTC by hayuna

## What are the changes?
Add new challenge mode

## Why am I doing these changes?
Make challenge more interesting

## What did change?
Added new option in challenge
Allow to use only Eevee
Allow to use duplicated species
Not allow to use other pokemon than Eeveelutions

### Screenshots/Videos
New option in challenge menu
<img width="1671" alt="Screenshot 2024-07-02 at 10 50 44" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/11d525ce-fdba-43ac-80bc-576ff2861122">
Allow to use *only* Eevee
<img width="1614" alt="Screenshot 2024-07-02 at 10 50 59" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/55e02ed9-074c-4690-b45d-45a4411638f7">
Allow to have duplicated species
<img width="1617" alt="Screenshot 2024-07-02 at 10 51 14" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/2bb9963f-143c-4fdf-9f3f-9268f3e38ab0">
Cannot use other pokemon than Eevee
<img width="1614" alt="Screenshot 2024-07-02 at 10 51 47" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/5fe18d88-2d46-4493-8e2a-00d3d8ef1759">
Completed challenge
<img width="1614" alt="Screenshot 2024-07-04 at 04 36 51" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/dcc2bffb-5b4f-4400-8d6b-aa607bae44ab">

## How to test the changes?
Choose new challenge

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-07-02 09:03 UTC, hayuna commented
Seems like this test is flaky, sometimes is working, sometimes fail

src/test/abilities/costar.test.ts > Abilities - COSTAR > ability copies positive stat changes

2024-07-02 10:31 UTC, Adri1 reviewed
Added French translations

2024-07-02 10:31 UTC, Adri1 commented on src/locales/fr/achv.ts
> +    description: "Complete Eevee Only challenge.",
```suggestion
    name: "RP Pania",
    description: "Terminer un challenge Évoli.",
```

2024-07-02 10:31 UTC, Adri1 commented on src/locales/fr/challenges.ts
> +    "value.1": "On",
```suggestion
    "name": "Évoli uniquement",
    "desc": "Vous ne pouvez choisir que des Évoli comme starters.",
    "value.0": "Désactivé",
    "value.1": "Activé",
```

2024-07-02 10:43 UTC, sodaMelon commented on src/locales/ko/challenges.ts
> +    "desc": "You can use only Eevee in this challenge",
```suggestion
    "name": "이브이 모드",
    "desc": "이 챌린지는 이브이만 사용할 수 있습니다.",
```

2024-07-02 10:45 UTC, sodaMelon commented on src/locales/ko/achv.ts
> +    description: "Complete Eevee Only Eevee challenge.",
```suggestion
    name: "이브이 트레이너",
    description: "이브이 챌린지 모드 클리어.",
```

2024-07-02 10:46 UTC, sodaMelon reviewed
Really cool  the "Eevee only challenge"
i added korean localization.

2024-07-02 10:52 UTC, CodeTappert commented on src/locales/de/achv.ts
> +    description: "Complete Eevee Only challenge.",
```suggestion
    name: "E wie Evoli",
    description: "Beende die Nur-Evoli Herausforderung.",
```

2024-07-02 10:53 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +  }
```suggestion
  "eeveeOnly": {
    "name": "Nur-Evoli",
    "desc": "Du kannst nur Evoli in dieser Herausforderung verwenden.",
    "value.0": "Aus",
    "value.1": "An",
  }
```

2024-07-02 10:53 UTC, CodeTappert commented
If Eveelutions are allowed then the description should reflect this.

2024-07-02 10:53 UTC, RimKnight reviewed
Add cn translation

2024-07-02 10:53 UTC, RimKnight commented on src/locales/zh_CN/challenges.ts
> +    "value.1": "On",
```suggestion
    "name": "伊布限定",
    "desc": "在这个挑战中你只能使用伊布",
    "value.0": "禁用",
    "value.1": "启用",
```

2024-07-02 10:53 UTC, RimKnight commented on src/locales/zh_CN/achv.ts
> +    description: "Complete Eevee Only challenge.",
```suggestion
    name: "唯布独尊",
    description: "完成伊布限定挑战。",
```

2024-07-02 11:05 UTC, hayuna commented
Moved On/Off to the top of translations
Changed description to be more descriptive with evolutions of Eevee

2024-07-02 11:11 UTC, josericardo-fo commented on src/locales/pt_BR/achv.ts
> +    description: "Complete Eevee Only challenge.",
```suggestion
    name: "Treinador de Eevee",
    description: "Complete o desafio Somente Eevees.",
```

2024-07-02 11:11 UTC, josericardo-fo commented on src/locales/pt_BR/challenges.ts
> +  "off": "Off",
```suggestion
  "on": "Ligado",
  "off": "Desligado",
```

2024-07-02 11:13 UTC, sodaMelon commented on src/locales/ko/challenges.ts
> +  "off": "Off",
```suggestion
  "on": "설정",
  "off": "해제",
```

2024-07-02 11:13 UTC, Adri1 reviewed
Edited French (you can merge this edit direcly from this comment with the button on the bottom right of it, no copy-pasting needed)

2024-07-02 11:13 UTC, Adri1 commented on src/locales/fr/challenges.ts
> +    "desc": "Vous ne pouvez choisir que des Évoli comme starters.",
```suggestion
    "desc": "Vous ne pouvez utiliser que des Évoli et leurs évolutions.",
```

2024-07-02 11:13 UTC, josericardo-fo commented on src/locales/pt_BR/challenges.ts
> +    "desc": "You can use only Eevee and its evolutions in this challenge",
```suggestion
    "desc": "Você só pode usar Pokémon do tipo {{type}}.",
    "desc_default": "Você só pode usar Pokémon de um único tipo."
  },
  "eeveeOnly": {
    "name": "Somente Eevees",
    "desc": "Você só pode usar Eevee e suas evoluções nesse desafio",
```

2024-07-02 11:32 UTC, hayuna commented
Connected with https://github.com/pagefaultgames/pokerogue/issues/2708

2024-07-02 14:38 UTC, returntoice approved these changes

2024-07-02 14:59 UTC, sodaMelon approved these changes

2024-07-02 23:47 UTC, jaimefd commented
I think this challenge should be extended to Monomon challenge, where you gotta bring 1-6 of the same species (depending on what weights allow ofc). Could reward a ribbon for the selected species if beaten.

2024-07-03 00:14 UTC, hayuna commented
Eevee is a unique pokemon with many evolution lines, not sure if any other pokemon would be great for similar challenge

2024-07-03 00:54 UTC, EnochG1 commented on src/locales/ko/achv.ts
> +    description: "이브이 챌린지 모드 클리어.",
```suggestion
    description: "이브이 모드 챌린지 클리어.",
```
@sodaMelon 
챌린지의 이름이 '이브이 모드'라 어순을 변경했습니다.

2024-07-03 00:54 UTC, EnochG1 commented on src/locales/ko/challenges.ts
> +    "desc": "이 챌린지는 이브이만 사용할 수 있습니다.",
```suggestion
    "desc": "이 챌린지는 이브이와 이브이의 진화체만 사용할 수 있습니다.",
```
changed korean translation for detail (CC : @sodaMelon)

2024-07-03 04:18 UTC, RimKnight approved these changes

2024-07-03 06:37 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "desc": "Du kannst nur Evoli in dieser Herausforderung verwenden.",
```suggestion
    "desc": "Du kannst nur Evoli und dessen Entwicklungen in dieser Herausforderung verwenden.",
```

2024-07-03 19:59 UTC, GoldTra requested changes
Spanish translations

2024-07-03 19:59 UTC, GoldTra commented on src/locales/es/challenges.ts
> +  "off": "Off",
```suggestion
  "on": "Activado",
  "off": "Desactivado",
```

2024-07-03 19:59 UTC, GoldTra commented on src/locales/es/achv.ts
> +    description: "Complete Eevee Only challenge.",
```suggestion
    name: "Entranador de Eevee",
    description: "Completa el desafío de solo Eevee.",
```

2024-07-04 05:11 UTC, GoldTra requested changes
Fix typo Spanish

2024-07-04 05:11 UTC, GoldTra commented on src/locales/es/achv.ts
> +    name: "Entranador de Eevee",
```suggestion
    name: "Entrenador de Eevee",
```

2024-07-05 21:39 UTC, nayfaan commented
In the Challenge modifier menu, instead of 

Eevee Only...............On / Off

maybe change it to something like

Others......................None / Eevee Only

?

This could allow future special challenges to be added to the "Others" menu without having them to all make a new row each.

2024-07-05 21:40 UTC, nayfaan commented
And what happens if I selects "On" with Eevee only while the other two options are not at default value? e.g. Gen IX + mono Ghost selected

2024-07-05 23:21 UTC, hayuna commented
@nayfaan I have compared current example.

Dark type + gen I = no pokemon available, so you cannot start

2024-07-06 00:06 UTC, InnocentGameDev requested changes
Some lines weren't translated

2024-07-06 00:06 UTC, InnocentGameDev commented on src/locales/es/challenges.ts
> +  }
```suggestion
  "eeveeOnly": {
    "name": "Solamente Eevee",
    "desc": "Solo puedes usar a Eevee o a sus evoluciones en este desafío",
  }
```

2024-07-07 18:04 UTC, NicusPulcis commented
hey @hayuna i've added translations for both achv and challenges in italian!

2024-07-08 13:13 UTC, Naothe commented
I'd like the third menu to be Others: Off / Eevee
This way there could be other challenges, for example: Fossil only

2024-07-24 22:41 UTC, CodeTappert commented
Please fix conflicts

2024-08-02 16:46 UTC, hayuna commented
New PR

https://github.com/pagefaultgames/pokerogue/pull/3305

2024-08-02 16:46 UTC, closed without merging