[BUG] Fixes Sketch copying the first move used by the opponent instead of the last
pagefaultgames/pokerogue pull request #2759
Opened 2024-07-02 18:06 UTC by schmidtc1

## What are the changes?

Sketch currently copies the first move used in a turn instead of the most recent.
#2758 exposed this issue, but it is not due to switching out like the issue states. Instead, it just always copies the first move used in the opponent's history.

## Why am I doing these changes?

Fixes a bug with Sketch.

## What did change?

SketchAttr now gets the last move used by the opponent, instead of the entire move history.

### Screenshots/Videos

Before fix (copies first move used - Gust)

https://github.com/pagefaultgames/pokerogue/assets/62030095/7059caba-cf6c-40ac-bccc-a7b0378f811f

After fix (copies last move used - Absorb)

https://github.com/pagefaultgames/pokerogue/assets/62030095/71cd14ec-b748-4532-9f4e-010ab1d97ff6

## How to test the changes?

Give opponent different moves, select Smeargle as your starter (preferably with other moves if Smeargle is faster than opponent). Let opponent use different moves. Smeargle uses Sketch on opponent. Smeargle should copy latest move used.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-07-02 20:44 UTC, OrangeRed approved these changes

2024-07-13 17:18 UTC, OrangeRed requested changes

2024-07-13 17:18 UTC, OrangeRed commented on src/data/move.ts
>      }
Some further discussion with the team and `TurnMove.virtual` actually means moves that were spawned by other moves like Metronome. With that being said can you revert back to the previous implementation and just access the last move via `Array.at(-1)`

2024-07-13 17:35 UTC, schmidtc1 commented on src/data/move.ts
>      }
Change to this then? That would allow it to copy Metronome by skipping the virtual moves [which seems to be intended](https://bulbapedia.bulbagarden.net/wiki/Sketch_(move)#:~:text=Sketch%20can%20now%20be%20used%20to%20copy%20Metronome%2C%20Mimic%2C%20and%20Transform%20like%20any%20other%20move%20(without%20the%20need%20for%20the%20move%20to%20fail%20due%20to%20sleep).)
```typescript
    const targetMoves = target.getMoveHistory().filter(m => !m.virtual);
    if (!targetMoves.length) {
      return false;
    }

    const sketchedMove = allMoves[targetMoves.at(-1).move];
```

2024-07-13 17:43 UTC, OrangeRed commented on src/data/move.ts
>      }
just do this to get the move instead of handling the array of moves
`const targetMoves = target.getMoveHistory().filter(m => !m.virtual).at(-1);`

2024-07-13 18:03 UTC, OrangeRed approved these changes

2024-07-13 18:04 UTC, OrangeRed commented
@schmidtc1 can you also as a separate PR add a tag or check so that sketch fails when its used against unsketchable moves

2024-07-13 18:07 UTC, merged

2024-07-13 18:18 UTC, schmidtc1 commented
> @schmidtc1 can you also make a separate PR add a tag or check so that sketch fails when its used against unsketchable moves

Like a move flag applied to all the unsketchable moves, and a check if the move has the flag? Or do you suggest a better way to do this?

2024-07-13 18:33 UTC, OrangeRed commented
@schmidtc1 something along those lines. Similar to how we have unswappable abilities

2024-07-13 18:46 UTC, schmidtc1 commented
> @schmidtc1 something along those lines. Similar to how we have unswappable abilities

Started here: #3013. Will work on it further.