[Moves] Add a FrenzyTag to Uproar
pagefaultgames/pokerogue pull request #2763
Opened 2024-07-03 03:57 UTC by 3ae3ae

## What are the changes?

To implement the effect of Uproar lasting for 3 turns, I added the Frenzy tag to Uproar.

For this, I modified the way Frenzy works to allow specifying the duration in turns.

Additionally, I adjusted the Frenzy tag to distinguish between moves that cause confusion and those that do not.

## Why am I doing these changes?

It wasn't implemented.

## What did change?

I added FrenzyAttr and MissEffectAttr to Uproar, and made it possible to optionally input the duration in turns into the constructor of FrenzyAttr.

I modified the onRemoved method of FrenzyTag to add the confusion tag only when the sourceMove is one of [Moves.OUTRAGE, Moves.PETAL_DANCE, Moves.THRASH].

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

2024-07-03 04:04 UTC, flx-sta commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
I assume this takes care of this?
> If Uproar fails to be executed completely on any turn—such as if it is used against a [Ghost-type](https://bulbapedia.bulbagarden.net/wiki/Ghost_(type)) Pokémon, a [protected](https://bulbapedia.bulbagarden.net/wiki/Category:Protection_moves) Pokémon, or a Pokémon with the Ability Soundproof—the user immediately calms down and is no longer forced to use Uproar.

2024-07-03 04:04 UTC, flx-sta commented
Just leaving the Bulbapedia link here for others:
https://bulbapedia.bulbagarden.net/wiki/Uproar_(move)

2024-07-03 04:08 UTC, 3ae3ae commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
Yes. I just tested it against a Ghost-type Pokémon and it worked fine.

2024-07-03 04:26 UTC, flx-sta commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
@3ae3ae always worth it to attach a video of such

2024-07-03 04:30 UTC, 3ae3ae commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
Got it. I'll make sure to attach a video next time. Thanks!

2024-07-03 04:41 UTC, 3ae3ae commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
I think I misunderstood what you said due to my inexperience, I'll take a video and post it soon.

2024-07-03 04:46 UTC, 3ae3ae commented
I just realized there was a problem with my commit. I'll fix it right away.

2024-07-03 05:20 UTC, 3ae3ae commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
@flx-sta Thanks to your review, I realized that the move does not shut down immediately when protected, I will fix it soon.

2024-07-03 08:25 UTC, 3ae3ae commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
@flx-sta I've fixed what you pointed out.
I will take a video and post it soon.
Thank you.

2024-07-03 13:58 UTC, flx-sta commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
Alright 👍 
Add these videos into the PR description though. Not just here (you can just copy paste the url it generated. No re-upload necessary)

2024-07-03 14:04 UTC, 3ae3ae commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
Yes, I will do that.
Thank you for all your help!

2024-07-03 15:27 UTC, flx-sta commented on src/data/move.ts
> +      .attr(MissEffectAttr, frenzyMissFunc)
@3ae3ae press `resolve` below this comment

2024-07-03 15:41 UTC, flx-sta requested changes
It's missing the `{{pkm}} caused an uproar` msg as seen here:
<img src="https://archives.bulbagarden.net/media/upload/1/11/Uproar_III.png" />
<sup>[sauce](https://bulbapedia.bulbagarden.net/wiki/Uproar_(move)#In_other_generations)</sup>

<sub>Another thing I noticed is that it doesn't wake up sleeping pokemon and all that but that is probably another PR worth<sub>

2024-07-03 16:51 UTC, Tempo-anon commented on src/data/battler-tags.ts
> +    if ([Moves.OUTRAGE, Moves.PETAL_DANCE, Moves.THRASH].includes(this.sourceMove)) {
Instead of hardcoding the moves here, would it make sense to have a boolean on FrenzyAttr and FrenzyTag to indicate whether or not this should inflict confusion?

2024-07-04 01:51 UTC, 3ae3ae commented on src/data/battler-tags.ts
> +    if ([Moves.OUTRAGE, Moves.PETAL_DANCE, Moves.THRASH].includes(this.sourceMove)) {
@Tempo-anon I don't know how to add a boolean to a tag.
Can I just create BattlerTagType.FRENZY and BattlerTagType.SAFE_FRENZY and specify the boolean value in getBattlerTag in battler-tags.ts?

2024-07-04 03:00 UTC, 3ae3ae commented
@flx-sta I've fixed what you pointed out.
https://github.com/pagefaultgames/pokerogue/assets/83870598/64f8a70f-a505-47e9-a4a6-5e2b7ab2c512

2024-07-04 04:01 UTC, flx-sta commented on src/data/battler-tags.ts
> +    if ([Moves.OUTRAGE, Moves.PETAL_DANCE, Moves.THRASH].includes(this.sourceMove)) {
@3ae3ae i think he means adding constructor arguments

2024-07-04 04:51 UTC, 3ae3ae commented on src/data/battler-tags.ts
> +    if ([Moves.OUTRAGE, Moves.PETAL_DANCE, Moves.THRASH].includes(this.sourceMove)) {
@flx-sta I've reviewed the code again and I'm still not sure what to do.
I can add a boolean to the constructor arguments of FrenzyAttr, but I haven't found a way to pass it to FrenzyTag.
The getBattlerTag function, which creates the FrenzyTag object, doesn't have any arguments to pass additional information to the FrenzyTag.
I could implement this by modifying the getBattlerTag and addTag functions, but I don't think it's a good idea.

2024-07-04 16:55 UTC, flx-sta commented on src/data/move.ts
> +    user.scene.queueMessage(getPokemonMessage(user, " caused\nan uproar!"));
The message has to be localizable

2024-07-04 16:56 UTC, flx-sta commented on src/data/battler-tags.ts
> +    if ([Moves.OUTRAGE, Moves.PETAL_DANCE, Moves.THRASH].includes(this.sourceMove)) {
Then let’s wait for @Tempo-anon response. He might be busy playing Elden ring 😁

2024-07-05 00:33 UTC, 3ae3ae commented on src/data/move.ts
> +    user.scene.queueMessage(getPokemonMessage(user, " caused\nan uproar!"));
I've fixed what you pointed out.
Fixed src/data/move.ts and src/locales/en/battle.ts.

2024-07-05 01:44 UTC, flx-sta commented
@3ae3ae looks good. Almost done.
1 more thing: please add the new translation key for all languages but just copy paste the English translation into it. The localization people will see it and provide comments with the proper translations then you can just “accept” 👍 that’s how it’s done here

2024-07-05 02:01 UTC, 3ae3ae commented
@flx-sta I've made the changes you suggested.
Thanks for your help.
I'm still new to PRs, and your feedback is really helpful.

2024-07-05 02:39 UTC, flx-sta approved these changes

2024-07-07 03:49 UTC, 3ae3ae commented on src/data/battler-tags.ts
> +    if ([Moves.OUTRAGE, Moves.PETAL_DANCE, Moves.THRASH].includes(this.sourceMove)) {
@Tempo-anon I'd like to get a PR review, is there anything I need to fix?

2024-07-07 15:59 UTC, flx-sta commented
@3ae3ae Its normal that PRs take quite some time to get merged onto live (unless localization). Patience is a virtue.

you could create another PR with the same changes but based of the `beta` branch and also merged into the `beta` branch.

keep in mind it will only be merged on the beta initially then but eventually on live

2024-07-07 21:03 UTC, 3ae3ae commented
I apologize for any confusion and inconvenience caused. I wasn't aware of the normal process regarding PR merges. I'm sorry for any trouble this may have caused. I will ensure to follow the proper procedures moving forward.

Sorry again for the oversight.

2024-07-07 21:05 UTC, 3ae3ae commented
I sincerely apologize for any confusion and inconvenience caused. I wasn't aware of the normal process regarding PR merges, and I'm very sorry for any trouble this may have caused. I'll make sure to follow the proper procedures moving forward.

Sorry again for the oversight.

2024-07-23 03:44 UTC, flx-sta commented
@3ae3ae you uuuh... merged main into that branch.. You shouldn't do that. you should only merge beta into it

2024-07-23 04:07 UTC, 3ae3ae commented
@flx-sta Apologies for the oversight. I've reverted the branch to its previous state.

2024-09-17 16:51 UTC, flx-sta commented
@3ae3ae  closed for being stale (no updates for over a month)

----

Feel free to create a new PR or ask us to re-open this one.

2024-09-18 07:32 UTC, 3ae3ae commented
@flx-sta Hello. I didn't realize I needed to do something. What should I do?

2024-09-18 14:09 UTC, flx-sta commented
Resolving the conflicts would be a start

2024-09-18 16:22 UTC, NicusPulcis approved these changes
italian localization done

2024-09-18 16:22 UTC, NicusPulcis commented on src/locales/it/battle.ts
> +  "battlerTagsUproar": "{{pokemonNameWithAffix}} caused\nan uproar!",
```suggestion
  "battlerTagsUproar": "{{pokemonNameWithAffix}} scatena\nuna baraonda!",
```

2024-09-19 03:04 UTC, returntoice requested changes

2024-09-19 03:04 UTC, returntoice commented on src/locales/ko/battler-tags.json
> +  "uproarOnAdd": "{{pokemonNameWithAffix}} caused\nan uproar!"
```suggestion
  "uproarOnAdd": "{{pokemonNameWithAffix}}[[는]]\n소란을 피우기 시작했다!"
```

2024-09-19 10:48 UTC, Chapybara-jp submitted a review, later dismissed

2024-10-02 03:11 UTC, flx-sta commented
Putting into draft to give time to resolve the conflicts

2024-10-02 03:13 UTC, Tempo-anon commented on src/data/battler-tags.ts
> +    if ([Moves.OUTRAGE, Moves.PETAL_DANCE, Moves.THRASH].includes(this.sourceMove)) {
For posterity's sake, I was thinking something like this
```ts
export class FrenzyTag extends BattlerTag {
  public boolean: addConfusion;
  constructor(turnCount: number, sourceMove: Moves, sourceId: number, addConfusion: boolean=false) {
    this.addConfusion = addConfusion;
    super(BattlerTagType.FRENZY, BattlerTagLapseType.CUSTOM, turnCount, sourceMove, sourceId);
  }

  onRemove(pokemon: Pokemon): void {
    super.onRemove(pokemon);
    if (this.addConfusion) {
      if (this.turnCount < 2) { // Only add CONFUSED tag if a disruption occurs on the final confusion-inducing turn of FRENZY
        pokemon.addTag(BattlerTagType.CONFUSED, pokemon.randSeedIntRange(2, 4));
      }
    }
  }
}
```
and then modifying outrage, petal dance, and thrash to pass in `true`

2024-10-02 15:59 UTC, Chapybara-jp approved these changes

2024-10-04 02:05 UTC, 3ae3ae commented on src/data/battler-tags.ts
> +    if ([Moves.OUTRAGE, Moves.PETAL_DANCE, Moves.THRASH].includes(this.sourceMove)) {
@Tempo-anon I still don't know how to do it, how do I pass additional arguments to the Tag?

2025-03-14 04:00 UTC, closed without merging