Heal Block, Psychic Noise (Partial)
pagefaultgames/pokerogue pull request #277
Opened 2024-04-24 21:17 UTC by adrienntindall

Still needs the 'prevent the mon from selecting moves that can heal' effect introduced in XY but that's far too much work for my first pull request.

2024-05-10 20:23 UTC, pixelizedgaming commented
hey idk if ur still working on this but i can help implement the heal move selection thing, had to work with it for my gorilla tactics implementation

2024-05-12 18:05 UTC, adrienntindall commented
> hey idk if ur still working on this but i can help implement the heal move selection thing, had to work with it for my gorilla tactics implementation

that'd be great, was still just hoping to get it reviewed at all tho lol

2024-05-13 10:13 UTC, bennybroseph requested changes
This needs comments where relevant. See recent commits for examples.

2024-05-13 10:13 UTC, bennybroseph commented on src/data/pokemon-level-moves.ts
This should be a separate pull request

2024-05-13 10:13 UTC, bennybroseph commented on src/data/battler-tags.ts
> +        pokemon.scene.queueMessage(getPokemonMessage(pokemon, ' was prevented from healing!'));
Called here

2024-05-13 10:13 UTC, bennybroseph commented on src/phases.ts
> +        this.scene.queueMessage(getPokemonMessage(pokemon, ' was prevented from healing!'));
and here. Doesn't this trigger twice?

2024-05-13 12:56 UTC, adrienntindall commented on src/phases.ts
> +        this.scene.queueMessage(getPokemonMessage(pokemon, ' was prevented from healing!'));
No, one is the apply message the other is the message that appears when healing is attempted. I work on the hgss repo and used the text from that game as a basis, not sure if it's changed in more recent gens.

2024-05-13 12:56 UTC, adrienntindall commented on src/data/pokemon-level-moves.ts
Why? Heal block would be completely inaccessible otherwise

2024-05-13 23:22 UTC, bennybroseph commented on src/data/pokemon-level-moves.ts
This is an old move that no longer exists in modern games. We don't want them on level-up moves and would need a broader discussion about it otherwise. Probably a TM addition, but not something that goes in this PR. I can't approve this with these changes included.

2024-05-13 23:29 UTC, bennybroseph requested changes

2024-05-13 23:29 UTC, bennybroseph commented on src/phases.ts
> +        this.scene.queueMessage(getPokemonMessage(pokemon, ' was prevented from healing!'));
Okay, I see. This message should pop up in three cases. 

1. On use of the move when it applies
2. When the player tries to select a healing move (it does not waste a turn similar to disable)
3. When the victim tried to heal through passive means

Does this account for all of these?

2024-05-18 08:55 UTC, closed without merging