[Feature] Allow Phione eggs to have a 1/8 chance to hatch Manaphy
pagefaultgames/pokerogue pull request #2787
Opened 2024-07-04 06:18 UTC by Tempo-anon

## What are the changes?
Allow Phione species-eggs to have a 1/8 chance to hatch Manaphy

## Why am I doing these changes?
Manaphy is obnoxiously hard to obtain right now since it is unaffected by pity.

## What did change?
Added the following in `egg.ts`
```ts
if (this._species === Species.PHIONE) {
      pokemonSpecies = getPokemonSpecies(Utils.randSeedInt(MANAPHY_EGG_MANAPHY_RATE) ? Species.PHIONE : Species.MANAPHY);
    }
```

### Screenshots/Videos
Obtained a lot of free 1 wave Phione eggs
![](https://cdn.discordapp.com/attachments/1241164581997510656/1258301805771620403/image.png?ex=66878c60&is=66863ae0&hm=d8d9ef2bbf82d667edce1eebfe750ebe4c00b49f359d9b861c1622980a809fce&)
Verify Manaphy hatched out
![](https://cdn.discordapp.com/attachments/1241164581997510656/1258304920822481046/image.png?ex=66878f47&is=66863dc7&hm=6695edc3b708868b0438f0398ad3082ca97d7394bacf6a8cde61bac3a52dfb30&)

## How to test the changes?

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-05 17:20 UTC, damocleas commented
Real

2024-08-05 18:24 UTC, flx-sta commented
@Tempo-anon here is a test you can add to `egg.test.ts` to cover this.
```ts
  it("should return a manaphy egg in 1 out 8 phione eggs", () => {
    const scene = game.scene;

    const hatchedPokemonSpeciesIds = Array.from({ length: 8 }).map(
      () => new Egg({ scene, species: Species.PHIONE }).generatePlayerPokemon(scene).species.speciesId
    );
    const hatchedPokemonSpeciesStrs = hatchedPokemonSpeciesIds.map((id) => Species[id]);
    console.log(hatchedPokemonSpeciesStrs)

    expect(hatchedPokemonSpeciesIds, `[${hatchedPokemonSpeciesStrs.join(", ")}] should contain MANAPHY`).toContain(Species.MANAPHY);
  });
  ```
  
  I ran this test about 1000 times and it succeed 100% of times so I'd say this is working as expected.
  
  I've also tuned the amount of eggs down to `4` and it failed about 50% of the cases (surprise)

2024-08-05 18:24 UTC, flx-sta approved these changes

2024-08-05 21:07 UTC, flx-sta requested changes
It seems right when running play tests.

2024-08-06 17:51 UTC, damocleas approved these changes

2024-08-06 18:05 UTC, merged