Localized moneyPickedUp message
pagefaultgames/pokerogue pull request #2788
Opened 2024-07-04 06:25 UTC by mercurius-00

## What are the changes?

Localized moneyPickedUp message

## Why am I doing these changes?

## What did change?

Localized the message "You picked up ₽______!".

### Screenshots/Videos

before:
![image](https://github.com/pagefaultgames/pokerogue/assets/80205689/0e883f54-6298-4cf2-97a4-8f4feb33fc64)

after:
![image](https://github.com/pagefaultgames/pokerogue/assets/80205689/3f84532d-9050-46e0-a18d-d3bcbbe31bf4)

## How to test the changes?

Use "Pay Day" or "Make It Rain".

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-07-04 07:05 UTC, GoldTra requested changes
Spanish translations

2024-07-04 07:05 UTC, GoldTra commented on src/locales/fr/battle.ts
> +  "moneyPickedUp": "You picked up ₽{{moneyAmount}}!",
```suggestion
  "moneyPickedUp": "Has recogido {{moneyAmount}} ₽.",
```

2024-07-04 11:24 UTC, KimJeongSun commented on src/locales/ko/battle.ts
> +  "moneyPickedUp": "You picked up ₽{{moneyAmount}}!",
```suggestion
  "moneyPickedUp": "₽{{moneyAmount}}을 주웠다!",
```
![image](https://github.com/pagefaultgames/pokerogue/assets/47556641/b9e0dfa8-447b-4c05-af1b-7c00d17f4276)

I suggest a Korean translation as above.

2024-07-04 11:56 UTC, Adri1 reviewed
Real French translation

2024-07-04 11:56 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "moneyPickedUp": "You picked up ₽{{moneyAmount}}!",
@GoldTra You put your Spanish translation on French 😭

2024-07-04 11:56 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "moneyPickedUp": "You picked up ₽{{moneyAmount}}!",
```suggestion
  "moneyPickedUp": "Vous obtenez {{moneyAmount}} ₽ !",
```

2024-07-04 12:54 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "moneyPickedUp": "You picked up ₽{{moneyAmount}}!",
```suggestion
  "moneyPickedUp": "Du hebst {{moneyAmount}} ₽ auf!",
```

Source Pokémon Scarlet/Violet

2024-07-05 01:10 UTC, sodaMelon approved these changes

2024-07-05 01:26 UTC, EnochG1 approved these changes

2024-07-05 01:27 UTC, EnochG1 commented on src/locales/ko/battle.ts
> +  "moneyPickedUp": "You picked up ₽{{moneyAmount}}!",
@KimJeongSun 
Minor thing but could you replace '을' to [[를]] ?

```suggestion
  "moneyPickedUp": "₽{{moneyAmount}}[[를]] 주웠다!",
```

2024-07-05 03:06 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "moneyPickedUp": "You picked up ₽{{moneyAmount}}!",
```suggestion
  "moneyPickedUp": "Você pegou ₽{{moneyAmount}} do chão!",
```

2024-07-05 12:22 UTC, CodeTappert commented
@mercurius-00 Do you know how to add our suggestions to your PR? Or do you need help with that

2024-07-08 01:11 UTC, EnochG1 approved these changes

2024-07-08 01:24 UTC, mercurius-00 commented
> @mercurius-00 Do you know how to add our suggestions to your PR? Or do you need help with that

Done now. sorry for the delay

2024-07-08 14:16 UTC, Tempo-anon approved these changes
Approved by the wiki/tl team

2024-07-08 14:25 UTC, merged