Rework the Candy Upgrade Notification feature
pagefaultgames/pokerogue pull request #2808
Opened 2024-07-05 12:08 UTC by josericardo-fo

## What are the changes?

Reworked the Candy Upgrade Notification logic to take account of the new "Buy Egg" option. Also reworked the "Passives Only" setting to "Passives First". The logic of this new setting was suggested in a discord suggestion post and works as follows:
It activates when a Pokémon has enough candies for a Passive Unlock, when a Pokémon has enough candies for a Cost Reduction and has its passive unlocked, and when a Pokémon has enough candies to Buy an Egg and its passive is unlocked and it Cost was reduced 2 times.

## Why am I doing these changes?

A new mechanic was implemented (Buying Eggs) and "Passives Only" needed a rework.

## What did change?

Addes two functions to check if a passive is unlocked and to check if the cost was reduced twice.

### Screenshots/Videos

Later

## How to test the changes?

Later

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-05 12:11 UTC, 40chyan commented on src/locales/zh_TW/settings.ts
> +  "passivesFirst": "Passives First", // Changed from "Passives Only" to "Passives First", needs new translation
```suggestion
  "passivesFirst": "優先被動", // Changed from "Passives Only" to "Passives First", needs new translation
```

2024-07-05 12:11 UTC, 40chyan commented on src/locales/zh_CN/settings.ts
> +  "passivesFirst": "Passives First", // Changed from "Passives Only" to "Passives First", needs new translation
```suggestion
  "passivesFirst": "优先被动", // Changed from "Passives Only" to "Passives First", needs new translation
```

2024-07-05 12:12 UTC, josericardo-fo commented on src/locales/zh_CN/settings.ts
> +  "passivesFirst": "Passives First", // Changed from "Passives Only" to "Passives First", needs new translation
make sure to remove the comment

2024-07-05 12:15 UTC, Adri1 reviewed
Added French + adjustment of an exiting entry to make it fit)

2024-07-05 12:15 UTC, Adri1 commented on src/locales/fr/settings.ts
>    "candyUpgradeNotification": "Notif amélioration de bonbon",
```suggestion
  "candyUpgradeNotification": "Notif. amélio. de bonbon",
```

2024-07-05 12:15 UTC, Adri1 commented on src/locales/fr/settings.ts
> +  "passivesFirst": "Passives First", // Changed from "Passives Only" to "Passives First", needs new translation
```suggestion
  "passivesFirst": "Prio Passif",
```

2024-07-05 12:18 UTC, CodeTappert commented on src/locales/de/settings.ts
> +  "passivesFirst": "Passives First", // Changed from "Passives Only" to "Passives First", needs new translation
```suggestion
  "passivesFirst": "Passive zuerst",
```

2024-07-05 12:19 UTC, EnochG1 commented on src/locales/ko/settings.ts
> +  "passivesFirst": "Passives First", // Changed from "Passives Only" to "Passives First", needs new translation
```suggestion
  "passivesFirst": "패시브우선",
```

2024-07-07 10:28 UTC, KimJeongSun reviewed
Overall, LGTM
As a minor suggestion, the menu name `passive first` seems to omit the actual logic that valueReduction is also prioritized.
`prioritize Passive and value reduction` appears to be a clearer description, but it doesn't seem concise enough for a menu name, so it's hard to recommend.

2024-07-07 11:18 UTC, josericardo-fo commented
Thanks!
If someone suggests a better name, I'll gladly change it. But I can't really find another concise name for that setting.

2024-07-07 11:31 UTC, KimJeongSun approved these changes

2024-07-07 21:59 UTC, EnochG1 approved these changes

2024-07-09 13:58 UTC, NicusPulcis commented
@josericardo-fo i've made an italian translation

2024-07-10 03:09 UTC, flx-sta requested changes

2024-07-10 03:09 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +    return starterData.valueReduction >= 2;
Magic numbers 👎 
```suggestion
    return starterData.valueReduction >= VALUE_REDUCTION_MAX;
```
(variable has to be defined somewhere central. See if there is other code occurrences for the exact number

2024-07-10 03:09 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +    const valueReductionMaxed = this.isValueReductionMaxed(species.speciesId);
```suggestion
    const isValueReductionMaxed = this.isValueReductionMaxed(species.speciesId);
```
`is` (or `has`) prefix helps to quickly distinguish a boolean

2024-07-10 03:09 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +    const valueReductionAvailable = this.isValueReductionAvailable(species.speciesId);
```suggestion
    const isValueReductionAvailable = this.isValueReductionAvailable(species.speciesId);
```
`is` (or `has`) prefix helps to quickly distinguish a boolean

2024-07-10 03:09 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +    const eggAvailable = this.isSameSpeciesEggAvailable(species.speciesId);
```suggestion
    const isEggAvailable = this.isSameSpeciesEggAvailable(species.speciesId);
```
`is` (or `has`) prefix helps to quickly distinguish a boolean

2024-07-10 03:09 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +    const passiveUnlocked = this.isPassiveUnlocked(species.speciesId);
```suggestion
    const isPassiveUnlocked = this.isPassiveUnlocked(species.speciesId);
```
`is` (or `has`) prefix helps to quickly distinguish a boolean

2024-07-10 03:09 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +    const valueReductionMaxed = this.isValueReductionMaxed(species.speciesId);
```suggestion
    const isValueReductionMaxed = this.isValueReductionMaxed(species.speciesId);
```
`is` (or `has`) prefix helps to quickly distinguish a boolean

2024-07-10 03:09 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +    const valueReductionAvailable = this.isValueReductionAvailable(species.speciesId);
```suggestion
    const isValueReductionAvailable = this.isValueReductionAvailable(species.speciesId);
```
`is` (or `has`) prefix helps to quickly distinguish a boolean

2024-07-10 03:09 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +    const eggAvailable = this.isSameSpeciesEggAvailable(species.speciesId);
```suggestion
    const isEggAvailable = this.isSameSpeciesEggAvailable(species.speciesId);
```
`is` (or `has`) prefix helps to quickly distinguish a boolean

2024-07-10 03:14 UTC, josericardo-fo commented on src/ui/starter-select-ui-handler.ts
> +    return starterData.valueReduction >= 2;
it is not defined anywhere 💀

2024-07-10 03:16 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +    return starterData.valueReduction >= 2;
I know. Thats part of your task

2024-07-10 03:35 UTC, flx-sta requested changes

2024-07-10 03:35 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +  private valueReductionMax: 2;
It shouldn't be an attribute of StartSelectUiHandler. It should be a constant defined outside of the class. for other code files to be available if needed (exported)

2024-07-10 03:38 UTC, josericardo-fo commented on src/ui/starter-select-ui-handler.ts
> +  private valueReductionMax: 2;
I don't really know where to define that. The costs of everything are located in this file as a const.

![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/27a14db6-50a6-4793-8182-c630fc8c5c2a)

2024-07-10 03:52 UTC, josericardo-fo commented on src/ui/starter-select-ui-handler.ts
> +  private valueReductionMax: 2;
maybe like this? lol

![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/2b7853a1-3d7c-41d3-871a-d22d3ccae591)

2024-07-10 04:09 UTC, flx-sta commented on src/ui/starter-select-ui-handler.ts
> +  private valueReductionMax: 2;
yeah like that but since it's an actual constant name it `export const VALUE_REDUCTION_MAX = 2`

2024-07-10 11:49 UTC, josericardo-fo commented on src/ui/starter-select-ui-handler.ts
> +  private valueReductionMax: 2;
fixed

2024-07-10 11:54 UTC, Adri1 approved these changes

2024-07-10 12:03 UTC, CodeTappert approved these changes

2024-07-10 16:00 UTC, flx-sta approved these changes
lgtm 🚀  (code review only)

2024-07-12 14:33 UTC, josericardo-fo commented
@brain-frog @bennybroseph Take a look whenever you can, we implemented this, so you guys maybe want to give an opinion.

2024-07-25 01:30 UTC, 40chyan commented
@Tempo-anon this PR all good

2024-08-01 02:20 UTC, josericardo-fo commented
Moved changes to #3279

2024-08-01 02:20 UTC, closed without merging