[Bug] Disable menu in shop
pagefaultgames/pokerogue pull request #2825
Opened 2024-07-06 00:45 UTC by Nohbody

## What are the changes?
1. This prevents the "Start Menu" from being opened in the Shop screen.

## Why am I doing these changes?
1. There's a Candy exploit where a user can repeatedly catch a Pokemon, open the Egg Gacha, pull an egg to have the game force save the session (with the caught Pokemon and Candy), and then reload to have the scene reset to before they caught the Pokemon (but keeping the caught Pokemon and Candy).

## What did change?
1. The exploit is no longer possible because the Egg Gacha save won't be accessible until after the session has been dealt with otherwise (e.g. exited or saved by the next wave starting).

## How to test the changes?
1. You should no longer be able to open the "Start Menu" (e.g. with ESC by default) while the Shop Overlay is open.

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-06 04:16 UTC, Opaque02 commented
One question I have about this is if people want to do things unrelated to egg gatcha in the shop - say changing some settings or looking at achievements/stats? Maybe a better option would be to allow the menu to be opened but the egg gatcha to not be enabled while within the shop?

2024-07-06 07:46 UTC, Nohbody commented
> One question I have about this is if people want to do things unrelated to egg gatcha in the shop - say changing some settings or looking at achievements/stats? Maybe a better option would be to allow the menu to be opened but the egg gatcha to not be enabled while within the shop?

They can just access the gacha and settings at the start of the next battle. I don't see why they'd have to do those things while in the shop.

2024-07-06 08:06 UTC, Opaque02 commented
> > One question I have about this is if people want to do things unrelated to egg gatcha in the shop - say changing some settings or looking at achievements/stats? Maybe a better option would be to allow the menu to be opened but the egg gatcha to not be enabled while within the shop?
> 
> They can just access the gacha and settings at the start of the next battle. I don't see why they'd have to do those things while in the shop.

Another option could be if someone wants to quit to restart - say they want to savescum and instead of reloading, they would normally quit to menu from within the shop menu? Or if you accidentally release a mon by accident and don't want to reload?

I bring this up because of a scenario I had earlier was that there was a bug that I found and I wanted to get my session data so I could raise a bug report. I went to open the menu from within the shop (where the bug appeared) and downloaded the session data. With this PR as is, I'd have to reload the page and get the session data from the start of the battle, whereas if you could disable the egg gacha from the menu during the shop, you'd still be able to do all this stuff, just without accessing the gacha?

2024-07-06 08:13 UTC, Nohbody commented
> > > One question I have about this is if people want to do things unrelated to egg gatcha in the shop - say changing some settings or looking at achievements/stats? Maybe a better option would be to allow the menu to be opened but the egg gatcha to not be enabled while within the shop?
> > 
> > 
> > They can just access the gacha and settings at the start of the next battle. I don't see why they'd have to do those things while in the shop.
> 
> Another option could be if someone wants to quit to restart - say they want to savescum and instead of reloading, they would normally quit to menu from within the shop menu? Or if you accidentally release a mon by accident and don't want to reload?
> 
> I bring this up because of a scenario I had earlier was that there was a bug that I found and I wanted to get my session data so I could raise a bug report. I went to open the menu from within the shop (where the bug appeared) and downloaded the session data. With this PR as is, I'd have to reload the page and get the session data from the start of the battle, whereas if you could disable the egg gacha from the menu during the shop, you'd still be able to do all this stuff, just without accessing the gacha?

I feel like it'd be a more confusing UX if the only time this menu didn't let you access the Gacha was from within the Shop. I always reset my save state by just reloading the game so it is interesting to hear it might be a legitimate issue for some people's experience.

2024-07-06 08:19 UTC, Opaque02 commented
> > > > One question I have about this is if people want to do things unrelated to egg gatcha in the shop - say changing some settings or looking at achievements/stats? Maybe a better option would be to allow the menu to be opened but the egg gatcha to not be enabled while within the shop?
> > > 
> > > 
> > > They can just access the gacha and settings at the start of the next battle. I don't see why they'd have to do those things while in the shop.
> > 
> > 
> > Another option could be if someone wants to quit to restart - say they want to savescum and instead of reloading, they would normally quit to menu from within the shop menu? Or if you accidentally release a mon by accident and don't want to reload?
> > I bring this up because of a scenario I had earlier was that there was a bug that I found and I wanted to get my session data so I could raise a bug report. I went to open the menu from within the shop (where the bug appeared) and downloaded the session data. With this PR as is, I'd have to reload the page and get the session data from the start of the battle, whereas if you could disable the egg gacha from the menu during the shop, you'd still be able to do all this stuff, just without accessing the gacha?
> 
> I feel like it'd be a more confusing UX if the only time this menu didn't let you access the Gacha was from within the Shop. It absolutely will be perceived/reported as a bug. I always reset my save state by just reloading the game so it is interesting to hear it might be a legitimate issue for some people's experience.

I started out by getting into making daily guides - there's quite a lot of us that do it and are involved with it, but one of the things is being able to reset quickly if need be; when writing guides you need to make sure you've got good steps, and sometimes it happens that rng or skill goes badly and you need to reset. Most of the time this happens from within the battle itself, but for other times you might accidentally kill a mon you meant to catch, or you might try for some rerolls only to get nothing and need to reset within the shop. I know for a fact that the daily guide making community uses the quit to menu button from the shop every day (no pun intended!), so I know there's definitely people that do use it

2024-07-06 08:28 UTC, Nohbody commented
> > > > > One question I have about this is if people want to do things unrelated to egg gatcha in the shop - say changing some settings or looking at achievements/stats? Maybe a better option would be to allow the menu to be opened but the egg gatcha to not be enabled while within the shop?
> > > > 
> > > > 
> > > > They can just access the gacha and settings at the start of the next battle. I don't see why they'd have to do those things while in the shop.
> > > 
> > > 
> > > Another option could be if someone wants to quit to restart - say they want to savescum and instead of reloading, they would normally quit to menu from within the shop menu? Or if you accidentally release a mon by accident and don't want to reload?
> > > I bring this up because of a scenario I had earlier was that there was a bug that I found and I wanted to get my session data so I could raise a bug report. I went to open the menu from within the shop (where the bug appeared) and downloaded the session data. With this PR as is, I'd have to reload the page and get the session data from the start of the battle, whereas if you could disable the egg gacha from the menu during the shop, you'd still be able to do all this stuff, just without accessing the gacha?
> > 
> > 
> > I feel like it'd be a more confusing UX if the only time this menu didn't let you access the Gacha was from within the Shop. It absolutely will be perceived/reported as a bug. I always reset my save state by just reloading the game so it is interesting to hear it might be a legitimate issue for some people's experience.
> 
> I started out by getting into making daily guides - there's quite a lot of us that do it and are involved with it, but one of the things is being able to reset quickly if need be; when writing guides you need to make sure you've got good steps, and sometimes it happens that rng or skill goes badly and you need to reset. Most of the time this happens from within the battle itself, but for other times you might accidentally kill a mon you meant to catch, or you might try for some rerolls only to get nothing and need to reset within the shop. I know for a fact that the daily guide making community uses the quit to menu button from the shop every day (no pun intended!), so I know there's definitely people that do use it

Thanks for the insight. I will rework the pr to just grey out/disable the gacha while in the Shop instead.

2024-07-09 04:01 UTC, Nohbody commented
@Opaque02 Changes have been made. Does this work better for you?

2024-07-09 04:28 UTC, Nohbody commented
@flx-sta Can this be looked at again?

2024-07-11 03:44 UTC, Nohbody commented
@f-fsantos Merge conflict fixed.

2024-07-12 05:08 UTC, flx-sta requested changes

2024-07-12 05:08 UTC, flx-sta commented on src/ui/menu-ui-handler.ts
> +        const nextOption = addTextObject(this.scene, 0, i*16, i18next.t(`menuUiHandler:${MenuOptions[o]}`), TextStyle.WINDOW);
What does the `*16` stand for ?

2024-07-12 05:08 UTC, flx-sta commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
Is this a not 0 check ? If so please clarify the code.

is mode chain guranteed set ? Or can it be undefined ? If so add a null check

2024-07-12 19:14 UTC, Nohbody commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
What do you mean clarify the code? It's a length 0 check. modeChain is initialized as an empty array as part of the TypeScript declaration.

2024-07-12 19:28 UTC, Nohbody commented on src/ui/menu-ui-handler.ts
> +        const nextOption = addTextObject(this.scene, 0, i*16, i18next.t(`menuUiHandler:${MenuOptions[o]}`), TextStyle.WINDOW);
I replaced both with a const named OPTION_HEIGHT. However, it's a bit of a misnomer because the actual text height is controlled by the Text Style, but this will control the size of the placement of the option and where the cursor points anyways (effective the option's rectangle).

2024-07-12 19:39 UTC, flx-sta commented on src/ui/menu-ui-handler.ts
> +        const nextOption = addTextObject(this.scene, 0, i*16, i18next.t(`menuUiHandler:${MenuOptions[o]}`), TextStyle.WINDOW);
fine by me. resolved

2024-07-13 01:31 UTC, Nohbody commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
This is less performant because Javascript is not a compiler-optimized language.

2024-07-13 01:56 UTC, f-fsantos commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
We value readability over performance.

2024-07-13 02:09 UTC, Nohbody commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
This is readable though? This is a pretty standard way to do this.

2024-07-13 02:10 UTC, Nohbody commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
Other people have already done it this way in this codebase.

https://github.com/search?q=repo%3Apagefaultgames%2Fpokerogue%20.length)&type=code

2024-07-13 16:46 UTC, Madmadness65 approved these changes
lgtm, disabling the egg gacha option was definitely a better call than disabling the menu all together.

2024-07-13 23:35 UTC, f-fsantos commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
I'm still adamant on this change. 
Length is not a boolean value and we shouldn't do things around the silliness that javascript allows us to do. I understand there are more examples on the whole repo and even in this PR there's another one that wasn't explicitly called out, but this is something we should improve rather than sustain. All the other cases should also change and I hope to tackle them at some point.

But for now, please change both if ...length) to be explicit about what you are creating the condition around.

2024-07-13 23:36 UTC, f-fsantos requested changes
Please change both if ...length) to be explicit about what you are creating the condition around.

2024-07-14 08:35 UTC, Nohbody commented
> Please change both if ...length) to be explicit about what you are creating the condition around.

I'm not making my code explicitly worse. There's nothing "less readable" about using a length check like I wrote it.

2024-07-14 08:41 UTC, Nohbody commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
This isn't "silliness that javascript allows us do". This is how conditional checks work in the vast majority of programming languages. 0 === false, everything else === true.

2024-07-14 08:48 UTC, Nohbody commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
I literally did not commit `if (this.scene.gameData.eggs.length)`. Someone else who knows how a conditional check works wrote that.

2024-07-14 09:24 UTC, CodeTappert commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
While you are correct that your apporach is correct in javascript. Not everybody knows this concept. For example i work mainly with golang which hasnt those kinds of checks.

Please make the change requested. It does not change the functionality of your code and help other, non javascript experts, to better understand. 

Also a lot of languages (go, c++, c# etc) dont allow the implicit conversion of non boolean types to boolean types. This is why your code, while correct in a javascript world, may confuse other developers that arent experts.

2024-07-14 09:24 UTC, CodeTappert commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
While you are correct that your apporach is correct in javascript. Not everybody knows this concept. For example i work mainly with golang which hasnt those kinds of checks.

Please make the change requested. It does not change the functionality of your code and help other, non javascript experts, to better understand. 

Also a lot of languages (go, c++, c# etc) dont allow the implicit conversion of non boolean types to boolean types. This is why your code, while correct in a javascript world, may confuse other developers that arent experts.

2024-07-14 19:15 UTC, Nohbody commented on src/ui/ui.ts
> +    if (this.modeChain.length) {
This isn't a repo written in go, c++, or c#. If you're contributing Javascript code you should know basic Javascript syntax. I don't know why we'd even attempt to try to do what you're suggesting. It's like writing a comment on every line explaining what everything does. Pointless fluff.

2024-07-16 18:40 UTC, flx-sta requested changes
Play-Test

The alpha is not updated properly

![in-shop](https://media.discordapp.net/attachments/1250836282926436413/1262840881573265409/image.png?ex=66980fb8&is=6696be38&hm=e086697ce8865e3d1a42d32d60b821a10a151fdf7900f13bde36867d4fa24530&=&format=webp&quality=lossless&width=1914&height=1114)
![next-wave after shop](https://media.discordapp.net/attachments/1250836282926436413/1262840881887711252/image.png?ex=66980fb8&is=6696be38&hm=a6d810ee4f206950298866b20ca93f7c614d238131abbdf0b0be5be416646e2a&=&format=webp&quality=lossless&width=1878&height=1116)

2024-07-16 21:54 UTC, Nohbody commented
@flx-sta Fixed.

2024-07-30 18:34 UTC, ben-lear commented
PR needs to be rebased

2024-08-02 17:27 UTC, f-fsantos commented
Closed by #3304

2024-08-02 17:27 UTC, closed without merging