French names for Abilities
pagefaultgames/pokerogue pull request #288
Opened 2024-04-25 13:49 UTC by Adri1

2024-04-25 17:22 UTC, Flashfyre requested changes

2024-04-25 17:22 UTC, Flashfyre commented on src/locales/fr/ability.ts
>    hospitality: {
What happened to the order here? Can we make sure it's the same as the English?

2024-04-25 17:36 UTC, Adri1 commented on src/locales/fr/ability.ts
>    hospitality: {
Everything's is here, just the order of my list of abilities comes directly form the order in SV datamine text files from which I generated the translation. And those are the only ones with a swapped order in PokéRogue's list, for some reason.
But in the end, it's the same thing and should be okay

2024-04-25 17:52 UTC, Adri1 commented on src/locales/fr/ability.ts
>    hospitality: {
Order restored

2024-04-26 01:23 UTC, Flashfyre requested changes

2024-04-26 01:23 UTC, Flashfyre commented on src/locales/fr/ability.ts
> -  toxicChain: {
Something still looks off here. Keys should be exactly the same to prevent desyncs. Toxic Chain is just missing here or moved elsewhere.

2024-04-26 10:13 UTC, Adri1 commented on src/locales/fr/ability.ts
> -  toxicChain: {
Order restored
It was there, but just the embodyAspect entries

2024-04-26 12:36 UTC, Flashfyre approved these changes

2024-04-26 12:36 UTC, merged