[Enhancement] Decouple accuracy calculation from phases.ts
pagefaultgames/pokerogue pull request #2899
Opened 2024-07-07 18:54 UTC by torranx

## What are the changes?
- see title

## Why am I doing these changes?
- cleaner phases file
- easier unit tests on move accuracy
- more maintainable

## What did change?
- see title

### Screenshots/Videos
n/a

## How to test the changes?
play the game/run unit tests

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-10 11:07 UTC, Corrade commented on src/phases.ts
> +    const moveAccuracy = this.move.getMove().calculateMoveAccuracy(user, target);
Could we move even more stuff from hitCheck() to calculateMoveAccuracy()?

For example, there happens to be a bug on line 3046 related to Lock-On and similar moves. I'd like to write a unit test to verify a fix. However, there's no easy way of doing this. I can't just verify that hitCheck() returns true since it could also return true by chance. I also can't use calculateMoveAcccuracy() because it doesn't involve the above line.

I'd suggest moving everything from hitCheck() into calculateMoveAccuracy() except the randomness roll, e.g. leaving hitCheck() to be something like:

```
  hitCheck(target: Pokemon): boolean {
    const moveAccuracy = this.calculateMoveAccuracy(target);
    return (moveAccuracy === -1)
      ? true
      : this.getUserPokemon().randSeedInt(100, 1) <= moveAccuracy;
  }
```

2024-07-10 12:43 UTC, torranx commented on src/phases.ts
> +    const moveAccuracy = this.move.getMove().calculateMoveAccuracy(user, target);
I'll check more on this when I have the time

2024-07-10 13:43 UTC, torranx commented on src/phases.ts
> +    const moveAccuracy = this.move.getMove().calculateMoveAccuracy(user, target);
done 😄 @Corrade

2024-07-10 23:20 UTC, f-fsantos requested changes
Is this being covered by existing unit tests? Can we add more on top of these changes?

2024-07-10 23:57 UTC, Corrade commented on src/phases.ts
> +    const moveAccuracy = this.move.getMove().calculateMoveAccuracy(user, target);
Tyvm! I agree with your point, although there's a use-case to extract the remaining stuff as well.

To be concrete, I'm writing unit tests for OHKO moves. I want to ensure they work with Lock-On, which your recent update would've permitted. But I also want to check that they're unaffected by the accuracy and evasion battle stats. To achieve that, we'd also need to extract that calculation, if not to calculateMoveAccuracy() then maybe to a different function?

2024-07-11 03:51 UTC, torranx commented on src/phases.ts
> +    const moveAccuracy = this.move.getMove().calculateMoveAccuracy(user, target);
> But I also want to check that they're unaffected by the accuracy and evasion battle stats.

won't the update I recently made already cover this?

2024-07-11 03:52 UTC, torranx commented
> Is this being covered by existing unit tests? Can we add more on top of these changes?

Wonder Skin unit test is one but I could add some more

2024-07-11 04:52 UTC, Corrade commented on src/phases.ts
> +    const moveAccuracy = this.move.getMove().calculateMoveAccuracy(user, target);
Oh sorry true. I think the Lock-On stuff remains unextracted though, i.e. line 3046.

2024-07-11 05:13 UTC, torranx commented on src/phases.ts
> +    const moveAccuracy = this.move.getMove().calculateMoveAccuracy(user, target);
I don't plan to extract those code in this PR because the context of this is move/pokemon accuracy. I also don't get why you can't test Lock-On with the way it is now, if you can enlighten me, please ping me on discord.

2024-07-11 10:11 UTC, Corrade commented on src/test/moves/double_team.test.ts
> +    expect(ally.summonData.battleStats[BattleStat.EVA]).toBe(0);
Might want to override ally and enemy abilities to be irrelevant (e.g. Ball Fetch) just in case there's something that can modify accuracy/evasion.

2024-07-11 10:55 UTC, torranx commented on src/test/moves/double_team.test.ts
> +    expect(ally.summonData.battleStats[BattleStat.EVA]).toBe(0);
that's already why I'm using magikarp. but I guess additional checks wont hurt

2024-07-11 10:55 UTC, torranx commented on src/test/arena/weather_fog.test.ts
> +    game.doAttack(getMovePosition(game.scene, 0, Moves.TACKLE));
it will hang to `CommandPhase` until timeout if `doAttack()` is missing

2024-07-11 10:55 UTC, torranx commented on src/phases.ts
>      }
Yeah I don't want to include that in this PR, feel free to open one for that.

2024-07-11 10:55 UTC, torranx commented on src/data/move.ts
> +    if (user.scene.arena.weather?.weatherType === WeatherType.FOG) {
Please do so.

2024-07-11 10:55 UTC, torranx commented on src/data/move.ts
> +   * @returns The calculated accuracy of the move.
While I agree that `-1` should be noted, I don't think this is the right place for that. `-1` is well all over the `move.ts` file, an enum would probably describe it better

2024-07-11 11:06 UTC, Corrade approved these changes
Pog

2024-07-15 21:50 UTC, f-fsantos approved these changes

2024-07-16 15:16 UTC, flx-sta commented on src/test/arena/arena_gravity.test.ts
> +  });
shouldn't the invert also be checked?
That it doesn't apply the 1.67 multiplier on non-OHKO moves?

2024-07-16 15:48 UTC, torranx commented on src/test/arena/arena_gravity.test.ts
> +  });
will add OHKO move test later

2024-07-16 15:48 UTC, torranx commented on src/test/arena/weather_fog.test.ts
> +  });
that shouldn't be part of fog test but a regular battle test imo

2024-07-16 19:21 UTC, flx-sta commented on src/test/arena/weather_fog.test.ts
> +  });
True.. true resolved ✅

2024-07-17 05:54 UTC, torranx commented on src/test/arena/arena_gravity.test.ts
> +  });
done @flx-sta

2024-07-17 15:03 UTC, flx-sta approved these changes
lgtm

@torranx FYI
Alternatively to this:
```ts
   vi.spyOn(moveToCheck, "calculateBattleAccuracy");
   //...
    expect(moveToCheck.calculateBattleAccuracy).toHaveReturnedWith(30);
```

You can also do this:
```ts
   const calculateBattleAccuracySpy = vi.spyOn(moveToCheck, "calculateBattleAccuracy");
   //...
    expect(calculateBattleAccuracySpy).toHaveReturnedWith(30);
```

I honestly didn't know the way you did it works but it makes sense. might actually prefer it as I'm not checking some odd spy var but rather the "original" one (at least by reading)

2024-07-22 15:14 UTC, merged