[Localization]Localized move-trigger text
pagefaultgames/pokerogue pull request #2913
Opened 2024-07-08 08:43 UTC by mercurius-00

## What are the changes?

Localized move-trigger text like:
- _"was damaged by the recoil!"_
- _" cut its own HP to power up its move!"_
- _"took {{targetName}}\ninto the sky!"_
- _"incinerated\n{{targetName}}'s {{itemName}}!"_
- _......_

## Why am I doing these changes?

It should be localized

## What did change?

- Extract the text from [data/move.ts](https://github.com/mercurius-00/pokerogue/blob/main/src/data/move.ts) to [locale/[language]/move-trigger.ts](https://github.com/mercurius-00/pokerogue/blob/main/src/locales/en/move-trigger.ts)
- Change some English text to match the original game.
- Translated zh-cn text.

### Screenshots/Videos

![1720427355327](https://github.com/pagefaultgames/pokerogue/assets/80205689/1a395cba-37da-4c9a-8692-a9a8b88c64c3)
![1720427256501](https://github.com/pagefaultgames/pokerogue/assets/80205689/469f09eb-9ab5-4e0b-b8a5-7536cac02fc8)

## How to test the changes?

1. set overrides.ts
`export const MOVESET_OVERRIDE: Array<Moves> = [Moves.SKY_DROP, Moves.BEAK_BLAST, Moves.MIND_BLOWN, Moves.STEEL_BEAM];`
2. run `npm run  start:dev`
3. enter a battle and use moves

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-07-08 14:08 UTC, EnochG1 requested changes
I suggested example with stoleItem (+ en locale)

2024-07-08 14:08 UTC, EnochG1 commented on src/data/move.ts
> +            user.scene.queueMessage(getPokemonMessage(user, i18next.t("moveTriggers:stoleItem", {targetName: target.name, ItemName: stolenItem.type.name})));
```suggestion
            user.scene.queueMessage(i18next.t("moveTriggers:stoleItem", {pokemonNameWithAffix: getPokemonNameWithAffix(user), targetName: target.name, ItemName: stolenItem.type.name}));
```

2024-07-08 14:08 UTC, EnochG1 commented on src/locales/en/move-trigger.ts
> +  "stoleItem": " stole\n{{targetName}}'s {{itemName}}!",
```suggestion
  "stoleItem": "{{pokemonNameWithAffix}} stole\n{{targetName}}'s {{itemName}}!",
```

2024-07-08 14:13 UTC, EnochG1 requested changes
You should localize with getPokemonName also (by put it to parameter).
If not, this makes translation difficult in languages with different word order.

in move.ts,
you can check "battle:battlerTagsCursedOnAdd" as sample, too.

2024-07-08 14:15 UTC, josericardo-fo commented on src/locales/pt_BR/move-trigger.ts
> +  "cannotUseMove": " cannot use {{moveName}}!"
```suggestion
  "hitWithRecoil" : " foi ferido pelo dano reverso!",
  "cutHpPowerUpMove": " diminuiu seus PS para aumentar o poder do ataque!",
  "absorbedElectricity": "absorveu eletricidade!",
  "switchedStatChanges": " trocou as mudanças de atributo com o alvo!",
  "goingAllOutForAttack": " está arriscando tudo nesse ataque!",
  "regainedHealth": " recuperou/nsaúde!",
  "keptGoingAndCrashed": " continuou/nindo e bateu!
  "fled": " fugiu!",
  "cannotBeSwitchedOut": " não pode ser trocado!",
  "swappedAbilitiesWithTarget": " trocou/nde habilidades com o alvo!",
  "coinsScatteredEverywhere": "Moedas foram espalhadas por toda parte!",
  "attackedByItem": "está prestes a ser atacado por {{itemName}}!",
  "whippedUpAWhirlwind": "criou\num redemoinho de vento!",
  "flewUpHigh": "voou\nbem alto!",
  "tookInSunlight": "absorveu a luz do sol!",
  "dugAHole": "cavou um buraco no chão!",
  "loweredItsHead": "abaixou sua cabeça!",
  "isGlowing": "ficou envolto em uma luz forte!",
  "bellChimed": "Um sino tocou!",
  "foresawAnAttack": "previu/num ataque!",
  "hidUnderwater": "se escondeu/nembaixo d'água!",
  "soothingAromaWaftedThroughArea": "Um aroma suave se espalhou pelo ambiente!",
  "sprangUp": "se levantou!",
  "choseDoomDesireAsDestiny": "escolheu\no Desejo da Perdição como seu destino!",
  "vanishedInstantly": "desapareceu/nde repente!",
  "tookTargetIntoSky": "levou {{targetName}}\npara o céu!",
  "becameCloakedInFreezingLight": "ficou envolto/nem uma luz congelante!",
  "becameCloakedInFreezingAir": "ficou envolto/nem ar congelante!",
  "isChargingPower": "está absorvendo energia!",
  "burnedItselfOut": " apagou seu próprio fogo!",
  "startedHeatingUpBeak": "começou\na esquentar seu bico!",
  "isOverflowingWithSpacePower": "está sobrecarregado\ncom energia espacial!",
  "usedUpAllElectricity": " usou toda a sua eletricidade!",
  "stoleItem": " roubou/no(a) {{itemName}} de {{targetName}}!",
  "incineratedItem": " incinerou\na {{itemName}} de {{targetName}}!",
  "knockedOffItem": " derrubou\no(a) {{itemName}} de {{targetName}}!",
  "tookMoveAttack": " pegou\no movimento {{moveName}}!",
  "cutOwnHpAndMaximizedStat": " reduziu seus PS\ne maximizou seu atributo de {{statName}}!",
  "copiedStatChanges": " {{userName}} copiou\nas mudanças de atributo de {{targetName}}!",
  "magnitudeMessage": "Magnitude {{magnitude}}!",
  "tookAimAtTarget": " mirou\nem {{targetName}}!",
  "transformedIntoType": " se transformou\nem tipo {{typeName}}!",
  "copiedMove": " copiou\no movimento {{moveName}}!",
  "sketchedMove": " desenhou\no movimento {{moveName}}!",
  "acquiredAbility": "{{pokemonName}} adquiriu\na habilidade {{abilityName}}!",
  "copiedTargetAbility": "{{userName}} copiou a habilidade\nde {{targetName}}!",
  "transformedIntoTarget": " se transformou\nem um(a) {{targetName}}!",
  "tryingToTakeFoeDown": " está tentando derrubar o atacante com ele!",
  "cannotUseMove": " não pode usar {{moveName}}!"
```

2024-07-10 03:48 UTC, josericardo-fo approved these changes

2024-07-10 04:32 UTC, EnochG1 reviewed
Korean Translation

2024-07-10 04:32 UTC, EnochG1 commented on src/locales/ko/move-trigger.ts
> +  "cannotUseMove": "{{pokemonName}} cannot use {{moveName}}!"
```suggestion
  "hitWithRecoil" : "{{pokemonName}}[[는]]\n반동으로 데미지를 입었다!",
  "cutHpPowerUpMove": "{{pokemonName}}[[는]]\n체력을 깎아서 자신의 기술을 강화했다!",
  "absorbedElectricity": "{{pokemonName}}[[는]]\n전기를 흡수했다!",
  "switchedStatChanges": "{{pokemonName}}[[는]] 상대와 자신의\n능력 변화를 바꿨다!",
  "goingAllOutForAttack": "{{pokemonName}}[[는]]\n전력을 다하기 시작했다!",
  "regainedHealth": "{{pokemonName}}[[는]]\n기력을 회복했다!",
  "keptGoingAndCrashed": "{{pokemonName}}[[는]]\n의욕이 넘쳐서 땅에 부딪쳤다!",
  "fled": "{{pokemonName}}[[는]]\N도망쳤다!",
  "cannotBeSwitchedOut": "{{pokemonName}}[[를]]\n돌아오게 할 수 없습니다!",
  "swappedAbilitiesWithTarget": "{{pokemonName}}[[는]]\n서로의 특성을 교체했다!",
  "coinsScatteredEverywhere": "돈이 주위에 흩어졌다!",
  "attackedByItem": "{{itemName}}[[가]]\n{{pokemonName}}에게 덤벼들었다!",
  "whippedUpAWhirlwind": "{{pokemonName}}의 주위에서\n공기가 소용돌이친다!",
  "flewUpHigh": "{{pokemonName}}[[는]]\n하늘 높이 날아올랐다!",
  "tookInSunlight": "{{pokemonName}}[[는]]\n빛을 흡수했다!",
  "dugAHole": "{{pokemonName}}[[는]]\n땅으로 파고들었다!",
  "loweredItsHead": "{{pokemonName}}[[는]]\n목을 움츠렸다!",
  "isGlowing": "{{pokemonName}}[[를]]\n강렬한 빛이 감쌌다!",
  "bellChimed": "방울소리가 울려 퍼졌다!",
  "foresawAnAttack": "{{pokemonName}}[[는]]\n미래의 공격을 예지했다!",
  "hidUnderwater": "{{pokemonName}}[[는]]\n물속에 몸을 숨겼다!",
  "soothingAromaWaftedThroughArea": "기분 좋은 향기가 퍼졌다!",
  "sprangUp": "{{pokemonName}}[[는]]\n높이 뛰어올랐다!",
  "choseDoomDesireAsDestiny": "{{pokemonName}}[[는]]\n파멸의소원을 미래에 맡겼다!",
  "vanishedInstantly": "{{pokemonName}}의 모습이\n일순간에 사라졌다!",
  "tookTargetIntoSky": "{{pokemonName}}[[는]] {{targetName}}[[를]]\n상공으로 데려갔다!",
  "becameCloakedInFreezingLight": "{{pokemonName}}[[는]]\n차가운 빛에 둘러싸였다!",
  "becameCloakedInFreezingAir": "{{pokemonName}}[[는]]\n차디찬 공기에 둘러싸였다!",
  "isChargingPower": "{{pokemonName}}[[는]]\n파워를 모으고 있다!",
  "burnedItselfOut": "{{pokemonName}}의 불꽃은 다 타 버렸다!",
  "startedHeatingUpBeak": "{{pokemonName}}[[는]]\n부리를 가열하기 시작했다!",
  "isOverflowingWithSpacePower": "{{pokemonName}}에게서\n우주의 힘이 넘쳐난다!",
  "usedUpAllElectricity": "{{pokemonName}}[[는]]\n전기를 다 써 버렸다!",
  "stoleItem": "{{pokemonName}}[[는]] {{targetName}}[[로]]부터\n{{itemName}}[[을]] 빼앗았다!",
  "incineratedItem": "{{pokemonName}} incinerated\n{{targetName}}'s {{itemName}}!",
  "knockedOffItem": "{{pokemonName}}[[는]] {{targetName}}의\n{{itemName}}[[를]] 탁 쳐서 떨구었다!",
  "tookMoveAttack": "{{pokemonName}}[[는]]\n{{moveName}} 공격을 끌어들였다!",
  "cutOwnHpAndMaximizedStat": "{{pokemonName}}[[는]] 체력을 깎아서\n{{stateName}}[[를]] 풀 파워로 만들었다!",
  "copiedStatChanges": "{{pokemonName}}[[는]] {{targetName}}의\n능력 변화를 복사했다!",
  "magnitudeMessage": "매그니튜드{{magnitude}}!",
  "tookAimAtTarget": "{{pokemonName}}[[는]] 목표를\n{{targetName}}[[로]] 결정했다!",
  "transformedIntoType": "{{pokemonName}}[[는]]\n{{typeName}}타입이 됐다!",
  "copiedMove": "{{pokemonName}}[[는]]\n{{moveName}}[[를]] 복사했다!",
  "sketchedMove": "{{pokemonName}}[[는]]\n{{moveName}}[[를]] 스케치했다!",
  "acquiredAbility": "{{pokemonName}}[[는]]\n{{abilityName}}[[가]] 되었다!",
  "copiedTargetAbility": "{{pokemonName}}[[는]] {{targerName}}의\n{{abilityName}}[[를]] 복사했다!",
  "transformedIntoTarget": "{{pokemonName}}[[는]]\n{{targetName}}[[로]] 변신했다!",
  "tryingToTakeFoeDown": "{{pokemonName}}[[는]] 상대를\n길동무로 삼으려 하고 있다!",
  "cannotUseMove": "{{pokemonName}}[[는]]\n{{moveName}}[[를]] 쓸 수 없다!"
```

2024-07-10 05:52 UTC, EnochG1 commented on src/locales/ko/move-trigger.ts
> +  "incineratedItem": "{{pokemonName}} incinerated\n{{targetName}}'s {{itemName}}!",
```suggestion
  "incineratedItem": "{{pokemonName}}[[는]] {{targetName}}의\n{{itemName}}[[를]] 불태워서 없애버렸다!",
```

2024-07-10 07:27 UTC, CodeTappert commented on src/data/move.ts
> +            user.scene.queueMessage(i18next.t("moveTriggers:stoleItem", {pokemonName: getPokemonNameWithAffix(user), targetName: target.name, ItemName: stolenItem.type.name}));
```suggestion
            user.scene.queueMessage(i18next.t("moveTriggers:stoleItem", {pokemonName: getPokemonNameWithAffix(user), targetName: getPokemonNameWithAffix(target), ItemName: stolenItem.type.name}));
```

The same for every other please

2024-07-10 07:54 UTC, mercurius-00 commented on src/data/move.ts
> +            user.scene.queueMessage(i18next.t("moveTriggers:stoleItem", {pokemonName: getPokemonNameWithAffix(user), targetName: target.name, ItemName: stolenItem.type.name}));
But in the original code, the targetName parameter uses target.name instead of getPokemonNameWithAffix(target). Sure it should be modified like this?"

2024-07-10 09:13 UTC, CodeTappert commented on src/locales/de/move-trigger.ts
> +} as const;
```suggestion
import { SimpleTranslationEntries } from "#app/interfaces/locales";

export const moveTriggers: SimpleTranslationEntries = {
  "hitWithRecoil" : "{{pokemonName}} erleidet Schaden durch Rückstoß!",
  "cutHpPowerUpMove": "{{pokemonName}} nutzt seine KP um seine Attacke zu verstärken!",
  "absorbedElectricity": "{{pokemonName}} absorbiert elektrische Energie!",
  "switchedStatChanges": "{{pokemonName}}tauschte die Statuswerteveränderungen mit dem Ziel!",
  "goingAllOutForAttack": "{{pokemonName}}legt sich ins Zeug!",
  "regainedHealth": "{{pokemonName}} erholt sich!",
  "keptGoingAndCrashed": "{{pokemonName}} springt daneben und verletzt sich!",
  "fled": "{{pokemonName}} ist geflüchtet!",
  "cannotBeSwitchedOut": "{{pokemonName}} kann nicht ausgewechselt werden!",
  "swappedAbilitiesWithTarget": "{{pokemonName}} tauscht Fähigkeiten mit dem Ziel!",
  "coinsScatteredEverywhere": "Es sind überall Münzen verstreut!",
  "attackedByItem": "{{pokemonName}} wird von seinem Item {{itemName}} angegriffen!",
  "whippedUpAWhirlwind": "{{pokemonName}} erzeugt eine Windböe!",
  "flewUpHigh": "{{pokemonName}} fliegt hoch empor!",
  "tookInSunlight": "{{pokemonName}} absorbiert Sonnenlicht!",
  "dugAHole": "{{pokemonName}} vergräbt sich in der Erde!",
  "loweredItsHead": "{{pokemonName}} zieht seinen Kopf ein!",
  "isGlowing": "{{pokemonName}} leuchtet grell!",
  "bellChimed": "Eine Glocke läutet!",
  "foresawAnAttack": "{{pokemonName}} sieht einen Angriff voraus!",
  "hidUnderwater": "{{pokemonName}} taucht unter!",
  "soothingAromaWaftedThroughArea": "Ein wohltuendes Aroma breitet sich aus!",
  "sprangUp": "{{pokemonName}} springt hoch in die Luft!",
  "choseDoomDesireAsDestiny": "{{pokemonName}} äußert einen Kismetwunsch für die Zukunft!",
  "vanishedInstantly": "{{pokemonName}} verschwindet augenblicklich!",
  "tookTargetIntoSky": "{{pokemonName}} entführt {{targetName}} in luftige Höhen!",
  "becameCloakedInFreezingLight": "{{pokemonName}} wird von einem kühlen Licht umhüllt!",
  "becameCloakedInFreezingAir": "{{pokemonName}} wird in klirrend kalte Luft gehüllt!",
  "isChargingPower": "{{pokemonName}} saugt Kraft in sich auf!",
  "burnedItselfOut": "{{pokemonName}} braucht sein Feuer komplett auf!",
  "startedHeatingUpBeak": "{{pokemonName}} erhitzt seinen Schnabel!",
  "isOverflowingWithSpacePower": "Kosmische Kräfte strömen aus {{pokemonName}}!",
  "usedUpAllElectricity": "{{pokemonName}} braucht seinen Strom komplett auf!",
  "stoleItem": "{{pokemonName}}  hat {{targetName}} das Item {{itemName}} geklaut!",
  "incineratedItem": "{{itemName}} von {{targetName}} ist verbrannt und somit nutzlos geworden!",
  "knockedOffItem": "{{pokemonName}} schlägt das Item {{itemName}} von {{targetName}} weg!",
  "tookMoveAttack": "{{pokemonName}} wurde von {{moveName}} getroffen!",
  "cutOwnHpAndMaximizedStat": "{{pokemonName}} nutzt seine KP und maximiert dadurch seinen {{stateName}}-Wert!",
  "copiedStatChanges": "{{pokemonName}} kopiert die Statusveränderungen von {{targetName}}!",
  "magnitudeMessage": "Intensität {{magnitude}}!",
  "tookAimAtTarget": "{{pokemonName}} zielt auf {{targetName}}!",
  "transformedIntoType": "{{pokemonName}} nimmt den Typ {{typeName}} an!",
  "copiedMove": "{{pokemonName}} kopiert {{moveName}}!",
  "sketchedMove": "{{pokemonName}} ahmt die Attacke {{moveName}} nach!",
  "acquiredAbility": "The {{pokemonName}} nimmt die Fähigkeit {{abilityName}} an!",
  "copiedTargetAbility": "{{pokemonName}} kopiert{{abilityName}} von  {{targerName}}!",
  "transformedIntoTarget": "{{pokemonName}} verwandelt sich in {{targetName}}!",
  "tryingToTakeFoeDown": "{{pokemonName}} versucht, den Angreifer mit sich zu nehmen!",
  "cannotUseMove": "{{pokemonName}} kann {{moveName}} nicht einsetzen!"
} as const;
```

2024-07-10 09:14 UTC, CodeTappert commented on src/data/move.ts
> +            user.scene.queueMessage(i18next.t("moveTriggers:stoleItem", {pokemonName: getPokemonNameWithAffix(user), targetName: target.name, ItemName: stolenItem.type.name}));
> But in the original code, {{targetName}} uses target.name instead of getPokemonNameWithAffix(target). Sure it should be modified like this?

Yes. The old code was just wrong. Please make the changes i suggested. If not sure ask Temp or Walker

2024-07-10 10:06 UTC, mercurius-00 commented on src/data/move.ts
> +            user.scene.queueMessage(i18next.t("moveTriggers:stoleItem", {pokemonName: getPokemonNameWithAffix(user), targetName: target.name, ItemName: stolenItem.type.name}));
fixed

2024-07-10 10:56 UTC, Adri1 reviewed
Added French

2024-07-10 10:56 UTC, Adri1 commented on src/locales/fr/move-trigger.ts
> +  "cannotUseMove": "{{pokemonName}} cannot use {{moveName}}!"
```suggestion
  "hitWithRecoil" : "{{pokemonName}} est blessé par le contrecoup !",
  "cutHpPowerUpMove": "{{pokemonName}} sacrifie des PV\net augmente la puissance ses capacités !",
  "absorbedElectricity": "{{pokemonName}} absorbe de l’électricité !",
  "switchedStatChanges": "{{pokemonName}} permute\nles changements de stats avec ceux de sa cible !",
  "goingAllOutForAttack": "{{pokemonName}} a pris\ncette capacité au sérieux !",
  "regainedHealth": "{{pokemonName}}\nrécupère des PV !",
  "keptGoingAndCrashed": "{{pokemonName}}\ns’écrase au sol !",
  "fled": "{{pokemonName}}\nprend la fuite !",
  "cannotBeSwitchedOut": "Impossible de rappeler {{pokemonName}}\nau combat.",
  "swappedAbilitiesWithTarget": "{{pokemonName}} et sa cible\néchangent leurs talents !",
  "coinsScatteredEverywhere": "Il pleut des pièces !",
  "attackedByItem": "{{pokemonName}} est attaqué\npar son propre objet {{itemName}} !",
  "whippedUpAWhirlwind": "{{pokemonName}}se prépare\nà lancer une bourrasque !",
  "flewUpHigh": "{{pokemonName}} s’envole !",
  "tookInSunlight": "{{pokemonName}}\nabsorbe la lumière !",
  "dugAHole": "{{pokemonName}}\nse cache dans le sol !",
  "loweredItsHead": "{{pokemonName}}\nbaisse la tête !",
  "isGlowing": "{{pokemonName}} est entouré\nd’une lumière intense !",
  "bellChimed": "Un grelot sonne !",
  "foresawAnAttack": "{{pokemonName}\nprévoit une attaque !",
  "hidUnderwater": "{{pokemonName}}\nse cache sous l’eau !",
  "soothingAromaWaftedThroughArea": "Une odeur apaisante flotte dans l’air !",
  "sprangUp": "{{pokemonName}}\nse propulse dans les airs !",
  "choseDoomDesireAsDestiny": "{{pokemonName}}souhaite\nle déclenchement de la capacité Vœu Destructeur !",
  "vanishedInstantly": "{{pokemonName}}\ndisparait instantanément !",
  "tookTargetIntoSky": "{{pokemonName}} emporte\n{{targetName}} haut dans le ciel !",
  "becameCloakedInFreezingLight": "{{pokemonName}} est baigné\nd’une lumière blafarde !",
  "becameCloakedInFreezingAir": "{{pokemonName}} est entouré\nd’un air glacial !",
  "isChargingPower": "{{pokemonName}}\nconcentre son énergie !",
  "burnedItselfOut": "Le feu intérieur de {{pokemonName}}\ns’est entièrement consumé !",
  "startedHeatingUpBeak": "{{pokemonName}}\nfait chauffer son bec !",
  "isOverflowingWithSpacePower": "La puissance du cosmos afflue dans le corps\nde {{pokemonName}} !",
  "usedUpAllElectricity": "{{pokemonName}}a utilisé\ntoute son électricité !",
  "stoleItem": "{{pokemonName}} vole\nl’objet {{itemName}} de {{targetName}} !",
  "incineratedItem": "{{pokemonName}} brule\nla {{itemName}} de {{targetName}} !",
  "knockedOffItem": "{{pokemonName}} fait tomber\nl’objet {{itemName}} de {{targetName}} !",
  "tookMoveAttack": "{{pokemonName}}\nsubit l’attaque {{moveName}} !",
  "cutOwnHpAndMaximizedStat": "{{pokemonName}} sacrifie des PV\net monte son {{stateName}} au maximum !",
  "copiedStatChanges": "{{pokemonName}} copie\nles changements de stats de {{targetName}} !",
  "magnitudeMessage": "Ampleur {{magnitude}} !",
  "tookAimAtTarget": "{{pokemonName}} vise\n{{targetName}} !",
  "transformedIntoType": "{{pokemonName}} prend\nle type {{typeName}} !",
  "copiedMove": "{{pokemonName}} copie\nla capacité {{moveName}} !",
  "sketchedMove": "{{pokemonName}} utilise Gribouille\npour copier {{moveName}} !",
  "acquiredAbility": "Le talent de {{pokemonName}}\ndevient {{abilityName}} !",
  "copiedTargetAbility": "{{pokemonName}} copie le talent\n{{abilityName}} de {{targerName}} !",
  "transformedIntoTarget": "{{pokemonName}} prend\nl’apparence de {{targetName}} !",
  "tryingToTakeFoeDown": "{{pokemonName}} veut entrainer\nson assaillant dans sa chute !",
  "cannotUseMove": "{{pokemonName}} ne peut pas\nutiliser la capacité {{moveName}} !"
```

2024-07-12 16:19 UTC, CodeTappert approved these changes

2024-07-12 16:23 UTC, merged