[Localization] Localize ability messages in ability.ts (trigger, apply...)
pagefaultgames/pokerogue pull request #2972
Opened 2024-07-11 07:30 UTC by EnochG1

## What are the changes?
Add the option to localize message text of ability events.

## Why am I doing these changes?
All text should be localizable.

## What did change?
 - Change the code for localize > src/data/ability.ts
 - Added localization keys in each language folders. (ability-trigger.ts) > missed key included.

### Screenshots/Videos
TBD

## How to test the changes?
Manually (Using override.ts)

### Note : message key and possible abilities matching list

<details>
<summary>**Click to expand/collapse**</summary>
typeImmunityHeal : VOLT_ABSORB, WATER_ABSORB, DRY_SKIN, EARTH_EATER
nonSuperEffectiveImmunity : WONDER_GUARD
postDefendDisguise : DISGUISE
reverseDrain : LIQUID_OOZE
postDefendTypeChange : COLOR_CHANGE
postDefendContactDamage : ROUGH_SKIN, IRON_BARBS
postDefendAbilitySwap : WANDERING_SPIRIT
postDefendAbilityGive : MUMMY, LINGERING_AROMA
postDefendMoveDisable : CURSED_BODY
pokemonTypeChange : PROTEAN, LIBERO
postAttackStealHeldItem : MAGICIAN
postDefendStealHeldItem : PICKPOCKET
copyFaintedAllyAbility : RECEIVER, POWER_OF_ALCHEMY
intimidateImmunity : OBLIVIOUS, OWN_TEMPO, INNER_FOCUS, SCRAPPY
postSummonAllyHeal : HOSPITALITY
postSummonClearAllyStats : CURIOUS_MEDICINE
postSummonTransform : IMPOSTER
protectStat : CLEAR_BODY, ILLUMINATE, KEEN_EYE, HYPER_CUTTER, WHITE_SMOKE, BIG_PECKS, FULL_METAL_BODY, MINDS_EYE
statusEffectImmunityWithName, statusEffectImmunity : LIMBER, INSOMNIA, IMMUNITY, MAGMA_ARMOR, WATER_VEIL, VITAL_SPIRIT, LEAF_GUARD, SWEET_VEIL, WATER_BUBBLE, COMATOSE, PASTEL_VEIL, THERMAL_EXCHANGE, PURIFYING_SALT
battlerTagImmunity : OBLIVIOUS, INSOMNIA, OWN_TEMPO, INNER_FOCUS, VITAL_SPIRIT, SWEET_VEIL, COMATOSE
forewarn : FOREWARN
frisk : FRISK
postWeatherLapseHeal : RAIN_DISH, DRY_SKIN, ICE_BODY
postWeatherLapseDamage : DRY_SKIN, SOLAR_POWER
postTurnLootCreateEatenBerry : HARVEST
postTurnHeal : none yet
fetchBall : BALL_FETCH
healFromBerryUse : CHEEK_POUCH
arenaTrap : SHADOW_TAG, MAGNET_PULL, ARENA_TRAP
postBattleLoot : PICKUP
postFaintContactDamage : AFTERMATH
postFaintHpDamage : INNARDS_OUT
postSummonPressure : PRESSURE
postSummonMoldBreaker : MOLD_BREAKER
postSummonAnticipation : ANTICIPATION
postSummonTurboblaze : TURBOBLAZE
postSummonTeravolt : TERAVOLT
postSummonDarkAura : DARK_AURA
postSummonFairyAura : FAIRY_AURA
postSummonNeutralizingGas : NEUTRALIZING_GAS
postSummonAsOneGlastrier : AS_ONE_GLASTRIER
postSummonAsOneSpectrier : AS_ONE_SPECTRIER
postSummonVesselOfRuin : VESSEL_OF_RUIN
postSummonSwordOfRuin : SWORD_OF_RUIN
postSummonTabletsOfRuin : TABLETS_OF_RUIN
postSummonBeadsOfRuin : BEADS_OF_RUIN
</details>

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-11 12:06 UTC, CodeTappert commented on src/locales/de/ability-trigger.ts
> +  "postSummonBeadsOfRuin": "{{pokemonNameWithAffix}}'s Beads of Ruin lowered the {{statName}}\nof all surrounding Pokémon!",
```suggestion
  "perishBody": "Durch {{abilityName}} von {{pokemonName}} werden beide Pokémon nach drei Runden K.O. gehen!", 
  "poisonHeal": "{{abilityName}} von {{pokemonName}} füllte einige KP auf!",
  "trace": "{{pokemonName}} kopiert {{abilityName}} von {{targetName}}!",
  "windPowerCharged": "Der Treffer durch {{moveName}} läd die Stärke von {{pokemonName}} auf!",
  "quickDraw": "Durch Schnellschuss kann {{pokemonName}} schneller handeln als sonst!",
  "blockItemTheft": "{{abilityName}} von {{pokemonNameWithAffix}} verhindert Item-Diebstahl!",
  "typeImmunityHeal": "{{abilityName}} von {{pokemonNameWithAffix}} füllte einige KP auf!",
  "nonSuperEffectiveImmunity": "{{pokemonNameWithAffix}} vermeidet Schaden mit {{abilityName}}!",
  "postDefendDisguise": "Die Tarnung von {{pokemonNameWithAffix}} ist aufgeflogen!!",
  "reverseDrain": "{{pokemonNameWithAffix}} saugt Kloakensoße auf!",
  "postDefendTypeChange": "{{abilityName}} von {{pokemonNameWithAffix}} macht es zu einem {{typeName}}-Typ!",
  "postDefendContactDamage": "{{abilityName}} von {{pokemonNameWithAffix}} schadet seinem Angreifer!",
  "postDefendAbilitySwap": "{{pokemonNameWithAffix}} tauscht Fähigkeiten mit dem Ziel!",
  "postDefendAbilityGive": "{{pokemonNameWithAffix}} gibt seinem Ziel {{abilityName}}!",
  "postDefendMoveDisable": "{{moveName}} von {{pokemonNameWithAffix}} wurde blockiert!",
  "pokemonTypeChange": "{{pokemonNameWithAffix}} nimmt den Typ {{moveType}} an!",
  "postAttackStealHeldItem": "{{pokemonNameWithAffix}} stiehlt {{stolenItemType}} von {{defenderName}}!",
  "postDefendStealHeldItem": "{{pokemonNameWithAffix}} stiehlt {{stolenItemType}} von {{attackerName}}!",
  "copyFaintedAllyAbility": "Die Fähigkeit {{abilityName}} von {{pokemonNameWithAffix}} wurde übernommen!",
  "intimidateImmunity": "{{abilityName}} von {{pokemonNameWithAffix}} verhindert den Effekt von Bedroher!",
  "postSummonAllyHeal": "{{pokemonNameWithAffix}} trinkt den von {{pokemonName}} zubereiteten Tee!",
  "postSummonClearAllyStats": "Die Statusveränderungen von {{pokemonNameWithAffix}} wurden aufgehoben!",
  "postSummonTransform": "{{pokemonNameWithAffix}} verwandelt sich in ${targetName}!",
  "protectStat": "{{abilityName}} von {{pokemonNameWithAffix}} verhindert das der Statuswert {{statName}} gesenkt wird!",
  "statusEffectImmunityWithName": "{{abilityName}} von {{pokemonNameWithAffix}} verhindert {{statusEffectName}}!",
  "statusEffectImmunity": "{{abilityName}} von {{pokemonNameWithAffix}} verhindert Statusprobleme",
  "battlerTagImmunity": "{{abilityName}} von {{pokemonNameWithAffix}} verhindert {{battlerTagName}}!",
  "forewarn": "Vorwarnung von {{pokemonNameWithAffix}}: Konzentraion auf {{moveName}}!",
  "frisk": "{{pokemonNameWithAffix}} hat die Fähigkeit {{opponentAbilityName}} von  {{opponentName}} erschnüffelt!",
  "postWeatherLapseHeal": "{{abilityName}} von {{pokemonName}} füllte einige KP auf!",
  "postWeatherLapseDamage": "{{pokemonNameWithAffix}} wurde durch {abilityName}} verletzt!",
  "postTurnLootCreateEatenBerry": "{{pokemonNameWithAffix}} hat {{berryName}} geerntet!",
  "postTurnHeal": "{{abilityName}} von {{pokemonName}} füllte einige KP auf!",
  "fetchBall": "{{pokemonNameWithAffix}} hat einen {{pokeballName}} gefunden!",
  "healFromBerryUse": "{{abilityName}} von {{pokemonName}} füllte einige KP auf!",
  "arenaTrap": "{{abilityName}} von {{pokemonNameWithAffix}} verhindert den Tausch!",
  "postBattleLoot": "{{pokemonNameWithAffix}} hebt {{itemName}} auf!",
  "postFaintContactDamage": "{{abilityName}} von {{pokemonNameWithAffix}} schadet seinem Angreifer!",
  "postFaintHpDamage": "{{abilityName}} von {{pokemonNameWithAffix}} schadet seinem Angreifer!",
  "postSummonPressure": "{{pokemonNameWithAffix}} setzt Gegner mit Erzwinger unter Druck!",
  "postSummonMoldBreaker": "{{pokemonNameWithAffix}} gelingt es, gegnerische Fähigkeiten zu überbrücken!",
  "postSummonAnticipation": "{{pokemonNameWithAffix}} erschaudert!",
  "postSummonTurboblaze": "{{pokemonNameWithAffix}} strahlt eine lodernde Aura aus!",
  "postSummonTeravolt": "{{pokemonNameWithAffix}} strahlt eine knisternde Aura aus!",
  "postSummonDarkAura": "{{pokemonNameWithAffix}} strahlt eine dunkle Aura aus!",
  "postSummonFairyAura": "{{pokemonNameWithAffix}} strahlt eine Feenaura aus!",
  "postSummonNeutralizingGas": "Reaktionsgas von {{pokemonNameWithAffix}} hat sich in der Umgebung ausgebreitet!",
  "postSummonAsOneGlastrier": "{{pokemonNameWithAffix}} verfügt über zwei Fähigkeiten!",
  "postSummonAsOneSpectrier": "{{pokemonNameWithAffix}} verfügt über zwei Fähigkeiten!",
  "postSummonVesselOfRuin": "Unheilsgefäß von {{pokemonNameWithAffix}} schwächt {{statName}} aller Pokémon im Umkreis!",
  "postSummonSwordOfRuin": "Unheilsschwert von {{pokemonNameWithAffix}} schwächt {{statName} aller Pokémon im Umkreis!",
  "postSummonTabletsOfRuin": "Unheilstafeln von {{pokemonNameWithAffix}} schwächt {{statName}} aller Pokémon im Umkreis!",
  "postSummonBeadsOfRuin": "Unheilsjuwelen von {{pokemonNameWithAffix}} schwächt {{statName}} aller Pokémon im Umkreis!",
```

2024-07-11 15:12 UTC, CodeTappert commented on src/locales/de/ability-trigger.ts
> +  "moveImmunity": "It doesn't affect {{pokemonNameWithAffix}}!",
```suggestion
  "moveImmunity": "Es hat keine Wirkung auf {{pokemonNameWithAffix}}...",
```

2024-07-11 22:30 UTC, NicusPulcis commented
@EnochG1 i've sent a partial PR for the italian localization, sadly didn't get much time to work on it today but defo getting it done tomorrow

2024-07-12 04:19 UTC, mercurius-00 requested changes
update zh-cn

2024-07-12 04:19 UTC, mercurius-00 commented on src/locales/zh_CN/ability-trigger.ts
> +  "postSummonBeadsOfRuin": "{{pokemonNameWithAffix}}'s Beads of Ruin lowered the {{statName}}\nof all surrounding Pokémon!",
"perishBody": "因为{{pokemonName}}的{{abilityName}}\n双方将在3回合后灭亡！",
  "poisonHeal": "{{pokemonName}}因{{abilityName}}\n回复了少许HP！",
  "trace": "{{pokemonName}}复制了{{targetName}}的\n{{abilityName}}！",
  "windPowerCharged": "受{{moveName}}的影响，{{pokemonName}}提升了能力！",
  "quickDraw":"因为速击效果发动，\n{{pokemonName}}比平常出招更快了！",
  "blockItemTheft": "{{pokemonNameWithAffix}}的{{abilityName}}\n阻止了对方夺取道具！",
  "typeImmunityHeal": "{{pokemonNameWithAffix}}因{{abilityName}}\n回复了少许HP！",
  "nonSuperEffectiveImmunity": "{{pokemonNameWithAffix}}因{{abilityName}}\n避免了伤害！",
  "postDefendDisguise": "{{pokemonNameWithAffix}}的\n画皮脱落了",
  "moveImmunity": "对{{pokemonNameWithAffix}}没有效果！",
  "reverseDrain": "{{pokemonNameWithAffix}}\n吸到了污泥浆！",
  "postDefendTypeChange": "{{pokemonNameWithAffix}}因{{abilityName}}\n变成了{{typeName}}属性！",
  "postDefendContactDamage": "{{pokemonNameWithAffix}}的{{abilityName}}\n使对方受到了伤害！",
  "postDefendAbilitySwap": "{{pokemonNameWithAffix}}\n互换了各自的特性！",
  "postDefendAbilityGive": "因为{{pokemonNameWithAffix}}\n对方的特性变成了{{abilityName}}！",
  "postDefendMoveDisable": "封住了{{pokemonNameWithAffix}}的\n{{moveName}}！",
  "pokemonTypeChange": "{{pokemonNameWithAffix}}\n变成了{{moveType}}属性！",
  "postAttackStealHeldItem": "{{pokemonNameWithAffix}}从{{defenderName}}那里\n夺取了{{stolenItemType}}！",
  "postDefendStealHeldItem": "{{pokemonNameWithAffix}}从{{attackerName}}那里\n夺取了{{stolenItemType}}！",
  "copyFaintedAllyAbility": "继承了{{pokemonNameWithAffix}}的\n{{abilityName}}！",
  "intimidateImmunity": "{{pokemonNameWithAffix}}因{{abilityName}}没有受到威吓！",
  "postSummonAllyHeal": "{{pokemonNameWithAffix}}喝光了\n{{pokemonName}}泡的茶！",
  "postSummonClearAllyStats": "{{pokemonNameWithAffix}}的\n能力变化消失了！",
  "postSummonTransform": "{{pokemonNameWithAffix}}\n变身成了{{targetName}}！",
  "protectStat": "因{{pokemonNameWithAffix}}的{{abilityName}}\n{{statName}}不会降低！",
  "statusEffectImmunityWithName": "{{pokemonNameWithAffix}}因{{abilityName}}\n{{statusEffectName}}没有效果！",
  "statusEffectImmunity": "{{pokemonNameWithAffix}}因{{abilityName}}\n异常状态没有效果！",
  "battlerTagImmunity": "{{pokemonNameWithAffix}}因{{abilityName}}\n而不会{{battlerTagName}}！",
  "forewarn": "{{pokemonNameWithAffix}}读取了\n{{moveName}}！",
  "frisk": "{{pokemonNameWithAffix}}察觉到了\n{{opponentName}}的{{opponentAbilityName}}！",
  "postWeatherLapseHeal": "{{pokemonNameWithAffix}}因{{abilityName}}\n回复了少许HP！",
  "postWeatherLapseDamage": "{{pokemonNameWithAffix}}\n因{abilityName}}而受到了伤害！",
  "postTurnLootCreateEatenBerry": "{{pokemonNameWithAffix}}\n收获了{{berryName}}！",
  "postTurnHeal": "{{pokemonNameWithAffix}}因{{abilityName}}\n回复了少许HP！",
  "fetchBall": "{{pokemonNameWithAffix}}\n捡回了{{pokeballName}}！",
  "healFromBerryUse": "{{pokemonNameWithAffix}}因{{abilityName}}\n回复了HP！",
  "arenaTrap": "因{{pokemonNameWithAffix}}的{{abilityName}}\n而无法进行替换！",
  "postBattleLoot": "{{pokemonNameWithAffix}}捡到了\n{{itemName}}！",
  "postFaintContactDamage": "{{pokemonNameWithAffix}}的{{abilityName}}\n使对方受到了伤害！",
  "postFaintHpDamage": "{{pokemonNameWithAffix}}的{{abilityName}}\n使对方受到了伤害！",
  "postSummonPressure": "从{{pokemonNameWithAffix}}的身上\n感到了一种压迫感！",
  "postSummonMoldBreaker": "{{pokemonNameWithAffix}}\n打破了常规！",
  "postSummonAnticipation": "{{pokemonNameWithAffix}}\n发抖了！",
  "postSummonTurboblaze": "{{pokemonNameWithAffix}}\n正在释放炽焰气场！",
  "postSummonTeravolt": "{{pokemonNameWithAffix}}\n正在释放溅射气场！",
  "postSummonDarkAura": "{{pokemonNameWithAffix}}\n正在释放暗黑气场！",
  "postSummonFairyAura": "{{pokemonNameWithAffix}}\n正在释放妖精气场！",
  "postSummonNeutralizingGas": "周围充满了\n{{pokemonNameWithAffix}}的化学变化气体！",
  "postSummonAsOneGlastrier": "{{pokemonNameWithAffix}}\n同时拥有了两种特性！",
  "postSummonAsOneSpectrier": "{{pokemonNameWithAffix}}\n同时拥有了两种特性！",
  "postSummonVesselOfRuin": "{{pokemonNameWithAffix}}的灾祸之鼎\n令周围的宝可梦的{{statName}}减弱了！",
  "postSummonSwordOfRuin": "{{pokemonNameWithAffix}}的灾祸之剑\n令周围的宝可梦的{{statName}}减弱了！",
  "postSummonTabletsOfRuin": "{{pokemonNameWithAffix}}的灾祸之简\n令周围的宝可梦的{{statName}}减弱了！",
  "postSummonBeadsOfRuin": "{{pokemonNameWithAffix}}的灾祸之玉\n令周围的宝可梦的{{statName}}减弱了！",

2024-07-12 11:13 UTC, EnochG1 commented on src/data/ability.ts
> +    return i18next.t("abilityTriggers:blockRecoilDamage", {pokemonNameWithAffix: getPokemonNameWithAffix(pokemon), abilityName: abilityName});
```suggestion
    return i18next.t("abilityTriggers:blockRecoilDamage", {pokemonName: getPokemonNameWithAffix(pokemon), abilityName: abilityName});
```

2024-07-12 15:23 UTC, NicusPulcis commented
hey @EnochG1 i've pushed another partial PR, sadly don't think i'll be able to get the whole thing translated today but i'll be trying my best in these days to complete it ASAp

2024-07-13 12:46 UTC, Adri1 reviewed
Added French

2024-07-13 12:46 UTC, Adri1 commented on src/locales/fr/ability-trigger.ts
> +  "postSummonBeadsOfRuin": "{{pokemonNameWithAffix}}'s Beads of Ruin lowered the {{statName}}\nof all surrounding Pokémon!",
```suggestion
  "quickDraw": "Tif Vif permet à {{pokemonName}}\nd’agir plus vite que d’habitude !",
  "blockItemTheft": "{{abilityName}} de {{pokemonNameWithAffix}}\nempêche son objet d’être volé !",
  "typeImmunityHeal": "{{abilityName}} de {{pokemonNameWithAffix}}\nrestaure un peu ses PV !",
  "nonSuperEffectiveImmunity": "{{pokemonNameWithAffix}} évite\nles dégâts avec {{abilityName}} !",
  "postDefendDisguise": "Le déguisement de {{pokemonNameWithAffix}}\ntombe !",
  "moveImmunity": "Ça n'affecte pas {{pokemonNameWithAffix}}…",
  "reverseDrain": "{{pokemonNameWithAffix}} aspire\nle suintement !",
  "postDefendTypeChange": "{{abilityName}} de {{pokemonNameWithAffix}}\nle transforme en type {{typeName}} !",
  "postDefendContactDamage": "{{pokemonNameWithAffix}} est blessé\npar son talent {{abilityName}} !",
  "postDefendAbilitySwap": "{{pokemonNameWithAffix}} et sa cible\néchangent leurs talents !",
  "postDefendAbilityGive": "{{pokemonNameWithAffix}} donne\nle talent {{abilityName}} à sa cible !",
  "postDefendMoveDisable": "La capacité {{moveName}}\nde {{pokemonNameWithAffix}} est mise sous entrave !",
  "pokemonTypeChange": "{{pokemonNameWithAffix}} prend\nle type {{moveType}} !",
  "postAttackStealHeldItem": "{{pokemonNameWithAffix}} vole\nl’objet {{stolenItemType}} de {{defenderName}} !",
  "postDefendStealHeldItem": "{{pokemonNameWithAffix}} vole\nl’objet {{stolenItemType}} de {{attackerName}} !",
  "copyFaintedAllyAbility": "{{pokemonNameWithAffix}} reçoit\nle talent {{abilityName}} !",
  "intimidateImmunity": "{{abilityName}} de {{pokemonNameWithAffix}}\nl’empêche d'être intimidé !",
  "postSummonAllyHeal": "{{pokemonNameWithAffix}} boit le thé\npréparé par {{pokemonName}} !",
  "postSummonClearAllyStats": "Les stats de {{pokemonNameWithAffix}}\nsont revenues à la normale !",
  "postSummonTransform": "{{pokemonNameWithAffix}} prend\nl’apparence de {{targetName}} !",
  "protectStat": "{{abilityName}} de {{pokemonNameWithAffix}}\nempêche {{statName}} de baisser !",
  "statusEffectImmunityWithName": "{{abilityName}} de {{pokemonNameWithAffix}}\nl’empêche d’être {{statusEffectName}} !",
  "statusEffectImmunity": "{{abilityName}} de {{pokemonNameWithAffix}}\nempêche tout problème de statut !",
  "battlerTagImmunity": "{{abilityName}} de {{pokemonNameWithAffix}}\nempêche {{battlerTagName}}!",
  "forewarn": "La capacité {{moveName}}\nde {{pokemonNameWithAffix}} a été détectée !",
  "frisk": "{{pokemonNameWithAffix}} fouille {{opponentName}}\net trouve son talent {{opponentAbilityName}} !",
  "postWeatherLapseHeal": "{{abilityName}} de {{pokemonNameWithAffix}}\nrestaure un peu ses PV !",
  "postWeatherLapseDamage": "{{pokemonNameWithAffix}} est blessé\npar son talent {{abilityName}} !",
  "postTurnLootCreateEatenBerry": "{{pokemonNameWithAffix}} a récolté\nune {{berryName}} !",
  "postTurnHeal": "{{abilityName}} de {{pokemonNameWithAffix}}\nrestaure un peu ses PV !",
  "fetchBall": "{{pokemonNameWithAffix}} trouve\nune {{pokeballName}} !",
  "healFromBerryUse": "{{abilityName}} de {{pokemonNameWithAffix}}\nrestaure un peu ses PV !",
  "arenaTrap": "{{pokemonNameWithAffix}} empêche\nles changements grâce à son talent {{abilityName}} !",
  "postBattleLoot": "{{pokemonNameWithAffix}} ramasse\nl’objet {{itemName}} !",
  "postFaintContactDamage": "{{pokemonNameWithAffix}} est blessé\npar son talent {{abilityName}} !",
  "postFaintHpDamage": "{{pokemonNameWithAffix}} est blessé\npar son talent {{abilityName}} !",
  "postSummonPressure": "{{pokemonNameWithAffix}}\naugmente la pression !",
  "postSummonMoldBreaker": "{{pokemonNameWithAffix}}\nbrise le moule !",
  "postSummonAnticipation": "{{pokemonNameWithAffix}}\nest tout tremblant !",
  "postSummonTurboblaze": "{{pokemonNameWithAffix}} dégage\nune aura de flammes incandescentes !",
  "postSummonTeravolt": "{{pokemonNameWithAffix}} dégage\nune aura électrique instable !",
  "postSummonDarkAura": "{{pokemonNameWithAffix}} dégage\nune aura ténébreuse !",
  "postSummonFairyAura": "{{pokemonNameWithAffix}} dégage\nune aura enchanteresse !",
  "postSummonNeutralizingGas": "Le gaz inhibiteur {{pokemonNameWithAffix}}\nenvahit les lieux !",
  "postSummonAsOneGlastrier": "{{pokemonNameWithAffix}}\na deux talents !",
  "postSummonAsOneSpectrier": "{{pokemonNameWithAffix}}\na deux talents !",
  "postSummonVesselOfRuin": "L’Urne du Fléau de {{pokemonNameWithAffix}}\naffaiblit l’{{statName}} des Pokémon alentour !",
  "postSummonSwordOfRuin": "L’Épée du Fléau de {{pokemonNameWithAffix}}\naffaiblit la {{statName}} des Pokémon alentour !",
  "postSummonTabletsOfRuin": "Le Bois du Fléau de {{pokemonNameWithAffix}}\naffaiblit l’{{statName}} des Pokémon alentour !",
  "postSummonBeadsOfRuin": "Les Perles du Fléau de {{pokemonNameWithAffix}}\naffaiblissent la {{statName}} des Pokémon alentour !",
```

2024-07-13 13:36 UTC, josericardo-fo commented on src/locales/pt_BR/ability-trigger.ts
> +  "postSummonBeadsOfRuin": "{{pokemonNameWithAffix}}'s Beads of Ruin lowered the {{statName}}\nof all surrounding Pokémon!",
```suggestion
  "blockItemTheft": "{{abilityName}} de {{pokemonNameWithAffix}}\nprevine o roubo de itens!",
  "typeImmunityHeal": "{{abilityName}} de {{pokemonNameWithAffix}}\nrestaurou um pouco de PS!",
  "nonSuperEffectiveImmunity": "{{pokemonNameWithAffix}} evitou dano\ncom {{abilityName}}!",
  "postDefendDisguise": "O disfarce de {{pokemonNameWithAffix}} foi descoberto!",
  "moveImmunity": "Isso não afeta {{pokemonNameWithAffix}}!",
  "reverseDrain": "{{pokemonNameWithAffix}} absorveu a gosma líquida!",
  "postDefendTypeChange": "{{abilityName}} de {{pokemonNameWithAffix}}\ntransformou-o no tipo {{typeName}}!",
  "postDefendContactDamage": "{{abilityName}} de {{pokemonNameWithAffix}}\feriu seu adversário!",
  "postDefendAbilitySwap": "{{pokemonNameWithAffix}} trocou\nde habilidades com seu alvo!",
  "postDefendAbilityGive": "{{pokemonNameWithAffix}} deu a seu alvo\na habilidade {{abilityName}}!",
  "postDefendMoveDisable": "{{moveName}} de {{pokemonNameWithAffix}}\nfoi desabilitado!",
  "pokemonTypeChange": "{{pokemonNameWithAffix}} se transformou no tipo {{moveType}}!",
  "postAttackStealHeldItem": "{{pokemonNameWithAffix}} roubou\n{{stolenItemType}} de {defenderName}}!",
  "postDefendStealHeldItem": "{{pokemonNameWithAffix}} roubou\n{{stolenItemType}} de {{attackerName}}!",
  "copyFaintedAllyAbility": "A habilidade {{abilityName}} de {{pokemonNameWithAffix}} foi tomada!",
  "intimidateImmunity": "{{abilityName}} de {{pokemonNameWithAffix}} previniu-o(a) de ser intimidado(a)!",
  "postSummonAllyHeal": "{{pokemonNameWithAffix}} bebeu todo o\nchá mate que {{pokemonName}} fez!",
  "postSummonClearAllyStats": "As mudanças de atributo de {{pokemonNameWithAffix}}\nforam removidas!",
  "postSummonTransform": "{{pokemonNameWithAffix}} se transformou\nem {{targetName}}!",
  "protectStat": "{{abilityName}} de {{pokemonNameWithAffix}}\nprevine-o(a) de diminuir seu(sua) {{statName}}!",
  "statusEffectImmunityWithName": "{{pokemonNameWithAffix}} de {{abilityName}}\nprevine {{statusEffectName}}!",
  "statusEffectImmunity": "{{abilityName}} de {{pokemonNameWithAffix}}\nprevine condições de estado!",
  "battlerTagImmunity": "{{abilityName}} de {{pokemonNameWithAffix}}\nprevine {{battlerTagName}}!",
  "forewarn": "{{pokemonNameWithAffix}} foi avisado sobre {{moveName}}!",
  "frisk": "{{pokemonNameWithAffix}} inspecionou a habilidade {{opponentAbilityName}} de {{opponentName}}!",
  "postWeatherLapseHeal": "{{abilityName}} de {{pokemonNameWithAffix}}\nrestaurou um pouco de PS!",
  "postWeatherLapseDamage": "{{pokemonNameWithAffix}} foi ferido\npor seu(sua) {{abilityName}}!",
  "postTurnLootCreateEatenBerry": "{{pokemonNameWithAffix}} colheu uma {{berryName}}!",
  "postTurnHeal": "{{abilityName}} de {{pokemonNameWithAffix}}\nrestaurou um pouco de PS!",
  "fetchBall": "{{pokemonNameWithAffix}} encontrou uma\n{{pokeballName}}!",
  "healFromBerryUse": "{{abilityName}} de {{pokemonNameWithAffix}}\nrestaurou PS!",
  "arenaTrap": "{{abilityName}} de {{pokemonNameWithAffix}}\nprevine trocas!",
  "postBattleLoot": "{{pokemonNameWithAffix}} pegou um(a)\n{{itemName}}!",
  "postFaintContactDamage": "{{abilityName}} de {{pokemonNameWithAffix}}\nferiu seu adversário!",
  "postFaintHpDamage": "{{abilityName}} de {{pokemonNameWithAffix}}\nferiu seu adversário!",
  "postSummonPressure": "{{pokemonNameWithAffix}} está exercendo sua pressão!",
  "postSummonMoldBreaker": "{{pokemonNameWithAffix}} quebra o molde!",
  "postSummonAnticipation": "{{pokemonNameWithAffix}} se arrepiou!",
  "postSummonTurboblaze": "{{pokemonNameWithAffix}} está irradiando uma aura ardente!",
  "postSummonTeravolt": "{{pokemonNameWithAffix}} está irradiando uma aura explosiva!",
  "postSummonDarkAura": "{{pokemonNameWithAffix}} está irradiando uma aura sombria!",
  "postSummonFairyAura": "{{pokemonNameWithAffix}} está irradiando uma aura de fada!!",
  "postSummonNeutralizingGas": "O Neutralizing Gas de {{pokemonNameWithAffix}} se espalhou pelo campo de batalha!",
  "postSummonAsOneGlastrier": "{{pokemonNameWithAffix}} tem duas Habilidades!",
  "postSummonAsOneSpectrier": "{{pokemonNameWithAffix}} tem duas Habilidades!",
  "postSummonVesselOfRuin": "Vessel of Ruin de {{pokemonNameWithAffix}} reduziu o {{statName}}\nde todos os Pokémon em volta!",
  "postSummonSwordOfRuin": "Sword of Ruin de {{pokemonNameWithAffix}} reduziu a {{statName}}\nde todos os Pokémon em volta!",
  "postSummonTabletsOfRuin": "Tablets of Ruin de {{pokemonNameWithAffix}} reduziu o {{statName}}\nde todos os Pokémon em volta!",
  "postSummonBeadsOfRuin": "Beads of Ruin de {{pokemonNameWithAffix}} reduziu a {{statName}}\nde todos os Pokémon em volta!",
```

2024-07-13 18:19 UTC, CodeTappert approved these changes

2024-07-13 18:19 UTC, CodeTappert commented
Please merge beta in this branch to make the tests work

2024-07-13 19:46 UTC, Adri1 reviewed
French typo correction

2024-07-13 19:46 UTC, Adri1 commented on src/locales/fr/ability-trigger.ts
> +  "battlerTagImmunity": "{{abilityName}} de {{pokemonNameWithAffix}}\nempêche {{battlerTagName}}!",
```suggestion
  "battlerTagImmunity": "{{abilityName}} de {{pokemonNameWithAffix}}\nempêche {{battlerTagName}} !",
```

2024-07-14 00:31 UTC, EnochG1 commented
@mercurius-00 
Could you re-review this PR? (and approve?)
You 'request changes' so I committed your suggestion and request for review.

2024-07-14 06:57 UTC, CodeTappert approved these changes

2024-07-15 01:52 UTC, 40chyan approved these changes

2024-07-15 05:48 UTC, mercurius-00 approved these changes

2024-07-16 09:19 UTC, merged