[BUG] fixing multi-hit and move messages on faint
pagefaultgames/pokerogue pull request #2981
Opened 2024-07-11 18:42 UTC by DustinLin

## What are the changes?

the same as PR #2857 , but that was purged so reopening

2024-07-11 18:56 UTC, CodeTappert approved these changes

2024-07-12 04:32 UTC, flx-sta commented
Pull the latest beta branch to fix the failing tests

2024-07-14 13:41 UTC, torranx requested changes
I feel like a lot of the comments here were made for personal consumption when debugging the code. Also, please format the comments correctly. Another nit: instead of starting the sentence with "want...", using "We want..." is a lot better imo

2024-07-14 13:41 UTC, torranx commented on src/battle-scene.ts
>        this.phaseQueuePrepend.splice(this.phaseQueuePrependSpliceIndex, 0, phase);
These are all unnecessary comments - you're basically defining/describing JS array methods

2024-07-14 13:41 UTC, torranx commented on src/battle-scene.ts
> +    // populatePhaseQueue() adds a turnInit Phase at the end of phaseQueue (if the queue is emtpy)
["Rule 1: Comments should not duplicate the code"](https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/#h2-b7593c698a940)

2024-07-14 13:41 UTC, torranx commented on src/field/pokemon.ts
> +          // queue critical message before effectiveness
unnecessary comment

2024-07-14 13:41 UTC, torranx commented on src/field/pokemon.ts
> +          // create attack result and push to turnData
unnecessary comment

2024-07-14 13:41 UTC, torranx commented on src/phases.ts
> +    // Readability?: this function declaration honestly gets in the way of readability of what start() is doing , move either to beginning or end
unnecessary comment

2024-07-14 13:41 UTC, torranx commented on src/phases.ts
> +          // if there are multiple hits, or if there are hits of the multi-hit move left
unnecessary comments

2024-07-17 18:34 UTC, DustinLin commented on src/battle-scene.ts
> +    // populatePhaseQueue() adds a turnInit Phase at the end of phaseQueue (if the queue is emtpy)
will remove

2024-07-17 18:44 UTC, DustinLin commented
Removed some of the comments you suggested, yes I agree we can make the assumption that people know what these functions do/can look them up themselves

2024-07-22 17:44 UTC, merged