[Enhancement] Decouple move power calculation from Pokemon.apply(), Fixes Power Spot & Battery not boosting ally's move
pagefaultgames/pokerogue pull request #2984
Opened 2024-07-11 20:01 UTC by torranx

merged my branch from #2847 to here with beta as base branch

## What are the changes?
- **included fix for Power Spot and Battery not boosting the ally's move - this is discovered when replacing the `getMockedMovePower()`, hence more reason this needs to be added 😄**
- moved move power calculation to its own method
- updated tests for power value/multipliers to use the new method instead of mimicking its implementation
- **kept the original order of power calculation**

## Why am I doing these changes?
- avoid convuloted code
- easier and cleaner unit tests for move power

## What did change?
- refactor
- fix Power Spot and Battery

### Screenshots/Videos
n/a

## How to test the changes?
run unit tests or play the game

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-11 20:56 UTC, torranx commented on src/data/move.ts
> +      applyPreAttackAbAttrs(AllyMoveCategoryPowerBoostAbAttr, source.getAlly(), target, this, power);
`source` was the previous argument here, which broke the ability attribute - should be `source.getAlly()`

2024-07-12 02:52 UTC, OrangeRed requested changes

2024-07-12 02:52 UTC, OrangeRed commented on src/test/abilities/battery.test.ts
> +    const movePower = allMoves[moveToBeUsed].calculatePower(game.scene.getPlayerField()[0], game.scene.getEnemyField()[0]);
`scene.getPlayerPokemon()` returns the 0th index of the player field and the same goies for `scene.getEnemyPokemon()`

2024-07-12 02:52 UTC, OrangeRed commented on src/data/move.ts
> +    const power = new Utils.NumberHolder(this.power);
I don't like how `calculatePower()` and `this.power` have somewhat colliding names. Can you change `this.power` to be something like `this.basePower`

2024-07-12 03:01 UTC, torranx commented on src/test/abilities/battery.test.ts
> +    const movePower = allMoves[moveToBeUsed].calculatePower(game.scene.getPlayerField()[0], game.scene.getEnemyField()[0]);
yes I know that, I've used this instead to be more explicit and easier to read because `getPlayerPokemon` is not apparent to return the index 0

2024-07-12 03:19 UTC, torranx commented on src/data/move.ts
> +    const power = new Utils.NumberHolder(this.power);
I would be changing a lot of things if we decide to change the property name, and potentially breaking some things in the process if ever I miss something.

2024-07-12 03:21 UTC, OrangeRed commented on src/test/abilities/battery.test.ts
> +    const movePower = allMoves[moveToBeUsed].calculatePower(game.scene.getPlayerField()[0], game.scene.getEnemyField()[0]);
I am of the contrary opinion in that `scene.getPlayerField[0]` / `scene.getPlayerParty[0]` is harder to parse

2024-07-12 03:23 UTC, OrangeRed commented on src/data/move.ts
> +    const power = new Utils.NumberHolder(this.power);
It's not used in that many places what could go wrong with a simple F10 change all symbols :grimacing: 

![image](https://github.com/user-attachments/assets/91149a66-00ae-42a7-aa71-69c53218c035)

2024-07-12 03:35 UTC, torranx commented on src/data/move.ts
> +    const power = new Utils.NumberHolder(this.power);
Problem is we can's just find and replace `move.power`, there are other usages like move being stored in a variable or something like `move.getMove().power`. If you can suggest a better name for the method instead, that'll be safer 👌

2024-07-12 03:49 UTC, torranx commented on src/test/abilities/battery.test.ts
> +    const movePower = allMoves[moveToBeUsed].calculatePower(game.scene.getPlayerField()[0], game.scene.getEnemyField()[0]);
I guess we agree to disagree 😆 , if other people too will tell me otherwise, I'd be happy to update this

2024-07-12 08:02 UTC, mcmontag commented
Getting the move's max base power from its attribute using a helper method is totally unnecessary.  These are integration tests, and the whole point of factoring out power calculation is to make it so we can test a move's behavior without needing to know about its attributes.

We know it's supposed to have a max power of 100, simply because the move is Hard Press.

2024-07-12 15:07 UTC, mcmontag commented on src/test/moves/hard_press.test.ts
>    });
nitpick - I don't think this test is necessary.  If someone somehow managed to change the attributed used by this move to work for every enemy HP ratio except for 2, there's a very slim chance that this test would catch it.  On the other end, testing all 100 possible HP ratios is mega overkill.

If it were me, I'd test HP ratios of -1, 0, 1, 50, 100, and 101.  Key inputs within the bounds, and one input out of the expected bounds on each end.  1, 50, and 100 is probably fine, though.

2024-07-12 15:08 UTC, torranx commented
> Getting the move's max base power from its attribute using a helper method is totally unnecessary. These are integration tests, and the whole point of factoring out power calculation is to make it so we can test a move's behavior without needing to know about its attributes.
> 
> We know it's supposed to have a max power of 100, simply because the move is Hard Press.

Updated the code, I'm ~not~ ready for you to tear it apart 😆

2024-07-12 15:22 UTC, mcmontag commented on src/test/abilities/aura_break.test.ts
> +   */
Not sure I understand this comment.  Does using `.toBeCloseTo` instead of `.toBe` solve `This means we can't net the multiplier`?

2024-07-12 18:54 UTC, mcmontag approved these changes
Test changes LGTM - deferring to other reviewer(s) for power calculation refactor.

2024-07-12 18:55 UTC, mcmontag commented on src/test/abilities/aura_break.test.ts
> +   */
(noted in discord that `.toHaveReturnedWith(expect.closeTo(...))` is a more applicable suggestion; resolving as this is a nitpick anyway)

2024-07-12 21:27 UTC, OrangeRed requested changes

2024-07-12 21:27 UTC, OrangeRed commented on src/data/move.ts
> +    }
Checking `Pokemon.hasAbilityWithAttr()` here isn't necessary since that gets invoked inside the `applyAbilityInternals` function.

2024-07-12 21:27 UTC, OrangeRed commented on src/data/move.ts
> +    source.scene.applyModifiers(PokemonMultiHitModifier, source.isPlayer(), source, new Utils.IntegerHolder(0), power);
Can you check whether its safe to pass in null instead of a `new Utils.IntegerHolder`

2024-07-12 21:27 UTC, OrangeRed commented on src/test/abilities/aura_break.test.ts
> +    expect(moveToCheck.calculateBattlePower).toHaveReturnedWith(basePower * auraMultiplier * auraBreakMultiplier);
since you're using fractions here can you use `expect.closeTo()` to prevent any floating point errors

2024-07-12 21:27 UTC, OrangeRed commented on src/field/pokemon.ts
> -        }
Are you handling this change correctly? By moving this inside of the calculate function `typeBoost.oneUse` tags will be consumed even if the move fails / is cancelled which is not what happens currently

2024-07-13 07:40 UTC, torranx commented on src/field/pokemon.ts
> -        }
All power calculation inside that `else` statement can be moved out safely because it's the end value that is only being consumed (part of damage calculation).

2024-07-13 08:02 UTC, torranx commented on src/data/move.ts
> +    source.scene.applyModifiers(PokemonMultiHitModifier, source.isPlayer(), source, new Utils.IntegerHolder(0), power);
Tried testing this but the game breaks when setting overrides for `ITEM_REWARD_OVERRIDE` or `STARTING_MODIFIER_OVERRIDE`. We can probably move this into another PR.

2024-07-13 16:22 UTC, OrangeRed commented on src/field/pokemon.ts
> -        }
Doesn't this particular block only trigger if the move has not been cancelled?
By moving this inside of calculatePower which happens before the is cancelled check you will sometimes run this particular block when it otherwise wouldn't be/

2024-07-13 16:28 UTC, torranx commented on src/field/pokemon.ts
> -        }
It wouldn't really matter because again it's only being consumed [here](https://github.com/pagefaultgames/pokerogue/blob/beta/src/field/pokemon.ts#L1913). Please correct me if I'm missing something.

2024-07-14 04:28 UTC, merged