[Bug] Fixing Magic Guard ability interactions
pagefaultgames/pokerogue pull request #3029
Opened 2024-07-15 00:27 UTC by frutescens

## What are the changes?
Magic Guard now prevents damage from Bad Dreams, Solar Power, Dry Skin, Liquid Ooze, Aftermath, and Innards Out. It should also prevent damage from Gulp Missile but that ability has not been implemented yet. 

## Why am I doing these changes?
While working on the Magic Guard test, I noticed these inaccuracies and wanted to update the repo so my test would work according to expectations. 

## What did change?
data/ability.ts
- PostFaintContactDamageAbAttr
- TBD

### Screenshots/Videos
TBD

## How to test the changes?
Would recommend using overrides.ts for testing

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Have I provided screenshots/videos of the changes?

2024-07-16 21:19 UTC, schmidtc1 requested changes

2024-07-16 21:19 UTC, schmidtc1 commented on src/data/ability.ts
> +      if (cancelled.value || attacker.hasAbilityWithAttr(BlockNonDirectDamageAbAttr)) {
```typescript
if (attacker.hasAbilityWithAttr(BlockNonDirectDamageAbAttr)) {
  return false;
}
```
Can you also do this for `PostFaintHPDamageAbAttr`. Innards Out should be blocked similarly.

2024-07-17 19:06 UTC, DustinLin commented on src/data/ability.ts
> +    if (pokemon.hasAbilityWithAttr(BlockNonDirectDamageAbAttr)) {
wouldn't this just skip the entire post-weather checks for the current pokemon? could there be a situation where it could have some positive effect from weather that could be skipped?

2024-07-17 19:10 UTC, DustinLin commented on src/data/ability.ts
> +      if ((opp.status?.effect === StatusEffect.SLEEP || opp.hasAbility(Abilities.COMATOSE)) && !opp.hasAbilityWithAttr(BlockNonDirectDamageAbAttr)) {
same situation here

2024-07-29 22:04 UTC, closed without merging