[Bug] Fix Baton Pass TM learnset
pagefaultgames/pokerogue pull request #3035
Opened 2024-07-16 04:59 UTC by EmberCM

## What are the changes?
Added and removed some Pokemon from [Baton Pass TM](https://bulbapedia.bulbagarden.net/wiki/Baton_Pass_(move)) learnset

## Why am I doing these changes?
Someone asked for it in [Discord](https://discord.com/channels/1125469663833370665/1262618712674926704)

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

2024-07-16 14:30 UTC, Tempo-anon requested changes
We really need to agree on how to deal with TM levelsets and what to do in cases where there's Pokemon that lose learning moves in between generations

2024-07-16 14:30 UTC, Tempo-anon commented on src/data/tms.ts
>      Species.RAPIDASH,
Just a quick check reveals Rapidash also lost access to baton pass via tm in gen 9, as well as farefetchd

2024-07-16 16:07 UTC, EmberCM commented
> We really need to agree on how to deal with TM levelsets and what to do in cases where there's Pokemon that lose learning moves in between generations

The way I implemented it currently was giving it to all the Pokemon in the list no matter the generation or if they lost it.

2024-07-19 05:45 UTC, Fontbane commented
> > We really need to agree on how to deal with TM levelsets and what to do in cases where there's Pokemon that lose learning moves in between generations
> 
> The way I implemented it currently was giving it to all the Pokemon in the list no matter the generation or if they lost it.

Yeah this is how we've been doing things so far, should be fine. Also maybe change from [Bug] to [Balance].

2024-07-29 23:55 UTC, Tempo-anon commented
Too many merge conflicts... closing this PR for now

2024-07-29 23:55 UTC, closed without merging