[Balance] More TM fixes
pagefaultgames/pokerogue pull request #3081
Opened 2024-07-21 02:14 UTC by Fontbane

## What are the changes?

- Update TM compatibility for more TMs, mostly from Gen 1-3, to match the Indigo Disk updates and stuff

## Why am I doing these changes?

- They were wrong

## What did change?

- Don't worry about it

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/4aec35ad-2c04-42e8-848e-6a5e7758d39a)

## How to test the changes?

- Just trust me

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-21 02:51 UTC, Xavion3 requested changes
Where did these come from? Just glancing through I'm seeing really weird choices like attract on genderless pokemon, which makes me question this entire PR if there's not even that most basic level of care taken when creating custom TM lists.

2024-07-21 03:03 UTC, Fontbane commented
> Where did these come from? Just glancing through I'm seeing really weird choices like attract on genderless pokemon, which makes me question this entire PR if there's not even that most basic level of care taken when creating custom TM lists.

Attract is a universal TM except on genderless mons. I forgot to remove Poltchageist and Sinistcha from this list, thank you for catching it.

2024-07-21 04:01 UTC, damocleas approved these changes

2024-07-23 06:14 UTC, Madmadness65 approved these changes

2024-07-23 16:08 UTC, merged