[Refactor] Code readability update
pagefaultgames/pokerogue pull request #3085
Opened 2024-07-21 11:08 UTC by DayKev

## What are the changes?
Some non-functional changes are made to improve the readability of the code in `src/field/pokemon.ts` (this code provided by DerTapp on Discord) and `src/data/pokemon-species.ts` (by me).

## Why am I doing these changes?
A convoluted nested ternary was noticed while looking through the code.

## What did change?
Nested ternary replaced with commented if/else blocks in `src/field/pokemon.ts`.
Nested ternaries in `PokemonSpeciesForm.getAbilityCount()` and `PokemonSpeciesForm.getAbility()` changed to if/then blocks in `src/data/pokemon-species.ts`. These weren't that bad, but I'm not a fan of nested ternaries

## How to test the changes?
Uh... play the game? All of the tests still pass and this should theoretically be entirely non-functional changes.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

2024-07-21 11:11 UTC, CodeTappert approved these changes

2024-07-21 14:57 UTC, mcmontag commented on src/data/pokemon-species.ts
> +    if (this.ability2) {
In `getAbility`, `ability2` is checked to make sure it's not `Abilities.NONE`.  I'm assuming `Abilities.NONE` has an actual value of `0`, so the two conditions are functionally equivalent, but it feels like they should be written the same way.

2024-07-21 16:24 UTC, flx-sta commented
If you are refactoring code, please write automated tests for the refactored section to make sure that you didn’t change any expected results

2024-07-21 21:43 UTC, DayKev commented on src/data/pokemon-species.ts
> +    if (this.ability2) {
Whoops, missed that one, ty!

2024-07-22 15:41 UTC, flx-sta requested changes

2024-07-22 15:41 UTC, flx-sta commented on src/data/pokemon-species.ts
>    getAbilityCount(): integer {
Please add some jsdoc

2024-07-22 15:41 UTC, flx-sta commented on src/data/pokemon-species.ts
>    getAbility(abilityIndex: integer): Abilities {
Please add some jsdoc

2024-07-22 15:41 UTC, flx-sta commented on src/test/internals.test.ts
> +  it("PokemonSpeciesForm - .getAbilityCount() and .getAbility()", async () => {
Test names should be a "narrative". The "it" is part of it.

e.g. "it should provide Eevee with 3 defined abilities"
=> 
```suggestion
  it("it should provide Eevee with 3 defined abilities", async () => {
```

2024-07-22 15:41 UTC, flx-sta commented on src/test/internals.test.ts
> +  it("Pokemon.abilityIndex definition", async () => {
Test names should be a "narrative". The "it" is part of it.

e.g. "it should set Eeeve abilityIndex between 0-2"
=> 
```ts
```suggestion
  it("should set Eeeve abilityIndex between 0-2", async () => {
```

2024-07-22 15:41 UTC, flx-sta commented on src/test/internals.test.ts
> +    expect(abilityIndexInRange).toBe(true);
expect(eevee.abilityIndex).toBeGreaterThanOrEqual(0);
    expect(eevee.abilityIndex).toBeLessThanOrEqual(2);

2024-07-23 03:45 UTC, flx-sta approved these changes

2024-07-23 17:32 UTC, CodeTappert approved these changes

2024-07-23 18:59 UTC, merged