[BUG][UI/UX] Loading process that avoids input spam
pagefaultgames/pokerogue pull request #3105
Opened 2024-07-23 04:37 UTC by Vassiat

## What are the changes?
That the page does not crash when spamming Save & exit/Log out

## Why am I doing these changes?
Fixes https://github.com/pagefaultgames/pokerogue/pull/3084#pullrequestreview-2192059356

Resolves https://github.com/pagefaultgames/pokerogue/issues/3048 by @flx-sta

## What did change?
I created a function in ``` src/ui/ui.ts ``` called ProcessOnce that puts the receiving function into a "processing" state, making it wait for the loading to finish so it can receive more calls, mainly aimed at API calls from an input button to avoid input spam.
Currently only used in ``` src/ui/menu-ui-handler.ts ```

## How to test the changes?
Using database (from rogueserver) and "Slowed 3G" (Presets from Network) for simulation.

## Checklist
- [x] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-26 06:56 UTC, flx-sta commented
I hate to tell you but you did something wrong creating this branch. 210 files changed seems wrong for that type of change

2024-07-26 06:57 UTC, flx-sta commented
You don’t need to create a new pr or branch you just need to fix the commits by either re-basing or force pushing and cherry picking

2024-07-26 09:33 UTC, Vassiat commented
Done, i apologize for any inconvenience caused.

2024-07-26 16:01 UTC, flx-sta commented
I think your 3rd video (labled "After") is not the after video but rather a copy of the first one

2024-07-26 17:15 UTC, flx-sta commented
https://github.com/user-attachments/assets/8bbec059-d884-4131-afa1-bc3c375bcc16

I guess it could have some black backdrop but this works for me

(I've used [mock-service-worker](https://mswjs.io/) to delay the `updateAll` call by 5s)

2024-07-26 17:16 UTC, flx-sta approved these changes
https://github.com/user-attachments/assets/8bbec059-d884-4131-afa1-bc3c375bcc16

I guess it could have some black backdrop but this works for me

(I've used [mock-service-worker](https://mswjs.io/) to delay the `updateAll` call by 5s)

2024-08-07 06:46 UTC, torranx commented
Please fix your PR branch

2024-08-12 07:10 UTC, frutescens requested changes

2024-08-12 07:10 UTC, frutescens commented on src/ui/modal-ui-handler.ts
> +      if ("fadeOut" in args[0]) {
This technically works locally, but args[0] may not be read as containing "fadeOut" in a live environment. It could be compiled differently and so this conditional check may fail. Could you find an alternative conditional check?

2024-08-12 17:49 UTC, frutescens approved these changes
Compiled version appears to pass the checks. Thanks for making the changes!

2024-08-20 14:34 UTC, flx-sta approved these changes

2024-08-25 18:57 UTC, Vassiat commented
I didn't mean to dismiss @frutescens 's review. I think I accidentally clicked the wrong button, sorry about that!

2024-08-25 21:17 UTC, frutescens approved these changes

2024-09-12 03:12 UTC, merged