[Bug] Fixed OHKO moves being affected by accuracy and evasion battle stats
pagefaultgames/pokerogue pull request #3117
Opened 2024-07-24 02:01 UTC by Corrade

## What are the changes?
Fixed OHKO moves being affected by accuracy and evasion battle stats.

## Why am I doing these changes?
Fixing a bug that was recently raised: https://discord.com/channels/1125469663833370665/1176874654015684739/1265121370954797056

## What did change?
One line as noted in the diff below. Note that the changed function is only called by `hitCheck()` in `src\phases.ts:3058`, which looks like:
```
    // other logic omitted

    // properly accounts for OHKO moves
    const moveAccuracy = this.move.getMove().calculateBattleAccuracy(user, target);

    if (moveAccuracy === -1) {
      return true;
    }

    // doesn't account for OHKO moves until this PR
    const accuracyMultiplier = user.getAccuracyMultiplier(target, this.move.getMove());
    const rand = user.randSeedInt(100, 1);

    return rand <= moveAccuracy * accuracyMultiplier;
```

### Screenshots/Videos
N/A

## How to test the changes?
Tested manually. We can't unit test this without further changes because the value we're interested in is coupled with RNG - see the above `hitCheck()` snippet. We should refactor `hitCheck()` to enable this sort of testing, but I'll leave it for a future PR to keep this one nice and small.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [No] Are the changes visual?
  - [No] Have I provided screenshots/videos of the changes?

2024-07-24 02:05 UTC, torranx commented
Can you please update the skipped test on `src/test/abilities/hustle.test.ts`? And if you can add addtl test/s on fissure, that'd be great!

2024-07-24 02:23 UTC, Corrade commented on src/test/abilities/hustle.test.ts
> +    expect(enemyPokemon.turnData.damageTaken).toBe(enemyPokemon.getMaxHp());
`game.scene.getEnemyPokemon()` returned `undefined` when it was originally called here, so I moved it up a bit.

2024-07-24 03:01 UTC, torranx requested changes

2024-07-24 03:01 UTC, torranx commented on src/test/moves/fissure.test.ts
> +    const accuracyMultiplier = partyPokemon.getAccuracyMultiplier(enemyPokemon, moveEffectPhase.move.getMove());
please use `spyOn` here (refer to hustle's last test) instead of manually calling it

2024-07-24 03:01 UTC, torranx commented on src/test/moves/fissure.test.ts
> +    const accuracyMultiplier = partyPokemon.getAccuracyMultiplier(enemyPokemon, moveEffectPhase.move.getMove());
same as above

2024-07-24 20:06 UTC, torranx commented on src/test/moves/fissure.test.ts
> +  it("ignores accuracy stat", async () => {
as mentioned in discord
> seems your 2 fissure tests are the same, is that intended? shouldn't you be setting the partyPokemon's ACC to < 1 on "ignores accuracy stat" instead?

2024-07-25 00:19 UTC, torranx approved these changes
looks good

2024-07-25 00:34 UTC, merged