[Bug] Game Stats Sub-Legendary NaN bug for new game files
pagefaultgames/pokerogue pull request #3122
Opened 2024-07-24 18:19 UTC by frutescens

## What are the changes?
This PR addresses the bug reported here: https://github.com/pagefaultgames/pokerogue/issues/3076 

## What did change?
Added a || 0 to the sub-legendary values stored in system/game-stats.ts

### Screenshots/Videos
I purposely edited game-stats-ui-handler to show all stat names for easier error checking. 
![image](https://github.com/user-attachments/assets/709b7ae6-0cbf-441c-87f6-bf1f70d37943)

## How to test the changes?
This bug only appears on a completely new user file. 
The tester should immediately go to the 'Game Stats' page in the menu after gender selection. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-07-24 18:44 UTC, flx-sta requested changes
Also you need to replace the
```ts
 vi.spyOn(overrides, "SINGLE_BATTLE_OVERRIDE", "get").mockReturnValue(true);
 ```
 with
 ```ts
 vi.spyOn(overrides, "BATTLE_TYPE_OVERRIDE", "get").mockReturnValue("single");
 ```
 to fix the tests.

2024-07-24 18:44 UTC, flx-sta commented on src/system/game-stats.ts
> +    this.subLegendaryPokemonHatched = source?.subLegendaryPokemonHatched || 0;
don't use `||`. If possible use `??`.
Some for the other ones.
cause with `||` the `0` is also considered `false`. But `??` only considers `null` or `undefined` as false

```suggestion
    this.subLegendaryPokemonSeen = source?.subLegendaryPokemonSeen ?? 0;
    this.subLegendaryPokemonCaught = source?.subLegendaryPokemonCaught ?? 0;
    this.subLegendaryPokemonHatched = source?.subLegendaryPokemonHatched ?? 0;
```

2024-07-24 19:17 UTC, frutescens commented
> Also you need to replace the
> 
> ```ts
>  vi.spyOn(overrides, "SINGLE_BATTLE_OVERRIDE", "get").mockReturnValue(true);
> ```
> 
> with
> 
> ```ts
> vi.spyOn(overrides, "BATTLE_TYPE_OVERRIDE", "get").mockReturnValue("single");
> ```
> 
> to fix the tests.

Sent in this PR to fix it https://github.com/pagefaultgames/pokerogue/pull/3123

2024-07-24 19:49 UTC, merged

2024-07-25 02:21 UTC, Mewtwo2387 commented
Isn't those 3 stats intentionally left out as undefined so fixLengendaryStats() works retroactively?

```js
if (systemData.gameStats) {
  if (systemData.gameStats.legendaryPokemonCaught !== undefined && systemData.gameStats.subLegendaryPokemonCaught === undefined) {
     this.fixLegendaryStats(systemData);
  }
  this.gameStats = systemData.gameStats;
}
 ```     
 ```js    
  fixLegendaryStats(systemData: SystemSaveData): void {
    systemData.gameStats.subLegendaryPokemonSeen = 0;
    systemData.gameStats.subLegendaryPokemonCaught = 0;
    systemData.gameStats.subLegendaryPokemonHatched = 0;
    allSpecies.filter(s => s.subLegendary).forEach(s => {
      const dexEntry = systemData.dexData[s.speciesId];
      systemData.gameStats.subLegendaryPokemonSeen += dexEntry.seenCount;
      systemData.gameStats.legendaryPokemonSeen = Math.max(systemData.gameStats.legendaryPokemonSeen - dexEntry.seenCount, 0);
      systemData.gameStats.subLegendaryPokemonCaught += dexEntry.caughtCount;
      systemData.gameStats.legendaryPokemonCaught = Math.max(systemData.gameStats.legendaryPokemonCaught - dexEntry.caughtCount, 0);
      systemData.gameStats.subLegendaryPokemonHatched += dexEntry.hatchedCount;
      systemData.gameStats.legendaryPokemonHatched = Math.max(systemData.gameStats.legendaryPokemonHatched - dexEntry.hatchedCount, 0);
    });
    systemData.gameStats.subLegendaryPokemonSeen = Math.max(systemData.gameStats.subLegendaryPokemonSeen, systemData.gameStats.subLegendaryPokemonCaught);
    systemData.gameStats.legendaryPokemonSeen = Math.max(systemData.gameStats.legendaryPokemonSeen, systemData.gameStats.legendaryPokemonCaught);
    systemData.gameStats.mythicalPokemonSeen = Math.max(systemData.gameStats.mythicalPokemonSeen, systemData.gameStats.mythicalPokemonCaught);
  }
```