Beta
pagefaultgames/pokerogue pull request #3141
Opened 2024-07-25 12:40 UTC by f-fsantos

## What are the changes?

## Why am I doing these changes?

## What did change?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-07-25 15:44 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsStockpilingOnAdd": "{{pokemonNameWithAffix}} stockpiled {{stockpiledCount}}!"
```suggestion
  "battlerTagsStockpilingOnAdd": "{{pokemonNameWithAffix}} hortet {{stockpiledCount}}!"
```

2024-07-25 18:54 UTC, ben-lear commented on src/data/nature.ts
> +export { Nature };
+1 to this

2024-07-25 18:54 UTC, ben-lear commented on src/modifier/modifier-type.ts
> +        return i18next.t("modifierType:ModifierType.PokemonHeldItemModifierType.extra.inoperable", { "pokemonName": getPokemonNameWithAffix(pokemon) });
should these not be getNicknameToRender()?

2024-07-25 18:54 UTC, ben-lear commented on src/phases.ts
> +      console.warn("Swapped %s %O with %s %O", getPokemonNameWithAffix(partyMember), partyMember, getPokemonNameWithAffix(party[0]), party[0]);
should this be getNameToRender()?

2024-07-25 18:54 UTC, ben-lear commented on src/phases.ts
> +      return i18next.t("battle:bossAppeared", { bossName: getPokemonNameWithAffix(enemyField[0])});
should this be getNameToRender()?

2024-07-25 18:54 UTC, ben-lear commented on src/phases.ts
> +      const pokemonName = getPokemonNameWithAffix(this.getPokemon());
should this be getNameToRender()?

2024-07-25 20:01 UTC, DustinLin commented on src/data/arena-tag.ts
> +        pokemon.scene.queueMessage(`The opposing ${getPokemonNameWithAffix(pokemon)} was caught in a sticky web!`);
@localization ppl?

2024-07-25 20:05 UTC, DustinLin commented on src/data/pokemon-forms.ts
> + * @param species
would be nice to add a `{@linkcode Species}`

2024-07-25 20:54 UTC, schmidtc1 commented on src/data/move.ts
> +      moveAccuracy.value = Math.floor(moveAccuracy.value * 1.67);
Looks like Gravity multiplies accuracy of all non-OHKO moves [by 1.67](https://bulbapedia.bulbagarden.net/wiki/Gravity_(move)#:~:text=During%20intense%20gravity%2C%20the%20accuracy%20of%20all%20moves%20(except%20OHKO%20moves)%20is%20multiplied%20by%205/3%20in%20Generation%20IV%20or%206840/4096%20(approximately%201.67)%20in%20Generation%20V%20onwards.) according to Bulbapedia.

2024-07-25 21:23 UTC, xsn34kzx commented on src/modifier/modifier-type.ts
> +      return 3*(weightMultiplier? 2: 1)+(weightMultiplier? weightMultiplier-1: 0);
```suggestion
      return 3 * (weightMultiplier ? 2 : 1) + (weightMultiplier ? (weightMultiplier - 1) : 0);
```

2024-07-25 21:23 UTC, xsn34kzx commented on src/modifier/modifier.ts
> +export class PokemonResetNegativeStatStageModifier extends PokemonHeldItemModifier {
Noting down that we should probably remove the`Pokemon` prefix from modifiers in the future since it just increases the length of classes that are already pretty long.

2024-07-25 21:25 UTC, xsn34kzx commented on src/data/challenge.ts
> +    if (speciesStarters[pokemon.speciesId] > 10 - this.value) {
I think this refers to the max weight allowed in the starter select menu when you're making your team, definitely should have a constant for that.

2024-07-25 21:31 UTC, flx-sta commented on src/modifier/modifier.ts
> +export class PokemonResetNegativeStatStageModifier extends PokemonHeldItemModifier {
@xsn34kzx please put that into an issue. Probably more persistent. Make sure to resolve this comment but link it

2024-07-25 22:36 UTC, EnochG1 commented on src/data/arena-tag.ts
> +        pokemon.scene.queueMessage(`The opposing ${getPokemonNameWithAffix(pokemon)} was caught in a sticky web!`);
If you mean translations, I'm working on that here. (It's next task though) https://github.com/pagefaultgames/pokerogue/pull/3011

2024-07-25 23:28 UTC, Tempo-anon requested changes
Can you add the following two commits into the beta merge?
https://github.com/pagefaultgames/pokerogue/pull/3145
https://github.com/pagefaultgames/pokerogue/pull/2940

2024-07-25 23:55 UTC, torranx commented on src/modifier/modifier-type.ts
> +    return i18next.t("modifierType:ModifierType.PokemonLevelIncrementModifierType.description", {levels });
```suggestion
    return i18next.t("modifierType:ModifierType.PokemonLevelIncrementModifierType.description", { levels });
```

2024-07-25 23:55 UTC, torranx commented on src/phases.ts
> +    // then switchAndSummon(), manually pick pokemon to switch into
these seems unnecessary to me, comments should not duplicate the code

2024-07-25 23:55 UTC, torranx commented on src/phases.ts
> +      //Look for any other stat change phases; if this is the last one, do White Herb check
nit
```suggestion
      // Look for any other stat change phases; if this is the last one, do White Herb check
```

2024-07-25 23:55 UTC, torranx commented on src/system/settings/settings.ts
> +});
what's the difference of instantiating a new array and using `Array.from`?

2024-07-25 23:55 UTC, torranx commented on src/data/ability.ts
> +    //Disable showAbility during getTargetBenefitScore
nit
```suggestion
    // Disable showAbility during getTargetBenefitScore
```

2024-07-25 23:55 UTC, torranx commented on src/data/battle-stat.ts
> +export function getBattleStatLevelChangeDescription(pokemonNameWithAffix: string, stats: string, levels: integer, up: boolean, count: integer = 1) {
```suggestion
export function getBattleStatLevelChangeDescription(pokemonNameWithAffix: string, stats: string, levels: integer, up: boolean, count: number = 1) {
```

2024-07-25 23:55 UTC, torranx commented on src/data/battle-stat.ts
> +import i18next, {ParseKeys} from "i18next";
nit
```suggestion
import i18next, { ParseKeys } from "i18next";
```

2024-07-25 23:55 UTC, torranx commented on src/data/type.ts
> +export function getTypeResistances(type: integer): Type[] {
```suggestion
export function getTypeResistances(type: number): Type[] {
```

2024-07-25 23:55 UTC, torranx commented on src/data/battler-tags.ts
> +  public lapseType: BattlerTagLapseType[];
careful commiting this suggestion, might break the game since the property will change

2024-07-26 00:30 UTC, Tempo-anon commented
> Can you add the following two commits into the beta merge? #3145 #2940

White herb is also breaking intimidate unit test. Here's a fix for that #3151

2024-07-26 00:32 UTC, Tempo-anon approved these changes
Wait I just realized this is a beta->main merge. I thought you created a new branch so still needed any new changes beta would pick up. Getting rid of my blocking request changes then :pikastare:

2024-07-26 00:36 UTC, torranx commented on src/data/battler-tags.ts
> +
add docs for new classes

2024-07-26 00:36 UTC, torranx commented on src/data/move.ts
> +export class ReceiveDoubleDamageAttr extends AddBattlerTagAttr {
docs please

2024-07-26 00:36 UTC, torranx commented on src/data/move.ts
> +  });
this could do some formatting, and documentation

2024-07-26 01:15 UTC, EnochG1 requested changes

2024-07-26 01:15 UTC, EnochG1 commented on src/data/arena-tag.ts
> +        pokemon.scene.queueMessage(`The opposing ${getPokemonNameWithAffix(pokemon)} was caught in a sticky web!`);
@sirzento,
I don't think this change is appropriate.
`getPokemonNameWithAffix(pokemon)` can return 'foe ${pokemonName}'.
And then queue message becomes weird -> '**The opposing Foe pokemonName** was caught in a sticky web!'
But just pokemonName would be right.
![image](https://github.com/user-attachments/assets/3904faea-b8ac-4774-962f-191b103d861b)

2024-07-26 04:21 UTC, DayKev commented on src/data/battler-tags.ts
> +
Seeing this I've realized that these classes aren't necessary, I should have just used the base BattlerTag class. PR created: #3154

2024-07-26 04:33 UTC, DayKev commented on src/data/move.ts
> +export class ReceiveDoubleDamageAttr extends AddBattlerTagAttr {
Same as above. PR here: #3155

2024-07-26 04:40 UTC, flx-sta approved these changes

2024-07-26 04:56 UTC, mcmontag commented on src/field/pokemon.ts
> +
It's common practice, and [a well-documented feature](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads) of typescript.  It enables more helpful type inference and tighter constraints, assuming it's used correctly.

When you're writing a function call and the popup/tooltip in the IDE says something like "3 more overloads" and let's you flip between them...this is how it knows.

2024-07-26 05:32 UTC, flx-sta commented on src/field/pokemon.ts
> +
@mcmontag i meant “not common” in a sense that I don’t usually see that. Interesting for sure.

2024-07-26 05:34 UTC, flx-sta commented on src/system/settings/settings.ts
> +});
It’s more cool

2024-07-26 06:14 UTC, mcmontag commented on src/field/pokemon.ts
> +
@flx-sta to be more specific about why I'm using it here, though  -- these overloads tell the type checker that `getTag` returns:
- `BattlerTag`, when a `BattlerTagType` is passed in.
- or `T`, when a `Constructor<T>` is passed in. 

The implementation already enforces this mapping from arg type -> return type, but a standalone function signature cannot capture it. The best it can say is "this function takes an argument of type `BattlerTagType | Constructor<T>` and returns a `BattlerTag | T`".  Based on that definition, passing in a `Constructor<T>` could return a `BattlerTag` (other than `T`).  Without overloads, the type checker only sees that (imprecise) definition, so it will never return simply `T`.  That's why we always had to cast the result when a `Constructor<T>` was passed in.

2024-07-26 11:22 UTC, sirzento commented on src/data/arena-tag.ts
> +        pokemon.scene.queueMessage(`The opposing ${getPokemonNameWithAffix(pokemon)} was caught in a sticky web!`);
Ah yes, you're right. It needs to be changed to `pokemon.getNameToRender()`

2024-07-26 11:25 UTC, sirzento commented on src/data/arena-tag.ts
> +        pokemon.scene.queueMessage(`The opposing ${getPokemonNameWithAffix(pokemon)} was caught in a sticky web!`);
```suggestion
        pokemon.scene.queueMessage(`The opposing ${pokemon.getNameToRender()} was caught in a sticky web!`);
```

2024-07-26 11:51 UTC, sirzento commented on src/modifier/modifier-type.ts
> +        return i18next.t("modifierType:ModifierType.PokemonHeldItemModifierType.extra.inoperable", { "pokemonName": getPokemonNameWithAffix(pokemon) });
`getPokemonNameWithAffix()` does return the nickname if that pokemon has one.

2024-07-26 11:51 UTC, DayKev commented on src/data/ability.ts
> +      // TODO Remove this when promises get reworked PR#924
> [closing this to restart and test more thoroughly along the way](https://github.com/pagefaultgames/pokerogue/pull/924#issuecomment-2125076372)

Seems like it's still planned at some point?

2024-07-26 11:53 UTC, sirzento commented on src/data/arena-tag.ts
> +        pokemon.scene.queueMessage(`The opposing ${getPokemonNameWithAffix(pokemon)} was caught in a sticky web!`);
Resolved with https://github.com/pagefaultgames/pokerogue/pull/3141#discussion_r1692927130

2024-07-26 12:07 UTC, DayKev commented on src/data/pokemon-species.ts
>    }
True, this was changed before that change. Should this then be changed again to `return this.abilityHidden !== Abilities.NONE ? 3 : 2;`?

2024-07-26 12:34 UTC, torranx approved these changes
Couple nits added and I don't see any game breaking bugs, except the possible unwanted implications from the changes in `pokemon-species.ts`. Otherwise, looks good to me.

2024-07-26 12:40 UTC, DayKev commented on src/data/pokemon-species.ts
>    }
Changed via #3157

Might revisit this (and related) later.

2024-07-26 12:40 UTC, DayKev commented on src/data/pokemon-species.ts
> +      if (this.ability2 !== Abilities.NONE) {
Fixed via #3157

2024-07-27 23:40 UTC, Tempo-anon approved these changes

2024-07-27 23:47 UTC, merged