Implement Gastro Acid
pagefaultgames/pokerogue pull request #315
Opened 2024-04-26 22:04 UTC by Martinrosen

Implement Gastro Acid
(This is my first PR so definitely look it over and let me know if I missed anything)

2024-04-26 22:58 UTC, Xavion3 requested changes
Feel free to ping me in the discord if you have questions, but currently this won't work, as it doesn't actually suppress their ability, in addition to the changes listed.

2024-04-26 22:58 UTC, Xavion3 commented on src/data/move.ts
> +    }
This would be part of a condition, but also this attribute doesn't make you immune to suppression, that's unsuppressable.

2024-04-26 22:58 UTC, Xavion3 commented on src/data/move.ts
> +    target.getAbility().attr(SuppressFieldAbilitiesAbAttr);
This line of code does nothing.

2024-04-26 22:58 UTC, Xavion3 commented on src/data/move.ts
> +    return (user, target, move) => !user.getAbility().hasAttr(UnswappableAbilityAbAttr) && !target.getAbility().hasAttr(UnswappableAbilityAbAttr);
Why is this checking for unswappable? It should check for unsuppressable, and should only check the target.

2024-05-02 04:24 UTC, Madmadness65 commented
Superseded by #393

2024-05-02 04:24 UTC, closed without merging