[BUG] Re: ALT Fixing move Chilly Reception
pagefaultgames/pokerogue pull request #3198
Opened 2024-07-29 01:24 UTC by DustinLin

same as PR #3061

2024-07-29 05:44 UTC, mcmontag commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
Not to sound like a broken record, but there are a lot of comments in this class trying to justify a super niche behavior that's ultimately just for one move.  The fact that it's limited to `||`ing the conditions with fixed precedence makes it even less likely that a hypothetical move would be able to reuse this.

There are other moves that have their own attributes.  Why shouldn't this one?

2024-07-29 23:52 UTC, mcmontag commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
Well let's back up a bit.  This is essentially a mixin.  An attribute that can be injected with additional `apply` and `condition` callbacks is effectively *two* attributes.  What justifies doing that, but only when one of the two is `ForceSwitchOutAttr`?

If mixins are the goal, there is actual language support for them.

But with that said -- all you're trying to do is continue using the move if the weather effect fails, right?  Why does it necessitate an entire new attribute in the first place?

2024-07-30 01:00 UTC, DustinLin commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
yeah my bad I didn't really explain in the original solution, but basically the way the Moves work is that (when going through the checks to see if the move will fail, before any actual hit/accuracy/move damage is calculated) we loop over each `attr` attached to the move, and call it's `getCondition()`. If all the `attr`s satisfy then the we go on and do the rest of the turn.

The original bug/problem with the move is that the switch-out and weather-apply attrs were separated, meaning that if one of them fails then the entire move will fail. Based on how the move works this is problematic. The fix in PR #2979 (which you can view [here](https://github.com/pagefaultgames/pokerogue/pull/3198/commits/1ae0d3380291871df9ff2da3b0fe18f4bb0fb4aa) ) is to add special checks *separately* in each of the 2 attributes to ensure that it doesn't fail for chilly reception. imo this is messy, and intertwines the 2 classes.

Another solution (which this PR does) is to just make a new attribute that combines both the weather change and force switchout, and has a separate `getCondition()` logic.  Now how we want to design this attr class is still up for discussion ig, but that's the reasoning.

Maybe there is some other cleaner solution i haven't thought of, it would be good to think about

2024-07-30 04:47 UTC, mcmontag commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
Right.  So the justification is that `MoveEffectAttr`s are typically "all or nothing" -- they all happen, or none of them happen.  This particular move has an effect that _happens_ to fit the description of two existing attributes, but differs in the fact that those two parts of the effect can occur independently of each other.  I get why you might want to create an abstraction for that kind of behavior, but I'm not seeing how it isn't just unnecessary complexity when it only applies to a single move.  Moreover, building the abstraction specifically for `ForceSwitchOutAttr` seems pointless.

> This class extends ForceSwitchOutAttr, we can think of this class as ForceSwitchOut with "something extra" in it's apply() and getConditions() functions

...this just restates one of the core purposes of inheritence.  If some new move comes along that needs to do "something extra" on top of `ForceSwitchOut`, subclassing `ForceSwitchOut` instead of `StatusForceSwitchOut` would take virtually the same amount of code, wouldn't duplicate any meaningful logic at all, and would be much easier to read and reason about.

If you're absolutely sure you want to abstract this, I'd suggest a few things.  For one, the name `StatusForceSwitchOutAttr` makes it seem like status moves which force a switch out would be able (or even *expected*) to leverage it, and that just isn't the case.  On top of that:
- It assumes that `statusApplyFunc` checks `statusCondFunc` internally (`trySetWeather` does that, but it's certainly not safe to assume that all hypothetical `statusApplyFunc`s would)
- The switch-out always occurs after the additional effect -- along the same lines, the return value of `apply` is always the result of the switch-out `apply`.
- Both `statusApplyFunc` and `statusCondFunc` are marked as nullable (also, they're missing types...), but neither is null-checked before being called (`this.statusApplyFunc(...)` instead of `this.statusApplyFunc?.(...)`) -- this isn't a problem because the only move that uses it _happens_ to provide both args.
- `statusCondFunc` has to be a `MoveConditionFunc` -- if there's a concrete instance of `MoveCondition`, why shouldn't it be valid to pass in as the condition?

2024-07-30 15:02 UTC, flx-sta commented
Please copy the description from https://github.com/pagefaultgames/pokerogue/pull/3061 into here with a note to the original PR

2024-07-30 15:40 UTC, flx-sta commented
Didn't mean to close it

2024-07-30 21:49 UTC, DustinLin commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
hmm so from a design perspective you would rather the new attribute be explicitly made for chilly reception, with the extra conditions "hardcoded" (not in a bad way) into the attribute's `getCondition()` and `apply()` functions?

I can see your reasoning, and wouldn't mind making the change. But perhaps we can get more opinions about this.

2024-08-05 17:58 UTC, Snailman11 commented
Link to Discord's bug report (Chilly reception freezes the game)
https://discord.com/channels/1125469663833370665/1256731008078712912

2024-08-06 16:17 UTC, Adri1 commented on src/locales/fr/move-trigger.ts
> +  "chillyReception": "{{pokemonName}} is preparing to tell a chillingly bad joke!",
```suggestion
  "chillyReception": "{{pokemonName}} s’apprête\nà faire un mauvais jeu de mots…",
```

2024-08-06 16:18 UTC, CodeTappert commented on src/locales/de/move-trigger.ts
> +  "chillyReception": "{{pokemonName}} is preparing to tell a chillingly bad joke!",
```suggestion
  "chillyReception": "{{pokemonName}} erzählt einen schlechten Witz,
der nicht besonders gut ankommt...",
```

2024-08-06 16:37 UTC, josericardo-fo commented on src/locales/pt_BR/move-trigger.ts
> +  "chillyReception": "{{pokemonName}} is preparing to tell a chillingly bad joke!",
```suggestion
  "chillyReception": "{{pokemonName}} está prestes a contar uma piada gelada!",
```

2024-08-07 01:29 UTC, mercurius-00 reviewed
zh

2024-08-07 01:29 UTC, mercurius-00 commented on src/locales/zh_CN/move-trigger.ts
> +  "chillyReception": "{{pokemonName}} is preparing to tell a chillingly bad joke!",
```suggestion
  "chillyReception": "{{pokemonName}}\n说出了冷笑话！",
```

2024-08-07 01:29 UTC, mercurius-00 commented on src/locales/zh_TW/move-trigger.ts
> +  "chillyReception": "{{pokemonName}} is preparing to tell a chillingly bad joke!",
```suggestion
  "chillyReception": "{{pokemonName}}\n說了冷笑話！",
```

2024-08-07 02:38 UTC, returntoice commented on src/locales/ko/move-trigger.ts
> +  "chillyReception": "{{pokemonName}} is preparing to tell a chillingly bad joke!",
```suggestion
  "chillyReception": "{{pokemonName}}[[는]] 썰렁한 개그를 선보였다!",
```

2024-08-07 04:57 UTC, EnochG1 commented
@DustinLin 
From now Japanese is added in beta.
Could you merge latest beta and add Japanese locale files? 🙏

2024-08-07 16:57 UTC, DustinLin commented
done, added localization tracker too, seems to be missing spanish, italian, and now japanese

2024-08-12 07:53 UTC, flx-sta commented on src/test/moves/chilly_reception.test.ts
> +    game.override.enemyLevel(5);
you can chain those if you want to
```suggestion
    game.override.battleType("single")
      .moveset([Moves.CHILLY_RECEPTION, Moves.SPLASH, Moves.SNOWSCAPE])
      .enemyMoveset(SPLASH_ONLY)
      .startingLevel(5)
      .enemyLevel(5);
```

2024-08-12 17:22 UTC, NicusPulcis reviewed
italian localization (also added another translation for something that still wasn't localized)

2024-08-14 00:36 UTC, DayKev commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
I think I ran into an issue with move `Attr`s being "all-or-nothing" before with a different move, so maybe that's what needs to be changed (so it's in-line with how abilities can have multiple `AbAttr`s with differing conditions).

2024-08-14 02:20 UTC, DustinLin commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
yeah that's similar to the problem this move faces, is there a particular `Attr` or move that you remember?

2024-08-14 02:33 UTC, DayKev commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
Unfortunately I don't remember which one specifically.

2024-08-14 03:44 UTC, protimita commented on src/locales/ja/move-trigger.ts
> +  "chillyReception": "{{pokemonName}} is preparing to tell a chillingly bad joke!",
```suggestion
  "chillyReception": "{{pokemonName}}は\nさむい　ギャグを　かました！",
```

2024-08-15 16:59 UTC, DustinLin commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
i looked around `move.ts` and couldn't find anything... I can either leave this implementation as is, or refactor it to it's own `ChillyRecepAttr`

2024-09-04 05:17 UTC, Snailman11 commented
Discord Bug report Post (Chilly Reception bug(Beta))
https://discord.com/channels/1125469663833370665/1280455029744209950

-Please take a look at this - wild pokemon using Chilly Reception and the game opening up a second reality. I noticed that you didn't include videos of enemy pokemon using the move so I'd like to know if you're aware of this issue.

2024-09-04 09:57 UTC, DayKev commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
As much as I hate single-use `Attr`s/etc, the current system kinda forces it (for now). Ditch the genericization and have the new Attr just "hardcode" the Chilly Reception extras.
The "better" solution would be to make it so move attrs can apply independently if specified and then otherwise keep the original move implementation, but I don't know how much work that would be.

2024-09-04 10:19 UTC, DayKev commented
Whoops, should have marked it as draft before updating it.

2024-09-04 13:28 UTC, Chapybara-jp approved these changes

2024-09-04 13:28 UTC, Chapybara-jp commented on src/locales/ja/move-trigger.json
> +  "chillyReception": "{{pokemonName}}は\nさむい　ギャグを　かました！"
```suggestion
  "chillyReception": "{{pokemonName}}は\n寒い　ギャグを　かました！"
```

2024-09-04 13:28 UTC, Chapybara-jp commented on src/locales/ja/move-trigger.json
> +  "swapArenaTags": "{{pokemonName}}は\nおたがいの　ばのこうかを　いれかえた！",
```suggestion
  "swapArenaTags": "{{pokemonName}}は\nお互いの　場の効果を　入れ替えた！",
```

2024-09-04 13:56 UTC, NicusPulcis submitted a review, later dismissed
italian is approved

2024-09-05 16:57 UTC, DustinLin commented on src/data/move.ts
> +export class StatusForceSwitchOutAttr extends ForceSwitchOutAttr {
thanks all, refactored in most recent change

2024-09-08 19:19 UTC, ben-lear requested changes

2024-09-08 19:19 UTC, ben-lear commented on src/test/moves/chilly_reception.test.ts
> +  }, TIMEOUT);
nit: can we have a happy path test case for setting weather + switch out?

2024-09-09 03:47 UTC, DustinLin commented on src/test/moves/chilly_reception.test.ts
> +  }, TIMEOUT);
added

2024-09-15 01:29 UTC, DayKev approved these changes

2024-09-15 01:29 UTC, DayKev commented
Another move that needs the `conditionalAttr()` system that abilities have
![](https://cdn.discordapp.com/emojis/1238147669432598659.webp?quality=lossless)

2024-09-19 10:57 UTC, Chapybara-jp approved these changes

2024-09-23 03:04 UTC, flx-sta approved these changes
Technically the tests shouldn't have a manual `timeout` set anymore but there is some other that sneaked in so I'm going to fix that in a new PR

2024-09-23 03:07 UTC, SangaraSorama approved these changes

2024-09-23 03:09 UTC, merged