Add Neutralizing Gas message, display Manaphy egg gacha origin, allow catching wonder guard bosses
pagefaultgames/pokerogue pull request #322
Opened 2024-04-27 21:44 UTC by TempsRay

* Neutralizing Gas should display a message upon being sent out so I added a `PostSummonMessageAbAttr` to it
* Manaphy eggs currently are hardcoded to not display where they were obtained. This is purely a cosmetic bug since the game still keeps track of their `gachaType` (an enum) while not reflecting a string description of it for the egg-list-ui-handler, confusing players. [Example of what it looks like](https://cdn.discordapp.com/attachments/1233819365510615050/1233891723495870494/image.png?ex=662ebeb7&is=662d6d37&hm=8d544d139c97acf7222c5edd41970d93cc427c683f672fad14a31914166706c0&)
* There is an edge case where a boss Pokemon has wonder guard in which case it is uncatchable without a master ball

2024-04-27 22:08 UTC, Flashfyre commented
Resolve conflicts

2024-04-27 22:48 UTC, TempsRay commented
conflicts resolved

2024-04-27 23:11 UTC, Xavion3 requested changes

2024-04-27 23:11 UTC, Xavion3 commented on src/phases.ts
> +            if (targetPokemon.isBoss() && targetPokemon.bossSegmentIndex >= 1 && !targetPokemon.hasAbility(Abilities.WONDER_GUARD) && cursor < PokeballType.MASTER_BALL) {
Should probably be `.hasAbility(Abilities.WONDER_GUARD, false, true)` so it doesn't care if wonder guard is currently suppressed or overridden.

2024-04-27 23:31 UTC, TempsRay commented on src/phases.ts
> +            if (targetPokemon.isBoss() && targetPokemon.bossSegmentIndex >= 1 && !targetPokemon.hasAbility(Abilities.WONDER_GUARD) && cursor < PokeballType.MASTER_BALL) {
Gotcha, will change

2024-05-01 05:04 UTC, Xavion3 approved these changes

2024-05-04 02:29 UTC, merged