[Move] Implement Natural Gift (latest)
pagefaultgames/pokerogue pull request #3247
Opened 2024-07-30 14:12 UTC by AyushBarik

please refer to https://github.com/pagefaultgames/pokerogue/pull/2333

Previous PR which was in beta got messed up because it got infiltrated with a bunch of commits from other people. Made a new clean PR. 

implemented latest changes.

2024-07-30 14:18 UTC, torranx commented
Can we write some tests here? Also all PRs should target `beta` except it is some urgent bugfix/hotfix.

2024-07-30 15:00 UTC, flx-sta commented
@AyushBarik can you also just copy the description of the previous PR into this one?
Simply start an `edit`, copy all, edit here, paste it here. Done.
That way the reviewers don't have to jump through 2 PRs to understand the content

2024-08-12 05:55 UTC, innerthunder commented on src/data/move.ts
> +   * @param args - n/a
args is not `n/a` here...

2024-08-12 06:02 UTC, innerthunder reviewed
Looks good for the most part, just some small nits

2024-08-12 06:49 UTC, flx-sta requested changes

2024-08-12 06:49 UTC, flx-sta commented on src/data/move.ts
> +  }
I think it would make sense to refactor the `findModifiers()` method to this:
```ts
  findModifiers<M extends PersistentModifier = PersistentModifier>(modifierFilter: ModifierPredicate, player: boolean = true): M[] {
    return (player ? this.modifiers : this.enemyModifiers).filter(m => (modifierFilter as ModifierPredicate)(m)) as M[];
  }
```

this way you can simply call 
```ts
      const userBerries = user.scene.findModifiers<BerryModifier>(
        m => m instanceof BerryModifier && m.pokemonId === user.id,
        user.isPlayer()
      );
```


same then for the following calls

2024-08-12 06:49 UTC, flx-sta commented on src/field/pokemon.ts
> +  public naturalGiftBerryModifier: BerryModifier;
Is this guaranteed to be defined? Or can this be `undefined/null`?
If so please add the corresponding notation. 

For undefined:
```ts
  public naturalGiftBerryModifier?: BerryModifier;
```

For null:
```ts
  public naturalGiftBerryModifier: BerryModifier | null = null;
```

2024-08-12 06:49 UTC, flx-sta commented on src/modifier/modifier.ts
> +    return berryNaturalGiftPowerMap[this.berryType] || 0;
Unless you really want to cover something like `false` or empty string `""` please use `??` instead. 
<sub>`||` should only be used when specifically wanted!</sub>

```suggestion
    return berryNaturalGiftPowerMap[this.berryType] ?? 0;
```

2024-08-12 06:49 UTC, flx-sta commented on src/modifier/modifier.ts
> +    return berryNaturalGiftTypeMap[this.berryType];
Is this guaranteed not to be `null/undefined`? Otherwise please make sure to adjust the return type or define fallback with `??`

2024-09-17 16:57 UTC, flx-sta commented
@AyushBarik  closed for being stale (no updates for over a month)

----

Feel free to create a new PR or ask us to re-open this one.

2024-09-17 16:57 UTC, closed without merging