[QoL][Feature] Hall of Fame + Run History
pagefaultgames/pokerogue pull request #3251
Opened 2024-07-30 15:09 UTC by frutescens

## What are the changes?
This adds a new option on the menu for 'Run History'.
It allows users to store and look at a maximum of 25 past runs. This functionality automatically logs a run based on the current SessionSaveData and stores it in cache/the network database. At the moment, the function mirrors the 'Load Save' UI and only shows the team, whether they were victorious or not, the mode, wave, and the final timestamp of the run.

The server-side code is here: https://github.com/pagefaultgames/rogueserver/pull/33
The previous PR (closed because of beta collision): https://github.com/pagefaultgames/pokerogue/pull/1815

## Why am I doing these changes?
This has been a feature requested by many users. In addition, this will allow the Balance and Development teams to do some analytics and have data on the gameplay experience.

I also have a bad memory so I thought it would be helpful to be able to access past runs to see what I need to do better.

## What did change?
- game-data.ts : 
- menu-ui-handler.ts :
- phases.ts :
- run-history-ui-handler.ts :
- run-info-ui-handler.ts :
- loading-scene.ts : 
- New localization files added for run-history specifically

### Screenshots/Videos
Finalizing some images

## How to test the changes?
Play the game normally and the game should record defeats / victories. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-07-30 18:50 UTC, CodeTappert commented
Please make sure that all languages have the same amount of localization keys. And fill all other lanugages (that you are not a native of) with english placeholders. Thank you!

2024-07-30 22:15 UTC, CodeTappert commented on src/locales/en/menu-ui-handler.ts
> +  "RUN_HISTORY": "Run History",
This is still missing in all other languages no?

2024-07-30 23:41 UTC, EnochG1 reviewed
Korean translation

2024-07-30 23:41 UTC, EnochG1 commented on src/locales/ko/run-history-ui-handler.ts
> +  "viewHallOfFame":"View Hall of Fame!"
```suggestion
  "victory": "승리!",
  "defeatedWild": "야생에서 패배: ",
  "defeatedTrainer": "트레이너에게 패배: ",
  "defeatedTrainerDouble": "더블 배틀에서 패배",
  "defeatedRival": "라이벌에게 패배",
  "defeated":"패배",
  "luck":"행운",
  "score":"점수",
  "mode":"모드",
  "challengeRules":"규칙",
  "challengeMonoGen1":"1세대",
  "challengeMonoGen2":"2세대",
  "challengeMonoGen3":"3세대",
  "challengeMonoGen4":"4세대",
  "challengeMonoGen5":"5세대",
  "challengeMonoGen6":"6세대",
  "challengeMonoGen7":"7세대",
  "challengeMonoGen8":"8세대",
  "challengeMonoGen9":"9세대",
  "playerItems":"플레이어 아이템",
  "personalBest":"개인 최고기록!",
  "SPDshortened":"스피드",
  "runInfo":"플레이 정보",
  "money":"소지금",
  "runLength":"플레이 타임",
  "viewHeldItems":"도구",
  "hallofFameText":"전당 등록을 축하합니다!",
  "viewHallOfFame":"전당 보기"
```

2024-07-30 23:44 UTC, EnochG1 commented on src/ui/run-history-ui-handler.ts
> +          const gameOutcomeLabel = addTextObject(this.scene, 8, 5, `${i18next.t("runHistory:defeatedTrainer")+tObj.config.nameDouble+" "+tObj.getName(0, false)}`, TextStyle.WINDOW);
I think this line have to get `i18next.t("runHistory:defeatedTrainerDouble")` instead of `i18next.t("runHistory:defeatedTrainer")`.
But not sure if position of tObj.config.nameDouble is wrong or not.

2024-07-31 03:44 UTC, frutescens commented on src/ui/run-history-ui-handler.ts
> +          const gameOutcomeLabel = addTextObject(this.scene, 8, 5, `${i18next.t("runHistory:defeatedTrainer")+tObj.config.nameDouble+" "+tObj.getName(0, false)}`, TextStyle.WINDOW);
You're right. I will fix that.

2024-07-31 07:07 UTC, CodeTappert commented on src/locales/de/run-history-ui-handler.ts
> +} as const;
```suggestion
  "victory": "Sieg!",
  "defeatedWild": "Besiegt durch ",
  "defeatedTrainer": "Besiegt durch",
  "defeatedTrainerDouble": "Besiegt durch Doppelkampf",
  "defeatedRival": "Besiegt durch Rivale",
  "defeated":"Besiegt",
  "luck":"Glück",
  "score":"Punkte",
  "mode":"Modus",
  "challengeRules":"Regeln",
  "challengeMonoGen1":"Gen I",
  "challengeMonoGen2":"Gen II",
  "challengeMonoGen3":"Gen III",
  "challengeMonoGen4":"Gen IV",
  "challengeMonoGen5":"Gen V",
  "challengeMonoGen6":"Gen VI",
  "challengeMonoGen7":"Gen VII",
  "challengeMonoGen8":"Gen VIII",
  "challengeMonoGen9":"Gen IX",
  "playerItems":"Spielergegenstände",
  "personalBest":"Persönlicher Bestwert!",
  "SPDshortened":"Geschw.",
  "runInfo":"Run Info.",
  "money":"Geld",
  "runLength":"Run Länge,
  "viewHeldItems":"Getragene Items",
  "hallofFameText":"Willkommen in der Ruhmeshalle",
  "viewHallOfFame":"Ruhmeshalle ansehen!"
} as const;
```

2024-07-31 07:08 UTC, CodeTappert commented on src/locales/de/menu-ui-handler.ts
> +  "RUN_HISTORY": "Run History",
```suggestion
  "RUN_HISTORY": "Laufhistorie",
```

2024-07-31 07:12 UTC, CodeTappert commented
Please ping me when you merge the german changes in. So i can test if they fit etc

2024-07-31 20:18 UTC, CodeTappert commented
![image](https://github.com/user-attachments/assets/740a1d4e-4e09-4d64-80c4-1195373c81c2)
EXCUSE ME. ITS PERFECTION. <3

![image](https://github.com/user-attachments/assets/1dc656ad-5810-4413-9485-20d8f8493c48)

2024-07-31 22:52 UTC, josericardo-fo commented on src/locales/pt_BR/menu-ui-handler.ts
> +  "RUN_HISTORY": "Run History",
```suggestion
  "RUN_HISTORY": "Histórico de Jogos",
```

2024-07-31 22:57 UTC, josericardo-fo commented on src/locales/pt_BR/run-history-ui-handler.ts
> +  "viewHallOfFame":"View Hall of Fame!"
```suggestion
  "victory": "Vitória!",
  "defeatedWild": "Derrotado por ",
  "defeatedTrainer": "Derrotado por ",
  "defeatedTrainerDouble": "Derrotado por Dupla",
  "defeatedRival": "Derrotado por Rival",
  "defeated": "Derrotado",
  "luck": "Sorte",
  "score": "Pontuação",
  "mode": "Modo",
  "challengeRules": "Regra(s)",
  "challengeMonoGen1": "G1",
  "challengeMonoGen2": "G2",
  "challengeMonoGen3": "G3",
  "challengeMonoGen4": "G4",
  "challengeMonoGen5": "G5",
  "challengeMonoGen6": "G6",
  "challengeMonoGen7": "G7",
  "challengeMonoGen8": "G8",
  "challengeMonoGen9": "G9",
  "playerItems": "Itens do Jogador",
  "personalBest": "Recorde Pessoal!",
  "SPDshortened": "Vel.",
  "runInfo": "Info. do Jogo",
  "money": "Dinheiro",
  "runLength": "Tamanho do Jogo",
  "viewHeldItems": "Itens Segurados",
  "hallofFameText": "Bem-vindo(a) ao Hall da Fama!",
  "viewHallOfFame": "Veja o Hall da Fama!"
```

2024-07-31 23:06 UTC, Adri1 reviewed
Added French
However, would it be possible to have in-game screenshots about all of this new feature? (In English, so it could but used by everyone) Because I don't want to provide a blind translation that might appear to be inaccurate because I do not know the overall environment of what I have to translate

2024-08-01 00:02 UTC, EnochG1 reviewed
Sorry, I missed translation.

2024-08-01 00:02 UTC, EnochG1 commented on src/locales/ko/menu-ui-handler.ts
> +  "RUN_HISTORY": "Run History",
```suggestion
  "RUN_HISTORY": "플레이 이력",
```

2024-08-01 01:23 UTC, 40chyan commented on src/locales/zh_CN/menu-ui-handler.ts
> +  "RUN_HISTORY": "Run History",
```suggestion
  "RUN_HISTORY": "历史记录",
```

2024-08-01 01:23 UTC, 40chyan commented on src/locales/zh_CN/run-history-ui-handler.ts
> +  "viewHallOfFame":"View Hall of Fame!"
```suggestion
  "victory": "胜利！",
  "defeatedWild": "被打败",
  "defeatedTrainer": "被打败",
  "defeatedTrainerDouble": "被组合打败",
  "defeatedRival": "被劲敌打败",
  "defeated":"被打败",
  "luck":"幸运",
  "score":"分数",
  "mode":"模式",
  "challengeRules":"规则",
  "challengeMonoGen1":"一代",
  "challengeMonoGen2":"二代",
  "challengeMonoGen3":"三代",
  "challengeMonoGen4":"四代",
  "challengeMonoGen5":"五代",
  "challengeMonoGen6":"六代",
  "challengeMonoGen7":"七代",
  "challengeMonoGen8":"八代",
  "challengeMonoGen9":"九代",
  "playerItems":"玩家道具",
  "personalBest":"个人最佳！",
  "SPDshortened":"Vel.",
  "runInfo":"游戏记录",
  "money":"金钱",
  "runLength":"游戏",
  "viewHeldItems":"持有道具",
  "hallofFameText":"欢迎来到名人堂！",
  "viewHallOfFame":"浏览名人堂！"
```

2024-08-01 01:41 UTC, frutescens commented
Hi, apologies. I uploaded some screenshots to the PR description. Thank you for your localization work.

2024-08-01 01:52 UTC, Adri1 commented
Questions :
How does this displays?
![image](https://github.com/user-attachments/assets/efbb1924-1249-4a44-8018-6a05ec6f063e)

It is possible to also be able have a translation entry for this? Because the money simple in languages like Frenc of German is located after the amount, not before :
![image](https://github.com/user-attachments/assets/b0995015-8062-467f-b099-99e4a532bc20)

Speaking of numbers do they dynamically adapt to the language format? As it's the case in most texts where numers appear, it detects the language used by the player's navigator (if I remeber well) to adapt it automatically, but idk if it's the case for your code

For example:
English : 1,234.56
French : 1 234,56

2024-08-01 03:58 UTC, frutescens commented
I am not sure. I use Pokerogue's own big number formatter so I will look into it + I will hopefully have a response for you in 12 or so hours.

2024-08-01 14:35 UTC, NicusPulcis commented on src/locales/it/menu-ui-handler.ts
> +  "RUN_HISTORY": "Run History",
```suggestion
  "RUN_HISTORY": "Run precedenti",
```

2024-08-01 14:46 UTC, NicusPulcis approved these changes
Italian has been localized

2024-08-01 14:46 UTC, NicusPulcis commented on src/locales/it/run-history-ui-handler.ts
> +  "viewHallOfFame":"View Hall of Fame!"
```suggestion
  "victory": "Vittoria!",
  "defeatedWild": "Sconfitti da ",
  "defeatedTrainer": "Sconfitti da ",
  "defeatedTrainerDouble": "Sconfitti dalla coppia ",
  "defeatedRival": "Sconfitti dal rivale",
  "defeated":"Sconfitti",
  "luck":"Fortuna",
  "score":"Punteggio",
  "mode":"Modalità",
  "challengeRules":"Regola/e",
  "challengeMonoGen1":"1ª gen",
  "challengeMonoGen2":"2ª gen",
  "challengeMonoGen3":"3ª gen",
  "challengeMonoGen4":"4ª gen",
  "challengeMonoGen5":"5ª gen",
  "challengeMonoGen6":"6ª gen",
  "challengeMonoGen7":"7ª gen",
  "challengeMonoGen8":"8ª gen",
  "challengeMonoGen9":"9ª gen",
  "playerItems":"Oggetti giocatore",
  "personalBest":"Record personale!",
  "SPDshortened":"Vel.",
  "runInfo":"Info Run",
  "money":"Patrimonio",
  "runLength":"Durata Run",
  "viewHeldItems":"Oggetti equipaggiati ",
  "hallofFameText":"Benvenuto alla Sala d'Onore!",
  "viewHallOfFame":"Visualizza Sala d'Onore!"
```

2024-08-01 17:02 UTC, CodeTappert commented
I am almost certain that the german text is too long

2024-08-01 17:10 UTC, Adri1 reviewed
First French corrections

2024-08-01 17:10 UTC, Adri1 commented on src/locales/fr/run-history-ui-handler.ts
> +  "runLength":"Durée session",
```suggestion
  "luck":"Chance ",
  "score":"Score",
  "mode":"Mode",
  "challengeRules":"Règles ",
  "challengeMonoGen1":"1G",
  "challengeMonoGen2":"2G",
  "challengeMonoGen3":"3G",
  "challengeMonoGen4":"4G",
  "challengeMonoGen5":"5G",
  "challengeMonoGen6":"6G",
  "challengeMonoGen7":"7G",
  "challengeMonoGen8":"8G",
  "challengeMonoGen9":"9G",
  "playerItems":"Objets joueur",
  "personalBest":"Record personnel !",
  "SPDshortened":"Vit.",
  "runInfo":"Infos session",
  "money":"Argent",
  "runLength":"Durée session ",
```

2024-08-02 17:25 UTC, CodeTappert commented
Uploading 2024-08-02 19-24-38.mp4…

Found a Bug.

2024-08-02 17:27 UTC, CodeTappert commented
![image](https://github.com/user-attachments/assets/90afc1bd-bee0-4691-96ba-c33f6ca9555c)
That background also looks not correct

2024-08-02 17:28 UTC, CodeTappert commented on src/locales/de/run-history-ui-handler.ts
> +  "runLength":"Länge des Durchlaufs",
```suggestion
  "runLength":"Durchlauf Dauer",
```

2024-08-02 17:29 UTC, CodeTappert commented on src/locales/de/run-history-ui-handler.ts
> +  "runInfo":"Durchlauf Info.",
```suggestion
  "runInfo":"Durchlauf Informationen",
```

2024-08-02 17:29 UTC, CodeTappert commented on src/locales/de/run-history-ui-handler.ts
> +  "SPDshortened":"Geschw.",
Where is this used?

2024-08-02 18:00 UTC, frutescens commented on src/locales/de/run-history-ui-handler.ts
> +  "SPDshortened":"Geschw.",
SPDshortened is only used in Spanish/Portuguese because Veloc. is too long

2024-08-02 18:31 UTC, frutescens commented
> 2024-08-02.19-24-38.mp4 
> Found a Bug.
> 
> Only option then is to reload

Fixed! Thank you for letting me know. I also replaced the hall of fame image.

2024-08-03 23:36 UTC, EnochG1 approved these changes

2024-08-04 14:43 UTC, Adri1 reviewed
French adjustment

2024-08-04 14:43 UTC, Adri1 commented on src/locales/fr/run-history-ui-handler.ts
> +  "playerItems":"Objets joueur",
```suggestion
  "playerItems":"Objets Dresseur",
```

2024-08-05 04:40 UTC, frutescens commented
![image](https://github.com/user-attachments/assets/8023d567-30d6-4fa5-9576-5c0dcd868f87)

2024-08-05 15:31 UTC, frutescens commented
![image](https://github.com/user-attachments/assets/33747bb0-4a68-4df1-a4f5-bf9d01046757)
![image](https://github.com/user-attachments/assets/3fcd2c27-b80e-4c20-8bb3-561e80034ccb)

2024-08-07 00:35 UTC, frutescens commented
![image](https://github.com/user-attachments/assets/ccd77afe-6677-4499-9fde-f494392b1fa7)

2024-08-07 10:52 UTC, Adri1 commented on src/locales/fr/run-history-ui-handler.ts
> +  "viewEndingSplash":"View ending art!"
```suggestion
  "viewHallOfFame":"Voir le Panthéon",
  "viewEndingSplash":"Voir l’illustration de fin !"
```

2024-08-07 21:36 UTC, Adri1 commented on src/locales/fr/menu-ui-handler.ts
> +  "unlinkGoogle": "Unlink Google",
```suggestion
  "importRunHistory":"Importer historique",
  "exportRunHistory":"Exporter historique",
  "linkDiscord": "Lier à Discord",
  "unlinkDiscord": "Délier Discord",
  "linkGoogle": "Lier à Google",
  "unlinkGoogle": "Délier Google",
```

2024-08-07 21:56 UTC, DustinLin commented on src/system/game-data.ts
> +       * Networking Code
if local storage is temporary, maybe make a note of it here in the comments, maybe something like "Networking Code (below code for eventual? move to online storage")?

2024-08-07 22:04 UTC, DayKev commented on src/ui/run-history-ui-handler.ts
> +          //This allows the enemyParty to be shown - doubles or sings -> 58+(e*8)
```suggestion
          // This allows the enemyParty to be shown - doubles or singles -> 58+(e*8)
```
Presumably you meant "singles" and not "sings"? 🤔

2024-08-07 22:06 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +  // Button.CYCLE_ABILITY (E key) --> shows pokemon held items
Should probably be tsdocs?

2024-08-07 22:12 UTC, DayKev requested changes
Hello, the style police is here. 🧐

2024-08-07 22:12 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +    //Thank you Hayuna for the code
```suggestion
    // Thank you Hayuna for the code
```

2024-08-07 22:12 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +    //Issue Note (08-05-2024): It seems as if fused pokemon do not appear with the averaged color b/c pokemonData's loadAsset requires there to be some active battle?
```suggestion
    // Issue Note (08-05-2024): It seems as if fused pokemon do not appear with the averaged color b/c pokemonData's loadAsset requires there to be some active battle?
```

2024-08-07 22:12 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +      //Column 1: HP Atk Def
```suggestion
      // Column 1: HP Atk Def
```

2024-08-07 22:12 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +      //Column 2: SpAtk SpDef Speed
```suggestion
      // Column 2: SpAtk SpDef Speed
```

2024-08-07 22:12 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +      //Trainer - Single and Double
```suggestion
      // Trainer - Single and Double
```

2024-08-07 22:12 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +          //Wild - Singles
```suggestion
          // Wild - Singles
```

2024-08-07 22:12 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +      //Wild - Single and Doubles
```suggestion
      // Wild - Single and Doubles
```

2024-08-07 22:12 UTC, DayKev commented on src/ui/run-history-ui-handler.ts
> +          //otherwise it becomes Rival_5 in Ivy's case
```suggestion
          // otherwise it becomes Rival_5 in Ivy's case
```

2024-08-07 22:12 UTC, DayKev commented on src/system/game-data.ts
> +    //Not implemented at the moment, but leaving room for future work
```suggestion
    // Not implemented at the moment, but leaving room for future work
```

2024-08-07 22:12 UTC, DayKev commented on src/system/game-data.ts
> +    //Arbitrary limit of 25 entries per User --> Can increase or decrease
```suggestion
    // Arbitrary limit of 25 entries per User --> Can increase or decrease
```

2024-08-07 22:12 UTC, DayKev commented on src/system/game-data.ts
> +        //check to see whether cachedData or serverData is more up-to-date
```suggestion
        // check to see whether cachedData or serverData is more up-to-date
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/zh_TW/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/zh_CN/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/pt_BR/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/ko/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/ja/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/it/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/fr/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/es/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/en/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/de/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-07 22:12 UTC, DayKev commented on src/locales/ca-ES/run-history-ui-handler.ts
> +//Wave / Lv found in save-slot-select-ui-handler.ts
```suggestion
// Mode Information found in game-mode.ts
// Wave / Lv found in save-slot-select-ui-handler.ts
```

2024-08-08 14:21 UTC, AsdarDevelops reviewed
Spanish done

2024-08-08 14:21 UTC, AsdarDevelops commented on src/locales/es/menu-ui-handler.ts
> +  "RUN_HISTORY": "Run History",
```suggestion
  "RUN_HISTORY": "Historial de partida",
```

2024-08-08 14:21 UTC, AsdarDevelops commented on src/locales/es/menu-ui-handler.ts
> +  "exportRunHistory":"Export Run History",
```suggestion
  "importRunHistory":"Importar Historial de partida",
  "exportRunHistory":"Exportar Historial de partida",
```

2024-08-08 14:21 UTC, AsdarDevelops commented on src/locales/es/run-history-ui-handler.ts
> +  "viewEndingSplash":"View ending art!"
```suggestion
  "victory": "Victory!",
  "defeatedWild": "Derrotado por ",
  "defeatedTrainer": "Derrotado por ",
  "defeatedTrainerDouble": "Derrotado por un dúo",
  "defeatedRival": "Derrotado por el rival",
  "defeated":"Derrotado",
  "luck":"Suerte",
  "score":"Puntuación",
  "mode":"Modo",
  "challengeRules":"Regla(s)",
  "challengeMonoGen1":"Gen I",
  "challengeMonoGen2":"Gen II",
  "challengeMonoGen3":"Gen III",
  "challengeMonoGen4":"Gen IV",
  "challengeMonoGen5":"Gen V",
  "challengeMonoGen6":"Gen VI",
  "challengeMonoGen7":"Gen VII",
  "challengeMonoGen8":"Gen VIII",
  "challengeMonoGen9":"Gen IX",
  "playerItems":"Objetos del jugador",
  "personalBest":"¡Récord personal!",
  "SPDshortened":"Vel.",
  "runInfo":"Info. de partida",
  "money":"Dinero",
  "runLength":"Duración de partida",
  "viewHeldItems":"Objetos equipados",
  "hallofFameText":"¡Bienvenido al Hall de la Fama!",
  "viewHallOfFame":"¡Ver Hall de la Fama!",
  "viewEndingSplash":"¡Ver la imagen final!"
```

2024-08-09 00:57 UTC, flx-sta requested changes

2024-08-09 00:57 UTC, flx-sta commented on src/loading-scene.ts
> +
do we want to load those immediately?
Can't we just load these when someone opens the UI?

_I know this has always been done that way but I'm really not a fan of stuffing EVERYTHING possible into the memory at the beginning of the game_

2024-08-09 00:57 UTC, flx-sta commented on src/phases.ts
> +        });
1. I assume this is meant to run asynchronously!?
2. Please add some context to the `console.error` (like `console.error("Failed to save run to history: ", err)`)

2024-08-09 00:57 UTC, flx-sta commented on src/system/game-data.ts
> +}
Can be simplified and please don't add any more `integer`:
```suggestion
export type RunHistoryData  = Record<number, RunEntry> 
```
<sub> Note that I used singular `RunEntry` here. See next comment </sub>

2024-08-09 00:57 UTC, flx-sta commented on src/system/game-data.ts
> +}
This should be singular. The plural indicates a list/array but this isn't one

```suggestion
export interface RunEntry {
  entry: SessionSaveData;
  victory: boolean;
  favorite: boolean;
}
```

2024-08-09 00:57 UTC, flx-sta commented on src/system/game-data.ts
> +        }
Please don't use `hasOwnProperty()`. It's not recommended 
<sub>can't find the source for that but below is a ChatGPT response</sub>

Instead do this
```suggestion
        const lsItemKey = `runHistoryData_${loggedInUser?.username}`
        const lsItem = localStorage.getItem(lsItemKey);
        if (!lsItem) {
          localStorage.setItem(lsItemKey, encrypt("", true));
        }
```

----

> Using `hasOwnProperty` on `localStorage` is not recommended because `localStorage` is an instance of the `Storage` interface, which is a key-value store for string data. The `Storage` object doesn't directly inherit properties from `Object.prototype`, so methods like `hasOwnProperty` might not behave as expected.
> 
> Instead, you can check for the existence of a key in `localStorage` using the `localStorage.getItem(key) !== null` pattern, which is more reliable. Here's an example:
> 
> ```javascript
> if (localStorage.getItem('yourKey') !== null) {
>   // Key exists in localStorage
> } else {
>   // Key does not exist in localStorage
> }
> ```
> 
> This approach is safer and aligns with the intended usage of the `Storage` API.

2024-08-09 00:57 UTC, flx-sta commented on src/system/game-data.ts
> +  public async getRunHistoryData(scene: BattleScene): Promise<Object> {
using `Object` as a response type is discouraged as it's very unspecific and close to using `any`.

Instead return the specific type expected. 
You can type cast the `JSON.parse` => 
```ts
JSON.parse(decrypt(cachedResponse, true)) as RunHistoryData;
```
<sub>if that's what's expected</sub>

2024-08-09 00:57 UTC, flx-sta commented on src/system/game-data.ts
> +        let cachedResponse = localStorage.getItem(`runHistoryData_${loggedInUser?.username}`);
Please don't use `hasOwnProperty()`. It's not recommended 
<sub>can't find the source for that but below is a ChatGPT response</sub>

Instead do this
```suggestion
      const lsItemKey = `runHistoryData_${loggedInUser?.username}`;
      const lsItem = localStorage.getItem(lsItemKey);
      if (lsItem) {
        let cachedResponse = lsItem;
```
----

> Using `hasOwnProperty` on `localStorage` is not recommended because `localStorage` is an instance of the `Storage` interface, which is a key-value store for string data. The `Storage` object doesn't directly inherit properties from `Object.prototype`, so methods like `hasOwnProperty` might not behave as expected.
> 
> Instead, you can check for the existence of a key in `localStorage` using the `localStorage.getItem(key) !== null` pattern, which is more reliable. Here's an example:
> 
> ```javascript
> if (localStorage.getItem('yourKey') !== null) {
>   // Key exists in localStorage
> } else {
>   // Key does not exist in localStorage
> }
> ```
> 
> This approach is safer and aligns with the intended usage of the `Storage` API.

2024-08-09 00:57 UTC, flx-sta commented on src/system/game-data.ts
> +    */
the networking code is not using `async/await`

2024-08-09 00:57 UTC, flx-sta commented on src/system/game-data.ts
> +    runHistoryData[timestamp]["favorite"] = false;
```suggestion
    runHistoryData[timestamp] = {
      entry: runEntry,
      victory: victory,
    };
```

And you should move the `Not implemented at the moment, but leaving room for future work` into the description of the interface

```ts
export interface RunEntry {
  entry: SessionSaveData;
  victory: boolean;
  /** Not used yet. Potential future feature */
  favorite?: boolean;
}

2024-08-09 00:57 UTC, flx-sta commented on src/system/game-data.ts
> +  async saveRunHistory(scene: BattleScene, runEntry : SessionSaveData, victory: boolean): Promise<boolean> {
```suggestion
  async saveRunHistory(scene: BattleScene, runEntry : SessionSaveData, isVictory: boolean): Promise<boolean> {
```

to make it more clear that `victory` is a boolean

2024-08-09 00:57 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +    return success || error;
shouldn't it be `success ?? error`?
Or should `success=false` also roll back to `error`?

2024-08-09 00:57 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +  showText(text: string, delay?: integer, callback?: Function, callbackDelay?: integer, prompt?: boolean, promptDelay?: integer) {
no more `integer` please

```suggestion
  showText(text: string, delay?: number, callback?: Function, callbackDelay?: number, prompt?: boolean, promptDelay?: number) {
```

2024-08-09 00:57 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +  setCursor(cursor: integer): boolean {
no more `integer` please

```suggestion
  setCursor(cursor: number): boolean {
```

2024-08-09 00:57 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +  setScrollCursor(scrollCursor: integer): boolean {
no more `integer`:

```suggestion
  setScrollCursor(scrollCursor: number): boolean {
```

2024-08-09 00:57 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +  public slotId: integer;
no more `integer`:
```suggestion
  public slotId: number;
```

2024-08-09 00:57 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +  constructor(scene: BattleScene, runHistory: any, timestamp: string, slotId: integer) {
no more `integer`
```suggestion
  constructor(scene: BattleScene, runHistory: any, timestamp: string, slotId: number) {
```

2024-08-09 03:07 UTC, frutescens commented on src/loading-scene.ts
> +
I can try looking into it, but it seems like you need access to class LoadingScene / SceneBase to load an image. I'll try to find another way though.

2024-08-09 04:05 UTC, flx-sta commented on src/loading-scene.ts
> +
@frutescens `BattleScene` is also an extension of `SceneBase` and almost everything has access to `BattleSccene`

2024-08-09 18:22 UTC, frutescens commented on src/ui/run-history-ui-handler.ts
> +    return success || error;
Should be the latter. But, I did take this code from older UI code which is you know, flawed.

2024-08-09 18:50 UTC, flx-sta commented on src/loading-scene.ts
> +
1 thing to watch out for is that `this.loadImage()` is an async action so you would have to make sure the image is loaded

2024-08-09 21:33 UTC, frutescens commented on src/loading-scene.ts
> +
Tested on slow 4G ---> hopefully this means it's ok

2024-08-09 22:00 UTC, flx-sta commented on src/loading-scene.ts
> +
Should be I guess. Worst things worst it’s an image missing

2024-08-09 22:02 UTC, frutescens commented on src/loading-scene.ts
> +
true, and there's the ending splash image below the hall of fame images anyways. thank you for your help.

2024-08-11 05:17 UTC, frutescens commented
I forgot to fix the cursor issue today.... nooooo.... tomorrow.

2024-08-12 07:50 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +        console.log(tObjSpriteKey);
debugging leftovers?
```suggestion
        const tObjSprite = this.scene.add.sprite(0, 5, tObjSpriteKey);
```

2024-08-12 07:51 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +      const pPassiveInfo = pokemon.passive ? `${passiveLabel+": "+pokemon.getPassiveAbility().name}` : "";
you are making it harder for yourself here. Use a template string to it's full potential:
```suggestion
      const pPassiveInfo = pokemon.passive ? `${passiveLabel}: ${pokemon.getPassiveAbility().name}` : "";
```

2024-08-12 15:45 UTC, Adri1 reviewed
Tiny French correction

2024-08-13 11:07 UTC, Corrade requested changes
Thanks a lot for this feature. I hope my comments are useful!

2024-08-13 11:07 UTC, Corrade commented on src/ui/run-info-ui-handler.ts
> +    if (button === Button.CANCEL) {
This could be moved into the switch statement below.

2024-08-13 11:07 UTC, Corrade commented on src/ui/run-info-ui-handler.ts
> +        if (!this.hallofFameContainer.visible) {
This could be simplified to this.hallofFameContainer.setVisible(!this.hallofFameContainer.visible). This conveys the toggling behaviour in one line.

Similar comment for party visibility below.

2024-08-13 11:34 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +    if (button === Button.ACTION || button === Button.CANCEL) {
I disagree. 
The usage for switch-cases is usually fairly niche and was generally over-used in this project.

There is room for improvements though. Like this:
```suggestion
    if ([Button.ACTION, Button.CANCEL].includes(button)) {
```

2024-08-13 17:33 UTC, frutescens commented on src/ui/run-history-ui-handler.ts
> +        if (data.trainer.trainerType >= 375) {
That's the ID of the rival trainers, which have some funky code behind it. But things may have changed between then and now so I should double check.

2024-08-13 17:35 UTC, frutescens commented on src/ui/run-info-ui-handler.ts
> +      for (let i = 0; i < runChallenges.length; i++) {
Yes, unfortunately.... it is what it is. Maybe after this, I can try fixing up how challenges are stored. I don't get why non-activated challenges are stored with activated challenges....

2024-08-13 18:25 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +        if (data.trainer.trainerType >= 375) {
Then give it the name `const RIVAL_TRAINER_ID_THRESHHOLD =375`

2024-08-13 18:41 UTC, frutescens commented on src/ui/run-info-ui-handler.ts
> +        if (!this.hallofFameContainer.visible) {
This causes an 'attempting to setVisible() an undefined object' because this.hallofFameContainer is not created for a loser's run.

2024-08-13 18:50 UTC, frutescens commented on src/ui/run-history-ui-handler.ts
> +      if (data.battleType === BattleType.WILD) {
I put the else there to indicate that the difference was between this.victory and !this.victory.

2024-08-13 18:51 UTC, frutescens commented on src/ui/run-info-ui-handler.ts
> +  	async setup() {
I'm using tabs though..

2024-08-13 18:53 UTC, frutescens commented on src/ui/run-history-ui-handler.ts
> +        if (data.trainer.trainerType >= 375) {
yes, I just wanted to double-check that the addition of new trainers did not change its # in enum/trainer-types.ts

2024-08-13 19:03 UTC, frutescens commented on src/ui/run-info-ui-handler.ts
> +        case 1:
Hi, I get that but I wanted to make it easier for people to read and position the sprites. Yes, it is unnecessary code and can be simplified but I think it is useful for centering the sprite or sprites.

2024-08-13 21:49 UTC, frutescens commented
![image](https://github.com/user-attachments/assets/a0293f0c-b576-4953-a927-411e3604241a)

2024-08-13 21:53 UTC, Adri1 reviewed
Tiny correction French

2024-08-13 21:53 UTC, Adri1 commented on src/locales/fr/run-history-ui-handler.ts
> +  "viewEndingSplash":"Voir l’illustration de fin !"
```suggestion
  "viewEndingSplash":"Voir l’illustration de fin"
```

2024-08-14 00:47 UTC, sodaMelon commented on src/locales/ko/menu-ui-handler.ts
> +  "exportRunHistory":"Export Run History",
```suggestion
  "importRunHistory":"플레이 이력 불러오기",
  "exportRunHistory":"플레이 이력 내보내기",
```

2024-08-14 01:59 UTC, EnochG1 commented
@frutescens 
Can you show us screenshot to check this label. (English is ok.)
```Typescript
  "viewHallOfFame":"View Hall of Fame!",
  "viewEndingSplash":"View ending art!"
```

2024-08-14 02:41 UTC, josericardo-fo commented on src/locales/pt_BR/menu-ui-handler.ts
> +  "exportRunHistory":"Export Run History",
```suggestion
  "importRunHistory":"Importar Histórico de Jogos",
  "exportRunHistory":"Exportar Histórico de Jogos",
```

2024-08-14 02:42 UTC, josericardo-fo commented on src/locales/pt_BR/run-history-ui-handler.ts
> +  "viewEndingSplash":"View ending art!"
```suggestion
  "viewEndingSplash":"Veja a arte final!"
```

2024-08-14 07:21 UTC, CodeTappert commented on src/locales/de/menu-ui-handler.ts
> +  "exportRunHistory":"Export Run History",
```suggestion
  "importRunHistory":"Laufhistorie importieren",
  "exportRunHistory":"Laufhistorie exportieren",
```

2024-08-14 07:22 UTC, CodeTappert commented on src/locales/de/run-history-ui-handler.ts
> +  "viewEndingSplash":"View ending art!"
```suggestion
  "viewEndingSplash":"Endgrafik anzeigen!"
```

2024-08-14 09:08 UTC, NicusPulcis approved these changes
italian localization done :)

2024-08-14 09:08 UTC, NicusPulcis commented on src/locales/it/menu-ui-handler.ts
> +  "exportRunHistory":"Export Run History",
```suggestion
  "importRunHistory":"Importa run precedenti",
  "exportRunHistory":"Esporta run precedenti",
```

2024-08-14 09:08 UTC, NicusPulcis commented on src/locales/it/run-history-ui-handler.ts
> +  "viewEndingSplash":"View ending art!"
```suggestion
  "viewEndingSplash":"Visualizza arte finale!"
```

2024-08-14 20:52 UTC, frutescens commented
Buttons have been changed!
![image](https://github.com/user-attachments/assets/836abefd-8204-44ce-aff3-d164639ceb6b)

2024-08-14 21:03 UTC, EnochG1 commented on src/locales/ko/run-history-ui-handler.ts
> +  "viewEndingSplash":"View ending art!"
```suggestion
  "viewEndingSplash":"엔딩 아트 보기"
```

2024-08-14 22:49 UTC, Adri1 commented
It is possible to have a screenshots for each language in the initial comment?

2024-08-15 00:33 UTC, Adri1 commented
> Hi @Adri1 I posted new photos. I will wait for new localizations, if possible, and then adjust the code so that other languages fit and look better.

Thanks a lot for it 🙏

2024-08-15 00:47 UTC, Adri1 commented
In the locale files, it is possible to make a two different entries for each "defeated" entry and for "hallofFameText", that depend on the player's gender?
Because in latin-based languages (and probably also German?), these entries are affected by gender (and the hallofFameText by Portugese only)

Exemple in French :
"Battu par" (male version)
"Battue par" (female version)

Not a big deal if not, but would look nicer

2024-08-15 01:27 UTC, 40chyan reviewed
fix zh_cn

2024-08-15 01:27 UTC, 40chyan commented on src/locales/zh_CN/run-history-ui-handler.ts
> +  "runLength":"游戏",
```suggestion
  "runLength":"游戏时长",
```

2024-08-15 01:27 UTC, 40chyan commented on src/locales/zh_CN/run-history-ui-handler.ts
> +  "viewEndingSplash":"View ending art!"
```suggestion
  "viewEndingSplash":"浏览结算画面"
```

2024-08-15 01:28 UTC, 40chyan commented
![image](https://github.com/user-attachments/assets/b14894e7-554e-4c6a-8780-579d01293944)
the position of this text is really weird
is this text even centered?

2024-08-15 01:30 UTC, 40chyan commented on src/locales/zh_CN/menu-ui-handler.ts
> +  "exportRunHistory":"Export Run History",
```suggestion
  "importRunHistory":"导入历史记录",
  "exportRunHistory":"导出历史记录",
```

2024-08-15 02:15 UTC, frutescens commented
@40chyan Hi - I will fix the off-centered text but I want to wait a day for updated localizations.

2024-08-15 04:48 UTC, protimita commented on src/locales/ja/menu-ui-handler.ts
> +  "exportRunHistory":"Export Run History",
```suggestion
  "importRunHistory":"ラン履歴のインポート",
  "exportRunHistory":"ラン履歴のエクスポート",
```

2024-08-15 04:48 UTC, protimita commented on src/locales/ja/menu-ui-handler.ts
> +  "RUN_HISTORY":"Run History",
```suggestion
  "RUN_HISTORY":"ラン履歴",
```

2024-08-15 04:51 UTC, protimita commented on src/locales/ja/menu-ui-handler.ts
> +  "RUN_HISTORY":"Run History",
```suggestion
  "RUN_HISTORY":"ラン履歴",
```

2024-08-15 04:51 UTC, protimita commented on src/locales/ja/menu-ui-handler.ts
> +  "exportRunHistory":"Export Run History",
```suggestion
  "importRunHistory":"ラン履歴インポート",
  "exportRunHistory":"ラン履歴エクスポート",
```

2024-08-15 04:52 UTC, protimita reviewed
JA translations for 3 lines.
menu-ui-handler.ts will be further edited on later PR

2024-08-15 05:11 UTC, protimita commented on src/locales/ja/run-history-ui-handler.ts
> +  "viewEndingSplash":"View ending art!"
```suggestion
  "victory": "勝利！",
  "defeatedWild": "倒された相手：",
  "defeatedTrainer": "倒された相手：",
  "defeatedTrainerDouble": "倒された相手：",
  "defeatedRival": "倒された相手：",
  "defeated":"敗北",
  "luck":"運",
  "score":"スコア",
  "mode":"モード",
  "challengeRules":"チャレンジ",
  "challengeMonoGen1":"I世代",
  "challengeMonoGen2":"II世代",
  "challengeMonoGen3":"III世代",
  "challengeMonoGen4":"IV世代",
  "challengeMonoGen5":"V世代",
  "challengeMonoGen6":"VI世代",
  "challengeMonoGen7":"VII世代",
  "challengeMonoGen8":"VIII世代",
  "challengeMonoGen9":"IX世代",
  "playerItems":"プレイヤーアイテム",
  "personalBest":"自己ベスト！",
  "SPDshortened":"速さ",//
  "runInfo":"ラン情報",
  "money":"お金",
  "runLength":"ラン最高ウェーブ",
  "viewHeldItems":"手持ちアイテム",
  "hallofFameText":"殿堂へようこそ！",
  "viewHallOfFame":"殿堂登録を見る！",
  "viewEndingSplash":"クリア後のアートを見る！"
```

2024-08-15 06:02 UTC, mercurius-00 commented on src/locales/zh_TW/run-history-ui-handler.ts
> +  "viewEndingSplash":"View ending art!"
```suggestion
  "victory": "勝利！",
  "defeatedWild": "被打敗",
  "defeatedTrainer": "被打敗",
  "defeatedTrainerDouble": "被組合打敗",
  "defeatedRival": "被勁敵打敗",
  "defeated":"被打敗",
  "luck":"幸運",
  "score":"分數",
  "mode":"模式",
  "challengeRules":"規則",
  "challengeMonoGen1":"I世代",
  "challengeMonoGen2":"II世代",
  "challengeMonoGen3":"III世代",
  "challengeMonoGen4":"IV世代",
  "challengeMonoGen5":"V世代",
  "challengeMonoGen6":"VI世代",
  "challengeMonoGen7":"VII世代",
  "challengeMonoGen8":"VIII世代",
  "challengeMonoGen9":"IX世代",
  "playerItems":"玩家道具",
  "personalBest":"個人最佳！",
  "SPDshortened":"速率",
  "runInfo":"遊戲記錄",
  "money":"金錢",
  "runLength":"遊戲時長",
  "viewHeldItems":"持有道具",
  "hallofFameText":"歡迎來到名人堂！",
  "viewHallOfFame":"浏覽名人堂！",
  "viewEndingSplash":"浏覽結算畫面"
```

2024-08-15 06:02 UTC, mercurius-00 commented on src/locales/zh_TW/menu-ui-handler.ts
> +  "RUN_HISTORY": "Run History",
```suggestion
  "RUN_HISTORY": "歷史記錄",
```

2024-08-15 06:02 UTC, mercurius-00 commented on src/locales/zh_TW/menu-ui-handler.ts
> +  "exportRunHistory":"Export Run History",
```suggestion
  "importRunHistory":"導入歷史記錄",
  "exportRunHistory":"導出歷史記錄",
```

2024-08-15 06:02 UTC, mercurius-00 commented on src/locales/zh_CN/run-history-ui-handler.ts
> +  "challengeMonoGen9":"九代",
```suggestion
  "challengeMonoGen1":"I世代",
  "challengeMonoGen2":"II世代",
  "challengeMonoGen3":"III世代",
  "challengeMonoGen4":"IV世代",
  "challengeMonoGen5":"V世代",
  "challengeMonoGen6":"VI世代",
  "challengeMonoGen7":"VII世代",
  "challengeMonoGen8":"VIII世代",
  "challengeMonoGen9":"IX世代",
```

2024-08-15 07:10 UTC, CodeTappert commented
Those are the two problems with the german images:
![image](https://github.com/user-attachments/assets/b9377166-d331-491c-95cf-7aa2039e5670)

The rest looks fine

(Besides the text beeing too long. But i honestly would just scale it down automatically if it gets to long)

2024-08-15 09:51 UTC, Adri1 commented
> Those are the two problems with the german images
> The rest looks fine
> 
> (Besides the text beeing too long. But i honestly would just scale it down automatically if it gets to long)

Yeah about the trainer category, il also raised that issue earlier
And about the hour format, I guess it's because it adjusts accortigly to the parameters of the system you play on, not on the language selected in Rogue

2024-08-15 11:05 UTC, AsdarDevelops commented on src/locales/es/run-history-ui-handler.ts
> +  "victory": "Victory!",
```suggestion
  "victory": "¡Victoria!",
```

2024-08-15 11:30 UTC, flx-sta requested changes
if you really want to bring it to the absolute next level you might wanna check if some of those new fields in the classes could be set to `readonly`. You should also check if the scopes (private/public/protected) are all correct and for all methods that are overwritten you should put a `override` in front of them to indicate that

2024-08-15 11:30 UTC, flx-sta commented on src/system/game-data.ts
> +      } else {
I mean at this point `lsItem` is basically cacheResponse. Might as well skip the unnecessary steps:

```suggestion
      const lsItemKey = `runHistoryData_${loggedInUser?.username}`;
      const cachedData = localStorage.getItem(lsItemKey);
      if (cachedData) {
        return Promise.resolve(JSON.parse(decrypt(cachedResponse, true)) as RunHistoryData);
      } else {
```

⚠️ Be aware that `return {};` is lost in the suggestion as I don't know if that still has a place then.

----

It might be worth it to wrap `JSON.parse(decrypt)` with `try/catch` since it can break fairly easy otherwise (I know this hasn't ever been done but we thrive to better)

2024-08-15 11:30 UTC, flx-sta commented on src/system/game-data.ts
> +  public async getRunHistoryData(scene: BattleScene): Promise<RunHistoryData> {
NIT: missing method docs

2024-08-15 11:30 UTC, flx-sta commented on src/system/game-data.ts
> +  async saveRunHistory(scene: BattleScene, runEntry : SessionSaveData, isVictory: boolean): Promise<boolean> {
NIT: Missing method docs

2024-08-15 11:30 UTC, flx-sta commented on src/system/game-data.ts
> +    }
⚠️ This is invalid by definition!

Your method at no point associates that it might return `null` or `undefined` thus a check should not be necessary! instead the method `this.getRunHistoryData(scene)` should be made sure to not return `null` or `undefined`

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +export default class RunHistoryUiHandler extends MessageUiHandler {
NIT: missing docs

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +    return success || error;
resolved I guess

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +  }
NIT: Keep naming consistent

```suggestion
  destroyCursor() {
    if (this.cursorObj) {
      this.cursorObj.destroy();
    }
    this.cursorObj = null;
  }
```

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +  clearruns() {
NIT: camel-case
```suggestion
  clearRuns() {
```

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +class RunEntryContainer extends Phaser.GameObjects.Container {
NIT: missing docs

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +          const gameOutcomeLabel = addTextObject(this.scene, 8, 5, `${i18next.t("runHistory:defeatedTrainer")+tObj.getName(0, true)}`, TextStyle.WINDOW);
NIT: odd use of template string.
Either
```suggestion
          const gameOutcomeLabel = addTextObject(this.scene, 8, 5, `${i18next.t("runHistory:defeatedTrainer")}${tObj.getName(0, true)}`, TextStyle.WINDOW);
```
or
```suggestion
          const gameOutcomeLabel = addTextObject(this.scene, 8, 5, i18next.t("runHistory:defeatedTrainer")  + tObj.getName(0, true), TextStyle.WINDOW);
```

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-history-ui-handler.ts
> +}
This is some weird pattern.. shouldn't this field just be part of the class? or why is this done?

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +export default class GameInfoUiHandler extends UiHandler {
NIT: Missing doc

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> + 		//const page = 0;
NIT: can this be deleted?

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +    this.modifiersModule = await import("../modifier/modifier");
I didn't know that's legit to do.
<sub>The more you know</sub>

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +    //this.updateStats();
Can this be deleted?

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +          enemy.destroy();
Consider moving this into it's own private method then
something like `private parse wildSingleResult()`

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +          enemyContainer.setPosition(8, 14);
Consider moving this into it's own private method.
e.g. `private parseWildDoubleResult()`

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +      }
Consider moving this into it's own private method 
e.g. `private parseTrainerResult()`

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +    runInfoText.appendText(`[color=#e8e8a8]\u20BD${Utils.formatLargeNumber(this.runInfo.money, 1000)}[/color]`);
NIT:
```suggestion
    runInfoText.appendText(`[color=${LIGHT_YELLOW}]\u20BD${Utils.formatLargeNumber(this.runInfo.money, 1000)}[/color]`);
```

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +          icon.setPosition(24 * (visibleModifierIndex%7), 20+(35*rowHeightModifier));
NIT: 
```suggestion
          icon.setPosition(24 * (visibleModifierIndex%7), 20 + (35 * rowHeightModifier));
```

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +            //itemIcon.setFrame(item.type.iconImage);
Can this be removed?

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +      (c.getByName("heldItems") as Phaser.GameObjects.Container).setVisible(!partyVisible);
If you look at the definition of `getByName()`:
```ts
getByName<T extends Phaser.GameObjects.GameObject>(name: string): T;
```
you can notice that passing custom interface as return type is possible through generic type definition.
You should use that

```suggestion
      c.getByName<Phaser.GameObjects.Container>("PkmnMoves").setVisible(partyVisible);
      c.getByName<Phaser.GameObjects.Container>("PkmnInfoText").setVisible(partyVisible);
      c.getByName<Phaser.GameObjects.Container>("PkmnStatsText").setVisible(partyVisible);
      c.getByName<Phaser.GameObjects.Container>("PkmnMarks").setVisible(partyVisible);
      c.getByName<Phaser.GameObjects.Container>("heldItems").setVisible(!partyVisible);
```

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +        });*/
Can this be deleted?

2024-08-15 11:30 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +  // Button.CYCLE_ABILITY (E key) --> shows pokemon held items
as @frutescens already mentioned:
Why not 
```ts
/**
 *
 */
 ```
 instead?

2024-08-15 18:34 UTC, frutescens commented on src/ui/run-info-ui-handler.ts
> +        });*/
Yes, I'll delete it.

2024-08-15 18:42 UTC, NicusPulcis reviewed
![momentanea](https://github.com/user-attachments/assets/568c4912-77f0-4732-8d6e-fdf873e5ac4b)
after taking a look at this, i edited a couple of text to be better formatted and fit in the boxes : )

2024-08-15 18:42 UTC, NicusPulcis commented on src/locales/it/run-history-ui-handler.ts
> +  "viewEndingSplash":"Visualizza arte finale!"
```suggestion
  "viewHeldItems":"Oggetti equip.",
  "hallofFameText":"Benvenuto alla Sala d'Onore!",
  "viewHallOfFame":"Vai alla Sala d'Onore!",
  "viewEndingSplash":"Vai all'arte finale!"
```

2024-08-15 18:52 UTC, frutescens commented
Fixing Incorrect Doubles titles
![image](https://github.com/user-attachments/assets/5f2e16b6-1cfc-480f-bffe-ebe3e3e60668)

2024-08-15 18:54 UTC, frutescens commented on src/ui/run-info-ui-handler.ts
> +          icon.setPosition(24 * (visibleModifierIndex%7), 20+(35*rowHeightModifier));
Sorry, I absent-mindedly edited your suggestion in.

2024-08-15 19:00 UTC, frutescens commented
Today's To-Do List
- [ ] Change text/container positioning based on text length (improving localizations)
- [ ] Break down large functions
- [ ] Write documentation
- [ ] Examine scope of variables + change to be reflective 
- [ ] Implement UI modes so the user has a more intuitive experience with exiting out of HoF/Ending Art 
- [ ] Implement more of flx-sta's suggestions

2024-08-16 00:09 UTC, Adri1 commented on src/locales/en/run-history-ui-handler.ts
> +  "SPDshortened":"Vel.",
Question, where this actually used, or just something that is supposed to be deleted?

2024-08-16 00:14 UTC, frutescens commented on src/ui/run-history-ui-handler.ts
> +}
This is so RunEntryContainer has access to scene. Just Phaser things.

2024-08-16 00:16 UTC, frutescens commented on src/locales/en/run-history-ui-handler.ts
> +  "SPDshortened":"Vel.",
Are you asking about SPDshortened? It's used for Spanish and Portuguese because Veloc. is too long.

2024-08-16 00:23 UTC, frutescens commented
@Adri1 - I apologize for the wait, but I updated the localization files to have male and female versions of 'Defeated X' and the hall of fame text. Thank you for your patience. I will eventually replace the pictures with updated versions, but the text is now dynamic and will position itself accordingly 
![image](https://github.com/user-attachments/assets/18c08655-fd10-487d-9934-157efc033167)

2024-08-16 00:23 UTC, Adri1 commented on src/locales/en/run-history-ui-handler.ts
> +  "SPDshortened":"Vel.",
Thanks for the clarification

2024-08-16 00:28 UTC, Adri1 commented
Oh! You're the best thanks for that!

While checking, I noticed that it displays "Wave" in English :
![image](https://github.com/user-attachments/assets/b9387c1c-0173-4865-8700-57de1a29b1d3)
Idk if it's something forgotten of still something in progres, but I notice you about it anyway 👌

2024-08-16 00:30 UTC, frutescens commented
That's my bad, whoops. Lots of moving pieces. Sending a quick-fix now

2024-08-16 00:36 UTC, Adri1 commented on src/locales/fr/run-history-ui-handler.ts
> +  "defeatedF":"Vaincu",
```suggestion
  "defeatedRivalM": "Battu par la Rivale",
  "defeatedM":"Vaincu",
  "defeatedWildF": "Battue par ",
  "defeatedTrainerF": "Battue par ",
  "defeatedTrainerDoubleF": "Battue par Duo",
  "defeatedRivalF": "Battue par le Rival",
  "defeatedF":"Vaincue",
```

2024-08-16 00:46 UTC, EnochG1 approved these changes

2024-08-16 03:21 UTC, frutescens commented
Tomorrow's To-Do List
- [ ] Examine scope of variables + change to be reflective of their actual use
- [ ] Run Info UI Handler Documentation
- [ ] Additional Documentation
- [ ] Misc. flx-sta changes
- [ ] Check if name handling of rivals have improved 
- [ ] Testing / Screenshots
    - [ ] Upload screenshots for all languages
    - [ ] Check Wild Single Battle Defeat
    - [ ] Check Wild Double Battle Defeat
    - [ ] Check Single Trainer with < 3 Pokemon Defeat
    - [ ] Check Single Trainer with > 3 Pokemon Defeat
    - [ ] Check Double Trainer Defeat
    - [ ] Check Daily Mode Victory + Defeat
    - [ ] Check Endless Mode Victory + Defeat
    - [ ] Check Challenges - Are rules being displayed properly? 
    - [ ] Spliced Pokemon
    - [ ] Behavior handling max # of runs - should delete the oldest one

2024-08-16 07:23 UTC, CodeTappert commented on src/locales/de/menu-ui-handler.ts
> +  "exportRunHistory":"Laufhistorie exportieren",
```suggestion
  "importRunHistory": "Laufhistorie importieren",
  "exportRunHistory": "Laufhistorie exportieren",
```

2024-08-16 07:23 UTC, CodeTappert commented on src/locales/de/run-history-ui-handler.ts
> +  "defeatedRivalF": "Besiegt durch Rivale",
```suggestion
  "defeatedRivalF": "Besiegt durch Rivalin",
```

2024-08-16 09:55 UTC, NicusPulcis approved these changes
italian male/female thingy fixed :) thanks for the new codes @frutescens

2024-08-16 09:55 UTC, NicusPulcis commented on src/locales/it/run-history-ui-handler.ts
> +  "defeatedF":"Sconfitti",
```suggestion
  "defeatedWildM": "Sconfitto da ",
  "defeatedTrainerM": "Sconfitto da ",
  "defeatedTrainerDoubleM": "Sconfitto dalla coppia ",
  "defeatedRivalM": "Sconfitto dal rivale",
  "defeatedM":"Sconfitto",
  "defeatedWildF": "Sconfitta da ",
  "defeatedTrainerF": "Sconfitta da ",
  "defeatedTrainerDoubleF": "Sconfitta dalla coppia ",
  "defeatedRivalF": "Sconfitta dal rivale",
  "defeatedF":"Sconfitta",
```

2024-08-16 11:41 UTC, CodeTappert commented on src/locales/de/run-history-ui-handler.ts
> +  "defeatedRivalM": "Besiegt durch Rivale",
```suggestion
  "defeatedRivalM": "Besiegt durch Rivalin",
```

2024-08-16 11:42 UTC, CodeTappert commented on src/locales/de/run-history-ui-handler.ts
> +  "defeatedRivalM": "Besiegt durch Rivale",
@frutescens Since those keys refer to the player gender apparently...
Make it more clear. For dialogue for example we use PGM and PGF (playerGenderMale and playerGenderFemale) 
so maybe "defeatedRivalPGM" etc

2024-08-16 11:58 UTC, flx-sta commented on src/locales/de/run-history-ui-handler.ts
> +  "defeatedRivalM": "Besiegt durch Rivale",
FYI a cleaner solution would be to use the `context` i18n object
https://www.i18next.com/translation-function/context#basic

```json
{
      "friend": "A friend",
      "friend_male": "A boyfriend",
      "friend_female": "A girlfriend"
}
```
```ts
i18next.t('friend'); // -> "A friend"
i18next.t('friend', { context: 'male' }); // -> "A boyfriend"
i18next.t('friend', { context: 'female' }); // -> "A girlfriend"
```

2024-08-16 12:00 UTC, AsdarDevelops reviewed
Added female protag texts

2024-08-16 12:00 UTC, AsdarDevelops commented on src/locales/es/run-history-ui-handler.ts
> +  "hallofFameTextF":"¡Bienvenido al Hall de la Fama!",
```suggestion
  "hallofFameTextF":"¡Bienvenida al Hall de la Fama!",
```

2024-08-16 12:00 UTC, AsdarDevelops commented on src/locales/es/run-history-ui-handler.ts
> +  "defeatedTrainerDoubleF": "Derrotado por un dúo",
```suggestion
  "defeatedWildF": "Derrotada por ",
  "defeatedTrainerF": "Derrotada por ",
  "defeatedTrainerDoubleF": "Derrotada por un dúo",
```

2024-08-16 12:00 UTC, AsdarDevelops commented on src/locales/es/run-history-ui-handler.ts
> +  "defeatedF":"Derrotado",
```suggestion
  "defeatedRivalF": "Derrotada por el rival",
  "defeatedF":"Derrotada",
```

2024-08-16 18:54 UTC, josericardo-fo commented on src/locales/pt_BR/run-history-ui-handler.ts
> +  "defeatedF": "Derrotado",
```suggestion
  "defeatedWildF": "Derrotada por ",
  "defeatedTrainerF": "Derrotada por ",
  "defeatedTrainerDoubleF": "Derrotada por Dupla",
  "defeatedRivalF": "Derrotada por Rival",
  "defeatedF": "Derrotada",
```

2024-08-17 01:13 UTC, Adri1 reviewed
Tiny French ajustements after seeing ```defeatedRival``` entries in a context

2024-08-17 01:13 UTC, Adri1 commented on src/locales/fr/run-history-ui-handler.ts
> +  "defeatedRivalF": "Battue par le Rival",
```suggestion
  "defeatedRivalM": "Battu par Rivale",
  "defeatedM":"Vaincu",
  "defeatedWildF": "Battue par ",
  "defeatedTrainerF": "Battue par ",
  "defeatedTrainerDoubleF": "Battue par Duo",
  "defeatedRivalF": "Battue par Rival",
```

2024-08-17 01:17 UTC, Adri1 commented
Would it be possible when you can, to have the run histroy menu with an entry where you are defeted by a wild Pokémon please ?🙏

2024-08-17 01:59 UTC, frutescens commented
@Adri1 
![image](https://github.com/user-attachments/assets/be51d0ae-8e3b-4190-a8d8-80aa62a4bce3)

2024-08-17 02:02 UTC, Adri1 commented
@frutescens I was more thinking about this screen :
![358781811-1ad32ad1-e722-4abf-a3fc-2e4986c23bf8](https://github.com/user-attachments/assets/a5643098-f94d-4c1e-8a87-e8d6d3d65cfb)

2024-08-17 03:34 UTC, frutescens commented
Ah, my bad @Adri1 
![image](https://github.com/user-attachments/assets/03c4b87b-c06a-476a-8221-d66f01b2b417)

2024-08-17 03:49 UTC, frutescens commented on src/system/game-data.ts
> +      } else {
Yes, I decided to go for a try/catch instead

2024-08-17 21:05 UTC, frutescens commented
Some of the Fusion names for non-English languages are very long. I believe that this PR should fix some of the issues. https://github.com/pagefaultgames/pokerogue/pull/3262

2024-08-21 02:49 UTC, Vassiat requested changes
Cursor is rendered before this for loop, so it is below windows

2024-08-21 02:49 UTC, Vassiat commented on src/ui/run-history-ui-handler.ts
> +    }
Cursor is rendered before this for loop, so it is below windows

2024-08-21 02:53 UTC, Vassiat commented on src/ui/run-history-ui-handler.ts
> +    }
```suggestion
    }
    if (this.cursorObj) {
      this.runsContainer.bringToTop(this.cursorObj);
      }
```

2024-08-21 03:21 UTC, frutescens commented on src/ui/run-history-ui-handler.ts
> +    }
wait... omg thank you so much

2024-08-21 04:07 UTC, Vassiat commented
I think it should be changed from where it is accessed, from `menu-ui-handler` to `title-phase`, and with it some locale from menuUiHandler to menu, because the log out is not being considered.

<img src="https://github.com/user-attachments/assets/bad248ef-f57c-47f6-92a6-2ede7ae7cd03"
         alt="image" />

<img src="https://github.com/user-attachments/assets/8104037c-fe8c-4791-b999-a6b6112cd1f3"
         alt="image" />

2024-08-21 05:07 UTC, frutescens commented
ah, I have a PR that will combine both vouchers and achievements together so there will be room

2024-08-21 05:46 UTC, Vassiat commented on src/ui/menu-ui-handler.ts
Due to the incorporation of importing/exporting runHistory, the MANAGE_DATA modal is a bit out of place, making it impossible to view the import/export session: 

![image](https://github.com/user-attachments/assets/9421077f-2bdb-4501-a7a2-6be9cbf80623)
> ### _This would only be seen in beta, as in production the import option is removed and in development the links_

### For this, I found two solutions:
- Add maxOptions to that modal:
``` ts
this.manageDataConfig = {
      xOffset: 98,
      options: manageDataOptions,
      maxOptions: 6
};
```
![image](https://github.com/user-attachments/assets/86697618-b3a6-48bc-baff-6aa81df9d3a5)

- Or make it scroll down depending on the number of options:
``` ts
//  if left is undefined, right assign
this.manageDataConfig.yOffset ??= this.manageDataConfig.options.length ** 1.66;

ui.setOverlayMode(Mode.MENU_OPTION_SELECT, this.manageDataConfig);
success = true;
```
![image](https://github.com/user-attachments/assets/11e095de-9bf5-4eaa-85a0-52fee139beb4)

2024-08-22 15:47 UTC, frutescens commented
![image](https://github.com/user-attachments/assets/defe6d91-cd97-43f6-b33f-3bb4c6ad5c14)

2024-08-22 16:18 UTC, frutescens commented
![image](https://github.com/user-attachments/assets/fbc2a29e-6940-4fff-b1e1-9a2ad1c5d18a)

2024-08-23 18:23 UTC, merged