Changed Bouncy Bubble to heal 100% of damage dealt
pagefaultgames/pokerogue pull request #326
Opened 2024-04-28 07:12 UTC by EggMuncherSupreme

Title. Previously only healed 50% of damage, which is accurate for LGPE, but based on the 60BP, it's clear the intention is to use the Gen 8 version.

2024-04-29 05:09 UTC, Xavion3 requested changes
Is it meant to not heal sleep?

2024-04-29 17:36 UTC, Madmadness65 requested changes

2024-04-29 17:36 UTC, Madmadness65 commented on src/data/move.ts
> +      .condition((user, target, move) => user.status && (user.status.effect === StatusEffect.PARALYSIS || user.status.effect === StatusEffect.POISON || user.status.effect === StatusEffect.TOXIC || us
```suggestion
      .attr(HealStatusEffectAttr, true, StatusEffect.PARALYSIS, StatusEffect.POISON, StatusEffect.TOXIC, StatusEffect.BURN, StatusEffect.SLEEP)
      .condition((user, target, move) => user.status && (user.status.effect === StatusEffect.PARALYSIS || user.status.effect === StatusEffect.POISON || user.status.effect === StatusEffect.TOXIC || user.status.effect === StatusEffect.BURN || user.status.effect === StatusEffect.SLEEP)),
```
Remember to account for the Sleep Talk edge case when curing all non-volatile statuses.

2024-05-05 05:46 UTC, Madmadness65 approved these changes

2024-05-05 16:01 UTC, merged