[Ability] Implement Ability Illusion
pagefaultgames/pokerogue pull request #3273
Opened 2024-07-31 20:35 UTC by PyGaVS

## What are the changes?

Adding illusion ability, works with fusion also

## Why am I doing these changes?

It's missing

## What did change?

-Added PreSummonAbAttr class as ability attribute.
-Illusion uses the appearance of the last conscious and available Pokémon in the party (ignoring itself), including :
Species, Form, Shininess, Pokeball, Gender
-If We encounter a wild Zorua/Zoroak he will use the illusion of a pokemon in the Abyss Biome. Depending on Zorua or Zoroark level the illusion will be evolved or not.
-If we encounter a boss Zoroark he will use the illusion of Entei, Suicune or Raiku like in the original game.
-The class pokemon has a new attribute illusion.
-A pokemon with illusion can use illusion one time per battle like in the original game.
-After a battle, the pokemon can use illusion again.
-The AI move choice will be affected by the illusion.
-The type will always be displayed as the Pokémon it is disguised as, even when affected by Soak etc.
-The illusion will disappear if the Pokemon has its ability changed or suppressed.
-Pokemon cannot transform into a Pokémon that is disguised by Illusion.
-Pokémon that are disguised by Illusion cannot Transform.
-Illusion will not activate if the last conscious Pokémon is a Terastallized Ogerpon or Terapagos.

### Screenshots/Videos

https://discord.com/channels/1125469663833370665/1176874654015684739/1257835032647831682
https://discord.com/channels/1125469663833370665/1176874654015684739/1257864381937619045
https://discord.com/channels/1125469663833370665/1176874654015684739/1257865512801538059
https://discord.com/channels/1125469663833370665/1176874654015684739/1258418548074745958

## How to test the changes?

I played Zoroark and override the enemy pokemon with Zoroark so we can see him using correct illusion
I used illusion on a fusion and with a fusion
I tried to switch with the illusion
We can also run `npm run test illusion`

Old conversations here : 
https://github.com/pagefaultgames/pokerogue/pull/2217

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-07-31 20:36 UTC, PyGaVS commented
I don't know why but Github is considering that there are changes in package-lock.json and items.json files but there is not.

2024-08-02 16:29 UTC, xsn34kzx reviewed
Mostly NITs and minor adjustments. Brought up the idea of making `illusion` a property of `summonData` rather than to `Pokemon` directly, may be something to look into but ultimately not a deal breaker.

2024-08-02 16:29 UTC, xsn34kzx commented on src/field/pokemon.ts
> +  isFusion(useIllusion: boolean = false): boolean {
Using this example for a larger idea: not necessarily a fan of attaching `useIllusion` to every function, feels a bit too specific; however, it would make sense for this to be `ignoreOverride` (meaning that Illusion and things like Transform are treated generically as "overrides" in name) like other functions (see `getFusionGender`, `getSpeciesForm`, etc.) that act similarly. 

As an aside though, I wonder if Illusion data and state could've been put in `summonData` instead of being directly attached to the `Pokemon` class. This isn't a necessary change, just a thought.

2024-08-02 16:29 UTC, xsn34kzx commented on src/test/abilities/illusion.test.ts
> +  it("disappear if the ability is suppressed", async () => {
NIT: `disappear` across all test names should be changed to `break` for consistency (because of `breakIllusion()`)

2024-08-02 16:29 UTC, xsn34kzx commented on src/test/abilities/illusion.test.ts
> +  it("trick the enemy AI", async () => {
I get what this test does, but it should have a more descriptive name (e.g., `move effectiveness uses ILLUSION type instead of original type`).

2024-08-02 16:29 UTC, xsn34kzx commented on src/test/abilities/illusion.test.ts
> +    expect(psychicEffectiveness).above(flameThwowerEffectiveness);
```suggestion
    const flameThrowerEffectiveness = zoroark.getAttackMoveEffectiveness(enemy, enemy.getMoveset()[0], false, true);
    const psychicEffectiveness = zoroark.getAttackMoveEffectiveness(enemy, enemy.getMoveset()[1], false, true);

    expect(psychicEffectiveness).above(flameThrowerEffectiveness);
```
NIT: Misspelled flamethrower

2024-08-03 00:57 UTC, torranx requested changes

2024-08-03 00:57 UTC, torranx commented on src/data/ability.ts
> +    });
\+ on this and curious why its on a loop?

2024-08-03 00:57 UTC, torranx commented on src/data/ability.ts
> +    pokemon.scene.queueMessage(i18next.t("abilityTriggers:illusionBreak", { pokemonName: getPokemonNameWithAffix(pokemon) }));
this 2 seem to be always present together, would it not be ideal to include the `queueMessage` in `breakIllusion()`?

2024-08-03 00:57 UTC, torranx commented on src/data/ability.ts
> +export class IllusionAfterBattle extends PostBattleAbAttr {
shouldn't Illusion follow Ice Face and Disguise implementation where "after battle" means when the arena resets?

2024-08-03 00:57 UTC, torranx commented on src/field/pokemon.ts
> +    this.illusion = {active: false, available: true};
nit
```suggestion
    this.illusion = { active: false, available: true };
```

2024-08-03 00:57 UTC, torranx commented on src/test/abilities/illusion.test.ts
> +    vi.spyOn(overrides, "STARTING_HELD_ITEMS_OVERRIDE", "get").mockReturnValue([{name: "WIDE_LENS", count: 3}]);
please use the new test helpers

2024-08-03 00:57 UTC, torranx commented on src/test/abilities/illusion.test.ts
> +  it("create illusion at the start", async () => {
nit
```suggestion
  it("creates illusion at the start", async () => {
```

2024-08-03 00:57 UTC, torranx commented on src/test/abilities/illusion.test.ts
> +
nit
```suggestion
```

2024-08-03 00:57 UTC, torranx commented on src/test/abilities/illusion.test.ts
> +  it("disappear after receiving damaging move and changing ability move", async () => {
this should be in 2 different test cases (1 for damaging move and 1 for ability changing move)

2024-08-03 00:57 UTC, torranx commented on src/test/abilities/illusion.test.ts
> +  it("do not disappear if the pokemon takes indirect damages", async () => {
please also test for moves like Flame Burst

2024-08-03 01:14 UTC, torranx commented
Please add spaces before and after the video links so it embeds correctly, and add label on what the video shows.

2024-08-04 05:14 UTC, Madmadness65 commented on src/locales/pt_BR/config.ts
> +import { arenaFlyout } from "./arena-flyout";
This is a duplicate import, it can be removed

2024-08-04 13:26 UTC, PyGaVS commented on src/locales/pt_BR/config.ts
> +import { arenaFlyout } from "./arena-flyout";
ok

2024-08-04 13:31 UTC, PyGaVS commented on src/test/abilities/illusion.test.ts
> +  it("do not disappear if the pokemon takes indirect damages", async () => {
ok

2024-08-04 13:34 UTC, PyGaVS commented on src/data/ability.ts
> +    pokemon.scene.queueMessage(i18next.t("abilityTriggers:illusionBreak", { pokemonName: getPokemonNameWithAffix(pokemon) }));
yes

2024-08-04 13:39 UTC, PyGaVS commented on src/data/ability.ts
> +export class PreSummonAbAttr extends AbAttr {
ok

2024-08-04 13:41 UTC, PyGaVS commented on src/data/ability.ts
> +    });
> + on this and curious why its on a loop?

It's on loop for checking every pokemons on the field

2024-08-04 13:41 UTC, PyGaVS commented on src/data/ability.ts
> +export class IllusionAfterBattle extends PostBattleAbAttr {
ok

2024-08-04 13:45 UTC, PyGaVS commented on src/data/ability.ts
> +    });
> Does this have to be in the generic `PostSummonMessageAbAttr` or can it be in its own extended class?

so i will do a `PostSummonIllusionDisableAbAttr` class

2024-08-04 14:01 UTC, PyGaVS commented on src/field/pokemon.ts
> +  isFusion(useIllusion: boolean = false): boolean {
ignoreOverride and useIllusion or not the same parameter they are not synced, sometime we want to ignoreOverride and still useIllision i can't use ignoreOverride for illusion. Same for summonData we don't want to change the type of the Pokemon but only the displayed type and that's not the same thing

2024-08-04 14:02 UTC, PyGaVS commented on src/test/abilities/illusion.test.ts
> +  it("disappear if the ability is suppressed", async () => {
ok

2024-08-04 14:03 UTC, PyGaVS commented on src/test/abilities/illusion.test.ts
> +  it("trick the enemy AI", async () => {
yes good idea

2024-08-04 14:05 UTC, PyGaVS commented on src/test/abilities/illusion.test.ts
> +    expect(psychicEffectiveness).above(flameThwowerEffectiveness);
my bad

2024-08-04 14:20 UTC, PyGaVS commented on src/data/ability.ts
> +export class IllusionAfterBattle extends PostBattleAbAttr {
No because it break when it's the SelectModifierPhase, that's force switch and do not give immunity

2024-08-04 14:25 UTC, PyGaVS commented on src/test/abilities/illusion.test.ts
> +    vi.spyOn(overrides, "STARTING_HELD_ITEMS_OVERRIDE", "get").mockReturnValue([{name: "WIDE_LENS", count: 3}]);
ok

2024-08-04 14:30 UTC, PyGaVS commented on src/test/abilities/illusion.test.ts
> +  it("disappear after receiving damaging move and changing ability move", async () => {
ok

2024-08-19 13:25 UTC, torranx reviewed
I still don't like how it's adding `useIllusion`- a very specific parameter just for illusion to a lot of functions

2024-08-19 17:21 UTC, PyGaVS commented on src/data/ability.ts
> +   * @param {boolean} passive - N/A
they asked me to do that but np i will remove lol

2024-08-19 17:21 UTC, PyGaVS commented on src/data/ability.ts
> + * (should use {@linkcode PostSummonAbAttr} for most ability)
same here

2024-08-19 17:25 UTC, PyGaVS commented on src/data/ability.ts
> +export class PostSummonRemoveIllusionAbAttr extends PostSummonAbAttr {
It's for pokemon who has ability like neutralizing gas that breaks illusion if a pokemon has an illusion on the field. Some dev asked me to create that class too

2024-08-19 19:19 UTC, PyGaVS commented on src/field/pokemon.ts
> +  public illusion: Illusion;
ok

2024-08-19 19:19 UTC, PyGaVS commented on src/data/ability.ts
> +    });
ok

2024-08-19 19:20 UTC, PyGaVS commented on src/data/ability.ts
>      }
i will change that

2024-08-19 20:50 UTC, PyGaVS commented on src/data/ability.ts
> +    });
the pokemon is not on field so i still need to check if there is SuppressFieldAbilitiesAbAttr, but i can shorten it

2024-08-25 11:50 UTC, CodeTappert commented
Please fix the problems before requesting a review

2024-10-02 15:59 UTC, flx-sta commented
@PyGaVS are you still working on this?

2024-10-10 15:56 UTC, PyGaVS commented
Okay i forgot that Zoroark can update his illusion if it's available after a switchout so i need to update that.
Otherwise i can't use BattleData or SummonData because i need to store a data (if the illusion is available or not) after a switchout if you know a way to use Illusion in SummonData or BattleData tell me.

2024-10-14 17:55 UTC, torranx commented
> The useIllusion parameter that's now fed to a lot of methods in Pokemon needs to change to account for future implementations that may want a similar effect (e.g. the enemy AI adjusting for form changes when evaluating type matchups). It would probably be more beneficial to adjust it to the inverse (say, useBaseType) where, if true, all effects that may change the Pokemon's observed type are ignored.

Did you consider updating your PR with this suggestion? Or have you got any idea on an alternative that would eliminate the use of the specific `useIllusion` param?

2024-10-15 13:45 UTC, PyGaVS commented
> > The useIllusion parameter that's now fed to a lot of methods in Pokemon needs to change to account for future implementations that may want a similar effect (e.g. the enemy AI adjusting for form changes when evaluating type matchups). It would probably be more beneficial to adjust it to the inverse (say, useBaseType) where, if true, all effects that may change the Pokemon's observed type are ignored.
> 
> Did you consider updating your PR with this suggestion? Or have you got any idea on an alternative that would eliminate the use of the specific `useIllusion` param?

@torranx i have got an idea tell me if this is better : we can add a param named "..._args: any[]" where we put additional arguments for specific params do you prefer this idea or should i rename useIllusion param ?

2024-10-25 16:28 UTC, innerthunder commented
> @torranx i have got an idea tell me if this is better : we can add a param named "..._args: any[]" just like in ability.ts where we put additional arguments for specific params do you prefer this idea or should i rename useIllusion param ?

Not sure how well this would work (typically the "...args" functions should be overridden by subclasses for stricter typing), but generally speaking it's better practice to use `unknown` over `any` to enforce stricter type checks.

2024-10-25 16:39 UTC, innerthunder commented on src/data/move.ts
> +      user.scene.queueMessage(i18next.t("battle:attackFailed"));
Do this through `getCondition` instead. Otherwise, it won't actually register using a failed move

2024-10-25 16:39 UTC, innerthunder commented on src/field/pokemon.ts
> +
```suggestion
```

2024-10-25 20:38 UTC, PyGaVS commented on src/data/move.ts
> +      user.scene.queueMessage(i18next.t("battle:attackFailed"));
ahhh yes

2024-11-04 21:42 UTC, damocleas reviewed
Should try to check for Sub Legendaries / Mythicals / (and last resort) Legendaries (maybe if none of any of these can be found, another mon in the biome) in equal or higher boss tiers than a set 'Entei/Raikou/Suicune', as they aren't in every biome, but every biome does have a sub legend in it. Hope this makes sense, discussed on discord.

2024-11-08 16:27 UTC, flx-sta submitted a review, later dismissed

2024-11-08 23:10 UTC, innerthunder requested changes
The enemy AI currently uses damage calculations to search for KOs, and will likely make more use of damage calculations when evaluating moves in the future. This means that the `Illusion` class should supply effective stats (HP, Attack, Defense, etc.) in support of bidirectional damage calculations. It might be easier to use a direct `Pokemon` reference in illusion and construct a new `Pokemon` object in cases where the Illusion isn't based on party Pokemon (i.e. Wild battles).

2024-11-08 23:10 UTC, innerthunder commented on src/field/pokemon.ts
> +   * @param useIllusion - `true` to return the types of the illusion instead of the actual types; Default: "AUTO"
Needs docs on the meaning behind the "AUTO" setting

2024-11-09 01:06 UTC, torranx submitted a review, later dismissed
this is still using the very specific param for illusion `useIllusion`. if other devs are ok with it, feel free to dismiss my `requested changes`

2024-11-09 10:42 UTC, PyGaVS commented on src/field/pokemon.ts
> +   * @param useIllusion - `true` to return the types of the illusion instead of the actual types; Default: "AUTO"
ok

2024-11-09 10:53 UTC, PyGaVS commented
> this is still using the very specific param for illusion `useIllusion`. if other devs are ok with it, feel free to dismiss my `requested changes`

@torranx i didn't found a better alt because we can't rename the params to a less specific name for 2 reasons :
- this param will always be specific because the illusion mechanic itself is specific
- if we rename this params other devs in the future will not understand the utility of this param

Maybe we can create a "purpose" param where purpose can either be "attack", "battleInfo", etc but only the illusion mechanic will use it today, so idk

2024-11-10 03:18 UTC, torranx commented
> @torranx i didn't found a better alt because we can't rename the params to a less specific name for 2 reasons :
> 
> * this param will always be specific because the illusion mechanic itself is specific
> * if we rename this params other devs in the future will not understand the utility of this param
> 
> Maybe we can create a "purpose" param where purpose can either be "forDefend", "battleInfo", etc but only the illusion mechanic will use it today, so idk

First of all thank you for being patient with us.
Regarding the param, it doesn't need to be specific, see @innerthunder 's [comment](https://github.com/pagefaultgames/pokerogue/pull/3273#pullrequestreview-2246210211)

2024-11-28 18:04 UTC, PyGaVS commented
> > @torranx i didn't found a better alt because we can't rename the params to a less specific name for 2 reasons :
> > 
> > * this param will always be specific because the illusion mechanic itself is specific
> > * if we rename this params other devs in the future will not understand the utility of this param
> > 
> > Maybe we can create a "purpose" param where purpose can either be "forDefend", "battleInfo", etc but only the illusion mechanic will use it today, so idk
> 
> First of all thank you for being patient with us. Regarding the param, it doesn't need to be specific, see @innerthunder 's [comment](https://github.com/pagefaultgames/pokerogue/pull/3273#pullrequestreview-2246210211)

I will do it later

2025-01-22 15:58 UTC, PyGaVS commented
> The enemy AI currently uses damage calculations to search for KOs, and will likely make more use of damage calculations when evaluating moves in the future. This means that the `Illusion` class should supply different effective stats (HP, Attack, Defense, etc.) in support of bidirectional damage calculations. It might be easier to use a direct `Pokemon` reference in illusion and construct a new `Pokemon` object in cases where the Illusion isn't based on party Pokemon (i.e. Wild battles).

So i used a direct Pokemon reference for base Pokemon in the interface Illusion this is now way better.
But for the specific params illusion i tried to remove it by adding other func for illusion but when i do that i'm forced to add if statement with illusion everywhere in the ui files

2025-01-29 13:44 UTC, Mourouh commented
https://github.com/user-attachments/assets/9efb92f4-8f6f-4282-8356-71b0317519f8

Illusion seems to be getting revealed in the battle end phase? Happens after both wild and trainer battles. Refreshing fixes it back. Recalling the Pokémon or arena change puts the illusion back.

It's not a visual error because move generation adapts to it. Tested this by doing this override and selecting Zorua and a Normal Type like Lillipup. On wave 2 the move AI will favour Hex on what's supposed to be a Normal type illusion Zorua. 

`OPP_MOVESET_OVERRIDE: [Moves.HEX, Moves.PSYBEAM]`

2025-01-29 15:51 UTC, PyGaVS commented
> Video.sin.titulo.Hecho.con.Clipchamp.1.mp4 
> Illusion seems to be getting revealed in the battle end phase? Happens after both wild and trainer battles. Refreshing fixes it back. Recalling the Pokémon or arena change puts the illusion back.
> 
> It's not a visual error because move generation adapts to it. Tested this by doing this override and selecting Zorua and a Normal Type like Lillipup. On wave 2 the move AI will favour Hex on what's supposed to be a Normal type illusion Zorua.
> 
> `OPP_MOVESET_OVERRIDE: [Moves.HEX, Moves.PSYBEAM]`



> Video.sin.titulo.Hecho.con.Clipchamp.1.mp4 
> Illusion seems to be getting revealed in the battle end phase? Happens after both wild and trainer battles. Refreshing fixes it back. Recalling the Pokémon or arena change puts the illusion back.
> 
> It's not a visual error because move generation adapts to it. Tested this by doing this override and selecting Zorua and a Normal Type like Lillipup. On wave 2 the move AI will favour Hex on what's supposed to be a Normal type illusion Zorua.
> 
> `OPP_MOVESET_OVERRIDE: [Moves.HEX, Moves.PSYBEAM]`

it was intentionnal but while correcting it i found another bug when we save and quit so i will update this pr this week end

2025-03-02 21:05 UTC, PyGaVS commented
> > Video.sin.titulo.Hecho.con.Clipchamp.1.mp4
> > Illusion seems to be getting revealed in the battle end phase? Happens after both wild and trainer battles. Refreshing fixes it back. Recalling the Pokémon or arena change puts the illusion back.
> > It's not a visual error because move generation adapts to it. Tested this by doing this override and selecting Zorua and a Normal Type like Lillipup. On wave 2 the move AI will favour Hex on what's supposed to be a Normal type illusion Zorua.
> > `OPP_MOVESET_OVERRIDE: [Moves.HEX, Moves.PSYBEAM]`
> 
> > Video.sin.titulo.Hecho.con.Clipchamp.1.mp4
> > Illusion seems to be getting revealed in the battle end phase? Happens after both wild and trainer battles. Refreshing fixes it back. Recalling the Pokémon or arena change puts the illusion back.
> > It's not a visual error because move generation adapts to it. Tested this by doing this override and selecting Zorua and a Normal Type like Lillipup. On wave 2 the move AI will favour Hex on what's supposed to be a Normal type illusion Zorua.
> > `OPP_MOVESET_OVERRIDE: [Moves.HEX, Moves.PSYBEAM]`
> 
> it was intentionnal but i found a bug when it's corrected so i will update this pr when i will have time again

Update : bug solved !

2025-03-30 20:14 UTC, SirzBenjie requested changes
This PR is a large endeavor, and it is admirable that you have been continually updating it as we release new updates.

I believe the in-game behavior for illusion is mostly right (with the exception of the boss pokemon chosen for the illusion), as the AI is properly considering the type, etc.
We may want to discuss with the balance team whether the pokemon's level should also be faked.

I am a bit perturbed by the `breakIllusion` method. First, it's using the `!` operator to avoid null checks. We should avoid that when possible.
Unless I'm missing something, clearing the illusion should be as simple as setting `this.battleData.illusion` to be undefined. Then, in each of the methods that checks against illusion, all it needs to do is access the property it is looking for and do nullish coalescing.
This will free up all of that data when it doesn't need to be there anymore. (I assume that once an illusion is broken, it can never re-activate?)


(e.g. as you have done in `getPlayerParty()`

```ts
pokemon.fusionVariant = pokemon.battleData?.illusion.basePokemon?.fusionVariant ?? pokemon.fusionVariant;
pokemon.fusionShiny = pokemon.battleData?.illusion.basePokemon?.fusionShiny ?? pokemon.fusionShiny
```

2025-03-30 20:14 UTC, SirzBenjie commented on src/data/ability.ts
> +  }
I believe this needs to be changed into `canApplyPostDefend` and `applyPostDefend` from #5267

2025-03-30 20:14 UTC, SirzBenjie commented on src/data/ability.ts
> +    return true;
Split in accordance with #5267

2025-03-30 20:14 UTC, SirzBenjie commented on src/field/pokemon.ts
> +        availables = [ Species.ENTEI, Species.RAIKOU, Species.SUICUNE ];
The choices for which legendary to use as boss need to be re-evaluated. Probably do this based on biome.

2025-03-31 07:22 UTC, emdeann commented on src/field/pokemon.ts
> +          globalScene.load.once(Phaser.Loader.Events.COMPLETE, () => {
The missing frame comment is unrelated to this pr, looks like it was just moved

2025-03-31 09:27 UTC, PyGaVS commented on src/field/pokemon.ts
> +   * @param {boolean} fakeShininess - Whether we want the fake or real shininess (illusion ability).
Some dev wanted me to rename these parameters to be usable for similar effect

2025-03-31 09:55 UTC, PyGaVS commented
> Unless I'm missing something, clearing the illusion should be as simple as setting this.battleData.illusion to be undefined. Then, in each of the methods that checks against illusion, all it needs to do is access the property it is looking for and do nullish coalescing.

This is not that simple : if Illusion isn't active we need to know if it's broken or available and if the illusion is active e also want the base pokemon properties to be accessible depending on the use, that's why there is so many parameters everywhere

2025-03-31 09:56 UTC, PyGaVS commented on src/messages.ts
>   * @param pokemon {@linkcode Pokemon} name and battle context will be retrieved from this instance
yes

2025-03-31 10:10 UTC, PyGaVS commented on src/field/pokemon.ts
> +  isDoubleShiny(fakeShininess: boolean = false): boolean {
yes

2025-03-31 10:48 UTC, PyGaVS commented on src/data/ability.ts
> +  }
done

2025-03-31 14:16 UTC, PyGaVS commented on src/field/pokemon.ts
> +          globalScene.load.once(Phaser.Loader.Events.COMPLETE, () => {
the code was just moved

2025-04-01 18:20 UTC, PyGaVS commented
> > This is not that simple : if Illusion isn't active we need to know if it's broken or available and if the illusion is active e also want the base pokemon properties to be accessible depending on the use, that's why there is so many parameters everywhere
> 
> What I'm specifically asking is, why do we need to know whether it's broken or active? Is there an interaction that can turn the illusion back on other than switching? Can't the on summon attribute just activate it, and then set these properties? And then when it's broken, it goes away completely.

@SirzBenjie the corrections are done

2025-04-01 21:34 UTC, SirzBenjie commented on src/data/ability.ts
> +      if ( lastPokemon === pokemon || !!pokemon.summonData?.illusion ||
```suggestion
      // Terapagos and Ogergpon cannot be an illusion if either they or the pokemon with illusion is terastallized.
      // See https://bulbapedia.bulbagarden.net/wiki/Illusion_(Ability)#Generation_IX
      if ( lastPokemon === pokemon || !!pokemon.summonData?.illusion ||
```

2025-04-01 21:34 UTC, SirzBenjie commented on src/data/ability.ts
> +   * @returns {boolean} - Whether the illusion was applied.
```suggestion
   * @param pokemon - The Pokémon with the Illusion ability.
   * @param passive - Unused
   * @param args - Unused
   * @returns - Whether the illusion was applied.
```

2025-04-01 21:34 UTC, SirzBenjie commented on src/data/ability.ts
> +   * Destroy illusion if attack move deals damage to zoroark
```suggestion
   * Destroy the illusion upon taking damage
```

2025-04-01 21:34 UTC, SirzBenjie commented on src/data/ability.ts
> +    }*/
```suggestion
```

2025-04-01 21:34 UTC, SirzBenjie commented on src/data/ability.ts
> +   * Illusion will be available again after a battle and apply the illusion of the pokemon is already on field
```suggestion
   * Break the illusion once the battle ends
```

2025-04-01 21:34 UTC, SirzBenjie commented on src/field/pokemon.ts
> +      */
```suggestion
```

2025-04-01 21:34 UTC, SirzBenjie commented on src/battle-scene.ts
> +    if (!useIllusion) {
This looks to be a bug, should be `useIllusion`, right? (or should the argument name be inverted?)

2025-04-01 21:53 UTC, PyGaVS commented on src/battle-scene.ts
> +    if (!useIllusion) {
By default we want to take the illusion in consideration. In case of saving (when we want to save the party), useIllusion parameter is set to false so the Zorua is saved properly without his properties being changed by illusion.

2025-04-01 23:57 UTC, SirzBenjie commented
Just to hash out what we discussed on discord.

We want to remove the `basePokemon` reference inside of the `Illusion` interface.
The illusion interface should contain _only_ the information about the pokemon featured in the illusion.
So it should look something like this:
```ts
/**
 * Illusion property
 */
interface Illusion {
  /**
   * Whether the illusion is active or not.
   * @type {boolean}
   */
  //active: boolean;
  /**
   * Whether the pokemon can generate an illusion or not.
   * @type {boolean}
   */
  //available: boolean;
  /** The name of the pokemon in the illusion*/
  name: string,
  /** The nickname of the pokemon in the illusion*/
  nickname: string
  /** The speciesId of the pokemon in the illusion*/
  speciesId: Species;
  /** The formIndex of the illusion */
  formIndex: number;
  /** The gender of the pokemon in the illusion
  gender: Gender;
  // And so on...
}
```

Then, you make each of these properties from the pokemon `private` (actually, likely `protected` so that the subclasses can acccess them).
All of the getter methods for these properties would then take a `useIllusion` parameter (which likely defaults to `true`). For example:

```ts
getGender(useIllusion = true) {
  if (useIllusion && this.summonData.illusion) {
    return this.summonData.illusion.gender;
  }
  return this.gender;
}
```

2025-04-10 14:06 UTC, SirzBenjie approved these changes
I think this is in a sufficient state that it's time to get it into the codebase.

2025-04-10 17:47 UTC, Madmadness65 approved these changes
At long last, it seems its finally ready to be merged 🎉
Everything seems to function as intended from a player's perspective from my in-game testing, so this lgtm

2025-04-10 22:02 UTC, DayKev commented on src/field/pokemon.ts
> +
```suggestion
```

2025-04-10 22:02 UTC, DayKev commented on src/field/pokemon.ts
> +        (!!!this.summonData?.illusion || !doIllusion)
```suggestion
        (!this.summonData?.illusion || !doIllusion)
```

2025-04-10 22:30 UTC, SirzBenjie commented on src/data/ability.ts
> +   * @returns {boolean} - Whether the illusion was applied.
```suggestion
   * @param pokemon - The Pokémon with the Illusion ability.
   * @param passive - N/A
   * @param args - N/A
   * @returns Whether the illusion was applied.
```

2025-04-10 22:32 UTC, SirzBenjie commented on src/field/pokemon.ts
> +   * @param {boolean} useIllusion - Whether we want the attack move effectiveness on the illusion or not
```suggestion
   * @param useIllusion - Whether we want the attack move effectiveness on the illusion or not
```

2025-04-10 22:32 UTC, SirzBenjie commented on src/field/pokemon.ts
> +   * @param {boolean} useIllusion - Whether we want the attack type effectiveness on the illusion or not
```suggestion
   * @param useIllusion - Whether we want the attack type effectiveness on the illusion or not
```

2025-04-10 22:56 UTC, SirzBenjie commented on src/field/pokemon.ts
> +  level?: number
```suggestion
  basePokemon: {
    /** The actual name of the Pokemon. */
    name: string;
    /** The actual nickname of the Pokemon */
    nickname: string;
    /** Whether the base pokemon is shiny or not */
    shiny: boolean;
    /** The shiny variant of the base pokemon */
    variant: Variant;
    /** Whether the fusion species of the base pokemon is shiny or not */
    fusionShiny: boolean;
    /** The variant of the fusion species of the base pokemon */
    fusionVariant: Variant;
  };
  /** The species of the illusion. */
  species: Species;
  /** The formIndex of the illusion */
  formIndex: number;
  /** The gender of the illusion*/
  gender: Gender;
  /** The pokeball of the illusion */
  pokeball: PokeballType;
  /** The fusion species of the illusion if it's a fusion */
  fusionSpecies?: PokemonSpecies;
  /** The fusionFormIndex of the illusion */
  fusionFormIndex?: number;
  /** The fusionGender of the illusion if it's a fusion */
  fusionGender?: Gender;
  /** The level of the illusion (not used currently) */
  level?: number
```

2025-04-11 16:53 UTC, SirzBenjie submitted a review, later dismissed

2025-04-11 16:56 UTC, Madmadness65 submitted a review, later dismissed

2025-04-13 00:07 UTC, DayKev approved these changes

2025-04-13 00:09 UTC, DayKev approved these changes

2025-04-13 00:41 UTC, Madmadness65 approved these changes

2025-04-13 01:18 UTC, xsn34kzx approved these changes

2025-04-13 01:22 UTC, merged