[QoL] IV scanner update to hide the prompt and let you see the stats mid battle on the stats screen
pagefaultgames/pokerogue pull request #3285
Opened 2024-08-01 15:13 UTC by Opaque02

This is a remake of #2451 in the current beta branch since the commit merge thingy. Also I'd like to thank DayKev because without their help I'd be writing this code from scratch, so thanks!

## What are the changes?
The IV scanner has been updated in two ways - the first is a setting that will allow you to disable the IV scanner prompt and all associated parts (animation, message etc), and the second is to change the stat container labels to show green/gold for the IV mid battle to show if the stats of the pokemon are better than what you've currently got.

## Why am I doing these changes?
A lot of people on discord have mentioned this is a feature they wanted, so I decided to make it

## What did change?
The first option is a setting that enables or disables the prompt about scanning a pokemon's IV. This is under the "general" tab of the settings.

The second option is to change the labels of the stat container to be green or gold depending on the stat. The stats container will show you the same amount of IV updates that you would from the IV scanner - so if you have no scanners you won't see any updates, all the way up to seeing all 6 stats for 3 scanners. If the stat is better than what you have, it'll show green, whereas if it's perfect IV it'll show gold; this is so if you do have the prompts being skipped, you can still see if the stat is perfect. Lastly, if the stat is unknown (not enough scanners), not scanned (ACC/EVA), or equal/worse than what you have, the label is white as usual.

The next change is to do with the stat labels themselves. Now if you have at least one IV scanner, the enemy stats will show a label for HP. There is no +/- number associated with it, as it's just there purely for IV purposes. This label does not show for player pokemon, and only shows when an IV scan would happen - so this label doesn't show for trainer battles

The last change is with how the IV scanner (and thus my code) and the pokemon info container (the container that shows when you catch/hatch a pokemon with the IV spread of the pokemon) work. The pokemon info container shows you increases against the baby form of a pokemon if it's available. For example, catching wigglytuff will show you how much of an increase igglybuff's IVs will take, whereas the IV scanner compares it against the non-baby form - in this case, jigglypuff. This means if jigglypuff and igglybuff have different IV spreads, they will show differently through the IV scanner and the pokemon info container. This last change makes it consistent. See pictures in the below section to see a before/after of this.

### Screenshots/Videos
Here is a screenshot of the settings screen showing the new setting:

![image](https://github.com/pagefaultgames/pokerogue/assets/66582645/fd1a9d34-0b39-4c5b-8be3-129595bb1d51)

Here is a screenshot of the stats screen in battle showing some stats and the IV scanner on screen:

![image](https://github.com/pagefaultgames/pokerogue/assets/66582645/e6fe13b1-bd68-4a95-a3ae-b6cd918a0316)

As you can see, the only stats that are better than what we have are HP, Def and Sp. Def. Since Def is "Best" (i.e. 31), it shows up gold on the stats container. However, HP and Sp. Def are not "Best", so it shows up green. The Atk for this pokemon isn't better than what we have, so it's white like usual. The other stats are unknown/unscanned, so they also show up as white. This is with 2 IV scanners, so only 4 stats are shown.

Below is an example of a fight where pokemon have changed their stats with various stat changing moves: 

![image](https://github.com/pagefaultgames/pokerogue/assets/66582645/73ab32a6-27d4-41b2-9128-508e94465473)

Below is an example with 2 IV scanners in a run showing the difference with the IV scanner setting on (current behaviour) and the IV scanner setting off:

https://github.com/pagefaultgames/pokerogue/assets/66582645/47438007-3edb-4a4e-a0f3-74605671ad12

Here's an example of a run where there's no IV scanners. You'll notice that the HP stat isn't shown, but everything has been moved over a bit. This is so that when the HP stat does get shown, the ui elements don't shift because of it:

https://github.com/pagefaultgames/pokerogue/assets/66582645/4e590d8e-56d3-4c78-bf69-a7d767bd1499

Here's an example with 3 IV scanners:

https://github.com/pagefaultgames/pokerogue/assets/66582645/77a66662-862d-4d34-8aec-2dfc2387d274

Here's a double battle with 1 IV scanner while also going through different waves:

https://github.com/pagefaultgames/pokerogue/assets/66582645/7696524a-6c99-45ee-855f-1be7cec2a94f

Below is an example of fighting a trainer and not seeing the IV scanner prompt:

https://github.com/pagefaultgames/pokerogue/assets/66582645/c2900bdf-7013-4303-87dc-b7e8a188b3cc

Lastly, below is an example where you start with no IV scanners and then pick up on in the store:

https://github.com/pagefaultgames/pokerogue/assets/66582645/4dab40d5-9ed9-47c5-a1f2-ab89ed8c2de8

Finally, here's a screenshot of the IV scanner in action for the legacy UI:

![image](https://github.com/pagefaultgames/pokerogue/assets/66582645/340271b7-6a95-485f-939c-ff5277c6e307)

Regarding the change to the IV scanner and pokemon info container, below is a picture of the current behaviour:

![image](https://github.com/user-attachments/assets/a2ad692f-0642-4433-8902-f78f93d13064)

You can see above that the IV scanner (which uses the same code as the display on the stat labels) shows that the HP, ATK, Sp DEF and SPD should be higher than what we've got, but in reality it's only the HP. Below is the update to make the IV scanner (and thus, my changes to the stat labels) be in line with the pokemon info container:

![image](https://github.com/user-attachments/assets/6b6d4031-ef30-4d11-bc1f-007391f50664)

![image](https://github.com/user-attachments/assets/48bdeac7-8329-46c2-a260-6b32ccf597f7)

As you can see above, now according to the IV scanner (and the stat labels), the only thing better should be HP, and when we catch the pokemon and see the pokemon info container, we see that's the case

## How to test the changes?
Download the branch to play with the changes. When you're at the battle screen, you can open the stats container (default Shift/C) to see the changes. Also in the settings, there should be an option to turn the setting on/off to hide the IV prompts

You can also use any of the following overrides:

Line 32 - this will force a double battle:

`export const DOUBLE_BATTLE_OVERRIDE: boolean = true;`

Line 90 - this will let you choose a specific pokemon to fight against. For example, this is set to spawn a charizard, but you can change that to anything else to fight other things:

`export const OPP_SPECIES_OVERRIDE: Species | integer = Species.CHARIZARD;`

Line 96 - this will let you set the moves the enemy opponent has; for example this could be used to set stat changing moves for enemy pokemon to see the stat numbers appear. In this example, we have given them the moves no retreat, quiver dance, and shell smash twice. This can be set to anything:

`export const OPP_MOVESET_OVERRIDE: Array<Moves> = [Moves.NO_RETREAT, Moves.QUIVER_DANCE, Moves.SHELL_SMASH, Moves.SHELL_SMASH];`

Line 99 - this will let you set the IVs of the enemy pokemon. It takes an array of 6 numbers, which, in order, are HP, Atk, Def, Sp. Atk, Sp. Def, Spd:

`export const OPP_IVS_OVERRIDE: integer | integer[] = [31, 24, 5, 3, 19, 16];`

Line 121 - this will give you 3 IV scanners. To change it, change the "count: 3" to "count: 1" or "count: 2":

`export const STARTING_MODIFIER_OVERRIDE: Array<ModifierOverride> = [{name: "IV_SCANNER", count: 3}];`

**NOTE:** If you want to get rid of your IV scanners, you have to revert this; changing the count to 0 will NOT work, so to have 0 IV scanners, you need to use:

`export const STARTING_MODIFIER_OVERRIDE: Array<ModifierOverride> = [];`

Also note that for the IV scanners, you'll need to start a new game to see the effects. At first it'll look like it didn't work,  [...]

2024-08-01 15:15 UTC, Tempo-anon commented on src/data/battle-stat.ts
> +  HP
Right now this is only used for the IV scanner right? Might be worth adding a comment here. Also make sure adding a new enum to `BattleStat` won't break anything

2024-08-01 15:16 UTC, Tempo-anon commented on src/phases.ts
> +      const currentIvs = this.scene.gameData.dexData[enemyField[e].species.getRootSpeciesId(false)].ivs;  // we are using getRootSpeciesId(false) here because we want to check against the baby form,
nit: I believe `false` is the default so you can just do `getRootSpeciesId()`

2024-08-01 15:31 UTC, Opaque02 commented on src/phases.ts
> +      const currentIvs = this.scene.gameData.dexData[enemyField[e].species.getRootSpeciesId(false)].ivs;  // we are using getRootSpeciesId(false) here because we want to check against the baby form,
Fixed in next commit

2024-08-01 15:37 UTC, torranx commented on src/ui/battle-info.ts
> +const battleStatOrderEnemy = [BattleStat.HP, BattleStat.ATK, BattleStat.DEF, BattleStat.SPATK, BattleStat.SPDEF, BattleStat.ACC, BattleStat.EVA, BattleStat.SPD];
```suggestion
const battleStatOrderEnemy = [ BattleStat.HP, BattleStat.ATK, BattleStat.DEF, BattleStat.SPATK, BattleStat.SPDEF, BattleStat.ACC, BattleStat.EVA, BattleStat.SPD ];
```

2024-08-01 15:37 UTC, torranx commented on src/ui/battle-info.ts
> +const battleStatOrderPlayer = [BattleStat.ATK, BattleStat.DEF, BattleStat.SPATK, BattleStat.SPDEF, BattleStat.ACC, BattleStat.EVA, BattleStat.SPD];
```suggestion
const battleStatOrderPlayer = [ BattleStat.ATK, BattleStat.DEF, BattleStat.SPATK, BattleStat.SPDEF, BattleStat.ACC, BattleStat.EVA, BattleStat.SPD ];
```

2024-08-01 15:37 UTC, torranx commented on src/ui/battle-info.ts
> +    battleStatOrder = this.player ? battleStatOrderPlayer : battleStatOrderEnemy; // this tells us whether or not to use the player or enemy battle stat order
I see a lot of occurences of this, might consider making `battleStatOrder` a class property instead.

2024-08-01 15:37 UTC, torranx commented on src/ui/battle-message-ui-handler.ts
> +  topIvs(ivs: integer[], shownIvsCount: integer): Stat[] {
I'm assuming this is a function to get the top IVs
```suggestion
  getTopIvs(ivs: integer[], shownIvsCount: integer): Stat[] {
```

2024-08-01 16:02 UTC, Opaque02 commented on src/ui/battle-info.ts
> +    battleStatOrder = this.player ? battleStatOrderPlayer : battleStatOrderEnemy; // this tells us whether or not to use the player or enemy battle stat order
Just so I get my head around it properly, what would be an example of a class property that I can do with this instead? I don't quite know what one would be?

2024-08-02 11:58 UTC, torranx commented on src/ui/battle-info.ts
> +    battleStatOrder = this.player ? battleStatOrderPlayer : battleStatOrderEnemy; // this tells us whether or not to use the player or enemy battle stat order
class properties are those you can access with `this` inside the class ie `private baseY`

2024-08-03 07:50 UTC, Opaque02 commented on src/ui/battle-message-ui-handler.ts
> +  topIvs(ivs: integer[], shownIvsCount: integer): Stat[] {
Fixed in next commit

2024-08-03 07:50 UTC, Opaque02 commented on src/ui/battle-info.ts
> +    battleStatOrder = this.player ? battleStatOrderPlayer : battleStatOrderEnemy; // this tells us whether or not to use the player or enemy battle stat order
Fixed in next commit

2024-08-03 07:50 UTC, Opaque02 commented on src/ui/battle-info.ts
> +const battleStatOrderPlayer = [BattleStat.ATK, BattleStat.DEF, BattleStat.SPATK, BattleStat.SPDEF, BattleStat.ACC, BattleStat.EVA, BattleStat.SPD];
Fixed in next commit

2024-08-03 07:51 UTC, Opaque02 commented on src/ui/battle-info.ts
> +const battleStatOrderEnemy = [BattleStat.HP, BattleStat.ATK, BattleStat.DEF, BattleStat.SPATK, BattleStat.SPDEF, BattleStat.ACC, BattleStat.EVA, BattleStat.SPD];
Fixed in next commit

2024-08-03 07:56 UTC, Opaque02 commented on src/data/battle-stat.ts
> +  HP
As far as I can tell, I can't see anything breaking from adding the new battle stat. The places we access the battle stats themselves are all based on set numbers assuming it starts at ATK (for example casting battle stat to regular stat), so adding HP at the end doesn't make a difference. There are a few places where it generates a random battle stat, but it checks the enum === BattleStat.RAND, then manually gets the value of the random stat using [this code](https://github.com/pagefaultgames/pokerogue/blob/main/src/phases.ts#L3395-L3398), which only goes up to speed and nothing further. There's a few other cases like [here](https://github.com/pagefaultgames/pokerogue/blob/main/src/data/move.ts#L2558-L2568) where it manually puts in the allowed BattleStats when generating a random one, but nothing I can see what uses _all_ BattleStats without some kind of limiter (i.e. specifically choosing what stats to use)

2024-08-03 10:53 UTC, torranx commented on src/ui/battle-info.ts
> +const battleStatOrderEnemy = [ BattleStat.HP, BattleStat.ATK, BattleStat.DEF, BattleStat.SPATK, BattleStat.SPDEF, BattleStat.ACC, BattleStat.EVA, BattleStat.SPD ];
is there any reason why these are defined outside the class? if none, please encapsulate them inside the class.

2024-08-03 10:53 UTC, torranx commented on src/ui/battle-info.ts
> +  public battleStatOrder: BattleStat[];
if this is not being used by other classes, make it private

2024-08-03 10:53 UTC, torranx commented on src/ui/battle-info.ts
> +    this.battleStatOrder = this.player ? battleStatOrderPlayer : battleStatOrderEnemy; // this tells us whether or not to use the player or enemy battle stat order
There are 3 occurences of this line, if this is _always_ the case, maybe we can make this as default?

2024-08-04 04:17 UTC, Opaque02 commented on src/ui/battle-info.ts
> +const battleStatOrderEnemy = [ BattleStat.HP, BattleStat.ATK, BattleStat.DEF, BattleStat.SPATK, BattleStat.SPDEF, BattleStat.ACC, BattleStat.EVA, BattleStat.SPD ];
Good point - a leftover from the old style. This has been fixed to be privates within the class in the next commit

2024-08-04 04:17 UTC, Opaque02 commented on src/ui/battle-info.ts
> +    this.battleStatOrder = this.player ? battleStatOrderPlayer : battleStatOrderEnemy; // this tells us whether or not to use the player or enemy battle stat order
I've updated this to only be around in the constructor now as of next commit

2024-08-04 04:17 UTC, Opaque02 commented on src/ui/battle-info.ts
> +  public battleStatOrder: BattleStat[];
Fixed in next commit

2024-08-05 18:06 UTC, Adri1 commented on src/locales/fr/settings.ts
> +  "hideIvs": "Hide IV scanner",
```suggestion
  "hideIvs": "Masquer Scanner d’IV",
```

2024-08-05 18:18 UTC, CodeTappert commented on src/locales/de/settings.ts
> +  "hideIvs": "Hide IV scanner",
```suggestion
  "hideIvs": "IS-Scanner verstecken",
```

2024-08-05 18:34 UTC, josericardo-fo commented on src/locales/pt_BR/settings.ts
> +  "hideIvs": "Hide IV scanner",
```suggestion
  "hideIvs": "Esconder scanner de IV",
```

2024-08-06 00:58 UTC, EnochG1 commented on src/locales/ko/settings.ts
> +  "hideIvs": "Hide IV scanner",
```suggestion
  "hideIvs": "개체값탐지기 메시지 숨김",
```

2024-08-06 00:59 UTC, sodaMelon commented on src/locales/ko/settings.ts
> +  "hideIvs": "Hide IV scanner",
```suggestion
  "hideIvs": "개체값 탐지기 숨기기",
```

2024-08-06 01:01 UTC, sodaMelon commented on src/locales/ko/settings.ts
> +  "hideIvs": "Hide IV scanner",
@EnochG1 how about "개체값 탐지기 숨기기"?  (This is shorter)

2024-08-06 01:10 UTC, sodaMelon commented on src/locales/ko/settings.ts
> +  "hideIvs": "Hide IV scanner",
Looking at the second option, I think we need to be a bit more comprehensive. (not only message off)

2024-08-06 01:14 UTC, mercurius-00 commented on src/locales/zh_CN/settings.ts
> +  "hideIvs": "Hide IV scanner",
```suggestion
  "hideIvs": "禁用个体值探测器",
```

2024-08-06 01:14 UTC, mercurius-00 commented on src/locales/zh_TW/settings.ts
> +  "hideIvs": "Hide IV scanner",
禁用個體值探測器

2024-08-06 01:15 UTC, EnochG1 commented on src/locales/ko/settings.ts
> +  "hideIvs": "Hide IV scanner",
I modified it

2024-08-06 17:41 UTC, frutescens requested changes
Mild nit - I noticed that a Best IV would be gold, but I feel like the colors should match up 
![image](https://github.com/user-attachments/assets/4097691e-27e8-42b7-ab62-f3fdf487a82a)

2024-08-06 21:23 UTC, Opaque02 commented
> Mild nit - I noticed that a Best IV would be gold, but I feel like the colors should match up ![image](https://private-user-images.githubusercontent.com/171087428/355548932-4097691e-27e8-42b7-ab62-f3fdf487a82a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Nzk1MTYsIm5iZiI6MTcyMjk3OTIxNiwicGF0aCI6Ii8xNzEwODc0MjgvMzU1NTQ4OTMyLTQwOTc2OTFlLTI3ZTgtNDJiNy1hYjYyLWYzZmRmNDg3YTgyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQyMTIwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzY1MTNlODEyYWRiNzM1MTFiOGM2ODA2ZjU3ZWIwODE3Mzg5ZGFjOTcyYTZhZjk4NWNhZGQ1OGI2YTdjMzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bNL0Wh3ox9rIWhLeroaChk37Imc0Cr_fBeNx2zJGvZU)

@frutescens this is a very good point but it was an intentional design choice to have "Best" be different because in the early days of this, people were giving feedback that if they had the IV scanner setting off they wouldn't know what IVs were best and wanted an indicator to know, since that might sway people to catch a pokemon if it's got a Best stat that you don't already have

2024-08-06 21:28 UTC, frutescens commented
I meant that the 'Best' used in IV scanner results on the right should be yellow, my bad!

2024-08-06 21:39 UTC, Opaque02 commented
> I meant that the 'Best' used in IV scanner results on the right should be yellow too, my bad!

Ooooh, sorry, I'm with you! Maybe! I'll bring it up in the discord and see if we can get other ideas for it! Good thinking!

2024-08-07 04:38 UTC, frutescens approved these changes
thank you for putting in my suggestion! i know you worked hard on finding the right look :)

2024-08-07 05:05 UTC, EnochG1 commented
@Opaque02 
From now Japanese is added in beta.
Could you merge latest beta and add Japanese locale files? 🙏

2024-08-07 11:28 UTC, Opaque02 commented
> @Opaque02 From now Japanese is added in beta. Could you merge latest beta and add Japanese locale files? 🙏

Done with the latest commit

2024-08-08 05:04 UTC, merged