[Test] added revive function in gamaManager & a double-battle test
pagefaultgames/pokerogue pull request #3298
Opened 2024-08-02 06:52 UTC by allen925

## What are the changes?
added a revive function in game manager that is currently for player use only. 
added a test of double battle that is related to my last PR. 

## Why am I doing these changes?
one requested an auto test from 
[my last PR](https://github.com/pagefaultgames/pokerogue/pull/3266)

## What did change?
A long test related to double battle double fainted and reviving, it takes quite a long time so I set the timeout to 200000
commented parts related to summon phase for recent change of summon phase successfully aborting with PR #3288 that the phase is no longer triggered. 

if anyone needs it to work on enemy team feel free to implement it.
if anyone planning to do a refactoring of revive modifier, you may want to modify doRevivePokemon() as well

### Screenshots/Videos

## How to test the changes?
npm run test double_battle.test.ts

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-02 08:43 UTC, torranx requested changes

2024-08-02 08:43 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +  it("3v2 edge case: double-battle player double faint same round and revive one, next double battle summon two", async() => {
can we make this much more clearer on what it is supposed to be testing?

2024-08-02 08:43 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +    game.override.moveset([Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL]);
what's the reason why we are using these overrides?

2024-08-02 08:43 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +    game.doRevivePokemon(1);
I don't see a 100% certainty that any player pokemon is fainted here.

2024-08-02 08:43 UTC, torranx commented on src/test/utils/gameManager.ts
> +  doRevivePokemon(pokemonIndex: number, player: boolean = true) {
remove unused param

2024-08-02 10:27 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    game.override.moveset([Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL]);
prankster destiny bond with 1 hp ensure death of player's pokemon after they attacked, at least that's how I test my pr before. but I can change it to something like override toxic with starting double battle shedinja and kill enemy pokemon or something like that.

2024-08-02 11:35 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +    game.override.moveset([Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL]);
either I'm blind or I'm not seeing where you are setting the 1 hp. as mentioned in another comment, the test does not ensure that the mons are actually fainted before being revived

2024-08-02 11:46 UTC, torranx requested changes
Too many uncertain variables that may affect the test result, I would suggest to look at the `doKillOpponents` and try to implement it with player pokemon instead.

2024-08-02 11:46 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +    // });
remove these if it's not relevant

2024-08-02 11:46 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +    expect(game.scene.getPlayerField().filter(p => !p.isFainted()).length).toBe(2);
is the `.length` even needed here?

2024-08-02 11:46 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +  it("3v2 edge case", async() => {
I'm thinking somewhere in the lines of "player summons 2 pokemon on the next battle after being fainted and revived"
I'm not trying to be pushy here but in any case this will fail, it's the description that will show up

2024-08-02 11:57 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    game.override.moveset([Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL]);
well it's shedinja / wonder guard that makes it 1hp, but i guess i can do killPokemon and killopponents and revive after, that is much more straight forward.

2024-08-02 12:02 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +    game.override.moveset([Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL]);
I see thanks for clearing that up, didn't know shedinja always has 1 hp 👍 . but still, the way it kills mons rn is hacky imo

2024-08-02 13:27 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    expect(game.scene.getPlayerField().filter(p => !p.isFainted()).length).toBe(2);
yeah that is needed

2024-08-02 13:27 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +  it("3v2 edge case", async() => {
updated

2024-08-02 13:28 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    game.override.moveset([Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL,Moves.SHADOW_BALL]);
I made it much more straight forward, is the current stage acceptable?

2024-08-02 14:42 UTC, flx-sta commented on src/test/battle/double_battle.test.ts
> +    expect(game.scene.getPlayerField().filter(p => !p.isFainted()).length).toBe(2);
```suggestion
    expect(game.scene.getPlayerField().filter(p => !p.isFainted())).toHaveLength(2);
```

2024-08-02 14:43 UTC, flx-sta commented on src/test/battle/double_battle.test.ts
> +    expect(pokemon2).not.toBe(undefined);
```suggestion
    expect(pokemon2).toBeDefined();
```

2024-08-02 14:43 UTC, flx-sta commented on src/test/battle/double_battle.test.ts
> +    expect(pokemon1).not.toBe(undefined);
```suggestion
    expect(pokemon1).toBeDefined();
```

2024-08-02 14:44 UTC, flx-sta commented on src/test/battle/double_battle.test.ts
> +    game.override.moveset(SPLASH_ONLY);
```suggestion
    game.override.battleType("double").enemyMoveset(SPLASH_ONLY).moveset(SPLASH_ONLY);
```

2024-08-02 14:44 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +    game.doRevivePokemon(1);
this is a comment from my initial review, code is updated now

2024-08-02 14:55 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +    game.doRevivePokemon(1);
please replace this magic number by getting the actual index of the pokemon

2024-08-02 14:55 UTC, torranx commented on src/test/battle/double_battle.test.ts
> +    expect(pokemon2.isFainted()).toBe(true);
this set of code is repeated on `pokemon1`, consider looping thru `getPlayerField()` instead

2024-08-02 14:58 UTC, torranx commented
Just some few comments, almost there! Please resolve the previous resolved comments so that it will collapse, thanks!

2024-08-03 02:19 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    expect(game.scene.getPlayerField().filter(p => !p.isFainted()).length).toBe(2);
done

2024-08-03 02:20 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    expect(pokemon2).not.toBe(undefined);
done

2024-08-03 02:20 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    expect(pokemon1).not.toBe(undefined);
done

2024-08-03 02:20 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    game.override.moveset(SPLASH_ONLY);
done

2024-08-03 02:20 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    expect(pokemon2.isFainted()).toBe(true);
done

2024-08-03 02:23 UTC, allen925 commented on src/test/battle/double_battle.test.ts
> +    game.doRevivePokemon(1);
Honestly it is eventually the magic number I want it to be, since that specific slot (double battle second pokemon) was the one that causing problem when switching. Anyway code is updated.

2024-08-03 02:27 UTC, torranx approved these changes
lgtm

2024-08-03 02:30 UTC, merged