[Bug] Rockruff, lycanroc wild spawn fix
pagefaultgames/pokerogue pull request #3299
Opened 2024-08-02 08:44 UTC by Smewkie

## What are the changes?
There's a few different changes here.

Change 1: Allows Own Tempo Rockruff to spawn in the wild, at a rate of 20%, so 20% of all rockruff's you might find can have Own Tempo Form, this allows for somewhat easier access to a pokemon that has the same base stats as its other forms, just put together differently.

Change 2: I changed Dusk Form Lycanroc from being form index 2, to form index 1, this makes it so if you run into a wild Dusk Form Lycanroc and haven't yet unlocked Own Tempo Rockruff, catching this Lycanroc will unlock Own Tempo Rockruff.

Change 3: I changed Lycanroc's forms from spawning based on Time of Day(including any Lycanroc owned by a enemy trainer), and instead just made it based on a % chance, the rates are 40% for Day form, 40% for Midnight form, and 20% for Dusk form.
I personally think it's silly to have the forms locked to a certain time of day in the first place, as Lycanroc itself isn't exactly a super strong pokemon to begin with.

## Why am I doing these changes?
Before, Own Tempo Rockruff couldn't spawn in the wild at all, and in order to get access to it you had to catch a midnight form Lycanroc.

### Screenshots/Videos
Midnight:
![image](https://github.com/user-attachments/assets/10932218-9a8e-44ea-8927-361297b44418)

Dusk:
![image](https://github.com/user-attachments/assets/f0f7d35d-cd42-42ac-9a7c-e711385eeb85)

Day:
![image](https://github.com/user-attachments/assets/cd83d296-f2b8-459b-9a2e-eaa207139d6d)

Own Tempo in the wild:
![image](https://github.com/user-attachments/assets/5902e91b-c786-498a-a7c2-b4d52786628b)

## How to test the changes?
Change your OPP_SPECIES_OVERRIDE to either 744 for Rockruff or 745 for Lycanroc
If on a fresh save file, you can see that catching a Dusk Lycanroc does indeed unlock Own Tempo Rockruff, while catching Midnight or Day Form only unlocks normal Rockruff.
And you can see that Lycanroc's forms can all spawn no matter the time of day, just based on random chance.

also sorry I really cannot figure out the whole cherry picking thing D:

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-02 15:48 UTC, Tempo-anon requested changes
1. Code doesn't compile
2. Your branch is not up to date
3. Solution for the forms can be more elegant

2024-08-02 15:48 UTC, Tempo-anon commented on index.css
Pretty sure this file is unrelated to your fix so you should make sure your branch is up to date with beta

2024-08-02 15:48 UTC, Tempo-anon commented on src/battle-scene.ts
> +      return "Blame Yda!" // just incase the random number goes haywire
This is an error since it's trying to return a `string` when it's expecting a `number`

I imagine you want something like this
```ts
console.log("Failed to generate random number for Rockruff");
return 0 // Default form
```

2024-08-02 15:48 UTC, Tempo-anon commented on src/battle-scene.ts
> +      const funnynumber1 = Utils.randSeedInt(100, 1); // roll between 1 - 100
randSeedInt(range, min) is not inclusive of range so this would be 1-99.

2024-08-02 15:48 UTC, Tempo-anon commented on src/battle-scene.ts
> +      } else {
This can be inline'd
```ts
return (Utils.randSeedInt(100) < 80) ? 1 : 0;
```

2024-08-14 00:40 UTC, DayKev commented on src/battle-scene.ts
> +      const funnynumber2 = Utils.randSeedInt(100, 1); // roll between 1 - 100
Variables should probably have normal/descriptive names.

2024-08-14 00:41 UTC, DayKev commented on src/battle-scene.ts
> +      return "Blame flx!" // just incase the random number goes haywire
Do we need a condition here for if `randSeedInt()` fails? It seems like rSI should be catching any errors itself.

2024-08-14 01:45 UTC, Smewkie commented on src/battle-scene.ts
> +      return "Blame flx!" // just incase the random number goes haywire
gonna be honest, I just copy / pasted all this in after flx wrote it all, but since it's still not right, I don't really have the knowledge to actually make it better, so I'll go ahead and close this pr

2024-08-14 01:48 UTC, closed without merging