[Bug] Fix a couple small issues with uturn and friends
pagefaultgames/pokerogue pull request #3321
Opened 2024-08-03 19:55 UTC by snoozbuster

## What are the changes?
Fixes three main issues with u-turn and company:
- U-turn would trigger regenerator twice on the user
- U-turn would trigger abilities like static twice on the attacker
- The party UI for u-turn and other switch moves would appear in the middle of the move, before effects and abilities were done applying

## Why am I doing these changes?
Pre-work for a pursuit implementation

## What did change?
- Removed the manual application of two ability attr types by ForceSwitchOutAttr
- Changed ForceSwitchOutAttr to use SwitchPhase for choosing and sending out a mon, rather than doing it inline in the MoveEffectPhase/apply() function
- Added UTs for everything that was broken, or that I noticed I had accidentally broke while working on these fixes
  - Added some new helpers/fixes for the UT harnesses to help test switch moves

### Screenshots/Videos

#### Pre-change: U-turn damage and effects (Stamina) happen _after_ party menu
[screen-capture (4).webm](https://github.com/user-attachments/assets/5a9fed96-40c8-4e17-bee3-17b134580326)

#### Pre-change: U-turn triggers regenerator twice
[screen-capture (5).webm](https://github.com/user-attachments/assets/b0569f2f-b487-40f1-af2a-a4f97221eb4a)

#### Pre-change: U-turn triggers static twice (only with no party members to switch to, because... yeah)
[screen-capture (6).webm](https://github.com/user-attachments/assets/79a7a9c7-735b-43db-88dd-ec632e74f664)

#### Pre-change: Demonstration of U-turn in doubles
[screen-capture (9).webm](https://github.com/user-attachments/assets/78ce009d-a077-4f8b-83d4-e4662666ae07)

#### Post-change: U-turn damage and effects (Stamina) happen _before_ party menu
[screen-capture (1).webm](https://github.com/user-attachments/assets/f11fd89c-903d-4a40-acb5-f5ff4c0938d4)

#### Post-change: Baton pass still passes Work Up
[screen-capture (2).webm](https://github.com/user-attachments/assets/d7ac0ea0-988b-430b-9d47-0201f584c0d5)

#### Post-change: Dragon tail activates Stamina on outgoing mon
This still looks a little funky, but it does function correctly
[screen-capture (3).webm](https://github.com/user-attachments/assets/a767562b-0e0b-4815-8a44-9fb0b609a48f)

#### Post-change: U-turn triggers regenerator once
[screen-capture (8).webm](https://github.com/user-attachments/assets/199edadd-ed49-4c1f-9681-be50345ce2cd)

#### Post-change: U-turn triggers static once
[screen-capture (7).webm](https://github.com/user-attachments/assets/2491bf56-1766-4855-b203-ce16d167a7ee)

#### Post-change: Demonstration of U-turn in doubles (works the same except for the better party UI placement)
[screen-capture (10).webm](https://github.com/user-attachments/assets/b63dbdc0-bf91-40bc-a535-757b635459d1)

## How to test the changes?

- automated tests ensure I fixed the regeneration/status ability problem (for status abilities, technically they only ensure the ability still applies, not exactly that it only applies a single time)
- automated tests ensure I didn't break at least the simplest cases for baton pass
- videos can verify the changes to party menu timing

The following overrides are helpful for local testing (make sure you have a party of 2 or 3 depending on if you are using doubles or not):
```ts
const overrides = {
  MOVESET_OVERRIDE: [
    Moves.DRAGON_TAIL,
    Moves.WORK_UP,
    Moves.U_TURN,
    Moves.BATON_PASS
  ],
  STARTING_WAVE_OVERRIDE: 5,
  ABILITY_OVERRIDE: Abilities.REGENERATOR,
  // some useful testing abilities
  OPP_ABILITY_OVERRIDE: Abilities.STAMINA,
  // OPP_ABILITY_OVERRIDE: Abilities.ROUGH_SKIN,
  // OPP_ABILITY_OVERRIDE: Abilities.STATIC,
  OPP_MOVESET_OVERRIDE: new Array(4).fill(Moves.U_TURN),
  OPP_SPECIES_OVERRIDE: Species.SHEDINJA,
  // BATTLE_TYPE_OVERRIDE: 'double',
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-03 20:05 UTC, snoozbuster commented on src/ui/party-ui-handler.ts
> +          const isBatonPassMove = this.partyUiMode === PartyUiMode.FAINT_SWITCH && moveHistory.length && allMoves[moveHistory[moveHistory.length - 1].move].getAttrs(ForceSwitchOutAttr)[0]?.isBatonPas
this change is because SwitchPhase doesn't take an explicit baton pass flag, it infers it from the PASS_BATON option being the selected one. I didn't think that was worth changing, plus doing it this way makes the menu show the "Pass Baton" text instead of "Send Out" which I thought was a minor improvement.

I did this by finding the ForceSwitchOutAttr of the last move used by the mon being switched out (since we are in MoveEffectPhase during a baton pass, it's already been added to the move history) and checking it if was a baton pass move because I thought maybe Shed Tail or some other move would/could use this attr. 

I don't think this causes issues - I tried a couple different things, including
- baton passing back and forth between two bpass users and trying to switch via Pokemon command
- dragon tailing a pokemon switched in via baton pass to see if the dragon tail switch also used "pass baton" command

and didn't see any issues with this picking up baton pass incorrectly.

2024-08-03 20:06 UTC, snoozbuster commented on src/test/utils/gameManager.ts
> +    }, () => this.isCurrentPhase(CommandPhase) || this.isCurrentPhase(MovePhase) || this.isCurrentPhase(TurnEndPhase));
using doAttack with a move that opens the party menu (eg switch moves) softlocks without this change

2024-08-03 20:07 UTC, snoozbuster commented on src/ui/party-ui-handler.ts
> + * Indicates the reason why the party UI is being opened.
I am not 100% sure of the accuracy of all of these descriptions, but I did my best to identify where they are used and at least hand-wave in that direction.

2024-08-03 23:55 UTC, torranx requested changes
not a fan of using `textInterceptor` to check if a switch happened - this just creates another dependency

2024-08-03 23:55 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    game.override.disableCrits();
I believe you can chain these overrides

2024-08-03 23:55 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    return game.scene.getParty()[0];
```suggestion
    return game.scene.getPlayerPokemon();
```

2024-08-03 23:55 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    await game.toNextTurn();
this can be ended earlier to save runtime

2024-08-03 23:55 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    game.phaseInterceptor.clearLogs();
why are you calling `clearLogs()` here?

2024-08-03 23:55 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    game.override.enemySpecies(Species.GENGAR);
is this necessary?

2024-08-03 23:55 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    expect(game.scene.getEnemyParty()[0].summonData.battleStats[BattleStat.SPATK]).toEqual(2);
```suggestion
    expect(game.scene.getEnemyPokemon().summonData.battleStats[BattleStat.SPATK]).toEqual(2);
```

2024-08-03 23:55 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    ]);
I think these can all just be simplified to checking whether phases ran through `SwitchSummonPhase`. This will also remove the need to call `initI18n()`

2024-08-03 23:55 UTC, torranx commented on src/test/moves/u_turn.test.ts
> +    return game.scene.getParty()[0];
```suggestion
    return game.scene.getPlayerPokemon();
```

2024-08-03 23:55 UTC, torranx commented on src/test/moves/u_turn.test.ts
> +    game.override.disableCrits();
can be chained

2024-08-03 23:55 UTC, torranx commented on src/test/moves/u_turn.test.ts
> +    // round 1 - take big damage
instead of relying on enemy's move to damage your pokemon, you can set the `hp` instead, this would also shorten the runtime since you can use u turn imm + expect a definite hp on the next turn

2024-08-03 23:55 UTC, torranx commented on src/test/moves/u_turn.test.ts
> +    vi.spyOn(game.scene.getEnemyParty()[0], "randSeedInt").mockImplementation((range, min) => {
does using `mockReturnValue` not work here instead?

2024-08-03 23:58 UTC, torranx commented
also, please fix your branch, just noticed there are commits from other people

2024-08-04 01:53 UTC, snoozbuster commented on src/test/moves/baton_pass.test.ts
> +    game.phaseInterceptor.clearLogs();
I think it might be leftover from an older way I was doing the assertion. I’ll check it’s still needed

2024-08-04 01:55 UTC, snoozbuster commented on src/test/moves/baton_pass.test.ts
> +    game.override.enemySpecies(Species.GENGAR);
No, I was trying to use this to change the species of the incoming pokemon as a more straightforward way of asserting the switch (asserting new species is active), but it didn’t work and I guess I forgot to remove this

2024-08-04 01:57 UTC, snoozbuster commented on src/test/moves/u_turn.test.ts
> +    vi.spyOn(game.scene.getEnemyParty()[0], "randSeedInt").mockImplementation((range, min) => {
Someone in Discord told me this function is used for a lot of things so I should to try to mock the specific call I wanted to control instead of mocking all calls. Otherwise I would have done that, yeah

2024-08-04 02:01 UTC, snoozbuster commented on src/test/moves/baton_pass.test.ts
> +    ]);
I kind of would like to assert explicitly that a new mon is in battle in case someone in the future adds code to SwitchSummonPhase like the code in SwitchPhase that instantly ends the phase without switching under certain conditions. I just couldn’t figure out how to do that, because I couldn’t figure out how to override specific team members for the AI, so I was using the messages and phases as a proxy for that.

2024-08-04 04:12 UTC, snoozbuster commented on src/test/moves/baton_pass.test.ts
> +    game.phaseInterceptor.clearLogs();
not needed, I can remove. do you want me to remove the utility method for it from phaseInterceptor as well?

2024-08-04 04:39 UTC, snoozbuster commented on src/test/moves/baton_pass.test.ts
> +    ]);
I changed the test to use active mon HP instead of textInterceptor

2024-08-04 05:09 UTC, snoozbuster commented on src/test/moves/baton_pass.test.ts
> +    expect(game.scene.getPlayerPokemon().species.species).toEqual(Species.SHUCKLE);
```suggestion
    expect(game.scene.getPlayerPokemon().species.speciesId).toEqual(Species.SHUCKLE);
```

oops

2024-08-04 07:54 UTC, snoozbuster commented
I have no idea what’s going on with these tests, they pass locally. Still looking into it.

2024-08-04 07:55 UTC, DayKev commented on src/data/move.ts
> +  }
You added `isBatonPass()` but didn't use it. 🤔

2024-08-04 08:20 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    // can't find a way to override trainer parties with more than 1 pokemon species
you don't have to override enemy trainer party, you can get the fielded pokemon and the other one inside the party. do the logic with that said

2024-08-04 23:37 UTC, snoozbuster commented on src/test/moves/baton_pass.test.ts
> +    // can't find a way to override trainer parties with more than 1 pokemon species
What logic though? They’re exactly the same pokemon due to the species override. They don’t take any damage or anything so how can I distinguish them?

2024-08-04 23:38 UTC, snoozbuster commented on src/data/move.ts
> +  }
It’s used in party-ui-handler

2024-08-05 03:20 UTC, Snailman11 commented
Link to Discord bug report (Regenerator trigger twice at once)
https://discord.com/channels/1125469663833370665/1269844249759973467

2024-08-05 03:50 UTC, snoozbuster commented
Merging in beta brought in https://github.com/pagefaultgames/pokerogue/pull/1236 which broke this branch. When that PR was authored, SwitchPhase wasn't being used for u-turn and company. Now that I'm trying to use this phase for u-turn, the active pokemon isn't actually fainted anymore - so u-turn for the player is just totally broken cause it can never get past this check.

2024-08-05 16:46 UTC, snoozbuster commented on src/phases.ts
> +    if (this.isModal && !this.doReturn && !this.scene.getParty()[this.fieldIndex].isFainted()) {
I tweaked this condition so that it doesn't run for ForceSwitchOutAttr. it's not the best solution, but I added a unit test in case anyone comes back here and tweaks it in the future.

2024-08-05 16:47 UTC, snoozbuster commented on src/test/battle/battle.test.ts
> +      expect.fail("Switch was forced");
I did confirm that this does work to fail the test (easy to trigger by commenting out the extra check in SwitchPhase)

2024-08-05 16:56 UTC, Snailman11 commented
Link to Discord's bug reports (Softlock when Wild Pokemon flees)
https://discord.com/channels/1125469663833370665/1246190022168805527

2024-08-05 16:59 UTC, snoozbuster commented
@Snailman11 - I wouldn't expect issues with wilds fleeing to be fixed by this PR (although it's not impossible, just wasn't my focus or what I was aiming to fix). there are three branches in ForceSwitchOutAttr - one for player pokemon, one for enemy trainers, and one for wilds. I've only touched the player pokemon branch so far, not the flee branch

2024-08-05 18:16 UTC, DustinLin commented on src/phases.ts
> +   * @param scene Current battle scene
would be good to add `{@linkcode }` for types of the params

2024-08-05 18:27 UTC, DustinLin commented on src/data/move.ts
> -        applyPostDefendAbAttrs(PostDefendContactApplyStatusEffectAbAttr, target, user, move, null);
maybe github or me being dumb, but where did the apply's get moved to? `applyPostDefendAbAttrs()` and `applyPreSwitchOutAbAttrs()`

2024-08-05 18:34 UTC, DustinLin commented
This PR below may be relevant. I remember some were discussing this a while ago, but it seems the PR is old and not maintained. I think any changes to how the moves actually work would have to be brought up to the balance team. Just mentioning it here to get thinking about how we may possibly extend this change:

[[Feature] Implement True Force Switch (Roar, Whirlwind, Circle Throw, Dragon Tail)](https://github.com/pagefaultgames/pokerogue/pull/1927)

2024-08-05 20:05 UTC, snoozbuster commented on src/data/move.ts
> -        applyPostDefendAbAttrs(PostDefendContactApplyStatusEffectAbAttr, target, user, move, null);
They were duplicate. Any times these ran, the effects were applied twice. I think that they were a misguided attempt to apply these effects before the mon switched out. (Or maybe it was correct at the time, ish - some of the code around these calls could have changed in such a way as to make these not needed anymore.) But these were the root cause of the double regenerator and double static issues.

2024-08-05 20:07 UTC, snoozbuster commented on src/phases.ts
> +   * @param scene Current battle scene
Can’t you just get there from the type? I guess it would be a little handy to have the type linked directly in the popup…

2024-08-05 20:12 UTC, snoozbuster commented
> This PR below may be relevant. I remember some were discussing this a while ago, but it seems the PR is old and not maintained. I think any changes to how the moves actually work would have to be brought up to the balance team. Just mentioning it here to get thinking about how we may possibly extend this change:
> 
> [[Feature] Implement True Force Switch (Roar, Whirlwind, Circle Throw, Dragon Tail)](https://github.com/pagefaultgames/pokerogue/pull/1927)

I think this PR would actually be easy to implement on top of this change. You just need to change `SwitchPhase` in this PR for `SwitchSummonPhase`, with a randomly chosen eligible party member in the player branch. Same thing for enemies, actually, I think the function used in that branch to choose a new party member equates to the enemy AI choosing a switch-in. I could try and revive that PR on top of these changes (with unit tests) once this gets merged.

2024-08-06 00:59 UTC, snoozbuster commented on src/phases.ts
> +   * @param scene Current battle scene
added

2024-08-06 04:41 UTC, snoozbuster commented
Tested by frutescens in discord:

https://discord.com/channels/1125469663833370665/1176874654015684739/1270238475345596419
https://discord.com/channels/1125469663833370665/1176874654015684739/1270237119872499773
https://discord.com/channels/1125469663833370665/1176874654015684739/1270235089296424982

2024-08-06 12:42 UTC, DayKev commented on src/test/moves/baton_pass.test.ts
> +    // can't find a way to override trainer parties with more than 1 pokemon species
Save the enemy party to variables earlier and reference them here. Something like this:
```ts
const [ enemy1, enemy2 ] = game.scene.getEnemyParty();

// test goes here

// whatever you're checking to confirm the test went as expected
expect(enemy1.hp).not.toEqual(100);
expect(enemy2.hp).toEqual(100);
```

2024-08-06 12:48 UTC, DayKev commented on src/test/utils/gameManager.ts
> +import {MockClock} from "#app/test/utils/mocks/mockClock";
```suggestion
import { EnemyPokemon, PlayerPokemon } from "#app/field/pokemon";
import { MockClock } from "#app/test/utils/mocks/mockClock";
```

2024-08-06 12:49 UTC, DayKev commented on src/test/utils/gameManager.ts
> +import CommandUiHandler, {Command} from "#app/ui/command-ui-handler";
```suggestion
import CommandUiHandler, { Command } from "#app/ui/command-ui-handler";
```

2024-08-06 12:52 UTC, DayKev commented on src/ui/party-ui-handler.ts
> +            // the BATON modifier gives uses an extra switch option for
```suggestion
            // the BATON modifier uses an extra switch option for
```

2024-08-06 12:54 UTC, DayKev commented on src/test/moves/u_turn.test.ts
> +} from "#app/phases";
```suggestion
import { SwitchPhase, TurnEndPhase } from "#app/phases";
```

2024-08-06 12:55 UTC, DayKev reviewed
I forgot to use GitHub's review thing for my comments so uh... just pretend I did lol.

2024-08-06 17:21 UTC, frutescens commented
My test video: Bulbasaur with Static + Rough Skim --- Opponents only with U-Turn

Uploading Screen Recording 2024-08-05 at 9.30.43 PM.mov…

2024-08-06 17:24 UTC, frutescens approved these changes
Seems good to me

2024-08-06 17:34 UTC, snoozbuster commented on src/test/moves/u_turn.test.ts
> +    expect(game.scene.getEnemyPokemon().battleData.abilityRevealed).toBe(true); // proxy for asserting ability activated
I checked that, unfortunately it's empty in this case. not 100% sure what it's used for, my guess is continuous effects?

2024-08-06 17:49 UTC, DustinLin approved these changes
Tested issue #682 and doesn't break it

2024-08-06 18:38 UTC, torranx commented on src/test/battle/battle.test.ts
> +      .enemyMoveset(new Array(4).fill(Moves.SPLASH))
same with other tests
```suggestion
      .enemyMoveset(SPLASH_ONLY)
```

2024-08-06 18:38 UTC, torranx commented on src/test/battle/battle.test.ts
> +    game.doRevivePokemon(0); // pretend max revive was picked
I don't see when the player pokemon is fainted?

2024-08-06 18:38 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    const moveToUse = Moves.BATON_PASS;
unnecessary declaration, only used once

2024-08-06 18:38 UTC, torranx commented on src/test/moves/u_turn.test.ts
> +    const moveToUse = Moves.U_TURN;
this is unnecessary declaration since you're only using it once (same with other occurences)

2024-08-06 19:24 UTC, snoozbuster commented on src/test/battle/battle.test.ts
> +    game.doRevivePokemon(0); // pretend max revive was picked
Fainted by take down recoil

2024-08-06 19:25 UTC, snoozbuster commented on src/test/moves/baton_pass.test.ts
> +    const moveToUse = Moves.BATON_PASS;
Will take care of these, I think they came from a test I copied as reference

2024-08-07 02:58 UTC, torranx commented on src/test/moves/baton_pass.test.ts
> +    // can't find a way to override trainer parties with more than 1 pokemon species
are these still relevant? should it be removed?

2024-08-07 03:04 UTC, snoozbuster commented on src/test/moves/baton_pass.test.ts
> +    // can't find a way to override trainer parties with more than 1 pokemon species
still relevant, yeah

2024-08-07 03:23 UTC, torranx requested changes

2024-08-07 03:23 UTC, torranx commented on src/test/utils/gameManager.ts
> +  doSelectPartyPokemon(slot: integer, inPhase = "SwitchPhase") {
```suggestion
  doSelectPartyPokemon(slot: number, inPhase = "SwitchPhase") {
```
moving forward, we want to replace all `integer` types with `number`

2024-08-07 03:24 UTC, snoozbuster commented on src/test/utils/gameManager.ts
> +  doSelectPartyPokemon(slot: integer, inPhase = "SwitchPhase") {
oh, fair. usually I would number but I think I saw integer somewhere and was like "well when in rome" 😄

2024-08-07 03:28 UTC, torranx approved these changes
the automated tests look good to me; seems well-tested too but would love other devs to take a look on the actual fixes made

2024-08-07 06:29 UTC, merged