[Move] Heal Block
pagefaultgames/pokerogue pull request #3326
Opened 2024-08-04 00:05 UTC by frutescens

## What are the changes?
This implements Heal Block and provides a test for it. 
Link to Old PR: https://github.com/pagefaultgames/pokerogue/pull/3047 

## Why am I doing these changes?
I think it would be nice for it to be implemented. 

## What did change?
- HealBlockTag (Duration: 5 Turns)
- PokemonHealPhase now accounts for HealBlockTag 
- Not implemented yet: moves restricted by heal block 
- Partially implemented: Tests 
- Lines for Localization 

### Screenshots/Videos
https://github.com/user-attachments/assets/08b71f5d-3325-437d-b4d4-975b7f803973

## How to test the changes?
Use Heal Block during a Pokemon battle and see if the affected pokemon can heal itself. 

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-05 17:48 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "battlerTagsHealBlockOnRemove": "{{pokemonNameWithAffix}} can restore its HP again!",
```suggestion
  "battlerTagsStockpilingOnAdd": "{{pokemonNameWithAffix}} utilise\nla capacité Stockage {{stockpiledCount}} fois !",
  "battlerTagsHealBlock": "{{pokemonNameWithAffix}} ne peut pas guérir !",
  "battlerTagsHealBlockOnRemove": "Le blocage de soins qui affectait\n{{pokemonNameWithAffix}} s’est dissipé !",
```

2024-08-05 18:04 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsStockpilingOnAdd": "{{pokemonNameWithAffix}} stockpiled {{stockpiledCount}}!",
```suggestion
  "battlerTagsStockpilingOnAdd": "{{pokemonNameWithAffix}} hortet {{stockpiledCount}}!",
```

2024-08-05 18:11 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "battlerTagsHealBlockOnRemove": "{{pokemonNameWithAffix}} can restore its HP again!",
```suggestion
  "battlerTagsHealBlock": "{{pokemonNameWithAffix}} kann nicht geheilt werden, da die Heilung blockiert wird!",
  "battlerTagsHealBlockOnRemove": "{{pokemonNameWithAffix}} kann wieder geheilt werden!",
```

2024-08-05 18:32 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "moneyWon": "Você ganhou\n₽{{moneyAmount}} por ganhar!",
```suggestion
  "moneyWon": "Você ganhou\n₽{{moneyAmount}} por vencer!",
```

The correct word is "vencer" and it has been fixed earlier

2024-08-05 18:33 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "battlerTagsHealBlockOnRemove": "{{pokemonNameWithAffix}} can restore its HP again!",
```suggestion
  "battlerTagsHealBlock": "{{pokemonNameWithAffix}} não pode restaurar seus PS!",
  "battlerTagsHealBlockOnRemove": "{{pokemonNameWithAffix}} pode restaurar seus PS novamente!",
```

2024-08-06 00:51 UTC, EnochG1 commented
@frutescens
When `battlerTagsHealBlock` message is triggered?
In og game, there's three messages.

{{pokemonNameWithAffix}} was prevented\nfrom healing! // when heal block used
{{pokemonNameWithAffix}} was prevented\nfrom healing due to Heal Block! // when heal blocked pokemon try using heal
{{pokemonNameWithAffix}}'s Heal Block\nwore off! // when heal block turn over.

2024-08-06 01:09 UTC, mercurius-00 commented
@frutescens 
I noticed that some content in `It` and `zh-CN` was rolled back that shouldn't be within the scope of this PR. Please check if it's correct.

2024-08-06 01:14 UTC, 40chyan commented
I was thinking that you are not using the newest beta branch as your pr base, causing many roll back commits in your pr, please refork a new branch with the newest version

2024-08-06 01:15 UTC, 40chyan requested changes
please use the newest beta branch as your pr base

2024-08-08 14:38 UTC, AsdarDevelops reviewed
Added Spanish

2024-08-08 14:38 UTC, AsdarDevelops commented on src/locales/es/battle.ts
> +  "battlerTagsHealBlockOnRemove": "{{pokemonNameWithAffix}} can restore its HP again!",
```suggestion
  "battlerTagsHealBlock": "¡{{pokemonNameWithAffix}} no puede restaurar sus PS!",
  "battlerTagsHealBlockOnRemove": "¡{{pokemonNameWithAffix}} ya puede recuperar PS!",
```

2024-09-09 00:20 UTC, closed without merging