Implements localization on Modifiers and everything related to them
pagefaultgames/pokerogue pull request #333
Opened 2024-04-28 17:55 UTC by Emmayuel80

This is a **big change** since a lot of things were dependent on the name string, so it needs to be **carefully tested** before merging, I did try to test every modifier before submitting and seemed fine but there's a lot of them so it's possible I missed something.

The most critical bug I found while making this is that sometimes i18n doesn't execute the t method at the right time, so it generates _undefined_ values (Mostly when rendering modifiers created with the ModifierType constructor, some modifiers like AddPokeballModifierType render just fine). 
I added a solution for when that happens, but it was by brute force so the root of the cause it's still a mystery, needs more investigation.

Changelog:
-Added berry en locale
-Added modifier types en/es locale
-Added modifier en/es locale contains miscelaneous descriptions for modifiers
-Added nature en/es locale
-Added type en locale
-Import new localization files into i18n plugin
 - Creates localize function withing various modifier classes
 -Reeplaces enum name strings for berry, nature, battle stats, vouchers, attack type boosters, stat boosters
 -Includes Dire Hit on the TempStatBooster modifier
 -Added a workaround for modifier name and description being undefined at rendering time (not the most optimal, needs more investigation)

2024-04-29 00:38 UTC, Flashfyre requested changes

2024-04-29 00:38 UTC, Flashfyre commented on src/data/battle-stat.ts
> +  CRIT
Why are we changing this enum?

2024-04-29 02:16 UTC, Emmayuel80 commented on src/data/battle-stat.ts
> +  CRIT
Sorry, forgot to revert that change before pushing, I just did on my latest commit!

2024-04-29 04:22 UTC, Flashfyre requested changes

2024-04-29 04:22 UTC, Flashfyre commented on src/modifier/modifier-type.ts
> +/* Now included in TEMP_STAT_BOOSTER  DIRE_HIT: () => return new TempBattleStatBoosterModifierType(TempBattleStat.CRIT), */
It's... not supposed to be in temp stat booster? It's supposed to be its own due to rarity tier. Please avoid changing logic when making a localization PR.

2024-04-29 04:59 UTC, Flashfyre requested changes
![image](https://github.com/pagefaultgames/pokerogue/assets/3542488/1953043b-8170-4ef4-b921-78db38d48dd1)
Here's an issue reported by someone doing testing. Make sure this is fixed and that the issue isn't present anywhere else.

2024-05-01 17:59 UTC, TeKrop commented on src/locales/en/berry.ts
> +        "name": "Sitrus",
As the ` Berry` suffix was removed from `getBerryName` function, shouldn't we specify it in every `name` here ? 🤔

2024-05-02 20:05 UTC, TeKrop commented
I would advise to make separate branches/PRs to properly introduce these changes : one for berries, another one for natures, etc.🤔 
IMHO It would make it easier to review and test, and make sure there isn't any hidden bug or regression 😅

2024-05-02 20:30 UTC, Emmayuel80 commented
I'm currently busy with other stuff from work, will revisit this when I gain some free time again 👀

2024-05-15 02:39 UTC, Adri1 commented
No news about this?

2024-05-16 08:21 UTC, bennybroseph commented
Currently out of date. Most of this has now been added in smaller chunks.

2024-05-16 08:21 UTC, closed without merging