[Enhancement] Fix and improve Starter selector UI
pagefaultgames/pokerogue pull request #3340
Opened 2024-08-04 10:59 UTC by KimJeongSun

## What are the changes?

## Why am I doing these changes?

## What did change?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-04 13:05 UTC, MokaStitcher requested changes
Some of the functionality got broken with the Sort filter:

The category doesn't display as changed if the direction is the default one, even if a different sort than the default one was selected

Resetting does not work properly if you set the sorting direction to descending before exiting and creating a new game.
Steps to reproduce:
- go to sort filter
- select Cost, descending, this requires two inputs, one to switch to Cost, the other to switch to descending
- exit out of starter select
- start a new game
- go to sort filter
- select Cost, it will directly be set to descending order
This is because of the way all sorting options keep track of the current sorting direction and these values don't get reset anymore with your changes.

2024-08-04 13:32 UTC, KimJeongSun commented on src/ui/starter-select-ui-handler.ts
> -      genDropDown.defaultCursor = 0;
current, it is using in dropdown.ts for update default cursor when not hovering mode. so let's keep it

2024-08-04 13:40 UTC, KimJeongSun commented on src/ui/dropdown.ts
> +    const currentValues = this.getSettings();
I gave it a try, but it doesn't seem to work properly as the dir and cursor parts seem to differ by type. Let's plan to refactor it next time.

2024-08-04 14:42 UTC, KimJeongSun commented on src/ui/dropdown.ts
> +    const currentValues = this.getSettings();
I will try refactoring this function, after that i will make it ready to review again

2024-08-04 14:48 UTC, KimJeongSun commented on src/ui/dropdown.ts
> +    const currentValues = this.getSettings();
updated

2024-08-05 15:34 UTC, MokaStitcher approved these changes
looks good!

2024-08-05 15:42 UTC, merged