[Enhancement] Add go filter shortcut
pagefaultgames/pokerogue pull request #3345
Opened 2024-08-04 17:21 UTC by KimJeongSun

## What are the changes?

## Why am I doing these changes?

## What did change?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-05 15:24 UTC, MokaStitcher requested changes
Should be good to go once the following is done:
- Address the comments from this review
- Add the shortcut button on mobile button layout (will try to look into that myself)
- I'm thinking we should also have the filter open automatically when using the shortcut? If you're using the shortcut it should be to change the filters anyway, so might as well spare ourselves the extra button press to open them

2024-08-05 15:24 UTC, MokaStitcher commented on src/ui/starter-select-ui-handler.ts
> -        this.updateButtonIcon(SettingKeyboard.Button_Cycle_Form, gamepadType, this.formIconElement, this.formLabel);
accidental extra space to remove

2024-08-05 15:24 UTC, MokaStitcher commented on src/ui/starter-select-ui-handler.ts
> +  updateFilterButtonIcon(iconSetting, gamepadType, iconElement, controlLabel): void {
Is the separate function for the filter button needed because it's in a different spot?
In this case, since the function is only used for the filter button and always called with the same iconSetting you could just remove the iconSetting parameter and the whole switch that is a copy paste from updateButtonIcon and not useful for the filter button

2024-08-05 15:24 UTC, MokaStitcher commented on src/locales/en/starter-select-ui-handler.ts
> +  "goFilter": ": Go to filters",
please add it in for the other locales as well

2024-08-05 17:34 UTC, Adri1 commented
Could you also add a placeholder in the French locale please?

2024-08-05 17:41 UTC, KimJeongSun commented
> Could you also add a placeholder in the French locale please?

added. sorry i missed

2024-08-05 17:53 UTC, Adri1 reviewed
Thanks!
I think you might also have to push it a bit to the left, as the text might overlap a bit on the filter bar (and might be the case for other languages)

2024-08-05 17:53 UTC, Adri1 commented on src/locales/fr/starter-select-ui-handler.ts
> +  "goFilter": ": Go to filters",
```suggestion
  "goFilter": ": Aller aux filtres",
```

2024-08-05 17:57 UTC, CodeTappert commented on src/locales/de/starter-select-ui-handler.ts
> +  "goFilter": ": Go to filters",
```suggestion
  "goFilter": ": Zu den Filtern",
```

2024-08-05 18:00 UTC, KimJeongSun commented
> Thanks! I think you might also have to push it a bit to the left, as the text might overlap a bit on the filter bar (and might be the case for other languages)

even I moved as much as it can, still it looks over length. can you change it?

<img width="1718" alt="image" src="https://github.com/user-attachments/assets/821ada61-c010-4406-8f45-5c6b52df73ed">

2024-08-05 18:01 UTC, KimJeongSun commented
or i can change the font size of `fr`

2024-08-05 18:27 UTC, josericardo-fo commented on src/locales/pt_BR/starter-select-ui-handler.ts
> +  "goFilter": ": Go to filters",
```suggestion
  "goFilter": ": Ir para filtros",
```

2024-08-06 00:39 UTC, EnochG1 commented on src/locales/ko/starter-select-ui-handler.ts
> +  "goFilter": ": Go to filters",
```suggestion
  "goFilter": ": 필터로 이동",
```

2024-08-06 00:40 UTC, Adri1 approved these changes

2024-08-06 00:53 UTC, mercurius-00 reviewed
zh-CN and zh-TW

2024-08-06 00:53 UTC, mercurius-00 commented on src/locales/zh_CN/starter-select-ui-handler.ts
> +  "goFilter": ": Go to filters",
```suggestion
  "goFilter": ": 转到筛选",
```

2024-08-06 00:53 UTC, mercurius-00 commented on src/locales/zh_TW/starter-select-ui-handler.ts
> +  "goFilter": ": Go to filters",
```suggestion
  "goFilter": ": 轉到篩選",
```

2024-08-07 23:14 UTC, f-fsantos approved these changes

2024-08-08 14:34 UTC, AsdarDevelops reviewed
Spain España

2024-08-08 14:34 UTC, AsdarDevelops commented on src/locales/es/starter-select-ui-handler.ts
> +  "goFilter": ": Go to filters",
```suggestion
  "goFilter": ": Ir a filtros",
```

2024-08-08 19:34 UTC, merged