[BUG] - dragon tail switchout ability in wild battles proc crashes game
pagefaultgames/pokerogue pull request #3346
Opened 2024-08-04 17:40 UTC by DustinLin

## What are the changes?

Fixed game freezing bug when force-out moves (commonly dragon tail) in doubles and single wild battles.

## Why am I doing these changes?

Bug often report on discord

## What did change?

Previous code was immediately destroying the forced-out pokemon object, causing any further reference to it (eg: showing its ability) to reference undefined and crash the game.

To remedy this I made a few changes:
- delay the destroying of wild pokemon objects until the end of the battle
- added an attribute to track wild pokemon that fled, this is to ensure that (since the fled pokemon's object is still around the `BattleScene` but not marked as `fainted`, it isn't selected by `getEnemyPokemon()` to move animations. Without this the game would sometimes crash, as Phaser would try to animate moves hitting a non-visible pokemon.
- added move auto-redirection (moves targeting a fled pokemon would redirect to the other in doubles), this is the same behavior as when a pokemon faints, so refactored code.

### Screenshots/Videos

- `beta`
![original report](https://github.com/user-attachments/assets/62bfb3bc-68da-438e-b9e4-205cb040d542)

https://github.com/user-attachments/assets/39c8cf24-141a-417c-a4f6-813348bf6c83

- `pr`
doubles battles
https://github.com/user-attachments/assets/a8fc1963-6798-43b9-986e-dacfb8799fdc

https://github.com/user-attachments/assets/c002c4d9-867a-44e6-9f3e-6a6852dfa917

Uploading doubles_1flee.mov…

single battles
https://github.com/user-attachments/assets/bb1a9e8f-72ca-4f62-82e5-c06e69664e85

## How to test the changes?

Commonly reported abilities are "mummy" and "cotton down". There are probably other abilities, but this fix should work for all of them.

This bug should only affect doubles wild battles

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-06 17:31 UTC, snoozbuster commented on src/data/move.ts
> +          switchOutTarget.setWildFlee(true);
instead of trying to do the flee inline in the phase and then having to handle redirecting moves - I think if we made a new EnemyFleePhase and added that to the phase order, it would allow the remaining parts of MoveEffectPhase to run normally (so for example, post-contact effects like static would work correctly and have all the references they need), then the flee phase could come after and handling removing the mon (probably similar to how FaintPhase does it, although I would need to look at that code). I think that MovePhase already handles cases where the move tries to run but the target is missing and needs to be re-directed (although again, I would need to confirm). 

that's how I was thinking about fixing this when I was looking into it, anyway. it seemed like all the relevant code existed already, it just needed to be sequenced properly - my experience with this attr so far is that using phases for its effects generally seems to be a lot more stable than trying to do things inline in the same MoveEffectPhase.

2024-08-06 17:39 UTC, snoozbuster requested changes
I would really like to see at least one unit test added for not crashing when a fleeing uturn user activates poison point or another ability - it should be an easy scenario to setup and test. there's some prior art in https://github.com/pagefaultgames/pokerogue/pull/3321 which could be referenced.

2024-08-06 17:44 UTC, snoozbuster commented on src/data/move.ts
> +      .hidesTarget(),
what does the hides target flag do? I see it's already on whirlwind and roar but there's no description for what it does in the code

2024-08-06 17:44 UTC, snoozbuster commented on src/field/pokemon.ts
> +  public wildFlee: boolean;
could call this `hasFled`

2024-08-06 17:45 UTC, snoozbuster commented on src/phases.ts
> +    for (const p of this.scene.getEnemyParty()) {
do you need to do any checks here? is there any harm in double-destroying a mon?

2024-08-06 17:46 UTC, snoozbuster commented on src/phases.ts
> +    // in double battles redirect potential moves off fainted pokemon
personally I don't think this comment is super needed anymore given that the function is now named accurately and has a good description/jsdoc - but that's something of a personal preference

2024-08-06 17:48 UTC, snoozbuster commented
>This bug should only affect doubles wild battles

there's a similar issue with singles and uturn - eg, a uturn wild pokemon uses uturn and gets afflicted by poison point or rough skin as it flees, or a uturn user has something like poison touch and it activates when they make contact with the player. can you check if these have been fixed as well (and ideally write a test for them)?

2024-08-06 18:12 UTC, DustinLin commented on src/phases.ts
> +    for (const p of this.scene.getEnemyParty()) {
don't think so, `destroy()`should only be called once at the end of the battle phase. I tested it real quick by calling `destroy()` multiple times and it wasn't game breaking.

2024-08-06 18:34 UTC, DustinLin commented on src/data/move.ts
> +          switchOutTarget.setWildFlee(true);
the flee logic is a bit different from fainting/`FaintPhase`. The latter is more complex (you gotta do some xp tracking, play the fainting cry, update some internal variables for if the 'mon and update scores, etc.) additionally fainting adds new phases like picking item rewards and all that. I thought of something similar to your solution at first. But I think this simpler in that we don't have to mess with adding more phases/code

i guess there is a philosophical discussion to be had with introducing new phases. For moves like dragon tail, the flee/switch out is *part of* the MoveEffect, so can make an argument for why it would make sense to include it in the same phase, rather than splitting up the move resolution to multiple phases.

2024-08-07 02:54 UTC, snoozbuster commented on src/data/move.ts
> +          switchOutTarget.setWildFlee(true);
the main reason to put it in a separate phase, IMO, is MoveEffectPhase pretty much exclusively operates on fieldIndexes (at least, as far as I'm aware) so any changes to the field during the phase's resolution can cause pretty serious issues - from what I've been able to surmise during debugging, a lot of the issues with moves that use this attribute are basically due to the fact that it modifies the field during the phase. in the case of the other PR I'm working on, changing the player branch to use SwitchPhase instead of `pokemon.switchOut` dramatically improved the stability of the move (and actually improved the order that the player sees things happen in, too) without actually changing the effect of it. that to me is the main reason to consider putting it in a separate phase. 

but tbh, I'm pretty sure the solution in this PR works fine too, and I'm not 100% convinced a new phase for this is a great idea either (honestly, I think it's probably not worth it unless FaintPhase can be made to use the same phase for part of its logic). as long as it's got UTs so we know if/when it breaks, I am fine with this or basically any implementation, since it means if someone does need to change it later it will be easy to verify.

2024-08-07 17:58 UTC, snoozbuster commented on src/test/moves/dragon_tail.test.ts
> +      expect(leadPokemon?.hp < leadPokemon?.getMaxHp());
given that you assert earlier that leadPokemon is defined, you probably don't need to use optional chaining here (plus it might fix the typedocs issues you're having)

2024-08-07 18:29 UTC, DustinLin commented on src/test/moves/dragon_tail.test.ts
> +      expect(leadPokemon?.hp < leadPokemon?.getMaxHp());
yeah i think that was the issue, from discord @ NightKev: 

"basically whenenever you do `enemy = game.scene.getEnemyPokemon();` and `player = game.scene.getPlayerPokemon(); `add a `!` after the `()`, for now anyway; maybe in the future it won't be nececssary "

adding the bang will tell the compiler that the variable can't be undefined (a bypass for writing tests)

2024-08-07 19:11 UTC, snoozbuster commented on src/test/moves/dragon_tail.test.ts
> +    game.override.enemyLevel(5);
I personally don't mind it either way but some folks prefer these to be chained together (`game.overrides.m1().m2()...`)

2024-08-07 19:11 UTC, snoozbuster commented on src/test/moves/dragon_tail.test.ts
> +      expect(!isVisible && hasFled ).toBe(true);
```suggestion
      expect(!isVisible && hasFled).toBe(true);
```

2024-08-07 19:12 UTC, snoozbuster commented on src/test/moves/dragon_tail.test.ts
> +      expect(true).toBe(true);
there's not really much of a point to this assertion imo, the comment does a fine job of explaining what's happening and this assertion never fails, so it's not really useful to have it here

2024-08-07 19:12 UTC, snoozbuster commented on src/test/moves/dragon_tail.test.ts
> +      expect(!isVisible && hasFled ).toBe(true);
```suggestion
      expect(!isVisible && hasFled).toBe(true);
```

2024-08-07 19:13 UTC, snoozbuster commented on src/test/moves/dragon_tail.test.ts
> +      expect(!isVisibleLead && hasFledLead && isVisibleSec && !hasFledSec ).toBe(true);
```suggestion
      expect(!isVisibleLead && hasFledLead && isVisibleSec && !hasFledSec).toBe(true);
```

2024-08-07 19:15 UTC, snoozbuster commented on src/test/moves/dragon_tail.test.ts
> +      expect(enemySecPokemon.hp < enemySecPokemon.getMaxHp() ).toBe(true);
I'm not entirely sure what this second turn is testing about dragon tail - is it just that you can take a second turn and nothing is crashing? just running the phases back around to TurnInitPhase is probably sufficient to say that a second turn would happen - a good way to "test the test" is to run the test on beta without your changes and remove as much as possible from the test such that it still fails without your change, and then passes with your change

2024-08-07 19:17 UTC, snoozbuster commented on src/test/moves/dragon_tail.test.ts
> +
you may also want to run this test to the BattleEndPhase and make sure the game makes it there - I'm not 100% sure this test would actually fail pre-fix (excepting the `hasFled` checks) because I think the rough skin damage and everything might go through before the crash. not 100% sure on that though

2024-08-07 19:32 UTC, DustinLin commented on src/data/move.ts
> +      .hidesTarget(),
`.hidesTarget()` sets moves flags, which I think is used in the animations (`battle-anims.ts`). TBH I don't know more than that, but I put this because whirlwind and roar both do similar things so I figured it makes sense too

2024-08-07 19:34 UTC, DustinLin commented on src/field/pokemon.ts
> +  public wildFlee: boolean;
I think `wildFlee` is a better name: since this variable is only updated/messed around with for wild battles, i feel like including "wild" in the variable name is more descriptive. `hasFled` was something that crossed my mind, but that requires one step to infer that fleeing can only happen for wild battles

2024-08-07 19:38 UTC, DustinLin commented on src/test/moves/dragon_tail.test.ts
> +      expect(enemySecPokemon.hp < enemySecPokemon.getMaxHp() ).toBe(true);
Yes, one of the bugs that I ran into while fixing this was that on the turn after the pokemon flees, certain move animations would crash the game (one such move was flamethrower). There were also problems with the CPU deciding enemy pokemon's moves after one has left the field so the simulation should at least go beyond `TurnInitPhase`

I was going to include these as comments in the test, but it seems like a lot of my comments get marked as unnecessary so I figured not. I could include this though if you think it's helpful

2024-08-07 19:42 UTC, snoozbuster commented on src/data/move.ts
> +      .hidesTarget(),
Assuming is a dangerous game (but it does probably make sense here, I would hope that this flag causes a sprite to be hidden after the animation plays)

2024-08-07 19:43 UTC, snoozbuster commented on src/field/pokemon.ts
> +  public wildFlee: boolean;
What about wildHasFled or hasWildFled? Could be best of both worlds

2024-08-07 20:35 UTC, DustinLin commented on src/test/moves/dragon_tail.test.ts
> +
Running to `BerryPhase` should be enough, the abilities triggering (showAbilityPhase, the damage, messagePhase, etc.) all happen before Berry so we should be good here

2024-08-07 20:36 UTC, DustinLin commented on src/test/moves/dragon_tail.test.ts
> +      expect(enemySecPokemon.hp < enemySecPokemon.getMaxHp());
yeah that's a much better comparator/assert to use

2024-08-08 00:44 UTC, merged

2024-08-09 02:57 UTC, flx-sta commented
This PR broke advancing past any 50th wave in endless mode by causing `pokemon.scene` to be `null/undefined`

2024-08-09 03:07 UTC, DayKev commented on src/data/move.ts
> +      .hidesTarget(),
Given that Roar and Whirlwind have a bug where they inappropriately hide the enemy Pokémon...

2024-08-09 03:08 UTC, flx-sta commented
Also found the reason
```ts
  end() {
    // removing pokemon at the end of a battle
    for (const p of this.scene.getEnemyParty()) {
      p.destroy(); // <--- ⚠️⚠️⚠️
    }

    super.end();
  }
  ```
  
  this is causing `pokemon.scene` to be `null/undefined` at the end of the fight even though there is still some calculation necessary. SO if that is just some "nice addition" we could just remove it

2024-08-09 03:10 UTC, DayKev commented
It only breaks endless past wave 50? That's... weird.

2024-08-09 03:16 UTC, flx-sta commented
> It only breaks endless past wave 50? That's... weird.

No it break any `%50` wave in endless. (or just some!?) idk.
Here is some session to work with (just change file-extension to `.prsv`)
[sessionData3_Guest.txt](https://github.com/user-attachments/files/16555427/sessionData3_Guest.txt)

What happens is
```
Start Phase BerryPhase
Start Phase TurnEndPhase
Start Phase BattleEndPhase | THIS calls p.destroy() on all enemies
...
Start Phase EggLapsePhase
Start Phase ModifierRewardPhase
Start Phase AddEnemyBuffModifierPhase
```

the last phase calls `regenerateModifierPoolThresholds` with the enemyParty() which has just been destroyed.

```ts
start() {
    super.start();

    const waveIndex = this.scene.currentBattle.waveIndex;
    const tier = !(waveIndex % 1000) ? ModifierTier.ULTRA : !(waveIndex % 250) ? ModifierTier.GREAT : ModifierTier.COMMON;

    regenerateModifierPoolThresholds(this.scene.getEnemyParty(), ModifierPoolType.ENEMY_BUFF);

    const count = Math.ceil(waveIndex / 250);
    for (let i = 0; i < count; i++) {
      this.scene.addEnemyModifier(getEnemyBuffModifierForWave(tier, this.scene.findModifiers(m => m instanceof EnemyPersistentModifier, false), this.scene), true, true);
    }
    this.scene.updateModifiers(false, true).then(() => this.end());
  }
}
```

and inside `regenerateModifierPoolThresholds()` it's trying to call
```ts
 const existingModifiers = party[0].scene.findModifiers
 ``` 
 but `scene` is null/undefined because all pokemons were destroyed previously and are not there anymore