[Balance] Adjust Gallade/Froslass evos to require move of their type
pagefaultgames/pokerogue pull request #3349
Opened 2024-08-04 20:05 UTC by Fontbane

## What are the changes?

- Adjust Snorunt and Kirlia evolution methods:
  - Snorunt -> Glalie: Level 42 (male)
    - Changed to: Level 42 (either gender, unless you fulfill Froslass requirements)
  - Snorunt -> Froslass: Level 42 (female)
    - Changed to: Level 42 (female) while knowing a Ghost-type move
  - Kirlia -> Gallade: Level 30 (male)
    - Changed to: Level 30 (male) while knowing a Fighting-type move
  - Kirlia -> Gardevoir: Level 30 (female)
    - Changed to: Level 30 (either gender, unless you fulfill Gallade requirements)
  - To accommodate Kirlia's new evolution method, it now learns **Quick Guard** at level 1.

## Why am I doing these changes?

- Froslass and Gallade's evolutions are custom in Rogue to just require reaching the level as the appropriate gender
- This is for convenience so these mons aren't nerfed by having to search for a Dawn Stone for players to evolve them
- This meant that only male Snorunt evolved into Glalie and only female Kirlia evolved into Gardevoir
- This created issues in cases of certain challenge runs where this custom evolution method, meant for convenience, could make these mons unusable if the player had one of the wrong gender
- The new solution follows more expected behavior in line with the main series, where both genders can evolve into Glalie or Gardevoir, while evolving into Froslass or Gallade requires a player choice (in this case, teaching a Ghost or Fighting move)
- Snorunt learns **Astonish** naturally at level 1. Kirlia was given Quick Guard at level 1 as it's a fitting move which Gallade learns by level up.

## What did change?

- Kirlia evolving into Gallade requires it being male and knowing a Fighting-type move
- Kirlia now learns Quick Guard at level 1
- Kirlia into Gardevoir now has no conditions other than level, though Gallade's evolution will take precedent if the conditions are met
- Snorunt evolving into Froslass requires it being female and knowing a Ghost-type move
- Snorunt into Glalie now has no conditions other than level, though Froslass's evolution will take precedent if the conditions are met

### Screenshots/Videos

## How to test the changes?

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I considered writing automated tests for the issue?
- [X] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-04 20:18 UTC, damocleas requested changes
Could you not put it at the same level as evolve, since you can learn moves before you evolve that would dictate it?

2024-08-04 20:37 UTC, damocleas approved these changes

2024-08-04 22:12 UTC, Tempo-anon reviewed
I personally think that "Male Kirlia turns into Gallade and Female Snorunt turns into Froslass" intuitively makes more sense and is easier to grasp than "They need to be the right gender and have a specific type move."

In terms of moves, this means adding a custom mediocre move to Kirlia and forcing Snorunt to carry a very bad move to level 42 and as seen from players reactions to Pokemon like Yanma needing ancientpower, that's not a very popular thing.

2024-08-04 22:12 UTC, Tempo-anon commented on src/data/pokemon-level-moves.ts
> +    [ 25, Moves.QUICK_GUARD ],
grrrr more custom moves (also quick guard is pretty bad)

2024-08-04 22:12 UTC, Tempo-anon commented on src/data/pokemon-evolutions.ts
> +    new SpeciesEvolution(Species.GALLADE, 30, null, new SpeciesEvolutionCondition(p => p.gender === Gender.MALE && !!p.getMoveset().find(m => m.getMove().type === Type.FIGHTING), p => p.gender = Gend
Needing to know a move of a specific type feels pretty weird to me. Personally I'd also just make Onix/Scyther be link cable only

2024-08-04 23:53 UTC, DayKev commented
If you're adding the move requirement why do Gallade and Froslass still have the gender requirement then?

2024-08-05 01:08 UTC, Fontbane commented
> If you're adding the move requirement why do Gallade and Froslass still have the gender requirement then?

Gallade and Froslass are male/female only

2024-08-05 01:09 UTC, Fontbane commented on src/data/pokemon-level-moves.ts
> +    [ 25, Moves.QUICK_GUARD ],
If you're gonna evolve into Gallade it's not like you're keeping any of Kirlia's level up moves anyway

2024-08-05 21:37 UTC, Fontbane commented on src/data/pokemon-evolutions.ts
> +    new SpeciesEvolution(Species.GALLADE, 30, null, new SpeciesEvolutionCondition(p => p.gender === Gender.MALE && !!p.getMoveset().find(m => m.getMove().type === Type.FIGHTING), p => p.gender = Gend
Sylveon also does this

2024-08-06 21:48 UTC, Fontbane commented
The woke mob got me folks

2024-08-06 21:54 UTC, damocleas requested changes
I feel like this can be gone about a different way for Froslass/Glalie, and if the same for Gallade/Gardevoir I don't see reason to gender lock Snorunt.

2024-08-06 21:56 UTC, Fontbane commented
> I feel like this can be gone about a different way for Froslass/Glalie, and if the same for Gallade/Gardevoir I don't see reason to gender lock them.

The move solution isn't as clean for Froslass/Glalie, true. I don't see why we would un-gender lock Gallade though.

2024-08-26 00:01 UTC, Fontbane commented
Not happening

2024-08-26 00:01 UTC, closed without merging