[QoL] Add setting to toggle UI sound efffects
pagefaultgames/pokerogue pull request #3354
Opened 2024-08-05 04:15 UTC by tlelievre26

## What are the changes?
Adds an option to the settings menu that toggles the sound effects from the UI.

## Why am I doing these changes?
Relevant issue: https://github.com/pagefaultgames/pokerogue/issues/3164

## What did change?

Adds a new variable to the settings menu that, when enabled, disables the playSound and playError functions in the UI class. The variable is also checked when playing the sound effects associated with opening/closing the menu

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/4006fbd6-13e2-40fe-82ff-e1aea3b010e3)

![image](https://github.com/user-attachments/assets/7f5ecf24-db9f-45ad-9724-ea76e4cb5ba2)

## How to test the changes?

Manually tested by enabling the setting and moving around the main menu, starter select menu, and playing through a few battles to ensure all UI sounds were disabled

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-05 17:32 UTC, Adri1 commented
Could you add it to all other locales please?

2024-08-05 23:54 UTC, tlelievre26 commented
> Could you add it to all other locales please?

Done

2024-08-05 23:57 UTC, Adri1 commented on src/locales/fr/settings.ts
> +  "uiSoundEffects": "UI Sound Effects",
```suggestion
  "uiSoundEffects": "Son des menus",
```

2024-08-06 00:15 UTC, sodaMelon commented on src/locales/ko/settings.ts
> +  "uiSoundEffects": "UI Sound Effects",
```suggestion
  "uiSoundEffects": "UI 효과음",
```

2024-08-06 00:16 UTC, sodaMelon reviewed
added korean localization

2024-08-06 01:26 UTC, 40chyan reviewed
zh

2024-08-06 07:52 UTC, CodeTappert commented on src/locales/de/settings.ts
> +  "uiSoundEffects": "UI Sound Effects",
```suggestion
  "uiSoundEffects": "UI-Soundeffekte",
```

2024-08-06 13:39 UTC, josericardo-fo commented on src/locales/pt_BR/settings.ts
> +  "uiSoundEffects": "UI Sound Effects",
```suggestion
  "uiSoundEffects": "Efeitos Sonoros do Menu",
```

2024-08-07 05:02 UTC, EnochG1 commented
@tlelievre26 
From now Japanese is added in beta.
Could you merge latest beta and add Japanese locale files? 🙏

2024-08-08 15:21 UTC, tlelievre26 commented
I think I'm still waiting for the Spanish + Japanese translation correct?

2024-08-10 19:43 UTC, AsdarDevelops reviewed
Added also some other translations that were missing in Spanish

2024-08-10 19:43 UTC, AsdarDevelops commented on src/locales/es/settings.ts
>    "gamepadPleasePlug": "Please Plug in a Gamepad or Press a Button",
```suggestion
  "masterVolume": "Volumen general",
  "bgmVolume": "Volumen de la música",
  "seVolume": "Volumen de los efectos",
  "uiSoundEffects": "Volumen de la interfaz",
  "musicPreference": "Preferencia de música",
  "mixed": "Mixto",
  "gamepadPleasePlug": "Conecta un Gamepad o pulsa un botón",
```

2024-08-10 20:11 UTC, torranx commented
To be consistent with other sound controls, I'd prefer this to be an actual volume control just like the others.

2024-08-11 14:57 UTC, NicusPulcis approved these changes
italian localization is done

2024-08-11 14:57 UTC, NicusPulcis commented on src/locales/it/settings.ts
> +  "uiSoundEffects": "UI Sound Effects",
```suggestion
  "uiSoundEffects": "Effetti sonori UI",
```

2024-08-13 00:34 UTC, frutescens requested changes
Hi. Thank you for writing this PR. Please let me know if you have any questions about battle-scene.ts ' playSound() function.

2024-08-13 00:34 UTC, frutescens commented on src/ui-inputs.ts
> +      if (this.scene.uiSoundEffects) {
Please move this check to inside the playSound() method in battle-scene.ts

2024-08-13 00:34 UTC, frutescens commented on src/ui/menu-ui-handler.ts
> +      this.scene.playSound("menu_open");
See above.

2024-08-13 00:34 UTC, frutescens commented on src/ui/ui.ts
> +    if ((this.scene as BattleScene).uiSoundEffects) {
See above comment.

2024-08-13 00:34 UTC, frutescens commented on src/ui/ui.ts
> +    if ((this.scene as BattleScene).uiSoundEffects) {
See above comment.

2024-08-13 21:15 UTC, tlelievre26 commented
> Hi. Thank you for writing this PR. Please let me know if you have any questions about battle-scene.ts ' playSound() function.

Thanks for pointing this out, I refactored this PR to work with the changes introduced in #3527, which includes changing this setting from a toggle to a volume control.

Only things still worth considering:
Should there be any other audio files considered as "ui" sounds other than "select", "error", and "menu_open"
Should the name of this setting be changed to "UI Volume" to be consistent with the other settings? I don't want to make the translators redo all their work

2024-08-25 17:10 UTC, CodeTappert commented
You have conflicts that need fixing

2024-08-25 17:24 UTC, CodeTappert approved these changes

2024-08-25 20:51 UTC, frutescens requested changes

2024-08-25 20:51 UTC, frutescens commented on src/battle-scene.ts
> +        config["volume"] = this.masterVolume * this.uiVolume;
can you add a comment specifying the sounds under the UI label? have you decided to make any decisions re: the categorization from before?

2024-08-26 01:31 UTC, torranx commented
Please update PR title and description

2024-08-26 04:31 UTC, Madmadness65 approved these changes

2024-08-26 08:19 UTC, torranx approved these changes

2024-08-26 17:21 UTC, frutescens approved these changes

2024-08-26 19:37 UTC, SangaraSorama approved these changes
My review is only about the locales/en file

2024-08-26 20:01 UTC, merged