[QoL] Change Dex filter name to Caught
pagefaultgames/pokerogue pull request #3361
Opened 2024-08-05 16:42 UTC by KimJeongSun

## What are the changes?

## Why am I doing these changes?

## What did change?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-05 16:51 UTC, MokaStitcher requested changes

2024-08-05 16:51 UTC, MokaStitcher commented on src/locales/zh_TW/filter-bar.ts
>    "dexFilter": "Dex",
changed the wrong entry here

2024-08-05 16:52 UTC, KimJeongSun commented on src/locales/zh_TW/filter-bar.ts
>    "dexFilter": "Dex",
you saved me

2024-08-05 16:57 UTC, MokaStitcher approved these changes
looks good

2024-08-05 17:31 UTC, Adri1 commented on src/locales/fr/filter-bar.ts
> +  "caughtFilter": "Caught",
```suggestion
  "caughtFilter": "Capturés",
```

2024-08-05 18:31 UTC, josericardo-fo commented on src/locales/pt_BR/filter-bar.ts
> +  "caughtFilter": "Caught",
```suggestion
  "caughtFilter": "Capturado",
```

2024-08-06 00:40 UTC, EnochG1 commented on src/locales/ko/filter-bar.ts
> +  "caughtFilter": "Caught",
```suggestion
  "caughtFilter": "포획",
```

2024-08-06 01:16 UTC, 40chyan reviewed
zh

2024-08-06 01:16 UTC, 40chyan commented on src/locales/zh_CN/filter-bar.ts
> +  "caughtFilter": "Caught",
```suggestion
  "caughtFilter": "捕获",
```

2024-08-06 01:16 UTC, 40chyan commented on src/locales/zh_TW/filter-bar.ts
> +  "caughtFilter": "Caught",
```suggestion
  "caughtFilter": "捕獲",
```

2024-08-06 02:54 UTC, merged