[Bug] Fix Assist bug of using only the user's moveset instead of whole team's, refactor Assist/Sleep Talk/Metronome implementation
pagefaultgames/pokerogue pull request #3380
Opened 2024-08-06 15:24 UTC by schmidtc1

Rebranch of #3075 
## What are the changes?

Properly implements Assist. 
Refactors RandomMovesetMoveAttr to extend RandomMoveAttr. 
Creates arrays of invalid moves for each move: Assist, Sleep Talk, Metronome, since they each have different sets of uncallable moves.

## Why am I doing these changes?

Assist did not call ally moves, had useless code, and was given no distinction in logic from Sleep Talk. 
Metronome calls random moves in a similar manner to the two other moves, so it makes sense to have Assist/Sleep Talk reuse the code for calling moves.
None of Assist/Sleep Talk/Metronome had properly implemented lists of uncallable moves.

## What did change?

- Assist now uses the entire team's party
- Assist/Sleep Talk's attribute now extends `RandomMoveAttr` and uses its callMoves function (which has been modified slightly to accommodate this) to call the move
- Sleep Talk targeting is changed to `NEAR_ENEMY`
- Assist/Sleep Talk/Metronome now have individual arrays listing uncallable moves. These arrays were created referencing Bulbapedia's list of uncallable moves.
- Uncallable moves for [Assist](https://bulbapedia.bulbagarden.net/wiki/Assist_(move)#:~:text=in%20a%20battle.-,Uncallable%20moves,-This%20move%20effect)
- Uncallable moves for [Sleep Talk](https://bulbapedia.bulbagarden.net/wiki/Sleep_Talk_(move)#:~:text=Z%2DPower%20effect.-,Unselectable%20moves,-This%20section%20is)
- Uncallable moves for [Metronome](https://bulbapedia.bulbagarden.net/wiki/Metronome_(move)#:~:text=Z%2DPower%20effect.-,Unselectable%20moves,-This%20move%20effect)

Note: Sleep Talk specifies that it targets the [opposite opponent](https://bulbapedia.bulbagarden.net/wiki/Sleep_Talk_(move)#:~:text=In%20Double%20and%20Triple%20Battles%2C%20because%20of%20the%20inability%20to%20select%20a%20target%2C%20the%20chosen%20move%20will%20always%20hit%20the%20opponent%20directly%20across%20from%20the%20user%2C%20if%20the%20move%20called%20normally%20hits%20only%20one%20Pok%C3%A9mon.). Since there is no `MoveTarget` specifically for opposite opponents, I chose to make it `NEAR_ENEMY` for now.

### Screenshots/Videos

Metronome

https://github.com/user-attachments/assets/c8861801-acd0-4ae0-b817-181cffa549d7

Assist

https://github.com/user-attachments/assets/9146fc45-9294-4d59-a726-ffcdf31b5777

Sleep Talk

https://github.com/user-attachments/assets/afd243b0-b2e9-4d84-9ba9-13a924c4b439

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-27 16:43 UTC, frutescens requested changes

2024-08-27 16:43 UTC, frutescens commented on src/data/move.ts
> +const invalidMetronomeMoves: Moves[] = [
I think that it would be better to have the invalid moves into one list and part of the RandomMovesetMoveAttribute class if possible. I also removed the Max/Z moves to remove clutter because I believe there are no plans at the moment to implement them. 

`const invalidMetronomeMoves: Moves[] = [Moves.AFTER_YOU, Moves.APPLE_ACID, Moves.ARMOR_CANNON, Moves.ASSIST, Moves.ASTRAL_BARRAGE, Moves.AURA_WHEEL, Moves.BANEFUL_BUNKER, Moves.BEAK_BLAST, Moves.BEHEMOTH_BASH, Moves.BEHEMOTH_BLADE, Moves.BELCH, Moves.BESTOW, Moves.BLAZING_TORQUE, Moves.BODY_PRESS, Moves.BRANCH_POKE, Moves.BREAKING_SWIPE, Moves.CELEBRATE, Moves.CHATTER, Moves.CHILLING_WATER, Moves.CHILLY_RECEPTION, Moves.CLANGOROUS_SOUL, Moves.COLLISION_COURSE, Moves.COMBAT_TORQUE, Moves.COMEUPPANCE, Moves.COPYCAT, Moves.COUNTER, Moves.COVET, Moves.CRAFTY_SHIELD, Moves.DECORATE, Moves.DESTINY_BOND, Moves.DETECT, Moves.DIAMOND_STORM, Moves.DOODLE, Moves.DOUBLE_IRON_BASH, Moves.DOUBLE_SHOCK, Moves.DRAGON_ASCENT, Moves.DRAGON_ENERGY, Moves.DRUM_BEATING, Moves.DYNAMAX_CANNON, Moves.ELECTRO_DRIFT, Moves.ENDURE, Moves.ETERNABEAM, Moves.FALSE_SURRENDER, Moves.FEINT, Moves.FIERY_WRATH, Moves.FILLET_AWAY, Moves.FLEUR_CANNON, Moves.FOCUS_PUNCH, Moves.FOLLOW_ME, Moves.FREEZE_SHOCK, Moves.FREEZING_GLARE, Moves.GLACIAL_LANCE, Moves.GRAV_APPLE, Moves.HELPING_HAND, Moves.HOLD_HANDS, Moves.HYPER_DRILL, Moves.HYPERSPACE_FURY, Moves.HYPERSPACE_HOLE, Moves.ICE_BURN, Moves.INSTRUCT, Moves.JET_PUNCH, Moves.JUNGLE_HEALING, Moves.KINGS_SHIELD, Moves.LIFE_DEW, Moves.LIGHT_OF_RUIN, Moves.MAKE_IT_RAIN, Moves.MAGICAL_TORQUE, Moves.MAT_BLOCK, Moves.ME_FIRST, Moves.METEOR_ASSAULT, Moves.METRONOME, Moves.MIMIC, Moves.MIND_BLOWN, Moves.MIRROR_COAT, Moves.MIRROR_MOVE, Moves.MOONGEIST_BEAM, Moves.NATURE_POWER, Moves.NATURES_MADNESS, Moves.NOXIOUS_TORQUE, Moves.OBSTRUCT, Moves.ORDER_UP, Moves.ORIGIN_PULSE, Moves.OVERDRIVE, Moves.PHOTON_GEYSER, Moves.PLASMA_FISTS, Moves.POPULATION_BOMB, Moves.POUNCE, Moves.POWER_SHIFT, Moves.PRECIPICE_BLADES, Moves.PROTECT, Moves.PYRO_BALL, Moves.QUASH, Moves.QUICK_GUARD, Moves.RAGE_FIST, Moves.RAGE_POWDER, Moves.RAGING_BULL, Moves.RAGING_FURY, Moves.RELIC_SONG, Moves.REVIVAL_BLESSING, Moves.RUINATION, Moves.SALT_CURE, Moves.SECRET_SWORD, Moves.SHED_TAIL, Moves.SHELL_TRAP, Moves.SILK_TRAP, Moves.SKETCH, Moves.SLEEP_TALK, Moves.SNAP_TRAP, Moves.SNARL, Moves.SNATCH, Moves.SNORE, Moves.SNOWSCAPE, Moves.SPECTRAL_THIEF, Moves.SPICY_EXTRACT, Moves.SPIKY_SHIELD, Moves.SPIRIT_BREAK, Moves.SPOTLIGHT, Moves.STEAM_ERUPTION, Moves.STEEL_BEAM, Moves.STRANGE_STEAM, Moves.STRUGGLE, Moves.SUNSTEEL_STRIKE, Moves.SURGING_STRIKES, Moves.SWITCHEROO, Moves.TECHNO_BLAST, Moves.TERA_STARSTORM, Moves.THIEF, Moves.THOUSAND_ARROWS, Moves.THOUSAND_WAVES, Moves.THUNDER_CAGE, Moves.THUNDEROUS_KICK, Moves.TIDY_UP, Moves.TRAILBLAZE, Moves.TRANSFORM, Moves.TRICK, Moves.TWIN_BEAM, Moves.V_CREATE, Moves.WICKED_BLOW, Moves.WICKED_TORQUE, Moves.WIDE_GUARD];

const invalidAssistMoves: Moves[] = [Moves.ASSIST, Moves.BANEFUL_BUNKER, Moves.BEAK_BLAST, Moves.BELCH, Moves.BESTOW, Moves.BOUNCE, Moves.CELEBRATE, Moves.CHATTER, Moves.CIRCLE_THROW, Moves.COPYCAT, Moves.COUNTER, Moves.COVET, Moves.DESTINY_BOND, Moves.DETECT, Moves.DIG, Moves.DIVE, Moves.DRAGON_TAIL, Moves.ENDURE, Moves.FEINT, Moves.FLY, Moves.FOCUS_PUNCH, Moves.FOLLOW_ME, Moves.HELPING_HAND, Moves.HOLD_HANDS, Moves.KINGS_SHIELD, Moves.MAT_BLOCK, Moves.ME_FIRST, Moves.METRONOME, Moves.MIMIC, Moves.MIRROR_COAT, Moves.MIRROR_MOVE, Moves.NATURE_POWER, Moves.PHANTOM_FORCE, Moves.PROTECT, Moves.RAGE_POWDER, Moves.ROAR, Moves.SHADOW_FORCE, Moves.SHELL_TRAP, Moves.SKETCH, Moves.SKY_DROP, Moves.SLEEP_TALK, Moves.SNATCH, Moves.SPIKY_SHIELD, Moves.SPOTLIGHT, Moves.STRUGGLE, Moves.SWITCHEROO, Moves.THIEF, Moves.TRANSFORM, Moves.TRICK, Moves.WHIRLWIND];

const invalidSleepTalkMoves: Moves[] = [Moves.ASSIST, Moves.BELCH, Moves.BEAK_BLAST, Moves.BIDE, Moves.BOUNCE, Moves.COPYCAT, Moves.DIG, Moves.DIVE, Moves.DYNAMAX_CANNON, Moves.FREEZE_SHOCK, Moves.FLY, Moves.FOCUS_PUNCH, Moves.GEOMANCY, Moves.ICE_BURN, Moves.ME_FIRST, Moves.METRONOME, Moves.MIRROR_MOVE, Moves.MIMIC, Moves.PHANTOM_FORCE, Moves.RAZOR_WIND, Moves.SHADOW_FORCE, Moves.SHELL_TRAP, Moves.SKETCH, Moves.SKULL_BASH, Moves.SKY_ATTACK, Moves.SKY_DROP, Moves.SLEEP_TALK, Moves.SOLAR_BLADE, Moves.SOLAR_BEAM, Moves.STRUGGLE, Moves.UPROAR];`

2024-08-27 17:12 UTC, schmidtc1 commented on src/data/move.ts
> +const invalidMetronomeMoves: Moves[] = [
I'll remove the Max/Z moves.

The invalid moves lists have to be separate, as Assist, Sleep Talk, and Metronome each have different invalid moves that they can't use. 

Also I thought it was easier to read the code if you exclude the invalidMoves lists from the class and pass them in under one variable name. Otherwise it looks something like this:

```typescript
// Current
const moves = partyMoveset.filter(m => !this.invalidMoves.includes(m!.moveId) && !m!.getMove().name.endsWith(" (N)")); 

// With invalid moves array in the class
const moves = partyMoveset.filter(m => this.useAssistMoves ? !this.invalidAssistMoves.includes(m!.moveId) : !this.invalidSleepTalkMoves.includes(m!.moveId) && !m!.getMove().name.endsWith(" (N)"));

// Alternative if-statement
let moves: Moves[] = [];
if (this.useAssistMoves) {
   moves = partyMoveset.filter(m => !this.invalidAssistMoves.includes(m!.moveId) && !m!.getMove().name.endsWith(" (N)"));
}
else {
   moves = partyMoveset.filter(m => !this.invalidSleepTalkMoves.includes(m!.moveId) && !m!.getMove().name.endsWith(" (N)"));
}
```

2024-08-28 00:48 UTC, frutescens approved these changes

2024-08-28 00:50 UTC, frutescens reviewed
Do you think it would be helpful to have tests for these moves?

2024-08-28 20:08 UTC, Snailman11 commented
Hello, might be too late, but could you consider adding this as part of your fix? 
https://github.com/pagefaultgames/pokerogue/issues/3874 (Metronome and Copycat targeting allies)

2024-08-28 20:27 UTC, schmidtc1 commented
> Hello, might be too late + disregard for the process, but could you consider adding this as part of your fix? #3874 (Metronome and Copycat targeting allies)

I'll attempt a fix.

2024-08-28 22:18 UTC, schmidtc1 commented
Converted to draft while I work on other aspects of this refactor

2024-08-30 16:19 UTC, Snailman11 commented
#3914 (Multihit hits once when called by a move)

2024-09-06 09:35 UTC, DayKev commented on src/data/move.ts
> +  }
```suggestion

```

2024-09-06 09:36 UTC, DayKev commented
> #3914 (Multihit hits once when called by a move)

Found the cause for this, it's unrelated to the code touched in this PR.

2024-09-06 10:00 UTC, DayKev commented on src/data/move.ts
> +  }
Iirc you can just leave out the constructor if that's all it's doing.

2024-09-09 06:52 UTC, DayKev commented on src/phases/command-phase.ts
> +        const moveId = !useStruggle ? !turnMove ? cursor > -1 ? playerPokemon.getMoveset()[cursor]!.moveId : Moves.NONE : turnMove.move : Moves.STRUGGLE; // TODO: is the bang correct?
Nested ternaries (esp 3+ deep) should be replaced with if/else blocks.

2024-09-16 01:56 UTC, schmidtc1 commented
> > #3914 (Multihit hits once when called by a move)
> 
> Found the cause for this, it's unrelated to the code touched in this PR.
> 
> Specifically, it's a bug in `MovePhase`. It'll be fixed in #3974.

I believe the multihit solution also solves other bugs with Metronome, such as Roar, Rest, etc.

2024-09-17 07:03 UTC, DayKev commented
The multi-hit bug was specifically due to the "hitsLeft" variable being set to 0 incorrectly in #3259 when a move was called via Metronome/etc, I don't think fixing it would impact anything else.
![image](https://github.com/user-attachments/assets/0ae7bab5-37f9-4047-987f-467a005a6593)

2024-09-18 21:44 UTC, schmidtc1 commented
> The multi-hit bug was specifically due to the "hitsLeft" variable being set to 0 incorrectly in #3259 when a move was called via Metronome/etc, I don't think fixing it would impact anything else. ![image](https://private-user-images.githubusercontent.com/34855794/368044298-0ae7bab5-37f9-4047-987f-467a005a6593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2OTU5ODgsIm5iZiI6MTcyNjY5NTY4OCwicGF0aCI6Ii8zNDg1NTc5NC8zNjgwNDQyOTgtMGFlN2JhYjUtMzdmOS00MDQ3LTk4N2YtNDY3YTAwNWE2NTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDIxNDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YmZkZjQ5NjE4OGM1ZDdkMDM1ZmNmODM4ZjdiNThkODNkZTEyMWJmMzNhYjUwNTIzNjc5MTgzNjE1ZmVkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cyj1RoxIXQ5-jU1OqLM7zfmpqsFquMQiuDgoYsNayfw)

I think when I tested roar, the issue arises due to hitsLeft being checked against hitCount to mark the lastHit Boolean as false, causing it's apply function to be filtered out when it's called in MoveEffectPhase

2024-10-02 16:24 UTC, flx-sta commented
@schmidtc1 please make sure to resolve your merge conflicts

2024-10-26 22:34 UTC, DayKev commented on src/data/move.ts
> +        if (user.scene.currentBattle.moveHistory.filter(m => m.targets.includes(user.getBattlerIndex())).length === 0) {
Mirror Move uses the last move used by the target of Mirror Move, bulba's description is wrong and/or worded badly.
- https://www.smogon.com/dex/sm/moves/mirror-move/

2024-10-27 00:53 UTC, schmidtc1 commented on src/data/move.ts
> +        if (user.scene.currentBattle.moveHistory.filter(m => m.targets.includes(user.getBattlerIndex())).length === 0) {
Fixed this in my latest commit.

2024-12-29 06:04 UTC, DayKev commented on src/test/moves/copycat.test.ts
> +    vi.spyOn(game.scene.getPlayerPokemon()!, "randSeedInt").mockReturnValue(Moves.SWORDS_DANCE);
Shouldn't this be mocking the return of `RandomMoveAttr.getMoveOverride()`?
(Same with the other instances in the Metronome tests).

2024-12-29 15:14 UTC, schmidtc1 commented on src/data/move.ts
> +        allies = user.isPlayer() ? user.scene.getPlayerParty() : user.scene.getEnemyParty();
Good catch, will update to filter out the user from getParty functions

2024-12-29 15:24 UTC, schmidtc1 commented on src/data/move.ts
> +export class CallMoveAttr extends OverrideMoveEffectAttr {
Adding docs

2024-12-29 15:24 UTC, schmidtc1 commented on src/data/move.ts
> +export class CopyMoveAttr extends CallMoveAttr {
Adding docs

2024-12-29 15:56 UTC, schmidtc1 commented on src/data/move.ts
> +        allies = user.isPlayer() ? user.scene.getPlayerParty() : user.scene.getEnemyParty();
Test updated in 5b8229c

2024-12-29 16:28 UTC, schmidtc1 commented on src/test/moves/copycat.test.ts
> +    vi.spyOn(game.scene.getPlayerPokemon()!, "randSeedInt").mockReturnValue(Moves.SWORDS_DANCE);
Updated metronome test in f6953e6 and copycat test in 400cdb3

2024-12-29 17:10 UTC, schmidtc1 commented on src/data/move.ts
> + * Invalid moves are indicated by what is passed in to invalidMoves: {@constant invalidAssistMoves} or {@constant invalidSleepTalkMoves}
Added in 499a7eb

2024-12-29 17:11 UTC, schmidtc1 commented on src/data/move.ts
> +   * @returns {Promise<boolean>}
Added in 499a7eb

2024-12-30 07:04 UTC, DayKev commented
Btw does this fix #3874 ?

2024-12-30 07:32 UTC, DayKev approved these changes

2024-12-30 12:11 UTC, schmidtc1 commented
> Btw does this fix #3874 ?

It should, I believe I replace `MoveTarget.NEAR_OTHER` with `MoveTarget.NEAR_ENEMY` to fix that.

2024-12-31 10:36 UTC, DayKev commented on src/data/move.ts
> +export class CallMoveAttr extends OverrideMoveEffectAttr {
```suggestion
class CallMoveAttr extends OverrideMoveEffectAttr {
```
Just noticed, this isn't imported to any other files so it doesn't need to be exported.

2024-12-31 10:36 UTC, DayKev submitted a review, later dismissed

2025-01-14 23:13 UTC, DayKev commented on src/battle.ts
> +
```suggestion
```

2025-01-14 23:13 UTC, DayKev approved these changes

2025-01-14 23:23 UTC, DayKev approved these changes

2025-01-14 23:26 UTC, merged