[Misc] Eternatus Dialogue reflects # of Classic Sessions Played
pagefaultgames/pokerogue pull request #3387
Opened 2024-08-06 18:43 UTC by frutescens

## What are the changes?
Before, Eternatus would use the same number of cycles 5643853 in its dialogue. Now, the number of cycles is accurately updated to the player's number of classic sessions played.  

## Why am I doing these changes?
I just thought it would be neat. 

## What did change?
phases.ts - Calculation of number of cycles + determination of any unique suffixes used by English

### Screenshots/Videos
36 classic sessions played --> 5653889
English + Non-Localized Languages (It + Es)
![image](https://github.com/user-attachments/assets/44f1aa16-8ae9-4091-a09f-cf1c8962931e)

German
![image](https://github.com/user-attachments/assets/c6a9f230-b8bf-4d83-9e4c-b92a7216b5e7)

French
![image](https://github.com/user-attachments/assets/1c4cc649-86df-4273-b5c2-4a84cfd377f1)

Portuguese
![image](https://github.com/user-attachments/assets/3a049325-5c1f-4b6c-91c1-07a4002beef3)

Korean
![image](https://github.com/user-attachments/assets/343cdad4-ebff-47e3-a009-ea570f8450bc)

Simplified Chinese 
![image](https://github.com/user-attachments/assets/71d90b91-54c0-413c-83aa-9586f64fe4b5)

Traditional Chinese
![image](https://github.com/user-attachments/assets/6b584440-9166-4ef3-a95f-2d3dc75db659)

## How to test the changes?
Set wave to 200 in overrides.ts and start a new game in classic mode.

Please note that number.toLocaleString() takes the device's language, not the language chosen in the settings. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-06 18:45 UTC, Tempo-anon commented
Soulful, but need to make sure this works for all languages

2024-08-06 18:58 UTC, frutescens commented
Yes, checked for any edge cases but it seems good.

2024-08-06 19:12 UTC, CodeTappert commented
Looks good for german!

2024-08-07 00:26 UTC, Adri1 requested changes
Don't forgot to also add {{cycleCount} to the line 5082 for French, and the line 4823 for Brazilian Portugese, as for this dialogue, these both languages uses the functionality to have this dialogue twice: one adapted to male avatar and the other adapted to female avatar

2024-08-07 00:39 UTC, Adri1 commented
And i just noticed that on line 1135 of phases.ts, only "PGM" is specified ("M" standing for "male"), so I guess you need to also adapt it for the female version (PGF). Idk how it works, I just warn just in case it dosen't work for female versions of dialogues as it is
[phases.ts](https://github.com/pagefaultgames/pokerogue/pull/3387/files#diff-7bfd86f885f7bd68a0b3b3a290cbfe482a6338ac569b6a7418716a863006537a)

2024-08-07 00:48 UTC, Adri1 approved these changes

2024-08-07 15:19 UTC, Adri1 reviewed
French typos corrections

2024-08-07 15:19 UTC, Adri1 commented on src/locales/fr/dialogue.ts
>                 $Tu a été appelé ici parce que t’y est déjà venu.\nUn nombre inimaginable de fois.
```suggestion
               $Tu as été appelé ici parce que t’y es déjà venu.\nUn nombre inimaginable de fois.
```

2024-08-07 15:19 UTC, Adri1 commented on src/locales/fr/dialogue.ts
>                 $Tu a été appelée ici parce que t’y est déjà venue.\nUn nombre inimaginable de fois.
```suggestion
               $Tu as été appelée ici parce que t’y es déjà venue.\nUn nombre inimaginable de fois.
```

2024-08-07 15:31 UTC, DayKev commented on src/phases.ts
> +        const ordinalIndex = (ordinalUse.includes(i18next.resolvedLanguage)) ? ["st","nd","rd"][((count+90)%100-10)%10-1]||"th" : "";
```suggestion
        const ordinalIndex = (ordinalUse.includes(i18next.resolvedLanguage)) ? ["st","nd","rd"][((count+90)%100-10)%10-1] || "th" : "";
```
Also it's been noted that there should be a comment explaining what's going on here.

2024-08-07 15:34 UTC, DayKev commented on src/phases.ts
> +        const encounterDialogue = i18next.t(`${(this.scene.gameData.gender === PlayerGender.FEMALE)?"PGF":"PGM"}battleSpecDialogue:encounter`, {cycleCount: cycleCount});
```suggestion
        const cycleCount = count.toLocaleString() + ordinalIndex;
        const encounterDialogue = i18next.t(`${(this.scene.gameData.gender === PlayerGender.FEMALE) ? "PGF" : "PGM"}battleSpecDialogue:encounter`, {cycleCount: cycleCount});
```

2024-08-07 15:36 UTC, DayKev commented on src/phases.ts
> +        const ordinalIndex = (ordinalUse.includes(i18next.resolvedLanguage)) ? ["st","nd","rd"][((count+90)%100-10)%10-1] || "th" : "";
```suggestion
        const ordinalIndex = (ordinalUse.includes(i18next.resolvedLanguage)) ? ["st", "nd", "rd"][((count + 90) % 100 - 10) % 10 - 1] || "th" : "";
```
Sorry, messed up the first comment/suggestion and some of the changes got left out.

2024-08-07 22:36 UTC, EnochG1 approved these changes
Korean is Okay

2024-08-08 00:41 UTC, Tempo-anon commented
For Italian

“To be precise, this is in fact your {{cycleCount}} cycle” becomes “Precisamente, questo per te è il ciclo n.{{cycleCount}}”

2024-08-08 00:44 UTC, merged