[Enhancement/Item] Add Achievement to Unlock Eviolite
pagefaultgames/pokerogue pull request #3390
Opened 2024-08-06 22:00 UTC by xsn34kzx

## What are the changes?

Adds a new achievement that, upon satisfying its requirement (completing Classic Mode with at least one Pokemon that can still evolve), introduces `Eviolite` into the item pool for future runs; essentially, this introduces `Eviolite` into the game officially.

## Why am I doing these changes?

When `Eviolite` was put into the game (#2161), it was purposefully left out of the general item pool to be obtainable via other means. This PR follows up by actually introducing `Eviolite` as a usable item within the general item pool with an achievement as a "barrier of entry".

## What did change?

### Screenshots/Videos

#### Achievement Notification

<img width="338" alt="achievementGet" src="https://github.com/user-attachments/assets/48038d3d-5b55-45f6-ae6d-e8c5bbc3f50c">

#### Achievement Menu after Completion

<img width="1215" alt="achievementScreen" src="https://github.com/user-attachments/assets/e45c1d16-c19c-47b5-bd7a-4fe3932af71e">

## How to test the changes?

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-06 23:42 UTC, CodeTappert commented on src/locales/de/achv.ts
> +    description: "Beat the game in Classic Mode with at least one unevolved party member."
```suggestion
    description: "Beende den klassischen Modus erfolgreich mit mindestens einem nicht entwickeltem Pokémon in deinem Team"
```

2024-08-06 23:42 UTC, CodeTappert commented on src/locales/de/achv.ts
> +    name: "Bring Your Child To Work Day",
```suggestion
    name: "'Bringe dein Kind zur Arbeit'-Tag" ,
```

2024-08-06 23:43 UTC, damocleas approved these changes

2024-08-07 00:24 UTC, Tempo-anon requested changes
Gonna place a blocker on this for now until we get scrolling in the achievement screen

2024-08-07 01:13 UTC, returntoice commented on src/locales/ko/achv.ts
> +  },
```suggestion
    name: "우리집 꿈나무",
    description: "최종 진화형이 아닌 포켓몬을 데리고 클래식 모드 클리어."
  },
```

2024-08-07 06:01 UTC, EnochG1 commented
@xsn34kzx 
From now Japanese is added in beta.
Could you merge latest beta and add Japanese locale files? 🙏

2024-08-07 07:25 UTC, CodeTappert approved these changes

2024-08-07 10:33 UTC, Adri1 reviewed
Added French, but could you also add it to the female achivments?

2024-08-07 10:33 UTC, Adri1 commented on src/locales/fr/achv.ts
> +    description: "Beat the game in Classic Mode with at least one unevolved party member."
```suggestion
    name: "Stagiaire de 3e",
    description: "Terminer le mode Classique avec au moins un Pokémon non-évolué dans l’équipe."
```

2024-08-07 14:50 UTC, josericardo-fo commented on src/locales/pt_BR/achv.ts
> +  },
```suggestion
  "UNEVOLVED_CLASSIC_VICTORY": {
    name: "Tire as Crianças da Sala",
    description: "Vença o jogo no Modo Clássico com pelo menos um membro da equipe não evoluído.."
  },
```

2024-08-07 15:13 UTC, Adri1 commented on src/locales/fr/achv.ts
> +    description: "Beat the game in Classic Mode with at least one unevolved party member."
```suggestion
    name: "Le stagiaire de 3e",
    description: "Terminer le mode Classique avec au moins un Pokémon non-évolué dans l’équipe."
```

2024-08-08 00:07 UTC, merged