Implement Incinerate
pagefaultgames/pokerogue pull request #341
Opened 2024-04-29 15:33 UTC by Fractaos

A proposition of implementation of the `Incinerate` effect.

Maybe a more generic `Attr` could be used here, I was not totally sure, don't hesitate to make suggestions.
Also, maybe using the `removeModifier` is not the proper way to do this, so again feel free to tell me if there is a better method. (I'm saying this because of the `StealHeldItemChanceAttr` seems to use a more complex process to do so.)

Another point, not directly correlated to this feature: I've seen that the `RemoveHeldItemAttr` seems not used (and seems to have a relatively close purpose to `StealHeldItemChanceAttr`). Maybe it should be removed?

2024-04-29 16:50 UTC, lucfd reviewed
Incinerate shouldn't be able to destroy berries being held by a Pokemon with Sticky Hold

2024-04-29 16:59 UTC, Fractaos commented on src/data/move.ts
> +      const couldRemoveBerry = target.scene.removeModifier(removedBerry, true);
Good point, it was not indeed so I'll update it 👍

2024-04-29 17:37 UTC, Fractaos commented on src/data/move.ts
> +      const couldRemoveBerry = target.scene.removeModifier(removedBerry, true);
[Updated](https://github.com/pagefaultgames/pokerogue/pull/341/commits/8ef29d13dd0c54b3a7bbf33e6e95a83694756cb0) with your feedback ✔️

2024-04-29 17:37 UTC, Fractaos commented
> Incinerate shouldn't be able to destroy berries being held by a Pokemon with Sticky Hold

@lucfd Behavior added ✔️

2024-04-30 19:18 UTC, lucfd requested changes

2024-04-30 19:18 UTC, lucfd commented on src/data/move.ts
> +      if (target.hasAbility(Abilities.STICKY_HOLD)) {
Checking if Sticky Hold's attribute `BlockItemTheftAbAttr` is being applied would be a cleaner approach. This would also bake in the proper interactions with ability ignoring effects such as Mold Breaker / Neutralizing Gas / Photon Geyser

2024-04-30 19:19 UTC, lucfd commented
Aside from the ability interactions LGTM

2024-05-01 10:31 UTC, Fractaos commented on src/data/move.ts
> +      if (target.hasAbility(Abilities.STICKY_HOLD)) {
Indeed, was not sure how it should be done, thanks for your help!

I modified it [here](https://github.com/pagefaultgames/pokerogue/pull/341/commits/90103af925baf1b57db0388fcb444df07c6164fe), I think it should be good this way unless I'm missing something else.

I've also moved down the abitily check to avoid having the pop-up if the target doesn't have any berry to burn in the first place, it seems better this way.

2024-05-19 13:50 UTC, bennybroseph commented
Closing this due to inactivity. Feel free to make a new request if interest is reignited

2024-05-19 13:50 UTC, closed without merging

2024-05-21 11:29 UTC, Fractaos commented
Hey, hello @bennybroseph, this PR was actually waiting for reviews on my end. I thought it was needing actual core team approval before getting possibly merged.

Do I miss something regarding the expected process here?