[MOVE] Some more implementation for Tera Blast
pagefaultgames/pokerogue pull request #3469
Opened 2024-08-09 22:08 UTC by cgyu7

## What are the changes the user will see?
Tera blast now changes the type of damage dealt as the same type of the tera type applied to the mon. Tera blast also accounts for if the user is terastalized into Stellar type with increased base damage and dropping ATK/SPATK by one stage.

## Why am I making these changes?
Tera blast is a commonly offered TM and loses a lot of utility due to the fact it's currently only possible to do Normal type damage. Also gives more incentive to pick up the tera orb, tera shards, and teach tera blast more often.

## What are the changes from a developer perspective?
To the TeraBlastCatgeoryAttr added a check for if the Pokemon is terastalized and if so, change tera blast's dmg to that of the tera type. Added a check for if the user is tera'd into the Stellar type, and if so make the base power of tera blast 200 instead of 100 to account for the missing 2x dmg by Stellar type moves on all types. Also included a check for the move being specifically tera blast so the class can be also used with tera starstorm.

Added to the move a ATK/SPATK drop by one stage after if the user is tera'd into Stellar type. 

### Screenshots/Videos
![terablaststellar](https://github.com/user-attachments/assets/459b1e20-eb81-483f-b368-89bbd954e45a)

## How to test the changes?
Use tera blast while terastalized

## Checklist
- [x ] **I'm using `beta` as my base branch**
- [x ] There is no overlap with another PR?
- [x ] The PR is self-contained and cannot be split into smaller PRs?
- [x ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I add placeholders for them in locales?
- [x ] Have I tested the changes (manually)?
    - [x ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-10 13:44 UTC, torranx commented on src/data/move.ts
> +    move.power = 80;
I think doing this will globally update the move's power. If you check `calculateBattlePower()` and other power manipulations, they are using Utils.NumberHolder

2024-08-10 15:46 UTC, cgyu7 commented on src/data/move.ts
> +    move.power = 80;
I considered using 
>const power = args[0] as Utils.NumberHolder
for calculating whether the move power will be 80 or 100, but line 3751 is already using Utils.NumberHolder and I thought and some others added that it might cause an issue to use it again in the same class. I could also just make a separate class for the damage calc if it'll cause issues with the phy/special dmg calc.

Another idea is treating the calculation similarly to how magnitude is calculated by having [80, 200] and have it choose one or the other based on the mon's tera type.

2024-08-10 16:25 UTC, cgyu7 commented
I've split the damage and move type calculations into two new classes, so that they're better organized and each catered to doing one specific calc instead of overloading one class with multiple

2024-08-11 21:05 UTC, DayKev requested changes
Seems good, just needs tests and tsdocs.

2024-08-11 21:05 UTC, DayKev commented on src/data/move.ts
> +    const category = (args[0] as Utils.IntegerHolder);
```suggestion
    const category = (args[0] as Utils.IntegerHolder);
```

2024-08-11 21:05 UTC, DayKev commented on src/data/move.ts
> +      .attr(StatChangeAttr, [ BattleStat.ATK, BattleStat.SPATK, ], -1, true, (user, target, move) => user.isTerastallized() && user.isOfType(Type.STELLAR))
```suggestion
      .attr(StatChangeAttr, [ BattleStat.ATK, BattleStat.SPATK ], -1, true, (user, target, move) => user.isTerastallized() && user.isOfType(Type.STELLAR))
```

2024-08-12 06:27 UTC, cgyu7 commented
> Seems good, just needs tests and tsdocs.

What tests do I need to do? And what do I do for the tsdocs?

2024-08-13 00:18 UTC, torranx commented
> What tests do I need to do? And what do I do for the tsdocs?

automated tests for Tera Blast's supposed behavior, refer to existing tests in the codebase if you don't know where to start. tsdocs/jsdocs -> document your classes

2024-08-13 00:53 UTC, DayKev commented
> > Seems good, just needs tests and tsdocs.
> 
> What tests do I need to do? And what do I do for the tsdocs?

As an example for docs, I'll use Destiny Bond's move attr:
```ts
/**
 * Applies {@linkcode BattlerTagType.DESTINY_BOND} to the user.
 *
 * @extends MoveEffectAttr
 */
export class DestinyBondAttr extends MoveEffectAttr {
  constructor() {
    super(true, MoveEffectTrigger.PRE_APPLY);
  }

  /**
   * Applies {@linkcode BattlerTagType.DESTINY_BOND} to the user.
   * @param user {@linkcode Pokemon} that is having the tag applied to.
   * @param target {@linkcode Pokemon} N/A
   * @param move {@linkcode Move} {@linkcode Move.DESTINY_BOND}
   * @param {any[]} args N/A
   * @returns true
   */
  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
    user.scene.queueMessage(`${i18next.t("moveTriggers:tryingToTakeFoeDown", {pokemonName: getPokemonNameWithAffix(user)})}`);
    user.addTag(BattlerTagType.DESTINY_BOND, undefined, move.id, user.id);
    return true;
  }
}
```
The text between the `/** ... */` is tsdocs. If you use VSCode (or the opensource version) it should have functionality to format these automatically for you (just start typing `/**` above the object you want to add comments for and hit enter). You put a description of what the thing you're commenting on does, and then below that you put more specific descriptions for things like function parameters. Don't worry if you don't get the formatting perfect, we can suggest fixes for that afterward.

2024-08-14 07:31 UTC, DayKev requested changes
Now you need tests to confirm the move works as expected. For Tera Blast, there should probably be:
* "changes type to match user's tera type"
* "increases power if user is Stellar tera type"
* "uses the higher stat of the user's Atk and SpAtk for damage calculation"
* "causes stat drops if user is Stellar tera type"

Here's a template you can copy to start making the test with. Look at the other tests for examples when you don't know what to do (moves/abilities that do similar things to what you're testing for are good places to start, ie: the Battery ability modifies the power of a move).
```ts
import { allMoves } from "#app/data/move";
import GameManager from "#test/utils/gameManager";
import { Moves } from "#enums/moves";
import { Species } from "#enums/species";
import Phaser from "phaser";
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { Abilities } from "#app/enums/abilities.js";
import { SPLASH_ONLY } from "../utils/testUtils";
import { Type } from "#app/data/type.js";

describe("Moves - Tera Blast", () => {
  let phaserGame: Phaser.Game;
  let game: GameManager;
  const moveToCheck = allMoves[Moves.TERA_BLAST];

  beforeAll(() => {
    phaserGame = new Phaser.Game({
      type: Phaser.HEADLESS,
    });
  });

  afterEach(() => {
    game.phaseInterceptor.restoreOg();
  });

  beforeEach(() => {
    game = new GameManager(phaserGame);

    game.override
      .battleType("single")
      .disableCrits()
      .starterSpecies(Species.FEEBAS)
      .moveset([Moves.TERA_BLAST])
      .ability(Abilities.BALL_FETCH)
      .startingHeldItems([{name: "TERA_SHARD", type: Type.FIRE}])
      .enemySpecies(Species.MAGIKARP)
      .enemyMoveset(SPLASH_ONLY)
      .enemyAbility(Abilities.BALL_FETCH)
      .enemyLevel(20);

    vi.spyOn(moveToCheck, "calculateBattlePower");
  });

  it("changes type to match user's tera type", async() => {
    await game.startBattle();

    // test goes here
    expect("test").toBe("test");
  }, 20000);

  it("increases power if user is Stellar tera type", async() => {
    game.override.startingHeldItems([{name: "TERA_SHARD", type: Type.STELLAR}]);
    await game.startBattle();

    // test goes here
  }, 20000);

  it("uses the higher stat of the user's Atk and SpAtk for damage calculation", async() => {
    await game.startBattle();

    // test goes here
  }, 20000);

  it("causes stat drops if user is Stellar tera type", async() => {
    game.override.startingHeldItems([{name: "TERA_SHARD", type: Type.STELLAR}]);
    await game.startBattle();

    // test goes here
  }, 20000);
});

```

2024-08-14 07:31 UTC, DayKev commented on src/data/move.ts
> + * @extends VariablePowerAttr
```suggestion
/**
 * Increases the power of Tera Blast if the user is Terastallized into Stellar type
 * @extends VariablePowerAttr
```

2024-08-14 07:31 UTC, DayKev commented on src/data/move.ts
> + * @extends VariableMoveTypeAttr
```suggestion
/**
 * Changes the type of Tera Blast to match the user's tera type
 * @extends VariableMoveTypeAttr
```

2024-08-14 07:31 UTC, DayKev commented on src/data/move.ts
> +      //200 instead of 100 to reflect lack of stellar being 2x dmg on any type
```suggestion
      //200 instead of 100 to reflect lack of stellar being 2x dmg on any type
      power.value = 200;
```

2024-08-14 15:26 UTC, cgyu7 commented on src/data/move.ts
> +      //200 instead of 100 to reflect lack of stellar being 2x dmg on any type
tsdoc update

2024-08-15 09:18 UTC, DayKev requested changes
Well you got them started, but the tests weren't finished. Amusingly in the course of finishing the tests I discovered a bug.

2024-08-15 16:40 UTC, cgyu7 commented on src/test/moves/tera_blast.test.ts
> +    expect(moveToCheck.calculateBattlePower).toBe((basePower + stellarTypeDmgBonus) * stellarTypeMultiplier);
I see. I was under the assumption that `doAttack()` would result in the attack and its effects following through after starting the battle. So the function itself only applies the attack when the game phase is in a place where the attack can happen? (in this case I assume `setTurnOrder()` allows for the attack to happen and `phaseInterceptor` to specifically trigger the move effect)

2024-08-15 16:43 UTC, cgyu7 commented on src/test/moves/tera_blast.test.ts
> +    expect(moveToCheck.type).toBe(Type.FIRE);
Would this be the best way to test moves that can change types? Or is there another way to directly check the move's type after the move effect is activated that isn't just checking type effectiveness against an enemy?

2024-08-15 16:49 UTC, cgyu7 commented on src/test/moves/tera_blast.test.ts
> +
In theory for this case, the test for the move being physical is the fact that it should pass the check of toxic debris being procced after the hit? And currently the issue is that it doesn't proc due to the bug? In this case, is it like the test for the move type where there's not a direct test for the move's category after move effect proc?

2024-08-15 16:59 UTC, cgyu7 commented
Thank you for all the help with the test. This is my first time contributing to PokeRogue so I'm still relatively unfamiliar with the code and test. Is there anything else I need to do still other than commit the changes to the test?

2024-08-15 20:52 UTC, DayKev commented on src/test/moves/tera_blast.test.ts
> +    expect(moveToCheck.calculateBattlePower).toBe((basePower + stellarTypeDmgBonus) * stellarTypeMultiplier);
I'm probably gonna see about renaming `doAttack()` to something like `prepareAttack()` to prevent this confusion in the future.

`setTurnOrder()` is used when we want to force specific Pokémon to move first/second, it's only needed sometimes (it's probably not necessary here but it allows me to shorten the time it takes for the test to complete because it doesn't matter if the opponent Pokémon attacks or not, so I can just make the player Pokémon move first, check the relevant conditions, and then end the test).

`phaseInterceptor.to()` tells the game to run like normal until it reaches the specific phase and then the rest of the test code continues to run at that point. Generally you'd use either "MoveEffectPhase" (this is where damage and effects happen for the current move being executed) or "TurnEndPhase" (which is, unsurprisingly, the end of the turn) depending on what needs to be checked.

2024-08-15 20:54 UTC, DayKev commented on src/test/moves/tera_blast.test.ts
> +    expect(moveToCheck.type).toBe(Type.FIRE);
Unfortunately in this case the internals aren't really possible to `spyOn()`/etc due to the way the code is written, so it's necessary to instead check something else as a proxy (like if the move is super effective, which should theoretically only happen in this test setup if the type of Tera Blast properly changes to Fighting type, since that's the only type Normal is weak to and is the tera type of the player Pokémon in this test).

2024-08-15 20:56 UTC, DayKev commented on src/test/moves/tera_blast.test.ts
> +
Yeah, there's no way to directly look at the category of the move being used, so we have to again test something that *should* happen if the move is working properly. In this case something other than the move being tested is broken which prevents us from testing this attribute properly, so until that's fixed the test is skipped.

2024-08-15 20:57 UTC, DayKev commented
> Thank you for all the help with the test. This is my first time contributing to PokeRogue so I'm still relatively unfamiliar with the code and test. Is there anything else I need to do still other than commit the changes to the test?

With the test changes, everything should be done. After the next beta -> main merge happening in a couple days (if nothing breaks) then feature PRs like this one will start being evaluated/merged again, and it should be good to go (unless someone else notices a problem I missed).

2024-08-16 05:42 UTC, DayKev approved these changes

2024-08-16 05:59 UTC, torranx approved these changes

2024-08-16 06:57 UTC, innerthunder approved these changes

2024-08-21 23:27 UTC, frutescens approved these changes

2024-08-21 23:27 UTC, innerthunder approved these changes

2024-08-21 23:33 UTC, merged

2024-09-08 22:15 UTC, podarsmarty commented
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/5ab4b7bb-4b1d-4c74-98a3-7b2b66c75e5c">

hmm was playing and noticed an error regarding tera-blast.json not being available. had the offline client redownload files but it still isn't there. is this related to the recent changes?