August 2024 Variant Update
pagefaultgames/pokerogue pull request #3470
Opened 2024-08-09 22:43 UTC by brain-frog

## What are the changes?

August 2024 Variant Update

## Why am I doing these changes?

Supposed to

## What did change?

771 Files :)

### Screenshots/Videos

## How to test the changes?

Play :)

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-10 05:25 UTC, Tempo-anon approved these changes
771 files changed LGTM

2024-08-10 08:46 UTC, CodeTappert commented
Give me Arcanine Variants or i riot!

Not approved! /s

2024-08-10 08:46 UTC, CodeTappert approved these changes

2024-08-10 13:41 UTC, torranx approved these changes
108,494 lines changed === lgtm

2024-08-12 12:11 UTC, flx-sta approved these changes
images + jsons seem to work all good.
I'm just a bit confused that we end on an uneven number. Isn't it 1 image + 1 json?

2024-08-13 03:16 UTC, Fontbane requested changes

2024-08-13 03:16 UTC, Fontbane commented on public/images/pokemon/variant/back/618_2.png
This is wrong

2024-08-13 21:08 UTC, Fontbane commented on public/images/pokemon/variant/back/618_2.png
Ok, I looked into it, all the variants that have separate image files have base fixes, meaning those should just be regular palette swaps. The only outliers that should have a separate sprite for their variants are Alomomola and Gigalith. Something probably went wrong with the script that's supposed to generate these files. But if the variants work, they work.

2024-08-13 21:30 UTC, merged