[QoL] Add arrows in the Stats screen to show it is scrollable
pagefaultgames/pokerogue pull request #3489
Opened 2024-08-11 14:00 UTC by MokaStitcher

## What are the changes?
Add animated arrows at the top of bottom of the Stats screen, and fix the windows broken look

## Why am I doing these changes?
- There is currently no indication that there are more stats to see than the ones shown on screen when opening the menu
- Since PR #2525 made changes to the way window masking worked, the windows composing the stats screen were looking wrong (see screenshots below)

## What did change?
- Add arrows to show if we can scroll up/down the list
- Fix the windows look
- Change the font color for legacy theme as the stats were showing white on white before

### Screenshots/Videos
Before (current beta/main): 
<img width="799" alt="_stats_before" src="https://github.com/user-attachments/assets/49cf3505-10bc-46f9-a550-519f1b66bc97">

(For reference, here's how it looked before PR #2525):
<img width="1179" alt="_stats_before_before" src="https://github.com/user-attachments/assets/dfb7637a-a1a3-4ae7-88be-2681b9c490ca">

After: 

https://github.com/user-attachments/assets/c2acb07b-f404-47e9-a11f-473f66e4adb3

Before, legacy theme:
<img width="803" alt="_legacy_before" src="https://github.com/user-attachments/assets/01cf6572-a531-4aaf-9cce-bfa041dcff6b">

After, legacy theme:
<img width="800" alt="_legacy_after" src="https://github.com/user-attachments/assets/984475a9-404b-49cc-8928-633cf1cfcf1b">

## How to test the changes?
* Open the stats screen, move up/down and make sure the arrows get shown when needed

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-08-11 15:57 UTC, ben-lear commented on src/ui/game-stats-ui-handler.ts
> +    if (this.scene.uiTheme) {
can we be explicit about which `uiTheme` it's looking for (legacy)

2024-08-11 16:00 UTC, ben-lear commented on src/ui/game-stats-ui-handler.ts
> +    if (this.scene.uiTheme) {
can we be explicit about which `uiTheme` it's looking for (legacy)

2024-08-11 16:00 UTC, ben-lear commented on src/ui/game-stats-ui-handler.ts
> +    this.arrowUp = this.scene.add.sprite(statsBgWidth, headerBg.height + (this.scene.uiTheme? 7 : 3), "prompt");
can we be explicit about which `uiTheme` it's looking for (legacy)

2024-08-11 16:00 UTC, ben-lear commented on src/ui/text.ts
> +    if (uiTheme) {
can we be explicit about which `uiTheme` it's looking for (legacy)

2024-08-11 16:00 UTC, ben-lear commented
other than the nits, code and UI lgtm

2024-08-11 16:12 UTC, MokaStitcher commented on src/ui/text.ts
> +    if (uiTheme) {
I agree that the check is very unclear... For this one I followed the way it was done in the rest of the function
I can definitely update it for the whole function/file while I'm at it though, should i just do that so it's consistent?

2024-08-11 16:24 UTC, MokaStitcher commented on src/ui/text.ts
> +    if (uiTheme) {
done, did the same for the rest of the function for consistency

2024-08-11 18:06 UTC, ben-lear approved these changes

2024-08-11 19:10 UTC, frutescens approved these changes
Bless, I'm glad those uneven windows were fixed. It looks good to me.

2024-08-11 20:14 UTC, torranx approved these changes
looks good to me, 1 nit added

2024-08-11 20:14 UTC, torranx commented on src/ui/text.ts
> +    if (uiTheme === UiTheme.LEGACY) {
nit: store `uiTheme === UiTheme.LEGACY` in a constant variable and reuse

2024-08-11 20:44 UTC, MokaStitcher commented on src/ui/text.ts
> +    if (uiTheme === UiTheme.LEGACY) {
you're right, done!

2024-08-24 17:56 UTC, frutescens commented on src/ui/game-stats-ui-handler.ts
> +import { UiTheme } from "#app/enums/ui-theme.js";
```suggestion
import { UiTheme } from "#app/enums/ui-theme";
```

2024-08-24 17:58 UTC, frutescens requested changes
Tested. It looks good, but I added some requests for changes. I'll send it over to the lead dev. for final review after they're implemented.

![image](https://github.com/user-attachments/assets/5c46f2b3-cf1f-46c4-a44d-e200628b8cda)

https://github.com/user-attachments/assets/4ead913d-1af7-43a9-a735-97426dd2a083

2024-08-24 17:58 UTC, frutescens commented on src/ui/game-stats-ui-handler.ts
> +  updateArrows(): void {
Could you write a sentence or two for documentation purposes?

2024-08-24 17:58 UTC, frutescens commented on src/ui/text.ts
> +  const legacyTheme = uiTheme === UiTheme.LEGACY;
```suggestion
  const isLegacyTheme = uiTheme === UiTheme.LEGACY;
```

2024-08-24 20:39 UTC, MokaStitcher commented on src/ui/text.ts
> +  const legacyTheme = uiTheme === UiTheme.LEGACY;
all should be good now, thank you!

2024-08-24 20:55 UTC, frutescens approved these changes

2024-08-24 22:56 UTC, merged