[Bug] Fix daily run generated movesets
pagefaultgames/pokerogue pull request #3519
Opened 2024-08-12 22:56 UTC by DayKev

## What are the changes?
Daily runs work again.

## Why am I doing these changes?
![image](https://github.com/user-attachments/assets/056157cc-6c5a-4c1c-8c55-256b198e924f)

## What did change?
A semi-random moveset is generated for player Pokémon in daily run mode (the same function that NPC trainers use for their Pokémon).

### Screenshots/Videos
![image](https://github.com/user-attachments/assets/f0e4e402-c7ea-4a22-b48c-9e67723b305d)

## How to test the changes?
Start a new daily run and check the movesets of your Pokémon.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - [x] Have I provided screenshots/videos of the changes?

2024-08-12 22:57 UTC, innerthunder approved these changes

2024-08-12 23:03 UTC, torranx approved these changes

2024-08-13 14:43 UTC, flx-sta requested changes
lgtm 🚀 

I've added some automated tests to cover this issue in the future:
https://github.com/DayKev/pokerogue/pull/3
<sub>there was some restructuring necessary due to daily-mode not being properly supported yet</sub>

2024-08-13 19:37 UTC, frutescens approved these changes

2024-08-13 20:31 UTC, f-fsantos commented
Pending the closure of the PR from @flx-sta

2024-08-13 20:48 UTC, merged