Implement Terrain Pulse
pagefaultgames/pokerogue pull request #352
Opened 2024-04-30 06:44 UTC by ReneGV

Similar to https://github.com/pagefaultgames/pokerogue/pull/73 implement missing effects of Terrain Pulse.

- Type should change depending on the current field terrain. 
- Increase base power from 50 to 100 if the is a terrain.

2024-04-30 16:19 UTC, Flashfyre requested changes

2024-04-30 16:19 UTC, Flashfyre commented on src/data/move.ts
> +      .attr(MovePowerMultiplierAttr, (user, target, move) => (user.scene.arena.terrain.terrainType != TerrainType.NONE)  ? 2 : 1)
Will this error if terrain is null? I believe terrainType will never be NONE, but instead terrain will be null.

2024-05-01 08:11 UTC, ReneGV commented
Implemented suggested code review changes.

2024-05-19 13:43 UTC, bennybroseph commented
Already implemented #235

2024-05-19 13:43 UTC, closed without merging