[Draft][Challenge] Inverse battle challenge
pagefaultgames/pokerogue pull request #3525
Opened 2024-08-13 04:56 UTC by KimJeongSun

## What are the changes?

## Why am I doing these changes?

## What did change?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-13 07:48 UTC, flx-sta commented
If you refactor code please also make sure to eliminate any outstanding `integer` and replace them with `number` (the real type, not some fake name)

2024-08-13 08:07 UTC, KimJeongSun commented
updated! but there are army of left `integer` on everywhere...

2024-08-13 08:09 UTC, flx-sta commented
> updated! but there are army of left `integer` on everywhere...

Yeah. But it's just an alias for `number` so we don't have to force it

2024-08-13 09:53 UTC, flx-sta commented
I think the name of the challenge should also be a bit more specific.
`inverse battle challenge` sounds a bit like I'd be fighting on the enemy side (top).
I would have expected something like `Inverse types challenge`

2024-08-13 10:01 UTC, KimJeongSun commented
Hmm, well, I didn't come up with this name, so I'm not sure.
https://bulbapedia.bulbagarden.net/wiki/Inverse_Battle

2024-08-13 10:25 UTC, flx-sta commented
> Hmm, well, I didn't come up with this name, so I'm not sure. https://bulbapedia.bulbagarden.net/wiki/Inverse_Battle

never mind then

2024-08-13 18:23 UTC, Adri1 commented
Possible to inclue other locales placeholders? 🙏

2024-08-14 01:06 UTC, KimJeongSun commented
@Adri1 It's still a draft PR, but thank you for taking an interest and leaving a comment.

Hmm, originally I was planning to finish developing the features needed for the first release and add them before marking it as ready to review, but if you prefer, we can proceed now.

First, I need to add some content regarding the English translations. ( After consulting with the balance team, we decided that for the first release, even if the existing challenges are combined with the inverse battle challenge, the existing challenge achievements will not be unlocked. We plan to specify this in the challenge description. )
After updating, I will inform the translation team and request their feedback and translations.

2024-08-17 08:58 UTC, CodeTappert commented on src/locales/de/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
```suggestion
    name: "Spieglein, Spieglein an der Wand",
    description: "Schließe die 'Umkehrkampf' Herausforderung ab"
```

2024-08-17 09:00 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
```suggestion
  "inverseBattle": {
    "name": "Umkehrkampf",
    "desc": "Die Typen-Effektivität wird umgekehrt, und kein Typ ist gegen einen anderen Typ immun. Deaktiviert die Erfolge anderer Herausforderungen.",
    "value.0": "Aus",
    "value.1": "An",
```

2024-08-17 09:00 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
This could be to long. Please check!

2024-08-17 09:00 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
Also @flx-sta please check my translation

2024-08-17 09:03 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
<img width="1689" alt="image" src="https://github.com/user-attachments/assets/b7993f2b-71ed-48d1-87bc-24d763e93d27">

do i need to change font size?

2024-08-17 09:04 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
Either that or i can make it shorter by using bullet points

2024-08-17 09:06 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
I think the font looks unnecessarily large in other languages as well. Let me adjust this first.

2024-08-17 09:07 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
![image](https://github.com/user-attachments/assets/3072a509-5fb3-49bd-92a6-fd75fda7ac7e)

2024-08-17 09:07 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
i will make a suggestion for the bullet points. Its good enough imo

2024-08-17 09:09 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
> I think the font looks unnecessarily large in other languages as well. Let me adjust this first.

Ok tell me if you need the bullet point thing

2024-08-17 09:11 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
<img width="1689" alt="Screenshot 2024-08-17 at 6 09 43 PM" src="https://github.com/user-attachments/assets/bb201bf0-f7e5-4eeb-bc70-5ed77f4abb9b">
<img width="1689" alt="Screenshot 2024-08-17 at 6 11 05 PM" src="https://github.com/user-attachments/assets/c592b650-963f-4a7a-b076-4ecab689f321">

i think 2nd one looks simple, but 1st one looks more unified with other desc

2024-08-17 09:12 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
which way do you like?

2024-08-17 09:12 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
> which way do you like?

do the first one. But remove the - after "Typen"

2024-08-17 09:12 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
or we can add `\n` in 1st option too

2024-08-17 09:14 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
```
    "desc": "Die Typen wird umgekehrt, und kein Typ ist gegen einen anderen Typ immun.\nDeaktiviert die Erfolge anderer Herausforderungen.",
```
is it correct?

2024-08-17 09:14 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
i will create a suggestion

2024-08-17 09:15 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "desc": "Die Typen-Effektivität wird umgekehrt, und kein Typ ist gegen einen anderen Typ immun. Deaktiviert die Erfolge anderer Herausforderungen.",
```suggestion
    "desc": "Die Typen Effektivität wird umgekehrt, und kein Typ ist gegen einen anderen Typ immun.\nDeaktiviert die Erfolge anderer Herausforderungen.",
```

2024-08-17 09:15 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
<img width="1701" alt="image" src="https://github.com/user-attachments/assets/dd2ade02-c103-4bc6-9da3-7efc8ace8b5e">

2024-08-17 09:17 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
<img width="1702" alt="image" src="https://github.com/user-attachments/assets/372d8625-bf0f-4e00-a436-4b9c8eb1858d">

final version! how about it?

2024-08-17 09:19 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
I hate that "Typen" and "Effektivität" are not on the same line... But thats just the fault of the german language for beeing to long :D 

We can keep it like this. Looks fine!

2024-08-17 09:21 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
It's unfortunate, but this seems to be the best we can do before adjusting the size of the explanatory UI window. 🤔 
Thank you for translating it quickly! 👍

2024-08-17 09:43 UTC, EnochG1 approved these changes

2024-08-17 09:53 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
<img width="1691" alt="image" src="https://github.com/user-attachments/assets/0d4a7d5d-30e7-4992-a4d5-6efd76e7673e">

if devs allow me to change UI size, then this will be final version.

2024-08-17 10:01 UTC, CodeTappert commented on src/locales/de/challenges.ts
> +    "value.1": "On",
well in this case you can readd the "-" between "Typen" and "Effektivität"

2024-08-17 10:03 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
in the very last moment, i will double check to you.

2024-08-17 10:13 UTC, KimJeongSun commented on src/locales/de/challenges.ts
> +    "value.1": "On",
<img width="1689" alt="Screenshot 2024-08-17 at 7 12 21 PM" src="https://github.com/user-attachments/assets/8ae96f4d-b207-4c93-a4dd-544b7149b00d">

how about this last last final version?

2024-08-17 10:14 UTC, Adri1 commented on src/locales/fr/challenges.ts
> +    "value.1": "On",
```suggestion
    "name": "Combat Inversé",
    "desc": "La table des types est inversée et disparition des immunités.\nDésactive les succès des autres challenges.",
    "value.0": "Non",
    "value.1": "Oui",
```

2024-08-17 10:14 UTC, Adri1 commented on src/locales/fr/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
```suggestion
    name: "La teté à verlan",
    description: "Terminer un challenge en Combat Inversé.\n..ésrevnI tabmoC ne egnellahc nu renimreT"
```

2024-08-17 10:15 UTC, KimJeongSun commented on src/locales/fr/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
<img width="1689" alt="Screenshot 2024-08-17 at 7 15 22 PM" src="https://github.com/user-attachments/assets/28141136-bf0b-4f73-87da-7c0ab567c30b">

how about it?

2024-08-17 10:16 UTC, KimJeongSun commented on src/locales/fr/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
plus this
<img width="1689" alt="Screenshot 2024-08-17 at 7 16 37 PM" src="https://github.com/user-attachments/assets/d1f61fe5-5472-44f0-9f26-c3a57dbe97f2">

2024-08-17 10:20 UTC, AsdarDevelops reviewed
Added Spanish

2024-08-17 10:20 UTC, AsdarDevelops commented on src/locales/es/challenges.ts
> +    "value.1": "On",
```suggestion
    "name": "Combate Inverso",
    "desc": "La efectividad de los tipos es invertida. No hay inmunidades entre tipos.\nEste reto deshabilita logros de otros retos.",
    "value.0": "Desactivado",
    "value.1": "Activado",
```

2024-08-17 10:20 UTC, Adri1 reviewed
Tini French correction (thanks for the screenshot!)

2024-08-17 10:20 UTC, Adri1 commented on src/locales/fr/challenges.ts
> +    "desc": "La table des types est inversée et disparition des immunités.\nDésactive les succès des autres challenges.",
```suggestion
    "desc": "Les affinités de la table des types sont inversées et plus aucun type n’a d’immunité.\nDésactive les succès des autres challenges.",
```

2024-08-17 10:21 UTC, Adri1 commented on src/locales/fr/achv.ts
> +    description: "Terminer un challenge en Combat Inversé.\n..ésrevnI tabmoC ne egnellahc nu renimreT"
```suggestion
    description: "Terminer un challenge en Combat Inversé.\n.ésrevnI tabmoC ne egnellahc nu renimreT"
```

2024-08-17 10:21 UTC, KimJeongSun commented on src/locales/es/challenges.ts
> +    "value.1": "On",
can you suggest translation for achv.ts also?

2024-08-17 10:23 UTC, KimJeongSun commented on src/locales/es/challenges.ts
> +    "value.1": "On",
can you suggest Spanish translation for this too?
[src/locales/es/achv.ts](https://github.com/pagefaultgames/pokerogue/pull/3525/files#diff-fc5a0390b73e3f2ebedbc154e29f833130c6a2a96be30dae5a0002dcc9b409f2)

2024-08-17 11:21 UTC, AsdarDevelops reviewed
Missed the achv.ts!

2024-08-17 11:21 UTC, AsdarDevelops commented on src/locales/es/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
```suggestion
    name: "Espejo ojepsE",
    description: "Completa el reto de Combate Inverso.\n.osrevnI etabmoC ed oter le atelpmoC"
```

2024-08-17 11:40 UTC, CodeTappert commented
How did you scale down the text?
I would love todo the same here:
![image](https://github.com/user-attachments/assets/75efb5b6-10d1-41d3-884b-eb2a59fc96d5)

2024-08-17 11:51 UTC, Adri1 reviewed
Better French adaptation

2024-08-17 11:51 UTC, Adri1 commented on src/locales/fr/achv.ts
> +    description: "Terminer un challenge en Combat Inversé.\n.ésrevnI tabmoC ne egnellahc nu renimreT"
```suggestion
    name: "La teuté à verlan",
    description: "Terminer un challenge en Combat Inversé.\nMineter un lenjcha en Ba-con Versin."
```

2024-08-17 16:32 UTC, Adri1 approved these changes

2024-08-17 23:49 UTC, returntoice approved these changes

2024-08-18 07:31 UTC, KimJeongSun commented
> How did you scale down the text? I would love todo the same here: ![image](https://private-user-images.githubusercontent.com/38758606/358843018-75efb5b6-10d1-41d3-884b-eb2a59fc96d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjU1NjksIm5iZiI6MTcyMzk2NTI2OSwicGF0aCI6Ii8zODc1ODYwNi8zNTg4NDMwMTgtNzVlZmI1YjYtMTBkMS00MWQzLTg4NGItZWIyYTU5ZmM5NmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA3MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNzFkOTFmMGQwYWEwNzcwNjM2YTkyODFkNzFmOTA4ODg3NmUzNGU5MDJiZWNmMmVkMTE4ZjczMTM5OWM5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1fi6Jvu_45p6jpulp9iGY4RspvoFa6c75yOsSPEVGXM)

<img width="1202" alt="Screenshot 2024-08-18 at 4 29 54 PM" src="https://github.com/user-attachments/assets/c58e86af-a019-470a-b7cf-839b258211f4">


@CodeTappert how about it? ( De font -> 80, middle align for achievement title label )

2024-08-19 02:44 UTC, mercurius-00 reviewed
zh-cn and zh-tw

2024-08-19 02:44 UTC, mercurius-00 commented on src/locales/zh_TW/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
```suggestion
  "INVERSE_BATTLE": {
    name: "鏡子子鏡",
    description: "完成逆轉之戰挑戰\n戰挑戰之轉逆成完"
```

2024-08-19 02:44 UTC, mercurius-00 commented on src/locales/zh_CN/challenges.ts
> +    "value.1": "On",
```suggestion
    "name": "逆转之战",
    "desc": "属性相克关系被反转，且没有任何属性对其他属性免疫。\n禁用其他挑战的成就。",
    "value.0": "关闭",
    "value.1": "开启",
```

2024-08-19 02:44 UTC, mercurius-00 commented on src/locales/zh_TW/challenges.ts
> +    "value.1": "On",
```suggestion
    "name": "逆轉之戰",
    "desc": "屬性相克關系被反轉，且沒有任何屬性對其他屬性免疫。\n禁用其他挑戰的成就。",
    "value.0": "關閉",
    "value.1": "開啓",
```

2024-08-19 02:44 UTC, mercurius-00 commented on src/locales/zh_CN/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
```suggestion
  "INVERSE_BATTLE": {
    name: "镜子子镜",
    description: "完成逆转之战挑战\n战挑战之转逆成完"
```

2024-08-19 10:47 UTC, DayKev requested changes

2024-08-19 10:47 UTC, DayKev commented on src/data/type.ts
>   * Retrieve the types resisting a given type
```suggestion
 * Retrieve the types resisting a given type. Used by Conversion 2
```

2024-08-19 10:47 UTC, DayKev commented on src/test/battle/inverse_battle.test.ts
> +    game.override.seed("Fire Fang vs Ice Fang against Dragon Type");
```suggestion
```
Tests already use a fixed seed. Though if the AI sometimes doesn't pick Fire Fang based on seed then this test isn't very useful anyway.

2024-08-19 10:47 UTC, DayKev commented on src/test/utils/gameManager.ts
> +
```suggestion

    if (overrides.OPP_HELD_ITEMS_OVERRIDE.length === 0) {
      this.game.removeEnemyHeldItems();
    }
    
```

2024-08-19 12:05 UTC, KimJeongSun commented on src/data/type.ts
> +    return multiplier = 1 as TypeDamageMultiplier;
it's my mis, i think it should be `multiplier as TypeDamageMultiplier;`
how about this?

2024-08-19 12:13 UTC, KimJeongSun commented on src/test/battle/inverse_battle.test.ts
> +    game.override.seed("Fire Fang vs Ice Fang against Dragon Type");
actually, it doesn't sometimes. can i remove this test 6?
because i am not sure there is way to compare AI score from test code?

2024-08-19 12:17 UTC, KimJeongSun commented on src/test/utils/gameManager.ts
> +
it looks suggested code looks not valid. do you think it is necessary?

2024-08-19 12:18 UTC, CodeTappert commented
> > How did you scale down the text? I would love todo the same here: ![image](https://private-user-images.githubusercontent.com/38758606/358843018-75efb5b6-10d1-41d3-884b-eb2a59fc96d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjU1NjksIm5iZiI6MTcyMzk2NTI2OSwicGF0aCI6Ii8zODc1ODYwNi8zNTg4NDMwMTgtNzVlZmI1YjYtMTBkMS00MWQzLTg4NGItZWIyYTU5ZmM5NmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA3MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNzFkOTFmMGQwYWEwNzcwNjM2YTkyODFkNzFmOTA4ODg3NmUzNGU5MDJiZWNmMmVkMTE4ZjczMTM5OWM5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1fi6Jvu_45p6jpulp9iGY4RspvoFa6c75yOsSPEVGXM)
> 
> <img alt="Screenshot 2024-08-18 at 4 29 54 PM" width="1202" src="https://private-user-images.githubusercontent.com/47556641/358890782-c58e86af-a019-470a-b7cf-839b258211f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzAxODQsIm5iZiI6MTcyNDA2OTg4NCwicGF0aCI6Ii80NzU1NjY0MS8zNTg4OTA3ODItYzU4ZTg2YWYtYTAxOS00NzBhLWI3Y2YtODM5YjI1ODIxMWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDEyMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNmNkY2I1NWY5Y2UxMjNlMzI0OTZkOTQyOWQ4M2U4Y2Q0ZTIzMTU2MjI4NzI4OGIyN2IwZTJjMGU3N2MyNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EMDAvyWxXnIAghYevczkfLPQR9UXRm-HfOqvksKBat8">
> @CodeTappert how about it? ( De font -> 80, middle align for achievement title label )

Looks good! (Or i could just shorten the title tbh)

2024-08-19 12:25 UTC, DayKev commented on src/data/type.ts
> +    return multiplier = 1 as TypeDamageMultiplier;
Makes sense.

2024-08-19 12:26 UTC, DayKev commented on src/data/type.ts
> +    }
Ah right, forgot about immunities. That should work then.

2024-08-19 12:27 UTC, DayKev commented on src/test/battle/inverse_battle.test.ts
> +    game.override.seed("Fire Fang vs Ice Fang against Dragon Type");
Yeah the test should probably be removed since there's no good way to evaluate the AI's decisions (that I know of).

2024-08-19 12:30 UTC, DayKev commented on src/test/utils/gameManager.ts
> +
Oh right, I forgot about imports. Make sure to add `import overrides from "#app/overrides.js";` at the top, and change this code to:
```ts
    if (overrides.OPP_HELD_ITEMS_OVERRIDE.length === 0) {
      this.removeEnemyHeldItems();
    }
```

2024-08-19 13:49 UTC, flx-sta commented on src/test/utils/gameManager.ts
> +
Without the `.js`

2024-08-19 15:09 UTC, josericardo-fo commented on src/locales/pt_BR/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
```suggestion
    name: "Subi no ônibuS",
    description: "Complete o desafio da Batalha Invertida.\n.aditrevnI ahlataB ad oifased o etelpmoC"
```

2024-08-19 15:09 UTC, josericardo-fo commented on src/locales/pt_BR/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
```suggestion
    name: "Subi no ônibuS",
    description: "Complete o desafio da Batalha Invertida.\n.aditrevnI ahlataB ad oifased o etelpmoC"
```

2024-08-19 15:27 UTC, josericardo-fo commented on src/locales/pt_BR/challenges.ts
> +    "value.1": "On",
```suggestion
    "name": "Batalha Inversa",
    "desc": "Fraquezas e resistências de tipos são invertidas e nenhum tipo é imune a outro tipo.\nDesativa as conquistas de outros desafios.",
    "value.0": "Desligado",
    "value.1": "Ligado",
```

2024-08-22 15:41 UTC, flx-sta commented on src/test/battle/inverse_battle.test.ts
> -  });
RIP?

2024-08-22 15:46 UTC, KimJeongSun commented on src/test/battle/inverse_battle.test.ts
> -  });
I understand that there will be a rework for that part in #3643 
So we decided to postpone updates for that part until after that PR is completed. (In my mind)

2024-08-22 15:56 UTC, DayKev approved these changes

2024-08-23 04:50 UTC, DayKev requested changes
Created a PR to fix up the tests, once you merge that I've got no complaints. https://github.com/KimJeongSun/pokerogue/pull/1

2024-08-23 05:12 UTC, DayKev approved these changes

2024-08-23 22:56 UTC, flx-sta requested changes
There were some changes made in testing utilities that shouldn't have been made!

2024-08-23 22:56 UTC, flx-sta commented on src/data/challenge.ts
> +  getDifficulty(): number {
NIT: you can use `override` as a keyword

```suggestion
  override getDifficulty(): number {
```

2024-08-23 22:56 UTC, flx-sta commented on src/data/challenge.ts
> +}
NIT: static method should be at the top of a class

2024-08-23 22:56 UTC, flx-sta commented on src/data/move.ts
> +    for (let i = 0; i < Type.STELLAR; i++) {
Q: 
Why `Type.STELLAR`? Is that the last one?

2024-08-23 22:56 UTC, flx-sta commented on src/locales/ca_ES/achv.ts
> +    name: "Mirror rorriM",
```suggestion
    name: "Mirror ɹoɹɹᴉW",
```

Idk if the font can render that :D

2024-08-23 22:56 UTC, flx-sta commented on src/locales/ca_ES/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
```suggestion
    description: "Complete the Inverse Battle challenge.\n.ǝƃuǝllɐɥɔ ǝlʇʇɐq ǝsɹǝʌuI ǝɥʇ ǝʇǝldɯoƆ"
```
Idk if the font can render that :D

2024-08-23 22:56 UTC, flx-sta commented on src/test/utils/gameManager.ts
> +
uuuh.. this was removed for good reason.
It was moved into `classicModeHelper.ts` and `dailyModeHelper.ts` instead

2024-08-23 22:56 UTC, flx-sta commented on src/test/utils/gameManager.ts
> +    }
Please don't use a boolean for `isClassicMode`! instead move them into `classicModeHelper` and such.

You can mark the original method as deprecated if you don't want to change all the existing calls

2024-08-23 23:07 UTC, flx-sta commented
@KimJeongSun I was so kind and resolved those translation merge conflicts

2024-08-24 08:00 UTC, KimJeongSun commented on src/data/challenge.ts
> +  getDifficulty(): number {
i added override as a keyword and removed comments

2024-08-24 08:00 UTC, KimJeongSun commented on src/data/challenge.ts
> +}
moved to top of the class method!

2024-08-24 08:00 UTC, KimJeongSun commented on src/data/move.ts
> +    for (let i = 0; i < Type.STELLAR; i++) {
changed to
`for (let i = 0; i < Object.keys(Type).length; i++) {`

2024-08-24 08:01 UTC, KimJeongSun commented on src/locales/ca_ES/achv.ts
> +    name: "Mirror rorriM",
do you want to change english translation?
( there is no ca_ES translation anymore? )

2024-08-24 08:01 UTC, KimJeongSun commented on src/locales/ca_ES/achv.ts
> +    description: "Complete the Inverse Battle challenge.\n.egnellahc elttaB esrevnI eht etelpmoC"
do you want to change english translation?
( there is no ca_ES translation anymore? )

2024-08-24 08:03 UTC, KimJeongSun commented on src/test/utils/gameManager.ts
> +
Then, should I create a `challengeModeHelper.ts` for the inverse battle challenge test?
I am not sure how to proceed (whether I need to create complex functions to support each individual challenge).

2024-08-24 08:06 UTC, KimJeongSun commented on src/test/utils/gameManager.ts
> +    }
Then, should I define a runToSummon function (which corresponds to this.runToSummon in the previous code) inside the classicModeHelper.ts without designating the mode internally? Should it be defined as a separate class? Or just as a different name within the same class?
This function was used to circumvent the issue where the gameMode gets overridden by classic mode within the runToSummon function.

2024-08-24 08:34 UTC, DayKev commented on src/test/utils/gameManager.ts
> +
I'd create a counterpart in `challengeModeHelper.ts` that starts the game in challenge mode instead of classic mode, and add some sort of `addChallenge()` function in that helper as well that has the various parameters of a challenge (your test uses `id`, `value`, and `severity` for example, though there might be more; and I assume some of them can have default values) that will then push that challenge to an internal `challenges` array. Then you can do:
```ts
game.challenge.addChallenge(id, ...);
game.challenge.startBattle(pokemon?);
```
and the `startBattle()` function of the challenge helper will load the game to the appropriate point, activate the challenges that have been specified, and then start the battle.

2024-08-24 08:37 UTC, DayKev commented on src/locales/ca_ES/achv.ts
> +    name: "Mirror rorriM",
Yeah you can replace the English translations of these. Make sure it shows up properly in game, there might be font issues (as mentioned). If it breaks then just leave it as-is.

2024-08-24 08:38 UTC, KimJeongSun commented on src/locales/ca_ES/achv.ts
> +    name: "Mirror rorriM",
i will try it!

2024-08-24 08:46 UTC, KimJeongSun commented on src/locales/ca_ES/achv.ts
> +    name: "Mirror rorriM",
sadly, we should update font later

<img width="1714" alt="image" src="https://github.com/user-attachments/assets/00faacae-c777-4115-bbbe-c4cb65a45101">

2024-08-24 09:11 UTC, CodeTappert commented
> @KimJeongSun I was so kind and resolved those translation merge conflicts for you so you can focus on the review :)

But this is now missing the localized part in challenge.ts?

2024-08-24 15:11 UTC, KimJeongSun commented on src/test/utils/gameManager.ts
> +
I updated! can you review it again? @DayKev @flx-sta

2024-08-24 15:11 UTC, KimJeongSun commented on src/test/utils/gameManager.ts
> +    }
I updated, can you review it again?

2024-08-24 15:19 UTC, flx-sta commented on src/locales/ca_ES/achv.ts
> +    name: "Mirror rorriM",
This looks good enough for me 😂

2024-08-24 15:21 UTC, KimJeongSun commented on src/locales/ca_ES/achv.ts
> +    name: "Mirror rorriM",
art team will kill me 🔫 . plz stop

btw, i updated others too! can you review it again? 🙇

2024-08-24 15:29 UTC, DayKev reviewed
Other than the minor comment copy-paste errors, lgtm.

2024-08-24 15:29 UTC, DayKev commented on src/test/utils/helpers/challengeModeHelper.ts
> +   * @param species - Optional array of species to summon.
```suggestion
```
Some copy/paste leftovers to remove.

2024-08-24 15:29 UTC, DayKev commented on src/test/utils/helpers/challengeModeHelper.ts
> +   * @param challenges - Array of challenges to set.
```suggestion
```
Same as other comment.

2024-08-24 15:39 UTC, Xavion3 requested changes

2024-08-24 15:39 UTC, Xavion3 commented on src/data/challenge.ts
> +
This is using the wrong type, and also why are you even adding a new loadChallenge function to fresh start? It already has one.

2024-08-24 15:39 UTC, Xavion3 commented on src/field/pokemon.ts
> +      multiplier.value = getTypeDamageMultiplier(moveType, defType);
There is some redundancy here, do we want to just do `const multiplier = new Utils.NumberHolder(getTypeDamageMultiplier(moveType, defType));`?

2024-08-24 15:39 UTC, Xavion3 commented on src/ui/achvs-ui-handler.ts
Why are we changing the achievement UI in a PR about adding a new challenge?

2024-08-24 15:39 UTC, Xavion3 commented on src/ui/challenges-select-ui-handler.ts
Why are we changing the challenge UI to add a new challenge, in ways unrelated to just adding a new row?

2024-08-24 15:41 UTC, KimJeongSun commented
close it, failed test

2024-08-24 15:51 UTC, KimJeongSun commented on src/ui/achvs-ui-handler.ts
There was an issue where the title text of the added achievements and the text related to the Eviolite achievement did not display properly in German, so this part was inevitably modified. (I aligned the titles because I wanted to, and the German reviewer liked it. But if it becomes an issue, I can revert it.)

2024-08-24 15:51 UTC, KimJeongSun commented on src/ui/challenges-select-ui-handler.ts
The description of that achievement was a bit longer than others (to explain our deactivation decision of the achievement), causing the text to overflow out of the box. Therefore, I adjusted the aspect ratio to make it look more natural. At that time, the feedback from others was positive, but if I messed something up, I apologize.

2024-08-24 15:52 UTC, KimJeongSun commented on src/field/pokemon.ts
> +      multiplier.value = getTypeDamageMultiplier(moveType, defType);
It's my first time using NumberHolder, so I didn't know. 
It's definitely better! I'll fix it.

2024-08-24 15:59 UTC, Xavion3 commented on src/ui/challenges-select-ui-handler.ts
It's just a general case, much like the achievements UI, that PRs should generally do one thing and a UI rework should really be seperate from adding a new challenge. A UI rework should have somewhat different standards than just adding a new challenge.

2024-08-24 16:05 UTC, KimJeongSun commented on src/data/challenge.ts
> +
I incorrectly pasted it while addressing the request to move the static function `loadChallenge` of flx to the top of the class. I apologize!!! I've fixed it.

2024-08-24 16:07 UTC, KimJeongSun commented on src/ui/challenges-select-ui-handler.ts
Then should I just revert it to only changing the font size?

2024-08-24 16:17 UTC, flx-sta commented
> > @KimJeongSun I was so kind and resolved those translation merge conflicts for you so you can focus on the review :)
> 
> But this is now missing the localized part in challenge.ts?

Keen eyes. Thanks for letting me know.
I've restored those on my own behalf (as I also lost those).

https://github.com/pagefaultgames/pokerogue/pull/3525/commits/1c06faf4272191205032e8753d2e33723067bfc9

2024-08-24 17:21 UTC, KimJeongSun commented on src/ui/challenges-select-ui-handler.ts
opened new PR https://github.com/pagefaultgames/pokerogue/pull/3731

2024-08-24 17:21 UTC, KimJeongSun commented on src/ui/achvs-ui-handler.ts
opened new PR https://github.com/pagefaultgames/pokerogue/pull/3731

2024-08-25 11:17 UTC, Adri1 approved these changes

2024-08-25 11:20 UTC, CodeTappert approved these changes

2024-08-25 15:26 UTC, KimJeongSun commented
@flx-sta @Xavion3  please check updated requested changes! 🙇

2024-08-25 21:21 UTC, frutescens requested changes

2024-08-25 21:21 UTC, frutescens commented on src/test/battle/inverse_battle.test.ts
> +});
Could you have some checks against abilities as well? Like to check that Pokemon with Fluffy/Dry Skin still take 2x damage against fire moves, etc. How does corrosion work in this mode? How does flying press (two types at once - flying and fighting) work?

2024-08-25 21:58 UTC, Adri1 approved these changes

2024-08-26 00:56 UTC, DayKev commented on src/test/battle/inverse_battle.test.ts
> +});
Fluffy/etc don't interact with type matchups at all. Those abilities should have their own tests to see if they work (which if this PR does somehow break then those tests should properly break and there's no extra test needed here), that doesn't belong here.

Flying press should probably have a test though.

2024-08-26 01:05 UTC, frutescens commented on src/test/battle/inverse_battle.test.ts
> +});
Yeah, that's fine by me. I meant that it would be good to make sure that those abilities shouldn't be affected by the type changes.

2024-08-26 01:36 UTC, torranx commented on src/data/challenge.ts
> +   * @returns {@link boolean} Whether this function did anything.
you can remove {@link boolean} here

2024-08-26 01:36 UTC, torranx commented on src/data/challenge.ts
> +   * @param effectiveness {@link Utils.NumberHolder} The current effectiveness of the move.
nit on all occurrences of this: should be using `linkcode` instead of `link`

2024-08-26 03:49 UTC, KimJeongSun commented on src/test/battle/inverse_battle.test.ts
> +});
I think I'll just add the test for Flying Press. (Honestly, I thought it would be fine to include it in the video.) 
I should be able to work on it this evening! I'll let you know once it's done, so please review and approve it if everything looks good!

2024-08-26 04:02 UTC, KimJeongSun commented on src/data/challenge.ts
> +   * @param effectiveness {@link Utils.NumberHolder} The current effectiveness of the move.
I should be able to work on it this(+ remove link in return comment) evening! I'll let you know once it's done, so please review and approve it if everything looks good!

2024-08-26 04:18 UTC, frutescens commented
I can update it myself through this PR but did you add Inverse Challenge to the Run History challenge parser?

2024-08-26 04:21 UTC, KimJeongSun commented
> I can update it myself through this PR but did you add Inverse Challenge to the Run History challenge parser?

I would be very grateful if you could open a PR and proceed with the merger into that PR. I'll go ahead and merge it with the latest beta for now.

2024-08-26 04:50 UTC, frutescens commented
Sent in my contribution. 
![image](https://github.com/user-attachments/assets/5a560ef8-2836-4ed8-a541-403dc54f8ac0)

2024-08-26 18:56 UTC, KimJeongSun commented on src/data/challenge.ts
> +   * @param effectiveness {@link Utils.NumberHolder} The current effectiveness of the move.
updated!

2024-08-26 18:57 UTC, KimJeongSun commented on src/data/challenge.ts
> +   * @returns {@link boolean} Whether this function did anything.
updated

2024-08-26 19:06 UTC, KimJeongSun commented
I would like to share a record with you about how I discovered an edge case with the move Freeze Dry in the inverse battle challenge while working on a test code for the move Flying Press by request from @frutescens 

First, I identified that the existing test code did not account for the additional type effectiveness of Flying Press, which includes the Flying type. The reason for this is that the following code only considers the basic type of the move, and it cannot check for type effectiveness changes due to additional effects:
```
expect(enemy.getAttackTypeEffectiveness(allMoves[Moves.FREEZE_DRY].type, player)).toBe(2);
```
To address this issue, I modified the test code from using `getAttackTypeEffectiveness` to the following:
```
expect(enemy.getMoveEffectiveness(player, allMoves[Moves.FREEZE_DRY])).toBe(2);
```
As a result, the move Flying Press now functions as expected and the test code works correctly.

Consequently, we discovered that in the context of an inverse battle matchup, the move Freeze Dry was actually functioning as an 8x multiplier against Water types! Here's the relevant code:
```
export class WaterSuperEffectTypeMultiplierAttr extends VariableMoveTypeMultiplierAttr {
  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
    const multiplier = args[0] as Utils.NumberHolder;
    if (target.isOfType(Type.WATER)) {
      multiplier.value *= 4; // Increased twice because initial reduction against water
      return true;
    }

    return false;
  }
}
```
To correct this, I modified the implementation so that in an inverse matchup, the move does not get a 4x multiplier. The updated code is as follows:
```
export class WaterSuperEffectTypeMultiplierAttr extends VariableMoveTypeMultiplierAttr {
  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
    const multiplier = args[0] as Utils.NumberHolder;
    if (target.isOfType(Type.WATER)) {
      const effectivenessAgainstWater = new Utils.NumberHolder(getTypeDamageMultiplier(move.getType(), Type.WATER));
      applyChallenges(user.scene.gameMode, ChallengeType.TYPE_EFFECTIVENESS, effectivenessAgainstWater);
      if (effectivenessAgainstWater.value < 1) {
        multiplier.value *= 4; // Increased twice because initial reduction against water
        return true;
      }
    }

    return false;
  }
}
```

2024-08-27 00:42 UTC, flx-sta submitted a review, later dismissed
This feels so wrong when playing with inverse types

2024-08-27 00:43 UTC, DayKev submitted a review, later dismissed

2024-08-27 02:08 UTC, Xavion3 commented on src/data/move.ts
> +      }
While more correct, this code doesn't quite work so would want a (P) or the like on the move. Freeze Dry should always deal super effective damage to water regardless of type matchup, and this code doesn't do that right now. Multiplying by 2/effectiveness will work though unless we ever add a way to make water immune to a type.

2024-08-27 02:42 UTC, KimJeongSun commented on src/data/move.ts
> +
Initially, I was planning to jut use Type.ICE, but since that attribute seemed to give the effect of being super effective against Water type, I prepared it to check for super effectiveness against general types. Of course, currently, that attribute is only being used for the Freeze-Dry move.

2024-08-27 02:45 UTC, KimJeongSun commented on src/data/move.ts
> +
I might have misunderstood the question or missed something, so I'm commenting again.
Is there another way to access the `this._type` (private) in the move class? I wasn't aware of it, so I created this function.

2024-08-27 13:17 UTC, KimJeongSun commented on src/data/move.ts
> +      }
I updated it

2024-08-27 17:05 UTC, Tempo-anon commented
I really love the idea of an inverse battle challenge modifier and think it would be great. However, inverse types are not very well balanced (normal is very OP) so would it make sense for it to interact or disable some mono type challenges? Beating inverse grass is very different from beating mono grass for example.

2024-08-27 17:32 UTC, KimJeongSun commented
> I really love the idea of an inverse battle challenge modifier and think it would be great. However, inverse types are not very well balanced (normal is very OP) so would it make sense for it to interact or disable some mono type challenges? Beating inverse grass is very different from beating mono grass for example.

So, I disabled it. (The balance team wanted it that way too!) :prayja:

2024-08-27 18:20 UTC, Xavion3 approved these changes

2024-08-27 18:54 UTC, Xavion3 commented
Where is the code that is preventing the other achievements being earned during inverse battles?

2024-08-28 03:23 UTC, frutescens approved these changes
This was so difficult omg
![image](https://github.com/user-attachments/assets/7b7f2467-3d95-4589-9a8c-8b1926d58209)

2024-08-28 03:51 UTC, frutescens requested changes
Not ready for merge. Please see second half of vidoe. 

https://github.com/user-attachments/assets/a714e771-3e8e-445d-8b1a-b3a62dd7beac

2024-08-28 04:45 UTC, KimJeongSun commented
> Not ready for merge. Please see second half of vidoe.
> 
>  freecompress-Screen.Recording.2024-08-27.at.8.27.41.PM.mp4

I found out blocking achv code in game over phase looks missing when we deleting old phases.ts
so i add it and for my test, works again!

2024-08-28 05:40 UTC, frutescens submitted a review, later dismissed
Issue resolved.

https://github.com/user-attachments/assets/970ed9b0-e839-4439-859f-21508a8b9789

2024-08-28 14:20 UTC, CodeTappert approved these changes

2024-08-29 02:26 UTC, DayKev submitted a review, later dismissed

2024-08-29 02:26 UTC, frutescens submitted a review, later dismissed

2024-08-29 02:40 UTC, frutescens commented on src/phases/game-over-phase.ts
> +            if (!this.scene.gameMode.challenges.some(c => c.id === Challenges.INVERSE_BATTLE)) {
this code won't work because challenges are judged to be active based on their value -> if it's not 0 (on) or 0 (off)

2024-08-29 07:18 UTC, KimJeongSun commented on src/phases/game-over-phase.ts
> +            if (!this.scene.gameMode.challenges.some(c => c.id === Challenges.INVERSE_BATTLE)) {
it is fixed!

2024-08-29 07:41 UTC, damocleas approved these changes

2024-08-29 18:36 UTC, damocleas approved these changes

2024-08-29 18:59 UTC, f-fsantos approved these changes

2024-08-29 18:59 UTC, merged