[Bug] Toxic Spikes implementation issues
pagefaultgames/pokerogue pull request #3528
Opened 2024-08-13 06:07 UTC by ElizaAlex

## What are the changes?

Adjusted MoveEffectPhase.start() so that ENEMY_SIDE targeted moves no longer occur twice per use in double battles.
Improved documentation / code readability
Fixed Toxic / Poison dealing damage immediately when applied.
Fixed Hazards not persisting through save
Updated Toxic Orb test

I wasn't able to recreate toxic spikes not being absorbed, or the double message, though I didn't attempt to until after fixing the double battle problem. 

## Why am I doing these changes?
Addresses bugs compiled in #3240 

## What did change?
- Adjusted MoveEffectPhase to only apply the effects of ENEMY_SIDE targeted moves a single time, even in double battles. Previously this caused a bug where you would apply two layers of toxic spikes (and presumably spikes)
- Fixed bug where toxin/poison/burn damage would apply prematurely by adding a new phase scheduled after weather effects to check for and queue status damage.
- As a result of the Poison/Toxic/Burn changes, Toxic and Flame Orb now behave as they should, with the damage not triggering until the second turn. 
- Fixed ArenaTags not being loaded properly after a reset by basing them off of the handling of BattlerTags. Previously the ArenaData class constructor never successfully recovered saved tags from the JSON string. 
- Updated Toxic Orb test to reflect changes.
- Refactored MoveEffectPhase in Phases.ts to improve readability, heavily reducing nested code by breaking the section into various documented helper functions. 

### Screenshots/Videos
Video/Images pending

## How to test the changes?

1. Use overrides to force double battles, and to give your starter(s) of choice toxic spikes
2. Use toxic spikes in a wild battle, and then defeat your opponent.
3. Proceed far enough into the next encounter so that the incoming pokemon get poisoned. The text should only display once, and only one set should go down.
4. Refresh the game
5. Load back into the same file, and the spikes should still be present / affect the incoming pokemon
6. Repeat steps 2-5 to test the Badly Poisoned effect
7. If at any point a grounded poison type pokemon enters the field, the spikes should be absorbed.

## Checklist
- [x ] **I'm using `beta` as my base branch**
- [x ] There is no overlap with another PR?
- [? ] The PR is self-contained and cannot be split into smaller PRs?
- [x ] Have I provided a clear explanation of the changes?
- [x ] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

I would appreciate feedback on the formatting changes in MoveEffectPhase, as well as whether or not this should be split into multiple separate PRs

2024-08-13 20:45 UTC, ElizaAlex commented on src/phases.ts
> -          if (pokemon.status?.isPostTurn()) {
This caused premature application of poison/burn damage, such as taking damage turn 1 from Toxic/Poison orb, and taking damage immediately upon landing in toxic spikes.

2024-08-19 19:55 UTC, ElizaAlex commented
Updated to reflect removal of Phases.ts

2024-08-22 17:58 UTC, Snailman11 commented
Probably fixes https://github.com/pagefaultgames/pokerogue/issues/684

2024-09-01 06:12 UTC, DayKev commented on src/phases/check-status-effect-phase.ts
> +import {BattlerIndex} from "#app/battle";
```suggestion
import { PostTurnStatusEffectPhase } from "#app/phases/post-turn-status-effect-phase";
import { Phase } from "#app/phase";
import { BattlerIndex } from "#app/battle";
```

2024-09-01 06:12 UTC, DayKev commented on src/phases/move-effect-phase.ts
> +import {Abilities} from "#enums/abilities";
```suggestion
import { Abilities } from "#enums/abilities";
```

2024-09-01 06:12 UTC, DayKev commented on src/phases/turn-start-phase.ts
> +import {CheckStatusEffectPhase} from "#app/phases/check-status-effect-phase";
```suggestion
import { CheckStatusEffectPhase } from "#app/phases/check-status-effect-phase";
```

2024-09-01 06:12 UTC, DayKev commented on src/system/arena-data.ts
> +import {ArenaTag, loadArenaTag} from "../data/arena-tag";
```suggestion
import { ArenaTag, loadArenaTag } from "../data/arena-tag";
```

2024-09-01 06:12 UTC, DayKev commented on src/system/game-data.ts
> +import {ArenaTrapTag} from "#app/data/arena-tag";
```suggestion
import { TagAddedEvent } from "#app/events/arena";
import { ArenaTrapTag } from "#app/data/arena-tag";
```

2024-09-01 06:14 UTC, DayKev commented
Merged in beta branch and updated the tests (plus applied some style nits).

2024-09-01 10:27 UTC, innerthunder requested changes

2024-09-01 10:27 UTC, innerthunder commented on src/phases/move-effect-phase.ts
> +        let hazardBounce: boolean = false;
The Magic Bounce-related stuff is a nice thought, but I don't really think it fits within the scope of this PR

2024-09-05 02:49 UTC, DayKev commented on src/phases/move-effect-phase.ts
> +
```suggestion
```

2024-09-11 22:01 UTC, DayKev commented on src/test/moves/safeguard.test.ts
> +    enemyPokemon.damageAndUpdate(1);
```suggestion
```

2024-09-11 22:05 UTC, DayKev approved these changes

2024-09-11 22:12 UTC, innerthunder submitted a review, later dismissed

2024-10-10 03:25 UTC, DayKev approved these changes

2024-10-10 03:28 UTC, DayKev approved these changes

2024-10-10 05:05 UTC, innerthunder approved these changes

2024-10-11 14:41 UTC, merged