[Refactor] Reduced nesting in MoveEffectPhase
pagefaultgames/pokerogue pull request #3541
Opened 2024-08-13 22:34 UTC by ElizaAlex

## What are the changes?
I adjusted MoveEffectPhase.run(), particularly the section that handles applying attributes when a move is used, to heavily reduce the amount of nested indents, and hopefully improve readability and clarity. 

## Why am I doing these changes?
I was working on another PR that required changes to this function, and found the changed section of code very difficult to read and follow what was going on. 

Improved comments have been added in the time between me finishing my other changes, and submitting this PR, but I still think that flattening 

## What did change?
All changes refer to specifically the section of MoveEffectPhase related to constructing the final promise in charge of applying Move or Ability Attribute effects that is then pushed into applyAttrs.

- Flattened out nested promises into chains whenever reasonable
- Extracted sections of code out into named and documented helper functions

## How to test the changes?
Functionality _should_ remain entirely unchanged.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

2024-08-13 23:13 UTC, innerthunder requested changes
Some nits, but I like the structural changes to the code overall.

2024-08-13 23:13 UTC, innerthunder commented on src/phases.ts
> +   * Step skipped if user is Charging
Minor clarification: `chargeEffect` is for moves with effects that are meant to trigger on the "charging turn" of charge moves (e.g. the stat boost from [Meteor Beam](https://bulbapedia.bulbagarden.net/wiki/Meteor_Beam_(move))). The big nested chain of move effects atm only triggers on the second turn of charge moves, which is why most attributes are ignored when `chargeEffect` is `true`

2024-08-13 23:13 UTC, innerthunder commented on src/phases.ts
> +   * @param user
I'm assuming that filling out these params is a WIP, but ideally this should follow a format similar to
```ts
/**
 * @param user {@linkcode Pokemon} insert description about this param
 */
```

2024-08-14 07:43 UTC, innerthunder approved these changes

2024-08-19 17:25 UTC, ElizaAlex commented
Updated to support removal of Phases.ts

2024-09-22 20:09 UTC, DayKev commented
Ooh wish I had seen this sooner, are you still around to update the PR?

2024-09-22 20:28 UTC, ElizaAlex commented
> Ooh wish I had seen this sooner, are you still around to update the PR?
Have been a bit too busy to work on any new PRs lately, but can prob get around to updating this and #3655 some time in the next few days/coming week.

2024-09-27 05:06 UTC, innerthunder submitted a review, later dismissed

2024-10-11 10:51 UTC, DayKev reviewed
https://github.com/ElizaAlex/pokerogue/pull/1

Thanks for not notifying me this was updated GitHub, very useful.

2024-11-02 19:47 UTC, DayKev approved these changes

2024-11-02 19:53 UTC, innerthunder approved these changes

2024-11-02 19:53 UTC, innerthunder commented on src/phases/move-effect-phase.ts
>       * e.g. Charging moves (Fly, etc.) on their first turn of use.
oh, this should probably use a different example since charge moves were reworked lol

2024-11-03 02:55 UTC, Tempo-anon commented on src/phases/move-effect-phase.ts
>       * e.g. Charging moves (Fly, etc.) on their first turn of use.
Just make a new PR to update it :snoremax:

2024-11-03 02:55 UTC, merged