[Refactor] Improvements on getOrder()
pagefaultgames/pokerogue pull request #3547
Opened 2024-08-14 19:27 UTC by frutescens

## What are the changes?
This moves the function getOrder() from FieldPhase to its child class TurnStartPhase. TurnStartPhase is the only class that uses getOrder().
This also incorporates command priority, move priority and speed bypass chance into getOrder()'s calculations. 
I also added documentation on the function's working + cleaned up some of its logic. 
Stall and Mycelium Might's tests will also be updated to utilize getOrder()

## Why am I doing these changes?
When I was working on Stall and Mycelium Might's tests, I learned that there was no sure-fire way to prove that a change in priority occurred because getOrder() only returned the turn order after speed calculations/Trick Room and before priority/command order. This addresses this limitation, hopefully improving code readability and tests. 

## How to test the changes?
Play the game normally. Run tests. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

2024-08-14 19:41 UTC, innerthunder requested changes

2024-08-14 19:41 UTC, innerthunder commented on src/phases.ts
> +        const isSameBracket = aPriority === bPriority;
```suggestion
        const isSameBracket = aPriority.value === bPriority.value;
```
Also, why is this set before attributes that can change priority are applied?

2024-08-14 19:41 UTC, innerthunder commented on src/phases.ts
> +          if (isSameBracket && battlerBypassSpeed[a].value !== battlerBypassSpeed[b].value) {
The stuff inside this `if` would never run because we know `aPriority.value !== bPriority.value` from the outer `if` condition

2024-08-14 19:45 UTC, frutescens commented on src/phases.ts
> +        const isSameBracket = aPriority === bPriority;
This checks if the **original** priority of the moves are the same.

2024-08-14 19:45 UTC, frutescens commented on src/phases.ts
> +          if (isSameBracket && battlerBypassSpeed[a].value !== battlerBypassSpeed[b].value) {
See above.

2024-08-15 23:05 UTC, snoozbuster approved these changes

2024-08-15 23:48 UTC, DayKev commented on src/phases.ts
> +    return orderedTargets.map(t => t.getFieldIndex() + (!t.isPlayer() ? BattlerIndex.ENEMY : 0));
Should probably change that `0` to `BattlerIndex.PLAYER` while you're here.

2024-08-15 23:49 UTC, DayKev commented on src/phases.ts
> +    return orderedTargets.map(t => t.getFieldIndex() + (!t.isPlayer() ? BattlerIndex.ENEMY : 0));
```suggestion
    return orderedTargets.map(t => t.getFieldIndex() + (!t.isPlayer() ? BattlerIndex.ENEMY : BattlerIndex.PLAYER));
```
Forgot to actually put the suggestion thing in.

2024-08-20 22:59 UTC, snoozbuster commented on src/phases.ts
empty file got re-added it seems

2024-08-20 23:02 UTC, snoozbuster commented on src/test/abilities/mycelium_might.test.ts
> +    expect(speedOrder.every((val, index) => val === commandOrder[index])).toBe(true);
```suggestion
    expect(speedOrder).toContainEqual(commandOrder);
```

does this work here? I thought there were matchers for directly comparing two arrays. honestly, I think even `.toBeEqual()` is deep equality by default so maybe that alone works

2024-08-20 23:02 UTC, snoozbuster commented on src/test/abilities/mycelium_might.test.ts
> +    expect(speedOrder.every((val, index) => val === commandOrder[index])).toBe(true);
toEqual

2024-08-20 23:03 UTC, snoozbuster commented on src/test/abilities/stall.test.ts
> +    expect(speedOrder.reverse().every((val, index) => val === commandOrder[index])).toBe(true);
toEqual

2024-08-20 23:03 UTC, snoozbuster commented on src/test/abilities/stall.test.ts
> +    expect(speedOrder.every((val, index) => val === commandOrder[index])).toBe(true);
and so on (I'm not gonna comment on every one)

2024-08-21 00:29 UTC, frutescens commented on src/test/abilities/mycelium_might.test.ts
> +    expect(speedOrder.every((val, index) => val === commandOrder[index])).toBe(true);
No, it does not work.

2024-08-22 05:37 UTC, DayKev requested changes

2024-08-22 05:37 UTC, DayKev commented on src/test/abilities/stall.test.ts
> +    expect(speedOrder.reverse()).toEqual(commandOrder);
Imo these various move order tests should be asserting that the orders are as we expect them to be, something like `expect(speedOrder).toBe([pkmnA, pkmnB])` and `expect(commandOrder).toBe([pkmnB, pkmnA])`. As it is, this test also passes if `speedOrder` is `[pkmnB, pkmnA]` and `commandOrder` is `[pkmnA, pkmnB]`, even though that would mean something has gone wrong.

2024-08-22 05:37 UTC, DayKev commented on src/test/battle/battle-order.test.ts
>      expect(order.indexOf(0)).toBeGreaterThan(order.indexOf(2));
Similar here, why are we not asserting that the order of moves was exactly as expected, and instead doing a bunch of greaterthan/lessthan checks?

2024-08-22 05:37 UTC, DayKev commented on src/test/moves/dynamax_cannon.test.ts
> +    vi.spyOn((game.scene.getCurrentPhase() as TurnStartPhase), "getCommandOrder").mockReturnValue([ BattlerIndex.PLAYER, BattlerIndex. ENEMY]);
This should be using `setTurnOrder()`.

2024-08-22 05:37 UTC, DayKev commented on src/enums/battle-spec.ts
> +    FINAL_BOSS_MONOTYPE
Why is this here? Improper merge?

2024-08-22 06:28 UTC, frutescens commented on src/enums/battle-spec.ts
> +    FINAL_BOSS_MONOTYPE
I swear I got rid of that....

2024-08-22 06:48 UTC, frutescens commented on src/test/abilities/stall.test.ts
> +    expect(speedOrder.reverse()).toEqual(commandOrder);
I just updated the stall and mycelium tests to be more in line with what you suggested. I will update the other tests after your thoughts, if that is alright?

2024-08-22 06:49 UTC, frutescens commented on src/test/battle/battle-order.test.ts
>      expect(order.indexOf(0)).toBeGreaterThan(order.indexOf(2));
I wish I knew too....

2024-08-22 07:49 UTC, DayKev commented on src/test/abilities/stall.test.ts
> +    expect(speedOrder.reverse()).toEqual(commandOrder);
Sure. 👍

2024-08-22 18:53 UTC, innerthunder requested changes
Some nits and test changes, otherwise looks good

2024-08-22 18:53 UTC, innerthunder commented on src/test/abilities/mycelium_might.test.ts
> +    await game.phaseInterceptor.run(EnemyCommandPhase);
```suggestion
    await game.phaseInterceptor.to(TurnStartPhase, false);
```
same thing here

2024-08-22 18:53 UTC, innerthunder commented on src/test/abilities/mycelium_might.test.ts
> +    await game.phaseInterceptor.run(EnemyCommandPhase);
```suggestion
    await game.phaseInterceptor.to(TurnStartPhase, false);
```
In case we end up putting something between `EnemyCommandPhase` and `TurnStartPhase` in the future (and it also helps get rid of an import)

2024-08-22 18:53 UTC, innerthunder commented on src/phases/turn-start-phase.ts
> +  getCommandOrder(): BattlerIndex[] {
nit: imo `getActionOrder` would be a better name for this, since it resolves the order in which commands are acted upon rather than when they're sent.

2024-08-22 18:53 UTC, innerthunder commented on src/phases/turn-start-phase.ts
> +  getSpeedOrder(): BattlerIndex[] {
This and `getCommandOrder` need tsdocs

2024-08-22 18:53 UTC, innerthunder commented on src/test/abilities/mycelium_might.test.ts
> +    await game.phaseInterceptor.run(EnemyCommandPhase);
```suggestion
    await game.phaseInterceptor.run(TurnStartPhase, false);
```

2024-08-22 18:53 UTC, innerthunder commented on src/test/abilities/mycelium_might.test.ts
> +import { EnemyCommandPhase } from "#app/phases/enemy-command-phase";
```suggestion
```
To go along with other suggested changes

2024-08-22 18:53 UTC, innerthunder commented on src/test/abilities/stall.test.ts
> +import { EnemyCommandPhase } from "#app/phases/enemy-command-phase";
```suggestion
```
Same changes as with the MM tests

2024-08-22 18:53 UTC, innerthunder commented on src/test/abilities/stall.test.ts
> +    await game.phaseInterceptor.run(EnemyCommandPhase);
```suggestion
    await game.phaseInterceptor.run(TurnStartPhase, false);
```

2024-08-22 18:53 UTC, innerthunder commented on src/test/abilities/stall.test.ts
> +    await game.phaseInterceptor.run(EnemyCommandPhase);
```suggestion
    await game.phaseInterceptor.run(TurnStartPhase, false);
```

2024-08-22 18:53 UTC, innerthunder commented on src/test/abilities/stall.test.ts
> +    await game.phaseInterceptor.run(EnemyCommandPhase);
```suggestion
    await game.phaseInterceptor.run(TurnStartPhase, false);
```

2024-08-22 18:53 UTC, innerthunder commented on src/test/battle/battle-order.test.ts
Could probably also make similar changes here to get rid of the `EnemyCommandPhase` import

2024-08-22 18:55 UTC, innerthunder commented
ugh my review comments are out of order, but hopefully you get the idea lol

2024-08-22 19:30 UTC, frutescens commented on src/test/battle/battle-order.test.ts
Yeah, I'm just hesitant to remove it since it seems like its testing if all the moving pieces involved are working.

2024-08-22 19:33 UTC, frutescens commented on src/phases/turn-start-phase.ts
> +  getCommandOrder(): BattlerIndex[] {
I feel like because we use 'Command.X' enums / identifiers; it's more coherent and matches the 'story' that the rest of the code is trying to tell. I do agree that Action.MOVE, Action.RUN, Action.BALL, etc. are much better but alas...

2024-08-22 19:46 UTC, frutescens commented
@innerthunder Let me know what you think about my responses! I added the documentation + fixes.

2024-08-22 20:16 UTC, innerthunder commented on src/phases/turn-start-phase.ts
> +   * @return {@linkcode BattlerIndex[]}
```suggestion
   * @returns {@linkcode BattlerIndex[]}
```

2024-08-22 20:16 UTC, innerthunder commented on src/phases/turn-start-phase.ts
> +   * @return {@linkcode BattlerIndex[]} this determines the timeline of the current turn
```suggestion
   * @returns {@linkcode BattlerIndex[]} the final sequence of commands for this turn
```
A description like this for `getSpeedOrder`'s `@returns` would also be nice.

2024-08-22 20:16 UTC, innerthunder commented on src/phases/turn-start-phase.ts
>          applyAbAttrs(ChangeMovePriorityAbAttr, this.scene.getField().find(p => p?.isActive() && p.getBattlerIndex() === b)!, null, false, bMove, bPriority); //TODO: is the bang correct here?
While here, can you make sure these bangs are correct (and get rid of the TODOs if they are)?

2024-08-22 20:29 UTC, innerthunder commented on src/test/battle/battle-order.test.ts
> +    enemyPokemon2.stats[Stat.SPD] = 150;
Could clean this up by doing something like
```ts
  const playerPokemon = game.scene.getPlayerField();
  const enemyPokemon = game.scene.getEnemyField();

  playerPokemon.forEach(p => p.stats[Stat.SPD] = 50);
  enemyPokemon.forEach(p => p.stats[Stat.SPD] = 150);
```
and using `map`/`forEach` for other parts of this file in a similar way

2024-08-22 20:32 UTC, innerthunder commented on src/test/battle/battle-order.test.ts
It looks like it's just testing the turn order that's returned by `TurnStartPhase` from what I've read, so the way it's written now unnecessarily requires `TurnStartPhase` to immediately follow `EnemyCommandPhase`. So yeah, it'd be better to make the same changes as we did with the other files.

2024-08-22 20:38 UTC, frutescens commented on src/test/battle/battle-order.test.ts
> +    enemyPokemon2.stats[Stat.SPD] = 150;
but I need the pokemon for their indexes too

2024-08-22 21:05 UTC, innerthunder commented on src/test/battle/battle-order.test.ts
> +    enemyPokemon2.stats[Stat.SPD] = 150;
You can pull indexes from these arrays with
```ts
playerPokemon[i].getBattlerIndex()
```
or
```ts
const playerIndexes = playerPokemon.map(p => p.getBattlerIndex());
playerIndexes[i]
```

2024-08-22 22:49 UTC, frutescens commented on src/phases/turn-start-phase.ts
>          applyAbAttrs(ChangeMovePriorityAbAttr, this.scene.getField().find(p => p?.isActive() && p.getBattlerIndex() === b)!, null, false, bMove, bPriority); //TODO: is the bang correct here?
The bangs are correct since the Pokemon object could be undefined due to a variety of circumstances. I;ll remove the comments

2024-08-25 14:25 UTC, DayKev commented on src/phases/turn-start-phase.ts
>          applyAbAttrs(ChangeMovePriorityAbAttr, this.scene.getField().find(p => p?.isActive() && p.getBattlerIndex() === b)!, null, false, bMove, bPriority); //TODO: is the bang correct here?
And there aren't any problems if it is undefined?

2024-08-25 18:43 UTC, innerthunder submitted a review, later dismissed

2024-08-25 18:55 UTC, DayKev approved these changes

2024-08-26 00:46 UTC, DayKev submitted a review, later dismissed

2024-08-26 01:39 UTC, torranx commented on src/test/utils/gameManager.ts
>    async setTurnOrder(order: BattlerIndex[]): Promise<void> {
would the changes here make the function name obsolete?

2024-08-26 01:39 UTC, torranx commented on src/test/battle/battle-order.test.ts
> +    enemyPokemon[1].stats[Stat.SPD] = 150;
I know these are already present before but moving forward we should not be manipulating global data- if it's possible to replace these, please do so

2024-08-26 02:07 UTC, frutescens commented on src/test/utils/gameManager.ts
>    async setTurnOrder(order: BattlerIndex[]): Promise<void> {
No, I don't think so.

2024-08-26 02:09 UTC, frutescens commented on src/test/battle/battle-order.test.ts
> +    enemyPokemon[1].stats[Stat.SPD] = 150;
Is it possible to generate Pokemon with the exact same stats with certainty?

2024-08-26 08:17 UTC, torranx commented on src/test/battle/battle-order.test.ts
> +    enemyPokemon[1].stats[Stat.SPD] = 150;
well no ofc, I'm just saying there _might_ be other ways like mocking `getStat` for example

2024-08-26 23:29 UTC, frutescens commented on src/test/battle/battle-order.test.ts
> +    enemyPokemon[1].stats[Stat.SPD] = 150;
Changed it! TY for your suggestion.

2024-08-27 00:35 UTC, DayKev approved these changes

2024-08-27 06:15 UTC, torranx approved these changes

2024-08-31 19:04 UTC, innerthunder approved these changes

2024-09-01 22:23 UTC, merged