[Bug] Don't recalculate stats that already exist
pagefaultgames/pokerogue pull request #3569
Opened 2024-08-16 07:11 UTC by DayKev

## What are the changes?
When a Pokémon evolves its current HP will increase by the same amount that its max HP does.

## Why am I doing these changes?
Fixes #2352

## What did change?
When creating a new `Pokemon` object, `calculateStats()` is not called if already existing stats are passed through the constructor.

### Screenshots/Videos
Before fix:

https://github.com/user-attachments/assets/2081477d-151b-4d10-8728-81ff7b8c7453

After fix:

https://github.com/user-attachments/assets/46c9462c-9442-406e-96bf-14a07d67c848

## How to test the changes?
Evolve a Pokémon in the same conditions pre- and post-patch.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

2024-08-16 09:11 UTC, torranx commented on src/test/utils/mocks/mockVideoGameObject.ts
> +export class MockVideoGameObject implements MockGameObject {
I know this is a mock class but can we at least add some docs/description on it?

2024-08-16 10:04 UTC, flx-sta commented
@DayKev there is 1 more thing to be tested: when it evolved without having full hP

2024-08-16 11:36 UTC, flx-sta commented
Added a test for that too
https://github.com/DayKev/pokerogue/pull/5

2024-08-16 21:23 UTC, DayKev commented
Ugh Github why are you like this?

2024-08-19 12:02 UTC, flx-sta requested changes
You imported every phases file with `.js` extension…

2024-08-20 14:43 UTC, flx-sta submitted a review, later dismissed

2024-08-28 00:25 UTC, DayKev commented on src/test/utils/mocks/mockVideoGameObject.ts
> +export class MockVideoGameObject implements MockGameObject {
I'm unsure what docs there even are to put here. @flx-sta

2024-08-28 02:49 UTC, innerthunder submitted a review, later dismissed

2024-08-28 03:10 UTC, frutescens approved these changes

2024-08-28 14:44 UTC, flx-sta commented on src/test/evolution.test.ts
> +import { Moves } from "#app/enums/moves.js";
```suggestion
import { Moves } from "#app/enums/moves";
```

2024-08-28 14:45 UTC, flx-sta commented on src/test/utils/mocks/mockVideoGameObject.ts
> +export class MockVideoGameObject implements MockGameObject {
Something that links to the original interface.  Nothing fancy

2024-08-28 19:31 UTC, DayKev commented on src/test/evolution.test.ts
> +import { Moves } from "#app/enums/moves.js";
There's gotta be a way to make auto-import not add `.js` to the imports...

2024-08-28 19:50 UTC, DayKev commented on src/test/utils/mocks/mockVideoGameObject.ts
> +export class MockVideoGameObject implements MockGameObject {
Well that's the thing, I'm not sure what exactly the original interface is; this is from your PR.

2024-08-31 03:01 UTC, innerthunder approved these changes

2024-08-31 03:05 UTC, Tempo-anon approved these changes

2024-08-31 03:11 UTC, frutescens approved these changes

2024-08-31 03:21 UTC, merged