[DOCS] adding JSDocs to `arena.ts`
pagefaultgames/pokerogue pull request #3590
Opened 2024-08-17 02:56 UTC by DustinLin

## What are the changes?

nothing

## Why am I doing these changes?

was looking through these functions and noticed there were no docs

## What did change?

some docs/comments were added

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?

2024-08-17 06:42 UTC, DayKev commented on src/field/pokemon.ts
> +  public battleStats: integer[] = [ 0, 0, 0, 0, 0, 0, 0 ]; // [Atk, Def, SpAtk, SpDef, Spd, Acc]
```suggestion
  public battleStats: integer[] = [ 0, 0, 0, 0, 0, 0, 0 ]; // [Atk, Def, SpAtk, SpDef, Spd, Acc, Eva]
```
Not 100% sure on it being accuracy and then evasion but regardless, it's missing.

2024-08-18 14:42 UTC, DustinLin commented on src/field/pokemon.ts
> +  public battleStats: integer[] = [ 0, 0, 0, 0, 0, 0, 0 ]; // [Atk, Def, SpAtk, SpDef, Spd, Acc]
looking at `data/battle-stat.ts` seems to support your guess

2024-09-05 16:22 UTC, frutescens submitted a review, later dismissed

2024-09-05 17:09 UTC, flx-sta requested changes
Some minor NITs

2024-09-05 17:09 UTC, flx-sta commented on src/field/arena.ts
> +   * @param hasPokemonSource boolean if the new weather is from a pokemon
```suggestion
   * @param hasPokemonSource true if the new weather is from a pokemon
```

you don’t need to put types into JS doc as we are using ts. This is just redundant

2024-09-05 17:09 UTC, flx-sta commented on src/field/arena.ts
> +   * @param weather {@linkcode WeatherType} new weather to set of type WeatherType
```suggestion
   * @param weather {@linkcode WeatherType} new {@linkcode WeatherType} to set
```
you don’t need to put types into JS doc as we are using ts. This is just redundant

2024-09-05 17:09 UTC, flx-sta commented on src/field/arena.ts
> +   * @returns boolean - true to force trySetWeather to return true
```suggestion
   * @returns true to force trySetWeather to return true
```
you don’t need to put types into JS doc as we are using ts. This is just redundant

2024-09-05 17:09 UTC, flx-sta commented on src/field/arena.ts
> +   * @param weather {@linkcode WeatherType} new weather to set of type WeatherType
```suggestion
   * @param weather new {@linkcode WeatherType} to set
```
you don’t need to put types into JS doc as we are using ts. This is just redundant

2024-09-05 17:36 UTC, DustinLin commented on src/field/arena.ts
> +   * @param hasPokemonSource boolean if the new weather is from a pokemon
I find them quite useful though for referring to types in vscode, for example in this case vscode gives you a direct link to the `WeatherType` enum, without the linkcode you have to take an extra step to search/find it

![screenshot](https://github.com/user-attachments/assets/d89d27ec-20a0-4b01-84db-d2d04bae1c1c)

2024-09-05 18:33 UTC, flx-sta commented on src/field/arena.ts
> +   * @param hasPokemonSource boolean if the new weather is from a pokemon
No offense but there is no extra steps needed. Look above 
`(method) Arena.trySetWeather(weather:  WeatherType, hasPokemonSource: boolean)`

I understand that you mean the internal link but I didn't remove that for the WeatherType. I'm aware of that feature. I just rephrased it to be less redundant

2024-09-05 20:20 UTC, DustinLin commented on src/field/arena.ts
> +   * @param hasPokemonSource boolean if the new weather is from a pokemon
thanks, for clarifying i get you (remove extra text, no the linkcode itself)

2024-09-05 20:49 UTC, flx-sta submitted a review, later dismissed

2024-09-05 21:51 UTC, DayKev requested changes
https://github.com/DustinLin/pokerogue/pull/1

2024-09-06 16:24 UTC, DustinLin commented
thanks @DayKev , merged in

2024-09-06 18:42 UTC, flx-sta approved these changes

2024-09-06 19:05 UTC, frutescens approved these changes

2024-09-06 21:53 UTC, DayKev approved these changes

2024-09-08 04:36 UTC, merged