[Localization] Add localization hard-coded message in move, pokemon.
pagefaultgames/pokerogue pull request #3639
Opened 2024-08-19 05:07 UTC by EnochG1

## What are the changes the user will see?
English : none.
Other languages : Can see translated messages.

## Why am I making these changes?
All message texts are localizable.

## What are the changes from a developer perspective?
- Change hard-coded messages in `src/data/move.ts`, `src/field/pokemon.ts`, `src/phases/move-phase.ts`
- Add locale texts in each language locale files.

### Screenshots/Videos
TBD (After translators' review)

## How to test the changes?
Manually. (Using overrides.ts)

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I add placeholders for them in locales?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-19 05:49 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "hitResultImmune": "{{pokemonName}} is unaffected!",
```suggestion
  "hitResultImmune": "{{pokemonName}} ist unversehrt!",
```

2024-08-19 05:50 UTC, CodeTappert commented on src/locales/de/move-trigger.ts
> +  "revivalBlessing": "{{pokemonName}} was revived!",
```suggestion
  "revivalBlessing": "{{pokemonName}} ist wieder fit!",
```

2024-08-19 05:51 UTC, mercurius-00 reviewed
zh

2024-08-19 05:51 UTC, mercurius-00 commented on src/locales/zh_TW/move-trigger.ts
> +  "revivalBlessing": "{{pokemonName}} was revived!",
```suggestion
  "revivalBlessing": "{{pokemonName}}復活了！",
```

2024-08-19 05:51 UTC, mercurius-00 commented on src/locales/zh_TW/battle.ts
> +  "hitResultImmune": "{{pokemonName}} is unaffected!",
```suggestion
  "hitResultImmune": "對于{{pokemonName}}，\n完全沒有效果！",
```

2024-08-19 05:51 UTC, mercurius-00 commented on src/locales/zh_CN/move-trigger.ts
> +  "revivalBlessing": "{{pokemonName}} was revived!",
```suggestion
  "revivalBlessing": "{{pokemonName}}复活了！",
```

2024-08-19 05:51 UTC, mercurius-00 commented on src/locales/zh_CN/battle.ts
> +  "hitResultImmune": "{{pokemonName}} is unaffected!",
```suggestion
  "hitResultImmune": "对于{{pokemonName}}，\n完全没有效果！",
```

2024-08-19 09:22 UTC, NicusPulcis approved these changes
italian localizations done : )

2024-08-19 09:22 UTC, NicusPulcis commented on src/locales/it/battle.ts
> +  "hitResultImmune": "{{pokemonName}} is unaffected!",
```suggestion
  "hitResultImmune": "{{pokemonName}} è incolume!",
```

2024-08-19 09:22 UTC, NicusPulcis commented on src/locales/it/move-trigger.ts
> +  "revivalBlessing": "{{pokemonName}} was revived!",
```suggestion
  "revivalBlessing": "{{pokemonName}} torna in forze!",
```

2024-08-19 11:30 UTC, Adri1 commented on src/locales/fr/move-trigger.ts
> +  "revivalBlessing": "{{pokemonName}} was revived!",
```suggestion
  "revivalBlessing": "{{pokemonName}} a repris connaissance\net est prêt à se battre de nouveau !",
```

2024-08-19 11:30 UTC, Adri1 commented on src/locales/fr/battle.ts
> +  "hitResultImmune": "{{pokemonName}} is unaffected!",
```suggestion
  "hitResultImmune": "{{pokemonName}} n’est pas affecté !",
```

2024-08-19 12:00 UTC, Adri1 approved these changes

2024-08-19 15:28 UTC, josericardo-fo commented on src/locales/pt_BR/battle.ts
> +  "hitResultImmune": "{{pokemonName}} is unaffected!",
```suggestion
  "hitResultImmune": "{{pokemonName}} não é afetado!",
```

2024-08-19 15:54 UTC, josericardo-fo commented on src/locales/pt_BR/move-trigger.ts
> +  "revivalBlessing": "{{pokemonName}} was revived!",
```suggestion
  "revivalBlessing": "{{pokemonName}} foi reanimado!",
```

2024-08-19 22:46 UTC, AsdarDevelops reviewed
Added Spanish

2024-08-19 22:46 UTC, AsdarDevelops commented on src/locales/es/move-trigger.ts
> +  "revivalBlessing": "{{pokemonName}} was revived!",
```suggestion
  "revivalBlessing": "¡{{pokemonName}} ha revivido!",
```

2024-08-19 22:48 UTC, AsdarDevelops reviewed
Unsure of what difference there is of this entry and the one right above it. Added.

2024-08-19 22:48 UTC, AsdarDevelops commented on src/locales/es/battle.ts
> +  "hitResultImmune": "{{pokemonName}} is unaffected!",
```suggestion
  "hitResultImmune": "¡No afecta a {{pokemonName}}!",
```

2024-08-21 00:03 UTC, Adri1 approved these changes

2024-08-21 04:43 UTC, CodeTappert approved these changes

2024-08-21 10:08 UTC, NicusPulcis approved these changes
italian is right (after seeing the screenshots)

2024-08-21 14:29 UTC, josericardo-fo approved these changes

2024-08-22 03:40 UTC, frutescens approved these changes

2024-08-22 16:25 UTC, KimJeongSun approved these changes

2024-08-22 16:25 UTC, KimJeongSun requested changes
need to resolve conflicts

2024-08-22 20:14 UTC, EnochG1 commented
@KimJeongSun Done. Please re-review.

2024-08-23 00:59 UTC, KimJeongSun approved these changes

2024-08-23 00:59 UTC, merged