[Refactor][Move] Improving Thunder Wave's Attribute
pagefaultgames/pokerogue pull request #3643
Opened 2024-08-19 15:11 UTC by frutescens

## What are the changes the user will see?
The user will be able to paralyze ground-type pokemon and unable to paralyze ghost-types if the Pokemon involved has the ability Normalize.

## Why am I making these changes?
Just a small improvement to code logic.

## What are the changes from a developer perspective?
Abilities that change the types of moves are applied when executing status moves.
Replaced StatusMoveTypeImmunity attribute with RespectTypeImmunity attribute. This checks if an opposing Pokemon has a type that is immune to the current type of the move. 

### Screenshots/Videos
https://github.com/user-attachments/assets/f38b6a90-36fc-43cb-ad96-3cc8d8afda14

https://github.com/user-attachments/assets/4553e8fe-4408-49bd-b7d2-e71cb893a627

https://github.com/user-attachments/assets/190b73aa-ab79-486e-9769-8ee74d436b38

## How to test the changes?
Use Thunder Wave with a Pokemon with the ability Normalize --> Ground Types no longer immune, Ghost Types immune
Use Thunder Wave with a Pokemon without the above ability --> Ground Types immune, Ghost Types not immune

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-19 15:25 UTC, schmidtc1 commented on src/field/pokemon.ts
>        ? this.getAttackTypeEffectiveness(move, source, false, false)
Is this ternary still necessary, if you have moved it to the move attribute instead?

2024-08-19 15:39 UTC, frutescens commented on src/field/pokemon.ts
>        ? this.getAttackTypeEffectiveness(move, source, false, false)
Yes, since it checks the value of typeEffectiveness.

2024-08-19 15:43 UTC, schmidtc1 commented on src/data/move.ts
> +      // The type of a status move is usually irrelevant but Thunder Wave is an exception and found in many movesets.
nit: "and found in many movesets" is not necessary to mention.

2024-08-19 15:47 UTC, schmidtc1 commented on src/test/moves/thunder_wave.test.ts
> +      enemyPokemon.status = new Status(StatusEffect.BURN);
is there a reason for using `enemyPokemon.status` instead of `game.override.enemyStatusEffect(StatusEffect.Burn)`

2024-08-19 15:50 UTC, frutescens commented on src/test/moves/thunder_wave.test.ts
> +      enemyPokemon.status = new Status(StatusEffect.BURN);
Ah, I forgot about that lol.

2024-08-19 15:53 UTC, schmidtc1 commented on src/test/moves/thunder_wave.test.ts
> +      expect(enemyPokemon.status).toBeUndefined();
```suggestion
      expect(enemyPokemon.status).toBeUndefined();
      game.doAttack(getMovePosition(game.scene, 0, Moves.THUNDER_WAVE));
      await game.phaseInterceptor.to(TurnEndPhase);

      expect(enemyPokemon.status).toBeUndefined();
```
Might be safe to expect status to be undefined before as well. This is applicable to all the other tests as well.

2024-08-19 16:10 UTC, KimJeongSun approved these changes
LGTM!

2024-08-19 16:27 UTC, frutescens commented on src/test/moves/thunder_wave.test.ts
> +      expect(enemyPokemon.status).toBeUndefined();
I think that even though this is a relatively small check + only adds a few milliseconds to the test, I think that because these Pokemon do not have items (thanks to earlier work in #3358) + the opponent Pokemon do not have abilities or passives that prevent Paralysis / lead to early recovery from Paralysis, the check is a little extra. I know its only a few ms but I am trying to be more efficient in my unit tests.

2024-08-19 16:30 UTC, schmidtc1 approved these changes

2024-08-19 17:07 UTC, frutescens commented on src/data/move.ts
> +      applyPreAttackAbAttrs(MoveTypeChangeAttr, source, target, this, new Utils.NumberHolder(1));
Yes, the last argument of applyPreAttackAbAttrs is where battle power is stored. It also changes the type of the move if ability conditions are met, which is why it is placed there. Here, the function is used only for its abilities to change the move's typing, which is why `new Utils.NumberHolder(1)` acts as a temporary address for battle power.

2024-08-19 17:08 UTC, frutescens commented on src/data/move.ts
> +      applyPreAttackAbAttrs(MoveTypeChangeAttr, source, target, this, new Utils.NumberHolder(1));
`export class MoveTypeChangeAttr extends PreAttackAbAttr {
  constructor(
    private newType: Type,
    private powerMultiplier: number,
    private condition?: PokemonAttackCondition
  ) {
    super(true);
  }

  applyPreAttack(pokemon: Pokemon, passive: boolean, defender: Pokemon, move: Move, args: any[]): boolean {
    if (this.condition && this.condition(pokemon, defender, move)) {
      move.type = this.newType;
      if (args[0] && args[0] instanceof Utils.NumberHolder) {
        args[0].value *= this.powerMultiplier;
      }
      return true;
    }

    return false;
  }
}`

2024-08-19 17:25 UTC, torranx commented on src/data/move.ts
> +      applyPreAttackAbAttrs(MoveTypeChangeAttr, source, target, this, new Utils.NumberHolder(1));
my point is status moves will not in any way have power so I don't see why this should be included here? It's counterintuitive and it's adding a completely different logic when it should care about the move's power

2024-08-19 17:38 UTC, frutescens commented on src/data/move.ts
> +      applyPreAttackAbAttrs(MoveTypeChangeAttr, source, target, this, new Utils.NumberHolder(1));
It is used to change the type of the move itself. The ability attribute application also changes the type of the move as well. The use of it here doesn't take into account the BP multiplier produced (as you see, Utils.IntegerHolder(1) goes literally unused). You can contrast it with how actual attacking moves use the BP multiplier just a few lines down.

2024-08-19 19:05 UTC, torranx commented on src/data/move.ts
> +      applyPreAttackAbAttrs(MoveTypeChangeAttr, source, target, this, new Utils.NumberHolder(1));
> It is used to change the type of the move itself. The ability attribute application also changes the type of the move as well.
That doesn't answer my argument, this function is solely used for **calculating move power**. Evident by the fact that we are returning `-1` early when the move is of status move. 

The use of it here doesn't take into account the BP multiplier produced (as you see, Utils.IntegerHolder(1) goes literally unused). You can contrast it with how actual attacking moves use the ability attribute / the resulting BP multiplier just a few lines down.

You said it yourself, it doesnt take into account the bp multiplier so why are you hijacking this function to add a **completely different logic**?

2024-08-19 20:52 UTC, flx-sta requested changes

2024-08-19 20:52 UTC, flx-sta commented on src/test/moves/thunder_wave.test.ts
> +    game.override.enemyMoveset([Moves.SPLASH, Moves.NONE, Moves.NONE, Moves.NONE]);
use chaining pls
```suggestion
    game.override.battleType("single")
      .starterSpecies(Species.PIKACHU)
      .moveset([Moves.THUNDER_WAVE])
      .enemyMoveset([Moves.SPLASH, Moves.NONE, Moves.NONE, Moves.NONE]);
```

2024-08-19 20:52 UTC, flx-sta commented on src/test/moves/thunder_wave.test.ts
> +    vi.spyOn(allMoves[Moves.THUNDER_WAVE], "accuracy", "get").mockReturnValue(100);
use the `MoveHelper` instead:

```suggestion
    game.move.forceHit()
```
<sub>Something like that. Just check how it's used elsewhere</sub>

2024-08-19 20:52 UTC, flx-sta commented on src/test/moves/thunder_wave.test.ts
> +      game.override.enemySpecies(Species.DIGLETT);
Use Chaining
```suggestion
      game.override.ability(Abilities.NORMALIZE).enemySpecies(Species.DIGLETT);
```

2024-08-19 20:52 UTC, flx-sta commented on src/test/moves/thunder_wave.test.ts
> +      game.override.enemyStatusEffect(StatusEffect.BURN);
Use chaining

```suggestion
      game.override.enemySpecies(Species.MAGIKARP).enemyStatusEffect(StatusEffect.BURN);
```

2024-08-19 20:52 UTC, flx-sta commented on src/test/moves/thunder_wave.test.ts
> +      game.override.enemySpecies(Species.HAUNTER);
use chaining:
```suggestion
      game.override.ability(Abilities.NORMALIZE).enemySpecies(Species.HAUNTER);
```

2024-08-19 20:52 UTC, flx-sta commented on src/test/moves/thunder_wave.test.ts
We are generally using `it()` instead of `test()`.

I'd prefer if you'd use the same

2024-08-19 21:34 UTC, torranx commented
I know I've said this to you before but I'll say this again: please don't immediately resolve comments that are actually not resolved/have no consensus made - also to allow others to chime in with what they think.

2024-08-19 21:51 UTC, frutescens commented
@torranx I did let you respond, but even after explaining my code and how it was different, you continued to repeat things that were easily disproven with a read of MoveTypeChangeAttr and move.ts' calculateBattlePower()'s code. I didn't want to continue repeating myself to someone who wasn't listening and that 'Resolve Conversation' was me peacefully exiting a pointless discussion. No offense, but it didn't seem like you wanted consensus in the first place.

2024-08-19 22:03 UTC, torranx commented
> @torranx I did let you respond, but even after explaining my code and how it was different, you continued to repeat things that were easily disproven with a read of MoveTypeChangeAttr and move.ts' calculateBattlePower()'s code. I didn't want to continue repeating myself to someone who wasn't listening and that 'Resolve Conversation' was me peacefully exiting a pointless discussion. No offense, but it didn't seem like you wanted consensus in the first place.

A mere response does not equate to a comment being resolved. I wasn't repeating things and was explaining to you as well what I meant. It seems to me that you're trying to say you were always right because you already explained your side.

You resolved the comment after your response on this:

> my point is status moves will not in any way have power so I don't see why this should be included here? It's counterintuitive and it's adding a completely different logic when it should only care about the move's power

How come I was repeating myself and didn't want to reach consensus? lol I was literally asking why it should be included in that function. 

If you can't take someone else's feedback and create a healthy conversation with it, that's a you problem. Anyways, I'm leaving this discussion here.

2024-08-19 22:26 UTC, flx-sta commented on src/data/move.ts
> +      applyPreAttackAbAttrs(MoveTypeChangeAttr, source, target, this, new Utils.NumberHolder(1));
@torranx Is this what you were aiming for ?
https://github.com/pagefaultgames/pokerogue/pull/3643/commits/56b1f0e676fa8677562632dca99753e2d57fab94

2024-08-20 01:46 UTC, flx-sta commented on src/test/moves/thunder_wave.test.ts
> +    game.move.forceHit();
I'm not sure it will work as simple like that. It might have to be called at a different spot. You probably wanna look at other tests that use it

2024-08-20 06:23 UTC, torranx commented on src/data/move.ts
> +      applyPreAttackAbAttrs(MoveTypeChangeAttr, source, target, this, new Utils.NumberHolder(1));
sort of yes, I will let you (and other devs) to decide where it should be placed. I only wanted that to be moved from the function because it is out of scope.

2024-08-20 14:41 UTC, flx-sta approved these changes

2024-08-21 04:56 UTC, frutescens commented
@torranx I was looking at this bug https://github.com/pagefaultgames/pokerogue/issues/3570 and I was thinking that it might be better to split MoveTypeChangeAbAttr into one attribute that changes the type and another that provides the BP multiplier. Would that interfere with calculateBasePower()?

2024-08-21 06:07 UTC, torranx commented
> @torranx I was looking at this bug #3570 and I was thinking that it might be better to split MoveTypeChangeAbAttr into one attribute that changes the type and another that provides the BP multiplier. Would that interfere with calculateBasePower()?

I would think so, yes. It needs to change type and multiply power simultaneously IIRC.

2024-08-21 19:26 UTC, innerthunder requested changes

2024-08-21 19:26 UTC, innerthunder commented on src/phases/move-effect-phase.ts
> +      applyPreAttackAbAttrs(MoveTypeChangeAttr, user, this.getTarget() ?? null, move);
If I'm reading this right, the move will be its changed type when passed into `target.apply` with this here, which I think would cause Aerilate (and similar abilities) to never be able to apply the power boost

2024-08-21 20:13 UTC, frutescens commented on src/phases/move-effect-phase.ts
> +      applyPreAttackAbAttrs(MoveTypeChangeAttr, user, this.getTarget() ?? null, move);
Discussed on Discord and fixed with a new conditional.

2024-08-21 21:22 UTC, innerthunder commented on src/data/ability.ts
> +      .attr(MoveTypeChangeAttr, Type.ICE, 1.2, (user, target, move) => move.defaultType === Type.NORMAL && !move.hasAttr(VariableMoveTypeAttr)),
Can you change `MoveTypeChangeAttr` to `MoveTypeChangeAbAttr` while you're at it?

2024-08-21 21:45 UTC, frutescens commented on src/data/ability.ts
> +      .attr(MoveTypeChangeAttr, Type.ICE, 1.2, (user, target, move) => move.defaultType === Type.NORMAL && !move.hasAttr(VariableMoveTypeAttr)),
Will do!

2024-08-21 21:58 UTC, innerthunder approved these changes
lgtm, but I think others should re-review before merging

2024-08-22 01:01 UTC, KimJeongSun approved these changes

2024-08-22 13:28 UTC, torranx reviewed
- couple minor comments
- ~not sure if there is no unintended side effect of `MoveTypeChangeAbAttr` because its being called in 2 different places~
- I personally don't like how there are both `typeMultiplier` and `typeEffectiveness` - there is no clear distinction between the two

other than those mentioned above, looks good

2024-08-22 13:28 UTC, torranx commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
docs on this please, esp the `args`

2024-08-22 13:28 UTC, torranx commented on src/data/move.ts
> +    args[0].value = typeEffectiveness;
```suggestion
    args[0].value = target.getAttackTypeEffectiveness(move.type, user);
```

2024-08-22 13:28 UTC, torranx commented on src/field/pokemon.ts
> +    const typeEffectiveness = new Utils.IntegerHolder(1);
```suggestion
    const typeEffectiveness = new Utils.NumberHolder(1);
```

2024-08-22 15:51 UTC, torranx commented on src/data/move.ts
> + */
I think this should be right above `apply()`, at least the params and returns

2024-08-23 23:49 UTC, frutescens commented
Closing since #3704 will fix things.

2024-08-23 23:49 UTC, closed without merging