[Refactor] Added ON_GET_HIT BattlerTagLapseType
pagefaultgames/pokerogue pull request #3655
Opened 2024-08-20 00:09 UTC by ElizaAlex

## What are the changes the user will see?
No changes user-side

## Why am I making these changes?
Beak Blast and Shell Trap both implement BattleTags that have some form of effect when the tag holder is hit but currently, each such effect needs to be handled and checked for individually. Adding a new LapseType to handle these similar tags all at once should help reduce duplicate code, standardize their implementations, and streamline future development.

## What are the changes from a developer perspective?
- BattlerTagLapseType.ON_GET_HIT has been added
- The implementations of Beak Blast and Shell Trap have been slightly adjusted to use this lapse type
- Instead of handling each tag individually, MoveEffectPhase now lapses all ON_GET_HIT tags using lapseTags()
- Minor utility functions have been added in Pokemon.ts and battler-tags.ts

## How to test the changes?
There should be no change in gameplay, so just proceed as you normally would and watch for any unexpected bugs.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

2024-08-20 12:32 UTC, torranx commented
Overlaps with https://github.com/pagefaultgames/pokerogue/pull/2559/

2024-08-21 10:07 UTC, DayKev requested changes
Some minor style consistency nits.

2024-08-21 10:07 UTC, DayKev commented on src/data/battler-tags.ts
> +    super(BattlerTagType.BEAK_BLAST_CHARGING, [ BattlerTagLapseType.PRE_MOVE, BattlerTagLapseType.TURN_END, BattlerTagLapseType.ON_GET_HIT], 1, Moves.BEAK_BLAST);
```suggestion
    super(BattlerTagType.BEAK_BLAST_CHARGING, [BattlerTagLapseType.PRE_MOVE, BattlerTagLapseType.TURN_END, BattlerTagLapseType.ON_GET_HIT], 1, Moves.BEAK_BLAST);
```

2024-08-21 10:07 UTC, DayKev commented on src/data/battler-tags.ts
> +function getMoveEffectPhaseData(pokemon : Pokemon) : {phase : MoveEffectPhase, attacker: Pokemon, move: Move } | null {
```suggestion
function getMoveEffectPhaseData(pokemon: Pokemon): {phase: MoveEffectPhase, attacker: Pokemon, move: Move} | null {
```

2024-08-21 10:07 UTC, DayKev commented on src/field/pokemon.ts
> +  isOpponentTo(target: Pokemon) : boolean {
```suggestion
  isOpponentTo(target: Pokemon): boolean {
```
Not sure I'm a fan of `isOpponentTo`, maybe just `isOpponent`? 🤔

2024-09-21 05:42 UTC, DayKev commented
Are you still around to update this PR? #2559 added a `HIT` lapse type, but didn't update the existing moves to use it.

2024-10-14 05:53 UTC, DayKev commented
After comparing to the `HIT` tag type added in 2559, this seems like an `AFTER_HIT` tag in regards to timing unlike the former which is more `ON_HIT`, so I renamed the tag from `ON_GET_HIT` to `AFTER_HIT`.

2024-10-14 05:55 UTC, DayKev submitted a review, later dismissed

2024-10-14 06:45 UTC, torranx reviewed
this could potentially open up a fix for https://github.com/pagefaultgames/pokerogue/issues/4552

2024-10-14 06:45 UTC, torranx commented on src/data/battler-tags.ts
> +  private triggerTrap(pokemon: Pokemon) {
please add docs here

2024-10-21 05:51 UTC, DayKev commented on src/data/battler-tags.ts
> +   * @returns `true` if invoked with the ON_GET_HIT lapse type; `false` otherwise
```suggestion
   * @returns `true` if invoked with the `AFTER_HIT` lapse type; `false` otherwise
```
Oops, missed this before.

2024-10-21 05:51 UTC, DayKev commented on src/field/pokemon.ts
> +  isOpponent(target: Pokemon): boolean {
```suggestion
  public isOpponent(target: Pokemon): boolean {
```

2024-10-21 06:13 UTC, DayKev approved these changes

2024-10-21 06:13 UTC, DayKev commented on src/data/battler-tags.ts
> +  private triggerTrap(pokemon: Pokemon) {
Would you ask for docs if the code was inlined?

2024-10-21 09:46 UTC, DayKev commented on src/data/battler-tags.ts
> +  private triggerTrap(pokemon: Pokemon) {
Tbh this shouldn't have even been pulled out into a separate function like that.

2024-10-21 09:46 UTC, DayKev approved these changes

2024-10-21 09:48 UTC, torranx approved these changes

2024-10-22 06:52 UTC, innerthunder approved these changes

2024-10-22 06:53 UTC, merged