[Balance] [QoL] [Feature] Allow mons to track and relearn used TMs
pagefaultgames/pokerogue pull request #3656
Opened 2024-08-20 00:36 UTC by Fontbane

## What are the changes the user will see?

- Player mons will be able to relearn TM moves previously taught to that mon during the run
- This will, of course, only track the TMs used after this patch is applied

## Why am I making these changes?

![image](https://github.com/user-attachments/assets/0d59d009-07b0-4855-8eef-36e3f506963a)

## What are the changes from a developer perspective?

- Adds a "fromTM" boolean parameter to the LearnMovePhase constructor (I imagine this would be very useful for other purposes too)
- Adds a "usedTMs" array to Pokemon data

### Screenshots/Videos

After teaching Trick Room to Mewtwo, then forgetting Trick Room for another move, then using a Memory Mushroom:
![image](https://github.com/user-attachments/assets/9f219d25-c8f0-4015-b85f-1f4ca6b75810)

## How to test the changes?

- Add TMs and Memory Mushroom to item reward overrides
- Use a TM
- Forget the move you learned from that TM
- Use Memory Mushroom

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I considered writing automated tests for the issue?
- [X] If I have text, did I add placeholders for them in locales?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-08-22 00:20 UTC, xsn34kzx requested changes
Had some minor requests. Was this tested already with an older save to make sure it doesn't do anything weird? It looks safe with the data handling so far, but I wanted to ask to be sure.

2024-08-22 00:20 UTC, xsn34kzx commented on src/field/pokemon.ts
> +    levelMoves = this.usedTMs?.length? this.usedTMs.filter(m => !levelMoves.includes(m)).concat(levelMoves) : levelMoves;
```suggestion
    if (Array.isArray(this.usedTMs) && this.usedTMs.length !== 0) {
      levelMoves = this.usedTMs.filter(m => !levelMoves.includes(m)).concat(levelMoves);
    }
```
Much safer and readable to make this an `if` rather than an extra ternary that, in the `false` case, just does an extra `levelMoves = levelMoves` assignment.

2024-08-22 00:20 UTC, xsn34kzx commented on src/phases/learn-move-phase.ts
> +    this.fromTM = fromTM || false;
```suggestion
    this.fromTM = fromTM ?? false;
```
NIT: Safer operator for this situation

2024-08-22 00:20 UTC, xsn34kzx commented on src/field/pokemon.ts
> +      this.usedTMs = dataSource.usedTMs || [];
```suggestion
      this.usedTMs = dataSource.usedTMs ?? [];
```
Duplicate NIT

2024-08-22 00:20 UTC, xsn34kzx commented on src/system/pokemon-data.ts
> +    this.usedTMs = source.usedTMs || [];
```suggestion
    this.usedTMs = source.usedTMs ?? [];
```
Duplicate NIT

2024-08-25 06:08 UTC, damocleas reviewed
Please resolve conversations and ping me on discord for approval when that is done

2024-08-25 23:13 UTC, Fontbane commented
> Had some minor requests. Was this tested already with an older save to make sure it doesn't do anything weird? It looks safe with the data handling so far, but I wanted to ask to be sure.

I tested it with older saves, works fine

2024-08-25 23:15 UTC, damocleas approved these changes

2024-08-27 17:14 UTC, xsn34kzx approved these changes

2024-08-27 23:35 UTC, damocleas approved these changes

2024-08-28 06:57 UTC, frutescens approved these changes

2024-09-02 23:25 UTC, merged