Qol/reroll targeting
pagefaultgames/pokerogue pull request #3666
Opened 2024-08-20 14:47 UTC by torranx

## What are the changes the user will see?
New option under display: Shop Post-Reroll Target

## Why am I making these changes?

[highly requested QoL](https://discord.com/channels/1125469663833370665/1235481427924095016), previous author is MIA

## What are the changes from a developer perspective?

no functional change, just a new option

### Screenshots/Videos

## How to test the changes?
get to the shop phase, set option and reroll

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I add placeholders for them in locales?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-20 15:17 UTC, Adri1 reviewed
French Added (to be tested in context)

2024-08-20 15:17 UTC, Adri1 commented on src/locales/fr/settings.ts
> +  "shop": "Shop"
```suggestion
  "shopRerollTarget": "Choix après relance",
  "items": "Obj. gratuits",
  "reroll": "Relance",
  "shop": "Obj. payants"
```

2024-08-20 15:28 UTC, flx-sta commented
Other settings have an enum for every option. It might make sense here too.

```ts
/**
 * Determines the cursor target after selecting the re-roll button
 */
export enum ShopPostRerollTarget {
   /** Cursor stays on re-roll button */ 
   REROLL,
   /** Cursor moves to the first item after re-roll */
    ITEMS,
    /** Cursor moves to the first shop item after re-roll */
    SHOP,
}

2024-08-20 15:32 UTC, CodeTappert commented on src/locales/de/settings.ts
> +  "shop": "Shop"
```suggestion
  "shopRerollTarget": "Shop Ziel nach Neurollen",
  "items": "Items",
  "reroll": "Neurollen",
  "shop": "Shop"
```

2024-08-20 16:05 UTC, torranx commented
Placing this back to draft, please pause on translations until PR is ready. I will also ask an updated translation from you guys @Adri1 @CodeTappert when it's ready.

2024-08-20 16:09 UTC, sodaMelon reviewed
added korean localization

2024-08-20 16:09 UTC, sodaMelon commented on src/locales/ko/settings.ts
> +  "shop": "Shop"
```suggestion
  "shopRerollTarget": "상점 갱신-후 타겟팅",
  "items": "아이템",
  "reroll": "갱신 버튼",
  "shop": "상점"
```

2024-08-20 18:46 UTC, torranx commented on src/locales/fr/settings.ts
> +  "shop": "Shop"
I've updated the keys, please suggest a new change. Thanks!

2024-08-20 18:46 UTC, torranx commented on src/locales/de/settings.ts
> +  "shop": "Shop"
I've updated the keys, please suggest a new change. Thanks!

2024-08-20 18:46 UTC, torranx commented on src/locales/ko/settings.ts
> +  "shop": "Shop"
I've updated the keys, please suggest a new change. Thanks!

2024-08-20 19:07 UTC, flx-sta requested changes

2024-08-20 19:07 UTC, flx-sta commented on src/system/settings/settings.ts
> +import { ShopCursorTarget } from "#app/enums/shop-cursor-target.js";
```suggestion
import { ShopCursorTarget } from "#app/enums/shop-cursor-target";
```

What a plague this is

2024-08-20 19:07 UTC, flx-sta commented on src/ui/modifier-select-ui-handler.ts
> +        }
I personally think using `set` in the name for a non setter function is confusing.
I'd recommend naming it `refreshCursorTarget()` or `updateCursorTarget()`

2024-08-20 19:07 UTC, flx-sta commented on src/ui/modifier-select-ui-handler.ts
> +import { ShopCursorTarget } from "#app/enums/shop-cursor-target.js";
```suggestion
import { ShopCursorTarget } from "#app/enums/shop-cursor-target";
```

💀

2024-08-20 20:11 UTC, flx-sta approved these changes
Code 🚀 
play-test 🚀 

<sub>BUT: I can already see the bug-reports coming in "THE CURSOR IS GONE!" as `check-team` is so far in the corner. Not your fault though</sub>

2024-08-20 20:20 UTC, mKroogz commented
> "THE CURSOR IS GONE!"

😱 😱 😱

2024-08-20 20:48 UTC, Adri1 commented on src/locales/fr/settings.ts
> +  "checkTeam": "Check Team"
```suggestion
  "shopCursorTarget": "Choix après relance",
  "items": "Obj. gratuits",
  "reroll": "Relance",
  "shop": "Boutique",
  "checkTeam": "Équipe"
```

2024-08-20 20:55 UTC, NicusPulcis approved these changes
italian localized :)

2024-08-20 20:55 UTC, NicusPulcis commented on src/locales/it/settings.ts
> +  "checkTeam": "Check Team"
```suggestion
  "shopCursorTarget": "Target Cursore Negozio",
  "items": "Oggetti",
  "reroll": "Rerolla",
  "shop": "Negozio",
  "checkTeam": "Controlla squadra"
```

2024-08-20 21:05 UTC, josericardo-fo commented on src/locales/pt_BR/settings.ts
> +  "checkTeam": "Check Team"
```suggestion
  "shopCursorTarget": "Alvo do Cursor da Loja",
  "items": "Itens",
  "reroll": "Atualizar",
  "shop": "Loja",
  "checkTeam": "Checar Time"
```

2024-08-20 21:14 UTC, torranx commented on src/locales/it/settings.ts
> +  "checkTeam": "Check Team"
issue with overlapping text
<img width="1335" alt="Screenshot 2024-08-21 at 5 13 53 AM" src="https://github.com/user-attachments/assets/b970cd97-8d94-4956-98f4-9808bea133bc">

2024-08-21 00:34 UTC, sodaMelon commented on src/locales/ko/settings.ts
> +  "checkTeam": "Check Team"
```suggestion
  "shopCursorTarget": "상점 커서 위치",
  "items": "아이템",
  "reroll": "갱신",
  "shop": "상점",
  "checkTeam": "Check Team"
```

2024-08-21 00:37 UTC, sodaMelon reviewed
added korean localization with "cursor"

2024-08-21 01:48 UTC, 40chyan reviewed
zhcn

2024-08-21 01:48 UTC, 40chyan commented on src/locales/zh_CN/settings.ts
> +  "checkTeam": "Check Team"
```suggestion
  "shopCursorTarget": "商店指针位置",
  "items": "道具",
  "reroll": "刷新",
  "shop": "购买",
  "checkTeam": "检查队伍"
```

2024-08-21 10:15 UTC, NicusPulcis commented on src/locales/it/settings.ts
> +  "checkTeam": "Check Team"
thanks for letting me know @torranx , i'll fix it rn

2024-08-21 10:17 UTC, NicusPulcis commented on src/locales/it/settings.ts
> +  "checkTeam": "Check Team"
Is it better like this @torranx ?
```suggestion
  "shopCursorTarget": "Target Cursore Negozio",
  "items": "Oggetti",
  "reroll": "Rerolla",
  "shop": "Negozio",
  "checkTeam": "Squadra"
```

2024-08-21 17:51 UTC, torranx commented on src/locales/es/settings.ts
> +  "checkTeam": "Check Team"
Overlapping text
<img width="1342" alt="Screenshot 2024-08-22 at 1 51 15 AM" src="https://github.com/user-attachments/assets/31ed2435-bd1e-4456-8305-a69a293ae803">

2024-08-21 19:21 UTC, frutescens commented
Tested and it looks good. If it's alright for me to ask, why not have the cursor of modifier-select-ui-hander remember its last held position?

2024-08-22 14:00 UTC, torranx commented
> Tested and it looks good. If it's alright for me to ask, why not have the cursor of modifier-select-ui-hander remember its last held position?

I've just tested this rn and if I;m not mistaken, this only matters if the shop is rerolled yes? 
- [One user commented](https://discord.com/channels/1125469663833370665/1235481427924095016/1248315812985438329) that you can accidentally reroll with this
- which leads to [this suggestion](https://discord.com/channels/1125469663833370665/1235481427924095016/1249352981015695500) that I agree with

I think this will be a good starting point for this feature and we could adjust it eventually from user feedback.

2024-08-22 14:07 UTC, DayKev commented on src/battle-scene.ts
> +  public shopCursorTarget: number = ShopCursorTarget.CHECK_TEAM;
Shouldn't the default be how it works now?

2024-08-22 14:09 UTC, torranx commented on src/battle-scene.ts
> +  public shopCursorTarget: number = ShopCursorTarget.CHECK_TEAM;
It's been discussed [here](https://discord.com/channels/1125469663833370665/1273029080828084234/1275479769596821598)

2024-08-22 14:15 UTC, DayKev commented on src/battle-scene.ts
> +  public shopCursorTarget: number = ShopCursorTarget.CHECK_TEAM;
Makes sense. 👍

2024-08-22 14:15 UTC, DayKev approved these changes
Tested it and it works, seems good.

2024-08-22 14:50 UTC, frutescens commented
That makes sense, and it looks and works good to me. But, because users can no longer access settings from the shop, they may run into issues when moving from one run to another. Wouldn't it be more straightforward to add a delay before processing inputs?

2024-08-22 15:32 UTC, torranx commented
> That makes sense, and it looks and works good to me. But, because users can no longer access settings from the shop, they may run into issues when moving from one run to another. Wouldn't it be more straightforward to add a delay before processing inputs?

I can open settings just fine (had to rebase to beta in case I was missing something):


https://github.com/user-attachments/assets/b5a15c20-bd54-4606-a400-ff426048dfeb

2024-08-22 15:34 UTC, torranx commented
F 
branch is still broken

2024-08-22 15:41 UTC, frutescens commented
Oh, I'm dumb. Users can no longer access the egg gachas. Sorry, I'm going to drink my caffeine and send an approval in once you're done cleaning up.

2024-08-22 15:42 UTC, torranx commented
PR FIXED!

2024-08-22 16:20 UTC, KimJeongSun approved these changes
LGTM! ( and I love it )

2024-08-22 16:25 UTC, frutescens approved these changes

2024-08-22 16:26 UTC, merged