[QoL] One Pokerus Pokemon for Every Generation
pagefaultgames/pokerogue pull request #3675
Opened 2024-08-21 00:22 UTC by mKroogz

## What are the changes the user will see?
Pokerus is spread out 1 pokemon per gen on pokerus generation.

## Why am I making these changes?
This is a quite highly requested feature and I believe in the reasoning behind it.
-Being able to have a pokerus mon for single gen challenges
-Encouraging people to use more mons spread across gens
-WE NO LONGER HAVE TO CHECK FOR DUPES IN GENERATION LOGIC
-Honestly doesn't break balance especially still randomized
-Again just giga requested :)

## What are the changes from a developer perspective?
-Changed Pokerus cursor objects to 9 instead of 3 (1 per gen)
-Changed generation loop and logic to be gen based and use "this.allspecies" for filtered by gen mons
-NO LONGER DUPE CHECK 😎  (because each of the 9 mons will be from a specific gen so no dupe chance)

### Screenshots/Videos
![image](https://github.com/user-attachments/assets/aa35f4db-e1dd-4612-ab49-574e050ab776)
![image](https://github.com/user-attachments/assets/fb977ac8-c67f-47f2-9941-585f2b814ea9)
![image](https://github.com/user-attachments/assets/c6a7822f-4aae-40ef-a882-c9e1823c20b1)

## How to test the changes?
Basically just boot it up!  
You can see all 9 pokemon whether you've caught them or not, 
but if you want to test a 4 mon party with the rus,
import the everything data and it runs smooth :) 

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I add placeholders for them in locales?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-21 15:14 UTC, schmidtc1 commented
Likely relevant: #3501

2024-08-21 18:55 UTC, schmidtc1 requested changes

2024-08-21 18:55 UTC, schmidtc1 commented on src/ui/starter-select-ui-handler.ts
> +        generateSpecies();
You can take the code out of `generateSpecies()` since you removed the do-while loop. Just place `randomSpeciesId`, `currentGenSpecies`, and `species` in `const` variables

2024-08-21 20:12 UTC, mKroogz commented on src/ui/starter-select-ui-handler.ts
> +        generateSpecies();
You are so right!  I'm gonna do that right away.  :)

2024-08-21 22:03 UTC, schmidtc1 approved these changes
Lgtm, only concern would be overlap with #3501

2024-08-22 17:41 UTC, frutescens commented
Hi! PR #3501 has been merged into the beta branch so hopefully your work will continue. :)

2024-08-22 17:55 UTC, damocleas commented
Would like to ask this only be 5 pokemon, 9 feels a bit too high, and I feel this actually discourages using any pokemon that doesn't have it in a run..

2024-08-22 18:01 UTC, mKroogz commented
> Hi! PR #3501 has been merged into the beta branch so hopefully your work will continue. :)

Yay I'm gonna keep working on it then :)

2024-08-22 18:12 UTC, frutescens commented
Hi! The balance team will be adding an update that will increase the number of daily Pokerus starters to 5. I think that it might be good for there to be a check to make sure these 5 Pokerus starters are all from different generations. Would you be interested in changing your PR to focus on that? TY!!

2024-08-22 21:26 UTC, mKroogz commented
> Hi! The balance team will be adding an update that will increase the number of daily Pokerus starters to 5. I think that it might be good for there to be a check to make sure these 5 Pokerus starters are all from different generations. Would you be interested in changing your PR to focus on that? TY!!

This sounds good to me I can do that

2024-08-22 22:28 UTC, DayKev commented
> -Being able to have a pokerus mon for single gen challenges

Maybe challenges should have a way to modify which Pokémon have pokerus, and then if you're doing a monogen challenge it can check to see if there's a Pokémon of that gen with pokerus and if not add pokerus to one of the mons in that gen.
It would be part of a different PR though.

2024-09-15 06:42 UTC, Tempo-anon requested changes
More pokerus mons is good but 9 feels a bit too many. I do like the fact that they're more distributed throughout the generations though.

2024-09-15 10:35 UTC, MokaStitcher commented
this code is quite out of date, starter select now calls an external function that gets the Pokerus species
https://github.com/pagefaultgames/pokerogue/blob/ddf97fd8f6129dfc1bab54da15f8c41655ed7380/src/ui/starter-select-ui-handler.ts#L927

FYI the number of Pokerus mons was just updated from 3 to 5 in #4268 

Can you update your PR to leave that number at 5 but still add your logic to `getPokerusSpecies` that makes sure they all come from different gens?

2024-10-07 18:05 UTC, closed without merging

2024-10-07 18:05 UTC, Tempo-anon commented
Going to close this since the PR is a bit out of date and the number of pokerus starters has been increased already.