[Unit Test] Add `forceEnemyMove` Game Manager util
pagefaultgames/pokerogue pull request #3678
Opened 2024-08-21 09:10 UTC by innerthunder

## What are the changes the user will see?

No user-facing changes; this just adds a tool to help with integration testing

## Why am I making these changes?

Unit tests at the moment are very limited in terms of controlling the enemy's actions. The vast majority of tests rely on using overrides to fill enemy movesets with four copies of the same move to force that move, and if the enemy needs to use more than one unique move during a test, moveset overrides would have to be set with every turn. The limitations from this lack of control are especially apparent, though, in tests with double battles:
- If the enemy is using a single-target move, there is currently no way to force the enemy to target a specific Pokemon on the field.
- Forcing moves via overrides is impractical when enemies in a double battle need to use different moves in one turn.

The `forceEnemyMove` util gives the test writer much more control in these situations while also cutting down on the enemy moveset overrides needed to carry out complex test cases.

## What are the changes from a developer perspective?

- `test/utils/gameManager`:
  - New `forceEnemyMove` util function forces the next enemy selecting a move to use a specific move. This also includes an optional `target` argument to force the enemy to use the given move against the given target (if the move is single-targeted).
  - Renamed `forceOpponentToSwitch` to `forceEnemyToSwitch` to match conventions with gameManager's enemy override functions as well as `forceEnemyMove`.
- `phases/enemy-command-phase`: Added getter for `fieldIndex` in support of `forceEnemyMove`
- TODO: update unit tests to incorporate `forceEnemyMove` and reduce calls to `override.enemyMoveset`

### Screenshots/Videos

N/A

## How to test the changes?

`npm run test`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue? (...)
- [n/a] If I have text, did I add placeholders for them in locales?
- [ ] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [n/a] Are the changes visual?
  - [n/a] Have I provided screenshots/videos of the changes?

2024-08-21 15:29 UTC, flx-sta requested changes

2024-08-21 15:29 UTC, flx-sta commented on src/test/utils/gameManager.ts
> +import { getMoveTargets } from "#app/data/move.js";
```suggestion
import { Moves } from "#app/enums/moves";
import { EnemyCommandPhase } from "#app/phases/enemy-command-phase";
import { getMoveTargets } from "#app/data/move";
```
💀

2024-08-21 15:29 UTC, flx-sta commented on src/test/utils/gameManager.ts
> +    const enemy = this.scene.getEnemyField()[(this.scene.getCurrentPhase() as EnemyCommandPhase).getFieldIndex()];
I'm not a fan of this `this.scene.getCurrentPhase() as EnemyCommandPhase`. Instead the method should be re-written:
```ts
  /* Phase Functions */
  getCurrentPhase<P extends Phase = Phase>(): P | null {
    return this.currentPhase ? this.currentPhase as P : null;
  }
```

So it can be called like this:
```ts
this.scene.getCurrentPhase<EnemyCommandPhase>();
```

2024-08-21 15:29 UTC, flx-sta commented on src/phases/enemy-command-phase.ts
> +  getFieldIndex(): integer {
```suggestion
  getFieldIndex(): number {
```

2024-08-21 19:14 UTC, innerthunder commented on src/test/utils/gameManager.ts
> +    const enemy = this.scene.getEnemyField()[(this.scene.getCurrentPhase() as EnemyCommandPhase).getFieldIndex()];
Is this PR the place to change this? This pattern's used a lot within the codebase...

2024-08-21 19:49 UTC, flx-sta commented on src/test/utils/gameManager.ts
> +    const enemy = this.scene.getEnemyField()[(this.scene.getCurrentPhase() as EnemyCommandPhase).getFieldIndex()];
> The PR is self-contained and cannot be split into smaller PRs?

I didn't know the extend of that change. All good

2024-09-04 08:51 UTC, DayKev approved these changes

2024-09-04 14:35 UTC, Tempo-anon approved these changes

2024-09-04 17:56 UTC, frutescens approved these changes

2024-09-04 17:57 UTC, merged