Adds ribbon in starter screen if mon has beat classic mode
pagefaultgames/pokerogue pull request #370
Opened 2024-05-01 04:08 UTC by shayebeadling

Heard lots of people liking the idea of rewarding classic runs so this is a super simple implementation that could get the ball rolling;
1. Adds a winCount variable in the dexEntry object to keep track of classic wins on a mon.
2. Adds a red ribbon that shows on an entry if the winCount > 0.

I implore anyone that is more artistically inclined to make a better ribbon if this idea is adopted, cause mine looks a crewmate from among us.

![image](https://github.com/pagefaultgames/pokerogue/assets/16782886/9e5b1602-f1b4-40fa-a2d5-290237907d41)

IMPORTANT NOTE: This does not include the incrementation on a victory, and I imagine the DB would have to have this field added as well.

2024-05-01 07:22 UTC, Akuma-Reiki commented
Good launching point!
Would suggest something like 
```for (const pokemon of this.scene.getParty()) {
              const speciesId = getPokemonSpecies(pokemon.species.speciesId)
              this.scene.gameData.incrementStarterWinCount(speciesId);
            }```
in phases.ts line 3498

and then something like
```incrementStarterWinCount(species: PokemonSpecies):void {
  const speciesWinCount = this.dexData[species.speciesId].winCount;

    if(Number.isNaN(speciesWinCount))
      this.dexData[species.speciesId].winCount=0;
    
    this.dexData[species.speciesId].winCount++;
    console.log(this.dexData[species.speciesId].winCount);
  }```
  
  at line 1081 of game-data.ts
  
  Played around with those a bit and could make it show the ribbon upon beating classic mode, but it didn't apply it to the last pokemon
  I think the way around this is by making it async / a promise
  
  
Also think that winCount would be better as starterData rather than dexData, so if you win with ivysaur, you get the ribbon on bulbasaur

2024-05-01 17:54 UTC, Akuma-Reiki requested changes
1083 of game-data.ts seems to cause a freeze / crash if the pokemon is evolved.
Perhaps some way of finding the species ID of the prevolution of the pokemon similar to how candy does it?

```
incrementStarterWinCount(species: PokemonSpecies): void {
    const hasPrevolution = pokemonPrevolutions.hasOwnProperty(species.speciesId);
    if (!hasPrevolution){
      if (!this.starterData[species.speciesId].winCount) 
        this.starterData[species.speciesId].winCount = 0;
      this.starterData[species.speciesId].winCount++;
    }
    
   //logic for getting the prevolution species ID and then updating the wincount for it

  }
```

2024-05-01 18:20 UTC, Akuma-Reiki commented
working with Brain Frog to get a better version of this, but this has the functionality

2024-05-01 18:33 UTC, Akuma-Reiki requested changes
```
incrementStarterWinCount(species: PokemonSpecies): void {
    const hasPrevolution = pokemonPrevolutions.hasOwnProperty(species.speciesId);
    const starterIndex = hasPrevolution ? getPokemonSpecies(pokemonPrevolutions[species.speciesId]).speciesId : species.speciesId ;

    if (!this.starterData[starterIndex].winCount) 
        this.starterData[starterIndex].winCount = 0;
    this.starterData[starterIndex].winCount++;
  }
```

Me and Brain Frog got this working, should work with the current call of the function in phases.ts

only direction to go from here is maybe changing the champion ribbon icon

2024-05-01 19:10 UTC, Akuma-Reiki approved these changes
lgtm !

2024-05-06 16:51 UTC, TempsRay commented on src/phases.ts
> +            for (let pokemon of this.scene.getParty()) {
Maybe here could be where the 5 egg voucher per new ribbon awarded can go? Something like this?

```ts
for (let pokemon of this.scene.getParty()) {
  const rootSpeciesId = pokemon.getRootSpeciesId(true);
  if (this.scene.gameData.starterData[rootSpeciesId] == 0) {
    this.scene.pushPhase(new ModifierRewardPhase(this.scene, modifierTypes.VOUCHER_PLUS));
  }
}
```

2024-05-06 21:13 UTC, shayebeadling commented
OK the way that this behaves now is winning in classic with a mon will reward them, and any prevolution starters of them with a ribbon. If it is their first win, it displays a phase in the postgame that rewards you with a 5-pull voucher

2024-05-07 01:29 UTC, bennybroseph commented
Looks good on my end. Tested all the combos I could think. I always got the expected tickets including the final 10x for beating classic in general.

Two starters who have never beaten classic. Expected 2 5x tickets

https://github.com/pagefaultgames/pokerogue/assets/13838608/49d6d0cf-bd61-47d2-9e99-39da25a5620b

Two starters who have never beaten classic and one that evolved. Expected 3 5x tickets

https://github.com/pagefaultgames/pokerogue/assets/13838608/205618fc-a58a-4eda-8bfc-ca6f66ad0aba

No starters who have beaten classic but one that evolved. Expected 1 5x tickets 

https://github.com/pagefaultgames/pokerogue/assets/13838608/67553422-8304-4d36-8b5e-bf71402f71e2

Six starters who have never beaten classic. Expected 6 5x tickets

https://github.com/pagefaultgames/pokerogue/assets/13838608/c49f390e-e334-4ec8-ae04-659d3337f303

One starter that has never beater classic and one that has but has now evolved. Expected 1 5x tickets

https://github.com/pagefaultgames/pokerogue/assets/13838608/6926b0d9-bf2c-4632-8165-8ca28287b778

All starters have beaten classic but they are different forms/evolutions. Expected 0 5x tickets

https://github.com/pagefaultgames/pokerogue/assets/13838608/c7dffdc8-9fda-4e74-a316-98dcd5b552db

One starter who has never beaten classic and a freshly caught pokemon that has never beaten classic. Expected 2 5x tickets

https://github.com/pagefaultgames/pokerogue/assets/13838608/2d769218-783b-4edf-a58b-0d3f9e3b496d

2024-05-07 04:05 UTC, TempsRay approved these changes
The next big version update!

2024-05-07 04:44 UTC, Flashfyre approved these changes

2024-05-07 04:44 UTC, merged