[Refactor] Make Move Properties Read-Only
pagefaultgames/pokerogue pull request #3704
Opened 2024-08-23 08:11 UTC by innerthunder

## What are the changes the user will see?

No user-facing changes, except that future move implementations may be less bug-prone in the future.

## Why am I making these changes?

When a Pokemon uses a move, it invokes the corresponding `Move` object from a shared cache `allMoves` directly by reference. The game pulls all of the move's base properties, including type, category, power, effect chance, accuracy, and priority, from that shared cache when resolving the move's damage and effects.

Given that every move is resolved based on data from `allMoves`, it's important that the data in `allMoves` remains consistent so that multiple uses of the move, simulated or otherwise, yield the same outcome. However, the fact that virtually every field in the `Move` class is `public` runs counter to this requirement. With the way `allMoves` is passed around, moves' properties can be modified virtually anywhere in the codebase, and at any phase in the game's battle sequence. This level of freedom leaves new Move implementations prone to bugs and generally encourages bad coding practices.

This lack of restriction with class fields is unfortunately a common pattern in the codebase, but hopefully changes like this PR inspire others to work toward breaking this pattern.

## What are the changes from a developer perspective?

In `data/move`: The following `Move` fields are now read-only (WIP)
  - [x] `type`
  - [x] `category`
  - [ ] `power`
  - [ ] `accuracy`
  - [ ] `pp`
  - [ ] `chance`
  - [ ] `priority`

Some move and ability attributes have been updated (or, in some cases, rewritten) to account for the new restrictions introduced by these changes. These mostly have to do with move-type-changing effects (e.g. Hidden Power, Aerilate, etc.) for the time being, but that is subject to change.

### Screenshots/Videos

N/A

## How to test the changes?

`npm run test` (Unit tests WIP)

## Checklist
- [x] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
  - #3643 
  - #3417 
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
  - considered, but not written :(
- [x] If I have text, did I add placeholders for them in locales?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [n/a] Are the changes visual?
  - [n/a] Have I provided screenshots/videos of the changes?

2024-08-24 08:25 UTC, innerthunder commented
### Update: Thousand Arrows Type Hint Fix

Thousand Arrows now correctly calculates its type effectiveness with and without Levitate revealed.

Turn 1:

![image](https://github.com/user-attachments/assets/6125f332-4c93-4369-98f9-9face416b11b)

Turn 2: After using Earthquake to reveal Levitate

![image](https://github.com/user-attachments/assets/22653701-d514-4dd6-a928-5de30aa1d030)

2024-08-25 05:39 UTC, frutescens approved these changes
Would it be alright if you added flx and I as co-authors to the PR? It's up to you though.

2024-08-25 09:46 UTC, torranx reviewed
looks good so far, just a few questions:
- Is there a reason why we're using `IntegerHolder` instead of `NumberHolder`?
- I didn't see any way for this but confirming otherwise, would these changes make it possible to get the move's type in the context of tests?

2024-08-25 09:46 UTC, torranx commented on src/data/ability.ts
> +        if (move.getMove() instanceof AttackMove && pokemon.getAttackTypeEffectiveness(move!.getMove().type, opponent, true) >= 2) { // TODO: is this bang correct?
can probably remove the bang here by adding a condition `move`

2024-08-25 09:56 UTC, innerthunder commented
> * Is there a reason why we're using `IntegerHolder` instead of `NumberHolder`?

It's just what's used for variable-category moves, and I wanted to keep the two consistent. If we're looking to phase out `IntegerHolder`, I can change them both, though.

> * I didn't see any way for this but confirming otherwise, would these changes make it possible to get the move's type in the context of tests?

`Pokemon#getMoveType` should do exactly this, so you can do something like:

```ts
const playerPokemon = game.scene.getPlayerPokemon()!;
vi.spyOn(playerPokemon, "getMoveType");

// have playerPokemon use Moves.TACKLE...

expect(playerPokemon.getMoveType).toHaveReturnedWith(Type.ELECTRIC);
```

(...in fact, I can add something like this to the Galvanize tests 🤔 )

2024-08-25 10:08 UTC, torranx commented
> It's just what's used for variable-category moves, and I wanted to keep the two consistent. If we're looking to phase out IntegerHolder, I can change them both, though.

I haven't looked at the 2 holders yet if they have significant difference but we're phasing out `integer` type in favor of `number` so..

> Pokemon#getMoveType should do exactly this, so you can do something like:

nice, would love to see it in action here (so there would also be a reference for other contributors/devs)

2024-08-25 14:10 UTC, DayKev commented
> > It's just what's used for variable-category moves, and I wanted to keep the two consistent. If we're looking to phase out IntegerHolder, I can change them both, though.
> 
> I haven't looked at the 2 holders yet if they have significant difference but we're phasing out `integer` type in favor of `number` so..

They're identical (and IH has no reason to exist lmao).

![image](https://github.com/user-attachments/assets/142b2e13-2474-4213-b2e4-36eb0ddd562d)

2024-08-25 18:41 UTC, xsn34kzx reviewed
Pretty much only had one NIT. I'll follow up after a play-testing later 🫡

2024-08-25 18:41 UTC, xsn34kzx commented on src/data/move.ts
> + */
```suggestion
 * into consideration (i.e. {@linkcode https://bulbapedia.bulbagarden.net/wiki/Thunder_Wave_(move) | Thunder Wave})
 * @extends MoveAttr
 */
```
NIT: Minor additional doc line

2024-08-25 19:55 UTC, torranx approved these changes
looks good

2024-08-25 20:16 UTC, DayKev requested changes

2024-08-25 20:16 UTC, DayKev commented on src/test/moves/effectiveness.test.ts
> +});
```suggestion
import { allMoves } from "#app/data/move";
import { getPokemonSpecies } from "#app/data/pokemon-species";
import { TrainerSlot } from "#app/data/trainer-config";
import { Abilities } from "#app/enums/abilities";
import { Moves } from "#app/enums/moves";
import { Species } from "#app/enums/species";
import * as Messages from "#app/messages";
import GameManager from "#test/utils/gameManager";
import Phaser from "phaser";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";

function testMoveEffectiveness(game: GameManager, move: Moves, targetSpecies: Species,
  expected: number, targetAbility: Abilities = Abilities.BALL_FETCH): void {
  // Suppress getPokemonNameWithAffix because it calls on a null battle spec
  vi.spyOn(Messages, "getPokemonNameWithAffix").mockReturnValue("");
  game.override.enemyAbility(targetAbility);
  const user = game.scene.addPlayerPokemon(getPokemonSpecies(Species.SNORLAX), 5);
  const target = game.scene.addEnemyPokemon(getPokemonSpecies(targetSpecies), 5, TrainerSlot.NONE);

  expect(target.getMoveEffectiveness(user, allMoves[move])).toBe(expected);
}

describe("Moves - Type Effectiveness", () => {
  let phaserGame: Phaser.Game;
  let game: GameManager;

  beforeAll(() => {
    phaserGame = new Phaser.Game({
      type: Phaser.HEADLESS,
    });
    game = new GameManager(phaserGame);
    game.override.ability(Abilities.BALL_FETCH);
  });

  afterEach(() => {
    game.phaseInterceptor.restoreOg();
  });

  it("Normal-type attacks are neutrally effective against Normal-type Pokemon",
    () => testMoveEffectiveness(game, Moves.TACKLE, Species.SNORLAX, 1)
  );

  it("Normal-type attacks are not very effective against Steel-type Pokemon",
    () => testMoveEffectiveness(game, Moves.TACKLE, Species.REGISTEEL, 0.5)
  );

  it("Normal-type attacks are doubly resisted by Steel/Rock-type Pokemon",
    () => testMoveEffectiveness(game, Moves.TACKLE, Species.AGGRON, 0.25)
  );

  it("Normal-type attacks have no effect on Ghost-type Pokemon",
    () => testMoveEffectiveness(game, Moves.TACKLE, Species.DUSCLOPS, 0)
  );

  it("Normal-type status moves are not affected by type matchups",
    () => testMoveEffectiveness(game, Moves.GROWL, Species.DUSCLOPS, 1)
  );

  it("Electric-type attacks are super-effective against Water-type Pokemon",
    () => testMoveEffectiveness(game, Moves.THUNDERBOLT, Species.BLASTOISE, 2)
  );

  it("Electric-type attacks are doubly super-effective against Water/Flying-type Pokemon",
    () => testMoveEffectiveness(game, Moves.THUNDERBOLT, Species.GYARADOS, 4)
  );

  it("Electric-type attacks are negated by Volt Absorb",
    () => testMoveEffectiveness(game, Moves.THUNDERBOLT, Species.GYARADOS, 0, Abilities.VOLT_ABSORB)
  );
});

```
Before:
![image](https://github.com/user-attachments/assets/4c61f0c0-9e11-4c3b-995e-c6ebe1341a1d)
After:
![image](https://github.com/user-attachments/assets/ec63b9ed-504f-459d-aa4d-dbf1bdb7eda3)

2024-08-25 20:16 UTC, DayKev commented on src/test/moves/thunder_wave.test.ts
> +});
```suggestion
import { StatusEffect } from "#app/data/status-effect";
import { Abilities } from "#app/enums/abilities";
import { EnemyPokemon } from "#app/field/pokemon";
import { Moves } from "#enums/moves";
import { Species } from "#enums/species";
import GameManager from "#test/utils/gameManager";
import Phaser from "phaser";
import { afterEach, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { SPLASH_ONLY } from "../utils/testUtils";

const TIMEOUT = 20 * 1000;

describe("Moves - Thunder Wave", () => {
  let phaserGame: Phaser.Game;
  let game: GameManager;

  beforeAll(() => {
    phaserGame = new Phaser.Game({
      type: Phaser.HEADLESS,
    });
  });

  afterEach(() => {
    game.phaseInterceptor.restoreOg();
  });

  beforeEach(() => {
    game = new GameManager(phaserGame);
    game.override
      .battleType("single")
      .starterSpecies(Species.PIKACHU)
      .moveset([Moves.THUNDER_WAVE])
      .enemyMoveset(SPLASH_ONLY);
  });

  // References: https://bulbapedia.bulbagarden.net/wiki/Thunder_Wave_(move)

  it("paralyzes non-statused Pokemon that are not Ground types", async () => {
    game.override.enemySpecies(Species.MAGIKARP);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status?.effect).toBe(StatusEffect.PARALYSIS);
  }, TIMEOUT);

  it("does not paralyze if the Pokemon is a Ground-type", async () => {
    game.override.enemySpecies(Species.DIGLETT);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status).toBeUndefined();
  }, TIMEOUT);

  it("does not paralyze if the Pokemon already has a status effect", async () => {
    game.override.enemySpecies(Species.MAGIKARP).enemyStatusEffect(StatusEffect.BURN);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status?.effect).not.toBe(StatusEffect.PARALYSIS);
  }, TIMEOUT);

  it("affects Ground types if the user has Normalize", async () => {
    game.override.ability(Abilities.NORMALIZE).enemySpecies(Species.DIGLETT);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status?.effect).toBe(StatusEffect.PARALYSIS);
  }, TIMEOUT);

  it("does not affect Ghost types if the user has Normalize", async () => {
    game.override.ability(Abilities.NORMALIZE).enemySpecies(Species.HAUNTER);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status).toBeUndefined();
  }, TIMEOUT);
});

```
I realize at the end of this I could made a PR for these test changes separate from the rest of my review but... oh well.

2024-08-25 23:17 UTC, DayKev approved these changes

2024-08-25 23:18 UTC, frutescens approved these changes

2024-08-26 01:44 UTC, torranx approved these changes

2024-08-26 02:11 UTC, merged