[Misc] Skip Eternatus dialogue again
pagefaultgames/pokerogue pull request #3716
Opened 2024-08-23 20:19 UTC by frutescens

## What are the changes the user will see?
The user will be now able to skip Eternatus' dialogue again. 

## Why am I making these changes?
My mess. 

## What are the changes from a developer perspective?
The function for Eternatus' dialogue now checks if the dialogue set to be skipped and has been seen by the user before playing the dialogue. If it is set to be skipped, it skips the dialogue and begins the battle like before. 

### Screenshots/Videos

https://github.com/user-attachments/assets/dcbb92e4-5548-4611-b464-468aef613cd3

## How to test the changes?
Fight Eternatus with the settings to skip dialogue on. And then fight Eternatus with the settings to skip dialogue off.
Also, check if a new seenDialogue entry has been created.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-23 20:27 UTC, flx-sta requested changes

2024-08-23 20:27 UTC, flx-sta commented on src/phases/encounter-phase.ts
> +          const count = 5643853 + this.scene.gameData.gameStats.classicSessionsPlayed;
why `5643853` as a minum + the sessions?

2024-08-23 20:27 UTC, flx-sta commented on src/phases/encounter-phase.ts
> +          const cycleCount = count.toLocaleString() + ordinalIndex;
shouldn't the ordinal be saved a translation key, rather than some hard-coded strings?
there is a tool at hand for that
https://www.i18next.com/translation-function/plurals
```ts
{
  "key_zero": "zero",
  "key_one": "singular",
  "key_two": "two",
  "key_few": "few",
  "key_many": "many",
  "key_other": "other"
}
```

----

for yours it would be 
```

```json
{
  "ordinal_one": "st",
  "ordinal_two": "nd",
  "ordinal_three": "rd",
  "ordinal_other": "th"
}
```

For the count you could provide the formular instead of the actual count so it can handle stuff like `21`, `22` etc.

That way you also don't have to check the language that is being resolved

2024-08-23 20:54 UTC, frutescens commented on src/phases/encounter-phase.ts
> +          const count = 5643853 + this.scene.gameData.gameStats.classicSessionsPlayed;
5643853 was the original number used.

2024-08-23 20:56 UTC, frutescens commented on src/phases/encounter-phase.ts
> +          const cycleCount = count.toLocaleString() + ordinalIndex;
this can handle 21, 22, etc. + other languages don't seem to use these ordinals. 
the only reason why spanish and italian are there is because they aren't translated yet

2024-08-23 22:44 UTC, flx-sta commented on src/phases/encounter-phase.ts
> +          const cycleCount = count.toLocaleString() + ordinalIndex;
I think it should be part of i18n never the less since it's language specific.
I'm personally not a fan of language specific code being hard-coded

2024-08-23 23:16 UTC, frutescens commented on src/phases/encounter-phase.ts
> +          const cycleCount = count.toLocaleString() + ordinalIndex;
I don't mind adding it since I do need to learn how to make translation keys with the new format but this is an English-only problem.

2024-08-23 23:43 UTC, xsn34kzx reviewed
Threw a few logistical comments!

2024-08-23 23:43 UTC, xsn34kzx commented on src/phases/encounter-phase.ts
> +          console.log(`Dialogue ${localizationKey} skipped`);
Should this still be here? Not sure what our overall policy/feelings are about having new `console.log`s since this can be somewhat practical for the general player base but, at the same time, it also shows the raw translation keys.

2024-08-23 23:43 UTC, xsn34kzx commented on src/phases/encounter-phase.ts
> +          const cycleCount = count.toLocaleString() + ordinalIndex;
+1 to doing as much language-based decisions as possible through i18next. I'd imagine it would be possible to not fallback / not append an ordinal to languages that don't use them (or in this case, don't have a translation key entry) somewhere in the i18next library. The main concern here is mostly having strings (and translations) in the general code base, making this snippet of code messier over time.

2024-08-23 23:51 UTC, frutescens commented on src/phases/encounter-phase.ts
> +          console.log(`Dialogue ${localizationKey} skipped`);
This is how ui.showDialogue() behaves re: skipping dialogue.

2024-08-23 23:55 UTC, xsn34kzx commented on src/phases/encounter-phase.ts
> +          console.log(`Dialogue ${localizationKey} skipped`);
Ah, gotcha, should be fine then.

2024-08-24 19:05 UTC, xsn34kzx approved these changes
Basically what I had in mind, lgtm!

2024-08-25 01:28 UTC, flx-sta approved these changes

2024-08-26 00:22 UTC, DayKev commented on src/phases/encounter-phase.ts
> +          console.log(`Dialogue ${localizationKey} skipped`);
Also, `console.log()` statements aren't executed on main.

2024-08-26 00:30 UTC, DayKev commented
Okay so apparently if you override directly to wave 200 things break slightly. Also the ordinal thing is missing, should be a "th" after the number there.
![image](https://github.com/user-attachments/assets/408e5655-ae73-4240-aa40-b556b3498d2f)

Also this is almost definitely unrelated but apparently reloading during the wave 200 dialog (this time vs boss Nidoking lol) causes this to happen (see left side of screen):
![image](https://github.com/user-attachments/assets/0537cdb7-7395-42f3-b2a0-b549b6ea874a)

The dialog does skip now though, so there's that.

2024-08-26 00:46 UTC, MokaStitcher commented on src/phases/encounter-phase.ts
> +        const localizationKey = ((this.scene.gameData.gender === PlayerGender.FEMALE) ? "PGF" : "PGM")+"battleSpecDialogue:";
Can't do a full review right now, but there's a function "shouldSkipDialog" in ui.ts that handles adding the PGM/PGF stuff to the key and checks if the dialog should get skipped, could you call it instead of doing the check yourself?

2024-08-28 23:40 UTC, frutescens commented
My bad, I fixed the issues now and it should work :)

https://github.com/user-attachments/assets/713cf848-e4b5-424d-b975-189b2fc9895f

2024-08-28 23:40 UTC, frutescens commented on src/phases/encounter-phase.ts
> +        const localizationKey = ((this.scene.gameData.gender === PlayerGender.FEMALE) ? "PGF" : "PGM")+"battleSpecDialogue:";
good idea!

2024-08-29 01:52 UTC, DayKev commented on src/phases/encounter-phase.ts
> +          //The line below checks if an English ordinal is necessary or not based on whether an entry for encounterLocalizationKey exists in the language or not.
```suggestion
          const localizationKey = ((this.scene.gameData.gender === PlayerGender.FEMALE) ? "PGF" : "PGM") + encounterLocalizationKey;
          const count = 5643853 + this.scene.gameData.gameStats.classicSessionsPlayed;
          // The line below checks if an English ordinal is necessary or not based on whether an entry for encounterLocalizationKey exists in the language or not.
```

2024-08-29 02:30 UTC, DayKev submitted a review, later dismissed

2024-08-29 05:10 UTC, KimJeongSun submitted a review, later dismissed
it looks working in shared case with Korean option

2024-08-29 11:08 UTC, MokaStitcher approved these changes
lgtm! (tested in french + a bit of english for the ordinals, and with both player genders)

2024-08-29 16:50 UTC, CodeTappert submitted a review, later dismissed

2024-08-29 17:38 UTC, MokaStitcher requested changes
just something to update I think in regards to PR #3879

2024-08-29 17:38 UTC, MokaStitcher commented on src/phases/encounter-phase.ts
> +        if (this.scene.ui.shouldSkipDialogue(localizationKey)) {
if what PR #3879 did stays as is you would need to call shouldSkipDialogue with the gender specific key now
however i'm not sure it was correct to remove the gender stuff from there, but my comment there came in after the PR was already merged :(

2024-08-29 17:41 UTC, flx-sta commented on src/phases/encounter-phase.ts
> +        if (this.scene.ui.shouldSkipDialogue(localizationKey)) {
@MokaStitcher the `localizationKey` is never changed so the skip logic works as such:

If you have the gender `Boy` and you've seen the dialogue the key is saved as `seen` without any gender suffix.

If you now change your gender to `Girl` you still wouldn't see the dialogue again (even if it's different) as the key is ultimate WITHOUT the gender. Which is an expected behavior. 
The difference in the key only exists in the `json` files, no in the i18next call logic.

2024-08-29 17:51 UTC, MokaStitcher commented on src/phases/encounter-phase.ts
> +        if (this.scene.ui.shouldSkipDialogue(localizationKey)) {
if that's how we want to have it work going forward i guess it's fine, but before if you changed gender you would see the dialogue once before it got skipped again, since potentially it is quite different between genders, especially for the rival

2024-08-29 17:58 UTC, MokaStitcher commented on src/phases/encounter-phase.ts
> +        if (this.scene.ui.shouldSkipDialogue(localizationKey)) {
@flx-sta but also the thing is [here](https://github.com/flx-sta/pokerogue/blob/c3e5c21463bd0f08924dad71f6db5d45122cbd65/src/ui/ui.ts#L320) unless I'm mistaken it stores the one with context as seen, so if you play exclusively as female it wouldn't then skip the male dialogs? I'll have to test it out though, maybe i'm wrong

2024-08-29 18:36 UTC, MokaStitcher commented on src/phases/encounter-phase.ts
> +        if (this.scene.ui.shouldSkipDialogue(localizationKey)) {
in the context of this specific dialog it's fine with the way it's done though you're right.
the issues i have are with the rest of the dialog related to the context PR but this is not the place to discuss them, sorry

2024-08-29 18:36 UTC, MokaStitcher approved these changes

2024-08-30 00:48 UTC, DayKev approved these changes

2024-08-30 07:42 UTC, innerthunder approved these changes

2024-08-30 09:16 UTC, merged