Bug 3722: Added fix so that text correctly appears when sleep fails in electric terrain
pagefaultgames/pokerogue pull request #3775
Opened 2024-08-26 06:56 UTC by jessemchung

This fix is for this issue:
https://github.com/pagefaultgames/pokerogue/issues/3722

## What are the changes the user will see?
The user will now, when attempting to put a pokemon to sleep on electric terrain, will receive a message why it failed

## Why am I making these changes?

I needed to add fixes to drowsy (from yawn) as well as to the tryStatusEffect 

Makes it more similar to the mainline games and pokemon showdown

## What are the changes from a developer perspective?

A simple change was added in the drowsy state check so that the message will appear.  I also had to add logic to the final

### Screenshots/Videos
See below

## How to test the changes?

I used override, I honestly am not sure how best to test yet.  I set my pokemon to Tapu Koko with spore and yawn as moves and the opponent as well to test

No

No

No

## Checklist
- [ ] **I'm using `beta` as my base branch**
- I set the target branch to beta
- [ ] There is no overlap with another PR?
- Not sure how best to look at this but I confirmed in the issue that I would fix it
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- Yes
- [ ] Have I provided a clear explanation of the changes?
- Yes
- [ ] Have I considered writing automated tests for the issue?
- I considered it but decided no for now
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- Text was already there.  Just no triggering logic
- [ ] Have I tested the changes (manually)?
-  Yes
    - [ ] Are all unit tests still passing? (`npm run test`)
    - Yes
- [ ] Are the changes visual?
  - Yes

Original Issue on display

https://github.com/user-attachments/assets/9658fa79-3638-4274-9a0a-b6f48862a5ec

Fixes both with spore and sing to showcase 

https://github.com/user-attachments/assets/92bb4ba5-5a34-4019-8069-9d0a88a61027

https://github.com/user-attachments/assets/044916ef-c235-4aaa-b343-54e8c079406c

2024-08-26 08:29 UTC, torranx commented
Shouldn't you be adding in `terrain.isMoveTerrainCancelled` instead?

2024-08-26 10:53 UTC, schmidtc1 requested changes

2024-08-26 10:53 UTC, schmidtc1 commented on src/field/pokemon.ts
> +          this.scene.queueMessage(i18next.t("terrain:defaultBlockMessage", { pokemonNameWithAffix: getPokemonNameWithAffix(this), terrainName: getTerrainName(TerrainType.ELECTRIC) }));
You do not need to add this switch here. `queueMessage` can simply be added inside the condition in `canSetStatus` here:
https://github.com/pagefaultgames/pokerogue/blob/762aa9e49b8df80d7ab2bea1a7074f5b6da53be3/src/field/pokemon.ts#L2739-L2741

2024-08-26 11:03 UTC, schmidtc1 commented on src/field/pokemon.ts
> +          this.scene.queueMessage(i18next.t("terrain:defaultBlockMessage", { pokemonNameWithAffix: getPokemonNameWithAffix(this), terrainName: getTerrainName(TerrainType.ELECTRIC) }));
Disregard this in favor of @torranx's suggestion, I should stop reviewing while I'm sleep deprived

2024-08-26 14:49 UTC, jessemchung commented
> Shouldn't you be adding in `terrain.isMoveTerrainCancelled` instead?

@torranx Wait, so, terrain.isMoveTerrainCancelled seems like it is intent on nullifying the move entirely like how psychic terrain nullfies all priority moves.

In the case of electric terrain, what about relic song from Meloetta?  That move would still deal damage just not put the target to sleep?  Also, what about effects that put the pokemon to sleep like effect spore?

2024-08-26 15:02 UTC, jessemchung commented on src/field/pokemon.ts
> +          this.scene.queueMessage(i18next.t("terrain:defaultBlockMessage", { pokemonNameWithAffix: getPokemonNameWithAffix(this), terrainName: getTerrainName(TerrainType.ELECTRIC) }));
I think it has something to do with getTargetBenefitScore also checking canSetStatus which causes a message in their to occur multiple times

2024-08-26 15:08 UTC, schmidtc1 commented on src/field/pokemon.ts
> +          this.scene.queueMessage(i18next.t("terrain:defaultBlockMessage", { pokemonNameWithAffix: getPokemonNameWithAffix(this), terrainName: getTerrainName(TerrainType.ELECTRIC) }));
I'm pretty sure that occurs due to canSetStatus being used by the enemy AI calculations. Then you may need to use the `quiet` boolean to prevent text showing up during those calculations:
```typescript
 if (this.isGrounded() && this.scene.arena.terrain?.terrainType === TerrainType.ELECTRIC) { 
   if (!quiet) {
     this.scene.queueMessage(i18next.t("terrain:defaultBlockMessage", { pokemonNameWithAffix: getPokemonNameWithAffix(this), terrainName: getTerrainName(TerrainType.ELECTRIC) }));
   }
   return false; 
 } 
```

2024-08-26 19:01 UTC, schmidtc1 commented on src/field/pokemon.ts
> +          this.scene.queueMessage(i18next.t("terrain:defaultBlockMessage", { pokemonNameWithAffix: getPokemonNameWithAffix(this), terrainName: getTerrainName(TerrainType.ELECTRIC) }));
I think that's the correct approach. I'd assume the apply function should be sending false for the `quiet` boolean in there, since we are actually applying the effect rather than simulating it like `getTargetBenefitScore` does.

2024-08-27 02:56 UTC, jessemchung commented on src/field/pokemon.ts
> +          this.scene.queueMessage(i18next.t("terrain:defaultBlockMessage", { pokemonNameWithAffix: getPokemonNameWithAffix(this), terrainName: getTerrainName(TerrainType.ELECTRIC) }));
Gotcha, yeah looking at the situation, I tested with will o wisp and that at some point also needs to have the text appear.  In any case, seems good to go.  Tested with this quiet and things are working correctly.

2024-08-29 16:09 UTC, frutescens commented
Bug Issue #3722

2024-08-29 18:20 UTC, Snailman11 commented
Will this fix the protected by message not displaying for status on Misty Terrain?

https://github.com/user-attachments/assets/3593b1e3-90b5-41c9-ab47-2a56f9aadc39

2024-08-29 20:06 UTC, jessemchung commented
> Will this fix the protected by message not displaying for status on Misty Terrain? -Looking through the code and I think that's unlikely. I'll open another bug report. #3898
> Misty.mp4

It will not, that would also be a very similar fix though.

2024-08-30 01:36 UTC, jessemchung commented
@schmidtc1 so the issue so far is that for some reason, setting quiet to false causes toxic damage to not work correctly.  Need to understand why still.

2024-08-30 02:04 UTC, schmidtc1 commented
> @schmidtc1 so the issue so far is that for some reason, setting quiet to false causes toxic damage to not work correctly. Need to understand why still. I suspect this might be better to adjust the if statement to check which phase it is instead of checking the quiet property as for some reason toxic damage is tied to that variable. At least, this way, fewer changes would be needed

My guess is that the asPhase variable is being set to false and used as the quiet variable passed to `canSetStatus`, since you are using `trySetStatus` in the apply function. I came across this issue a while ago and had a PR to make a separate quiet parameter in `trySetStatus`, but it never went through. 

Imo, a separate quiet parameter should still be implemented to pass to canSetStatus, instead of using asPhase in place of the quiet parameter. 

As an alternative solution, you could maybe use `canSetStatus` in the if statement, and `trySetStatus` inside the block. But you'd have to play around with that to see if it works.

2024-08-30 02:31 UTC, jessemchung commented
Right now that you mentioned it, I believe you are right.  This part is probably the part causing a few issues.  I have an idea for a fix.  The code will be simple but a more elegant solution is likely a good idea

```
    if (asPhase) {
      this.scene.unshiftPhase(new ObtainStatusEffectPhase(this.scene, this.getBattlerIndex(), effect, cureTurn, sourceText!, sourcePokemon!)); // TODO: are these bangs correct?
      return true;
    }

```

2024-08-30 04:51 UTC, jessemchung commented
@schmidtc1 Hey quick question, what happened to that pull request? Also, I did find a solution sort of related to this

    As an alternative solution, you could maybe use canSetStatus in the if statement, and trySetStatus inside the block. But you'd have to play around with that to see if it works.

Now, I tried this and the problem is this chunk of code that causes problems if run multiple times (see below code block). Now, one option is to have the quiet variable work as it seems like it should but I don't think that is necessary. The big issue is that canSetStatus probably should only check if it is possible to setStatus and not handle other applications. As a result, the solution I have now is to split that function into two pieces. One part only checks if it is possible for the pokemon to be statused and the other handles the other logic like below. I ran the tests and everything passes.  


```
    const cancelled = new Utils.BooleanHolder(false);
    applyPreSetStatusAbAttrs(StatusEffectImmunityAbAttr, this, effect, cancelled, quiet);

    const userField = this.getAlliedField();
    userField.forEach(pokemon => applyPreSetStatusAbAttrs(UserFieldStatusEffectImmunityAbAttr, pokemon, effect, cancelled, quiet));
```

2024-08-30 11:21 UTC, schmidtc1 commented
> @schmidtc1 Hey quick question, what happened to that pull request? Also, I did find a solution sort of related to this
> 
> ```
> As an alternative solution, you could maybe use canSetStatus in the if statement, and trySetStatus inside the block. But you'd have to play around with that to see if it works.
> ```
> 
> Now, I tried this and the problem is this chunk of code that causes problems if run multiple times (see below code block). Now, one option is to have the quiet variable work as it seems like it should but I don't think that is necessary. The big issue is that canSetStatus probably should only check if it is possible to setStatus and not handle other applications. As a result, the solution I have now is to split that function into two pieces. One part only checks if it is possible for the pokemon to be statused and the other handles the other logic like below. I ran the tests and everything passes.
> 
> ```
>     const cancelled = new Utils.BooleanHolder(false);
>     applyPreSetStatusAbAttrs(StatusEffectImmunityAbAttr, this, effect, cancelled, quiet);
> 
>     const userField = this.getAlliedField();
>     userField.forEach(pokemon => applyPreSetStatusAbAttrs(UserFieldStatusEffectImmunityAbAttr, pokemon, effect, cancelled, quiet));
> ```

It's a bit messed up and outdated due to some beta merge issues, but here it is: #2663

2024-08-30 16:45 UTC, jessemchung commented
Gotcha.  Sorry to hear that pull request didn't get pulled in. Looks like a ton of work went into it

2024-09-02 00:28 UTC, schmidtc1 commented on src/data/battler-tags.ts
> +    const isNotElectricTerrainProtected = pokemon.scene.arena.terrain?.terrainType !== TerrainType.ELECTRIC || !pokemon.isGrounded();
I feel like `isElectricTerrainProtected` makes more sense, and then refactoring to fit that name

2024-09-02 00:32 UTC, jessemchung commented on src/data/battler-tags.ts
> +    const isNotElectricTerrainProtected = pokemon.scene.arena.terrain?.terrainType !== TerrainType.ELECTRIC || !pokemon.isGrounded();
I see, I was thinking about that as a possibility in which case, the return would be return !isElectricTerrainProtected

And then isElectricTerrainProtocted could be
`(pokemon.scene.arena.terrain?.terrainType === TerrainType.ELECTRIC && !pokemon.isGrounded();)`

2024-09-02 02:51 UTC, Tempo-anon requested changes

2024-09-02 02:51 UTC, Tempo-anon commented on src/data/battler-tags.ts
> +    const isElectricTerrainProtected = pokemon.scene.arena.terrain?.terrainType === TerrainType.ELECTRIC && !pokemon.isGrounded();
nit:  `const isElectricTerrainProtected = )pokemon.scene.arena.terrain?.terrainType === TerrainType.ELECTRIC && !pokemon.isGrounded());`

2024-09-02 02:51 UTC, Tempo-anon commented on src/field/pokemon.ts
> +  canSetStatus(effect: StatusEffect | undefined, quiet: boolean = false, overrideStatus: boolean = false, sourcePokemon: Pokemon | null = null): boolean {
Add documentation to this new function

2024-09-02 02:51 UTC, Tempo-anon commented on src/field/pokemon.ts
> +    const checker = this.checkIfCanSetStatus(effect, quiet, overrideStatus, sourcePokemon);
nit: rename variable name because `checker` makes it seem like it's an object that is checking something rather than a boolean

2024-09-02 02:51 UTC, Tempo-anon commented on src/data/move.ts
>        if ((!pokemon.status || (pokemon.status.effect === this.effect && moveChance < 0))
Is this the same `if`? If so, why can't this `checkIfCanSetStatus` call just go in the existing if?

2024-09-02 03:21 UTC, jessemchung commented on src/field/pokemon.ts
> +  canSetStatus(effect: StatusEffect | undefined, quiet: boolean = false, overrideStatus: boolean = false, sourcePokemon: Pokemon | null = null): boolean {
Where do I add documentation for the new function?

2024-09-02 03:53 UTC, jessemchung commented on src/data/move.ts
>        if ((!pokemon.status || (pokemon.status.effect === this.effect && moveChance < 0))
I just realized yes it can.  It just has to go before pokemon.trySetStatus because that function prevents messages from showing up.  I got thrown off initially as I tried to put it in the conditional block but that didn't work.

Fixed now

2024-09-02 03:53 UTC, jessemchung commented on src/data/battler-tags.ts
> +    const isElectricTerrainProtected = pokemon.scene.arena.terrain?.terrainType === TerrainType.ELECTRIC && !pokemon.isGrounded();
Gotcha, added paranthesis

2024-09-02 03:54 UTC, jessemchung commented on src/field/pokemon.ts
> +  canSetStatus(effect: StatusEffect | undefined, quiet: boolean = false, overrideStatus: boolean = false, sourcePokemon: Pokemon | null = null): boolean {
Nevermind, figured it out.  I wasn't sure what you meant since the original function canSetStatus did not have any documentation.  Added documentation both for that function and the new function.

2024-09-02 04:35 UTC, Tempo-anon commented
Looks like some other changes were caught up in this commit? https://github.com/pagefaultgames/pokerogue/pull/3775/commits/754d3775396cbfcd6b9b981403df2b6bed69c10c

2024-09-02 06:26 UTC, jessemchung commented
> Looks like some other changes were caught up in this commit? [754d377](https://github.com/pagefaultgames/pokerogue/commit/754d3775396cbfcd6b9b981403df2b6bed69c10c)

@Tempo-anon Yeah, I don't know but this situation is basically unsalvagable. Attempt to pull down beta made things worse.  Made a new pull request

https://github.com/pagefaultgames/pokerogue/pull/3972

2024-09-02 06:45 UTC, innerthunder commented
closing this in favor of the new PR without conflicts

2024-09-02 06:45 UTC, closed without merging