Daily standardization
pagefaultgames/pokerogue pull request #3776
Opened 2024-08-26 07:55 UTC by RedstonewolfX

This Pull Request makes a few changes to Daily Runs as requested by Vicksin

## What are the changes the user will see?
- Shiny Luck will no longer affect Daily Runs
- Eviolite is unobtainable in Daily Runs
- The player starts with a Map in Daily Runs, in addition to their 300% charms bonus

## Why am I making these changes?
The Map allows players to more easily explore biomes and get more out of each day.
Removing Eviolite allows players who have unlocked it to get the same items as players who haven’t.
Removing shiny luck allows players to play the same as others, even when they get a shiny.

## What are the changes from a developer perspective?
Eviolite is now disabled in daily runs, using the same method that disabled it in Fresh Start
The function to get the player’s Luck checks if you’re in a daily run, and if you are, it sets your luck to 0
The luck display hides in Daily Runs since it is irrelevant
A Map has been inserted in between the Golden EXP Charms and the starters’ held items

### Screenshots/Videos
Soon™️

## How to test the changes?
Open up a Daily Run.
- You will have a Map in your key items
- The shop no longer shows how much Luck you have
- Wave 18 (will double check this) gives an Amulet Coin if you have Eviolite, as opposed to a Shiny Charm without

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-26 07:56 UTC, RedstonewolfX commented
Ignore the first 3 commits, they were leftover from the last PR and I couldn’t figure out how to make them go away without deleting the actual commits I made for this or adding revert commits

2024-08-26 07:57 UTC, RedstonewolfX commented
![image](https://github.com/user-attachments/assets/72314f2b-2e30-444a-bb1b-c7b9ee6faaba)

2024-08-26 08:01 UTC, RedstonewolfX commented
Going to repost tomorrow without the excess commits

2024-08-26 10:22 UTC, RedstonewolfX commented
Was told that it was fine

2024-08-26 15:15 UTC, flx-sta requested changes
Please also add some automated tests to cover your changes

2024-08-26 15:15 UTC, flx-sta commented on src/battle-scene.ts
> +  updateAndShowText(duration: integer, isDaily?: boolean): void {
while you are at it, please replace `integer` with `number` (integer is just a *useless* alias for number)

```suggestion
  updateAndShowText(duration: number, isDaily?: boolean): void {
```

2024-08-26 15:15 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +import { GameModes } from "#app/game-mode.js";
```suggestion
import { GameModes } from "#app/game-mode";
```

2024-08-26 15:15 UTC, flx-sta commented on src/ui/modifier-select-ui-handler.ts
> +import { GameModes } from "#app/game-mode.js";
```suggestion
import { GameModes } from "#app/game-mode";
```

2024-08-26 15:15 UTC, flx-sta commented on src/modifier/modifier-type.ts
>          return party.some(p => ((p.getSpeciesForm(true).speciesId in pokemonEvolutions) || (p.isFusion() && (p.getFusionSpeciesForm(true).speciesId in pokemonEvolutions))) && !p.getHeldItems().some(i
try improving readability by buffering some values:
```suggestion
      const { gameMode, gameData } = party[0].scene;
      if (!gameMode.isFreshStartChallenge() && !gameMode.isDaily && gameData.unlocks[Unlockables.EVIOLITE]) {
        return party.some(p => ((p.getSpeciesForm(true).speciesId in pokemonEvolutions) || (p.isFusion() && (p.getFusionSpeciesForm(true).speciesId in pokemonEvolutions))) && !p.getHeldItems().some(i => i instanceof Modifiers.EvolutionStatBoosterModifier)) ? 10 : 0;
```

2024-08-26 15:15 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +  if (party[0].scene.gameMode.modeId === GameModes.DAILY) {
Up top you are using `.scene.gameMode.isDaily` and here you are checking `gameMode.modeId`. Is there a reason for that?

2024-08-26 15:15 UTC, flx-sta commented on src/ui/modifier-select-ui-handler.ts
> +    this.scene.updateAndShowText(750, this.scene.gameMode.modeId === GameModes.DAILY);
In `modifier-type.ts` you are using `.scene.gameMode.isDaily` and here you are checking `gameMode.modeId`. Is there a reason for that?

2024-08-26 16:03 UTC, RedstonewolfX commented on src/modifier/modifier-type.ts
> +  if (party[0].scene.gameMode.modeId === GameModes.DAILY) {
I didn't know .gameMode.isDaily existed yet

2024-08-26 16:03 UTC, RedstonewolfX commented on src/ui/modifier-select-ui-handler.ts
> +    this.scene.updateAndShowText(750, this.scene.gameMode.modeId === GameModes.DAILY);
[Copying above reply]
I didn't know .gameMode.isDaily existed yet

2024-08-26 16:06 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +  if (party[0].scene.gameMode.modeId === GameModes.DAILY) {
if you are able to use it there, I think you should use it.
It's a bit sketchy to me that it's a field/attribute and not a method

2024-08-26 16:14 UTC, RedstonewolfX commented
Going to eat lunch and then I'll start looking around at how to put together an automated test like you asked

2024-08-26 16:28 UTC, RedstonewolfX commented
> Please also add some automated tests to cover your changes
What am I testing exactly?
Whether or not the Daily Run is a Daily Run?
Whether the map is added to your inventory properly or not?

2024-08-26 16:56 UTC, RedstonewolfX commented on src/modifier/modifier-type.ts
> +  if (party[0].scene.gameMode.modeId === GameModes.DAILY) {
I switched it out, they both use `scene.gameMode.isDaily` now

2024-08-26 18:47 UTC, RedstonewolfX commented
I'm going to stop for the day
It's been 2 and a half hours and I have made almost no progress
Going to look around in more tests to see if I can find a way to override luck, and will use some console logging to find where Eviolite is in the loot pool

2024-08-26 18:53 UTC, RedstonewolfX commented
Oh did I forget to put an it() inside of the describe()?

I did see that Describe was for categorizing/scope

2024-08-26 18:54 UTC, RedstonewolfX commented
thank you for this link, now maybe I'll know what I'm doing

2024-08-27 15:04 UTC, RedstonewolfX commented
New test just dropped
I added some overrides and two booleans to make things easier for me because I was going to go crazy with that shop test

2024-08-27 15:08 UTC, RedstonewolfX commented
Oops sorry
Tapping and dragging onto something mouses over it on mobile, but it also clicks it

2024-08-27 15:22 UTC, RedstonewolfX commented
I have school now but will write the other test this evening

2024-08-27 16:21 UTC, flx-sta commented
> I have school now but will write the last test this evening

Since you are still working on it I've put into Draft

2024-08-27 16:25 UTC, flx-sta commented on src/overrides.ts
> +  readonly DISABLE_UNLOCK_OVERRIDE: Unlockables[] = [];
I personally think It's a bit chaotic to have 2 overrides that are basically "fighting" each other.
Having the `UNLOCK_OVERRIDE` should be sufficient, especially for automated testing

2024-08-27 16:25 UTC, flx-sta commented on src/system/unlockables.ts
> +
This function makes absolutely no sense to me.
It only checks the unlockable if overrides are set. Otherwise it will always check for `MINI_BLACK_HOLE`?

-----

Also since `gameData` is always passed into it consider moving it into `gameData` as method (I might be wrong about this. Need a 2nd opinion)

2024-08-27 17:15 UTC, xsn34kzx requested changes
Had some comments and requests 🫡

2024-08-27 17:15 UTC, xsn34kzx commented on src/modifier/modifier-type.ts
> +  poolHasBlackHole = false;
Not a huge fan of these variables since, in the event that more unlockable items are added, we'd essentially need to match that with more `boolean` variables under this precedent.

2024-08-27 17:15 UTC, xsn34kzx commented on src/modifier/modifier-type.ts
> +
```suggestion
```
NIT: Code shouldn't be added if it's not used

2024-08-27 17:15 UTC, xsn34kzx commented on src/system/unlockables.ts
> +  return !!gameData.unlocks[Unlockables.MINI_BLACK_HOLE];
```suggestion
  return gameData.unlocks[unlockable];
```
As flx said, as is the function would default to `MINI_BLACK_HOLE` regardless of the `unlockable`. Moreover, because `unlocks` is already a key-value pair giving back a `boolean`, there's no need for the `!!`.

2024-08-27 17:15 UTC, xsn34kzx commented on src/system/unlockables.ts
> +
+1 to both comments.  For the second one in particular, I do think it would be more semantically natural to write something like `scene.gameData.isUnlocked(...)` rather than `isUnlocked(..., scene.gameData)`, so it really should be a function of `gameData`.

2024-08-27 17:30 UTC, RedstonewolfX commented on src/overrides.ts
> +  readonly DISABLE_UNLOCK_OVERRIDE: Unlockables[] = [];
I did try to collapse them into one but couldn’t think of any way to do so
However, you don’t really need to re-lock anything - the test has everything locked by default I’m sure - so I’ll just remove that one

2024-08-27 17:31 UTC, RedstonewolfX commented on src/system/unlockables.ts
> +
Oops

2024-08-27 18:06 UTC, RedstonewolfX commented on src/system/unlockables.ts
> +
The first one is purely a mistake on my part
The second one is a given and I don’t know why I didn’t think of that

2024-08-27 18:08 UTC, RedstonewolfX commented on src/modifier/modifier-type.ts
> +  poolHasBlackHole = false;
This is the most straightforward method I could think of for testing whether they are removed from the shop properly
Is there any alternative you could suggest?
Could I just attach an export tag to the player loot thresholds? That would be a lot simpler than any alternative I can think of

2024-08-27 18:09 UTC, RedstonewolfX commented on src/modifier/modifier-type.ts
> +
Sorry, forgot to remove that

2024-08-27 18:10 UTC, RedstonewolfX commented
I’ll move that code block and fix the tests once I get home

2024-08-27 21:59 UTC, RedstonewolfX commented
somehow fixing the two errors didn't fix it while also making a third error in a place I didn't edit
Making good progress

2024-08-27 22:53 UTC, RedstonewolfX commented
Copied over some fixes from [this Pull Request](https://github.com/pagefaultgames/pokerogue/pull/3855#issue-2490475302) so I can use them before the PR is approved; I will remove it once it's approved, or remove it and find an alternative if it gets rejected for some reason

2024-09-01 00:40 UTC, DayKev commented on src/modifier/modifier-type.ts
> +  poolHasBlackHole = false;
What if we just put a `// TODO: do this properly` for now and fix this later? Modifiers are fucked and need to be overhauled anyway, at which point this can probably be done better.

2024-09-01 08:14 UTC, DayKev commented
I would recommend not trying to nest `describe()` statements, it doesn't seem to work.

2024-09-04 01:51 UTC, damocleas commented
Any updates on this?

2024-09-04 16:04 UTC, RedstonewolfX commented
The actual features were completed forever ago, but the test that makes sure Eviolite and Mini Black Hole function properly has been giving me so much trouble

2024-09-04 19:54 UTC, MokaStitcher commented on src/test/game-mode.test.ts
> +  /*
Have you tried using the `SHINY_OVERRIDE`and `VARIANT_OVERRIDE` for this?
https://github.com/pagefaultgames/pokerogue/blob/fde32cea6c9376a64f6d8dcb4e77cef9b4a0a265/src/overrides.ts#L102-L103

The nicest way to use them in tests would be to add helper functions for them, similar to this one:
https://github.com/pagefaultgames/pokerogue/blob/fde32cea6c9376a64f6d8dcb4e77cef9b4a0a265/src/test/utils/helpers/overridesHelper.ts#L256-L260

And then use them like in the other tests to start with an epic tier shiny by doing something like that:
```
game.override
      .shinyStarter(true)
      .starterVariant(2)
```

hope that helps

2024-09-08 12:17 UTC, RedstonewolfX commented on src/test/game-mode.test.ts
> +  /*
Oh god thank you

2024-09-08 12:17 UTC, RedstonewolfX commented on src/test/game-mode.test.ts
> +  /*
If that works fine, all I will have left is the Eviolite check

2024-09-12 23:21 UTC, RedstonewolfX commented on src/modifier/modifier-type.ts
> +  poolHasBlackHole = false;
Remade with a better system
Going to fully implement it tonight or tomorrow

2024-09-15 20:50 UTC, CodeTappert commented
So that one reset test times out....
Can we change that one?

2024-09-18 00:44 UTC, RedstonewolfX commented
Since giving the player a Map in Daily Runs is already complete, I made [a separate pull request](https://github.com/pagefaultgames/pokerogue/pull/4305) for it

2024-09-18 15:40 UTC, RedstonewolfX commented
Making progress on the tests finally

2024-09-18 16:26 UTC, flx-sta requested changes

2024-09-18 16:26 UTC, flx-sta commented on src/battle-scene.ts
> +  updateAndShowText(duration: number, isDaily?: boolean): void {
NIT:
docs

2024-09-18 16:26 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +      if (party[0].scene.gameMode.isDaily || gameMode.isDaily || (!gameMode.isFreshStartChallenge() && gameData.isUnlocked(Unlockables.EVIOLITE))) {
uuuh... `gameMode` is extracted from`party[0].scene` .
So the check is quite redundant here
```suggestion
      if (gameMode.isDaily || (!gameMode.isFreshStartChallenge() && gameData.isUnlocked(Unlockables.EVIOLITE))) {
```

2024-09-18 16:26 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +    new WeightedModifierType(modifierTypes.MINI_BLACK_HOLE, (party: Pokemon[]) => (party[0].scene.gameMode.isDaily || (!party[0].scene.gameMode.isFreshStartChallenge() && party[0].scene.gameData.isUn
You are still in the same method so `gameMode` and `gameData` should still be available (extracted from `party[0].scene`)

```suggestion
    new WeightedModifierType(modifierTypes.MINI_BLACK_HOLE, (party: Pokemon[]) => (gameMode.isDaily || (!gameMode.isFreshStartChallenge() && gameData.isUnlocked(Unlockables.MINI_BLACK_HOLE))) ? 1 : 0, 1),
```

2024-09-18 16:26 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +export const itemPoolChecks: Map<ModifierTypeKeys, boolean> = new Map();
Is there a specific reason/benefit to use a `Map` here instead of a classic object?

2024-09-18 16:26 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +  }
NIT: docs

2024-09-18 16:26 UTC, flx-sta commented on src/overrides.ts
>    readonly BYPASS_TUTORIAL_SKIP: boolean = false;
NIT:
I know this isn't yours but: This is missing a `OVERRIDE` suffix

2024-09-18 16:26 UTC, flx-sta commented on src/overrides.ts
> +  readonly UNLOCK_OVERRIDE: Unlockables[] = [];
Please be more specific here

```suggestion
  readonly ITEM_UNLOCK_OVERRIDE: Unlockables[] = [];
```

2024-09-18 16:26 UTC, flx-sta commented on src/phases/title-phase.ts
> +        if (this.scene.gameData.isUnlocked(Unlockables.ENDLESS_MODE)) {
if you are going to re-use `gameData.[...]` buffer it

```suggestion
        const { gameData } = this.scene;
        if (gameData.isUnlocked(Unlockables.ENDLESS_MODE)) {
```

2024-09-18 16:26 UTC, flx-sta commented on src/phases/title-phase.ts
> +          if (this.scene.gameData.isUnlocked(Unlockables.SPLICED_ENDLESS_MODE)) {
as you buffered `gameData` previously you can now do:

```suggestion
          if (gameData.isUnlocked(Unlockables.SPLICED_ENDLESS_MODE)) {
```

2024-09-18 16:26 UTC, flx-sta commented on src/system/game-data.ts
> +  public isUnlocked(unlockable: Unlockables): boolean {
NIT: missing new-line & docs (public methods have to be documented

2024-09-18 16:26 UTC, flx-sta commented on src/system/version-converter.ts
we should consider putting those patches per-version into separate migration files. Otherwise this one will grow quite the proportions.

This could also increase readability by naming certain converters with functions

2024-09-18 16:26 UTC, flx-sta commented on src/test/daily_mode.test.ts
> +//const TIMEOUT = 20 * 1000;
```suggestion
```

2024-09-18 16:26 UTC, flx-sta commented on src/test/daily_mode.test.ts
> +//*/
Jut add a `.skip` to the describe if you don't want to run it (yet)

```suggestion
// Need to figure out how to properly start a battle
// Need to fix eviolite - test keeps insisting it is not in loot table, even though Mini Black Hole (which is using the exact same condition) is
describe.skip("Shop modifications", async () => {
  let phaserGame: Phaser.Game;
  let game: GameManager;

  beforeAll(() => {
    phaserGame = new Phaser.Game({
      type: Phaser.HEADLESS,
    });
  });
  beforeEach(() => {
    game = new GameManager(phaserGame);

    game.override
      .battleType("single")
      .startingLevel(200)
      .moveset([Moves.SURF])
      .enemyAbility(Abilities.BALL_FETCH);
    itemPoolChecks.set("EVIOLITE", false);
    itemPoolChecks.set("MINI_BLACK_HOLE", false);
  });

  afterEach(() => {
    game.phaseInterceptor.restoreOg();
    itemPoolChecks.clear();
  });
});
```

2024-09-18 16:26 UTC, flx-sta commented on src/test/game-mode.test.ts
> +//import { Species } from "#app/enums/species";
```suggestion
```

2024-09-18 16:26 UTC, flx-sta commented on src/test/game-mode.test.ts
> +  //*/
Jut add a `.skip` to the describe if you don't want to run it (yet)

```suggestion
  // Need to figure out how to properly start a battle
  describe.skip("Luck Check", async () => {
    let classicGameMode: GameMode;
    let dailyGameMode: GameMode;

    beforeAll(() => {
      phaserGame = new Phaser.Game({
        type: Phaser.HEADLESS,
      });
    });

    afterEach(() => {
      game.phaseInterceptor.restoreOg();
    });

    beforeEach(() => {
      game = new GameManager(phaserGame);
      classicGameMode = getGameMode(GameModes.CLASSIC);
      dailyGameMode = getGameMode(GameModes.DAILY);
    });

    it("applies luck in Classic", () => {
      game.override
        .shinyLevel(true, 2);
      game.classicMode.startBattle([Species.PICHU]);
      const party = game.scene.getParty();
      expect(getPartyLuckValue(party)).toBe(3);
    });
    it("does not apply luck in Daily Runs", () => {
      game.override
        .shinyLevel(true, 2);
      game.dailyMode.startBattle();
      const party = game.scene.getParty();
      expect(getPartyLuckValue(party)).toBe(0);
    });
  });
```

2024-09-18 16:26 UTC, flx-sta commented on src/test/utils/helpers/overridesHelper.ts
> +  unlockUnlockable(unlockable: Unlockables[]) {
quite the name. 💀 

Missing docs

2024-09-18 16:26 UTC, flx-sta commented on src/ui/modifier-select-ui-handler.ts
> +    this.scene.updateAndShowText(750, this.scene.gameMode.modeId === GameModes.DAILY);
Still not using `isDaily()`?

2024-09-18 16:27 UTC, RedstonewolfX commented on src/battle-scene.ts
> +  updateAndShowText(duration: number, isDaily?: boolean): void {
Huh?

2024-09-18 16:29 UTC, RedstonewolfX commented on src/ui/modifier-select-ui-handler.ts
> +    this.scene.updateAndShowText(750, this.scene.gameMode.modeId === GameModes.DAILY);
Whoops

2024-09-18 16:31 UTC, RedstonewolfX commented on src/test/game-mode.test.ts
> +  //*/
Okay, thanks

2024-09-18 16:36 UTC, RedstonewolfX commented on src/battle-scene.ts
> +  updateAndShowText(duration: number, isDaily?: boolean): void {
Oh, you want me to make documentation for this since I changed it

2024-09-18 16:40 UTC, RedstonewolfX commented on src/modifier/modifier-type.ts
> +    new WeightedModifierType(modifierTypes.MINI_BLACK_HOLE, (party: Pokemon[]) => (party[0].scene.gameMode.isDaily || (!party[0].scene.gameMode.isFreshStartChallenge() && party[0].scene.gameData.isUn
gameMode is defined within the function that places Eviolite in Rogue tier; it throws a scope error when I attempt to do this.

2024-09-18 16:42 UTC, RedstonewolfX commented on src/modifier/modifier-type.ts
> +export const itemPoolChecks: Map<ModifierTypeKeys, boolean> = new Map();
Simplest thing I could think of, really
Makes it easy to set keys and clear all keys

2024-09-18 17:24 UTC, RedstonewolfX commented on src/system/version-converter.ts
I can barely write tests, I promise you I will be no help whatsoever with the version converter

2024-09-18 17:27 UTC, RedstonewolfX commented on src/overrides.ts
>    readonly BYPASS_TUTORIAL_SKIP: boolean = false;
Actually, that one is mine, I will fix that

2024-09-18 17:30 UTC, RedstonewolfX commented on src/overrides.ts
>    readonly BYPASS_TUTORIAL_SKIP: boolean = false;
oh wait it showed the wrong line in the preview

2024-09-18 18:28 UTC, RedstonewolfX commented
Still in progress; will request a review once I am done

2024-09-19 15:25 UTC, RedstonewolfX commented
You gotta be kidding me

2024-09-19 15:33 UTC, RedstonewolfX commented on src/test/daily_mode.test.ts
I put this on line 142:
`vi.spyOn(party[0],"getLuck").mockReturnValue(3);`
Is the mock not being reset properly, and resulting in all Pokémon being shiny?

2024-09-19 15:45 UTC, RedstonewolfX commented
Nvm fixed it

2024-09-19 16:16 UTC, f-fsantos requested changes

2024-09-19 16:16 UTC, f-fsantos commented on src/modifier/modifier-type.ts
> +    return 0;
this should be dynamic based on the daily seed, not always 0. that would also cut down the amount of if(daily) going around.

2024-09-19 16:20 UTC, DayKev commented on src/modifier/modifier-type.ts
>    return luck || 0;
```suggestion
  return luck ?? 0;
```
Might as well change this too since you're already editing the function.

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +// Need to fix eviolite - test keeps insisting it is not in loot table, even though Mini Black Hole (which is using the exact same condition) is
I assume these were fixed.
```suggestion
```

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +    await game.classicMode.runToSummon();
```suggestion
    await game.classicMode.startBattle();
```
This wouldn't have worked before I changed tests to use `SET` battle style by default lol.

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +    await game.dailyMode.runToSummon();
```suggestion
    await game.dailyMode.startBattle();
```

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +    await game.classicMode.runToSummon([Species.PIKACHU]);
```suggestion
    await game.classicMode.startBattle([Species.PIKACHU]);
```

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +import { BattleEndPhase } from "#app/phases/battle-end-phase";
```suggestion
```

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +    await game.phaseInterceptor.to(BattleEndPhase);
```suggestion
    await game.phaseInterceptor.to("BattleEndPhase");
```

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +    //vi.clearAllMocks();
```suggestion
```

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +    expect(party[0]).toBeDefined();
```suggestion
```

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +    await game.dailyMode.runToSummon();
```suggestion
    await game.dailyMode.startBattle();
```

2024-09-19 16:20 UTC, DayKev commented on src/test/daily_mode.test.ts
> +    expect(party[0]).toBeDefined();
```suggestion
```

2024-09-19 16:20 UTC, DayKev commented on src/test/utils/helpers/modifiersHelper.ts
> +
```suggestion
```

2024-09-19 16:20 UTC, DayKev commented on src/test/utils/helpers/modifiersHelper.ts
> +   * Note that all modifiers are updated during the start of SelectModifierPhase.
```suggestion
   * Note that all modifiers are updated during the start of `SelectModifierPhase`.
```

2024-09-19 16:20 UTC, DayKev commented on src/test/utils/helpers/modifiersHelper.ts
> +  checkHasRun(modifier: ModifierTypeKeys): boolean {
I think this could use a better name, it's a bit ambiguous as-is (and is also missing docs).

2024-09-19 16:20 UTC, DayKev commented on src/test/utils/helpers/modifiersHelper.ts
> +   * @returns this
```suggestion
   * @param expectToBePreset Whether the Modifier should be in the Modifier Pool. Set to `false` to expect it to be absent instead.
   * @returns `this`
```

2024-09-19 16:20 UTC, DayKev commented on src/test/utils/helpers/overridesHelper.ts
> +   * @returns this
```suggestion
   * @param unlockable The Unlockable(s) to enable.
   * @returns `this`
```

2024-09-19 16:48 UTC, RedstonewolfX commented on src/modifier/modifier-type.ts
> +    return 0;
The point of this PR is to disable luck in Daily so that Shinies do not result in players having different runs than each another

2024-09-19 16:52 UTC, RedstonewolfX commented on src/modifier/modifier-type.ts
> +    return 0;
Ah, I see the discussion in discord now

2024-09-19 16:53 UTC, RedstonewolfX commented on src/test/daily_mode.test.ts
> +// Need to fix eviolite - test keeps insisting it is not in loot table, even though Mini Black Hole (which is using the exact same condition) is
Yep, that’s my bad lol

2024-09-19 17:25 UTC, RedstonewolfX commented on src/test/utils/helpers/modifiersHelper.ts
> +  checkHasRun(modifier: ModifierTypeKeys): boolean {
Ok, I’ll fix that once I’m home (or find time before then)

2024-09-24 23:01 UTC, flx-sta commented on src/field/pokemon.ts
> +    const rand = new Utils.IntegerHolder(0);
Please don't use `IntegerHolder` but `NumberHolder` instead.

2024-09-24 23:44 UTC, DayKev commented on src/modifier/modifier-type.ts
> + * @returns A value between 0 and 14, or 0 if the player is in Daily Run mode.
```suggestion
 * @returns A number between 0 and 14 based on the party's total luck value, or a random number between 0 and 14 if the player is in Daily Run mode.
```

2024-09-25 00:30 UTC, RedstonewolfX commented on src/field/pokemon.ts
> +    const rand = new Utils.IntegerHolder(0);
Alright, thanks
I also used IntegerHolder in another file, and updated that to NumberHolder as well

2024-09-25 01:37 UTC, flx-sta approved these changes

2024-09-25 16:47 UTC, flx-sta submitted a review, later dismissed

2024-09-25 16:48 UTC, damocleas submitted a review, later dismissed

2024-09-25 21:28 UTC, DayKev submitted a review, later dismissed

2024-09-25 23:38 UTC, DayKev reviewed
Noticed something on second look, also:
![image](https://github.com/user-attachments/assets/19af26b6-f889-4e69-b595-234d9554f34f)

2024-09-25 23:38 UTC, DayKev commented on src/modifier/modifier-type.ts
> +        return party.some(p => ((p.getSpeciesForm(true).speciesId in pokemonEvolutions) || (p.isFusion() && (p.getFusionSpeciesForm(true).speciesId in pokemonEvolutions))) && !p.getHeldItems().some(i
Don't forget to put the `!p.isMax()` condition back in.

2024-09-26 07:41 UTC, RedstonewolfX commented
Resolved, thanks @DayKev

2024-09-26 07:52 UTC, DayKev approved these changes

2024-09-26 07:52 UTC, DayKev commented on src/modifier/modifier-type.ts
> +        return party.some(p => ((p.getSpeciesForm(true).speciesId in pokemonEvolutions) || (p.isFusion() && (p.getFusionSpeciesForm(true).speciesId in pokemonEvolutions))) && !p.getHeldItems().some(i
```suggestion
        return party.some(p => ((p.getSpeciesForm(true).speciesId in pokemonEvolutions) || (p.isFusion() && (p.getFusionSpeciesForm(true).speciesId in pokemonEvolutions)))
          && !p.getHeldItems().some(i => i instanceof Modifiers.EvolutionStatBoosterModifier) && !p.isMax()) ? 10 : 0;
```

2024-09-26 08:34 UTC, innerthunder approved these changes

2024-09-26 08:37 UTC, damocleas approved these changes

2024-09-26 08:40 UTC, merged