Weather & evolution i18n with french translations
pagefaultgames/pokerogue pull request #380
Opened 2024-05-01 15:27 UTC by suriinam

- Added Yes/No translation entries 
- Added evolution related translation entries
- Added weather related translation entries

2024-05-01 16:16 UTC, Flashfyre submitted a review, later dismissed

2024-05-01 16:16 UTC, Flashfyre commented on src/locales/fr/menu.ts
> +  "yes": "Oui",
Please add all new entries to all other languages as English.

2024-05-01 17:20 UTC, suriinam commented on src/locales/fr/menu.ts
> +  "yes": "Oui",
@Flashfyre done !

2024-05-01 19:06 UTC, Dakurei requested changes
Missing spaces between certain punctuation marks in French
Especially all the words stuck to the "!" and "?"

2024-05-01 19:40 UTC, suriinam commented
> Missing spaces between certain punctuation marks in French Especially all the words stuck to the "!" and "?"
True that in french a space before punctuation is mandatory but in the official Pokémon games it's not there...
![](https://www.pokepedia.fr/images/8/8b/Temp%C3%AAtesable_E.gif)

What should we do ? :)

2024-05-01 19:43 UTC, Dakurei commented
> https://github.com/pagefaultgames/pokerogue/assets/8146474/63e07fbd-015c-41bf-b3c3-826cdb904527

What should we do ? :)

2024-05-02 15:24 UTC, Dakurei approved these changes

2024-05-02 15:27 UTC, Dakurei commented
I think some phrases have been translated literally, and don't match what's in the officials games (especially the harshSun that comes to mind), but this can be modified later if necessary 👍

2024-05-15 15:48 UTC, suriinam commented
> No update here?

Updated

2024-05-15 16:16 UTC, bennybroseph approved these changes

2024-05-15 17:31 UTC, merged