Implemented "Emergency Exit" and "Wimp Out"
pagefaultgames/pokerogue pull request #384
Opened 2024-05-01 19:50 UTC by Korwai

Added Wimpod's and Golisopod's ability to forcibly retreat upon reaching 50% HP or less.

- https://bulbapedia.bulbagarden.net/wiki/Emergency_Exit_(Ability)

I've tested that it works for the player's Golisopod in singles and doubles (wild and trainer). It also works in singles for wild and enemy trainers. Berries also activate before the HP condition check.

2024-05-15 17:35 UTC, bennybroseph commented
Would like to check this out if the conflicts can be resolved. Seems like reverse U-Turn which is not behaving nicely like in your video.

2024-05-19 13:53 UTC, bennybroseph requested changes
Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

2024-05-20 22:52 UTC, Korwai commented on src/data/ability.ts
> +        pokemon.scene.pushPhase(new BattleEndPhase(pokemon.scene));
Overlooked a few conditions here. I can't blindly push the end of battle phase if it's a double battle. Gotta check both pokemon are either not active or fainted, I think.

I might also have to look into the condition if pokemon 1 faints but pokemon 2 (Golisopod) flees. It should go to the reward phase.

2024-05-21 22:35 UTC, Korwai commented on src/phases.ts
> +                      Utils.executeIf(!isProtected && !chargeEffect && target.active, () => applyFilteredMoveAttrs((attr: MoveAttr) => attr instanceof MoveEffectAttr && (attr as MoveEffectAttr).trigg
Worried if this would cause trouble anywhere else but ultimately, if a pokemon flees, it's no longer active and we shouldn't check postDefend/postAttackAbAttrs after.

I was debating adding another status effect called FLED so that this behavior wouldn't affect anything else but I wasn't sure if it belonged as a status effect. Any thoughts on if this should be changed?

2024-05-21 22:37 UTC, Korwai commented on src/data/ability.ts
> +   */
Honestly, I'm not sure what 'passive' is since I copied it from the other AbAttr classes (that also don't make use of it).

2024-05-21 22:51 UTC, Korwai commented
Added JSDoc comments to most of the big classes/functions that I've added. I've also adjusted the logic for double battles for enemies. Happy to change anything if needed.

2024-06-02 23:48 UTC, flx-sta commented
I've tried it with 2 Pokemon (for both abilities) but neither of them wanted to use their ability ❌ 

<img width="986" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/1500ac6f-98e2-4bb3-812c-235aea483cab">
<img width="1009" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/98e350d7-a2a4-4c03-aaa3-dd35a34f7274">

<img width="1009" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/63c1377e-dbec-4c3f-b128-ac35422a8434">
<img width="999" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/b81e8df6-9935-418c-b7aa-45139fc0f3a9">

2024-06-02 23:51 UTC, flx-sta requested changes
### I've tried it with 2 Pokemon (for both abilities), against Wild Pkmn and trainer but neither of them switch out ❌ 

<img width="350" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/1500ac6f-98e2-4bb3-812c-235aea483cab"><img width="350" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/98e350d7-a2a4-4c03-aaa3-dd35a34f7274">

<img width="350" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/63c1377e-dbec-4c3f-b128-ac35422a8434"><img width="350" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/50131232/b81e8df6-9935-418c-b7aa-45139fc0f3a9">

2024-06-03 07:11 UTC, Korwai commented
Gah, I removed the line of code that was supposed to trigger the ability. That's my bad for not testing thoroughly before pushing. I'll update it and test it again.

2024-06-03 08:34 UTC, Korwai commented on src/data/ability.ts
> +        pokemon.scene.time.delayedCall(200, () => {
I added this in because it was difficult to tell the final HP of the pokemon visually after a hit since the ability triggers immediately after. This make it easier to read at lower game speeds (1x, 2x) but anything higher, it looks the same visually.

Not sure if this is the right way to go about doing this because I believe this is triggering this function 200ms later which can lead to unexpected behavior.

2024-06-03 08:57 UTC, Korwai commented
Here's some sample videos of my testing.

Enemy trainers properly switch with parties of 3+ non-fainted mons in double battles.
https://github.com/pagefaultgames/pokerogue/assets/24775950/a03335ab-1866-414f-a6fc-4de294f79610

As long as one wild mon dies in a double battle, it will trigger a reward phase.
https://github.com/pagefaultgames/pokerogue/assets/24775950/7a841076-c1dc-4981-bcad-ad042c0d847a

Enemy trainers properly switch with parties of 2+ non-fainted mons in single battles. Also, status effects don't trigger the forced switch.
https://github.com/pagefaultgames/pokerogue/assets/24775950/c5e0c2e6-259c-4f44-81b7-eb2dfd28beb6

I'm aware right now that berries do not trigger before the check but they still get consumed.

2024-06-03 14:49 UTC, flx-sta commented on src/data/ability.ts
> +        pokemon.scene.time.delayedCall(200, () => {
Hi don’t k ow what to think about this. I get the idea but hard-coded delays are … ouf…

2024-06-03 14:59 UTC, OrangeRed commented on src/data/ability.ts
> +
Is there any reason why this has to be `PostDamageAbAttr` and can't be a `PostMoveUsedAbAttr`?

2024-06-03 14:59 UTC, OrangeRed commented on src/data/ability.ts
> +    return new Promise<boolean>(resolve => {
Does this need to be a promise? Can't this be rewritten to simply return true / false instead?

2024-06-03 14:59 UTC, OrangeRed commented on src/data/ability.ts
> +      pokemon.scene.unshiftPhase(new BerryPhase(pokemon.scene));
Why are you triggering berry phase here? Doesn't berry phase trigger on its own at the end of the turn?

2024-06-04 02:09 UTC, Korwai commented on src/data/ability.ts
> +      pokemon.scene.unshiftPhase(new BerryPhase(pokemon.scene));
Forgot to remove, was part of my testing with berries not triggering before the check.

2024-06-04 02:13 UTC, Korwai commented on src/data/ability.ts
> +
From what I understand, the MovePhase triggers before the DamagePhase so I don't think it'd be able to check for different HP values from pre/post hits.

2024-06-04 02:39 UTC, OrangeRed commented on src/data/ability.ts
> +
PostTurnAbAttr should trigger after berries no?

2024-06-04 02:48 UTC, flx-sta commented on src/data/ability.ts
> +      pokemon.scene.unshiftPhase(new BerryPhase(pokemon.scene));
@Korwai advice for next time:
Put a `// TODO: remove` behind it, on the top of it

2024-06-04 02:58 UTC, Korwai commented on src/data/ability.ts
> +        pokemon.scene.time.delayedCall(200, () => {
Yeah... thinking about this more... this is a terrible way to do it.

I now know of a different way though. Triggering the ability during the TurnEndPhase would allow MoveEndPhase and BerryPhase messages to play before and should resolve this issue.

2024-06-04 02:59 UTC, Korwai commented on src/data/ability.ts
> +
Mistyped but yes. I think that's a better path.

2024-06-04 08:44 UTC, Korwai commented
More testing and cleaning, hopefully it's a bit less buggy now.

Multi-hits only trigger Emergency Exit/Wimp Out on the last hit. Berries will also proc before the ability checks HP.
<video src="https://github.com/pagefaultgames/pokerogue/assets/24775950/f6495cfc-d260-4ebe-8a8c-90c624f89c61
" width="300" />

U-Turn will not trigger if it triggers the opponent's Emergency Exit/Wimp Out skill.
<video src="https://github.com/pagefaultgames/pokerogue/assets/24775950/ffaf2225-d113-458b-b58f-afa65d7cab39
" width="300" />

2024-06-05 13:31 UTC, EvasiveAce commented
Does your Wimp Out/Emergency Exit allow you to choose who you switch in to, or is it random?

2024-06-05 15:05 UTC, flx-sta commented
> Does your Wimp Out/Emergency Exit allow you to choose who you switch in to, or is it random?

You can see that behavior on his [first comment](https://github.com/pagefaultgames/pokerogue/pull/384#issue-2274090909) in the gif.

2024-06-05 15:59 UTC, EvasiveAce commented
> > Does your Wimp Out/Emergency Exit allow you to choose who you switch in to, or is it random?
> 
> You can see that behavior on his [first comment](https://github.com/pagefaultgames/pokerogue/pull/384#issue-2274090909) in the gif.

I know, I was just seeing if its changed. If not, add me on Discord because I have code for it to be random. @Korwai 

EvasiveAce

2024-06-05 20:13 UTC, Korwai commented
> > > Does your Wimp Out/Emergency Exit allow you to choose who you switch in to, or is it random?
> > 
> > 
> > You can see that behavior on his [first comment](https://github.com/pagefaultgames/pokerogue/pull/384#issue-2274090909) in the gif.
> 
> I know, I was just seeing if its changed. If not, add me on Discord because I have code for it to be random. @Korwai
> 
> EvasiveAce

Still the same behaviour as the first gif. I'm pretty sure Emergency Exit/Wimp Out allows you to choose which pokemon you want to swap into if the HP condition is met.

Source: https://youtu.be/3MBXB7hozaA?si=AWXmxAwY2MJpB6oz&t=985 (audio/volume warning)

2024-06-05 20:52 UTC, EvasiveAce commented
> > > > Does your Wimp Out/Emergency Exit allow you to choose who you switch in to, or is it random?
> > > 
> > > 
> > > You can see that behavior on his [first comment](https://github.com/pagefaultgames/pokerogue/pull/384#issue-2274090909) in the gif.
> > 
> > 
> > I know, I was just seeing if its changed. If not, add me on Discord because I have code for it to be random. @Korwai
> > EvasiveAce
> 
> Still the same behaviour as the first gif. I'm pretty sure Emergency Exit/Wimp Out allows you to choose which pokemon you want to swap into if the HP condition is met.
> 
> Source: https://youtu.be/3MBXB7hozaA?si=AWXmxAwY2MJpB6oz&t=985 (audio/volume warning)

Damn that sucks they changed it. Anyways good PR

2024-06-14 03:42 UTC, closed without merging

2024-06-14 03:42 UTC, Korwai commented
Well, I messed up that rebase. Closing this PR for a cleaner slate.

2024-06-14 05:42 UTC, flx-sta commented
Please link the slate