[Enhancement] add font size option per language on registration UI
pagefaultgames/pokerogue pull request #3849
Opened 2024-08-27 15:59 UTC by KimJeongSun

## What are the changes the user will see?

Spanish-language users will see a more polished and organized register menu screen.

## Why am I making these changes?

There was a request from @AsdarDevelops  to make these changes!

## What are the changes from a developer perspective?

I modified `registration-form-ui-handler.ts` to allow font settings for each language.

### Screenshots/Videos

- before
![image](https://github.com/user-attachments/assets/86b8a8f7-e284-4595-b64a-3c6efb258c04)

- after
<img width="1689" alt="Screenshot 2024-08-28 at 12 39 11 AM" src="https://github.com/user-attachments/assets/eca2ef03-de3b-4937-b18e-afea912f4e69">

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-08-27 16:09 UTC, KimJeongSun commented
@flx-sta 

Actually, while working on the above changes, I also planned to organize the German version. However, the problem with the German version is that the button sizes need to be adjusted as well.

Below is a screenshot where I only adjusted the button labels’ size: ([related commit](https://github.com/pagefaultgames/pokerogue/pull/3849/commits/b6396771fdd70db1c3ee4ddeec98943e7d23d070))
<img width="1689" alt="Screenshot 2024-08-28 at 12 46 34 AM" src="https://github.com/user-attachments/assets/ecfe0872-9d7b-463f-a6de-13851600d28f">

As you can see, in my previous attempt, the button sizes didn't reduce properly.

If possible, adding this feature might make it more flexible and better. Additionally, you can consider refactoring my code by inheriting classes, if possible! (It was a bit too much for me)

Of course, if it’s not possible to work on this immediately, we can proceed as is and add further developments later.

2024-08-27 16:13 UTC, CodeTappert commented
Please also for german. I think the text is too big there too

2024-08-27 16:13 UTC, KimJeongSun commented
@flx-sta 🙏

2024-08-27 16:44 UTC, flx-sta submitted a review, later dismissed

2024-08-27 16:55 UTC, KimJeongSun commented on src/ui/registration-form-ui-handler.ts
> +const languageSettings: { [key: string]: LanguageSetting } = {
Next time, we should consider gathering the relevant settings from each source file (this, starter UI etc.) and putting them into JSON keys in a PR.

2024-08-28 08:01 UTC, KimJeongSun commented
@flx-sta
can you make new PR to beta ( or PR toward this PR ) for DE updates? ( including resize button size + button label font size )?

2024-08-28 14:52 UTC, flx-sta commented
> @flx-sta can you make new PR to beta ( or PR toward this PR ) for DE updates? ( including resize button size + button label font size )?

that would be @CodeTappert

2024-08-29 08:34 UTC, AsdarDevelops approved these changes
Thank you so much

2024-08-29 08:34 UTC, AsdarDevelops commented on src/locales/es/menu.json
> +  "confirmPassword": "Confirmar Contraseña",
```suggestion
  "confirmPassword": "Confirmar contraseña",
```

2024-08-29 08:39 UTC, f-fsantos requested changes

2024-08-29 08:39 UTC, f-fsantos commented on src/ui/registration-form-ui-handler.ts
> +    const label = addTextObject(this.scene, 10, 87, i18next.t("menu:registrationAgeWarning"), TextStyle.TOOLTIP_CONTENT, { fontSize: warningMessageFontSize ?? "42px" });
Put the default "42px" value when warningMessageFontSize is being assigned please, it's easy to miss that the variable may contain a null value

2024-09-02 12:59 UTC, SangaraSorama approved these changes

2024-09-03 12:03 UTC, CodeTappert approved these changes

2024-09-05 09:52 UTC, f-fsantos approved these changes

2024-09-05 09:53 UTC, merged