Update italian pokemon-stat.ts
pagefaultgames/pokerogue pull request #389
Opened 2024-05-01 21:52 UTC by Adri1

2024-05-01 23:14 UTC, Flashfyre requested changes

2024-05-01 23:14 UTC, Flashfyre commented on src/locales/it/pokemon-stat.ts
> +    "HP": "PS",
Can we include the 'Max' part, whatever the equivalent is?

2024-05-01 23:25 UTC, Adri1 commented on src/locales/it/pokemon-stat.ts
> +    "HP": "PS",
If you prefer yes, you can put "PS Max".
I scrapped because it seems to not exist anywhere in any official italian translation + I also took example on the French translation of this file which also does not include "Max"

2024-05-01 23:30 UTC, Flashfyre commented on src/locales/it/pokemon-stat.ts
> +    "HP": "PS",
The French translation made an error there

2024-05-02 12:36 UTC, Flashfyre approved these changes

2024-05-02 12:37 UTC, merged