[Beta][Misc] Banner
pagefaultgames/pokerogue pull request #3926
Opened 2024-08-30 22:41 UTC by frutescens

## What are the changes the user will see?
They will see the event banner. 

## Why am I making these changes?
I want to avoid repetitive questions so hopefully this banner will answer some of them.

## What are the changes from a developer perspective?
X-position, Y-Position, and Scale variables added to timed-event-manager banner to improve ease of adding banners for the future.
Generic Event Type (No shiny boost) added. 

### Screenshots/Videos
![image](https://github.com/user-attachments/assets/c48206d8-1d1a-498c-96fb-ceab747af874)

## How to test the changes?
Run PokeRogue and open the title page.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-08-30 22:50 UTC, DayKev commented on src/timed-event-manager.ts
> +    endDate: new Date(Date.UTC(2024, 8, 15, 0)),
July 28th to August 15th? 🤔

2024-08-30 22:53 UTC, DayKev commented on src/timed-event-manager.ts
>      console.log(this.event?.bannerFilename);
```suggestion
    this.event = this.event!; // TODO: resolve the `!` issue
    console.log(this.event?.bannerFilename);
```
And then remove all the `!` from the various `this.event` calls after this.

2024-08-30 22:57 UTC, flx-sta commented on src/timed-event-manager.ts
> +    endDate: new Date(Date.UTC(2024, 8, 15, 0)),
Sadly javascript uses 0 indexed month. You can see that from the removed events.
So 
```
0 -> January
1 -> February
...
7 -> August
8 -> September
...
11 -> December
```

2024-08-30 22:58 UTC, flx-sta commented on src/timed-event-manager.ts
>      console.log(this.event?.bannerFilename);
Might remove the one from the console then too :D

2024-08-30 22:58 UTC, flx-sta commented on src/timed-event-manager.ts
>      console.log(this.event?.bannerFilename);
But it would be cleaner to put a proper `this.event` check up instead of just telling the compiler `Yes! it's defined`.

2024-08-31 01:10 UTC, frutescens commented on src/timed-event-manager.ts
>      console.log(this.event?.bannerFilename);
Removed the bangs!

2024-08-31 01:57 UTC, DayKev commented on src/timed-event-manager.ts
> +    endDate: new Date(Date.UTC(2024, 8, 15, 0)),
That's... very dumb.

2024-08-31 03:00 UTC, flx-sta submitted a review, later dismissed

2024-08-31 09:32 UTC, DayKev commented on src/timed-event-manager.ts
> +      this.eventTimerText.setText(this.timeToGo(this.event!.endDate));
```suggestion
    if (this.event && this.event.eventType !== EventType.GENERIC) {
      this.eventTimerText.setText(this.timeToGo(this.event.endDate));
```

2024-08-31 13:13 UTC, torranx commented on src/timed-event-manager.ts
> +  scale?: number;
wouldnt this be better if it is in a separate interface and extend it here?

2024-08-31 16:45 UTC, frutescens commented on src/timed-event-manager.ts
> +  scale?: number;
how so?

2024-08-31 19:05 UTC, torranx commented on src/timed-event-manager.ts
> +  scale?: number;
```
interface EventBanner {
  bannerFilename?: string;
  xPosition?: number;
  yPosition?: number;
  scale?: number;
}

interface TimedEvent extends EventBanner {...}
```

2024-08-31 19:19 UTC, frutescens commented on src/timed-event-manager.ts
> +  scale?: number;
Thank you! It's been updated.

2024-08-31 19:41 UTC, torranx approved these changes

2024-09-01 18:02 UTC, torranx submitted a review, later dismissed

2024-09-01 19:16 UTC, f-fsantos requested changes

2024-09-01 19:16 UTC, f-fsantos commented on src/timed-event-manager.ts
> +      // this.bannerShadow.setOrigin(0,0);
```suggestion
```

2024-09-01 19:18 UTC, merged