[Feature] Add Mystery Encounters to the game
pagefaultgames/pokerogue pull request #3938
Opened 2024-08-31 15:51 UTC by ben-lear

## What are the changes the user will see?

## Why am I making these changes?

## What are the changes from a developer perspective?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-07 15:31 UTC, ben-lear commented on src/battle-scene.ts
> +              // const isTransferable = mt.isTransferable ?? true;
this needs to be an added enhancement to allow setting isTransferable

2024-09-07 15:42 UTC, CodeTappert commented on src/locales/en/trainer-names.json
> +  "buck": "Buck",
```suggestion
  "piers_marnie_double": "Piers & Marnie",
  
  // Mystery Encounters
  "buck": "Buck",
```

2024-09-07 15:43 UTC, CodeTappert commented on src/locales/en/dialogue.json
> +  },
You can not have more encounter then victory lines.
Pleae add the same amount to all of them.

2024-09-08 00:12 UTC, frutescens requested changes
I tested the 'A Trainer's Test' and 'Dancing Lessons' but something weird happened. Also, if you could send me the session data for defeats related to MEs that would be helpful.

https://github.com/user-attachments/assets/90e22a6c-87b2-49e9-8bd1-79dbba82d3ee

I set the rate to 256 so the weird double bird generation at the end may be related to that. But in my opinion the level up + move learning phase should probably occur after the teacher provides feedback. It's a bit confusing other wise.

Run History is a bit wonky too. 
![image](https://github.com/user-attachments/assets/340c608f-939e-47ab-af2e-248d31631a53)
![image](https://github.com/user-attachments/assets/500663aa-fdb0-4755-b438-a537741ce99d)

2024-09-08 00:12 UTC, frutescens commented on src/enums/mystery-encounter-type.ts
> +  UNCOMMON_BREED,
I think it would be nice to change the 'Met at Plains' to a 'Met in a Mysterious Encounter' but up to you

![image](https://github.com/user-attachments/assets/4b6386fb-d983-4a09-b988-0eb7cbc59e5e)

2024-09-08 00:18 UTC, frutescens requested changes
Will have to look through each file more.

2024-09-08 00:18 UTC, frutescens commented on .github/pull_request_template.md
> +- [ ] If I have text, did I add make it translatable and added a key in the English language?
I think this file is a stray file from a previous version of beta.

2024-09-08 00:18 UTC, frutescens commented on src/battle.ts
> +  WILD,
I think you might have deleted the indents here

2024-09-08 00:18 UTC, frutescens commented on src/battle.ts
>  export enum BattlerIndex {
and here

2024-09-08 00:18 UTC, frutescens commented on src/battle.ts
> +  command: Command;
Here too.

2024-09-08 10:44 UTC, AsdarDevelops requested changes
Reviewed first 5 locale files.

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/a-trainers-test-dialogue.json
The name of the 5 trainers (Buck, Cheryl, Marley, Mira, Riley) should be called from trainers-name and be added there.

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +  "intro": "A Greedent ambushes you\nand steals your party's berries!",
All entries containing "Greedent" should call it from pokemon.json instead

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +  "description": "The Greedent has caught you totally off guard now all your berries are gone!\n\nThe Greedent looks like it's about to eat them when it pauses to look at you, interested.",
Two entries here

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +      "food_stash": "It looks like the Greedent was guarding an enormous stash of food!$@s{item_fanfare}Each Pokémon in your party gains 1x Reviver Seed!"
Three more here, and also a reference to "Reviver Seed" which should probably call its name from modifiers

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +      "selected": "Your pleading strikes a chord with the Greedent.$It doesn't give all your berries back, but still tosses a few in your direction."
Another Greedent here

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +  "description": "The Greedent has caught you totally off guard now all your berries are gone!\n\nThe Greedent looks like it's about to eat them when it pauses to look at you, interested.",
I think two "\n" push the text out of visibility

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +      "selected": "The Greedent devours the entire\nstash of berries in a flash!$Patting its stomach,\nit looks at you appreciatively.$Perhaps you could feed it\nmore berries on your adventure...$@s{
Two more "Greendent" here. Also I think three "\n" is too many and the dialogue box where this pops can only hold one. After that, you need to use "$" if I'm not mistaken

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "selected": "My word, we're being robbed, Liepard!\n       $You'll be hearing from my lawyers for this!"
This one needs to be called from pokemon.json. Also, does the "\n     " make sense considering there's already a "$" ?

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "selected": "What a rotten day...$Ah, well. Let's return to the yacht club then, Liepard."
Same thing

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/berries-abound-dialogue.json
> +  "description": "It looks like there's a strong Pokémon guarding a berry bush. Battling is the straightforward approach, but this Pokémon looks strong. Maybe a fast Pokémon would be able to grab som
It is a Pokémon game, but we are repeating "Pokémon" way too much here. Perhaps we use "it" instead?

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/bug-type-superfan-dialogue.json
> +  "title": "The Bug-Type Superfan",
Should probably be added as its own entry in trainers-name and called from there

2024-09-08 10:44 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/bug-type-superfan-dialogue.json
> +      "disabled_tooltip": "You need to have a Quick Claw, Grip Claw, or Silver Powder to select this.",
These all should be called from modifiers

2024-09-08 10:52 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/clowning-around-dialogue.json
> +  "description": "Something is off about this encounter. The clown seems eager to goad you into a battle, but to what end?\n\nThe Blacephalon is especially strange, like it has @[TOOLTIP_TITLE]{weird
Blacephalon should be called from pokemon.json

2024-09-08 11:07 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/uncommon-breed-dialogue.json
> +      "stat_boost": "The {{enemyPokemon}} heightened abilities boost its stats!"
I'll add this to my locale suggestions

2024-09-09 13:02 UTC, ben-lear commented on src/locales/en/dialogue.json
> +  },
fixed

2024-09-09 13:04 UTC, ben-lear commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +  "intro": "A Greedent ambushes you\nand steals your party's berries!",
why? These lines are all going to be translated regardless, there is no need to pass Greedent name as a token

2024-09-09 13:04 UTC, ben-lear commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +  "description": "The Greedent has caught you totally off guard now all your berries are gone!\n\nThe Greedent looks like it's about to eat them when it pauses to look at you, interested.",
The text scrolls

2024-09-09 13:08 UTC, ben-lear commented on src/locales/en/mystery-encounters/a-trainers-test-dialogue.json
they are already in trainer-names.ts...

2024-09-09 13:09 UTC, ben-lear commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +      "food_stash": "It looks like the Greedent was guarding an enormous stash of food!$@s{item_fanfare}Each Pokémon in your party gains 1x Reviver Seed!"
There is no need to tokenize the names of Pokemon/items in encounters where that is the only thing you can see with that name.

2024-09-09 14:50 UTC, AsdarDevelops commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +      "food_stash": "It looks like the Greedent was guarding an enormous stash of food!$@s{item_fanfare}Each Pokémon in your party gains 1x Reviver Seed!"
What if the item reward wanted to be change to a different seed/item in the future?

2024-09-09 16:07 UTC, ben-lear commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +  "intro": "A Greedent ambushes you\nand steals your party's berries!",
Resolving, as there is no need to tokenize an item or Pokemon name for something that is completely static in an encounter.

2024-09-09 16:07 UTC, ben-lear commented on src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
> +      "food_stash": "It looks like the Greedent was guarding an enormous stash of food!$@s{item_fanfare}Each Pokémon in your party gains 1x Reviver Seed!"
we can tokenize the item name, but there is no need for Greedent

2024-09-09 16:52 UTC, ben-lear commented on src/locales/en/mystery-encounters/bug-type-superfan-dialogue.json
> +  "title": "The Bug-Type Superfan",
it is in trainer names as well, but the two should be separated

2024-09-09 21:08 UTC, ben-lear commented on src/battle-scene.ts
> +  public lastMysteryEncounter?: MysteryEncounter;
if the previous wave was a ME, that is what this property will contain

2024-09-09 21:15 UTC, ben-lear commented on src/battle-scene.ts
> +      const highestMysteryEncounterWave = 180;
moved to game mode config

2024-09-09 21:15 UTC, ben-lear commented on src/battle-scene.ts
> +      const lowestMysteryEncounterWave = 10;
moved to game mode config

2024-09-09 21:18 UTC, ben-lear commented on src/battle-scene.ts
> +        const roll = Utils.randSeedInt(256);
moved to exported const with other values

2024-09-09 21:19 UTC, ben-lear commented on src/battle-scene.ts
> +      const resetArenaState = isNewBiome || this.currentBattle.battleType === BattleType.TRAINER || this.currentBattle.battleType === BattleType.MYSTERY_ENCOUNTER || this.currentBattle.battleSpec ===
fixed

2024-09-09 21:22 UTC, ben-lear commented on src/battle-scene.ts
> +  removePokemonFromPlayerParty(pokemon: PlayerPokemon, destroy: boolean = true) {
fixed

2024-09-09 22:51 UTC, flx-sta reviewed
Didn't finish everything 
<img width="151" alt="image" src="https://github.com/user-attachments/assets/b5954b36-d063-450f-b8e2-c00ccb298422">


---

Some of those:
```
NIT
Missing tsdoc or wrong scope (private/public/protected)
```
Could also be resolved by putting a `override` in front which should adopt the parent ts-doc (if existing 💀 )

---

I might have marked some `constructor` with `NIT: Missing tsdoc`. My bad...

2024-09-09 22:51 UTC, flx-sta commented on src/phases/faint-phase.ts
> +      if (this.scene.currentBattle.battleType === BattleType.TRAINER || this.scene.currentBattle.battleType === BattleType.MYSTERY_ENCOUNTER) {
NIT
```suggestion
      if ([BattleType.TRAINER, BattleType.MYSTERY_ENCOUNTER].includes(this.scene.currentBattle.battleType)) {
```

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  constructor(type: ModifierTypes.PokemonBaseStatTotalModifierType, pokemonId: integer, statModifier: integer, stackCount?: integer) {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  matchType(modifier: Modifier): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  getArgs(): any[] {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  shouldApply(args: any[]): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  apply(args: any[]): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  getScoreMultiplier(): number {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  getArgs(): any[] {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  shouldApply(args: any[]): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  apply(args: any[]): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  getScoreMultiplier(): number {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  constructor (type: ModifierType, pokemonId: integer, stackCount?: integer) {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  matchType(modifier: Modifier): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  clone(): PersistentModifier {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  shouldApply(args: any[]): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  apply(args: any[]): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  getMaxHeldItemCount(pokemon?: Pokemon): integer {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  constructor(type: ModifierType, stackCount?: integer) {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  getMaxStackCount(scene: BattleScene): integer {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  apply(args: any[]): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  clone(): HealShopCostModifier {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +  match(modifier: Modifier): boolean {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +export class BoostBugSpawnModifier extends PersistentModifier {
NIT: 
Missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier.ts
> +export class PokemonBaseStatTotalModifier extends PokemonHeldItemModifier {
NIT: 
Missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +export class AddPokeballModifierType extends ModifierType {
NIT: 
Missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +  constructor(statModifier: integer) {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +  getDescription(scene: BattleScene): string {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +  getDescription(scene: BattleScene): string {
NIT
Missing tsdoc or wrong scope (private/public/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/modifier/modifier-type.ts
> +function getNewModifierTypeOption(party: Pokemon[], poolType: ModifierPoolType, tier?: ModifierTier, upgradeCount?: integer, retryCount: integer = 0, allowLuckUpgrades: boolean = true): ModifierTypeO
NIT: missing tsdocs

2024-09-09 22:51 UTC, flx-sta commented on src/locales/en/mystery-encounter.ts
Can we merge this into the `config.ts` in every language as we want to get rid of all `ts` files in locales in the long run anyway

2024-09-09 22:51 UTC, flx-sta commented on src/game-mode.ts
> +import MAX_SAFE_INTEGER = Phaser.Math.MAX_SAFE_INTEGER;
I've never seen an import like that

2024-09-09 22:51 UTC, flx-sta commented on src/game-mode.ts
> +    return new GameMode(GameModes.CLASSIC, { isClassic: true, hasTrainers: true, hasMysteryEncounters: true, maxMysteryEncounterWave: 180, minMysteryEncounterWave: 10 }, classicFixedBattles);
Those `min` and `max` values should life in some constants instead of being spread through the code-base

2024-09-09 22:51 UTC, flx-sta commented on src/field/mystery-encounter-intro.ts
> +  playAnim(): void {
NIT:
Missing tsdoc or wrong scope (public/private/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/field/mystery-encounter-intro.ts
> +  getTintSprites(): Phaser.GameObjects.Sprite[] {
NIT:
Missing tsdoc or wrong scope (public/private/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/field/mystery-encounter-intro.ts
> +  tint(sprite, color: number, alpha?: number, duration?: integer, ease?: string): void {
NIT:
Missing tsdoc or wrong scope (public/private/protected)

missing type for `sprite`

2024-09-09 22:51 UTC, flx-sta commented on src/field/mystery-encounter-intro.ts
> +  tintAll(color: number, alpha?: number, duration?: integer, ease?: string): void {
NIT:
Missing tsdoc or wrong scope (public/private/protected)

2024-09-09 22:51 UTC, flx-sta commented on src/field/mystery-encounter-intro.ts
> +export default interface MysteryEncounterIntroVisuals {
this still required?

2024-09-09 22:51 UTC, flx-sta commented on src/enums/mystery-encounter-tier.ts
> +  MASTER = 0 // Not currently used
Still not used?

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-transformation-sequence.ts
> +function doSpiralUpward(scene: BattleScene, transformationBaseBg, transformationContainer, xOffset: number, yOffset: number) {
NIT; missing docs

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-transformation-sequence.ts
> +function doArcDownward(scene: BattleScene, transformationBaseBg, transformationContainer, xOffset: number, yOffset: number) {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-transformation-sequence.ts
> +function doCycle(scene: BattleScene, l: number, lastCycle: integer, pokemonTintSprite, pokemonEvoTintSprite): Promise<boolean> {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-transformation-sequence.ts
> +function doCircleInward(scene: BattleScene, transformationBaseBg, transformationContainer, xOffset: number, yOffset: number) {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-transformation-sequence.ts
> +function doSpiralUpwardParticle(scene: BattleScene, trigIndex: integer, transformationBaseBg, transformationContainer, xOffset: number, yOffset: number) {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-transformation-sequence.ts
> +function doCircleInwardParticle(scene: BattleScene, trigIndex: integer, speed: integer, transformationBaseBg, transformationContainer, xOffset: number, yOffset: number) {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> +export function getSpriteKeysFromSpecies(species: Species, female?: boolean, formIndex?: integer, shiny?: boolean, variant?: integer): { spriteKey: string, fileRoot: string } {
```suggestion
export function getSpriteKeysFromSpecies(species: Species, female?: boolean, formIndex?: number, shiny?: boolean, variant?: number): { spriteKey: string, fileRoot: string } {
```

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> +export function getSpriteKeysFromPokemon(pokemon: Pokemon): { spriteKey: string, fileRoot: string } {
NIT:
Missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> +function failCatch(scene: BattleScene, pokemon: EnemyPokemon, originalY: number, pokeball: Phaser.GameObjects.Sprite, pokeballType: PokeballType) {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> +function removePb(scene: BattleScene, pokeball: Phaser.GameObjects.Sprite) {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> +export async function doPokemonFlee(scene: BattleScene, pokemon: EnemyPokemon): Promise<void> {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> +export function getGoldenBugNetSpecies(scene: BattleScene, waveIndex: integer, level: integer): PokemonSpecies {
```suggestion
export function getGoldenBugNetSpecies(scene: BattleScene, waveIndex: number, level: number): PokemonSpecies {
```

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-dialogue-utils.ts
> +export function getEncounterText(scene: BattleScene, keyOrString?: string, primaryStyle?: TextStyle, uiTheme: UiTheme = UiTheme.DEFAULT): string | null {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-dialogue-utils.ts
> +function getTextWithDialogueTokens(scene: BattleScene, keyOrString?: string): string | null {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/requirements/can-learn-move-requirement.ts
> +  override getDialogueToken(_scene: BattleScene, _pokemon?: PlayerPokemon): [string, string] {
NIT: 
missing tsdoc

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +  pokemonMeetsPrimaryRequirements(scene: BattleScene, pokemon: Pokemon) {
NIT: 
missing tsdoc or wrong scope (p/p/p)

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +  meetsPrimaryRequirementAndPrimaryPokemonSelected(scene: BattleScene): boolean {
NIT: 
missing tsdoc or wrong scope (p/p/p)

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +  meetsSecondaryRequirementAndSecondaryPokemonSelected(scene: BattleScene): boolean {
NIT: 
missing tsdoc or wrong scope (p/p/p)

2024-09-09 22:51 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +  setDialogueToken(key: string, value: string): void {
NIT: 
missing tsdoc or wrong scope (p/p/p)

2024-09-09 23:48 UTC, ben-lear commented on src/ui/mystery-encounter-ui-handler.ts
> +  private optionScrollTweens: (Phaser.Tweens.Tween | null)[] = [null, null, null, null];
array has to be prefilled and it winds up like this lol

2024-09-09 23:49 UTC, ben-lear commented on src/ui/mystery-encounter-ui-handler.ts
majority of the methods in this class are inherited, added `override` fwiw

2024-09-09 23:54 UTC, ben-lear commented on src/ui/modifier-select-ui-handler.ts
> +    if (args.length !== 4 || !(args[1] instanceof Array) || !(args[2] instanceof Function)) {
this was removed intentionally, to allow for empty shops.

2024-09-09 23:54 UTC, ben-lear commented on src/ui/modifier-select-ui-handler.ts
> +    if (args.length !== 4 || !(args[1] instanceof Array) || !(args[2] instanceof Function)) {
Additional logic and safeguards were added elsewhere in this UI handler and `SelectModifierPhase` to handle edge cases this used to cover

2024-09-10 00:00 UTC, ben-lear commented on src/data/mystery-encounters/requirements/can-learn-move-requirement.ts
> +  override getDialogueToken(_scene: BattleScene, _pokemon?: PlayerPokemon): [string, string] {
added doc to parent method

2024-09-10 00:06 UTC, ben-lear commented on src/ui/message-ui-handler.ts
> +    const actionPattern = /@(c|d|s|f)\{(.*?)\}/;
added some comments, but this is a pattern matching regex that checks for `@c{}`, `@f{}`, `@s{}`, and `@f{}` patterns within message text and parses them to their respective behaviors.

2024-09-10 01:37 UTC, ben-lear commented on src/test/vitest.setup.ts
> +});
this was written before the override manager existed lol. Ancient tech

2024-09-10 01:40 UTC, ben-lear commented on src/test/utils/phaseInterceptor.ts
> +  awaitingActionInput?;
I have no idea, it was written by GreenLamp; I simply abstracted the data to an interface

2024-09-10 01:41 UTC, ben-lear commented on src/test/utils/phaseInterceptor.ts
> +  awaitingActionInput?;
fixed now

2024-09-10 01:50 UTC, ben-lear commented on src/test/utils/mocks/mocksContainer/mockText.ts
> +    UI.prototype.showDialogue = this.showDialogue;
because that's how showText was being mocked and I didn't have the energy to dig deeper and fix it 💀

2024-09-10 02:13 UTC, ben-lear commented on src/test/utils/gameManager.ts
> +
probably not, MEs will eventually be added to other modes

2024-09-10 02:14 UTC, ben-lear commented on src/system/game-data.ts
> +  mysteryEncounterType: MysteryEncounterType | -1; // Only defined when current wave is ME,
typically I would agree, but this is an API-facing structure, which I was not sure if it handles null/undefined values properly when storing to db.

2024-09-10 02:16 UTC, ben-lear commented on src/system/game-data.ts
> +  mysteryEncounterType: MysteryEncounterType | -1; // Only defined when current wave is ME,
This was more out of an abundance of caution than anything else. The thing that scared me was other number values in other DB-stored data used this pattern https://github.com/pagefaultgames/pokerogue/blob/16fc3a87b7c550041cccf91855b7ee8d2cae98f8/src/field/pokemon.ts#L88-L93

2024-09-10 02:18 UTC, ben-lear commented on src/phases/victory-phase.ts
needed the code to be accessible in other helper functions to eliminate redundant functions. It also didn't make much sense for all party EXP logic to be owned by VictoryPhase

2024-09-10 02:23 UTC, ben-lear commented on src/phases/summon-phase.ts
> +    // If the Pokemon about to be sent out is fainted, illegal under a challenge, or no longer in the party for some reason, switch to the first non-fainted legal Pokemon
bruh it's an oxford comma

2024-09-10 02:23 UTC, ben-lear commented on src/phases/summon-phase.ts
> +    // If the Pokemon about to be sent out is fainted, illegal under a challenge, or no longer in the party for some reason, switch to the first non-fainted legal Pokemon
https://www.scribbr.com/commas/oxford-comma/

2024-09-10 02:26 UTC, ben-lear commented on src/phases/select-modifier-phase.ts
> +          if (rerollCost === 0 || this.scene.money < rerollCost) {
Because in a "no item" shop, reroll cost is set to 0 (the text still needs to display a value despite button being disabled) and rerolling is disabled.
![image](https://github.com/user-attachments/assets/f3a4a17e-38d7-47be-ad4b-96351c78b6db)

2024-09-10 02:32 UTC, ben-lear commented on src/phases/mystery-encounter-phases.ts
> +    // TODO: remove?
removed

2024-09-10 02:34 UTC, ben-lear commented on src/modifier/modifier.ts
> +  constructor(type: ModifierTypes.PokemonBaseStatTotalModifierType, pokemonId: integer, statModifier: integer, stackCount?: integer) {
constructor

2024-09-10 02:47 UTC, ben-lear commented on src/modifier/modifier-type.ts
> +export class AddPokeballModifierType extends ModifierType {
didn't need this export, not sure why it was there

2024-09-10 03:05 UTC, ben-lear commented on src/locales/en/mystery-encounter.ts
I might need some help with this, if we merge to `config.ts` that would change the naming convention of ME dialogue keys from `mysteryEncounter:encounterName` to just `encounterName`. Perhaps that's desirable, but I personally prefer the layer of definition.

2024-09-10 03:13 UTC, ben-lear commented on src/locales/en/config.ts
> +  mysteryEncounter: mysteryEncounter,
removed as part of a different refactor anyway

2024-09-10 03:15 UTC, ben-lear commented on src/game-mode.ts
> +    return new GameMode(GameModes.CLASSIC, { isClassic: true, hasTrainers: true, hasMysteryEncounters: true, maxMysteryEncounterWave: 180, minMysteryEncounterWave: 10 }, classicFixedBattles);
they will be game mode dependent, so it is appropriate to define them here imo

2024-09-10 03:23 UTC, ben-lear commented on src/field/mystery-encounter-intro.ts
> +export default interface MysteryEncounterIntroVisuals {
yep, added a comment

2024-09-10 03:23 UTC, ben-lear commented on src/enums/mystery-encounter-tier.ts
> +  MASTER = 0 // Not currently used
still not used, no

2024-09-10 04:33 UTC, flx-sta commented on src/phases/summon-phase.ts
> +    // If the Pokemon about to be sent out is fainted, illegal under a challenge, or no longer in the party for some reason, switch to the first non-fainted legal Pokemon
👀

2024-09-10 09:13 UTC, AsdarDevelops commented on src/phases/select-modifier-phase.ts
> +          if (rerollCost === 0 || this.scene.money < rerollCost) {
NIT: Can this cause rerolls to be banned when using the "rerolls cost 0" override, even on MEs where they should be able to reroll naturally?

... and if so, do we care? (since that's for troubleshooting rather than actual players)

2024-09-11 19:22 UTC, CodeTappert commented on src/data/dialogue.ts
> +        "dialogue:stat_trainer_buck.defeat.1"
You need to have same amount of encounter, victory and defeat text for all of them

2024-09-11 19:39 UTC, CodeTappert commented
![image](https://github.com/user-attachments/assets/c9e7a463-1580-4cfd-997f-9d256169cf77)

Why does it try to search the already translated title again?

2024-09-11 19:45 UTC, CodeTappert commented
![image](https://github.com/user-attachments/assets/f5f3fdb7-ac38-4dd1-9467-ed60405d11fc)
Cant you use a bug catcher for him an not the gym leader from johto?

2024-09-11 19:50 UTC, CodeTappert commented
I get random error that make the game stuck (fixes itself upon reload)
For example here when ecountering mystery challengers:
![image](https://github.com/user-attachments/assets/a2a937f1-2c25-4364-a039-2e6824df9362)

2024-09-11 19:58 UTC, AsdarDevelops commented
> ![image](https://private-user-images.githubusercontent.com/38758606/366606072-f5f3fdb7-ac38-4dd1-9467-ed60405d11fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwODQ5MDAsIm5iZiI6MTcyNjA4NDYwMCwicGF0aCI6Ii8zODc1ODYwNi8zNjY2MDYwNzItZjVmM2ZkYjctYWMzOC00ZGQxLTk0NjctZWQ2MDQwNWQxMWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE5NTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMjc3NzM2ODQ4Yjk2NGJjMDE5NDFiMWM5Y2M0NGZlYTE4NDNhMGJhNTQzZDNiOGY4NmNjMDA5YTRiOWM1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IcWjB1h9WxR5akx_2tSfU93HutuwfHu-m9bLk9XNSdI) Cant you use a bug catcher for him an not the gym leader from johto?

It's a placeholder, actual sprite is original and will be added ASAP

2024-09-11 21:48 UTC, ben-lear commented on src/data/dialogue.ts
> +        "dialogue:stat_trainer_buck.defeat.1"
I swear I added these, I must have lost the commit somewhere

2024-09-11 21:51 UTC, ben-lear commented
> Cant you use a bug catcher for him an not the gym leader from johto?

The art is a placeholder, WIP by @FishF in the discord. Will be updated before go-live

2024-09-11 21:54 UTC, frutescens commented on src/battle.ts
> +  WILD,
I see - can you make a list of non-ME related changes you've made to the code and put it in the description?

2024-09-11 22:03 UTC, frutescens submitted a review, later dismissed

2024-09-11 22:03 UTC, frutescens commented on src/phases/select-modifier-phase.ts
> +import { isNullOrUndefined } from "#app/utils";
Isn't this function already imported in line 9? It's only used once here, so I feel like using Utils.isNullOrUndefined() is fine.

2024-09-11 22:03 UTC, frutescens commented on src/phases/party-exp-phase.ts
> +export class PartyExpPhase extends Phase {
Could you document this phase? What makes this phase different from victory-phase? They both call scene.applyPartyExp()

2024-09-11 22:15 UTC, ben-lear commented on src/phases/party-exp-phase.ts
> +export class PartyExpPhase extends Phase {
done

2024-09-11 22:16 UTC, ben-lear commented on src/phases/select-modifier-phase.ts
> +import { isNullOrUndefined } from "#app/utils";
we should move to a larger pattern of avoiding `Utils.*` calls and imports, as it's non-standard from the rest of the application. Functions should be imported individually, but that will all have to be part of a larger refactor.

2024-09-11 22:16 UTC, ben-lear commented on src/phases/summon-phase.ts
> +  summonWild(): void {
fixed

2024-09-11 22:29 UTC, ben-lear commented on src/battle-scene.ts
> +  applyPartyExp(expValue: number, pokemonDefeated: boolean, useWaveIndexMultiplier?: boolean, pokemonParticipantIds?: Set<number>): void {
Nothing was actually modified from a logic standpoint for applying party EXP here, was simply moved to eliminate redundant code between 2 phases.

2024-09-11 23:00 UTC, flx-sta commented on src/battle-scene.ts
>            applyPostBattleInitAbAttrs(PostBattleInitAbAttr, pokemon);
NIT:
Since you are checking if they are on field, couldn't you combine these loops technically?

2024-09-11 23:12 UTC, innerthunder commented on src/battle-scene.ts
> +    });
Do you have stats on how much this impacts average ME rarity? I feel like this would make it difficult to add effects that increase ME encounter rates without spiking the rates of rare MEs.

2024-09-12 00:27 UTC, ben-lear commented on src/battle-scene.ts
>            applyPostBattleInitAbAttrs(PostBattleInitAbAttr, pokemon);
This is how the existing EXP logic worked prior in VictoryPhase, exactly line for line (except for Macho Brace stuff). I’d rather save cleanup/optimization for a different PR

2024-09-12 00:30 UTC, ben-lear commented on src/battle-scene.ts
> +    });
I built an entire function to simulate spawn statistics actually, and used it heavily to calculate what weights worked for the targets we wanted. It’s still in the code, “calculateAggregateMEStats()”

2024-09-12 00:32 UTC, ben-lear commented on src/battle-scene.ts
> +    });
This is intended to be an anti-variance tool to reduce the standard deviation on average Ultra/Rogue spawns per run. I do realize this might have to be reworked down the line for other game modes though.

2024-09-12 01:04 UTC, damocleas approved these changes

2024-09-12 03:22 UTC, ben-lear commented on src/battle-scene.ts
>            applyPostBattleInitAbAttrs(PostBattleInitAbAttr, pokemon);
I wanted to avoid invasively refactoring too much code. While on the surface the two loops look similar in function, the fact that they're iterating over different arrays (field pokemon vs party pokemon) spooks me a little from wanting to make those changes in this PR.

2024-09-13 03:15 UTC, ben-lear commented on src/locales/en/modifier-type.json
> +    "MYSTERY_ENCOUNTER_SHUCKLE_JUICE": { "name": "Shuckle Juice" },
The item is not obtainable in shops/rewards screens

2024-09-13 03:15 UTC, ben-lear commented on src/locales/en/modifier-type.json
> +    "MYSTERY_ENCOUNTER_SHUCKLE_JUICE": { "name": "Shuckle Juice" },
Real description is under `PokemonBaseStatTotalModifierType`

2024-09-13 05:07 UTC, DayKev commented on src/battle-scene.ts
> +  public lastMysteryEncounter?: MysteryEncounter;
Only if the last wave was a ME?

2024-09-13 05:51 UTC, DayKev commented on src/battle-scene.ts
> +  public lastMysteryEncounter?: MysteryEncounter;
```suggestion
  /** Defined if the previous wave was a Mystery Encounter */
  public lastMysteryEncounter?: MysteryEncounter;
```
Probably should have a tsdoc of some sort.

2024-09-13 06:24 UTC, DayKev reviewed
Review pt 1

2024-09-13 06:24 UTC, DayKev commented on src/battle-scene.ts
> +   * @param destroy - Default true. If true, will destroy the Pokemon object after removing
```suggestion
   * Removes a {@linkcode PlayerPokemon} from the party, and clears modifiers for that Pokemon's id.
   * Useful for MEs/Challenges that remove Pokemon from the player party temporarily or permanently
   * @param pokemon
   * @param destroy Default `true`. If true, will destroy the Pokemon object after removing
```

2024-09-13 06:24 UTC, DayKev commented on src/battle-scene.ts
> +   * @param encounterType - used to load session encounter when restarting game, etc.
```suggestion
   * @param encounterType Used to load session encounter when restarting game, etc.
```

2024-09-13 06:24 UTC, DayKev commented on src/battle-scene.ts
> +          if (!encounterCandidate.meetsRequirements!(this)) { // Meets encounter requirements
Why the `!` after `meetsRequirements`?

2024-09-13 06:24 UTC, DayKev commented on src/battle-scene.ts
> +            (encounterCandidate.maxAllowedEncounters && encounterCandidate.maxAllowedEncounters > 0)
```suggestion
          if (this.mysteryEncounterSaveData.encounteredEvents.length > 0 // Encounter has not exceeded max allowed encounters
            && (encounterCandidate.maxAllowedEncounters && encounterCandidate.maxAllowedEncounters > 0)
```

2024-09-13 06:24 UTC, DayKev commented on src/battle-scene.ts
> +    encounter.populateDialogueTokensFromRequirements!(this);
Another `!` (in case it's a mistake).

2024-09-13 06:24 UTC, DayKev commented on src/data/battle-anims.ts
> + * @param encounterAnim - one or more animations to fetch
```suggestion
 * @param encounterAnim The animation or animations to fetch
```

2024-09-13 06:24 UTC, DayKev commented on src/data/battle-anims.ts
> + * MUST be called after [initEncounterAnims()](./battle-anims.ts) to load all required animations properly
```suggestion
 * Loads encounter animation assets to scene.
 * MUST be called after {@linkcode initEncounterAnims()} to load all required animations properly
```

2024-09-13 06:24 UTC, DayKev commented on src/data/battle-anims.ts
> +    playWithoutTargets(scene: BattleScene, targetInitialX: number, targetInitialY: number, frameTimeMult: number, frameTimedEventPriority?: 0 | 1 | 3 | 5, callback?: Function) {
Why `0 | 1 | 3 | 5`?

2024-09-13 07:54 UTC, DayKev reviewed
Review pt 2/?

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-option.ts
> + * Post-construct and flag data properties are defined in the {@link MysteryEncounterOption} class itself.
```suggestion
 * Used by {@linkcode MysteryEncounterOptionBuilder} class to define required/optional properties on the {@linkcode MysteryEncounterOption} class when building.
 *
 * Should ONLY contain properties that are necessary for {@linkcode MysteryEncounterOption} construction.
 * Post-construct and flag data properties are defined in the {@linkcode MysteryEncounterOption} class itself.
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-option.ts
> +  hasRequirements() {
```suggestion
  hasRequirements(): boolean {
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-option.ts
> +      this.meetsPrimaryRequirementAndPrimaryPokemonSelected(scene);
```suggestion
  meetsRequirements(scene: BattleScene): boolean {
    return !this.requirements.some(requirement => !requirement.meetsRequirement(scene))
      && this.meetsSupportingRequirementAndSupportingPokemonSelected(scene)
      && this.meetsPrimaryRequirementAndPrimaryPokemonSelected(scene);
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-option.ts
> +  pokemonMeetsPrimaryRequirements(scene: BattleScene, pokemon: Pokemon) {
```suggestion
  pokemonMeetsPrimaryRequirements(scene: BattleScene, pokemon: Pokemon): boolean {
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-option.ts
> +  meetsPrimaryRequirementAndPrimaryPokemonSelected(scene: BattleScene) {
```suggestion
  meetsPrimaryRequirementAndPrimaryPokemonSelected(scene: BattleScene): boolean {
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-option.ts
> +  meetsSupportingRequirementAndSupportingPokemonSelected(scene: BattleScene) {
```suggestion
  meetsSupportingRequirementAndSupportingPokemonSelected(scene: BattleScene): boolean {
```
These function names are getting a bit silly lmao

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-option.ts
> +        this.primaryPokemon = truePrimaryPool[Utils.randSeedInt(truePrimaryPool.length, 0)];
Are Mystery Encounters intended to not use the battle's seed?

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-option.ts
> +          // is this working?
So, is it?

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-option.ts
> +   * Se the full dialogue object to the option. Will override anything already set
```suggestion
   * Set the full dialogue object to the option. Will override anything already set
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/requirements/can-learn-move-requirement.ts
> +    const { excludeLevelMoves, excludeTmMoves, excludeEggMoves, includeFainted, minNumberOfPokemon, invertQuery } = options;
Couldn't you just do `this.excludeLevelMoves = options.excludeLevelMoves ?? false;` etc instead of making this set of indirection variables?

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/requirements/can-learn-move-requirement.ts
> +    if (isNullOrUndefined(partyPokemon) || this?.requiredMoves?.length < 0) {
```suggestion
    if (isNullOrUndefined(partyPokemon) || this.requiredMoves?.length < 0) {
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/utils/encounter-dialogue-utils.ts
> + * @param primaryStyle - can define a text style to be applied to the entire string. Must be defined for BBCodeText styles to be applied correctly
```suggestion
 * @param primaryStyle Can define a text style to be applied to the entire string. Must be defined for BBCodeText styles to be applied correctly
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/utils/encounter-dialogue-utils.ts
> + * Will inject all relevant dialogue tokens that exist in the {@link BattleScene.currentBattle.mysteryEncounter.dialogueTokens}, into i18n text.
```suggestion
 * Will inject all relevant dialogue tokens that exist in the {@linkcode BattleScene.currentBattle.mysteryEncounter.dialogueTokens}, into i18n text.
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/utils/encounter-dialogue-utils.ts
> + * Helper function to inject {@link BattleScene.currentBattle.mysteryEncounter.dialogueTokens} into a given content string
```suggestion
 * Helper function to inject {@linkcode BattleScene.currentBattle.mysteryEncounter.dialogueTokens} into a given content string
```

2024-09-13 07:54 UTC, DayKev commented on src/data/mystery-encounters/utils/encounter-dialogue-utils.ts
> +    // @ts-ignore
```suggestion
  if (i18next.exists(keyOrString!, tokens)) {
    const stringArray = [`${keyOrString}`] as any;
    stringArray.raw = [`${keyOrString}`];
```
What exactly is going on here?

2024-09-13 11:54 UTC, ben-lear commented on src/battle-scene.ts
> +          if (!encounterCandidate.meetsRequirements!(this)) { // Meets encounter requirements
vestige of a different time

2024-09-13 11:59 UTC, ben-lear commented on src/data/battle-anims.ts
> +    playWithoutTargets(scene: BattleScene, targetInitialX: number, targetInitialY: number, frameTimeMult: number, frameTimedEventPriority?: 0 | 1 | 3 | 5, callback?: Function) {
these are the indexes of the respective field containers. I didn't want to allow passing any number, as there are only 4 applicable cases for what "layer" a sprite should be rendered on/above.

2024-09-13 11:59 UTC, ben-lear commented on src/data/battle-anims.ts
> +      scene.tweens.addCounter({
yeahhh....

2024-09-13 12:07 UTC, ben-lear commented on src/data/battler-tags.ts
> +  constructor(sourceMove: Moves) {
nope, at least not atm.

2024-09-13 12:08 UTC, ben-lear commented on src/data/battler-tags.ts
> +  constructor(sourceMove: Moves) {
removed the unnecessary var.

2024-09-13 12:26 UTC, ben-lear commented on src/data/mystery-encounters/mystery-encounter-option.ts
> +        this.primaryPokemon = truePrimaryPool[Utils.randSeedInt(truePrimaryPool.length, 0)];
this might be something that is worth a refactor down the line, but currently no ME logic uses battle seed for randomness.

2024-09-13 12:33 UTC, ben-lear commented on src/data/mystery-encounters/utils/encounter-dialogue-utils.ts
> +    // @ts-ignore
good question, cleaned it up

2024-09-13 14:19 UTC, MokaStitcher commented
Not done yet with code review, but here are the issues I found so far when playtesting:

**Field trip**
The dialog when picking a wrong move is not correct
<img width="721" alt="Screenshot 2024-09-13 at 15 09 24" src="https://github.com/user-attachments/assets/c3d48cd7-e54c-41a1-b18b-b0e2c82353b3">

**Weird dream**
Ah nit, but when the event unlocks a bunch of starter/moves, the order in which things are shown is a bit weird : first all eggs moves are shown one after the others, then all starter unlocks
I would expect for the starter unlocks to show before the egg moves. It would be nice if it also said for which starters the moves are
<img width="720" alt="Screenshot 2024-09-13 at 15 30 24" src="https://github.com/user-attachments/assets/09bccaff-12f9-4d9c-92db-e959e41b1442">

**Bug super fan**
Picked the option to show my Bug Pokemon and it didn't find the dialog
<img width="722" alt="Screenshot 2024-09-13 at 15 44 24" src="https://github.com/user-attachments/assets/a284e1ba-3584-42f1-bc33-6e3cf3d01516">

**Safari Zone**
If I catch a Pokemon and don't add it to the team the game crashes
<img width="1174" alt="Screenshot 2024-09-13 at 16 03 48" src="https://github.com/user-attachments/assets/9b63b82c-0b22-4e56-8b2b-b9752b9b1948">
[Session file](https://github.com/user-attachments/files/16995137/sessionData_safari.txt) (capture Emolga by using bait then ball, and don't add it to the team)
(If that changes anything to RNG, my ME rate is set to 200)

2024-09-13 16:49 UTC, ben-lear commented
> Not done yet with code review, but here are the issues I found so far when playtesting:
> 
> **Field trip** The dialog when picking a wrong move is not correct <img alt="Screenshot 2024-09-13 at 15 09 24" width="721" src="https://private-user-images.githubusercontent.com/54149968/367327428-c3d48cd7-e54c-41a1-b18b-b0e2c82353b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzg5OTMsIm5iZiI6MTcyNjIzODY5MywicGF0aCI6Ii81NDE0OTk2OC8zNjczMjc0MjgtYzNkNDhjZDctZTU0Yy00MWExLWIxOGItYjBlMmM4MjM1M2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE0NDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZDYzZTkwNjE1MWMxZDQ4YzAzMWE0NGZmZmQzNTQxNmIwMjkzZjg0Y2Q0YjQyMTA1MzM1NTA0MWM2ZDQ2YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uJ4qKAZnl8eENJhRVWd8SyLM6yBv8qaokpZdWwLtiVg">
> 
> **Weird dream** Ah nit, but when the event unlocks a bunch of starter/moves, the order in which things are shown is a bit weird : first all eggs moves are shown one after the others, then all starter unlocks I would expect for the starter unlocks to show before the egg moves. It would be nice if it also said for which starters the moves are <img alt="Screenshot 2024-09-13 at 15 30 24" width="720" src="https://private-user-images.githubusercontent.com/54149968/367330800-09bccaff-12f9-4d9c-92db-e959e41b1442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzg5OTMsIm5iZiI6MTcyNjIzODY5MywicGF0aCI6Ii81NDE0OTk2OC8zNjczMzA4MDAtMDliY2NhZmYtMTJmOS00ZDljLTkyZGItZTk1OWU0MWIxNDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE0NDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNWE2Mjk0YzZkMjViYmNhMDM2NWU1N2M0MzgxYTU1Y2QwNmRlNmJjNjA3YTc1NTJmNTQzN2UwZDk1OGM4MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ILT1f5tfNltnGFhNevMPMG7r7XXDJt43Ms-TS1hfkPg">
> 
> **Bug super fan** Picked the option to show my Bug Pokemon and it didn't find the dialog <img alt="Screenshot 2024-09-13 at 15 44 24" width="722" src="https://private-user-images.githubusercontent.com/54149968/367328936-a284e1ba-3584-42f1-bc33-6e3cf3d01516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzg5OTMsIm5iZiI6MTcyNjIzODY5MywicGF0aCI6Ii81NDE0OTk2OC8zNjczMjg5MzYtYTI4NGUxYmEtMzU4NC00MmYxLWJjMzMtNmUzY2YzZDAxNTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE0NDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MzgxZDNiZjZjMmI4NDE5ZWJmMjQ4YzJjNzBjMjk5ZGE5NTQwMmE0M2ViZjdiOTdmZjQxNjM4MzRhMDMxMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vr5Wn_al0EzWlg65iGyuCwiu6KsKQ57B6qcBk__jVsE">
> 
> **Safari Zone** If I catch a Pokemon and don't add it to the team the game crashes <img alt="Screenshot 2024-09-13 at 16 03 48" width="1174" src="https://private-user-images.githubusercontent.com/54149968/367329567-9b63b82c-0b22-4e56-8b2b-b9752b9b1948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzg5OTMsIm5iZiI6MTcyNjIzODY5MywicGF0aCI6Ii81NDE0OTk2OC8zNjczMjk1NjctOWI2M2I4MmMtMGIyMi00ZTU2LThiMmItYjk3NTJiOWIxOTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE0NDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNTE1OWQyNjJjNzZiY2FhMmY4ZTY1Y2IxNzJlNTQ0NTNhMzgyNzhkZDc3NzYxMWY0MDU1ODE5NDIzOTFmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lrz3I1zohjVVlDwnS1gQaMxxZMdE4FoM7SlQT8MY6Pc"> [Session file](https://github.com/user-attachments/files/16995137/sessionData_safari.txt) (capture Emolga by using bait then ball, and don't add it to the team) (If that changes anything to RNG, my ME rate is set to 200)

These should all be fixed now

2024-09-13 18:57 UTC, flx-sta reviewed
99% NITs (again)

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/requirements/requirement-groups.ts
> +export const CHARMING_MOVES = [
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/requirements/requirement-groups.ts
> +export const STEALING_MOVES = [
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/requirements/requirement-groups.ts
> +export const DISTRACTION_MOVES = [
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/requirements/requirement-groups.ts
> +export const PROTECTING_MOVES = [
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/requirements/requirement-groups.ts
> +export const EXTORTION_MOVES = [
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/requirements/requirement-groups.ts
> +export const EXTORTION_ABILITIES = [
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +   */
you could use 
```suggestion
  // #region Flags
```

Make sure to close it with
```ts
  // #endregion
```

this will show up like this in vs-codium minimap:
<img width="154" alt="image" src="https://github.com/user-attachments/assets/1cc24b61-200f-4d17-8d84-08bff26c1baa">

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +   */
you could use 
```suggestion
  // #region Post-construct / Auto-populated params
```

Make sure to close it with
```ts
  // #endregion
```

This would show up like this on vs-codium minimap:
<img width="174" alt="image" src="https://github.com/user-attachments/assets/6e510219-209f-47ae-aa44-b3daf46b1c83">

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +   */
you could use 
```suggestion
  // #region Event callback functions
```

Make sure to close it with
```ts
  // #endregion
```

This would show up like this on vs-codium minimap:
<img width="166" alt="image" src="https://github.com/user-attachments/assets/a4e31814-77c8-4a47-a112-2fcdc11afe46">

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +  requirements: EncounterSceneRequirement[];
you could use 
```suggestion
  // #region Requirements
  
```

Make sure to close it with
```ts
  // #endregion
```

This would show up like this on vs-codium minimap:
<img width="177" alt="image" src="https://github.com/user-attachments/assets/2d2d9736-b043-49d7-a1b0-a0002e36509a">

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +   */
you could use 
```suggestion
  // #region Optional params
  
```

Make sure to close it with
```ts
  // #endregion
```

This would show up like this on vs-codium minimap:
<img width="182" alt="image" src="https://github.com/user-attachments/assets/5d074134-f58b-418d-9b36-10084aeefb9e">

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter.ts
> +   */
you could use 
```suggestion
  // #region Optional params
  
```

This would show up like this on vs-codium minimap:
<img width="133" alt="image" src="https://github.com/user-attachments/assets/7b7e86c9-c384-4e34-ae51-162c2097b936">

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
NIT: could use some `override`

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter-pokemon-data.ts
> +export class MysteryEncounterPokemonData {
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/battler-tags.ts
> +  lapse(pokemon: Pokemon, lapseType: BattlerTagLapseType): boolean {
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/battler-tags.ts
> +  onAdd(pokemon: Pokemon): void {
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/battler-tags.ts
> +  onRemove(pokemon: Pokemon): void {
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/egg.ts
> +  eventEggTypeDescriptor?: string;
I don't know if this is too specific here. It might be worth it to take a more generalized approach and allow for an override of `eggTypeDescriptor` in general

2024-09-13 18:57 UTC, flx-sta commented on src/battle.ts
NIT:
Could be replaced with

```suggestion
type TurnCommands = Record<number, TurnCommand | null>;
```

2024-09-13 18:57 UTC, flx-sta commented on src/battle.ts
> +  public mysteryEncounter?: MysteryEncounter;
NIT:
So does this reference the currently active encounter?
Please add ts-doc then

2024-09-13 18:57 UTC, flx-sta commented on src/battle-scene.ts
> +  public lastMysteryEncounter?: MysteryEncounter;
👀

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/mystery-encounter-dialogue.ts
> +  options?: [...OptionTextDisplay[]]; // Options array with minimum 2 options
NIT:
```suggestion
  /* Options array with minimum 2 options */
  options?: [...OptionTextDisplay[]];
```

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/weird-dream-encounter.ts
> +  /** UBs */
What does `UBs` mean?

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/weird-dream-encounter.ts
> +    let newBstRange;
NIT:
missing type

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/weird-dream-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT: 
replace with const

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/uncommon-breed-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180) // waves 10 to 180
NIT: 
should be replaced with const

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/trash-to-treasure-encounter.ts
> +    .withSceneWaveRangeRequirement(60, 180)
NIT:
`180` should be replaced with const

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/training-session-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180) // waves 10 to 180
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/the-winstrate-challenge-encounter.ts
> +    .withSceneWaveRangeRequirement(100, 180)
NIT:
`180` should be replaced with const

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/the-strong-stuff-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180) // waves 10 to 180
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/the-pokemon-salesman-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/slumbering-snorlax-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180) // waves 10 to 180
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/shady-vitamin-dealer-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/safari-zone-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/part-timer-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180) // waves 10 to 180
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180) // waves 10 to 180
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/lost-at-sea-encounter.ts
> +  .withSceneWaveRangeRequirement(11, 179)
NIT:
Should be replaced with constants `-1`

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/fun-and-games-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180) // waves 10 to 180
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/fiery-fallout-encounter.ts
> +    .withSceneWaveRangeRequirement(40, 180)
NIT:
`180` Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/field-trip-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/delibirdy-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/dark-deal-encounter.ts
> +    .withSceneWaveRangeRequirement(30, 180) // waves 30 to 180
NIT:
`180` should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/dancing-lessons-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/clowning-around-encounter.ts
> +    .withSceneWaveRangeRequirement(80, 180)
NIT:
`180` Should be replaced with constant

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180) // waves 10 to 180
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/berries-abound-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180) // waves 10 to 180
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/an-offer-you-cant-refuse-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/absolute-avarice-encounter.ts
> +    .withSceneWaveRangeRequirement(10, 180)
NIT:
Should be replaced with constants

2024-09-13 18:57 UTC, flx-sta commented on src/data/mystery-encounters/encounters/a-trainers-test-encounter.ts
> +    .withSceneWaveRangeRequirement(100, 180)
NIT:
`180` should be replaced with constant

2024-09-13 20:31 UTC, ben-lear commented on src/data/egg.ts
> +  eventEggTypeDescriptor?: string;
refactored to be usable for any EggType

2024-09-13 20:31 UTC, ben-lear commented on src/battle.ts
out of scope, refactor of code that does not pertain to MEs

2024-09-13 20:34 UTC, ben-lear commented on src/data/mystery-encounters/encounters/weird-dream-encounter.ts
> +  /** UBs */
Ultra Beasts, see description above

2024-09-13 21:33 UTC, flx-sta approved these changes

2024-09-13 21:37 UTC, frutescens approved these changes

2024-09-13 23:31 UTC, flx-sta submitted a review, later dismissed

2024-09-13 23:31 UTC, flx-sta commented on src/ui/modifier-select-ui-handler.ts
> +    const continueButton = this.continueButtonContainer.getAt(0) as Phaser.GameObjects.Text;
NIT:
`getAt()` support generic types
```suggestion
    const continueButton = this.continueButtonContainer.getAt<Phaser.GameObjects.Text>(0);
```

2024-09-13 23:42 UTC, flx-sta approved these changes

2024-09-13 23:49 UTC, damocleas submitted a review, later dismissed

2024-09-13 23:55 UTC, frutescens submitted a review, later dismissed

2024-09-13 23:57 UTC, xsn34kzx approved these changes

2024-09-14 00:20 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> + * NOTE: If the Pokemon already knows the move, this requirement will fail, since it's not technically learnable.
So even if a Pokémon is level 200, as long as it doesn't have the move but could at one point have learned that move, it would pass the requirement?

2024-09-14 00:21 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> +export class EvolutionTargetSpeciesRequirement extends EncounterPokemonRequirement {
Why left in but commented out?

2024-09-14 00:24 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> +export class AttackTypeBoosterHeldItemTypeRequirement extends EncounterPokemonRequirement {
So like Charcoal/etc? Why wouldn't that be covered under a more generic held item check? Is this due to the 🍝 that is the modifiers system?

2024-09-14 00:24 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> +    // Party Pokemon inside required level range
s/level/health

Something to fix later.

2024-09-14 00:25 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> +    // Party Pokemon inside required friendship range
s/friendship/weight

2024-09-14 00:34 UTC, ben-lear commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> +export class AttackTypeBoosterHeldItemTypeRequirement extends EncounterPokemonRequirement {
This is due to the 🍝 yes. There’s no way to specify pregen arcs/specific type of attack booster in a generic requirement while also being usable for other modifiers with pregen args. I wrangled with the problem for a bit and gave up in frustration after a while

2024-09-14 00:35 UTC, DayKev commented on src/data/trainer-config.ts
> +   * @returns {TrainerConfig} - The updated TrainerConfig instance.
```suggestion
   * @param {Species | Species[]} signatureSpecies The signature species for the Elite Four member.
   * @param {Type[]} specialtyTypes The specialty types for the Stat Trainer.
   * @param isMale Whether the Elite Four Member is Male or Female (for localization of the title).
   * @returns {TrainerConfig} The updated TrainerConfig instance.
```
Note that putting the type before the param like that in the tsdoc is pointless because it won't be rendered by vscode's tsdoc extension (or at least, not the one I use which I think is the one most people use?).
![image](https://github.com/user-attachments/assets/314cf8ae-33cd-4514-8dea-41ca779bb24c)

If there's a better tsdoc extension than this one lmk.
![image](https://github.com/user-attachments/assets/0ff78046-ffe5-4ac8-97fa-5025b2104dcf)

2024-09-14 00:46 UTC, f-fsantos approved these changes

2024-09-14 00:47 UTC, ben-lear commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> + * NOTE: If the Pokemon already knows the move, this requirement will fail, since it's not technically learnable.
correct

2024-09-14 00:47 UTC, ben-lear commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> +export class EvolutionTargetSpeciesRequirement extends EncounterPokemonRequirement {
removed

2024-09-14 00:48 UTC, ben-lear commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> +    // Party Pokemon inside required level range
fixed

2024-09-14 00:48 UTC, ben-lear commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> +    // Party Pokemon inside required friendship range
fixed

2024-09-14 00:49 UTC, DayKev commented on src/modifier/modifier-type.ts
> +   * @param poolType - Default 'ModifierPoolType.PLAYER'. Which pool to lookup item tier from
```suggestion
   * Populates item tier for ModifierType instance.
   * Tier is a necessary field for items that appear in player shop (determines the Pokeball visual they use).
   * To find the tier, this function performs a reverse lookup of the item type in modifier pools
   * @param poolType Default 'ModifierPoolType.PLAYER'. Which pool to lookup item tier from
```

2024-09-14 00:53 UTC, DayKev commented on src/modifier/modifier-type.ts
> + * @param modifierTiers - (Optional) If specified, rolls items in the specified tiers. Commonly used for tier-locking with Lock Capsule.
```suggestion
 * Generates modifier options for a {@linkcode SelectModifierPhase}
 * @param count Determines the number of items to generate
 * @param party Party is required for generating proper modifier pools
 * @param modifierTiers (Optional) If specified, rolls items in the specified tiers. Commonly used for tier-locking with Lock Capsule.
```

2024-09-14 00:54 UTC, DayKev commented on src/modifier/modifier-type.ts
> + *  - `allowLuckUpgrades?: boolean` - Default true, if false will prevent set item tiers from upgrading via luck
```suggestion
 *  - `allowLuckUpgrades?: boolean` - Default `true`, if `false` will prevent set item tiers from upgrading via luck
```

2024-09-14 00:55 UTC, DayKev commented on src/modifier/modifier-type.ts
> + *  - `rerollMultiplier?: number` - If specified, can adjust the amount of money required for a shop reroll. If set to 0, the shop will not allow rerolls at all.
`0` or `-1`? The comment above says `-1` but this says `0`.

2024-09-14 00:58 UTC, DayKev commented on src/modifier/modifier-type.ts
> + * @param allowLuckUpgrades - allow items to upgrade tiers (the little animation that plays and is affected by luck)
```suggestion
 * Will generate a {@linkcode ModifierType} from the {@linkcode ModifierPoolType.PLAYER} pool, attempting to retry duplicated items up to `retryCount`
 * @param existingOptions Currently generated options
 * @param retryCount How many times to retry before allowing a dupe item
 * @param party Current player party, used to calculate items in the pool
 * @param tier If specified will generate item of tier
 * @param allowLuckUpgrades `true` to allow items to upgrade tiers (the little animation that plays and is affected by luck)
```

2024-09-14 01:00 UTC, DayKev commented on src/modifier/modifier-type.ts
> + * @param allowLuckUpgrades - Default true. If false, will not allow ModifierType to randomly upgrade to next tier
```suggestion
 * Generates a {@linkcode ModifierType} from the specified pool
 * @param party {arty of the trainer using the item
 * @param poolType `PLAYER | WILD | TRAINER`
 * @param tier If specified, will override the initial tier of an item (can still upgrade with luck)
 * @param upgradeCount If defined, means that this is a new `ModifierType` being generated to override another via luck upgrade. Used for recursive logic
 * @param retryCount Max allowed tries before the next tier down is checked for a valid ModifierType
 * @param allowLuckUpgrades Default `true`. If `false`, will not allow `ModifierType` to randomly upgrade to next tier
```

2024-09-14 01:02 UTC, DayKev commented on src/phases/encounter-phase.ts
> +          if (!!this.scene.findModifier(m => m instanceof BoostBugSpawnModifier) && randSeedInt(10) === 0) {
```suggestion
          if (this.scene.findModifier(m => m instanceof BoostBugSpawnModifier) && randSeedInt(10) === 0) {
```

2024-09-14 01:17 UTC, DayKev commented on src/phases/select-modifier-phase.ts
>    private modifierTiers: ModifierTier[];
```suggestion
  private modifierTiers?: ModifierTier[];
```

2024-09-14 01:17 UTC, DayKev commented on src/phases/select-modifier-phase.ts
>      this.modifierTiers = modifierTiers!; // TODO: is this bang correct?
```suggestion
    this.modifierTiers = modifierTiers;
```
Smh flx not even trying to fix the simple `!` when he made the `strict-null` PR.

2024-09-14 01:20 UTC, DayKev commented on src/system/game-data.ts
> +   * @returns - true if Pokemon catch unlocked a new starter, false if Pokemon catch did not unlock a starter
```suggestion
   * @param pokemon
   * @param incrementCount
   * @param fromEgg
   * @param showMessage
   * @returns `true` if Pokemon catch unlocked a new starter, `false` if Pokemon catch did not unlock a starter
```

2024-09-14 01:21 UTC, DayKev commented on src/system/game-data.ts
> +   * @returns - true if Pokemon catch unlocked a new starter, false if Pokemon catch did not unlock a starter
```suggestion
   * @param pokemon
   * @param incrementCount
   * @param fromEgg
   * @param showMessage
   * @returns `true` if Pokemon catch unlocked a new starter, `false` if Pokemon catch did not unlock a starter
```

2024-09-14 01:22 UTC, DayKev commented on src/system/game-data.ts
> +   * @param prependSpeciesToMessage - Default false. If true, will change message from "X Egg Move Unlocked!" to "Bulbasaur X Egg Move Unlocked!"
```suggestion
   * @param species
   * @param eggMoveIndex
   * @param showMessage Default `true`. If `true`, will display message for unlocked egg move
   * @param prependSpeciesToMessage Default `false`. If `true`, will change message from "X Egg Move Unlocked!" to "Bulbasaur X Egg Move Unlocked!"
```

2024-09-14 01:24 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> + * - Queuing of the MysteryEncounterOptionSelectedPhase
```suggestion
 * - Execute `onPreOptionPhase()` logic if it exists for the selected option
 * - Display any `OptionTextDisplay.selected` type dialogue that is set in the `MysteryEncounterDialogue` dialogue tree for selected option
 * - Queuing of the {@linkcode MysteryEncounterOptionSelectedPhase}
```

2024-09-14 01:25 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Mostly useful for having repeated queries during a single encounter, where the queries and options may differ each time
```suggestion
   * Mostly useful for having repeated queries during a single encounter, where the queries and options may differ each time
   * @param scene
   * @param optionSelectSettings Allows overriding the typical options of an encounter with new ones
```

2024-09-14 01:26 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Queues MysteryEncounterOptionSelectedPhase, displays option.selected dialogue and ends phase
```suggestion
   * Queues {@linkcode MysteryEncounterOptionSelectedPhase}, displays `option.selected` dialogue and ends phase
```

2024-09-14 01:27 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Any phase that is meant to follow this one MUST be queued via the onOptionSelect() logic of the selected option
```suggestion
   * - Execute {@linkcode onOptionSelect()} logic if it exists for the selected option
   *
   * It is important to point out that no phases are directly queued by any logic within this phase.
   * Any phase that is meant to follow this one MUST be queued via the `onOptionSelect()` logic of the selected option
```

2024-09-14 01:30 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> + * See [TurnEndPhase](../phases.ts) for more details
```suggestion
 * Will clean up any residual flinches, Endure, etc. that are left over from `startOfBattleEffects`
 * Will also handle Game Overs, switches, etc. that could happen from `handleMysteryEncounterBattleStartEffects`
* @see [TurnEndPhase](./turn-end-phase.ts) for more details
```

2024-09-14 01:31 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Cleans up TURN_END tags, any PostTurnEffectPhases, checks for Pokemon switches, then continues
```suggestion
   * Cleans up `TURN_END` tags, any `PostTurnEffectPhase`s, checks for Pokemon switches, then continues
```

2024-09-14 01:33 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> + * - Queue the SummonPhases, PostSummonPhases, etc., required to initialize the phase queue for a battle
```suggestion
 * - Queue the [SummonPhases](./summon-phase.ts), [PostSummonPhases](./post-summon-phase.ts), etc., required to initialize the phase queue for a battle
```

2024-09-14 01:34 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Queues SummonPhases for the new battle, and handles trainer animations/dialogue if Trainer battle
```suggestion
   * Queues [`SummonPhases`](./summon-phase.ts) for the new battle, and handles trainer animations/dialogue if it's a Trainer battle
```

2024-09-14 01:35 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Initiate SummonPhases, scanner phases, PostSummon phases, etc.
```suggestion
   * Initiate [`SummonPhases`](./summon-phase.ts), scanner phases, [`PostSummon`](./post-summon-phase.ts) phases, etc.
```

2024-09-14 01:37 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> + * - Queuing of the PostMysteryEncounterPhase
```suggestion
 * - `doContinueEncounter()` callback for continuous encounters with back-to-back battles (this should push/shift its own phases as needed)
 *
 * OR
 *
 * - Any encounter reward logic that is set within `MysteryEncounter` `doEncounterExp`
 * - Any encounter reward logic that is set within `MysteryEncounter` `doEncounterRewards`
 * - Otherwise, can add a no-reward-item shop with only Potions, etc. if `addHealPhase` is true
 * - Queuing of the {@linkcode PostMysteryEncounterPhase}
```

2024-09-14 01:39 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Runs {@link MysteryEncounter.doContinueEncounter} and ends phase, OR {@link MysteryEncounter.onRewards} then continues encounter
```suggestion
   * Runs `MysteryEncounter.doContinueEncounter` and ends phase, OR `MysteryEncounter.onRewards` then continues encounter
```
Unfortunately that doesn't work for things that aren't imported; and while it's "possible" to do comment-only imports, they seem to be buggy (or at least the extension's handling of them is buggy).

2024-09-14 01:39 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Queues encounter EXP and rewards phases, PostMysteryEncounterPhase, and ends phase
```suggestion
   * Queues encounter EXP and rewards phases, {@linkcode PostMysteryEncounterPhase}, and ends phase
```

2024-09-14 01:40 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> + * - onPostOptionSelect logic (based on an option that was selected)
```suggestion
 * - {@linkcode onPostOptionSelect} logic (based on an option that was selected)
```

2024-09-14 01:42 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Runs {@link MysteryEncounter.onPostOptionSelect} then continues encounter
```suggestion
   * Runs `MysteryEncounter.onPostOptionSelect` then continues encounter
```

2024-09-14 01:43 UTC, DayKev commented on src/phases/mystery-encounter-phases.ts
> +   * Queues NewBattlePhase, plays outro dialogue and ends phase
```suggestion
   * Queues {@linkcode NewBattlePhase}, plays outro dialogue and ends phase
```

2024-09-14 01:46 UTC, DayKev commented on src/test/mystery-encounter/encounter-test-utils.ts
> + * @param isBattle - if selecting option should lead to battle, set to true
```suggestion
 * Runs a `MysteryEncounter` to either the start of a battle, or to the {@linkcode MysteryEncounterRewardsPhase}, depending on the option selected
 * @param game
 * @param optionNo human number, not index
 * @param secondaryOptionSelect 
 * @param isBattle if selecting option should lead to battle, set to `true`
```

2024-09-14 01:46 UTC, DayKev commented on src/test/mystery-encounter/encounter-test-utils.ts
> + * @param isBattle - if selecting option should lead to battle, set to true
By "human number" you mean "start at 1" instead of "start at 0"?

2024-09-14 01:48 UTC, DayKev commented on src/test/mystery-encounter/encounter-test-utils.ts
> + * For any MysteryEncounter that has a battle, can call this to skip battle and proceed to MysteryEncounterRewardsPhase
```suggestion
 * For any `MysteryEncounter` that has a battle, can call this to skip battle and proceed to {@linkcode MysteryEncounterRewardsPhase}
```

2024-09-14 01:56 UTC, DayKev approved these changes

2024-09-14 01:56 UTC, flx-sta approved these changes

2024-09-14 02:00 UTC, f-fsantos approved these changes

2024-09-14 02:05 UTC, merged