[UI][Misc] Force users to have an active challenge
pagefaultgames/pokerogue pull request #3953
Opened 2024-09-01 05:42 UTC by frutescens

## What are the changes the user will see?
The user will not able to continue from the Challenges Select UI if no challenges are currently active. The 'Start' button text will only appear if the user has activated a challenge. If the user hasn't, the button text will be set to "None Selected"

## Why am I making these changes?
pokemon go to school

## What are the changes from a developer perspective?
- new class variable 'hasActiveChallenge' that is a boolean determined by if the user has activated a challenge and determines if the user is eligible to continue into the starter select screen
- new UI behavior that responsively reacts to the user's actions and indicate to them whether a challenge has been selected or not

### Screenshots/Videos

https://github.com/user-attachments/assets/984a61b7-539f-4925-9d62-f51952ace36d

## How to test the changes?
Try to access the starter select UI without activating a challenge

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-09-01 06:22 UTC, DayKev commented on src/ui/challenges-select-ui-handler.ts
> +
```suggestion
```

2024-09-01 06:24 UTC, DayKev approved these changes

2024-09-01 06:25 UTC, DayKev commented
Randomly changed around challenge options, started a new challenge, seems to work.

2024-09-01 08:03 UTC, DayKev approved these changes

2024-09-01 08:44 UTC, KimJeongSun requested changes
LGTM!, except nit

2024-09-01 08:44 UTC, KimJeongSun commented on src/ui/challenges-select-ui-handler.ts
> +        } else  {
mis added space?

2024-09-01 14:26 UTC, CodeTappert commented
![image](https://github.com/user-attachments/assets/a9b3e23d-b737-4a66-b9b9-97726f02a8c9)
? xD

2024-09-01 18:41 UTC, frutescens commented
@CodeTappert It's a reference to the failed K-12 education policies of the Bush administration

2024-09-01 18:42 UTC, CodeTappert commented
> @CodeTappert It's a reference to the failed K-12 education policies of the Bush administration

Ok some obscure american reference. So i dont need to know it xD

2024-09-01 20:48 UTC, DayKev approved these changes

2024-09-02 03:04 UTC, Tempo-anon commented on src/locales/en/challenges.json
> +  "noneSelected": "None Selected",
How does the new localization work? Does this key need to be added to all the other locales too?

2024-09-02 04:12 UTC, frutescens commented on src/locales/en/challenges.json
> +  "noneSelected": "None Selected",
No. It'll automatically fall back to English if the game can't find a key.

2024-09-02 04:15 UTC, Tempo-anon commented on src/locales/en/challenges.json
> +  "noneSelected": "None Selected",
Wasn't the convention to add the missing keys to all localizations to make it easier for translators? Unless that changed with the new localization changes

2024-09-02 04:32 UTC, Tempo-anon commented on src/locales/en/challenges.json
> +  "noneSelected": "None Selected",
I was told not anymore

2024-09-02 04:32 UTC, merged