Electric Terrain Fix
pagefaultgames/pokerogue pull request #3972
Opened 2024-09-02 06:23 UTC by jessemchung

## What are the changes the user will see?

## Why am I making these changes?

## What are the changes from a developer perspective?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-02 06:25 UTC, Tempo-anon commented on src/field/pokemon.ts
> +    const canSetStatus = this.checkIfCanSetStatus(effect, quiet, overrideStatus, sourcePokemon);
nit: I like the name but now it is the same as the function's. Maybe `canSetStatusResult`?

2024-09-02 06:37 UTC, jessemchung commented on src/field/pokemon.ts
> +    const canSetStatus = this.checkIfCanSetStatus(effect, quiet, overrideStatus, sourcePokemon);
Makes sense.  Changed to canSetStatusResult

2024-09-02 06:41 UTC, DayKev commented on src/field/pokemon.ts
> +  checkIfCanSetStatus(effect: StatusEffect | undefined, quiet: boolean = false, overrideStatus: boolean = false, sourcePokemon: Pokemon | null = null): boolean {
Why did you split this into 2 functions?

2024-09-02 06:56 UTC, jessemchung commented on src/field/pokemon.ts
> +  checkIfCanSetStatus(effect: StatusEffect | undefined, quiet: boolean = false, overrideStatus: boolean = false, sourcePokemon: Pokemon | null = null): boolean {
So long story short, the issue was trying to get the message to only show up when it is supposed to.  This led me to try investigating quiet as an option but quiet has to be set to false in the place I needed the message to show up (move.ts line 1965).  This is because quiet is being used as asPhase I believe.

Furthermore this part of that code proved problematic as well as this part prevented me from running the function more than once so I couldn't just run a check when needed.
```
    const cancelled = new Utils.BooleanHolder(false);
    applyPreSetStatusAbAttrs(StatusEffectImmunityAbAttr, this, effect, cancelled, quiet);

    const userField = this.getAlliedField();
    userField.forEach(pokemon => applyPreSetStatusAbAttrs(UserFieldStatusEffectImmunityAbAttr, pokemon, effect, cancelled, quiet));

```

One option I considered was adding a brand new propety to canSetStatus (something like showMessages) but that seemed unnecessary and more importantly @schmidtc1 mentioned attempting to do something like this a while ago but it not being successful.  It seemed like for future proofing, splitting that function into two pieces would be better as that way, if checking if a pokemon was statusable was needed somewhere, it could be done easily

2024-09-02 07:35 UTC, jessemchung commented on src/field/pokemon.ts
> +  checkIfCanSetStatus(effect: StatusEffect | undefined, quiet: boolean = false, overrideStatus: boolean = false, sourcePokemon: Pokemon | null = null): boolean {
Also, I just retested to make sure.  For some reason, it just doesn't work when it is the message is in canSetStatus. if I try to put

`      this.scene.queueMessage(i18next.t("terrain:defaultBlockMessage", { pokemonNameWithAffix: getPokemonNameWithAffix(this), terrainName: getTerrainName(TerrainType.ELECTRIC) }));`

Inside canSetStatus it just doesn't show the message (I think it has something to do with the fact that that function is called multiple times).  That's when schmidtc1 pointed out earlier attempts at fixing this..

2024-09-05 22:44 UTC, DayKev commented on src/field/pokemon.ts
> +  checkIfCanSetStatus(effect: StatusEffect | undefined, quiet: boolean = false, overrideStatus: boolean = false, sourcePokemon: Pokemon | null = null): boolean {
🍝 strikes again...

This function needs a better name than just being a longer version of the other function's name.

2024-09-05 22:50 UTC, flx-sta requested changes
Something went wrong with creating the branch.
There is more commits showing up than expected.
My assumption would be, that you branched off of `main` instead of `beta`

2024-09-05 22:56 UTC, jessemchung commented
> Something went wrong with creating the branch. There is more commits showing up than expected. My assumption would be, that you branched off of `main` instead of `beta`

@fix-sta

I think that was what I originally did and I have had trouble getting it right since but the changes should be correct with regards to comparison to beta.  Is there something else I should do to fix this?

2024-09-06 00:19 UTC, DayKev commented on src/field/pokemon.ts
> +  checkIfCanSetStatus(effect: StatusEffect | undefined, quiet: boolean = false, overrideStatus: boolean = false, sourcePokemon: Pokemon | null = null): boolean {
Seems good enough for now.

2024-09-06 02:08 UTC, flx-sta commented
I'm putting this into draft so you can resolve the branch issues

2025-05-21 18:41 UTC, closed without merging

2025-05-21 18:41 UTC, SirzBenjie commented
I am going to close this since it is very old and does not seem to have activity. Feel free to reopen if there is desire to revisit this.