[Refactor] Refactor move phase
pagefaultgames/pokerogue pull request #3974
Opened 2024-09-02 07:28 UTC by DayKev

This is an attempt to port #3064, currently very little has been done to make sure it's up-to-date; just posting as draft for now to have it here / for reference.

2024-09-06 09:25 UTC, DayKev commented on src/phases/move-phase.ts
> +      this.pokemon.turnData.hitCount = 0;
Good point, that's another bug down.

2024-09-06 15:08 UTC, flx-sta commented
@DayKev I know this is a mirror but refactors like this unfortunately require some test coverage to make sure everything works as expected.

There is also 2 more nits:
- Check if all the public methods & fields/attributes really have to be public
- If a method is public it should have tsdoc `/**` on it
- If a method overrides it should be tagged with `override` in front

2024-09-07 09:43 UTC, DayKev commented
> @DayKev I know this is a mirror but refactors like this unfortunately require some test coverage to make sure everything works as expected.

That's what the test suite is for, we have plenty of tests that check a bunch of things about various moves; what would I even add that isn't already covered by another test?

> There is also some general things to check:
> 
> * Check if all the public methods & fields/attributes really have to be public
> * If a method is public it should have tsdoc `/**` on it (Same maybe for a public field/attribute)
> * If a method overrides it should be tagged with `override` in front

* I modified some of the fields from `public` to `protected` `set`/`public` `get`.
* I moved a bit of `//` comments out into tsdocs where it seemed to make sense, I think the rest of the comments are good.
* No methods are overridden.

2024-09-20 00:15 UTC, flx-sta requested changes
Make sure to double check for potential `override` usages

2024-09-20 00:15 UTC, flx-sta commented on src/battle-scene.ts
> +import { BlockItemTheftAbAttr, DoubleBattleChanceAbAttr, PostBattleInitAbAttr, applyAbAttrs, applyPostBattleInitAbAttrs } from "./data/ability";
NIT:
Might wanna use the `#app` import pattern

2024-09-20 00:15 UTC, flx-sta commented on src/field/arena.ts
> +  isMoveWeatherCancelled(user: Pokemon, move: Move): boolean {
NIT:
- please add a scope (public/protected/private)
- please add docs

2024-09-20 00:15 UTC, flx-sta commented on src/field/arena.ts
> +  isMoveTerrainCancelled(user: Pokemon, targets: BattlerIndex[], move: Move): boolean {
NIT:
- please add a scope (public/protected/private)
- please add docs

2024-09-20 00:15 UTC, flx-sta commented on src/field/arena.ts
> +  getTerrainType(): TerrainType {
NIT:
- please add a scope (public/protected/private)
- please add docs

2024-09-20 00:15 UTC, flx-sta commented on src/field/pokemon.ts
> +  public hitsLeft: number = -1;
Q:
Why `-1` here?
I mean `0` also means there is no more hits left, right?

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
>    canMove(ignoreDisableTags?: boolean): boolean {
NIT:
- please add a scope (public/protected/private)

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
> +  getActiveTargetPokemon() {
NIT:
- please add a scope (public/protected/private)
- add docs

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
> +  resolvePreMoveStatusEffects() {
NIT:
- please add a scope (public/protected/private)
- please fix docs formatting

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
> +  useMove() {
NIT:
- please add a scope (public/protected/private)
- add docs

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
> +  resolveRedirectTarget() {
NIT:
- please add a scope (public/protected/private)
- add docs

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
> +  getPpIncreaseFromPressure(targets: Pokemon[]) {
NIT:
- please add a scope (public/protected/private)
- add docs

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
> +  end() {
NIT:
- please add a scope (public/protected/private)
- add docs

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
> +  resolveCounterAttackTarget() {
NIT:
- please add a scope (public/protected/private)

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
> +  handlePreMoveFailures() {
NIT:
- please add a scope (public/protected/private)

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
>    showMoveText(): void {
NIT:
- please add a scope (public/protected/private)
- add docs

2024-09-20 00:15 UTC, flx-sta commented on src/phases/move-phase.ts
> +  showFailedText(failedText?: string): void {
NIT:
- please add a scope (public/protected/private)
- add docs

2024-09-20 20:52 UTC, DayKev commented on src/field/arena.ts
> +  isMoveWeatherCancelled(user: Pokemon, move: Move): boolean {
I don't see the point of docs when they would just restate the name of the function in a couple more words. Everything about the function is self-explanatory.

2024-09-20 21:00 UTC, flx-sta commented on src/field/arena.ts
> +  isMoveWeatherCancelled(user: Pokemon, move: Move): boolean {
It's mostly to describe the params a little better.
I know it's self explanatory but i ain't making the rules

2024-09-20 21:26 UTC, DayKev commented on src/field/pokemon.ts
> +  public hitsLeft: number = -1;
`0` makes the move assume it's finished and so multi-hit moves don't do all their hits, `-1` means it should calculate how many hits are left.

2024-09-20 22:07 UTC, DayKev commented on src/phases/move-phase.ts
> +    // TODO: does this intentionally happen before the no targets/Moves.NONE on queue cancellation case is checked?
It doesn't seem like it? I just used Hyper Beam a bunch (gave the other mon Attract) and it never triggered infatuation on the recharge turn. I guess it's possible I failed ~10 coinflips though.

2024-09-20 23:27 UTC, flx-sta requested changes

2024-09-20 23:27 UTC, flx-sta commented on src/field/arena.ts
> +    return (this.terrain && this.terrain.isMoveTerrainCancelled(user, targets, move)) as boolean;
You should be able to avoid `as boolean` by using `!!this.terrain`.
<sub>This is caused by the fact that you are checking this.terrain in a return and not in a if-clause. The compiler doesn't automatically know that you are simply checking if it's defined</sub>

```suggestion
    return !!this.terrain && this.terrain.isMoveTerrainCancelled(user, targets, move);
```

---

Alternatively you could also simply use `?.`

```suggestion
    return this.terrain?.isMoveTerrainCancelled(user, targets, move);
```

2024-09-20 23:27 UTC, flx-sta commented on src/field/arena.ts
> +    return (this.weather && !this.weather.isEffectSuppressed(this.scene) && this.weather.isMoveWeatherCancelled(user, move)) as boolean;
You should be able to avoid `as boolean` by using `!!this.weather`.
<sub>This is caused by the fact that you are checking this.terrain in a return and not in a if-clause. The compiler doesn't automatically know that you are simply checking if it's defined</sub>

```suggestion
    return !!this.weather && !this.weather.isEffectSuppressed(this.scene) && this.weather.isMoveWeatherCancelled(user, move)) as boolean;
```

---

Alternatively you could also simplify this by using `.?`

```suggestion
    return !this.weather?.isEffectSuppressed(this.scene) && this.weather.isMoveWeatherCancelled(user, move);
```
<sup> Only the first one needs it as the it's an AND connection and the 2nd one will be guaranteed for it to be set</sup>

2024-09-20 23:29 UTC, flx-sta requested changes

2024-09-20 23:29 UTC, flx-sta commented on src/field/pokemon.ts
> +  public hitsLeft: number = -1;
@DayKev Would you mind adding that as a comment on top of this?
```suggestion
  /** 0 = Move is finished. -1 = flagged to calculate how many hits are left */
  public hitsLeft: number = -1;
```

2024-09-22 22:29 UTC, innerthunder approved these changes

2024-09-23 02:21 UTC, flx-sta approved these changes

2024-09-25 18:04 UTC, innerthunder submitted a review, later dismissed

2024-09-26 02:04 UTC, frutescens approved these changes

2024-10-03 07:20 UTC, innerthunder approved these changes

2024-10-03 14:29 UTC, flx-sta submitted a review, later dismissed

2024-10-04 06:12 UTC, DayKev commented on src/phases/move-phase.ts
> +      if ([Moves.ROAR, Moves.WHIRLWIND, Moves.TRICK_OR_TREAT, Moves.FORESTS_CURSE].includes(this.move.moveId)) {
```suggestion
      if ([ Moves.ROAR, Moves.WHIRLWIND, Moves.TRICK_OR_TREAT, Moves.FORESTS_CURSE ].includes(this.move.moveId)) {
```

2024-10-04 06:37 UTC, innerthunder approved these changes

2024-10-04 14:50 UTC, merged