[Move] Fully implement Tar Shot
pagefaultgames/pokerogue pull request #4043
Opened 2024-09-05 07:33 UTC by torranx

## What are the changes the user will see?
Tar Shot implemented

## Why am I making these changes?
partially implemented move

## What are the changes from a developer perspective?
new BattlerTag `DoubleMoveTypeEffectiveness`

### Screenshots/Videos

## How to test the changes?
use Tar Shot then Fire-type move
or
`npm run test tar_shot`

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-05 07:40 UTC, DayKev submitted a review, later dismissed

2024-09-05 09:05 UTC, torranx commented on src/test/moves/tar_shot.test.ts
> +    vi.spyOn(enemy, "getMaxHp").mockReturnValue(1000);
checked and it does not hehe

2024-09-05 09:18 UTC, DayKev approved these changes

2024-09-05 14:12 UTC, Tempo-anon submitted a review, later dismissed

2024-09-05 14:15 UTC, torranx commented on src/data/battler-tags.ts
> + * Tag that doubles the type effectiveness of a move.
this is my lack of knowledge on moves - "there might be some move that is similar to how this works" so I named it like so. I can specify the name to `TarShotTag` instead if its the only move that does this.

2024-09-05 14:20 UTC, Tempo-anon commented on src/data/battler-tags.ts
> + * Tag that doubles the type effectiveness of a move.
You can keep it as is for now if you just note in the comments that it's a bespoke battlertag. This is more of a readability thing where bespoke battlertags with names that do not match up to the only instance they're used for is confusing for people unfamiliar with the code or have an encyclopedic knowledge of the game. We don't have a guideline for the exact naming convention of classes like this yet though my initial thought is that classes only used for one thing should reflect or document that

2024-09-05 15:07 UTC, Tempo-anon submitted a review, later dismissed

2024-09-05 19:09 UTC, torranx commented
Added message @frutescens , also fyi @Tempo-anon I changed the tag name to be specific (TarShotTag)

2024-09-05 19:16 UTC, frutescens requested changes

2024-09-05 19:16 UTC, frutescens commented on src/data/battler-tags.ts
> +    pokemon.scene.queueMessage(i18next.t("battlerTags:tarShotOnAdd", { pokemonNameWithAffix: getPokemonNameWithAffix(pokemon) }));
This is more of a nit but I think 'wild' should be lowercase.

https://github.com/user-attachments/assets/183342f0-76a1-4876-b1fb-d911a3238543

2024-09-05 19:18 UTC, frutescens commented on src/data/battler-tags.ts
> +    pokemon.scene.queueMessage(i18next.t("battlerTags:tarShotOnAdd", { pokemonNameWithAffix: getPokemonNameWithAffix(pokemon) }));
Or I don't know... it seems more of an issue with getPokemonNameWithAffix()
There really should be an option to return the affix as lowercase...

2024-09-05 19:19 UTC, torranx commented on src/data/battler-tags.ts
> +    pokemon.scene.queueMessage(i18next.t("battlerTags:tarShotOnAdd", { pokemonNameWithAffix: getPokemonNameWithAffix(pokemon) }));
remove the starting word "The" instead to align with other text

2024-09-05 19:33 UTC, frutescens requested changes
Looks good to me.
Tested with some outlier scenarios.
This happened with Flash Fire but I'm not sure if Flash Fire has a message? 

https://github.com/user-attachments/assets/5f5d95d2-8e65-482b-b21b-1b00541bdf80

Otherwise, Clear Body, Contrary, and Well-Baked Body worked as expected.

2024-09-05 19:35 UTC, frutescens commented
This does seem like an unrelated bug from Tar Shot so I'm going to report it to Issues instead.

2024-09-05 19:35 UTC, frutescens approved these changes

2024-09-05 19:37 UTC, torranx commented
> This happened with Flash Fire but I'm not sure if Flash Fire has a message?

which one? seems ok to me?

2024-09-05 19:40 UTC, frutescens commented
Ah nevermind.

2024-09-05 19:41 UTC, frutescens commented
https://github.com/user-attachments/assets/2a693715-2bf2-4853-8829-36a3848a8537

This was being weird but it's unrelated to Tar Shot

2024-09-05 19:46 UTC, flx-sta commented on src/field/pokemon.ts
> +    if (this.getTag(TarShotTag) && (this.getMoveType(move) === Type.FIRE)) {
```suggestion
    if (this.hasTag(TarShotTag) && (this.getMoveType(move) === Type.FIRE)) {
```
I think in this case you would use `hasTag()`. Same result but clearer on whats' going on

2024-09-05 19:46 UTC, flx-sta commented on src/test/moves/tar_shot.test.ts
> +import { Stat } from "#app/enums/stat.js";
The classic
```suggestion
import { BattlerIndex } from "#app/battle";
import { Type } from "#app/data/type";
import { Moves } from "#app/enums/moves";
import { Species } from "#app/enums/species";
import { Stat } from "#app/enums/stat";
```

2024-09-05 19:46 UTC, flx-sta commented on src/data/battler-tags.ts
> +   * @param pokemon the pokemon to which the tag is added
NIT:
```suggestion
   * @param pokemon the {@linkcode Pokemon} to which the tag is added
```

2024-09-05 19:46 UTC, flx-sta commented on src/data/battler-tags.ts
> +  canAdd(pokemon: Pokemon): boolean {
NIT
```suggestion
  override canAdd(pokemon: Pokemon): boolean {
```

2024-09-05 19:46 UTC, flx-sta commented on src/data/battler-tags.ts
> +  onAdd(pokemon: Pokemon): void {
NIT:
```suggestion
  override onAdd(pokemon: Pokemon): void {
```

2024-09-05 19:46 UTC, flx-sta commented on src/data/battler-tags.ts
>  export function getBattlerTag(tagType: BattlerTagType, turnCount: number, sourceMove: Moves, sourceId: number): BattlerTag {
NIT:
Mind adding js-docs here?

2024-09-05 19:57 UTC, flx-sta commented
Apart from my comments/NITs it looks to be working as expected:

### NOT Terastallized

<details>
  <summary>⏯️ NOT Terastallized Video</summary>

https://github.com/user-attachments/assets/59e164f7-d776-49c9-8955-09ea5cea3049

</details>


### Terastallized

<details>
  <summary>⏯️ Terastallized Video</summary>

https://github.com/user-attachments/assets/4c6a87d0-64dd-4486-a761-2ef236cd2f98

</details>

2024-09-06 13:32 UTC, torranx commented on src/field/pokemon.ts
> +    if (this.getTag(TarShotTag) && (this.getMoveType(move) === Type.FIRE)) {
we do not have `hasTag` for `Pokemon` object

2024-09-06 13:35 UTC, torranx commented on src/data/battler-tags.ts
> +  canAdd(pokemon: Pokemon): boolean {
I will update the code with this but bear in mind we are not currently using the `override` keyword for other classes so an update to them would be somewhat `necessary` to be consistent

2024-09-06 15:03 UTC, flx-sta approved these changes
lgtm (1 NIT)

2024-09-06 15:03 UTC, flx-sta commented on src/data/battler-tags.ts
> + * Retrieves a BattlerTag based on the provided tag type, turn count, source move, and source ID.
NIT:
```suggestion
 * Retrieves a {@linkcode BattlerTag} based on the provided tag type, turn count, source move, and source ID.
```

2024-09-06 18:43 UTC, flx-sta approved these changes

2024-09-06 19:06 UTC, frutescens approved these changes

2024-09-07 06:10 UTC, DayKev approved these changes

2024-09-09 07:40 UTC, CodeTappert approved these changes
Approved only the new localization key

2024-09-09 07:42 UTC, merged