[Localization] Move-disabling effects locales
pagefaultgames/pokerogue pull request #4046
Opened 2024-09-05 10:38 UTC by Adri1

Translation fllowing the merged of #2051 

## What are the changes the user will see?
Added move-disabling effect messages other locales

## Why am I making these changes?
Having move-disabling effect messages translated

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?

2024-09-05 12:10 UTC, CodeTappert commented on src/locales/de/battle.json
> +  "disableInterruptedMove": "{{pokemonNameWithAffix}}'s {{moveName}}\nis disabled!",
```suggestion
  "disableInterruptedMove": "{{moveName}} von {{pokemonNameWithAffix}} ist blockiert!",
```

2024-09-05 12:13 UTC, CodeTappert commented on src/locales/de/battler-tags.json
> +  "disabledLapse": "{{pokemonNameWithAffix}}'s {{moveName}}\nis no longer disabled."
```suggestion
  "stockpilingOnAdd": "{{pokemonNameWithAffix}} hortet {{stockpiledCount}}!",
  "disabledOnAdd": " {{moveName}}  von {{pokemonNameWithAffix}} wurde blockiert!",
  "disabledLapse": "{{moveName}} von {{pokemonNameWithAffix}} ist nicht länger blockiert!"
```

2024-09-05 14:54 UTC, sodaMelon reviewed
added korean localization

2024-09-05 14:54 UTC, sodaMelon commented on src/locales/ko/battle.json
> +  "disableInterruptedMove": "{{pokemonNameWithAffix}}'s {{moveName}}\nis disabled!",
```suggestion
  "disableInterruptedMove": "{{pokemonNameWithAffix}}의 {{moveName}}[[는]]\n 사용할 수 없다.",
```

2024-09-05 14:54 UTC, sodaMelon commented on src/locales/ko/battler-tags.json
> +  "disabledLapse": "{{pokemonNameWithAffix}}'s {{moveName}}\nis no longer disabled."
```suggestion
  "disabledOnAdd": "{{pokemonNameWithAffix}}의 {{moveName}}[[는]]\n사용할 수 없었다!",
  "disabledLapse": "{{pokemonNameWithAffix}}의 {{moveName}}[[는]]\n이제 사용할 수 있다."
```

2024-09-06 12:57 UTC, NicusPulcis submitted a review, later dismissed
italian localization done

2024-09-06 12:57 UTC, NicusPulcis commented on src/locales/it/battle.json
> +  "disableInterruptedMove": "{{pokemonNameWithAffix}}'s {{moveName}}\nis disabled!",
```suggestion
  "disableInterruptedMove": "La mossa {{moveName}} di\n{{pokemonNameWithAffix}} è bloccata!",
```

2024-09-06 15:33 UTC, CodeTappert commented on src/locales/de/ability-trigger.json
> +  "fullHpResistType": "{{pokemonNameWithAffix}} made its shell gleam!\nIt's distorting type matchups!",
```suggestion
  "fullHpResistType": "Der Panzer von {{pokemonNameWithAffix}} funkelt und verzerrt
die Wechselwirkungen zwischen den Typen!",
```

2024-09-06 15:34 UTC, CodeTappert commented on src/locales/de/ability-trigger.json
> +  "postSummonAuraBreak": "{{pokemonNameWithAffix}} reversed all other Pokémon's auras!",
```suggestion
  "postSummonAuraBreak": "{{pokemonNameWithAffix}} kehrt die Wirkung aller Aura-Fähigkeiten um!",
```

2024-09-06 15:35 UTC, CodeTappert commented on src/locales/de/menu.json
> +  "tooManySaves": "You have too many save files on record!"
```suggestion
  "noSaves": "Du hast keine gespeicherten Dateien!",
  "tooManySaves": "Du hast zu viele gespeicherte Dateien!"

```

2024-09-06 15:54 UTC, KimJeongSun requested changes

2024-09-06 15:54 UTC, KimJeongSun commented on src/locales/ko/ability-trigger.json
> +  "fullHpResistType": "{{pokemonNameWithAffix}} made its shell gleam!\nIt's distorting type matchups!",
```suggestion
  "fullHpResistType": "{{pokemonNameWithAffix}}[[는]] 등껍질을 빛나게 하여\n타입 상성을 왜곡시켰다!!",
```
![image](https://github.com/user-attachments/assets/48c18581-4951-4323-9b7e-e89e1d7baf3b)

2024-09-06 15:54 UTC, KimJeongSun commented on src/locales/ko/ability-trigger.json
> +  "postSummonAuraBreak": "{{pokemonNameWithAffix}} reversed all other Pokémon's auras!",
```suggestion
  "postSummonAuraBreak": "{{pokemonNameWithAffix}}[[는]]\n모든 오라를 제압한다!",
```
![image](https://github.com/user-attachments/assets/78501430-9e6b-4e75-aef5-d9f4b21e38ea)

2024-09-06 15:54 UTC, KimJeongSun commented on src/locales/ko/menu.json
> +  "noSaves": "You don't have any save files on record!",
```suggestion
  "noSaves": "기기에 세이브 파일이 없습니다!",
```

2024-09-06 15:54 UTC, KimJeongSun commented on src/locales/ko/menu.json
> +  "tooManySaves": "You have too many save files on record!"
```suggestion
  "tooManySaves": "기기에 세이브 파일이 너무 많습니다!"
```

2024-09-06 16:02 UTC, closed without merging

2024-09-06 19:19 UTC, DanStevensonx reviewed
Translated from Poké Corpus to Spanish, had to change line 72 from the original Poke Corpus lines since it didnt specify the move name

2024-09-06 19:19 UTC, DanStevensonx commented on src/locales/es/battler-tags.json
> +  "disabledOnAdd": "{{pokemonNameWithAffix}}'s {{moveName}}\nwas disabled!",
"disabledOnAdd": "¡Se ha anulado el movimiento {{moveName}}\nde {{pokemonNameWithAffix}}!",

2024-09-06 19:19 UTC, DanStevensonx commented on src/locales/es/battler-tags.json
> +  "disabledLapse": "{{pokemonNameWithAffix}}'s {{moveName}}\nis no longer disabled."
"disabledLapse": "¡El movimiento {{moveName}} de {{pokemonNameWithAffix}} \n ya no está anulado!"

2024-09-06 19:19 UTC, DanStevensonx commented on src/locales/es/battle.json
> +  "disableInterruptedMove": "{{pokemonNameWithAffix}}'s {{moveName}}\nis disabled!",
"disableInterruptedMove": "¡Se ha anulado el movimiento {{moveName}}\nde {{pokemonNameWithAffix}}!",