[P2 Bug] Fix sandstorm/hail interaction with semi invulnerable state
pagefaultgames/pokerogue pull request #4047
Opened 2024-09-05 12:51 UTC by torranx

## What are the changes the user will see?
A Pokemon in a semi-invulnerable state should no longer be damaged by Hail/Sandstorm

## Why am I making these changes?
closes #4042 

## What are the changes from a developer perspective?
add new condition on inflicting weather damage

### Screenshots/Videos

## How to test the changes?
use Dive/Fly on sandstorm/hail weather
or
`npm run test weather_sandstorm`
`npm run test weather_hail`

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-05 14:10 UTC, Tempo-anon approved these changes
Code looks good to me. Just want to confirm (on showdown) if flying/diving/digging actually does prevent sand/hail damage

2024-09-05 16:18 UTC, Snailman11 commented
> Code looks good to me. Just want to confirm (on showdown) if flying/diving/digging actually does prevent sand/hail damage

https://replay.pokemonshowdown.com/gen9customgame-2195182905-dh4jembqzrgshlkf4oed9miqur0vmrupw

Smogon on Dive 
> On the first turn, the user avoids all attacks other than Surf and Whirlpool but takes double damage from them, and is also unaffected by weather.

Smogon on Dig
> On the first turn, the user avoids all attacks other than Earthquake and Magnitude but takes double damage from them, and is also unaffected by weather.

2024-09-05 19:59 UTC, flx-sta requested changes

2024-09-05 19:59 UTC, flx-sta commented on src/phases/weather-effect-phase.ts
> +import { SemiInvulnerableTag } from "#app/data/battler-tags.js";
Groundhog day
```suggestion
import { SemiInvulnerableTag } from "#app/data/battler-tags";
```

2024-09-05 21:11 UTC, DayKev commented on src/phases/weather-effect-phase.ts
> +import { SemiInvulnerableTag } from "#app/data/battler-tags.js";
Remove all the `.js` while you're here, not just from the new import.

2024-09-06 02:31 UTC, Tempo-anon commented
> It doesn't look like Fly should avoid Sand/Hail damage, only Dig and Dive.

I seemed to recall taking damage from weather while using fly. That also means Fly needs bespoke behavior compared to all the other semi invulnerable moves then :pikastare:

2024-09-06 02:32 UTC, Tempo-anon requested changes
Fly why

2024-09-06 03:10 UTC, flx-sta commented
Back to `Draft` for Fly fix

2024-09-06 12:53 UTC, Snailman11 commented
***Additional context***
Pokemon in the semi-invulnerable turn of Bounce, Fly, Phantom and Shadow Force correctly take damage.

Not sure if this was seen?

2024-09-06 14:14 UTC, Tempo-anon approved these changes
You're telling me being underwater and underground will protect you from sand/hail but teleporting into the shadow dimension won't

2024-09-06 14:24 UTC, CodeTappert approved these changes

2024-09-06 18:15 UTC, merged