[QoL] Adding challenge arrows
pagefaultgames/pokerogue pull request #4048
Opened 2024-09-05 13:44 UTC by Opaque02

## What are the changes the user will see?
When going to start a challenge, left/right arrows will now show up for each challenge to show you that you can use the arrow keys to change them. When you get to the end, the appropriate arrow will disappear to let you know you've hit the end.

## Why am I making these changes?
Smewkie suggested it on discord, here we are
![image](https://github.com/user-attachments/assets/8a1f3f7c-ddee-4c39-9eba-a9d352f2d3ce)

## What are the changes from a developer perspective?
Added in some arrows based on the cursor and reverse cursor icons. They get placed onto the challenge ui handler, and the value text of the challenge (i.e. the generation number, type, on/off etc) is now centered between the two arrows. When you get to the max/min range of the challenge, it makes hides the arrows

### Screenshots/Videos
Below is a video of me going through the challenges screen and showing the arrows on display:

https://github.com/user-attachments/assets/b038a0c4-0426-4621-9f8f-14b3134fc47c

## How to test the changes?
Download this PR and go to start a new challenge run. Try to change the values on the challenges and see how they go. This does _not_ handle other languages well yet, so that's the next thing to work on for it

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-09-07 09:30 UTC, DayKev commented on src/ui/challenges-select-ui-handler.ts
> +      //value.setX((rightArrow.x - (leftArrow.x + leftArrow.width)) / 2);
You missed some commented out code.

2024-09-09 16:29 UTC, frutescens requested changes
When the player has pressed their first button.ACTION, could you hide the cursor arrows to signify that the challenges have been locked in? If they cancel out of confirming, then they should reappear.

2024-09-10 18:43 UTC, torranx commented on src/data/challenge.ts
while you're at it, can you change the `integer` types to `number` from the functions you changed?

2024-09-12 13:10 UTC, Opaque02 commented on src/ui/challenges-select-ui-handler.ts
> +      //value.setX((rightArrow.x - (leftArrow.x + leftArrow.width)) / 2);
Fixed in next commit

2024-09-12 13:21 UTC, Opaque02 commented on src/data/challenge.ts
Done in next commit

2024-09-12 16:16 UTC, MokaStitcher requested changes
suggested some modifications to the placement calculations, otherwise looks good!

2024-09-12 16:16 UTC, MokaStitcher commented on src/ui/challenges-select-ui-handler.ts
> +        this.monoTypeValue.setPositionRelative(challengeLabel.label, 112, 8);
```suggestion
```
setting the relative position is not needed anymore since the X and Y are set directly below

2024-09-12 16:16 UTC, MokaStitcher commented on src/ui/challenges-select-ui-handler.ts
> +      const xLocation = challengeLabel.rightArrow.x - (challengeLabel.rightArrow.x - (challengeLabel.leftArrow.x + challengeLabel.leftArrow.width)) / 2 - 0.5;
```suggestion
      // this line of code gets the center point between the left and right arrows from their left side (Arrow.x gives middle point), taking into account the width of the arrows
      const xLocation = Math.round((challengeLabel.leftArrow.x + challengeLabel.rightArrow.x + challengeLabel.leftArrow.displayWidth) / 2);;
```

leftArrow has its xOrigin to 0.5, so x is the middle point, which means the xLocation calculation can be simplified since challengeLabel also has the same xOrigin. also rounding it to avoid subpixel stuff

2024-09-13 08:22 UTC, Opaque02 commented on src/ui/challenges-select-ui-handler.ts
> +      const xLocation = challengeLabel.rightArrow.x - (challengeLabel.rightArrow.x - (challengeLabel.leftArrow.x + challengeLabel.leftArrow.width)) / 2 - 0.5;
Fixed in next commit

2024-09-13 11:37 UTC, MokaStitcher approved these changes
👍

2024-09-15 08:00 UTC, DayKev approved these changes

2024-09-23 03:22 UTC, flx-sta approved these changes
Just some NITs.
Nothing wild

2024-09-23 03:22 UTC, flx-sta commented on src/data/challenge.ts
> +    return i18next.t("challenges:singleGeneration.desc", { gen: i18next.t(`challenges:singleGeneration.gen_${value}`) });
Why isn't `this.geti18nKey()` used here?

2024-09-23 03:22 UTC, flx-sta commented on src/data/challenge.ts
>        return i18next.t("challenges:singleGeneration.desc_default");
Why isn't `this.geti18nKey()` used here?

2024-09-23 06:34 UTC, merged

2024-09-23 06:52 UTC, DayKev commented on src/data/challenge.ts
>        return i18next.t("challenges:singleGeneration.desc_default");
Probably just an oversight of the original author (or it wasn't a thing at the time), I added it to my challenge PR.