[P2 Bug] Revert to normal form when Pokemon are is fainted
pagefaultgames/pokerogue pull request #4049
Opened 2024-09-05 14:03 UTC by torranx

## What are the changes the user will see?
all pokemon that changed form and fainted in battle will now revert to their normal form

## Why am I making these changes?
closes #4029 , this not only affects Aegislash but all other pokemon that can change form like Castform, Cramorant, etc

## What are the changes from a developer perspective?
added form change trigger in faint-phase

### Screenshots/Videos
Castform

https://github.com/user-attachments/assets/af0193ea-e13e-46cf-ad2b-efed00ac7701

Meloetta

https://github.com/user-attachments/assets/623fe16f-1067-4911-85fc-0c3b288d4008

Aegislash

https://github.com/user-attachments/assets/9c9050f8-707a-4e1b-a810-973b9dd821af

Xerneas

https://github.com/user-attachments/assets/aefa77f5-f82f-4f22-b55e-0024f427f293

Cramorant

https://github.com/user-attachments/assets/24b0ed6a-4762-4bf8-a7e3-513880b9d3e2

## How to test the changes?
Overrides used, change species accordingly:
```
{
  STARTER_FORM_OVERRIDES: {
    [Species.MELOETTA]: 1,
    [Species.CASTFORM]: 1,
    [Species.AEGISLASH]: 1,
    [Species.XERNEAS]: 1,
    [Species.CRAMORANT]: 1,
  },
  STARTER_SPECIES_OVERRIDE: Species.CRAMORANT,
  OPP_LEVEL_OVERRIDE: 50,
}
```

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-05 20:00 UTC, flx-sta requested changes

2024-09-05 20:00 UTC, flx-sta commented on src/phases/faint-phase.ts
> +import { SpeciesFormChangeActiveTrigger } from "#app/data/pokemon-forms.js";
Groundhog day
```suggestion
import { SpeciesFormChangeActiveTrigger } from "#app/data/pokemon-forms";
```

2024-09-06 06:24 UTC, DayKev approved these changes

2024-09-06 14:25 UTC, CodeTappert approved these changes

2024-09-06 19:16 UTC, frutescens approved these changes

2024-09-06 19:17 UTC, merged