Basic analog support
pagefaultgames/pokerogue pull request #405
Opened 2024-05-03 03:48 UTC by WillCMcC

Add some basic analog support. I hooked into the existing button timeouts. 

Looking for some guidance on proper formatting rules here. Thanks for your work all!

2024-05-03 04:52 UTC, Flashfyre requested changes

2024-05-03 04:52 UTC, Flashfyre commented on src/battle-scene.ts
> +	LEFT_STICK_UP,
Do these need to be separate buttons for this to work? I feel like they should just trigger the directional buttons.

2024-05-03 05:24 UTC, WillCMcC commented on src/battle-scene.ts
> +	LEFT_STICK_UP,
I should be able to refactor to just use the directional buttons

2024-05-03 15:23 UTC, WillCMcC commented on src/battle-scene.ts
> +	LEFT_STICK_UP,
I think I can actually integrate this a little more deeply but we might lose some flexibility. I'll get it submitted today.

2024-05-03 15:25 UTC, Flashfyre commented on src/battle-scene.ts
> +	LEFT_STICK_UP,
You might want to wait on that, someone is refactoring inputs entirely.

2024-05-03 15:45 UTC, WillCMcC commented on src/battle-scene.ts
> +	LEFT_STICK_UP,
Ok, reworked this to use existing buttons and simplified it a bit.

2024-05-03 16:27 UTC, WillCMcC commented on src/battle-scene.ts
> +	LEFT_STICK_UP,
hm, reusing the constants I seem to be getting phantom inputs, taking a look

2024-05-05 15:18 UTC, Flashfyre commented on src/battle-scene.ts
> +	LEFT_STICK_UP,
The refactor is in, so this is ready to be updated

2024-05-05 16:36 UTC, WillCMcC commented on src/battle-scene.ts
> +	LEFT_STICK_UP,
Roger, will take a look thanks. I'm on paternity so moving slowly

2024-05-19 13:55 UTC, bennybroseph commented
Closing this due to inactivity. Feel free to make a new request if interest is reignited

2024-05-19 13:55 UTC, closed without merging