[Enhancement] Update instruction for gamepad in run history UI
pagefaultgames/pokerogue pull request #4053
Opened 2024-09-05 16:37 UTC by KimJeongSun

## What are the changes the user will see?

## Why am I making these changes?

## What are the changes from a developer perspective?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-05 17:05 UTC, frutescens requested changes

2024-09-05 17:05 UTC, frutescens commented on src/ui/run-info-ui-handler.ts
> +  private getGamepadType(): string {
I think this is a great method and so it should be part of the ui.ts class so all other UI can access it.

2024-09-05 18:42 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +      }
Is touch a special-case scenario? Cause you would think that that the
`this.scene.inputController?.getIconForLatestInputRecorded(SettingKeyboard.Button_Cycle_Ability));` would also be able to handle touch

2024-09-05 18:42 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +      }
same question as before

2024-09-05 18:42 UTC, flx-sta commented on src/ui/run-info-ui-handler.ts
> +  private getGamepadType(): string {
+1

2024-09-06 00:34 UTC, KimJeongSun commented on src/ui/run-info-ui-handler.ts
> +  private getGamepadType(): string {
I will update it!

2024-09-06 00:35 UTC, KimJeongSun commented on src/ui/run-info-ui-handler.ts
> +      }
I follow the method in starter-select-ui, but i will check if it also possible in `touch`

2024-09-06 00:49 UTC, KimJeongSun commented on src/ui/run-info-ui-handler.ts
> +      }
I checked it, but that function looks not working to get proper icon in gamepadType = "touch" 
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/a502ed8a-2d9f-4b5d-90c8-e8985583b136">

2024-09-06 01:32 UTC, KimJeongSun commented on src/ui/run-info-ui-handler.ts
> +  private getGamepadType(): string {
updated!

2024-09-06 02:11 UTC, frutescens approved these changes

2024-09-10 18:45 UTC, torranx commented on src/ui/ui.ts
> +   * if inputMethod is "gamepad", then the gamepad type is returned it could be "xbox" or "duelshock"
isn't it supposed to be `dualshock`?
```suggestion
   * if inputMethod is "gamepad", then the gamepad type is returned it could be "xbox" or "dualshock"
```

2024-09-11 00:48 UTC, KimJeongSun commented on src/ui/ui.ts
> +   * if inputMethod is "gamepad", then the gamepad type is returned it could be "xbox" or "duelshock"
you are right!

2024-09-11 03:45 UTC, merged