[P2 Bug] Fix Aura Break applying without Dark/Fairy Aura present
pagefaultgames/pokerogue pull request #4057
Opened 2024-09-05 19:36 UTC by innerthunder

## What are the changes the user will see?
This fixes a bug where Aura Break would apply its power debuff despite Dark and/or Fairy Aura not being present on the field

## Why am I making these changes?
closes #4050 

## What are the changes from a developer perspective?

- `data/ability`: Changed Aura Break's condition (in its `conditionalAttr`s) to check all active Pokemon on the field for Dark/Fairy Aura instead of a single "target" Pokemon (or, really, just Aura Break's source under a misnamed arg).
- `data/move`: Changed `Move#calculateBattlePower` so that field aura attributes that don't satisfy their conditions from `getCondition()` are filtered out before applying.
- `test/abilities/aura_break.test`: New test covering the case where neither Dark Aura nor Fairy Aura are present.

### Screenshots/Videos

## How to test the changes?
`npm run test aura_break`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [?] Are the changes visual?
  - [?] Have I provided screenshots/videos of the changes?

2024-09-05 19:41 UTC, torranx approved these changes
coolio

2024-09-05 20:30 UTC, flx-sta commented on src/data/ability.ts
> +      .conditionalAttr(pokemon => pokemon.scene.getField(true).some(p => p.hasAbility(Abilities.FAIRY_AURA)), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 9 / 16),
Does this resolve in a `AND` or in a `OR` connection of conditions?

2024-09-05 20:30 UTC, flx-sta commented on src/data/move.ts
> +          return (!condition || condition(p));
what!? I'm a bit confused what this does

2024-09-05 20:31 UTC, innerthunder commented on src/data/ability.ts
> +      .conditionalAttr(pokemon => pokemon.scene.getField(true).some(p => p.hasAbility(Abilities.FAIRY_AURA)), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 9 / 16),
`some` is an `OR` connection/reduction

2024-09-05 20:40 UTC, flx-sta commented
# Fairy Aura (Player)

## No Break (Enemy)

https://github.com/user-attachments/assets/164ca89e-5ea6-47d8-ae25-fae64a9c2112

## Aura Break (Enemy)

https://github.com/user-attachments/assets/afecb35c-41cf-4b85-a86d-c6b6be1e856f

---

# Dark Aura

## No Break (Enemy)

https://github.com/user-attachments/assets/e981982b-db61-4518-985f-f7081b63565e

## Aura Break (Enemy)

https://github.com/user-attachments/assets/b836d5af-6dc3-4d86-a6b6-29e2d2d41147

2024-09-05 20:43 UTC, innerthunder commented on src/data/move.ts
> +          return (!condition || condition(p));
This gets all "aura" ability attributes from the Pokemon on the field and checks their condition from `getCondition`. Then it filters out any ability that has a condition that isn't met.

Maybe a clearer way to put this would be:
```suggestion
          return (condition === null || condition(p));
```

2024-09-05 20:55 UTC, flx-sta requested changes
There should be a message if the aura is broken
![image](https://github.com/user-attachments/assets/99a002da-ff9b-4768-8b32-574c493c6fbc)
https://youtu.be/aT3eNBkSElY?t=10

2024-09-05 21:09 UTC, innerthunder commented
Just added a post-summon message. It should only trigger if there is a Pokemon with Dark/Fairy Aura on the field

2024-09-05 21:41 UTC, flx-sta approved these changes
lgtm

https://github.com/user-attachments/assets/0ac61f6f-4d12-4feb-9f34-245b16d05622

2024-09-05 21:47 UTC, Tempo-anon approved these changes

2024-09-06 00:08 UTC, frutescens approved these changes

2024-09-06 07:58 UTC, f-fsantos approved these changes

2024-09-06 07:59 UTC, merged