[Balance] Rogue ball increase catch chance tinted pokemon
pagefaultgames/pokerogue pull request #4065
Opened 2024-09-06 07:50 UTC by Opaque02

## What are the changes the user will see?
Rogue balls now have a 5x chance to catch pokemon instead of 3x if the pokemon has a tinted pokeball

## Why am I making these changes?
Damo wanted it. More details to come
![image](https://github.com/user-attachments/assets/78400b64-a951-47d5-8d0f-0865cff9c4e4)

## What are the changes from a developer perspective?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-06 14:12 UTC, Tempo-anon commented on src/locales/en/modifier-type.json
> +      "catchRateGenerator": "{{normalCatchRate}}x ({{boostedCatchRate}}x for uncaught Pokemon)"
Uncaught is not quite the same as the tinted pokeball since the tinted pokeball relates to both the specific pokemon form's dex attributes (like having owned a male charizard but not a female one) as well as the root form's ability index

2024-09-07 01:28 UTC, Adri1 commented on src/locales/en/modifier-type.json
> +      "catchRateGenerator": "{{normalCatchRate}}x ({{boostedCatchRate}}x for uncaught Pokemon)"
```suggestion
      "catchRateGenerator": "{{normalCatchRate}}x ({{boostedCatchRate}}x for uncaught Pokémon)"
```

2024-09-07 01:54 UTC, Opaque02 commented on src/locales/en/modifier-type.json
> +      "catchRateGenerator": "{{normalCatchRate}}x ({{boostedCatchRate}}x for uncaught Pokemon)"
Thanks! Fixed in next commit!

2024-09-07 01:55 UTC, Opaque02 commented on src/locales/en/modifier-type.json
> +      "catchRateGenerator": "{{normalCatchRate}}x ({{boostedCatchRate}}x for uncaught Pokemon)"
Ah, that's a very good point - what wording would we want to use instead? "{{boostedCatchRate}}x for tinted pokeballs? We're a little limited on space is the only issue?

2024-09-17 04:51 UTC, Opaque02 commented on src/data/pokeball.ts
> +  const description = getBoostedDescription ?? false;
Would doing it the way I've already got it not be safer for things as a just in case? Or would it not make a difference in this case with how I've got it?

2024-09-17 12:41 UTC, DayKev commented on src/data/pokeball.ts
> +  const description = getBoostedDescription ?? false;
`null` and `undefined` are both treated the same way in this scenario (for `enemyPokemon`), and both also evaluate to `false` when used in an if statement (for `getBoostedDescription`).

2024-09-17 22:37 UTC, Opaque02 commented on src/data/pokeball.ts
> +  const description = getBoostedDescription ?? false;
Perfect! I think I was in the mindset of fixing the challenges which used a similar change to what I did here - let me push a  change through now!

2024-09-19 08:19 UTC, Opaque02 commented on src/locales/en/modifier-type.json
> +      "catchRateGenerator": "{{normalCatchRate}}x ({{boostedCatchRate}}x for uncaught Pokemon)"
@Tempo-anon it should now be clearer - let me know what you think

2024-09-19 08:47 UTC, DayKev commented on src/data/pokeball.ts
> +       */
```suggestion
    // Rogue balls have a higher chance to catch pokemon if they have a tinted pokeball icon (i.e. at least one thing is new for them).
    // You can also get the boosted type for a description (i.e. for modifier-type).
```
> You can also get the boosted type for a description (i.e. for modifier-type).

What exactly does this mean?

2024-09-19 08:47 UTC, DayKev commented on src/field/pokemon.ts
> +   */
```suggestion
  /*
   * Checks whether or not the pokemon's pokeball icon will be tinted.
   * This checks the dex attributes (gender, shiny/non shiny, variant and forms).
   * These values are checked against the exact pokemon you're catching (i.e. catching charizard won't compare against charmander).
   * It also checks your abilities against the starter version.
   * If you are missing any, the pokemon's pokeball icon is tinted.
   * @returns `true` if the pokemon's pokeball icon should be tinted, meaning at least one thing is new
   */
```

2024-09-19 08:47 UTC, DayKev commented on src/modifier/modifier-type.ts
> +  }
This function doesn't seem to be named properly (or it's not working as it should), it's setting an amount and not adding it.

2024-09-19 13:47 UTC, Tempo-anon commented
How does this work with fresh start since theoretically this would mean the more full your dex is the technically harder fresh start would be

2024-09-19 13:48 UTC, Tempo-anon commented on src/field/pokemon.ts
> +      playerOwnsThisAbility = true;
I ended up just taking this whole chunk into its own helper function in https://github.com/pagefaultgames/pokerogue/pull/4307 since it seems to be needed in the pokemon-info-container as well

2024-09-19 14:39 UTC, Opaque02 commented on src/data/pokeball.ts
> +       */
The boosted type for the description in shops. Since normally it's just listed as "Catch rate: 3x", there needs to be a way to get the boosted value without a pokemon. The getBoostedDescription boolean does that, so if that's passed, then the it's for the shop description.

2024-09-19 15:00 UTC, Opaque02 commented on src/field/pokemon.ts
> +      playerOwnsThisAbility = true;
Ah good point - want me to change it based on your or make a new change once yours goes in?

2024-09-19 15:10 UTC, Opaque02 commented on src/modifier/modifier-type.ts
> +  }
True, fixed in next commit

2024-09-19 15:45 UTC, Opaque02 commented
> How does this work with fresh start since theoretically this would mean the more full your dex is the technically harder fresh start would be

As per Damo on discord, only for fresh start rogue balls should be at a constant 5x rate; I'll get this updated

2024-09-19 22:41 UTC, EnochG1 requested changes
If you modify, not add new text,
all translations become mistranslated if you do not modify the text in all locale files to changed English text.
(I thing wrong translation is worse than untranslated right English)
I would request to change all locales/{lang}/modifire-type.json.

2024-09-23 07:42 UTC, Opaque02 commented
> If you modify, not add new text, all translations become mistranslated if you do not modify the text in all locale files to changed English text. (I thing wrong translation is worse than untranslated right English) I would request to change all locales/{lang}/modifire-type.json.

@EnochG1 - can you elaborate a bit more on what I should change? We don't need to put the new keys in manually these days, so  just want to double check about what I should change for this one

2024-09-23 15:21 UTC, Tempo-anon commented
4307 has been merged in. You can keep the `isTintedPokeball` function but you can now refactor it based on the other helper function I added. (And can also update pokemon-info-container and battle-info to use the new `isTintedPokeball`)

As for a constant 5x for fresh start... I'm not sure. Sure it works but there's a bunch of edge cases for that. Would it really be that broken for them to be a constant 5x boost? Pokeballs in general feel pretty underpowered for the tiers they're in. (5 ultra balls is the equivalent of 10 pokeballs has to compete with things like reviver seeds, rare evo items, mints, competitive items and 5 rogue balls which is the equivalent of 15-25 pokeballs has to compete with form change items and really competitive items like leftovers, shell bell, king's rock, etc)

2024-10-19 09:48 UTC, Opaque02 commented on src/field/pokemon.ts
> +      playerOwnsThisAbility = true;
Fixed and updated - should be in latest commit

2024-10-26 02:21 UTC, MokaStitcher requested changes
Haven't reviewed the rest yet, but it seems Skorupi's sprite got accidentally modified during of the merges probably, please fix :pray: 
![1000069300](https://github.com/user-attachments/assets/5a83ed2e-c38a-4d72-827f-5d9b16adad87)

2024-10-26 03:47 UTC, chaosgrimmon commented
> Haven't reviewed the rest yet, but it seems Skorupi's sprite got accidentally modified during of the merges probably, please fix 🙏

Yeah, those had to be hotfixed for Main because they'd cause a crash when used as a fusion material. The preferable solution would be to keep the .pngs, and use the .json [here instead](https://discord.com/channels/1125469663833370665/1290008413975351317/1290938914122633247)

This one might be the download link directly:
https://cdn.discordapp.com/attachments/1290008413975351317/1290938913774501909/451.json?ex=671d434d&is=671bf1cd&hm=f289a034970205777c842f39687efa0e47c4f05c8caabf643a291eafd5099cac&

2024-10-26 04:09 UTC, MokaStitcher commented
> The preferable solution would be to keep the .pngs, and use the .json here instead

Yeah but I don't think it should be part of this PR, I'd rather have a separate PR to fix Skorupi and just revert the changes from this PR

2024-10-26 06:11 UTC, DayKev commented
> > The preferable solution would be to keep the .pngs, and use the .json here instead
> 
> Yeah but I don't think it should be part of this PR, I'd rather have a separate PR to fix Skorupi and just revert the changes from this PR

It's just a git history issue, the change isn't part of this PR (it's in the f7715d7 merge commit).

2024-10-30 12:17 UTC, PigeonBar commented on src/modifier/modifier-type.ts
> +      "catchRate": catchRate,
The master ball's catch rate is no longer being displayed:

![20241030 Master Catch Rate](https://github.com/user-attachments/assets/c100de00-e6b5-4ebf-a56b-013e3615d2b4)

2024-10-30 12:27 UTC, PigeonBar commented
ME's have their own copy of the capture attempt function, which probably also needs updating (Line 376):
https://github.com/pagefaultgames/pokerogue/blob/b3a0ca94753d13dd110c17f1856872a7b2dc9890/src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#L369-L380

2024-10-30 17:19 UTC, Tempo-anon commented
I still think this change while is cool in theory, seems to be quite complicated as it involves changing a LOT of files, not to mention a lot of locale changes and thoughts on how to future proof it for various challenges.

Hell, just make rogue balls 5x or 10x across the board no matter what because they suck compared to the other things in the rogue tier.

2024-10-30 20:37 UTC, DayKev commented
> ME's have their own copy of the capture attempt function, which probably also needs updating (Line 376):
> 
> https://github.com/pagefaultgames/pokerogue/blob/b3a0ca94753d13dd110c17f1856872a7b2dc9890/src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#L369-L380

Wait what? Why?

2024-10-30 21:48 UTC, PigeonBar commented
> > ME's have their own copy of the capture attempt function, which probably also needs updating (Line 376):
> > https://github.com/pagefaultgames/pokerogue/blob/b3a0ca94753d13dd110c17f1856872a7b2dc9890/src/data/mystery-encounters/utils/encounter-pokemon-utils.ts#L369-L380
> 
> Wait what? Why?

Right now, I think it's just used for Safari Zone

2024-10-30 22:03 UTC, MokaStitcher commented
> It's just a git history issue, the change isn't part of this PR (it's in the [f7715d7](https://github.com/pagefaultgames/pokerogue/commit/f7715d7d10469cce8ac829e6c367bec794901535) merge commit).

No, it's an issue with this branch. Here's how the Skorupi sheet looks in beta (taller than it is wide)
![Screenshot_20241030-225049~2](https://github.com/user-attachments/assets/b3acff43-87a2-4c63-a25c-c4f0cd159f00)

Here's how it is on Opaquer's branch (wider than it is tall. This is the one that got added then reverted some time ago. It shouldn't get back in as it is broken, and has nothing to do with this PR anyway. Something went wrong during one of the merges to this branch, it's fine as long as a new commit it made that reverts the changes)
![Screenshot_20241030-225535~2](https://github.com/user-attachments/assets/97455ae6-2f50-4a94-815c-a742590f4ff6)

2025-05-21 18:42 UTC, SirzBenjie commented
Closing this as it is an old draft and it has many conflicts. If this behavior is desired, it can be reopened.

2025-05-21 18:42 UTC, closed without merging