[Localization] New translations batch locales (Move-disabling effects, abilities triggers, error messages)
pagefaultgames/pokerogue pull request #4068
Opened 2024-09-06 16:06 UTC by Adri1

## What are the changes the user will see?
Added missing translations to locales (Move-disabling effects, abilities triggers, error messages)
**I added English placeholders to facilitate suggestions, but if a language never provide any translation, I'll remove these placeholders before merge.**

## Why am I making these changes?
Having them translated

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?

2024-09-06 17:57 UTC, 40chyan reviewed
zh

2024-09-06 17:57 UTC, 40chyan commented on src/locales/zh_CN/battle.json
> +  "disableInterruptedMove": "{{pokemonNameWithAffix}}'s {{moveName}}\nis disabled!",
```suggestion
  "disableInterruptedMove": "{{pokemonNameWithAffix}}的{{moveName}}\n被无效化了！",
```

2024-09-06 17:57 UTC, 40chyan commented on src/locales/zh_TW/battle.json
> +  "disableInterruptedMove": "{{pokemonNameWithAffix}}'s {{moveName}}\nis disabled!",
```suggestion
  "disableInterruptedMove": "{{pokemonNameWithAffix}}的{{moveName}}\n被無效化了！",
```

2024-09-07 01:32 UTC, EnochG1 commented on src/locales/ko/modifier-type.json
> +      "description": "Quadruples the chance of an encounter being a double battle for up to {{battleCount}} battles."
```suggestion
      "description": "{{battleCount}}번의 배틀 동안 더블 배틀이 등장할 확률이 4배가 된다."
```

2024-09-07 01:32 UTC, EnochG1 commented on src/locales/ko/modifier-type.json
> +      }
```suggestion
      "description": "자신의 모든 포켓몬이 {{amount}}번의 배틀 동안 {{stat}}[[가]] 한 단계 증가한다.",
      "extra": {
        "stage": "1 스테이지",
        "percentage": "30%"
      }
```

2024-09-07 01:34 UTC, EnochG1 commented on src/locales/ko/modifier-type.json
> +      }
```suggestion
      "description": "자신의 모든 포켓몬이 5번의 배틀 동안 {{stat}}[[가]] {{amount}}단계 증가한다.",
      "extra": {
        "stage": "1 스테이지",
        "percentage": "30%"
      }
```

2024-09-07 11:21 UTC, Chapybara-jp requested changes

2024-09-07 11:21 UTC, Chapybara-jp commented on src/locales/ja/modifier-type.json
> +      "description": "バトル{{battleCount}}かいのあいだ ダブルバトルになるかくりつを4ばいにする"
```suggestion
      "description": "バトル{{battleCount}}回の間 　ダブルバトルになる　　確率を　4倍に　する"
```

2024-09-07 11:21 UTC, Chapybara-jp commented on src/locales/ja/modifier-type.json
> +      "description": "Increases the {{stat}} of all party members by {{amount}} for up to 5 battles.",
```suggestion
      "description": "全員の　手持ちポケモンの　{{stat}}を　最大５回の　バトルの間に　{{amount}}あげる.",
```

2024-09-07 11:21 UTC, Chapybara-jp commented on src/locales/ja/modifier-type.json
> +        "percentage": "30%"
```suggestion
        "stage": "１段階",
        "percentage": "３０％"
```

2024-09-07 11:55 UTC, Chapybara-jp submitted a review, later dismissed

2024-09-07 14:07 UTC, CodeTappert commented on src/locales/de/modifier-type.json
> +      "description": "Quadruples the chance of an encounter being a double battle for up to {{battleCount}} battles."
```suggestion
      "description": "Vervierfacht die Chance, dass ein Kampf ein Doppelkampf wird, für bis zu {{battleCount}} Kämpfe."
```

2024-09-07 14:24 UTC, CodeTappert commented on src/locales/de/modifier-type.json
> +      }
```suggestion
  "description": "Erhöht {{stat}} aller Teammitglieder um {{amount}} für bis zu 5 Kämpfe.",
  "extra": {
    "stage": "eine Stufe",
    "percentage": "30%"
  }
}
```

2024-09-07 16:55 UTC, NicusPulcis submitted a review, later dismissed
italian thingies approved and localization for the new two texts added

2024-09-07 16:55 UTC, NicusPulcis commented on src/locales/it/menu.json
> +  "tooManySaves": "You have too many save files on record!"
```suggestion
  "noSaves": "Non ci sono file di salvataggio registrati!",
  "tooManySaves": "Ci sono troppi file di salvataggio registrati!"
```

2024-09-07 20:10 UTC, 40chyan reviewed
zh

2024-09-07 20:10 UTC, 40chyan commented on src/locales/zh_CN/modifier-type.json
> +      "description": "Quadruples the chance of an encounter being a double battle for up to {{battleCount}} battles."
```suggestion
      "description": "遭遇双打概率提升四倍，持续{{battleCount}}场战斗。"
```

2024-09-07 20:10 UTC, 40chyan commented on src/locales/zh_CN/modifier-type.json
> +      "description": "Increases the {{stat}} of all party members by {{amount}} for up to 5 battles.",
```suggestion
      "description": "提升全队的{{stat}}{{amount}}级，持续5场战斗。",
```

2024-09-07 20:10 UTC, 40chyan commented on src/locales/zh_CN/modifier-type.json
> +        "stage": "1 stage",
```suggestion
        "stage": "1阶",
```

2024-09-07 20:10 UTC, 40chyan commented on src/locales/zh_CN/menu.json
> +  "tooManySaves": "You have too many save files on record!"
```suggestion
  "noSaves": "你没有任何记录文件！",
  "tooManySaves": "你的记录文件太多了！"
```

2024-09-07 20:10 UTC, 40chyan commented on src/locales/zh_TW/modifier-type.json
> +      "description": "Quadruples the chance of an encounter being a double battle for up to {{battleCount}} battles."
```suggestion
      "description": "遭遇雙打機率提升四倍，持續{{battleCount}}場戰鬥。"
```

2024-09-07 20:10 UTC, 40chyan commented on src/locales/zh_TW/modifier-type.json
> +      "description": "Increases the {{stat}} of all party members by {{amount}} for up to 5 battles.",
```suggestion
      "description": "提升全隊的{{stat}}{{amount}}級，持續5場戰鬥。",
```

2024-09-07 20:10 UTC, 40chyan commented on src/locales/zh_TW/modifier-type.json
> +        "stage": "1 stage",
```suggestion
        "stage": "1階",
```

2024-09-07 20:10 UTC, 40chyan commented on src/locales/zh_TW/menu.json
> +  "noSaves": "You don't have any save files on record!",
```suggestion
  "noSaves": "你沒有任何記錄檔！",
```

2024-09-07 20:10 UTC, 40chyan commented on src/locales/zh_TW/menu.json
> +  "tooManySaves": "You have too many save files on record!"
```suggestion
  "tooManySaves": "你的記錄檔太多了！"
```

2024-09-07 20:27 UTC, CodeTappert approved these changes

2024-09-07 21:37 UTC, Chapybara-jp approved these changes

2024-09-07 22:34 UTC, frutescens approved these changes

2024-09-08 00:49 UTC, EnochG1 approved these changes

2024-09-08 01:03 UTC, frutescens commented
Hi, has this bug been addressed in this PR? https://discord.com/channels/1125469663833370665/1282109467650953236/1282109467650953236

2024-09-08 11:57 UTC, merged

2024-09-08 15:10 UTC, Adri1 commented
> Hi, has this bug been addressed in this PR? https://discord.com/channels/1125469663833370665/1282109467650953236/1282109467650953236

Nope, just learned about it