[Featuyre] Toggle Pokemon cries
pagefaultgames/pokerogue pull request #4074
Opened 2024-09-06 21:34 UTC by flx-sta

## What are the changes the user will see?

A new setting will be available to turn PKM cries on/off during battle. 
> [!WARNING]
> This will not affect cries in the starter-select screen or in the evolution phase!

## Why am I making these changes?
It's a highly requested feature and can also speed up tests

## What are the changes from a developer perspective?
The `BattleScene` has a new field called `enablePokemonCries` (Same old...).
This fields value is checked during `faintCry()`, `encounter-phase` and `summon-phase`.
Some callback delay values are automatically adjusted too as we don't want the player to have to wait for a cry that isn't even being played.

### Screenshots/Videos

<img width="946" alt="image" src="https://github.com/user-attachments/assets/22e0bef1-b1d5-4375-a0d2-625adb8e028d">

## How to test the changes?

- Adjust the setting to on or off
- Play 1 wave and make sure that both your pokemon and the enemy pokemon is fainted to check if the faint cries are also (not) playing

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- ~~[ ] Have I considered writing automated tests for the issue?~~
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-09-06 23:02 UTC, Adri1 submitted a review, later dismissed

2024-09-06 23:03 UTC, Adri1 commented on src/locales/en/settings.json
> +  "pokemonCries": "Pokemon Cries"
```suggestion
  "pokemonCries": "Pokémon Cries"
```

2024-09-06 23:03 UTC, Adri1 approved these changes

2024-09-07 03:09 UTC, frutescens requested changes
Wouldn't it make more sense to go to the function cry() in pokemon-species.ts and disable the cry there? This way, cries will be disabled at the source. Also, wouldn't it be better to check / set scene.fieldVolume to 0 and use that in pokemon-species.ts' cry() instead of creating a new setting?

2024-09-07 03:12 UTC, frutescens commented
Mm, I did take a look at faintCry() and fusionFaintCry() and they do seem fairly clunky. It is surprising that they're very different from cry() but I do get why it's not so easily cut and dry.

2024-09-07 05:59 UTC, DayKev commented
If it only affects cries during battle and not elsewhere (ie: evolution) then maybe the label in the settings should be "Pokémon Cries In Battle [y/n]"

2024-09-07 11:35 UTC, DayKev commented
Btw I checked the test speed-up vs beta and:

Before:
![image](https://github.com/user-attachments/assets/de07d1d8-7629-40f8-8cf2-74886146b88a)
After:
![image](https://github.com/user-attachments/assets/3ed1e931-a678-431b-8f3f-c872c02e48a4)

Not incredible or anything, but it's decent. However, when one or more Pokémon faint:

Before:
![image](https://github.com/user-attachments/assets/aaf8172f-d882-48de-ad90-a44b68545e8c)
After:
![image](https://github.com/user-attachments/assets/1de8aec2-89f6-4b1e-902f-3c75aeb65deb)

Insane. `FaintPhase` no longer takes multiple whole seconds (!).

2024-09-07 18:37 UTC, flx-sta commented
> Wouldn't it make more sense to go to the function cry() in pokemon-species.ts and disable the cry there? This way, cries will be disabled at the source. Also, wouldn't it be better to check / set scene.fieldVolume to 0 and use that in pokemon-species.ts' cry() instead of creating a new setting?

This might be something to consider… yeah.
Is field only cries and faint cries anyway ?

regarding not changing `cry()`: cause I didn’t want it to affect evolutions & starter select cry’s. But if that is affected by “field” volume too I would probably cut it out too

2024-09-07 20:26 UTC, frutescens commented
Yes, field volume covers all cries + battle sounds. I think this feature is useful for devs, but not so useful for users (although I could see performance arguments for putting similar checks for other sound cues like BGM)

2024-09-12 17:57 UTC, flx-sta commented
@frutescens may take over this feature

2024-09-12 17:57 UTC, closed without merging