Fix Form Changes with Secondary Fusion Component
pagefaultgames/pokerogue pull request #408
Opened 2024-05-03 05:40 UTC by bennybroseph

Allows form changes when you have a Pokemon chosen as the second component of a fusion. i.e. Charizard/Snorlax can still be Dynamaxed with a Max Mushroom.

This also allows these items to spawn where they wouldn't previously.

https://github.com/pagefaultgames/pokerogue/assets/13838608/7e2bb4f5-d1c2-4910-9a36-7cf506893696

2024-05-03 05:40 UTC, bennybroseph commented
Regular form change for sanity
https://github.com/pagefaultgames/pokerogue/assets/13838608/6b8c0687-aee9-4fa0-ba9c-8e729af70390

2024-05-03 08:11 UTC, Xavion3 requested changes
Nice, I was working on basically this feature myself too, so I've got some grounding for it.

How does this handle form changes which match both halves? That was one of the trickiest things to me, supporting independent form changes.

2024-05-03 08:11 UTC, Xavion3 commented on src/field/pokemon.ts
>    changeForm(formChange: SpeciesFormChange): Promise<void> {
There's two changeForm functions, why aren't you doing anything with the second one?

2024-05-03 16:29 UTC, bennybroseph commented on src/field/pokemon.ts
>    changeForm(formChange: SpeciesFormChange): Promise<void> {
Ah, both very good points. I haven't tested a double fusion like that before. Does seems tricky, but also probably fine to include without support for now right? I imagine most people are fusing two different things and enabling that to work is better than waiting for an edge case fix.

As far as the other changeForm function, it must not have gotten called on anything I was testing so I didn't see I needed to make changes. Taking a glance, it looks like it's nearly identical to the other one so it won't take much to update it. I'm now curious why it exists though and when it gets called.

I'll take a look at both of these later today.

2024-05-03 18:20 UTC, bennybroseph commented on src/field/pokemon.ts
>    changeForm(formChange: SpeciesFormChange): Promise<void> {
I've updated the second function as requested. Still not sure when it gets called, but it matches the functionality of the other one now. 

As for double fusions, do you think that should be a separate PR?

2024-05-13 10:15 UTC, bennybroseph commented
This is probably doable now but will need to be nearly restarted. Closing this out for now.

2024-05-13 10:15 UTC, closed without merging