Implement Stockpile, Spit Up, and Swallow (WIP)
pagefaultgames/pokerogue pull request #410
Opened 2024-05-03 08:05 UTC by mareksison

Currently partially implemented Stockpile (apply the STOCKPILE BattlerTag that does not do anything yet and buffs Stockpile user's Defense and Special Defense)

To-Do:
- Stockpile counter
- find way to detect and remove Stockpile counter and debuff Defense and Special Defense
- implement Spit Up and Swallow

2024-05-04 02:51 UTC, TempsRay commented
Where are you planning on storing the stockpile counter? Somewhere in the Pokemon or just through battler tags like STOCKPILE_ONE, STOCKPILE_TWO, and STOCKPILE_THREE?

2024-05-05 05:00 UTC, mareksison commented
> Where are you planning on storing the stockpile counter? Somewhere in the Pokemon or just through battler tags like STOCKPILE_ONE, STOCKPILE_TWO, and STOCKPILE_THREE?

I was wrestling with this question actually, and I think Im leaning towards battler tags, because I think it would be cleaner code wise, as opposed to having to write functions into the pokemon class

2024-05-06 14:21 UTC, TempsRay commented on src/data/move.ts
> +export class StockpileDamageAttr extends FixedDamageAttr {
You don't want to be using FixedDamageAttr as that is fixed damage. You probably want VariablePowerAttr since you're just adjusting base power

2024-05-06 14:23 UTC, TempsRay commented on src/data/move.ts
> +          attackScore *= 1.5;
What is this chunk of code doing? It's not clear at a glance

2024-05-06 14:25 UTC, TempsRay commented on src/data/move.ts
> +      .attr(StatChangeAttr, [ BattleStat.DEF, BattleStat.SPDEF ], 1, true)
I would bundle all of this into a single StockpileAttr that does the checking for which battler tag to apply and do the stat changes. I don't think what you're doing here will necessarily work

2024-05-06 14:26 UTC, TempsRay commented on src/data/move.ts
> +      .attr(StatChangeAttr, [ BattleStat.DEF, BattleStat.SPDEF ], -1, true)
Would also move the stat changing into the damage attr (and probably name it something like `SpitUpDamageAttr` since it's only used by Spit Up) since you're losing def/spdef based on how much you've stockpiled up

2024-05-06 14:27 UTC, TempsRay requested changes

2024-05-06 14:27 UTC, TempsRay commented on src/data/move.ts
> +     */
nit: remove comments

2024-05-06 15:43 UTC, mareksison commented on src/data/move.ts
> +      .attr(StatChangeAttr, [ BattleStat.DEF, BattleStat.SPDEF ], 1, true)
okay yeah, I'll condense them to one

2024-05-06 23:58 UTC, TempsRay commented on src/data/move.ts
> +  constructor(move: string = "Stockpile") {
I don't think you want to be passing in a string when Move exists as an enum

2024-05-06 23:58 UTC, TempsRay commented on src/data/move.ts
> +    if (move === "Spit-Up" || move === "Swallow"){
this is not how hardcoded moves are checked

2024-05-06 23:58 UTC, TempsRay commented on src/data/move.ts
> +    super([ BattleStat.ATK, BattleStat.SPATK ], l, true);
stockpile gives +1def and spdef

2024-05-07 00:00 UTC, TempsRay commented on src/data/move.ts
> +    super([ BattleStat.ATK, BattleStat.SPATK ], l, true);
Also are you passing `l` or `this.levels` into the super?

2024-05-07 00:02 UTC, TempsRay commented on src/data/move.ts
> +      case 1:
break/default to close off the switch?

2024-05-07 00:03 UTC, TempsRay commented on src/data/move.ts
> +    switch (stock){
this should fail if the user already is on stockpile_three

2024-05-07 00:03 UTC, TempsRay commented on src/data/move.ts
> +      .attr(StockpileStatChangeAttr, 'Stockpile')
You probably want to be passing in the enum like `.attr(StockpileStatChangeAttr, Moves.STOCKPILE)`

2024-05-07 00:04 UTC, TempsRay commented on src/data/move.ts
> +      .attr(RemoveBattlerTagAttr, [
RemoveBattlerTagAttr by default targets whatever the target is. As an AttackMove the target will be the opponent

2024-05-07 00:05 UTC, TempsRay requested changes
Make sure to test these changes work properly

2024-05-08 06:53 UTC, mareksison commented on src/data/move.ts
> +    super([ BattleStat.ATK, BattleStat.SPATK ], l, true);
ah the stats are an honest mistake.

I intended for "l" to be passed into the super

2024-05-08 06:57 UTC, mareksison commented
> stockType = BattlerTagType.STOCKPILE_ONE;

thank you so much for the patience and for helping me along with the changes. I have made the changes in my local and will upload once I have properly tested it.

2024-05-08 16:34 UTC, TempsRay commented on src/data/move.ts
> +    if (move === Moves.SPIT_UP || move === Moves.SWALLOW){
I believe when checking id you want `move.getMove().id`

2024-05-08 16:38 UTC, TempsRay commented on src/data/move.ts
> +      this.levels = stock * -1;
This is a bit hard to read uncommented

2024-05-08 16:40 UTC, TempsRay commented on src/data/move.ts
> +    if (!super.apply(user, target, move, args) || willFail)
Having the super.apply first will mean that it's always called before checking `willFail`.

Also, the `AddBattlerTagAttr` has a variable `failOnOverlap` that can be set to automatically fail if it tries to apply a battler tag that already exists

2024-05-08 16:41 UTC, TempsRay commented on src/field/pokemon.ts
> +>>>>>>> main
Git merge conflicts in here

2024-05-08 16:41 UTC, TempsRay commented on src/overrides.ts
> +export const MOVE_OVERRIDE_3 = Moves.NONE;
I believe there's already 4 move overrides merged into main. You might want to rebase and fix conflicts

2024-05-08 16:43 UTC, TempsRay commented on src/data/move.ts
> +  constructor(move: Moves = Moves.STOCKPILE) {
Personally I think it'd make much more sense to have the input be just a boolean and then pass in either true or false from the moves declaration
```ts
export class StockpileStatChangeAttr extends StatChange Attr {
  private gainStats: boolean;
  // code implementation
}
```

2024-05-10 04:09 UTC, mareksison commented on src/data/move.ts
> +    if (move === Moves.SPIT_UP || move === Moves.SWALLOW){
I pass the "id" straight into the Attr though, and I don't see how to access the move through the Attr

2024-05-10 04:10 UTC, mareksison commented on src/data/move.ts
> +      this.levels = stock * -1;
got it, added comments

2024-05-10 04:13 UTC, mareksison commented on src/data/move.ts
> +    if (!super.apply(user, target, move, args) || willFail)
I tried making failOnOverlap true, but it made the move fail on times when I dont want it to fail, so I think I'll just move willFail to the front.

2024-05-10 04:13 UTC, mareksison commented on src/data/move.ts
> +  constructor(move: Moves = Moves.STOCKPILE) {
you know actually this makes sense, I'll do that

2024-05-15 04:58 UTC, mareksison commented
@TempsRay hi! just following up on this

2024-05-15 14:54 UTC, TempsRay commented on src/data/move.ts
> +export class SwallowHealAttr extends HealAttr {
New standards dictate documentation on new classes so please add those. You can take a look at recent PRs for how they should be handled

2024-05-15 14:56 UTC, TempsRay commented on src/data/move.ts
> +    super([ BattleStat.DEF, BattleStat.SPDEF ], 1, true);
shouldn't this line be using gainStats rather than always true?
`super([ BattleStat.DEF, BattleStat.SPDEF ], 1, gainStats);`

2024-05-15 15:00 UTC, TempsRay commented on src/data/move.ts
> +        break;
nit: can just merge the `case 3` with the default since they should have the same functionality

2024-05-15 15:02 UTC, TempsRay commented on src/data/move.ts
> +    user.scene.queueMessage(getPokemonMessage(target, `\nstockpiled ${stock+1}.`));
All queued messages should be localized https://github.com/pagefaultgames/pokerogue/blob/main/src/locales/en/ability-trigger.ts

2024-05-15 15:02 UTC, TempsRay commented on src/data/move.ts
> +      .partial(),
Can remove all the `.partial()`'s here if you implemented them

2024-05-15 15:03 UTC, TempsRay requested changes
Add docs and address comments

2024-05-15 16:23 UTC, mareksison commented on src/data/move.ts
> +    super([ BattleStat.DEF, BattleStat.SPDEF ], 1, true);
gainStats is to show if the move will gainStats or loseStats, so Swallow or SpitUp for example would have it at false.

2024-05-15 16:25 UTC, mareksison commented on src/data/move.ts
> +        (this.selfTarget ? user : target).removeTag(tagType);
ah my bad, this has been rectified

2024-05-15 17:13 UTC, mareksison commented on src/data/move.ts
> +    user.scene.queueMessage(getPokemonMessage(target, `\nstockpiled ${stock+1}.`));
Is there another guide for the localisation? I cant quite see how it's used in the move.ts file

2024-05-15 18:21 UTC, mareksison commented
> Add docs and address comments

Added documentation and localisation, removed "partial," and fixed the switch statement in StockpileAttr

2024-05-16 17:09 UTC, mareksison commented
Merged conflicts

2024-05-19 14:02 UTC, bennybroseph requested changes
Could we get a video of this move working in game? Would also be a good idea to resync your branch as many changes have been made since this was requested. 

Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

2024-05-22 08:46 UTC, mareksison commented
Added more detail to documentation and attaching videos that show the moves work as intended

https://github.com/pagefaultgames/pokerogue/assets/1327797/9d79367a-89e1-476f-8918-f990b89bb48b
https://github.com/pagefaultgames/pokerogue/assets/1327797/2ca41ab4-b1cb-4c92-b4b4-2572e6413abd

2024-05-29 14:18 UTC, mareksison commented
Merged once again with latest

2024-06-03 00:08 UTC, flx-sta approved these changes
I've tested it on my system.
replace `MOVESET_OVERRIDE`  in `override.ts` to test it:

```ts
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.STOCKPILE, Moves.SWALLOW, Moves.SPIT_UP];
```

Seems to work as expected.
@mareksison please resolve the merge conflicts

2024-06-03 03:35 UTC, mareksison commented
@flx-sta resolved merge conflicts

2024-06-03 05:02 UTC, flx-sta commented on src/data/move.ts
> +    if (!super.apply(user, target, move, args))
You could return the condition instead of using the if

2024-06-03 05:03 UTC, flx-sta commented on src/data/move.ts
> +    if (h > -1)
To quote @XGSleepWalker :
> seems a bit hacky

2024-06-03 05:20 UTC, mareksison commented on src/data/move.ts
> +    if (h > -1)
I will need to be able to change the healRatio though depending on the number of stockpiles. How would you suggest I do this?

2024-06-03 05:20 UTC, mareksison commented on src/data/move.ts
> +    if (!super.apply(user, target, move, args))
Alright, will fix in the next merge

2024-06-03 06:10 UTC, flx-sta commented on src/data/move.ts
> +    if (h > -1)
I’d have to guess tbh..
1 thing for sure that’s bad is using a `get` prefixed method to change the value of the field. That’s not expected and cause unedited side effects.

2024-06-03 06:57 UTC, mareksison commented on src/data/move.ts
> +    if (h > -1)
Yeah, I see that. I was able to find a solution and removed the getHealRatio method completely (since I really made it just for this)

2024-06-04 05:21 UTC, mareksison commented on src/data/move.ts
> +    if (h > -1)
@flx-sta can you check? This should be good now

2024-06-04 19:05 UTC, flx-sta requested changes

2024-06-04 19:05 UTC, flx-sta commented on src/data/move.ts
> +
```suggestion
function getStockpiles(user: Pokemon) : integer {
  const stockpiles = [BattlerTagType.STOCKPILE_ONE, BattlerTagType.STOCKPILE_TWO, BattlerTagType.STOCKPILE_THREE];

  return stockpiles.filter((stockpile) => user.getTag(stockpile)).length;
}
```

2024-06-04 19:05 UTC, flx-sta commented
You should mark some conversations as `resolved` if you fixed that

2024-06-06 06:45 UTC, mareksison commented on src/data/move.ts
> +
ooooh, I didn't realise that's how the getTag function works, that makes a lot of sense. Making the necessary change now

2024-06-06 07:02 UTC, mareksison commented
Thanks for the reminder @flx-sta. I resolved the conversatiions and made the necessary changes as well

2024-06-06 14:57 UTC, flx-sta commented
Still LGTM ✅ 


https://github.com/pagefaultgames/pokerogue/assets/50131232/d69c5163-a824-4c66-8892-8dc8c92d957a

2024-06-10 21:01 UTC, zacharied commented
I hate to be that guy, but the behavior here is incorrect. To reproduce the problem:

* Use Amnesia to bring SpDef up to +6.
* Use Stockpile; note that it does not increase the SpDef stat
* Use Swallow

You will see that upon Swallowing, the user loses a stage of SpDef. This should not be happening, since Swallow/Spit Up are only supposed to undo the stat changes that were provided by uses of Stockpile ([source](https://bulbapedia.bulbagarden.net/wiki/Stockpile_(move))).

https://github.com/pagefaultgames/pokerogue/assets/6374275/7e4e4349-18da-4faa-bd35-f7c93cf181de

Expected behavior would be for only Def to get decreased here.

2024-06-11 18:20 UTC, mareksison commented
> I hate to be that guy, but the behavior here is incorrect. To reproduce the problem:
> 
> * Use Amnesia to bring SpDef up to +6.
> * Use Stockpile; note that it does not increase the SpDef stat
> * Use Swallow
> 
> You will see that upon Swallowing, the user loses a stage of SpDef. This should not be happening, since Swallow/Spit Up are only supposed to undo the stat changes that were provided by uses of Stockpile ([source](https://bulbapedia.bulbagarden.net/wiki/Stockpile_(move))).
> 
>  firefox_oCY5Tn7IUZ.mp4 
> Expected behavior would be for only Def to get decreased by Swallow.

Good point. Will fix this issue. I think for this the best course of action is to put variable son the Pokemon itself to act as trackers. That's what I will be working on

2024-06-15 21:13 UTC, mareksison commented
@zacharied I think I fixed the issue. Initial testing shows that it should be working as normal. Please do check. I will test some more when I wake up.

2024-06-16 04:09 UTC, zacharied commented
Why not just have a single Stockpile BattlerTag that tracks the stack count, Def, and SpDef increase? I'm not a huge fan of having to add the `stockpileStats` field to the Pokemon class when that's already what a BattlerTag is supposed to accomplish.

2024-06-17 16:28 UTC, mareksison commented
> Why not just have a single Stockpile BattlerTag that tracks the stack count, Def, and SpDef increase? I'm not a huge fan of having to add the `stockpileStats` field to the Pokemon class when that's already what a BattlerTag is supposed to accomplish. It would also save you from having to mess with `StatChangePhase`. Just my personal recommendation.

So, it would be like having 9 tags? 3 for just stockpile, 3 for knowing that defense was buffed, and 3 for knowing spdef was buffed?

I just realised that "getTargetBenefitScore" in StatChangeAttr does give me the feedback I need, which I needed "StatChangePhase" for, so I can move the check in that level at least, maybe in "StockpileStatChangeAttr"'s own "getTargetBenefitScore"

2024-06-17 17:41 UTC, zacharied commented
> So, it would be like having 9 tags? 3 for just stockpile, 3 for knowing that defense was buffed, and 3 for knowing spdef was buffed?

The idea I have in mind would only require one tag -- just store a `stackCount`, `defIncrease`, and `spDefIncrease` as variables of the tag. Then, in the tag's `onAdd` / `onOverlap` you can just check if the user's Def/SpDef is below +6, and add to the `defIncrease`/`spDefIncrease`. Once the user removes their stockpiles, you can just check `defIncrease` to see how much you need to decrease their Def by, and likewise for SpDef.

You can see `HighestStatBoostingTag` as an example of a tag that stores and manipulates its own data. 

> I just realised that "getTargetBenefitScore" in StatChangeAttr does give me the feedback I need, which I needed "StatChangePhase" for, so I can move the check in that level at least, maybe in "StockpileStatChangeAttr"'s own "getTargetBenefitScore"

Definitely don't do this, `getTargetBenefitScore` is used by the AI for calculating which move to use, and will get run regardless of whether the move is actually used in battle or not. You'll probably notice some bugs pretty quick if you try.

2024-06-19 23:03 UTC, zacharied commented
@mareksison, I got curious and tried out the approach I described on my own remote. You can see the changes [here](https://github.com/zacharied/pokerogue/commit/ee92c92e3634cd4156f6317ff2a01c98019dd971). It's basically completely implemented besides AI and localization.

IMO it ends up being way cleaner. It avoids adding state to the Pokemon class and requires no modification to phases, which greatly reduces our chances of bugs. It's also just much less code in general. Let me know your thoughts when you have a moment.

2024-06-25 02:34 UTC, mareksison commented
> @mareksison, I got curious and tried out the approach I described on my own remote. You can see the changes [here](https://github.com/zacharied/pokerogue/commit/ee92c92e3634cd4156f6317ff2a01c98019dd971). It's basically completely implemented besides AI and localization.
> 
> IMO it ends up being way cleaner. It avoids adding state to the Pokemon class and requires no modification to phases, which greatly reduces our chances of bugs. It's also just much less code in general. Let me know your thoughts when you have a moment.

Alright, will take a look and implement them

2024-06-26 04:23 UTC, mareksison commented
> @mareksison, I got curious and tried out the approach I described on my own remote. You can see the changes [here](https://github.com/zacharied/pokerogue/commit/ee92c92e3634cd4156f6317ff2a01c98019dd971). It's basically completely implemented besides AI and localization.
> 
> IMO it ends up being way cleaner. It avoids adding state to the Pokemon class and requires no modification to phases, which greatly reduces our chances of bugs. It's also just much less code in general. Let me know your thoughts when you have a moment.

I see, I understand now, you can actually just add the variable straight to the tag. Didn't know that was possible when I started this. Thanks. Implementing now.

2024-06-26 10:11 UTC, mareksison commented
https://github.com/pagefaultgames/pokerogue/assets/1327797/099d12de-3180-470e-98d7-23c921472b88

Tested and merged into PR

2024-07-04 03:36 UTC, mareksison commented
@zacharied hello, this should be ready for checking again

2024-07-10 17:58 UTC, mcmontag commented
@mareksison Not to add a cook to this kitchen, but I took a stab at implementing Stockpile/Spit Up/Swallow as a way to familiarize myself with the codebase yesterday.  Having done that, I just wanted to note that this PR doesn't properly implement stat change tracking when adding and removing stacks.  Most of it centers around Contrary, but there may be other problematic cases, as well.

More specifically, removing stacks should apply -1 DEF and/or -1 SPDEF (before taking abilities into account) for each stack that *successfully changed* DEF or SPDEF, respectively.

The stacking logic in this PR simply checks that DEF/SPDEF are below +6 before raising them (and counting them as successful).

But consider (as just one example) a pokemon with Contrary and -6 DEF (or SPDEF).  With your logic, using Stockpile would not *actually* change their DEF, but if their DEF is then raised to at least -5 before removing stacks, the removal will incorrectly lower DEF by 1 stage (well, raise it because of Contrary, but the point is that it shouldn't try to adjust DEF at all).

My implementation (https://github.com/mcmontag/pokerogue/commit/c16b1610c) happens to otherwise be almost identical to yours (though I didn't get around to localization), and handles stat change tracking by adding an optional callback to the constructor of `StatChangePhase`, which the tag utilizes.

Thoughts on this?  I'd be happy to make a PR to your branch with this logic, if you think it makes sense to go that route.  When I was working through it (and unaware of this PR), my assumption was that hooking into `StatChangePhase` is the only way to be certain that a stat did in fact change, but I could be missing something.

2024-07-11 09:05 UTC, mareksison commented
> @mareksison Not to add a cook to this kitchen, but I took a stab at implementing Stockpile/Spit Up/Swallow as a way to familiarize myself with the codebase yesterday. Having done that, I just wanted to note that this PR doesn't properly implement stat change tracking when adding and removing stacks. Most of it centers around Contrary, but there may be other problematic cases, as well.
> 
> More specifically, removing stacks should apply -1 DEF and/or -1 SPDEF (before taking abilities into account) for each stack that _successfully changed_ DEF or SPDEF, respectively.
> 
> The stacking logic in this PR simply checks that DEF/SPDEF are below +6 before raising them (and counting them as successful).
> 
> But consider (as just one example) a pokemon with Contrary and -6 DEF (or SPDEF). With your logic, using Stockpile would not _actually_ change their DEF, but if their DEF is then raised to at least -5 before removing stacks, the removal will incorrectly lower DEF by 1 stage (well, raise it because of Contrary, but the point is that it shouldn't try to adjust DEF at all).
> 
> My implementation ([mcmontag@c16b1610c](https://github.com/mcmontag/pokerogue/commit/c16b1610c)) happens to otherwise be almost identical to yours (though I didn't get around to localization), and handles stat change tracking by adding an optional callback to the constructor of `StatChangePhase`, which the tag utilizes.
> 
> Thoughts on this? I'd be happy to make a PR to your branch with this logic, if you think it makes sense to go that route. When I was working through it (and unaware of this PR), my assumption was that hooking into `StatChangePhase` is the only way to be certain that a stat did in fact change, but I could be missing something.

I get it. I think it would make sense if you PR into my branch so that we can update this PR

2024-07-19 16:11 UTC, flx-sta commented
@mareksison since you are still looking into the implementation I'd ask you to mark this PR as draft

2024-07-24 06:28 UTC, Tempo-anon commented
Closing due to merge conflicts and https://github.com/pagefaultgames/pokerogue/pull/2960 was merged in

2024-07-24 06:28 UTC, closed without merging