[Hotfix] Allow Fake Out to be used at the start of every wave again
pagefaultgames/pokerogue pull request #4105
Opened 2024-09-08 08:07 UTC by DayKev

## What are the changes the user will see?
Fake Out and First Impression can be used at the start of every wave.

## Why am I making these changes?
Request from @damocleas due to player feedback.

## What are the changes from a developer perspective?
The active Pokémon's turn count is set to 1 at the start of every wave, so first-turn-only moves won't fail.

## How to test the changes?
`npm run test fake_out`

## Checklist
- ~[ ] **I'm using `beta` as my base branch**~
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- ~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

2024-09-08 08:17 UTC, innerthunder approved these changes
lgtm 🚀

2024-09-08 14:59 UTC, damocleas approved these changes

2024-09-08 17:23 UTC, damocleas commented
Please test with mat block too

2024-09-08 20:57 UTC, DayKev commented
Mat Block also works.

2024-09-09 02:24 UTC, Tempo-anon requested changes

2024-09-09 02:24 UTC, Tempo-anon commented on src/phases/battle-end-phase.ts
> +     * Allow Fake Out and First Impression to be used at the start of every wild battle
If you just want to make a change to two specific moves wouldn't this make more sense as a move attribute rather than doing something that might cause unintended behavior by manually changing a Pokemon's turns out?

2024-09-09 02:46 UTC, DayKev commented
![image](https://github.com/user-attachments/assets/06b15ee6-050f-4648-896a-1c9305ff82f3)

2024-09-09 02:46 UTC, closed without merging