[Bug] Obstruct et al no longer protect against status moves
pagefaultgames/pokerogue pull request #4106
Opened 2024-09-08 10:39 UTC by DayKev

## What are the changes the user will see?
[Burning Bulwark](https://dex.pokemonshowdown.com/moves/burningbulwark), [King's Shield](https://dex.pokemonshowdown.com/moves/kingsshield), [Obstruct](https://dex.pokemonshowdown.com/moves/obstruct) and [Silk Trap](https://dex.pokemonshowdown.com/moves/silktrap) no longer protect against status moves.

## Why am I making these changes?
These moves are not supposed to protect against status moves but currently they do.

## What are the changes from a developer perspective?
A new `BattlerTag` class `DamageProtectedTag` was created. `ContactStatStageChangeProtectedTag` and `ContactBurnProtectedTag` now inherit from that instead of `ProtectedTag`, and the protection check in `MoveEffectPhase` was updated to account for the change.

## How to test the changes?
`npm run test obstruct`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- ~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

2024-09-08 19:16 UTC, ben-lear commented on src/test/moves/obstruct.test.ts
> +import { Stat } from "#app/enums/stat.js";
nit: import .js

2024-09-08 19:17 UTC, ben-lear requested changes

2024-09-08 19:17 UTC, ben-lear commented on src/test/moves/obstruct.test.ts
> +import { Stat } from "#app/enums/stat.js";
```suggestion
import { Stat } from "#app/enums/stat";
```

2024-09-08 20:54 UTC, DayKev commented on src/test/moves/obstruct.test.ts
> +import { Stat } from "#app/enums/stat.js";
:despair:

2024-09-08 20:59 UTC, innerthunder approved these changes
lgtm, though maybe a better name for the new tag would be `AttackMoveProtectedTag` (or just `AttackProtectedTag`)?

2024-09-10 16:17 UTC, schmidtc1 approved these changes

2024-09-10 17:01 UTC, Tempo-anon requested changes

2024-09-10 17:01 UTC, Tempo-anon commented on src/data/battler-tags.ts
> +export class DamageProtectedTag extends ProtectedTag {}
Can we get some tsdoc on these new classes

2024-09-10 17:01 UTC, Tempo-anon commented on src/data/battler-tags.ts
> +export class ContactStatStageChangeProtectedTag extends DamageProtectedTag {
Each of these classes should have a tsdoc that explains what they're doing and which moves they're associated with

2024-09-12 01:31 UTC, Tempo-anon approved these changes
Baneful bunker is somehow different. Gamefreak why.

2024-09-12 01:31 UTC, merged