[Hotfix] Fix reloads causing lures to refresh, and fix game version
pagefaultgames/pokerogue pull request #4114
Opened 2024-09-08 17:51 UTC by PigeonBar

Note: This is copied from #4109 in order to re-point it to the main branch cleanly.

## What are the changes the user will see?
Fixes #4100, so reloading the game will no longer cause lures to refresh their durations.

May also introduce other fixes and/or side effects that I am not aware of.

## Why am I making these changes?

A fix for #4100.

## What are the changes from a developer perspective?

The version in `package.json` and `package-lock.json` is now updated to the game's current version of v1.0.5. This means that all game data saved during v1.0.5 will be correctly labelled as v1.0.5, so `version-converter.ts` will no longer treat them as v1.0.4 data and will no longer interfere with them.

`version-converter.ts` is also revised to automatically use the latest version in `package.json`.

## Screenshots/Videos

### Before the changes

https://github.com/user-attachments/assets/d758cecf-c883-436c-a9b3-cdecc208f06b

After the reload, the lure's duration gets reset to 10.

### After the changes

https://github.com/user-attachments/assets/864ab28f-05f7-4682-96a2-edf8c59e7f0a

After the reload, the lure's duration stays at 7.

## How to test the changes?

1. While playing a run, obtain a lure.
2. Advance to the next wave to count down the lure's duration.
3. Reload the session.
4. The lure's duration should not refresh.

## Checklist
- ~~[ ] **I'm using `beta` as my base branch**~~
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- ~~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-09-08 19:37 UTC, xsn34kzx approved these changes

2024-09-08 19:38 UTC, ben-lear approved these changes

2024-09-08 19:38 UTC, CodeTappert approved these changes

2024-09-08 19:49 UTC, torranx approved these changes

2024-09-08 21:09 UTC, DayKev approved these changes

2024-09-08 21:19 UTC, flx-sta approved these changes

2024-09-08 21:22 UTC, CodeTappert approved these changes

2024-09-09 03:01 UTC, PigeonBar commented
Caution: It has been discovered that this PR could cause the client to be unable to connect to the server due to a version mismatch, so make sure this does NOT get merged until the senior devs work out a safer way to update versions or a safer approach altogether to fix this bug.
Source: https://discord.com/channels/1125469663833370665/1281859363899838607/1282427810111029268

2024-09-09 16:53 UTC, Tempo-anon requested changes
Changing version numbers is risky. Going to put a blocker on this for now.

2024-09-12 01:03 UTC, Tempo-anon commented
Closing because this is no longer needed

2024-09-12 01:03 UTC, closed without merging