[Localization] Localization batch - Will
pagefaultgames/pokerogue pull request #4127
Opened 2024-09-09 11:04 UTC by Adri1

## What are the changes the user will see?
New translated text

## Why am I making these changes?
To have these texts translated

## What are the changes from a developer perspective?
None, just translated text

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?

2024-09-09 11:10 UTC, sodaMelon commented on src/locales/ko/battler-tags.json
> +  "tarShotOnAdd": "{{pokemonNameWithAffix}} became weaker to fire!"
```suggestion
  "tarShotOnAdd": "{{pokemonNameWithAffix}}[[는]] 불꽃에 약해졌다!"
```
![image](https://github.com/user-attachments/assets/54e8360b-f6dc-4037-99ba-b281bdb111da)

2024-09-09 11:11 UTC, EnochG1 commented on src/locales/ko/battler-tags.json
> +  "tarShotOnAdd": "{{pokemonNameWithAffix}} became weaker to fire!"
```suggestion
  "tarShotOnAdd": "{{pokemonNameWithAffix}}[[는]]불꽃에 약해졌다!"
```

2024-09-09 11:41 UTC, josericardo-fo commented on src/locales/pt_BR/battler-tags.json
> +  "tarShotOnAdd": "{{pokemonNameWithAffix}} became weaker to fire!"
```suggestion
  "tarShotOnAdd": "{{pokemonNameWithAffix}} tornou-se mais fraco ao fogo!"
```

2024-09-09 11:42 UTC, Chapybara-jp commented on src/locales/ja/battler-tags.json
> +  "tarShotOnAdd": "{{pokemonNameWithAffix}} became weaker to fire!"
```suggestion
  "tarShotOnAdd": "{{pokemonNameWithAffix}}は　ほのおに　弱くなった！"
```

2024-09-09 12:58 UTC, AsdarDevelops requested changes

2024-09-09 12:58 UTC, AsdarDevelops commented on src/locales/es/battler-tags.json
> +  "disabledLapse": "¡El movimiento {{moveName}}\nde {{pokemonNameWithAffix}} ya no está anulado!",
```suggestion
  "disabledLapse": "¡El movimiento {{moveName}} de {{pokemonNameWithAffix}} ya no está anulado!",
```

I don't want to risk overflowing to 3rd line here

2024-09-09 13:19 UTC, NicusPulcis approved these changes
italian localization done (added a \n to make sure it doesnt exceed the border limits)

2024-09-09 13:19 UTC, NicusPulcis commented on src/locales/it/battler-tags.json
> +  "tarShotOnAdd": "{{pokemonNameWithAffix}} became weaker to fire!"
```suggestion
  "tarShotOnAdd": "{{pokemonNameWithAffix}} è diventato vulnerabile\nal tipo Fuoco!"
```

2024-09-09 13:29 UTC, CodeTappert commented on src/locales/de/battler-tags.json
> +  "tarShotOnAdd": "{{pokemonNameWithAffix}} became weaker to fire!"
```suggestion
  "tarShotOnAdd": "{{pokemonNameWithAffix}} ist nun schwach gegenüber Feuer-Attacken!"
```

2024-09-09 20:37 UTC, josericardo-fo commented on src/locales/pt_BR/fight-ui-handler.json
> +  "teraHover": "{{type}} Terastallized"
```suggestion
  "teraHover": "Terastalizado {{type}}"
```

2024-09-09 22:46 UTC, DanStevensonx reviewed
Suggested the Spanish translation. Line 7 of fight-ui-handler.json didn't have a translation Corpus, so I translated at my own discretion.

2024-09-09 22:46 UTC, DanStevensonx commented on src/locales/es/move-trigger.json
> +  "afterYou": "{{pokemonName}} took the kind offer!"
```suggestion
  "afterYou": "¡{{pokemonName}} ha decidido aprovechar la oportunidad!"
```

2024-09-09 22:46 UTC, DanStevensonx commented on src/locales/es/fight-ui-handler.json
> +  "teraHover": "{{type}} Terastallized"
```suggestion
  "teraHover": "{{type}} se teracristalizó"
```

2024-09-09 22:53 UTC, EnochG1 commented on src/locales/ko/fight-ui-handler.json
> +  "teraHover": "{{type}} Terastallized"
```suggestion
  "teraHover": "{{type}} 테라스탈"
```

2024-09-09 22:53 UTC, EnochG1 commented on src/locales/ko/move-trigger.json
> +  "afterYou": "{{pokemonName}} took the kind offer!"
```suggestion
  "afterYou": "{{pokemonName}}[[는]]\n배려를 받아들이기로 했다!"
```

2024-09-10 13:38 UTC, NicusPulcis submitted a review, later dismissed
fixing the terastilized text in italian

2024-09-10 16:05 UTC, josericardo-fo commented on src/locales/pt_BR/move-trigger.json
> +  "afterYou": "{{pokemonName}} took the kind offer!"
```suggestion
  "afterYou": "{{pokemonName}} aceitou a gentil oferta!"
```

2024-09-10 16:15 UTC, EnochG1 commented on src/locales/ja/fight-ui-handler.json
> +  "teraHover": "{{type}} Terastallized"
```suggestion
  "teraHover": "{{type}}テラスタル"
```

2024-09-10 23:08 UTC, Chapybara-jp submitted a review, later dismissed

2024-09-11 03:17 UTC, 40chyan reviewed
zn tera

2024-09-11 03:17 UTC, 40chyan commented on src/locales/zh_CN/fight-ui-handler.json
> +  "teraHover": "{{type}} Terastallized"
```suggestion
  "teraHover": "{{type}} 太晶化"
```

2024-09-11 03:17 UTC, 40chyan commented on src/locales/zh_TW/fight-ui-handler.json
> +  "teraHover": "{{type}} Terastallized"
```suggestion
  "teraHover": "{{type}} 太晶化"
```

2024-09-11 20:26 UTC, SangaraSorama approved these changes

2024-09-11 20:40 UTC, CodeTappert approved these changes

2024-09-11 20:45 UTC, DayKev approved these changes

2024-09-11 20:46 UTC, merged