[Bug] Fix for Roost Grounds the User Rather than Removing Flying Typing#3984
pagefaultgames/pokerogue pull request #4164
Opened 2024-09-11 03:40 UTC by PrabbyDD

## What are the changes the user will see?
Roost will now work as listed on bulbapedia for the cases listed in the bug report and more. This includes:
Roost correctly removing flying for a turn instead of immediately grounding a pokemon. 
Roost will only ground a pokemon if it was ungrounded solely due to being flying type
Roost on a pure flying type will change it to normal until end of turn.
Roost on a dual type will change it to the non flying type until end of turn
Roost on a pokemon that has used burn up will make it typeless until end of turn, then revert to flying
Roost on a pokemon afflicted with trick or treat/forests curse will change types faithfully to the base game
Roost on a non flying type pokemon will not change its type. 

## Why am I making these changes?
bugfix

## What are the changes from a developer perspective?
Added new tag for roost called RoostedTag, added BurnUpTag, added test cases in roost.test.ts, filled out 
BattleTag class for RoostedTag. 

### Screenshots/Videos

https://github.com/user-attachments/assets/94da4050-2d92-4c1e-9bb9-999757114d16

https://github.com/user-attachments/assets/3ad8eb42-cc9b-4cba-99fd-66c255c06090

https://github.com/user-attachments/assets/732ce9fa-4a83-476d-a118-45efd05c0576

https://github.com/user-attachments/assets/b57546fa-0a66-4d58-a815-5f25f4a7aa0c

https://github.com/user-attachments/assets/9d8a96b1-a896-4c78-9d8a-12e4d1395969

## How to test the changes?
You can run the roost.test.ts file using npm test roost
You can also change the override file to any roost related test cases you wish. 

## Checklist
- [X ] **I'm using `beta` as my base branch**
- [X ] There is no overlap with another PR?
- [X ] The PR is self-contained and cannot be split into smaller PRs?
- [X ] Have I provided a clear explanation of the changes?
- [X ] Have I considered writing automated tests for the issue?
- [ X] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [X ] Have I tested the changes (manually)?
    - [X ] Are all unit tests still passing? (`npm run test`)
- [X ] Are the changes visual?
  - [X ] Have I provided screenshots/videos of the changes?

2024-09-11 03:50 UTC, PrabbyDD commented
Am fixing merge conflicts and checking if tests still pass (including the one i added)...

2024-09-11 04:29 UTC, PrabbyDD commented
Some issues i suppose. Will try and fix tomorrow

2024-09-11 05:16 UTC, innerthunder requested changes

2024-09-11 05:16 UTC, innerthunder commented on src/data/battler-tags.ts
> +    return new BurnedUpTag(tagType, BattlerTagLapseType.CUSTOM, sourceMove);
```suggestion
    return new RoostedTag();
  case BattlerTagType.BURNED_UP:
    return new BurnedUpTag();
```
To go along with other suggestions...

Also, doesn't Double Shock also need a tag in this vein?

2024-09-11 05:16 UTC, innerthunder commented on src/test/moves/roost.test.ts
> +    game.override.enemyMoveset([Moves.EARTHQUAKE, Moves.EARTHQUAKE, Moves.EARTHQUAKE, Moves.EARTHQUAKE]);
```suggestion
    game.override.enemyMoveset(Moves.EARTHQUAKE);
```
A recent change to moveset overrides makes this so that the enemy's only move is Earthquake

2024-09-11 05:16 UTC, innerthunder commented on src/test/moves/roost.test.ts
> +      let playerPokemonTypes = playerPokemon.getTypes();
```suggestion
      const playerPokemon = game.scene.getPlayerPokemon()!;
      const playerPokemonStartingHP = playerPokemon.hp;
      let playerPokemonTypes = playerPokemon.getTypes();
      
      game.move.select(Moves.ROOST);
```
This avoids potential desync issues. You're currently collecting the player's types and starting HP as the turn is progressing (this also applies to the other tests)

2024-09-11 22:53 UTC, PrabbyDD commented on src/data/battler-tags.ts
> +    return new BurnedUpTag(tagType, BattlerTagLapseType.CUSTOM, sourceMove);
Ill take a peek at this, hopefully its the same as what i did for burn up, will need another test case tho

2024-09-11 22:53 UTC, PrabbyDD commented on src/test/moves/roost.test.ts
> +      let playerPokemonTypes = playerPokemon.getTypes();
Thanks for all the help!

2024-09-11 23:36 UTC, PrabbyDD commented
Also I tried linking the issue by putting the number in my description, how did you do it in the comments? @innerthunder

2024-09-11 23:47 UTC, innerthunder commented
> Also I tried linking the issue by putting the number in my description, how did you do it in the comments? @innerthunder

Not related to the comments, I can just link them manually as a junior dev :)

2024-09-11 23:51 UTC, PrabbyDD commented
I see

> > Also I tried linking the issue by putting the number in my description, how did you do it in the comments? @innerthunder
> 
> Not related to the comments, I can just link them manually as a junior dev :)

I see lol. Also when it says my branch is out of date with the branch, does that mean i need to update it before the PR?

2024-09-12 17:11 UTC, PrabbyDD commented on src/data/battler-tags.ts
> +
I suppose I can merge them into a single class.

2024-09-12 19:14 UTC, innerthunder approved these changes

2024-09-12 19:27 UTC, merged