[Localization] ME translations
pagefaultgames/pokerogue pull request #4183
Opened 2024-09-11 20:51 UTC by Adri1

## What are the changes the user will see?
Translated ME

## Why am I making these changes?
To have ME translated

## What are the changes from a developer perspective?
None

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?

2024-09-11 22:34 UTC, DanStevensonx reviewed
Translated the battle.json before going to bed

2024-09-11 22:34 UTC, DanStevensonx commented on src/locales/es/battle.json
> +  "playerFled": "You fled from the {{pokemonName}}!",
```suggestion
  "pokemonObtained": "¡Has recibido a {{pokemonName}}!",
  "pokemonBrokeFree": "¡Oh, no!\n¡El Pokémon se ha escapado!",
  "pokemonFled": "¡El {{pokemonName}} salvaje ha huido!",
  "playerFled": "¡Huiste del {{pokemonName}}!",
```

2024-09-11 22:34 UTC, DanStevensonx commented on src/locales/es/battle.json
> +  "noPokeballMysteryEncounter": "You aren't able to\ncatch this Pokémon!",
```suggestion
  "noPokeballMysteryEncounter": "¡No puedes capturar este Pokémon!",
```

2024-09-11 22:34 UTC, DanStevensonx commented on src/locales/es/battle.json
> +  "mysteryEncounterAppeared": "What's this?"
```suggestion
  "mysteryEncounterAppeared": "¿Que es esto?"
```

2024-09-11 23:33 UTC, EnochG1 reviewed
Partial Korean

2024-09-11 23:33 UTC, EnochG1 commented on src/locales/ko/battle.json
> +  "playerFled": "You fled from the {{pokemonName}}!",
```suggestion
  "pokemonObtained": "{{pokemonName}}[[를]] 손에 넣었다!",
  "pokemonBrokeFree": "안 돼!\n포켓몬이 볼에서 나와 버렸다!",
  "pokemonFled": "야생 {{pokemonName}}[[는]]\n도망쳤다!",
  "playerFled": "{{pokemonName}}[[로]]부터 도망쳤다!",
```

2024-09-11 23:33 UTC, EnochG1 commented on src/locales/ko/battle.json
> +  "noPokeballMysteryEncounter": "You aren't able to\ncatch this Pokémon!",
```suggestion
  "noPokeballMysteryEncounter": "이 포켓몬은 잡을 수 없습니다!",
```

2024-09-11 23:33 UTC, EnochG1 commented on src/locales/ko/mystery-encounter-messages.json
> +  "cancel_option": "Return to encounter option select."
```suggestion
  "paid_money": "₽{{amount, number}}[[를]] 를 지불했다.",
  "receive_money": "₽{{amount, number}}[[를]] 받았다!",
  "affects_pokedex": "Affects Pokédex Data",
  "cancel_option": "Return to encounter option select."
```

2024-09-11 23:33 UTC, EnochG1 commented on src/locales/ko/party-ui-handler.json
> +  "SELECT": "Select",
```suggestion
  "SELECT": "선택",
```

2024-09-11 23:48 UTC, EnochG1 commented on src/locales/ko/trainer-titles.json
> +  "the_winstrates": "The Winstrates'"
```suggestion
  "the_winstrates": "연승가족'"
```

2024-09-11 23:48 UTC, EnochG1 commented on src/locales/ko/trainer-names.json
> +  "bug_type_superfan": "Bug-Type Superfan"
```suggestion
  "buck": "맥",
  "cheryl": "모미",
  "marley": "미",
  "mira": "미루",
  "riley": "신용우",
  "victor": "상우",
  "victoria": "수혜",
  "vivi": "추희",
  "vicky": "영아",
  "vito": "철준",
  "bug_type_superfan": "벌레타입 마니아"
```

2024-09-12 00:33 UTC, sodaMelon commented
It seems like a lot of work to suggest each one here. 🤔 
If someone have easy way, please share them

2024-09-12 01:26 UTC, Adri1 commented
> It seems like a lot of work to suggest each one here. 🤔 If someone have easy way, please share them

Don't you have the power to make edits directliy from the File changed tab?
If not, maybe try to fork my branch and then, create PR to this branch with your translations

2024-09-12 12:22 UTC, sodaMelon commented
> > It seems like a lot of work to suggest each one here. 🤔 If someone have easy way, please share them
> 
> Don't you have the power to make edits directliy from the File changed tab? If not, maybe try to fork my branch and then, create PR to this branch with your translations

I made [korean team repository](https://github.com/pokerogue-KO/ME-KOREAN) for ME  localization. When it's done, I'll make PR in [your repository](https://github.com/Adri1/pokerogue/tree/mystery-encounters-translations).

2024-09-12 12:24 UTC, sodaMelon commented
and here is [reference for ME Events](https://github.com/AsdarDevelops/PokeRogue-Events/issues)
it's better to check for story.

2024-09-12 12:54 UTC, Chapybara-jp commented on src/locales/ja/battle.json
> +  "mysteryEncounterAppeared": "What's this?"
```suggestion
  "mysteryEncounterAppeared": "あれ？"
```

2024-09-12 12:54 UTC, Chapybara-jp commented on src/locales/ja/bgm-name.json
> +  "mystery_encounter_gen_6_gts": "XY GTS"
```suggestion
  "mystery_encounter_weird_dream": "ポケダン空　じげんのとう",
  "mystery_encounter_fun_and_games": "ポケダン空　おやかたプクリン",
  "mystery_encounter_gen_5_gts": "BW　GTS",
  "mystery_encounter_gen_6_gts": "XY　GTS"
```

2024-09-12 14:12 UTC, DanStevensonx reviewed
Translated most from PokeCorpus, some of them weren't available so I had to translate them myself.

2024-09-12 14:19 UTC, NicusPulcis commented on src/locales/it/trainer-names.json
> +  "bug_type_superfan": "Bug-Type Superfan"
```suggestion
  "buck": "Chicco",
  "cheryl": "Demetra",
  "marley": "Risetta",
  "mira": "Matilde",
  "riley": "Fabiolo",
  "victor": "Vincenzo",
  "victoria": "Vittoria",
  "vivi": "Viviana",
  "vicky": "Vicky",
  "vito": "Enrico",
  "bug_type_superfan": "Fan n.1 dei tipi Coleottero"
```

2024-09-12 14:19 UTC, NicusPulcis commented on src/locales/it/trainer-titles.json
> +  "the_winstrates": "The Winstrates'"
```suggestion
  "the_winstrates": "Famiglia Vinci'"
```

2024-09-12 14:21 UTC, NicusPulcis commented
added italian localizations for anything but dialogues

2024-09-12 14:29 UTC, sodaMelon commented on src/locales/es/dialogue.json
> +      "2": "... Goodbye."
```suggestion
      "1": "... Goodbye.",
      "2": "... Goodbye."
```
```suggestion
      "1": "...Adiós.",
      "2": "...Adiós."
```

2024-09-12 20:52 UTC, DanStevensonx reviewed
Translated to Spanish, needs checking.

2024-09-12 23:31 UTC, DanStevensonx reviewed
Traducido a Español

2024-09-12 23:31 UTC, DanStevensonx commented on src/locales/es/modifier-type.json
> +    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "Golden Bug Net", "description": "Imbues the owner with luck to find Bug Type Pokémon more often. Has a strange heft to it." }
```suggestion
    },

    "MYSTERY_ENCOUNTER_SHUCKLE_JUICE": { "name": "Jugo de Shuckle" },
    "MYSTERY_ENCOUNTER_BLACK_SLUDGE": { "name": "Lodo Negro", "description": "El hedor es tan poderoso que las tiendas solo te venderán artículos a un coste mucho más alto" },
    "MYSTERY_ENCOUNTER_MACHO_BRACE": { "name": "Brazal Firme", "description": "Derrotar a un Pokémon otorga al poseedor una pila de Brazal Firme. Cada pila aumenta ligeramente las estadísticas, con un bono extra al alcanzar el máximo de pilas." },
    "MYSTERY_ENCOUNTER_OLD_GATEAU": { "name": "Tarta Vieja", "description": "Aumenta las estadísticas de {{stats}} del portador en {{statValue}}." },
    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "Cazamariposas Dorado", "description": "Imbuye al dueño con suerte para encontrar Pokémon de tipo Bicho más a menudo. Tiene un peso extraño." }
```

2024-09-13 18:55 UTC, DanStevensonx reviewed
Corrected a typo and translated one file to Spanish

2024-09-13 18:55 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/absolute-avarice-dialogue.json
> +}
```suggestion
{
  "intro": "¡Un {{greedentName}} te embosca y roba las bayas de tu equipo!",
  "title": "Avaricia Absoluta",
  "description": "¡Un {{greedentName}} te ha tomado completamente por sorpresa y ahora todas tus bayas han desaparecido! El {{greedentName}} parece que está a punto de comérselas cuando se detiene para mirarte, interesado.",
  "query": "¿Qué harás?",
  "option": {
    "1": {
      "label": "Combatir",
      "tooltip": "(-) Batalla Difícil\n(+) Recompensas de su Alijo de Bayas",
      "selected": "El {{greedentName}} llena sus mejillas y se prepara para la batalla!",
      "boss_enraged": "¡El feroz amor de {{greedentName}} por la comida lo tiene enfurecido!",
      "food_stash": "¡Parece que el {{greedentName}} estaba protegiendo un enorme alijo de comida!$@s{item_fanfare}¡Cada Pokémon en tu grupo obtiene una {{foodReward}}!"
    },
    "2": {
      "label": "Razona con él",
      "tooltip": "(+) Recupera algunas bayas perdidas",
      "selected": "Tus súplicas conmueven al {{greedentName}}.$No te devuelve todas tus bayas, pero aún así te lanza algunas en tu dirección."
    },
    "3": {
      "label": "Déjalo quedarse con la comida",
      "tooltip": "(-) Perder todas las bayas\n(?) Le gustarás al {{greedentName}}",
      "selected": "El {{greedentName}} devora todas sus bayas en un instante!$Acariciando su estómago, te mira con aprecio.$Quizás podrías darle más bayas en tu aventura....$@s{level_up_fanfare}El {{greedentName}} quiere unirse a tu equipo!"
    }
  }
}
```

2024-09-13 22:08 UTC, DanStevensonx reviewed
Translated to Spanish

2024-09-13 22:08 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/berries-abound-dialogue.json
> +}
```suggestion
{
  "intro": "¡Hay un gran arbusto de bayas cerca de ese Pokémon!",
  "title": "Bayas Abundantes",
  "description": "Parece que hay un Pokémon fuerte protegiendo un arbusto de bayas. Luchar es el enfoque directo, pero parece fuerte. Quizás un Pokémon rápido podría agarrar algunas bayas sin ser descubierto?",
  "query": "¿Que harás?",
  "berries": "¡Bayas!",
  "option": {
    "1": {
      "label": "Enfréntate al Pokémon",
      "tooltip": "(-) Batalla Difícil\n(+) Obtén bayas",
      "selected": "You approach the\nPokémon without fear."
    },
    "2": {
      "label": "Corre hacia el arbusto",
      "tooltip": "(-) {{fastestPokemon}} Utiliza su velocidad\n(+) Obtén bayas",
      "selected": "¡Tu {{fastestPokemon}} corre hacia el arbusto de bayas!$¡Logra agarrar {{numBerries}} antes de que {{enemyPokemon}} pueda reaccionar!$Huyes rápidamente con tu nuevo premio.",
      "selected_bad": "¡Tu {{fastestPokemon}} corre hacia el arbusto de bayas!$¡Oh no! ¡El {{enemyPokemon}} fue más rápido y bloqueó el camino!",
      "boss_enraged": "¡El {{enemyPokemon}} oponente se ha enfurecido!"
    },
    "3": {
      "label": "Irse",
      "tooltip": "(-) Ninguna Recompensa",
      "selected": "Dejas al Pokémon fuerte con su premio y continúas."
    }
  }
}
```

2024-09-14 06:19 UTC, 40chyan commented
please create PR to this branch instead of making hundreds of suggestions, to make sure this PR won't be broken.

2024-09-14 14:03 UTC, DanStevensonx reviewed
Fixed a few translation things

2024-09-14 14:03 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "description": "Te están ofreciendo @[TOOLTIP_TITLE]{Shiny Charm} y {{price, money}} por tu {{strongestPokemon}}!¡Es un trato extremadamente bueno, pero ¿realmente puedes soportar separarte de un m
```suggestion
  "description": "Te están ofreciendo @[TOOLTIP_TITLE]{Amuleto Iris} y {{price, money}} por tu {{strongestPokemon}}!¡Es un trato extremadamente bueno, pero ¿realmente puedes soportar separarte de un miembro tan fuerte de tu equipo?",
```

2024-09-14 15:03 UTC, DanStevensonx reviewed
Translated to Spanish

2024-09-14 15:03 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/bug-type-superfan-dialogue.json
> +}
```suggestion
{
  "intro": "¡Un entrenador inusual con todo tipo de parafernalia de bichos bloquea tu camino!",
  "intro_dialogue": "¡Hola, entrenador! ¡Estoy en una misión para encontrar el Pokémon Bicho más raro que existe!$¿A ti también te encantan los Pokémon Bicho, verdad? ¡A todos les encantan los Pokémon Bicho!",
  "title": "El Superfan de los Pokémon Bicho",
  "speaker": "Superfan de los Pokémon Bicho",
  "description": "El entrenador parlotea, sin siquiera esperar una respuesta...\n\n¡Parece que la única forma de salir de esta situación es captando la atención del entrenador!",
  "query": "¿Que harás?",
  "option": {
    "1": {
      "label": "Proponer a luchar",
      "tooltip": "(-) Batalla Desafiante\n(+) Enseña un movimiento de tipo Bicho a un Pokémon",
      "selected": "¿Un desafío, eh?\n¡Mis Pokémon Bicho están más que preparados para ti!"
    },
    "2": {
      "label": "Muestra tus tipos Bicho",
      "tooltip": "(+) ¡Recibe un objeto de regalo!",
      "disabled_tooltip": "Necesitas al menos 1 Pokémon de tipo Bicho en tu equipo para seleccionar esto.",
      "selected": "Le muestras al entrenador todos tus Pokémon de tipo Bicho...",
      "selected_0_to_1": "¿Eh? Solo tienes {{numBugTypes}}...$Supongo que estoy perdiendo el tiempo con alguien como tú...",
      "selected_2_to_3": "¡Oye, tienes {{numBugTypes}} Pokémon de tipo Bicho! No está mal.$Aquí, esto podría ayudarte en tu viaje para atrapar más.",
      "selected_4_to_5": "¿Qué? ¿Tienes {{numBugTypes}} Bug Types?\nNice!$No estás a mi nivel, pero puedo ver destellos de mí en ti.$¡Toma esto, mi joven aprendiz!",
      "selected_6": "¡Vaya! {{numBugTypes}}Pokémon de tipo Bicho!$¡Debes amar a los Pokémon de tipo Bicho casi tanto como yo!$Aquí, toma esto como un símbolo de nuestra camaradería."
    },
    "3": {
      "label": "Regala un objeto de tipo Bicho",
      "tooltip": "(-) Dale al entrenador un {{requiredBugItems}}\n(+) Recibe un item de regalo",
      "disabled_tooltip": "Necesitas tener un {{requiredBugItems}} para seleccionar esto.",
      "select_prompt": "Selecciona un objeto para dar",
      "invalid_selection": "El Pokémon no tiene ese tipe de objeto.",
      "selected": "Le entregas al entrenador un{{selectedItem}}.",
      "selected_dialogue": "¡Vaya! ¿Un {{selectedItem}}, para mí? ¡No eres tan malo, chico!$Como muestra de mi agradecimiento, quiero que tengas este regalo especial.$Ha pasado por toda mi familia, y ahora quiero que lo tengas tú."
    }
  },
  "battle_won": "¡Tu conocimiento y habilidad fueron perfectos para explotar nuestras debilidades!$A cambio de la valiosa lección, permíteme enseñarle a uno de tus Pokémon un movimiento de tipo Bicho.",
  "teach_move_prompt": "Selecciona un movimiento para enseñar a un Pokémon.",
  "confirm_no_teach": "¿Estás seguro de que no quieres aprender uno de estos excellentes movimientos?",
  "outro": "¡Veo grandes Pokémon de tipo Bicho en tu futuro! ¡Que nuestros caminos se crucen de nuevo! ¡Bicho fuera!"
}
```

2024-09-14 23:53 UTC, DanStevensonx reviewed
Translated to Spanish

2024-09-14 23:53 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/clowning-around-dialogue.json
> +}
```suggestion
{
  "intro": "¿Es un...@d{64} payaso?",
  "speaker": "Payaso",
  "intro_dialogue": "¡Bufón torpe, prepárate para una batalla brillante! ¡Serás derrotado por este trovador peleador!",
  "description": "Algo no esta bien en este encuentro. El payaso parece ansioso por provocarte a una batalla, ¿pero con qué fin? El {{blacephalonName}} es especialmente extraño, como si tuviera @[TOOLTIP_TITLE]{tipos y habilidades raros.}",
  "query": "¿Qué harás?",
  "option": {
    "1": {
      "label": "Enfrentarse al Payaso",
      "tooltip": "(-) Batalla extraña\n(?) Afecta las habilidades de los Pokémon",
      "selected": "¡Tus patéticos Pokémon están listos para una actuación patética!",
      "apply_ability_dialogue": "¡Una exhibición sensacional! ¡Tu astucia se adapta a una habilidad sensacional como recompensa!",
      "apply_ability_message": "¡El payaso está ofreciendo intercambiar permanentemente la habilidad de uno de tus Pokémon por {{ability}}!",
      "ability_prompt": "¿Te gustaría enseñar permanentemente a un Pokémon la habilidad {{ability}}?",
      "ability_gained": "¡@s{level_up_fanfare}{{chosenPokemon}} obtenió la habilidad {{ability}}!"
    },
    "2": {
      "label": "No involucrarse",
      "tooltip": "(-) Molesta al payaso\n(?) Afecta los objetos de los Pokémon",
      "selected": "¡Cobarde desdichado, niegas un exquisito duelo?\n ¡Siente mi furia!",
      "selected_2": "¡El {{blacephalonName}} del payaso usa Truco! ¡Todos los objetos de tu {{switchPokemon}} fueron intercambiados al azar!",
      "selected_3": "¡Tonto desconcertado, cae en mi engaño impecable!"
    },
    "3": {
      "label": "Devolver los insultos",
      "tooltip": "(-) Molesta al payaso\n(?) Afecta los objetos de los Pokémon",
      "selected": "¡Cobarde desdichado, niegas un exquisito duelo?\n ¡Siente mi furia!",
      "selected_2": "¡El {{blacephalonName}} del payaso usa un movimiento extraño! ¡Todos los tipos de tu equipo fueron intercambiados al azar!",
      "selected_3": "¡Tonto desconcertado, cae en mi engaño impecable!"
    }
  },
  "outro": "El payaso y sus secuaces\ndesaparecen en una nube de humo."
}
```

2024-09-15 07:31 UTC, CodeTappert commented on src/locales/de/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "intro_dialogue": "Guten Tag!$Ich kann nicht anders, als zu bemerken, dass dein\n{{strongestPokemon}} einfach göttlich aussieht!$Ich habe schon immer ein Haustier wie dieses haben wollen!$Ich würde
```suggestion
  "intro_dialogue": "Guten Tag!$Ich kann nicht anders, als zu bemerken, dass dein\n{{strongestPokemon}} einfach göttlich aussieht!$Ich habe schon immer ein Pokémon wie dieses haben wollen!$Ich würde es dir großzügig bezahlen, und dir auch diesen alten Kram geben!",
```

2024-09-15 17:13 UTC, DanStevensonx reviewed
Translated some files, and corrected some others.

2024-09-15 17:13 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/dancing-lessons-dialogue.json
> +}
```suggestion
{
  "intro": "Un {{oricorioName}} baila tristemente solo, sin pareja.",
  "title": "Clases de baile",
  "description": "El {{oricorioName}} no parece agresivo, más bien parece triste.\nTal vez solo quiera alguien con quien bailar...",
  "query": "¿Qué harás?",
  "option": {
    "1": {
      "label": "Enfrentars",
      "tooltip": "(-) Batalla Ardua\n(+) Obtén el objeto Relevo",
      "selected": "¡El {{oricorioName}} está angustiado e intenta defenderse!",
      "boss_enraged": "¡El miedo del {{oricorioName}} aumentó sus estadísticas!"
    },
    "2": {
      "label": "Aprende su danza",
      "tooltip": "(+) Enseña a un Pokémon Danza despertar",
      "selected": "Observas atentamente al {{oricorioName}} mientras realiza su danza…$@s{level_up_fanfare}¡Tu {{selectedPokemon}} aprendió del {{oricorioName}}!"
    },
    "3": {
      "label": "Muéstrale una danza",
      "tooltip": "(-) Enseña al {{oricorioName}} un movimiento de danza\n(+) Le gustaras al {{oricorioName}}",
      "disabled_tooltip": "Tus Pokémon necesitan conocer un movimiento de danza para esto.",
      "select_prompt": "Selecciona un movimiento de tipo danza para usar.",
      "selected": "¡El {{oricorioName}} observa fascinado mientras\n{{selectedPokemon}} muestra {{selectedMove}}!$¡Le encanta la exhibición!$@s{level_up_fanfare}¡El {{oricorioName}} quiere unirse a tu equipo!"
    }
  },
  "invalid_selection": "Este Pokémon no conoce un movimiento de danza"
}
```

2024-09-15 20:14 UTC, CodeTappert commented on src/locales/de/mystery-encounters/trash-to-treasure-dialogue.json
> +      "selected": "Du arbeitest dich durch den Müllhaufen und wirst von Dreck überzogen.$Kein respektabler Ladenbesitzer wird dir in deinem schmutzigen Zustand etwas verkaufen!$Du musst ohne Heilitem
```suggestion
      "selected": "Du arbeitest dich durch den Müllhaufen und wirst von Dreck überzogen.$Kein respektabler Ladenbesitzer wird dir in deinem schmutzigen Zustand etwas verkaufen!$Aber es gibt ja auch andere... weniger respektable.$Natürlich verlangen sie höhere Preise.$Aber du hast einige unglaubliche Items im Müll gefunden!"

```

2024-09-15 22:50 UTC, DanStevensonx reviewed
Translated encounter to Spanish

2024-09-15 22:50 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/dark-deal-dialogue.json
> +}
```suggestion


{
  "intro": "Un hombre extraño con un abrigo andrajoso se interpone en tu camino...",
  "speaker": "Tipo sombrío",
  "intro_dialogue": "¡Oye, tú!$He estado trabajando en un nuevo dispositivo\npara sacar el poder latente de un Pokémon!$Reorganiza completamente los átomos del Pokémon\na nivel molecular en una forma mucho más poderosa.$Jeje…@d{64} Solo necesito algunos sac-@d{32}\nEh, sujetos de prueba, para demostrar que funciona.",
  "title": "Pacto Oscuro",
  "description": "El tipo inquietante sostiene unas Pokéballs.\n\"¡Te lo compensaré! Puedes tener estas Pokéballs fuertes como pago. ¡Todo lo que necesito es un Pokémon de tu equipo! Jeje...",
  "query": "¿Qué harás?",
  "option": {
    "1": {
      "label": "Acceptar",
      "tooltip": "(+) 5 Rogue Balls\n(?) Mejora un Pokémon aleatorio",
      "selected_dialogue": "Veamos, ¡Ese {{pokeName}} servirá muy bien!$Recuerda, no soy responsable\nsi algo malo sucede!@d{32} Jeje...",
      "selected_message": "El hombre te entrega 5 Rogue Balls.${{pokeName}} entra dentro de la máquina...$¡Luces intermitentes y ruidos extraños\ncomienzan a salir de la máquina!$...@d{96} Algo emerge\ndel dispositivo, ¡furiosamente!"
    },
    "2": {
      "label": "Rechazar",
      "tooltip": "(-) Ninguna Recompensa",
      "selected": "¿No vas a ayudar a un pobre hombre?\n¡Bah!"
    }
  },
  "outro": "Después del encuentro angustioso, te recuperas y te marchas."
}
```

2024-09-15 22:56 UTC, DanStevensonx reviewed
minor translation correction

2024-09-15 22:56 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/dancing-lessons-dialogue.json
> +  "invalid_selection": "Este Pokémon no conoce un movimiento de danza"
```suggestion
  "invalid_selection": "Este Pokémon no conoce ningún movimiento de danza"
```

2024-09-16 16:22 UTC, NicusPulcis submitted a review, later dismissed
Added italian translations for few missing keys and a whole ME

2024-09-16 16:22 UTC, NicusPulcis commented on src/locales/it/mystery-encounters/a-trainers-test-dialogue.json
> +  "outro": "{{statTrainerName}} gave you {{eggType}}!"
```suggestion
  "intro": "Un allenatore davvero forte ti si avvicina...",
  "buck": {
    "intro_dialogue": "Yo, allenatore! Sono Buck.$Ho una proposta super fantastica\nper allenatori forti come te!$Ho qui con me due uova Pokémon rare,\nma vorrei affidarne una a qualcuno.$Se mi darai prova delle tue doti di allenatore,\nti darò quella più rara!",
    "accept": "Whoooo, comincio a scaldarmi!",
    "decline": "Accidenti, pare che la tua\nsquadra non se la passi bene.$Lascia che ti aiuti."
  },
  "cheryl": {
    "intro_dialogue": "Ciao, mi chiamo Cheryl.$Ho una particolare richiesta,\nmirata ad allenatori come te.$Ho qui con me due uova Pokémon rare,\nma vorrei affidarne una a qualcuno.$Se mi darai prova delle tue doti di allenatore,\nti darò quella più rara!",
    "accept": "Spero tu sia pronto/a!",
    "decline": "Capisco, mi sa che i tuoi Pokémon\nnon stanno benissimo al momento.$Ti do una mano."
  },
  "marley": {
    "intro_dialogue": "...@d{64} Sono Marley.$Ho da farti un'offerta...$Ho con me due uova Pokémon rare,\nma voglio regalarne una.$Se ti dimostri più forte di me,\nti darò la più rara tra le due.",
    "accept": "... capisco.",
    "decline": "...capisco.$I tuoi Pokémon hanno una brutta cera...\nLasciami aiutare."
  },
  "mira": {
    "intro_dialogue": "Ciaoo! Sono Mira!$Mira ha una richiesta\nper un allenatore forte come te!$Mira ha due uova Pokémon rare,\nma Mira vuole darne via una delle due!$Se dimostri a Mira che te la cavi,\nMira ti da la più rara!",
    "accept": "Affronterai Mira?\nYuppi!",
    "decline": "Aww, niente lotta?\nVa bene!$Ecco, ora Mira cura la tua squadra!"
  },
  "riley": {
    "intro_dialogue": "Sono Riley.$Ho una strana proposta\nper gli allenatori forti.$Ho qui due uova Pokémon rare,\nma vorrei darne via una.$Dimostrami quanto vali,\ne ti darò la più rara!",
    "accept": "Lo sguardo nei tuoi occhi...\nDiamoci dentro.",
    "decline": "Capisco, la tua squadra non se la passa bene.$Lasciami rimediare."
  },
  "title": "La prova di un allenatore",
  "description": "Pare che questo allenatore ti darà un uovo a prescindere dalla tua volontà. Tuttavia, sconfiggendolo, potrai riceverne uno nettamente più raro.",
  "query": "Che cosa farai?",
  "option": {
    "1": {
      "label": "Accetta la sfida",
      "tooltip": "(-) Ardua lotta\n(+) Ottieni un @[TOOLTIP_TITLE]{Very Rare Egg}"
    },
    "2": {
      "label": "Rifiuta la sfida",
      "tooltip": "(+) Squadra completamente curata\n(+) Ottieni un @[TOOLTIP_TITLE]{Egg}"
    }
  },
  "eggTypes": {
    "rare": "un uovo raro",
    "epic": "un uovo epico",
    "legendary": "un uovo leggendario"
  },
  "outro": "{{statTrainerName}} ti dona {{eggType}}!"
```

2024-09-16 17:34 UTC, DanStevensonx reviewed
translated to Spanish

2024-09-16 17:34 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/delibirdy-dialogue.json
> +  "outro": "The {{delibirdName}} pack happily waddles off into the distance.$What a curious little exchange!"
```suggestion


{
  "intro": "¡Ha aparecido una bandada de {{delibirdName}}!",
  "title": "Pajarradas",
  "description": "Los {{delibirdName}} te miran expectantes, como si quisieran algo. Tal vez darles un objeto o algo de dinero los satisfaría.",
  "query": "¿Qué les darás?",
  "invalid_selection": "Pokémon no tienen ese tipo de objeto.",
  "option": {
    "1": {
      "label": "Dar dinero",
      "tooltip": "(-) Dar a los {{delibirdName}}s {{money, money}}\n(+) Recibe un objeto de regalo",
      "selected": "Lanzas el dinero a los {{delibirdName}}s, \nque charlan emocionados entre ellos.$Luego se vuelven hacia ti y te dan un regalo con alegría."
    },
    "2": {
      "label": "Dar comida",
      "tooltip": "(-) Dar a los {{delibirdName}}s una Baya o Semilla milagro\n(+) Recibe un objeto de regalo",
      "select_prompt": "Selecciona un objeto para dar.",
      "selected": "Lanzas el {{chosenItem}} a los {{delibirdName}},\nque charlan emocionados entre ellos.$Se vuelven hacia ti y te dan un regalo alegremente."
    },
    "3": {
      "label": "Dar objeto",
      "tooltip": "(-) Dar a los {{delibirdName}}s un objeto equipado\n(+) Recibe un objeto de regalo",
      "select_prompt": "Selecciona un objeto para dar.",
      "selected": "Lanzas el {{chosenItem}} a los {{delibirdName}},\nque charlan emocionados entre ellos.$Se vuelven hacia ti y te dan un regalo alegremente."
    }
  },
  "outro": "La bandada de {{delibirdName}} se aleja felizmente a lo lejos. ¡Qué intercambio tan curioso!"
}
```

2024-09-17 16:21 UTC, sodaMelon reviewed
left piece for BGM for Korean localization. 
The whole thing will add tomorrow.

2024-09-17 18:27 UTC, CodeTappert commented on src/locales/de/mystery-encounters/a-trainers-test-dialogue.json
> +  "egg_list_full_dialogue": "Oh, it looks like you don't have room to carry another egg.$Here, take these instead!"
```suggestion
  "egg_list_full_dialogue": "Oh, es sieht so aus, als hättest du keinen Platz, um ein weiteres Ei zu tragen.$Hier, nimm stattdessen das hier!"
```

2024-09-17 18:28 UTC, CodeTappert commented on src/locales/de/mystery-encounters/a-trainers-test-dialogue.json
> +  "egg_list_full_dialogue": "Oh, it looks like you don't have room to carry another egg.$Here, take these instead!",
```suggestion
  "egg_list_full_dialogue": "Oh, es sieht so aus, als hättest du keinen Platz, um ein weiteres Ei zu tragen.$Hier, nimm stattdessen das hier!",
```

2024-09-18 11:36 UTC, sodaMelon reviewed
modified some grammar typo in Korean.
(this is real LAST THING! thanks)

2024-09-18 11:36 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/fiery-fallout-dialogue.json
> +      "selected": "쉘터를 향해 고분고투하는 동안\n재와 불씨로 인해 심각한 피해를 입었다!$모든 포켓몬이 HP의 20% 피해를 받았다!",
```suggestion
      "selected": "셸터를 향해 고분고투하는 동안\n재와 불씨로 인해 심각한 피해를 입었다!$모든 포켓몬이 HP의 20% 피해를 받았다!",
```

2024-09-18 11:36 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/shady-vitamin-dealer-dialogue.json
> +  "cheap_side_effects": "그런데 약이 부작용이 있는 것 같다!${{selectedPokemon}}[[가]] 약간 고통스러워 한다.\n성격이 {{newNature}}[[로]] 변해버렸다!",
```suggestion
  "cheap_side_effects": "그런데 약이 부작용이 있는 것 같다!${{selectedPokemon}}[[가]] 약간 고통스러워한다.\n성격이 {{newNature}}[[로]] 변해버렸다!",
```

2024-09-18 12:43 UTC, DanStevensonx reviewed
Translated to Spanish

2024-09-18 12:43 UTC, DanStevensonx commented on src/locales/es/modifier-select-ui-handler.json
> +  "continueNextWaveDescription": "Continue to the next wave"
```suggestion
  "continueNextWaveButton": "Continuar",
  "continueNextWaveDescription": "Continuar a la siguiente ronda"
```

2024-09-18 12:43 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/fiery-fallout-dialogue.json
> +}
```suggestion
{
  "intro": "¡Te encuentras con una tormenta abrasadora de humo y ceniza!",
  "title": "¡Pasión Ardiente!",
  "description": "La ceniza y las brasas han reducido la visibilidad a casi cero. Parece que podría haber alguna… fuente que esté causando estas condiciones. Pero, ¿qué podría estar detrás de un fenómeno de esta magnitud?",
  "query": "¿Qué harás?",
  "option": {
    "1": {
      "label": "Encontrar la causa",
      "tooltip": "(?) Encunetra la causa\n(-) Batalla Difícil",
      "selected": "¡Empujas a través de la tormenta y encuentras a dos {{volcaronaName}}s en medio de una danza de apareamiento!$¡No toman bien la interrupción y atacan!"
    },
    "2": {
      "label": "Refugiarse",
      "tooltip": "(-) Sufre los efectos del clima",
      "selected": "Los efectos del clima causan un daño significativo mientras luchas por encontrar refugio. ¡Tu grupo pierde el 20% de su HP máximo!",
      "target_burned": "¡Tu {{burnedPokemon}} también acabo quemándose!"
    },
    "3": {
      "label": "Tus tipos de fuego ayudan",
      "tooltip": "(+) Paras las condiciones del clima\n(+) Obtén un Carbón",
      "disabled_tooltip": "Necesitas al menos 2 Pokémon de tipo Fuego para elegir esto",
      "selected": "Tus {{option3PrimaryName}} y {{option3SecondaryName}} te guían hasta donde dos {{volcaronaName}}s están en medio de una danza de apareamiento.$Afortunadamente, tus Pokémon logran calmarlos y se van sin problemas."
    }
  },
  "found_charcoal": "Después de que el clima se despeja,\ntu {{leadPokemon}} ve algo en el suelo. $¡@s{item_fanfare}{{leadPokemon}} obtuvo un Carbón!"
}
```

2024-09-18 16:10 UTC, DanStevensonx reviewed
Translated some more

2024-09-19 03:33 UTC, KimJeongSun requested changes
In addition to @sodaMelon 's suggestion, 
I made additional modifications to ensure that the counting units and bug type words do not overlap with the existing text. ( + spacing nit )

2024-09-19 03:33 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +  "numBugTypes_other": "벌레타입 {{count}}마리"
```suggestion
  "numBugTypes_one": "벌레 타입 {{count}}마리",
  "numBugTypes_other": "벌레 타입 {{count}}마리"
```

2024-09-19 03:33 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +      "selected_6": "우와!\n{{numBugTypes}}마리 모두 벌레 타입!$너도 나만큼 벌레 타입을 사랑하는 거지?$이걸 가져가!\n동지의 증표로 나눠줄게!"
```suggestion
      "selected_0_to_1": "응? 너 {{numBugTypes}}밖에 안 갖고 있구나...$너 같은 일반인한테 떠들었다니, 쓸데없이 입만 아팠네…",
      "selected_2_to_3": "어라, 너 {{numBugTypes}} 갖고 있구나!\n나쁘지 않아.$내가 더 많이 잡는 데 도움이 될만한 걸 줄게!",
      "selected_4_to_5": "뭐야? 너 {{numBugTypes}}마리나 갖고 있네?\n좋아!$아직 수준엔 못 미치지만, 너한테 내 옛날 모습이 보여!\n$이걸 받거라, 내 제자여…!",
      "selected_6": "우와!\n{{numBugTypes}}! 모두 벌레 타입!$너도 나만큼 벌레 타입을 사랑하는 거지?$이걸 가져가!\n동지의 증표로 나눠줄게!"
```

2024-09-19 08:56 UTC, 40chyan reviewed
imsorry

2024-09-19 08:56 UTC, 40chyan commented on src/locales/zh_CN/mystery-encounters/mysterious-chest-dialogue.json
> +  "query": "要打开么?"
```suggestion
  "query": "要打开么?",
```

2024-09-19 09:26 UTC, 40chyan commented on src/locales/zh_CN/mystery-encounters/fight-or-flight-dialogue.json
> +  "query": "你要怎么做？"
```suggestion
  "query": "你要怎么做？",
```

2024-09-19 16:41 UTC, Chapybara-jp commented on src/locales/ja/modifier-select-ui-handler.json
> +  "continueNextWaveDescription": "Continue to the next wave"
```suggestion
  "continueNextWaveButton": "続く",
  "continueNextWaveDescription": "次の　ラウンドに　続く"
```

2024-09-19 19:13 UTC, josericardo-fo commented on src/locales/pt_BR/trainer-names.json
> +  "bug_type_superfan": "Bug-Type Superfan"
```suggestion
  "bug_type_superfan": "Superfã de Insetos"
```

2024-09-19 19:15 UTC, josericardo-fo commented on src/locales/pt_BR/trainer-titles.json
> +  "the_winstrates": "The Winstrates'"
```suggestion
  "the_winstrates": "Os Winstrates'"
```

2024-09-20 14:38 UTC, Chapybara-jp commented
sorry @Adri1 , the strong trainer + winstrate dialog is done now!

2024-09-20 16:19 UTC, 40chyan commented on src/locales/zh_CN/mystery-encounters/the-expert-pokemon-breeder-dialogue.json
> +  "numEggs_other": "{{count}} {{rarity}} Eggs"
```suggestion
  "intro": "这是一位携带大量神奇宝贝蛋的训练师！",
  "intro_dialogue": "嘿，训练师！$看起来你的一些\n宝可梦感觉有点沮丧。$为什么不和我打一场来让它们兴奋一下呢？",
  "title": "专业饲养员",
  "description": "你被发起了一场@[TOOLTIP_TITLE]{只能使用一只宝可梦}的挑战。\n这可能很难，但它肯定会\n加深你与所选神奇宝贝之间的联系！\n如果你赢了，饲养员还会给你一些@[TOOLTIP_TITLE]{蛋}！",
  "query": "Who will you battle with?",
  "cleffa_1_nickname": "王牌",
  "cleffa_2_nickname": "皮氪稀",
  "cleffa_3_nickname": "帝王{{speciesName}}",
  "option": {
    "1": {
      "label": "{{pokemon1Name}}",
      "tooltip_base": "(-)艰难的战斗\n(+)获得与{{pokemon1Name}}的友谊"
    },
    "2": {
      "label": "{{pokemon2Name}}",
      "tooltip_base": "(-)艰难的战斗\n(+)获得与{{pokemon2Name}}的友谊"
    },
    "3": {
      "label": "{{pokemon3Name}}",
      "tooltip_base": "(-)艰难的战斗\n(+)获得与{{pokemon3Name}}的友谊"
    },
    "selected": "我们开始吧！"
  },
  "outro": "看看你的 {{chosenPokemon}}现在有多开心！$给，这些你也拿着。",
  "gained_eggs": "@s{item_fanfare}你获得了{{numEggs}}！",
  "eggs_tooltip": "\n(+)获得{{eggs}}",
  "numEggs_one": "{{count}}个{{rarity}}蛋",
  "numEggs_other": "{{count}}个{{rarity}}蛋"

```

2024-09-20 16:19 UTC, 40chyan commented on src/locales/zh_CN/trainer-names.json
> +  "expert_pokemon_breeder": "Expert Pokémon Breeder"
```suggestion
  "expert_pokemon_breeder": "专业宝可梦饲养员"
```

2024-09-20 21:35 UTC, CodeTappert commented on src/locales/de/achv.json
> +    "description": "Beat the Expert Pokémon Breeder in the Space Biome."
```suggestion
  },
  "BREEDERS_IN_SPACE": {
    "name": "Züchter im Weltall!",
    "description": "Besiege die Pokémon-Züchter-Expertin im Stratosphären Biome"
```

2024-09-20 21:36 UTC, CodeTappert commented on src/locales/de/achv.json
> +    "description": "Besiege die Pokémon-Züchter-Expertin im Stratosphären Biome"
```suggestion
    "description": "Besiege die Pokémon-Züchter-Expertin im Stratosphären Biome."
```

2024-09-21 03:04 UTC, protimita requested changes
achv.json ja translation

2024-09-21 03:11 UTC, DanStevensonx reviewed
Translated to Spanish

2024-09-21 03:11 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/fun-and-games-dialogue.json
> +}
```suggestion
{
  "intro_dialogue": "¡Pasen y vean, amigos! Prueben su suerte en el nuevo {{wobbuffetName}} Whack-o-matic!",
  "speaker": "El Feriante",
  "title": "Juegos y diversión",
  "description": "¡Te has encontrado con una feria ambulante con un juego de premios! Tendrás @[TOOLTIP_TITLE]{3 turnos} para dejar al {{wobbuffetName}} lo más cerca posible de @[TOOLTIP_TITLE]{1 PS} @[TOOLTIP_TITLE]{sin debilitarlo} para que pueda cargar un gran Contraataque en la máquina de golpear la campana. ¡Pero ten cuidado! Si debilitas al {{wobbuffetName}}, tendrás que pagar el coste de revivirlo.",
  "query": "¿Te gustaría jugar?",
  "option": {
    "1": {
      "label": "Jugar el juego",
      "tooltip": "(-) Paga {{option1Money, money}}\n(+) Juega al {{wobbuffetName}} Whack-o-matic",
      "selected": "¡Es hora de probar tu suerte!"
    },
    "2": {
      "label": "Irse",
      "tooltip": "(-) Ninguna Recompensa",
      "selected": "Te apresuras en irte, con una ligera sensación de arrepentimiento."
    }
  },
  "ko": "¡Oh no! ¡El {{wobbuffetName}} se debilitó!$Pierdes el juego y\ntienes que pagar el coste de revivirlo...",
  "charging_continue": "¡El Wobbuffet sigue cargando su contraataque!",
  "turn_remaining_3": "¡Quedan tres turnos!",
  "turn_remaining_2": "¡Quedan dos turnos!",
  "turn_remaining_1": "¡Queda un turno!",
  "end_game": "¡Se acabó el tiempo!$El {{wobbuffetName}} se prepara para el contraataque y@d{16}.@d{16}.@d{16}.",
  "best_result": "¡El {{wobbuffetName}} golpea el botón con tanta fuerza\nque la campana se rompe!$¡Ganas el gran premio!",
  "great_result": "¡El {{wobbuffetName}} golpea el botón, casi alcanzando la campana!$¡Tan cerca!\n¡Ganas el  segundo premio!",
  "good_result": "¡El {{wobbuffetName}} golpea el botón con suficiente fuerza para llegar a la mitad de la escala!$¡Ganas el tercer premio!",
  "bad_result": "El {{wobbuffetName}} apenas toca el botón y no pasa nada…$¡Oh no!\nNo ganas nada.",
  "outro": "¡Ese fue un juego muy divertido!"
}
```

2024-09-21 04:00 UTC, josericardo-fo commented on src/locales/pt_BR/achv.json
> +    "description": "Beat the Expert Pokémon Breeder in the Space Biome."
```suggestion
  },
  "BREEDERS_IN_SPACE": {
    "name": "Criadores no Espaço!",
    "description": "Derrote o Criador de Pokémon Experiente no Bioma Espaço."
```

2024-09-21 04:01 UTC, josericardo-fo commented on src/locales/pt_BR/achv.json
> +    "description": "Beat the Expert Pokémon Breeder in the Space Biome."
```suggestion
  "BREEDERS_IN_SPACE": {
    "name": "Criadores no Espaço!",
    "description": "Derrote o Criador de Pokémon Experiente no Bioma Espaço."
```

2024-09-21 05:09 UTC, KimJeongSun commented on src/locales/ko/achv.json
> +    "description": "Beat the Expert Pokémon Breeder in the Space Biome."
```suggestion
  "BREEDERS_IN_SPACE": {
    "name": "충격!우주에 브리더 진짜 계심ㄷㄷ",
    "description": "우주 바이옴에서 포켓몬 전문 브리더에게 승리."
```
discussed with korean translation team

2024-09-21 14:57 UTC, returntoice requested changes

2024-09-21 14:57 UTC, returntoice commented on src/locales/ko/mystery-encounter-messages.json
> +  "paid_money": "₽{{amount, number}}[[를]] 를 지불했다.",
```suggestion
  "paid_money": "₽{{amount, number}}[[를]] 지불했다.",
```
a typo fix

2024-09-21 15:14 UTC, returntoice requested changes

2024-09-21 15:14 UTC, returntoice commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +      "selected": "{{chosenItem}}}[[를]] 건네니,\n{{delibirdName}}들은 자기들끼리 신나서 떠들어댔다.$그리고 당신에게 돌아와 행복하게 선물을 건넨다!"
```suggestion
      "selected": "{{chosenItem}}[[를]] 건네니,\n{{delibirdName}}들은 자기들끼리 신나서 떠들어댔다.$그리고 당신에게 돌아와 행복하게 선물을 건넨다!"
```

2024-09-21 15:20 UTC, returntoice requested changes

2024-09-21 15:20 UTC, returntoice commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +      "selected": "{{chosenItem}}}[[를]] 건네니,\n{{delibirdName}}들은 자기들끼리 신나서 떠들어댔다.$그리고 당신에게 돌아와 행복하게 선물을 건넨다!"
```suggestion
      "selected": "{{chosenItem}}[[를]] 건네니,\n{{delibirdName}}들은 자기들끼리 신나서 떠들어댔다.$그리고 당신에게 돌아와 행복하게 선물을 건넨다!"
```

2024-09-21 15:43 UTC, returntoice requested changes

2024-09-21 15:43 UTC, returntoice commented on src/locales/ko/mystery-encounters/part-timer-dialogue.json
> +      "tooltip": "(-) {{option3PrimaryName}}의 {{option3PrimaryMove}}를 활용\n(+) @[MONEY]{Money} 획득",
```suggestion
      "tooltip": "(-) 포켓몬의 스피드를 활용\n(+) @[MONEY]{소지금} 획득",
      "selected": "{{selectedPokemon}}[[는]] 배달 아르바이트를 시작했다."
    },
    "2": {
      "label": "창고 정리",
      "tooltip": "(-) 포켓몬의 힘과 튼튼함을 활용\n(+) @[MONEY]{소지금} 획득",
      "selected": "{{selectedPokemon}}[[는]] 창고 정리를 시작했다."
    },
    "3": {
      "label": "바람잡이",
      "tooltip": "(-) {{option3PrimaryName}}의 {{option3PrimaryMove}}를 활용\n(+) @[MONEY]{소지금} 획득",
```
![캡처](https://github.com/user-attachments/assets/c831ff34-cd2f-4727-a1d9-2659b81e0949)
not translated

2024-09-21 16:23 UTC, returntoice requested changes

2024-09-21 16:23 UTC, returntoice commented on src/locales/ko/trainer-names.json
> +  "marley": "미",
```suggestion
  "marley": "미정",
```
a typo

2024-09-21 19:14 UTC, Chapybara-jp commented on src/locales/ja/mystery-encounters/bug-type-superfan-dialogue.json
> +}
```suggestion
{
  "intro": "色々な　むし式の　アクセを　着ている　奇抜な　トレーナー　は通せんぼ！",
  "intro_dialogue": "むしむし　トレーナーむ氏！　わたむしの　目的は　この世界で　一番珍しい　むしポケモンを　見つけること　でチュウ！$トレーナーむ氏も　むしが　大好き　でチョウ？\nみんなと同じ　でチュウね！",
  "title": "虫好きも好き好き",
  "speaker": "むしマニア",
  "description": "返事でも　待たずに　むしマニアは　言い続けています……\n\nこの状況から　出るには　注目を　引くしかない　ようです！",
  "query": "どうしますか？",
  "option": {
    "1": {
      "label": "バトルを挑む",
      "tooltip": "(-) 相手が手強い\n(+) ポケモンをむしタイプ技を教える",
      "selected": "わたむしを　挑むッシか？\n仲間の　むしたちは　もう　覚悟していまチュウ！"
    },
    "2": {
      "label": "むしポケモンを見せる",
      "tooltip": "(+) プレゼントをもらう",
      "disabled_tooltip": "選べるには　最小限　1匹の　むしタイプの　手持ちポケモンが　必要",
      "selected": "むしマニアに　手持ちの　むしポケモンを　見せる……",
      "selected_0_to_1": "何チュウこと？？　{{numBugTypes}}しか　いないの　でチョウ……$よクモ　時間を　むダニ　させます……",
      "selected_2_to_3": "ほほう！　{{numBugTypes}}が　いるんでチュウね！\n良く出来ムシた！$ね、　これが　あれば　冒険チュウに　もっともっと　捕まえられまチュウ！",
      "selected_4_to_5": "ほほう！　 {{numBugTypes}}が　いるんでチュウね！\nチョウナイス！$わたむしの　位に　果たさなかった　でチュウけど、\nトレーナーむ氏の　中に　チョーっと　自分が　見えますね\n$こちらをどうぞ！　我が虫弟子よ！",
      "selected_6": "チョチョチョウっと　待って！　 {{numBugTypes}}！！\n$わたむしと　同じくらいに　むしが　大好きでちょう？！$この友情の印を　受け取って　ください！"
    },
    "3": {
      "label": "むしアイテムをあげる",
      "tooltip": "(-) {{requiredBugItems}}をあげる\n(+) プレゼントをもらう",
      "disabled_tooltip": "選べるには　{{requiredBugItems}}を　持っているのが　必要",
      "select_prompt": "あげたい　アイテムを　選んで　ください",
      "invalid_selection": "ポケモンが　そんなアイテムを　持っていない！",
      "selected": "むしマニアに　{{selectedItem}}を　あげます。",
      "selected_dialogue": "チョウっと待って！　その{{selectedItem}}、 くれます？\nアリがとう　ございますムシ！$このアリがたさの印、受け取ってください！$古くから　先祖の　形見　でチュウよ…　トレーナーむ氏が　預かってくれます　蚊？"
    }
  },
  "battle_won": "その知識と　腕前は　弱点を　つけ込むには　チョウど良かった　でチュウ！$いい　勉強になったから、\nトレーナーむ氏の　手持ちポケモン　１匹に　むしタイプ技を　教えまチョウ！",
  "teach_move_prompt": "教えたい　技を　選んでください",
  "confirm_no_teach": "本当に　こんなすごい技を　教えませんか？",
  "outro": "チョウ強い　むしポケモンが\nトレーナーむ氏の　未来に　予知しまチュウよ！$また　でハエる　まで　バイ　ビー！",
  "numBugTypes_one": "{{count}}匹の　むしポケモン",
  "numBugTypes_other": "{{count}}匹の　むしポケモン"
}
```

2024-09-21 22:57 UTC, DanStevensonx reviewed
Translated to Spanish

2024-09-21 22:57 UTC, DanStevensonx commented on src/locales/es/mystery-encounters/global-trade-system-dialogue.json
> +}
```suggestion
{
  "intro": "¡Es una interfaz para la Estación de Intercambio Global, la GTS!",
  "title": "La GTS",
  "description": "¡Ah, la GTS! Una maravilla tecnológica, puedes conectarte con cualquier persona en todo el mundo para intercambiar Pokémon con ellos. ¿Tendrás suerte en tu intercambio hoy?",
  "query": "¿Qué harás?",
  "option": {
    "1": {
      "label": "Ver ofertas de intercambio"
      "tooltip": "(+) Selecciona una oferta de intercambio para uno de tus Pokémon",
      "trade_options_prompt": "Selecciona un Pokémon para recibir a través del intercambio."
    },
    "2": {
      "label": "Intercambio Prodigioso",
      "tooltip": "(+) Envía uno de tus Pokémon a la GTS y recibe un Pokémon aleatorio a cambio."
    },
    "3": {
      "label": "Intercambia un objeto",
      "trade_options_prompt": "Selecciona un objeto para enviar.",
      "invalid_selection": "Este Pokémon no tiene objetos legales para intercambiar.",
      "tooltip": "(+) Envía uno de tus objetos a la GTS y recibe un nuevo objeto aleatorio."
    },
    "4": {
      "label": "Irse",
      "tooltip": "(-) Ninguna Recompensa",
      "selected": "¡No hay tiempo para intercambiar hoy!\nSigues adelante."
    }
  },
  "pokemon_trade_selected": "{{tradedPokemon}} será enviado a {{tradeTrainerName}}.",
  "pokemon_trade_goodbye": "¡Adiós, {{tradedPokemon}}!",
  "item_trade_selected": "{{chosenItem}} será enviado a {{tradeTrainerName}}.$.@d{64}.@d{64}.@d{64}\n@s{level_up_fanfare}¡Intercambio completo!$¡Has recibido un {{itemName}} de {{tradeTrainerName}}!",
  "trade_received": "¡@s{evolution_fanfare}{{tradeTrainerName}} envió a {{received}}!"
}
```

2024-09-22 13:46 UTC, CodeTappert commented on src/locales/de/mystery-encounters/the-expert-pokemon-breeder-dialogue.json
> +  "outro_failed": "How disappointing...$It looks like you still have a long way\nto go to earn your Pokémon's trust!",
```suggestion
  "outro_failed": "Wie enttäuschend...$Es sieht so aus, als hättest du noch einen langen Weg vor dir, um das Vertrauen deines Pokémon zu gewinnen!"
```

2024-09-22 15:01 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/the-expert-pokemon-breeder-dialogue.json
> +  "outro_failed": "How disappointing...$It looks like you still have a long way\nto go to earn your Pokémon's trust!",
```suggestion
  "outro_failed": "실망이네요….$포켓몬의 신뢰를 얻으려면 아직 멀었어요!",
```

2024-09-22 15:09 UTC, 40chyan commented on src/locales/zh_CN/mystery-encounters/the-expert-pokemon-breeder-dialogue.json
> +  "outro_failed": "How disappointing...$It looks like you still have a long way\nto go to earn your Pokémon's trust!",
```suggestion
  "outro_failed": "太可惜了……$看起来要让你的宝可梦信任你\n你的路还长着呢。",

```

2024-09-22 19:22 UTC, DanStevensonx reviewed
Translated to Spanish

2024-09-22 19:22 UTC, DanStevensonx commented on src/locales/es/achv.json
> +    "description": "Beat the Expert Pokémon Breeder in the Space Biome."
```suggestion
  "BREEDERS_IN_SPACE": {
    "name": "¡Criapokémon en el Espacio!",
    "description": "Derrota al Criapokémon Experto en el Bioma Espacial."
```

2024-09-23 17:55 UTC, CodeTappert approved these changes

2024-09-23 18:24 UTC, josericardo-fo approved these changes

2024-09-23 18:37 UTC, CodeTappert approved these changes

2024-09-23 19:09 UTC, flx-sta approved these changes
I'll trust the translators

2024-09-23 19:34 UTC, SangaraSorama approved these changes

2024-09-23 19:38 UTC, merged