[QoL] Admin panel unlink accounts
pagefaultgames/pokerogue pull request #4198
Opened 2024-09-12 14:47 UTC by Opaque02

## What are the changes the user will see?
None for regular users

## Why am I making these changes?
Walker wanted it 
![image](https://github.com/user-attachments/assets/74261576-4281-4f1e-86b0-6611cd6e71cc)
More details to come

## What are the changes from a developer perspective?
Weird ui stuff going on with the action buttons - form-modal-ui-handler is coded to only handle a single action button, so adding a second one is iffy

### Screenshots/Videos
![image](https://github.com/user-attachments/assets/b4561e87-ea9f-4319-b002-bb94e8933439)

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-10-18 15:07 UTC, MokaStitcher commented
PR with code cleanup suggestions: https://github.com/Opaque02/pokerogue/pull/3

2024-10-19 12:59 UTC, MokaStitcher reviewed
lgtm
Mostly doc + scope change suggestions
The most important doc is in `FormModalUiHandler` since it'll help future devs who want to extend the class understand what they need to do. These and more generally doc for anything that is not private should use /** */ style comment so that the IDE picks up on it (within reason of course, we don't want to comment every single thing if they are self explanatory)

Not asking to change it but in general I think it would be better if the inline comments were on their own line unless they are really short. Some of these are too long to show in a single line so it makes things harder to read

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/admin-ui-handler.ts
> +  // this is used to update the fields' text when loading a new admin ui handler. It uses the adminResult to update the input text fields depending on the adminMode
can we change this to proper tsdoc? typing /** then enter in vsCode will create the template for you
unless the function can be made private in which case do that and the doc doesn't matter as much

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/admin-ui-handler.ts
> +  populateFields(adminMode: AdminMode, adminResult: AdminSearchInfo) {
```suggestion
  private populateFields(adminMode: AdminMode, adminResult: AdminSearchInfo) {
```

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/admin-ui-handler.ts
> +  areFieldsValid(adminMode: AdminMode, service?: string): { error: boolean; errorMessage?: string; } {
```suggestion
  private areFieldsValid(adminMode: AdminMode, service?: string): { error: boolean; errorMessage?: string; } {
```

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/admin-ui-handler.ts
> +  convertInputsToAdmin(): AdminSearchInfo {
```suggestion
  private convertInputsToAdmin(): AdminSearchInfo {
```

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/admin-ui-handler.ts
> +  async adminSearch(adminSearchResult: AdminSearchInfo) {
```suggestion
  private async adminSearch(adminSearchResult: AdminSearchInfo) {
```

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/admin-ui-handler.ts
> +  async adminLinkUnlink(adminSearchResult: AdminSearchInfo, service: string, mode: string) {
```suggestion
  private async adminLinkUnlink(adminSearchResult: AdminSearchInfo, service: string, mode: string) {
```

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/admin-ui-handler.ts
> +  updateAdminPanelInfo(adminSearchResult: AdminSearchInfo, mode?: AdminMode) {
```suggestion
  private updateAdminPanelInfo(adminSearchResult: AdminSearchInfo, mode?: AdminMode) {
```

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/form-modal-ui-handler.ts
> +  updateFields(fieldsConfig: InputFieldConfig[], hasTitle: boolean) {
can we get tsdoc for this? can probably be `protected` too

```suggestion
  protected updateFields(fieldsConfig: InputFieldConfig[], hasTitle: boolean) {
```

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/form-modal-ui-handler.ts
> +      this.modalContainer.add(this.inputContainers[this.inputContainers.length - 1]);
I think inputContainer is the same object as `this.inputContainers[this.inputContainers.length - 1]` right?
```suggestion
      this.modalContainer.add(inputContainer);
```

2024-10-19 12:59 UTC, MokaStitcher commented on src/ui/form-modal-ui-handler.ts
> +   * @returns array of {@linkcode InputFieldConfig}
```suggestion
   * Get configuration for all fields that should be part of the modal
   * Gets used by {@linkcode updateFields} to add the proper text inputs and labels to the view
   * @returns array of {@linkcode InputFieldConfig}
```

2024-10-20 11:08 UTC, Opaque02 commented on src/ui/admin-ui-handler.ts
> +  // this is used to update the fields' text when loading a new admin ui handler. It uses the adminResult to update the input text fields depending on the adminMode
Done I think - marking resolved, along with all other commits suggested for docs/private changes

2024-10-20 14:22 UTC, MokaStitcher approved these changes
Might as well so it's not forgotten

Full discussion in discord UI thread, but we also may want a specific error message if a discord/google id is already linked to another account

2024-10-20 14:22 UTC, MokaStitcher commented on src/ui/admin-ui-handler.ts
> +                  return this.showMessage(response.errorType, adminResult, true); // fail
```suggestion
                  this.scene.ui.setMode(Mode.LOADING, { buttonActions: []});
                  return this.showMessage(response.errorType, adminResult, true); // fail
```

2024-10-20 14:22 UTC, MokaStitcher requested changes
sorry, meant to request changes 💀

2024-10-20 22:17 UTC, Opaque02 commented on src/ui/admin-ui-handler.ts
> +                  return this.showMessage(response.errorType, adminResult, true); // fail
Fixed in next commit :)

2024-10-20 22:19 UTC, MokaStitcher submitted a review, later dismissed
ship it 👀

2024-10-21 10:42 UTC, MokaStitcher commented
> For these errors, the translation team has been made aware that this is now too long for the panel and they are in the process of updating things

oh I didn't even noticed that earlier. For reference the various error messages were already too long in some languages before adding those error codes. And I'm pretty sure I've seen a PR before to handle that by resizing the text if needed or something? But I can't find it so who knows lol

2024-10-23 18:36 UTC, flx-sta approved these changes

2024-10-23 18:36 UTC, flx-sta commented on src/loading-scene.ts
> +    this.loadImage("unlink_icon", "ui");
Technically these should only load if the logged in user is an admin.
I do understand though that at the point of loading-scene that information is not available.
It's something to consider though especially regarding mobile device performance issues

2024-10-23 18:36 UTC, flx-sta commented on src/ui/admin-ui-handler.ts
> +
I do understand that we are looking at an ADMIN interface but technically these string shouldn't be hard-coded (in a perfect world). Something we can look at another time though

2024-10-23 20:00 UTC, merged