[Bug] Using default animation for errors that occur.
pagefaultgames/pokerogue pull request #4266
Opened 2024-09-15 05:44 UTC by podarsmarty

## What are the changes the user will see?
- Fetch errors will no longer result in a crashed game

## Why am I making these changes?
- These errors are prevalent in offline builds that crash the game. I expect this to be possible on the live version but more rare and transient

## What are the changes from a developer perspective?
- Adds error handling to promise so that default animations do not occur ONLY for bad responses

### Screenshots/Videos
N/A

## How to test the changes?
- Build and package offline with move animation json file for a pokemon being used deleted. Will crash before and work properly after

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
     I took a look but for tests the entirely of fetch is mocked out. would need to add mock configurations to add unit tests
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-16 17:39 UTC, flx-sta requested changes

2024-09-16 17:39 UTC, flx-sta commented on src/data/battle-anims.ts
> +function useDefaultAnim(move: Moves, defaultMoveAnim: Moves, ...optionalParams: any[]) {
NIT:
missing ts-docs

2024-09-16 17:39 UTC, flx-sta commented on src/enums/moves.ts
> +export class MovesUtil {
NIT:
Missing ts-docs

2024-09-16 17:39 UTC, flx-sta commented on src/enums/moves.ts
> +  public static filename(move: Moves) {
NIT:
Missing ts-docs

2024-09-16 17:39 UTC, flx-sta commented on src/enums/moves.ts
> +export class MovesUtil {
Also I'd prefer to move new classes into their own files.

To keep it simple though you might want to consider simply creating an exported function/method in `utils.ts`

2024-09-16 18:07 UTC, flx-sta requested changes
sorry found 1 more.
(make sure to not always force push 👀 )

2024-09-16 18:07 UTC, flx-sta commented on src/data/battle-anims.ts
> +            return resolve();
We should probably print at least a log, better yet a warning here
```suggestion
          .catch(error => {
            console.warn(`No move animation found for ${Utils.animationFileName(move)}! Falling back to default.`);
            useDefaultAnim(move, defaultMoveAnim, error);
            return resolve();
```

2024-09-16 18:27 UTC, podarsmarty commented
> sorry found 1 more. (make sure to not always force push 👀 )

ahh no worries. will fix. my bad, saw you were merging, figured id rebase on beta and squash my commits so forced

2024-09-16 18:28 UTC, podarsmarty commented on src/data/battle-anims.ts
> +            return resolve();
@flx-sta hmm the useDefaultAnim function already logs an error to the console

2024-09-16 18:30 UTC, podarsmarty commented on src/data/battle-anims.ts
> +            return resolve();
renamed method to make that behavior more clear

2024-09-16 18:36 UTC, flx-sta commented
I find it rather odd that you decided to move the logging into the defaultAnim function (although you did rename it).
But technically the functions (original) context has nothing to with the logging. It would be better to have the logging inside the actual `catch()`.
Also `console.error` seems to elevated as it's not breaking anything. It's just an inconvenience, a warning to say so. Which implies wanting to use `console.warn()`

2024-09-16 18:48 UTC, podarsmarty commented
> I find it rather odd that you decided to move the logging into the defaultAnim function (although you did rename it). But technically the functions (original) context has nothing to with the logging. It would be better to have the logging inside the actual `catch()`. Look at it this way: Technically you could be calling `defaultAnim()` on purpose without it being an error/warning, right?
> 
> Also `console.error` seems to elevated as it's not breaking anything. It's just an inconvenience, a warning to say so. Which implies wanting to use `console.warn()`

i had moved it since the function is called in two places that would both warrant a log. figured it be better to share rather than copy pasting it. yea its not breaking, i had left it as an error the way it originally was, i can switch it over to a warn and duplicate the logging though.

however, i'd argue you should only be calling defaultAnim() in an error state since everything should have an animation defined the way it is setup

2024-09-16 19:24 UTC, flx-sta submitted a review, later dismissed
Thanks for elaborating your approach.

2024-09-16 22:49 UTC, DayKev commented on src/data/battle-anims.ts
> + * @param defaultMoveAnim the default move to use as the default animation
```suggestion
 * @param defaultMoveAnim the move to use as the default animation
```

2024-09-16 22:49 UTC, DayKev commented on src/data/battle-anims.ts
> + * Helper method to call when an move animation is missing.
```suggestion
 * Helper method for printing a warning to the console when a move animation is missing.
```

2024-09-16 22:49 UTC, DayKev commented on src/data/battle-anims.ts
> + * @remarks use {@link useDefaultAnim} to use a default animation
```suggestion
 * @remarks use {@linkcode useDefaultAnim} to use a default animation
```

2024-09-17 03:56 UTC, flx-sta approved these changes

2024-09-17 06:48 UTC, DayKev approved these changes

2024-09-18 02:15 UTC, merged