[Move][Mirror] Update HitTagAttr attributes v2
pagefaultgames/pokerogue pull request #4297
Opened 2024-09-17 19:42 UTC by flx-sta

### Mirror of #3082

> [!WARNING]
> Copied PR template/comment from #3082

---

## What are the changes?
Particular moves had outdated effects, or had effects removed due to not being in the most recent games.
It adjusts Whirlwind affecting Fly, Steamroller affecting Minimize, and Malicious Moonsault affecting Minimize.

## Why am I doing these changes?
These cause the game to behave in a way that those familiar with canonical mechanics might not expect.

Whirlwind was only supposed to be able to hit Pokemon in the semi-invulnerable turn of Fly in Gen II, and so that behaviour is getting removed. In fact, it is currently also capable of hitting Pokemon in the semi-invulnerable turn of Bounce and Sky Drop, since those all share the FLYING BattlerTag.
![image](https://github.com/user-attachments/assets/bd527688-1de0-43b2-98c4-2c1b744ba1ab)
Steamroller and Malicious Moonsault were effective against Minimized Pokemon as of the last time they were canonically implemented, and so that functionality is being restored.
![image](https://github.com/user-attachments/assets/050d9d24-79fb-4523-bdc9-cf6b26120acb)

## What did change?
Whirlwind lost the attribute allowing it to hit Pokemon in the FLYING turn of the two-turn moves Fly, Bounce, and Sky Drop.
Steamroller and Malicious Moonsault gained the attribute that bypasses accuracy checks on Minmized targets, as well as the attribute that does double damage against them.

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-17 22:25 UTC, chaosgrimmon commented
Can confirm that flx kept me looped in and we concepted the tests collaboratively.
Full disclosure, I'm pretty sure I didn't actually get to testing the changes for my old draft PR. It _should_ work exactly as well as other moves that have the same properties, but like, it very much was not a polished, usable PR until flx dug it back out of the attic.

2024-09-18 02:25 UTC, Tempo-anon requested changes
Can I request a name change for two Attrs? Could also potentially copy some logic to make the damage doubling part of the anti-minimize tag since all moves that always hit minimize targets seem to double damage but I guess for simplicity's sake this can be done first

`HitsTagAttr` -> `DealsDoubleDamageToTagAttr`
`MinimizeAccuracyAttr` -> `AlwaysHitsMinimizeAttr`

2024-09-18 02:25 UTC, Tempo-anon commented on src/data/move.ts
> +      .attr(MinimizeAccuracyAttr)
Does the MinimizeAccuracyAttr not already also basically do the same thing as HitsTagAtr minimized? Looking at the code it seems like the HitsTagAttr only doubles the damage while MinimizeAccuracyAttr means it never misses. lol

2024-09-18 02:38 UTC, flx-sta commented on src/data/move.ts
> +      .attr(MinimizeAccuracyAttr)
I think it's better to keep it separate for potential race-conditions

2024-09-18 02:41 UTC, Tempo-anon approved these changes

2024-09-18 02:41 UTC, Tempo-anon commented on src/data/move.ts
> +      .attr(MinimizeAccuracyAttr)
agree

2024-09-18 02:41 UTC, merged

2024-09-19 10:57 UTC, DayKev commented
Moves that use it that deal 2x damage:
- Gust
- Stomp
- Body Slam
- Surf
- Earthquake
- Magnitude
- Twister
- Whirlpool
- Dragon Rush
- Heavy Slam
- Heat Crash
- Steamroller
- Flying Press

Moves that use it that don't deal 2x damage:
- Thunder
- Fissure
- Sky Uppercut
- Smack Down
- Hurricane
- Thousand Arrows