Mystery Encounter bug fixes and minor adjustments
pagefaultgames/pokerogue pull request #4299
Opened 2024-09-17 19:47 UTC by ben-lear

Fixing problems from Issue https://github.com/pagefaultgames/pokerogue/issues/4240

2024-09-17 19:49 UTC, flx-sta commented
Does it fix ALL of them? or till a certain point?

2024-09-17 22:13 UTC, flx-sta requested changes

2024-09-17 22:13 UTC, flx-sta commented on src/test/mystery-encounter/encounters/fight-or-flight-encounter.test.ts
> -    expect(config.levelAdditiveMultiplier).toBe(1);
shouldn't `levelAdditiveModifier` be checked instead now?

2024-09-17 22:13 UTC, flx-sta commented on src/test/mystery-encounter/encounters/berries-abound-encounter.test.ts
> -    expect(config.levelAdditiveMultiplier).toBe(1);
shouldn't `levelAdditiveModifier` be checked instead now?

2024-09-17 22:13 UTC, flx-sta commented on src/phases/game-over-phase.ts
> +            if (encounter && encounter.introVisuals) {
NIT:
Could be simplified right?
```suggestion
            if (encounter?.introVisuals) {
```

2024-09-17 22:13 UTC, flx-sta commented on src/phases/command-phase.ts
> +      if (!isSwitch && (this.scene.arena.biomeType === Biome.END || (!isNullOrUndefined(mysteryEncounterFleeAllowed) && !mysteryEncounterFleeAllowed))) {
NIT: potentially make use of destructuring:

```suggestion
      const { currentBattle, arena } = this.scene;
      const mysteryEncounterFleeAllowed = currentBattle.mysteryEncounter?.fleeAllowed;
      if (!isSwitch && (arena.biomeType === Biome.END || (!isNullOrUndefined(mysteryEncounterFleeAllowed) && !mysteryEncounterFleeAllowed))) {
```

2024-09-17 22:13 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> +}
NIT:
should use some buffer variables:

```suggestion
export function getEncounterPokemonLevelForWave({ currentBattle }: BattleScene, levelAdditiveModifier: number = 0) {
  // Default to use the first generated level from enemyLevels, or generate a new one if it DNE
  const baseLevel = currentBattle.enemyLevels && currentBattle.enemyLevels.length > 0 ? currentBattle.enemyLevels[0] : currentBattle.getLevelForWave();

  // Add a level scaling modifier that is (+1 level per 10 waves) * levelAdditiveModifier
  return baseLevel + Math.max(Math.round((currentBattle.waveIndex / 10) * levelAdditiveModifier), 0);
}
```

2024-09-17 22:22 UTC, flx-sta approved these changes

2024-09-18 01:43 UTC, f-fsantos requested changes

2024-09-18 01:43 UTC, f-fsantos commented on src/data/mystery-encounters/encounters/a-trainers-test-encounter.ts
> +            scene.unshiftPhase(new ModifierRewardPhase(scene, modifierTypes.VOUCHER_PREMIUM));
the voucher solution is a no-go, we can either fix the UI to allow for more than 99 eggs or find a different alternative.

2024-09-18 03:30 UTC, damocleas approved these changes

2024-09-18 03:38 UTC, damocleas submitted a review, later dismissed

2024-09-18 03:39 UTC, flx-sta commented on src/data/move.ts
> +  getUserBenefitScore(user: Pokemon, target: Pokemon, move: Move): integer {
👀 
scope and/or docs

2024-09-18 03:39 UTC, flx-sta commented on src/data/mystery-encounters/encounters/delibirdy-encounter.ts
> +    .withSceneRequirement(new MoneyRequirement(0, 1.5)) // Must have enough money for it to spawn at the very least
Q:
Where is this `1.5` value coming from? 
Like is it based off something?

2024-09-18 03:39 UTC, flx-sta commented on src/data/mystery-encounters/encounters/delibirdy-encounter.ts
> +      });
We should make a helper method in the future.
Something like `replaceBgm(key: string, delay: number, whateverThisBooleanDoes: boolean = false)`

2024-09-18 03:39 UTC, flx-sta commented on src/data/mystery-encounters/encounters/delibirdy-encounter.ts
> +        .withSceneMoneyRequirement(0, 1.5) // Must have money to spawn
The 1.5. is being used a 2nd time.
Makes it a magic number which should be defined more central

2024-09-18 03:39 UTC, flx-sta commented on src/data/mystery-encounters/encounters/slumbering-snorlax-encounter.ts
> +        aiType: AiType.SMART // Required to ensure Snorlax uses Sleep Talk while it is asleep
_lol. Is there AiType.DUMB?_

2024-09-18 03:39 UTC, flx-sta commented on src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts
> +  const level = getEncounterPokemonLevelForWave(scene, 1);
The `1` is used multiple times. maybe it should be centralized into a const?

2024-09-18 03:39 UTC, flx-sta commented on src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts
> +        const level = getEncounterPokemonLevelForWave(scene, 1);
The `1` is used multiple times. maybe it should be centralized into a const?

2024-09-18 03:39 UTC, flx-sta commented on src/data/mystery-encounters/encounters/the-pokemon-salesman-encounter.ts
> +      if (randSeedInt(100) === 0 || isNullOrUndefined(species.abilityHidden) || species.abilityHidden === Abilities.NONE) {
you might want to move this `100` somewhere more central.
e.g. if damo wants to change some balance in this ME more easily

2024-09-18 03:39 UTC, flx-sta commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> + */
NIT: missing `@param`s

2024-09-18 04:01 UTC, damocleas commented on src/data/mystery-encounters/encounters/the-pokemon-salesman-encounter.ts
> +      if (randSeedInt(100) === 0 || isNullOrUndefined(species.abilityHidden) || species.abilityHidden === Abilities.NONE) {
anything easier is always appreciated

2024-09-18 12:11 UTC, ben-lear commented on src/data/mystery-encounters/encounters/delibirdy-encounter.ts
> +    .withSceneRequirement(new MoneyRequirement(0, 1.5)) // Must have enough money for it to spawn at the very least
it is a multiplier value that is based off of the value of Nuggets/Shop Items. It essentially is multiplied by wave index to arrive at final money cost.
![image](https://github.com/user-attachments/assets/b8a819d5-19bb-4aea-ab24-ad424869e26a)

2024-09-18 12:28 UTC, ben-lear commented on src/data/mystery-encounters/encounters/slumbering-snorlax-encounter.ts
> +        aiType: AiType.SMART // Required to ensure Snorlax uses Sleep Talk while it is asleep
lol there are `RANDOM` and `SMART_RANDOM` which both do not guarantee the use of Sleep Talk

2024-09-18 13:14 UTC, MokaStitcher reviewed
only had a look at the code so far, will try to do some playtesting if i find the time

2024-09-18 14:42 UTC, ben-lear commented on src/locales/en/mystery-encounters/bug-type-superfan-dialogue.json
> +      "selected_0_to_1": "Huh? You only have {{numBugTypes}} Bug Types...$Guess I'm wasting my breath on someone like you...",
This should be updated (again) to say “Bug Type” instead of “Bug Types”. The only valid case for this dialogue is when the player has exactly 1 Bug type, though technically it also handles an impossible edge case of if the player has 0.

2024-09-18 14:53 UTC, flx-sta commented on src/locales/en/mystery-encounters/bug-type-superfan-dialogue.json
> +      "selected_0_to_1": "Huh? You only have {{numBugTypes}} Bug Types...$Guess I'm wasting my breath on someone like you...",
you would use the `count` context for that
see here
https://www.i18next.com/translation-function/plurals#singular-plural

2024-09-18 14:59 UTC, flx-sta approved these changes
only minor nits left

2024-09-18 14:59 UTC, flx-sta commented on src/battle-scene.ts
> +  fadeAndSwitchBgm(newBgmKey: string, destroy: boolean = false, delay: number = 2000) {
NIT 
docs

2024-09-18 14:59 UTC, flx-sta commented on src/data/mystery-encounters/encounters/fun-and-games-encounter.ts
> +      party[chosenIndex] = leadPokemon;
NIT:
```suggestion
[party[0], party[chosenIndex]] = [party[chosenIndex], party[0]];
```
This is a shorthand to switch two items in an array.
I actually found that trick in this project

2024-09-18 16:51 UTC, ben-lear commented on src/data/mystery-encounters/encounters/fun-and-games-encounter.ts
> +      party[chosenIndex] = leadPokemon;
It was broken before because of this

2024-09-18 22:03 UTC, damocleas approved these changes

2024-09-19 03:05 UTC, flx-sta approved these changes

2024-09-19 13:43 UTC, f-fsantos approved these changes

2024-09-19 13:44 UTC, merged