[Challenge] Add Nuzlocke-related challenges
pagefaultgames/pokerogue pull request #4311
Opened 2024-09-18 10:43 UTC by DayKev

WIP

## What are the changes the user will see?

## Why am I making these changes?

## What are the changes from a developer perspective?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [x] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
  - Updated version of #2421 
- [x] The PR is self-contained and cannot be split into smaller PRs?
  - The individual challenges are related to a common overarching challenge
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-19 13:40 UTC, DayKev commented
I see it picks 3 random people to request for review now lmao.

Anyway, more or less ready (still need to figure out some tests). Could use some opinions on the challenge names/descriptions, I didn't spend long on them.

2024-09-20 00:25 UTC, frutescens requested changes
Could you edit challengeParser() in run-info-ui-handler to process these new challenges?

2024-09-20 14:13 UTC, Adri1 commented
Question: "Hardcore" mode also prevent the Pokémon to be heald every 10 waves, or it only applies to reviving items?

2024-09-21 06:26 UTC, DayKev commented
> Question: "Hardcore" mode also prevent the Pokémon to be heald every 10 waves, or it only applies to reviving items?

It only prevents reviving, non-fainted Pokémon will still be healed if only Hardcore is active.

2024-09-21 18:36 UTC, KimJeongSun commented on src/test/challenge/no_legends.test.ts
> +describe("Inverse Battle", () => {
```suggestion
describe("No Legends", () => {
```

2024-09-21 18:36 UTC, KimJeongSun commented on src/test/challenge/no_auto_heal.test.ts
> +describe("Inverse Battle", () => {
```suggestion
describe("No Auto Heal", () => {
```

2024-09-21 18:37 UTC, KimJeongSun commented on src/test/challenge/hardcore.test.ts
> +describe("Inverse Battle", () => {
```suggestion
describe("Hardcore", () => {
```

2024-09-30 14:23 UTC, Xavion3 commented on src/data/challenge.ts
> +  }
Can we make this know about the pokemon using the move too? For example, in a nuzlocke the AI should probably still be allowed to use revival blessing even if the player can't.

2024-09-30 14:24 UTC, Xavion3 commented on src/data/challenge.ts
>    }
Can we consider making this a more generic applier to just modify the pool of items available in the shop? That'd also naturally support challenges that do things like add items or modify their prices.

2024-09-30 14:26 UTC, Xavion3 commented on src/data/challenge.ts
> +  }
Can we consider letting this modify the pool as a whole instead of being just blacklisting items? It'll help future challenges, most notably the spliced challenge will need to be able to both add and remove items and I feel like it makes more sense to just have a single apply for modifying the reward pool.

2024-09-30 14:30 UTC, Xavion3 commented on src/data/challenge.ts
> +  }
I'm not sure this specific challenge is actually worth adding, just turning on the max starter cost challenge feels like it achieves the same goals but better. Legendary is already a pretty arbitrary distinction after all, starter costs are much more representative of a starter's power.

2024-09-30 14:45 UTC, Fontbane commented on src/modifier/modifier-type.ts
> +    isValidForChallenge = new Utils.BooleanHolder(true);
It would be nice to have a more general isValidItemForGameMode function, or a function that modifies the item table based on game mode. Inside that we'd apply the challenges too. There's several items that have different weight or are removed depending on gamemode and it'd be nice to have those all defined in one place.

2024-09-30 14:45 UTC, Fontbane commented on src/data/challenge.ts
> +   * Checks if the cought pokemon can be add to the team
_Mild spelling mistake_

2024-09-30 15:13 UTC, Adri1 commented on src/locales/en/challenges.json
> +    "desc": "You can only add the first Pokemon of a biome to your current party.",
```suggestion
    "desc": "You can no longer revive Pokémon that have fainted.",
    "value.0": "Off",
    "value.1": "On"
  },
  "noLegends": {
    "name": "No Starter Legends",
    "desc": "You can't choose any legendary, sub-legendary or mythical Pokémon as a starter.",
    "value.0": "Off",
    "value.1": "On"
  },
  "limitedCatch": {
    "name": "Limited Catch",
    "desc": "You can only add the first Pokémon of a biome to your current party.",
```

2024-09-30 15:13 UTC, Adri1 commented on src/locales/en/challenges.json
> +    "desc": "You can only add the first Pokemon of a biome to your current party.",
Added "é" to "Pokémon"

2024-09-30 15:25 UTC, SangaraSorama approved these changes
Approval for the locales folder.

2024-09-30 15:36 UTC, damocleas commented on src/data/challenge.ts
> +  }
agree, on this

2024-09-30 20:08 UTC, Fontbane commented on src/modifier/modifier-type.ts
> +    isValidForChallenge = new Utils.BooleanHolder(true);
Spliced Endless has DNA Splicers in Great tier and there's some classic/endless differences

2024-09-30 22:01 UTC, Xavion3 commented on src/modifier/modifier-type.ts
> +    isValidForChallenge = new Utils.BooleanHolder(true);
Spliced endless is being removed.

2024-10-01 00:15 UTC, DayKev commented on src/data/challenge.ts
> +  }
Yeah it felt kinda redundant but I didn't have a strong opinion on it so I wanted some feedback on whether to keep it from the original PR or not.

2024-10-02 13:26 UTC, DayKev commented on src/modifier/modifier-type.ts
> +  applyChallenges(party[0].scene.gameMode, ChallengeType.RANDOM_ITEM_POOL_MODIFIER, pool);
So this doesn't seem to work... now what?

2024-10-10 01:55 UTC, Fontbane commented on src/data/challenge.ts
> +      pool[i].filter((modifierType: WeightedModifierType) => !this.itemBlackList.includes(modifierType.modifierType.localeKey));
The filter function doesn't modify the array, it just returns a new array with the filter applied. Probably want .map instead, that will modify it.

2024-10-15 23:51 UTC, DayKev commented
Reverted attempts to modify the item pool and went back to the original blacklist implementation for now.

2024-10-15 23:53 UTC, DayKev commented on src/data/challenge.ts
> +  }
This prevents the player from selecting the move during the Command Phase, it doesn't actually prevent the move from happening (which I guess means there's an edge case where Metronome calls the move that needs to be taken care of at some point).
The AI isn't affected by this.

2024-10-16 01:37 UTC, damocleas submitted a review, later dismissed

2024-10-16 02:38 UTC, damocleas approved these changes

2024-10-17 13:36 UTC, PigeonBar commented on src/data/challenge.ts
> +    if (!(waveIndex % 10 === 1) && !(pokemon.scene.lastMysteryEncounter && (waveIndex % 10 === 2))) {
`lastMysteryEncounter` gets cleared upon reload (it's only used for clearing the last wave's ME visuals), so the player would no longer be able to add a wild Pokemon to the party if they reload on wave X2 after an ME.

There's also an edge case of ME on wave X1 and then trainer battle on wave X2, which would not allow the player to add any Pokemon from that biome.

Would it be possible for the session save data to keep track of a `mostRecentWildEncounter` instead (it would probably also require changes to the backend DB)? If not, then we could use `mysteryEncounterSaveData.encounteredEvents` to search for wave X1 ME's instead.

2024-10-17 14:02 UTC, PigeonBar commented on src/phases/party-heal-phase.ts
> +    }
Some ME's also use `PartyHealPhase` now. What is the intended behaviour here?

https://github.com/user-attachments/assets/7c78e3bf-f494-4eee-8fa4-1116861f1b49

2024-10-17 14:33 UTC, PigeonBar commented
In the Hardcore challenge, should the player be allowed to splice a fainted Pokemon with an alive Pokemon, which would sort of allow the fainted Pokemon to participate again?

2024-10-17 15:04 UTC, PigeonBar commented
The Hardcore challenge still allows rewards to contain hardcoded revival items from certain ME's (e.g., A Trainer's Test):

![20241017 ME Sacred Ash](https://github.com/user-attachments/assets/12e9d047-9ac7-4cd3-8671-9144d8b9e397)

2024-10-17 15:35 UTC, PigeonBar commented
The Hardcore challenge allows Revival Blessing to be used indirectly, such as from Sleep Talk:

https://github.com/user-attachments/assets/dcc9353f-f7ac-4dc0-84d4-dd0dd9ec68fb

`RevivalBlessingAttr` distinguishes between reviving player Pokemon and reviving enemy Pokemon, so we could probably apply the challenge and have the move fail there instead.

2024-10-17 18:08 UTC, Adri1 commented
Would it be possible to add "short_name" keys to be used in the Run History?
Like it's already the case for "Inverse Battle" challenge:
![image](https://github.com/user-attachments/assets/72198903-3b06-47fa-a87b-1badb6d165cf)

2024-10-17 19:54 UTC, DayKev commented on src/phases/party-heal-phase.ts
> +    }
Uh, hm... I hadn't considered MEs (well, they didn't even exist when the challenge was first added). Will probably have to consult with damo on this.

2024-10-17 19:55 UTC, DayKev commented on src/data/challenge.ts
> +    if (!(waveIndex % 10 === 1) && !(pokemon.scene.lastMysteryEncounter && (waveIndex % 10 === 2))) {
Hm, I'll look into it and see what can be done.

2024-10-17 19:56 UTC, DayKev commented
> Would it be possible to add "short_name" keys to be used in the Run History?

Sure. I'm not sure what the best short names to use are though.

> In the Hardcore challenge, should the player be allowed to splice a fainted Pokemon with an alive Pokemon, which would sort of allow the fainted Pokemon to participate again?

Probably not. Ugh, fusions...

2024-10-17 20:05 UTC, MokaStitcher reviewed
(not done with reviewing at all, just submitting to share the comments i have so far)

2024-10-17 20:05 UTC, MokaStitcher commented on src/data/challenge.ts
> +    if (!(waveIndex % 10 === 1) && !(pokemon.scene.lastMysteryEncounter && (waveIndex % 10 === 2))) {
Adding to this, some MEs let you fight and catch a mon (or even several mons, like the Safari Zone) so it probably needs to be considered even with PigeonBar's suggestion
Some MEs also allow to get a mon without needing to catch it like the Oricorio one or the Pokemon Salesman, should that be allowed for this challenge if not on wave X1?

2024-10-17 22:03 UTC, Adri1 commented
> Sure. I'm not sure what the best short names to use are though.

Might not always apply for English, but might apply for some languages

2024-10-18 01:44 UTC, damocleas commented
> Would it be possible to add "short_name" keys to be used in the Run History? Like it's already the case for "Inverse Battle" challenge: ![image](https://private-user-images.githubusercontent.com/2070109/377582753-72198903-3b06-47fa-a87b-1badb6d165cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTU5NzUsIm5iZiI6MTcyOTIxNTY3NSwicGF0aCI6Ii8yMDcwMTA5LzM3NzU4Mjc1My03MjE5ODkwMy0zYjA2LTQ3ZmEtYTg3Yi0xYmFkYjZkMTY1Y2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDE0MTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU1NzlkZWQ3NmZmYTQ2OTYxMTk3YjQyMThhZGQwZWM3NTNlOGM4NTlmZTU5ODEzM2I2YzBmZWI0NmZlYTg4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Lk4Ex0DUd6DayLMpMMCKB5FvJmFYTkgRg0BFJWDX7HY)
> 
> In order to limit this kind of scenario, when possible: ![image](https://private-user-images.githubusercontent.com/2070109/377586445-eb74fb24-678a-489a-8168-f0443de102a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTU5NzUsIm5iZiI6MTcyOTIxNTY3NSwicGF0aCI6Ii8yMDcwMTA5LzM3NzU4NjQ0NS1lYjc0ZmIyNC02NzhhLTQ4OWEtODE2OC1mMDQ0M2RlMTAyYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDE0MTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDAzOTVkZGM4YWU0OTU4ZDU5NGUxOTMwZTk0ZjI5YTM4ZTVkZDk0YThhZjc5YTcxNDI0OTFiYTkzNjRiNjg1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cYxh9t7qzmrjwDwrGdmB16V9FU1n6NvmgO34W7atoG4)

Would it not be better to just have this menu show the achievement icons with a hover over for the name? Different PR issue likely.

2024-10-18 01:46 UTC, damocleas commented
Or, well, on the above, a small icon to indicate each challenge type will likely be needed in the future as they wouldn't *all* have achievements associated likely.

2024-10-20 03:00 UTC, PigeonBar commented
It turns out that after beating Wave X0, `PartyHealPhase` normally runs _after_ the global RNG gets set for Wave X1. This means that in the No Free Heal challenge, replacing `PartyHealPhase` with `SelectModifierPhase` can cause item generation (especially rerolls) to interfere with RNG for generating the wild Pokemon in Wave X1.

To avoid the problem, we could instead have `PartyHealPhase` simply do nothing if No Free Heal is active, and have `SelectModifierPhase` activate normally from `VictoryPhase` (which occurs before RNG gets set for Wave X1) as if it were a non-X0 wave.

2024-10-25 16:08 UTC, Blitz425 commented
Is it possible to reuse the code from Sam's original nuzlocke mode that makes cries longer when a Pokemon faints in permadeath? It's such a small thing but it makes death's feel more impactful

2024-10-26 06:04 UTC, DayKev commented
> Is it possible to reuse the code from Sam's original nuzlocke mode that makes cries longer when a Pokemon faints in permadeath? It's such a small thing but it makes death's feel more impactful

What exactly do you mean by longer? Like, the cry should be slowed down so that it takes a longer time to complete? By how much; and what should be done about pitch shifting, if anything?

2025-03-16 05:26 UTC, damocleas commented
After a discussion some time ago on the discord, it was settled on best to just leave the "No Free Heal" challenge related things to another PR, unsure if you want to continue to work on this PR, make a new one, or let someone else do this since it may be very outdated now.

2025-06-13 18:08 UTC, closed without merging