Implemented Protean and Libero
pagefaultgames/pokerogue pull request #432
Opened 2024-05-03 21:25 UTC by takeyourt1me

Adds functionality for Libero and Protean abilities

2024-05-03 21:29 UTC, Flashfyre requested changes

2024-05-03 21:29 UTC, Flashfyre commented on .gitignore
> +src/overrides.ts
What's the purpose of this duplicate line?

2024-05-03 21:30 UTC, takeyourt1me commented on .gitignore
> +src/overrides.ts
Im not sure, must have accidentally left it in

2024-05-03 21:31 UTC, Flashfyre requested changes

2024-05-03 21:31 UTC, Flashfyre commented on src/field/pokemon.ts
> +  public abilityTriggeredThisSwitch: boolean = false;
```suggestion
  public abilityTriggered: boolean = false;
```
Being in battle summon data, I believe 'this switch' is implied

2024-05-03 21:31 UTC, Flashfyre commented on src/data/ability.ts
> +  applyPreAttack(pokemon:Pokemon,passive:boolean,defender:Pokemon,move:PokemonMove): boolean{
```suggestion
  private condition: PokemonAttackCondition;
  
  constructor (condition:PokemonAttackCondition) {
    super(true);
    this.condition = condition;
  }
  
  applyPreAttack(pokemon:Pokemon,passive:boolean,defender:Pokemon,move:PokemonMove): boolean{
```

2024-05-03 21:31 UTC, Flashfyre commented on src/data/ability.ts
>  export class VariableMoveTypeAbAttr extends AbAttr {
```suggestion
  }
}
 
export class VariableMoveTypeAbAttr extends AbAttr {
```

2024-05-03 22:29 UTC, takeyourt1me reviewed
Changed to fit the new suggested name and got rid of that extra line in the ignore. Is there anything else I should do?

2024-05-04 04:26 UTC, Flashfyre requested changes

2024-05-04 04:26 UTC, Flashfyre commented on src/data/ability.ts
> +    .attr(PreAttackChangeType,(user,target,move) => move.name !== 'Struggle' && !user.isTerastallized() && user.battleSummonData.abilityTriggered === false),
Checking move name will not work with localization, use move ID

2024-05-19 14:03 UTC, bennybroseph commented
Closing this due to inactivity. Feel free to make a new request if interest is reignited

2024-05-19 14:03 UTC, closed without merging