[Feature] Adds special item rewards to fixed classic/challenge battles
pagefaultgames/pokerogue pull request #4332
Opened 2024-09-19 22:24 UTC by ben-lear

## What are the changes the user will see?

## Why am I making these changes?
To give custom rewards for special battles

## What are the changes from a developer perspective?
- 25 Rival 2: 1 Ultra 2 Great Items
- 55 Rival 3: 2 Ultra 2 Great Items
- 95 Rival 4:  4 Ultra Items
- 115 Evil Boss 1: 3 Ultra 2 Rogue Items
- 145 Rival 5: 2 Ultra 3 Rogue Items
- 165 Evil Boss 2: Lock Capsule +4 Ultra 2 Rogue Items

### Screenshots/Videos

https://github.com/user-attachments/assets/beb3d510-5645-4e2d-8a9a-249606a61218

https://github.com/user-attachments/assets/43f96c31-7ce3-40e3-8f67-6c6ea9f09d6e

## How to test the changes?
locally, override floor to one of the specified floors and check the rewards are correct

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-19 22:53 UTC, damocleas requested changes
Please remove Lock Capsule from classic in pokerogue / src / modifier / modifier-type.ts

2024-09-19 23:37 UTC, damocleas approved these changes

2024-09-19 23:42 UTC, ben-lear commented on src/modifier/modifier-type.ts
>      new WeightedModifierType(modifierTypes.LOCK_CAPSULE, skipInLastClassicWaveOrDefault(3)),
```suggestion
    new WeightedModifierType(modifierTypes.LOCK_CAPSULE, (party: Pokemon[]) => party[0].scene.gameMode.isClassic ? 0 : 3)),
```

2024-09-19 23:42 UTC, ben-lear commented on src/modifier/modifier-type.ts
> +    new WeightedModifierType(modifierTypes.SUPER_EXP_CHARM, (party: Pokemon[]) => party[0].scene.gameMode.isClassic ? 0 : 8),
```suggestion
    new WeightedModifierType(modifierTypes.SUPER_EXP_CHARM, skipInLastClassicWaveOrDefault(8)),
```

2024-09-20 00:02 UTC, flx-sta submitted a review, later dismissed
only NITs

Nothing crucial

2024-09-20 00:02 UTC, flx-sta commented on src/phases/victory-phase.ts
> +        if (this.scene.gameMode.isClassic && this.scene.currentBattle.waveIndex === 165) {
NIT: 
`165` is a magic number.
Should possibly be moved to a constant

2024-09-20 00:02 UTC, flx-sta commented on src/phases/victory-phase.ts
> +   * will pass those settings to the upcoming `SelectModifierPhase`.
NIT: 
```suggestion
   * will pass those settings to the upcoming {@linkcode SelectModifierPhase}.
```

2024-09-20 00:28 UTC, innerthunder commented on src/modifier/modifier-type.ts
> +    new WeightedModifierType(modifierTypes.LOCK_CAPSULE, (party: Pokemon[]) => party[0].scene.gameMode.isClassic ? 0 : 3),
Is this meant to get rid of Lock Capsule in Classic altogether? 🤔

2024-09-20 00:28 UTC, damocleas commented on src/modifier/modifier-type.ts
> +    new WeightedModifierType(modifierTypes.LOCK_CAPSULE, (party: Pokemon[]) => party[0].scene.gameMode.isClassic ? 0 : 3),
Yes, please check the other files. It is given on a set wave now.

2024-09-20 00:32 UTC, innerthunder approved these changes

2024-09-20 00:51 UTC, damocleas approved these changes

2024-09-20 00:51 UTC, innerthunder approved these changes

2024-09-20 01:26 UTC, merged