[Challenge] Add Trick room challenge
pagefaultgames/pokerogue pull request #4343
Opened 2024-09-20 15:48 UTC by KimJeongSun

## What are the changes the user will see?

can enjoy trick room challenge! let's Snorlax!

## Why am I making these changes?

@Tempo-anon 's suggestion! thanks for the idea!

## What are the changes from a developer perspective?

- add trick room challenge
- reverse TrickRoomTag when challenge activated

## Todo
- add achievement for it (update achievement logic to disable other challenge achievement)

### Screenshots/Videos

( overrided starting level=100 and starting wave = 21 )
https://github.com/user-attachments/assets/c828d98e-2895-4b5b-99b3-f47d28d1bc83

## How to test the changes?

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-09-20 17:05 UTC, DayKev commented on src/data/challenge.ts
> +   * @returns {@link boolean} Whether this function did anything.
```suggestion
   * @returns `true` if this function did anything.
```

2024-09-20 17:05 UTC, DayKev commented on src/data/challenge.ts
> + * @returns True if any challenge was successfully applied.
```suggestion
 * Apply all challenges that modify Trick Room.
 * @param gameMode The current {@linkcode GameMode}
 * @param challengeType {@linkcode ChallengeType.TRICK_ROOM}
 * @param isTrickRoom {@linkcode Utils.BooleanHolder} Whether the battle is under the effect of Trick Room.
 * @returns `true` if any challenge was successfully applied.
```

2024-09-20 17:05 UTC, DayKev commented on src/data/challenge.ts
> +    }
```suggestion
    isTrickRoom.value = !isTrickRoom.value;
```

2024-09-20 17:13 UTC, flx-sta requested changes

2024-09-20 17:13 UTC, flx-sta commented on src/data/challenge.ts
> +   * @returns {@link boolean} Whether this function did anything.
paramNIT:
The type is already given by typescript. not need for redundancy here.
It's a little different at the top with the `@param` (don't ask please)
```suggestion
   * @returns always `false`
```

2024-09-20 17:13 UTC, flx-sta commented on src/data/challenge.ts
> +  applyTrickRoom(isTrickRoom: Utils.BooleanHolder): boolean {
NIT:
Unused params should be prefixed with `_`
```suggestion
  applyTrickRoom(_isTrickRoom: Utils.BooleanHolder): boolean {
```

2024-09-20 17:13 UTC, flx-sta commented on src/data/challenge.ts
> +  applyTrickRoom(isTrickRoom: Utils.BooleanHolder): boolean {
NIT:
- Missing `override`
- Missing docs
- Missing scope (ppp)

2024-09-20 17:13 UTC, flx-sta commented on src/phases/turn-start-phase.ts
> +    applyChallenges(this.scene.gameMode, ChallengeType.TRICK_ROOM, speedReversed);
I think optimize this you should instead do that check before `orderedTargets.sort` is ran and adjust the sort function instead. Cause afaik the `reverse()` + a sort before takes quite some resources

2024-09-20 17:13 UTC, flx-sta commented on src/system/achv.ts
>    BREEDERS_IN_SPACE: new Achv("BREEDERS_IN_SPACE", "", "BREEDERS_IN_SPACE.description", "moon_stone", 100).setSecret(),
This is getting quite chaotic.
There should be a helper method on `scene.gameMode.challenges`.
Soemthing like
```ts
scene.gameMode.challenges.isActive(Challenges.TRICK_ROOM)
```

YOu should also probably spred the scene argument into 
```ts
(c, {gameMode: { challenges }}) => [...]
```
thus you only have to write `challenges.isActive(...)` instead of `scene.gameMode.challenges[...]`

2024-09-20 17:23 UTC, KimJeongSun commented on src/data/challenge.ts
> +  TRICK_ROOM,
ok i will put it there

2024-09-20 17:43 UTC, KimJeongSun commented on src/system/achv.ts
>    BREEDERS_IN_SPACE: new Achv("BREEDERS_IN_SPACE", "", "BREEDERS_IN_SPACE.description", "moon_stone", 100).setSecret(),
updated with gameMode.hasChallenge!

2024-09-20 17:58 UTC, KimJeongSun commented on src/phases/turn-start-phase.ts
> +    applyChallenges(this.scene.gameMode, ChallengeType.TRICK_ROOM, speedReversed);
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/d0921bbd-f2fb-4a8c-9c68-1c7ce2d1355b">

how about this? 
```

    // Next, a check for Trick Room is applied to determine sort order.
    const speedReversed = new Utils.BooleanHolder(false);
    this.scene.arena.applyTags(TrickRoomTag, speedReversed);
    applyChallenges(this.scene.gameMode, ChallengeType.TRICK_ROOM, speedReversed);

    // Adjust the sort function based on whether Trick Room is active.
    orderedTargets.sort((a: Pokemon, b: Pokemon) => {
      const aSpeed = a?.getEffectiveStat(Stat.SPD) || 0;
      const bSpeed = b?.getEffectiveStat(Stat.SPD) || 0;

      return speedReversed.value ? aSpeed - bSpeed : bSpeed - aSpeed;
    });
```

2024-09-20 20:37 UTC, flx-sta reviewed
Code looks good.
I'd have to do play-testing but don't have time right now

2024-09-21 02:48 UTC, KimJeongSun commented
> Code looks good. I'd have to do play-testing but don't have time right now

I will test it and update screenshots and video! thanks for the review!! 👍

2024-09-21 05:35 UTC, DayKev commented on src/phases/turn-start-phase.ts
>        const bSpeed = b?.getEffectiveStat(Stat.SPD) || 0;
```suggestion
      const aSpeed = a?.getEffectiveStat(Stat.SPD) ?? 0;
      const bSpeed = b?.getEffectiveStat(Stat.SPD) ?? 0;
```
Might as well change these while you're here.

2024-09-21 05:35 UTC, DayKev commented on src/data/challenge.ts
> +
```suggestion
```
Not sure why you're overriding this (nor why you set it to 0). For a challenge with only an on/off state, you can leave this out.

2024-09-21 06:35 UTC, Xavion3 commented
This should probably just turn on trick room as part of a generic arena tag handling method, instead of being exclusively trick room based.

2024-09-21 06:40 UTC, DayKev commented
If it's done this way then the Trick Room move can still have an effect.

2024-09-21 19:40 UTC, DayKev submitted a review, later dismissed

2024-09-22 04:46 UTC, Xavion3 commented
Yes, which probably isn't bad, but also you could still set it up to prevent that if you wanted.

2024-09-27 10:36 UTC, Xavion3 requested changes

2024-09-27 10:36 UTC, Xavion3 commented on src/data/challenge.ts
> +  TRICK_ROOM,
Challenges should not be this specific if at all possible, it should be able to just manage all arena tags.

2024-09-27 18:26 UTC, KimJeongSun commented on src/data/challenge.ts
> +  TRICK_ROOM,
I updated code. please review the changes when you available!

2024-09-30 11:37 UTC, Xavion3 commented
The challenge code should decide which tags are added, not the phase code. I'd elaborate a bit but reviewing on mobile is a pain. Feel free to ask on discord though, I can elaborate.

2024-10-01 05:26 UTC, KimJeongSun commented
> The challenge code should decide which tags are added, not the phase code. I'd elaborate a bit but reviewing on mobile is a pain. Feel free to ask on discord though, I can elaborate.

yeah, updated!

2024-10-05 00:27 UTC, Adri1 commented
Dont forget to move the English locales to [this new repo](https://github.com/pagefaultgames/pokerogue-locales) and delete them from this PR!

2024-10-06 10:22 UTC, Xavion3 commented on src/data/challenge.ts
> +   * Modifies the Arena Tags when a encounter starts
We should probably rename this to be more descriptive, not sure on what would be best though.

2024-10-15 14:20 UTC, Adri1 commented
@KimJeongSun  You can delete the locales from your PR, I added all of them here:
https://github.com/pagefaultgames/pokerogue-locales/pull/32

2024-10-27 03:44 UTC, KimJeongSun commented on src/data/challenge.ts
> +   * Modifies the Arena Tags when a encounter starts
if someone suggest better comment, i will update it

2025-06-14 01:16 UTC, closed without merging