[Feature] Show app version on title screen
pagefaultgames/pokerogue pull request #4344
Opened 2024-09-20 16:03 UTC by fransdhinta

## What are the changes the user will see?

- Now the title screen will display the app version.

## Why am I making these changes?

- Because users need to know which version is running this game
- As a user, I would be happy to know that the game version is updated, meaning the game is still maintained.
- An issue mentioned this feature https://github.com/pagefaultgames/pokerogue/issues/3909#issue-2495887371
## What are the changes from a developer perspective?

- Show app version below the title

### Screenshots/Videos

before:
![before](https://github.com/user-attachments/assets/e4910ab2-f47c-4d0b-b7eb-d5d1036830a0)
after:
![after](https://github.com/user-attachments/assets/92f28129-d57b-42ff-a5d7-f36a18508c2c)

## How to test the changes?

Just load the game, go to title screen

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-09-20 17:15 UTC, flx-sta requested changes

2024-09-20 17:15 UTC, flx-sta commented on src/ui/title-ui-handler.ts
> +      this.appVersionText.setText("Ver."+version);
a `v` should be sufficient

2024-09-20 17:27 UTC, fransdhinta commented on src/ui/title-ui-handler.ts
> +      this.appVersionText.setText("Ver."+version);
okay will adjust this

2024-09-20 17:35 UTC, flx-sta approved these changes

2024-09-20 22:28 UTC, DayKev approved these changes

2024-09-27 21:56 UTC, xsn34kzx approved these changes

2024-09-30 01:18 UTC, merged