[Localization] Team Star Translations
pagefaultgames/pokerogue pull request #4356
Opened 2024-09-21 02:18 UTC by Adri1

## What are the changes the user will see?
Translated Team Star-related texts

## Why am I making these changes?
To have Team Star-related texts translated

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?

2024-09-21 03:07 UTC, EnochG1 commented on src/locales/ko/bgm-name.json
> +  "battle_star_admin": "SV Team Star Boss",
```suggestion
  "battle_star_grunt": "SV 스타단 배틀",
  "battle_galactic_admin": "BDSP 갤럭시단 간부 배틀",
  "battle_skull_admin": "SM 스컬단 간부 배틀",
  "battle_oleana": "SWSH 올리브 배틀",
  "battle_star_admin": "SV 스타단 보스 배틀",
```

FYI to KO team, I chekced 'Team Star Boss' using '보스' instead of '간부'

2024-09-21 03:07 UTC, EnochG1 commented on src/locales/ko/bgm-name.json
> +  "battle_star_boss": "SV Cassiopeia Battle",
```suggestion
  "battle_star_boss": "SV 카시오페아 배틀",
```

2024-09-21 03:07 UTC, EnochG1 commented on src/locales/ko/trainer-classes.json
> +  "star_grunts": "Star Grunts"
```suggestion
  "star_grunt": "스타단 조무래기",
  "star_grunt_female": "스타단 조무래기",
  "star_grunts": "스타단 조무래기들"
```

2024-09-21 03:07 UTC, EnochG1 commented on src/locales/ko/trainer-names.json
> +  "cassiopeia": "Cassiopeia",
```suggestion
  "cassiopeia": "카시오페아",
```

2024-09-21 03:07 UTC, EnochG1 commented on src/locales/ko/trainer-names.json
> +  "eri": "Eri",
```suggestion
  "giacomo": "피나",
  "mela": "멜로코",
  "atticus": "추명",
  "ortega": "오르티가",
  "eri": "비파",
```

2024-09-21 03:07 UTC, EnochG1 commented on src/locales/ko/trainer-titles.json
> +  "star_boss": "Team Star Leader",
```suggestion
  "star_boss": "스타단 보스",
```

2024-09-21 03:07 UTC, EnochG1 commented on src/locales/ko/trainer-titles.json
> +  "star_admin": "Team Star Squad Boss"
```suggestion
  "star_admin": "스타단 군단 보스"
```

2024-09-21 04:04 UTC, josericardo-fo commented on src/locales/pt_BR/bgm-name.json
> +  "battle_star_admin": "SV Team Star Boss",
```suggestion
  "battle_star_grunt": "SV Batalha do Time Estrela",
  "battle_galactic_admin": "BDSP Batalha com Admin da Equipe Galáctica",
  "battle_skull_admin": "SM Batalha com Admin da Euipe Skull",
  "battle_oleana": "SWSH Batalha da Oleana",
  "battle_star_admin": "SV Chefe do Time Estrela",
```

2024-09-21 04:08 UTC, josericardo-fo commented on src/locales/pt_BR/bgm-name.json
> +  "battle_star_boss": "SV Cassiopeia Battle",
```suggestion
  "battle_star_boss": "SV Batalha da Cassiopeia",
```

2024-09-21 04:12 UTC, josericardo-fo commented on src/locales/pt_BR/dialogue.json
> +      "5": "An earful from Ms. Oleana is way worse than anything you can do!"
```suggestion
      "3": "Sou da Macro Cosmos Seguros! Já tem um seguro de vida?",
      "4": "Te encontrei! Nesse caso, é hora de uma batalha Pokémon!",
      "5": "Ouvir uma bronca da Srta. Oleana é bem pior do que qualquer coisa que você possa fazer!"
```

2024-09-21 04:13 UTC, josericardo-fo commented on src/locales/pt_BR/dialogue.json
> +      "5": "Battles didn't work... Only thing to do now is run!"
```suggestion
      "4": "Eu até troquei meu Pokémon...",
      "5": "As batalhas não funcionaram... A única coisa a fazer agora é fugir!"
```

2024-09-21 04:25 UTC, josericardo-fo commented on src/locales/pt_BR/dialogue.json
> +  },
```suggestion
  "star_grunt": {
    "encounter": {
      "1": "Nós somos a Equipe Estrela, garoto. Brilhamos tão forte que dói olhar pra nós!",
      "2": "Vamos com tudo pra cima de você - Hasta la vistaaar! ☆",
      "3": "Se você não sair rapidinho, vou ter que me defender. Entendeu?",
      "4": "Desculpe, mas se você não der meia-volta, amigo, vamos ter que te despachar!",
      "4_female": "Desculpe, mas se você não der meia-volta, amiga, vamos ter que te despachar!",
      "5": "Ótimo. Lá vem mais um qualquer para estragar o meu dia."
    },
    "victory": {
      "1": "Como é que EU estou vendo estrelas?!",
      "2": "Você é assustador, garoto. Se você se juntasse à Equipe Estrela, estaria no topo rapidinho!",
      "3": "Me defendi bem... Mas não foi o suficiente!",
      "4": "H-hasta la vistar... ☆",
      "5": "Eu não achei que o trabalho de recruta da Equipe Estrela seria uma tarefa tão pesada..."
    }
  },
  "giacomo": {
    "encounter": {
      "1": "Você realmente não pensa muito, né? Declarar guerra contra a Equipe Estrela é uma jogada muito ruim.",
      "2": "Vou tocar uma sinfonia do seu fracasso enquanto você cai e queima. Vamos começar a festa!"
    },
    "victory": {
      "1": "Acho que é isso...",
      "2": "Você transformou minha melodia em um lamento..."
    }
  },
  "mela": {
    "encounter": {
      "1": "Então você é o idiota que arrumou briga com a Equipe Estrela... Prepare-se para ser destruído.",
      "2": "Tudo bem, VAMOS LÁ! Vou explodir tudo!"
    },
    "victory": {
      "1": "Ugh. É assim que isso vai acabar? Que problema...",
      "2": "Usei tudo o que eu tinha... e agora apaguei."
    }
  },
  "atticus": {
    "encounter": {
      "1": "Você tem coragem de mostrar suas garras para a Equipe Estrela. Venha, então, vil criatura!",
      "2": "Esteja avisado—não te darei misericórdia! Em guarda!"
    },
    "victory": {
      "1": "Perdoem-me, meus amigos...",
      "2": "Você me venceu completamente. Mas sua vitória não me trouxe amargura—tamanha foi sua brilhante execução."
    }
  },
  "ortega": {
    "encounter": {
      "1": "Prometo que serei gentil, então não me culpe quando essa batalha te mandar chorando de volta para casa!",
      "2": "Vou apagar esse sorriso convencido do seu rosto com certeza! Você vai perder!"
    },
    "victory": {
      "1": "Ugh! Como eu pude PERDER! Que RAIVA!",
      "2": "Arrrrgggh! Essa sua força é tão INJUSTA."
    }
  },
  "eri": {
    "encounter": {
      "1": "Não importa quem você é. Vou derrubar qualquer um que tente destruir a Equipe Estrela!",
      "2": "Eu dou tudo de mim, e isso é uma promessa! Vamos ver quem fica de pé no final!"
    },
    "victory": {
      "1": "Me desculpem, pessoal...",
      "2": "Dei tudo de mim, mas não foi o suficiente—eu não fui o suficiente..."
    }
  },
```

2024-09-21 04:27 UTC, josericardo-fo commented on src/locales/pt_BR/dialogue.json
> +  },
```suggestion
  "star_boss_penny_1": {
  "encounter": {
    "1": "Eu sou a grande chefe da Equipe Estrela. Meu nome é Cassiopeia. \n$Agora, ajoelhe-se diante do poder esmagador da fundadora da Equipe Estrela!"
  },
  "victory": {
    "1": "... ... .."
  },
  "defeat": {
    "1": "Heh..."
  }
},
"star_boss_penny_2": {
  "encounter": {
    "1": "Não vou me segurar nesta batalha! Vou permanecer fiel ao código da Equipe Estrela! \n$Meu poder Veevee vai te reduzir a pó estelar!"
  },
  "victory": {
    "1": "...Agora acabou tudo."
  },
  "defeat": {
    "1": "Não posso te culpar por suas habilidades de batalha... Considerando como os chefes caíram diante de você."
  },
```

2024-09-21 04:32 UTC, josericardo-fo commented on src/locales/pt_BR/trainer-classes.json
> +  "star_grunts": "Star Grunts"
```suggestion
  "star_grunt": "Capanga da Equipe Estrela",
  "star_grunt_female": "Capanga da Equipe Estrela",
  "star_grunts": "Capangas da Equipe Estrela"
```

2024-09-21 04:32 UTC, josericardo-fo commented on src/locales/pt_BR/trainer-titles.json
> +  "star_boss": "Team Star Leader",
```suggestion
  "star_boss": "Líder da Equipe Estrela",
```

2024-09-21 04:33 UTC, josericardo-fo commented on src/locales/pt_BR/trainer-titles.json
> +  "star_admin": "Team Star Squad Boss"
```suggestion
  "star_admin": "Chefe de Esquadrão da Equipe Estrela"
```

2024-09-21 08:30 UTC, returntoice requested changes

2024-09-21 08:30 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "I gave it my all, but it wasn't enough—I wasn't enough..."
```suggestion
      "1": "우리는 우는 아이도 웃게 하는 스타단!",
      "2": "멤버들을 총동원해서 공격할 테니, 수고하셨스타~! ☆",
      "3": "빨리 돌아가지 그래? 아니면 방어권을 행사하는 수밖에 없다고?",
      "4": "미안하지만 돌아가지 않겠다면 힘으로라도 쫓아내 주겠어!",
      "4_female": "미안하지만 돌아가지 않겠다면 힘으로라도 쫓아내 주겠어!",
      "5": "아~ 또 사람이 와 버렸잖아."
    },
    "victory": {
      "1": "저 하늘의 별이 되는 건 나였네!?",
      "2": "스타단에 들어가면 다들 쫄아서 꼭대기에서 군림할 수 있는 거 아니었어?",
      "3": "나의 방어권이…!",
      "4": "수, 수고하셨스타… ☆",
      "5": "스타단 신입이 이렇게 귀찮은 일일 줄이야…"
    }
  },
  "giacomo": {
    "encounter": {
      "1": "스타단에게 싸움을 걸다니, 넌 정말 겁이 없구나?",
      "2": "레퀴엠을 들려줄 테니! 자! 파티를 시작하자고!"
    },
    "victory": {
      "1": "결국 이렇게 되는 건가…",
      "2": "레퀴엠을 들은 건 내 쪽이었네."
    }
  },
  "mela": {
    "encounter": {
      "1": "…우리에게 싸움을 걸었다는 녀석이 너냐? …터뜨려 주지.",
      "2": "좋아! …그럼, 한번 터뜨려 볼까!"
    },
    "victory": {
      "1": "이걸로 끝인 건가? …이런 이런.",
      "2": "그렇게 타오르고 타오르다… 완전히 연소해 버린 건가…"
    }
  },
  "atticus": {
    "encounter": {
      "1": "스타단을 해하려 하는 괘씸한 자는 독으로 해치울 뿐!",
      "2": "그럼, 진검승부를 펼쳐 봅시다!"
    },
    "victory": {
      "1": "동지들이여, 미안하오…",
      "2": "미련 하나 남지 않을 정도로 명백한 소인의 완패였소…"
    }
  },
  "ortega": {
    "encounter": {
      "1": "잔뜩 귀여워해 줄 테니까 울며불며 돌아갈 준비나 하라고!",
      "2": "어디 한번 여유롭게 굴어 보시지. 내가 이길 테니까!"
    },
    "victory": {
      "1": "어째서 내가 지는 건데!? 대체 왜! 어째서 진 거냐고~!!",
      "2": "젠장~! 너무 강하잖아! 비겁해!"
    }
  },
  "eri": {
    "encounter": {
      "1": "어디의 누가 됐든 스타단을 노리는 자는 박살 낼 뿐!",
      "2": "맞았으면 그저 맞받아칠 뿐!! 승리는 끝까지 서 있는 사람의 것이니까!!"
    },
    "victory": {
      "1": "얘들아… 미안해…",
      "2": "열심히… 했는데… 나는 역시… 부족했어…"
```

한국판 SV에는 수고하셨스타 뒤에 ☆ 표시가 없지만 여기서는 한 번 살려 보았습니다.

2024-09-21 08:30 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "1": "I can't fault you on your battle skills at all... Considering how the bosses fell at your hands."
```suggestion
      "1": "내가 바로 스타단의 진 보스, 카시오페아… \n$…진 보스의 힘 앞에 무릎 꿇게 만들어 주겠어!!"
    },
    "victory": {
      "1": "… … …"
    },
    "defeat": {
      "1": "후후…"
    }
  },
  "star_boss_penny_2": {
    "encounter": {
      "1": "승부인 이상, 봐주지 않아! 그것이 스타단의 규칙이니까! \n$브이브이 파워로 우주의 먼지로 만들어 주겠어!!"
    },
    "victory": {
      "1": "이걸로 진짜 끝이구나…"
    },
    "defeat": {
      "1": "군더더기가 없는 실력이네. 보스들이 당한 걸 생각해 보면 말이야."
```
"Considering how the bosses fell at your hands." 부분의 원문은 "No wonder how the bosses fell at your hands."인데, 의미가 크게 달라진 것은 아니지만 미묘한 뉘앙스 차이가 있어 살려서 고쳐 보았습니다.

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/bgm-name.json
> +  "battle_star_grunt": "SV Team Star Battle",
```suggestion
  "battle_star_grunt": "SV　戦闘！スター団",
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/bgm-name.json
> +  "battle_star_admin": "SV Team Star Boss",
```suggestion
  "battle_star_admin": "SV　戦闘！スター団ボス",
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/bgm-name.json
> +  "battle_star_boss": "SV Cassiopeia Battle",
```suggestion
  "battle_star_boss": "SV　戦闘！カシオペア",
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/trainer-classes.json
> +  "star_grunts": "Star Grunts"
```suggestion
  "star_grunt": "スター団の下っ端",
  "star_grunt_female": "スター団の下っ端",
  "star_grunts": "スター団の下っ端"
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/trainer-names.json
> +  "eri": "Eri",
```suggestion
  "giacomo": "ピーニャ",
  "mela": "メロコ",
  "atticus": "シュウメイ",
  "ortega": "オルティガ",
  "eri": "ビワ",
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/trainer-names.json
> +  "cassiopeia": "Cassiopeia",
```suggestion
  "cassiopeia": "カシオペア",
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/trainer-titles.json
> +  "star_boss": "Team Star Leader",
```suggestion
  "star_boss": "スター団ボス",
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/trainer-titles.json
> +  "star_admin": "Team Star Squad Boss"
```suggestion
  "star_admin": "スター団　組ボス"
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/dialogue.json
> +      "5": "An earful from Ms. Oleana is way worse than anything you can do!"
```suggestion
      "5": "オリーヴさまに　怒られたくないから　あきらめない！"
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/dialogue.json
> +      "4": "I found you! In that case, time for a Pokémon battle!",
```suggestion
      "4": "見つけた！　では　勝負だ！",
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/dialogue.json
> +      "5": "Battles didn't work... Only thing to do now is run!"
```suggestion
      "5": "かくれんぼも　ダメ！\n勝負も　ダメ！　逃げるしかない！"
```

2024-09-21 08:33 UTC, Chapybara-jp commented on src/locales/ja/dialogue.json
> +      "4": "I even switched up my Pokémon...",
```suggestion
      "4": "ポケモンを　入れ替えたのに……",
```

2024-09-21 08:59 UTC, CodeTappert commented on src/locales/de/bgm-name.json
> +  "battle_star_grunt": "SV Team Star Battle",
```suggestion
  "battle_star_grunt": "KAPU Vs. Team Star",
```

2024-09-21 09:04 UTC, CodeTappert commented on src/locales/de/bgm-name.json
> +  "battle_star_admin": "SV Team Star Boss",
```suggestion
  "battle_star_admin": "KAPU Vs. Team Star Vorstand",
```

2024-09-21 09:04 UTC, CodeTappert commented on src/locales/de/bgm-name.json
> +  "battle_star_boss": "SV Cassiopeia Battle",
```suggestion
  "battle_star_boss": "KAPU Vs. Cosima",
```

2024-09-21 09:07 UTC, CodeTappert commented on src/locales/de/dialogue.json
> +      "5": "An earful from Ms. Oleana is way worse than anything you can do!"
```suggestion
      "4": "Ich habe dich gefunden! Das bedeutet es ist Zeit für einen Pokémon-Kampf!",
      "5": "Eine Standpauke von Frau Olivia ist schlimmer als alles, was Sie tun können!"
```

2024-09-21 09:08 UTC, CodeTappert commented on src/locales/de/bgm-name.json
>    "battle_oleana": "SWSH Vs. Oleana",
```suggestion
  "battle_oleana": "SWSH Vs. Olivia",
```

2024-09-21 09:09 UTC, CodeTappert commented on src/locales/de/dialogue.json
> +      "5": "Battles didn't work... Only thing to do now is run!"
```suggestion
      "4": "Ich habe sogar meine Pokémon ausgetauscht...",
      "5": "Kämpfen hat nicht funktioniert... Jetzt können wir nur noch rennen!"
```

2024-09-21 09:18 UTC, CodeTappert commented on src/locales/de/dialogue.json
> +      "5": "Oh great. Here comes another rando to ruin my day."
```suggestion
      "1": "Wir sind von Team Star, wo jeder nach den Sternen greifen kann!",
      "2": "Wir werden mit voller Kraft auf dich losgehen - Hasta la vistar! ☆",
      "3": "Könntest du bitte wieder abzischen? Sonst muss ich dich davonjagen. Aus reinem Selbstschutz!",
      "4": "Es tut mir furchtbar leid, aber wenn du nicht umkehrst, könnte es ungemütlich für dich werden.",
      "4_female": "Es tut mir furchtbar leid, aber wenn du nicht umkehrst, könnte es ungemütlich für dich werden.",
      "5": "Och nee, nicht noch so ein Clown..."
```

2024-09-21 09:21 UTC, CodeTappert commented on src/locales/de/dialogue.json
> +      "5": "I didn't think grunt work for Team Star newbies would be this much of a chore..."
```suggestion
      "1": "Jetzt bin ich die Person, die Sterne sieht...",
      "2": "Jemand wie du wäre bei Team Star wahrscheinlich im Nullkommanichts an der Spitze.$Alle hätten Angst vor dir. Trotzdem...",
      "3": "Da war meine Selbstverteidigung wohl nicht gut genug...",
      "4": "H-hasta la vistar... ☆",
      "5": "Als neues Mitglied bei Team Star bekommt man echt nur die Drecksarbeit ab..."
```

2024-09-21 09:28 UTC, CodeTappert commented on src/locales/de/dialogue.json
> +      "2": "I burned through everythin' I had...and now I've sputtered out."
```suggestion
      "1": "Du willst dich echt mit Team Star anlegen? Bist du lebensmüde, oder was?",
      "2": "Weil ich so nett bin, leg ich zu deinem Abgang auch ein fettes Requiem auf!$Lass uns die Party in Schwung bringen"
    },
    "victory": {
      "1": " Besser hätte ich es auch nicht sagen können...",
      "2": "Uff, da hab ich schon bessere Shows gegeben... Schade, aber verloren ist verloren."
    }
  },
  "mela": {
    "encounter": {
      "1": "Du bist also diese Pfeife, die sich unbedingt mit uns anlegen will...$Dir werd ich zeigen, was mit Leuten passiert, die sich mit uns anlegen!",
      "2": "Yeah, lassen wir’s krachen!"
    },
    "victory": {
      "1": "Uff, ich hab echt versagt... Das war’s dann wohl...",
      "2": "Ich... brannte so sehr auf diesen Kampf. Doch jetzt ist meine Flamme erloschen..."
```

2024-09-21 09:37 UTC, CodeTappert commented on src/locales/de/dialogue.json
> +      "2": "I gave it my all, but it wasn't enough—I wasn't enough..."
```suggestion
      "1": "hr habt Team Star Leid angetan, unverschämter Schurke! Mein Gift soll Euer Niedergang sein!",
      "2": "Eure Bereitschaft zum Duell erfreut mich! Möge der Kampf ein ehrwürdiger sein!"
    },
    "victory": {
      "1": "Meine Gefährten... Vergebt mir...",
      "2": "Ich habe eine klare Niederlage erlitten, bei der Groll und Bitterkeit fehl am Platz wären."
    }
  },
  "ortega": {
    "encounter": {
      "1": "Wenn ich mit dir fertig bin, wirst du heulend nach Hause rennen!",
      "2": "Ich werde gewinnen, also spar dir deinen
überheblichen Auftritt!"
    },
    "victory": {
      "1": "Was?! Wie konnte ich nur verlieren? Warum? Warum nur?!",
      "2": "Graaaah! Du bist viel zu stark, das ist so was von unfair!"
    }
  },
  "eri": {
    "encounter": {
      "1": "Wer auch immer es auf Team Star abgesehen hat, wird zerschmettert!",
      "2": "Ich kann genauso gut austeilen wie einstecken! Wer am Ende noch steht, gewinnt."
    },
    "victory": {
      "1": "Leute, es tut mir so leid...",
      "2": "Ich habe alles gegeben... Ich bereue nichts..."
```

2024-09-21 09:37 UTC, CodeTappert commented on src/locales/de/dialogue.json
> +überheblichen Auftritt!"
```suggestion
      "2": "Ich werde gewinnen, also spar dir deinen überheblichen Auftritt!"
```

2024-09-21 09:41 UTC, CodeTappert commented on src/locales/de/dialogue.json
> +  },
```suggestion
      "1": "Ich bin Team Stars Big Boss. Mein Name ist Cassiopeia...$Die Gründerin von Team Star ist kampfbereit! Verneigt euch vor meiner unermesslichen Kraft!"
    },
    "victory": {
      "1": "... ... .."
    },
    "defeat": {
      "1": "Heh..."
    }
  },
  "star_boss_penny_2": {
    "encounter": {
      "1": "Ich werde mich in diesem Kampf nicht zurückhalten! Ich werde dem Kodex von Team Star treu bleiben!$Unsere Evoli-Power verwandelt euch in Sternenstaub!"
    },
    "victory": {
      "1": "Es ist vorbei..."
    },
    "defeat": {
      "1": "Du bist unfassbar stark. Kein Wunder, dass die anderen Bosse gegen dich verloren haben..."
    }
  },
```

2024-09-21 09:42 UTC, CodeTappert commented on src/locales/de/bgm-name.json
> +  "battle_star_admin": "KAPU Vs. Team Star Vorstand",
```suggestion
  "battle_star_admin": "KAPU Vs. Team Star Boss",
```

2024-09-21 09:42 UTC, CodeTappert commented on src/locales/de/trainer-classes.json
> +  "star_grunt": "Star Grunt",
```suggestion
  "star_grunt": "Rüpel von Team Star",
```

2024-09-21 09:43 UTC, CodeTappert commented on src/locales/de/trainer-classes.json
> +  "star_grunts": "Star Grunts"
```suggestion
  "star_grunt_female": "Rüpel von Team Star",
  "star_grunts": "Rüpel von Team Star"
```

2024-09-21 09:43 UTC, CodeTappert commented on src/locales/de/trainer-titles.json
> +  "star_boss": "Team Star Leader",
```suggestion
  "star_boss": "Team Star Big Boss",
```

2024-09-21 09:44 UTC, CodeTappert commented on src/locales/de/trainer-titles.json
> +  "star_admin": "Team Star Squad Boss"
```suggestion
  "star_admin": "Team Star Boss"
```

2024-09-21 09:44 UTC, CodeTappert commented on src/locales/de/trainer-names.json
> +  "eri": "Eri",
```suggestion
  "giacomo": "Pinio",
  "mela": "Irsa",
  "atticus": "Shugi",
  "ortega": "Otis",
  "eri": "Rioba",
```

2024-09-21 09:45 UTC, CodeTappert commented on src/locales/de/trainer-names.json
> +  "cassiopeia": "Cassiopeia",
```suggestion
  "cassiopeia": "Cosima",
```

2024-09-21 10:47 UTC, Adri1 commented on src/locales/fr/dialogue.json
> +      "5": "Quoi ? Toi aussi, t’es venu me casser les pieds ? C’est vraiment pas ma journée…"
```suggestion
      "5": "Quoi ? Toi aussi, t’es venu me casser les pieds ? C’est vraiment pas ma journée…",
```

2024-09-21 10:47 UTC, Adri1 commented on src/locales/fr/dialogue.json
> +      "2": "T’as beau avoir l’air sûr de toi, aujourd’hui, c’est moi qui vais gagner. Je te le garantis !"
```suggestion
      "2": "T’as beau avoir l’air sûr de toi, aujourd’hui, c’est moi qui vais gagner. Je te le garantis !",
```

2024-09-21 13:58 UTC, returntoice commented
The current font doesn't support the letter ☆ but ★
![캡처](https://github.com/user-attachments/assets/ae195cba-ea75-4951-a292-152ec7ffe738)
so all the stars must be changed into ★

2024-09-21 14:03 UTC, returntoice requested changes

2024-09-21 14:03 UTC, returntoice commented on src/locales/de/dialogue.json
> +      "2": "Wir werden mit voller Kraft auf dich losgehen - Hasta la vistar! ☆",
```suggestion
      "2": "Wir werden mit voller Kraft auf dich losgehen - Hasta la vistar! ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/de/dialogue.json
> +      "4": "H-hasta la vistar... ☆",
```suggestion
      "4": "H-hasta la vistar... ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/fr/dialogue.json
> +      "2": "Notre comité d’accueil va pas te faire de cadeau ! Hasta la vistaaar ! ☆",
```suggestion
      "2": "Notre comité d’accueil va pas te faire de cadeau ! Hasta la vistaaar ! ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/ja/dialogue.json
> +      "2": "We'll come at you full force - Hasta la vistaaar! ☆",
```suggestion
      "2": "We'll come at you full force - Hasta la vistaaar! ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/ja/dialogue.json
> +      "4": "H-hasta la vistar... ☆",
```suggestion
      "4": "H-hasta la vistar... ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "멤버들을 총동원해서 공격할 테니, 수고하셨스타~! ☆",
```suggestion
      "2": "멤버들을 총동원해서 공격할 테니, 수고하셨스타~! ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "4": "수, 수고하셨스타… ☆",
```suggestion
      "4": "수, 수고하셨스타… ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/pt_BR/dialogue.json
> +      "2": "Vamos com tudo pra cima de você - Hasta la vistaaar! ☆",
```suggestion
      "2": "Vamos com tudo pra cima de você - Hasta la vistaaar! ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/pt_BR/dialogue.json
> +      "4": "H-hasta la vistar... ☆",
```suggestion
      "4": "H-hasta la vistar... ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/zh_CN/dialogue.json
> +      "4": "H-hasta la vistar... ☆",
```suggestion
      "4": "H-hasta la vistar... ★",
```

2024-09-21 14:03 UTC, returntoice commented on src/locales/zh_CN/dialogue.json
> +      "2": "We'll come at you full force - Hasta la vistaaar! ☆",
```suggestion
      "2": "We'll come at you full force - Hasta la vistaaar! ★",
```

2024-09-21 14:14 UTC, returntoice approved these changes

2024-09-22 11:31 UTC, CodeTappert approved these changes

2024-09-22 13:56 UTC, EnochG1 approved these changes

2024-09-22 15:07 UTC, ben-lear approved these changes

2024-09-22 15:31 UTC, merged