[Enhancement]
pagefaultgames/pokerogue pull request #4358
Opened 2024-09-21 03:00 UTC by damocleas

## What are the changes the user will see?
New Splash text

## Why am I making these changes?
Wanted to finally clear out splash text suggestions channel in the main discord.

## What are the changes from a developer perspective?
Pretty much nothing, as all of the work needed was done in #4318 

### Screenshots/Videos

## How to test the changes?

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [Shut Up] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-21 17:53 UTC, flx-sta requested changes
Try using a JSON validator

https://duckduckgo.com/?t=ffab&q=JSON+validator&ia=answer

2024-09-21 17:53 UTC, flx-sta commented on src/locales/en/splash-messages.json
> +  "iPreferRarerCandies": "I prefer Rarer Candies!"
missing `comma`
```suggestion
  "iPreferRarerCandies": "I prefer Rarer Candies!",
```

2024-09-21 17:53 UTC, flx-sta commented on src/locales/en/splash-messages.json
> +  "notForTheFaintOfHeart": "Not for the faint of heart!"
missing `,`
```suggestion
  "notForTheFaintOfHeart": "Not for the faint of heart!",
```

2024-09-21 17:55 UTC, damocleas commented on src/locales/en/splash-messages.json
> +  "iPreferRarerCandies": "I prefer Rarer Candies!"
this was done across multiple commits then condensed, left as a draft so it was saved somewhere

2024-09-22 15:35 UTC, CodeTappert commented
Dont add placeholders. That will be done by lugiad in the localization pr

2024-09-23 20:53 UTC, damocleas commented
> Dont add placeholders. That will be done by lugiad in the localization pr

Ok! So once I'm finalized on this I'm good to just ask for it to be checked and merged and that will be separate?

2024-09-24 20:16 UTC, BooLin753 commented on src/locales/en/splash-messages.json
5.] "Everything is Stackable!" should be "Everything Is Stackable!" instead. "Is" is a verb so it should be capitalized in title formats.
17.] "Do People Read this?" should be "Do People Read This?"
28.] "Nothing Beats a Jelly-Filled Donut!" instead of "Nothing beats a Jelly-Filled Donut!"
38.] "Basic reading ability recommended!" changed to "Basic Reading Ability Recommended!"
40.] "Gambling not encouraged!" to "Gambling Not Encouraged!"
41.] "Don't forget to take a break!" changed to "Don't Forget To Take a Break!" ("To" capitalized in this case because it's part of an infinitive with "Take").
43.] "If it's not 100% accurate, it's 50%." changed to "If It's Not 100% Accurate, It's 50%."
44.] "Every loss is progress made!" changed to "Every Loss Is Progress Made!"
46.] "It's a feature, not a bug!" changed to "It's a Feature, Not a Bug!"
47.] "The eggs are not for eating!" changed to "The Eggs Are Not for Eating!"
48.] "7.8 out of 10, too many water biomes." changed to "7.8 out of 10, Too Many Water Biomes."
49.] "But nothing happened!" changed to "But Nothing Happened!"
50.] "The power of science is amazing!" changed to "The Power of Science Is Amazing!"
51.] "Free to play!" changed to "Free To Play!" (Again, because "To" forms an infinitive here.)
52.] "There's a time and place for everything!" changed to "There's a Time and Place for Everything!"
53.] "Now with shinier shinies!" changed to "Now With Shinier Shinies!" ("With" capitalized because prepositions that are four letters or longer are capitalized.)
54.] "Smiles go for miles!" changed to "Smiles Go for Miles!"
55.] "Certainly not dragon free" changed to "Certainly Not Dragon-Free!" (Need the hyphen here because it's a compound modifier.)
56.] "Have a nice day!" changed to "Have a Nice Day!"
58.] (Could capitalize this one, but I feel the lowercase works here stylistically. Just wanted to highlight it for consideration.)
60.] "Shiny odds higher than you think!" changed to "Shiny Odds Higher Than You Think!"
61.] "No false trades!" changed to "No False Trades!"
62.] "Not for profit!" changed to "Not for Profit!"
63.] "Time for your Daily Run!" changed to "Time for Your Daily Run!"
64 ] "More Eggs than a Daycare!" changed to "More Eggs Than a Daycare!"
65.] "There is no Safari Zone!" changed to "There Is No Safari Zone!"
66.] "Disclaimer: Harsh Sun does NOT give Vitamin D!" changed to "Disclaimer: Harsh Sun Does NOT Give Vitamin D!"
67.] "Who needs a map?" changed to "Who Needs a Map?"
68.] "Luxray is not a Dark Type!" changed to "Luxray Is Not a Dark-Type!" ("Dark-Type" is a compound modifier, so it should have a hyphen. This is also consistent with item descriptions such as the Dragon Fang's in main series games.)
69.] "Self-Destructive encounters!" changed to "Self-Destructive Encounters!"
70.] "Most options are viable!" changed to "Most Options Are Viable!"
73.] "Be aware of Passives!" changed to "Be Aware of Passives!"
74.] "As seen on the World-Wide Web!" changed to "As Seen on the World-Wide Web!"
78.] "Win with your favorites!" changed to "Win With Your Favorites!"
79.] "Also try PokéRogue! Wait.." changed to "Also Try PokéRogue! Wait..."
80.] "The way I see it, Kyogre is surrounded..." changed to "The Way I See It, Kyogre Is Surrounded..."
82.] "Not for the faint of heart!" changed to "Not for the Faint of Heart!"

2024-09-25 05:37 UTC, flx-sta approved these changes

2024-09-25 14:13 UTC, CodeTappert approved these changes

2024-09-25 14:13 UTC, merged