[Bugs/Balance] Fix various ME bugs and small balance adjustments
pagefaultgames/pokerogue pull request #4369
Opened 2024-09-21 20:02 UTC by ben-lear

2024-09-21 21:26 UTC, damocleas approved these changes

2024-09-21 22:10 UTC, CodeTappert approved these changes

2024-09-21 23:25 UTC, frutescens requested changes

2024-09-21 23:25 UTC, frutescens commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> +
Can't comment directly, but can 'getHighestStatPlayerPokemon()' and similar functions use isAllowedinBattle() instead? Just in case a player has an ineligible Pokemon in their party that has high/low stats/qualities.

2024-09-22 03:02 UTC, ben-lear commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> +
refactored all those methods to be more consistent now

2024-09-22 03:09 UTC, damocleas approved these changes

2024-09-22 03:10 UTC, frutescens approved these changes

2024-09-22 03:47 UTC, CodeTappert approved these changes

2024-09-22 03:47 UTC, merged