[Bug] [Localization] Added Snow Worker Keys and Dialogue for En, Es, It, Fr, De, Ko, / Suppressed Female
pagefaultgames/pokerogue pull request #4373
Opened 2024-09-22 04:49 UTC by Snailman11

## What are the changes the user will see?

-Snow Worker 
-Snow Worker will have translated dialogue in English, French, Spanish, Italian, German, and Korean.
-Brazilian Portuguese, ZH_CN, ZH_TW, and Japanese, have placeholder English dialogue.

-Removed the option for Snow Worker to spawn as female. It was using the female worker sprite as there actually is no female snow worker.

## Why am I making these changes?

Closes https://github.com/pagefaultgames/pokerogue/issues/4081

Link to Discord's Bug Report (Snow worker has no dialogue)
https://discord.com/channels/1125469663833370665/1281452532455047168

## What are the changes from a developer perspective?

-Added Dialogue Keys in **Dialogue.ts** to summon Single and Double Snow Worker "encounter" and "victory" lines.
Doubles Dialogue is not currently displayed but added doubles dialogues keys and lines if the doubles keys ever get called in the future.
-Added Singles and Doubles Defeat Lines in the language .jsons but no keys in dialogue.ts file
-Added Translated Single Snow worker "encounter" and "victory" lines for English, French, Spanish, German, Italian, and Korean in their respective JSON files
-Added placeholder English Text for Japanese, ZH_CN, ZH_TW, PT_BR in their respective JSON files
-setHasGenders("Worker Female") has been removed from trainer-config.ts .
-Added "snow_worker.json" and "snow_worker.png", copied from "snow_worker_m.json" and "snow_worker_m.png"
-snow_worker_f.png and snow_worker_f.json still exist.
-Doubles names can still be Female. As far as I can tell, this is due to Snow Worker pulling from the Worker Bulbapedia Page. Not sure it matters as the sprite could be considered gender neutral.

## How to test the changes?
**Overrides.ts**
```
const overrides = {
STARTING_LEVEL_OVERRIDE: 8,
OPP_SPECIES_OVERRIDE: Species.PIDGEY,
STARTING_WAVE_OVERRIDE: 2,
OPP_LEVEL_OVERRIDE: 1
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

Singles Dialogue
**Battle.ts**
```
[2]: new FixedBattleConfig().setBattleType(BattleType.TRAINER)
    .setGetTrainerFunc(scene => new Trainer(scene, TrainerType.SNOW_WORKER, TrainerVariant.DEFAULT)),
```
Doubles Dialogue
```
[2]: new FixedBattleConfig().setBattleType(BattleType.TRAINER)
    .setGetTrainerFunc(scene => new Trainer(scene, TrainerType.SNOW_WORKER, TrainerVariant.DOUBLE)),
```
### Screenshots/Videos

https://github.com/user-attachments/assets/346bb882-02f9-4f2c-919c-0774bd8c29c

https://github.com/user-attachments/assets/03282b37-97e1-448b-9d28-3e2b9583c57f

https://github.com/user-attachments/assets/fa394b1b-4e72-4520-af03-9c31b2f59d15

https://github.com/user-attachments/assets/7a7d5577-97da-4b71-aa28-17c6021c0118

https://github.com/user-attachments/assets/4053ff87-c657-4ddd-bdc0-3ccd7c367b5b

https://github.com/user-attachments/assets/4ae7be10-8838-4303-9e2e-404c009929f2

https://github.com/user-attachments/assets/27e387d4-b3bf-483a-85d1-4d7c6a131f7b

https://github.com/user-attachments/assets/69e4743c-0d60-4ecf-bfb7-4e365aa9e19c

https://github.com/user-attachments/assets/56797924-76f0-4a9e-8ee2-c17f785f4e7b

https://github.com/user-attachments/assets/979cf347-6958-4150-94f9-745345b2d440

https://github.com/user-attachments/assets/e3caf9a9-46b5-4956-910a-7143cd285a8a

https://github.com/user-attachments/assets/25b2c8ab-74f1-4317-85ad-8607f4660504

https://github.com/user-attachments/assets/208bdd11-cd85-4686-a97f-793eeb3ec564

https://github.com/user-attachments/assets/0df01886-691b-40d8-a361-6319f2537e93

https://github.com/user-attachments/assets/3625470b-b44d-4dae-bc1f-50f9e6c06888

https://github.com/user-attachments/assets/d315b063-6b95-49d8-a195-2a7f27fc0196

https://github.com/user-attachments/assets/4ec1d0a5-4b0e-4ee6-9fdc-eff3b79d1654

https://github.com/user-attachments/assets/d42289eb-f8c2-4ed8-9aef-cb596887a48d

https://github.com/user-attachments/assets/19118171-7129-4011-a46d-5eece2df844e

https://github.com/user-attachments/assets/f1a83c80-bbec-4f8d-8bd5-b2c9038db105

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-22 11:36 UTC, CodeTappert commented on src/locales/de/dialogue.json
> +	    "1": "Lass mich dir einen Ratschlag geben. Ist ein Pokémon gefroren, kannst du es wieder auftauen, indem du eine Attacke vom Typ Feuer auf es anwendest!"
Did you test this ingame? Seems very long and needs a $ i guess

2024-09-22 11:57 UTC, Adri1 commented
"-Removed the option for Snow Worker to spawn alone as female. It was using the female worker sprite as there actually is no female snow worker."
And why shoud they not exists in Rogue just because they dont in OG games? Personally I'm against removing them because of this reason.
+ You deleted females, bu you kept the female names.
![image](https://github.com/user-attachments/assets/6505647d-795e-44b9-8d95-7d9800739a13)
![image](https://github.com/user-attachments/assets/ed0ea00d-f494-41ec-a7ff-88bc5c070a4b)
![image](https://github.com/user-attachments/assets/ceac09cb-aba0-4a26-8a20-1d73fc0678e9)

2024-09-22 15:55 UTC, CodeTappert approved these changes

2024-09-22 16:09 UTC, Snailman11 commented
Here's what it looks like with \n$ appended to German and Spanish

https://github.com/user-attachments/assets/746d7d65-7eb9-45ba-8396-0bbd7ef32826


https://github.com/user-attachments/assets/c5db426a-1583-4230-8e4a-bfc49602a073

2024-09-22 18:33 UTC, Snailman11 commented
Here's how the Korean double text would display with ellipses by @returntoice 's suggestion

Doubles Encounter and Victory (changed . . . to ellipsis)

https://github.com/user-attachments/assets/3d01db38-cb3e-4986-a389-e786798fb402

Doubles Defeat (changed ... to ellipsis)

https://github.com/user-attachments/assets/06238dab-fe22-43e2-bf5d-a095e43c172f

Singles Defeat (added period)

https://github.com/user-attachments/assets/452a2109-8f30-4eca-8ea0-7b15f46c883d

2024-09-24 21:35 UTC, flx-sta requested changes

2024-09-24 21:35 UTC, flx-sta commented on src/locales/ja/dialogue.json
> +  },
No English placeholders anymore
```suggestion
```

2024-09-24 21:35 UTC, flx-sta commented on src/locales/pt_BR/dialogue.json
> +  },
No English placeholders anymore
```suggestion
```

2024-09-24 21:35 UTC, flx-sta commented on src/locales/zh_CN/dialogue.json
> +  },
No English placeholders anymore
```suggestion
```

2024-09-24 21:35 UTC, flx-sta commented on src/locales/zh_TW/dialogue.json
> +  },
No English placeholders anymore
```suggestion
```

2024-09-24 21:36 UTC, flx-sta commented
https://discord.com/channels/1125469663833370665/1281859097481711648/1288251320826068992

2024-09-25 16:27 UTC, SangaraSorama approved these changes

2024-09-25 17:20 UTC, CodeTappert approved these changes

2024-09-25 17:20 UTC, merged