[Moves] Implement Torment / Taunt / Imprison
pagefaultgames/pokerogue pull request #4378
Opened 2024-09-22 22:43 UTC by frutescens

## What are the changes the user will see?
Torment / Taunt / Imprison will be implemented. 

## Why am I making these changes?
Gotta do my part. 

## What are the changes from a developer perspective?
New Battler Tags for Torment / Taunt / Imprison
Checklist: 
- Torment
    - [x] Torment prevents the target from using the same move twice in a row. The effect lasts until the target is switched out. 
    - [ ] If a Pokémon has selected the move it used last turn and becomes affected with Torment, it may still use the move this turn (even if it moves after the user of Torment).
    - [ ] Moves such as [Rollout](https://bulbapedia.bulbagarden.net/wiki/Rollout_(move)) will still be fully executed under the effects of Torment.
    - [ ] Test
- Taunt
- Imprison

### Screenshots/Videos

https://github.com/user-attachments/assets/24587f85-97fd-42d7-bedd-61acbda73450

## How to test the changes?
Use overrides to emulate the conditions needed to use and activate the effects of these moves. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-09-24 02:47 UTC, ben-lear commented on src/data/arena-tag.ts
> +    this.source = arena.scene.getPokemonById(this.sourceId!)!;
is this actually a safe null assertion?

2024-09-24 02:47 UTC, ben-lear submitted a review, later dismissed

2024-09-24 02:47 UTC, ben-lear commented on src/data/arena-tag.ts
> +    this.source = arena.scene.getPokemonById(this.sourceId!)!;
is this actually a safe null assertion?

2024-09-24 03:09 UTC, frutescens commented on src/data/arena-tag.ts
> +    this.source = arena.scene.getPokemonById(this.sourceId!)!;
I think so since the existence of the Pokemon is required for a PostSummon Activation Ability. But, it doesn't hurt to add a check, so I'll add one.

2024-09-24 04:00 UTC, innerthunder requested changes
The effects of Aroma Veil aren't supported well by arena tags for a few reasons:
- What happens if the ability gets suppressed/ignored? You basically have to rewrite these checks within the arena tag's functions if you want to account for them correctly.
- Arena tags currently only support end-of-turn lapsing. If a Pokemon with Aroma Veil decides to switch out, the arena tag will still apply throughout the rest of the turn.

The implementation for Armor Tail/Dazzling/Queenly Majesty is probably the closest thing to how Aroma Veil *should* work, imo.

2024-09-24 20:56 UTC, flx-sta requested changes

2024-09-24 20:56 UTC, flx-sta commented on src/data/ability.ts
>    }
if you would have allowed array & non array and simply handle that in the constructor you didn't have to refactor all those single one calls.

```ts
constructor(immuneTagTypes: BattlerTagType | BattlerTagType[]) {
  super();

  this.immuneTagTypes = Array.isArray(immuneTagTypes) ? immuneTagTypes : [immuneTagTypes];
}
```

2024-09-24 20:56 UTC, flx-sta commented on src/data/arena-tag.ts
> +import Pokemon, { HitResult, PlayerPokemon, PokemonMove, EnemyPokemon } from "../field/pokemon";
adjust it to those `#app` imports if possible please

2024-09-24 20:56 UTC, flx-sta commented on src/data/arena-tag.ts
> +    console.log(side);
still necessary?

2024-09-24 21:11 UTC, frutescens commented on src/data/arena-tag.ts
> +    console.log(side);
Just removed it hahahah

2024-09-24 21:21 UTC, frutescens commented on src/data/ability.ts
>    }
Fixed!

2024-09-24 21:22 UTC, frutescens commented on src/data/arena-tag.ts
> +    this.source = arena.scene.getPokemonById(this.sourceId!)!;
Added a check!

2024-09-24 21:31 UTC, flx-sta reviewed
Just some NITs and questions

2024-09-24 21:31 UTC, flx-sta commented on src/data/arena-tag.ts
> +  lapse(_arena: Arena): boolean {
NIT:
Missing `override`

2024-09-24 21:31 UTC, flx-sta commented on src/data/arena-tag.ts
> +  activateTrap(pokemon: Pokemon): boolean {
NIT:
Missing `override`

2024-09-24 21:31 UTC, flx-sta commented on src/data/arena-tag.ts
> +  onRemove(arena: Arena): void {
NIT:
Missing `override`

2024-09-24 21:31 UTC, flx-sta commented on src/data/arena-tag.ts
> +      const party = !this.source.isPlayer() ? arena.scene.getPlayerField() : arena.scene.getEnemyField();
NIT:
You are using the exact same logic in `onRemove()` to get `party`.
You should consider preparing a private helper method for that to reduce redundancy

2024-09-24 21:31 UTC, flx-sta commented on src/data/arena-tag.ts
> +  }
NIT:
use destructuring to your advantage
```suggestion
  override onAdd({ scene }: Arena) {
    this.source = scene.getPokemonById(this.sourceId!)!;
    if (this.source) {
      const party = !this.source.isPlayer() ? scene.getPlayerField() : scene.getEnemyField();
      party?.forEach((p: PlayerPokemon | EnemyPokemon ) => {
        p.addTag(BattlerTagType.IMPRISON, 1, Moves.IMPRISON, this.sourceId);
      });
      scene.queueMessage(i18next.t("battlerTags:imprisonOnAdd", {pokemonNameWithAffix: getPokemonNameWithAffix(this.source)}));
    }
  }
```

2024-09-24 21:31 UTC, flx-sta commented on src/data/battler-tags.ts
> +  onAdd(pokemon: Pokemon) {
NIT:
- Missing `override`
- (Missing docs?)

2024-09-24 21:31 UTC, flx-sta commented on src/data/battler-tags.ts
> +  isMoveRestricted(move: Moves): boolean {
NIT:
- Missing `override`

2024-09-24 21:31 UTC, flx-sta commented on src/data/battler-tags.ts
> +  //Torment does not interrupt the move if the move is performed consecutively in the same turn and right after Torment is applied
Why is this random comment here?

2024-09-24 21:43 UTC, frutescens commented on src/data/battler-tags.ts
> +  //Torment does not interrupt the move if the move is performed consecutively in the same turn and right after Torment is applied
It's to explain the lack of an moveInterruptedText method

2024-09-24 21:58 UTC, flx-sta commented on src/data/battler-tags.ts
> +  //Torment does not interrupt the move if the move is performed consecutively in the same turn and right after Torment is applied
Wouldn't it make sense to move that into the TOP comment then so It shows up in the documentation of the Tag?

2024-09-24 22:03 UTC, frutescens commented on src/data/battler-tags.ts
> +  //Torment does not interrupt the move if the move is performed consecutively in the same turn and right after Torment is applied
Ah true!

2024-09-24 22:15 UTC, frutescens commented on src/data/arena-tag.ts
> +      const party = !this.source.isPlayer() ? arena.scene.getPlayerField() : arena.scene.getEnemyField();
Done!

2024-09-24 22:18 UTC, flx-sta commented on src/data/arena-tag.ts
> +  retrieveField(scene: BattleScene): PlayerPokemon[] | EnemyPokemon[] {
Since it's a helper it doesn't have to be `public`.
It can be `private`

2024-09-24 22:21 UTC, flx-sta commented on src/data/arena-tag.ts
> +  retrieveField(scene: BattleScene): PlayerPokemon[] | EnemyPokemon[] {
Also since you are calling `party?.[...]` I assume it can also be `undefined` (or `null`)?

2024-09-24 23:03 UTC, flx-sta requested changes

2024-09-24 23:03 UTC, flx-sta commented on src/data/arena-tag.ts
> +  constructor(sourceId: integer, side: ArenaTagSide) {
NIT: No more `integer` please
```suggestion
  constructor(sourceId: number, side: ArenaTagSide) {
```

2024-09-25 02:42 UTC, flx-sta approved these changes

2024-09-25 03:42 UTC, DayKev commented on src/data/battler-tags.ts
> +    return true;
```suggestion
    return !pokemon.isActive(true);
```

2024-09-25 03:42 UTC, DayKev commented on src/data/battler-tags.ts
> +   * This checks if the current move used is identical to the last used move with a MoveResult of SUCCESS/MISS
```suggestion
   * This checks if the current move used is identical to the last used move with a {@linkcode MoveResult} of `SUCCESS`/`MISS`
```

2024-09-25 03:42 UTC, DayKev commented on src/data/battler-tags.ts
> +    const isLockedIntoMove = allMoves[lastMove.move].hasAttr(ConsecutiveUseDoublePowerAttr);
What about Outrage/etc?

2024-09-25 03:42 UTC, DayKev commented on src/data/battler-tags.ts
> +   * @returns `true` if the move is a status move | `false` if not
```suggestion
   * @returns `true` if the move is a status move
```

2024-09-25 03:42 UTC, DayKev commented on src/data/battler-tags.ts
> +   * @returns `true` if the source is still active | `false` if not
```suggestion
   * @returns `true` if the source is still active
```

2024-09-25 03:42 UTC, DayKev commented on src/data/battler-tags.ts
> +   * @returns `true` if both conditions are met | `false` if either conditions are not met
```suggestion
   * @returns `false` if either condition is not met
```

2024-09-25 03:42 UTC, DayKev commented on src/data/battler-tags.ts
> +    });
```suggestion
    const sourceMoveset = this.source.getMoveset().map(m => m!.moveId);
```
I think this can be simplified like this. Test to make sure though.

2024-09-25 03:42 UTC, DayKev commented on src/enums/arena-tag-type.ts
> +  IMPRISON = "IMPRISON"
```suggestion
  IMPRISON = "IMPRISON",
```

2024-09-25 03:42 UTC, DayKev commented on src/locales/en/battler-tags.json
> +  "autotomizeOnAdd": "{{pokemonNameWIthAffix}} became nimble!"
```suggestion
  "autotomizeOnAdd": "{{pokemonNameWithAffix}} became nimble!"
```
Might as well fix Temp's mistake while you're here :plains:

2024-09-25 03:42 UTC, DayKev commented on src/test/abilities/aroma_veil.test.ts
> +    game.move.select(Moves.GROWL);
```suggestion
    game.move.select(Moves.GROWL, 1);
```
Technically you need to specify when it's the second Pokémon (though for the moment this doesn't matter because all player Pokémon are forced to have the same moveset when the moveset override is used).

2024-09-25 03:42 UTC, DayKev commented on src/test/abilities/aroma_veil.test.ts
> +import { Species } from "#app/enums/species";
```suggestion
import { Moves } from "#enums/moves";
import { Species } from "#enums/species";
```

2024-09-25 03:42 UTC, DayKev commented on src/test/abilities/aroma_veil.test.ts
> +import { ArenaTagType } from "#app/enums/arena-tag-type";
```suggestion
import { BattlerTagType } from "#enums/battler-tag-type";
import { ArenaTagType } from "#enums/arena-tag-type";
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +import { Species } from "#app/enums/species";
```suggestion
import { Moves } from "#enums/moves";
import { Species } from "#enums/species";
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +import { ArenaTagType } from "#app/enums/arena-tag-type";
```suggestion
import { BattlerTagType } from "#enums/battler-tag-type";
import { ArenaTagType } from "#enums/arena-tag-type";
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    const playerPokemon = game.scene.getPlayerPokemon();
```suggestion
    const playerPokemon = game.scene.getPlayerPokemon()!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    const playerMoveset = playerPokemon!.getMoveset().map(x => x?.moveId);
```suggestion
    const playerMoveset = playerPokemon.getMoveset().map(x => x?.moveId);
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    const imprisonBattlerTag = playerPokemon!.getTag(BattlerTagType.IMPRISON);
```suggestion
    const imprisonBattlerTag = playerPokemon.getTag(BattlerTagType.IMPRISON);
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    const move1 = playerPokemon?.getLastXMoves(1)[0]!;
```suggestion
    const move1 = playerPokemon.getLastXMoves(1)[0]!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    const playerPokemon1 = game.scene.getPlayerPokemon();
```suggestion
    const playerPokemon1 = game.scene.getPlayerPokemon()!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    const imprisonBattlerTag1 = playerPokemon1!.getTag(BattlerTagType.IMPRISON);
```suggestion
    const imprisonBattlerTag1 = playerPokemon1.getTag(BattlerTagType.IMPRISON);
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    const imprisonBattlerTag2 = playerPokemon2!.getTag(BattlerTagType.IMPRISON);
```suggestion
    const playerPokemon2 = game.scene.getPlayerPokemon()!;
    const imprisonBattlerTag2 = playerPokemon2.getTag(BattlerTagType.IMPRISON);
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    const enemyPokemon = game.scene.getEnemyPokemon();
```suggestion
    const playerPokemon = game.scene.getPlayerPokemon()!;
    const enemyPokemon = game.scene.getEnemyPokemon()!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    expect(enemyPokemon!.getTag(BattlerTagType.IMPRISON)).toBeDefined();
```suggestion
    expect(enemyPokemon.getTag(BattlerTagType.IMPRISON)).toBeDefined();
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    expect(enemyPokemon!.getTag(BattlerTagType.IMPRISON)).toBeUndefined();
```suggestion
    expect(enemyPokemon.getTag(BattlerTagType.IMPRISON)).toBeUndefined();
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/imprison.test.ts
> +    expect(playerPokemon?.isActive(true)).toBeFalsy();
```suggestion
    expect(playerPokemon.isActive(true)).toBeFalsy();
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/taunt.test.ts
> +import { Species } from "#app/enums/species";
```suggestion
import { Moves } from "#enums/moves";
import { Species } from "#enums/species";
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/taunt.test.ts
> +import { BattlerTagType } from "#app/enums/battler-tag-type";
```suggestion
import { BattlerTagType } from "#enums/battler-tag-type";
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/taunt.test.ts
> +    const playerPokemon = game.scene.getPlayerPokemon();
```suggestion
    const playerPokemon = game.scene.getPlayerPokemon()!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/taunt.test.ts
> +    const move1 = playerPokemon?.getLastXMoves(1)[0]!;
```suggestion
    const move1 = playerPokemon.getLastXMoves(1)[0]!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/taunt.test.ts
> +    const move2 = playerPokemon?.getLastXMoves(1)[0]!;
```suggestion
    const move2 = playerPokemon.getLastXMoves(1)[0]!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/torment.test.ts
> +import { Species } from "#app/enums/species";
```suggestion
import { Moves } from "#enums/moves";
import { Species } from "#enums/species";
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/torment.test.ts
> +import { BattlerTagType } from "#app/enums/battler-tag-type";
```suggestion
import { BattlerTagType } from "#enums/battler-tag-type";
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/torment.test.ts
> +    const playerPokemon = game.scene.getPlayerPokemon();
```suggestion
    const playerPokemon = game.scene.getPlayerPokemon()!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/torment.test.ts
> +    const move1 = playerPokemon?.getLastXMoves(1)[0]!;
```suggestion
    const move1 = playerPokemon.getLastXMoves(1)[0]!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/torment.test.ts
> +    const move2 = playerPokemon?.getLastXMoves(1)[0]!;
```suggestion
    const move2 = playerPokemon.getLastXMoves(1)[0]!;
```

2024-09-25 03:42 UTC, DayKev commented on src/test/moves/torment.test.ts
> +    const move3 = playerPokemon?.getLastXMoves(1)[0]!;
```suggestion
    const move3 = playerPokemon.getLastXMoves(1)[0]!;
```

2024-09-25 03:59 UTC, frutescens commented on src/data/battler-tags.ts
> +    const isLockedIntoMove = allMoves[lastMove.move].hasAttr(ConsecutiveUseDoublePowerAttr);
That's a good point. I added some other conditions to check. However, because Uproar hasn't been fully implemented, Torment can't be fully implemented so I marked it as partial

2024-09-25 07:30 UTC, DayKev submitted a review, later dismissed

2024-09-25 14:16 UTC, flx-sta approved these changes

2024-09-25 14:53 UTC, flx-sta commented
@frutescens looks like you broke some tests

2024-09-25 14:56 UTC, SangaraSorama approved these changes

2024-09-25 20:11 UTC, frutescens commented on src/data/battler-tags.ts
> + * Torment restricts the consecutive use of moves.
Yes - the documentation is just worded weirdly.

2024-09-25 21:23 UTC, flx-sta commented on src/data/battler-tags.ts
> +      this.source = pokemon.scene.getPokemonById(this.sourceId)!;
we really really really want to avoid adding even more bangs `!`
Please make this another check or something to avoid it

2024-09-25 21:27 UTC, frutescens commented on src/data/battler-tags.ts
> +      this.source = pokemon.scene.getPokemonById(this.sourceId)!;
fixed!

2024-09-25 21:28 UTC, SangaraSorama approved these changes

2024-09-25 21:31 UTC, Adri1 approved these changes

2024-09-25 21:52 UTC, flx-sta approved these changes

2024-09-25 21:52 UTC, merged

2024-09-25 22:32 UTC, frutescens commented on src/data/arena-tag.ts
> +  private source: Pokemon;
No b/c only one "layer" of Imprison is allowed + It will fail.

2024-09-25 23:10 UTC, frutescens commented on src/data/arena-tag.ts
> +    this.source = scene.getPokemonById(this.sourceId!)!;
TypeDocs still throws a fit about it b/c the private class variable this.source expects a Pokemon object.

2024-09-25 23:10 UTC, frutescens commented on src/data/arena-tag.ts
> +   * Helper function that retrieves the Pokemon effected
Fixed.