[Localization] localize reward gain with hard-coded numBerries(item count) in ME.
pagefaultgames/pokerogue pull request #4379
Opened 2024-09-22 23:36 UTC by EnochG1

## What are the changes the user will see?
English : No changes
Some languages : Not to see awkward reward message (with count).

## Why am I making these changes?
There's an issue with the script displaying awkwardly when multiple items are obtained during the ME events in some languages (specifically for Korean, Chinese, and Japanese).
It's grammatically correct to use a measure word when referring to multiple nouns.
![image](https://github.com/user-attachments/assets/a301e6ff-91c1-428b-b29b-de2b152b0c33)
`2 itemName` is grammatically weird in Korean, Chinese, Japanese.

## What are the changes from a developer perspective?
- Add new i18n key `rewardGainCount` instead of `rewardGain`.
- change files which uses rewardGain with hard-coded number.
```berries-abound-encounter.ts
trash-to-treasure-encounter.ts
```
- Translate them for each languages.

### Screenshots/Videos
TBD (After translator's review)

## How to test the changes?
Manually with overrides.ts

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-23 08:35 UTC, Chapybara-jp approved these changes

2024-09-23 09:04 UTC, Adri1 submitted a review, later dismissed

2024-09-23 14:10 UTC, 40chyan reviewed
extra spaces are not included in ZH

2024-09-23 14:10 UTC, 40chyan commented on src/locales/zh_CN/battle.json
> +  "rewardGainCount": "你获得了\n{{rewardCount}}个 {{modifierName}}!",
```suggestion
  "rewardGainCount": "你获得了\n{{rewardCount}}个{{modifierName}}!",
```

2024-09-23 14:10 UTC, 40chyan commented on src/locales/zh_TW/battle.json
> +  "rewardGainCount": "你獲得了\n{{rewardCount}}個 {{modifierName}}!",
```suggestion
  "rewardGainCount": "你獲得了\n{{rewardCount}}個{{modifierName}}!",
```

2024-09-23 23:35 UTC, Adri1 submitted a review, later dismissed

2024-09-25 10:34 UTC, Adri1 approved these changes

2024-09-25 10:50 UTC, Chapybara-jp submitted a review, later dismissed

2024-09-25 16:23 UTC, SangaraSorama approved these changes

2024-09-25 16:30 UTC, flx-sta requested changes
You should use the `{{count}}` interpolation instead (and also pass it in the code).

### Why?

The `count` interpolation supports the [Plurals feature](https://www.i18next.com/translation-function/plurals) of i18next. So if in the future the text needs to adjust acording to it being 1/2/3 ... items you can achieve that via passing `count`.

Check the link for more information.

2024-09-25 16:30 UTC, flx-sta commented on src/locales/en/battle.json
> +  "rewardGainCount": "You received\n{{rewardCount}} {{modifierName}}!",
When wanting to use the `count` to use plurals in `modifierName` you have to use the [i18next nesting feature](https://www.i18next.com/translation-function/nesting#passing-options-to-nestings)

```suggestion
  "rewardGainCount": "You received\n{{count}} $t(modifierName, {\"count\": {{count}} })!",
```

----

Se my general review comment for more info about this

2024-09-25 17:00 UTC, EnochG1 commented on src/locales/en/battle.json
> +  "rewardGainCount": "You received\n{{rewardCount}} {{modifierName}}!",
I changed rewardCount to count

2024-09-25 17:01 UTC, flx-sta commented on src/locales/en/battle.json
> +  "rewardGainCount": "You received\n{{rewardCount}} {{modifierName}}!",
the nested call is still necessary to make it future proof. soory :(

2024-09-25 17:07 UTC, flx-sta requested changes

2024-09-25 17:07 UTC, flx-sta commented on src/locales/de/battle.json
> +  "rewardGainCount": "Du erhältst {{count}} {{modifierName}}!",
```suggestion
  "rewardGainCount": "Du erhältst {{count}} $t(modifierName, {\"count\": {{count}} })!",
```

This is necessary so plural can be handled in the future.
e.g. instead of `1 Beeren` you can then control is to show `1 Beere`, `2 Beeren` etc.

2024-09-25 17:07 UTC, flx-sta commented on src/locales/en/battle.json
> +  "rewardGainCount": "You received\n{{count}} {{modifierName}}!",
```suggestion
  "rewardGainCount": "You received\n{{count}} $t(modifierName, {\"count\": {{count}} })!",
```

This is necessary for plural handling of modifier name

e.g instead of `1 Berries` it can show `1 Berry` and `2 Berries`

2024-09-25 17:07 UTC, flx-sta commented on src/locales/es/battle.json
> +  "rewardGainCount": "¡Has conseguido\n{{count}} {{modifierName}}!",
```suggestion
  "rewardGainCount": "¡Has conseguido\n{{count}} $t(modifierName, {\"count\": {{count}} })!",
```

For possible plural handling

2024-09-25 17:07 UTC, flx-sta commented on src/locales/fr/battle.json
> +  "rewardGainCount": "Vous recevez\n{{count}} {{modifierName}} !",
```suggestion
  "rewardGainCount": "Vous recevez\n{{count}} $t(modifierName, {\"count\": {{count}} }) !",
```

For possible plural handling

2024-09-25 17:07 UTC, flx-sta commented on src/locales/it/battle.json
> +  "rewardGainCount": "Ricevi\n{{count}} {{modifierName}}!",
```suggestion
  "rewardGainCount": "Ricevi\n{{count}} $t(modifierName, {\"count\": {{count}} })!",
```

For possible plural handling

2024-09-25 17:07 UTC, flx-sta commented on src/locales/ja/battle.json
> +  "rewardGainCount": "{{modifierName}}を　{{count}}個　手に入れた!",
```suggestion
  "rewardGainCount": "$t(modifierName, {\"count\": {{count}} })を　{{count}}個　手に入れた!",
```

For possible plural handling

DISCLAIMER: Does japanese need this kind of handling for plurals?

2024-09-25 17:07 UTC, flx-sta commented on src/locales/ko/battle.json
> +  "rewardGainCount": "{{modifierName}}[[를]]\n{{count}}개 손에 넣었다!",
```suggestion
  "rewardGainCount": "$t(modifierName, {\"count\": {{count}} })[[를]]\n{{count}}개 손에 넣었다!",
```

For possible plural handling

DISCLAIMER: Does `ko` need this kind of plural handling?

2024-09-25 17:07 UTC, flx-sta commented on src/locales/pt_BR/battle.json
> +  "rewardGainCount": "Você recebeu\n{{count}} {{modifierName}}!",
```suggestion
  "rewardGainCount": "Você recebeu\n{{count}} $t(modifierName, {\"count\": {{count}} })!",
```

For possible plural handling

2024-09-25 17:07 UTC, flx-sta commented on src/locales/zh_CN/battle.json
> +  "rewardGainCount": "你获得了\n{{count}}个{{modifierName}}!",
```suggestion
  "rewardGainCount": "你获得了\n{{count}}个$t(modifierName, {\"count\": {{count}} })!",
```

For possible plural handling

DISCLAIMER: Does `zh_CN` need this kind of plural handling?

2024-09-25 17:07 UTC, flx-sta commented on src/locales/zh_TW/battle.json
> +  "rewardGainCount": "你獲得了\n{{count}}個{{modifierName}}!",
```suggestion
  "rewardGainCount": "你獲得了\n{{count}}個$t(modifierName, {\"count\": {{count}} })!",
```
For possible plural handling

DISCLAIMER: Does `zh_TW` need this kind of plural handling?

2024-09-25 17:41 UTC, ben-lear commented on src/data/mystery-encounters/encounters/berries-abound-encounter.ts
> +        const doBerryRewards = async () => {
```suggestion
        const doBerryRewards = () => {
```

2024-09-25 17:41 UTC, ben-lear commented on src/data/mystery-encounters/encounters/berries-abound-encounter.ts
> +            const doBerryRewards = async () => {
```suggestion
            const doBerryRewards = () => {
```

2024-09-25 17:41 UTC, ben-lear commented on src/data/mystery-encounters/encounters/berries-abound-encounter.ts
> +            const doFasterBerryRewards = async () => {
```suggestion
            const doFasterBerryRewards = () => {
```

2024-09-25 17:45 UTC, flx-sta approved these changes

2024-09-25 17:48 UTC, flx-sta approved these changes

2024-09-25 17:50 UTC, Adri1 approved these changes

2024-09-25 17:53 UTC, EnochG1 commented
FYI,
some modifiers' name are already plural so in this PR I won't handle i18next's plurals
(test results in EN)
![image](https://github.com/user-attachments/assets/9f16dd6d-7a8d-473d-9523-8e30e9e06bb4)
![image](https://github.com/user-attachments/assets/8ac4d4d6-cb01-4b64-bbb4-6728767c4829)
![image](https://github.com/user-attachments/assets/ce7d614d-f1e7-4c14-a292-085ca3e88e85)

2024-09-25 18:02 UTC, CodeTappert approved these changes

2024-09-25 18:02 UTC, merged