Implements Merciless
pagefaultgames/pokerogue pull request #440
Opened 2024-05-03 23:35 UTC by NxKarim

- Implements `CritIfTargetPoisonedAbAttr`, which checks if the target is poisoned or badly poisoned, then guarantees a critical hit.

2024-05-04 02:20 UTC, Xavion3 requested changes

2024-05-04 02:20 UTC, Xavion3 commented on src/data/ability.ts
> +  }
Apply functions should return true if they did something and false otherwise. Also shouldn't line 1666 here be indented?

2024-05-05 08:11 UTC, NxKarim commented on src/data/ability.ts
> +  }
yeah, done

2024-05-14 20:13 UTC, TempsRay commented on src/data/ability.ts
> +export class CritIfTargetPoisonedAbAttr extends AbAttr {
Going forward, can you add doc on new classes?

2024-05-14 20:14 UTC, TempsRay reviewed
Code looks okay to me. Do you have any screenshots or video of testing this in action? And how it interacts with moves/abilities that blocks crits?

2024-05-14 20:56 UTC, NxKarim commented on src/data/ability.ts
> +export class CritIfTargetPoisonedAbAttr extends AbAttr {
Yes, code comments added.

2024-05-14 22:05 UTC, NxKarim commented
https://github.com/pagefaultgames/pokerogue/assets/43686802/b2e1446e-7dd1-4750-a5f4-9395ea5bc3ae

2024-05-15 02:11 UTC, bennybroseph requested changes
I think this should be a Crit if Status and pass in a status on the constructor. Could we modify this?

2024-05-15 15:58 UTC, shayebeadling commented
Going off of the point made above, you could even do a conditional crit attr, similar to how we use our MovePowerBoostAttr. It would be super clean, and allow any "crit if x" stuff to work the same way.
![image](https://github.com/pagefaultgames/pokerogue/assets/16782886/41dd0d6b-1956-4e97-9f7d-0c64bd33284a)

2024-05-15 16:03 UTC, bennybroseph commented
Nice, I do think that's the best solution

2024-05-19 14:06 UTC, bennybroseph approved these changes

2024-05-19 14:06 UTC, merged