[Feature][UI] Save Preview
pagefaultgames/pokerogue pull request #4410
Opened 2024-09-25 00:15 UTC by frutescens

## What are the changes the user will see?
Users can use Button.RIGHT to see more information about their runs. 

## Why am I making these changes?
I thought it would be neat. 

## What are the changes from a developer perspective?
Run Info uses an enum to determine its purpose and chooses to display/not display certain information. 
Trainer Parties are not displayed in this mode. Only the trainer sprites are.
Will clean up the code tomorrow. 

### Screenshots/Videos

## How to test the changes?
Press right on any session save slot. 
Needs pressure testing for trainers. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-09-25 02:46 UTC, flx-sta commented
Can we please consider calling it `session preview` or something?

cause generally in the context those are called sessions.
Save can be save-data too

2024-09-26 08:38 UTC, Opaque02 commented
I know you said you plan on cleaning up the code still so this is probably something you've already got planned but having some indication on how to open the preview/start a run would be good

2024-09-28 23:13 UTC, DayKev commented
The `>` should disappear for empty slots.

2024-09-30 13:48 UTC, MokaStitcher reviewed
We need to figure out the scrolling thing
I'll try and make the fix for the erased sessions first so that it doesn't cause even more confusion and/or conflicts (see discord ui thread)

2024-09-30 13:48 UTC, MokaStitcher commented on src/ui/run-info-ui-handler.ts
> +        this.parseWildSingleDefeat(enemyContainer);
```suggestion
        // Wild - Singles
        this.parseWildSingleDefeat(enemyContainer);
```

2024-09-30 13:48 UTC, MokaStitcher commented on src/ui/run-info-ui-handler.ts
> +        this.parseWildDoubleDefeat(enemyContainer);
```suggestion
        // Wild - Doubles
        this.parseWildDoubleDefeat(enemyContainer);
```

2024-09-30 13:48 UTC, MokaStitcher commented on src/ui/run-info-ui-handler.ts
> +  private loadTrainerSprites(enemyContainer: Phaser.GameObjects.Container) {
technically this loads and adds the trainer sprites to the view, so maybe `showTrainerSprites`?

2024-09-30 13:48 UTC, MokaStitcher commented on src/ui/save-slot-select-ui-handler.ts
> +          this.revertSessionSlot(this.cursor);
I think the way we would want to handle this is to save the last used cursor in a variable, and in setCursor if the cursor gets updated, call `revertSessionSlot(this.lastCursor)`
Because these changes have messed up a bit the way scrolling works especially when going up
If you want I can try and have a go at it, let me know

2024-09-30 13:48 UTC, MokaStitcher commented on src/ui/save-slot-select-ui-handler.ts
> +      const rightArrow = this.scene.add.image(0, 0, "cursor");
can we tint the arrow if the slot is empty? Or hide the arrow and maybe not offset the save file (that would look weird maybe)?

2024-09-30 17:58 UTC, frutescens commented on src/data/mystery-encounters/utils/encounter-phase-utils.ts
> +export function getMysteryEncounterKey(encounter: MysteryEncounterType | -1): string {
I agree - I asked @ben-lear to take a look at the function to see what he thought was the best way to go about things. Tagging him again to remind him

2024-09-30 17:59 UTC, frutescens commented on src/ui/save-slot-select-ui-handler.ts
> +      const rightArrow = this.scene.add.image(0, 0, "cursor");
I can hide the arrow and not offset the save file. Think that should be possible

2024-09-30 18:09 UTC, frutescens commented on src/ui/save-slot-select-ui-handler.ts
> +          this.revertSessionSlot(this.cursor);
That would be great <3

2024-09-30 21:54 UTC, frutescens commented on src/ui/run-info-ui-handler.ts
> +  private loadTrainerSprites(enemyContainer: Phaser.GameObjects.Container) {
wait shoot, i renamed the wrong function

2024-10-02 04:07 UTC, frutescens commented on src/data/mystery-encounters/utils/encounter-phase-utils.ts
> +export function getMysteryEncounterKey(encounter: MysteryEncounterType | -1): string {
I will replace the function with a ME-specific class variable holding the key, but until the locales module settles down, I'll keep this function but it will be replaced in this PR.

2024-10-03 13:45 UTC, MokaStitcher requested changes
Would be nice if there was the little success sound effect when pressing right to open a save preview. I don't think we need the buzz sound when we do it and there's no data though

otherwise lgtm, aside from the broken check for the current slot having data

2024-10-03 13:45 UTC, MokaStitcher commented on src/ui/save-slot-select-ui-handler.ts
> +        if (this.sessionSlots[this.cursor].hasData) {
```suggestion
        if (this.sessionSlots[cursorPosition].hasData) {
```

that should help!

2024-10-04 13:05 UTC, DayKev approved these changes

2024-10-04 13:18 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter.ts
> +   */
```suggestion
```
Tsdocs that are just restating the name of the variable/etc are useless.

2024-10-04 13:18 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter.ts
> +   * @returns
```suggestion
   * @param localizationKey the string used as the key
   * @returns `this`
```

2024-10-04 13:18 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +import { getPokeballAtlasKey } from "../data/pokeball";
```suggestion
import { getPokeballAtlasKey } from "#app/data/pokeball";
```

2024-10-04 13:18 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +import { MysteryEncounterType } from "#app/enums/mystery-encounter-type";
```suggestion
import { MysteryEncounterType } from "#enums/mystery-encounter-type";
```

2024-10-04 13:18 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +   * It edits runResultContainer, but most importantly - does not display the negative results of a Mystery Encounter or any details of a trainer's party
```suggestion
   * This function is used when the Run Info UI is used to preview a Session.
   * It edits {@linkcode runResultContainer}, but most importantly - does not display the negative results of a Mystery Encounter or any details of a trainer's party.
```

2024-10-04 13:18 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +      }
```suggestion

    if (this.runInfo.battleType === BattleType.WILD) {
      if (this.runInfo.enemyParty.length === 1) {
        this.parseWildSingleDefeat(enemyContainer);
      } else if (this.runInfo.enemyParty.length === 2) {
        this.parseWildDoubleDefeat(enemyContainer);
      }
```

2024-10-04 13:18 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +   * @param {Phaser.GameObjects.Container} enemyContainer a Phaser Container that should hold enemy sprites
```suggestion
   * Used by {@linkcode parseRunStatus} and {@linkcode parseTrainerDefeat}
   * @param enemyContainer a Phaser Container that should hold enemy sprites
```

2024-10-04 13:18 UTC, DayKev commented on src/ui/run-info-ui-handler.ts
> +   * Party Pokemon have their icons, terastalization status, and level shown.
```suggestion
   * This edits a container to represent a loss from a defeat by a trainer battle.
   * The trainers are placed to the left of their party.
   * Depending on the trainer icon, there may be overlap between the edges of the box or their party. (Capes...)
   *
   * Party Pokemon have their icons, terastalization status, and level shown.
   * @param enemyContainer - container holding enemy visuals and level information
```

2024-10-04 22:36 UTC, MokaStitcher reviewed
You'll have to merge with beta and run eslint
+
[issue I shared on discord with some double trainer battles](https://discord.com/channels/1125469663833370665/1267339517371875361/1291882956767498364) so still no approval sorry 😭 
<img width="697" alt="Screenshot 2024-10-04 at 23 59 19" src="https://github.com/user-attachments/assets/bd0d6d52-706a-491e-bc2c-a230b29d85e4">

2024-10-05 00:16 UTC, frutescens commented
Fixed! 
![image](https://github.com/user-attachments/assets/532c3c62-d800-4312-b6d0-2852a241d39d)

2024-10-05 08:25 UTC, DayKev approved these changes

2024-10-05 14:10 UTC, MokaStitcher approved these changes

2024-10-09 19:04 UTC, merged