Implement Guard Dog, attribute for abilities to give Intimidate immunity
pagefaultgames/pokerogue pull request #448
Opened 2024-05-04 04:48 UTC by madibye

Added 3 new ability effect "tags" (let me know if the way I did this was stupid; I'm still pretty new here), `ForceSwitchOutImmunityAbAttr` gives you immunity to moves that force you to switch out, such as Roar and the like. `InvertIntimidateAbAttr` makes Intimidate invert the stat change; giving you +1 attack instead of -1. And then `IntimidateImmunityAbAttr` makes you unable to be affected by Intimidate.

2024-05-04 04:56 UTC, Xavion3 requested changes

2024-05-04 04:56 UTC, Xavion3 commented on src/data/ability.ts
> +        const respectsAbilities: boolean = !pokemon.hasAbilityWithAttr(MoveAbilityBypassAbAttr)
Why are you checking for mold breaker in the intimidate code?

2024-05-04 04:56 UTC, Xavion3 commented on src/data/move.ts
> +      if (!this.user && target.hasAbilityWithAttr(ForceSwitchOutImmunityAbAttr) && !user.hasAbilityWithAttr(MoveAbilityBypassAbAttr))
You shouldn't need to check for mold breaker explicitly, test it since a bug if it fails, but hasAbilityWithAttr should ignore ignorable abilities during move resolution if the user has mold breaker.

2024-05-04 04:56 UTC, TempsRay commented
Instead of `InvertIntimidateAbAttr` can you make it a tag that just takes in a stat and gives it a buff? That way it can also be used by Rattled which gives +1 speed on being intimidated

2024-05-04 05:16 UTC, madibye commented on src/data/move.ts
> +      if (!this.user && target.hasAbilityWithAttr(ForceSwitchOutImmunityAbAttr) && !user.hasAbilityWithAttr(MoveAbilityBypassAbAttr))
Handled 70802040

2024-05-04 05:16 UTC, madibye commented on src/data/ability.ts
> +        const respectsAbilities: boolean = !pokemon.hasAbilityWithAttr(MoveAbilityBypassAbAttr)
Also removed this here 70802040

2024-05-04 05:17 UTC, madibye commented
> Instead of `InvertIntimidateAbAttr` can you make it a tag that just takes in a stat and gives it a buff? That way it can also be used by Rattled which gives +1 speed on being intimidated

@TempsRay this has been done and rattled's secondary effect implemented 70802040

2024-05-04 05:22 UTC, Xavion3 approved these changes

2024-05-04 05:25 UTC, TempsRay commented on src/data/ability.ts
> +      .attr(OverwriteIntimidateStatChangeAbAttr, [BattleStat.SPD], 1),
Rattled should still suffer the -1 atk debuff

2024-05-04 05:51 UTC, madibye commented on src/data/ability.ts
> +      .attr(OverwriteIntimidateStatChangeAbAttr, [BattleStat.SPD], 1),
Fixed that up, thanks for reminding me 5b8418c

2024-05-04 05:55 UTC, Xavion3 approved these changes

2024-05-04 19:50 UTC, madibye commented
Currently things are working a bit better, but there are some visual issues:
- For intimidate-immune abilities, the ability bar pops up *before* the intimidate pop-up, rather than after
- For guard dog's switch out immunity effect, the switch out animation still happens. No clue why.
Any help would be much appreciated here :)

2024-05-04 19:54 UTC, bennybroseph commented
> Currently things are working a bit better, but there are some visual issues:
> 
> * For intimidate-immune abilities, the ability bar pops up _before_ the intimidate pop-up, rather than after
> * For guard dog's switch out immunity effect, the switch out animation still happens. No clue why.
>   Any help would be much appreciated here :)

Could you create a formal issue in GitHub for these known bugs? That way they're tracked in an open ticket instead of this one which is closed

2024-05-05 14:09 UTC, madibye commented
> * For intimidate-immune abilities, the ability bar pops up _before_ the intimidate pop-up, rather than after

Worked around this in 9fdc5d6 by manually showing the ability bar in `PostSummonStatChangeAbAttr`, and then not showing the ability bar for the intimidate immunity, instead leaving that to the message box. It's not really perfect but it works for now.

2024-05-05 14:52 UTC, Flashfyre approved these changes

2024-05-05 14:52 UTC, merged