[QOL] Have Friendship Value be shown in summary
pagefaultgames/pokerogue pull request #4490
Opened 2024-09-28 13:12 UTC by CodeTappert

## What are the changes the user will see?

The current friendship value of a pokemon in the summary

## Why am I making these changes?

Because it is kinda annoying to not know how far you pokemon currently is till its evo

## What are the changes from a developer perspective?

I copied the code from candy icon and while talking to damo placed it where it is.

### Screenshots/Videos

(Still has the placeholder Icon!)
https://github.com/user-attachments/assets/9294ac07-fccb-439c-810c-13052a5b9a38

## How to test the changes?

Open the summary

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-28 13:18 UTC, CodeTappert commented
Draft till we have the icon from the art team

2024-09-28 13:24 UTC, CodeTappert commented on src/locales/de/pokemon-summary.json
> +  "friendship": "Freundschaft"
```suggestion
  }
```

2024-09-28 13:37 UTC, CodeTappert commented on src/locales/de/pokemon-summary.json
> +  "friendship": "Freundschaft"
```suggestion
  }
```

2024-09-30 17:34 UTC, CodeTappert commented
No real issues with this to discuss. It could only be problematic with super big pokemon. But thats the same for the candy counter so...

2024-09-30 18:08 UTC, torranx commented on src/ui/summary-ui-handler.ts
> +    this.friendshipText.setText(` ${this.pokemon?.friendship||"0"}/255`);
nit: formatting ( I should really update my pr :pokedollAh: )
```suggestion
    this.friendshipText.setText(`${this.pokemon?.friendship || "0"} / 255`);
```

2024-09-30 18:08 UTC, torranx commented on src/ui/summary-ui-handler.ts
> +    this.friendshipShadow.setCrop(0, 0, 16, 16 - (16 * ((this.pokemon?.friendship||0) / 255)));
nit
```suggestion
    this.friendshipShadow.setCrop(0, 0, 16, 16 - (16 * ((this.pokemon?.friendship || 0) / 255)));
```

2024-09-30 18:50 UTC, MokaStitcher requested changes
Just some doubts about whether we should tint the icon + a few nits

This is already the case for the candy tooltip, but might as well fix it while we're at it:
If you leave the summary with a tooltip open it doesn't get cleared. Should be easily fixable by calling `ui.hideTooltip()` in the handler's `clear()` function (I think. If not maybe don't worry about it)

https://github.com/user-attachments/assets/0792fb80-290c-43c4-ad03-425d3d1c13e5

2024-09-30 18:50 UTC, MokaStitcher commented on src/ui/summary-ui-handler.ts
> +    this.friendshipIcon.setTint(argbFromRgba(Utils.rgbHexToRgba(colorScheme[0])));
Should we really tint the icon like this? It makes it hard to see how full the heart actually is for some mons, like this Garchomp
<img width="250" alt="Screenshot 2024-09-30 at 20 29 19" src="https://github.com/user-attachments/assets/043b7a57-6f58-4701-8d3a-247f810b60d4"> <img width="250" alt="Screenshot 2024-09-30 at 20 29 25" src="https://github.com/user-attachments/assets/c5fee406-8a70-4868-84a6-3f083dbc3ba5">

2024-09-30 18:50 UTC, MokaStitcher commented on src/ui/summary-ui-handler.ts
> +      this.friendshipShadow.on("pointerout", () => (this.scene as BattleScene).ui.hideTooltip());
```suggestion
      this.friendshipShadow.on("pointerover", () => this.scene.ui.showTooltip("", `${i18next.t("pokemonSummary:friendship")}`, true));
      this.friendshipShadow.on("pointerout", () => this.scene.ui.hideTooltip());
```

Pretty sure this.scene is a BattleScene in UiHandlers. Just double check if possible, and might as well update it for the candy tooltip as well if it's the case

2024-09-30 18:50 UTC, MokaStitcher commented on src/ui/summary-ui-handler.ts
> +
```suggestion
```

bit too many empty lines here :p

2024-09-30 19:01 UTC, CodeTappert commented on src/ui/summary-ui-handler.ts
> +    this.friendshipIcon.setTint(argbFromRgba(Utils.rgbHexToRgba(colorScheme[0])));
No we should not! I just copied the code from candy and wanted remove that. Thank you

2024-09-30 19:02 UTC, CodeTappert commented on src/ui/summary-ui-handler.ts
> +    this.friendshipIcon.setTint(argbFromRgba(Utils.rgbHexToRgba(colorScheme[0])));
```suggestion
```

2024-09-30 19:25 UTC, torranx approved these changes

2024-09-30 19:57 UTC, MokaStitcher approved these changes

2024-09-30 19:58 UTC, MokaStitcher commented
For Temp, still some doubts about the friendship location [here](https://discord.com/channels/1125469663833370665/1289575708066058374/1290382247891046452), not the one to make the call of whether this is fine for now or not

2024-10-01 08:14 UTC, DayKev commented
Can you replace the image in the OP with an updated one?

2024-10-02 20:04 UTC, CodeTappert commented on src/locales/en/pokemon-summary.json
> +  "friendship": "Friendship"
```suggestion
  }
```

2024-10-02 20:10 UTC, CodeTappert commented
> Just some doubts about whether we should tint the icon + a few nits
> 
> This is already the case for the candy tooltip, but might as well fix it while we're at it: If you leave the summary with a tooltip open it doesn't get cleared. Should be easily fixable by calling `ui.hideTooltip()` in the handler's `clear()` function (I think. If not maybe don't worry about it)
> 
>  tooltip_clear.mov

The text staying is a problem with our hovers at all. Not with this specific one

2024-10-03 03:13 UTC, flx-sta approved these changes

2024-10-03 03:14 UTC, flx-sta commented
It begs the question how we going to update the sub-module reference to include the newly added keys

2024-10-03 05:52 UTC, DayKev approved these changes

2024-10-03 14:34 UTC, merged