[Balance] Increase Minimum BST Filter for Elite 4 / Champion Teams
pagefaultgames/pokerogue pull request #4501
Opened 2024-09-29 02:37 UTC by Blitz425

## What are the changes the user will see?
Elite 4 will improve very slightly in mon selection, Champions will now have a pool of way more competent Pokemon.

## Why am I making these changes?
The current minimum BST filter for Champions being 470 was criminally low for an important trainer, who is meant to be a secondary boss to the rival who currently sits with a minimum 540 BST filter in their config. This meant you would see oddities like Champion Red with a Simisear or Wallace with a Leavanny which are extremely unfitting in terms of power. 508 was chosen as a sweet spot in BST that targets slightly more premium Pokemon while fitting in some that aren't at exactly 510 like the Drillbur or Sinistea line. Elite 4 got a +10 BST increase to not limit the pool _too_ much but still cutting out a few weaker tier Pokemon.

## What are the changes from a developer perspective?
Changes in trainer-config, Elite 4 BST Filter 450 -> 460 / Champion BST Filter 470 -> 508

### Screenshots/Videos
An example of a weaker Pokemon spawning on a Champion (Wallace) with the current BST Filter
![image](https://github.com/user-attachments/assets/3c76fd33-6668-45a1-b1b8-03d1e4817411)

An example of the pool of Pokemon the new BST limit is around
![image](https://github.com/user-attachments/assets/9976fb32-1b33-4875-9c06-da4867da0483)

## How to test the changes?
Override to a E4 / Champion Wave

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-29 02:41 UTC, Tempo-anon commented
Please be more descriptive in the PR desc. List out exactly which Pokemon are lost from 450 -> 460 and 470 -> 508

2024-09-29 02:43 UTC, DayKev approved these changes

2024-09-29 02:44 UTC, Tempo-anon commented on src/data/trainer-config.ts
>      // Set species filter to only include species with a base total of 470 or higher.
Comment not updated 😠 might also be worth moving all magic numbers into constants

2024-09-30 02:09 UTC, Tempo-anon requested changes
1. I know you're doing the list in the description just because I asked, but that's not readable at all and feels like malicious compliance. At least use some bullet points to make that more readable.
2. The PR right now doesn't even increase the random Pokemon min BST of E4 (see my comment)
3. Not a blocker, but would be nice to move the magic numbers into constants so issues like #2 wouldn't happen
4. I personally find `508` such a weird number and there are a lot of very strong, cool, and unique Pokemon in the 500-508 range that I think would be a shame to have them excluded

2024-09-30 02:09 UTC, Tempo-anon commented on src/data/trainer-config.ts
> +      this.setSpeciesFilter(p => p.baseTotal >= 460);
This doesn't actually set the E4 random Pokemon min BST to 460 since all E4 have specialty types. The logic will go to the `if` portion of code up above which still has 450.

2024-09-30 02:51 UTC, DayKev commented
> 4. I personally find `508` such a weird number and there are a lot of very strong, cool, and unique Pokemon in the 500-508 range that I think would be a shame to have them excluded

We just need to reduce the BST of the mediocre 500 BST pokemon to be 499 :plains:

2024-09-30 02:56 UTC, DayKev approved these changes

2024-09-30 17:04 UTC, Tempo-anon commented
Going to be honest, I still think it should be 500 instead of 508 but whatever

2024-09-30 17:05 UTC, merged