[Move] Telekinesis + [Bug] Ingrain
pagefaultgames/pokerogue pull request #4506
Opened 2024-09-29 19:14 UTC by frutescens

## What are the changes the user will see?
Telekinesis will now be usable. 
Ingrain also properly grounds the user. 

## Why am I making these changes?
Gotta implement all the moves. 

## What are the changes from a developer perspective?
New Battler Tag for Telekinesis.
Gravity and Ingrain + Smack Down/1000 Arrows will have some related changes. 

Checklist:
- [ ] Telekinesis raises its target into the air for three turns. The target will be immune to Ground-type moves and Arena Trap. 
- [ ] This makes all moves used against the target (with the exception of one-hit knockout moves) bypass accuracy checks to always hit, unless the target is in the semi-invulnerable turn of a move such as Dig or Fly.
- [ ]  If a Pokémon under the effect of Telekinesis is affected by Ingrain or holds an Iron Ball, it becomes grounded (i.e. it becomes vulnerable to Ground-type moves, etc.), but the effect to make moves targeting it ignore accuracy checks still applies. 
- [ ] If a Pokémon under the effect of Telekinesis is hit by Smack Down or Thousand Arrows, the effect of Telekinesis disappears. 
- [ ] If Gravity comes into effect, the effect of Telekinesis disappears from all Pokémon.
- [ ] The move Telekinesis cannot affect a Pokémon under the effect of Ingrain, Smack Down, or Thousand Arrows. 
- [ ] While Gravity is in effect, Telekinesis cannot be selected.
- [x] Mega Gengar, Diglett, Dugtrio, Sandygast, and Palossand cannot be affected by the move Telekinesis, but a Pokémon transformed into one of these Pokémon can be affected. 
- [ ] If Mega Gengar is affected by Telekinesis before Mega Evolving or receives the effect via Baton Pass, the effect disappears; the other four will retain the effect if they obtain it via Baton Pass.

### Screenshots/Videos
TBD

## How to test the changes?
TBD

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-10-07 15:22 UTC, DayKev commented on src/data/move.ts
> +      //.condition((_user, target, _move) => target.getTag(BattlerTagType.INGRAIN) || target.getTag(BattlerTagType.IGNORE_FLYING)
```suggestion
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent?.getTag(BattlerTagType.FLOATING)).toBeDefined();
```suggestion
    expect(enemyOpponent.getTag(BattlerTagType.TELEKINESIS)).toBeDefined();
    expect(enemyOpponent.getTag(BattlerTagType.FLOATING)).toBeDefined();
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent).toBeDefined();
```suggestion
    const enemyOpponent = game.scene.getEnemyPokemon()!;
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent?.getTag(BattlerTagType.FLOATING)).toBeDefined();
```suggestion
    expect(enemyOpponent.getTag(BattlerTagType.TELEKINESIS)).toBeDefined();
    expect(enemyOpponent.getTag(BattlerTagType.FLOATING)).toBeDefined();
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent?.hp).toEqual(enemyOpponent?.getMaxHp()!);
```suggestion
    expect(enemyOpponent.isFullHp()).toBe(true);
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent).toBeDefined();
```suggestion
    const enemyOpponent = game.scene.getEnemyPokemon()!;
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent?.summonData.speciesForm?.speciesId).toBe(Species.DIGLETT);
```suggestion
    expect(enemyOpponent.getTag(BattlerTagType.TELEKINESIS)).toBeDefined();
    expect(enemyOpponent.getTag(BattlerTagType.FLOATING)).toBeDefined();
    expect(enemyOpponent.summonData.speciesForm?.speciesId).toBe(Species.DIGLETT);
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent).toBeDefined();
```suggestion
    const enemyOpponent = game.scene.getEnemyPokemon()!;
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent?.getTag(BattlerTagType.FLOATING)).toBeDefined();
```suggestion
    expect(enemyOpponent.getTag(BattlerTagType.TELEKINESIS)).toBeDefined();
    expect(enemyOpponent.getTag(BattlerTagType.FLOATING)).toBeDefined();
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent?.getTag(BattlerTagType.FLOATING)).toBeUndefined();
```suggestion
    expect(enemyOpponent.getTag(BattlerTagType.TELEKINESIS)).toBeUndefined();
    expect(enemyOpponent.getTag(BattlerTagType.FLOATING)).toBeUndefined();
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent).toBeDefined();
```suggestion
    const playerPokemon = game.scene.getPlayerPokemon()!;
    const enemyOpponent = game.scene.getEnemyPokemon()!;
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(enemyOpponent?.getTag(BattlerTagType.FLOATING)).toBeDefined();
```suggestion
    expect(enemyOpponent.getTag(BattlerTagType.TELEKINESIS)).toBeDefined();
    expect(enemyOpponent.getTag(BattlerTagType.FLOATING)).toBeDefined();
```

2024-10-07 15:22 UTC, DayKev commented on src/test/moves/telekinesis.test.ts
> +    expect(lastMoveResult).toBe(MoveResult.SUCCESS);
```suggestion
    expect(enemyOpponent.getTag(BattlerTagType.TELEKINESIS)).toBeDefined();
    expect(enemyOpponent.getTag(BattlerTagType.INGRAIN)).toBeDefined();
    expect(enemyOpponent.getTag(BattlerTagType.IGNORE_FLYING)).toBeDefined();
    expect(enemyOpponent.getTag(BattlerTagType.FLOATING)).toBeUndefined();
    expect(playerPokemon.getLastXMoves()[0].result).toBe(MoveResult.SUCCESS);
```

2024-10-07 15:31 UTC, frutescens commented on src/data/move.ts
> +      //.condition((_user, target, _move) => target.getTag(BattlerTagType.INGRAIN) || target.getTag(BattlerTagType.IGNORE_FLYING)
wait that was not supposed to be like that

2024-10-08 04:05 UTC, DayKev approved these changes

2024-10-08 21:52 UTC, PigeonBar commented on src/data/move.ts
> +    new StatusMove(Moves.TELEKINESIS, Type.PSYCHIC, 100, 15, -1, 0, 5)
```suggestion
    new StatusMove(Moves.TELEKINESIS, Type.PSYCHIC, -1, 15, -1, 0, 5)
```
According to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Telekinesis_(move)), Telekinesis should bypass accuracy checks.

2024-10-09 09:26 UTC, innerthunder requested changes

2024-10-09 09:26 UTC, innerthunder commented on src/data/battler-tags.ts
> +    pokemon.addTag(BattlerTagType.TELEKINESIS, 3, this.sourceMove);
`addTag` calls `onAdd`, so this line isn't needed

2024-10-09 09:26 UTC, innerthunder commented on src/data/battler-tags.ts
> +    }
```suggestion
    pokemon.removeTag(BattlerTagType.FLOATING);
```
Slight optimization; `removeTag` just doesn't do anything if a matching tag isn't found.

2024-10-09 09:26 UTC, innerthunder commented on src/data/battler-tags.ts
> +  }
I think it'd be simpler if Ingrain just had 2 different `AddBattlerTagAttrs` to add these tags separately. It'd basically remove the need for this override and the `onRemove` override. You could probably get away with doing the same thing for Telekinesis, but I'm less sure on that.

2024-10-09 09:26 UTC, innerthunder commented on src/data/move.ts
> +      .condition((_user, target, _move) => (target.species.speciesId !== Species.GENGAR && target.getFormKey() !== "mega"))
```suggestion
      .condition((_user, target, _move) => !(target.species.speciesId === Species.GENGAR && target.getFormKey() === "mega"))
```
The old condition causes TK to fail against all Mega-Evos

2024-10-09 09:26 UTC, innerthunder commented on src/field/pokemon.ts
> +    return !!this.getTag(GroundedTag) || (!this.isOfType(Type.FLYING, true, true) && !this.hasAbility(Abilities.LEVITATE) && !this.getTag(BattlerTagType.FLOATING) && !this.getTag(SemiInvulnerableTag)
```suggestion
    return !!this.getTag(GroundedTag) || (!this.isOfType(Type.FLYING, true, true) && !this.hasAbility(Abilities.LEVITATE) && !this.getTag(BattlerTagType.FLOATING) && !this.getTag(BattlerTagType.FLYING));
```

I feel like using the entire `SemiInvulnerableTag` class here introduces issues...

2024-10-10 05:36 UTC, frutescens commented on src/field/pokemon.ts
> +    return !!this.getTag(GroundedTag) || (!this.isOfType(Type.FLYING, true, true) && !this.hasAbility(Abilities.LEVITATE) && !this.getTag(BattlerTagType.FLOATING) && !this.getTag(SemiInvulnerableTag)
I didn't add the check for SemiInvulnerableTag in this PR so this change is out of scope for this PR.

2024-10-10 05:37 UTC, frutescens commented on src/data/battler-tags.ts
> +  }
I disagree since this shows that one tag is dependent on the other tag's presence. Same with Telekinesis since there are situations where a Pokemon can be floating, but still subject to Telekinesis.

2024-10-10 05:43 UTC, frutescens commented on src/data/battler-tags.ts
> +  }
Yeah, I think it should be fine to move them as part of move attr.

2024-10-10 05:56 UTC, innerthunder commented on src/data/battler-tags.ts
> +
```suggestion
```

2024-10-10 05:56 UTC, innerthunder commented on src/data/battler-tags.ts
> +
I don't think this is really needed, either (?). `resetSummonData`'s basically the only thing that removes these tags, anyway (well, that and fainting), and both events remove all tags in general

2024-10-11 02:12 UTC, frutescens commented on src/data/battler-tags.ts
> +
Fixed.

2024-10-11 03:21 UTC, innerthunder approved these changes

2024-10-11 03:44 UTC, Tempo-anon commented on src/data/battler-tags.ts
> +export class TelekinesisTag extends BattlerTag {
Since you're here, mind documenting FloatingTag and TelekinesisTag?

2024-10-11 03:44 UTC, Tempo-anon commented on src/data/move.ts
> +      .condition((_user, target, _move) => !(target.species.speciesId === Species.GENGAR && target.getFormKey() === "mega"))
Might want to add a comment about the known edge case of Gengar becoming mega but all this hardcoded inability to be affected thing is honestly quite silly and I would not be opposed to just removing it altogether. Not like anyone ever uses this move any way.

2024-10-11 16:29 UTC, frutescens commented on src/data/move.ts
> +      .condition((_user, target, _move) => !(target.species.speciesId === Species.GENGAR && target.getFormKey() === "mega"))
Ok, I'll add a comment there.

2024-10-11 17:39 UTC, DayKev commented on src/data/battler-tags.ts
> + * Moves that provide this effect are Magnet Rise and Telekinesis
```suggestion
 * Battler Tag that lifts the affected Pokemon into the air and provides immunity to Ground type moves.
```

2024-10-11 17:39 UTC, DayKev approved these changes

2024-10-11 18:27 UTC, innerthunder approved these changes

2024-10-11 21:44 UTC, merged