[Refactor] Move relevant files, tables etc to new balance folder
pagefaultgames/pokerogue pull request #4510
Opened 2024-09-29 22:51 UTC by Fontbane

## What are the changes the user will see?

- None

## Why am I making these changes?

- Walker wanted all the balance relevant files in one place so the balance team could be made codeowners

## What are the changes from a developer perspective?

- New folder `src/data/balance`
- Moved the following items:
  - data/egg-moves.ts
  - data/pokemon-evolutions.ts
  - data/pokemon-level-moves.ts
  - data/tms.ts
- New files:
  - `rates.ts` has shiny chances/rates and various chances for eggs
  - `starter-candy.ts` has candy costs for unlocks previously found in `starter-select-ui-handler.ts`, and the functions to access them

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-09-30 02:22 UTC, DayKev reviewed
https://github.com/Fontbane/pokerogue/pull/2

2024-09-30 16:00 UTC, damocleas approved these changes

2024-09-30 16:25 UTC, MokaStitcher reviewed
small nitpicks & suggestions, otherwise lgtm

2024-09-30 16:25 UTC, MokaStitcher commented on src/data/balance/starters.ts
> +  switch (value) {
```suggestion
export function getStarterValueFriendshipCap(starterCost: integer): integer {
  switch (starterCost) {
```

For clarity. Doc would be nice as well

2024-09-30 16:25 UTC, MokaStitcher commented on src/data/balance/starters.ts
> +export const speciesStarters = {
should be renamed `speciesStartersCosts` or similar imo, for clarity

2024-09-30 16:25 UTC, MokaStitcher commented on src/data/balance/starters.ts
> +export const starterPassiveAbilities = {
should this be moved to its own file? Almost everything else in this file is related to starter costs in some way, but this isn't. The other exception is the Pokerus count

2024-09-30 16:25 UTC, MokaStitcher commented on src/data/balance/starters.ts
> +  return starterCandyCosts[baseValue - 1].passive;
```suggestion
export function getPassiveCandyCount(starterCost: integer): integer {
  return starterCandyCosts[starterCost - 1].passive;
```

2024-09-30 16:25 UTC, MokaStitcher commented on src/data/balance/starters.ts
> +  return starterCandyCosts[baseValue - 1].costReduction;
```suggestion
export function getValueReductionCandyCounts(starterCost: integer): [integer, integer] {
  return starterCandyCosts[starterCost - 1].costReduction;
```

2024-09-30 16:25 UTC, MokaStitcher commented on src/data/balance/starters.ts
> +  return starterCandyCosts[baseValue - 1].egg;
```suggestion
export function getSameSpeciesEggCandyCounts(starterCost: integer): integer {
  return starterCandyCosts[starterCost - 1].egg;
```

2024-09-30 16:41 UTC, flx-sta commented on src/data/balance/starters.ts
> +  switch (value) {
```suggestion
export function getStarterValueFriendshipCap(starterCost: number): integer {
  switch (starterCost) {
```
Adding: no more `integer`

2024-09-30 16:54 UTC, flx-sta requested changes

2024-09-30 16:54 UTC, flx-sta commented on src/data/balance/rates.ts
> +/** Encounterable properties */
NIT: You might be better of using the `region` feature here:

```suggestion
// #region Encounterable properties
```

---

This will also show up in the IDE minimap
<img width="141" alt="image" src="https://github.com/user-attachments/assets/c5aa0895-5a2c-4029-8916-28967f33395f">

2024-09-30 16:54 UTC, flx-sta commented on src/data/balance/rates.ts
> +/** Egg properties */
NIT: You might be better of using the `region` feature here:

```suggestion
// #region Egg properties
```

---

This will also show up in the IDE minimap

<img width="132" alt="image" src="https://github.com/user-attachments/assets/8d7a5855-9232-4465-83c1-ba71da20e127">

2024-09-30 16:54 UTC, flx-sta commented on src/data/balance/starters.ts
> +  return starterCandyCosts[baseValue - 1].passive;
Adding: no more integers please
```suggestion
export function getPassiveCandyCount(starterCost: number): number {
  return starterCandyCosts[starterCost - 1].passive;
```

2024-09-30 16:54 UTC, flx-sta commented on src/data/balance/starters.ts
> +  return starterCandyCosts[baseValue - 1].costReduction;
Adding: no more `integer` please:

```suggestion
export function getValueReductionCandyCounts(starterCost: number): [number, number] {
  return starterCandyCosts[starterCost - 1].costReduction;
```

2024-09-30 16:54 UTC, flx-sta commented on src/data/balance/starters.ts
> +  return starterCandyCosts[baseValue - 1].egg;
Adding: no more `integer` please:

```suggestion
export function getSameSpeciesEggCandyCounts(starterCost: number): number {
  return starterCandyCosts[starterCost - 1].egg;
```

2024-09-30 16:54 UTC, flx-sta commented on src/data/balance/starters.ts
> +const starterCandyCosts: { passive: integer; costReduction: [integer, integer]; egg: integer; }[] = [
Please no more `integer`:
```suggestion
const starterCandyCosts: { passive: number; costReduction: [number, number]; egg: number; }[] = [
```

2024-09-30 16:55 UTC, flx-sta commented
Should the `256` here also represent some `rate`? 
https://github.com/pagefaultgames/pokerogue/blob/f470d6496ece4d50d975a559d960123ba8b9fa44/src/data/egg.ts#L349

2024-09-30 16:56 UTC, flx-sta commented
Should the `10` here also represent some rate?
https://github.com/pagefaultgames/pokerogue/blob/f470d6496ece4d50d975a559d960123ba8b9fa44/src/data/egg.ts#L489

2024-09-30 18:19 UTC, Fontbane commented on src/data/balance/rates.ts
> +/** Encounterable properties */
Did not know this was a thing in ts, cool

2024-09-30 18:59 UTC, MokaStitcher approved these changes
lgtm

2024-10-01 03:29 UTC, DayKev approved these changes

2024-10-01 04:05 UTC, damocleas approved these changes

2024-10-01 14:08 UTC, flx-sta submitted a review, later dismissed

2024-10-02 00:19 UTC, damocleas submitted a review, later dismissed

2024-10-02 00:49 UTC, DayKev approved these changes

2024-10-02 01:04 UTC, damocleas approved these changes

2024-10-02 11:44 UTC, MokaStitcher approved these changes

2024-10-02 13:20 UTC, merged