[Ability] Implement Unburden
pagefaultgames/pokerogue pull request #4534
Opened 2024-10-01 17:02 UTC by muscode13

## What are the changes the user will see?
Unburden implemented

## Why am I making these changes?
Ability is not implemented

## What are the changes from a developer perspective?
`UnburdenBerryAbAttr` - Triggers the speed boost once the user eats berries. It's based off how many they eat, so if the pokemon eats one berry they get +2, if they eat two they get +4 and so on.
`UnburdenDefStolenAbAttr` - This triggers if the user's item is stolen or lost when they are defending, in cases of Magician or moves like Thief, Knock Off and Pluck.
`UnburdenAtkStolenAbAttr` - This triggers when an item is lost during attacking, in cases like Pickpocket
`pokemon.turnData.itemsLost` - This variable tracks how many items the pokemon has lost during a turn. It is an integer that is used in `UnburdenDefStolenAbAttr` and `UnburdenAtkStolenAbAttr`. The integer gets decremented when an Unburden boost occurs. The integer gets incremented in various spots where items get stolen (Grip Claw, Moves, Abilities)

## How to test the changes?
- Use Pokemon with Unburden in the game and give them berries. Also have a pokemon with Magician steal items from them in double battles
- run `npm run test unburden`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR? - I believe the other Unburden PR was closed
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-10-02 04:45 UTC, Xavion3 commented
This should give a battler tag that doubles speed, not directly interact with combat stages.

2024-10-02 13:09 UTC, muscode13 commented
Will do!

2024-10-02 14:01 UTC, muscode13 commented
Alright I switched it to tags! I wasn't sure if it should keep doubling speed for each item lost, but I can implement that if you guys want.

2024-10-03 14:42 UTC, Tempo-anon requested changes
I think for simplicity's sake of implementation a battler tag is a fine way of going about implementation. Any item lost/used up will grant the full doubled speed boost.

Right now I believe it's missing some documentation and edge case interactions though.

2024-10-03 17:02 UTC, muscode13 commented on src/data/battler-tags.ts
> +    pokemon.setStat(Stat.SPD, pokemon.getStat(Stat.SPD, false) * 2, false);
I did onAdd here since I saw that Gorilla Tactics, which provides a similar boost to a stat, had it that way. I'm not sure if there is a functional difference though. I can change it to be persistent instead of an onAdd if that if preferred though

2024-10-03 17:03 UTC, muscode13 commented on src/data/battler-tags.ts
> +export class UnburdenTag extends AbilityBattlerTag {
I'll double check and add a test case for that. I assumed that abilities like that did the heavy lifting of the logic.

2024-10-03 17:20 UTC, Xavion3 commented on src/data/battler-tags.ts
> +export class UnburdenTag extends AbilityBattlerTag {
They'll make it so the game won't acknowledge the pokemon as having unburden while neutralised, but they can't remove existing things like this so easily.

2024-10-03 18:30 UTC, muscode13 commented
Alright I added documentation to the attributes, renamed them, added a test for neutralizing abilities, and accounted for getEffectiveStat

2024-10-03 19:05 UTC, Xavion3 commented
Don't double the speed twice, current it doubles in both getEffectiveStat and onAdd

2024-10-03 19:39 UTC, muscode13 commented
> Don't double the speed twice, current it doubles in both getEffectiveStat and onAdd

Oh right forgot about that. Got a fix, just trying to get the Grip Claw to actually steal in my tests now

2024-10-03 19:50 UTC, muscode13 commented
OK should only be doubling in one place now

2024-10-08 23:02 UTC, muscode13 commented
Any updates? Been waiting for a review for almost a week now

2024-10-09 18:42 UTC, Tempo-anon requested changes
I think functionally for the most part it is fine. The only real blocker I see is to have the neutralizing gas interaction. 

Should we also slap a (P) on unburden for the weird edge cases of gaining/losing this ability though?

2024-10-09 18:42 UTC, Tempo-anon commented on src/data/ability.ts
> + * Ability attribute for Unburden, triggers upon berry consumption
Is this just for consumption? Or is it also for all removal like stealing, fling, knocked off, and incinerate? The name of the class seems like it doesn't match up with the functionality (checking berries eaten)

2024-10-09 18:42 UTC, Tempo-anon commented on src/data/ability.ts
> +    return (pokemon: Pokemon) => pokemon.battleData.berriesEaten.length !== 0;
Is berriesEaten the right tag when there's other cases for berry removal?

2024-10-09 18:42 UTC, Tempo-anon commented on src/data/ability.ts
> + * Ability attribute for Unburden, triggers upon an item being lost while attacking (Pickpocket)
Also for things that remove an item when attacking? Things like fling, natural gift, etc

2024-10-09 18:42 UTC, Tempo-anon commented on src/field/pokemon.ts
> +      if (this.getTag(BattlerTagType.UNBURDEN)) {
This should have a check here to make sure there is no neutralizing gas on the field

2024-10-09 21:16 UTC, muscode13 commented on src/data/ability.ts
> + * Ability attribute for Unburden, triggers upon berry consumption
Just for a pokemon eating their berry. I'll reword the documentation. Other stuff like knock off and incinerate are handled by the UnburdenDefendingItemRemovedAbAttr, which tracks berry's lost through turnData.itemsLost. I did forget about fling, I'll double check that that causes a boost.

2024-10-10 00:35 UTC, muscode13 commented on src/field/pokemon.ts
> +      if (this.getTag(BattlerTagType.UNBURDEN)) {
Not sure if this is required. No other ability has a check for neutralizing gas, including slow start which is a couple lines above the Unburden speed modifier. I believe the canApplyAbility already addresses this in the Pokemon class

2024-10-10 00:36 UTC, muscode13 commented on src/data/ability.ts
> + * Ability attribute for Unburden, triggers upon an item being lost while attacking (Pickpocket)
I checked and all of them are unimplemented. The only one I found was stuff cheeks. To make them work with unburden, you'd just have to iterate the turnData.itemsLost when the move is used when they get implemented

2024-10-28 05:19 UTC, muscode13 commented
Refactored my implementation in a way that I believe is more in line with the rest of the codebase. Let me know what you think!

2024-11-02 20:11 UTC, innerthunder requested changes

2024-11-02 20:11 UTC, innerthunder commented on src/data/ability.ts
> +  pokemon: Pokemon, passive: boolean, simulated: boolean = false, args: any[]): Promise<void> {
```suggestion
  pokemon: Pokemon, passive: boolean, simulated: boolean = false, ...args: any[]): Promise<void> {
```
Matches other `applyAbAttrs` functions. This also means you don't have to pass empty arrays as arguments (e.g. in the new code in `battle-scene.ts`)

2024-11-02 20:11 UTC, innerthunder commented on src/field/pokemon.ts
> +        if (this.getTag(BattlerTagType.UNBURDEN)) {
```suggestion
        if (this.getTag(BattlerTagType.UNBURDEN) && !this.scene.getField(true).some(pokemon => pokemon !== this && pokemon.hasAbilityWithAttr(SuppressFieldAbilitiesAbAttr))) {
```
For the Neutralizing Gas interaction (please also add a unit test for neut gas Pokemon entering the field when Unburden has already activated)

2024-11-03 18:09 UTC, muscode13 commented on src/field/pokemon.ts
> +        if (this.getTag(BattlerTagType.UNBURDEN)) {
I'll commit this in, but I am confused why Unburden needs an explicit check for this when abilities like Gorilla Tactics and Slow Start do not.

2024-11-03 23:20 UTC, torranx commented on src/battle-scene.ts
> +                  if (source) {
sorry if this was answered before but are these necessary checks? iirc the attributes already does that

2024-11-03 23:20 UTC, torranx commented on src/test/abilities/unburden.test.ts
nit: can we add proper line breaks here please, its hard to read

2024-11-03 23:20 UTC, torranx commented on src/data/ability.ts
> +  pokemon: Pokemon, passive: boolean, simulated: boolean = false, ...args: any[]): Promise<void> {
I don't think parameter `passive` is necessary here since the attribute itself does not check whether or not the pokemon has passive?

2024-11-04 00:49 UTC, muscode13 commented on src/battle-scene.ts
> +                  if (source) {
If I don't check for source here I get a typescript error: Argument of type 'Pokemon | null | undefined' is not assignable to parameter of type 'Pokemon'. I could change the typing within my AbAttr to reflect this if you'd prefer that.

2024-11-04 00:55 UTC, muscode13 commented on src/battle-scene.ts
> +                  if (source) {
Also, source is the pokemon with Unburden here

2024-11-04 01:27 UTC, torranx commented on src/battle-scene.ts
> +                  if (source) {
ah I see, this is ok then 👍

2024-11-04 01:33 UTC, torranx reviewed
sorry for being nitpicky, but otherwise looks good to me

2024-11-04 01:33 UTC, torranx commented on src/test/abilities/unburden.test.ts
nit: consistent line break after each test cases

2024-11-04 01:44 UTC, torranx approved these changes
lgtm!

2024-11-04 02:17 UTC, innerthunder approved these changes

2024-11-04 02:58 UTC, merged