[Test] Fix Scale Shot flaky test
pagefaultgames/pokerogue pull request #4564
Opened 2024-10-03 19:13 UTC by Fontbane

## What are the changes the user will see?

## Why am I making these changes?

- Scale Shot unit test was incorrectly setting the player species instead of opponent species leading to undesired randomness
- Test would fail when a Fairy-type opponent generated

## What are the changes from a developer perspective?

- Overrides opponent species correctly

### Screenshots/Videos

## How to test the changes?

- `npm run test scale_shot`

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-10-03 19:43 UTC, torranx requested changes
could do some line breaks

2024-10-03 19:43 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>      const minccino = game.scene.getPlayerPokemon()!;
this is not guaranteed to spawn a minccino but a random mon instead since it is not specified in `startBattle()`

2024-10-03 19:43 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>      await game.phaseInterceptor.to(MoveEffectPhase);
this is another cause of a flaky test since it is not guaranteed which pokemon moves first.
see `setTurnOrder`

2024-10-03 19:43 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>      const minccino = game.scene.getPlayerPokemon()!;
same concern above

2024-10-03 19:43 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>      wobbuffet.setStat(Stat.HP, 100, true);
this should not write to the actual stats

2024-10-03 19:43 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>    it("unaffected by sheer force", async () => {
wouldnt this be simplified by spying on `calculateBattlePower`?
also shouldn't the scale shot user be the one having Sheer Force? its set to the enemy currently

2024-10-03 19:43 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>        .enemyAbility(Abilities.SHEER_FORCE)
this should be inside the specific test case

2024-10-03 19:43 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>        .enemyPassiveAbility(Abilities.STALL)
unnecessary passive abilities are set

2024-10-03 19:43 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>        .enemyMoveset(Moves.SKILL_SWAP)
its generally best to use SPLASH to avoid any interaction that may result in a different result

2024-10-03 19:45 UTC, Fontbane commented on src/test/moves/scale_shot.test.ts
>      await game.phaseInterceptor.to(MoveEffectPhase);
Forretress uses Mirror Coat which has negative priority

2024-10-03 19:46 UTC, Fontbane commented on src/test/moves/scale_shot.test.ts
>      const minccino = game.scene.getPlayerPokemon()!;
Wobbuffet has Stall

2024-10-03 19:47 UTC, Fontbane commented on src/test/moves/scale_shot.test.ts
>    it("unaffected by sheer force", async () => {
Turn one you use it normally, then Wobbuffet swaps Sheer Force onto you, then you use it with Sheer Force

2024-10-03 19:48 UTC, Fontbane commented on src/test/moves/scale_shot.test.ts
>        .enemyPassiveAbility(Abilities.STALL)
This guarantees Minccino moves first

2024-10-03 19:48 UTC, Fontbane commented on src/test/moves/scale_shot.test.ts
>        .enemyMoveset(Moves.SKILL_SWAP)
This is done to give Minccino Sheer Force for the second turn

2024-10-03 19:58 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>      await game.phaseInterceptor.to(MoveEffectPhase);
I guess that could work but then again a helper function exists for this which does rely on any abilities

2024-10-03 20:00 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>    it("unaffected by sheer force", async () => {
what's the need to use it normally on turn 1 when the test should only be testing that it doesn't affect sheer force? that is just unnecessary complication imo

2024-10-03 20:01 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>        .enemyMoveset(Moves.SKILL_SWAP)
see [comment here](https://github.com/pagefaultgames/pokerogue/pull/4564/files#r1786778827).
also if an override is for a specific test case, that should be placed there

2024-10-03 20:02 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>      const minccino = game.scene.getPlayerPokemon()!;
sorry concern being this is not guaranteed to spawn a mincinno

2024-10-04 15:12 UTC, Fontbane commented on src/test/moves/scale_shot.test.ts
>      const minccino = game.scene.getPlayerPokemon()!;
Integrated your suggestions, thanks

2024-10-04 16:36 UTC, torranx reviewed
looks a lot better, except for 1 nit

2024-10-04 16:36 UTC, torranx commented on src/test/moves/scale_shot.test.ts
>      await game.phaseInterceptor.to(DamagePhase);
I don't think these are needed?

2024-10-04 17:06 UTC, Fontbane commented on src/test/moves/scale_shot.test.ts
>      await game.phaseInterceptor.to(DamagePhase);
I believe the effect, if activated on the first hit, would apply on that first MoveEffectPhase so I just wait for the second hit. It's gonna go through all 5 anyway.

2024-10-04 17:55 UTC, torranx approved these changes

2024-10-06 19:01 UTC, ben-lear approved these changes

2024-10-06 19:26 UTC, innerthunder commented on src/test/moves/scale_shot.test.ts
>      await game.phaseInterceptor.to(DamagePhase);
There's no need for the `DamagePhase` line if that's the case.

2024-10-07 03:29 UTC, DayKev approved these changes

2024-10-07 03:29 UTC, merged