[Beta][Balance][Mystery Encounter] Balance changes and updates to various MEs
pagefaultgames/pokerogue pull request #4566
Opened 2024-10-03 23:35 UTC by ben-lear

Fiery Fallout:
- Option 1 remove free QD > replace with +1 SpDef/Spd
- Option 1 and 3, change guaranteed Charcoal rewards > randomly generated Attack Type Boost item
- Option 2, the burned pokemon's ability is permanently swapped to Heatproof
- Option 3, change requirements from 2 Fire Types > 1 Fire Type OR mon with Well-Baked Body/Heatproof/Flash Fire/etc.

Vitamin Dealer:
- Pricey Deal money cost updated from 3.5x to 5x

Expert Breeder:
- Egg ratios changed from 6:1 > 4:1 (player gets more eggs)
- Egg rewards give 5 Common eggs first, then the rest of points are divided into Rare/Common eggs based on above ratio
- Guaranteed Soothe Bell in fight rewards
- Change fight levels from STRONG to AVERAGE config

Trash to Treasure:
- Black Sludge also affects shop reroll cost by 2.5x now
- Change fight level modifier from 1x to 0.5x (slightly easier fight)

Delibirdy:
- Giving a Held Item option now rewards player with Healing Charm (was Berry Pouch)
- Giving a Reviver Seed now rewards player with a Berry Pouch (was Healing Charm)

An Offer You Can't Refuse:
- Option 1 Shiny Charm replaced with new item, Silver Pokeball. Functions the same as a Golden Pokeball, but lasts 100 floors only.

Weird Dream:
- Old Gateau changed to give +20 on 3 stats: hp/speed, atk/spatk, def/spdef
- Old Gateaus are given to every mon below 570 BST on the newly transformed team
- Level decrease option lowered from 12.5% to 10%
- Add another full option to the ME
  - Player battles against what their team would have been transformed into if they had picked Option 1
  - Enemy team will have the same held items, etc. (not stealable)
  - 2 Rogue/2 Ultra/2 Great rewards (same as brutal Mysterious Challengers)

2024-10-03 23:37 UTC, f-fsantos requested changes
Frozen until my approval

2024-10-04 15:50 UTC, Fontbane commented
On breaking changes:

1. We should use version migration system to avoid this
2. I'm not sure I like mints being tied to an ME class to begin with. Can CustomPokemonData just be moved?

2024-10-05 21:01 UTC, CodeTappert approved these changes

2024-10-08 02:55 UTC, DayKev commented on src/data/mystery-encounters/mystery-encounter-requirements.ts
> +      return partyPokemon.filter((pokemon) => this.requiredAbilities.some((ability) => pokemon.getAbility().id === ability || pokemon.getPassiveAbility().id === ability));
Shouldn't these be using `hasAbility(ability)`?

2024-10-08 02:55 UTC, DayKev commented on src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
> + * @param ability
```suggestion
```

2024-10-08 02:55 UTC, DayKev commented on src/modifier/modifier.ts
> +   * @param count
```suggestion
```

2024-10-08 02:55 UTC, DayKev commented on src/modifier/modifier.ts
> +   * @param count {@linkcode Utils.IntegerHolder} that holds the resulting shop item reward count
```suggestion
   * Increases the current rewards in the battle by the `stackCount`.
   * @returns `true` if the shop reward number modifier applies successfully
   * @param count {@linkcode NumberHolder} that holds the resulting shop item reward count
```

2024-10-08 02:55 UTC, DayKev commented on src/phases/select-modifier-phase.ts
> +    const baseMultiplier = Math.min(Math.ceil(this.scene.currentBattle.waveIndex / 10) * baseValue * Math.pow(2, this.rerollCount) * multiplier, Number.MAX_SAFE_INTEGER);
```suggestion
    const baseMultiplier = Math.min(Math.ceil(this.scene.currentBattle.waveIndex / 10) * baseValue * (this.rerollCount ** 2) * multiplier, Number.MAX_SAFE_INTEGER);
```

2024-10-08 02:56 UTC, DayKev commented
> 2. I'm not sure I like mints being tied to an ME class to begin with. Can CustomPokemonData just be moved?

Agreed, if `CustomPokemonData` is now no longer used only by MEs then it should be moved to a more general location.

2024-10-21 15:42 UTC, Tempo-anon commented
Closing in favor of https://github.com/pagefaultgames/pokerogue/pull/4700 which has resolved merge conflicts

2024-10-21 15:42 UTC, closed without merging