[Balance] Evil Admin Fixes / Slight Magma/Flare Grunt Update
pagefaultgames/pokerogue pull request #4577
Opened 2024-10-04 18:39 UTC by Blitz425

## What are the changes the user will see?
Magma Grunts will have a chance to spawn with a Toedscool
Magma Admins will no longer have Barboach, now has a chance to spawn with Toedscool instead
Aqua Admins now have a chance to spawn with Barboach
Flare Grunts will have a chance to spawn with a Foongus
Xerosic will no longer have a chance to spawn with 2 Malamars, now has a chance to spawn with Amoongus instead

## Why am I making these changes?
Barboach was meant to be removed from the Magma pool entirely alongside Grunts and instead put in the Aqua pools, this was missed with the admins though so I am replacing it with Toedscool to parallel Team Aqua members getting access to Tentacruel. Xerosic was able to spawn with two Malamars since he has one as his signature and Inkay was mistakenly left in the admin pools, so it is now replaced with Foongus to reference the Pokeball Factory from XY. Both of these Pokemon were also added to the grunt pools for consistency.

## What are the changes from a developer perspective?
Trainer-Config

Magma Grunts
- Toedscool added to Rare pools

Magma Admins
- Barboach -> Toedscool

Aqua Admins
- Barboach added to Common pools

Flare Grunts
- Foongus added to Uncommon pools

Flare Admins
- Inkay -> Foongus

### Screenshots/Videos

## How to test the changes?
Overrides

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-10-04 19:16 UTC, damocleas approved these changes

2024-10-04 20:02 UTC, f-fsantos requested changes
freeze

2024-10-04 20:19 UTC, Tempo-anon commented on src/data/trainer-config.ts
> -        [TrainerPoolTier.COMMON]: [ Species.FLETCHLING, Species.LITLEO, Species.INKAY, Species.HELIOPTILE, Species.ELECTRIKE, Species.SKORUPI, Species.PURRLOIN, Species.CLAWITZER, Species.PANCHAM, Sp
This removes Malamar out of Bryony's possible mons, is that intentional? It wouldn't affect Xerosic since there should be some deduplication code now

2024-10-05 21:00 UTC, CodeTappert submitted a review, later dismissed

2024-10-14 01:56 UTC, Blitz425 commented
This PR initially was set to change Inkay off Flare Admins due to the deduplication code not accounting for set Pokemon but https://github.com/pagefaultgames/pokerogue/pull/4585 addresses this issue, so the Inkay change has been reverted.

2024-10-14 02:06 UTC, DayKev commented on src/data/trainer-config.ts
> -      p.setBoss(true, 2);
Shouldn't the `p.setBoss` stay so that Sylveon will be a boss pokemon?

2024-10-14 02:16 UTC, damocleas approved these changes

2024-10-14 02:16 UTC, DayKev approved these changes

2024-10-15 09:17 UTC, merged