Implement Form Localisation
pagefaultgames/pokerogue pull request #458
Opened 2024-05-04 18:08 UTC by Kiriox94

Implementation of the ability to translate pokemon form, not being very advanced in the game I wasn't able to test if it worked well.

2024-05-04 18:12 UTC, Madmadness65 commented on src/locales/en/pokemon-form.ts
> +    "sinisrchaMasterpiece": "Masterpiece Form",
Minor nitpick, all instances of Sinistcha's Masterpiece Form has the typo `sinisrcha`.

2024-05-04 18:15 UTC, Flashfyre requested changes

2024-05-04 18:15 UTC, Flashfyre commented on src/plugins/i18n.ts
> +        pokemonForm: enPokemonForm,
Everywhere you order this, it should go after Pokemon, not at the end.

2024-05-04 18:15 UTC, Flashfyre commented on src/locales/de/pokemon-form.ts
> +    "LegendaryHeroesHero": "Hero of Many Battles",
L should not be capital. Also, fix typo in comment

2024-05-05 10:42 UTC, Adri1 commented
Are these form names supposed to be paired with Pokémon names, or just displayed by themselves? Because if paired with Pokémon names, I would like to adress a potential word order issue.
In English, the name of the form is always **before** the name of the Pokémon.
But in languages like French, it's mostly placed **after** the name of the Pokémon, with a few exceptions like "Méga", "Primo"or "Ultra", always placed before.

Furthermore, if they are supposed to be paired with Pokémon names AND be used by themselves, so I'd like to point out that some form comes with extra features when paired with a Pokémon name. For example "Méga", "Primo" and "Ultra" comes with an extra dash instead of a space when pair with a Pokémon name like :
-Méga-Steelix
-Primo-Groudon
-Ultra-Necrozma
So either in the translation we write "Méga" and it would be incorret when paired with a Pokémon name, or we write "Méga-" and would be incorrect too if it is not

2024-05-05 10:50 UTC, Kiriox94 commented
Yes, the display order is a bit awkward, I'll probably do another pull request to fix it, and as for the dash, do you think it's really annoying? Personally, once I'm in the game, I don't pay attention to this kind of detail, but if it really bothers you, I can try to find a solution.

2024-05-05 11:15 UTC, Adri1 commented
> Yes, the display order is a bit awkward, I'll probably do another pull request to fix it, and as for the dash, do you think it's really annoying? Personally, once I'm in the game, I don't pay attention to this kind of detail, but if it really bothers you, I can try to find a solution.

About the dash, it's not that much even if it's their official orthography, but idk the importance of it the other languages, like German, also using dashes in this context like in French.

Also if someday we have a Japanese translation, this kind of issue might come back in some ways, as for example they completly glue the word "Mega" (メガ) to the name of the Pokémon
And in some cases they add a particle when the name of the form is glued to a Pokémon, as when they talk about a regional form of a Pokémon between the name of the form and the name of the Pokémon, kida like the dashes I'm taking about.
(I know regional forms aren't part of theses files, but it's just to give you an example of somthing that may occur)

2024-05-08 16:28 UTC, CodeTappert commented
> About the dash, not that much even if it's their official orthography, but idk the importance of it the other languages, like German, also using dashes in the context of Mega, Ultra and Primal, like in French.
> 

German also uses the Dash for Mega Pokemon. 

For example `Mega-Rayquaza`. Same for `Proto-Groudon` and `Proto-Kyogre`. As well as `Ultra-Necrozma`.

Some form are added in () at the end. Like `Giratina (Urform)`

2024-05-15 02:43 UTC, Adri1 commented
Any news about this?

2024-05-15 06:28 UTC, Kiriox94 commented
I'm sorry I've stopped working on it a bit, the simplest thing would be that I have all the different ways to display a form in all supported languages, but I don't know how to do that

2024-05-15 16:41 UTC, closed without merging

2024-05-15 16:53 UTC, Kiriox94 commented
Oh, sorry I made a wrong manipe it closed the pr, I'll reopen one when the requested changes are ready.