[Bug] Pollen Puff behavior fix
pagefaultgames/pokerogue pull request #4615
Opened 2024-10-08 15:01 UTC by frutescens

Cat in front of keyboard will update later. Sorry.

## What are the changes the user will see?

## Why am I making these changes?

## What are the changes from a developer perspective?

### Screenshots/Videos

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-10-08 15:06 UTC, Tempo-anon requested changes

2024-10-08 15:06 UTC, Tempo-anon commented on src/field/pokemon.ts
> +  apply(source: Pokemon, move: Move, moveCategory: MoveCategory): HitResult {
Adding a third param here causes issues on line 2686 of `pokemon.ts` `apply(source: Pokemon, move: Move, moveCategory: MoveCategory): HitResult {` and line 168 of `sheer_force.test.ts` `applyPostDefendAbAttrs(PostDefendTypeChangeAbAttr, target, user, move, target.apply(user, move));`

Luckily those are the only two places that need updating I believe

2024-10-08 15:15 UTC, frutescens commented on src/field/pokemon.ts
> +  apply(source: Pokemon, move: Move, moveCategory: MoveCategory): HitResult {
fix

2024-10-08 20:33 UTC, MokaStitcher commented on src/phases/move-effect-phase.ts
> +          const moveCategory = new Utils.IntegerHolder(move.category);
```suggestion
          const moveCategory = new Utils.NumberHolder(move.category);
```
I think we're trying to move away from using integer since there's no actual difference with number

These lines may need to be updated too, but i think that's it?
https://github.com/pagefaultgames/pokerogue/blob/d8c914c7686c0fa4c74609ebed97c03f65a46f3e/src/data/move.ts#L4110-L4114

2024-10-08 23:36 UTC, frutescens commented on src/phases/move-effect-phase.ts
> +          const moveCategory = new Utils.IntegerHolder(move.category);
Ok, fixed!

2024-10-09 03:53 UTC, innerthunder commented on src/field/pokemon.ts
> +  apply(source: Pokemon, move: Move, moveCategory: MoveCategory): HitResult {
I feel like things would be organized better if the move's final category was calculated within this function rather than in `MoveEffectPhase` (or, better yet, make a `getMoveCategory` method similar to `Pokemon.getMoveType`). Scope-wise, move category isn't used anywhere else in `MoveEffectPhase`, and I don't think that's likely to change with what's left to implement.

2024-10-10 05:33 UTC, frutescens commented on src/field/pokemon.ts
> +  apply(source: Pokemon, move: Move, moveCategory: MoveCategory): HitResult {
Fixed.

2024-10-10 05:46 UTC, innerthunder approved these changes

2024-10-10 09:17 UTC, DayKev approved these changes

2024-10-10 15:37 UTC, Tempo-anon approved these changes

2024-10-10 15:38 UTC, merged