[Bug] [P2] Prevent wild mons from fleeing with U-turn, Flip Turn, Volt Switch
pagefaultgames/pokerogue pull request #4643
Opened 2024-10-11 17:52 UTC by Fontbane

## What are the changes the user will see?

- Fixes a bug or oversight where wild mons will flee after using U-turn, Flip Turn or Volt Switch.

## Why am I making these changes?

- In the main series games, these moves do not allow wild mons to flee. Teleport is the only self-switching move that allows fleeing.

## What are the changes from a developer perspective?

- Adds another check to the ForceSwitchOutAttr

### Screenshots/Videos

- Player using U-turn and switching, wild Weedle using U-turn and not fleeing, wild Rookidee using Teleport and fleeing
![LoadSceneDemo7](https://github.com/user-attachments/assets/53d73e81-f82c-4139-b562-1de82431ae91)

## How to test the changes?

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

2024-10-11 18:04 UTC, DayKev commented on src/data/move.ts
> +        return true;
```suggestion
        return false;
```
I think this should be `false`, otherwise seems good.

2024-10-11 18:20 UTC, innerthunder requested changes
We need a way to bypass this check for Teleport (maybe a `canFlee` field or similar?)

EDIT: Also, some moves (e.g. Shed Tail) need to outright fail under this condition. This still allows the move's other effects to go off.

2024-10-11 19:03 UTC, DayKev commented
> We need a way to bypass this check for Teleport (maybe a `canFlee` field or similar?)

What do you mean? The video already shows Teleport still working after the change.

> EDIT: Also, some moves (e.g. Shed Tail) need to outright fail under this condition. This still allows the move's other effects to go off.

Ugh this attr needs a rewrite so badly...

2024-10-11 21:02 UTC, Snailman11 commented
Link to Innerthunder's comment (Discord Report), this could include Chilly Reception and Parting Shot

https://discord.com/channels/1125469663833370665/1289493136871264297

2024-10-28 04:46 UTC, PigeonBar commented
Relevant issue: #4747

2024-11-01 18:38 UTC, DayKev submitted a review, later dismissed

2024-11-01 18:41 UTC, DayKev approved these changes

2024-11-01 19:09 UTC, MokaStitcher approved these changes

2024-11-02 04:21 UTC, innerthunder approved these changes
lgtm (provided that Shed Tail and Baton Pass are made to fail in a future PR)

2024-11-02 04:21 UTC, merged