[Ability] Remove partials from Serene Grace and Shield Dust
pagefaultgames/pokerogue pull request #4646
Opened 2024-10-11 22:05 UTC by frutescens

## What are the changes the user will see?
Users will be less confused when using Pokemon with Serene Grace and Shield Dust. 

## Why am I making these changes?
Making our shareholders happy. 

## What are the changes from a developer perspective?
In PR #246 Secret Power's (as-of-now unimplemented) 30% secondary effect chance was cited as the reason for why Serene Grace and Shield Dust was labeled partial; however, the secondary effect modifications that Serene Grace/Shield Dust provide should affect that 30% secondary effect chance even though Secret Power is only partially implemented. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

2024-10-11 22:11 UTC, DayKev approved these changes

2024-10-11 22:12 UTC, DayKev commented
Maybe we should say that Sheer Force blocking Meloetta's form change is a `wontfix` and remove the partial from it too? 🤔

2024-10-11 22:16 UTC, frutescens commented
> Maybe we should say that Sheer Force blocking Meloetta's form change is a `wontfix` and remove the partial from it too? 🤔

It's not just Meloetta's form change; there's some other secondary effects that Sheer Force blocks. 
![image](https://github.com/user-attachments/assets/327890e3-3dba-4de6-8c5f-0846216f33d0)

2024-10-11 22:23 UTC, DayKev commented
Ah, so shell bell and a handful of abilities (half of which are unimplemented :plains:).

2024-10-11 22:26 UTC, innerthunder approved these changes

2024-10-12 00:17 UTC, frutescens commented
We can always add the Partial label back after those items are implemented :yawn:

2024-10-12 15:21 UTC, Tempo-anon requested changes
We can remove the partials but let's at least leave a comment here explaining any future TODOs so someone can just read a comment instead of chasing down this PR

2024-10-12 16:10 UTC, DayKev commented
Seems like #4649 supercedes this PR.

2024-10-12 23:45 UTC, closed without merging