[Bug Fix] Fix for Speed Boost is Activated on the Turn a Pokemon is Switched In, and When a Pokemon Fails to Escape #4353
pagefaultgames/pokerogue pull request #4676
Opened 2024-10-16 23:32 UTC by PrabbyDD

Fix for #4353 

## What are the changes the user will see?
Speed boost will no longer trigger if the pokemon failed to escape or if it was just switched in on any turn via any method except the initial switch in question. 

## Why am I making these changes?
Bug fix

## What are the changes from a developer perspective?
I have added a couple of variables to determine if a pokemon was just switched in or failed an escape, and modified several phase files in order to achieve the intended fix. 

### Screenshots/Videos

https://github.com/user-attachments/a

https://github.com/user-attachments/assets/1518f82c-2f72-4d4e-be5d-242d8b762e9a

https://github.com/user-attachments/assets/3445cf02-935c-4391-a09b-0be4a93c8c71

https://github.com/user-attachments/assets/f597bef4-995b-4ea2-a59d-595ade89eb08

## How to test the changes?
Override files, and running test files

Note I still need to write test files

## Checklist
- [ X] **I'm using `beta` as my base branch**
- [X ] There is no overlap with another PR?
- [ X] The PR is self-contained and cannot be split into smaller PRs?
- [X ] Have I provided a clear explanation of the changes?
- [X ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ X] Have I tested the changes (manually)?
    - [X ] Are all unit tests still passing? (`npm run test`)
- [ X] Are the changes visual?
  - [ X] Have I provided screenshots/videos of the changes?

2024-10-16 23:36 UTC, PrabbyDD commented
I have not written unit tests yet, I will probably today or tomorrow, I just wanted to put this pr out there because I feel like my code is kinda shady here and im not sure if there might be unintended consequences messing with the turn end and other phase files like this.

2024-10-16 23:44 UTC, innerthunder requested changes

2024-10-16 23:44 UTC, innerthunder commented on src/field/pokemon.ts
> +  public failedRunAway: boolean;
Put these in `turnData`, please.

2024-10-16 23:44 UTC, innerthunder commented on src/phases/turn-end-phase.ts
> +      }
does this also apply to Moody?

2024-10-16 23:47 UTC, PrabbyDD commented on src/phases/turn-end-phase.ts
> +      }
Bulbapedia doesnt saying anything about moody acting the same way as speed boost

2024-10-17 01:22 UTC, DayKev commented on src/phases/turn-end-phase.ts
> +      }
Based on the Showdown code Moody doesn't act the same as Speed Boost.

2024-10-17 19:25 UTC, PrabbyDD commented on src/field/pokemon.ts
> +  public failedRunAway: boolean;
I am trying to put these variables in TurnData, but am running into an issue where I am trying to set these variables in turndata while turndata is undefined. I am not sure where turnData is being initialized with an actual object, and its happening after I try to access these variables.

2024-10-17 19:32 UTC, PrabbyDD commented on src/field/pokemon.ts
> +  public failedRunAway: boolean;
I guess it would kinda make sense that it wouldnt work, because switching is between turns, so maybe the turn data for the switched in pokemon doesnt exist yet?

2024-10-17 22:27 UTC, innerthunder commented on src/phases/switch-summon-phase.ts
> +    this.lastPokemon.setSwitchedInStatus(false);
This needs to go in `onEnd`. The superclass `SummonPhase`'s `onEnd` function resets the turn data of the Pokemon switching in, so the switched in Pokemon is only guaranteed to have its turn data defined after `super.onEnd()` is called.

2024-10-17 22:28 UTC, innerthunder commented on src/field/pokemon.ts
> +  public failedRunAway: boolean;
See my other comment below

2024-10-17 22:32 UTC, PrabbyDD commented on src/phases/switch-summon-phase.ts
> +    this.lastPokemon.setSwitchedInStatus(false);
I updated the solution - I still had left it in the same spot but tried to save the turn data after the switch summon phase because the turn data wasnt defined in this file because it was before the new pokemon enters, which I guess is before its turn begins.

2024-10-17 22:57 UTC, innerthunder commented on src/data/ability.ts
> +      }
```suggestion
      if (!pokemon.hasAbility(Abilities.SPEED_BOOST) || (!pokemon.turnData.switchedInThisTurn && !pokemon.turnData.failedRunAway)) {
        if (!simulated) {
           pokemon.scene.unshiftPhase(new StatStageChangePhase(pokemon.scene, pokemon.getBattlerIndex(), true, this.stats, this.stages));
        }
        return true;
      } 
      return false;
```
You should remove the `if (!simulated)` block encapsulating this, too... GitHub is being annoying about me removing it lol

2024-10-17 23:05 UTC, innerthunder approved these changes

2024-10-19 20:51 UTC, DayKev commented on src/data/ability.ts
> +      if (!pokemon.hasAbility(Abilities.SPEED_BOOST)) {
Seems like this would cause issues if the Pokémon has both Speed Boost and Moody, since you're not checking whether Speed Boost is the ability currently activating but instead just whether the Pokémon has that ability at all.

2024-10-19 20:51 UTC, DayKev commented on src/phases/attempt-run-phase.ts
> +
I think technically this should be put before the `constructor()` block, not a big deal though.

2024-10-20 03:58 UTC, PrabbyDD commented on src/data/ability.ts
> +      if (!pokemon.hasAbility(Abilities.SPEED_BOOST)) {
Im not sure what you mean in this instance - is it possible for a pokemon to have 2 active abilities at the same time?

2024-10-20 06:02 UTC, innerthunder commented on src/data/ability.ts
> +      if (!pokemon.hasAbility(Abilities.SPEED_BOOST)) {
Yes. `hasAbility` checks the Pokemon's Ability *and* Passive, so you have to account for having 2 different post-turn abilities at the same time

2024-10-20 16:49 UTC, PrabbyDD commented on src/data/ability.ts
> +      if (!pokemon.hasAbility(Abilities.SPEED_BOOST)) {
So does that mean a pokemon can have both abilities, but only 1 can be active? So that means instead of checking if it has that ability with hasAbility, I need to check if speed boost is active?

2024-10-20 21:17 UTC, innerthunder commented on src/data/ability.ts
> +      if (!pokemon.hasAbility(Abilities.SPEED_BOOST)) {
For the record, I don't think this breaks anything atm, since Speed Boost is the only ability that uses this attribute. But this could introduce problems with scalability.

Suppose there was another ability that used this attribute, and you have a Pokemon `source` that has that ability and Speed Boost as a passive. When this attribute is applied for the new ability, `source.hasAbility(Abilities.SPEED_BOOST)` would return `true`, so the new ability wouldn't trigger its stat change on the turn `source` is switched in.

The way I see it, you have 2 options to make the code more robust:
1. Make a field in this attribute class (say, `appliesOnSwitch`), set it to `true` for Speed Boost, and check that instead of doing the `hasAbility` checks.
2. Rename this attribute to `SpeedBoostAbAttr` and only have it apply to Speed Boost (meaning you no longer need the `hasAbility` checks). Future abilities with similar effects would have to use another attribute or rewrite this attribute at the time of their implementation.

I think I'd personally prefer option 2 since there really isn't another ability in the game that would use this attribute, but I don't feel strongly about going one way or the other.

2024-10-21 16:16 UTC, PrabbyDD commented on src/data/ability.ts
> +      if (!pokemon.hasAbility(Abilities.SPEED_BOOST)) {
Should be good now.

2024-10-21 21:47 UTC, innerthunder requested changes

2024-10-21 21:47 UTC, innerthunder commented on src/data/ability.ts
>    private stages: number;
These should be removed since we're always using the same values for them now

2024-10-22 06:15 UTC, innerthunder submitted a review, later dismissed
Looking good for the most part now. Thanks for bearing with our suggestions and responding quickly 😅

2024-10-22 06:15 UTC, innerthunder commented on src/phases/attempt-run-phase.ts
> +  public forceFailEscape = false;
Not a blocker, but this should probably be turned into an override eventually.

2024-10-22 16:49 UTC, PrabbyDD commented on src/phases/attempt-run-phase.ts
> +  public forceFailEscape = false;
eventually :P

2024-10-24 04:43 UTC, PrabbyDD commented
ahhhh i broke it after doing the merge conflict

2024-10-24 21:13 UTC, innerthunder approved these changes

2024-10-25 00:48 UTC, DayKev approved these changes

2024-10-29 21:38 UTC, merged