[Ability] Implement Wimp Out and Emergency Exit
pagefaultgames/pokerogue pull request #4701
Opened 2024-10-21 21:47 UTC by muscode13

## What are the changes the user will see?
Wimp Out and Emergency Exit implemented

## Why am I making these changes?
Ability is not implemented

## What are the changes from a developer perspective?
There are several attributes and a condition function, as well as some helper functions I added to make this ability work:

- `getHealthKnockedBelowHalf `- This function determines if the Pokemon's health was knocked below half. It checks through different phases and evaluates based off conditions that can happen during it, such as Stealth Rocks during PostSummon or Leech Seed damage during TurnEnd
  - `calculateTurnEndDamage` - This functions calculates how much damage the Pokemon would take from TurnEnd effects like Poison, Salt Cure, Whirlpool
  - `calculateSleepDamage` - This function calculates how much damage the Pokemon would take from abilities like Bad Dreams
  - `calculateShellBellRecovery` - Calculates the amount healed off Shell Bell. This covers the case where if the pokemon's health falls below half and recovers back above half from a Shell Bell, Wimp Out should activate even after the Shell Bell recovery
  - `checkSheerForceCondition` - Since the two conditions were unable to coexist, I added a check to verify that an attack that would trigger Wimp Out from a Sheer Force user wouldn't. I'd normally refactor getSheerForceHitDisableAbCondition to use this helper, but I wanted to keep my changes isolated.
- `ForceSwitchOutHelper` - This is mostly logic from the ForceSwitchOutAttr in moves that was lifted and shifted here.
- `PostDefendForceSwitchOutAttr `- Triggers Wimp Out if the Pokemon's health drops below half after taking an attack. If defending from a multi-hit move, the ability will trigger after the last hit. Phasing damaging moves like Dragon Tail and Circle Throw's effect will be applied and Wimp Out will not trigger.
- `PostAttackForceSwitchOutAttr `- Triggers Wimp Out if the Pokemon's health drops below half after attacking. This triggers primarily off recoil. It will not trigger if the user cuts it's health with moves like Substitute or Belly Drum.
- `PostSummonForceSwitchOutAttr `- Triggers Wimp Out if the Pokemon's health drops below half after entering the field. Triggers off entry hazards.
- `PostTurnForceSwitchOutAttr `- Triggers Wimp Out if the Pokemon's health drops below half after Turn End damage like poison, leech seed, etc. 
- `PostWeatherForceSwitchOutAttr `- Triggers Wimp Out if the Pokemon's health drops below half after suffering from Weather damage. It calculates how much the Pokemon would take from the weather, and if it would drop it below half, the damage is applied and the pokemon switches out.
- `PostVictoryForceSwitchOutAttr `- Triggers Wimp Out if the Pokemon's health drops below half after killing an enemy. Accounts for abilities like Aftermath and Innards Out
- All of the following attributes remove the Trapped tag from the user, since Wimp Out can occur despite being trapped.

I also had to add a small check and helper function to ForceSwitchOutAttr in moves.ts, to account for an edge case interaction: If Wimp Out activates due to being hit by U-turn or Volt Switch, the user of that move will not be switched out.

## How to test the changes?
- Use Pokemon with Wimp Out in the game. If you want to test out a specific interaction, you can override and give the enemy pokemon a certain move, like Stealth Rock or Leech Seed. 
- run `npm run test wimp_out`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR? - The other PR has been closed for several months
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-10-21 23:01 UTC, flx-sta commented
@muscode13 Thank you for your contribution.
Please make sure to provide some videos/screenshots of in-game footage for these implementations

2024-10-22 02:58 UTC, muscode13 commented
Hey! @flx-sta Added some videos. Let me know if you'd like some more!

Also just added the nightmare interaction following its recent bug fix

2024-10-22 06:39 UTC, innerthunder requested changes
I feel like this can all be condensed into a single attribute if applied in [`Pokemon.damage`](https://github.com/pagefaultgames/pokerogue/blob/c2eb9de9df6cd7ba625dd73c3812274f47994731/src/field/pokemon.ts#L2840), which covers every source of damage and is where the Pokemon's HP is actually updated. A new subset of ability attributes (say, `PostDamageAbAttr`) and a new apply function `applyPostDamageAbAttrs` in support of Wimp Out/EE's attribute could also be helpful.

2024-10-22 21:12 UTC, muscode13 commented
Refactored the code to now use a new class `PostDamageAbAttr` as suggested. The ability attributes have been cut down to just `PostDamageForceSwitchAttr`, which covers damage during all phases. I'll add some new videos later tonight.

2024-10-23 04:37 UTC, muscode13 commented
Alright! I updated the videos. They are all of the refactored version. Ready for another review

2024-10-23 09:12 UTC, innerthunder commented on src/test/abilities/wimp_out.test.ts
> -  });
You can add this back if you change `it()` to `it.todo()` or `it.skip()`

2024-10-23 13:16 UTC, muscode13 commented on src/test/abilities/wimp_out.test.ts
> -  });
added back

2024-10-23 21:58 UTC, innerthunder reviewed
Just one nit left on my end

2024-10-23 21:58 UTC, innerthunder commented on src/data/ability.ts
> +  applyPostDamageAbAttrs(pokemon: Pokemon, damage: number, passive: boolean, simulated: boolean, args: any[]): boolean | Promise<boolean> {
nit: This should be `applyPostDamage` to match with the other apply types

2024-10-23 22:32 UTC, muscode13 commented on src/data/ability.ts
> +  applyPostDamageAbAttrs(pokemon: Pokemon, damage: number, passive: boolean, simulated: boolean, args: any[]): boolean | Promise<boolean> {
updated

2024-10-23 23:03 UTC, innerthunder commented on src/data/ability.ts
> +export function applyPostDamage(attrType: Constructor<PostDamageAbAttr>,
```suggestion
export function applyPostDamageAbAttrs(attrType: Constructor<PostDamageAbAttr>,
```
Not what I meant earlier 😖 

- The apply functions within `XAbAttrs` are usually called `applyX` (e.g. `PostDefendAbAttr` -> `applyPostDefend`)
- The external functions that invoke attributes are usually called `applyXAbAttrs` (e.g. `applyPostDefendAbAttrs`)

2024-10-23 23:24 UTC, muscode13 commented on src/data/ability.ts
> +export function applyPostDamage(attrType: Constructor<PostDamageAbAttr>,
fixed! Thanks for the explanation on that

2024-10-24 04:55 UTC, torranx commented
FYI you need to add spaces before and after the video links so that it would be embedded.

2024-10-26 18:37 UTC, innerthunder requested changes
`PostDamageForceSwitchAttr` -> `PostDamageForceSwitchAbAttr` to keep in line with other ability attributes (otherwise, it might be misinterpreted as a move attribute at a glance)

2024-11-01 15:32 UTC, DayKev commented on src/data/ability.ts
> +      if (!player && pokemon.scene.currentBattle.isBattleMysteryEncounter() && !pokemon.scene.currentBattle.mysteryEncounter?.fleeAllowed) {
The first `if` checks if `switchOutTarget` is a `PlayerPokemon` and then the nested `if` within immediately checks if `switchOutTarget` is *not* a `PlayerPokemon`. The second `if` is never be able to be reached.

2024-11-01 15:33 UTC, DayKev commented on src/data/ability.ts
> +    if (switchOutTarget instanceof PlayerPokemon) {
```suggestion
    if (player) {
```

2024-11-01 15:35 UTC, DayKev commented on src/data/ability.ts
> +  constructor(hpRatio:number = 0.5) {
```suggestion
  constructor(hpRatio: number = 0.5) {
```

2024-11-01 15:36 UTC, DayKev commented on src/data/ability.ts
> +        if (pokemon.getTag(BattlerTagType.TRAPPED) !== undefined) {
I don't think this is necessary, this tag should already be removed when a Pokémon switches out.

2024-11-01 15:37 UTC, DayKev commented on src/data/ability.ts
> +  applyPostDamage(pokemon: Pokemon, damage: number, passive: boolean, simulated: boolean, args: any[]): boolean | Promise<boolean> {
```suggestion
  public applyPostDamage(pokemon: Pokemon, damage: number, passive: boolean, simulated: boolean, args: any[]): boolean | Promise<boolean> {
```

2024-11-01 15:38 UTC, DayKev commented on src/data/ability.ts
> +  getFailedText(target: Pokemon): string | null {
```suggestion
  public getFailedText(target: Pokemon): string | null {
```

2024-11-01 15:38 UTC, DayKev commented on src/data/ability.ts
> +  getSwitchOutCondition(pokemon: Pokemon, opponent: Pokemon): boolean {
```suggestion
  public getSwitchOutCondition(pokemon: Pokemon, opponent: Pokemon): boolean {
```

2024-11-01 15:38 UTC, DayKev commented on src/data/ability.ts
> +  switchOutLogic(pokemon: Pokemon): boolean {
```suggestion
  public switchOutLogic(pokemon: Pokemon): boolean {
```

2024-11-01 15:39 UTC, DayKev commented on src/data/ability.ts
> +  applyPostDamage(pokemon: Pokemon, damage: number, passive: boolean, simulated: boolean, args: any[]): boolean | Promise<boolean> {
```suggestion
  public override applyPostDamage(pokemon: Pokemon, damage: number, passive: boolean, simulated: boolean, args: any[]): boolean | Promise<boolean> {
```

2024-11-01 15:39 UTC, DayKev commented on src/data/ability.ts
> +  getFailedText(user: Pokemon, target: Pokemon, move: Move, cancelled: Utils.BooleanHolder): string | null {
```suggestion
  public getFailedText(user: Pokemon, target: Pokemon, move: Move, cancelled: Utils.BooleanHolder): string | null {
```

2024-11-01 16:00 UTC, DayKev commented
Btw you should update the OP with the changes you made (it currently lists a bunch of `AbAttr`s that you've since removed).

2024-11-01 16:38 UTC, muscode13 commented on src/data/ability.ts
> +      if (!player && pokemon.scene.currentBattle.isBattleMysteryEncounter() && !pokemon.scene.currentBattle.mysteryEncounter?.fleeAllowed) {
fixed! thanks for pointing that out!

2024-11-01 19:36 UTC, muscode13 commented
@DayKev Added some code for Multi-Lens, but it's pretty ghetto since the modifier doesn't update the turnData with all the damage dealt. Let me know if you think we're better off without it. Thanks!

2024-11-02 02:55 UTC, muscode13 commented on src/data/ability.ts
> +  public applyPostDamage(pokemon: Pokemon, damage: number, passive: boolean, simulated: boolean, args: any[]): boolean | Promise<boolean> {
I wouldn't mind making this change. Since we only care about the moves that are being used against the pokemon, maybe we could add an optional arg for source in damageAndUpdate then update the call in pokemon.apply?

2024-11-02 06:54 UTC, muscode13 commented on src/data/ability.ts
> +  public applyPostDamage(pokemon: Pokemon, damage: number, passive: boolean, simulated: boolean, args: any[]): boolean | Promise<boolean> {
Alright I made that change and updated the AbAttr accordingly. I also ran all the tests and didn't run into any issues. Let me know what you think!

2024-11-02 06:55 UTC, muscode13 commented
Added 3 more videos to the description showing the updated Multi Hit, Multi Lens, and P Bond interaction

2024-11-02 08:45 UTC, innerthunder commented on src/data/ability.ts
> +        if (allMoves[enemyLastMoveUsed.move].hasAttr(MultiHitAttr) || multiHitModifier || source.hasAbilityWithAttr(AddSecondStrikeAbAttr)) {
```suggestion
        if (source.turnData.hitCount > 1) {
```
This should cover any case where an attack strikes more than once

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +
```suggestion
```

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +  /**
```suggestion

  /**
```

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +    } else if (pokemon.scene.currentBattle.battleType !== BattleType.WILD) {
```suggestion
    } else if (pokemon.scene.currentBattle.battleType !== BattleType.WILD && switchOutTarget instanceof EnemyPokemon) {
```

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +          (pokemon.scene.currentBattle.trainer ? pokemon.scene.currentBattle.trainer.getNextSummonIndex((switchOutTarget as EnemyPokemon).trainerSlot) : 0),
```suggestion
          (pokemon.scene.currentBattle.trainer ? pokemon.scene.currentBattle.trainer.getNextSummonIndex(switchOutTarget.trainerSlot) : 0),
```

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +    return (!player && !pokemon.scene.currentBattle.battleType)
```suggestion
    return (!player && pokemon.scene.currentBattle.battleType !== BattleType.WILD)
```

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +    this.helper = new ForceSwitchOutHelper(SwitchType.SWITCH);
```suggestion
```

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +  private helper: ForceSwitchOutHelper;
```suggestion
  private helper: ForceSwitchOutHelper = new ForceSwitchOutHelper(SwitchType.SWITCH);
```

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> + * @extends PostDamageAbAttr
```suggestion
 * Used by Wimp Out and Emergency Exit
 *
 * @extends PostDamageAbAttr
 * @see {@linkcode applyPostDamage}
```

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +      // Will not activate if the Pokémon's HP falls below half while it is in the air during Sky Drop.
```suggestion
```
Looks like this comment is in the wrong spot.

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +        if (fordbiddenDefendingMoves.includes(enemyLastMoveUsed.move) || enemyLastMoveUsed.move === Moves.SKY_DROP && enemyLastMoveUsed.result === MoveResult.OTHER) {
```suggestion
        // Will not activate if the Pokémon's HP falls below half while it is in the air during Sky Drop.
        if (fordbiddenDefendingMoves.includes(enemyLastMoveUsed.move) || enemyLastMoveUsed.move === Moves.SKY_DROP && enemyLastMoveUsed.result === MoveResult.OTHER) {
```

2024-11-02 16:45 UTC, DayKev commented on src/data/ability.ts
> +function calculateShellBellRecovery(pokemon: Pokemon): number {
This makes me think there needs to be a `healthHealed` field in `PokemonTurnData`; maybe a `startOfTurnHP` field too. Something to look into in the future I guess.

2024-11-02 16:45 UTC, DayKev commented on src/data/move.ts
> +* Used for an edge case interaction with Wimp Out/Emergency Exit
```suggestion
* Helper function to check if the Pokémon's health is below half after taking damage.
* Used for an edge case interaction with Wimp Out/Emergency Exit.
```

2024-11-02 16:45 UTC, DayKev commented on src/data/move.ts
> +* If the Ability activates due to being hit by U-turn or Volt Switch, the user of that move will not be switched out.
Shouldn't this also apply to Flip Turn?

2024-11-02 16:45 UTC, DayKev commented on src/data/move.ts
> +function shouldPreventSwitchOut(target: Pokemon): boolean {
This function should probably be moved into `ForceSwitchOutAttr`, and I'm not sure I like the name. The name reflects what it's being used for, but not what it does. Maybe `hpDroppedBelowHalf`?

2024-11-02 16:45 UTC, DayKev commented on src/data/move.ts
>      const switchOutTarget = this.selfSwitch ? user : target;
```suggestion
```

2024-11-02 16:45 UTC, DayKev commented on src/data/move.ts
```suggestion

    const switchOutTarget = this.selfSwitch ? user : target;
```

2024-11-02 16:45 UTC, DayKev commented on src/field/pokemon.ts
> +    }
```suggestion
    applyPostDamageAbAttrs(PostDamageAbAttr, this, damage, this.hasPassive(), false, [], source);
```

2024-11-02 16:49 UTC, DayKev commented on src/data/ability.ts
> +        const multiHitModifier = source.getHeldItems().find(m => m instanceof PokemonMultiHitModifier);
```suggestion
```
Forgot to remove this?

2024-11-02 17:04 UTC, muscode13 commented on src/data/ability.ts
> +        const multiHitModifier = source.getHeldItems().find(m => m instanceof PokemonMultiHitModifier);
oh sorry! yea forgot to get rid of that. thanks

2024-11-02 20:00 UTC, DayKev approved these changes
Lemme properly move this comment to the right spot this time, then it's all good from me.

2024-11-02 21:26 UTC, innerthunder submitted a review, later dismissed

2024-11-03 06:04 UTC, merged