[Ability implementation] Implementing Friend Guard
pagefaultgames/pokerogue pull request #4718
Opened 2024-10-24 04:22 UTC by PrabbyDD

## What are the changes the user will see?
Friend guard should now work

## Why am I making these changes?
To complete the game

## What are the changes from a developer perspective?
Added new AbAttr in ability.ts and some changes in pokemon.ts to detect friend guard from an ally

### Screenshots/Videos

Without friend guard, normal damage
https://github.com/user-attachments/assets/5ddb4944-2d4c-4e91-b749-9a0b0ee8b646

With friend guard, less damage
https://github.com/user-attachments/assets/2029ec97-9308-4db5-ac25-39c1d1e54ccc

## How to test the changes?
Use test file and override for visuals

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-10-24 04:44 UTC, torranx submitted a review, later dismissed

2024-10-24 04:44 UTC, torranx commented on src/data/ability.ts
> +    return true;
shouldnt there be a condition to check for `simulated` here?

2024-10-24 04:44 UTC, torranx commented on src/data/ability.ts
> +export class FriendGuardAbAttr extends PreDefendAbAttr {
missing docs

2024-10-24 04:44 UTC, torranx commented on src/test/abilities/friend_guard.test.ts
> +  it("first part of test, getting hp without friend guard", async () => {
I dont think this is a necessary test

2024-10-24 04:44 UTC, torranx commented on src/test/abilities/friend_guard.test.ts
> +  it("second part of test, getting hp with friend guard and comparing", async () => {
```suggestion
  it("should reduce damage that other allied Pokémon receive from attacks (from any Pokémon) by 25%", async () => {
```

2024-10-24 04:44 UTC, torranx commented on src/test/abilities/friend_guard.test.ts
test cases could do some line breaks.
please also add a test re: "If multiple of a Pokémon's allies have Friend Guard, Friend Guard stacks multiplicatively."

2024-10-24 04:47 UTC, torranx commented on src/test/abilities/friend_guard.test.ts
> +    expect(hp2).toBeGreaterThan(hp1);
test cases should be isolated/not dependent on other tests

2024-10-24 04:52 UTC, torranx commented
Edited the description to properly embed the videos. FYI, you need to add spaces before and after the video link.

2024-10-24 05:04 UTC, DayKev commented on src/test/abilities/friend_guard.test.ts
> +    expect(hp2).toBeGreaterThan(hp1);
While we try to control for RNG in tests, not all of it is controlled for yet, such as natures. By starting 2 different battles, a rare nature combination could potentially break the test.
Instead of starting 2 battles, you could modify the ability of the player's second pokemon and swap it to Friend Guard mid-test with `vi.spyOn(alliedPokemon, "getAbility", "get").mockReturnValue(allAbilities[Abilities.FRIEND_GUARD]);` and then compare the damage dealt on each turn.

2024-10-24 05:04 UTC, DayKev commented on src/test/abilities/friend_guard.test.ts
> +    const party = game.scene.getParty()! as PlayerPokemon[];
```suggestion
    const [ player1, player2 ] = game.scene.getPlayerField();
```

2024-10-24 05:05 UTC, innerthunder requested changes

2024-10-24 05:05 UTC, DayKev commented on src/test/abilities/friend_guard.test.ts
That's not possible, we don't have triple battles in PokeRogue.

2024-10-24 05:06 UTC, innerthunder commented on src/data/ability.ts
> +    return true;
This is fine as is because it's just modifying a container's value (i.e. not changing game state)

2024-10-24 05:07 UTC, DayKev commented
> Edited the description to properly embed the videos. FYI, you need to add spaces before and after the video link.

I put the videos into expandos too.

2024-10-24 05:09 UTC, DayKev commented
Put some basic docs into suggestions, they may require more later.

2024-10-24 05:58 UTC, frutescens requested changes

2024-10-24 05:58 UTC, frutescens commented on src/data/ability.ts
> +      .attr(FriendGuardAbAttr, .25)
I would prefer it to be named something like 'AlliedFieldDamageReductionAbAttr' if the percentage is going to be part of the constructor. If you want to keep it as 'FriendGuardAttr', I would suggest moving the 0.75 to the FriendGuardAttr as a constant there instead of it being part of the constructor if that makes sense.

2024-10-24 18:07 UTC, PrabbyDD commented on src/data/ability.ts
> +export class FriendGuardAbAttr extends PreDefendAbAttr {
Do you just mean to add a descriptive comment?

2024-10-24 18:09 UTC, PrabbyDD commented on src/test/abilities/friend_guard.test.ts
I was doing this assuming there wouldnt be triple battles or multiple allies with friend guard, but should I consider the potential for triple battles in the future? Friend guard does not work on the pokemon itself with friend guard so as of the current state of the game its not possible to stack it.

2024-10-24 18:16 UTC, PrabbyDD commented on src/field/pokemon.ts
> +      if (this.scene.currentBattle.double && this.getAlly().isActive()) {
oops

2024-10-24 18:27 UTC, PrabbyDD commented on src/test/abilities/friend_guard.test.ts
> +    expect(hp2).toBeGreaterThan(hp1);
Thank you, I was trying to find this when I wrote the test but I couldnt figure out how to change abilities mid test

2024-10-24 19:49 UTC, torranx commented on src/test/abilities/friend_guard.test.ts
oh yeah re-read the description, I thought it works like Steely Spirit, this should be fine for now @PrabbyDD

2024-10-24 22:02 UTC, innerthunder approved these changes
LGTM. How this interacts with the `ignoreAbility` param could use a touch-up, but that's a problem for future me 😴

2024-10-25 23:11 UTC, frutescens approved these changes

2024-10-26 15:14 UTC, DayKev commented on src/test/abilities/friend_guard.test.ts
> +    expect(turn1Damage).toBe(40);
Technically the first turn isn't necessary here since you're not comparing the damage between turns for this one but 🤷

2024-10-28 20:49 UTC, merged