[P2 BUG] Fixed Lingering Arena Trap if Pokemon Switches Out (#3713)
pagefaultgames/pokerogue pull request #4755
Opened 2024-10-29 09:19 UTC by geeilhan

[P2 BUG] Fixed Lingering Arena Trap if Pokemon Switches Out (#3713)

## What are the changes the user will see?

The user can now switch Pokemon or Run away if enemy Pokemon with Arena Trap gets forced out of the field during a double battle.

## Why am I making these changes?

Countering Arena Trap with switch out attacks is unrewarding since it does not work.

## What are the changes from a developer perspective?

1. [isActive()](https://github.com/geeilhan/pokerogueFork/blob/6cf047aa1f831f531a83dfde6e0e1becb20affb6/src/field/pokemon.ts#L357-L365) now checks if the Pokemon is on the field and returns false if he is not active.
2. [apply()](https://github.com/geeilhan/pokerogueFork/blob/6cf047aa1f831f531a83dfde6e0e1becb20affb6/src/field/pokemon.ts#L2728-L2752) checks if a move with the ForceSwitchOutAttr is used and sets [switchOutStatus]() according to the move effect
3. [isTrapped()](https://github.com/geeilhan/pokerogueFork/blob/6cf047aa1f831f531a83dfde6e0e1becb20affb6/src/field/pokemon.ts#L1522-L1540) now filters out Pokemon on the opposing field that are not on the field anymore

### Screenshots/Videos

No recording of before the changes but @Snailman11 recorded a video and I can confirm its content:
https://discord.com/channels/1125469663833370665/1275424376103374968/1275973836453449889

After changes (Right Pokemon has Arena Trap):
[Lingering_Arena_Trap_After_Changes_Doubles.webm](https://github.com/user-attachments/assets/4656689e-bc32-447a-b2bb-6dc68f8a3f23)

## How to test the changes?

Use:
```
const overrides = {
  BATTLE_TYPE_OVERRIDE: "double",
  MOVESET_OVERRIDE: [ Moves.ROAR, Moves.EXTREME_SPEED, Moves.SPLASH ],
  OPP_SPECIES_OVERRIDE: Species.DIGLETT,
  STARTING_BIOME_OVERRIDE: Biome.BADLANDS,
  OPP_MOVESET_OVERRIDE: [ Moves.SPLASH ],
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

And start with at least 3 Pokemon. After that you have to manually find an encounter with 1 Arena Trap Diglett and 1 Sand Veil Diglett.
Note: I saved my game during the wave I found the matching Digletts. That way I could always easily retest some edge case behaviour.

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-10-29 09:26 UTC, geeilhan commented
One test started to fail randomly for some reason after the latest commit on the beta branch (src/test/mystery-encounters/encounters/clowning-around-encounter.test.ts). I reran this specific test 20 times and i always got a rogueCounter value from 5 to 7 instead of 7 for the test in line [250](https://github.com/geeilhan/pokerogueFork/blob/6cf047aa1f831f531a83dfde6e0e1becb20affb6/src/test/mystery-encounter/encounters/clowning-around-encounter.test.ts#L250-L296)

2024-10-29 10:38 UTC, innerthunder requested changes
Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.

2024-10-29 10:38 UTC, innerthunder commented on src/field/pokemon.ts
> +    }
I think this would be better placed in `Pokemon.isOnField()`.

Also, is there a reason this only applies to enemies?

2024-10-29 10:38 UTC, innerthunder commented on src/field/pokemon.ts
> +
Not sure if this is necessary. `Pokemon.leaveField` already sets `switchOutStatus` to `true`, and that's already called after applying any forced switch-out.

2024-10-29 10:52 UTC, geeilhan commented
> Collaborator

Thank you for your fast reply. I was just taking a break since I have been sitting here for this for a long time :D but I will be writing a test case as soon as I can.

2024-10-29 10:53 UTC, geeilhan commented
> Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.

Thank you for your fast reply. I was just taking a break since I have been sitting here for this for a long time :D but I will be writing a test case as soon as I can.

2024-10-29 11:20 UTC, geeilhan commented on src/field/pokemon.ts
> +    }
This is my mistake. I failed the automated u-turn test and added this limit to fix one problem at a time. It seems I forgot about this since this should work for both sides (isPlayer and not). I will review my code again and try to clean it up.

2024-10-29 11:49 UTC, geeilhan commented on src/field/pokemon.ts
> +
I have not noticed that Thank you. I was looking somewhere different but after seeing `Pokemon.leaveField` it does everything I needed.

2024-10-29 11:56 UTC, geeilhan commented
> Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.

I have implemented your improvements. Thanks for the help!

Do you perhaps know a command for my automated tests where I can force one enemy Pokemon in double battles to have Arena Trap and the other enemy some other ability? I have not found one yet. Maybe I can use `vi.spyOn()` for this?

2024-10-29 12:08 UTC, geeilhan reviewed
Changes for improvement have been implemented with the latest commit.

2024-10-29 20:07 UTC, geeilhan commented on src/field/pokemon.ts
>    isActive(onField?: boolean): boolean {
It would seem that way for me too but after checking the tests using `!!onField` instead of `!onField` many tests failed.
![(Screenshot)](https://github.com/user-attachments/assets/34869b3b-db05-463f-bb9b-3f42e866e2d3) This might be a Problem for an additional PR or Issue.
I have only looked into it a bit but it seems so far that `this.isOnField()` usually returns the correct boolean.
Additionally, only `isActive(true)` or `isActive()` are used in pokerogue. `isActive(false)` is never used.
I think because `this.isOnField()` returns the correct value and the input param is always undefined or true (in `isActive()` true would be false) in works correctly.

2024-10-29 20:11 UTC, flx-sta commented on src/field/pokemon.ts
>    isActive(onField?: boolean): boolean {
<img width="785" alt="image" src="https://github.com/user-attachments/assets/c320ff02-9986-4748-beb7-b954ad6f3c60">
Of course last person touched was sam..

Maybe the naming of the variable is just wrong then?

2024-10-29 20:39 UTC, DayKev commented on src/field/pokemon.ts
>    isActive(onField?: boolean): boolean {
I already have a fix for this in another PR.

2024-10-29 20:50 UTC, DayKev commented
> > Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.
> 
> I have implemented your improvements. Thanks for the help!
> 
> Do you perhaps know a command for my automated tests where I can force one enemy Pokemon in double battles to have Arena Trap and the other enemy some other ability? I have not found one yet. Maybe I can use `vi.spyOn()` for this?

Yeah, you can use `vi.Spyon(enemyPokemon, "getAbility", "get").mockReturnValue(allAbilities[Abilities.ARENA_TRAP]);` (might be slightly different, just typing that from memory) to "change" the ability of a specific Pokémon when the overrides can't be used.

2024-10-29 20:55 UTC, geeilhan commented
> > > Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.
> > 
> > 
> > I have implemented your improvements. Thanks for the help!
> > Do you perhaps know a command for my automated tests where I can force one enemy Pokemon in double battles to have Arena Trap and the other enemy some other ability? I have not found one yet. Maybe I can use `vi.spyOn()` for this?
> 
> Yeah, you can use `vi.Spyon(enemyPokemon, "getAbility", "get").mockReturnValue(allAbilities[Abilities.ARENA_TRAP]);` (might be slightly different, just typing that from memory) to "change" the ability of a specific Pokémon when the overrides can't be used.

Thanks for the hint :+1:

2024-10-30 19:08 UTC, geeilhan commented
> Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.

Automated test case in `src/test/abilities/arena_trap.test.ts` implemented

2024-10-30 20:32 UTC, PigeonBar commented on src/field/pokemon.ts
>    isActive(onField?: boolean): boolean {
I think `onField` is meant to tell the function whether or not to filter for Pokemon being on the field?

2024-11-04 02:26 UTC, DayKev commented on src/field/pokemon.ts
> +   */
```suggestion
```
Since a more accurate tsdoc is added in another PR, you can remove this one.

2024-11-04 02:26 UTC, DayKev commented on src/test/abilities/arena_trap.test.ts
> +   * is forcefully moved out of the field from moves such as Roar {@link Moves.ROAR}
```suggestion
   * This checks if the Player Pokemon is able to switch out/run away after the Enemy Pokemon with {@linkcode Abilities.ARENA_TRAP}
   * is forcefully moved out of the field from moves such as Roar {@linkcode Moves.ROAR}
```

2024-11-04 02:26 UTC, DayKev commented on src/test/abilities/arena_trap.test.ts
> +    const player2 = game.scene.getPlayerField()[1];
```suggestion
    const [ enemy1, enemy2 ] = game.scene.getEnemyField();
    const [ player1, player2 ] = game.scene.getPlayerField();
```

2024-11-04 02:26 UTC, DayKev commented on src/test/abilities/arena_trap.test.ts
> +    game.override.moveset([ Moves.ROAR, Moves.SPLASH ]);
```suggestion
    game.override
      .battleType("double")
      .enemyMoveset(Moves.SPLASH)
      .moveset([ Moves.ROAR, Moves.SPLASH ])
      .ability(Abilities.BALL_FETCH);
```

2024-11-04 02:26 UTC, DayKev commented on src/test/abilities/arena_trap.test.ts
> +    vi.spyOn(player2, "getAbility").mockReturnValue(allAbilities[Abilities.BALL_FETCH]);
```suggestion
```

2024-11-04 02:26 UTC, DayKev commented on src/test/abilities/arena_trap.test.ts
> +    game.move.select(Moves.SPLASH);
```suggestion
    game.move.select(Moves.SPLASH, 1);
```

2024-11-04 02:26 UTC, DayKev commented on src/test/abilities/arena_trap.test.ts
> +    await game.toNextTurn();
```suggestion
    game.move.select(Moves.SPLASH);
    game.move.select(Moves.SPLASH, 1);
    await game.toNextTurn();
```

2024-11-04 02:26 UTC, DayKev commented on src/test/abilities/arena_trap.test.ts
> +    expect(game.scene.getEnemyField()[1].isOnField()).toBe(true);
```suggestion
    expect(player1.isTrapped()).toBe(false);
    expect(player2.isTrapped()).toBe(false);
    expect(enemy1.isOnField()).toBe(false);
    expect(enemy2.isOnField()).toBe(true);
```

2024-11-04 09:38 UTC, geeilhan commented
@DayKev I have reviewed your changes and tested them on my device too. Everything seems to be working for me too.

2024-11-05 03:02 UTC, geeilhan commented
Are there still some issues with the tests or is there a weird interaction between my implementation and mystery encounters? The automated tests here keep failing.

2024-11-30 19:39 UTC, MokaStitcher approved these changes

2024-11-30 21:08 UTC, merged