[Feature] Add GROWTH sorting option to dropdown in Starter Select UI
pagefaultgames/pokerogue pull request #4790
Opened 2024-11-04 16:40 UTC by afa7789

## What are the changes the user will see?

New option at dropdown in starter selection to explore growth rate pokemons

## Why am I making these changes?

I wanted to sort by growth rate to see which mon`s are faster/slower

## What are the changes from a developer perspective?

Added just a column, and a case in the sorting part

### Screenshots/Videos

## How to test the changes?

not sure yet.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [] If I have text, did I make it translatable and add a key in the English locale file(s)?
no I did not. 
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-11-04 16:55 UTC, MokaStitcher commented
Thank you for your contribution

You need to also make a PR to the [translation repo](https://github.com/pagefaultgames/pokerogue-locales) to add the "sortByGrowth" string you want to use. You only need to add it for English. Link this PR in the locale one, and the other way around too.

We also need before and after screenshots or videos for these kind of changes
If you don't know how to run the game locally to test things we can help here or in the dev corner in the official discord

On the PR itself, I'm not entirely sure that sorting by growth rate makes complete sense since it's not as simple as "this Pokemon grows faster than this other one", but I could be convinced

2024-11-04 17:12 UTC, MokaStitcher commented on src/ui/starter-select-ui-handler.ts
>        new DropDownOption(this.scene, SortCriteria.NAME, new DropDownLabel(i18next.t("filterBar:sortByName")))
```suggestion
      new DropDownOption(this.scene, SortCriteria.NAME, new DropDownLabel(i18next.t("filterBar:sortByName"))),
```
Code fails to compile

2024-11-05 01:35 UTC, afa7789 commented
Hey Moka.

Im gonna do it later, just need some time due to work.

I dont actually think it matters, but it would be good to have, I wanted to
see which of my mins had a faster growth rate to be a supporter character.

And had to browse one by one so why not right ? I also strongly believe
sorting is great thing to have.

I think we could also have a sorting by egg moves ( number of unlocked eggs
moves ). ( Could be useful ).

Had some trouble locally setting it up, still going over the code base.

On Mon, Nov 4, 2024, 14:12 Moka ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/ui/starter-select-ui-handler.ts
> <https://github.com/pagefaultgames/pokerogue/pull/4790#discussion_r1828086969>
> :
>
> > @@ -490,6 +490,7 @@ export default class StarterSelectUiHandler extends MessageUiHandler {
>        new DropDownOption(this.scene, SortCriteria.CANDY, new DropDownLabel(i18next.t("filterBar:sortByCandies"))),
>        new DropDownOption(this.scene, SortCriteria.IV, new DropDownLabel(i18next.t("filterBar:sortByIVs"))),
>        new DropDownOption(this.scene, SortCriteria.NAME, new DropDownLabel(i18next.t("filterBar:sortByName")))
>
> ⬇️ Suggested change
>
> -      new DropDownOption(this.scene, SortCriteria.NAME, new DropDownLabel(i18next.t("filterBar:sortByName")))
> +      new DropDownOption(this.scene, SortCriteria.NAME, new DropDownLabel(i18next.t("filterBar:sortByName"))),
>
> Code fails to compile
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pagefaultgames/pokerogue/pull/4790#pullrequestreview-2413644551>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGNEMF5NFL73CUUQZA2W7WDZ66TJVAVCNFSM6AAAAABREVDCC2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMJTGY2DINJVGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-06 16:26 UTC, innerthunder requested changes
I think this would make more sense as a filtering option than as a sorting option since there isn't a clear linear relationship between all growth rates. Sorting could be misleading for the user when it comes to interpreting the meaning of "Erratic" and "Fluctuating" growth rates, for example, compared to other growth rates.

2024-11-06 17:33 UTC, CodeTappert commented
I do not really think this is necessary.

2024-11-06 19:04 UTC, afa7789 commented
Makes sense.
Okay we cant scrap the PR then.

On Wed, Nov 6, 2024, 14:34 Jannik Tappert ***@***.***> wrote:

> I do not really think this is necessary.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pagefaultgames/pokerogue/pull/4790#issuecomment-2460386351>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGNEMF5OAKE5FKA4AWXFNDTZ7JHJBAVCNFSM6AAAAABREVDCC2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINRQGM4DMMZVGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-07 04:01 UTC, closed without merging