[Bug] Fixing Encore's interactions with other Move Restriction moves
pagefaultgames/pokerogue pull request #4805
Opened 2024-11-06 20:19 UTC by frutescens

## What are the changes the user will see?
Encore will interact correctly with other Move Restriction moves like Torment and Disable. Previously, it would override them and allow the use of restricted moves. 

## Why am I making these changes?
A bug a day keeps the shareholders and the triage team happy. 
See #4745 

## What are the changes from a developer perspective?
Because Encore was implemented before the introduction of the MoveRestrictionBattlerTag class, it had a separate implementation from other Move Restriction moves. Encore would override any other move restriction battler tags as result. This PR converts Encore into a MoveRestrictionBattlerTag and removes checkFightOverride() --> which was specifically only used to execute Encore's effects. Now, Encore uses the same 'scaffolding' as move restriction battler tags. 

A test was created for Encore's interactions with other tags of MoveRestrictionBattlerTag.

### Screenshots/Videos
<Will film a video soon>

## How to test the changes?
1. Apply Encore and a move-restriction move on a target with a single move. 
2. Target should use Struggle depending on the move + quality of the move-restriction  

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-11-06 22:42 UTC, innerthunder requested changes

2024-11-06 22:42 UTC, innerthunder commented on src/phases/command-phase.ts
> +    }
You might be able to just use `pokemon.lapseTag(BattlerTagType.ENCORE)` here instead.

2024-11-06 22:42 UTC, innerthunder commented on src/test/moves/encore.test.ts
Needs more test coverage.

I wrote some other tests for this on my branch if you want to take a look: https://github.com/innerthunder/pokerogue/blob/encore-disable-fix/src/test/moves/encore.test.ts

2024-11-06 22:49 UTC, frutescens commented on src/test/moves/encore.test.ts
Do you want to push the first two tests to the branch? I would feel bad for taking away your credit

2024-11-06 23:51 UTC, innerthunder commented on src/test/moves/encore.test.ts
Sure, made a PR https://github.com/frutescens/pokerogue/pull/11

2024-11-07 01:45 UTC, DayKev commented on src/data/battler-tags.ts
> +   * @param lapseType
```suggestion
```

2024-11-07 01:45 UTC, DayKev commented on src/data/battler-tags.ts
> +   * @param user {@linkcode Pokemon}
```suggestion
   * @param user N/A
```

2024-11-07 23:32 UTC, DayKev approved these changes

2024-11-08 04:12 UTC, torranx approved these changes

2024-11-08 17:35 UTC, innerthunder approved these changes

2024-11-08 17:35 UTC, merged