[Move] Instruct
pagefaultgames/pokerogue pull request #4813
Opened 2024-11-07 19:59 UTC by Bertie690

## What are the changes the user will see?
Instruct actually works and calls the target's last used move correctly.
(ATM it doesn't work fully, but eventually...)

## Why am I making these changes?
Because I want funny klefki prankster instructing power trick shuckle rock slide. 

## What are the changes from a developer perspective?
Added `RepeatMoveAttr` for moves that force targets to repeat moves themselves. (This is distinct from `CopyMoveAttr` which has the user use a target's previous move)

### Screenshots/Videos
WIP

## How to test the changes?
WIP

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-11-07 20:15 UTC, innerthunder requested changes
Get rid of all the changes to overrides, `package-lock.json`, and `package.json`.

2024-11-07 20:15 UTC, innerthunder commented on src/data/move.ts
> +    }
These need to be covered in this attribute's `getCondition` function. There might be some overlap with the `lastMoveCopiableCondition` you already have, but doing this bypasses the usual failure handling in `phases/move-phase.ts`

2024-11-07 20:16 UTC, Bertie690 commented
> Get rid of all the changes to overrides, `package-lock.json`, and `package.json`.

Yessiree will do that at home

2024-11-08 19:59 UTC, Bertie690 commented
Requesting #3503 to be updated with this PR

2024-11-11 05:06 UTC, Bertie690 commented
I am officially doen now.
Have the other 2 videos on hard drive but can't upload because clipchamp is being a royal !@#?$ ATM.

2024-11-11 05:21 UTC, innerthunder commented on src/data/move.ts
> +    const lastMove = target.getLastXMoves(-1).find(m => m.move !== Moves.NONE);
```suggestion
    const lastMove = target.getLastXMoves().find(m => m.move !== Moves.NONE);
```

2024-11-11 05:21 UTC, innerthunder commented on src/data/move.ts
> +    target.scene.unshiftPhase(new MovePhase(target.scene, target, moveTargets!, movesetMove!, false, false));
This seems like it could easily be broken if the queue is somehow already populated. Maybe unshift the move queue entry instead of pushing it?

2024-11-11 12:11 UTC, Bertie690 commented on src/data/move.ts
> +    const lastMove = target.getLastXMoves(-1).find(m => m.move !== Moves.NONE);
Correct me if I'm wrong, but doesn't calling `getlastXMoves()` with an empty argument default to only grabbing the singular last move used?
We want to get the most recent move used that isn't a full paralysis, sleep turn, etc. (hence why I made it check em all for safety).

2024-11-11 19:09 UTC, innerthunder commented on src/data/move.ts
> +    target.scene.unshiftPhase(new MovePhase(target.scene, target, moveTargets!, movesetMove!, false, false));
Mirror Move does this for the user itself, which basically means it's safe to assume the move queue is empty when it's used. This is slightly different in that the targeted Pokemon may have a populated move queue when it's Instructed.

I know that a lot of the moves that add to the move queue are already set for Instruct to fail against, but I think changing this to `unshift` for both Instruct and Mirror Move would be the most robust way to implement them.

2024-11-11 19:12 UTC, innerthunder commented
Btw, please don't use your fork's `beta` branch for PRs. It makes it hard for us to checkout your branch for playtesting without affecting our own `beta` branch.

The best practice for dev work is to make a new branch for every PR/feature, named differently from any of the existing branches on upstream.

2024-11-12 04:33 UTC, Bertie690 commented
> Btw, please don't use your fork's `beta` branch for PRs. It makes it hard for us to checkout your branch for playtesting without affecting our own `beta` branch.
> 
> The best practice for dev work is to make a new branch for every PR/feature, named differently from any of the existing branches on upstream.

I completely forgot about this initially. Sorry!

2024-11-12 18:02 UTC, closed without merging

2024-11-12 18:02 UTC, Bertie690 commented
Closing PR to change commit branch.