[Move] Fully implement Freeze Dry
pagefaultgames/pokerogue pull request #4840
Opened 2024-11-10 15:29 UTC by geeilhan

## What are the changes the user will see?
Freeze-Dry now does the correct amount of damage.

## Why am I making these changes?
While I was working on the Bug Fix of Freeze-Dry interacting with a soaked wonder guard target I noticed that "Freeze-Dry" was not fully implemented and its interaction with "Electrify" as well as "Normalize" was faulty.
(#3503)

## What are the changes from a developer perspective?
If the Player Pkm gets hit by `Electrify` before its attack the type of `Freeze-Dry`  changes to electric. As a result the damage multiplier should change according to the [Wiki](https://bulbapedia.bulbagarden.net/wiki/Freeze-Dry_(move)).
If the move is of type electric it naturally has a super effectiveness against water/flying type pokemon (e.g.Gyarados). After already having a 4x multiplier against Gyarados the [`WaterSuperEffectTypeMultiplierAttr`](https://github.com/pagefaultgames/pokerogue/blob/2968059814dd714a1a855006adc6016b1f081a1b/src/data/move.ts#L4941-L4955) was forcefully applied even though the multiplier was correct which resulted in a 16x damage multiplier at the end of the calculation. 
A similar thing happened with `Freeze-Dry` under the effect of `Normalize`.

I have changed `WaterSuperEffectTypeMultiplierAttr` so it considers if `Normalize` is in effect or if the move has been affected by `Electrify`.

### Screenshots/Videos
Note: If you look at the right hand side of the recording you can see the mulitplier value through `console.log`

<details>
  <summary>Before Changes Electrify + Freeze Dry (Multiplier should be 4x but is 16x after calculation)</summary>

https://github.com/user-attachments/assets/c4c19396-cd43-46a0-8eaf-dbda3ad378a0

</details>
<details>
  <summary>Before Changes Normalize + Freeze Dry (Multiplier should be 2x but is 4x)</summary>

https://github.com/user-attachments/assets/6d41e0bb-6172-44e4-9a6c-8dfc63452a21

</details>
<details>
  <summary>After Changes Electrify + Freeze Dry</summary>

https://github.com/user-attachments/assets/a5fb177c-e516-44fc-aab7-2d8b573e7d82

</details>
<details>
  <summary>After Changes Normalize + Freeze Dry</summary>

https://github.com/user-attachments/assets/de826c00-45dc-42bc-9a8a-65fec492d9c4

</details>

## How to test the changes?
I used this to test Normalize:
```
const overrides = {
  MOVESET_OVERRIDE: [ Moves.FREEZE_DRY, Moves.ELECTRIFY, Moves.SEED_BOMB, Moves.SOAK ],
  ABILITY_OVERRIDE: Abilities.NORMALIZE,
  OPP_MOVESET_OVERRIDE: Moves.SPLASH ,
  OPP_SPECIES_OVERRIDE: Species.GYARADOS,
  OPP_ABILITY_OVERRIDE: Abilities.BALL_FETCH,
  OPP_LEVEL_OVERRIDE: 10,
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```
as well as this for Electriy:
```
const overrides = {
  MOVESET_OVERRIDE: [ Moves.FREEZE_DRY, Moves.ELECTRIFY, Moves.SEED_BOMB, Moves.SOAK ],
  OPP_MOVESET_OVERRIDE: Moves.ELECTRIFY ,
  OPP_SPECIES_OVERRIDE: Species.GYARADOS,
  OPP_ABILITY_OVERRIDE: Abilities.BALL_FETCH,
  OPP_LEVEL_OVERRIDE: 10,
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

Also some automated tests have been added to `src/test/moves/freeze_dry.test.ts` in order to test 0.25x dmg multiplier as well as 4x dmg

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

2024-11-10 19:18 UTC, Tempo-anon commented on src/data/move.ts
> +        if (user.getAbility().id === Abilities.NORMALIZE) {
Shouldn't this be a hasAbility check in case the user has a passive?

2024-11-10 19:18 UTC, Tempo-anon commented on src/test/moves/freeze_dry.test.ts
Is there a test for inverse battles in here? Bulbapedia says the move should do 2x against water even during inverse battles

2024-11-10 19:18 UTC, Tempo-anon commented on src/data/move.ts
> -        multiplier.value *= 2 / effectivenessAgainstWater.value;
nit: Since this attr is only used for a single move, I'd be okay with renaming it and also adding documentation to it

```ts
/**
 * Attribute used for Freeze Dry that deals super effective damage against water even during inverse or if the move's type is changed
 */
export class FreezeDryAttr extends VariableMoveTypeMultiplierAttr
```

2024-11-10 20:01 UTC, innerthunder commented on src/data/move.ts
> +        if (user.getAbility().id === Abilities.NORMALIZE) {
Yeah, that'd also check if the ability is suppressed (or ignored, but that's not really relevant here)

2024-11-10 20:34 UTC, geeilhan commented on src/data/move.ts
> +        if (user.getAbility().id === Abilities.NORMALIZE) {
Thanks will change this to hasAbility

2024-11-10 20:35 UTC, geeilhan commented on src/test/moves/freeze_dry.test.ts
I did not know inverse battles are implemented in here. I will have to revise the code in case of inverse battles

2024-11-10 22:07 UTC, geeilhan commented on src/test/moves/freeze_dry.test.ts
The super effectiveness against water type works for the inverse battle but not for the other types. Will need a little bit more time to figure that out.

2024-11-11 17:15 UTC, Tempo-anon commented on src/data/move.ts
> +export class FreezeDryAttr extends VariableMoveTypeMultiplierAttr {
nit: Would also like an overview TSdoc on the class, even if it's a quick 1 sentence summary

2024-11-11 17:15 UTC, Tempo-anon commented on src/data/move.ts
> +        if (user.getMoveType(move) !== Type.ELECTRIC) {
nit: I know this isn't a thing, but would it make sense for this to check for electric and grass for future proofing purposes?

2024-11-11 17:15 UTC, Tempo-anon commented on src/test/moves/freeze_dry.test.ts
> +  it("should deal 2x damage to Water type during inverse battle", async () => {
Can there also be some tests for normalize/electrify interactions under inverse?

2024-11-11 19:19 UTC, innerthunder reviewed
I feel like there's a cleaner way to do this. The Normalize and Electrify interactions kind of suggest that Freeze Dry directly sets the type multiplier to 2 against the Water type (while the normal type matchup still applies for the target's other types). The way it behaves in inverse battles seems to suggest the same. 

I'm not totally sure if this is actually the case and, if so, how well the attribute's parent class supports this, but I'd rather avoid the individual ability checks if possible.

2024-11-11 22:36 UTC, geeilhan commented on src/data/move.ts
> +        if (user.getMoveType(move) !== Type.ELECTRIC) {
I used to have grass type in here too but when I was thinking back the wiki only shows special interaction between freeze-dry and normalize/electrify so I removed the Type.GRASS check

2024-11-11 22:45 UTC, geeilhan commented on src/data/move.ts
> +        if (user.getMoveType(move) !== Type.ELECTRIC) {
I can still change it so it also checks for GRASS type. No incorrect behaviour happens if I do so.

2024-11-11 22:54 UTC, geeilhan commented
> I feel like there's a cleaner way to do this. The Normalize and Electrify interactions kind of suggest that Freeze Dry directly sets the type multiplier to 2 against the Water type (while the normal type matchup still applies for the target's other types). The way it behaves in inverse battles seems to suggest the same.
> 
> I'm not totally sure if this is actually the case and, if so, how well the attribute's parent class supports this, but I'd rather avoid the individual ability checks if possible.

The other classes that have `VariableMoveTypeMultiplierAttr` as a parent also force values like this. This seems to be a characteristic of this class. Either way it looks like l can't go around checking the conditions like this. 
Moving this check somewhere else would make `VariableMoveTypeMultiplierAttr` children classes obsolete.

2024-11-12 01:29 UTC, geeilhan commented on src/data/move.ts
> +export class FreezeDryAttr extends VariableMoveTypeMultiplierAttr {
Added documentation to `FreezeDryAttr` and `apply()`

2024-11-12 01:33 UTC, geeilhan commented on src/test/moves/freeze_dry.test.ts
> +  it("should deal 2x damage to Water type during inverse battle", async () => {
Added basic test cases for these edge cases.

2024-11-12 04:57 UTC, geeilhan commented on src/data/move.ts
> +        const effectivenessAgainstTarget = new Utils.NumberHolder(getTypeDamageMultiplier(move.type, target.getTypes().filter(types => types !== Type.WATER)[0]));
Thanks for review

2024-11-12 07:21 UTC, innerthunder requested changes

2024-11-12 07:21 UTC, innerthunder commented on src/data/move.ts
> +        const effectivenessAgainstTarget = new Utils.NumberHolder(getTypeDamageMultiplier(move.type, nonWaterType));
```suggestion
        const effectivenessAgainstTarget = new Utils.NumberHolder(getTypeDamageMultiplier(user.getMoveType(move), nonWaterType));
```
obtains the move's type after applying Normalize, etc.

2024-11-12 07:21 UTC, innerthunder commented on src/test/moves/freeze_dry.test.ts
> +  it("should deal 4x damage to water/flying type under Electrify", async () => {
This might cause false positives since Electric and Ice have the same effectiveness against Flying. It wouldn't catch what I suggested a fix for above.

Maybe another test for "should deal 0x damage to Water/Ghost (i.e. Jellicent) under Normalize" would help? Alternatively, you could test for Water/Ground types and Electrify...

2024-11-12 10:52 UTC, geeilhan commented on src/test/moves/freeze_dry.test.ts
> +  it("should deal 4x damage to water/flying type under Electrify", async () => {
added both test cases (Water/Ghost under Normalize and Water/Ground under Electrify)

2024-11-12 11:56 UTC, geeilhan commented on src/test/moves/freeze_dry.test.ts
> +  it("should deal 4x damage to water/flying type under Electrify", async () => {
Thanks for the review!

2024-11-12 21:14 UTC, innerthunder approved these changes

2024-11-13 01:57 UTC, DayKev approved these changes

2024-11-13 15:41 UTC, merged