add chinese locale, but translation is not yet complete.
pagefaultgames/pokerogue pull request #485
Opened 2024-05-05 09:42 UTC by Jane620

only for the code part and a small portion of text testing.

2024-05-05 16:27 UTC, Adri1 commented
I think it would be better to precise if it is traidtional Chinese or simplifed Chinese, including in the name of the folde not just named "cn"

2024-05-06 06:27 UTC, Aizzzs commented
Hello! I can offer assistance with localizing games into Chinese. I have experience in localizing Pokémon fan games!

2024-05-06 15:23 UTC, TempsRay commented
> I think it would be better to precise if it is traditional Chinese or simplifed Chinese, including not just naming it "cn" both in the name of the folder and in the code

I am not 100% on this but the locales for simplified Chinese should be zh-cn while Traditional should be zh-tw

2024-05-07 10:42 UTC, justhil commented
#592 I localized the skill names and traits into Chinese.

2024-05-08 01:38 UTC, justhil approved these changes
frontsize is too big

2024-05-08 02:16 UTC, justhil approved these changes

2024-05-08 02:48 UTC, justhil approved these changes

2024-05-08 03:10 UTC, Jane620 commented on src/system/settings.ts
change 'SETTINGS_SELECTED' to 66px seems to look better, however all the icons are misaligned.

2024-05-08 08:26 UTC, justhil commented on src/system/settings.ts
对齐要我命感觉这样也不是不能玩

2024-05-08 14:30 UTC, justhil commented on src/locales/chs/battle.ts
"pokemon": "宝可梦上吧！",  多打了个"上吧!"

2024-05-08 15:18 UTC, Madmadness65 requested changes
Just a couple small fixes requested, then it should be ready to go

2024-05-08 15:18 UTC, Madmadness65 commented on src/locales/chs/battle.ts
> +  "trainerAppeared": "{{trainerName}}\nwould like to battle!",
It looks this one line was overlooked

2024-05-08 15:18 UTC, Madmadness65 commented on src/system/settings.ts
> +                label: 'Simplifed  Chinese',
Minor spelling mistake, should be "Simplified"

2024-05-08 16:05 UTC, TempsRay commented
> > I think it would be better to precise if it is traditional Chinese or simplifed Chinese, including not just naming it "cn" both in the name of the folder and in the code
> 
> I am not 100% on this but the locales for simplified Chinese should be zh-cn while Traditional should be zh-tw

^ Thoughts on this?

2024-05-08 17:40 UTC, Adri1 commented
`src/system/settings.ts` have just been modified with the names of the languages labeled in their repsective languages and not just in English, so you may to edit it

2024-05-08 23:45 UTC, Haleclipse commented
1.Normalized category fixes for supportedLngs lists

Currently the language codes in "supportedLngs" are all abbreviated, which leads to an error in the automatic language recognition, at least for zh-CN recognition, which does not fall back to zh or so-called chs correctly.

2. Replace similar pixel fonts to display GBK characters correctly.

The pokemon-emerald-pro.ttf does not contain GBK characters, causing Phaser to process GBK characters with the font being displayed on the user's side. For this reason, I replaced pokemon-emerald-pro.ttf with [MuZaiPixel](https://github.com/DWNfonts/MuzaiPixel/blob/main/MZPXorig.ttf)

3. Fixed the vast majority of display overflow errors in translations due to inappropriate text lengths.

2024-05-09 03:55 UTC, Madmadness65 approved these changes

2024-05-09 03:59 UTC, merged

2024-06-07 10:38 UTC, davidyan-hub commented
I did not have envirement to do this...
Who can modify the text.ts to change the font-family and font-size for chinese.

Code as below:

fontFamily: localStorage.getItem('prLang')==="zh_CN"?'simhei':'emerald',

styleOptions.fontFamily = localStorage.getItem('prLang')==="zh_CN"?'MuZaiPixel':'pkmnems';

and same judgement logic for changing font-size, let the size is smaller.