QOL - Settings to choose party Exp display at the end of fight
pagefaultgames/pokerogue pull request #488
Opened 2024-05-05 12:45 UTC by Greenlamp2

I've added a new setting:
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/983f9b84-db39-499e-a23e-e477cfdf14f0)

**Normal**: Same as current, nothing changed.

**Only Up**: Display the text: 'Lv. UP' instead of the experience gained and does not display 'Pokemon grew to Lv. XX', evolution, move learn, etc still displayed when they occurs

**Skip**: Display nothing on level up, evolution, move learn, etc still displayed when they occurs.

"**Show stats on level up**" setting ignored ONLY when the previous setting is set on "skip".

**Normal**:
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/dae9b5cb-6b25-4f43-a753-23d794d67df6)

**Only Up**:
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/de24fc15-300a-4107-a9f4-32ffc9c81adc)

2024-05-09 01:47 UTC, bennybroseph requested changes
let's get some comments for this change

2024-05-09 20:19 UTC, bennybroseph requested changes

2024-05-09 23:21 UTC, Greenlamp2 commented
@Flashfyre I've renammed the "Only Up" To "Level Up Notification" and "Exp Party" to "Exp Party Display"
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/7a7d48c8-70cc-4ecc-84a5-9ad9b70662f0)

i have no idea left on how i can make the labels and name clearer

2024-05-10 13:50 UTC, Flashfyre requested changes

2024-05-10 13:50 UTC, Flashfyre commented on src/ui/party-exp-bar.ts
> +          this.expText.setText(`Lv. UP : ${newLevel.toString()}`);
```suggestion
          this.expText.setText(`Lv. UP: ${newLevel.toString()}`);
```

2024-05-10 13:54 UTC, Flashfyre approved these changes

2024-05-10 13:54 UTC, merged