[Ability] Fully implement Sheer Force
pagefaultgames/pokerogue pull request #4890
Opened 2024-11-16 23:37 UTC by frutescens

## What are the changes the user will see?
Pokemon with Sheer Force will no longer benefit from healing of Shell Bell.
If Meloetta happens to have the ability Sheer Force when using Relic Song, she does not transform.  

## Why am I making these changes?
Shareholder value up!

## What are the changes from a developer perspective?
Conditionals added to MeloettaFormChangePostMoveTrigger and HitHealModifier that check for Sheer Force. Tests also added. 

## How to test the changes?
1. Use Relic Song with a Meloetta that has the ability Sheer Force
2. Use a Pokemon with Sheer Force + Shell Bell. It should not heel.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

2024-11-17 02:58 UTC, Snailman11 commented
very small chance that it fixes
https://github.com/pagefaultgames/pokerogue/issues/2354
(Sheer force edge cases)

2024-11-18 00:52 UTC, innerthunder commented
It'd be nice if you could rewrite the other Sheer Force tests along with this change. The tests right now tend to follow a bad pattern where they try to replicate their own code (applying the ability's attributes, etc.) and test against that output. If the components used aren't implemented correctly, the tests won't catch that, so the current tests hardly prove anything.

2024-11-18 09:24 UTC, innerthunder requested changes
There are a few items incorrectly being cancelled out here...

2024-11-18 09:24 UTC, innerthunder commented on src/data/pokemon-forms.ts
> +      if (pokemon.hasAbility(Abilities.SHEER_FORCE, true)) {
```suggestion
      if (pokemon.hasAbility(Abilities.SHEER_FORCE)) {
```
`true` is the default value

2024-11-18 09:24 UTC, innerthunder commented on src/modifier/modifier.ts
> +    const sheerForceAffected = pokemon.hasAbility(Abilities.SHEER_FORCE, true);
```suggestion
    const sheerForceAffected = pokemon.hasAbility(Abilities.SHEER_FORCE);
```

2024-11-18 09:24 UTC, innerthunder commented on src/modifier/modifier.ts
> +    } else if (pokemon.hasAbility(Abilities.SERENE_GRACE, true)) {
```suggestion
    } else if (pokemon.hasAbility(Abilities.SERENE_GRACE)) {
```

2024-11-18 09:24 UTC, innerthunder commented on src/modifier/modifier.ts
> +    }
```suggestion
```
Scope Lens shouldn't be affected by Sheer Force

2024-11-18 09:24 UTC, innerthunder commented on src/modifier/modifier.ts
> +    return super.shouldApply(pokemon, critStage) && super.getSecondaryChanceMultiplier(pokemon) !== 0 && (this.species.includes(pokemon.getSpeciesForm(true).speciesId) || (pokemon.isFusion() && this.
```suggestion
    return super.shouldApply(pokemon, critStage) && (this.species.includes(pokemon.getSpeciesForm(true).speciesId) || (pokemon.isFusion() && this.species.includes(pokemon.getFusionSpeciesForm(true).speciesId)));
```
Same deal as Scope Lens. These items are applied during attacks, not as a subsequent effect, so Sheer Force shouldn't negate their effects

2024-11-18 09:24 UTC, innerthunder commented on src/modifier/modifier.ts
> +    }
```suggestion
```
Same as the other items, not a post-attack effect

2024-11-18 09:24 UTC, innerthunder commented on src/modifier/modifier.ts
> +    }
```suggestion
```

2024-11-19 23:41 UTC, innerthunder submitted a review, later dismissed

2024-11-30 19:49 UTC, DayKev commented on src/modifier/modifier.ts
> +    // The check for pokemon.battleSummonData is to ensure that a crash doesn't occur when a Pokemon with King's Rock procs a flinch
There's no check for `pokemon.battleSummonData` though?

2024-11-30 20:58 UTC, PigeonBar commented on src/data/ability.ts
> -      .edgeCase() // Should disable shell bell and Meloetta's relic song transformation
Just realized that we forgot to also add the shell bell interaction to this PR

2024-11-30 21:21 UTC, PigeonBar commented on src/modifier/modifier.ts
>        return true;
```suggestion
      const sheerForceAffected = allMoves[pokemon.getLastXMoves()[0].move].chance >= 0 && pokemon.hasAbility(Abilities.SHEER_FORCE);
      if (!sheerForceAffected) {
        flinched.value = true;
        return true;
      }
```
Assuming that Sheer Force activation should still disable King's Rock

2024-12-01 00:38 UTC, frutescens commented on src/modifier/modifier.ts
>        return true;
Ah, no. It will be separate from King's Rock.

2024-12-01 00:39 UTC, frutescens commented on src/data/ability.ts
> -      .edgeCase() // Should disable shell bell and Meloetta's relic song transformation
Ah, this was my bad for not updating the description but Balance decided to have item effects separate from moves so shell bell will not be affected by sheer force + shell bell will not boost the BP of moves when held by the pokemon. Same with King's Rock, etc.

2024-12-01 02:21 UTC, innerthunder approved these changes

2024-12-01 02:36 UTC, frutescens commented
![image](https://github.com/user-attachments/assets/ff4e5f88-f0aa-4621-a6fc-48461fe049b4)

2024-12-01 02:40 UTC, merged