[Bug] Honey Gather and Pickup will only activate if the battle was won
pagefaultgames/pokerogue pull request #4903
Opened 2024-11-18 00:31 UTC by DayKev

## What are the changes the user will see?
Honey Gather and Pickup will now only activate if the player wins the battle (ie: the enemy Pokémon were fainted; neither the player nor the enemy ran away).

## Why am I making these changes?
Bugfix.

## What are the changes from a developer perspective?
`BattleEndPhase`'s `isVictory` parameter is no longer set to `true` if either the player or enemy ran away, and it's passed to `applyPostBattleAbAttrs()` so Honey Gather and Pickup can check if it's `true` or `false`.

## How to test the changes?

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

2024-11-19 07:47 UTC, innerthunder requested changes

2024-11-19 07:47 UTC, innerthunder commented on src/phases/battle-end-phase.ts
There are some stats that should be updated outside of a victory but aren't, namely:
- `battles` (L23, counts total number of battles)
- `highestEndlessWave` (L27-29)

2024-11-28 08:00 UTC, innerthunder approved these changes

2024-11-29 01:25 UTC, frutescens commented on src/phases/battle-end-phase.ts
Resolving conversation based on recent commit + subsequent approval.

2024-11-29 01:26 UTC, frutescens approved these changes

2024-11-29 21:29 UTC, merged