[Bug Fix] Fix for Octolock bypasses Ghost Invulnerability to lower Stats
pagefaultgames/pokerogue pull request #4923
Opened 2024-11-20 01:32 UTC by PrabbyDD

## What are the changes the user will see?
octolock properly interacts with ghost types

## Why am I making these changes?
Fix for #4867 

## What are the changes from a developer perspective?
changed some tests around and removed some obsolete ones, as well as just removing canAdd from octolock tag

## Screenshots/Videos

https://github.com/user-attachments/assets/4be1b605-c3a5-460d-b213-8b2dc859ad54

https://github.com/user-attachments/assets/d977f00e-921a-4eac-aee6-087d98aeac62

## How to test the changes?
override files, as well as tests

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes manually?
- [ ] Are all unit tests still passing? (`npm run test`)
  - [ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

Are there any localization additions or changes? If so:
- [ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?
  - [ ] If so, please leave a link to it here: 
- [ ] Has the translation team been contacted for proofreading/translation?

2024-11-20 01:45 UTC, innerthunder requested changes
The move should fail when used against a Ghost-type instead of resolving and doing nothing.

I think the best approach to fix this would be to add a `.condition()` function to Octolock, Block, Mean Look, and Spider Web.

2024-11-20 02:17 UTC, PrabbyDD commented
What is the intent of using the .condition()? Do I need to subtmit some function into it that checks whether the pokemon is a ghost type and then if it queue a message?

2024-11-26 08:49 UTC, DayKev submitted a review, later dismissed

2024-11-28 07:19 UTC, frutescens submitted a review, later dismissed

2024-11-28 07:19 UTC, frutescens commented on src/test/moves/octolock.test.ts
> +  it("does not work on ghost type pokemon", async () => {
Could you add an additional test that checks for that this fix applies to a Pokemon affected by Trick O' Treat?

2024-11-28 07:31 UTC, innerthunder commented on src/data/move.ts
> +      .condition(failIfGhostType)
```suggestion
      .condition(failIfGhostTypeCondition)
```

2024-11-28 07:31 UTC, innerthunder commented on src/data/move.ts
> +      .condition(failIfGhostType)
```suggestion
      .condition(failIfGhostTypeCondition)
```

2024-11-29 21:40 UTC, DayKev approved these changes

2024-11-30 01:55 UTC, innerthunder approved these changes

2024-11-30 10:05 UTC, CodeTappert approved these changes

2024-11-30 10:06 UTC, merged