[Move][Beta] Powder edge cases
pagefaultgames/pokerogue pull request #4960
Opened 2024-12-02 03:26 UTC by PigeonBar

## What are the changes the user will see?

1. When Powder cancels a Fire-type move, the Fire-type move's PP now gets consumed.
2. Powder no longer deals damage when a Fire-type move gets cancelled by Primordial Sea.

## Why am I making these changes?

Adding some polish based on edge cases listed on [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Powder_(move)).

## What are the changes from a developer perspective?

1. `PowderTag` has a check for Primordial Sea and no longer activates when Primordial Sea is active.
2. `PowderTag` now tells `MovePhase` to "fail" a Fire-type move instead of "cancelling" it, so that PP gets consumed.
3. Removed an `edgeCase()` tag for Dancer, since the interaction actually works correctly. (The corresponding test was broken due to Powder never actually getting used, so I fixed it.)
4. Added some tests. This includes tests for interactions with Pledge moves, which work correctly without any modifications.

## Screenshots/Videos

<details>
<summary> Before the changes: Ember has 25/25 PP after activating Powder </summary>

https://github.com/user-attachments/assets/6272dc8d-601d-46cc-baff-244444b8fec9

</details>
<details>
<summary> After the changes: Ember has 24/25 PP after activating Powder </summary>

https://github.com/user-attachments/assets/e7b975d6-839a-44db-b683-00f199fb9159

</details>
<details>
<summary> Before the changes: Powder deals damage when Fire-type move gets cancelled by Primordial Sea </summary>

https://github.com/user-attachments/assets/b5d06dfe-52a3-4f4a-beb8-aa2f5b88715a

</details>
<details>
<summary> After the changes: Powder no longer deals damage when Fire-type move gets cancelled by Primordial Sea </summary>

https://github.com/user-attachments/assets/332c5150-7b4a-49c8-8321-9e623f6050b8

</details>

## How to test the changes?

`npm run test powder`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?

2024-12-02 04:04 UTC, DayKev submitted a review, later dismissed

2024-12-02 15:04 UTC, MokaStitcher approved these changes

2024-12-02 19:41 UTC, innerthunder requested changes

2024-12-02 19:41 UTC, innerthunder commented on src/data/battler-tags.ts
> +        if (pokemon.getMoveType(move) === Type.FIRE && pokemon.scene.arena.weather?.weatherType !== WeatherType.HEAVY_RAIN) {
Needs a check for weather suppression

2024-12-02 20:53 UTC, PigeonBar commented on src/data/battler-tags.ts
> +        if (pokemon.getMoveType(move) === Type.FIRE && pokemon.scene.arena.weather?.weatherType !== WeatherType.HEAVY_RAIN) {
https://github.com/pagefaultgames/pokerogue/blob/c6e80de1be8bec58e515efc2c3a8b7d44c8d3f6c/src/field/arena.ts#L344-L346

It's the same check that is used for Heavy Rain cancelling a Fire-type move, so it should be good

2024-12-02 22:04 UTC, DayKev commented on src/data/battler-tags.ts
> +        if (pokemon.getMoveType(move) === Type.FIRE && pokemon.scene.arena.weather?.weatherType !== WeatherType.HEAVY_RAIN) {
The code you linked has a weather suppression check but this PR doesn't.

> https://github.com/pagefaultgames/pokerogue/blob/c6e80de1be8bec58e515efc2c3a8b7d44c8d3f6c/src/field/arena.ts#L344-L346
> 
> It's the same check that is used for Heavy Rain cancelling a Fire-type move, so it should be good

2024-12-03 02:49 UTC, DayKev commented on src/data/battler-tags.ts
> +        if (pokemon.getMoveType(move) === Type.FIRE && pokemon.scene.arena.weather?.weatherType !== WeatherType.HEAVY_RAIN) {
```suggestion
        const weather = pokemon.scene.arena.weather;
        if (pokemon.getMoveType(move) === Type.FIRE && !(weather && weather.weatherType === WeatherType.HEAVY_RAIN && !weather.isEffectSuppressed(pokemon.scene))) {
```

2024-12-03 02:55 UTC, PigeonBar commented on src/data/battler-tags.ts
> +        if (pokemon.getMoveType(move) === Type.FIRE && pokemon.scene.arena.weather?.weatherType !== WeatherType.HEAVY_RAIN) {
Sorry, I meant to say that your changes look good

2024-12-03 03:15 UTC, DayKev approved these changes

2024-12-03 03:48 UTC, innerthunder requested changes

2024-12-03 03:48 UTC, innerthunder commented on src/data/battler-tags.ts
> +          movePhase.fail();
```suggestion
          movePhase.fail();
          movePhase.showMoveText();
```

"{Pokemon} used {move}!" is meant to show before Powder explodes but currently doesn't. This is kind of a bandaid fix since it's awkward to implement this within the `PRE_MOVE` or `MOVE` lapse types

2024-12-03 04:10 UTC, DayKev approved these changes

2024-12-03 04:14 UTC, innerthunder approved these changes

2024-12-03 06:28 UTC, merged