[Move] Add makeContact To Physical Part Of Shell Side Arm
pagefaultgames/pokerogue pull request #4982
Opened 2024-12-10 09:05 UTC by geeilhan

## What are the changes the user will see?

The user now makes physical contact if Shell Side Arm does physical damage.

## What are the changes from a developer perspective?

Now calls `makesContact()` if move turns physical.

Removed `.partial()` 

Added test that checks for contact

## Screenshots/Videos

Before changes vs Rough Skin:

[shell-side-arm-implementation-before.webm](https://github.com/user-attachments/assets/b858a4ad-c51f-48c2-ae12-5e86841b4739)

After changes vs Rough Skin:

[shell-side-arm-implementation-after.webm](https://github.com/user-attachments/assets/13967dd3-e747-4091-a9ac-34aac31340a7)

## How to test the changes?

Give enemy Pokemon Rough Skin (Ability) and use Side Shell Arm. Make sure the enemy Pokemon has more SPDEF than DEF.

## Checklist
- [ ] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes manually?
- [ ] Are all unit tests still passing? (`npm run test`)
  - [ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

2024-12-10 16:23 UTC, Tempo-anon commented
Hey geeilhan, are you on the discord server? I have some questions

2024-12-10 18:49 UTC, Tempo-anon requested changes
I don't think this works as it's making contact even when special. Can you add the following test?
```ts
  it("should not make contact if the move becomes special", async () => {
    game.override.enemySpecies(Species.SLOWBRO).enemyAbility(Abilities.ROUGH_SKIN);

    await game.classicMode.startBattle([Species.XURKITREE]);

    const player = game.scene.getPlayerPokemon()!;

    game.move.select(Moves.SHELL_SIDE_ARM);
    await game.toNextTurn();

    expect(player.getMaxHp()).toBe(player.hp);
  });
```

2024-12-11 00:16 UTC, geeilhan commented
> I don't think this works as it's making contact even when special. Can you add the following test?
> 
> ```ts
>   it("should not make contact if the move becomes special", async () => {
>     game.override.enemySpecies(Species.SLOWBRO).enemyAbility(Abilities.ROUGH_SKIN);
> 
>     await game.classicMode.startBattle([Species.XURKITREE]);
> 
>     const player = game.scene.getPlayerPokemon()!;
> 
>     game.move.select(Moves.SHELL_SIDE_ARM);
>     await game.toNextTurn();
> 
>     expect(player.getMaxHp()).toBe(player.hp);
>   });
> ```

Thanks for 

> I don't think this works as it's making contact even when special. Can you add the following test?
> 
> ```ts
>   it("should not make contact if the move becomes special", async () => {
>     game.override.enemySpecies(Species.SLOWBRO).enemyAbility(Abilities.ROUGH_SKIN);
> 
>     await game.classicMode.startBattle([Species.XURKITREE]);
> 
>     const player = game.scene.getPlayerPokemon()!;
> 
>     game.move.select(Moves.SHELL_SIDE_ARM);
>     await game.toNextTurn();
> 
>     expect(player.getMaxHp()).toBe(player.hp);
>   });
> ```

Thanks for the feedback. Will implement this too

2024-12-11 01:16 UTC, Tempo-anon commented
That is weird. For reference I was testing out something like 
```ts
override apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
    const category = args[0] as NumberHolder;

    const predictedPhysDmg = target.getBaseDamage(user, move, MoveCategory.PHYSICAL, true, true);
    const predictedSpecDmg = target.getBaseDamage(user, move, MoveCategory.SPECIAL, true, true);

    // Random chance of being physical or special if predicted damage is tied
    if (predictedPhysDmg > predictedSpecDmg || (predictedPhysDmg === predictedSpecDmg && user.randSeedInt(2) === 0)) {
      category.value = MoveCategory.PHYSICAL;
      move.makesContact();
      console.log("CONTACT");
      return true;
    }
    move.makesContact(false);
    console.log("NO CONTACT");
    return false;
  }
```
and when I `npm run test shell_side_arm` I get the following output
```
stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ { targets: [ 2 ], multiple: false }, 'Xurkitree' ]
[ 'setMode', 'MESSAGE (=0)', [] ]
[ '%cStart Phase EnemyCommandPhase', 'color:green;' ]

stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ '%cStart Phase TurnStartPhase', 'color:green;' ]

stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ '%cStart Phase MovePhase', 'color:green;' ]

stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ 'SHELL_SIDE_ARM' ]
[ '%cStart Phase MessagePhase', 'color:green;' ]

stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ 'Xurkitree used Shell Side Arm!' ]
[ '%cStart Phase MoveEffectPhase', 'color:green;' ]

stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ 'NO CONTACT' ]
[ 'crit stage: +0' ]
[ 'NO CONTACT' ]
[ 'base damage', 161.8754098360656, 'Shell Side Arm', 90, 387, 183 ]
[ 'damage', 161, 'Shell Side Arm' ]
[ '%cStart Phase DamageAnimPhase', 'color:green;' ]

stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ '%cStart Phase DamageAnimPhase', 'color:green;' ]

stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ '%cStart Phase ShowAbilityPhase', 'color:green;' ]

stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ '%cStart Phase MessagePhase', 'color:green;' ]

stdout | src/test/moves/shell_side_arm.test.ts > Moves - Shell Side Arm > should not make contact if the move becomes special
[ "Wild Slowbro's Rough Skin\nhurt its attacker!" ]
[ '%cStart Phase MoveEndPhase', 'color:green;' ]

AssertionError: expected 276 to be 242 // Object.is equality
```

So it's definitely reaching the line where it's logging NO CONTACT but it's still having contact.

2024-12-11 01:22 UTC, geeilhan commented
> That is weird. 
> So it's definitely reaching the line where it's logging NO CONTACT but it's still having contact.

Yes I found the same issue so I thought that maybe MAKES_CONTACT is set when the constructor is called or somewhere else at the beginning but it not set anywhere

2024-12-11 01:35 UTC, geeilhan commented
> > That is weird.
> > So it's definitely reaching the line where it's logging NO CONTACT but it's still having contact.
> 
> Yes I found the same issue so I thought that maybe MAKES_CONTACT is set when the constructor is called or somewhere else at the beginning but it not set anywhere

So the solution for the tests to work was to move the no-contact-test to the top of the automated tests...

2024-12-11 02:03 UTC, geeilhan reviewed
Tests should work now

2024-12-11 18:08 UTC, Tempo-anon commented
Yep looks like tests pass with that. Strangely, replacing the code block
```ts
    if (move.hasFlag(MoveFlags.MAKES_CONTACT)) {
      move.makesContact(false);
    }
```
with just `move.makesContact(False);` results in the test failing 🤔

2024-12-11 18:10 UTC, Tempo-anon submitted a review, later dismissed

2024-12-11 18:32 UTC, flx-sta commented on src/data/move.ts
> +    }
should probably wrap it in a descriptive method (private?).

e.g.
```ts
private resetFlags() {
// MoveFlags are not reset every turn so if this flag is set it needs to be reset if the move is a special attack
 if (move.hasFlag(MoveFlags.MAKES_CONTACT)) {
      move.makesContact(false);
    }
}

2024-12-11 18:35 UTC, geeilhan commented
> Yep looks like tests pass with that. Strangely, replacing the code block
> 
> ```ts
>     if (move.hasFlag(MoveFlags.MAKES_CONTACT)) {
>       move.makesContact(false);
>     }
> ```
> 
> with just `move.makesContact(False);` results in the test failing 🤔

I think that is because `move.makesContact(False);` XORs the flag MAKES_CONTACT and not removes it. 
This would basically set the MAKES_CONTACT flag in some situations instead of removing the flag if `move.makesContact(False);` is called unconditionally.

2024-12-11 18:37 UTC, geeilhan commented
> Yep looks like tests pass with that. Strangely, replacing the code block
> 
> ```ts
>     if (move.hasFlag(MoveFlags.MAKES_CONTACT)) {
>       move.makesContact(false);
>     }
> ```
> 
> with just `move.makesContact(False);` results in the test failing 🤔

This does seem weird

2024-12-11 18:43 UTC, geeilhan commented on src/data/move.ts
> +    }
Added this method as descriptive method.

2025-07-22 04:19 UTC, SirzBenjie commented
So the fix for this works but it is a bit hacky in that it adds state to the move attribute itself.
I think we can port this over when we eventually revisit fixing shell side arm. Hopefully sooner rather than later.

2025-07-22 04:19 UTC, closed without merging