Facade should ignore burn damage reduction
pagefaultgames/pokerogue pull request #530
Opened 2024-05-06 02:54 UTC by mattrossdev

Facade should ignore the burn damage reduction of physical moves: https://bulbapedia.bulbagarden.net/wiki/Facade_(move)

I didn't add a move flag for this because it only applies to this move, but I can rewrite it that way if that's preferred. 

Testing: 
- non facade contact moves do half damage when burned 
- facade does 2x damage if burned

2024-05-06 18:48 UTC, happinyz commented
Just curious, do you happen to know if Guts also has the same bug?

2024-05-06 19:09 UTC, mattrossdev commented
> Just curious, do you happen to know if Guts also has the same bug?

Just looking at the code I don't think so but haven't tested

2024-05-11 00:30 UTC, bennybroseph requested changes

2024-05-11 00:30 UTC, bennybroseph commented on src/field/pokemon.ts
> +            if (isPhysical && source.status && source.status.effect === StatusEffect.BURN && move.id !== Moves.FACADE) {
i think we can move this check to the front of the if statement, no? There's no reason to check anything else if you're using Facade.

2024-05-11 01:51 UTC, mattrossdev commented on src/field/pokemon.ts
> +            if (isPhysical && source.status && source.status.effect === StatusEffect.BURN && move.id !== Moves.FACADE) {
Updated

2024-05-11 02:11 UTC, bennybroseph commented
Would like to make this an Attribute instead of hard-coding only Facade to work like this. Abilities are already doing so right below this code, so let's be consistent.

2024-05-11 02:12 UTC, bennybroseph requested changes

2024-05-11 02:12 UTC, bennybroseph commented on src/field/pokemon.ts
>                if (!burnDamageReductionCancelled.value)
referring to these few lines here

2024-05-11 03:12 UTC, bennybroseph requested changes

2024-05-11 03:12 UTC, bennybroseph commented on src/data/move.ts
> +    return true
need a semi-colon here

2024-05-11 03:12 UTC, bennybroseph commented on src/data/move.ts
> +
Would like to get TSDoc documentation for this class/function

2024-05-11 21:09 UTC, bennybroseph approved these changes

2024-05-13 18:06 UTC, merged