Repels Implementation
pagefaultgames/pokerogue pull request #544
Opened 2024-05-06 09:12 UTC by ojukeihpos

Implements all types of Repels (Regular, Super, and Max) with functionality as described on the [Trello Board](https://trello.com/c/1TSW0HSz/29-add-repels). Repels last for (5/10/25) waves and prevent double battles from occurring (including trainer doubles) by checking if the player has the modifier active during `newBattle()`, and overriding the double parameter to be false.

Also modifies the weightings of both repels and lures so that they do not show up in the shop if the player already has one of either.

2024-05-06 12:48 UTC, Flashfyre requested changes
Avoiding running a formatter on the code next time, it makes changes hard to read.

2024-05-06 12:48 UTC, Flashfyre commented on src/battle-scene.ts
> +			double = false;
I don't think this is the right place to put this. This is for initialization and whether it's set or not depends on whether data is being loaded.

2024-05-06 18:37 UTC, Flashfyre requested changes

2024-05-06 18:37 UTC, Flashfyre commented on src/battle-scene.ts
> +					let doubleChance = new Utils.IntegerHolder(newWaveIndex % 10 === 0 ? 32 : 8);
This was fine as const

2024-05-06 18:37 UTC, Flashfyre commented on src/battle-scene.ts
> +				let doubleChance = new Utils.IntegerHolder(newWaveIndex % 10 === 0 ? 32 : 8);
Same as above.

2024-05-06 18:37 UTC, Flashfyre commented on src/battle-scene.ts
> +				if (this.getModifiers(DoubleBattleChancePreventerModifier).length != 0) newDouble = false;
```suggestion
				if (this.getModifiers(DoubleBattleChancePreventerModifier).length != 0)
					newDouble = false;
```

2024-05-06 18:37 UTC, Flashfyre commented on src/modifier/modifier-type.ts
> +    super(name, `Prevents the chance of an encounter being a double battle for ${battleCount} battles`, (_type, _args) => new Modifiers.DoubleBattleChancePreventerModifier(this, this.battleCount),
```suggestion
    super(name, `Prevents double battles for ${battleCount} battles`, (_type, _args) => new Modifiers.DoubleBattleChancePreventerModifier(this, this.battleCount),
```

2024-05-06 18:37 UTC, Flashfyre commented on src/modifier/modifier-type.ts
> +      //return existingItem ? 0 : 2;
Debug code left

2024-05-06 18:37 UTC, Flashfyre commented on src/overrides.ts
> +export const SEED_OVERRIDE = 'b3DoubDG5i4izShAO06Z2V2y';
Debug code left

2024-05-06 18:39 UTC, ojukeihpos commented
For whatever reason trying to grab the latest commits from the main repo completely broke whatever I had, I'll fix it and reopen

2024-05-19 14:15 UTC, bennybroseph requested changes
Could we get a video of this move working in game?

Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

2024-05-19 14:15 UTC, bennybroseph commented on package-lock.json
These changes need to be reverted

2024-05-19 15:50 UTC, ojukeihpos commented on package-lock.json
hi Benny, I'm not sure what changes you mean. I didn't make any changes to `package-lock.json`, do you mean that I should pull the version from the main repo? I also don't know how I would make a video of the item working in game as the main function of the item is to prevent the occurrence of something happening.

I will add comments as per the documentation.

2024-05-19 16:17 UTC, bennybroseph commented on package-lock.json
I'm unsure, but changes to package-lock.json are committed here and need to be removed.

As for the video, you are still able to show the item itself in the shop, the description, etc.

2024-05-19 19:40 UTC, bennybroseph requested changes

2024-05-19 19:40 UTC, bennybroseph commented on src/overrides.ts
We don't commit changes to the override

2024-05-19 19:42 UTC, ojukeihpos commented on src/overrides.ts
Yeah, I'm trying to clean up the commits. I'll make a comment when I have things cleaned up, but to be quite honest, things are kind of a mess here and the dev-corner channel is closed

2024-05-19 21:00 UTC, ojukeihpos commented
https://github.com/pagefaultgames/pokerogue/assets/10471964/e699a9e9-ed9f-4ff5-a7e8-edc103394804

Video is subtitled, explanation of implementation is written here for easy access:

The implementation was tested by setting the double battle override to true, forcing double battles to always occur.
Normal Repel weighting was set to 10000 to ensure it appears in the store for demonstration purposes.

When `newBattle()` is called, there is a check for if a modifier of `DoubleBattleChanceModifierType` exists in the player's modifiers list. If it does, then one of the following occurs:

If the `newBattleType` is a Trainer, the `doubleTrainer` value is overwritten to always be `false`. This does not apply if the Trainer can ONLY be a double battle.
Otherwise, `newDouble`'s value is overwritten to always be false as long as the player has a Repel.

This also overrides the `DOUBLE_BATTLE_OVERRIDE` value. Let me know if that shouldn't be the case.

2024-07-11 17:50 UTC, Tempo-anon commented
Closing due to inactivity and merge conflicts. We're also not sure if we want repels right now.

2024-07-11 17:50 UTC, closed without merging