fix scrappy and mindseye working as passive ability
pagefaultgames/pokerogue pull request #567
Opened 2024-05-06 20:21 UTC by contra1337

- change the attribute apply to more properly use the cancelled param
- apply the attribute for active and passive abilities
- mark minds eye as partially implemented

2024-05-06 20:32 UTC, contra1337 commented on src/field/pokemon.ts
> +      if (source && source.hasAbilityWithAttr(IgnoreTypeImmunityAbAttr)) {
i think hasAbilityWithAttr might be redundant with how applyAbAttrs works, can remove if desired but was suggested to use it

2024-05-06 23:44 UTC, Xavion3 requested changes

2024-05-06 23:44 UTC, Xavion3 commented on src/data/ability.ts
> +    if (this.defenderType === (args[1] as Type) && this.allowedMoveTypes.some(type => type === (args[0] as Type))) {
This could just be an includes right, doesn't have to be a some?

2024-05-06 23:44 UTC, Xavion3 commented on src/field/pokemon.ts
> +      if (source && source.hasAbilityWithAttr(IgnoreTypeImmunityAbAttr)) {
Yeah, the apply handles this so this is redundant.

2024-05-07 00:14 UTC, contra1337 commented on src/data/ability.ts
> +    if (this.defenderType === (args[1] as Type) && this.allowedMoveTypes.some(type => type === (args[0] as Type))) {
yep good point thanks

2024-05-07 01:12 UTC, Xavion3 approved these changes

2024-05-08 05:32 UTC, Madmadness65 approved these changes

2024-05-08 05:32 UTC, merged