Implement Heal Bell, Aromatherapy, Sparkly Swirl and added status effect options to overrides
pagefaultgames/pokerogue pull request #575
Opened 2024-05-07 00:32 UTC by innerthunder

This is a cleaner version of my last pull request...

A new attribute `HealPartyStatusAttr` implements the status healing effects of these moves:
- Aromatherapy
- Heal Bell
- Sparkly Swirl

These moves are also implemented/updated with the existing `HealStatusEffectAttr` attribute:
- Purify
- Refresh (should now wake up the user if used via Sleep Talk)

New overrides are also added to `overrides.ts`. `STATUS_OVERRIDE` initalizes player Pokemon with the specified status effect, and `OPP_STATUS_OVERRIDE` does the same for enemy Pokemon.

2024-05-07 00:46 UTC, contra1337 commented on .gitignore
> +package.json
these files are necessary for the project

2024-05-07 00:46 UTC, contra1337 commented on package.json
> +		"@koa/router": "^12.0.1",
why is this being added? doesn't seem relevant or imported anywhere either

2024-05-07 00:51 UTC, innerthunder commented on package.json
> +		"@koa/router": "^12.0.1",
Sorry for the confusion, I had an error when I first ran the dev build related to koa/router, and I had to manually install a later version of npm to work around it. It modified the json files and I figured those changes shouldn't be included

2024-05-08 07:48 UTC, Xavion3 requested changes
This should be two seperate PRs. Don't include both the engine changes and package changes in the same PR. Also don't include override values which actually affect things in a PR.

2024-05-12 08:28 UTC, bennybroseph commented
Already implemented here https://github.com/pagefaultgames/pokerogue/pull/238

2024-05-12 08:28 UTC, closed without merging