Implemented Dancer Ability
pagefaultgames/pokerogue pull request #590
Opened 2024-05-07 09:09 UTC by YounesM

Added basic implementation for "Dancer" ability according to : https://bulbapedia.bulbagarden.net/wiki/Dancer_(Ability).

2024-05-12 08:15 UTC, bennybroseph requested changes
Needs TSDoc documentation on all new classes and functions and code comments where applicable.

2024-05-13 01:14 UTC, bennybroseph approved these changes

2024-05-13 01:14 UTC, bennybroseph requested changes
When you say basic implementation, what does that imply?

2024-05-13 06:37 UTC, YounesM commented
> When you say basic implementation, what does that imply?

Well it's honeslty not that basic anymore. I tested all the dancing moves and it seems to work as intended in solo and double battles, there might be some weird cases that I didn't think of but think should cover most if not all use cases.

2024-05-19 14:19 UTC, bennybroseph requested changes
Could we get a video of this move working in game? 

Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

2024-05-19 16:16 UTC, YounesM commented
> Could we get a video of this move working in game?

Sure, in a solo battle:

https://github.com/pagefaultgames/pokerogue/assets/11600168/95aac2dc-8998-425c-b419-5ee7f8545dcd

```
-> Player uses self status dance move
-> Opponent copies it
-> Opponent uses damaging dance move
-> Player returns it
```

In double battles :

https://github.com/pagefaultgames/pokerogue/assets/11600168/d398268b-8570-4d1a-bf8f-0c4a6461730c

```
-> Oricorio [Opp. 1] uses Feather Dance on Cyndaquil 
-> Oricorio [Player] ability triggers and uses Feather Dance on the source of the dance (Oricorio Opp. 1)
-> Oricorio [Opp. 2] ability triggers and uses Feather Dance on the same target than Oricorio [Opp. 1] (Cyndaquil)

-> Oricorio [Opp. 2] uses Fiery Dance on Cyndaquil
-> Oricorio [Player] ability triggers and uses Fiery Dance on the source of the dance (Oricorio Opp. 2)
-> Oricorio [Opp. 1] ability triggers and uses Fiery Dance on the same target than Oricorio [Opp. 2] (Cyndaquil)

-> Oricorio [Player] uses Dragon Dance
-> Oricorio [Opp. 1] and [Opp. 2] ability triggers and copies the move on themselves

-> Cyndaquil uses Aqua Step on Oricorio [Opp. 1]
-> Oricorio [Player] ability triggers and uses Aqua Step on the same target than Cyndaquil (Oricorio Opp. 1)
-> Oricorio [Opp. 1] ability triggers and uses Aqua Step on the source of the dance (Cyndaquil)
-> Cyndaquil is KO
-> Oricorio [Opp. 2] ability triggers and uses Aqua Step on the source of the dance (Cyndaquil) but since Cyndaquil is KO the move goes on Oricorio [Player] instead
```

I tried to cover all the possible cases that could happen when a dance move is used and when multiples dancer are in the fight on the video.

2024-05-22 18:00 UTC, bennybroseph requested changes

2024-05-22 18:00 UTC, bennybroseph commented on src/phases.ts
> +
Should this occur based on the pokemon's speed?

2024-05-22 19:16 UTC, YounesM commented on src/phases.ts
> +
I don't think so (I cannot find something saying it should), I believe that it should just "react" to a dance move and trigger just after a dance move

2024-05-25 04:00 UTC, bennybroseph approved these changes

2024-05-25 04:00 UTC, merged