Implement Beat Up
pagefaultgames/pokerogue pull request #593
Opened 2024-05-07 10:13 UTC by happinyz

This PR implements the move Beat Up. It's a pretty unique move with mechanics not found anywhere so a lot of this code is tightly coupled together.

https://github.com/pagefaultgames/pokerogue/assets/59787978/fd0c4692-1b64-4488-ab5a-9ffc58a33e93

2024-05-10 19:29 UTC, happinyz commented
@bennybroseph @Madmadness65 Could I get a review on this? Thanks!

2024-05-12 08:15 UTC, bennybroseph requested changes
Needs TSDoc documentation on all new classes and functions and code comments where applicable.

2024-05-17 17:55 UTC, happinyz commented
@bennybroseph Could you take another look at this? thanks!

2024-05-18 02:49 UTC, bennybroseph requested changes

2024-05-18 02:49 UTC, bennybroseph commented on src/data/move.ts
> +    // Allies can contribute only if they do not have a non-volatile status condition.
this is referenced in two places, is this by mistake?

2024-05-18 02:49 UTC, bennybroseph commented on src/data/move.ts
> +        }, 0);
here as well

2024-05-19 04:24 UTC, happinyz commented on src/data/move.ts
> +    // Allies can contribute only if they do not have a non-volatile status condition.
No, we do this in line 1075 to determine how many times Beat Up can hit, then do it again here to determine which party member's turn it is to hit

2024-05-19 14:22 UTC, bennybroseph approved these changes

2024-05-19 14:22 UTC, merged