corrected u turn and flip turn crash
pagefaultgames/pokerogue pull request #596
Opened 2024-05-07 14:06 UTC by YounesM

corrects #273  and #584

2024-05-07 14:11 UTC, YounesM commented
Not sure if it's the entended behavior but Flip Turn / U-turn makes the **wild** pokemon using it flee the fight. If it's not the entended behavior there are some more changes that need to be added to these two move. Nonetheless, this should fix the crashes at least

2024-05-09 18:30 UTC, chacolah commented
Testing Done:
-Tested Ferrothorn with Iron Barbs being hit with both U-Turn and Flip Turn (issue #584)
-Tested pokemon with U-Turn swapping when being targeted with a suicide move (issue #273)

No error logs or crashes present.

2024-05-12 08:13 UTC, bennybroseph requested changes

2024-05-12 08:13 UTC, bennybroseph commented on src/field/damage-number-handler.ts
> +    if (!scene?.damageNumbersMode)
I'm worried that value being null is causing more issues down the line. Why would scene be null/undefined here?

2024-05-12 09:44 UTC, YounesM commented on src/field/damage-number-handler.ts
> +    if (!scene?.damageNumbersMode)
Not 100% sure about what I'm going to say since I'm travelling and don't have direct access to my PC but when I looked a it seemed like that since Flip Turn and U-Turn causes the Wild Pokemon to flee, the scene unloads before the damage is applied (the pokemon is remove from the UI)

As I said in my previous comment I'm not sure if that's the intended behavior of those moves. I believe that these moves do not make wild pokémon leave the battle in the main line games.

It's maybe preferable to change UTurn / Filp turn accordingly so but this seemed to be a quickfix that doesn't change much for the time being

2024-05-12 09:56 UTC, bennybroseph commented on src/field/damage-number-handler.ts
> +    if (!scene?.damageNumbersMode)
Yeah, that's a tough call. I think we should fix the root cause. This may cover it up and cause other problems to be hard to identify later.

2024-05-13 22:15 UTC, YounesM commented on src/field/damage-number-handler.ts
> +    if (!scene?.damageNumbersMode)
I did some more investigating and it seems like what's happening is :

- Flip Turn / U-Trun is used and `ForceSwitchOutAttr` triggers, damage is applied, pokemon flees (scene is destroyed here).
- Damage is taken by pokemon with Iron Barbs / Rough Skin and the ability triggers `PostDefendContactDamageAbAttr`
- `PostDefendContactDamageAbAttr` tries to apply damage to a pokemon that has already fled, but doesn't find the scene.

The only thing I can think of to fix this is to find a way to trigger the move in two steps :
Step 1 : Move deals damage
(Ability triggers and deals damage)
Step 2 : Move switches out the Pokémon (Maybe split the animation in 2 phases too?)

I don't know if it is possible right know looking at how the code is structured to have a move to pause and wait until the damage phase is done to decide what happens next. This seems to be a very specific requirement for these two moves.

On the other hand it's very weird to me that the game tries to display damage numbers without checking if a scene is present. Isn't it better to check if a scene is present before trying to display anything anyway?

2024-05-13 23:52 UTC, bennybroseph approved these changes

2024-05-13 23:52 UTC, merged