Override - Modifiers & Held items
pagefaultgames/pokerogue pull request #598
Opened 2024-05-07 15:01 UTC by Greenlamp2

![chrome_Uhuddx6dQd](https://github.com/pagefaultgames/pokerogue/assets/44787002/408ee57a-e18d-482c-8c39-e905216b6a15)

2024-05-07 15:06 UTC, molker commented on src/overrides.ts
> +export const STARTING_MODIFIER_OVERRIDE = []; // ['EXP_SHARE', 'GOLDEN_EXP_CHARM']
instead of separate const for modifier list and quantity list can you just make it an array of objects with a modifier value and quantity value

2024-05-09 01:43 UTC, bennybroseph requested changes
Some of these comments are short enough to go off to the side of the line of code. Let's clean those up

2024-05-09 02:17 UTC, bennybroseph approved these changes

2024-05-09 02:23 UTC, bennybroseph commented
Looks good to me. Only adds items when populated. Works on both enemy pokemon in a double battle. Applies on every floor. Very useful for dev

Some notes for a future pull request of v 1.1:
- Needs a way to autocomplete the names of items/modifiers. Simple suggestion is an enum of the strings in a file like overrides-enums.ts or whatever
  - A more elegant solution may a possible v 1.2
- Currently applies the same held items to both pokemon in a double battle. needs a second override for the other pokemon

2024-05-09 19:17 UTC, molker commented
Implementing as part of https://github.com/pagefaultgames/pokerogue/pull/603

2024-05-09 19:17 UTC, closed without merging