Added splash messages literals for all languages
pagefaultgames/pokerogue pull request #600
Opened 2024-05-07 16:02 UTC by Bruzzii

- Created `splash-messages.ts` for all languages
- Created `getbattleCountSplashMessage` and `getSplashMessages` for work correctly

2024-05-07 16:36 UTC, Flashfyre requested changes

2024-05-07 16:36 UTC, Flashfyre commented on src/ui/title-ui-handler.ts
> +      console.log(this.splashMessage)
Debug code left

2024-05-07 16:36 UTC, Flashfyre commented on src/ui/title-ui-handler.ts
> +        if (this.splashMessage === getbattleCountSplashMessage())
```suggestion
        if (this.splashMessage === getBattleCountSplashMessage())
```
Rename this for proper casing

2024-05-16 08:36 UTC, bennybroseph approved these changes

2024-05-16 08:37 UTC, merged