Fix sturdy
pagefaultgames/pokerogue pull request #604
Opened 2024-05-07 17:41 UTC by Tiduzz

Stops sturdy ability from popping up everytime the user that has it gets hit.

Not the fix in mind, but attacks like double hit popped sturdy on the first hit, and fainted on the second, as i saw some people commenting on discord it was a bug, i couldn't reproduce it with those changes, but might not be related.

2024-05-08 15:02 UTC, Tiduzz commented
I made a few videos demonstrating how it currently is, and how it is after applying the fix. In main, double hits DO activate sturdy and THEN faint the target at the second hit-- i'm assuming people are just getting endure-token'd and crying about it(?)

All tests, except OHKO, are from full hp to X hp

Main: Sturdy activating without target going down to 1hp

https://github.com/pagefaultgames/pokerogue/assets/42784723/7284d39e-3798-4cc6-b0a4-cb5ffc080b5f

Fix: Sturdy NOT activating without target going down to 1hp

https://github.com/pagefaultgames/pokerogue/assets/42784723/0ac45c73-2509-4e6d-9872-d049cc89715a

--------

Main and Fix respectivelly: Both activating at 1hp


https://github.com/pagefaultgames/pokerogue/assets/42784723/eeec1692-93ee-4447-9a43-692f240c4f12


https://github.com/pagefaultgames/pokerogue/assets/42784723/8e895fdb-9bff-4a1e-9e88-df2bdd29181b

--------

Main and Fix: Both activating at 1hp and THEN fainting on the next hit

https://github.com/pagefaultgames/pokerogue/assets/42784723/b7b7b57b-e543-423a-a705-a9d1ccdb1676


https://github.com/pagefaultgames/pokerogue/assets/42784723/e0115a1b-e45c-4d70-a068-534670d82061

--------

Main and Fix respectivelly: Both blocking OHKO


https://github.com/pagefaultgames/pokerogue/assets/42784723/cf2b8a44-b956-461d-b6bc-3d03c33dfe13


https://github.com/pagefaultgames/pokerogue/assets/42784723/55eaf15e-62c3-43b3-9e8f-823e022a7c11

--------

Main and Fix respectivelly: Both bypassing sturdy with wonderguard


https://github.com/pagefaultgames/pokerogue/assets/42784723/3d6ea9c1-7e4a-4a16-a708-dad0786af63e

https://github.com/pagefaultgames/pokerogue/assets/42784723/96b7e77c-b59c-4d72-bcd8-cfb858fd6363

2024-05-09 20:45 UTC, bennybroseph requested changes

2024-05-09 20:45 UTC, bennybroseph commented on src/data/ability.ts
> +    }
technically the else statement is irrelevant. you can just return false and it will only be called if the condition is false.

2024-05-09 21:22 UTC, Tiduzz commented on src/data/ability.ts
> +    }
Ah, gotcha, i'll remove the else then

2024-05-12 08:09 UTC, bennybroseph requested changes

2024-05-12 16:44 UTC, bennybroseph approved these changes

2024-05-12 19:53 UTC, merged