More german translations
pagefaultgames/pokerogue pull request #612
Opened 2024-05-07 20:54 UTC by phynor

Added more German translation, for all abilites, moves, and more.

2024-05-08 16:00 UTC, CodeTappert commented on src/locales/de/starter-select-ui-handler.ts
>      "toggleIVs": 'Toggle IVs',
"IV umschalten"

(Well in german it is 'IS' (Individuelle Stärken) instead of IV but nobody uses it)

2024-05-08 16:04 UTC, CodeTappert commented on src/locales/de/battle.ts
> +  "ivScannerUseQuestion": "IV-Scanner auf {{pokemonName}} benutzen?"
Here again the correct translation would be "IS"

2024-05-08 17:29 UTC, MonsieurDMA commented
We are also working on the button translation and face an issue that you probably have:
![image](https://github.com/pagefaultgames/pokerogue/assets/92155252/edb769c8-57df-4cf3-8e1b-2b82216c3d37)

2024-05-08 18:35 UTC, phynor commented on src/locales/de/starter-select-ui-handler.ts
>      "toggleIVs": 'Toggle IVs',
I didn't translate `"toggleIVs"`, it's still the English text.

2024-05-08 18:37 UTC, phynor commented on src/locales/de/battle.ts
> +  "ivScannerUseQuestion": "IV-Scanner auf {{pokemonName}} benutzen?"
I didn't want to only partially change IV to IS.
Should only be changed globally for all German text.

2024-05-08 18:52 UTC, CodeTappert commented on src/locales/de/starter-select-ui-handler.ts
>      "toggleIVs": 'Toggle IVs',
Yes i know. 
I just provided a possible translation here

2024-05-11 20:39 UTC, CodeTappert requested changes
Other then the one thing i mentioned just now it looks good. 

Please change the one thing and then (language wise) it can be merged.

2024-05-11 20:39 UTC, CodeTappert commented on src/locales/de/tutorial.ts
> +    $Falls das Spiel langsam läuft, prüfe ob die 'Hardware Beschleuningung' in deinen Browsereinstellungen aktiviert sind.`,
Should be 
```
in deinen Browsereinstellungen aktiviert ist.`,
```

instead.

2024-05-12 16:25 UTC, phynor commented on src/locales/de/tutorial.ts
> +    $Falls das Spiel langsam läuft, prüfe ob die 'Hardware Beschleuningung' in deinen Browsereinstellungen aktiviert sind.`,
Merged it with current version.
Used already existing translation for `tutorial.ts`.

2024-05-12 17:45 UTC, CodeTappert requested changes

2024-05-12 17:45 UTC, CodeTappert commented on src/locales/de/ability.ts
> +    description: "Kann bei Kampfantritt Auskunft über das vom Gegner getragene Item geben.",
Since apparently in this game the ability "Frisk" detects abilitys this should be changed to

`Kann bei Kampfantritt Auskunft über die Fähigkeit vom Gegner geben.`

2024-05-12 17:53 UTC, Madmadness65 approved these changes

2024-05-12 17:53 UTC, merged

2024-05-12 17:53 UTC, phynor commented on src/locales/de/ability.ts
> +    description: "Kann bei Kampfantritt Auskunft über das vom Gegner getragene Item geben.",
changed description of frisk.