Implement Ball Fetch
pagefaultgames/pokerogue pull request #619
Opened 2024-05-07 22:26 UTC by Fabpharos

Could have some niche use. This implementation tracks the most recently thrown type of Pokeball that failed to catch a Pokemon, letting a Pokemon with Ball Fetch fetch it. Triggers once per battle, at the end of the turn. Tested with all types of Pokeballs, besides Master Balls obviously, and tested a mon switching in when a ball was thrown on a previous turn.

Pokemon can't hold Pokeballs so they just put it directly into your inventory.

https://m.bulbapedia.bulbagarden.net/wiki/Ball_Fetch_(Ability)

2024-05-08 05:42 UTC, TempsRay approved these changes
lgtm

2024-05-08 05:42 UTC, TempsRay commented on src/data/ability.ts
> +    if(lastUsed != null && pokemon.isPlayer) {
I believe you can check if lastUsed is null with just
```suggestion
    if(!lastUsed && pokemon.isPlayer) {
```

2024-05-12 07:56 UTC, bennybroseph commented on src/data/ability.ts
> +    if(lastUsed != null && pokemon.isPlayer) {
Nah, I think that's backwards. You would remove the exclamation mark.

2024-05-12 07:57 UTC, bennybroseph requested changes
Needs TSDoc documentation on all new classes and functions and code comments where applicable.

2024-05-14 20:16 UTC, TempsRay commented on src/data/ability.ts
> +    if(lastUsed != null && pokemon.isPlayer) {
I think you're right. Can't believe I made such a typo 🤦

2024-05-14 20:22 UTC, TempsRay reviewed
Hope the doc I added helps

2024-05-14 20:22 UTC, TempsRay commented on src/data/ability.ts
> +export class FetchBallAbAttr extends PostTurnAbAttr {
Not sure the exact doc requirements, but here's something

```ts
/**
 * Grabs the last failed Pokeball used
 * @extends PostTurnAbAttr
 * @see {@link applyPostTurn}
 */
export class FetchBallAbAttr extends PostTurnAbAttr {
...
  /**
   * Adds the last used Pokeball back into the player's inventory
   * @param pokemon the Pokemon with this ability
   * @param passive n/a
   * @param args n/a
   * @returns true if player has used a pokeball and this pokemon is owned by the player
   */
  applyPostTurn(pokemon: Pokemon, passive: boolean, args: any[]): boolean
```

2024-05-19 16:13 UTC, closed without merging