Attempt 1 at exponential backoff in server-down behavior.
pagefaultgames/pokerogue pull request #628
Opened 2024-05-08 09:26 UTC by exitmouse

Making this PR to illustrate a point--I'm not super comfortable as a typescript dev and I also can't figure out how to test this behavior locally. Happy to make changes.

2024-05-08 09:38 UTC, MonsieurDMA approved these changes

2024-05-08 09:38 UTC, MonsieurDMA commented on src/ui/unavailable-modal-ui-handler.ts
> +	    this.reconnectInterval *= 2;
Don't make it infinitely exponential as it's a bad UX.
Add a condition
```
if this.reconnectInterval >= 30000:
    this.reconnectInterval = 30000
```

2024-05-08 09:38 UTC, MonsieurDMA commented on src/ui/unavailable-modal-ui-handler.ts
> +	    this.reconnectTimer = setInterval(this.tryReconnect, reconnectInterval);
For compliance, last parameter should be :  **this.reconnectInterval**

2024-05-08 09:43 UTC, MonsieurDMA requested changes
After these change, it should be good to be in prod and hopefully mitigate a little the unintended ddos

2024-05-08 09:46 UTC, exitmouse commented on src/ui/unavailable-modal-ui-handler.ts
> +	    this.reconnectTimer = setInterval(this.tryReconnect, reconnectInterval);
Oh, nice catch.

2024-05-08 09:59 UTC, MonsieurDMA approved these changes

2024-05-08 10:58 UTC, MonsieurDMA requested changes

2024-05-08 10:58 UTC, MonsieurDMA commented on src/ui/unavailable-modal-ui-handler.ts
> +	    this.reconnectTimer = setInterval(this.tryReconnect, this.reconnectInterval);
Replace setInterval by [setTimeout](https://developer.mozilla.org/fr/docs/Web/API/setTimeout)

> It may be helpful to be aware that setInterval() and setTimeout() share the same pool of IDs, and that clearInterval() and clearTimeout() can be used interchangeably

2024-05-08 10:58 UTC, MonsieurDMA commented on src/ui/unavailable-modal-ui-handler.ts
Make sure that you follow the same indent pattern as the other part of the file

2024-05-08 11:01 UTC, MonsieurDMA commented on src/ui/unavailable-modal-ui-handler.ts
> +	    if (this.reconnectInterval >= 60000) {
Should be set at this.reconnectInterval > 60000 instead

2024-05-19 16:19 UTC, bennybroseph commented
Closing this due to inactivity. Feel free to make a new request if interest is reignited

2024-05-23 19:23 UTC, Dakurei commented
I'd recommend setting the maximum at 5 minutes
and add some randomness to avoid the pendulum effect where all requests end up being synchronized and make a BIG ddos at regular interval

2024-05-23 19:44 UTC, Dakurei reviewed
Some suggestions for modifications 👍

If I manage to set up the server and connect it to my local PokéRogue, I could do some tests to tell if this PR in its current state is possible to merge into main, but I haven't done that setup yet.

2024-05-23 19:44 UTC, Dakurei commented on src/ui/unavailable-modal-ui-handler.ts
> +        if (this.reconnectInterval > 60000) {
```suggestion
        if (this.reconnectInterval > 300000) {
```

2024-05-23 19:45 UTC, Dakurei commented on src/ui/unavailable-modal-ui-handler.ts
> +          this.reconnectInterval = 60000; // 1 minute maximum delay.
```suggestion
          this.reconnectInterval = 300000; // 5 minute maximum delay.
```

2024-05-23 19:45 UTC, Dakurei commented on src/ui/unavailable-modal-ui-handler.ts
> +        this.reconnectTimer = setTimeout(this.tryReconnect, this.reconnectInterval);
```suggestion
        this.reconnectTimer = setTimeout(this.tryReconnect, this.reconnectInterval + (Math.random() * 15) * 1000); // Adds a random factor between 0 and 15 seconds to avoid pendulum effect during long total breakdown
```

2024-05-23 20:29 UTC, Dakurei commented
The last commit removes the randomness and resets the delay to 1 minute instead of 5, that's not good

2024-05-23 20:41 UTC, Dakurei commented
I've tested this with a local server, forcing the /info request to return a 500 error, and the delay is well included in the exponential backoff set up, so it looks all right to me apart from the shortened maximum delay.

This should save the server from getting a ton of useless requests during outages, making the situation worse in the event of a provider's ddos block.

> Server view requests
![image](https://github.com/pagefaultgames/pokerogue/assets/8146474/bf26a6f7-b391-49a9-a5b3-7d614d005c6d)
![image](https://github.com/pagefaultgames/pokerogue/assets/8146474/c4a770cd-b764-4b48-862b-809e03276c30)

> Client view requests
![image](https://github.com/pagefaultgames/pokerogue/assets/8146474/89304d92-1736-4abc-8b86-ef28f2d8ec87)

2024-05-23 21:33 UTC, bennybroseph commented
Sorry about any confusion caused with how I had to go about this. Had to make a bunch of changes and test on someone else's repository and it just ended up being faster to create my own branch with the changes rather than keep editing this one. Closing this out for real this time.

2024-05-23 21:33 UTC, closed without merging