Implements bad dreams
pagefaultgames/pokerogue pull request #633
Opened 2024-05-08 12:39 UTC by Sbug98

Hi,
This is my attempt at implementing Bad Dreams.
Hopefully the video showcases some worst case scenarios of the ability and it's enough proof of testing. I'm a bit worried of the interaction with healer, I wasn't able to test it as it is not yet implemented, but if the priority is consistent the order of activation should handle the rest. 
https://github.com/pagefaultgames/pokerogue/assets/68464158/2683bb74-1998-4cd1-a3a4-0ec3c2d25a91

2024-05-08 14:15 UTC, PinsonJonas requested changes

2024-05-08 14:15 UTC, PinsonJonas commented on src/data/ability.ts
> +        pokemon.scene.queueMessage(getPokemonMessage(oppo, ' is tormeted!'));
```suggestion
        pokemon.scene.queueMessage(getPokemonMessage(oppo, ' is tormented!'));
```

2024-05-08 15:37 UTC, PinsonJonas approved these changes

2024-05-12 03:12 UTC, TempsRay commented on src/data/ability.ts
> +      if(oppo.status !== undefined && oppo.status.effect == StatusEffect.SLEEP) {
nit: usually I see `opp` instead of `oppo` but that's minor. Also most comparisons use 3 equals signs rather than just 2

2024-05-12 03:15 UTC, TempsRay commented on src/data/ability.ts
> +        oppo.damageAndUpdate(Math.ceil(oppo.getMaxHp() * (1 / 8)), HitResult.OTHER);
Smogon says it rounds down so it should be Math.floor rather than Math.ceil. Also, for the edge case of wonder guard this should probably do a minimum of one damage.
`oppo.damageAndUpdate(Math.Max(1, Math.floor(oppo.getMaxHp() / 8)), HitResult.OTHER);`

2024-05-12 03:15 UTC, TempsRay requested changes
Some minor changes but otherwise looks fine

2024-05-12 07:49 UTC, bennybroseph requested changes

2024-05-13 16:04 UTC, TempsRay commented on src/data/ability.ts
> +    //returns true only if one of the opponents were sleeping
I don't think this is what Benny meant by comments. Here's what he means by tsdoc
```ts
/**
 * Attribute used for abilities (Nightmare) that damages the opponents for being asleep
 */
export class PostTurnHurtIfSleepingAbAttr extends PostTurnAbAttr {

/**
 * Deals damage to all sleeping opponents equal to 1/8 of their max hp (min 1)
 * @param {Pokemon} pokemon Pokemon that has this ability 
 * @param {boolean} passive N/A
 * @param {any[]} args N/A
 * @returns {boolean} true if any opponents are sleeping
 */
  applyPostTurn(pokemon: Pokemon, passive: boolean, args: any[]): boolean | Promise<boolean> {
```

2024-05-13 16:05 UTC, TempsRay approved these changes
Code looks good to me but your tsdoc doesn't seem quite right. I've commented what the appropriate TSdoc looks like. Your // comments aren't needed since your code is easy enough to understand

2024-05-13 16:21 UTC, Sbug98 commented on src/data/ability.ts
> +    //returns true only if one of the opponents were sleeping
Ah I see, that makes sense. I'll update the PR with your docs. Thanks

2024-05-15 15:05 UTC, TempsRay commented on src/data/ability.ts
> +        pokemon.scene.queueMessage(getPokemonMessage(opp, ' is tormented!'));
Here's where the localization files are https://github.com/pagefaultgames/pokerogue/blob/main/src/locales/en/ability-trigger.ts

2024-05-17 15:47 UTC, Sbug98 commented on src/data/ability.ts
> +        pokemon.scene.queueMessage(getPokemonMessage(opp, ' is tormented!'));
Using the getTriggerMessage method I'm not sure how to trigger the message for each opponent since I can only give one value as the return. Could you suggest an approach to this problem? I can't seem to find any reference using localization for more than one Pokémon.

2024-05-17 16:03 UTC, Sbug98 commented on src/data/ability.ts
> +        pokemon.scene.queueMessage(getPokemonMessage(opp, ' is tormented!'));
I added translations but they may be inaccurate from the games.

2024-05-20 19:36 UTC, bennybroseph commented
has conflicts currently. need to resync and resolve

2024-05-21 07:25 UTC, bennybroseph approved these changes

2024-05-21 07:26 UTC, merged

2024-05-21 07:26 UTC, Sbug98 reviewed
I've resolved the conflicts and resynced my PR branch