Fix - Gamepad support setting "lost focus" behaviour
pagefaultgames/pokerogue pull request #658
Opened 2024-05-08 21:10 UTC by Greenlamp2

I noticed when you disable the gamepad support, it keeps the key "RIGHT" pressed.

2024-05-09 01:46 UTC, bennybroseph requested changes
Let's get some comments for this change

2024-05-09 20:18 UTC, bennybroseph requested changes

2024-05-09 20:18 UTC, bennybroseph commented on src/inputs-controller.ts
> +                if (!this.gamepadSupport && this.interactions[b].source === 'gamepad') {
Block comment here

2024-05-09 20:18 UTC, bennybroseph commented on src/inputs-controller.ts
> +            }
let's get these functions documented using TSDoc

2024-05-09 20:18 UTC, bennybroseph commented on src/inputs-controller.ts
>      update(): void {
let's get these functions documented using TSDoc

2024-05-09 20:18 UTC, bennybroseph commented on src/inputs-controller.ts
>      gamepadButtonUp(pad: Phaser.Input.Gamepad.Gamepad, button: Phaser.Input.Gamepad.Button, value: number): void {
let's get these functions documented using TSDoc

2024-05-10 13:26 UTC, Flashfyre approved these changes

2024-05-10 13:26 UTC, merged