Implement Snipe Shot, and Propeller Tail/Stalwart
pagefaultgames/pokerogue pull request #661
Opened 2024-05-08 23:50 UTC by f-raZ0R

This pull request adds the functionality of ignoring redirects to the move Snipe Shot, and the abilities Propeller Tail and Stalwart. Currently, the only things that can redirect a move, are the abilities Storm Drain and Lightning Rod. If more ways to do so get implemented in the future, these moves and abilities may need to be tweaked further.

2024-05-09 18:21 UTC, bennybroseph requested changes

2024-05-09 18:23 UTC, f-raZ0R commented on src/phases.ts
> +import { CheckTrappedAbAttr, IgnoreOpponentStatChangesAbAttr, PostAttackAbAttr, PostBattleAbAttr, PostDefendAbAttr, PostSummonAbAttr, PostTurnAbAttr, PostWeatherLapseAbAttr, PreSwitchOutAbAttr, PreWe
BlockRedirectAbAttr was added to the attributes imported

2024-05-09 18:39 UTC, f-raZ0R commented on src/phases.ts
> +          }
Does this look good?

2024-05-09 20:22 UTC, bennybroseph requested changes

2024-05-09 20:22 UTC, bennybroseph commented on src/data/move.ts
> +
let's get some TSDoc documentation to explain why someone would what to use this attribute in the future

2024-05-09 22:29 UTC, bennybroseph approved these changes

2024-05-09 22:38 UTC, bennybroseph requested changes
When Propeller Tail/Stalwart activates, I'm not seeing the pop-up even though it is working. Are you seeing different?

2024-05-09 22:48 UTC, f-raZ0R commented
This is intentional, as it does not make a pop-up in the official games either.

2024-05-10 14:57 UTC, bennybroseph requested changes

2024-05-10 14:57 UTC, bennybroseph commented on src/phases.ts
> +
looks like an extra return got added here

2024-05-10 15:17 UTC, bennybroseph approved these changes

2024-05-10 15:17 UTC, bennybroseph commented
This is good to go in my opinion.

2024-05-10 15:25 UTC, bennybroseph commented
This is good to go in my opinion.

2024-05-10 15:40 UTC, Madmadness65 approved these changes

2024-05-10 15:40 UTC, merged