Sacrifical Moves (that dont require a target like explosion or self d…
pagefaultgames/pokerogue pull request #691
Opened 2024-05-09 21:24 UTC by CodeTappert

…estruct) now also work if the target is flying, diving etc.

There is also a new catagorie of moves. "SacrificalMovesOnHit" for all moves that need to hit for them to be sacrifical like MEMENTO

Fixes https://discord.com/channels/1125469663833370665/1238179985571975300/1238179985571975300

2024-05-11 14:53 UTC, CodeTappert commented
Solved the conflict with main

2024-05-12 07:41 UTC, bennybroseph requested changes
Needs TSDoc documentation on all new classes and functions and code comments where applicable. Also needs some formatting fixes as there's a lot of open space between lines.

2024-05-12 08:01 UTC, CodeTappert commented
So i added the changes you requested to the best of my ability. (I dont know how a TSDoc for a class should look like. Please provide an example).

2024-05-14 19:48 UTC, CodeTappert commented
> So i added the changes you requested to the best of my ability. (I dont know how a TSDoc for a class should look like. Please provide an example).

@bennybroseph

2024-05-14 20:25 UTC, TempsRay commented on src/data/move.ts
> + * */
nit: the bottom of the comment should be `**/` without the space in between

2024-05-14 20:26 UTC, TempsRay commented on src/data/move.ts
> +     */
This seems like it's 1 tabbed in further than it should be. I'd also suggest changing the main `Applies the sacrificial effect to the user` to be more concise like `Deals damage to the user equal to their current hp`. You're also missing the `@return` in the doc and the comment should be ended with `**/`

2024-05-14 20:28 UTC, TempsRay commented on src/data/move.ts
> +   *
This part should describe what's happening (the AI is calculating how good the move is). Bosses will always return -20 while otherwise it scales based on the user's hp ratio. The doc here is also a bit mis-tabbed I think

2024-05-14 20:29 UTC, TempsRay commented on src/data/move.ts
> +    // If the move hits a target, the user will self KO
Doesn't this line mean the opposite? If the move fails then the user does not faint and the function returns false

2024-05-14 20:49 UTC, CodeTappert commented on src/data/move.ts
> +    // If the move hits a target, the user will self KO
You are correct.

2024-05-14 20:50 UTC, CodeTappert commented on src/data/move.ts
> +   *
Fixed. But tabbing was right imo (same as at other places)

2024-05-14 20:51 UTC, CodeTappert commented on src/data/move.ts
> +     */
Yes your idea for a description is better indeed!

2024-05-14 20:51 UTC, CodeTappert commented on src/data/move.ts
> + * */
Fixed

2024-05-15 02:20 UTC, bennybroseph commented
This makes weird behavior happen. Because you're targeting yourself, you take damage in parts. First from the move and then to fully faint. I'm about to mess around with this.

https://github.com/pagefaultgames/pokerogue/assets/13838608/048c622a-f82d-4cfd-8cf8-9c360e8556ca

2024-05-15 06:27 UTC, bennybroseph commented
Working to make this even better, but as I thought you definitely don't need to force target yourself. Self Inflicted damage is now applied after all other move effects and does not rely on a target in order to do so.


https://github.com/pagefaultgames/pokerogue/assets/13838608/9979a5fa-e610-434d-a0d2-927353bbd5a1

2024-05-15 09:03 UTC, bennybroseph approved these changes

2024-05-15 09:05 UTC, bennybroseph commented
I tried a few things, but any other changes were just out of scope for this PR. Changes are needed to how the system handles Fly, Dig, Dive, etc. before this works is implemented correctly. Everything works like it should though.

2024-05-15 09:10 UTC, merged