Fix tags not being applied on session load
pagefaultgames/pokerogue pull request #694
Opened 2024-05-09 22:24 UTC by happinyz

This PR addresses a reported issue where hazards were being removed when loading a save session: https://github.com/pagefaultgames/pokerogue/issues/684#issuecomment-2103263308

https://github.com/pagefaultgames/pokerogue/assets/59787978/bf369936-2024-4e24-a869-2b2fbba7095d

2024-05-09 22:38 UTC, Xavion3 commented
I doubt this is going to work, so I'll just ask about some of the cases where I expect it not to work.

Has this been tested with multiple layers of spikes to ensure it maintains the correct amount of layers? Toxic spikes has layers too that could be tested.
Has this been tested with wish to ensure it still heals and heals the correct amount?

You can look at what I did with battlerTag save/loading for a reference if you want, but it wound up needing significantly more than this.

2024-05-09 23:28 UTC, happinyz commented
> I doubt this is going to work, so I'll just ask about some of the cases where I expect it not to work.
> 
> Has this been tested with multiple layers of spikes to ensure it maintains the correct amount of layers? Toxic spikes has layers too that could be tested. Has this been tested with wish to ensure it still heals and heals the correct amount?
> 
> You can look at what I did with battlerTag save/loading for a reference if you want, but it wound up needing significantly more than this.

You were right, those cases failed in my initial implementation. I've updated the PR to account for these cases, and posted demo videos. Thanks for mentioning your work with the battler tags, that really helped!

2024-05-10 19:29 UTC, happinyz commented
@Xavion3 Could you give this another look? Thanks!

2024-05-21 05:41 UTC, Xavion3 requested changes
Is this tested against tags with custom private data like wish?

2024-05-21 05:41 UTC, Xavion3 commented on src/data/arena-tag.ts
> -export function getArenaTag(tagType: ArenaTagType, turnCount: integer, sourceMove: Moves, sourceId: integer, targetIndex?: BattlerIndex, side: ArenaTagSide = ArenaTagSide.BOTH): ArenaTag {
Why are you changing the order of arguments?

2024-05-21 05:41 UTC, Xavion3 commented on src/data/arena-tag.ts
> +}
Keep ending newline consistent preferably, just increases compatibility with other PRs.

2024-05-21 06:52 UTC, happinyz commented on src/data/arena-tag.ts
> +}
Fixed

2024-05-21 06:52 UTC, happinyz commented on src/data/arena-tag.ts
> -export function getArenaTag(tagType: ArenaTagType, turnCount: integer, sourceMove: Moves, sourceId: integer, targetIndex?: BattlerIndex, side: ArenaTagSide = ArenaTagSide.BOTH): ArenaTag {
optional params should be at the end of the parameter list

2024-05-21 06:52 UTC, happinyz commented
> Is this tested against tags with custom private data like wish?

Yes, the main description of the PR has a demo video for Wish. Are there other specific tags you'd like me to test?

2024-07-11 17:52 UTC, Tempo-anon commented
Closing due to inactivity and merge conflicts. If this is still required, feel free to open a new PR

2024-07-11 17:52 UTC, closed without merging