Implement Tera Shell
pagefaultgames/pokerogue pull request #695
Opened 2024-05-09 22:35 UTC by jaimefd

Implemented the ability Tera Shell.

Added FullHpTypeMultiplierAbAttr that changes the type multiplier when defending if the user was full HP at the start of the turn.

Had to create a boolean called "startedFullHp" since Tera Shell isn't like Multiscale. If you get git by a multi-hit move, all hits are reduced if you were full HP at the start of the attack.

There may be better ways to implement this, so let me know if I can improve it in any way.

2024-05-24 18:28 UTC, Xavion3 requested changes

2024-05-24 18:30 UTC, Xavion3 commented
Also there's some merge conflicts to fix.

2024-06-01 00:09 UTC, jaimefd commented on src/phases.ts
> +        targets.map((t) => { t.turnData.startedFullHp = t.getHpRatio() === 1});
Solved, it now checks actual HP

2024-06-01 00:10 UTC, jaimefd commented on src/phases.ts
> +        this.getTargets().map((t) => { t.turnData.startedFullHp = t.getHpRatio() === 1});
Solved, since this code is now removed

2024-06-01 00:48 UTC, jaimefd commented
Changes from the previous version of the PR:
- Updated the description at the top of the PR with the new template
- Cleaned up the logic a bit, with inspiration from https://github.com/pagefaultgames/pokerogue/pull/728, renaming the attribute to `ReceivedMoveEffectivenessAbAttr` and making it extend `PreDefendAbAttr` for consistency with the existing `ReceivedMoveDamageMultiplierAbAttr`
- Added some documentation for the attribute
- Reworked the logic that checks if the target was full HP at the start of the hits. It no longer updates it both at the start and end of the hits, it only does it at the start, as the other one was unnecessary. It now also keeps track of the HP before the attacks, instead of being a boolean, to potentially make it useful in the future.

2024-07-29 17:32 UTC, flx-sta commented
No action within more than a month. 
Considered stale

2024-07-29 17:32 UTC, closed without merging