Implemented Power Split and Guard Split
pagefaultgames/pokerogue pull request #699
Opened 2024-05-10 01:21 UTC by XGSleepWalker

* Implemented Power Split
* Implemented Guard Split

2024-05-12 06:01 UTC, bennybroseph requested changes

2024-05-12 06:01 UTC, bennybroseph commented on src/field/pokemon.ts
> +    return this.summonData.stats[stat];
We use Egyptian style braces in this project, let's get these updated

2024-05-12 06:01 UTC, bennybroseph commented on src/field/pokemon.ts
> +  }
We use Egyptian style braces in this project, let's get these updated

2024-05-12 06:24 UTC, XGSleepWalker commented on src/data/move.ts
> +
Documentation added

2024-05-12 06:24 UTC, XGSleepWalker commented on src/field/pokemon.ts
> +    return this.summonData.stats[stat];
Braces fixed.

2024-05-12 06:24 UTC, XGSleepWalker commented on src/field/pokemon.ts
> +  }
Braces fixed.

2024-05-13 08:10 UTC, bennybroseph approved these changes

2024-05-13 08:11 UTC, bennybroseph requested changes

2024-05-13 08:11 UTC, bennybroseph commented on src/data/terrain.ts
Is this change needed?

2024-05-13 08:36 UTC, bennybroseph requested changes

2024-05-13 08:36 UTC, bennybroseph commented on src/data/move.ts
> +      const defenseValue = Math.floor((target.getStat(Stat.DEF) + user.getStat(Stat.DEF)) / 2);
Is there a source that states these values are rounded down? If not we should be using Math.round here.

2024-05-13 10:52 UTC, XGSleepWalker commented on src/data/move.ts
> +      const defenseValue = Math.floor((target.getStat(Stat.DEF) + user.getStat(Stat.DEF)) / 2);
From Smogon: https://www.smogon.com/dex/sv/moves/guard-split/
https://www.smogon.com/dex/sv/moves/power-split/

'The user and the target have their Attack/Defense and Special Attack/Defense stats set to be equal to the average of the user and the target's Attack and Special Attack stats, respectively, rounded down. Stat stage changes are unaffected.'

2024-05-13 11:00 UTC, XGSleepWalker commented on src/data/terrain.ts
Leftover from a bad push, removed.

2024-05-13 11:01 UTC, bennybroseph requested changes

2024-05-13 11:01 UTC, bennybroseph commented on src/field/pokemon.ts
> +  }
Didn't realize these were brand new functions. need these documented

2024-05-13 11:01 UTC, bennybroseph commented on src/field/pokemon.ts
> +    return this.summonData.stats[stat];
Didn't realize these were functions. need these documented

2024-05-13 13:42 UTC, XGSleepWalker commented on src/field/pokemon.ts
> +    return this.summonData.stats[stat];
Documentation added.

2024-05-13 13:43 UTC, XGSleepWalker commented on src/field/pokemon.ts
> +  }
Documentation added.

2024-05-15 08:58 UTC, bennybroseph approved these changes

2024-05-15 12:41 UTC, merged