Rockruff dusk form not evolving
pagefaultgames/pokerogue pull request #700
Opened 2024-05-10 01:44 UTC by j-diefenbach

This PR addresses an issue raised where rockruff with own tempo is unable to evolve into dusk form. During dusk it does not evolve, during day or night it evolves instead into the midday/midnight forms.
Replaced inappropriate 'getSpeciesFormIndex' (which is not able to check rockruff's species since it doesn't have access to the pokemon's information, only scene info. It defaults to zero so rockruffs form index will always be zero) with 'hasAbility' for own tempo. In order to prevent an own tempo rockruff from evolving otherwise I've added a check for own tempo. Plus relevant import from enum abilities.
Screenshots of bug (#681)
![image](https://github.com/pagefaultgames/pokerogue/assets/105332964/e1bb8efc-99e9-4591-8867-3391b142d017)
note that getSpeciesFormIndex might be worth updating in future for more complex forms however this approach seems to be suitable and avoids messing with getSpeciesFormIndex unnecessarily

2024-05-10 02:01 UTC, Xavion3 requested changes

2024-05-10 02:01 UTC, Xavion3 commented on src/data/pokemon-evolutions.ts
> +    new SpeciesFormEvolution(Species.LYCANROC, '', 'dusk', 25, null, new SpeciesEvolutionCondition(p =>  p.hasAbility(Abilities.OWN_TEMPO)), null),
You should be using the second and third arguments here as false and true respectively. This will fail if the ability is changed/suppressed/etc. right now.

2024-05-10 02:02 UTC, Xavion3 commented on src/data/pokemon-evolutions.ts
> +    new SpeciesFormEvolution(Species.LYCANROC, '', 'dusk', 25, null, new SpeciesEvolutionCondition(p =>  p.hasAbility(Abilities.OWN_TEMPO)), null),
Actually more complex, you'd want to somehow check the actual ability. Fusions complicated this as fusing a base rockruff with something with own tempo shouldn't let you evolve, and fusing an own tempo rockruff with something  else causing it to lose own tempo won't work either.

2024-05-12 02:38 UTC, j-diefenbach commented
Since the getSpeciesFormIndex doesn't work for rockruff, formIndex will accurately track whether it was originally an owntempo rockruff or not (otherwise we would be creating additional functions or modifying getFormIndex which was intended for wild pokemon gen). If it fuses to any other pokemon it still keeps its formIndex the same since it takes the first pokemon's form. So far rockruff still evolves correctly, an OT rockruff fused w any pokemon still evolves into dusk form, a regular rockruff fused with an OT rockruff (or any other pokemon that overwrites the ability as own tempo) will turn into day/night forms still.

Regular rockruff fused with own tempo rockruff evolves into day form correctly:
![image](https://github.com/pagefaultgames/pokerogue/assets/105332964/24291a04-29db-4b32-89b4-98382758e39b)
OT rockruff fused with another pokemon (replacing OT) still evolves into dusk form:
![image](https://github.com/pagefaultgames/pokerogue/assets/105332964/7e80b12c-b5ec-48c7-b766-faf64e14b950)

2024-05-12 03:03 UTC, TempsRay commented on src/overrides.ts
> +export const STARTING_WAVE_OVERRIDE: integer = 15;
override changes should not be committed

2024-05-12 03:05 UTC, TempsRay requested changes

2024-05-12 03:05 UTC, TempsRay commented on src/data/pokemon-evolutions.ts
> +    new SpeciesFormEvolution(Species.LYCANROC, '', 'dusk', 25, null, new SpeciesEvolutionCondition(p =>  p.formIndex === 1), null),
Doesn't dusk form require a specific time of day as well?

2024-05-12 05:53 UTC, Xavion3 approved these changes

2024-05-13 03:00 UTC, merged