Passive display add
pagefaultgames/pokerogue pull request #703
Opened 2024-05-10 04:53 UTC by bennybroseph

Adds the ability to view passives on the Summary screen. Just like in the starter select, you can only see the passive once it is unlocked.

There is a small pixel button prompt which helps indicate you are able to press the button to view the passive. This buttons shows an A when gamepad support is enabled and a Z otherwise.

https://github.com/pagefaultgames/pokerogue/assets/13838608/41b6f945-5907-4403-9dff-8dcc3fa4578d

2024-05-10 05:11 UTC, Flashfyre requested changes
This is great. Unfortunately though, I do need to ask you to support the legacy theme.

2024-05-10 05:33 UTC, bennybroseph commented
Gotcha covered

https://github.com/pagefaultgames/pokerogue/assets/13838608/b193bc29-f308-46e9-bf83-34a129a1df9c

2024-05-11 04:48 UTC, bennybroseph commented
@Flashfyre does the above work for Legacy Theme?

2024-05-13 03:38 UTC, Flashfyre approved these changes

2024-05-13 03:38 UTC, merged