Impl: Poison Heal
pagefaultgames/pokerogue pull request #727
Opened 2024-05-11 00:55 UTC by kd8lvt

I probably did this in a really weird way, but I got Poison Heal working.

I used [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Poison_Heal_(Ability)) as reference, and I'm glad I did, because I was today years old when I learned that Toxic's turn count still increases regardless of Poison Heal. Certainly a niche use of Gastro Acid, but sure, GameFreak.

In the future when Heal Block is implemented, Poison Heal's healing (though not immunity) will have to be negated by it, but until then, this works.

2024-05-11 01:02 UTC, happinyz commented on src/data/ability.ts
> +  private statusEffect2: StatusEffect;
`private statusEffects: StatusEffect[]` would be better here imo, just in case in the future we implement heal conditions for possible 1 or 3+ statuses.

2024-05-11 01:03 UTC, happinyz commented on src/data/ability.ts
> +    if (pokemon.status.effect === this.statusEffect || pokemon.status.effect === this.statusEffect2) {
`if (this.statusEffects.includes(pokemon.status.effect)` if we change this to take in a list of status effects instead.

2024-05-11 01:06 UTC, kd8lvt commented
Ah, yeah that's a much better implementation. No idea why I didn't think of that.

2024-05-11 01:08 UTC, kd8lvt commented on src/data/ability.ts
> +  private statusEffect2: StatusEffect;
1 was covered by `StatusEffect, null` but yeah, like I said that's a much better implementation

2024-05-11 02:06 UTC, happinyz commented on src/data/ability.ts
> +  constructor(healRatio: integer,statusEffects: StatusEffect[]) {
```suggestion
  constructor(healRatio: integer, statusEffects: StatusEffect[]) {
```

2024-05-11 02:06 UTC, happinyz commented on src/data/ability.ts
> +      cancelled.value = true;
What does setting this to true do?

2024-05-11 02:17 UTC, kd8lvt commented on src/data/ability.ts
> +      cancelled.value = true;
It prevents the status effect from triggering

2024-05-11 04:11 UTC, happinyz approved these changes
lgtm, we should get feedback from a contributor with write access first though

2024-05-12 07:33 UTC, bennybroseph requested changes
Needs TSDoc documentation on all new classes and functions and code comments where applicable.

Also, does this show any sort of animation for the heal?

2024-05-19 16:56 UTC, bennybroseph commented
Closing this due to inactivity. Feel free to make a new request if interest is reignited

2024-05-19 16:56 UTC, closed without merging