Bugfix - Ghost types are no longer trapped by abilities like Shadow Tag or moves like Fire Spin
pagefaultgames/pokerogue pull request #731
Opened 2024-05-11 02:56 UTC by td76099

Originally reported in Discord, Ghost type Pokemon were being trapped by Shadow Tag as well as moves like Fire Spin/Whirlpool/etc. despite documentation saying [trapping abilities](https://bulbapedia.bulbagarden.net/wiki/Ghost_(type)#Interacting_with_the_Ghost_type) shouldn't work and [trapping moves](https://bulbapedia.bulbagarden.net/wiki/Fire_Spin_(move)#Generation_VI_onwards) shouldn't work.

The function didn't even take in the Pokemon trying to switch/run in the first place, so it now gets passed in and checked to see if it's a Ghost type.

Here is a Ghost type swapping through Shadow Tag and a non-Ghost type getting stuck:

https://github.com/pagefaultgames/pokerogue/assets/85713900/d017534b-fd46-45f5-ae0c-d3d5ca22e414

Ghost type successfully swapping through Fire Spin and a non-Ghost type getting stuck:

https://github.com/pagefaultgames/pokerogue/assets/85713900/5897b8d0-a9af-4a85-9270-4e6d3de6794a

2024-05-11 04:11 UTC, kd8lvt requested changes

2024-05-11 04:11 UTC, kd8lvt commented on src/data/ability.ts
> +    if (otherPokemon[0].getTypes().indexOf(Type.GHOST) != -1){
Could be simplified as
```suggestion
    if (otherPokemon[0].getTypes().includes(Type.GHOST)){
```

2024-05-11 04:11 UTC, kd8lvt commented on src/data/ability.ts
> +    if (otherPokemon[0].getTypes().indexOf(Type.GHOST) != -1){
Also, how does this work with more than one Pokemon on the field? From a cursory glance it looks like you're only checking the first party member?

2024-05-11 14:14 UTC, td76099 commented on src/data/ability.ts
> +    if (otherPokemon[0].getTypes().indexOf(Type.GHOST) != -1){
> Could be simplified as

Agreed - made change

2024-05-11 14:37 UTC, td76099 commented on src/data/ability.ts
> +    if (otherPokemon[0].getTypes().indexOf(Type.GHOST) != -1){
> Also, how does this work with more than one Pokemon on the field? From a cursory glance it looks like you're only checking the left party member?

`otherPokemon`, while an array, ever only contains a single Pokemon. It's the Pokemon that is being targeted by a trapping move or the Pokemon that is trying to run/switch. That's not something I wanted to do; that is how it is in `phases.ts` and it's just passed on to `ability.ts`.

Here's it working on right side Pokemon too
https://github.com/pagefaultgames/pokerogue/assets/85713900/540e985b-6981-4da0-8edc-9b8f813bbb69

2024-05-19 04:39 UTC, td76099 commented on src/data/ability.ts
> +    if (otherPokemon[0].getTypes().indexOf(Type.GHOST) != -1){
Figured out why it was passing in as an array and it is now updated to not do that 👍

2024-05-19 17:04 UTC, bennybroseph approved these changes

2024-05-19 17:05 UTC, merged