Ability Corrosion
pagefaultgames/pokerogue pull request #744
Opened 2024-05-11 15:47 UTC by Brandon-Rodgers

Implemented Corrosion Partially.
Tested against:
- Poison Powder
- Toxic
- Dire Claw
- Sludge Bomb
- Psycho Shift

They all work as expected

Missing ability Magic Bounce to test against.

2024-05-12 07:29 UTC, bennybroseph requested changes
Needs TSDoc documentation on all new classes and functions and code comments where applicable.

2024-05-13 08:08 UTC, bennybroseph requested changes

2024-05-14 01:03 UTC, bennybroseph commented
So, it's doing what it is supposed to, but there's no indication of what's happening here. Corrosion can't go through an Immunity Pokemon but neither ability pops up to say that's why it's failing nor does it say "But it failed!" or similar. I will check showdown to see what the message is there, but you should so some research as well

https://github.com/pagefaultgames/pokerogue/assets/13838608/85c2dae4-214c-48a2-bcf1-21141ff21701

2024-05-14 02:30 UTC, bennybroseph approved these changes

2024-05-14 13:46 UTC, Brandon-Rodgers commented
https://github.com/pagefaultgames/pokerogue/assets/9848614/5693a796-8b78-440f-96b0-d3a00f21c41f

Toxic - Affects Steelix and triggers Corrosion pop-up
Poison Sting - Does not affect Steelix due to it being a damaging move

2024-05-14 18:00 UTC, merged