[DRAFT] Fixes some variable damage moves not working with abilities
pagefaultgames/pokerogue pull request #759
Opened 2024-05-12 00:28 UTC by mattrossdev

Some moves with variable power attributes don't get modified by variable power ability attributes. As an example magnitude and dragon energy don't get boosted by tinted lens. 

This happens because we are overwriting the base power for these moves after applying the ability attributes which seems like the wrong order. This PR changes the order and resolves those issues, but needs further discussion on if there are any ability/move interactions this would break.

2024-05-12 01:01 UTC, mattrossdev commented
Closing this for now, I think a better approach is that there should be a different class for tinted lens since it modifies the damage dealt and not the base power. Also need to check if there are other abilities this is true for. 
https://bulbapedia.bulbagarden.net/wiki/Power
https://bulbapedia.bulbagarden.net/wiki/Damage

2024-05-12 01:58 UTC, mattrossdev commented on src/data/ability.ts
> +      .attr(DamageBoostAbAttr, 2, (user, target, move) => target.getAttackTypeEffectiveness(move.type, user) <= 0.5),
I changed the order of the multiplier/condition to match StabBoostAbAttr

2024-05-12 02:00 UTC, mattrossdev commented
Updated now. I checked and tinted lens and flash fire appear to be the only abilities that modify the damage of an attack rather than the base power, and flash fire has a battlertag so doesn't need to be  added here.

2024-05-12 06:22 UTC, bennybroseph requested changes

2024-05-12 06:22 UTC, bennybroseph commented on src/field/pokemon.ts
> +            applyPreAttackAbAttrs(DamageBoostAbAttr, source, this, battlerMove, damage)
missing a semi-colon here

2024-05-12 07:04 UTC, bennybroseph commented
Functionality looks good for this. 

https://github.com/pagefaultgames/pokerogue/assets/13838608/5e634691-7bc1-4664-a849-8cbf9e37264b

Magnitude

https://github.com/pagefaultgames/pokerogue/assets/13838608/615d2ac0-2013-4430-ae27-44a46489ff67

2024-05-13 11:40 UTC, bennybroseph approved these changes

2024-05-13 18:05 UTC, merged