Added Portuguese (Brazil) translations
pagefaultgames/pokerogue pull request #766
Opened 2024-05-12 07:48 UTC by josericardo-fo

Every translation was made with interpretation and adaptation, as there is not an official source of portuguese Pokémon material. Me and @Hareon, owner of [Elite dos Quatro Traduções](https://e4t.com.br/), used translations from Pokémon Unite, Anime, TCG, Pokémon GO.

- Moves and abilities not translated?
A small poll was made with the brazillian community and we chose to not translate the names of moves and abilities. The original games never had an official portugues translation, so many portuguese fans grew up playing those games in English and got used to it. If needed, we have the translations of every name of moves and abilities to follow the pattern of other languages.

2024-05-12 19:51 UTC, CodeTappert requested changes

2024-05-12 19:51 UTC, CodeTappert commented on src/system/settings.ts
> +                label: 'Português',
Maybe change this to include the "Brazil" Part since there is also european portugese. (Otherwise there will be confusion later)

2024-05-12 20:08 UTC, josericardo-fo commented on src/system/settings.ts
> +                label: 'Português',
Fixed

2024-05-13 16:18 UTC, Madmadness65 approved these changes

2024-05-13 16:18 UTC, merged