Prevent applying item boosts when power is <1
pagefaultgames/pokerogue pull request #795
Opened 2024-05-12 18:56 UTC by LaukkaE

This PR prevents item boosts from being applied, if base power is less than 1. (For example, when you hit a disguise with multi-lens).
Because the value is Math.floored, applying the boost will cause the move to do no damage at all.

This is Disguise not breaking against Magnet + Multi-Lens Thunderbolt before the fix

https://github.com/pagefaultgames/pokerogue/assets/73663099/986e12d7-2cfe-4f7e-bd1a-ef71b2e8d5c2

The Disguise not breaking bug does not happen with Multi-Lens and no Magnet before the fix

https://github.com/pagefaultgames/pokerogue/assets/73663099/38b63bb9-048e-473b-b339-2794fba9df05

The Disguise breaks properly with Magnets equipped after the fix

https://github.com/pagefaultgames/pokerogue/assets/73663099/9fcdd8cc-85bc-4723-9525-af491a61b0b2

2024-05-12 19:39 UTC, TempsRay approved these changes

2024-05-13 08:50 UTC, bennybroseph requested changes

2024-05-13 08:50 UTC, bennybroseph commented on src/modifier/modifier.ts
> +    if (args[1] === this.moveType && (args[2] as Utils.NumberHolder).value >= 1) {
please add a comment stating what args[0], [1], and [2] are in this context

2024-05-13 23:48 UTC, bennybroseph commented
Pairs nicely with https://github.com/pagefaultgames/pokerogue/pull/781

2024-05-13 23:48 UTC, bennybroseph approved these changes

2024-05-13 23:48 UTC, merged