Fixed clear freeze in offline mode
pagefaultgames/pokerogue pull request #799
Opened 2024-05-12 19:45 UTC by Nexllon

Currently when in offline mode, api "savedata/newclear" gets called to check dailyRun seed every handleGameOver().
Added a simple isLocal check to prevent that since it was causing freezes when playing classic offline.

2024-05-12 19:49 UTC, Admiral-Billy commented
Oh cool, you did that for me! I'll note that this does fix the problem but I think this also lets you redo dailies to get the same reward multiple times.

Of course, if you're playing in offline mode you can already do far crazier shenanigans if you want to cheese the system, and the daily run isn't even a consideration unless some other code is changed to add it to offline, but it's worth noting regardless.

2024-05-12 21:56 UTC, scw6538 approved these changes
LGTM

2024-05-13 08:43 UTC, bennybroseph requested changes
```ts
export const isLocal = window.location.hostname === 'localhost' || window.location.hostname === '';
```
How easy is this to spoof to be false

2024-05-13 11:27 UTC, Nexllon commented
> ```ts
> export const isLocal = window.location.hostname === 'localhost' || window.location.hostname === '';
> ```
> 
> How easy is this to spoof to be false

As easy as anything else in the game client (pretty)

2024-05-13 20:57 UTC, Nexllon commented
@Flashfyre since the issue with this PR is correlated to [#808](https://github.com/pagefaultgames/pokerogue/pull/808) that is not yet implemented (and will be fixed). Could we push this and fix in the other issue?
Or just close this one and I'll merge everything in the other one too.

2024-05-13 21:10 UTC, closed without merging