Implement type immunity removal moves
pagefaultgames/pokerogue pull request #812
Opened 2024-05-13 07:24 UTC by JakubHanko

The scope of this draft PR is to at least partially implement the following moves:

1. Odor Sleuth
2. Miracle Eye
3. Foresight

The goal is to make the evasiveness reset and type removal work.

Right now, Odor Sleuth works. The rest of the moves will follow in the near future. What is left to do is to clean up the code, mainly the functionality around battle tags (parameters, lapse function).

2024-05-16 18:35 UTC, DustinLin commented on src/data/move.ts
> +  }
lol

2024-05-16 18:35 UTC, DustinLin commented on src/data/move.ts
> +import { BattlerTag, EncoreTag, TypeImmunityIgnoreTag } from "./battler-tags";
do we need to import `BattlerTag` here?

2024-05-16 19:37 UTC, DustinLin commented
Included a demo for odor sleuth, checking to make sure everything works, it would be great if the author does something similar for the rest that they implemented

---


https://github.com/pagefaultgames/pokerogue/assets/39450497/2ecfe207-de48-45ff-9c60-5778effc758b

2024-05-16 20:23 UTC, JakubHanko commented
@DustinLin Thanks for the demo and the review. I cleaned up the nits.

About the recording - I might do in during the weekend. The other moves follow the exactly same logic as Odor Sleuth though. If one works, all should.

2024-05-18 06:51 UTC, JakubHanko commented
Adding videos for the other two moves.

https://github.com/pagefaultgames/pokerogue/assets/60473007/d99d7b27-45bc-4037-a1a4-2c70bbcacfa1


https://github.com/pagefaultgames/pokerogue/assets/60473007/e64fc237-56b1-48bf-b6b2-7d3508a80cf1

2024-05-19 18:15 UTC, bennybroseph requested changes
Looks like there are conflicts on this currently

Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

2024-05-19 18:59 UTC, JakubHanko commented
> Looks like there are conflicts on this currently
> 
> Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

Added the docs, is it better now?

2024-05-19 19:39 UTC, bennybroseph requested changes

2024-05-19 19:39 UTC, bennybroseph commented on src/data/battler-tags.ts
> +export class IgnoreTypeImmunityTag extends BattlerTag {
this class still needs to adhere to the guidelines

2024-05-19 20:44 UTC, JakubHanko commented on src/data/battler-tags.ts
> +export class IgnoreTypeImmunityTag extends BattlerTag {
Cleaned up the class and hopefully made it respect the guidelines.

2024-05-23 07:34 UTC, bennybroseph requested changes

2024-05-23 07:34 UTC, bennybroseph commented on src/data/move.ts
> +    target.updateInfo();
This is modifying the target's stats which is not what this move does

2024-05-23 07:53 UTC, JakubHanko commented on src/data/move.ts
> +    target.updateInfo();
Oh I see, it doesn't reset the evasiveness just once, does it? The evasiveness is completely ignored after this move is used.

2024-05-23 08:18 UTC, JakubHanko commented on src/data/move.ts
> +    target.updateInfo();
Will change it later today.

2024-05-24 15:06 UTC, JakubHanko commented on src/data/move.ts
> +    target.updateInfo();
Reworked it to completely ignore the target's evasiveness.

2024-05-26 08:29 UTC, bennybroseph commented
Can we get a video of the same scenarios from the original comment to show that evasion no longer gets reset?

2024-05-26 14:52 UTC, JakubHanko commented
https://github.com/pagefaultgames/pokerogue/assets/60473007/27895635-c127-4b5c-a3a1-c6ad81c128a1

Here is video of Odor Sleuth. Are the other two videos necessary? They all follow the same logic. Either all work or none.

2024-06-05 19:43 UTC, FogMP commented
For the most part, these moves are working correctly, evasion and types are being ignored.

But going over some edge cases, mainly Wonder Guard and Mind's Eye (basically same functionality as Odor/Foresight):

Mind's eye allows hitting through Wonder Guard with a fighting type move:

https://github.com/pagefaultgames/pokerogue/assets/171270136/87187c27-0048-4280-99de-a8903c898393

However, after using foresight i can't hit it anymore:

https://github.com/pagefaultgames/pokerogue/assets/171270136/480cf340-bce5-4006-abd2-d26e02e13e4b

And just in case here's Wonder Guard vs just Foresight:

https://github.com/pagefaultgames/pokerogue/assets/171270136/8ada1340-548e-4f2e-88a5-b4ffe8b9c496

Unsure how this interaction is supposed to go, but in theory both Mind's Eye and Foresight should have the same result vs wonder guard. And why it makes Mind's Eye stop working.

2024-06-08 11:17 UTC, JakubHanko commented
Will look into the interaction with Wonder Guard soon-ish.

2024-06-08 15:27 UTC, JakubHanko commented
https://github.com/pagefaultgames/pokerogue/assets/60473007/d9bf1c23-e01a-490d-a607-24123c9abd5f

Fixed the interaction. I thought I was being smart with the way I initially implemented it.

2024-06-27 23:19 UTC, brain-frog commented
I'm sorry this was left un-reviewed for 3 weeks, if you update the merge conflicts ping me in discord and I can review it

2024-07-05 04:02 UTC, DayKev commented
Imo there should be some unit tests as well.

2024-07-29 17:38 UTC, flx-sta commented
make sure to address the conflicts and the comments

2024-08-07 15:02 UTC, closed without merging

2024-08-07 16:11 UTC, flx-sta commented
Closed in favor of #3379