Implement Trump Card move
pagefaultgames/pokerogue pull request #816
Opened 2024-05-13 16:01 UTC by hayuna

2024-05-13 16:08 UTC, TempsRay commented on src/data/move.ts
> +  apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
Add TSdoc for new classes/apply's

2024-05-13 16:09 UTC, TempsRay commented on src/data/move.ts
> +    switch (ppRemains) {
nit: feels a bit weird going from case 3->0 instead of case 0->3 since the numbers should all be ascending or descending

2024-05-13 16:10 UTC, TempsRay reviewed
Code looks mostly good to me. Did you test and verify it works like it's supposed to?

2024-05-13 20:12 UTC, TempsRay commented on src/data/move.ts
> +    const ppUsed = user.moveset.find((m) => m.moveId === move.id).ppUsed;
If you are 5/5 pp and use trump card against a pressure opponent the pp will drop to 3 before calculating bp (50bp)

2024-05-14 14:43 UTC, TempsRay requested changes
Can you just do a quick test to verify how this works with and without pressure? You can get some pretty simple screenshots by opening the console (F12) and showing examples since you can log the base power (which is different from damage) of the moves you use.

2024-05-14 14:43 UTC, TempsRay commented on src/data/move.ts
> +    }
Just straight up adding 1 will result in an edge case if the move is at 1/5 right?

2024-05-14 15:29 UTC, hayuna commented on src/data/move.ts
> +    }
If we use this twice, we will have 1PP, then to avoid negative numbers, I reduced PP to 0

2024-05-14 15:51 UTC, hayuna commented
Added description with screenshots of using this move with and without pressure

2024-05-14 17:11 UTC, TempsRay approved these changes

2024-05-16 12:31 UTC, bennybroseph commented
would like the comments updated to match [this write-up](https://discord.com/channels/1125469663833370665/1239957703820836975)

2024-05-16 14:45 UTC, hayuna commented
@bennybroseph Done

2024-05-19 18:16 UTC, bennybroseph approved these changes

2024-05-19 18:17 UTC, merged