added auto hit and 2x damage from certain moves when targeting a pokemon that used minimize
pagefaultgames/pokerogue pull request #824
Opened 2024-05-13 19:41 UTC by andrew-wilcox

Referenced the Gen 9 column of this image (from bulbapedia)

![image](https://github.com/pagefaultgames/pokerogue/assets/3037156/74a5ed34-e215-45d9-9a24-a22ac3176e42)

Any checked boxes in the gen 9 column those moves will A) Auto hit any pokemon that has used minimize and B) deal double damage with those moves.

2024-05-13 19:43 UTC, Flashfyre submitted a review, later dismissed

2024-05-13 19:43 UTC, Flashfyre commented on src/data/move.ts
> +    console.log("---------")
Remove console logs

2024-05-13 19:43 UTC, Flashfyre commented on src/data/move.ts
> -/**
Why was this removed? A bad merge?

2024-05-13 19:47 UTC, TempsRay commented on src/data/battler-tags.ts
> +export class MinimizeTag extends BattlerTag {
Should probably have some check for gmax since in vanilla gmaxing will remove the minimized tag. Here I think can just make it so that gmax pokemon don't get this tag

2024-05-13 19:48 UTC, TempsRay commented on src/data/move.ts
> +export class MinimizeAccuracyAttr extends VariableAccuracyAttr{
TSDocs for new classes

2024-05-13 19:48 UTC, TempsRay commented on src/data/move.ts
> +export class MinimzeDamageAttr extends VariablePowerAttr {
I believe it's damage doubling, not power doubling. Also tsdocs

2024-05-13 19:48 UTC, andrew-wilcox commented on src/data/move.ts
> +    console.log("---------")
Ah, thanks.

2024-05-13 19:49 UTC, TempsRay commented on src/data/move.ts
> -        .attr(BypassBurnDamageReductionAttr),
This seems to remove the facade change. Rebase?

2024-05-13 19:50 UTC, TempsRay requested changes
* Need tsdocs
* Fix merge conflict with facade
* Address comments for functionality

2024-05-13 19:51 UTC, andrew-wilcox commented on src/data/move.ts
> -        .attr(BypassBurnDamageReductionAttr),
Yeah this stuff must be a weird merge, let me go remerge from main and see if they go away.

2024-05-13 20:49 UTC, andrew-wilcox commented
All issues resolved.

2024-05-14 02:11 UTC, bennybroseph approved these changes

2024-05-15 12:36 UTC, merged