Update Item Check
pagefaultgames/pokerogue pull request #826
Opened 2024-05-13 21:21 UTC by Brandon-Rodgers

Updated item check for when applying item to a Pokemon

Used similar code to when generating map for After Battle items list. Gets all item triggers for the Pokemon, then maps it and flattens it down to just a list of items the pokemon can use to change form. Then finally it checks if the current item exists in the list.

This is meant to be a fix for Shaymin, and any other pokemon that had issues with Time of day blocking items being given. 

In general this should allow any item to be given to your Pokemon whether they can evolve yet or not. As long as it shows in the shop, it can be given to the proper Pokemon

https://github.com/pagefaultgames/pokerogue/assets/9848614/b1d78204-6a1d-45dc-872f-6303b82e697b

2024-05-14 01:21 UTC, bennybroseph commented
> In general this should allow any item to be given to your Pokemon whether they can evolve yet or not. As long as it shows in the shop, it can be given to the proper Pokemon

That doesn't sound like the solution we're looking for. The shop should only show items that are valid and when applying an item, it should only do so if it is also valid. What happens when I have a Pichu and a Pikachu? Can I give Pichu a Max Mushroom?

2024-05-16 15:35 UTC, Brandon-Rodgers commented
This should work like Rayquaza, where you can give the megastone even when Dragon Ascent is not learned. But it cannot be given to other Pokemon if they cannot use it. 
It uses the same check logic as the shop where a Thunderstone only shows up if a Pokemon can use it to evolve. 
So if you try to apply it to Pichu it will check if Pichu has SpeciesFormEvolution attribute with the EvolutionItem.THUNDER_STONE. Since Pichu does not have that attribute with that item, then it will say it will not affect Pichu

2024-05-16 16:40 UTC, Brandon-Rodgers commented
https://github.com/pagefaultgames/pokerogue/assets/9848614/80141eb2-178d-4f87-bb89-9e33da5a708d

Video of it not affecting Pichu and only Pikachu

2024-05-19 18:20 UTC, bennybroseph requested changes

2024-05-19 18:20 UTC, bennybroseph commented on src/modifier/modifier-type.ts
> +          .flat().flatMap(fc => fc.item).includes(this.formChangeItem))
Could we get some basic comments to explain some of these checks and the surrounding code?

2024-05-25 12:16 UTC, closed without merging

2024-05-25 12:16 UTC, bennybroseph commented
Closing due to inactivity