Partially implemented mimicry.
pagefaultgames/pokerogue pull request #840
Opened 2024-05-14 01:35 UTC by Electrolyzer

Edge cases where other effects also change type may exhibit some unintended behavior (soak, forest's curse).

Streamlined on summon weather/terrain effects by adding an onTerrainChange and onWeatherChange call when switching in and removing the relevant onSummonEffect so that when coding an ability that activates on specific terrain or weather, you only need to implement the onTerrainChange or onWeatherChange attribute. Added a getWeather() function to arena.ts to simplify it (identical to the preceding getTerrain() function).

2024-05-19 18:24 UTC, bennybroseph requested changes

2024-05-19 18:24 UTC, bennybroseph commented on src/data/ability.ts
> +    return true;
Could we get some comments explaining this function?

2024-05-21 03:05 UTC, Electrolyzer commented on src/data/ability.ts
> +    return true;
Added comments. Let me know if there is anything else or something in particular I should explain more. Thank you!

2024-05-21 03:06 UTC, Electrolyzer commented on src/data/ability.ts
> +    return true;
(If the question was about terrainToTypeMap that was already explained above in the comment on the constructor)

2024-07-29 17:37 UTC, flx-sta commented
No action within more than a month. 
Considered stale.

Feel free to re-open it when you are still working on it/want to work on it again

2024-07-29 17:37 UTC, closed without merging