Do not trigger focus band effect on status damage
pagefaultgames/pokerogue pull request #850
Opened 2024-05-14 03:36 UTC by GriffinDZ

2024-05-14 03:38 UTC, GriffinDZ commented
https://trello.com/c/NmVfN8xy/22-focus-band-keeping-pokemon-alive-through-status-damage

Files used for reproduction / testing the fix attached


[overridests.txt](https://github.com/pagefaultgames/pokerogue/files/15302238/overridests.txt)

(Just modifies the focus band to always trigger)
[modifierts.txt](https://github.com/pagefaultgames/pokerogue/files/15302239/modifierts.txt)

2024-05-14 03:39 UTC, GriffinDZ commented
Not sure if there's an optimal way to handle the parameters here, was hoping to be able to only pass two with a named param, but looks like TypeScript only does that through object passing

2024-05-14 21:17 UTC, knispeja commented on src/field/pokemon.ts
> +  damage(damage: integer, ignoreSegments: boolean = false, preventEndure: boolean = false, statusDamage: boolean = false): integer {
Instead of creating a new param, can't you just reuse `preventEndure`? It appears to me that Endure/Sturdy are also incorrectly triggering on status damage, if I'm reading this correctly

2024-05-14 23:15 UTC, GriffinDZ commented on src/field/pokemon.ts
> +  damage(damage: integer, ignoreSegments: boolean = false, preventEndure: boolean = false, statusDamage: boolean = false): integer {
Let me check to see if they also are triggering incorrectly, I separated them because I figured there isn't a scenario where you could be taken from 100% to 0% with status damage, but now that I think about it maybe you could with healing + high toxic stacks

2024-05-14 23:40 UTC, GriffinDZ commented on src/field/pokemon.ts
> +  damage(damage: integer, ignoreSegments: boolean = false, preventEndure: boolean = false, statusDamage: boolean = false): integer {
It looks like Endure/Sturdy work correctly because of something in the `lapseTag` logic (tested with a shedinja w/ sturdy set to one health manually, and it dies after being toxic'd), but I think we can reuse `preventEndure` here safely actually

2024-05-19 18:27 UTC, bennybroseph requested changes
Looks like this has conflicts at the moment.

Also, can we get a video of this being tested?

2024-07-29 17:33 UTC, flx-sta commented
No action within more than a month. 
Considered stale

2024-07-29 17:33 UTC, closed without merging