Add unthaw logic to Steam Eruption, Scorching Sands, Matcha Gotcha and all Damaging Fire moves
pagefaultgames/pokerogue pull request #940
Opened 2024-05-16 03:32 UTC by OrangeRed

Quotes from the [Freeze bulbapedia entry](https://bulbapedia.bulbagarden.net/wiki/Freeze_(status_condition))
> Starting in Generation VI, if a frozen Pokémon is successfully hit by Scald, Steam Eruption, Scorching Sands, or Matcha Gotcha, it will be immediately thawed.
>
> All damaging Fire-type moves can now thaw a frozen target, regardless of whether or not they have a chance to burn;

- Add thaw target `HealStatusEffectAttr` for Steam Eruption, Scorching Sands, or Matcha Gotcha since they were missing it
- Add comments to the `HealStatusEffectAttr` Class
- Add thaw target `HealStatusEffectAttr` to every attacking fire move inside of the `AttackMove` Class

* Also added `STATUS_OVERRIDE` and `OPP_STATUS_OVERRIDE` to make testing stuff like this easier

2024-05-18 01:25 UTC, td76099 commented
Tested out locally - can confirm it works

LGTM

2024-05-18 03:29 UTC, IceFire03 approved these changes

2024-05-19 18:53 UTC, bennybroseph requested changes
Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975). Current comments look a little messy

2024-05-20 04:58 UTC, OrangeRed commented
> Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975). Current comments look a little messy

@bennybroseph I don't quite understand, what changes are you looking for specifically? I only added comments in two places the if statement on `src/data/move.ts:386` and the class on `src/data/move.ts:1438`. Which of them would you like changed?

2024-05-20 07:25 UTC, bennybroseph requested changes

2024-05-20 07:25 UTC, bennybroseph commented on src/data/move.ts
>  export class HealStatusEffectAttr extends MoveEffectAttr {
This class

2024-05-20 07:25 UTC, bennybroseph commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
Why does hp need to be above 0 to heal a freeze?

2024-05-20 11:57 UTC, OrangeRed commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
A pokemon that is going to faint from an attack doesn't need to be unthawed. Not having that check would trigger the unthaw logic / display the message and then the pokemon would immediately faint (and have its status changed to that).

2024-05-20 12:06 UTC, OrangeRed commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
This also applies not to just freeze of course. A pokemon that is poisoned or burned doesn't need to display that it's been cured when the thing that happens immediately after is it fainting since fainting changes the pokemon's statusEffect.

2024-05-20 12:08 UTC, bennybroseph commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
I'm not aware of any off hand, but what about abilities or effects that require the user to not be frozen in order to activate? I feel like the thaw should be happening upon getting hit by the move, not taking damage.

2024-05-20 12:10 UTC, bennybroseph commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
Ah, yeah how does this handle if the pokemon should get burned by the fire move? It can't do so if the pokemon is still considered frozen

2024-05-20 13:05 UTC, OrangeRed commented on src/data/move.ts
>  export class HealStatusEffectAttr extends MoveEffectAttr {
I still don't know exactly what you're looking for but here is a draft of the comments I am considering pushing. Let me know if there is still something I need to change.
```ts
/**
 * Move attribute that signals that that move should cure a status effect
 * @extends MoveEffectAttr
 * @see {@linkcode apply()}
 */
export class HealStatusEffectAttr extends MoveEffectAttr {
  /** Array of Status Effects to cure */
  private effects: StatusEffect[];
  
  /**
   * @param selfTarget - Whether this move targets the user
   * @param ...effects - Array of status effects to cure
   */
  constructor(selfTarget: boolean, ...effects: StatusEffect[]) {
    super(selfTarget);

    this.effects = effects;
  }
// ...
}
```

Also on a related note, should we be adding comments to every single `Class.apply()` inside of child classes? I feel like it would be a lot better doing it once for a given parent and then letting the comments propagate via inheritance.

2024-05-20 13:55 UTC, bennybroseph commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
Understood. My question rolls back to the original one. Why would a pokemon need to be at above 0 HP in order to be defrosted? I don't think this should be included based on the info provided.

2024-05-20 14:09 UTC, OrangeRed commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
Again because in either scenario (whether the status is cured and then the pokemon faints or the status is not cured and the pokemon faints) the end result will be the same the pokemon's status will change to `FAINTED`.

So its just a matter of cutting out an unnecessary step in that in the first scenario the pokemon will go from status -> no status -> fainted, whereas in the second the pokemon will go straight from status -> fainted

2024-05-20 14:11 UTC, bennybroseph commented on src/data/move.ts
>  export class HealStatusEffectAttr extends MoveEffectAttr {
Please take a look at the linked information [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975). There are also examples within the code itself that I have already documented if you need.

2024-05-20 14:25 UTC, XGSleepWalker commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
> So its just a matter of cutting out an unnecessary step in that in the first scenario the pokemon will go from status -> no status -> fainted, whereas in the second the pokemon will go straight from status -> fainted

I don't agree with this part. For now it may be okay to make the jump assuming the pokemon will be fainted anyways, but we may cause issues down the line with new interactions (who knows what comes from Z-A). I am in support of reverting the hp check and applying the effect regardless.

2024-05-20 14:27 UTC, bennybroseph commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
Agreed, let's leave each step intact. The move thaws the pokemon, so it should do so even if it just faints afterwards.

2024-05-20 17:42 UTC, OrangeRed commented on src/data/move.ts
>  export class HealStatusEffectAttr extends MoveEffectAttr {
Is there something in the code block above that isn't what you're looking for? From my point of view it conforms to what is written in the FAQ. 

Also I believe writing JSDoc on the constructor is a nicety because when creating a new class the intellisense will show you the comments as you're writing the variable.

2024-05-25 21:06 UTC, OrangeRed commented on src/data/move.ts
> +    if (pokemon.hp > 0 && pokemon.status && this.effects.includes(pokemon.status.effect)) {
I removed the `pokemon.hp > 0` check so the effect will trigger before a pokemon faints

2024-05-28 17:08 UTC, OrangeRed commented
@bennybroseph I added comments to the `HealStatusEffectAttr` class that are hopefully easy enough to understand.

2024-05-29 22:03 UTC, bennybroseph requested changes

2024-05-29 22:03 UTC, bennybroseph commented on src/overrides.ts
need to remove this commit

2024-05-30 02:25 UTC, OrangeRed commented on src/overrides.ts
Which commit? The one that adds status overrides? Isn't that a useful addition for testing moves / abilities that interact with statuses?

2024-05-30 13:04 UTC, bennybroseph commented on src/overrides.ts
if we're adding new overrides that should be in a separate PR. it's completely unrelated to this

2024-05-30 15:54 UTC, OrangeRed commented on src/overrides.ts
Sure that makes sense. I removed the status overrides from this PR and I'll make a new PR with them included.

2024-05-30 16:22 UTC, OrangeRed commented on src/overrides.ts
> if we're adding new overrides that should be in a separate PR. it's completely unrelated to this

I made a separate PR for this. https://github.com/pagefaultgames/pokerogue/pull/1602

2024-05-30 20:04 UTC, bennybroseph approved these changes

2024-05-30 20:04 UTC, merged